### ISSUE TITLE
Test and Document Minimum Recommended K8s Versions

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#10011]
We need to update our guidance on supported versions of Kubernetes in our [CRDB/K8s Orchestration docs.](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html)

At the moment, [our docs](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#kubernetes-version) require users to use Kubernetes v1.15 or higher.

However, some customers are facing challenges with K8s v1.17 and later.

@lin-crl  is in the process of testing multi-cluster secure deployment on EKS 1.17. 

Overall, let's check in our Kubernetes supported version(s) across supported deployment patterns.

**Comment by taroface** [comment]
cc @keith-mcclellan, in case you have any immediate thoughts on a minimum recommended K8s version.
