### ISSUE TITLE
Known limitation: Document the p99 service latency graph spikes on individual nodes due to backups

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#10012]
https://cockroachdb.zendesk.com/agent/tickets/7910
https://cockroachdb.zendesk.com/agent/tickets/7849
https://cockroachlabs.atlassian.net/browse/CC-3830

https://github.com/cockroachdb/cockroach/issues/42174

can we document this as a known issue in CC? or at least under backups in FAQ https://www.cockroachlabs.com/docs/cockroachcloud/frequently-asked-questions.html

cc: @dbist

**Comment by jseldess** [comment]
Eng issue: https://github.com/cockroachdb/cockroach/issues/42174

**Comment by jseldess** [comment]
We should add this to our overall known limitations page, but we need to look at the eng issue to get the framing right. See Ben's comment in there. It's about more than bulk io, though backups probably do need to be called out. @lnhsingh, I defer to you on whether you want to route this to bulk io or observability. In any case, we generally document all newly identified limitations a little closer to GA; it's part of our GA checklist: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/402718726/GA+Release+Checklist

**Comment by chriscasano** [comment]
We find prospects and customers comparing apples and oranges with this metric that don’t favor Cockroach sometimes.  We should unpack in our docs what’s included in the metric as it includes backup and GC activity which can show huge spikes here.  With a customer evaluation a few weeks ago, they were comparing this metric to their select, insert, delete and update p99 statements only from Postgres and we obviously didn’t look good until we up leveled it to the metrics produced at their app layer for comparison.  My real worry is on the prospects we’re not talking too.   We also had to remind them they’re paying a small latency up front for better HA/resilience which was another key reminder of why they were looking at Cockroach in the first place.

**Comment by lnhsingh** [comment]
I think I'm going to kick this issue over to Observability (@taroface). Will update the [Jira ticket](https://cockroachlabs.atlassian.net/browse/CC-3830) too

**Comment by ericharmeling** [comment]
The root issue here is resolved in https://github.com/cockroachdb/cockroach/commit/559f20545e3c7a9ebaead4e873c3f03f868de118. I believe we can close this docs issue.
