### ISSUE TITLE
windows builds are for experimental use only

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#10023]
Windows builds are for experimental testing purposes only. This used to be easily discoverable in the docs but now is only [listed in the 1.0 path](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-windows.html). It also doesn't return via search:
<img width="1676" alt="Screen Shot 2021-03-22 at 9 23 06 AM" src="https://user-images.githubusercontent.com/22278911/111996339-4cc9a680-8af0-11eb-915f-9791dc2758b3.png">

We should add this disclaimer back in a discoverable way.

**Comment by jseldess** [comment]
@awoods187, can you clarify what you mean here? All versions of the Windows install page have a red warning about this, for example, https://www.cockroachlabs.com/docs/v21.1/install-cockroachdb-windows#download-the-executable. But I think you're saying something about the search results that I don't understand.

**Comment by awoods187** [comment]
Ah good point. I was talking about not finding it here: https://www.cockroachlabs.com/docs/releases/v20.2.6.html (which where I started looking releases->production releases).

I think in the search for "windows," I missed that the first link had the information. I think because it lacked the bold text that the links below carried. Those links don't have that windows warning. 

I'd suggest the following: 
Add the warning into production releases 
Add a bold windows tag to the first link https://www.cockroachlabs.com/docs/v21.1/install-cockroachdb-windows#download-the-executable

**Comment by jseldess** [comment]
Opened a separate issue to bold search terms in search results: https://github.com/cockroachdb/docs/issues/10153
