### ISSUE TITLE
protectedts: raise max_spans limit to 32768

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10048]
PR: https://github.com/cockroachdb/cockroach/pull/61018

From release notes:
> Raised the default limit on the maximum number of spans that can be protected by the `protectedts` subsystem. This limit can be configured using the `kv.protectedts.max_spans` [cluster setting](../v21.1/cluster-settings.html). [#61018][#61018] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we need to document this...

@rmloveland It seems storage-y - so I defer to you. Closing for now.

**Comment by rmloveland** [comment]
Eric Harmeling ***@***.***> writes:

> I don't think we need to document this...
>
> @rmloveland It seems storage-y - so I defer to you. Closing for now.

Agreed - it is not a public cluster setting in v21.1 (at least the build
I'm currently running).
