### ISSUE TITLE
streamingccl: add minimum flush interval cluster setting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10049]
PR: https://github.com/cockroachdb/cockroach/pull/60160

From release notes:
> Added the `bulkio.stream_ingestion.minimum_flush_interval` [cluster setting](../v21.1/cluster-settings.html), which allows the user to control how often the stream ingestion job will flush. Note that the job may still flush more often if the in-memory buffers are filled. [#60160][#60160] {% comment %}doc{% endcomment %}

**Comment by gemma-shay** [comment]
Closing after discussing with @pbardea as this setting is already doc'd in the generated table here: https://www.cockroachlabs.com/docs/dev/cluster-settings.html#settings and controls a feature that isn't public yet.
