### ISSUE TITLE
tracing: use manual collection in ForkCtxSpan

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10047]
PR: https://github.com/cockroachdb/cockroach/pull/59815

From release notes:
> [`SHOW TRACE FOR SESSION`](../v21.1/show-trace.html) previously included CockroachDB internal traces for async threads kicked off as part of user operations. This trace data is no longer captured. [#59815][#59815] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Hmm... I don't think this affects any of our docs. But I've opened a PR that updates the example output on the `SHOW TRACE` page.
