### ISSUE TITLE
cloud: upgrade AWS and Azure SDKs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10046]
PR: https://github.com/cockroachdb/cockroach/pull/59709

From release notes:
> Updated the AWS SDK used to interface with AWS services such as S3 (for backup, restore, and import) and KMS (for backup/restore). [#59709][#59709] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - I don't think docs are needed here.
