### ISSUE TITLE
kvserver: remove `kv.atomic_replication_changes.enabled` setting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10044]
PR: https://github.com/cockroachdb/cockroach/pull/61170

From release notes:
> Removed the `kv.atomic_replication_changes.enabled` [cluster setting](../v21.1/cluster-settings.html). All replication changes on a range now use joint-consensus. [#61170][#61170] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This setting does not appear anywhere in the v21.1 docs (most especially the [cluster settings page](https://www.cockroachlabs.com/docs/v21.1/cluster-settings.html), but I also grepped the repo and did not find anywhere in v21.1 things)
