### ISSUE TITLE
multiregionccl: gate multi-region database configuration behind a license

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10051]
PR: https://github.com/cockroachdb/cockroach/pull/61041

From release notes:
> [Multi-region database](../v21.1/multi-region-database.html) creations are now permitted as long as the cluster has a CockroachDB subscription. [#61041][#61041] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Handled in #10560 and #10052
