### ISSUE TITLE
changefeedccl: support primary key changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10050]
PR: https://github.com/cockroachdb/cockroach/pull/58422

From release notes:
> CockroachDB now supports [primary key](../v21.1/primary-key.html) changes in [`CREATE CHANGEFEED`](../v21.1/create-changefeed.html). [#58422][#58422] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I think the only edit that needs to be made here is under https://www.cockroachlabs.com/docs/v21.1/stream-data-out-of-cockroachdb-using-changefeeds#known-limitations
