### ISSUE TITLE
util/tracing, sql: expose span's goroutine IDs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10058]
PR: https://github.com/cockroachdb/cockroach/pull/59717

From release notes:
> Added the `goroutine_id` column to the `crdb_internal.node_inflight_trace_spans` virtual table that represents the goroutine ID associated with a particular span. [#59717][#59717] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8909.
