### ISSUE TITLE
changefeedccl: Add WITH avro_schema_prefix option to changefeeds in avro format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10054]
PR: https://github.com/cockroachdb/cockroach/pull/59710

From release notes:
> Added `WITH avro_schema_prefix` option to Avro [changefeeds](../v21.1/create-changefeed.html) to prevent collisions in a shared schema registry [#59710][#59710] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Related to #9450

**Comment by HonoreDB** [comment]
I've written up an internal guide to our name generation logic, configuration, and rationale [here](https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/1636958818/Sink+Names+A+u0022+Simple+u0022+Guide). Hope it's helpful in creating the public docs.
