### ISSUE TITLE
util/tracing, sql: surface finished bool in span recordings

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10065]
PR: https://github.com/cockroachdb/cockroach/pull/59856

From release notes:
> Added the `finished` column to the virtual table `crdb_internal.node_inflight_trace_spans`, which represents whether each span has finished or not. [#59856][#59856] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8909.
