### ISSUE TITLE
sql: mark implicit crdb_region column as HIDDEN

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10068]
PR: https://github.com/cockroachdb/cockroach/pull/59831

From release notes:
> `REGIONAL BY ROW` tables that have an implicitly created `crdb_region` table will now mark the given column as hidden so it does not display in `SELECT *` statements. [#59831][#59831] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
We have docs that say this column is hidden in the [`SET LOCALITY REGIONAL BY ROW`](https://www.cockroachlabs.com/docs/v21.1/set-locality.html#set-the-table-locality-to-regional-by-row) example
