### ISSUE TITLE
sql: implement GLOBAL/REGIONAL BY TABLE -> REGIONAL BY ROW change

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10063]
PR: https://github.com/cockroachdb/cockroach/pull/59624

From release notes:
> [`ALTER TABLE ... SET LOCALITY`](../v21.1/alter-table.html) adds the ability to change the locality of a `GLOBAL` or `REGIONAL BY TABLE` table to `REGIONAL BY ROW`, provided an existing column of the appropriate type already exists. [#59624][#59624] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Correct
