### ISSUE TITLE
sql: include invalid type descriptors in crdb_internal.invalid_objects

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10064]
PR: https://github.com/cockroachdb/cockroach/pull/59978

From release notes:
> `crdb_internal.invalid_objects` now includes invalid type descriptors. [#59978][#59978] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8909.
