### ISSUE TITLE
sql: Allow for multi-region database restores

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10076]
PR: https://github.com/cockroachdb/cockroach/pull/60257

From release notes:
> Added support for [restore](../v21.1/restore.html) of multi-region databases. [#60257][#60257] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @rmloveland as well

**Comment by jseldess** [comment]
@lnhsingh, @rmloveland, I'm not sure who should take this?

**Comment by rmloveland** [comment]
I will also yoink this one into #9932
