### ISSUE TITLE
sql: materialized views require ownership or admin privilege to refresh

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10078]
PR: https://github.com/cockroachdb/cockroach/pull/60448

From release notes:
> Materialized views now require ownership or admin privilege to refresh. [#60448][#60448] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans on the sql side. not sure who should take this.

**Comment by ericharmeling** [comment]
@jseldess I got it!
