### ISSUE TITLE
delegate: gate estimated_row_count on SHOW TABLES behind cluster setting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10071]
PR: https://github.com/cockroachdb/cockroach/pull/60282

From release notes:
> Added the `sql.show_tables.estimated_row_count.enabled` [cluster setting](../v21.1/cluster-settings.html), which defaults to `true`. If `false`, `estimated_row_count` will not display on `SHOW TABLES` which improves performance. [#60282][#60282] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9944.

(see follow-up PR for backport: https://github.com/cockroachdb/docs/pull/10229)
