### ISSUE TITLE
sql: implement ALTER TABLE LOCALITY !(REGIONAL BY ROW) -> REGIONAL BY ROW

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10070]
PR: https://github.com/cockroachdb/cockroach/pull/59824

From release notes:
> Implemented the ability to `ALTER TABLE SET LOCALITY` to `REGIONAL BY ROW` without specifying `AS` for `GLOBAL` and `REGIONAL BY TABLE` tables. [#59824][#59824] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rmloveland 
I don't think we need to document this any more than you already have done in https://www.cockroachlabs.com/docs/v21.1/set-locality.html ?

**Comment by rmloveland** [comment]
Correct
