### ISSUE TITLE
sql/pgwire: send placeholder BackendKeyData

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10073]
PR: https://github.com/cockroachdb/cockroach/pull/60281

From release notes:
> When a connection is established, CockroachDB will now return a placeholder `BackendKeyData` message in the response. This is for compatibility with some tools, but using `BackendKeyData` to cancel a query will still have no effect (which is the same as before). [#60281][#60281] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we don't need to document this.

@rafiss Please re-open if you disagree.
