### ISSUE TITLE
sql: Rebuild zone configs for multi-region tables during restore

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10084]
PR: https://github.com/cockroachdb/cockroach/pull/60519

From release notes:
> Multi-region tables will have their zone configs regenerated during database [restore](../v21.1/restore.html). [#60519][#60519] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @rmloveland. Not sure who's plate this lands on.

**Comment by jseldess** [comment]
@lnhsingh, @rmloveland, who should take this?

**Comment by rmloveland** [comment]
Jesse I can take this as part of #9932
