### ISSUE TITLE
sql: add crdb_internal.show_create_all_tables builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10080]
PR: https://github.com/cockroachdb/cockroach/pull/60154

From release notes:
> Add the builtin `crdb_internal.show_create_all_tables`, which takes in a database name (`STRING`) and returns a flat log of all the [`CREATE TABLE`](../v21.1/create-table.html) statements in the database followed by `ALTER` statements to add constraints. The output can be used to recreate a database. This builtin was added to replace old dump logic. [#60154][#60154] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
