### ISSUE TITLE
sql: add schema_name,table_id to crdb_internal.ranges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10092]
PR: https://github.com/cockroachdb/cockroach/pull/59865

From release notes:
> Added the `schema_name` and `table_i`d columns to the `crdb_internal.ranges` and `crdb_internal.ranges_no_leases` virtual tables. [#59865][#59865] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8909.
