### ISSUE TITLE
sql,gcjob: set RunningStatus when GC job performs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10090]
PR: https://github.com/cockroachdb/cockroach/pull/59220

From release notes:
> [`SHOW JOBS`](../v21.1/show-jobs.html) now displays a meaningful value in the `running_status` column for GC jobs which are actually performing garbage collection, as opposed to waiting on a timer. [#59220][#59220] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I believe the linked PR is just a bug fix, resulting in `SHOW JOBS` to output as currently documented. Closing.
