### ISSUE TITLE
builtins: add builtin to retrieve the payload(s) for a span.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10097]
PR: https://github.com/cockroachdb/cockroach/pull/60616

From release notes:
> Added `payloads_for_span` builtin that takes in a span ID and returns its paylods in `JSONB` format. If the span is not found, or if the span does not have any payloads, the builtin returns an empty JSON object. [#60616][#60616] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
