### ISSUE TITLE
sql: repartition regional by row tables on region add

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10107]
PR: https://github.com/cockroachdb/cockroach/pull/60596

From release notes:
> [`ALTER DATABASE ... ADD REGION`](../v21.1/alter-database.html) now re-partitions `REGIONAL BY ROW` tables and updates the [zone configs](../v21.1/configure-replication-zones.html) on the newly created partitions as well. [#60596][#60596] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rmloveland Do we want to explicitly document this beyond https://www.cockroachlabs.com/docs/v21.1/multiregion-overview.html#regional-by-row-tables?

**Comment by rmloveland** [comment]
no! linked doc already mentions the behind the scenes partitioning n stuff

**Comment by rmloveland** [comment]
I think between your link and https://www.cockroachlabs.com/docs/v21.1/add-region.html this can be closed
