### ISSUE TITLE
builtins: add generator builtin for span payloads

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10108]
PR: https://github.com/cockroachdb/cockroach/pull/60784

From release notes:
> Updated the `crdb_internal.payloads_for_span` builtin to return a table instead of a `JSONB` array. Each row of the table represents one payload for the given span. It has columns for `payload_type` and `payload_jsonb`. [#60784][#60784] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
