### ISSUE TITLE
sql,opt: add cluster and session settings for locality optimized search

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10104]
PR: https://github.com/cockroachdb/cockroach/pull/60771

From release notes:
> Added a new [session setting](../v21.1/set-vars.html) `locality_optimized_partitioned_index_scan` and corresponding [cluster default setting](../v21.1/cluster-settings.html) `sql.defaults.locality_optimized_partitioned_index_scan.enabled`. Both are currently disabled by default, and are currently unused. In the future, these settings will be used to enable or disable locality optimized search. If enabled, the optimizer will try to search locally for rows in `REGIONAL BY ROW` tables before searching remote nodes. [#60771][#60771] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Both of these settings are disabled and unused. I don't think we should document their usage until they do something.
