### ISSUE TITLE
sql: drop partitions and zone configs from RBR tables on region drop

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10109]
PR: https://github.com/cockroachdb/cockroach/pull/60938

From release notes:
> [`ALTER DATABASE ... DROP REGION ...`](../v21.1/alter-database.html) now re-partitions `REGIONAL BY ROW` tables to remove the partition for the removed region and removes the [zone configuration](../v21.1/configure-replication-zones.html) for the partition as well. [#60938][#60938] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
https://github.com/cockroachdb/docs/issues/10107#issuecomment-832820759
@rmloveland Similar question on this one
