### ISSUE TITLE
sql: add parse_timestamp builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10105]
PR: https://github.com/cockroachdb/cockroach/pull/60772

From release notes:
> Added the new `parse_timestamp` function, which can be used to parse absolute timestamp strings in computed column expressions or partial index predicates. [#60772][#60772] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
