### ISSUE TITLE
geo: add support for storing spatial types with Z and M dimensions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10106]
PR: https://github.com/cockroachdb/cockroach/pull/60832

From release notes:
> CockroachDB now supports storing spatial type objects with `Z` and `M` dimensions (e.g., `POINTZ`, `LINESTRINGM`). [#60832][#60832] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed by #10555
