### ISSUE TITLE
sql: add pg_class.relpartbound column

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10119]
PR: https://github.com/cockroachdb/cockroach/pull/61162

From release notes:
> The `pg_catalog.pg_class` table now has a `relpartbound` column. This is only for compatibility, and the column value is always `NULL`. [#61162][#61162] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8909.
