### ISSUE TITLE
sql: augment statement logging with a txn counter

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10114]
PR: https://github.com/cockroachdb/cockroach/pull/41929

From release notes:
> The structured payloads used for SQL audit and execution logs now include a transaction counter since the beginning of the session. Statements issued inside the same SQL [transaction](../v21.1/transactions.html) will thus be logged with the same counter value, thus enabling per-transactions grouping during log analysis. Separate sessions use independent counters. [#41929][#41929] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans, this might be SQL observability, not sure.

**Comment by taroface** [comment]
This is about the log messages, so it should be my area.

**Comment by taroface** [comment]
Closed by #10273.
