### ISSUE TITLE
sql,cli: add payloads_for_trace builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10116]
PR: https://github.com/cockroachdb/cockroach/pull/60922

From release notes:
> Added the `payloads_for_trace()` builtin so that all payloads attached to all spans for a given trace ID will be displayed, utilizing the `crdb_internal.payloads_for_span()` builtin under the hood. All payloads for long-running spans are also added to debug.zip in the `crdb_internal.node_inflight_trace_spans` table dump. [#60922][#60922] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
