### ISSUE TITLE
importccl,sql: support importing non-public schemas from pgdump

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10117]
PR: https://github.com/cockroachdb/cockroach/pull/57183

From release notes:
> [`IMPORT PGDUMP`](../v21.1/import.html) can now import dump files with non-public schemas. [#57183][#57183] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - I don't think docs need to be updated for this.
