### ISSUE TITLE
sql, server: expose contention info via vtable and StatusServer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10113]
PR: https://github.com/cockroachdb/cockroach/pull/60713

From release notes:
> Added new virtual tables `crdb_internal.cluster_contention_events` and `crdb_internal.node_contention_events`, which expose cluster-wide and gateway-only, respectively, contention information. In order to access them, the user needs to be either an admin or have `VIEWACTIVITY` grant. [#60713][#60713] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8909.
