### ISSUE TITLE
opt: remove uniqueness checks for gen_random_uuid()

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10118]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/61132

From release notes:
> Added the `sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled` [cluster setting](../v21.1/cluster-settings.html), which controls creation of uniqueness checks for [`UUID`](../v21.1/uuid.html] columns set to `gen_random_uuid(]`. When enabled, uniqueness checks will be added for the `UUID` column if it has a unique constraint that cannot be enforced by an index. When disabled, no uniqueness checks are planned for these columns, and uniqueness is assumed due to the near-zero collision probability of `gen_random_uuid()`. [#61132)[#61132) {% comment %}doc{% endcomment %}

Jira Issue: DOC-1055

**Comment by ericharmeling** [comment]
The `sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled` cluster setting is documented by https://github.com/cockroachdb/docs/pull/9904.
Beyond that, I don't think we need to document this, as it is a performance optimization that won't affect syntax/behavior.

**Comment by nvanbenschoten** [comment]
We should reconsider whether we want to document this or not. My take is that this is more than just a performance optimization and it is something we should document alongside REGIONAL BY ROW tables for two reasons:
1. people may want to use UUIDs in their primary keys if they know that this fast-path exists
2. people may want to disable this functionality if it sufficiently concerns them

**Comment by ajstorm** [comment]
I agree.  I'd also argue that if it defaults to off, we'd be less concerned with documenting.  That it defaults to on implies that some customers could be surprised if we encounter a (albeit unexpected) collision.  My vote is to document.

**Comment by rmloveland** [comment]
@ericharmeling for some additional context, I have a PR up adding some docs on locality optimized search which is conceptually related to why this 'removal of uniqueness checks' feature exists: https://github.com/cockroachdb/docs/pull/11900

**Comment by ajstorm** [comment]
AFAIK, this parameter only applies to REGIONAL BY ROW tables.  @rytaft would be able to confirm.

**Comment by rytaft** [comment]
That is correct -- we only need to consider uniqueness checks for `REGIONAL BY ROW` tables, not for any other table type. (We also consider uniqueness checks for the experimental features implicit partitioning and `UNIQUE WITHOUT INDEX`, but I don't think we usually make much of an effort to document experimental features)
