### ISSUE TITLE
builtins: implement ST_MakePoint and ST_MakePointM

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10115]
PR: https://github.com/cockroachdb/cockroach/pull/61105

From release notes:
> The geometry builtins `ST_MakePoint` and `ST_MakePointM` have been implemented and provide a mechanism for easily creating new points. [#61105][#61105] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
