### ISSUE TITLE
builtins: implement ST_Affine for 3D transformations

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10122]
PR: https://github.com/cockroachdb/cockroach/pull/61286

From release notes:
> The geography builtin `ST_Affine` now supports 3D transformations. [#61286][#61286] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
