### ISSUE TITLE
builtins: implement ST_Z, ST_M, and ST_Zmflag

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10123]
PR: https://github.com/cockroachdb/cockroach/pull/61032

From release notes:
> The `ST_Z`, `ST_M`, and `ST_Zmflag` builtins are now available for use. [#61032][#61032] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
