### ISSUE TITLE
geo/geomfn: implement ST_RotateY and ST_RotateZ

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10128]
PR: https://github.com/cockroachdb/cockroach/pull/61387

From release notes:
> `ST_RotateY` and `ST_RotateZ` are now available. [#61387][#61387] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
