### ISSUE TITLE
geo/geomfn: implement ST_RotateX

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10126]
PR: https://github.com/cockroachdb/cockroach/pull/61326

From release notes:
> `ST_RotateX` function is now available. [#61326][#61326] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
