### ISSUE TITLE
builtins: implement ST_Force3D, ST_Force3DM, ST_Force3DZ, ST_Force4D

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10124]
PR: https://github.com/cockroachdb/cockroach/pull/61297

From release notes:
> Geometry builtins for forcing geometries into non-2D layouts are now available. [#61297][#61297] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
