### ISSUE TITLE
sql: Require FORCE to modify protected zone config fields

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10131]
PR: https://github.com/cockroachdb/cockroach/pull/61499

From release notes:
> Updates to certain fields in the zone configurations are blocked for multi-region enabled databases. This block can be overridden through the use of the `FORCE` keyword on the blocked statement. [#61499][#61499] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@ajstorm AFAICT this feature got yanked for beta.2 in favor of a setting `override_multi_region_foo` or similar.

That would mean there is no `FORCE` syntax to document for v21.1.

Is my understanding above correct?  If so I'd like to close this issue.
