### ISSUE TITLE
util/tracing,sql: add builtin to set trace spans' verbosity

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10133]
PR: https://github.com/cockroachdb/cockroach/pull/61353

From release notes:
> Added a new builtin that sets the verbosity of all spans in a given trace. Syntax: `crdb_internal.set_trace_verbose($traceID,$verbosityAsBool)`. [#61353][#61353] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
