### ISSUE TITLE
builtins: implement ST_AddMeasure

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10132]
PR: https://github.com/cockroachdb/cockroach/pull/61514

From release notes:
> The `ST_AddMeasure` function is now available for use. [#61514][#61514] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
