### ISSUE TITLE
cli: add new pgdump/mysqldump flags to import cli command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10147]
PR: https://github.com/cockroachdb/cockroach/pull/60923

From release notes:
> Added the `ignore-unsupported-statements`, `log-ignored-statements` and `row-limit` flags to the [`cockroach import`](../v21.1/cockroach-import.html) command. [#60923][#60923] {% comment %}doc{% endcomment %}

**Comment by ianjevans** [comment]
Assigning myself to this issue, since I am already updating a topic that uses `IMPORT PGDUMP` as part of my work on updating `EXPLAIN`.
