### ISSUE TITLE
util/log: new experimental integration with Fluentd 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10144]
PR: https://github.com/cockroachdb/cockroach/pull/57170

From release notes:
> It is now possible to redirect logging to [Fluentd](https://www.fluentd.org)-compatible network collectors. See the reference sink documentation for details.This is an alpha-quality feature. Note that Fluent-enabled configuration only provide minimal event buffering, and log entries are dropped if the logging server becomes unavailable or network errors are encountered. This is a known limitation and will be likely improved in a later version. [#57170][#57170] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closed by #10273.
