### ISSUE TITLE
cli: add userfile get command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10146]
PR: https://github.com/cockroachdb/cockroach/pull/60490

From release notes:
> [`cockroach userfile get`](../v21.1/cockroach-userfile-get.html) can now be used to fetch files from a cluster. [#60490][#60490] {% comment %}doc{% endcomment %}

**Comment by gemma-shay** [comment]
I believe this was already opened here: https://github.com/cockroachdb/docs/issues/9821
And closed by this PR: https://github.com/cockroachdb/docs/pull/9946

**Comment by lnhsingh** [comment]
Closing - this is a dupe / has been documented
