### ISSUE TITLE
release-21.1: sql: add json{,b}_extract_path_text

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10141]
PR: https://github.com/cockroachdb/cockroach/pull/61813

From release notes:
> Added `json_extract_path_text` and `jsonb_extract_path_text` builtins. [#61813][#61813] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed https://github.com/cockroachdb/docs/pull/9907.
