### ISSUE TITLE
release-21.1: builtins: add Z and M dimension support for ST_SnapToGrid

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10140]
PR: https://github.com/cockroachdb/cockroach/pull/61826

From release notes:
> The `ST_SnapToGrid` function can now be used to snap `Z` and `M` dimensions. [#61826][#61826] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on [functions and operators](www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions) and mentioned elsewhere in docs via #10555
