### ISSUE TITLE
*: configure the use of separated intents in a cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10143]
PR: https://github.com/cockroachdb/cockroach/pull/59829

From release notes:
> Added the `storage.transaction.separated_intents.enabled` [cluster setting](../v21.1/cluster-settings.html), which enables separated intents by default. [#59829][#59829] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9904.
