### ISSUE TITLE
Update Database Restore example

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/docs#10165]
I tried to restore a database from a backup following the steps in our documentation, however, the restore failed.
[Our documentation ](https://www.cockroachlabs.com/docs/stable/restore.html#databases)states the following:

> Restoring a database will create a new database and restore all of its tables and views.
The created database will have the name of the database in the backup. The database cannot already exist in the target cluster.

The inaccuracy, pertains to this statement:

**The database cannot already exist in the target cluster.**

I attempted to restore the database after dropping it and received the following errors:

```
root@:26257/defaultdb> drop database test;
DROP DATABASE
Time: 358ms total (execution 85ms / network 274ms)

root@:26257/defaultdb> RESTORE test.* FROM 'nodelocal://1/full_backup' WITH into_db = 'test';
ERROR: a database named "test" needs to exist to restore table "t1"

root@:26257/defaultdb> RESTORE test.* FROM 'nodelocal://1/full_backup';
ERROR: a database named "test" needs to exist to restore table "t1"
```

Please notice, I tried 2 different restore calls and both failed:

- **WITH into_db = 'test'**
- and **without** the WITH into_db = 'test'

I then proceeded to creating an empty database and tried again. This time the restore worked:

```
root@:26257/defaultdb> create database test;
CREATE DATABASE
Time: 111ms total (execution 110ms / network 1ms)

root@:26257/defaultdb> RESTORE test.* FROM 'nodelocal://1/full_backup';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  643980358420070403 | succeeded |                  1 |    5 |             0 |    95
(1 row)
Time: 725ms total (execution 724ms / network 1ms)

root@:26257/defaultdb> use test;
SET
Time: 21ms total (execution 21ms / network 1ms)

root@:26257/test> select count(*) from t1;
  count
---------
      5
(1 row)
```

```
Server version: CockroachDB CCL v20.2.6 (x86_64-unknown-linux-gnu, built 2021/03/15 16:04:08, go1.13.14) (same version as client)
```

**Comment by lnhsingh** [comment]
Relevant slack convo: https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1616597376002800

The example in the docs is incorrect - it needs to be `RESTORE DATABASE backup_database_name` (it's missing the `DATABASE`). We might also want to remove the `into_db` option from this simple example too, as it can be confusing. Once the correct syntax is used, the RESTORE worked as documented (i.e., you can't restore a database if the database already exists)

**Comment by daniel-crlabs** [comment]
Thanks for the detailed info and working on correcting the docs :-)
