### ISSUE TITLE
Document IMPORT INTO limitations

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#10169]
Add to know limitations that changefeed doesn't pick up on IMPORT INTO.

**Comment by jseldess** [comment]
@amruss, if we're going to add this to the known limitations page, it's helpful to have a corresponding cockroach issue with the `docs-known-limitations` label.

**Comment by amruss** [comment]
Related to: https://github.com/cockroachdb/cockroach/issues/64276

**Comment by ericharmeling** [comment]
@amruss I believe this is resolved by https://github.com/cockroachdb/cockroach/pull/64323 and https://github.com/cockroachdb/docs/pull/10452.

Any objections to closing this issue?
