### ISSUE TITLE
Page "make queries fast" was renamed, but its links weren't, effectively breaking search

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#10161]
Richard Loveland (rmloveland) commented:

I don't know the new name, only the old name: "Make queries fast".

When I search for the above string, I get a lot of pages with links *to* the old page name above, but not (AFAICT?) the new thing.  Like I said I don't know what the new name is

I'm not 100% sure what the fix should be, but the user outcome I want is that if I search for "make queries fast", I either get (a) nothing, and taste the pain of page renames that don't use redirects (editorial: a practice I am against, for basically this reason), or (b) I should get a "DWIM" (do what I mean) result and get the intended page, even though it is renamed.

I think (b) is much harder to achieve technically, so ideally we would rename pages using the following process:

1. Want to rename a page from "Foo" to "Bar"
2. Make a new page "Bar", with the same/updated content
3. Edit the old "Foo" with the name we don't want anymore so it is a redirect to "Bar"
4. User searches for "Foo" because that's what they know and they go instantly to "Bar"
5. ???
6. Profit

Right now the results look like the screenshot below and are very confusing IMO.  I have to do 2 clicks, once to some page that has a link, then Ctrl-F to find the link, then click.  That's a lotta work to get a page.

![Screen Shot 2021-03-24 at 10 25 50 AM](https://user-images.githubusercontent.com/1312291/112326890-50456500-8c8b-11eb-843c-6e32dc52eba1.png)

**Comment by rmloveland** [comment]
@ericharmeling and @ianjevans - I think this one is for y'all so I went ahead and assigned, but let me know?

sorry to ping you both!  I still don't really know the breakdown of ownership in SQL docs-land, embarrassingly

**Comment by ericharmeling** [comment]
> I still don't really know the breakdown of ownership in SQL docs-land, embarrassingly

That makes a minimum of two of us - I think this one is for Ian though.

**Comment by ianjevans** [comment]
Yup, that’s mine.
