### ISSUE TITLE
Document known limitation re: new voter_constraints vs. old duplicate indexes

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#10173]
Via cockroachdb/cockroach#59482:

> until this issue is addressed, the duplicate indexes pattern won't work with "voter constraints" in zone configs. The suggested workaround is to use GLOBAL tables instead of duplicate indexes if users want fast reads and non-voting replicas.

> (Existing schemas with the duplicated indexes pattern should work fine -- what won't work is if users try to update the zone configs to use the new "voter constraints" instead of "constraints")

We will need to, at minimum, add this to the [Known Limitations for v21.1](https://www.cockroachlabs.com/docs/v21.1/known-limitations.html).

I'm torn on whether to do much beyond that since for the most part the old topology patterns are going away in favor of the [improved multi-region magic](https://www.cockroachlabs.com/docs/v21.1/multiregion-overview.html).  Then again, this is related to other things linked below, so ... scope of work TBD.

See also:

- cockroachdb/docs#10151
- #9039
- #9887
- #9710
- #9302 (this is not available from SQL, so we may need to do more here for folks using zone configs)

**Comment by rmloveland** [comment]
@awoods187 and @aayushshah15 : 

do we need to put this in docs?  if you are using the old duplicate indexes and also start tweaking `voter_constraints` or the other new multi-region zone config fields and it doesn't work is that really a "limitation"?  We already have [some docs on `voter_constraints`](https://www.cockroachlabs.com/docs/v21.1/configure-replication-zones.html#replication-zone-variables) that basically say "you should not use this field directly, just use the multi-region abstractions"

another reason not to document this as a "known limitation" is that even explaining the limitation may require that we explain a whole use case around why you might do this, and could serve as a sort of de facto "here is how you do this use case" but ... this is not something we wanted to support, right?

(my vote is no in case it's not obvious :-) but I defer to y'all's expertise)

**Comment by awoods187** [comment]
I'm aligned with you for a no here.

**Comment by rmloveland** [comment]
OK thanks Andy - I'll close this one
