### ISSUE TITLE
Stylesheet is broken for bullet lists - on FF

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1019]
See this screenshot:
![schermafdruk_2017-01-23_13-44-01](https://cloud.githubusercontent.com/assets/642886/22204413/276dac46-e172-11e6-9edb-dfef9319fa13.png)

The bullet point is not properly aligned with the bullet labels.

This is the latest Firefox.

**Comment by jseldess** [comment]
Thanks for reporting, @knz, but there's actually a lot more going haywire with the styling right now. Looks like all callouts (tips, warnings) are not getting closed properly. I think I messed something up in https://github.com/cockroachdb/docs/pull/1014. Looking now.

**Comment by jseldess** [comment]
Fixed that other issue but still seeing what @knz reports, just on firefox. 

@sploiselle, can you take a look at this? I don't see what would cause this in the css.

**Comment by sploiselle** [comment]
Fixed at some point in the past.
