### ISSUE TITLE
Simplify process for contributing to docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#102]
No need to fork repo. Can just clone and create branch. 

Page to update: https://github.com/cockroachdb/docs/blob/gh-pages/improve-the-docs.md

**Comment by bdarnell** [comment]
Only users who have permissions to write to the repo can create a branch directly; all others must still use a fork.

**Comment by jseldess** [comment]
Ah, ok. I was talking to @spencerkimball about this and must've misunderstood something. We can leave the process as is (fork repo, create branch, submit pull request).
