### ISSUE TITLE
Update partitioning docs re: PARTITION BY ROW vs. PARTITION BY LIST

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/docs#10217]
Exalate commented:

I could not find good info in the documentation on the differences between using `PARTITION BY ROW` and `PARTITION BY LIST`.

Jira Issue: DOC-1070

**Comment by nickvigilante** [comment]
@spaskob Thank you for your patience with this issue. I touched base with our product team on this and we don't have a `PARTITION BY ROW` option, but we do have a `PARTITION BY RANGE` option. Is that what you were referring to?

We have some docs outlining the differences between those two: https://www.cockroachlabs.com/docs/v22.1/partitioning.html#table-creation
