### ISSUE TITLE
Replace paper plane icon

### ISSUE THREAD

**Issue by yingzhuchin** [cockroachdb/docs#10220]
@anagio found that we're using a `fontawesome` library just for one icon, the paper plane icon below:

![image](https://user-images.githubusercontent.com/63265176/113209787-7a75c480-9241-11eb-9d3d-9cb79b7b57fd.png)

Can be seen live here: https://www.cockroachlabs.com/docs/v21.1/cockroach-import.html

It would be great if we could replace the icon so that we can swap out the entire `fontawesome` library for just one image file. This will improve page load. Opening this issue so @luciaaaaaaa can help us on the design front with this.

**Comment by luciaaaaaaa** [comment]
What kind of image file do you need for this one? I can get it to you

**Comment by yingzhuchin** [comment]
png should be fine, thank you!

**Comment by luciaaaaaaa** [comment]
Hey! @yingzhuchin I looked at the icon library we use (https://www.figma.com/file/B1vk7hciFy0Wba1B5tFqIutm/Symbolicons-Pro-Line?node-id=0%3A1) to select an alternative 
![icon](https://user-images.githubusercontent.com/48258790/113912909-ae089f80-97a9-11eb-8c1f-824ab1723788.png)
Let me know if this works , here is my working file in Figma https://www.figma.com/file/gUgY9eSxcWpLENJHLS5FZv/Docs-Redesign-follow-up-Issues?node-id=327%3A1

**Comment by yingzhuchin** [comment]
That looks good to me! Thank you @luciaaaaaaa.

@anagio, do you want to implement the new icon as part of your load time work, or should I put this on my backlog?

**Comment by anagio** [comment]
@yingzhuchin ill add it in my branch

**Comment by yingzhuchin** [comment]
Thanks @anagio!
