### ISSUE TITLE
Document known limitation re: can not IMPORT into REGIONAL BY ROW tables

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#10226]
Just what it says above.  We should add this to our [Known limitations](https://www.cockroachlabs.com/docs/v21.1/known-limitations.html).

**Comment by ajstorm** [comment]
A good place to start is here: https://github.com/cockroachdb/cockroach/pull/62899/files

Look at this comment, and the steps we're taking to make this into a "fake" RBR table.  We might want to document this as one possible workaround:

```
	// Convert fake table to full RBR table. This test is only required until we
	// support IMPORT directly to RBR tables. The thinking behind this test is
	// that this _could_ be one way that customers work-around the limitation of
	// not supporting IMPORT to RBR tables in 21.1. Note that right now we can't
	// make this column hidden (#62892).
```
