### ISSUE TITLE
CockroachDB Change Data Capture: Transactionally and Horizontally Scalable

### ISSUE THREAD

**Issue by iswade** [cockroachdb/docs#10223]
Exalate commented:

Re: [CockroachDB Change Data Capture: Transactionally and Horizontally Scalable](https://www.cockroachlabs.com/blog/change-data-capture/)

> Finally, imagine some later time when all messages up through `Z` have been read. Going through the same two processes again gets us the transactions and state of the database. In this case, transaction `(A->3,B->4)` committed at `hlc2` and `(C->5)` committed at `hlc3`. At `hlc3` the database contained `A=3,B=1,C=5`. Note that we can also reconstruct the database at `hlc2` if necessary.

## Issue Description

At `hlc3` the database contained `A=3,B=1,C=5`. 

## Suggested Resolution 

At `hlc3` the database contained `A=3,B=4,C=5`. 

Jira Issue: DOC-1078

**Comment by lnhsingh** [comment]
@jess-edwards - a blog copy edit for you!
