### ISSUE TITLE
Removing text from compare page

### ISSUE THREAD

**Issue by meagan-g** [cockroachdb/docs#10243]
The subheadline of this page: https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html# indicates you can click on feature but you can't.

It would be great if we could remove the text that says: `and click CockroachDB answers to view related documentation.`

**Comment by olgaromashko** [comment]
@jseldess can i work on this issue? :)

**Comment by jseldess** [comment]
@olgaromashko, sure. Please be sure to update the page in both the v20.2 and v21.1 directories.

**Comment by olgaromashko** [comment]
@jseldess I opened a PR, if anything needs to be edited, let me know :)
