### ISSUE TITLE
release-20.2: sql: add cluster settings for timeout settings

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10253]
PR: https://github.com/cockroachdb/cockroach/pull/62185

From release notes:
> `sql.defaults.idle_in_session_timeout` is now a public cluster setting. [#62185][#62185] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9904
