### ISSUE TITLE
release-21.1: sql: show time since table stats were collected in EXPLAIN

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10266]
PR: https://github.com/cockroachdb/cockroach/pull/61945

From release notes:
> [`EXPLAIN`](../v21.1/explain.html) and [`EXPLAIN ANALYZE`](../v21.1/explain-analyze.html) now show how long ago [table statistics](../v21.1/cost-based-optimizer.html#table-statistics) were collected. [#61945][#61945] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@ianjevans You might have already documented this?
