### ISSUE TITLE
release-21.1: sql: add EXPLAIN (VEC) output to the stmt bundle

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10262]
PR: https://github.com/cockroachdb/cockroach/pull/62049

From release notes:
> Statement [diagnostics bundles](../v21.1/explain-analyze.html#debug-option) now contain output of `EXPLAIN (VEC)` and `EXPLAIN (VEC, VERBOSE)` commands for the statements. [#62049][#62049] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@ianjevans You might have already documented this?

**Comment by ianjevans** [comment]
I haven't, but I added it to the mega-PR.
