### ISSUE TITLE
Improve the stylesheet for docs

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1026]
General thoughts about "how to increase value in the eye of the OSS community". Improve the docs stylesheet! By fixing these at least:

1) too much whitespace / too little density, to the point it's distracting; in particular:

   a) inter-line spacing, 
   b) inter-paragraph spacing 
   c) character width 
   d) table cell margins 

   are all too large 

2) the styling of `<code>...</code>` blocks has terrible contrast 

3) the color scheme of `<pre>` and `<code>` blocks is "sad" - it's overwhelmed by gray, there is no reason to do that, a white background with a better font would be just as fine and increase readability (edited)

**Comment by knz** [comment]
FWIW I like the spacing used in the release notes: https://forum.cockroachlabs.com/t/release-notes-for-beta-20170126/436

that would be great for docs.

**Comment by jseldess** [comment]
Have to say I disagree that the spacing is nicer in the forum, @knz. But there will inevitably be many perspectives on this type of thing. In any case, @kuanluo and I are going to talk about this next week and we'll come up with a plan, though there's too much to do this quarter already for this to be in focus.

**Comment by jseldess** [comment]
We recently restyled the entire site, including docs, so I'm closing this for now, although there's  plenty of additional room for improvement.
