### ISSUE TITLE
release-21.1: catalog: add namespace validation

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10267]
PR: https://github.com/cockroachdb/cockroach/pull/62245

From release notes:
> Changed the formatting of namespace validation failures in `cockroach debug doctor` output. [#62245][#62245] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We don't currently document the `cockroach debug doctor` tool, so we can probably close this issue.
