### ISSUE TITLE
release-21.1: multi-region DROP REGION fixes

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10268]
Lauren Hirata Singh (lnhsingh) commented:

PR: https://github.com/cockroachdb/cockroach/pull/62162

From release notes:
> Added validation that prevents regions being dropped on [multi-region databases](../v21.1/multiregion-overview.html] when there are <= 3 regions left on the database. [#62162][#62162) {% comment %}doc{% endcomment %}

Jira Issue: DOC-1088

**Comment by rmloveland** [comment]
After reading the related commit, this should more properly read as:

> ... prevents regions being dropped on multi-region databases when there are <= 3 regions left on the database and the survival goal is `REGION`
