### ISSUE TITLE
release-21.1: sql: ensure user has correct privileges when adding/removing regions

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10260]
PR: https://github.com/cockroachdb/cockroach/pull/62450

From release notes:
> `ALTER DATABASE .. SET PRIMARY REGION` now requires both `CREATE` and `ZONECONFIG` privilege on all objects inside the database when [adding the first region to the database](../v21.1/add-region.html#examples). The same behavior applies for dropping the last region using `ALTER DATABASE ... DROP REGION`. [#62450][#62450] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Permissions are documented for both [SET PRIMARY REGION](https://www.cockroachlabs.com/docs/v21.1/set-primary-region) and [DROP REGION](https://www.cockroachlabs.com/docs/v21.1/drop-region.html) in v21.1 docs
