### ISSUE TITLE
release-21.1: sql: disallow adding OIDVECTOR and INT2VECTOR columns

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#10270]
PR: https://github.com/cockroachdb/cockroach/pull/62180

From release notes:
> Disallowed adding columns of type `OIDVECTOR` or `INT2VECTOR` to a table in [`ALTER TABLE ... ADD COLUMN`](../v21.1/add-column.html) statements. These types are not allowed in user-created tables via [`CREATE TABLE`](../v21.1/create-table.html) and were previously erroneously allowed in `ALTER TABLE ... ADD COLUMN`. [#62180][#62180] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is a bug fix - I don't think it needs documentation.
