### ISSUE TITLE
remove "cross-continent" line from cross-config docs

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#1028]
@jseldess 

Can you remove the line "cross-continent scenarios will be better supported in the future" from  the [config page](https://www.cockroachlabs.com/docs/configure-replication-zones.html#nodereplica-recommendations)?

Per @dianasaur323 - this language is too vague and should cleared up when the expressive zine config docs are live.

**Comment by dianasaur323** [comment]
Ok - synced up with Ben. Apparently we are no longer recommending the raft tick interval config, so we should remove that. He also suggested using the term inter-contient versus cross-continent. On the cross-continent scenarios will be better supported in the future, let's do "cross-continent scenarios will improve in performance soon", and we can link over to the reactive lease RFC when Alex finishes writing it.

**Comment by jseldess** [comment]
Got it, thanks, @dianasaur323. As part of https://github.com/cockroachdb/docs/pull/1027, I've already removed the raft tick interval part. In that PR, I'll also revise the language as suggested.
