### ISSUE TITLE
release-21.1: changefeedccl: Apply avro schema prefix as a namespace

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10304]
PR: https://github.com/cockroachdb/cockroach/pull/61734

From release notes:
> The `WITH avro_schema_prefix` option for Avro [changefeeds](../v21.1/create-changefeed.html) now sets `schema.namespace` [#61734][#61734] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@lnhsingh for triage.

**Comment by lnhsingh** [comment]
Covered by https://github.com/cockroachdb/docs/pull/10292 - closing this issue
