### ISSUE TITLE
release-21.1: changefeedccl: Disable sinkful changefeeds when external io is disabled.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10305]
PR: https://github.com/cockroachdb/cockroach/pull/62756

From release notes:
> CockroachDB now fails fast when [Change Data Capture](../v21.1/change-data-capture.html) writes are blocked. [#62756][#62756] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@lnhsingh for triage.

**Comment by lnhsingh** [comment]
Closing - no docs updates needed
