### ISSUE TITLE
Orchestrate CockroachDB in a Single Kubernetes Cluster Doc Update 

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#10301]
Re: [Orchestrate CockroachDB in a Single Kubernetes Cluster](https://cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes.html)

## Issue Description
Users need to customize the statefulset yaml to set localities for production usage. 
Because the default Kubernetes statefulset yaml doesn't set locality on node start.

## Suggested Resolution 
Add a note to warn customers that customization is required. If localities are not set, the cluster will experience reduced resiliency and may encounter data loss.

**Comment by lin-crl** [comment]
Since the same yaml file is used for multi-region deployment, the same issue exists.

**Comment by jseldess** [comment]
Thanks, @lin-crl. I'm closing this in favor of https://github.com/cockroachdb/docs/issues/10311.
