### ISSUE TITLE
Update our SQL feature support reference docs for 21.1

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10349]
- [PostgreSQL Compatibility](https://www.cockroachlabs.com/docs/v21.1/postgresql-compatibility.html)
- [SQL Support Summary](https://www.cockroachlabs.com/docs/v21.1/sql-feature-support.html)

**Comment by jseldess** [comment]
@ianjevans, @ericharmeling, I'm just creating some issues for 21.1 GA. Can either of you help with this one?

**Comment by ericharmeling** [comment]
Happy to help out with this !

**Comment by jseldess** [comment]
@ericharmeling, is this something you can work on over the next week or so?

**Comment by ericharmeling** [comment]
>  is this something you can work on over the next week or so?

Yes! After wrapping up multi-region SQL syntax work, I'll make this the priority. Likely get to it early next week (May 10/11).
