### ISSUE TITLE
release-21.1: backupccl: require explicit option to backup interleaved tables

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#10353]
https://github.com/cockroachdb/cockroach/pull/63501

This should be listed as a known limitation in the BACKUP docs, as well as in the Upgrade docs, as folks that upgrade inadvertently may have their BACKUPs suddenly fail unless they have that option.

Currently, asking team whether we should backport the option as a no-op so that upgrade path is:
- Update your BACKUP processes to include that option
- Upgrade and hunky dory

**Comment by kathancox** [comment]
A note was added recently to the top of the BACKUP page on this and there is [a section](https://www.cockroachlabs.com/docs/v21.1/interleave-in-parent#deprecation) on the interleave page re the deprecation. 

So, I think this covers the issue... if other edits are needed beyond this, please feel free to reopen @mwang1026

**Comment by mwang1026** [comment]
I think people need to know about this since they will be (1) unable to take a backup and (2) unable to RESTORE that backup to any future versions if it contains interleaved tables.

**Comment by kathancox** [comment]
Jesse has included this in the upcoming upgrade docs, so I will also include this in a known limitations section in the 21.1 BACKUP docs
