### ISSUE TITLE
Update our performance benchmarking docs for 21.1 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10350]
@awoods187, @mwang1026, do we have new tpcc benchmarking results for 21.1 that should be reflected in the docs? And should we update the tutorials in any way? 

https://www.cockroachlabs.com/docs/v21.1/performance.html

**Comment by awoods187** [comment]
We aren't planning to push the scale here in 21.1 testing-wise. @nvanbenschoten can PTAL and see if we need to update anything else here?

**Comment by nvanbenschoten** [comment]
I'm not aware of anything that needs to change on that page, other than the reference to v20.2. There was no significant movement in any of the workloads that it references.
