### ISSUE TITLE
release-21.1: sql: add pg_get_partkeydef builtin for compatibility

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10368]
PR: https://github.com/cockroachdb/cockroach/pull/63149

From release notes:
> The [`pg_get_partkeydef` builtin function](../v21.1/functions-and-operators.html) is now implemented by always returning `NULL`. [#63149][#63149] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is documented in https://github.com/cockroachdb/docs/pull/9907.

Because the function returns `NULL` (i.e., is unimplemented) and is supported only for compatibility, I don't think we should document its use further.
