### ISSUE TITLE
release-21.1: sql: s/tuples/rows/ in vectorized stats

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10372]
PR: https://github.com/cockroachdb/cockroach/pull/62956

From release notes:
> Replaced the word "tuple" with its more user-friendly synonym "row" in [vectorized stats outputs](../v21.1/vectorized-execution.html). [#62956][#62956] {% comment %}doc{% endcomment %}

**Comment by ianjevans** [comment]
Fixed in #10240.
