### ISSUE TITLE
Search tool fails to find stuff

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1037]
I try to search for "CASE" here: https://www.cockroachlabs.com/docs/search.html?q=CASE

and this fails to find the docs about the SQL CASE expression, expected here: https://www.cockroachlabs.com/docs/sql-expressions.html#case-expressions

Similarly NULLIF cannot be found.

I wouldn't be surprised if the indexing engine that the search tool is based on is confused by the enclosing of the keyword in a `<code>` block. But I don't know for sure.

**Comment by jseldess** [comment]
Since switching to Algolia, this doesn't seem to be a problem anymore, based on my testing.
