### ISSUE TITLE
document COCKROACH_LOG_MAX_SYNC_DURATION

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#10395]
Ryan Kuo (taroface) commented:

The environment variable `COCKROACH_LOG_MAX_SYNC_DURATION` configures the time to detect a disk stall during file writes in logging. This needs to be documented.

Thread: https://cockroachlabs.slack.com/archives/CHVV403F0/p1619026675117800

Jira Issue: DOC-1627

**Comment by knz** [comment]
Nb: this was implemented ever since v19.1.

The default has changed over the releases

- 19.1 to 20.2: 30 seconds
- 21.1: 60 seconds

**Comment by knz** [comment]
Separately, we have another env var `COCKROACH_ENGINE_MAX_SYNC_DURATION` which does the same thing for low-level KV writes to disk.

**Comment by knz** [comment]
Note for logging, we detect a stall starting at 10 seconds in all cases. That first threshold triggers a waraning. Then when the max duration (as configured by env var) is reached, the process terminated.

**Comment by andreimatei** [comment]
Note also the `storage.max_sync_duration` and `storage.max_sync_duration.fatal.enabled` cluster settings.
