### ISSUE TITLE
Remove references or add warnings to DaemonSet deployments

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/docs#10405]
Chris Seto (chrisseto) commented:

Currently our docs recommend [deploying cockroachDB as a daemonset in some cases](https://www.cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes#storage). While the recommendation to do so for performance reasons are valid, there are many drawbacks to doing so that may not be apparent at first.

I've outlined some of the dangers in a [community response](https://forum.cockroachlabs.com/t/cockroachdb-running-in-kubernetes-with-longhorn-or-ceph/4465/6?u=chrisseto).

Jira Issue: DOC-1623

**Comment by taroface** [comment]
Per @chrisseto we might link the K8s tutorial to the K8s performance guide, which has a DaemonSet section that contains some warnings.
