### ISSUE TITLE
sql: add docs on new session variable for follower reads

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#10418]
Andy Woods (awoods187) commented:

In https://github.com/cockroachdb/cockroach/pull/57851 we introduced a new `default_transaction_use_follower_reads`
session variable, along with support for the `SET SESSION CHARACTERISTICS AS TRANSACTION AS OF SYSTEM TIME follower_read_timestamp()` statement. Let's document those accordingly.

**Comment by rmloveland** [comment]
Partially addressed by #10242 

TIL there is something called `SET SESSION CHARACTERISTICS` ? huh

**Comment by vy-ton** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/40265, we should also add a recipe that you can set `default_transaction_use_follower_reads=true` as a user/role-level default with `ALTER ROLE..SET`

**Comment by vy-ton** [comment]
@rmloveland Can we complete this in the next few weeks?

**Comment by rmloveland** [comment]
Vy Ton ***@***.***> writes:

> @rmloveland Can we complete this in the next few weeks?

Yes!  Thanks for the ping on this
