### ISSUE TITLE
Clarify self-service VPC Peering limitations

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#10416]
In our [CockroachCloud docs today](https://www.cockroachlabs.com/docs/cockroachcloud/network-authorization.html#vpc-peering), we say:

> Self-service VPC peering setup is available only while creating a new CockroachCloud cluster. To set up VPC peering for existing clusters, contact us.

This is not accurate. Self-service VPC peering is available for any cluster created after March 5th, 2020, and can be set up after the cluster is created. If the user sets up VPC peering after the cluster is created and they did not specify a CIDR range, they will be locked into the CIDR range we selected for them. This may lead to conflicts with IP addresses in their VPC. 

cc @DuskEagle

**Comment by DuskEagle** [comment]
This is correct. Also, we can note the CIDR range we choose for them is `172.28.0.0/14`. This can help them determine if there will be a conflict with the IP range of their VPC.

**Comment by lnhsingh** [comment]
@mikeCRL - moving this to your backlog, but let me know if you want @gemma-shay to cover this update since they're also familiar with VPC peering in CC.

**Comment by gemma-shay** [comment]
Moved to Jira: https://cockroachlabs.atlassian.net/browse/CC-4380.
