### ISSUE TITLE
Document connection usage test results

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#10421]
We will want to incorporate @RichardJCai  [connection test results](https://docs.google.com/document/d/1V5yZXBYm6bUFQrkqKRYaKoX3Fdru2jG3p1bYyG4D-fo/edit) into our docs. I see a couple of things to document

- Steps to reproduce results (similar to how users can reproduce TPC-C results
- Actual results - idle connection cost

@RichardJCai also mentioned

-  I think we should focus on memory overhead of connections and also document that starting a connection can be expensive (checking for pw / auth) but idle ones after opening them are not very expensive
- `cockroach workload run tpcc` accepts an --idle-conns param so that you can test tpcc with idle connections

**Comment by rafiss** [comment]
Is there an update on when this work is scheduled? More information about pool sizing and connection overhead continues to be a recurring ask from customers.

**Comment by vy-ton** [comment]
@ianjevans Do you or @ericharmeling  have the bandwidth to tackle this in the next 2 weeks?

**Comment by ianjevans** [comment]
I haven't had a chance to finish getting all the steps for using the Docker images & scripts Artem set up for testing this.

As a stopgap, I can create a quick PR with the connection pool sizing/overheard from the PgBouncer PR branch.

**Comment by vy-ton** [comment]
Yeah, I think we'll want to separate this from the PgBouncer docs (PgBouncer is on the 21.2 roadmap so we had a headstart)
