### ISSUE TITLE
release-20.2: backup: revalidate restored indexes if added during inc backup

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10433]
PR: https://github.com/cockroachdb/cockroach/pull/63314

From release notes:
> [`RESTORE`](../v20.2/restore.html) now re-validates restored indexes if they were restored from an incremental backup that was taken while the index was being created. [#63314][#63314] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @lnhsingh, @kathancox

**Comment by kathancox** [comment]
Closing this issue as I think this was taken care of with #10498. Feel free to reopen, if otherwise.
