### ISSUE TITLE
release-20.2: changefeedccl: Make it possible to configure kafka behavior.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10437]
PR: https://github.com/cockroachdb/cockroach/pull/63362

From release notes:
> Made the Kafka library used in [changefeeds](../v20.2/stream-data-out-of-cockroachdb-using-changefeeds.html) configurable via the `kafka_sink_config` option to enable latency vs. throughput configuration. [#63362][#63362] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @lnhsingh, @kathancox

**Comment by amruss** [comment]
We have this internally documented here - https://github.com/cockroachdb/docs/projects/47 
This option is meant to be an advanced operator configuration, and doesn't have the right syntax/guardrails for mass market yet. For now I don't think its something we want to document.
