### ISSUE TITLE
Orchestrate a Local Cluster with Kubernetes Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#10441]
Re: [Orchestrate a Local Cluster with Kubernetes](https://cockroachlabs.com/docs/v20.2/orchestrate-a-local-cluster-with-kubernetes.html)

## Issue Description

In the step to decommission a node, include a note to issue decommission command against a node and include the node port.

## Suggested Resolution 

```bash
kubectl exec -it cockroachdb-3 -- ./cockroach node decommission --self --certs-dir cockroach-certs --host=cockroachdb-3.cockroachdb.default:26258
```

**Comment by taroface** [comment]
This is now resolved.
