### ISSUE TITLE
How to download Windows executable from the command line

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10443]
For [Mac](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-mac#download-the-binary-1) and [Linux](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-linux#download-the-binary), we provide `curl` and `wget` commands to download, unpack, and place the `cockroach` binary on the `PATH`. 

For [Windows](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-windows#download-the-executable), however, we have them click a link to download the executable.

We should document a way to do this from the command line for Windows as well. This would be friendly to Windows users wanting to operate the CockroachDB server. But it's even more important for Windows users of our built-in SQL client. In the CockroachCloud UI, we currently just link them to our docs to download the executable:

![Screen Shot 2021-04-27 at 6 18 25 PM](https://user-images.githubusercontent.com/15893490/116319743-0cabb280-a785-11eb-8235-d06912d55d90.png)

**Comment by jseldess** [comment]
Based on input from @aaron-crl, `curl` is built into Windows 10 now, so the same command that works on mac or linux should work with minor path edits on Windows 10 machines. Confirmed by this [Microsoft article](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows#:~:text=Tar%20and%20curl%20are%20staples,come%20to%20know%20and%20love!&text=Tar%3A%20A%20command%20line%20tool,extract%20files%20and%20create%20archives.). 

```curl https://binaries.cockroachdb.com/cockroach-v20.2.8.windows-6.2-amd64.zip  | tar -xJ```

@aaron-crl. does that look right? 

Also, in the Windows install docs, we don't tell users to put the executable on the Windows PATH. Should we correct that as well?

**Comment by aaron-crl** [comment]
The above command gave me some trouble on Windows 10 - this might be related to PIPE on windows. However downloading the zip file first and then extracting it worked fine. Something like this:

```
curl https://binaries.cockroachdb.com/cockroach-v20.2.8.windows-6.2-amd64.zip -o cockroach-v20.2.8.windows-6.2-amd64.zip ; tar -xJ -f cockroach-v20.2.8.windows-6.2-amd64.zip
```

Someone with more Windows CLI foo can probably give you something better but the above _should_ work.

> Also, in the Windows install docs, we don't tell users to put the executable on the Windows PATH. Should we correct that as well?

We probably should correct this to standardize the experience as much as possible.

**Comment by knz** [comment]
windows uses a zip file; so using `tar -xJ` is incorrect in that case.

@jseldess I hadn't caught that we use `.zip` and not `.tgz` for windows. This changes the situation a bit. The proper command to extract zip files is `unzip`, not `tar`.

**Comment by aaron-crl** [comment]
fwiw: tar also supports zip files with the `z` flag. I just tested the below on a windows box and got the exe.
`curl -O https://binaries.cockroachdb.com/cockroach-v20.2.8.windows-6.2-amd64.zip | tar -xzJ`

**Comment by knz** [comment]
`z` and `J` are contradictory. The fact you are not getting an error tells me that this `tar` command is no tar at all and ignores its args, probably some powershell trickery.
I am of the opinion we should not rely on trickery and recommend the proper commands.

**Comment by aaron-crl** [comment]
Apologies. I didn't test cleanly and mistook an old file for successful extraction. User error on my part for the args. 
You are correct, it does emit an error with both args specified namely: `tar: Can't specify both -J and -z`

The version of tar on my windows 10 machine lists itself as `bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp`
`tar -xf cockroach-v20.2.8.windows-6.2-amd64.zip` works flawlessly.

I have tested and confirmed a slightly modified version of the above command on a currently patched Windows 10 machine:

`curl https://binaries.cockroachdb.com/cockroach-v20.2.8.windows-6.2-amd64.zip -o cockroach-v20.2.8.windows-6.2-amd64.zip && tar -xf cockroach-v20.2.8.windows-6.2-amd64.zip`

**Comment by knz** [comment]
ok so it so happens that bsdtar has a compile-time option to auto-recognize zip files, which is why this appears to work. 

FWIW, GNU tar does not have such an option. If the user is mixing-and-matching their tar from multiple sources, this is going to fail sometimes.

OTOH, the "unzip" command is bound to always succeed.

**Comment by jseldess** [comment]
OK, so if we go with zip, what would the exact command be?

```
curl https://binaries.cockroachdb.com/cockroach-v20.2.8.windows-6.2-amd64.zip  | unzip
```

Or something else?

**Comment by knz** [comment]
`curl ...; unzip ...` (with semicolon)

**Comment by jseldess** [comment]
Thanks, @knz. On macOS at least, it looks like I need to use `curl -O`:

```
curl -O https://binaries.cockroachdb.com/cockroach-v20.2.8.windows-6.2-amd64.zip ; unzip cockroach-v20.2.8.windows-6.2-amd64.zip
```
Look right? Should we use `curl -O` for the linux and macOS curl commands as well, even if not technical necessary?

**Comment by knz** [comment]
yep, that sounds right. I had forgotten about `-O`.

**Comment by jseldess** [comment]
Awesome. And one final question: What about adding the executable to the PATH on Windows? Is there an equivalent to `cp -i cockroach-v21.1.0.darwin-10.9-amd64/cockroach /usr/local/bin/` on macOS/Linux? I know we will be looking into find a different location in the user's home directory, but for now, it'd be nice to offer the equivalent approach for all 3 OSs.

**Comment by knz** [comment]
I'd say

```
mkdir -p %programfiles%/Cockroach
cp -i yourfile %programfiles%/Cockroach
```

There's no common shared location that's guaranteed to be in the user's PATH env var.

A windows expert would need to tell.

**Comment by gemma-shay** [comment]
Moved to Jira: https://cockroachlabs.atlassian.net/browse/CC-4384
