### ISSUE TITLE
sql: new multi-region ORM guidance

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#10455]
In general, we encourage DDL to be done outside of ORMs (especially DDL requiring special CRDB only features). The new multi-region features largely are contained to DDL (and the changes to DML are automatic like homing on insert). However, the one area in which it can be a bit tricky is for regional by row tables using the crdb_region column. How should ORMs map this entity as a user-defined ENUM? You can model your data this way from the start, but what about upgrading from a single-region to multi-region? It's likely that this will be mitigated by user-defined columns set as the crdb_region column https://www.cockroachlabs.com/docs/v21.1/set-locality#regional-by-row but we should still provide guidance for each supported ORM.

I think this likely falls into @ericharmeling area given his work with MovR and ORM expertise but @rmloveland should be aware of it and we are both available for support. cc @vy-ton  for awareness

**Comment by nstewart** [comment]
> It's likely that this will be mitigated by user-defined columns set as the crdb_region column

One tricky thing about the user-defined column (also a problem with the hidden column) is that those columns still have to be of type `crdb_internal_region`, which we need to teach an ORM how to understand.

**Comment by vy-ton** [comment]
For Hibernate, I followed [this tutorial](https://thorben-janssen.com/hibernate-enum-mappings/#customizedMapping) to map to an `ENUM` type

**Comment by ericharmeling** [comment]
For SQLAlchemy, it looks like you can just use an ENUM as well, but you need to specify the right parameters to make sure that it's not attempting to use the native postgres ENUM type.

[The SQLAlchemy docs](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Enum.__init__) suggest it would look something like:

```
from sqlalchemy.types import Enum

crdb_internal_regions = Enum(regions_list, name='crdb_internal_regions', native_enum=False)
```

I think the crdb_internal_regions is just implemented as a string enum in cockroach... but I could be wrong? @otan

**Comment by ericharmeling** [comment]
So here are two general approaches to representing the `crdb_internal_region` ENUM in an ORM **for DML queries**:

**1. Just use string-typed columns**

I have found this approach works fine in SQLAlchemy when reading/writing against a table with an existing `crdb_region` column:

- Add `crdb_region` to an existing table object as a string-typed column.
- Use string literals as `crdb_region` values in read/write operations.

For example, suppose that you have a single-region table that has just been transformed into a multi-region table. In the absence of an explicit, back-filling computed column for `crdb_region`, the following function updates the (hidden, auto-generated) `crdb_region` column values of rows that were inserted before the multi-region transformation was executed:

```
def update_region(self, table, region, cities):

    def update_region_helper(session, table, region, cities):
        crdb_region = Column('crdb_region', String)
        table.append_column(crdb_region)
        query = table.update().where(column('city').in_(cities)
                                     ).values({crdb_region: region})
        session.execute(query)

    run_transaction(sessionmaker(bind=self.engine),
                    lambda session: update_region_helper(session, table, region, cities))
```

(I actually used this approach initially for [the `movr` load generator](https://github.com/cockroachdb/movr/commit/a62649e0cb5af45d98a4aa628b054c56bcb59ed3#diff-d65aa44d9ba12146d4d074fc4027e0b5a533a70b1252e902de8030e85ec77b83R224).)

A few things to note about this approach:

- I haven't tested it for any other ORM. I don't see why it wouldn't work with other ORMs, as `crdb_internal_region` is a string enum, but I could be naive in assuming that.
- There is no client-side string validation with an approach this simple. But CRDB validates input on the server-side, so we could just recommend some exception handling for SQL errors.... or we could recommend implementing string validation (which honestly might be more work than doing the **2** approach).

**2. Create an enum type, and then use that type for the column**

This is the more involved (probably more correct?) approach that I suggested [above](https://github.com/cockroachdb/docs/issues/10455#issuecomment-829319329):

- Create an `ENUM` type (using the ORM/language type library) of name `crdb_internal_region`, with enumerated values for each of the existing regions.
- Create a new column of the new `ENUM` type, and add it to the table object after the multi-region transformation. 

For example (the same scenario as above):

```
def update_region(self, table, region, cities):

    region_list = self.get_regions()
    region_enum = Enum(*region_list, name='crdb_internal_region', create_type=False, native_enum=False)

    def update_region_helper(session, table, region, cities):
        crdb_region = Column('crdb_region', region_enum)
        table.append_column(crdb_region)
        query = table.update().where(column('city').in_(cities)
                                     ).values({crdb_region: region})
        session.execute(query)

    run_transaction(sessionmaker(bind=self.engine),
                    lambda session: update_region_helper(session, table, region, cities))
```

This also works, but it might not be as straightforward with other ORMs. And it certainly won't look the same, and will depend heavily on the ORM/language's support for `ENUM` types.

(I have a PR open that implements this approach for `movr`: https://github.com/cockroachdb/movr/pull/112).

----

So here are some of my takes:

- It would be difficult to maintain ORM-specific guidance for creating custom `crdb_region` ENUMs in each ORM we support. As a result, we might need to just give some generic recommendations, based on the **2** approach, with SQLAlchemy (and possibly Hibernate and another common ORM) as examples. 
- We can add a note recommending **1** in the absence of ENUM support in a given framework, or in the event of some unexpected type-compatibility issues.
- The **1** and **2** approaches are limited to representing `crdb_region` columns in DML operations only (i.e., for reading/writing rows). For DDL statements (e.g., when we need to have some client-side `ALTER TABLE ... ADD COLUMN crdb_region` schema migration), we can only really recommend using raw SQL until we figure out the best schema migration guidance for ORMs. SQLAlchemy, for example, does **not** support any DDL statements beyond creating/dropping a table. From [their docs](https://docs.sqlalchemy.org/en/14/core/metadata.html#altering-database-objects-through-migrations):
    > While SQLAlchemy directly supports emitting CREATE and DROP statements for schema constructs, the ability to alter those constructs, usually via the ALTER statement as well as other database-specific constructs, is outside of the scope of SQLAlchemy itself. 

    So we will have to treat the way we model the `crdb_region` column differently for DDL statements (much closer to the **2** approach, I assume), and put it in the context of a schema migration tool, as Andy noted above.

**Comment by otan** [comment]
Sorry, late to the part!

> I think the crdb_internal_regions is just implemented as a string enum in cockroach... but I could be wrong? @otan

yes.

> So here are some of my takes

I agree with the approach.

> e.g., when we need to have some client-side ALTER TABLE ... ADD COLUMN crdb_region schema migration

indeed, this seems difficult with existing ORMs :\

**Comment by vy-ton** [comment]
Wanted to note that Option #2 would be useful as a general developer recipe for mapping ENUM database type to ENUM in a developer's programming language.
