### ISSUE TITLE
release-21.1: sql, config: make `voter_constraints` inherit from parent by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10467]
PR: https://github.com/cockroachdb/cockroach/pull/63674

From release notes:
> The internal representation of the `voter_constraints` [zone configuration](../v21.1/configure-replication-zones.html) attribute (new in v21.1) has been altered in a way that is partially incompatible with the representation used by previous v21.1 betas (and the alphas that include this attribute). This means that users who directly set the `voter_constraints` attribute to an empty list will lose those constraints and will have to reset them. [#63674][#63674] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Closing since this is referring to a behavior change between betas of v21.1, which now has a GA release.  Also, [our docs say you should probably not set this directly, but instead use the new MR capabilities](https://www.cockroachlabs.com/docs/v21.1/configure-replication-zones.html#num_voters)
