### ISSUE TITLE
release-21.1: changefeedccl: disallow changfeeds on regional by row tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10469]
PR: https://github.com/cockroachdb/cockroach/pull/63542

From release notes:
> [Changefeeds](../v21.1/create-changefeed.html) will now fail on any [regional by row table](../v21.1/multiregion-overview.html#regional-by-row-tables) with an error, `CHANGEFEED cannot target REGIONAL BY ROW tables: <table_name>.` This is to prevent unexpected behavior in changefeeds until they offer full support for this type of table. [#63542][#63542] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
cc @rmloveland and @kathancox, as I'm not sure how we're documenting this limitation.

**Comment by rmloveland** [comment]
This was fixed in https://github.com/cockroachdb/docs/pull/10310
