### ISSUE TITLE
Provide more details on how backup works

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#10495]
Jessie Lin (lin-crl) commented:

Re: [BACKUP](https://cockroachlabs.com/docs/v1.0/backup.html)

## Issue Description
Provide more details as described in the doc below
Each node backs up only a specific subset of the data it stores (those for which it serves writes; _more details about this architectural concept forthcoming_) 

## Suggested Resolution 
For example "The node you run the BACKUP command from defaults to being the coordinator, but which node is coordinating can change as the backup runs. BACKUP writes data to storage from the leaseholder so it doesn't matter which node you kick-off the backup from (any node with a leaseholder can be writing data to the backup). The coordinator though also needs access to the storage bucket because the coordinator writes the metadata from the backup, and since the coordinator can be any node in your cluster every node needs access to that file storage. "

Jira Issue: DOC-1604

**Comment by sheaffej** [comment]
A @lin-crl states, the current docs display:

https://www.cockroachlabs.com/docs/v20.2/backup.html#performance
> Each node backs up only a specific subset of the data it stores (those for which it serves writes; **more details about this architectural concept forthcoming)**

However, this same text is displayed going back to v1.0:
https://www.cockroachlabs.com/docs/v1.0/backup#performance
