### ISSUE TITLE
sasl_mechanism included in changefeed docs before it is available

### ISSUE THREAD

**Issue by osmes** [cockroachdb/docs#10497]
The CREATE CHANGEFEED documentation [1] references the query parameter "sasl_mechanism" but the feature enabling that has not yet been released (as of 20.2.8).  This should be removed until which time a user can implement it to avoid confusion.

[1] https://www.cockroachlabs.com/docs/v20.2/create-changefeed.html

gz#8218

**Comment by jseldess** [comment]
cc @amruss, @kathancox, since this has come up a few times via Support, should we prioritize a fix, if it's still needed?

**Comment by jseldess** [comment]
Ah, sorry. Just saw the open PR. Would be great to get that merged.
