### ISSUE TITLE
CC Upgrade to v21.1 docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10502]
CC example from 20.2:

https://www.cockroachlabs.com/docs/cockroachcloud/upgrade-to-v20.2.html#respect-temporary-limitations

This work should be based on the CRDB v21.1 upgrade docs, which are in progress.

**Comment by jseldess** [comment]
@emily-horing, @joshimhoff, will the process for CC upgrade to 21.1 be the same as for 20.2, overall?

**Comment by emily-horing** [comment]
We haven't iterated at all on the CC upgrade process for major upgrades this cycle to my knowledge, definitely not on the user-facing side.  The process should be more or less the same as last cycle.

**Comment by jseldess** [comment]
OK, great. When do we plan to offer 21.1 upgrade in the CC Console? Just so I know when we need docs by.

**Comment by emily-horing** [comment]
May 18th -- same as the Marketing GA date! Thanks for being on top of this
Jesse.
