### ISSUE TITLE
Clarify difference between Developer and Console Admin roles in CC

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#10511]
Re: [Console Access Management](https://cockroachlabs.com/docs/cockroachcloud/console-access-management.html)

## Issue Description

The difference in roles between Developer role and Console Admin role is not clear.

## Suggested Resolution 

Please provide a complete list of privileges, with a description of what actions those privileges enable.  Then show which of those privileges are associated with the Developer role and which are associated with the Console Admin role.

Please add any additional discussion as necessary, perhaps highlighting from a practical point of view what a Developer role can do compared to a Console admin role.  For example, 

* it may be helpful to clarify what role is needed to perform backups.  
* It may be helpful to clarify whether there is a way to create a read-only role.
* It may be helpful to clarify the relationship between CC roles and role-based access control (RBAC) for database users.

**Comment by jseldess** [comment]
@gemma-shay, @emily-horing for triage. Feel free to close this and move to Jira.

**Comment by emily-horing** [comment]
@hand-crdb can you confirm you've viewed [these docs ](https://www.cockroachlabs.com/docs/cockroachcloud/console-access-management.html)and are requesting enhancements? If so I'll create a Jira ticket to track.

**Comment by gemma-shay** [comment]
Moved to Jira https://cockroachlabs.atlassian.net/browse/CC-4379.
