### ISSUE TITLE
Update Operator on OpenShift docs for Connecting to SQL Client

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#10517]
It appears our current guidance ([README](https://github.com/cockroachdb/cockroach-operator#access-the-sql-shell), [public docs](https://www.cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes.html#step-3-use-the-built-in-sql-client)) for securely connecting to a SQL client for deployments with the Operator needs to be updated. AFAIK, this is related to our changing our guidance to moving away from the K8s CA that’s being deprecated ([old Github issue](https://github.com/cockroachdb/cockroach-operator/issues/291)).

In @taroface 's open PR for creating Operator on OpenShift docs ([#10453](https://github.com/cockroachdb/docs/pull/10453)), he drafted this guidance for [creating an additional client pod for connecting to a cluster](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/openshift-dev.md#create-a-secure-client-pod-to-connect-to-the-cluster). Previously, we would connect to an existing pod.

As noted in [this slack message](https://cockroachlabs.slack.com/archives/C0165QKD78F/p1620327546279300), let's first agree on what best practices are for connecting a SQL client Operator deployments on GKE.

**Comment by taroface** [comment]
This duplicates https://github.com/cockroachdb/docs/issues/8889 and https://github.com/cockroachdb/docs/issues/9782 and is not related to K8s CA deprecation. Closing in favor of #8889.
