### ISSUE TITLE
SQL FAQs - row ID and rowid confusion

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#10518]
Crossman Wilkins commented:

Re: [SQL FAQs](https://cockroachlabs.com/docs/v20.2/sql-faqs.html)

## Issue Description

I think this line:

"To auto-generate unique row IDs, use the UUID column with the gen_random_uuid() function as the default value:"

Unintentionally conflates rowid with UUID. I think this could cause confusion since rowid is something specific and row IDs could be read as rowid. 

## Suggested Resolution 

Use a term other than "row IDs" to explain UUID and the random function. 

Jira Issue: DOC-1600

**Comment by awoods187** [comment]
@vy-ton  can you PTAL and make a rec here with @ericharmeling?

**Comment by vy-ton** [comment]
@ericharmeling My suggestion would be `To auto-generate unique row identifiers`. It's a small change but `identifier` to me conveys the concept without the confusion with any variable named `ID`.
