### ISSUE TITLE
Explain the drawbacks of sslmode=require for CockroachCloud

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/docs#10525]
In the Cockroach Cloud docs for [connecting to your cluster](https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster#step-4-connect-to-your-cluster), we note that users can connect using `sslmode=require` to avoid using the `ca.crt` file. We note that it is less secure, but we don't explain why.

We should explain that using `sslmode=require` opens a customer up to man-in-the-middle attacks, because their client is unable to verify the identity of the server they are connecting to as belonging to Cockroach Cloud or not.

**Comment by jseldess** [comment]
cc @mikeCRL and @gemma-shay. Not sure who wants to take this. Perhaps Gemma (CC) can take it and Mike (security) can support?

**Comment by gemma-shay** [comment]
Moved to Jira https://cockroachlabs.atlassian.net/browse/CC-4378.
