### ISSUE TITLE
PostgreSQL "cancel" messages are currently unsupported in CockroachDB

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#10566]
Matthew Vardi (mattcrdb) commented:

I believe that we should add that to our incompatibility on https://www.cockroachlabs.com/docs/v20.2/postgresql-compatibility.html

Relevant issues:
1. https://github.com/cockroachdb/cockroach/issues/41335
2. https://github.com/cockroachdb/cockroach/pull/54618

The current guidance is to use CANCEL QUERY instead.

cc @knz 

Jira Issue: DOC-1593

**Comment by jseldess** [comment]
@ericharmeling, did you recently cover this?

**Comment by ericharmeling** [comment]
> did you recently cover this?

I don't believe so. I've put it on the SQL docs board for triage.

**Comment by knz** [comment]
We've "fixed" this by actually supporting cancel requests.
