### ISSUE TITLE
List of compatible postgreSQL UIs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1056]
@andreimatei, @sploiselle, do either of you know which postgres UI was mentioned as working with cockroachdb in today's team meeting?

**Comment by andreimatei** [comment]
I think Postico was reported to work.
https://eggerapps.at/postico/

**Comment by jseldess** [comment]
Thanks, @andreimatei. 

@knz, in Gitter, you said, "we know some others got web-based tools to work already, unfortunately we don't maintain a list of which clients work yet." Can you name any of those other clients?

**Comment by knz** [comment]
FWIW there's a list of pg tools maintained here: https://wiki.postgresql.org/wiki/Community_Guide_to_PostgreSQL_GUI_Tools

**Comment by knz** [comment]
the one I was thinking about was phpPgAdmin but I'm fairly sure support was only partial

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2979.
