### ISSUE TITLE
Distribution Layer in Architecture does not mention range merges

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#10577]
We make no reference to range merging in https://www.cockroachlabs.com/docs/v20.2/architecture/distribution-layer.html.

We should do so in much the same way that we reference range splitting on the page.

**Comment by jseldess** [comment]
@nvanbenschoten, @rmloveland added range merges to the 21.1 version of the page (soon to be stable): https://www.cockroachlabs.com/docs/v21.1/architecture/distribution-layer.html#range-merges. It's easy to port it back to 20.2, if the details are the same.

**Comment by nvanbenschoten** [comment]
Thanks for pointing that out @jseldess!

One other change we'll want to make across 21.1 and 20.2 (if we decide to backport) is to list range merges in the `Range descriptors are updated whenever there are:` list on this page.
