### ISSUE TITLE
Distribution Layer in Architecture makes incorrect claims about leaseholder info in range descriptors

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#10576]
Throughout https://www.cockroachlabs.com/docs/v20.2/architecture/distribution-layer.html, we make reference to information about a range's leaseholder being stored in meta ranges. For instance, we say that the meta range KV structure includes leaseholder information and that leaseholder changes require an update to a range's descriptor.

This is inaccurate. Leaseholder state is local to a range and is not stored outside of the range or in the range's descriptor. As a result, changes to a range's leaseholder do not result in updates to its range descriptor.

**Comment by jseldess** [comment]
cc @rmloveland, @mwang1026 for prioritization.
