### ISSUE TITLE
Improve docs for backup to Caddy fileserver

### ISSUE THREAD

**Issue by recursionbane** [cockroachdb/docs#10581]
Exalate commented:

**Describe the problem**

The [current docs](https://www.cockroachlabs.com/docs/v21.1/use-a-local-file-server-for-bulk-operations.html#using-caddy-as-a-file-server] as of v21.1 use Caddy v1 as reference. It is no longer possible to download Caddy v1 with the http.upload plugin from official sources.

Using the instructions provided with Caddy v2 fails with:

`[ERROR) first argument must be a subcommand; see 'caddy help'`

**To Reproduce**

Just follow instructions listed in the [docs](https://www.cockroachlabs.com/docs/v21.1/use-a-local-file-server-for-bulk-operations.html#using-caddy-as-a-file-server].

**Expected behavior**

The backup should succeed.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [e.g. 2.0.x]: v21.1.0
 - Server OS: [e.g. Linux/Distrib]: Linux
 - Client app [e.g. `cockroach sql`, JDBC, ...): cockroach sql

![image](https://user-images.githubusercontent.com/9662059/117890363-e4828000-b269-11eb-93a1-9e7f2151763e.png)

**Additional context**
Cannot perform backups to Caddy fileserver by following docs.

Jira Issue: DOC-1595

**Comment by mwang1026** [comment]
FYI https://github.com/cockroachdb/cockroach/issues/58865#issuecomment-897681209
