### ISSUE TITLE
Typo on Deploy CockroachDB on Red Hat OpenShift tutorial

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#10585]
Artem Ervits (dbist) commented:

Re: [Deploy CockroachDB on Red Hat OpenShift](https://cockroachlabs.com/docs/v21.1/deploy-cockroachdb-with-kubernetes-openshift.html)

## Issue Description

Make sure CockroachDB Version is set to an valid CockroachDB version

## Suggested Resolution 

**Make sure CockroachDB Version is set to a valid CockroachDB version**

Jira Issue: DOC-1590

**Comment by dbist** [comment]
@taroface

**Comment by taroface** [comment]
@dbist I attempted to cover this here: https://www.cockroachlabs.com/docs/v21.1/deploy-cockroachdb-with-kubernetes-openshift.html#step-3-start-cockroachdb 

although I know it isn't the most elegant instruction. Any recommendations on adding to this part would be appreciated.

**Comment by dbist** [comment]
@taroface this is issue a minor nit, it says `an valid` to `a valid`.
