### ISSUE TITLE
OpenShift tutorial: Missing steps to label the Prometheus service

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#10586]
Artem Ervits (dbist) commented:

Re: [Orchestrate CockroachDB in a Single Kubernetes Cluster](https://cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes.html)

## Issue Description

Openshift directions for Prometheus should include equivalent steps to label the service

## Suggested Resolution 

`oc label svc crdb-tls-example-public prometheus=cockroachdb
service/crdb-tls-example-public labeled`

Jira Issue: DOC-1589

**Comment by dbist** [comment]
@taroface @johnrk

**Comment by jseldess** [comment]
@dbist, you're linking to the non-openshift tutorial but naming a problem in the openshift tutorial. Can you please clarify the issue?
