### ISSUE TITLE
Document CDC backwards incompatible change in 21.1

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/docs#10597]
The upgrade to the sarama library in facbd60 included a change to the default Version assumed by sarama from 0.8.2.0 to 1.0.0.

The result of this is that we no longer support Kafka < 1.0 (Confluent Platform < 4.0).

All of the impacted versions are EOL according to:

https://docs.confluent.io/platform/current/installation/versions-interoperability.html

NB: We are working on a workaround for users on these older versions, but at the moment we are simply incompatible with them.

**Comment by jseldess** [comment]
@stevendanna, this is specific to CDC, correct? Was this called out in a alpha/beta/rc release note, or is this something we just discovered?

cc @kathancox and @amruss, can you work on this together? I think we need to add an item to this list: https://www.cockroachlabs.com/docs/releases/v21.1.0.html#backward-incompatible-changes. And probably call this out in various CDC docs.

**Comment by stevendanna** [comment]
@jseldess It is something we just discovered.  I don't mind working on the language to add here as well.
