### ISSUE TITLE
Create performance troubleshooting recipes document

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/docs#10606]
In addition to the existing tutorials we use that are more focused on schema design:
https://www.cockroachlabs.com/docs/v21.1/make-queries-fast.html
https://www.cockroachlabs.com/docs/v21.1/sql-tuning-with-explain.html

we want a recipes document that would have small, targeted performance troubleshooting scenarios with actions the user can perform. For example, the user notices a high level of contention in the SQL metrics table in the DB Console. What should they do?

The recommendations must be high-level, as each application and deployment is going to have its own particular steps. The idea is to point the user in the right direction.

Brainstorming document: https://docs.google.com/document/d/1IwYbqdaQ9BYAxWhnQ1KOdYkZ3IX91-dbI7f9NQA5z94/edit?usp=sharing

cc @awoods187 @kevin-v-ngo

**Comment by awoods187** [comment]
I think this is great and we should consider it a p-1 for 21.2 but I'll leave that up to @kevin-v-ngo

**Comment by ianjevans** [comment]
Here's a proposed template for individual recipes.

## Problem: An observed performance issue

A description of the performance issue. This could be error messages, observed application behavior, or performance statistic from the DB Console or querying the system table.

For example:
Problem: The SQL Statement Contention graph in the DB Console is indicating a high amount of contention.

### Possible causes of the problem

A general description of the potential causes of the performance issue. There can be multiple potential causes.

For example: 
Applications are accessing and modifying rows with the same index keys or within the same data range.

### Action(s) to take

Concrete actions the user can take to either fix the problem or more clearly identify where the problem lies.

For example:
Rewrite your statements to make each transaction smaller, so each transaction completes more quickly.
Use index keys with a more random distribution of values to avoid modifying data with the same index key or data range.
Batch statements together in the same transaction so CockroachDB will retry the transactions automatically.
