### ISSUE TITLE
Postgres server version now reports version 13

### ISSUE THREAD

**Issue by wodka** [cockroachdb/docs#10607]
**Describe the problem**

there was no notification that the upgrade to 21.1.0 would now report server_version as 13.0.0

**To Reproduce**

look at server variables.

**Expected behavior**

some clients restrict functionality based on postgre server version. a bump from 9.5 to 13 should at least be noted in the changelog

**Environment:**
 - CockroachDB version 21.1.0

**Additional context**
What was the impact?

not yet known

**Comment by jseldess** [comment]
Documented here: https://www.cockroachlabs.com/docs/v21.1/postgresql-compatibility.html

cc @vy-ton, @ericharmeling, do we need to call this out in the 21.1.0 GA release notes or anywhere else?

**Comment by vy-ton** [comment]
Based on the user feedback, we should go ahead and mention this in the release notes. We tested extensively with different client drivers. @ericharmeling lmk if you need a review

**Comment by ericharmeling** [comment]
> we should go ahead and mention this in the release notes.

Agreed! Opened a fix: https://github.com/cockroachdb/docs/pull/10612
