### ISSUE TITLE
Import data into CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1062]
We should add a page more explicitly documenting the current conventions for getting data into CockroachDB, as well as limitations and future improvements.

- Batches of statements
- From CSV

cc: @dianasaur323

**Comment by sploiselle** [comment]
Should also include #546.

Are you working on this, @jseldess? I have the `COPY FROM` stuff in progress, so I'm glad to take this on if not.

**Comment by jseldess** [comment]
Good point, @sploiselle. I was going to do this quick in next few days, since batch and csv imports are already more or less documented elsewhere. Do you have time to handle `COPY` soon (within next week) without taking away from the script and other topics you're working on? If so, feel free to take. If not, I'll throw up a basic page and you can add `COPY` details later.

**Comment by sploiselle** [comment]
@jseldess I can get this done pretty quickly.

**Comment by jseldess** [comment]
Great! All yours ;)
