### ISSUE TITLE
Unsupported Statement in Interactive Spatial tutorial 

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/docs#10625]
Was trying the interactive spatial tutorial on this page
https://www.cockroachlabs.com/docs/tutorials/spatial-tutorial-interactive

Works well up to step 3, until this statement

```
demo@127.0.0.1:26257/tutorial>  IMPORT PGDUMP ('https://spatial-tutorial.s3.us-east-2.amazonaws.com/bookstores-and-roads-20210125.sql');
ERROR: unsupported statement: ALTER TABLE public.bookstore_routes VALIDATE CONSTRAINT fk_start_store_id_ref_bookstores
HINT: To ignore unsupported statements and log them for review post IMPORT, see the options listed in the docs: https://www.cockroachlabs.com/docs/stable/import.html#import-options

```
and cannot move forward because the table is not imported.

**Comment by rmloveland** [comment]
Thanks for filing @leomkkwan !  Sorry for the inconvenience.

We are working on this via #11718 so I will close this issue - please see #11718 for updates
