### ISSUE TITLE
CockroachCloud onboarding points to old binaries

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#10637]
Hi, I signed up for a free-tier CockroachCloud cluster and was presented with the following modal:

![Screen Shot 2021-05-23 at 9 17 32 AM](https://user-images.githubusercontent.com/60245/119273697-cc82f880-bba7-11eb-96ab-0e1247d38152.png)

All the download commands point to the 20.2 release. The download commands for Mac and Linux are:

`curl https://binaries.cockroachdb.com/cockroach-v20.2.10.darwin-10.9-amd64.tgz | tar -xJ; cp -i cockroach-v20.2.10.darwin-10.9-amd64/cockroach /usr/local/bin/`

`wget -qO- https://binaries.cockroachdb.com/cockroach-v20.2.10.linux-amd64.tgz | tar xvz; cp -i cockroach-v20.2.10.linux-amd64/cockroach /usr/local/bin/`

And the "Install on Windows" link points to `https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-windows`.

Is the 21.1 release not recommended for use with CockroachCloud yet, or are these links just out of date?

**Comment by rolandcrosby** [comment]
oh, I guess this is because the latest stable version of CockroachDB isn't available in CockroachCloud yet, or at least not in the free tier. That's kinda confusing, since [the "get started" page](https://www.cockroachlabs.com/get-started-cockroachdb/) specifically says "Get Started with CockroachDB 21.1 Today".

**Comment by emily-horing** [comment]
Thanks for filing this issue Roland! CockroachCloud Free beta doesn't yet use v21.1 but this will become the default and all free clusters updated very soon. We do support v21.1 on the paid tier today, if you're looking to test out new features. That said, I've created an issue to update the binary download commands to align with the latest release.

**Comment by jseldess** [comment]
Thanks, Emily. Closing this issue since the updates should be on the CC side.
