### ISSUE TITLE
release-21.1: timeutil: better error reporting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10645]
PR: https://github.com/cockroachdb/cockroach/pull/63540

From release notes:
> The error payload returned to the client when a [`DATE`](../v21.1/date.html)/[`TIME`](../v21.1/time.html) conversion fails now contains more details about the difference between the values provided and the values that are expected. [#63540][#63540] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
IDK if this needs explicit documentation. It looks like a simple bug fix (see the original issue: https://github.com/cockroachdb/cockroach/issues/63250).
