### ISSUE TITLE
release-21.1: sql/opt: use maximally selective constant filter for lookup joins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10653]
PR: https://github.com/cockroachdb/cockroach/pull/65361

From release notes:
> [Lookup joins](../v21.1/joins.html) on indexes with [computed columns](../v21.1/computed-columns.html) which are also either constrained by [`CHECK`](../v21.1/check.html) constraints or use an [`ENUM`](../v21.1/enum.html) data type may now choose a more optimal plan. [#65361][#65361] {% comment %}doc{% endcomment %}

**Comment by ianjevans** [comment]
This change affects how the optimizer chooses plans under certain conditions, which we cover generally but not specifically in our docs. Closing.
