### ISSUE TITLE
How to log queries for debugging

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1066]
Asked in Gitter.

Answer: Start the server with `--vmodule=executor=2` (log all queries) or set the env var `COCKROACH_TRACE_SQL` to a duration to log all queries longer than that duration.

The `--vmodule` logging flag is currently undocumented.

**Comment by jseldess** [comment]
Decided to leave `cockroach debug` and debugging logging flags undocumented for now.

**Comment by bdarnell** [comment]
We probably don't want do document *these* options, but we should add a new option for logging queries that we can document (maybe a setting in some system configuration table instead of something to be set on each node at startup)

**Comment by jseldess** [comment]
@bdarnell , that makes sense. Do we have a cockroach issue for that work yet, or should I create one?

**Comment by bdarnell** [comment]
I don't see an open issue for query logging. If we want to use a system settings table for this, that's tracked in cockroachdb/cockroach#9304.

**Comment by jseldess** [comment]
Related to #1197

**Comment by jseldess** [comment]
Can now also use a cluster setting to log sql queries: 

`SET CLUSTER SETTING sql.trace.log_statement_execute = true`
