### ISSUE TITLE
release-21.1: cli/sql: properly format different times and floats

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10662]
PR: https://github.com/cockroachdb/cockroach/pull/63541

From release notes:
> The SQL shell (`cockroach demo`, [`cockroach sql`](../v21.1/cockroach-sql.html)) now attempts to better format values that are akin to time/date values, as well as floating-point numbers. [#63541][#63541] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Hmm ... does this commit need to be explicitly documented? Looks like a bug fix (see https://github.com/cockroachdb/cockroach/issues/29044).
