### ISSUE TITLE
release-21.1: ui: use uPlot lib for line graphs on metrics page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10669]
PR: https://github.com/cockroachdb/cockroach/pull/64479

From release notes:
> Placed a legend under charts on [metrics page](../v21.1/ui-overview-dashboard.html), if more than 10 series are being displayed [#64479][#64479] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing; doesn't need docs.
