### ISSUE TITLE
Add a "copy to clipboard" button

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1070]
To make it easier/faster to run our sample commands and code, we should have an option to add a "copy to clipboard" feature to a code block. 

This needs to be an option (not universally applied to all code blocks) because some blocks don't warrant copy/past (command responses), and other blocks will need to be edited to work meaningfully with copy/paste (e.g., multiple sql commands in a single block will need to be split into separate blocks).

**Comment by jseldess** [comment]
How other sites do it:

# Django

Django provides a copy to clipboard feature only for entire files:

![screen shot 2017-06-07 at 10 34 04 am](https://user-images.githubusercontent.com/15893490/26884135-0955b84c-4b6d-11e7-8022-f61c82d7c2b8.png)

Not for individual commands:

![screen shot 2017-06-07 at 10 35 54 am](https://user-images.githubusercontent.com/15893490/26884170-21673604-4b6d-11e7-9e4c-7f4a90305f9d.png)

# Google SDK

Google dev docs provide a copy to clipboard feature (shows up on hover) for individual commands:

![screen shot 2017-06-07 at 10 41 36 am](https://user-images.githubusercontent.com/15893490/26884549-05d643ac-4b6e-11e7-847f-0c6765cafc22.png)

Probably also for entire files, but I can't find any examples of that at the moment.

# Kubernetes

Kubernetes docs provide a copy to clipboard feature for entire files:

![screen shot 2017-06-07 at 10 47 13 am](https://user-images.githubusercontent.com/15893490/26884833-c00a129e-4b6e-11e7-9431-e3f9ba8e3f83.png)

But not for individual commands.

**Comment by jseldess** [comment]
@kuanluo, examples of where we could use this feature in our docs:

## Single CLI command

[Start a Local Cluster](https://www.cockroachlabs.com/docs/start-a-local-cluster.html#step-1-start-the-first-node):

![screen shot 2017-06-07 at 1 26 35 pm](https://user-images.githubusercontent.com/15893490/26892062-11c08332-4b85-11e7-85eb-7957c0b30716.png)

## Single SQL command

[`CREATE VIEW`](https://www.cockroachlabs.com/docs/create-view.html#example):

![screen shot 2017-06-07 at 1 30 27 pm](https://user-images.githubusercontent.com/15893490/26892208-8d0928c8-4b85-11e7-929b-7a2682505d23.png)

## Entire file

[Build a Go App](https://www.cockroachlabs.com/docs/build-a-go-app-with-cockroachdb.html#basic-statements):

![screen shot 2017-06-07 at 1 29 14 pm](https://user-images.githubusercontent.com/15893490/26892136-513059e8-4b85-11e7-9791-dc827fa95f52.png)

**Comment by jseldess** [comment]
@kuanluo, assigning this over to you for design. Once you're ready, we can pass it over to Division Of.

**Comment by kuanluo** [comment]
@jseldess, I am going to assign directly to division of. Might be the best way to get this done, looking at my schedule for next week!

**Comment by jseldess** [comment]
OK, if you like, I'm happy to write up the task in Assana directly and cc you?

**Comment by jseldess** [comment]
OH, I see you created one already. Nevermind ;)

**Comment by kuanluo** [comment]
I took care of it. :)

**Comment by deronjohnson** [comment]
@jseldess 

I'm currently working on implementing this. The clipboard functionality itself is fairly simple, but I'm running into an issue regarding the markup of the code samples. For this to work, we need to add markup into the generated code snippet html. It seems that all code samples get converted into markup wrapped in a div with class "highlighted", but I can't seem to find that markup anywhere in the repository.

**Comment by jseldess** [comment]
Closed by https://github.com/cockroachdb/docs/pull/1624.
