### ISSUE TITLE
release-21.1: sql/table: returns notice when table already exist in case of CREATE TABLE IF NOT EXISTS

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10744]
PR: https://github.com/cockroachdb/cockroach/pull/65636

From release notes:
> CockroachDB now returns a SQL Notice if a [`CREATE TABLE IF NOT EXISTS`](../v21.1/create-table.html) command is used to create a `TABLE` and the `TABLE` already exists. [#65636][#65636] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is just a notice - no behavior has changed.
