### ISSUE TITLE
release-21.1: Add internal tables for detecting lost table data and clearing it

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10742]
PR: https://github.com/cockroachdb/cockroach/pull/65462

From release notes:
> Added the `crdb_internal.force_delete_table_data` [cluster setting](../v21.1/cluster-settings.html) which allows table data to be cleaned up only using a descriptor ID for cases of table descriptor corruption. [#65462][#65462] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Not sure we need to document this explicitly. The included cluster settings should capture the new setting.
