### ISSUE TITLE
release-21.1: backport crdb_internal.reset_sql_stats

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10748]
PR: https://github.com/cockroachdb/cockroach/pull/65674

From release notes:
> SQL stats can now be cleared using the `crdb_internal.reset_sql_stats()` function. [#65674][#65674] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we should document this explicitly. The included functions should cover it for reference.

In general, it's probably a good idea to not explicitly document `crdb_internal` functions (though we do so on a few select pages in the docs). I am under the impression that `crdb_internal` functions are relatively experimental.
