### ISSUE TITLE
release-21.1: changefeedccl: Treat memory monitor errors as retryable.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10740]
PR: https://github.com/cockroachdb/cockroach/pull/65387

From release notes:
> [Changefeeds](../v21.1/create-changefeed.html) now better handle slow or unavailable sinks by treating "memory exceeded" errors as retryable. [#65387][#65387] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
I don't think we need to document this change outright - something we might want to do is add details around retryable errors and what the right monitoring we want to put in place is, but we're doing a larger rethink of this during this release and can document it when needed
