### ISSUE TITLE
release-21.1: sql: return a SQL Notice if "CREATE TYPE IF NOT EXISTS" command is used to create a type and the type's already existed.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10746]
PR: https://github.com/cockroachdb/cockroach/pull/65635

From release notes:
> CockroachDB now returns a SQL Notice if a [`CREATE TYPE IF NOT EXISTS`](../v21.1/create-type.html) command is used to create a type and the type already exists. [#65635][#65635] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is just a notice - no behavior has changed.
