### ISSUE TITLE
release-21.1: Add internal tables for detecting lost table data and clearing it

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10741]
PR: https://github.com/cockroachdb/cockroach/pull/65462

From release notes:
> Added the `crdb_internal.lost_descriptors_with_data` [cluster setting](../v21.1/cluster-settings.html) to show descriptors that have no entries but data left behind. [#65462][#65462] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Not sure we need to document this explicitly. The cluster setting includes should capture it.
