### ISSUE TITLE
release-21.1: importccl: add `chunk_size` option to EXPORT CSV

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10747]
PR: https://github.com/cockroachdb/cockroach/pull/65388

From release notes:
> Added a `chunk_size` option to [`EXPORT INTO CSV`](../v21.1/export.html) to control the target CSV file size. [#65388][#65388] {% comment %}doc{% endcomment %}

**Comment by adityamaru** [comment]
I don't think we actually added the `chunk_size` option to the 21.1 docs? @kathancox
