### ISSUE TITLE
sql: document how to setup and use geoserver

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#10763]
We should document how to setup and use geoserver with CockroachDB.

Also, corresponds to these release issues:
https://github.com/cockroachdb/docs/issues/10652
https://github.com/cockroachdb/docs/issues/10651
https://github.com/cockroachdb/docs/issues/10650
https://github.com/cockroachdb/docs/issues/10649

**Comment by awoods187** [comment]
Additional example https://docs.google.com/document/d/1qwhduZ6bVlGceBPMq3XlbuKfORr2fqv9DmRFBDOuBrs/edit?ts=60c216ad#

**Comment by rmloveland** [comment]
Andy we have some docs up here: https://www.cockroachlabs.com/docs/v21.1/geoserver.html 

unfortunately I wrote them before seeing MGoddard's stuff so there may be some follow-up work but at least #itssomething

**Comment by awoods187** [comment]
this should work for now--thanks Rich. We can add to it in the future.
