### ISSUE TITLE
Update security overview page with SOC2 certification and other changes

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#10773]
The page "Cockroach Labs Security Overview" at https://www.cockroachlabs.com/security/ was last updated Jan. 8, 2021.  It does not mention some important changes since then, notably that CockroachCloud is officially SOC 2 Type I and Type II compliant.

This is such a broad document that an overall review with input from multiple teams may be appropriate.

**Comment by adbrenn** [comment]
We have a Jira issue to track this as it is part of a larger marketing update. @hand-crdb I tagged you on the Jira ticket and added these comments. https://cockroachlabs.atlassian.net/browse/COMP-305

**Comment by adbrenn** [comment]
Closing as this is not related to docs work.
