### ISSUE TITLE
bulk: update Free Tier docs for Bulk I/O

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#10799]
BACKUP, RESTORE, IMPORT and Core Changefeeds should now be mentioned as available in Free Tier

(_Note: this is contingent on free tier clusters being upgraded to 21.1_)
(_Note: EXPORT is NOT supported and therefore is specifically not mentioned here. We chose not to implement because running `cockroach sql "query" > file.csv` is a more direct way to export your data_)

The major caveats are:
* You can only use `userfile` as file storage for BACKUP, RESTORE and IMPORT -- you cannot use http, s3, etc. (This does not apply to Core Changefeeds because that writes to the SQL connection rather than file storage)
* We should note that `userfile` takes up space and that you should ensure you have enough space to both load the file and take whatever action you want to take. We could say 1GB as a safe limit maybe for first IMPORT?
* We probably want to note that even if you `cockroach userfile delete 'file'` that it takes gc.ttl to be removed from disk. Right now that's 25h but we're having conversations to lower that.
* We can also suggest database and/or table level backups because cluster level backups would take backups of the `userfile` stuff too (since it's technically table data).
* (NOTE: I actually think that you cannot do cluster restore, because you have to first load data into `userfile` first. Ugh. It's not a great experience because it doesn't fail saying you can't, it'll fail with another error. So we probably should explicitly say that you can't on Free Tier, and maybe in a troubleshooting section explain the error as well)

**Comment by ianjevans** [comment]
@mwang1026 I'd like to clarify some things here regarding the doc work, specifically regarding `userfile` as a `BACKUP`/`RESTORE` destination.

We don't currently document `userfile` URLs as a valid target for `BACKUP`/`RESTORE` operations in CRDB:
https://www.cockroachlabs.com/docs/v21.1/backup#backup-file-urls
https://www.cockroachlabs.com/docs/v21.1/restore#backup-file-urls

The `userfile` topic appears to be distinct from cloud and local file destinations, and only references `IMPORT`:
https://www.cockroachlabs.com/docs/v21.1/use-userfile-for-bulk-operations.html

Is this a hole in the CRDB docs? If so, it sounds like @kathancox should first update the CRDB docs with this information so we can consume it in the Cloud documentation for the Serverless MVP launch.

**Comment by ianjevans** [comment]
The same situation applies to changefeeds. We don't document how they work with `userfile` URLs.
https://www.cockroachlabs.com/docs/v21.1/create-changefeed.html

**Comment by mwang1026** [comment]
OK. We can document them, with the caveat that it is not recommended for production usage outside of free tier.

I'd also argue that we don't have examples of how it works, but it is "just another file storage" option. But I agree for completeness it's worth having an end-to-end example somewhere of how you
- upload your backup to `userfile` from local
- then run restore off of it
- then delete that file from `userfile` once you're done with it

When speaking with Kathryn it was unclear whether that lives in CRDB or in CC. I didn't have a particular preference
