### ISSUE TITLE
release-21.1: changefeedccl: allow user to configure kafka server version

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10823]
PR: https://github.com/cockroachdb/cockroach/pull/66314

From release notes:
> The `kafka_sink_config` object now supports a `version` configuration item to specify Kafka server versions. This is likely only necessary for old (Kafka 0.11/Confluent 3.3 or earlier) Kafka servers. Additionally, settings not specified in `kafka_sink_config` now retain their default values. [#66314][#66314] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
This has been covered in the following docs: https://www.cockroachlabs.com/docs/v21.1/create-changefeed#kafka-sink-configuration
