### ISSUE TITLE
release-21.1: docs, server: various generated doc updates

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10827]
PR: https://github.com/cockroachdb/cockroach/pull/66128

From release notes:
> The description string for the `random()` function now clarifies that there are at most 53 bits of randomness available; that is, the function is unsuitable to generate 64-bit random integer values. This behavior is similar to that of PostgreSQL. [#66128][#66128] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as this update appears in the generated doc.
