### ISSUE TITLE
Evaluate Foreign Keys video and blog post to link/embed as appropriate in Foreign Key Constraint doc

### ISSUE THREAD

**Issue by mikeCRL** [cockroachdb/docs#10859]
The CRL Marketing team [has published](https://github.com/cockroachdb/docs/issues/10859#issuecomment-872371773) a [blog post](https://www.cockroachlabs.com/blog/what-is-a-foreign-key/) and a [video](https://youtu.be/5kiMg7GXAsY) about foreign keys.

* Review each. The subsequent steps assume that the new content will be useful to a significant number of readers who initially land on the Foreign Key Constraint doc https://www.cockroachlabs.com/docs/stable/foreign-key.html
* Embed the video at https://www.cockroachlabs.com/docs/stable/foreign-key.html (just as we've done with another video on https://www.cockroachlabs.com/docs/stable/follower-reads.html)
* Find a good place within https://www.cockroachlabs.com/docs/stable/foreign-key.html to link to the blog post, for readers who may be interested in this additional information.
* If there's info in the blog post that we should consider bringing in to the docs, please create another issue for this.

**Comment by dankellycockroach** [comment]
@mikeCRL here is the video embed code:

<iframe width="560" height="315" src="https://www.youtube.com/embed/5kiMg7GXAsY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Also, for SEO purposes, it would be great if you could link to [this new blog](https://www.cockroachlabs.com/blog/what-is-a-foreign-key/) that essentially defines what a foreign key is.
