### ISSUE TITLE
blog: blog CSS is heavily broken

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1085]
- images with attribute "aligncenter" are not properly centered.
- links are always non-bold even when included in `<b> ... </b>`
- links are always large even when included in `<small> ... </small>`
- a paragraph starting in a list with `<li><p>.... </p></li>` cause the bullet point to be mis-aligned.

I can't claim I can make our blog look good, and this is definitely not my area of competence, but FWIW I've been taught my HTML 101 classes that avoiding these specific issues is really part of the basic skillset of any CSS author. I would strongly suggest either we place the CSS entire our control (perhaps in a repo) and start fixing things ourselves, or consider a different business partner to get this done properly for us.

**Comment by jseldess** [comment]
@knz, the docs repo doesn't encompass the blog, so this is the wrong place to report this. I'll move your issue to the correct repo and cc you. But for what it's worth, @mjibson is right now in the process of migrating the website (non-docs), including the blog, off of wordpress, entirely into a github repo, so we'll have full control of all content and assets.
