### ISSUE TITLE
Configure logs Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#10858]
Re: [Configure logs](https://cockroachlabs.com/docs/v21.1/configure-logs.html)

## Issue Description

There's a code formatting problem:
![image](https://user-images.githubusercontent.com/642886/123861623-b0514480-d927-11eb-9b4d-5e6a08410a28.png)

## Suggested Resolution 
unsure

**Comment by taroface** [comment]
This has been fixed already! Closing.
