### ISSUE TITLE
create docs on draining behavior

### ISSUE THREAD

**Issue by otan** [cockroachdb/docs#10866]
Oliver Tan (otan) commented:

See also: https://github.com/cockroachdb/cockroach/issues/67071

Draining is a very difficult dance that requires specific settings to result in 0 availability blips. We should document the behaviour as appropriate.

[Doc with more context.](https://docs.google.com/document/d/1oOQ4pnTxEdUPA69qlK5NLCk0C-RldIJeXdlcY1HE3nY/edit#)

Jira Issue: DOC-1524

**Comment by ianjevans** [comment]
I think there are two tasks here.

1. Document the correct draining procedure and settings for rolling upgrades.
2. Link to that doc from the connection pooling topic with the recommendations from the linked doc below.

### Recommendations
To use connection pools and recycle CockroachDB nodes without availability hits, the current mitigation available for a DBA would be to:

- Set the cluster setting `server.shutdown.drain_wait` to be at least 40s.
- Set the connection pool's maximum time to be 30s less than the drain time. The 30s should be changed to be the estimate of the longest acceptable transaction time.

In general, a non-availability drain should have:
connection pool max time + max txn latency < server.shutdown.drain_wait

This does mean that connections get re-established more frequently and thus more overhead for certain calls on some infrequent basis, but I don't imagine this to be unbearable.

In the CockroachCloud case, there is 5 minutes from SIGTERM (when drain starts) to SIGKILL (when the server is force terminated). Thus:

- Set `drain_wait` to 3 minutes (allow 2 minutes for `query_wait` to move leases).
- Set HikariCP max time to (3 minutes - min(30s, `longest_transaction_duration`)).
