### ISSUE TITLE
Add Note that deleting cluster stops billing

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#10861]
Zendesk ticket: https://cockroachdb.zendesk.com/agent/tickets/8647

Summarize the improvement needed: 
https://www.cockroachlabs.com/docs/cockroachcloud/cluster-management.html#delete-cluster
Add a note:
> With a paid CockroachCloud cluster, you will only be billed for when the cluster is running -- even if it is only for a few hours. Please delete the cluster when you are done to stop the billing.

**Comment by lnhsingh** [comment]
Closing this issue in lieu of: https://cockroachlabs.atlassian.net/browse/CC-5009
