### ISSUE TITLE
Free tier FAQ around cluster versions

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#10860]
A free tier user reached out asking when a newer version of CRDB will roll out to free tier.

It's not clear according to our version policy on the CC docs what version the server is running (or when it might get upgraded).

I think we can benefit from a FAQ answering what version Free Tier will ship with / when we will roll out new minor / major versions to free tier. 

I started with pointing them to https://www.cockroachlabs.com/docs/cockroachcloud/upgrade-policy but there wasn't enough information.

**Comment by lnhsingh** [comment]
Closing this issue in lieu of https://cockroachlabs.atlassian.net/browse/CC-5009
