### ISSUE TITLE
Column Families Doc Update

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#10870]
Steven Hand (hand-crdb) commented:

Re: [Column Families](https://cockroachlabs.com/docs/v21.1/column-families.html)

## Issue Description

This page should describe, or point to a description, of limitations associated with column families; specifically that CDC does not work with tables that have more than one column family.

## Suggested Resolution 

Describe, or provide a link to a description of, imitations associated with column families; specifically that CDC does not work with tables that have more than one column family.

Ref: https://www.cockroachlabs.com/docs/stable/known-limitations.html#change-data-capture

Jira Issue: DOC-1520

**Comment by oliverhausler** [comment]
The document should also explain what happens when a family is only defined for part of the columns. Will the remaining columns revert to the default family?
