### ISSUE TITLE
Document new webhook sink 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#10876]
For the webhook sink, this doc includes documentation details: https://docs.google.com/document/d/14rgvDtVgIudmbFwCXRgRrgXFSyr5m8qY5Mr5zeoMYz0/edit

**Comment by mwang1026** [comment]
https://cockroachlabs.atlassian.net/browse/CRDB-7748

**Comment by kathancox** [comment]
cc @mikeCRL
