### ISSUE TITLE
sql: Postgres comparison page

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1088]
Potential comparisons:
  - Glossary/translation of technical terms
  - Overlap/limitation in features incl. workarounds
  - SQL translation incl. how to structure SQL differently given different storage engines

**Comment by jseldess** [comment]
For second bullet, heroic was particularly interested in knowing with differences were by design and which were known limitations that would eventually be resolved.

**Comment by jseldess** [comment]
The heart of this is covered in https://github.com/cockroachdb/docs/issues/2467.
