### ISSUE TITLE
Update Avro Limitations and types

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#10881]
The avro limitations section of the changefeed docs is out of date: https://www.cockroachlabs.com/docs/stable/create-changefeed.html#avro-limitations is out of date, especially since we're introducing new avro format support in 21.2 (everything is backported to 21.1 besides changes in decimals, so we should include these doc updates for those as well)

- Decimals must have precision specified. (still true - we may later update this) 
- Decimals with NaN or infinite values cannot be written in Avro (no longer applies - they are now written in string)
- TIME, DATE, INTERVAL, UUID, INET, ARRAY, JSONB, BIT, and collated STRING are not supported in Avro yet- we've added support for all of these so we should take this out ( For TIME, DATE, UUID, INET, JSONB - these are available at least in 20.2 so we should take them out of the list in earlier versions)
- Bit limitations - see https://github.com/cockroachdb/cockroach/pull/65869 

Updates to the Avro Types section:
- CockroachDB Type: Decimals, Avro Type: String, Bytes, Avro Logical Type: Decimal 
- CockroachDB Type: ENUMs (encoded as strings https://github.com/cockroachdb/cockroach/pull/65474)
- CockroachDB Type: Interval , Avro Type:  String
- CockroachDB Type: Array , Avro Type:  Array
- CockroachDB Type: Bit , Avro Type:  Array of LONGS
- CockroachDB Type: VarBit , Avro Type:  Array of LONGS
- CockroachDB Type: Collated String, Avro Type:  String

Add callout that Decimal type is a union between string and avro decimal type 

For Bit and Varbit encoding, we should call out some nuances and give an example of the format (example in this PR https://github.com/cockroachdb/cockroach/pull/65869): We encode BIT and VARBIT as arrays of 64-bit integers for efficiency. Since our encoding is big-endian, the last value may have many trailing zeroes. For this reason, the first value of each array gives the number of bits that are used in the last value. For example, if the bitfield is 65 bits long, this will be encoded into an array that looks like [1, <first 64 bits>, either 0 or the 64-bit integer with only the first bit set]. So you would first take every element in the array besides the first and base 2 encode it. Then you would look at the first number, which gives you the number of bits to take from the last base 2 encoded number. Then you would append all the base 2 encoded numbers together (with the caveat that the last item is truncated).

Example:
{sqlType: `VARBIT`, sql: `B'010'`, avro: `{"array":[3,4611686018427387904]}`}, // Take the 3 most significant bits of 1<<62

So first we base 2 encode '4611686018427387904', which encodes to: '0100000000000000000000000000000000000000000000000000000000000000' in 64 bits

We then take the first three bits: '010', which gives us our bit value

-------
Additionally, we are removing the experimental tag from avro, so we should change experimental-avro to just avro in the docs

**Comment by amruss** [comment]
https://cockroachlabs.atlassian.net/browse/CRDB-2606

**Comment by amruss** [comment]
https://github.com/cockroachdb/cockroach/pull/67433

**Comment by amruss** [comment]
Acceptance Testing for reference: https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/2132051191/CDC+21.2+Acceptance+Testing+Full+Avro+Support

**Comment by amruss** [comment]
As of last week, we've also taken off the 'experimental' tag from the avro format (since we now fully support it) - we should change 'experimental-avro' examples to 'avro' in the docs as well, should that be a different issue or a part of this?

**Comment by kathancox** [comment]
cc @mikeCRL
