### ISSUE TITLE
sql: correct the note about NULLS FIRST/LAST support

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/docs#10914]
Yahor Yuzefovich (yuzefovich) commented:

In https://github.com/cockroachdb/docs/pull/6766 we added an incorrect documentation of our "syntax-only" support of NULLS FIRST | LAST modifiers of ORDER BY. On https://www.cockroachlabs.com/docs/v21.1/order-by.html#parameters we say that we won't error out on cases that we don't support which is incorrect.

Here is an example that captures the current state of things (applicable to all releases I believe):
```
root@127.0.0.1:26257/defaultdb> CREATE TABLE t (a INT, INDEX index_asc(a ASC), INDEX index_desc (a DESC));
CREATE TABLE


Time: 3ms total (execution 3ms / network 0ms)

root@127.0.0.1:26257/defaultdb> SELECT * FROM t@index_asc ORDER BY a ASC NULLS FIRST;
  a
-----
(0 rows)


Time: 4ms total (execution 4ms / network 0ms)

root@127.0.0.1:26257/defaultdb> SELECT * FROM t@index_asc ORDER BY a ASC NULLS LAST;
invalid syntax: statement ignored: at or near "last": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
SELECT * FROM t@index_asc ORDER BY a ASC NULLS LAST
                                               ^
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/6224/v21.2
root@127.0.0.1:26257/defaultdb> SELECT * FROM t@index_desc ORDER BY a DESC NULLS LAST;
  a
-----
(0 rows)


Time: 1ms total (execution 1ms / network 0ms)

root@127.0.0.1:26257/defaultdb> SELECT * FROM t@index_desc ORDER BY a DESC NULLS FIRST;
invalid syntax: statement ignored: at or near "first": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
SELECT * FROM t@index_desc ORDER BY a DESC NULLS FIRST
                                                 ^
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/6224/v21.2
```
So we error out in cases which we don't support instead of silently ignoring the modifier. cc @ericharmeling 

Jira Issue: DOC-1507

**Comment by yuzefovich** [comment]
As Rafi eloquently put it, we can do `ORDER BY DESC … NULLS LAST` or `ORDER BY ASC … NULLS FIRST` (and `ASC` is the default order). This page could be improved a bit too: https://www.cockroachlabs.com/docs/stable/null-handling.html#nulls-and-sorting.

**Comment by rafiss** [comment]
As per the comments in https://github.com/cockroachdb/cockroach/issues/6224, a workaround is to use an expression like `CASE WHEN x IS NULL THEN 1 ELSE 0 END` to achieve whatever order you want. e.g.

```
SELECT * FROM t@index_asc ORDER BY CASE WHEN x IS NULL THEN 1 ELSE 0 END ASC, a ASC;

SELECT * FROM t@index_asc ORDER BY CASE WHEN x IS NULL THEN 1 ELSE 0 END DESC, a DESC;
```

**Comment by rafiss** [comment]
simpler workarounds:

```
SELECT * FROM t@index_asc ORDER BY (a IS NULL) ASC, a ASC;

SELECT * FROM t@index_desc ORDER BY (a IS NULL) DESC, a DESC;
```
