### ISSUE TITLE
Document why a dead/disconnected node means you can not create new connections on other nodes for a while

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#10921]
As explained by @rafiss in #10913:

> A major motivation for this docs request was a report from a customer who observed a long period of inability to create any new connections to any node in the cluster when one other node was forcefully terminated and black-holed. It was actually easy to reproduce reliably. Note that the system ranges are also very early in the keyspace. During authentication user/password information needs to be looked from a system range. So if that system range is colocated with the liveness range, it made the period of inability-to-connect last longer.

So there are at least the following pieces of work:

1. We need docs (probably in [Troubleshoot Cluster > Authentication issues](https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#cockroachdb-authentication-issues)) about what it means when this happens, with a link to ...

2. An update to the [Replication Layer docs]() that at least mentions this behavior and how it is linked to the fact that liveness range and the range holding user/pass auth info are nearby - with links back over to the troubleshooting docs for findability

Did not want to do this directly in #10917 since it's a slightly different ask than "describe how leases are transferred when a node dies" and as such would make writing a coherent PR harder if it was smushed in that one.

See also:

- #5470
- #10913

**Comment by rmloveland** [comment]
cc @mwang1026 FYI - breaking this task out of #10913 since it's a little different (see issue description for details)

**Comment by rafiss** [comment]
Here's a bit more background:

- https://github.com/cockroachlabs/support/issues/1022 is a support issue covering this topic.
- In 21.2, https://github.com/cockroachdb/cockroach/pull/66919 will address the great majority of instances of "app not being able to connect after the system leaseholder goes down."
- we are writing a test that reproduced the issue https://github.com/cockroachdb/cockroach/pull/66768 - with the change above the test doesn't encounter the issue. but the "no new connections" symptom can still happen if the cache doesn't have what it needs.
