### ISSUE TITLE
Document memory budget cluster setting

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#10939]
Also backported to 21.1

changefeed.memory.per_changefeed_limit: This cluster setting gives our internal memory buffers more room to work with during times of heavy traffic or when the sink is unreachable. Default value is 1GB. Increasing may lead to more changefeed memory usage overall

**Comment by amruss** [comment]
https://cockroachlabs.atlassian.net/browse/CRDB-6788

**Comment by kathancox** [comment]
Hey @amruss, this cluster setting is not a public setting. Settings generated for docs on the [cluster settings page](https://www.cockroachlabs.com/docs/v21.1/cluster-settings) are all public — won't destabilize the cluster. What do you think in terms of documenting vs. not documenting this setting?
