### ISSUE TITLE
Document SHOW CHANGEFEED JOBS

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#10934]
In 21.2 we added an observability tool: SHOW CHANGEFEED JOBS which isolates changefeed jobs and outputs information about all changefeed jobs in the jobs table.

Syntax: `SHOW CHANGEFEED JOBS;`
See acceptance testing for example outputs - the output is similar to `SHOW JOB job_id` for a changefeed job, with the sink URIs redacted and full table names added. 

Ticket: https://cockroachlabs.atlassian.net/browse/CRDB-1419 
Acceptance Testing: https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/2150432932/CDC+21.2+Acceptance+Testing+SHOW+Changefeed+Job

**Comment by kathancox** [comment]
cc @mikeCRL
