### ISSUE TITLE
Document CLI for job debug trace

### ISSUE THREAD

**Issue by livlobo** [cockroachdb/docs#10943]
https://cockroachlabs.atlassian.net/browse/CRDB-7076

**Comment by kathancox** [comment]
As a note @livlobo and I discussed that the majority of `debug` commands are for internal use as [mentioned in a section on each external-facing debug command](https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html#subcommands) in the docs. It seems like `debug trace` could be useful on the support side, but maybe not externally? Thinking about this in comparison to the `cockroach debug backup [subcommand]` cli tool (PR here #11841)

**Comment by kathancox** [comment]
https://github.com/cockroachdb/cockroach/pull/65324
