### ISSUE TITLE
Provide recommended in-mem store parameters for local application unit testing

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/docs#10991]
Rafi Shamim (rafiss) commented:

We have been receiving a lot of questions about how to make CockroachDB faster when it is used for testing locally. The performance issues can often be tracked down to being disk I/O bound.

I'm not sure where this would fit in, but perhaps as part of our developer guide (or somewhere else), we should give our recommendation to use startup params like this:

```
 ./cockroach start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost
```

This results in logs going to the console. If the user wants logs to go to a file, then:
```
 ./cockroach start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost --log="{file-defaults: {dir: /path/to/logs}, sinks: {stderr: {filter: NONE}}}"
```

cc @vy-ton : do we also need guidance on how to use an enterprise license when testing like this?

**Comment by vy-ton** [comment]
Enterprise license has surfaced a few times. 

@piyush-singh if you have the guidance ready, we could fold it into this docs issue?
