### ISSUE TITLE
sql: add docs for using multi-region TPC-C

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#11011]
Andy Woods (awoods187) commented:

In 21.2 we've added a configuration option for multi-region tpc-c. We should document this in a public-facing way for others to use testing with CockroachCloud and CockroachDB. In addition, we will likely backport the workload change to 21.1.X. 

https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/2095349891/Run+TPC-C+with+roachprod

**Comment by awoods187** [comment]
Backport issue (https://github.com/cockroachdb/cockroach/issues/68472)

**Comment by rmloveland** [comment]
Hey @otan ! Is this in v21.1.7?  Or will it be a later v21.1 release?  Not sure how to check.

**Comment by rmloveland** [comment]
FWIW here's what i did today

using cockroachdb v21.1.7

spun up a simulated multiregion cluster using [these instructions](http://localhost:4000/docs/dev/simulate-a-multi-region-cluster-on-localhost.html) (`cockroach demo`)

then pointed workload at it as follows:

    cockroach workload init tpcc --drop --warehouses=30 --partitions=9 'postgres://root@127.0.0.1:26257?sslmode=disable'

it ran for a while and then failed with something about a "rack" zone config missing:

    I210811 15:58:47.795668 1 workload/workloadsql/dataload.go:146  [-] 1  imported warehouse (0s, 30 rows)
    I210811 15:58:47.816535 1 workload/workloadsql/dataload.go:146  [-] 2  imported district (0s, 300 rows)
    I210811 15:59:50.816166 1 workload/workloadsql/dataload.go:146  [-] 3  imported customer (1m3s, 900000 rows)
    I210811 16:00:06.538773 1 workload/workloadsql/dataload.go:146  [-] 4  imported history (16s, 900000 rows)
    I210811 16:00:39.370224 1 workload/workloadsql/dataload.go:146  [-] 5  imported order (33s, 900000 rows)
    I210811 16:00:41.248777 1 workload/workloadsql/dataload.go:146  [-] 6  imported new_order (2s, 270000 rows)
    I210811 16:00:45.819716 1 workload/workloadsql/dataload.go:146  [-] 7  imported item (5s, 100000 rows)
    I210811 16:02:30.157343 1 workload/workloadsql/dataload.go:146  [-] 8  imported stock (1m44s, 3000000 rows)
    I210811 16:06:01.653069 1 workload/workloadsql/dataload.go:146  [-] 9  imported order_line (3m31s, 9002592 rows)
    Error: Could not postload: could not partition tables: Couldn't exec "ALTER PARTITION p0_0 OF TABLE warehouse CONFIGURE ZONE USING constraints = '[+rack=0]'": pq: constraint "+rack=0" matches no existing nodes within the cluster - did you enter it correctly?

**Comment by otan** [comment]
it should be available in v21.1.8

you'll want to run it with https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/2095349891/Run+TPC-C+with+roachprod - note regions have to be specified.

**Comment by awoods187** [comment]
September is fine--we can wait for it to be released. Note, its the same process for 21.2 though so I think we could merge it in the beta docs and then backport the doc for 21.1. That being said, I think #11017 is the priority

**Comment by ajstorm** [comment]
Hey @rmloveland.  Just a heads-up that I've updated the instructions on how to run MR tpc-c but they'll only work properly with #70121.  That PR is in 21.2 now, and I'm backporting it to 21.1 as I type this.

**Comment by awoods187** [comment]
cc @holtrdan

**Comment by ajstorm** [comment]
Multi-tenant may be tripping you up.  Can you try again with:

cockroach demo --global --nodes 9 --no-example-database --insecure
--multitenant=false
