### ISSUE TITLE
Remove recommendations to use `crdb_internal.mvcc_timestamp` in favor of `ON UPDATE`

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#11028]
Once we support [ON UPDATE](https://github.com/cockroachdb/cockroach/issues/28281) in hopefully 21.2, we should remove recommendations to use `crdb_internal.mvcc_timestamp` in favor of an `ON UPDATE` example.

Pages:

- https://www.cockroachlabs.com/docs/v21.1/bulk-delete-data.html#batch-delete-expired-data

**Comment by mwang1026** [comment]
The latter is a *must* if we keep it around.

I *think* it'd be abrupt to remove it, if people rely on it, so I say we keep it for now with the major caveat
