### ISSUE TITLE
ALTER PRIMARY KEY Doc Update 

### ISSUE THREAD

**Issue by electrum** [cockroachdb/docs#11034]
Re: [ALTER PRIMARY KEY](https://cockroachlabs.com/docs/v21.1/alter-primary-key.html)

Related to https://github.com/cockroachdb/cockroach/issues/68742, the documentation should mention that a table created without a primary key will have a hidden `rowid` column with a `UNIQUE` constraint, neither of which is removed when altering the primary key. Since this isn't mentioned in the documentation, it's not clear if this is a bug in the documentation or in the product.

**Comment by ajwerner** [comment]
I think this is documented. It's the combination of:

> In CockroachDB, every table requires a primary key. If one is not explicitly defined, a column called rowid of the type INT is added automatically as the primary key, with the unique_rowid() function used to ensure that new rows always default to unique rowid values. The primary key is automatically indexed.

https://www.cockroachlabs.com/docs/stable/create-table.html

And

> When you change a primary key with ALTER PRIMARY KEY, the old primary key index becomes a UNIQUE secondary index. This helps optimize the performance of queries that still filter on the old primary key column.

https://www.cockroachlabs.com/docs/stable/alter-primary-key.html
