### ISSUE TITLE
Document High Consistency Changefeed Tunings

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#11069]
if you're designing a system that relies on not missing any messages coming through a changefeed, you should ideally set up your changefeed in a certain way. We should maybe include this in the "advanced operator" section mentioned: https://github.com/cockroachdb/docs/issues/11001. 

Gc.ttl cluster setting: increasing this setting gives you a higher recoverability window if the changefeed fails for some reason
high gcttl or protect_on_pause + on failure pause
Monitoring: 
kafka_sink_config: {"RequiredAcks": "ALL" }
memory budget
maybe fail on schema change if you’re worried about data corruption downstream
what sink you use: kafka great, cloud storage good, http not good- dont know if they’re lying

**Comment by kathancox** [comment]
Closed by #12100
