### ISSUE TITLE
Document CDC cloud storage http sink and remove experimental tag from cloud storage

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#11068]
We're removing the experimental tag from cloud storage. We should reflect this in the docs for 21.2, and document the cloud storage http sink (this is especially important to make sure the differences between the webhook sink and the cloud storage http sink are clear).

https://github.com/cockroachdb/cockroach/issues/69069

**Comment by amruss** [comment]
For http - we should link to the  bulk cloud storage schema docs: https://www.cockroachlabs.com/docs/stable/use-cloud-storage-for-bulk-operations.html and just be explicit that CDC supports azure, gs, s3, and http

**Comment by kathancox** [comment]
cockroachdb/cockroach#69787
