### ISSUE TITLE
Document High Throughput Changefeed settings

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#11070]
if you're designing a system that needs to push through a lot of changefeed messages, whether it be steady traffic or a burst in traffic, you should ideally set up your changefeed in a certain way. We should maybe include this in the "advanced operator" section mentioned: #11001.

Resolved: Don't set resolved messages - or set a high resolved message
Batch messages
high memory budget 
avro format (JSON encoding can be a bottle neck)
parallelism in scan requests- for backfills (increase) 

heuristic is 3x the number of nodes, but we internally cap at 100 - if you set the setting you can change however you want.

Negative: higher CPU usage - for 100 node cluster, each node will issue requests to the same node, 300 requests

Turn on time based iterator cluster setting

**Comment by kathancox** [comment]
Closed by #12100
