### ISSUE TITLE
sql: Document valid string->boolean conversions

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#1108]
We support a number of string->boolean conversions through both explicit type casts and [untyped string constant coercion](https://github.com/cockroachdb/cockroach/pull/13685). These can be seen in [a test here](https://github.com/cockroachdb/cockroach/blob/f89ad5b009c068cdb81e798639e7d889377b1729/pkg/sql/parser/eval_test.go#L500).

We should document these valid literals in a similar method to https://www.postgresql.org/docs/current/static/datatype-boolean.html.

**Comment by jseldess** [comment]
@knz, I think https://www.cockroachlabs.com/docs/v2.1/bool.html#supported-casting-and-conversion and https://www.cockroachlabs.com/docs/v2.1/data-types.html#data-type-conversions-and-casts takes care of this, or details on https://www.cockroachlabs.com/docs/v2.1/scalar-expressions.html. Closing this, but let me know if you think there's still docs to be written here.
