### ISSUE TITLE
Improve "key-value store" FAQ

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1109]
Improve this [FAQ](https://www.cockroachlabs.com/docs/frequently-asked-questions.html#can-i-use-cockroachdb-as-a-key-value-store), and add an example to [`CREATE TABLE`](https://www.cockroachlabs.com/docs/create-table.html).

From forum (@petermattis):

Any implementation of the Spanner API would be built on top of our SQL implementation. The code paths for "simple" tables with no indexes or foreign keys have very small overhead (single digit percent slowdowns) for `INSERT/UPDATE/UPSERT/DELETE`. For example, a simple "kv" table might be defined as:

```
CREATE TABLE kv (
k INT PRIMARY KEY,
v BYTES,
)
```

Adding or replacing a row would be:

`UPSERT INTO kv VALUES (1, 'hello'::bytes)`

Under the hood, this translates into a single KV Put operation and the overhead to this translation is minimal. The upside is large as you still have a SQL table for which there is a well defined query language (if you ever need it), a known transaction model and you can add more columns to the table if the need arises. Want this to look like just keys and values? Add some simple wrapper code in the language of your choice.

**Comment by danhhz** [comment]
HA! I literally just read this reply and came over to the docs repo to suggest we use it to expand the FAQ answer. Consider this seconded.
