### ISSUE TITLE
Several "Orchestrate Kubernetes" docs in v21.2 refer to much older versions (e.g. 20.2) in upgrade steps

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#11109]
Specifically, the [upgrade the cluster](https://www.cockroachlabs.com/docs/dev/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#upgrade-the-cluster) section refers to some very old versions and probably needs editing.   Also the one [on this page](https://www.cockroachlabs.com/docs/dev/operate-cockroachdb-kubernetes.html#upgrade-the-cluster) - maybe an include?

Editing the steps would require changing enough information that I wasn't comfortable doing it in a mechanical way as part of the v21.2 docs version bump in #11035, since it looks complicated enough to probably need some re-testing (or at least, it looks that way to someone who doesn't know this area so I didn't want to just do it)

**Comment by rmloveland** [comment]
Hey Ryan this looks like your area but please let me know if I should un/re-assign

**Comment by taroface** [comment]
Thanks for filing @rmloveland !
