### ISSUE TITLE
Update v21.2 upgrade docs re: interleaved tables

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#11110]
I'm doing some edits in the v21.2 docs as a follow up to #11035, and came across some pretty specific instructions in the [breaking changes section](https://www.cockroachlabs.com/docs/dev/upgrade-cockroach-version.html#review-breaking-changes) w.r.t. how to move forward with interleaved tables.

I'm hesitant to blindly update this section's version numbers without knowing more or doing some actual testing, but that's kinda beyond the scope of the mechanical copy edits I'm doing right now.  Hence this issue.

**Comment by ericharmeling** [comment]
Thanks for opening this issue, Rich! I can take this one.
