### ISSUE TITLE
storage: push txn queues for high contention scenarios

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1117]
Important updates to how we handle transaction priority in high-contention scenarios. Need to update `transactions.md` and other transaction-related docs.

PR: https://github.com/cockroachdb/cockroach/pull/13501

cc: @spencerkimball

**Comment by spencerkimball** [comment]
If you can point me at relevant docs, I can do an update.

**Comment by jseldess** [comment]
Thanks for offering, @spencerkimball. Mostly, we need to update `transactions.md`. But there may be minor updates needed on other pages as well:

- `set-transaction.md`: Might want to clarify the description for the `PRIORITY` parameter.
- `begin-transaction.md`: Same as above. Also might want to alter the callouts about transaction retries.
- `rollback-transaction.md`: Not sure if we need to change any details around the `40001` / `retry transaction` error.
- `release-savepoint.md`: Not sure if this needs updates.
- `frequently-asked-questions.md`: Probably want to update the answer to "How are transactions in CockroachDB lock-free?"

Also, we may need to tweak the language in the `Transaction (with retry logic)` sections of these tutorials:
- `build-a-c++-app-with-cockroachdb.md`
- `build-a-clojure-app-with-cockroachdb.md`
- `build-a-go-app-with-cockroachdb.md`
- `build-a-java-app-with-cockroachdb.md`
- `build-a-nodejs-app-with-cockroachdb.md`
- `build-a-php-app-with-cockroachdb.md`
- `build-a-python-app-with-cockroachdb.md`
- `build-a-ruby-app-with-cockroachdb.md`
- `build-a-rust-app-with-cockroachdb.md`

Lots of updates, so let me know if you'd rather I take on some or all of them.
