### ISSUE TITLE
release-21.1: sql: add setting to clone parent partitions for deinterleaving

### ISSUE THREAD

**Issue by mikeCRL** [cockroachdb/docs#11184]
Mike Lewis (mikeCRL) commented:

PR: https://github.com/cockroachdb/cockroach/pull/68114

From release notes:
> Added a new [session variable](../v21.1/set-vars.html) (`enable_copying_partitioning_when_deinterleaving_table`) which will change the behavior of [`ALTER PRIMARY KEY`](../v21.1/alter-primary-key.html) when performing a change which retains the same primary key but removes an [`INTERLEAVE INTO` clause](../v21.1/interleave-in-parent.html). When this variable is set to `true` and an `ALTER PRIMARY KEY` is run that only removes an `INTERLEAVE INTO` clause, the [partitioning](../v21.1/partitioning.html) and [zone configuration](../v21.1/configure-zone.html] which applied to the root of the interleave will be applied to the new primary index. The default value for `enable_copying_partitioning_when_deinterleaving_table` is equal to the value set for the new cluster setting `sql.defaults.copy_partitioning_when_deinterleaving_table.enabled`. [#68114][#68114) {% comment %}doc{% endcomment %}

Jira Issue: DOC-1444

**Comment by jseldess** [comment]
Updated this based on https://github.com/cockroachdb/docs/pull/11794/files.

**Comment by jseldess** [comment]
cc @ajwerner
