### ISSUE TITLE
sql: support opt_interval in interval constants

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1119]
PR: https://github.com/cockroachdb/cockroach/pull/13702

Think we just need to update the SQL Standard description.

**Comment by Shiwanee** [comment]
Hi @Amruta-Ranade! I was studying this issue and I looks like it is already fixed. (Re: Duration Fileds on https://www.cockroachlabs.com/docs/v20.1/interval.html#example)

If this issue needs further fix; I would like to investigate more and work on this issue. 

 Thanks,
Shiwanee

**Comment by Amruta-Ranade** [comment]
cc @ericharmeling

**Comment by ericharmeling** [comment]
@Shiwanee is correct. This was added to the grammar docs a while ago.
