### ISSUE TITLE
Load balancing in Kubernetes deployment

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11217]
Jesse Seldess commented:

Our Kubernetes config defines a service for load balancing client traffic: https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/bring-your-own-certs/cockroachdb-statefulset.yaml#L60

In the [SQL shell step](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes.html?#step-3-use-the-built-in-sql-client) of our Kubernetes tutorial, we point the shell at that load balancer (`--host=cockroachdb-public`). But we never explicitly mention anything about the load balancer and that client traffic should use it. 

In contrast, in all of our manual deployment docs, we are very explicit that a load balancer is important, e.g., https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-google-cloud-platform.html#step-4-set-up-load-balancing.

We should find a way to explicitly mention load balancing in the Kubernetes deployment docs.

Jira Issue: DOC-1425

**Comment by taroface** [comment]
Load balancer for the Operator: https://github.com/cockroachdb/cockroach-operator/blob/c8490eff8f9aca5d5bc5fccbd68a308715f32f7d/pkg/resource/public_service.go

For Helm deployments: https://github.com/cockroachdb/helm-charts/blob/eca29c95a1d3e2edccc28530f684841ef8f0c606/cockroachdb/templates/service.public.yaml
