### ISSUE TITLE
Upgrade to CockroachDB v21.1 Doc Update 

### ISSUE THREAD

**Issue by alistair-roacher** [cockroachdb/docs#11228]
Re: [Upgrade to CockroachDB v21.1](https://cockroachlabs.com/docs/v21.1/upgrade-cockroach-version.html)

## Issue Description
Ran the Linux command as suggested to download 20.1.8 and got the following error:

$ curl https://binaries.cockroachdb.com/cockroach-v21.1.8.linux-amd64.tgz
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

## Suggested Resolution 
Combine the 2 Linux commands into a single statement:

$ curl https://binaries.cockroachdb.com/cockroach-v21.1.8.linux-amd64.tgz|tar -xzf -

**Comment by jseldess** [comment]
cc @taroface and @mikeCRL
