### ISSUE TITLE
Operational FAQs Doc Update  - 10 days vs. 90 days

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#11245]
Re: [Operational FAQs](https://cockroachlabs.com/docs/v21.1/operational-faqs.html)

## Issue Description

The doc says
>By default, CockroachDB stores timeseries data for the last 90 days for display in the DB Console

However, the preceding paragraph says:
>The timeseries data used to power the graphs in the DB Console is stored within the cluster and accumulates for 10 days before it starts getting truncated. As a result, for the first 10 days or so of a cluster's life, you will see a steady increase in disk usage and the number of ranges even if you aren't writing data to the cluster yourself.

## Suggested Resolution 
Perhaps this should say 10 days instead of 90 days, e.g.
> By default, CockroachDB stores timeseries data for the last 10 days for display in the DB Console

**Comment by jseldess** [comment]
Good point, @hand-crdb. I'm not sure which is correct. @taroface, do you know if this changed recently and we just didn't catch all the places to make updates?

**Comment by taroface** [comment]
Hmm, I don't think I have worked on either section. cc @ianjevans in case you're aware of any recent time-series changes from SQL Observability.

**Comment by ianjevans** [comment]
I don't think SQL Observability changed `timeseries.storage.resolution_10s.ttl`. There's a separate cluster setting for SQL metrics collection.

**Comment by jseldess** [comment]
I see that @rimadeodhar changed that part of the FAQ in this PR: https://github.com/cockroachdb/docs/pull/10528. I think we need to work together to figure out what still needs clarification. That PR was reviewed just by @thtruo. In the future, we probably want to make sure the relevant docs writer is also involved. 

@taroface, can you please triage and prioritize this with @thtruo? Not sure of the urgency.
