### ISSUE TITLE
sql: changed pg_catalog data type columns to "char" to match postgres

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11256]
PR: https://github.com/cockroachdb/cockroach/pull/65101

From release notes:
> Switched types from `TEXT` to `"char"` for compatibility with postgres in the following columns: `pg_constraint` (`confdeltype`, `confmatchtype`, `confudptype`, `contype`) `pg_operator` (`oprkind`), `pg_prog` (`proargmodes`), `pg_rewrite` (`ev_enabled`, `ev_type`), `pg_trigger` (`tgenabled`) [#65101][#65101] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We don't explicitly document the data types of the columns in these tables. I don't think there's anything to update here.
