### ISSUE TITLE
cli: add support for -r flag to userfile upload CLI command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11251]
PR: https://github.com/cockroachdb/cockroach/pull/65307

Release note:

> - Added the `--recursive` or `-r` flag to the [`cockroach userfile upload`](../v21.2/cockroach-userfile-upload.html) CLI command allowing users to upload the entire subtree rooted at a specified directory to user-scoped file storage: `userfile upload -r path/to/source/dir destination`. The destination can be expressed one of four ways:<ul><li>Empty (not specified)</li><li>A relative path, such as `path/to/dir`</li><li>A well-formed URI with no host, such as `userfile:///path/to/dir/`</li><li>A full well-formed URI, such as `userfile://db.schema.tablename_prefix/path/to/dir`</li></ul>If a destination is not specified, the default URI scheme and host will be used, and the basename from the source will be used as the destination directory. For example: `userfile://defaultdb.public.userfiles_root/yourdirectory`. If the destination is a relative path such as `path/to/dir`, the default userfile URI schema and host will be used (`userfile://defaultdb.public.userfiles_$user/`), and the relative path will be appended to it. For example: `userfile://defaultdb.public.userfiles_root/path/to/dir`. If the destination is a well-formed URI with no host, such as `userfile:///path/to/dir/`, the default userfile URI schema and host will be used (`userfile://defaultdb.public.userfiles_$user/`). For example: `userfile://defaultdb.public.userfiles_root/path/to/dir`. If the destination is a full well-formed URI, such as `userfile://db.schema.tablename_prefix/path/to/dir`, then it will be used verbatim. For example: `userfile://foo.bar.baz_root/path/to/dir`. [#65307][#65307]

**Comment by kathancox** [comment]
Closed in favor of https://github.com/cockroachdb/docs/issues/10875
