### ISSUE TITLE
*: Build APIv2 spec using go-swagger, annotate endpoints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11265]
PR: https://github.com/cockroachdb/cockroach/pull/62560

From release notes:
> Added documentation for [Cluster API](../v21.2/cluster-api.html) v2 endpoints. [#62560][#62560] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@taroface, not sure if there's anything new here.

**Comment by mikeCRL** [comment]
This is the work done by @itsbilal to generate the original spec file for the Cluster API. For the v21.1 docs, we used the spec built from this code on master, though this code itself hadn't made it in to 21.1. No action is needed.

**Comment by jseldess** [comment]
Thanks, @mikeCRL. Closing.
