### ISSUE TITLE
kvcoord: merge budgets for in-flight writes and lock spans

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11269]
PR: https://github.com/cockroachdb/cockroach/pull/66915

From release notes:
> The setting `kv.transaction.write_pipelining_max_outstanding_size` is now a no-op. Its function is folded into the `kv.transaction.max_intents_bytes` setting. [#66915][#66915] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we need to document this no-op. 

@rmloveland Please re-open if you disagree from a KV perspective.

**Comment by rmloveland** [comment]
Makes sense to me - the write pipelining cluster setting is only mentioned in a couple of very old release notes.  It does not appear to have even been in the public settings available via `SHOW CLUSTER SETTINGS`.
