### ISSUE TITLE
backupccl: check mismatched cluster regions on backup and restore

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11278]
PR: https://github.com/cockroachdb/cockroach/pull/64758

From release notes:
> Previously, if a restore cluster mismatched the regions in backup cluster, the data would be restored as if the zone configuration did not exist. CockroachDB now checks the regions before restore, making users aware of mismatched regions between backup and restore clusters. If there is a mismatched region, users can either update cluster localities or restore with the `--skip-localities-check` option to continue. [#64758][#64758] {% comment %}doc{% endcomment %}

**Comment by livlobo** [comment]
@kathancox - for testing this feature - it was helpful for me to read this in addition to the description in the PR.
https://www.cockroachlabs.com/docs/v21.1/multiregion-overview.html

For additional context, you can refer to my test results [here](https://docs.google.com/document/d/1qsYSWbZsiv9NDXQOght-0VL-5pzY7DdMuNQnBLRBjjA/edit#), if you'd like.

I'm not sure how we want to note this open issue: https://github.com/cockroachdb/cockroach/issues/71349
