### ISSUE TITLE
changefeedccl: refactor schema registry code to fail early 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11280]
PR: https://github.com/cockroachdb/cockroach/pull/65775

From release notes:
> [Changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) will now report more schema registry connection problems immediately at job creation time. [#65775][#65775] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
No docs needed
