### ISSUE TITLE
backupccl: allow restoring into multi-region databases

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11283]
PR: https://github.com/cockroachdb/cockroach/pull/65015

From release notes:
> [`RESTORE`](../v21.2/restore.html) now supports restoring individual tables into a multi-region database. If the table being restored is also multi-region, `REGIONAL BY ROW` tables cannot be restored, and `REGIONAL BY TABLE` tables can only be restored if their localities match those of the database they're being restored into. [#65015][#65015] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
Relates to #10937

**Comment by livlobo** [comment]
This can be closed as a dupe of #10937
