### ISSUE TITLE
changefeedccl: allow changefeeds on regional by row tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11286]
PR: https://github.com/cockroachdb/cockroach/pull/68229

From release notes:
> [Changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) no longer fail when started on `REGIONAL BY ROW` tables. Note that in `REGION BY ROW` tables, the `crdb_region` column becomes part of the primary index. Thus, changing an existing table to `REGIONAL BY ROW` will trigger a changefeed backfill with new messages emitted using the new composite primary key. [#68229][#68229] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
Closing in favor of #10934
