### ISSUE TITLE
changefeedccl: don't attempt to protect timestamp in tenant

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11284]
PR: https://github.com/cockroachdb/cockroach/pull/67285

From release notes:
> [Changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) don't attempt to use protected timestamps when running in a multi-tenant environment. [#67285][#67285] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
Closing - does not need docs
