### ISSUE TITLE
backupccl: add option to display descriptor ids to SHOW BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11287]
PR: https://github.com/cockroachdb/cockroach/pull/68540

From release notes:
> Descriptor IDs of every object are now visible in [`SHOW BACKUP`](../v21.2/show-backup.html), along with the descriptor IDs of the object's database and parent schema. `SHOW BACKUP` will display these IDs if the `WITH debug_ids` option is specified. [#68540][#68540] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
Closed by #11876
