### ISSUE TITLE
changefeedccl: detect sink URLs with no scheme

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11289]
PR: https://github.com/cockroachdb/cockroach/pull/68978

From release notes:
> [Changefeed](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) statements now error if the provided sink URL does not contain a scheme. Such URLs are typically a mistake and will result in non-functional changefeeds. [#68978][#68978] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
Closing - does not need docs
