### ISSUE TITLE
changefeedccl: Rework sink flushing behavior.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11297]
PR: https://github.com/cockroachdb/cockroach/pull/67988

From release notes:
> [Changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) will now flush the sink only when frontier advances. This eliminates unnecessary sink flushes. [#67988][#67988] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
@miretskiy I don't think this needs to be mentioned in the docs, but I wanted to double check

**Comment by kathancox** [comment]
OK thanks both, I will close this.
