### ISSUE TITLE
changefeedccl: signal changeAggregator shutdown from the kvfeed

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11294]
PR: https://github.com/cockroachdb/cockroach/pull/69234

From release notes:
> Fixed a bug where [changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) would fail to correctly handle a primary key change. [#69234][#69234] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
Closing - does not need docs
