### ISSUE TITLE
changefeedccl: Reduce the rate of changefeed progress checkpoints.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11298]
PR: https://github.com/cockroachdb/cockroach/pull/67815

From release notes:
> Improved [changefeed](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) scalability, particularly when running against large tables, by reducing the rate of job progress updates. [#67815][#67815] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
closing - does not need docs
