### ISSUE TITLE
changefeedccl: Checkpoint changefeeds during backfill.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11299]
PR: https://github.com/cockroachdb/cockroach/pull/66013

From release notes:
> [Changefeeds](../v21.2/stream-data-out-of-cockroachdb-using-changefeeds.html) can resume during backfill without losing too much progress. [#66013][#66013] {% comment %}doc{% endcomment %}

**Comment by amruss** [comment]
closing - this does not need docs
