### ISSUE TITLE
sql: adding new tables at pg_catalog

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11319]
PR: https://github.com/cockroachdb/cockroach/pull/64035

From release notes:
> Added new columns to `pg_catalog` tables: `pg_class` (`relminmxid`), `pg_constraint` (`conparentid`). [#64035][#64035] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We don't explicitly document columns in the `pg_catalog` system catalog tables.
