### ISSUE TITLE
sql: fixed information_schema.columns.data_type for enum type columns

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11328]
PR: https://github.com/cockroachdb/cockroach/pull/65154

From release notes:
> `information_schema.columns.data_type` now returns "`USER-DEFINED`" when the column is a user-defined type (e.g., [`ENUM`](../v21.2/enum.html)) [#65154][#65154] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We don't explicitly document the data types returned by this column, as it is implemented for pg compatibility. So this fix is more of a bug fix, and the table now exhibits expected behavior in the case of ENUMs.
