### ISSUE TITLE
Minimum and recommended hardware configuration per cloud provider

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1132]
Minimum and recommended, per cloud provider:
- CPU
- RAM
- Disk types

Also related: #960 (configuring NTP)

**Comment by jseldess** [comment]
@mberhault, can you help me here? If so, I'll set up time.

**Comment by mberhault** [comment]
sure.
The basic hardware profile we're using right now is:
AWS: m3.large (2cpu/7.5Ram)
GCE: custom (8cpu/16Ram)
Azure: mostly D3V2 (4cpu/14Ram)

They all have local SSD as well, in varying amounts.

I still have it on my todo list to test various things (cockroach speed, disk/network speed) on various machines types on all clouds. I'm hoping to have those in this quarter.

**Comment by jseldess** [comment]
Excellent, @mberhault. These initial details are great. Let me know once you get to that testing.

**Comment by bdarnell** [comment]
On Azure, the A series VMs eat data and must be avoided (cockroachdb/cockroach#12875). The D and Dv2 series seem to be fine (I think those are the only ones we have enough experience to say something about).

**Comment by jseldess** [comment]
MemSQL's installation requirements: http://docs.memsql.com/docs/system-requirements

**Comment by jseldess** [comment]
From @spencerkimball in https://github.com/cockroachdb/docs/issues/965: Please include minimum recommended configuration as well.

**Comment by jseldess** [comment]
@mberhault, it'd be great to have minimum and recommendation hardware configurations in place for 1.0, which leaves us ~3 weeks. Have you had more time to dig into this, and do you have updates?

I'm wondering if we could provide details similar to what [memsql](http://docs.memsql.com/docs/system-requirements) has...

**Comment by sploiselle** [comment]
From @mberhault 

Minimum hardware requirements:
- Not less than 2 cores; adding cores will help throughput.
- Not less than 1 Gig of RAM; impact on caching at RocksDB level
- If performance is a concern, use SSD; but all SSDs not equal across clouds.
- Triplicate data by default: Storage = ⅓ raw disk space

Cluster size: 
- Thoroughly tested up to 32 nodes, with experiments up to 64 with no issues.
- Won’t have network blowup up to 100 nodes.

More nodes vs bigger nodes: 
- More nodes: If node dies, amount of data to recover is smaller; more aggregate bandwidth across cluster.
- Bigger nodes: Might have better power; on cloud, more likely to get your own node.

Cloud-specific:
 - **Azure**
   - Clocks on Azure; hyperv
   - When VM migrations happen on Azure, disks are wiped
   - GCE and Amazon do not have these issues.

**Comment by bdarnell** [comment]
We currently recommend up to 64 nodes; it's not just experimental. 

I think VM migrations on AWS also cause disks to be wiped (in some cases; we haven't had one of these events in a while on our AWS instances), but in general they recover automatically (except for the first node, which is why we must recommend restarting the first node with `--join` after bootstrapping is complete). The problem on azure is that a wiped disk there comes back with a bad filesystem (ntfs over fuse) which causes severe performance degradation.

**Comment by bdarnell** [comment]
Users are [reporting](https://gitter.im/cockroachdb/cockroach?at=592f942a00efc2bb3ec50b8e) OOM failures in VMs with 1GB of memory. We may need to increase our recommendation to 2GB unless and until we can keep our Go memory usage under better control. Logs from one such failure show that CGo memory was stable at 266MiB as expected, but Go usage was fairly high (and significantly exceeding the default budget for `--max-sql-memory`). I don't know what kind of load the cluster was under at the time.

```
I170529 22:10:26.582974 117 server/status/runtime.go:225  [n4] runtime stats: 818 MiB RSS, 964 goroutines, 231 MiB/176 MiB/449 MiB GO alloc/idle/total, 264 MiB/337 MiB CGO all
oc/total, 308.54cgo/sec, 0.10/0.01 %(u/s)time, 0.00 %gc (2x)
I170529 22:10:36.199060 117 server/status/runtime.go:225  [n4] runtime stats: 838 MiB RSS, 221 goroutines, 261 MiB/156 MiB/449 MiB GO alloc/idle/total, 265 MiB/337 MiB CGO all
oc/total, 1666.68cgo/sec, 0.39/0.05 %(u/s)time, 0.00 %gc (7x)
I170529 22:10:47.035821 117 server/status/runtime.go:225  [n4] runtime stats: 837 MiB RSS, 1077 goroutines, 380 MiB/27 MiB/449 MiB GO alloc/idle/total, 266 MiB/337 MiB CGO all
oc/total, 871.13cgo/sec, 0.20/0.02 %(u/s)time, 0.00 %gc (4x)
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fe9f2a7f067 m=2 sigcode=18446744073709551610
```

**Comment by jseldess** [comment]
We can probably learn from [Cassandra's hardware recommendations](https://docs.datastax.com/en/landing_page/doc/landing_page/planning/planningHardware.html).

**Comment by jseldess** [comment]
@mberhault, what's your sense: We now have [cloud-agnostic hardware recs](https://www.cockroachlabs.com/docs/recommended-production-settings.html#hardware) documented, but will we be able to track down and document cloud-specific hardware recs for the 1.1 release? If not, I'll just move this issue to the `Later` milestone.

**Comment by mberhault** [comment]
I think `later` will be fine for this, if ever. Cloud specs get... tricky.

**Comment by bdarnell** [comment]
One thing we do need to do is add warnings about the data corruption bug that we've seen on Azure A-series instances. D-series instances are believed to be fine; other series should be tested extensively before production use.

**Comment by jseldess** [comment]
Tracking the Azure-specific recommendations in #1356.

**Comment by jseldess** [comment]
@mberhault, @bdarnell, reviving this issue in service of the deployment doc updates I'm planning. Marc and I agreed that we should include the hardware configurations that we have tested on various clouds, not as a rec for all workloads, but just as a starting point. We could also share details about load gens run against different configurations. Marc, you shared the following in an earlier comment:

```
The basic hardware profile we're using right now is:
AWS: m3.large (2cpu/7.5Ram)
GCE: custom (8cpu/16Ram)
Azure: mostly D3V2 (4cpu/14Ram)

They all have local SSD as well, in varying amount
```

Is that the level of detail we want to share with users? If not, can you update and expand?

Also, we discussed included things to avoid:
- We already have this issue about [Azure](https://github.com/cockroachdb/docs/issues/1356). My understanding is there are two aspects there, performance (concerns VM migrations) and data loss/corruption (concerns local storage). That right?
- If there are other cloud-specific gotchas to avoid, please add here.

**Comment by bdarnell** [comment]
For azure, most of our testing to date has been on D-series VMs, but recent work by the bulk IO team has found that everything but the L series is subject to problematic disk throttling so that should be our recommendation there. (I've updated #1356 too)

@nvanbenschoten has found that it is sometimes (only on older kernels? this was observed with ubuntu 14.04) necessary to run `sudo ethtool -K eth0 sg off` on ec2 machines to avoid a kernel (or hypervisor?) bug. 

Amazon has just introduced some new time-synchronization capabilities that we should test (and recommend, assuming the testing goes well)

We should recommend ubuntu 16.04 (if we don't already - this is not cloud-specific advice), since that's our most thoroughly tested platform.
