### ISSUE TITLE
sql: allow references to top-level WITH from apply-join

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11335]
PR: https://github.com/cockroachdb/cockroach/pull/65550

From release notes:
> References to WITH expressions from correlated subqueries are now always supported. [#65550][#65550] {% comment %}doc{% endcomment %}

**Comment by ianjevans** [comment]
Our [`WITH`](https://www.cockroachlabs.com/docs/v21.2/common-table-expressions.html), [correlated subqueries ](https://www.cockroachlabs.com/docs/v21.2/subqueries#correlated-subqueries), and [known limitations](https://www.cockroachlabs.com/docs/v21.2/known-limitations.html) docs do not explicitly disallow `WITH` expressions in correlated subqueries.

Closing as there doesn't seem to be doc impact.
