### ISSUE TITLE
sql: surface sampled query plan, database name, and execution nodes to internal node statement statistics table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11344]
PR: https://github.com/cockroachdb/cockroach/pull/65782

From release notes:
> Added `sample_plan`, `database_name`, and `exec_node_ids` columns to the `crdb_internal.node_statement_statistics` table. This allows for third-party and partner consumption of this data. [#65782][#65782] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Not going to document individual columns in `crdb_internal` tables. https://github.com/cockroachdb/docs/issues/11446
