### ISSUE TITLE
sql: pg_rewrite implemented for table-view dependencies

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11345]
PR: https://github.com/cockroachdb/cockroach/pull/65495

From release notes:
> Implemented `pg_rewrite` for table-view dependencies. Table-view dependencies are no longer stored directly in `pg_depend`. [#65495][#65495] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't require docs, as the tables now behave as expected.
