### ISSUE TITLE
sql/pgwire: report "too large" errors in extended protocol

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11340]
PR: https://github.com/cockroachdb/cockroach/pull/57590

From release notes:
> Previously, SQL commands that were sent during the PostgreSQL extended protocol that were too big would error opaquely. This is now resolved by returning a friendlier error message. [#57590][#57590] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is more of a bug fix that does not affect user documentation.
