### ISSUE TITLE
sql: add cluster settings for a PRIMARY REGION and blocking PRIMARY REGION drops

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11358]
PR: https://github.com/cockroachdb/cockroach/pull/67168

From release notes:
> Added a [cluster setting](../v21.2/cluster-settings.html) `sql.defaults.primary_region`, which assigns a `PRIMARY REGION` to a database by default. [#67168][#67168] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This setting's doc is already live on [the v21.2 cluster settings page](https://www.cockroachlabs.com/docs/dev/cluster-settings.html)
