### ISSUE TITLE
sql: add cluster settings for a PRIMARY REGION and blocking PRIMARY REGION drops

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11359]
PR: https://github.com/cockroachdb/cockroach/pull/67168

From release notes:
> Introduced a [cluster setting](../v21.2/cluster-settings.html) `sql.allow_drop_final_region.enabled` which disallows dropping of a `PRIMARY REGION` (the final region of a database). [#67168][#67168] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
The setting (which ended up being called `sql.multiregion.drop_primary_region.enabled`) is already live on [the v21.2 cluster settings page](https://www.cockroachlabs.com/docs/dev/cluster-settings.html)
