### ISSUE TITLE
importccl: add deprecation warning to IMPORT TABLE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11360]
PR: https://github.com/cockroachdb/cockroach/pull/67275

From release notes:
> [`IMPORT TABLE`](../v21.2/import.html) will be deprecated in v21.2 and removed in a future release. Users should create a table using [`CREATE TABLE`](../v21.2/create-table.html) and then [`IMPORT INTO`](../v21.2/import-into.html) the newly created table. [#67275][#67275] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
A deprecation warning for this has already been added to 21.2 and 21.1 re the deprecation. Feel free to reopen if further docs are needed
