### ISSUE TITLE
builtin: add {de,}compress builtins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11368]
PR: https://github.com/cockroachdb/cockroach/pull/67426

From release notes:
> Added new [builtins](../v21.2/functions-and-operators.html#built-in-functions) `compress(data, codec)` and `decompress(data, codec)` which can compress and decompress bytes with the specified codec. `Gzip` is the only currently supported codec. [#67426][#67426] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
included docs
