### ISSUE TITLE
backupccl: respect sql.defaults.primary_region during RESTORE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11373]
PR: https://github.com/cockroachdb/cockroach/pull/67581

From release notes:
> A database that is restored with the [cluster setting](../v21.2/cluster-settings.html) `sql.defaults.primary_region` will now have the `PRIMARY REGION` from the cluster setting assigned to the database. [#67581][#67581] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
Relates to #10937
