### ISSUE TITLE
sql: support `nearest_only` argument for with_min_timestamp/max_staleness

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11379]
PR: https://github.com/cockroachdb/cockroach/pull/67837

From release notes:
> Introduced a `nearest_only` argument for `with_min_timestamp`/`with_max_staleness`, which enforces that bounded staleness reads only talk to the nearest replica. [#67837][#67837] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Captured in included docs.
