### ISSUE TITLE
jobs: add support for SHOW CREATE SCHEDULE command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11383]
PR: https://github.com/cockroachdb/cockroach/pull/66782

From release notes:
> Added the `SHOW CREATE SCHEDULE` command to view SQL statements used to create existing schedules. [#66782][#66782] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
Duplicate, Closing this in favor of #11008
