### ISSUE TITLE
tree: block interval::string for Stable cases when IntervalStyle_enabled

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11385]
PR: https://github.com/cockroachdb/cockroach/pull/67970

From release notes:
> Implemented the `parse_interval` and `to_char_with_style` [builtins](../v21.2/functions-and-operators.html#built-in-functions), which convert strings from/to intervals with immutable volatility. [#67970][#67970] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We probably don't need to document this built-in explicitly (it's included from the generated docs).
