### ISSUE TITLE
sql: Create a builtin to reset the zone configs of a multi-region table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11384]
PR: https://github.com/cockroachdb/cockroach/pull/67985

From release notes:
> Created a [builtin](../v21.2/functions-and-operators.html#built-in-functions) to reset the zone configurations of multi-region tables. This builtin can be helpful in cases where the user has overridden the [zone configuration](../v21.2/configure-replication-zones.html) for a given table and wishes to revert back to the original system-specified state. [#67985][#67985] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Captured in included docs.
