### ISSUE TITLE
settings: retire sql.defaults.optimizer_improve_disjunction_selectivity.enabled

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11399]
PR: https://github.com/cockroachdb/cockroach/pull/68349

From release notes:
> The session setting `optimizer_improve_disjunction_selectivity` and its associated [cluster setting](../v21.2/cluster-settings.html) `sql.defaults.optimizer_improve_disjunction_selectivity.enabled` are no longer supported. They were added in v21.1.7 to enable better optimizer selectivity calculations for disjunctions. This logic is now always enabled. [#68349][#68349] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Captured in included docs.
