### ISSUE TITLE
sql: implement SHOW DEFAULT PRIVILEGES

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11402]
PR: https://github.com/cockroachdb/cockroach/pull/67997

From release notes:
> Added a `crdb_internal.default_privileges` table that is useful for getting a human-readable way of examining default [privileges](../v21.2/authorization.html#privileges). [#67997][#67997] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Captured in included docs.
