### ISSUE TITLE
backup: always write to cloud storage in processor

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11407]
PR: https://github.com/cockroachdb/cockroach/pull/68468

From release notes:
> The `bulkio.backup.proxy_file_writes.enabled` [cluster setting](../v21.2/cluster-settings.html) is no longer needed to enable proxied writes, which are now the default. [#68468][#68468] {% comment %}doc{% endcomment %}

**Comment by kathancox** [comment]
Looks like this setting was removed. Docs not required here. Feel free to reopen if otherwise @dt
