### ISSUE TITLE
sql: introduce crdb_internal.index_usage_stats virtual table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11406]
PR: https://github.com/cockroachdb/cockroach/pull/66640

From release notes:
> Introduced the `crdb_internal.index_usage_statistics` virtual table to surface index usage statistics. The `sql.metrics.index_usage_stats.enabled` [cluster setting](../v21.2/cluster-settings.html) can be used to turn on/off the subsystem. It defaults to `true`. [#66640][#66640] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Captured by included docs.
