### ISSUE TITLE
c-deps,storage: remove libroach

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11473]
PR: https://github.com/cockroachdb/cockroach/pull/67389

From release notes:
> [`debug.zip`](../v21.2/cockroach-debug-zip.html) files no longer contain the file `threads.txt`, which was previously used to list RocksDB background threads. [#67389][#67389]

**Comment by rmloveland** [comment]
@dt the scope of docs work here appears to be that we can remove the line that says "Thread stack traces (Linux only)" from the [`cockroach debug zip`](https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html#files) docs

Do you agree with that assessment?  If so I'm gonna do it

**Comment by dt** [comment]
yeah, that seems right, thanks!
