### ISSUE TITLE
backup: use fixed sizes for concurrency and flush threshold

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11476]
PR: https://github.com/cockroachdb/cockroach/pull/68105

From release notes:
> [`RESTORE`](../v21.2/restore.html) no longer dynamically reads from the `kv.bulk_ingest.batch_size` [cluster setting](../v21.2/cluster-settings.html) to determine its batch size. If the value is updated, [`RESTORE`](../v21.2/restore.html) jobs need to be `PAUSE`d and `RESUME`d to adopt the updated setting. [#68105][#68105]

**Comment by kathancox** [comment]
Closing issue - no user facing docs required here.
