### ISSUE TITLE
sql, kv: add sql.mutations.max_row_size guardrails

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11481]
PR: https://github.com/cockroachdb/cockroach/pull/67953

From release notes:
> Added a new [cluster setting](../v21.2/cluster-settings.html), `sql.mutations.max_row_size.err`, which limits the size of rows written to the database (or individual column families, if multiple column families are in use). Statements trying to write a row larger than this will fail with a code `54000 (program_limit_exceeded)` error. (Internal queries writing a row larger than this will not fail, but will log a `LargeRowInternal` event to the SQL_INTERNAL_PERF channel.) This limit is enforced for INSERT, UPSERT, and UPDATE statements. [`CREATE TABLE`](../v21.2/create-table.html) AS, CREATE INDEX, ALTER TABLE, ALTER INDEX, IMPORT, and [`RESTORE`](../v21.2/restore.html) will not fail with an error, but will log LargeRowInternal events to the [`SQL_INTERNAL_PERF`](../v21.2/logging.html#sql_internal_perf) channel. [`SELECT`](../v21.2/select-clause.html), [`DELETE`](../v21.2/delete.html), [`TRUNCATE`](../v21.2/truncate.html), and [`DROP`](../v21.2/drop-table.html) are not affected by this limit. Note that existing rows violating the limit **cannot** be updated, unless the update shrinks the size of the row below the limit, but *can* be selected, deleted, altered, backed-up, and restored. For this reason we recommend using the accompanying setting `sql.mutations.max_row_size.log` in conjunction with `SELECT pg_column_size()` queries to detect and fix any existing large rows before lowering `sql.mutations.max_row_size.err`. [#67953][#67953]

**Comment by michae2** [comment]
Note that this setting was renamed, as described in https://github.com/cockroachdb/docs/issues/11485, and metrics were added, as described in https://github.com/cockroachdb/docs/issues/11490.
