### ISSUE TITLE
sql: add txn rows written/read guardrails

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11483]
PR: https://github.com/cockroachdb/cockroach/pull/69202

From release notes:
> The new [cluster settings](../v21.2/cluster-settings.html) `sql.defaults.transaction_rows_written_log`, `sql.defaults.transaction_rows_written_err`, `sql.defaults.transaction_rows_read_log`, and `sql.defaults.transaction_rows_read_err` (as well as the corresponding session variables) have been introduced. These settings determine the "size" of the transactions in written and read rows upon reaching of which the transactions are logged or rejected. The logging will go into the [`SQL_PERF`](../v21.2/logging.html#sql_perf) logging channel. Note that the internal queries (i.e., those issued by CockroachDB internally) cannot error out but can be logged instead into [`SQL_INTERNAL_PERF`](../v21.2/logging.html#sql_internal_perf) logging channel. The "written" limits apply to [`INSERT`](../v21.2/insert.html), [`INSERT INTO SELECT FROM`](../v21.2/insert.html), [`INSERT ON CONFLICT`](../v21.2/insert.html), [`UPSERT`](../v21.2/upsert.html), [`UPDATE`](../v21.2/update.html), and [`DELETE`](../v21.2/delete.html) whereas the "read" limits apply to [`SELECT`](../v21.2/select-clause.html) statement in addition to all of these. These limits will not apply to [`CREATE TABLE AS`](../v21.2/create-table.html), [`SELECT`](../v21.2/select-clause.html), [`IMPORT`](../v21.2/import.html), [`TRUNCATE`](../v21.2/truncate.html), [`DROP`](../v21.2/drop-table.html), [`ALTER TABLE`](../v21.2/alter-table.html), [`BACKUP`](../v21.2/backup.html), [`RESTORE`](../v21.2/restore.html), or [`CREATE STATISTICS`](../v21.2/create-statistics.html) statements. Note that enabling `transaction_rows_read_err` guardrail comes at the cost of disabling the usage of the auto commit optimization for the mutation statements in implicit transactions. [#69202][#69202]

**Comment by stbof** [comment]
Related to #12133.
