### ISSUE TITLE
sql, kv: add sql.mutations.max_row_size guardrails

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11480]
PR: https://github.com/cockroachdb/cockroach/pull/67953

From release notes:
> Added a new [cluster setting](../v21.2/cluster-settings.html), `sql.mutations.max_row_size.log`, which controls large row logging. Whenever a row larger than this size is written (or a single column family if multiple column families are in use) a `LargeRow` event is logged to the [`SQL_PERF`](../v21.2/logging.html#sql_perf) channel (or a `LargeRowInternal` event is logged to [`SQL_INTERNAL_PERF`](../v21.2/logging.html#sql_internal_perf) if the row was added by an internal query). This could occur for [`INSERT`](../v21.2/insert.html), [`UPSERT`](../v21.2/upsert.html), [`UPDATE`](../v21.2/update.html), [`CREATE TABLE AS`](../v21.2/create-table.html), [`CREATE INDEX`](../v21.2/create-index.html), [`ALTER TABLE`](../v21.2/alter-table.html), [`ALTER INDEX`](../v21.2/alter-index.html), [`IMPORT`](../v21.2/import.html), or [`RESTORE`](../v21.2/restore.html) statements. [`SELECT`](../v21.2/select-clause.html), [`DELETE`](../v21.2/delete.html), [`TRUNCATE`](../v21.2/truncate.html), and [`DROP`](../v21.2/drop-table.html) are not affected by this setting. [#67953][#67953]

**Comment by michae2** [comment]
Note that this setting was renamed, as described in https://github.com/cockroachdb/docs/issues/11485, and metrics were added, as described in https://github.com/cockroachdb/docs/issues/11490.
