### ISSUE TITLE
cliccl/load: export backup table data as csv

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11498]
PR: https://github.com/cockroachdb/cockroach/pull/62662

From release notes:
> Updated `load show data` command to display backup data in CSV format. Users can either pipe the output to a file or specify the destination by a `--destination` flag. [#62662][#62662]

**Comment by kathancox** [comment]
This issue is related to #10936 and docs will be covered with the PR linked to that issue. Closing this in favor of that
