### ISSUE TITLE
cliccl: add `load show backups` to display backup collection

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11493]
PR: https://github.com/cockroachdb/cockroach/pull/61862

From release notes:
> Updated `load show` with `incremental` subcommand to display incremental backups. Users can list incremental backup paths of a full backup by running `cockroach load show incremental <backup_url>.` [#61862][#61862]

**Comment by kathancox** [comment]
Closing as this is a duplicate of #11494
