### ISSUE TITLE
cliccl/debug_backup.go: add `--max-rows` and `--start-key` flag

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11507]
PR: https://github.com/cockroachdb/cockroach/pull/64157

From release notes:
> Added `--max-rows` and `--start-key` of `cockroach backup debug` tool for users to specify on export row number and start key when inspecting data from backup. [#64157][#64157]

**Comment by kathancox** [comment]
This issue is related to #10936 and docs will be covered with the PR linked to that issue. Closing this in favor of that
