### ISSUE TITLE
cliccl/load.go: update `--as-of` to display backup data at arbitrary timestamp

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11500]
PR: https://github.com/cockroachdb/cockroach/pull/63181

From release notes:
> Previously, `--as-of` of `load show data` had the restriction that users could only inspect data at an exact backup timestamp. The flag has improved to work with [backups with revision history](../v21.2/take-backups-with-revision-history-and-restore-from-a-point-in-time.html) so that users can inspect data at an arbitrary timestamp. [#63181][#63181]

**Comment by kathancox** [comment]
This issue is related to #10936 and docs will be covered with the PR linked to that issue. Closing this in favor of that
