### ISSUE TITLE
cliccl/debug_backup.go: refactor backup inspection tool

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11503]
PR: https://github.com/cockroachdb/cockroach/pull/63309

From release notes:
> Previously, backup inspection was done via `cockroach load show ..`, which could confuse users with ambiguous verbs in the command chain. The syntax is now more clear and indicative for users debugging backups. The changes are: `load show summary <backup_url>` -> `debug backup show <backup_url>`; `load show incremental <backup_url>` -> `debug backup list-incremental <backup_url>`; `load show backups <collection_url>` -> `debug backup list-backups <collection_url>`; `load show data <table_name> <backup_url>` -> `debug backup export <backup_url> --table=<table_name>`. [#63309][#63309]

**Comment by kathancox** [comment]
This issue is related to #10936 and docs will be covered with the PR linked to that issue. Closing this in favor of that
