### ISSUE TITLE
server: create api to query persisted stats by date range

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11539]
PR: https://github.com/cockroachdb/cockroach/pull/69238

From release notes:
> Added a new endpoint `/_status/combinedstmts` to retrieve persisted and in-memory statements from `crdb_internal.statement_statistics` and `crdb_internal.transaction_statistics` by aggregated_ts range. The request supports optional query string parameters `start` and `end`, which are the date range in unix time. The response returned is currently the response expected from `/_status/statements`. `/_status/statements` has also been updated to support the parameters `combined`, `start`, and `end`. If `combined` is `true`, then the statements endpoint will use `/_status/combinedstmts` with the optional parameters `start` and `end`. [#69238][#69238]

**Comment by jseldess** [comment]
@awoods187, not sure if this should be taken by the SQL team. But if we can auto-gen docs for these endpoints, the Observability team probably needs to be involved.

**Comment by awoods187** [comment]
@jseldess this is now owned by SQL Observability cc @kevin-v-ngo
