### ISSUE TITLE
Disaster Recovery docs (backup/restore)

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1157]
- How to set up an environment for DR
- Best practices
- How to execute on your DR plan (restore from today, from last week, from 6 months ago)

Weave this reference into other deployment production docs to ensure visibility

Will need to work with ours and others' SREs to find and verify this info.

**Comment by jseldess** [comment]
@sploiselle, is this the main backup/restore docs issue?

**Comment by sploiselle** [comment]
@jseldess Not the enterprise docs, no. This is a separate issue for creating disaster recovery plans, inclusive of the Apache license product.

**Comment by jseldess** [comment]
Ah, ok. Where's the issue for enterprise docs? I'd like to give it the 1.0 milestone.

**Comment by jseldess** [comment]
Ah, thanks for adding this here, @sploiselle. Forgot about this issue.

**Comment by jseldess** [comment]
Closing in favor of other io planning issues.
