### ISSUE TITLE
concurrency: improvements to lock garbage collection

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11583]
Jesse Seldess commented:

PR: https://github.com/cockroachdb/cockroach/pull/64102

From release notes:
> Peak memory usage in the lock table is now significantly reduced. Runaway CPU usage due to wasted quadratic time complexity in clearing unclearable locks is addressed. [#64102][#64102]

Jira Issue: DOC-1335

**Comment by rmloveland** [comment]
This is a performance enhancement but does not effect the user-facing docs for the lock table that we already have: https://www.cockroachlabs.com/docs/v21.2/architecture/transaction-layer#concurrency-control
