### ISSUE TITLE
Consider changing time sync defaults from NTP to chrony

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#11632]
Jesse Seldess commented:

Way back in 2018, @bdarnell suggested we might want recommend chrony instead of NTP as the default time sync software: https://github.com/cockroachdb/docs/issues/3856. I think this got lost, so putting it back in the queue.

Jira Issue: DOC-1309

**Comment by bdarnell** [comment]
I still feel like most people should use whatever is the default on their linux distribution - switching from one to another is error-prone and I don't think we want to encourage this. If you really are setting something up from scratch chrony is probably the best choice, but that's very uncommon.

**Comment by jseldess** [comment]
More details from @bdarnell:
> we generally want to recommend the platform's default time sync service to avoid interference between them (we've seen problems related to this in practice where two time synchronizers were active at once). But... as far as I know chrony is the "best" and if you're installing something with a clean slate that's the one to use. On ubuntu I wouldn't recommend replacing the default systemd-timesyncd with ntpd.
