### ISSUE TITLE
Add info about changefeed retryable errors

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#11686]
Florence Morris (florence-crl) commented:

Currently, the below 2 links mention changefeed retryable errors:
https://www.cockroachlabs.com/docs/v21.1/ui-cdc-dashboard.html#changefeed-restarts
https://www.cockroachlabs.com/docs/v21.1/stream-data-out-of-cockroachdb-using-changefeeds.html#using-the-db-console

However, they do not describe what a retryable error is. I reached out to our CDC engineering team (@HonoreDB) for more information about retryable errors and 1 error in particular.

In general, a `retryable error` means the changefeed will automatically retry whatever caused the error. If you see a retryable error occasionally, but no other evidence of a problem, no action is needed.

However, in this particular case, the error is `kafka server: Message was too large, server rejected it to avoid allocation error`. To resolve this scenario requires manual intervention, since it means that at least one row is too big for the kafka server to accept change data about it. Ideally, you would fix this by reconfiguring your kafka server (which is outside of CockroachDB's control). The kafka broker setting that needs to be increased is most likely `message.max.bytes`. The changefeed may recover on its own if you increase this setting. If you can not increase it, then you need to find a way to decrease the size of the individual rows being watched by changefeeds.

gz#9773

Jira Issue: DOC-1286

**Comment by amruss** [comment]
We might want to reopen this re: your suggestion kathryn to provide a list of example retrybale and non retryable errors
