### ISSUE TITLE
FAQ link to joins post may be out of date

### ISSUE THREAD

**Issue by raxraxraxraxrax** [cockroachdb/docs#1168]
The page https://www.cockroachlabs.com/docs/frequently-asked-questions.html says CockroachDB is not yet suitable for "Complex SQL JOINS (the feature still needs optimization)" and links to a 2016 blog post (https://www.cockroachlabs.com/blog/cockroachdbs-first-join/). Perhaps this should include a reference to 2017 blog post https://www.cockroachlabs.com/blog/better-sql-joins-in-cockroachdb/ suggesting progress toward SQL joins?

**Comment by jseldess** [comment]
Thanks, @raxraxraxraxrax. We'll update that.
