### ISSUE TITLE
Update SQL statement output on Learn CockroachDB SQL

### ISSUE THREAD

**Issue by raxraxraxraxrax** [cockroachdb/docs#1169]
The page https://www.cockroachlabs.com/docs/learn-cockroachdb-sql.html demonstrates SHOW COLUMNS FROM accounts; when I run this with a current Cockroach, I see an extra column, Indices, in the table:

```
+---------+---------+-------+---------+-----------+
|  Field  |  Type   | Null  | Default |  Indices  |
+---------+---------+-------+---------+-----------+
| id      | INT     | false | NULL    | {primary} |
| balance | DECIMAL | true  | NULL    | {}        |
+---------+---------+-------+---------+-----------+
```

This might need to be updated?

**Comment by jseldess** [comment]
Nice find, @raxraxraxraxrax. Thanks!
