### ISSUE TITLE
The Spatial Data tutorial has an error when importing bookstores-and-roads data

### ISSUE THREAD

**Issue by kikiya** [cockroachdb/docs#11718]
https://www.cockroachlabs.com/docs/tutorials/spatial-tutorial-interactive

When importing bookstores-and-roads data, Step 3.2, there's an error in the console. 

```
demo@127.0.0.1:26257/tutorial>  IMPORT PGDUMP ('https://spatial-tutorial.s3.us-east-2.amazonaws.com/bookstores-and-roads-20210125.sql');

ERROR: unsupported statement: ALTER TABLE public.bookstore_routes VALIDATE CONSTRAINT fk_start_store_id_ref_bookstores
HINT: To ignore unsupported statements and log them for review post IMPORT, see the options listed in the docs: https://www.cockroachlabs.com/docs/stable/import.html#import-options
```

<img width="1905" alt="Screen Shot 2021-09-20 at 09 30 06" src="https://user-images.githubusercontent.com/4748696/134014087-e99bddfa-5081-4c11-b9cf-9733c53f46bc.png">

**Comment by jseldess** [comment]
cc @awoods187, @rmloveland. Not sure if this error is also in the docs version or just in the Katacoda version. If the latter, let me know, and I can fix it.

**Comment by smcvey** [comment]
Also the same issue with step 3.4, when importing the birds database:

<img width="1776" alt="Screenshot 2021-10-01 at 15 45 40" src="https://user-images.githubusercontent.com/28270695/135639865-0e7bded8-1e17-412e-ad89-d1397dca3eeb.png">

This is independent of Katacoda.  If I download both these sql files and attempt to import them into my own local cluster, I get the same error messages.

The solution is to change the steps to say this:

Step 3.2:

```
IMPORT PGDUMP ('https://spatial-tutorial.s3.us-east-2.amazonaws.com/bookstores-and-roads-20210125.sql') WITH ignore_unsupported_statements;
```

Step 3.4 to say:

```
IMPORT PGDUMP ('https://spatial-tutorial.s3.us-east-2.amazonaws.com/birds-20210125.sql') WITH ignore_unsupported_statements;
```

Note the addition of `WITH ignore_unsupported_statements` in both lines.

**Comment by rmloveland** [comment]
Thanks @kikiya and @smcvey.  Verified this just now as well.  Filed https://github.com/cockroachdb/cockroach/issues/70992 since this appears to be a regression / breaking change from previous versions.

In any case I will work on updating the docs as well, thanks for filing :-)

**Comment by rmloveland** [comment]
@jseldess it looks like this is only in the Katacoda version - docs for v21.1 were kindly updated by @ianjevans in 59d564b0c
