### ISSUE TITLE
multi-region: clarify you cannot backup and restore a partition of a RBR table

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#11732]
Andy Woods (awoods187) commented:

Currently, you cannot backup and restore a partition of a RBR table. This is an extension of the limitation that you [cannot backup and restore a table in a multi-region database](https://www.cockroachlabs.com/docs/v21.1/backup.html#backup-of-multi-region-tables).

Jira Issue: DOC-723

**Comment by awoods187** [comment]
cc @lin-crl

**Comment by rmloveland** [comment]
@adityamaru is this limitation (no backup/restore of a partition of a RBR table) fixed by your work on https://github.com/cockroachdb/cockroach/pull/71178 ?

**Comment by adityamaru** [comment]
Nope, we don't have precedence for backup+restore at a partition level in CockroachDB. Table is the smallest object once can backup+restore today, so we'd have to do new feature work to support this.

**Comment by rmloveland** [comment]
Aditya Maru ***@***.***> writes:

> Nope, we don't have precedence for backup+restore at a partition level
> in CockroachDB. Table is the smallest object once can backup+restore
> today, so we'd have to do new feature work to support this.

OK - then this docs issue is still valid.

Thank you, Aditya!
