### ISSUE TITLE
Add note about setting no files limit to SystemD service def to infinity

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/docs#11748]
In our Prod Recommendations doc, we talk about setting file descriptor limits: https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#file-descriptors-limit

Edit the service definition to configure the maximum number of open files -- like this:
```
[Service]
...
LimitNOFILE=35000
```

We also say that we recommend setting this to unlimited:
```
It is recommended to set the file descriptors limit to unlimited; otherwise, the recommended limit is at least 15000 (10000 per store plus 5000 for networking). This higher limit ensures performance and accommodates cluster growth.
```

However, you will get an error in Linux if you do this:
```
LimitNOFILE=unlimited
```

Instead, you need to do:
```
LimitNOFILE=infinity
```

I think it would be helpful to add a note to the SystemD section that says:
NOTE: To set the file descriptor limit to "unlimited" in the SystemD service definition file, you need to use the value "infinity"

**Comment by jonstjohn** [comment]
I think the sample code in the docs could use `infinity` since that is the recommendation stated above, rather than `35000.` Not sure where the `35000` number comes from since it isn’t mentioned above and the recommendation is that it is between `15000` and unlimited.

**Comment by jseldess** [comment]
cc @taroface
