### ISSUE TITLE
Adding CockroachDB to your PATH

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1175]
The current instructions for installing from binary ask users to put cockroach into their `PATH`. We should simplify things and add that to the `tar` step.

@benesch, @dt, please let me know the commands to use when you get a chance.

FYI @dianasaur323, @kuanluo, since I think this was a slight hurdle during one of your user interviews.

**Comment by kuanluo** [comment]
@jseldess @dianasaur323 

Awesome! Also related and minor: the Mac/Homebrew install link needs scrolling, and someone we interviewed suggested it'd be better if it's shortened. Is that possible?

**Comment by benesch** [comment]
@kuanluo #1177

Still working on getting you the commands, @jseldess!

**Comment by kuanluo** [comment]
Always one step ahead, @benesch! Thank you.

**Comment by jseldess** [comment]
@benesch, any updates on how to run `tar` and set the path as one command?

**Comment by benesch** [comment]
Yup, sorry for the delay. Thought we might be rejiggering the way the Cockroach command is packaged in the tarball. Looks like that's an issue for another day. Here's commands for the current packaging.

1. Download Cockroach:

```bash
$ curl -O https://binaries.cockroachdb.com/cockroach-latest.darwin-10.9-amd64.tgz
```

2. Untar Cockroach:

```bash
$ tar xfz cockroach-latest.darwin-10.9-amd64.tgz
```

(Same as before.)

3. Install the `cockroach` binary into your PATH:

```bash
$ sudo mv cockroach-latest.darwin-10.9-amd64/cockroach /usr/local/bin
```

I'd probably advocate for combining steps one and two (note the missing `-O`):

```bash
$ curl https://binaries.cockroachdb.com/cockroach-latest.darwin-10.9-amd64.tgz | tar x
$ sudo mv cockroach-latest.darwin-10.9-amd64/cockroach /usr/local/bin
```

But you can certainly combine them all:

```bash
$ curl https://binaries.cockroachdb.com/cockroach-latest.darwin-10.9-amd64.tgz |
    sudo tar x -C /usr/local/bin --strip-components 1
```

**Comment by benesch** [comment]
Also, the above instructions will blindly overwrite whatever lives at `/usr/local/bin/cockroach`. Probably that's just an older version of Cockroach, but you never know. You can replace `mv` with `mv -i` to have the user prompted if they're about to overwrite something.

**Comment by tamird** [comment]
Arriving here from https://github.com/cockroachdb/cockroach/issues/14232 - can we avoid directing users to `sudo`? Seems like a bad idea, generally.

**Comment by benesch** [comment]
To be clear, are you advocating for something like

> Install the binary onto your path:
> ```
> cp -i bin/cockroach /usr/local/bin
> ```
> Please note this may require root, in which case you should prefix the command with `sudo`.

or do you want to go back to what we had previously? We landed here because user research showed that most users got hung up on having to modify their path manually.

**Comment by tamird** [comment]
The former.

**Comment by benesch** [comment]
Sorry for the hassle @jseldess. Would you mind terribly to remove the `sudo` from the command and replace it with a note beneath that directs them to prepend `sudo` if they encounter permissions errors?

**Comment by jseldess** [comment]
Np, @benesch. Just opened a PR for your review.
