### ISSUE TITLE
SPLIT AT Docs for 21.1 do not cover changed behavior for TRUNCATE

### ISSUE THREAD

**Issue by nickelnickel** [cockroachdb/docs#11779]
Nick Lamb (nickelnickel) commented:

As per https://github.com/cockroachdb/cockroach/pull/65940 this is no longer the case in 20.2+

> Note that when a table is truncated, it is essentially re-created in a single new empty range, and the old ranges that used to constitute the table are garbage collected. Any pre-splitting you have performed on the old version of the table will not carry over to the new version. The new table will need to be pre-split again.

This should be reworded to cover the changed behavior.

**Comment by rmloveland** [comment]
Thanks @nickelnickel and @chengxiong-ruan 

I have filed the PR #12523 to remove this old information
