### ISSUE TITLE
Low Latency Reads and Writes in a Multi-Region Cluster Doc Update 

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#11786]
Re: [Low Latency Reads and Writes in a Multi-Region Cluster](https://cockroachlabs.com/docs/v21.1/demo-low-latency-multi-region-deployment.html)

## Issue Description

Contradicting table locality patterns are recommended at different places in the same web page.

At one place it says (my emphasis):

> All of the tables except promo_codes have a composite primary key of city and id, in that order. This means that the rows in these tables are ordered by their geography. These tables are read from and written to very frequently. To keep read and write latency low, **you'll use the Regional table locality pattern for these tables.**

Later it says:

> All of the tables except promo_codes are geographically specific, and updated very frequently. For these tables, **the right table locality for optimizing access to their data is REGIONAL BY ROW.**

## Suggested Resolution 

Change the first reference to match the second one, which is correct.  So change the first one to:

> All of the tables except promo_codes have a composite primary key of city and id, in that order. This means that the rows in these tables are ordered by their geography. These tables are read from and written to very frequently. To keep read and write latency low, **you'll use the REGIONAL BY ROW table locality pattern for these tables.**

**Comment by jseldess** [comment]
@rmloveland, PTAL.
