### ISSUE TITLE
Working with Spatial Data Doc Update 

### ISSUE THREAD

**Issue by stbof** [cockroachdb/docs#11785]
Re: [Working with Spatial Data](https://cockroachlabs.com/docs/v20.2/spatial-data.html#performance)

## Issue Description

Incomplete sentence:

> The syntax for adding an index to a geometry  column is. 

Incorrect reference to tornadoes database which should be tornadoes table:

> For example, to add an index to the geom column of the sample tornadoes database:
> 
> CREATE INDEX tornado_geom_idx ON tornadoes USING GIST (geom);
> 

## Suggested Resolution 

The syntax for adding an index to a geometry column is `CREATE INDEX index_name ON table_name USING GIST (column_name);`

For example, to add an index to the geom column of the sample tornadoes table:

**Comment by jseldess** [comment]
@rmloveland, PTAL.
