### ISSUE TITLE
Connection string examples

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1181]
We currently have [drivers listed](https://www.cockroachlabs.com/docs/install-client-drivers.html), as well as connection strings as part of code samples ([example](https://www.cockroachlabs.com/docs/build-a-java-app-with-cockroachdb.html)), but we do not have connection string examples for simple copy/pasting.

See a use for this because of a large volume of searches for "connection string" related to different databases.

**Comment by jseldess** [comment]
Thanks for adding this, @sploiselle. So are you thinking a separate page with these examples, where the connections strings just have placeholders?

**Comment by knz** [comment]
I think this was addressed by #2853?

**Comment by jseldess** [comment]
Yep. Thanks, @knz!
