### ISSUE TITLE
Rolling upgrade (zero-downtime upgrades)

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1182]
- Conceptual doc for "upgrades" with notion of taking down one node at a time, replacing binary, and rejoining cluster.
- ASCII cast showing taking node down, upgrading binary, rejoining cluster
- Documentation for each environment/deployment because this is automatable.

**Comment by jseldess** [comment]
Thanks for adding thisk @sploiselle . We definitely need it for 1.0.

**Comment by jseldess** [comment]
First bullet is done. Tracking the second two in https://github.com/cockroachdb/docs/issues/1559.
