### ISSUE TITLE
Datacenter migration

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1183]
How to migrate off of an existing datacenter:
1. Ensure all nodes have properly locality flags set (possible for existing clusters with rolling restart adding locality flags), or possibly some other flag.
2. Set zone config to not replicate to that datacenter––data eventually moves off of old servers onto new.

@jseldess: Does this sound feasible from your understanding of zone configs? Was an off-handed mention today and can't find an issue regarding it (other "migration" issues are related to schema migration, not moving physical storage).

**Comment by jseldess** [comment]
Yep, that sounds right to me. And you're right; that scenario isn't covered anywhere. 

Basically, you could start with [this example](https://www.cockroachlabs.com/docs/configure-replication-zones.html#even-replication-across-datacenters) and add a second step (add the locality you don't want as a prohibited constraint in a zone config or something similar).

**Comment by jseldess** [comment]
In the meantime, we added a Cloud Migration tutorial, which demonstrates these principles, but with a focus on deploying across different clouds. It would be easy to add another tutorial to demonstrate migration across datacenters, though the process is virtually identical, just with diferrent locality settings.

**Comment by jseldess** [comment]
On second thought, for now, I think we can just add a note to the cross-cloud migration doc explaining that the exact same principles and approach applies to cross-datacenter, with different `--locality` settings.

**Comment by jseldess** [comment]
@taroface, old issue worth keeping on the backlog, but I don't think it's priority.

**Comment by jseldess** [comment]
Closing for now. If this becomes an important topic again, we can revisit.
