### ISSUE TITLE
Should not ignore EMPTY expression when generate RR diagram

### ISSUE THREAD

**Issue by ppggff** [cockroachdb/docs#1185]
Production 'opt_interleave':
```
opt_interleave:
  INTERLEAVE IN PARENT name '(' name_list ')' opt_interleave_drop_behavior
  {
    $$.val = &InterleaveDef{
               Parent: NormalizableTableName{UnresolvedName{Name($4)}},
               Fields: $6.nameList(),
               DropBehavior: $8.dropBehavior(),
    }
  }
| /* EMPTY */
  {
    $$.val = (*InterleaveDef)(nil)
  }
```

When generating individual RR diagram for 'opt_interleave', the 'EMPTY' expression
is ignored. See [https://www.cockroachlabs.com/docs/create-table.html#expanded](create_table)
for the result.

I tried to find the reason: it maybe caused by function `split()` in `extract.go`. When
dealing with empty expression, it returns empty array.

**Comment by jseldess** [comment]
@mjibson, is this issue still valid? If so, I'll recreate in the cockroach repo.
