### ISSUE TITLE
Time synchronization instructions per cloud provider

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1187]
See https://github.com/cockroachdb/cockroach/issues/13808#issuecomment-286390103, which focuses on Azure.

**Comment by jseldess** [comment]
From chat with client:

Quote from Jepsen: 
> Like Spanner, Cockroach's correctness depends on the strength of its clocks. If any node drifts beyond the clock-offset threshold (by default, 250 ms), all guarantees are basically out the window.

What exactly does `all guarantees are out the window` mean in practice? 

Raphael 'kena' Poss: 
> The default has been bumped to 500ms, btw, and the nodes will spontaneously abort when they detect a drift half of the configured value. The guarantees here are that of serializable consistency. You can then get stale reads and write skews

Spencer Kimball:
> The guarantee you lose is that you may fail to read a value that was written before the read started.

Ben Darnell:
> there's an issue filed for clockless mode (https://github.com/cockroachdb/cockroach/issues/14093), but no plans to implement it at this point. the cost would be that reads can no longer be served from a single node, you'd have to talk to a quorum for every read 

Spencer Kimball:
> But as @knz says, it's very difficult to experience that issue in practice as we are constantly measuring clock offsets and have a more than generous default max offset. You would need to have a node's clock jump suddenly by more than 500ms, and even then, you would be facing only 3s window of vulnerability. NTP should keep your clock offsets within 10s of milliseconds.

**Comment by mberhault** [comment]
The issue addressed by #13808 is supposed to be fixed soon, making that workaround no longer needed.

**Comment by jseldess** [comment]
Give that the Azure workaround is no longer needed, closing this issue in favor of #960.
