### ISSUE TITLE
Render Liquid templates before the remote_include plugin is run.

### ISSUE THREAD

**Issue by stbof** [cockroachdb/docs#11895]
Stephanie Bodoff (stbof) commented:

This works: {% include {{ page.version.version }}/sql/combine-alter-table-commands.md %}

but this fails: 

{% remote_include https://raw.githubusercontent.com/cockroachdb/generated-diagrams/release-{{ page.version.version }}/grammar_svg/add_column.html %} 

with   Liquid Exception: bad URI(is not URI?): "https://raw.githubusercontent.com/cockroachdb/generated-diagrams/release-{{ page.version.version }}/grammar_svg/add_column.html" in v21.1/add-column.md

Jira Issue: DOC-1220

**Comment by ianjevans** [comment]
Looks like there's already an issue for this in the plugin repo with a potential fix.
https://github.com/ianjevans/jekyll-remote-include/issues/4
