### ISSUE TITLE
restore: describe restoring across major versions

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/docs#11894]
Matt Sherman (shermanCRL) commented:

It seems we don’t document our support for restoring across major versions, by which I mean (say): backup in a v20.2 cluster → restore in a v21.1 cluster.

On [this page](https://www.cockroachlabs.com/docs/stable/restore.html), let’s mention our guarantees. @dt @livlobo do we have existing written guarantees? I haven’t found any.

Additionally, let’s also document what possibly-surprising issues to expect when doing a restore across major versions.

For example, we have a client migrating, via backup & restore, from v20.1 → v21.1. They discovered that some queries were slow on the new version, and we believe it’s due to the fact that table stats restored from the old version are suboptimal in the new version.

This will resolve itself, as the RESTORE process automatically triggers a stats update. That update may take some time, however. The user can simply wait (recommended), or if they have a more urgent need, they can trigger status update manually (potentially expensive in the short term).

Jira Issue: DOC-1221

**Comment by kathancox** [comment]
https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1635536670096800
