### ISSUE TITLE
certs: provide openssl commands to generate cockroach-compatible certs.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#119]
For each `cockroach cert` command, we need the  equivalent openssl command.
This will provide clarity into what the cert commands do, allow paranoid users to use a familiar tool instead, allow easier integration with existing certs-generating tools, and allow more complex scenarios (eg: real CA instead of self-signed).

**Comment by jjzazuet** [comment]
Yes, please. Thanks!

**Comment by jseldess** [comment]
@mberhault, are you still planning to draft up docs here? If so, any updates?

**Comment by sploiselle** [comment]
@mberhault I know OpenSSL is maybe-the-least-fun thing in the world to work with (_"I'd rather write in binary!"_, I hear you say)––is there any chance I could get even a dump of a list of commands you might use that I could fashion into documentation, though?

**Comment by mberhault** [comment]
I've started working on that. The PR listed above shows how to generate the CA cert and key with the same fields (almost). I'll add node and client certs to that as well.

**Comment by mberhault** [comment]
The PR above has openssl equivalents for all `cockroach cert` commands. You'll notice that it needs three config files and 5 fairly verbose commands (8 if you include key creation, but in the example I just reuse the cockroach ones to make certificate comparison better).

I'm happy to add comments clarifying everything, and I definitely can't claim that this is the cleanest or shortest way to do it. @bdarnell: how's your openssl-fu?

**Comment by mberhault** [comment]
Moved PR to #1804

**Comment by bdarnell** [comment]
>  @bdarnell: how's your openssl-fu?

In this area, just cargo-culting. I think when I've done this in the past I've used command-line args instead of config files for the `openssl req` command, so the CA is the only thing that needs a config file.

**Comment by mberhault** [comment]
Yeah, I tried going that way, but then you end up sticking the DN and altSubjectName in ugly-looking args.

**Comment by jseldess** [comment]
@Amruta-Ranade, here's the issue to document the openssl commands for cockroach-compatible certs. See also Marc's draft PR linked above.

**Comment by Amruta-Ranade** [comment]
Docs that might need to be updated:

- Create security certificates
- Rotate certificates
- Start a local cluster (secure)
- Create user
- Create and manage users
- Manual deployment
- Deploy CockroachDB on AWS, Azure, Digital Ocean, GCE

**Comment by jjzazuet** [comment]
Hi. Just a quick follow-up on https://github.com/cockroachdb/cockroach/issues/16455 . Is it still strictly necessary for a node's certificate to specify it's X.520 `commonName` attribute as `node` for the node to be able to join a cluster?

I'm evaluating the option of creating/maintaining node certificates with [https://letsencrypt.org/](Let's Encrypt), but I'm not sure if `cert-bot` allows to request a different common name for a node's certificate.

Thanks again!

**Comment by mberhault** [comment]
Unfortunately it is, because node certificates are dual purpose server/client certs. The client username (always `node` for cockroach nodes) is stored in `CommonName`.

Let's Encrypt can't do client certificate or non-public certificates (since it can't verify the authenticity of either). However, one thing that would be nice is to allow for a separate certificate for the admin UI, and that could be from Let's Encrypt given externally-reachable addresses. We actually have this one filed already: https://github.com/cockroachdb/cockroach/issues/14272

**Comment by jjzazuet** [comment]
@mberhault well I guess it's back to DebOps PKI support then. Thanks!
