### ISSUE TITLE
Surface core value props earlier in getting started

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1191]
New users do not appear to understand the meaning behind adding new nodes. Wrap in an explanation of what adding new nodes mean, and surface earlier that the SQL client is built-in.

**Comment by kuanluo** [comment]
Totally agree. 

Another place to add an explanation might be where we talk about how to kill a node. A short sentence or two on how the data survives with a node down would be beneficial in understanding the core value props.
