### ISSUE TITLE
document meaning of metrics in the admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1192]
A lot of confusion around what replicas per range mean. We discussed a while back potentially having docs involved in editing "info" tags that explain different metrics in the admin UI.

@kuanluo

**Comment by kuanluo** [comment]
We have this issue: https://github.com/cockroachdb/cockroach/issues/13766. The same thing you're thinking, @dianasaur323?

**Comment by dianasaur323** [comment]
Yes! Perfect - @jseldess I assume you have an issue open to document the admin UI outside of the actual UI as well? If so, we can close this issue out.

**Comment by jseldess** [comment]
Duplicate of https://github.com/cockroachdb/docs/issues/384.
