### ISSUE TITLE
Document /debug and other debugging tools

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#1197]
Some users have requested information about how to use the various debugging tools available within CockroachDB to look into problems with their queries or with the system's health. A core dev or two that have a lot of debugging experience should write up some documentation or at least a blog post with examples in the time leading up to 1.0 after feature freeze.

@cockroachdb/core

**Comment by tamird** [comment]
Related to https://github.com/cockroachdb/docs/issues/1190.

**Comment by jseldess** [comment]
@petermattis's training material should serve as the basis here.

**Comment by jseldess** [comment]
With @kuanluo, decided that we should add a quick overview of the `/debug` page somewhere in docs, following up later with deeper explanations and examples. 

@a-robinson, what other developer-facing debug tools should we eventually document?

**Comment by a-robinson** [comment]
The /debug pages is the biggest one. `cockroach debug zip` would be nice (although it looks like https://github.com/cockroachdb/docs/pull/1469 will cover that). The troubleshooting docs that @sploiselle wrote up are great. The internal doc that Peter wrote up is probably the most comprehensive resource we have of developer-facing debug tools.

**Comment by jseldess** [comment]
@dianasaur323, @Amruta-Ranade mentioned that we're going to polish and expose our `/debug` pages for 2.0. Is that right? If so, we should discuss how to document these. In my opinion, debug docs are probably higher value than some other admin ui docs (updating graphs, etc.). Should I set up a meeting to discuss?

**Comment by dianasaur323** [comment]
Sure, there are just 3 pages I think are worth documenting, so we can do those.

**Comment by jseldess** [comment]
Since this issue is broader than just debug pages, I created a separate issue to document the 4 pages we're exposing in 2.0: https://github.com/cockroachdb/docs/issues/2373

**Comment by jseldess** [comment]
At this point, this is mostly about debug pages, so closing this in favor of https://github.com/cockroachdb/docs/issues/3399.
