### ISSUE TITLE
CREATE USER Doc Update

### ISSUE THREAD

**Issue by alistair-roacher** [cockroachdb/docs#12016]
Alistair Parry (alistair-roacher) commented:

Re: [CREATE USER](https://cockroachlabs.com/docs/v21.1/create-user.html)

## Issue Description
The railroad diagram in the synopsis only shows the use of the password option - there are lots of other options that can be specified (such as CREATELOGIN and VIEWACTIVITY) and the use of multiple options is not shown.

## Suggested Resolution 
Update the railroad diagram to show the use of options other than password and the use of multiple options.

Jira Issue: DOC-1191

**Comment by ericharmeling** [comment]
Solving https://github.com/cockroachdb/docs/issues/11723 should also solve this issue (at least in 21.2).
