### ISSUE TITLE
sql: collated strings, phase three

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1206]
PR: https://github.com/cockroachdb/cockroach/pull/13609

**Comment by jseldess** [comment]
@sploiselle, can you take this? Not sure what needs to be added to our existing docs on collation.

**Comment by sploiselle** [comment]
@jseldess Thanks for taking this!

**Comment by jseldess** [comment]
Np. Did the bare minimum, really. Let me know if you think we need more examples showing collation with indexes.
