### ISSUE TITLE
Docker: Explain how to use `cockroach` commands from CLI

### ISSUE THREAD

**Issue by lykfe** [cockroachdb/docs#1207]
I wish you guys can update the tutorial for ppl who have instantiated CRDB in docker or in any case where they aren't able to install cockroach globally to leverage the cockroach command. 

For Ex) 
`cockroach user set maxroach` => is also equivalent as `docker exec -it roach1 ./cockroach user set maxroach`
or even get into bash by `docker exec -it roach1 ./cockroach bash`

Thanks :)

**Comment by jseldess** [comment]
Thanks for opening this issue, @lykfe. We're working on a Windows binary, which will drastically simplify the usage/deployment process on Windows. I'm optimistic that'll happen soon, but if it doesn't, we'll be sure to add this additional guidance.

**Comment by jseldess** [comment]
Windows binary is available at this point. We don't have plans to expand the build an app tutorials to cover docker guidance.
