### ISSUE TITLE
allow the left nav bar to collapse

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/docs#1208]
When looking at the docs on smaller screen and when you want a view with a small width, it takes over instead of showing the doc you're looking at.

For example, after shrinking the width of my browser, instead of seeing the doc, I see this:
<img width="788" alt="screen shot 2017-03-19 at 12 54 56" src="https://cloud.githubusercontent.com/assets/1614265/24084228/68dcecda-0ca3-11e7-9ebf-aefeb97ec388.png">

**Comment by jess-edwards** [comment]
@jseldess This is something we can get DivisionOf's help on. 

@kuanluo When the homepage is finished, do you think we pitch this to DivOf?

**Comment by jseldess** [comment]
OK, that'd be great, @jess-edwards! @kuanluo, we should probably think through some basic design recommendations before sending the work to DivO. Let me know when you're free for this.

**Comment by kuanluo** [comment]
Yes, definitely. @jseldess, if you have recommendations, I'd love to hear them. Just grab me at my desk, or send me an invite.

**Comment by jseldess** [comment]
@kuanluo, assigning this to you for now, since you're driving the effort.

**Comment by kuanluo** [comment]
Sounds good, thanks @jseldess! The improvement is going to dev this week, and should be live by the end of next week.

**Comment by sploiselle** [comment]
Closed by #1301
