### ISSUE TITLE
Update build-from-source instructions to use source tarball

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1209]
Only relevant once our next beta goes out with a source tarball.

**Comment by benesch** [comment]
Ok, @jseldess, this is finally ready! Here are the new steps:

1. The prerequisites are the same, but we can drop the part about setting `$GOPATH` and `$PATH`. 
2. Download the [latest CockroachDB source archive](https://binaries.cockroachdb.com/cockroach-latest.src.tgz).
3. Extract the sources:

    ```bash
    $ tar xfz cockroach-latest.src.tgz
    ```

4. In the extracted directory, run `make`:

   ```bash
   $ cd cockroach-latest
   $ make
   ```

   The build process can take 10+ minutes, so please be patient. The first time you run make, it can take even longer to download and install various dependencies.

5. Move the binary onto your `PATH`, so it's easy to execute cockroach commands from any shell.

    ```bash
    cp -i ./pkg/cockroach /usr/local/bin
    ```

    If you get a permissions error, prefix the command with `sudo`.

**Comment by jseldess** [comment]
Great. Thanks, @benesch. I'll open a PR soon. Think I'll also include a link to the cockroach `CONTRIBUTING.md` file for developers who want to build from source for development purposes.

**Comment by benesch** [comment]
Makes sense!
