### ISSUE TITLE
Update remote_include URLs to point to named cockroach branch

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#12136]
In `docs/v21.2/functions-and-operators.md` and `docs/v21.2/cluster-settings.md`, update the remote_include urls to point to the named `release-21.2` branch instead of to `master`.

**Comment by jseldess** [comment]
This is done, I believe. @ianjevans, do you know if there are other pages where we'll need to do this ahead of the GA release?

**Comment by ianjevans** [comment]
The logging topics in v21.2 point to `master`.

~~~
$ ag --md "remote_include https://raw.githubusercontent.com/cockroachdb/cockroach/master"
log-formats.md
7:{% remote_include https://raw.githubusercontent.com/cockroachdb/cockroach/master/docs/generated/logformats.md %}

logging.md
7:{% remote_include https://raw.githubusercontent.com/cockroachdb/cockroach/master/docs/generated/logging.md %}

eventlog.md
7:{% remote_include https://raw.githubusercontent.com/cockroachdb/cockroach/master/docs/generated/eventlog.md %}
~~~

I remember @stbof ran into an issue with changing some of the `remote_include` URLs to point to the release branch, but I can't remember the exact issue.

**Comment by stbof** [comment]
See https://github.com/cockroachdb/docs/pull/11920#discussion_r729214331.

**Comment by jseldess** [comment]
Thanks, @stbof and @ianjevans. Let me open a PR and take a look. If we don't update the links in the source, we could put redirects in place.
