### ISSUE TITLE
Update SQL feature support reference docs for v21.2

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#12148]
[PostgreSQL Compatibility](https://www.cockroachlabs.com/docs/v21.2/postgresql-compatibility.html)
[SQL Feature Support](https://www.cockroachlabs.com/docs/v21.2/sql-feature-support.html)

**Comment by vy-ton** [comment]
I cross-referenced these pages with the SQL roadmap and propose these changes:

- `Full-text indexes` change from "Planned" to X for unsupported for now
- `Expression index` which @stbof is already addressing
