### ISSUE TITLE
Replace docs search feature

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#1217]

**Comment by mjibson** [comment]
@jseldess I attempted this but ran into a problem: our docs pages CSS overrides the default `table` CSS stylings. The Google results use `table` elements, and so they looked messed up on our page. I see two solutions:

1. We just redirect to google.com.
2. Someone fixes the CSS. This is not an easy change because it would require auditing all the uses of `table` on the site to figure out how to keep them correct and also allow the google tables to work. The docs CSS is kind of a mess because we have custom CSS, bootstrap CSS, and something called lavish CSS (which is some theme or something on bootstrap, but it's like not a strict subs or super-set of bootstrap so it's not easy to remove. I looked into this once a decided I didn't want to fix it). Doing a CSS deep dive and refactor is not something I'm going to do unless the sky is falling.

**Comment by jseldess** [comment]
Thanks for looking into this, @mjibson. Fortunately, the sky isn't falling; we have a year to move over. 

In the meantime, @kuanluo, once DivisionOf does a style audit between the site and docs, perhaps a next step could be to get them to help us cleanup/simplify the css. If we can get them for that, @mjibson, perhaps you could give guidance in terms of what we want the end-state to look like?

**Comment by kuanluo** [comment]
Yup, that's what I'm planning on, @jseldess. And if @mjibson is available, some guidance to Div/Of would be incredibly useful. Let me know!

**Comment by mjibson** [comment]
I'm not really qualified to give much guidance here. Decisions like "how do we want our CSS organized" should be done by a person who has experience doing frontend/design stuff. I can describe a feature we want, which is that we want the CSS rules to uses classes instead of only raw elements, which would fix the above bug. Beyond that, I'm not sure.

**Comment by jseldess** [comment]
Point taken, @mjibson, but in addition to sharing details about that bug with DivisionOf, I think your insights about our current css mess would be a good starting point for a cleanup by DivisionOf. A lot of the mess comes from the theme I chose when I started, and how we messily built on that subsequently.

**Comment by jseldess** [comment]
@kuanluo, just fyi, this is definitely something for the web dev, once that's filled.

**Comment by kuanluo** [comment]
@jseldess Sounds great, totally agree.

**Comment by jseldess** [comment]
@mjibson, do you remember what I might have meant by "CSE 2.0 API" here? I'm finding nothing on that when I search for alternatives to Google Site Search, for example, https://www.impactbnd.com/blog/3-life-saving-alternatives-to-google-site-search

**Comment by mjibson** [comment]
I don't know where I got CSE from, but it's Google Custom Search.

**Comment by jseldess** [comment]
According to the red note at the bottom of [this page](https://support.google.com/customsearch/answer/4541888?hl=en), "Google Site Search will be completely shut down by **April 1, 2018**." @kuanluo, that means this isn't an urgent project for Q4. But if we hire a web dev, it would be good to start looking at alternatives so we can implement something in Q1.

**Comment by kuanluo** [comment]
@jseldess That's fairly soon! I will prioritize that after we make the hire. Thanks for finding out the info.

**Comment by jseldess** [comment]
Google API for search: https://developers.google.com/custom-search/json-api/v1/overview

**Comment by j-low** [comment]
@mjibson @jseldess @kuanluo, I went digging into this a bit more and I don't think we can go the Google route here.  As far as I can tell there is no version of Custom Search that is free and also unbranded/doesn't use AdSense.  The link that @jseldess indicated points to an API that hits Custom Search but requires either the free version (AdSense) or the paid version (currently in sunset) to be implemented.  So I think this ultimately will require us to go with a solution outside of Google.  If any of this doesn't sound correct please let me know.

**Comment by mjibson** [comment]
Note that we can always have our search bar just redirect to google with a site: tag. Yes, it causes people to leave the site, but it does work and is free. Just something to keep in mind as a compromise or backup.

**Comment by jseldess** [comment]
Thanks for the update, @j-low. In your research, have you found good potential alternatives? It's definitely preferable that we retain a search experience that keeps users on our site when they're using our search (as opposed to going directly to google).

It might be best for you to compile some alternatives and then schedule a meeting with @jess-edwards, @kuanluo, myself, and @mjibson.

FYI, the [aerospike docs](https://www.aerospike.com/docs/) used to use google site search like us, and now they're using something else. Might want to check into that. 

@bdarnell, what search does read the docs use, for example, on your [tornado docs site](http://www.tornadoweb.org/en/stable/search.html?q=get+started&check_keywords=yes&area=default)?

**Comment by jseldess** [comment]
Nevermind, @bdarnell, just found the answer: http://docs.readthedocs.io/en/latest/features.html?highlight=search#search

**Comment by j-low** [comment]
@jseldess, I did some research over the previous week and put together some rough notes on each including pricing and some breakdown of the features.  Almost all of them actively market themselves as an alternative to GSS. I'd be happy to review some of these in a meeting context.  I'll also look into Aerospike in the meantime.

**Comment by bdarnell** [comment]
@jseldess That readthedocs feature applies to the global search box on readthedocs.org, not the search boxes on individual doc pages (as far as I can tell - at least the tornado one is not using the RTD feature)

The tornado docs search is actually a feature of [sphinx](http://www.sphinx-doc.org/en/stable/contents.html). It's hardly documented at all, just [mentioned in passing in the sphinx configuration docs](http://www.sphinx-doc.org/en/stable/config.html#options-for-html-output). If we move to sphinx, we'd get this search for free; if we don't make the switch then it probably wouldn't make sense to try to use it from jekyll (although there are probably jekyll plugins with a similar implementation)

**Comment by jseldess** [comment]
Ah, thanks for clarifying, @bdarnell. I doubt we'll be able to move to Sphinx before the Google Site Search expires, but that's a larger project that @j-low is looking into.

**Comment by jseldess** [comment]
This is done. Closing.
