### ISSUE TITLE
Connection string instructions refer to <cluster-name> instead of <cluster-id>

### ISSUE THREAD

**Issue by stbof** [cockroachdb/docs#12221]
https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-a-serverless-cluster#step-2-connect-to-your-cluster

Steps 3 and 4 have the variable `<cluster-id>`, 

`curl --create-dirs -o ~/.postgresql/root.crt -O https://cockroachlabs.cloud/clusters/<cluster-id>/cert`

`cockroach sql --url 'postgresql://<username>:<password>@<serverless-host>:26257/defaultdb?sslmode=verify-full&sslrootcert='$HOME'/.postgresql/root.crt&options=--cluster=<cluster-id>'`

but the text after refers to `<cluster-name>`

`<cluster-name>` is the short name of your cluster plus the tenant ID. For example, funny-skunk-3. The <cluster-name> is used to identify your tenant cluster on a multitenant host.

**Comment by gemma-shay** [comment]
Closing and moving to Jira https://cockroachlabs.atlassian.net/browse/CC-5363
