### ISSUE TITLE
Configure logs Doc Update

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#12270]
Jessie Lin (lin-crl) commented:

Re: [Configure logs](https://cockroachlabs.com/docs/v21.1/configure-logs.html)

## Issue Description
The default `max-group-size` is 100MiB and it's too probably too small, and logs roll off over weekend easily and makes troubleshooting difficult.

## Suggested Resolution 
Update the default value to a larger value for example 1GB. And/or put the change into the Production Check.

Jira Issue: DOC-1117

**Comment by taroface** [comment]
@lin-crl This default would need to be changed on the backend before the docs can be updated. Can I ask you to refile this issue on `cockroach`?

**Comment by lin-crl** [comment]
Sure @taroface I created this https://github.com/cockroachdb/cockroach/issues/72830

Could we make a change to the Production Checklist to change this value, before product changes the default value? Thank you!
