### ISSUE TITLE
server: windows builds do not need to set file descriptors limits

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1229]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/14447

No doc updates until we have a windows build, right, @BramGruneir?

Jira Issue: DOC-102

**Comment by BramGruneir** [comment]
Sure, it can wait.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
