### ISSUE TITLE
timestamp formats accepted by `./cockroach sql`

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/docs#123]
For future reference, we try each of the following formats in this order, falling to the next one if it doesn't work.

	dateFormat                            = "2006-01-02"
	timestampFormat                       = "2006-01-02 15:04:05.999999999"
	TimestampWithOffsetZoneFormat         = "2006-01-02 15:04:05.999999999-07:00"
	timestampWithNamedZoneFormat          = "2006-01-02 15:04:05.999999999 MST"
	timestampRFC3339NanoWithoutZoneFormat = "2006-01-02T15:04:05.999999999"

From https://github.com/cockroachdb/cockroach/blob/902ce2c5ed4f3cd029f3ad169c76cb37101f30b2/sql/parser/eval.go#L1562

**Comment by jseldess** [comment]
Fixed by PR #131
