### ISSUE TITLE
What's New in v20.2.18 Doc Update 

### ISSUE THREAD

**Issue by alistair-roacher** [cockroachdb/docs#12316]
Re: [What's New in v20.2.18](https://cockroachlabs.com/docs/releases/v20.2.18.html)

## Issue Description

The statement "Cockroach Labs will stop providing Assistance Support for this version on November 12, 2021" is not consistent with the date in https://www.cockroachlabs.com/docs/releases/release-support-policy

## Suggested Resolution 

Update this page to state that 
- Maintenance Support has already ended
- Assistance Support will end on 2022-05-10,

**Comment by lnhsingh** [comment]
@taroface - routing this to you since you did the v20.2.18 release notes
