### ISSUE TITLE
Add a warning for use case of Backup from MR DB restored into Non-MR DB

### ISSUE THREAD

**Issue by livlobo** [cockroachdb/docs#12338]
When a user takes a backup from a MR DB, they have no idea that they cannot restore it into a Non-MR DB. We should include a "warning" to that effect on the Backup page, Restore page and the Known limitations page -- for both 21.1 and 21.2 docs as well as Cockroach Cloud docs.

CC: @adityamaru

**Comment by gemma-shay** [comment]
Migrating to JIRA: https://cockroachlabs.atlassian.net/browse/CC-5433
