### ISSUE TITLE
Kubernetes doc links 404ing

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1233]
On [Orchestrate CockroachDB with Kubernetes](https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-kubernetes.html), the following links now 404:

- http://kubernetes.io/docs/user-guide/kubectl/kubectl_create/
- http://kubernetes.io/docs/user-guide/kubectl/kubectl_delete/
- http://kubernetes.io/docs/user-guide/kubectl/kubectl_get/
- http://kubernetes.io/docs/user-guide/kubectl/kubectl_scale/

**Comment by jseldess** [comment]
Fix was merged with PR https://github.com/cockroachdb/docs/pull/1213. Was buried in there. Should've handled it separately. Sorry.
