### ISSUE TITLE
Document consistency guarantees & anomalies

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1249]
Provide canonical documentation about terms related to consistency:
- Linearizability
- Serializability
etc.

Included in these definitions should be sensible explanations of database anomalies, narrated clearly/diagramed.

The goal in this would be to make it simple for amateur developers to clearly understand our consistency guarantees/options, as well as providing references for our future workshops/onboarding material.

Also includes opportunity to tackle #124.

**Comment by jseldess** [comment]
@sploiselle, think this is a 1.0 issue? If so, please apply that milestone.

**Comment by sploiselle** [comment]
Think it's related to this quarter's work, but I don't think it's a hard requirement to have this done by 1.0 launch.

**Comment by mwang1026** [comment]
closing in favor of #6306
