### ISSUE TITLE
Build a go app: include not rendered properly

### ISSUE THREAD

**Issue by huachaohuang** [cockroachdb/docs#1250]
For example, `{% include app/basic-sample.go %}` in [here](https://github.com/cockroachdb/docs/blob/gh-pages/build-a-go-app-with-cockroachdb.md) will be rendered to [this](https://www.cockroachlabs.com/docs/build-a-go-app-with-cockroachdb.html).

**Comment by jseldess** [comment]
Thanks for filing this. I'll fix this asap.
