### ISSUE TITLE
How to contribute code？

### ISSUE THREAD

**Issue by a1424360017** [cockroachdb/docs#12508]
Exalate commented:

null

**Comment by a1424360017** [comment]
I wrote a verification code with TLA +, how can I submit it to cockroachdb/cockroachdb/docs/tla-plus or somewhere else?

**Comment by jseldess** [comment]
@a1424360017, thanks for the question. Can you say more about the code that you would like to contribute? Is it for our docs site or for something else?

**Comment by a1424360017** [comment]
Thank you for your reply. I have solved the problem.
