### ISSUE TITLE
cli: haproxy config now includes `check`

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1253]
[Manual Deployment](https://www.cockroachlabs.com/docs/manual-deployment.html) guide needs to be updated to reflect cockroachdb/cockroach#14624

According to @mberhault the new `check` value at the end end of the `server` line simply enabled TCP checks, which are good so you know which instances are up or down.

**Comment by jseldess** [comment]
Might as well handle https://github.com/cockroachdb/docs/issues/1600 at the same time.
