### ISSUE TITLE
Update tutorial on Digital Ocean for v1

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1256]
https://www.digitalocean.com/community/tutorials/how-to-deploy-cockroachdb-on-a-three-node-cluster-on-ubuntu-16-04

Maybe be as little as removing reference to beta, but there may be more to do, too.

cc: @sploiselle, @jess-edwards

**Comment by jseldess** [comment]
@sploiselle, can you look into what needs to be changed when you have a few?

**Comment by sploiselle** [comment]
@benesch @bdarnell  Have we made any changes to the binary URLs yet?

**Comment by benesch** [comment]
Nope, not yet. cockroachdb/cockroach#15982 made it so that unstable
releases won't touch the existing latest link, so we're safe until 1.1.

**Comment by jseldess** [comment]
@sploiselle, I just reviewed the DO tutorial, and it seems that everything's still fine, with the exception of out-dated admin UI screenshots. If you can confirm, we can close this issue for now.

**Comment by jseldess** [comment]
@sploiselle, instead of closing this, I'm moving it to `later` since we'll eventually want/need to update the tutorial.
