### ISSUE TITLE
Too many categories in auto-generated function docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1258]
When you regenerate the functions page based on the current `cockroach` master, you get this:

![screen shot 2017-04-06 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/15893490/24770471/0e821204-1ad8-11e7-815c-b6dd13665072.png)

This is what we had before:

![screen shot 2017-04-06 at 2 40 19 pm](https://cloud.githubusercontent.com/assets/15893490/24770520/33ffa5a0-1ad8-11e7-8734-4a57f8dcb1e1.png)

**Comment by sploiselle** [comment]
cc @dt
