### ISSUE TITLE
core: Explicit init command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1288]
Background: 
  - https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recdaFNmgzO5oBwe7
  - RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/init_command.md

Owner: @bdarnell 

PRs: https://github.com/cockroachdb/cockroach/pull/16371

**Comment by jseldess** [comment]
@bdarnell , this is the overall docs issue for the init command work you're doing for 1.1. Once it's ready for docs, please assign the `ready` label and add relevant PR links?

**Comment by sploiselle** [comment]
Landed in cockroachdb/cockroach#16371

**Comment by jseldess** [comment]
Thanks for tracking this, @sploiselle!

**Comment by dianasaur323** [comment]
@jseldess do you mind letting me know when your docs for this land? It's the last feature on my list of features to acceptance test.

**Comment by jseldess** [comment]
Will do, @dianasaur323. Working on upgrade docs now. `init` is next.
