### ISSUE TITLE
sql: Support parallel statement execution using RETURNING NOTHING syntax

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#1290]
RFC: https://github.com/cockroachdb/cockroach/pull/13160
Implementation PRs:
- https://github.com/cockroachdb/cockroach/pull/14188
- https://github.com/cockroachdb/cockroach/pull/14553
- https://github.com/cockroachdb/cockroach/pull/14803
- etc.

The parallel statement execution feature can now be used and is demonstrating the expected speedups for target workloads (near-linear speedup for fully-independent statement sequences). I'm starting to write a blog post for this, but figured that we should have documentation for it as well before the post goes live.

**Comment by jseldess** [comment]
Thanks for adding, @nvanbenschoten. Sean and I won't have time to document this for the v1 release due to other doc priorities. If you feel the docs need to be there in time, would you be willing to create a draft doc for us?

**Comment by nvanbenschoten** [comment]
Thanks for the update @jseldess. I'll look into writing a draft doc alongside the blog post.

**Comment by jseldess** [comment]
@Amruta-Ranade, this blog post has a lot of relevant details as well: https://www.cockroachlabs.com/blog/local-and-distributed-processing-in-cockroachdb/

**Comment by Amruta-Ranade** [comment]
As per discussion during the docs weekly, need to add a note stating this is an experimental feature and should be used with care. (Discuss with Nathan in detail what exactly that entails, what precautions should the user take, and when should they not use the feature).

**Comment by andreimatei** [comment]
Well, I think I was wrong about cockroachdb/cockroach#17250, so stuff's not as broken. The parallel execution can still eat your data, but not in the easiest way I thought.

**Comment by nvanbenschoten** [comment]
Nice job @Amruta-Ranade 🎉 🎉
