### ISSUE TITLE
sql: Document `system` database

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1291]
Briefly mentioned in #1160, but the tables of the `system` database should each be documented.

We don't see many questions about this currently (so I don't think it meets the 1.0 milestone requirement), but think it warrants documentation.

Currently the only reference to the `system` database is in [Learn CockroachDB SQL](https://www.cockroachlabs.com/docs/learn-cockroachdb-sql.html), which says:

> CockroachDB comes with a single default system database, which contains CockroachDB metadata and is read-only.

**Comment by rmloveland** [comment]
I think this should be internal engineering/support documentation.  IIRC, users should not be doing anything with the `system` database other than knowing it exists and is used by the system.  What do you think @sploiselle ?  Can I convince you of this position?  🙂

**Comment by rmloveland** [comment]
> users should not be doing anything with the system database

After reading some internal discussion about tables that live in `system.*` I realize this is not a correct opinion. :-)

**Comment by rmloveland** [comment]
E.g., `DELETE FROM system.table_statistics WHERE name LIKE '%foo%';`

**Comment by ericharmeling** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/10340
