### ISSUE TITLE
backup/restore: document experimental `crdb_internal.jobs` table

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1293]
Just chatted with @jseldess, @danhhz, and @dianasaur323 and we thought it'd be worth documenting how to query progress of a `BACKUP` or `RESTORE` query. No rush on this.

The progress of backups and restores—and soon schema changes—is visible in the `crdb_internal.jobs` table. Note this does *not* include other types of queries, like long-running `SELECT`s. The columns are:

  * `id` — the ID of the job
  * `type` — the type of the job (currently `BACKUP` or `RESTORE`)
  * `description` — the query used to create the job
  * `username` — the user who created the job
  * `descriptor_ids` — the IDs of the tables impacted by the job
  * `status` — `pending`, `running`, `succeeded`, `failed` (`aborted` soon)
  * `created`, `started`, `finished` — the time of state transitions
  * `modified` — the last time this row was updated
  * `fraction_completed` — the approximate progress of this job
  * `error` — the error that caused the job to fail, if it failed

We don't currently have a good way of returning the job ID to users, unfortunately, so here's what I like to do:

```sql
SELECT id, type, created, username, description FROM crdb_internal.jobs ORDER BY created DESC LIMIT 5;
```

That lists the five most recent jobs, along with their type, creation time, creating user, and creating query. That's usually more than enough to identify the job. Once you have the job ID, you can query its status and completion progress:

```sql
SELECT status, fraction_completed FROM crdb_internal.jobs WHERE id = [job-id] LIMIT 1;
```

If you know you're the only one using a cluster, you can just blindly snag the fraction completed and status from the latest job.

```sql
SELECT id, status, fraction_completed FROM crdb_internal.jobs ORDER BY created DESC LIMIT 1;
```

We'll eventually return the job and progress information from `BACKUP` and `RESTORE` directly, but that requires streaming query responses, which we don't yet have support for.

FYI the above is all *experimental* and should be covered in warnings. The `crdb_internal.jobs` API will not be considered stable, even in 1.0.

+cc @sploiselle
+cc @jordanlewis putting this on your radar for when schema change support lands

**Comment by jseldess** [comment]
Closing in favor of #1517
