### ISSUE TITLE
cloud deployment

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#13]
Instructions for deploying a multi-node cluster in the cloud (at least AWS).

**Comment by uptimeDBA** [comment]
I've been working on a set of guides to set up a multi-node cluster with three configurations.

- A cluster on multiple VirtualBox machines using Vagrant
- A cluster on a single machine using Docker
- A cluster using EC2 instances on AWS using either CloudFormation or Teraform

The VirtualBox guide is about 80% complete while the others are TBD. I should have something for you to look at, if you're interested, in about 7 to 10 days. It's not online anywhere yet as it's currently a 23 page Microsoft Word document (lots of example outputs and diagrams). They will eventually end up in an online format somewhere, probably github.

**Comment by jseldess** [comment]
This is great, @uptimeDBA! 

For beta (end of quarter), we're aiming to have two tutorials, in addition to [starting up a local cluster](https://www.cockroachlabs.com/docs/start-a-local-cluster.html): Manual deployment (environment agnostic) as well as deploying to AWS (and probably other cloud providers) with terraform. I'm planning to draft those up this week. Might make sense for you to hold off until those are done so you have some final updates we're making to our cert commands? 

Really appreciate your interest in helping! 

cc @mberhault

**Comment by uptimeDBA** [comment]
Sounds good. I'll look at converting my guide(s) into something more web friendly. I guess github markdown is the way to go?

**Comment by jseldess** [comment]
Yep, we're using [Jekyl](https://jekyllrb.com/)l, which takes markdown files and layout files and builds a static site. We're using [kramdown](http://kramdown.gettalong.org/syntax.html) syntax in our markdown files. I'll aim to update the Readme with details about Jekyll, our basic style conventions, etc., hopefully this week. 

We'd definitely like to integrate your material and insights into our site, rather than see them posted elsewhere. I think these topics in particular will be different than what we're already planning to write:

- A cluster on multiple VirtualBox machines using Vagrant
- A cluster using EC2 instances on AWS using CloudFormation

We'll cover Terraform. And for running on a single machine using Docker, we cover installing using Docker, but I'd love your opinion about how the [Starting a Local Cluster](https://www.cockroachlabs.com/docs/start-a-local-cluster.html) page should be extended to cover that particular case.  

For now, feel free to fork our repo and start converting to markdown, as mentioned on our [Improve the Docs](https://www.cockroachlabs.com/docs/improve-the-docs.html) page. I think your topics will fit best on our cloud deployment page, but we can figure that out a bit later.

Thanks for the help!

**Comment by uptimeDBA** [comment]
I'm coming up to speed with Jekyll, kramdown, etc. For now, I'll put up my "cluster on multiple VirtualBox machines using Vagrant" guide on my own github in a few days for you to take a look at. I want to be happy with the format and flow of this one before I start on the EC2/AWS/Cloud-Formation one. We can look at combining my work latter if you like it.

**Comment by jseldess** [comment]
OK, sounds good. Thanks, @uptimeDBA. I just published a basic page on [manual deployment](https://www.cockroachlabs.com/docs/manual-deployment.html), including some recent updates to how certs work. Hope it's helpful. Please feel free to send thoughts and feedback.

**Comment by jseldess** [comment]
Closing this in favor of tickets for specific providers.
