### ISSUE TITLE
interleaved tables - commonly asked questions

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1302]
When is it appropriate to use them? 

Ans: Any time your tables are hierarchical, interleaving them can be a big performance win. You cannot interleave in an "alter table" statement. You have to do it upon table creation.

**Comment by sploiselle** [comment]
We have something like this [in the docs](https://www.cockroachlabs.com/docs/interleave-in-parent.html#when-to-interleave-tables).

**Comment by dianasaur323** [comment]
Perfect, you have exactly what they asked. As we start getting more users though, we should see if they keep asking and use that velocity to optimize docs. Closing out.

**Comment by jseldess** [comment]
Reused Sean's text on a new SQL FAQs page as well, as part of https://github.com/cockroachdb/docs/pull/1315
