### ISSUE TITLE
Stop displaying the "sign up for our newsletter" popup on phones

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#1308]
@jseldess & @sploiselle 

Having now tested the docs site on a phone multiple times in the last few days, I've noticed how annoying the newsletter modal is. The x to close out is pretty small, and Safari on iOS does not allow third party cookies, so the "do not show again" setting is moot. 

What do you think of setting it to not display on phones?

**Comment by sploiselle** [comment]
+1

**Comment by jseldess** [comment]
+1 from me, too. Do you want to punt this to Division Of, or should I?

**Comment by jess-edwards** [comment]
@jseldess please go for it.

**Comment by jseldess** [comment]
Opened an issue with Division Of: https://app.asana.com/0/96629601608286/324409183002100
