### ISSUE TITLE
security: certificate rotation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1319]
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/certificate_rotation.md
PR: https://github.com/cockroachdb/cockroach/pull/14925

**Comment by jseldess** [comment]
@mberhault, will need your help with this next week.

**Comment by mberhault** [comment]
Please see PR #1331 for a draft doc about certificate rotation.

The actual reload of certificates is fairly easy and short.
However, I spend some time detailing the process to renew all certificates at about the same time which can cause issues if done improperly.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/1499.
