### ISSUE TITLE
Index of Terms (Glossary)

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1323]
Updating and making externally availably our internal glossary could help users understand CockroachDB more easily. e.g. _node_, _cluster_, _ranges_

**Comment by rmloveland** [comment]
I came to create this ticket, glad to see it exists!

A specific way this could make things better for users (in addition to providing the info, ofc) is that we could perhaps build the glossary from `include`s to ensure that all definitions are using the best possible version in all places.

E.g., a term could have the following structure (say):


- Short description, suitable for includes
- Longer example with diagrams (shown only on main glossary page).  Diagrams are pretty key to understanding this stuff IMO (and we use them in a bunch of presos so I think we agree).

**Comment by rmloveland** [comment]
Working on #2282 and would find this useful for linkable definitions of range, range lease, leaseholder, etc.

**Comment by jseldess** [comment]
Thanks for resurrecting this, @rmloveland. This sounds like a good project and approach. Is this something you'd like to take a shot at now?

You're right that we do have some basic definitions in a few places already. This is probably the closest to the beginnings of a glossary: https://www.cockroachlabs.com/docs/stable/architecture/overview.html#glossary

**Comment by rmloveland** [comment]
> Is this something you'd like to take a shot at now?

Sure, my assumption is it will slot in behind the current prio items #2282 and #2729  - let me know if that works!

**Comment by jseldess** [comment]
Let's make this a 2.1 project (that can already be started). Note that we have a [large internal glossary](https://docs.google.com/document/d/1JCU0A8ut5nF_lsB-NPkq3OpV07RPERFvwvrFeT1KhTk/edit) that an external contributor made early on in the project. I don't think we want to emulate it, but it's probably good to check out.

**Comment by jseldess** [comment]
@lhirata to link to another internal example.

**Comment by lhirata** [comment]
This is the glossary I was thinking of: https://github.com/cockroachdb/cockroach/wiki/Jargon

Covers a lot of stuff and is good for database noobs (like myself). Not sure if all of it should be included in the new glossary though.

**Comment by jseldess** [comment]
Officially moving this out of scope, given that we're half-way through the release cycle and will need time for other higher priority docs projects and product work.

**Comment by taroface** [comment]
References:

- https://wiki.crdb.io/wiki/spaces/CRDB/pages/73072850/Jargon+CockroachDB+words+for+non-tech+people
- https://docs.google.com/document/d/1JCU0A8ut5nF_lsB-NPkq3OpV07RPERFvwvrFeT1KhTk/edit

**Comment by jseldess** [comment]
Glossary tooltips: https://docs.echo-security.co/mydoc_adding_tooltips.html

**Comment by jseldess** [comment]
Using data file for tooltips: https://idratherbewriting.com/documentation-theme-jekyll/mydoc_adding_tooltips.html

Using same data file to create glossary entries: https://idratherbewriting.com/documentation-theme-jekyll/mydoc_glossary.html

**Comment by jseldess** [comment]
Closing for now. Adding a glossary is a big project. If it becomes a priority, we'll open a new issue.
