### ISSUE TITLE
Add psql example, including secure mode

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#1324]
We should list an example to use `psql` against cockroach.
The main difference I'm aware of is that we need to specify `sslmode=verify-ca` instead of `sslmode-verify-full` when in secure mode.
See [this forum post](https://forum.cockroachlabs.com/t/psql-remote-connection-certificate-not-valid/584) for details

**Comment by bdarnell** [comment]
We have an [acceptance test that uses `psql`](https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/psql_test.go), and I think it [uses secure mode](https://github.com/cockroachdb/cockroach/blob/f06c35dbb3556aba980b3e8bf377c64c5a95600b/pkg/acceptance/util.go#L526). Is this test doing the right thing?

**Comment by mberhault** [comment]
I'm not sure they even are using secure mode, but I need to dig into it further.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
