### ISSUE TITLE
Please Add Prism ORM to https://www.cockroachlabs.com/docs/v21.2/install-client-drivers.html

### ISSUE THREAD

**Issue by rainleander** [cockroachdb/docs#13245]
Rain Leander (rainleander) commented:

The Prisma ORM is listed https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb-prisma.html but not within $SUBJECT and was specifically listed as 'missing' from the ORM list by a community member this past Friday.

I'm not sure with which versions of CockroachDB it is compatible or I'd add it myself.

Please let me know how I may be of further assistance.

Jira issue: CRDB-13760

Jira Issue: DOC-2904

**Comment by otan** [comment]
fwiw, it should be available *in preview* for v21.2, but i'd say v22.1 (upcoming) is the real first supported version

**Comment by otan** [comment]
also cc @kernfeld-cockroach

**Comment by kernfeld-cockroach** [comment]
Can we remove the "install client drivers" page entirely? The information appears to be a subset of knowledge that's already available in more detail elsewhere on our site.

**Comment by ericharmeling** [comment]
> Can we remove the "install client drivers" page entirely? The information appears to be a subset of knowledge that's already available in more detail elsewhere on our site.

Big fan of this idea. Made a new issue to do that.

> The Prisma ORM is listed https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb-prisma.html but not within $SUBJECT and was specifically listed as 'missing' from the ORM list by a community member this past Friday

I'd rather remove the "Install a Driver or ORM Framework" page. Prisma Client is currently listed in our [Third-Party Tools Supported by Cockroach Labs](https://www.cockroachlabs.com/docs/v21.2/third-party-database-tools.html) page.

**Comment by ericharmeling** [comment]
> If we do remove this page, we'll need a redirect; it's cached solidly on several search engines - but only if all of the drivers available somewhere else in a central location - if they're available all over, we need to be careful about removing a central hub page.

I will definitely add a redirect to the [Third-Party Tools Supported by Cockroach Labs](https://www.cockroachlabs.com/docs/v21.2/third-party-database-tools.html) page. That page is the "central hub page" for our tooling support.
