### ISSUE TITLE
document postgres differences

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#1327]
Current known:

- float overflow (https://github.com/cockroachdb/cockroach/issues/15255)
- precedence of unary `~`
- int division (https://github.com/cockroachdb/cockroach/issues/14940)
- shift modulo (https://github.com/cockroachdb/cockroach/issues/14874)
- precedence of bitwise ops (https://github.com/cockroachdb/cockroach/pull/14944)

**Comment by mjibson** [comment]
@jess-edwards I think we need a page to document known differences between us and postgres (for identical input). This page would be a great resource for people porting from postgres to cockroach as a checklist for things to audit their application for. The above list covers the known math differences. Do you have a suggestion about where to put this page?

**Comment by jess-edwards** [comment]
@mjibson To me, it makes most sense to put this page in the SQL section of the docs. A lighter weight alternative would be to give it its own question in the FAQ. 

If you were looking for this kind of info, would it make sense to you to search the SQL docs? 

cc: @jseldess

**Comment by mjibson** [comment]
Oops, I meant to tag @jseldess but I mixed up your github names.

**Comment by jseldess** [comment]
Awesome idea, @mjibson. I remember getting this suggestion from a beta customer.

Do you think we might want to add additional "porting guides"? If so, we could create a new section under `Develop` called `Porting`. This could be the first item there, `Porting from PostgreSQL`... Thoughts?

**Comment by mjibson** [comment]
Yes, I like that. Will do.
