### ISSUE TITLE
Issue on docs for Build a Node.js App with CockroachDB

### ISSUE THREAD

**Issue by tlperkins** [cockroachdb/docs#1329]
Please include specific details about the section with the issue, as well as steps we can take to reproduce any problems you found.

**Comment by tlperkins** [comment]
Is it possible to provide a secure by default example for the top three language runtimes connecting to CockroachDB?

**Comment by jseldess** [comment]
@tlperkins, I'm closing this issue in favor of our main tracking issue for this work: //github.com/cockroachdb/docs/issues/631.
