### ISSUE TITLE
Navigation elements need HTML IDs

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1337]
Our navigation elements do not have IDs, so they cannot be easily accessed with JavaScript.

This came up because I wanted to create a link to the latest version's release notes and wanted to reliably interact with it by ID, instead of a more fragile method like finding the last header in the nav.

@kuanluo Can we get this to DivisionOf?

**Comment by kuanluo** [comment]
@sploiselle Absolutely. 

@deronjohnson - Can you take a look?

**Comment by deronjohnson** [comment]
@sploiselle Is there a naming convention you would like the IDs to use?

**Comment by sploiselle** [comment]
@deronjohnson Doesn't matter much; just the name of the link text separated by underscores or hyphens would be great.

**Comment by jseldess** [comment]
@sploiselle, since we closed the related PR, I'm closing this issue as well, for now.
