### ISSUE TITLE
sql: ALTER TABLE ... RENAME TO across databases is deprecated!

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/docs#13394]
Matthew Gardner (data-matt) commented:

Please put a massive banner on this page and its kin to mention is deprecated across databases

https://www.cockroachlabs.com/docs/v21.2/rename-table.html

Context here:
https://cockroachlabs.slack.com/archives/C0168LW5THS/p1648228225815339 

Jira Issue: DOC-3051

**Comment by knz** [comment]
Clarification: ALTER RENAME TO is still supported and will continue to be (like in postgres).

The only thing that's limited is the ability to rename *across databases*.

- rename table within schema: ALTER  RENAME TO works
- rename table across user-defined schemas: ALTER SET SCHEMA  (not RENAME TO)
- rename table across databases: we need to talk about this. It's midlly possible we will still able to support  a way to do this without backup/restore, just in a different way than pg

**Comment by data-matt** [comment]
Ah ok, can we put across databases?
