### ISSUE TITLE
Expand guidance on porting from PostgreSQL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1340]
Our [Port from PostgreSQL](porting-postgres.html) doc lists known difference in the way Postgres and CockroachDB handle identical SQL inputs, with porting instructions. 

What other type of guidance could/should we provide on this page? 

Some ideas:
- Differences in way we handle schema changes. Ours are not transactional - rationale behind why they’re different.
- The fact that CockroachDB doesn’t support all Postgres extensions.
- Maybe mention that we are a distributed database; network roundtrips are involved in doing each statement. Adding FK, for example, increases latency of operations. SQL parallelization can alleviate it.

@mjibson, @knz, @vivekmenezes, @cuongdo, other thoughts?

**Comment by mjibson** [comment]
For me, the first goal of these pages is to document behavior that, for the exact same input, will result in something different. Schema changes seems like it qualifies. I'm not worried about specifically listing postgres extensions because those will just break, and I don't think there's a lot we can document there besides "you can't do that", which they already know from the error message, but maybe users would find it helpful. The third point seems like it would be better documented in a common place since that's not postgres-specific. Maybe the bar should be "anything a postgres user would find surprising", which could reasonably include all of those points.

**Comment by knz** [comment]
A few things that I miss from that doc

- a note that anything related to `pg_catalog` is going to be subtly different in CockroachDB in many ways. (`select * from pg_catalog.xxx` is going to give quite different output in CockroachDB from postgres.) 

  Porting suggestion: "if the application depends on `pg_catalog` for introspection, please let us know. In general we are interested to increase compatibility with Postgres in that dimension, but in some cases we can work with you to find alternatives instead."

- a note that the error messages will be different in most cases. 

  Porting suggestion: "if the application contains code that inspects the text of error messages, please review your error strings database and consider creating an alternate dictionary for CockroachDB errors."

- regarding your second point, highlight that it goes both ways: CockroachDB supports things that Postgres does not. In particular, some queries cause an error in Postgres but work fine in CockroachDB. This includes both CockroachDB-specific features (like column families, interleaved tables) and also areas where we have extended Postgres' behavior (like WITH ORDINALITY).

- regarding the third point, this is a pandora's box of topics to discuss. I think that it is best to keep the topic silent until we have gathered both institutional knowledge about these issues (I think we have not yet) and evidence/facts to report (we don't have enough of those yet)

**Comment by awoods187** [comment]
I'm going to take an incremental approach to beefing this up in the docs fixit day.

**Comment by ericharmeling** [comment]
I think we now address most of the requested guidance in https://www.cockroachlabs.com/docs/v20.2/postgresql-compatibility.html. Please re-open if that page needs further improvements.
