### ISSUE TITLE
Schema change within a transaction

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1344]
On a few occasions, we've been asked if multiple schema changes are allowed in a single transaction. We should document the answer:

Within a transaction, following a schema change (a `CREATE`, `ALTER`, or `DROP` statement), the transaction must be committed, aborted, or rolled back. Any attempt to perform another schema change or access data will abort the transaction.

Note: There may be some statements allowed after a transaction, such as `SET`, `SHOW`, `CREATE USER`, `GRANT`, `REVOKE`. Need to check on these. 

@vivekmenezes, I hear that we may change things to be more permissive here. Can you offer any details?

**Comment by jseldess** [comment]
Update: Ability to run some statements after a schema change: https://github.com/cockroachdb/cockroach/pull/15511#issuecomment-298337559

**Comment by jseldess** [comment]
With https://github.com/cockroachdb/cockroach/pull/15511, it's now safe to say that multiple schema changes, or a schema change followed by non-schema changing statements, are allowed within a single transaction, with the following exceptions:

CREATE TABLE with FK or Interleaved table, followed by statements
referencing the table #13505
DROP TABLE FOLLOWED BY CREATE fails:
#12123
database writes followed by a schema change fails: INSERT on a table,
followed by a table CREATE for example
#7570

**Comment by bdarnell** [comment]
Yes, but A) that's not in rc1, so don't update the docs until rc2, and B) interleaved tables are a big deal that we should be encouraging most applications to use, so we'll still need to discourage putting table creation in transactions.

**Comment by jseldess** [comment]
Got it. Thanks, @bdarnell.

**Comment by andreimatei** [comment]
The documentation of "schema changes within transactions" should include a description of when errors encountered by such schema changes are delivered to clients. The story there is still being written, but the answer is likely to be that they'll be delivered as the result of the COMMIT. Then the caveat that other changes done by the transaction might have been committed needs to be shouted out.

**Comment by jseldess** [comment]
OK, it'll be a good time for us to finally add explicit docs on how online schema changes work.

**Comment by jseldess** [comment]
@rmloveland added more details on this: https://www.cockroachlabs.com/docs/stable/online-schema-changes.html#limitations.
