### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1345]
https://www.cockroachlabs.com/docs/start-a-local-cluster.html

![image](https://cloud.githubusercontent.com/assets/5768024/25571509/6fc1678e-2dfe-11e7-8e97-6798e625c2f2.png)

In the what's next section, should that read "Explore Core Features"?

**Comment by jseldess** [comment]
Yep, good catch. Error is also on https://www.cockroachlabs.com/docs/start-a-local-cluster-in-docker.html
