### ISSUE TITLE
dead link in https://www.cockroachlabs.com/docs/search.html?q=back+up

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/docs#1353]
![image](https://cloud.githubusercontent.com/assets/5076964/25615422/0ef77792-2f05-11e7-843d-91e467155ed4.png)

**Comment by jseldess** [comment]
Thanks for reporting this, @tschottdorf. We're basically returning google search results in the context of our site, and it seems Google hasn't caught up with that page having been removed. 

@mjibson, do you know of a way for us to ensure that removed pages aren't returning in the results?

**Comment by mjibson** [comment]
I need someone to review my 404 PR in the website repo, which will fix this.

**Comment by jseldess** [comment]
Thanks, @mjibson!
