### ISSUE TITLE
typo in docker install page

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1354]
From a user:
Found a typo on your download/install pages.
https://www.cockroachlabs.com/docs/install-cockroachdb.html

Docker install:
`sudo docker pull cockroachdb/cockroach:1.0-rc.1`

Should have said:
`sudo docker pull cockroachdb/cockroach:v1.0-rc.1`

Note the docker tag.

**Comment by jseldess** [comment]
Thanks for reporting, @dianasaur323. Fixing this now.
