### ISSUE TITLE
Microsoft Azure best practices

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1356]
- Incidental VM migrations wipe disks; can reduce past quorum 
- Clock issues (cc @mberhault for more detail)

**Comment by jseldess** [comment]
From @bdarnell in https://github.com/cockroachdb/docs/issues/1132:

> One thing we do need to do is add warnings about the data corruption bug that we've seen on Azure A-series instances. D-series instances are believed to be fine; other series should be tested extensively before production use.

> The problem on azure is that a wiped disk there comes back with a bad filesystem (ntfs over fuse) which causes severe performance degradation.

**Comment by jseldess** [comment]
Updating this issue:

Warning I proposed in https://github.com/cockroachdb/docs/pull/1638:

> On Microsoft Azure, A-series VMs can come back from VM migrations with bad filesystems, which can in turn cause data corruption and performance degradation. We therefore recommend not using A-series VMs. Instead, use D-series VMs, which have not been seen to exhibit these problems. Before using any other Azure VM series in production, you should test them extensively.

@bdarnell's response:

> This is not about VM migrations (that issue is common to all azure VMs. It's not data corruption, though, just a performance problem). The issue is that the local disk of A-series VMs just eats data randomly.
>
> Actually, these azure instructions don't specify where the data lives, so they're using the root filesystem. This works (and appears to be immune to the A-series problems), but you have very limited space there. We should update the docs to discuss how to use the local disk (as well as the alternative of using premium storage. Microsoft heavily recommends this and is reluctant to provide support if you're not using it).

@bdarnell, a few follow-up questions so I can refocus this work properly:

1. Do we still need to say something about the performance implications of VM migrations?
2. Any guidance you or @mberhault can provide on using local disk or premium storage? That now seems like the main revision needed here.

**Comment by bdarnell** [comment]
1. Yes, I think we do. Users of local disk on azure will need to ensure that their startup scripts examine the partition, and if it's NTFS, reformat it as ext4 (or another linux filesystem). This is kind of a scary thing to do in an automated way, but it's not unique to cockroach - anyone using linux and local disk on azure needs to deal with this.
2. Microsoft support will tell you that you should be using premium storage for any database; it's hard to get it through their heads that a replicated database can work with non-replicated storage. Premium storage will avoid both the A-series HDD issue and the NTFS issue above, but it's more expensive (and that's going to make azure a more expensive place to run cockroachdb than other providers where we can use local disks).  Our own testing has been almost entirely on local disks so we don't know much about how the performance of the two options compare.

**Comment by bdarnell** [comment]
The bulk IO team has found that all azure VMs except the L series suffer from disk throttling that can cause availability issues. So I believe our current recommendation here is to use L-series VMs for production deployments, or D-series VMs as a slightly less expensive alternative for light workloads. A-series are completely busted and should not be used at all; other machine classes have not been tested and should be viewed with suspicion.
