### ISSUE TITLE
Document backup/restore & changefeed behavior with row-level TTL

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#13664]
Vy Ton (vy-ton) commented:

We've completed the initial [docs for row-level TTL](https://www.cockroachlabs.com/docs/v22.1/row-level-ttl.html].

We should also describe the TTL behavior with:

- [ ) [backup/restore](https://docs.google.com/document/d/1NBXzzXMWSEopll27h_ZF0jyImXX3m4GEfpR36ixJc4c/edit]
- [ ) [changefeed](https://docs.google.com/document/d/1NBXzzXMWSEopll27h_ZF0jyImXX3m4GEfpR36ixJc4c/edit#bookmark=id.v9mt2dwql39z)

FYI @livlobo @amruss 

Jira Issue: DOC-3563

**Comment by rmloveland** [comment]
Will be fixed by https://github.com/cockroachdb/docs/pull/14288
