### ISSUE TITLE
Link to source tarball in release notes.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#1368]
Porting over from https://github.com/cockroachdb/cockroach/issues/15684:
CC: 	@williamh

Hello, this is a question about building from source.

I am a maintainer on Gentoo Linux, and I want to package cockroach-1.0-rc1, but your documentation refers to a source tarball which is just named cockroach-latest.src.tgz with no version number in the name. Is this 1.0-rc1, or is it some snapshot later than that?

I have spent most of the day trying to figure out how to check out your git repositories and build from there without the build checking out anything from git but haven't had any luck.

If the tarball referred to in your documentation is the source for 1.0-rc1 do you mind versioning your tarball names in the future? If not, is there a simple way to download the release from http://github.com/cockroachdb/cockroach/releases, put the vendored code in the vendor directory, then build everything without the build process trying to pull from git?

Thanks,

William

**Comment by mberhault** [comment]
@williamh: the `latest` tarball is currently rc1, though rc2 is expected soon.

We do need to clarify this. I think at the very least we need a link to the source tarball from the release notes (eg: [1.0-rc.1 releasenote](https://www.cockroachlabs.com/docs/v1.0-rc.1.html)). This Should be straightforward.

Something else we've been talking about for a bit is to always use the actual latest version in the install docs, as opposed to just `latest`.

@jseldess: thoughts? I think we should at least add the link in the release notes from now one.

**Comment by mberhault** [comment]
@williamh: I forgot to mention: we do have versioned binaries and tarballs, it's just that we use the `latest` name in the docs. The versioned ones are only linked to from the release notes.
For example, you can download the 1.0-rc.1 source tarball at: https://binaries.cockroachdb.com/cockroach-v1.0-rc.1.src.tgz

**Comment by williamh** [comment]
Hi Mark, I looked at https://binaries.cockroachdb.com with a web browser but saw nothing, so I wasn't sure whether or not you had versioned tarballs; that is why I opened the issue. Thanks a lot for the information.

**Comment by sploiselle** [comment]
@williamh Hey, William! You can find the specific version links on the release note page for each version, e.g.:

- [v1.0-rc.1](https://www.cockroachlabs.com/docs/v1.0-rc.1.html)
- [older versions](https://www.cockroachlabs.com/docs/older-versions.html)

We haven't come up with a strategy yet for more widely sharing version-specific links in the docs yet, but will work on that in the future.

**Comment by jseldess** [comment]
Some relevant updates here:

- Once https://github.com/cockroachdb/docs/pull/1357 lands (today sometime), the most recent release notes will link to version-specific tarballs.
- @benesch also opened https://github.com/cockroachdb/docs/pull/1371, which adds a page listing all versions, with links to the source tarball for each version. This new page probably would've been most useful for you, @williamh , I think. Here's a [preview](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/2019e2e0b0288d9272b339a8e70f834a8b6fd611/releases.html).

**Comment by williamh** [comment]
@jseldess Yes, #1371 would be extremely useful. #1357 is nice as well. Thanks everyone for working on this.

**Comment by benesch** [comment]
Thank you for working on Gentoo packaging, @williamh. It's much appreciated!

FYI, our [new releases page](https://www.cockroachlabs.com/docs/releases.html) just landed, along with the change to link to the source tarballs on the individual release pages. I've additionally opened #1375 to excise the non-versioned latest tarballs from the install instructions as well.
