### ISSUE TITLE
Performance Improvements/Best Practices

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1369]
Users should be able to find a resource that provides a list of tips/tools they can use to improve their deployment's performance, e.g.:

- Parallelized SQL execution (#1290)
- Interleaved tables
- Index formatting

**Comment by jseldess** [comment]
@Amruta-Ranade is handling the first part of this, and likely creating a "performance optimization" section, so assigning to her for now.

**Comment by Amruta-Ranade** [comment]
- Move Indexes, Column Families, and Interleaved Tables to the Performance Optimization section.
- Move Views up one level, just below Transactions.
- Move NULL Handling to SQL Syntax, just below Name Resolution.
- Get rid of empty Data Definition section.
