### ISSUE TITLE
Explain `cockroach debug zip` in docs

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1372]
This new command is going to become very important for us and we will advise users to use it whenever possible. It is important that they can  understand what it does before they run it.

**Comment by tschottdorf** [comment]
In particular, which (if any) sensitive information it might leak, and whether it's ok to post these semi-publicly or not.

**Comment by jseldess** [comment]
@sploiselle just opened a [PR for initial troubleshooting docs](https://github.com/cockroachdb/docs/pull/1370). If we want people to use this command as a standard part of filing an issue, it would make sense to update the `file-an-issue.md` file in that PR at the least, as well as updating our `cockroach` issue template. 

@sploiselle, would you be willing to incorporate `cockroach debug zip` into your troubleshooting docs?

**Comment by knz** [comment]
Thanks!

Also in the general CLI docs it needs to be mentioned with either a detailed explanation or a link to the suitable document.

**Comment by knz** [comment]
Copy of my earlier comment:

"""
debug zip's output is absolutely not suitable for public posting, because the log files enclosed within will often contain partial copies of the data inserted in the database, including sometimes usernames, table contents and passwords" 

Also, while we are at it, we should absolutely make it clear in docs that cockroachdb logs must be treated with the same level of security/confidentiality as the db files themselves!!!

**Comment by knz** [comment]
Some additional discussion
![schermafdruk_2017-05-05_15-32-05](https://cloud.githubusercontent.com/assets/642886/25747560/23a4ce74-31a8-11e7-8dd6-f4f96bce9904.png)

**Comment by knz** [comment]
Some suggestions for encryption:

- **do not use a "ZIP password"**  - the ZIP format does not offer secure encryption (in general distrust archive formats with a password function; so don't embed a file in a password-protected Word document either)
- secure encryption can be achieved using PGP/GnuPG; we recommend [gpg4win](https://www.gpg4win.org/) (Windows) and [GPGTools](https://gpgtools.org/) (MacOS)
   - we will produce a PGP/GnuPG public key (if we don't have one already? @mberhault ?) so users can use that to encrypt to us, this is the safest
   - user can also use password encryption with these tools, and communicate the password to us using a separate channel (phone, email)
- for very large files, please contact us first. The best is to mail us a larger storage device (DVD, SSD, hard drive) by post with encrypted files on it. Note that TrueCrypt is no longer considered secure.

**Comment by knz** [comment]
@sploiselle note that the discussion above higlights several issues about "Reporting issues to Cockroach Labs" that go beyond the specifics of `cockroach zip`.

**Comment by sploiselle** [comment]
@knz This looks like a really thoughtful tool. Is there a semi-simpler way of getting the logs to us? Like Dropbox and then emailing us the link/giving us the password over another channel?

**Comment by knz** [comment]
Users have to decide themselves if they are to trust Dropbox (a 3rd party). If they do not, then strong encryption directed to us is the solution.

**Comment by mberhault** [comment]
I think we need to provide something with at least a modicum or privacy. This could be an upload-only bucket somewhere with https. If people want to add encryption, they should be welcome to.
We would still need to generate and publish a public key. That part's easy. How to keep the private key safe, yet available to all engineers, is another issue.

**Comment by sploiselle** [comment]
@petermattis @bdarnell Think there was recently discussion around this issue, so want to make sure I understand what's happening from a user interaction perspective.

I don't think the documentation needs to explicitly call out how to share the file with us, but I think it's important to have the process in place internally. I don't need to know how, but have we achieved an internal consensus on how we want customers to deliver these files to us?

**Comment by petermattis** [comment]
I don't think we've reached consensus on the secure delivery. The simplest option would be for them to `scp` the file to our bastion machine. The downside to that is that everyone at CRL can access the data. I'd prefer to encourage that, though, over trying to provide a more rigorously secure option.
