### ISSUE TITLE
Clarify that unique_rowid does *not* guarantee uniqueness for non-PK columns

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1373]
Raphael 'kena' Poss (knz) commented:

Spotted in the release notes from #1357:

Using `unique_rowid()` to populate a table is only guaranteed to produce unique values if it is used for a primary key or "unique" column.

If `unique_rowid()` is used in a DEFAULT expression, or explicitly, in INSERT/UPDATE/ALTER TABLE ADD COLUMN with a non-PK, non-unique column, there is an extremely small, but non-zero chance that duplicate values will be produced. This is because the value generated by `unique_rowid()` is based on a formula using the node ID and system time that *is* robust to time jumps but does not fully guarantee uniqueness across different nodes or across node restarts.

Also I'd suggest this:

"""
Note: this behavior is intended by design, to ensure that `unique_rowid()` can fit in an INT column. We could provide a function that provides guaranteed-unique values but it could not fit in an INT column any more. Users are invited to file an issue on our GitHub to request this functionality and their use case if they wish so.
"""

Jira Issue: DOC-111

**Comment by petermattis** [comment]
Can you elaborate on what you're worried about? Two different nodes can't generate the same `unique_rowid()`. And the same node will not generate a duplicate `unique_rowid()` within the lifetime of a process. Yes, there is a small window of vulnerability across process restarts, but the above hints at something more significant.

**Comment by knz** [comment]
Two different nodes can generate the same unique_rowid if they have been attributed a NodeID with their 41st bit set or beyond. In an environment where nodes are added and removed regularly (not likely but *possible*) this will eventually happen. Also, across restarts.

There is a fundamental difference between specifying that a function returns "guaranteed unique" values and "probabilistically unique with an negligible probability of duplicates". I recall someone writing "We put correctness first, where it belongs"...

**Comment by andreimatei** [comment]
Keep in mind that we wait MAX_OFFSET on restarts. I'm also not sure what risk you're thinking of.

**Comment by andreimatei** [comment]
We could alot some bits to the epoch of the node's licenses record. I think we've made that increment on each restart.

**Comment by knz** [comment]
If MAX_OFFSET is set smaller than 10 microseconds, then the wait of MAX_OFFSET is not sufficient.

**Comment by petermattis** [comment]
Isn't the language around `unique_rowid` already sufficient. See https://www.cockroachlabs.com/docs/create-table.html#create-a-table-with-auto-generated-unique-row-ids.

**Comment by knz** [comment]
"except in extreme cases where a very large number of IDs (100,000+) are generated per node per second. In" - that's the current phrasing, and is also incorrect. The code was modified to prevent this from happening.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
