### ISSUE TITLE
Start a Cluster in Docker (Insecure) Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#13747]
Artem Ervits (dbist) commented:

Re: [Start a Cluster in Docker (Insecure)](https://cockroachlabs.com/docs/v21.2/start-a-local-cluster-in-docker-mac.html)

## Issue Description

the existing instructions no longer work as roach1 container communicates on IPv6 by default. It results in one of the three containers exiting quickly.

## Suggested Resolution 

Based on https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1651207584064039?thread_ts=1651180348.280279&cid=CJ0H8Q97C, we need to add `--listen-addr=0.0.0.0` to the start command.

Jira Issue: DOC-3522

**Comment by rail** [comment]
It turns out `--listen-addr=0.0.0.0` doesn't solve the issue, see another slack thread https://cockroachdb.slack.com/archives/CP4D9LD5F/p1651271277591949
