### ISSUE TITLE
Statements Page Doc Update - discuss stats collection with threshold

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#13750]
Re: [Statements Page](https://cockroachlabs.com/docs/v22.1/ui-statements-page.html)

In a recent version, the Statements Page got the ability to request diagnostics for a statement corresponding to an execution that takes over a duration threshold. We should mention this in the docs, and in particular highlight that using this threshold feature means that we'll trace all queries with the respective fingerprint until the threshold is hit. This can be expensive. This is in contrast with what the page currently says for the non-threshold case.

> Tip:
> Diagnostics will be collected a maximum of N times for a given activated fingerprint where N is the number of nodes in your cluster.

**Comment by stbof** [comment]
This is already in progress here: https://github.com/cockroachdb/docs/pull/13623
