### ISSUE TITLE
Windows binary requires Windows 8+

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1377]
I believe (still waiting on confirmation) that the Windows binaries to fail for this user on the forum because they're running a version of Windows pre-8: https://forum.cockroachlabs.com/t/where-are-the-windows-binaries/602/4

We should document the minimum required Windows version wherever we link to the binaries.

@tamird, can you confirm? Seems to be a RocksDB issue? https://github.com/facebook/rocksdb/issues/726.

**Comment by tamird** [comment]
Not sure about rocksdb, but we definitely use a Windows 8+ API in timeutil.
GetSomethingPrecise is the windows API function name (not at computer,
don't recall, should be easy to find).

**Comment by benesch** [comment]
Yup, that's the one. All good, then! Just need to document the limitation.
