### ISSUE TITLE
faq: Can I use CockroachDB as a KV store?

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/docs#138]
This is a question that keeps coming up and is better answered in the FAQ

**Comment by jseldess** [comment]
Got this question again in Gitter: 

x2a @x2a-io 04:55
Hi all! Not sure if this is the right place to ask this... But is there any way of accessing and using a cluster's underlying kv store?

kena @knz 04:58
x2a what we recommend is to create a SQL table with two columns k and v and set k s primary key. This maps rather directly to KV operations underneath. Then we do not officially support this but you can also make your own go program using cockroach as a library and use the KV api directly

x2a @x2a-io 05:39
Thanks kena, that makes a lot of sense. I think I'll stick with the SQL solution... I'm sure the pg interface isn't likely to change soon.
