### ISSUE TITLE
fix spellling/case of rewriteBatchedInserts in Java docs

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/docs#13822]
Jim Hatcher (jhatcher9999) commented:

We have a few docs that mention the JDBC parameter called "reWriteBatchedInserts", but in the docs we spell it as "rewriteBatchedInserts"

https://www.cockroachlabs.com/docs/v21.2/build-a-java-app-with-cockroachdb-hibernate.html
https://www.cockroachlabs.com/docs/v21.2/build-a-java-app-with-cockroachdb.html

This option is actually case-sensitive in JDBC and can be silently ignored if not spelled right.

Can we update all these references to use a capital W on "Write"?

Jira Issue: DOC-3489

**Comment by jhatcher9999** [comment]
link to the JDBC spec: https://jdbc.postgresql.org/documentation/94/connect.html

**Comment by chaneth8** [comment]
@jhatcher9999 I made a PR that I think fixes the issue, but I'm not sure how to request a review. This is what I see in the PR: 
<img width="1193" alt="Screen Shot 2022-05-10 at 8 45 01 AM" src="https://user-images.githubusercontent.com/83342511/167631423-8d6276df-3bea-417f-96e8-9488a6f9dd17.png">
I don't see the dropdown that lets you request a review, so how would I go about doing that? 

Thank you so much in advance!
