### ISSUE TITLE
Update ORM tutorials to cover client-side transaction retries

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/docs#1383]
Hibernate users do not have a clear example of how to use the COCKROACH_RESTART savepoint in their apps. We should add one.

**Comment by jseldess** [comment]
Thanks, @jordanlewis. Is the subtext here that our ORM examples need to cover client-side transaction retries like our driver examples do? If so, we actually need this across our ORM tutorials. @cuongdo, when do you think devs might be able to help with this? Something for 1.1?

**Comment by jordanlewis** [comment]
Yes, I think that's the subtext indeed. This may not have been identified early on because the SQLAlchemy driver largely does this under the hood - but the rest of our drivers do not.

**Comment by jseldess** [comment]
OK, thanks for the clarification. I'll rename the issue accordingly.

**Comment by jseldess** [comment]
@cuongdo, @petermattis, @nstewart: Our orm examples don't account for client-side transaction retries. Expanding the docs to cover that involves dev work. Any thoughts about factoring this into the roadmap?

**Comment by petermattis** [comment]
How much work is the refactoring of the ORM examples? I think we should do this, just hesitant about putting everything in the roadmap. Certainly a github issue.

**Comment by cuongdo** [comment]
We have a pretty full roadmap, so we'll likely need to drop something to fit this in.

**Comment by jseldess** [comment]
Requested by @nstewart:

Re: [Build a Python App with CockroachDB](https://cockroachlabs.com/docs//v2.0/build-a-python-app-with-cockroachdb-sqlalchemy.html)

We need transaction retry instructions for sqlalchemy, we have it for psycopg

**Comment by nstewart** [comment]
cc @awoods187 -- following the tutorials online you get a bunch of unhandled exceptions as soon as you put any load on the cluster due to this. It's a pretty bad UX. Deferring to you on priority but adding some context as someone who just created a python app.

**Comment by rmloveland** [comment]
@jordanlewis for Hibernate, would this be addressed by updating [Build a Java app with Hibernate](https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb-hibernate.html) to add the code and configuration from https://github.com/cockroachdb/hibernate-savepoint-fix ?

**Comment by jordanlewis** [comment]
I think so, yes. @justinj, what do you think?

**Comment by justinj** [comment]
Yes, probably, though I'm a bit fuzzy on that repo, it's been a while.

**Comment by awoods187** [comment]
How vetted is this test of transaction retries?  I know it doesnt work in Spring and am curious how reliable this solution is for Hibernate

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3315
