### ISSUE TITLE
disclose diagnostics reporting in typical download flow

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1386]
From a discussion on Slack, we seem to have consensus that the default-enabled diagnostics reporting should be called out somewhere in the typical download flow.

**Comment by jseldess** [comment]
Thanks for opening this, @benesch. Can you clarify what you mean by typical download flow, though?

**Comment by benesch** [comment]
I think the "Install CockroachDB" and "Releases" pages, at a minimum should have one of those blue informational boxes (or similar) that says something like:

> By default, each node of a CockroachDB cluster shares diagnostic details with Cockroach Labs on an hourly basis. These details, which are completely scrubbed of identifiable information, greatly help us understand and improve how the system behaves in real-world scenarios. [Learn more about what details are shared and how to opt-out of reporting.](https://www.cockroachlabs.com/docs/diagnostics-reporting.html).

@bdarnell, do you have thoughts? Not sure if we want this on e.g. the release notes.

**Comment by bdarnell** [comment]
I'd say it should just be in the "install" pages; I don't think it needs to be repeated everywhere there is a download link.

**Comment by jseldess** [comment]
OK, I'll look into adding it to the install page.

**Comment by dt** [comment]
tiny nit: I'd suggest `s/on an hourly basis/periodically/`, keeping the specifics in one place, the dedicated page.
