### ISSUE TITLE
Tabs on install page should be directly linkable

### ISSUE THREAD

**Issue by tamird** [cockroachdb/docs#1387]
It is not currently possible to directly link to e.g. the Windows section of https://www.cockroachlabs.com/docs/install-cockroachdb.html, which is unfortunate.

Assigning @mjibson for triage.

**Comment by mjibson** [comment]
There's no one who owns this stuff, so there's no one to triage it to. I'm unassigning so it can be picked up by someone who wants to do it.

**Comment by jseldess** [comment]
Duplicate of https://github.com/cockroachdb/docs/issues/1856.
