### ISSUE TITLE
Monitoring and Alerting Doc Update 

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#13888]
Florence Morris (florence-crl) commented:

Re: [Monitoring and Alerting](https://cockroachlabs.com/docs/v21.2/monitoring-and-alerting.html]

## Issue Description
On this page this error message is incorrect/outdated:

```
{
  "error": "node is not ready",
  "code": 14
}
```

## Suggested Resolution
 
The correct error message (as of v21.2.10) is:

```
{
  "error": "node is not healthy",
  "code": 14,
  "message": "node is not healthy",
  "details": [)
}
```

Jira Issue: DOC-3453

**Comment by andf-crl** [comment]
Addressed in #14029
