### ISSUE TITLE
What does JOIN being 'functional' mean in the docs?

### ISSUE THREAD

**Issue by gflarity** [cockroachdb/docs#1394]
https://www.cockroachlabs.com/docs/sql-feature-support.html

What does 'functional' mean in the context of SQL features? 'functional joins'?  There's a blog post from july about how they're working but don't use them. Is that the current state? Working, but don't use them?

**Comment by jseldess** [comment]
Thanks for this question, @gflarity. I agree that `Functional` is not a very clear way to describe our level of support. We'll aim to add more substantial documentation on joins soon. In the meantime, this more blog post describing where we are with Joins: https://www.cockroachlabs.com/blog/better-sql-joins-in-cockroachdb/

@sploiselle and @knz , can you help figure out what the right support-level is now? If `Functional` is still accurate, perhaps we should make that term link to the blog post mentioned above?

**Comment by knz** [comment]
Functional is still accurate. The blog post can serve to provide details. We will increase performance/support over 2017.

**Comment by knz** [comment]
![this picture](https://www.cockroachlabs.com/uploads/2017/02/CockroachDB-join-performance-2017Q2-header-01.png) 

this is still accurate and is probably the best high-level summary of the current situation.
