### ISSUE TITLE
Issue on docs for SQL Feature Support

### ISSUE THREAD

**Issue by justinpitts** [cockroachdb/docs#1395]
The docs ( https://www.cockroachlabs.com/docs/sql-feature-support.html ) reference window functions as a common extension, when they have been part of the standard since SQL:2003.

**Comment by sploiselle** [comment]
For anyone curious in the future, this is substantiated by the [Wikipedia entry on SQL 2003](https://en.wikipedia.org/wiki/SQL:2003).
