### ISSUE TITLE
Improve usability of CockroachDB in Comparison

### ISSUE THREAD

**Issue by SamHasler** [cockroachdb/docs#1402]
could you color code the table cells so it's easier to scan.

**Comment by jseldess** [comment]
Thanks for the suggestion, @SamHasler. It's definitely on our plan to improve the usability of this page. We'll be sure to consider this particular improvement.

cc: @kuanluo

**Comment by kuanluo** [comment]
Updated comparison chart added color coded table cells: https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html

Feedback welcome!

**Comment by kuanluo** [comment]
Closing this issue.
