### ISSUE TITLE
Add TIDB to Comparison page in CockroachDB Docs

### ISSUE THREAD

**Issue by pirate** [cockroachdb/docs#1412]
[PingCAP's TIDB](https://github.com/pingcap/tidb/) is not listed on your [CockroachDB in Comparison](https://www.cockroachlabs.com/docs/cockroachdb-in-comparison.html) page.

There's definitely some demand ([hn](https://news.ycombinator.com/item?id=10180822), [hn](https://news.ycombinator.com/item?id=13661673), [reddit](https://www.reddit.com/r/golang/comments/3jy7g8/tidb_first_scalable_rdbms_inspired_by_google_f1/cutav2y/)) for a comparison between the two.

They seem to be the only major competitor that's doing **exactly** what you're trying to do (correct me if I'm wrong here).

If CDB has more features and has TiDB beat, awesome, I'd love to see how far ahead CDB is!

**Comment by jseldess** [comment]
Thanks for the suggestion, @pirate. 

cc: @dianasaur323, @nstewart

**Comment by jess-edwards** [comment]
Thanks for the suggestion @pirate. To build the comparison matrix, we chose a handful of representative databases from different categories. We’ll keep an eye on TiDB, but for now we’ll leave Spanner as our NewSQL point of comparison. If you’re looking for a more robust comparison of production-ready databases, I recommend looking at dbengine.com.

**Comment by ShalokShalom** [comment]
+1

**Comment by max-feng** [comment]
+1

**Comment by ShalokShalom** [comment]
Cockroach is exactly the same as TiDB, just for Postgres. 
This is why people are interested in a comparison. 
It is comparing apples with apples.

**Comment by andreimatei** [comment]
"exactly the same" except the design is fundamentally different :)
TiDB has a central component that all transactions need to contact, which prevents geographically-distributed clusters. CRDB supports geo-distributed clusters.
Also, TiDB provides snapshot isolation for transactions whereas CRDB transactions are serializable.

**Comment by ShalokShalom** [comment]
Same use case. Drop in replacement for a standard DB. :hugs:
