### ISSUE TITLE
Administrator privileges are no longer required on Windows

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1425]
PR: https://github.com/cockroachdb/cockroach/pull/15916

Just need to update https://www.cockroachlabs.com/docs/known-limitations.html#running-on-windows-as-a-non-admin-user. 

@bdarnell, @tamird: Instead of removing this known limitation from the docs, we should update it with a note that it's been resolved as of 1.0.1. Do you agree?

**Comment by tamird** [comment]
:+1:

**Comment by bdarnell** [comment]
Yeah, I think it makes sense for the "known limitations" to stick around at least until the next major release, with a note about when they were fixed.
