### ISSUE TITLE
Need a callout in the upgrade docs for the 20.2->21.1 migration

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#14254]
Raphael 'kena' Poss (knz) commented:

### Background

When a customer is upgrading to a version prior to 21.1 (20.2 or earlier), to 21.1 or later—for example, they are upgrading from 19.2 to 22.1—they will hit a snag at the 20.2->21.1 transition:   the upgrade will stop, complaining that "nodes are still decommissioning"

([slack thread](https://cockroachlabs.slack.com/archives/CHVV403F0/p1654802377471299))

This limitation is because the v20.2 release introduced the "decommissioned" state for the first time. Prior to 20.2,  decommissioning a node would only bring it into state "decommissioning",  which kept it possible (theoretically) to bring the node back online later.   

Since 20.2, version upgrades requires certainty about whether a node is fully decommissioned. Since the "decommissioning" state does not provide this certainty, any node decommissioned in v20.1 or before will block an upgrade.

### Required resolution

In the "version upgrade" docs, a callout should be added, to tell users upgrading from 20.2 to a later version to **manually finalize the decommission of all previously-decommissioned nodes**, using the `cockroach node decommission` command.

This can be done, for example, using the shell command
```shell
$ cockroach node status --decommission | tail -n +2 | grep decommissioning | awk '{ system("echo cockroach node decommission " $1) }'
```

(NB: this example needs to be extended with connection flags as necessary, depending on the deployment)

cc @taroface 

Jira Issue: DOC-3776

**Comment by smcvey** [comment]
Can we have two updates to the docs:

In the 'Upgrade to 20.2' docs, once `SHOW CLUSTER SETTING version;` shows '20.2`', the customer should then check what nodes need to be moved to decommissioned:

```
cockroach node status --decommission (look for any nodes in 'decommissioning' state)
```

decommission them:

```
cockroach node decommission <node id>
```

If they read these steps, they will have a smoother transitition when they upgrade to 21.1.

Conversely, in the 'Upgrade to 21.1' steps, make checking for decommissioning nodes the FIRST step.

**Comment by knz** [comment]
NB: it's likely that users upgrading from an old version to the latest one will only read the latest docs (i.e. they won't realize that it's useful to read the intermediate docs as well).

So I think we should add a similar-sounding callout to all the versions after 20.2.
