### ISSUE TITLE
sql: support explicit ON [UPDATE|DELETE] RESTRICT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1433]
PR: https://github.com/cockroachdb/cockroach/pull/15815

From release notes: 
> The `ON UPDATE RESTRICT` and `ON DELETE RESTRICT` modifiers can now be used when creating foreign keys (this behavior is the default, but now it can be specified explicitly).

**Comment by jseldess** [comment]
@benesch, are we planning to ever support anything but `RESTRICT` for `ADD FOREIGN KEY`? If not, I'm wondering if I should just leave this change out of the docs...

**Comment by bdarnell** [comment]
Yes, @BramGruneir is working on supporting `ON DELETE CASCADE` and other variants.

**Comment by jseldess** [comment]
Ah, right. I'll close this in favor of the issue tracking Bram's work: https://github.com/cockroachdb/docs/issues/2015
