### ISSUE TITLE
Incorrect link in build-a-java-app-with-cockroachdb.html

### ISSUE THREAD

**Issue by mxd** [cockroachdb/docs#1442]
For the second java code snippet, the source link incorrectly points to: 

https://raw.githubusercontent.com/cockroachdb/docs/gh-pages/_includes/app/txn-sample.rb

should instead point to:

https://raw.githubusercontent.com/cockroachdb/docs/gh-pages/_includes/app/TxnSample.java

**Comment by jseldess** [comment]
Thanks for catching this, @mxd. I'll fix this asap.
