### ISSUE TITLE
Install on linux-gnu vs. linux-musl

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1444]
As mentioned [here](https://github.com/cockroachdb/cockroach/issues/16053#issuecomment-303112203), we should look into expanding our linux install docs to cover both `linux-gnu` and `linux-musl`.

@tamird, @a-robinson, @bdarnell, who can help me understand the differences here?

**Comment by tamird** [comment]
Any one of us should be able to. Happy to explain in person.

**Comment by jseldess** [comment]
Based on decision [here](https://github.com/cockroachdb/cockroach/issues/16053#issuecomment-303517426), closing this issue for now.
