### ISSUE TITLE
Troubleshooting: `node_statement_statistics` for long-running queries

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1445]
@knz mentioned:

> ...to troubleshoot long-running query we would first recommend people to look at the virtual table `node_statement_statistics`, before they enable additional logging flags. That is always available and will not cause any performance overhead.

Will integrate this into troubleshooting documentation based on further research.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2330.
