### ISSUE TITLE
Installation: some MacBooks don't have `usr/local/bin`

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1447]
> if you don’t already have a local/bin this command renames the cockroach binary:
> `cp -i cockroach-latest.darwin-10.9-amd64/cockroach /usr/local/bin`

In this case, the MacBook only had `/usr/bin` without the interstitial `local` dir

**Comment by jseldess** [comment]
Haven't gotten more complaints about this, so closing for now. @sploiselle, if you feel strongly that we should add more info to the install page about this, please let me know.
