### ISSUE TITLE
Fix on-page anchor links

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1451]
Currently when you click arbitrary HTML anchor links, they load at the top of the page. However, that location is "under" the site-wide header.

To fix this, arbitrary HTML anchor links should be treated the same as the `<h#>` headers, and have their location offset by the height of the header.

**Comment by jseldess** [comment]
Can you include a screenshot, @sploiselle? I don't see this happening...

**Comment by sploiselle** [comment]
Given this content:

~~~
---
title: Anchor Test
summary: Learn how to find and read CockroachDB error logs
toc: false
---

Here's a link to an arbitrary HTML anchor<sup>[1](#myfootnote1)</sup>.

<a name="myfootnote1">1</a>: Here's the anchor's target

Here

is

more

content.
~~~

# Pre-Click Page

<img width="765" alt="screen shot 2017-05-23 at 2 29 15 pm" src="https://cloud.githubusercontent.com/assets/19260003/26369972/533c4688-3fc4-11e7-9ba0-16dddd9efb2e.png">

# Post-Click Page

<img width="755" alt="screen shot 2017-05-23 at 2 29 30 pm" src="https://cloud.githubusercontent.com/assets/19260003/26369992/63817fc2-3fc4-11e7-831a-1d3386a3337c.png">

**Comment by jseldess** [comment]
Ah, now I see what you mean. We fixed this problem with header anchors. Just need to track down the solution there and apply to arbitrary anchors.

**Comment by j-low** [comment]
@jseldess @sploiselle is this still a current issue?

**Comment by jseldess** [comment]
Yep, @j-low. See https://www.cockroachlabs.com/docs/dev/start-a-node.html#locality, which is this anchor: https://github.com/cockroachdb/docs/blame/master/v2.0/start-a-node.md#L51

**Comment by j-low** [comment]
Great, thanks @jseldess.

**Comment by rmloveland** [comment]
I just ran into this and filed the dupe #3026 - there are some screenshots there which are hopefully useful.

My comment from there (which is probably less useful but here goes 😄 )

<blockquote>
As a user, it's very confusing to click on an anchor link and the content of the anchor is chopped off at the top. It's disorienting and leaves me not sure what I'm supposed to look at.

I think we have a few options to address this:

- If we must float the navbar we could add some logic to slide the page content down by whatever amount of screen the navbar consumes.

- If floating the navbar in the `/docs` section of the site is not a requirement, we could turn it off. (I would prefer this option as a frequent reader of the docs, but there are other considerations.)

- Something else?
</blockquote>

FWIW I just took a look and ours is the only of Oracle, Postgres, MySQL, SQLite that has a floating header on their tech docs.

I'm personally in favor of not having a floating navbar in the spirit of increasing  "information density" for frequent readers but I suppose that discussion belongs in #2195 

Whatever solution is chosen, any fix for this is appreciated - thank you!

**Comment by mjibson** [comment]
This is still happening with the new managed header: https://www.cockroachlabs.com/docs/v2.1/import.html#available-storage

**Comment by jseldess** [comment]
This has become a glaring UX problem with our secondary topnav. @j-low, any chance you can fix this soon?

**Comment by rmloveland** [comment]
I am still having this issue when trying to link directly to a particular row in a table (specifically, I'm trying to add anchor links to specific flags such as `--max-offset` in [Start a node](https://www.cockroachlabs.com/docs/stable/start-a-node.html) because linking to a giant list of stuff and asking the user to search from there is very confusing IMO).

I'm reopening this issue since it appears to still be a problem.  I've attached a screenshot below shows the bug acting up in my local environment, followed by what it should look like (IMO).

![screenshot 2019-02-21 11 15 51](https://user-images.githubusercontent.com/1312291/53184281-c4a00c80-35ca-11e9-8b1c-8a035af2eaa7.png)

![screenshot 2019-02-21 11 16 06](https://user-images.githubusercontent.com/1312291/53184291-c964c080-35ca-11e9-816d-b4c7cdd610d3.png)

**Comment by sploiselle** [comment]
@rmloveland What are you using to link to a `<tr>` element?

**Comment by rmloveland** [comment]
Inside the table text in `start-a-node.md` I insert `<a name="flags-max-offset"></a>` inline into the Markdown table cell for `--max-offset`.  It's sorta hacky (because Markdown) but it works. :-)
