### ISSUE TITLE
Investigate additional docs testing tools

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1455]
Heard about some nice automated testing tools for docs at the Write the Docs conference last week, outlined in these slides: http://lyzidiamond.com/content-testing-wtd/#0.

Most interesting are some of these `retext` plugins: https://github.com/wooorm/retext/blob/master/doc/plugins.md#list-of-plugins

**Comment by jseldess** [comment]
Additional ideas Rachel Whitton at Pantheon:

> Our testing toolchain uses htmlproofer for HTML validation, a11y for accessibility testing, sitespeed.io for performance, a handwritten test that looks for residual merge conflict text, and behat (which we are not using appropriately, but we added it as a starting point for now).

**Comment by sploiselle** [comment]
+1 on `retext` plugins, especially `retext-equality`, `retext-passive`, and `retext-spell`

**Comment by jseldess** [comment]
https://valelint.github.io/docs/

**Comment by jseldess** [comment]
We implemented vale, and we're running htmltest. Closing this for now. We can open issues for specific tools and recommendations, when we have them.
