### ISSUE TITLE
More explanation on backup .. as of system time

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1459]
Exalate commented:

https://www.cockroachlabs.com/docs/backup.html has examples of full and incremental backups that backup data from 10 seconds ago and older by specifying AS OF SYSTEM TIME.  More explanation how to properly determine value would be helpful.  

1.  When not specified, what is the default value being used.
2.  The value has to more recent than cluster’s last garbage collection.  A documentation or link on what this value would be helpful.
3.  document trade offs and considerations made by specifying AS OF SYSTEM TIME (current_timestamp() - INTERVAL '0:0:10')
4. if default best practice is -10 sec, should that be the documented default (see 1)

**Comment by sploiselle** [comment]
> The value has to more recent than cluster’s last garbage collection. A documentation or link on what this value would be helpful.

Can I get more detail about what link you would like to see in the documentation for this, @robert-s-lee ?

**Comment by jseldess** [comment]
Thanks for opening, @robert-s-lee, and for fielding this, @sploiselle.

**Comment by robert-s-lee** [comment]
found additional info from the [backup_restore RFC](https://github.com/cockroachdb/cockroach/blob/de62e70109c23120ae8807b5d45db28c8ca223e7/docs/RFCS/backup_restore.md) 

| When not specified, what is the default value being used.
The start time is implicitly 0,0 (from RFC)

| document trade offs and considerations made by specifying AS OF SYSTEM TIME (current_timestamp() - INTERVAL '0:0:10')

[there is an existing documentation on the trade off.](https://www.cockroachlabs.com/docs/backup.html#performance).  Some additional context could help Operational DBA would likely run and monitor the command on scheduled basis at night time.  Typically, long running production jobs are also run at night.

**Comment by jseldess** [comment]
@Amruta-Ranade, another backup/restore enhancement for you.

**Comment by jseldess** [comment]
This has changed. Can't use `current_timestamp()`. Have to use literal timestamp.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
