### ISSUE TITLE
Build a Ruby App with CockroachDB Doc Update 

### ISSUE THREAD

**Issue by geowa4** [cockroachdb/docs#1461]
Re: [Build a Ruby App with CockroachDB](https://cockroachlabs.com/docs//build-a-ruby-app-with-cockroachdb-activerecord.html)

## Issue Description

From the ActiveRecord docs:
```The name of the primary key, if one is to be added automatically. Defaults to id. If :id is false this option is ignored.

Note that Active Record models will automatically detect their primary key. This can be avoided by using self.primary_key= on the model to define the key explicitly.
```

However, in the docs, it shows `create_table :accounts, force: true, id: false, primary_key: 'id'`. That has caused me some confusion since it definitely does not create the `id` column as the primary key.

## Suggested Resolution 

Remove `primary_key` option and include a mention to using `self.primary_key=` on the model.

**Comment by jseldess** [comment]
@jordanlewis, I've confirmed that the table created via our activerecord sample does not have `id` as the primary key:

```root@:26257/> show create table bank.accounts;
+---------------+--------------------------------------------+
|     Table     |                CreateTable                 |
+---------------+--------------------------------------------+
| bank.accounts | CREATE TABLE accounts (␤                   |
|               |     id INT NULL,␤                          |
|               |     balance INT NULL,␤                     |
|               |     FAMILY "primary" (id, balance, rowid)␤ |
|               | )                                          |
+---------------+--------------------------------------------+
(1 row)
```

Can you help update the ruby code?

**Comment by jseldess** [comment]
@geowa4, was playing around with this today. I wasn't able to get `self.primary_key=` on the model to work, but `t.integer :id, :primary_key => true` in the migration seems to do the job. I opened a PR with this change in case you want to review: https://github.com/cockroachdb/docs/pull/1473. Also looking for @jordanlewis's input, since he helped write up the code sample in the first place.
