### ISSUE TITLE
Docs for INSERT, UPSERT, CREATE TABLE AS and SELECT do not sufficiently explain "select clauses"

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1488]
This is an unfortunate artifact of the grammar in the source code which obfuscates this fact:
**anywhere you can have a SELECT query, you can also use TABLE and VALUES**.

SELECT, TABLE and VALUES together are the three forms of what is called a "select clause".
Any select clause is a valid data source for INSERT, UPSERT, CREATE TABLE AS, table expressions in SELECT's FROM and within value expressions as a subquery.

| Statement | Example using SELECT | Example using VALUES | Example using TABLE |
|----------------|-----------------------------------|------------------------------------|-------------------------------|
| INSERT | `INSERT INTO foo SELECT * FROM bar` | `INSERT INTO foo VALUES (1), (2), (3)` | `INSERT INTO foo TABLE bar`
| UPSERT | `UPSERT INTO foo SELECT * FROM bar` | `UPSERT INTO foo VALUES (1), (2), (3)` | `UPSERT INTO foo TABLE bar`
| CREATE TABLE AS | `CREATE TABLE foo AS SELECT * FROM bar` | `CREATE TABLE foo AS VALUES (1),(2),(3)` | `CREATE TABLE foo AS TABLE bar`
| SELECT | `SELECT * FROM (SELECT * FROM bar)` | `SELECT * FROM (VALUES (1),(2),(3))` | `SELECT * FROM (TABLE bar)`
| Expression subquery | `SELECT * FROM foo WHERE x IN (SELECT * FROM bar)` | `SELECT * FROM foo WHERE x IN (VALUES (1),(2),(3))` | `SELECT * FROM foo WHERE x IN (TABLE bar)`

I think in general it would be useful to start to convey throughout the docs that SQL is really about manipulating tabular data, and there are fundamentally just 3 ways to obtain tabular data *anywhere where it is manipulated by other statements*: **load it from the database** (TABLE), **list it by the client** (VALUES), and **compute it from other things** (SELECT).

**Comment by sploiselle** [comment]
@knz Ping. This doc could use the information about using full statements in subqueries.

**Comment by knz** [comment]
the thing that needs to be modified for that is the table expressions page - https://www.cockroachlabs.com/docs/stable/table-expressions.html

**Comment by knz** [comment]
I'll work on it.
