### ISSUE TITLE
core: Clockless read mode

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1495]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/reckakPyk8qSlcU1u

PRs: 
- https://github.com/cockroachdb/cockroach/pull/16867

**Comment by jseldess** [comment]
@petermattis, @tschottdorf , this is the overall docs issue for the clockless read mode work you're doing for 1.1. Once it's ready for docs, please assign the `ready` label and add relevant PR links?

**Comment by tschottdorf** [comment]
We have an experimental prototype for 1.1, but I don't think there's a lot to be documented. @petermattis do you agree? If so, please bump to 1.2.

**Comment by jseldess** [comment]
@petermattis, should we bump docs on clockless read mode to 1.2? Some weeks ago, we already added more explicit docs on [clock offsets]( https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#clock-synchronization).

**Comment by petermattis** [comment]
@jseldess Yes. The clockless read mode is still experimental.

**Comment by jseldess** [comment]
@petermattis, do we need to document clockless read mode for 2.0, or can I punt till later?

**Comment by petermattis** [comment]
@jseldess The clockless mode is experimental and so far not something we'd recommend. If there is any documentation, it could warn users to not use clockless mode. I'd be fine with punting to later.

**Comment by tschottdorf** [comment]
Closing as we're unlikely to move forward with clockless mode anytime soon.
