### ISSUE TITLE
core: Decommissioning a node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1496]
Roadmap: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recGdsZPsKLSD26fY
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/decommission.md
Issues:
- https://github.com/cockroachdb/cockroach/issues/17419
- https://github.com/cockroachdb/cockroach/issues/6198
 
PRs: 
- https://github.com/cockroachdb/cockroach/pull/16528
- https://github.com/cockroachdb/cockroach/pull/17272

Test:
- https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/decommission_test.go

**Comment by jseldess** [comment]
Seems like this is ready to be documented for 1.1, so I've applied the `ready` label. @tschottdorf, please chime in if you disagree.

**Comment by tschottdorf** [comment]
Ready-ish. @m-schneider is revamping the cli commands: https://github.com/cockroachdb/cockroach/issues/17419

But we should be able to write the docs soon.

**Comment by tschottdorf** [comment]
I'm done here, @jseldess. Assigning you because I don't think there's anything actionable left on my end.
