### ISSUE TITLE
core: Cert rotation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1499]
Background: 
 - RFC: https://github.com/cockroachdb/cockroach/pull/14254
 - https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recSJKR91duNibBlb

PRs: 
 - docs draft: https://github.com/cockroachdb/docs/pull/1331
 - https://github.com/cockroachdb/cockroach/pull/14925
 - https://github.com/cockroachdb/cockroach/pull/16055
 - https://github.com/cockroachdb/cockroach/pull/16101

**Comment by Amruta-Ranade** [comment]
Also refer to https://github.com/cockroachdb/docs/pull/1331

**Comment by jseldess** [comment]
@Amruta-Ranade, let's plaese also update the `--lifetime` flag description for 1.0 and 1.1 as described in https://github.com/cockroachdb/cockroach/issues/18812#issuecomment-332499669.
