### ISSUE TITLE
sql: mention that UDFs are not supported in changefeed expressions 

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/docs#15011]
Chengxiong Ruan (chengxiong-ruan) commented:

This is a docs version of [this issue](https://github.com/cockroachdb/cockroach/issues/84176). Basically, we should mention explicitly in docs that UDFs not supported in changefeed expressions as a known limitation.

Uncomment {% include {{ page.version.version }}/known-limitations/udf-changefeed-expression.md %} in [known-limitations.md](http://known-limitations.md) and [user-defined-functions.md](http://user-defined-functions.md)

Jira Issue: DOC-5575

**Comment by ajwerner** [comment]
@chengxiong-ruan can you make the PR against the docs repo to fix this?

**Comment by chengxiong-ruan** [comment]
oops... mis-clicked on `close` with my touch pad....... But yes, I'll create a pr for this.

**Comment by chengxiong-ruan** [comment]
Thanks for working on this @kathancox

**Comment by chengxiong-ruan** [comment]
resolved by : https://github.com/cockroachdb/docs/pull/15308
