### ISSUE TITLE
ui: Network diagnostics (debug page)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1507]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recDXeT1I2CzUqhAX
Owner: @BramGruneir 

PRs: 
- https://github.com/cockroachdb/cockroach/pull/16174
- https://github.com/cockroachdb/cockroach/pull/16243

**Comment by jseldess** [comment]
@BramGruneir , this is the overall docs issue for the network diagnostics page(s) you're building for 1.1. Once the work's read for docs, please assign the `ready` label and add relevant PR links.

**Comment by Amruta-Ranade** [comment]
As per discussion with Diana, not to be documented for 1.1

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2373
