### ISSUE TITLE
sql: Provide a native UUID column type

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1508]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/rechLTMWBr0DDfNyD

PR: https://github.com/cockroachdb/cockroach/pull/15930

**Comment by Amruta-Ranade** [comment]
Update FAQ: 
https://www.cockroachlabs.com/docs/stable/sql-faqs.html#does-cockroachdb-support-a-uuid-type
