### ISSUE TITLE
server: report more configuration upon initialization

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1509]
PRs: 
  - https://github.com/cockroachdb/cockroach/pull/16209 
  - https://github.com/cockroachdb/cockroach/pull/16221

**Comment by jseldess** [comment]
@a-robinson, @knz, before I document that these get logged on node startup, I'd like your help understanding how/where users set and change these. 

- Some of them are node-level flags: `max offset` = `--max-offeset`, `cache size` = `--cache`, `sql memory pool size` = `--max-sql-memory`, `linearlizable` = `--linearlizable` (though this flag is undocumented). 
- Others are cluster settings: `time until store dead` = `server.time_until_store_dead`, others?
- I'm not sure where everything else is set? Env variables? 

```
I170530 19:13:38.857967 1 server/config.go:381  server configuration:
max offset                   500ms
cache size                   1.9 GiB
SQL memory pool size         1.9 GiB
scan interval                10m0s
scan max idle time           200ms
consistency check interval   24h0m0s
metrics sample interval      10s
time until store dead        5m0s
send next timeout            500ms
pending RPC timeout          1m0s
event log enabled            true
linearizable                 false
```

**Comment by a-robinson** [comment]
Most of the rest are environment variables: https://github.com/cockroachdb/cockroach/blob/7a6984aba7840caa012e3be9ecaa32044a14d8f0/pkg/server/config.go#L538

**Comment by jseldess** [comment]
Ah, ok. Given that we don't document env variables, only flags and cluster settings, I don't think it makes sense to document these logged configurations at this time. Please reopen if you disagree.
