### ISSUE TITLE
ui/cli: Cert monitoring and debugging

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1510]
Roadmap: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recdsACzmeeP7k8nz

PRs: 
 - certificates debug page: https://github.com/cockroachdb/cockroach/pull/16087
 - certificate expiration metrics: https://github.com/cockroachdb/cockroach/pull/16045
 - prometheus alert rules for certificate expiration: https://github.com/cockroachdb/cockroach/pull/16329
 - https://github.com/cockroachdb/cockroach/pull/16045

**Comment by jseldess** [comment]
@mberhault, when you're ready for docs to get started, please apply the `ready` label and add links to other relevant PRs.

**Comment by mberhault** [comment]
This is pretty much ready. I've added another link to the alerting rules.

**Comment by Amruta-Ranade** [comment]
As per discussion with Diana, not to be documented for 1.1

**Comment by dianasaur323** [comment]
yes, i think it would be nice to do this one

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2373
