### ISSUE TITLE
ui: add a node debug page 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1516]
PRs: 
 - https://github.com/cockroachdb/cockroach/pull/16300
 - https://github.com/cockroachdb/cockroach/pull/16331

**Comment by Amruta-Ranade** [comment]
As per discussion with Diana, not to be documented for 1.1

**Comment by Amruta-Ranade** [comment]
@dianasaur323  Do we want to document this for 1.2? Or are the debug pages still hidden from the main UI?

**Comment by dianasaur323** [comment]
Still hidden. thanks!

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2373
