### ISSUE TITLE
sql/ui: Show progress of schema changes and backup/restore jobs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1517]
Roadmap items: 
- Backup and restore jobs in the admin ui (read-only): https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recmew4RyDWj8glZ9
- Schema change progress in the admin ui (read-only): https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recmew4RyDWj8glZ9

RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/jobs_monitoring.md

PRs: 
- `SHOW JOBS` sql statement: https://github.com/cockroachdb/cockroach/pull/16733
- JOBS screen in the UI: https://github.com/cockroachdb/cockroach/pull/17253

Note: `SHOW JOBS` selects from the internal `crdb_internal.jobs` table. This earlier issue provides good details on the fields returned (may be outdated now): https://github.com/cockroachdb/docs/issues/1293

**Comment by jseldess** [comment]
@jordanlewis, this is the overall docs issue for the jobs table work you're doing. Since the work will be split across multiple PRs, once it's ready for docs, can you please add relevant PR links to this issue and assign the `ready` label? Would be a big help.

**Comment by jseldess** [comment]
@Amruta-Ranade, can you look into whether parts of this work are ready to be documented for 1.1? I know that https://github.com/cockroachdb/cockroach/pull/16733 is ready. Not sure what else is ready.

**Comment by jseldess** [comment]
@Amruta-Ranade, @sploiselle, I've consolidated a number related 1.1 projects into this single issue. Essentially, there's a new `SHOW JOBS` sql statement that lets you monitor the progress of schema changes and backup/restore jobs, and there's a corresponding UI screen that lets you do the same via the UI. 

@sploiselle, would you like to take this, since it touches backup/restore, or would you like Amruta to take it, since she's working on admin ui docs?

**Comment by sploiselle** [comment]
For this, I'm going to take the SQL CLI statements and Amruta is planning to document what's possible through the Admin UI.
