### ISSUE TITLE
Make start in “insecure” mode section better 

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/docs#1523]
In the last round of research, one participant asked, "Is starting it 'insecure' best practice?" Currently, toggling between "insecure" and "secure" modes doesn't reveal much difference. Would be great to explain why I should consider using "secure" mode, or what advantages do I have if I choose to use "insecure." 

On the most surface level, perhaps the word "insecure" itself brings out more anxiety than necessary?

cc @jseldess @sploiselle

**Comment by mberhault** [comment]
We have a warning in some places (eg: https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-kubernetes.html) but that's pretty deep inside the docs.
We should have something similar on https://www.cockroachlabs.com/docs/start-a-local-cluster.html

As for anxiety, `insecure` is about as tame as we can make it, I would prefer something even more worrisome (`--insecure-no-really-this-is-stupidly-insecure`)

**Comment by jseldess** [comment]
In all of our prod deployment tutorials, we map out the dangers of `insecure` more extensively, for example, https://www.cockroachlabs.com/docs/manual-deployment-insecure.html#recommendations. I don't think we need to go so far for a local testing cluster, but I agree we should be more explicit. @sploiselle, you actually had thoughts about this that I didn't manage to integrate in my last PR. Want to take a shot at this?

**Comment by sploiselle** [comment]
We can definitely improve the documentation's treatment of secure/insecure. Glad to put this on the list.

FWIW, though, @kuanluo––developers/operators should have an "intrinsic" understanding of the benefit of a secure deployment of a distributed system. If they don't, it's strange for us to provide that kind of semi-educational material.

**Comment by mberhault** [comment]
We may need to add a specific page detailing exactly what is insecure vs secure, they vary by system with ours being a the very extremes of secure and insecure.

A few important things that should be made very clear:
* inter-node encryption vs plain
* client-node encryption vs plain
* certificate/password authentication vs no authentication
* (eventually) admin UI authentication vs no authentication

The insecure mode is so incredibly insecure that I really think we want call it out as soon as possible which would probably be the local cluster case.

**Comment by jseldess** [comment]
@mberhault, @bdarnell created a docs issue to create a more robust summary about security: https://github.com/cockroachdb/docs/issues/1460

**Comment by kuanluo** [comment]
I totally defer to you guys on the anxiety level of ```insecure```. Perhaps surfacing the security info as shown in Kubernetes sooner in Start a Cluster, as @mberhault suggested, would be sufficient as the first step.

**Comment by jseldess** [comment]
We've made secure the default in almost all places, and added some stronger language about the dangers of insecure. Closing this, in favor of further improvements noted here: https://github.com/cockroachdb/docs/issues/3549
