### ISSUE TITLE
Build a Java App with CockroachDB Doc Update 

### ISSUE THREAD

**Issue by dimsmol** [cockroachdb/docs#1528]
Re: [Build a Java App with CockroachDB](https://cockroachlabs.com/docs//build-a-java-app-with-cockroachdb.html)

## Issue Description

```java
                // Check if the error code indicates a SERIALIZATION_FAILURE.
                if(e.getErrorCode() == 40001) {
                    // Signal the database that we will attempt a retry.
                    conn.rollback(sp);
                }
                // This is a not a serialization failure, pass it up the chain.
                throw e;
```

This part ^ looks to be incorrect – it rethrows unconditionally.

## Suggested Resolution 

Either put `throw e;` into `else` clause or add `continue;` right after `conn.rollback(sp);`

**Comment by jseldess** [comment]
Thanks for reporting this, @dimsmol. We'll look into it soon.

**Comment by jseldess** [comment]
@arjunravinarayan, since you helped write this code, can you speak @dimsmo's suggestion above?
