### ISSUE TITLE
Code blocks: Make code blocks editable

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1530]
Suggested by @knz: When a user clicks in a code block, we could turn it into an HTML text editor to allow users to customize the contents before copy/pasting. 

https://github.com/cockroachdb/docs/issues/1070 and https://github.com/cockroachdb/docs/issues/1529 should come first.

**Comment by luciaaaaaaa** [comment]
@jseldess @knz following up on this as part of our redesign. is this a common pattern in other docs sites?

**Comment by knz** [comment]
(I don't remember the context of this request, so my response will be vague.)

My response: I don't know what "common" means. Based on the phrasing of the issue, I suspect this came up to answer a pain point. We don't need a problem to be common to want to solve it.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
