### ISSUE TITLE
CockroachDB in Comparison Doc Update 

### ISSUE THREAD

**Issue by daxfohl** [cockroachdb/docs#1531]
Re: [CockroachDB in Comparison](https://cockroachlabs.com/docs//cockroachdb-in-comparison.html)

## Issue Description
The label "Eventually Consistent Reads" sounds much worse than it is (if I understand correctly)
## Suggested Resolution 
Change to "Permits Stale Reads"

**Comment by jseldess** [comment]
Thanks, @daxfohl. I like your suggestion. 

@bdarnell, are you ok with this change? The dimension would be labeled `Permits Stale Reads`, with the following hovertext:

> Optionally allows reading from replicas that do not have the most recently written data.

Actually, there are a few other options here:

1. We could make the label a nominative to stay consistent with the other dimensions, perhaps `Optional Stale Reads`. The rest of the row could stay Yes and No.
2. We could make the label just `Stale Reads` and make change the per-db answer to either `No` (never stale), `Yes` (always stale), or `Optional` (can choose stale).

Thoughts?

**Comment by sploiselle** [comment]
fwiw 5 CRL engineers preferred _stale reads_ to _eventually consistent_ reads (whereas 0 preferred the converse).

Regarding the fix, your second option makes a lot of sense to me, @jseldess. I think it elucidates CRDB's behavior in relation to other databases really clearly. It's easy to imagine a developer seeing the flexibility of allowing stale reads to be a benefit.

**Comment by bdarnell** [comment]
Yeah, it's good to capture the fact that stale reads are optional in some databases. "Stale reads: yes" is generally a bad thing, but "Stale reads: optional" is a good thing (even then, the "staleness" isn't the desirable part; it's the low-latency "read from any replica" part that this option implies). I like the "Stale reads: yes (red)/no (yellow)/optional (green)" phrasing (I know we're not color-coding these currently, but I feel like for this line in particular it's unclear what the "good" answer is and some guidance would be helpful). 

There's another important dimension here: bounded vs unbounded staleness. Eventual consistency usually implies unbounded staleness; Spanner (for one) offers optional bounded staleness. (CockroachDB plans to eventually offer bounded staleness; we have decided against exposing unbounded staleness in the meantime even though it would be technically easy to do). We may want to consider adding that to this chart although it may be too much clutter.

**Comment by bdarnell** [comment]
@daxfohl Also, I'm curious: What, in your view, is the distinction between "eventually consistent reads" and "stale reads"? To me they're nearly equivalent in this context.

**Comment by daxfohl** [comment]
@bdarnell I look at `Eventually Consistent Reads:  No` and think "Wait, this database doesn't guarantee consistent reads?  Not even _eventually_ consistent?  Isn't that the whole purpose of it though?"  It took me a while to figure out that what it meant was that the label means allowing possibly-stale reads as an optimization.

Also to answer the question more directly, I'd say "eventually consistent" is a property of a system, and "stale" is a property of a read.  So "eventually consistent reads" seems not entirely well-defined.

**Comment by bdarnell** [comment]
Ah, you interpreted the "no" as "our reads aren't consistent, even eventually". That argues against trying to get too clever with the matrix here (such as a yes/no/optional framing where "yes" is bad and "optional" is best. It will take a very knowledgable reader to interpret that correctly). Maybe the line should be "Local reads" with values like "stale" for the eventually consistent systems and "optional bounded staleness" for spanner. But I'm not sure what we'd put for cockroach - we only support fully consistent reads, which may mean you have to read from a remote replica, but we try to optimize lease placement as much as possible. 

> Also to answer the question more directly, I'd say "eventually consistent" is a property of a system, and "stale" is a property of a read. So "eventually consistent reads" seems not entirely well-defined.

Yeah, that's why I prefer the "stale read" terminology too.

**Comment by daxfohl** [comment]
@bdarnell It would have been most clear to me, to use 2nd option from @jseldess, but with `No**` instead of `Optional`, with a note at the bottom that they can be configured to deliver stale reads as an optimization if desired.

**Comment by daxfohl** [comment]
Appears to have been changed. Closing.
