### ISSUE TITLE
A few rows on Functions and Operators are not rendering

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1536]
<img width="566" alt="screen shot 2017-06-08 at 7 58 35 am" src="https://user-images.githubusercontent.com/15893490/26927554-5be26e12-4c20-11e7-9e57-de81d879d0f2.png">

**Comment by sploiselle** [comment]
@dt Mind helping me tag-team this?

**Comment by sploiselle** [comment]
Turns out this is a [known limitation of Redcarpet](https://github.com/vmg/redcarpet/issues/477)
