### ISSUE TITLE
Feedback: Quickstart with CockroachDB

### ISSUE THREAD

**Issue by mgirod** [cockroachdb/docs#15378]
Exalate commented:

Page: https://cockroachlabs.com/docs/cockroachcloud/quickstart.html

## What is the reason for your feedback?

[x] Missing the information I need

Does one need to install a cockroach CLI? Tu create the example db? From where?

[x] Too complicated

Confusing... many pages overlapping. Unclear status.

[ ] Out of date

[x] Something is broken

The example failed to run, probably because the dbinit.sql commands were not run previously?

example-app-go-pgx> go run main.go
2022/10/17 11:47:25 Creating new rows...
2022/10/17 11:47:27 error: ERROR: relation "accounts" does not exist (SQLSTATE 42P01)
exit status 1

[ ] Other

## Additional details

Jira Issue: DOC-5964

**Comment by imhamzaazam** [comment]
Were you able to resolve this?
