### ISSUE TITLE
Feedback: Transport Layer Security (TLS) and Public Key Infrastructure (PKI)

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#15408]
Florence Morris commented:

Page: https://cockroachlabs.com/docs/v22.1/security-reference/transport-layer-security.html

## What is the reason for your feedback?

[ ] Missing the information I need

[ ] Too complicated

[ ] Out of date

[ ] Something is broken

[X] Other **Typos**

## Additional details

`these requests are be TLS encrypted with mutual authentication` should be
`these requests are TLS encrypted with mutual authentication`

`and the server mustu authenticate the client` should be
`and the server must authenticate the client`

Jira Issue: DOC-5989

**Comment by MichaelTrestman** [comment]
These typos have both been fixed by other commits.
