### ISSUE TITLE
How to get CockroachDB data into other systems for reporting/analytics

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1550]
Since we don't have integrations with kafka-like systems, how do you do this during the normal course of business?

From a Slack thread:

- Option 1: a time travel query periodically run at a time where database load from online apps is at a minimum
- Option 2: a time travel dump

Performance would be about the same. A dump however can capture multiple tables at once; also a dump generates the exported data using SQL syntax, so presumably you can import it into another SQL database more easily.

cc: @nstewart, @knz, @bdarnell

**Comment by bdarnell** [comment]
Incremental backups should perform better than either of these options, so the best way to do this (in the absence of some streaming solution) would be to either make incremental backups and then transform them into the desired format, or introduce some new functionality using the incremental backup infrastructure (time bounded iterators, etc).

**Comment by jseldess** [comment]
We have CDC now, so closing this.
