### ISSUE TITLE
Clarify docs on backup to GCS

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#1551]
The [BACKUP](https://www.cockroachlabs.com/docs/backup.html) docs say the parameters for the `gs://` backup scheme are "None––currently only supports instance auth, but we can build non-instance auth at a customer's request". What exactly does "instance auth" mean? How do I give my instance the appropriate access to a bucket?

**Comment by sploiselle** [comment]
@danhhz Can you answer Ben's question for me and I can potentially modify the doc with appropriate info?

**Comment by dt** [comment]
On many of the cloud providers, when you run a VM on their computing offering, they add a socket, special file, network-backed mechanism for processes running on that VM to retrieve authorization credentials associated with the account that owns the VM, which can then be used when accessing other resources offered by that provider. Most of the SDKs they offer for interacting with their services then include support for retrieving/using that machine-speicifc authorization, in place of proving explicit credentials when initializing/calling the client library.

**Comment by bdarnell** [comment]
And when I have a bucket and an instance that can't write to it, how do I fix it? I'm in a maze of twisty IAM docs, all alike...

**Comment by bdarnell** [comment]
OK, I have it working now. I had to go into the GCE console, stop the instance, change the storage access scope to read/write, copy the service account email address, go to the GCS console and give that account access to the bucket, then restart the instance.

**Comment by sploiselle** [comment]
@bdarnell If you could walk me through this so I can add it to the docs, we can hopefully save someone the frustration in the future.

**Comment by jseldess** [comment]
@mwang1026, @lnhsingh, is this docs issue still relevant?

**Comment by bdarnell** [comment]
The docs have been improved here, so I think we can close it.

**Comment by mwang1026** [comment]
Agreed we can close so closing. We're planning a reorg to make file storage its own separate section at which point we'll scrutinize the level of detail at that point as well.
