### ISSUE TITLE
core: Command queue optimization for read-only workloads

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1558]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recRoc1FYLw7XFAIG

PRs: None yet

**Comment by jseldess** [comment]
@tschottdorf, we may want to include details about this in conceptual documentation, so once the work is done, please assign the `ready` label and add relevant PR links.

**Comment by petermattis** [comment]
@jseldess This is pretty low-level. I don't think there is any documentation work to be done here.

**Comment by jseldess** [comment]
OK, thanks, @petermattis.
