### ISSUE TITLE
core: Expand docs on rolling upgrades

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1559]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recKby3c0SLGQtDj7

**Comment by jseldess** [comment]
@mberhault, we already have basic documentation on rolling upgrades, but during testing, if you identify details/tips that should be exposed externally, please lets us know.

**Comment by jseldess** [comment]
Also, as @sploiselle mentions in https://github.com/cockroachdb/docs/issues/1182, we may want an asciicast showing taking node down, upgrading binary, rejoining cluster, as well as docs on automating rolling upgrades.

**Comment by jseldess** [comment]
@mberhault, this is marked as "done" in AirTable. Do you have any insights/tips that should be added to our [docs](https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html)?

**Comment by mberhault** [comment]
I think somewhere between steps 3) and 4) we should mention to wait for the node to stop, either by looking at the list of running processes (eg: `ps aux | grep cockroach`) or looking in the log files for `server drained and shutdown completed`
