### ISSUE TITLE
Feedback: Statements Page

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#15607]
Florence Morris (florence-crl) commented:

Page: https://cockroachlabs.com/docs/cockroachcloud/statements-page.html

## What is the reason for your feedback?

[ X] Missing the information I need

[ ] Too complicated

[ ] Out of date

[ ] Something is broken

[ ] Other

## Additional details

Refer to https://github.com/cockroachdb/cockroach/issues/91763#issuecomment-1312250948

Hidden columns should be mentioned in the section for the Statements table: https://www.cockroachlabs.com/docs/cockroachcloud/statements-page.html#statements-table

Also from this comment: https://github.com/cockroachdb/cockroach/issues/91763#issuecomment-1312241447,
explain how a Statement Fingerprint ID can be used to query the `crdb_internal.statement_statistics`:

>  then on cli you can look for that fingerprint adding the \x at the start of the value like this:
> `select * from crdb_internal.statement_statistics where fingerprint_id='\xe56448b12fbe7990';`
> 
> or encoding the fingerprint column like this:
> `select * from crdb_internal.statement_statistics where encode(fingerprint_id, 'hex')='e56448b12fbe7990';`

Jira Issue: DOC-6180

**Comment by maryliag** [comment]
There was an issue for this, but shows as closed (maybe by accident?): https://github.com/cockroachdb/docs/issues/14960

**Comment by maryliag** [comment]
To clarify, these changes are valid for both Statements and Transactions.
