### ISSUE TITLE
sql: Enable storing non-PK ARRAY columns

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1561]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recIfrzTv0P5w7Gf7
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/array_encoding.md
PRs:
- cockroachdb/cockroach#16764
- https://github.com/cockroachdb/cockroach/pull/17318
- https://github.com/cockroachdb/cockroach/pull/17331
- https://github.com/cockroachdb/cockroach/pull/17489
- https://github.com/cockroachdb/cockroach/pull/17455 (sql: support <type> ARRAY syntax in CREATE

**Comment by jseldess** [comment]
@justinj, this is the docs issue for the `ARRAY` work you're doing for 1.1. Once it's ready for docs, please add the `ready` label and links to relevant PRs. Thanks!

**Comment by jseldess** [comment]
Ping, @justinj: Is this work ready for docs?

**Comment by sploiselle** [comment]
Some of this landed in cockroachdb/cockroach#16764

**Comment by justinj** [comment]
A bunch of the ARRAY stuff has landed, but they're not *really* usable until [17318](https://github.com/cockroachdb/cockroach/pull/17318) and to a lesser extend [17331](https://github.com/cockroachdb/cockroach/pull/17331) merge (which I don't think are too far off, so I'll ping this thread once they do).

**Comment by justinj** [comment]
This is ready for docs! @sploiselle @jseldess feel free to grab me any time if you want to discuss.

**Comment by jseldess** [comment]
Will do, @justinj. Thanks.

**Comment by Amruta-Ranade** [comment]
To-Do: Need to update "Size" section in Bytes and Arrays docs: Update size to 1MB.
