### ISSUE TITLE
sql/cli: Inspect running queries (SHOW SESSIONS and SHOW QUERIES)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1562]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recxCTpBVipNFFHll

PRs: 
- https://github.com/cockroachdb/cockroach/pull/16072
- https://github.com/cockroachdb/cockroach/pull/16543
- https://github.com/cockroachdb/cockroach/pull/16602
- https://github.com/cockroachdb/cockroach/pull/17579

**Comment by jseldess** [comment]
@cuongdo, @vivekmenezes, @knz, @itsbilal, @asubiotto, you're all listed as owners for this in airtable. Once there's docs-relevant work here, can one of you please assign the `ready` label and add links to relevant PRs?

**Comment by itsbilal** [comment]
The implementation PR (already merged): https://github.com/cockroachdb/cockroach/pull/16072

**Comment by knz** [comment]
@itsbilal here is what I wrote on Airtable:
> There is a PR already merged for this https://github.com/cockroachdb/cockroach/pull/16072 however this does not yet detail distributed queries. For example **it does not say on each node how many queries are being executed on behalf of other nodes.**

**Comment by jseldess** [comment]
@knz, will those details come with the [`Track and report in-flight query execution stats`](https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recnrbh1GsETw2E7D) project?

**Comment by knz** [comment]
I don't think so. That project will report how long a query is running and how many rows it was processing, but not on which nodes it is running. Also that project is doing "for this query, give me information about that query", not "for this node, give me all queries"

**Comment by jseldess** [comment]
Got it. Thanks for the clarification, @knz.
