### ISSUE TITLE
multi-region: PLACEMENT syntax is missing from ALTER DATABASE docs

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/docs#15631]
Adam Storm (ajstorm) commented:

https://www.cockroachlabs.com/docs/stable/alter-database.html doesn't include the PLACEMENT syntax mentioned here: https://www.cockroachlabs.com/docs/stable/placement-restricted.html

Jira Issue: DOC-6204

**Comment by rmloveland** [comment]
hi @ajstorm I think this is now resolved by a big revamp of the `ALTER DATABASE` page (and other SQL docs) that was done by @taroface in 6888e533d14e81d085891f21007163e1ec03aa82 

AFAICT the state as of now is that the PLACEMENT syntax is appearing in the diagram at 

https://www.cockroachlabs.com/docs/stable/alter-database.html#synopsis 

and the description of said syntax is here:

https://www.cockroachlabs.com/docs/stable/alter-database.html#placement

these look ok to me now and seem to match - but am I missing something?

**Comment by ajstorm** [comment]
LGTM.  ABC - Always Be Closing.
