### ISSUE TITLE
distsql: Support outer joins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1564]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recgn1mKTiwiSBov0

PRs:
- https://github.com/cockroachdb/cockroach/pull/16372
- https://github.com/cockroachdb/cockroach/pull/17017

**Comment by jseldess** [comment]
@asubiotto, once this work is ready for docs, please assign the `ready` label here and add links to relevant PRs. Thanks!

**Comment by jseldess** [comment]
This is really part of adding more robust documentation on JOINs. As of now, we mention joins only in the [table expressions](https://www.cockroachlabs.com/docs/stable/table-expressions.html#join-expressions) doc. Most of the info is in blog posts.

**Comment by asubiotto** [comment]
@jseldess, an external contributor took this on and merged [this PR](https://github.com/cockroachdb/cockroach/pull/17017).

**Comment by jseldess** [comment]
Thanks, @asubiotto. We'll have to cover this when we have properly detailed docs on distributed sql, but I think that'll have to wait for 1.2.

**Comment by jseldess** [comment]
Given the plans to merge the local and dist sql engines, closing this for now.
