### ISSUE TITLE
distsql: Distsql support for UNION, INTERSECT, EXCEPT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1566]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recyYEWVr1MitVEL2

PRs:

**Comment by jseldess** [comment]
@cuongdo, @arjunravinarayan, we don't yet have conceptual docs on distsql, but we aim to, so once this work is done, please add the `ready` label here and link to any relevant PRs.

**Comment by jseldess** [comment]
@arjunravinarayan, any updates? Will this work still be in 1.1?

**Comment by arjunravinarayan** [comment]
No, this will not make it into 1.1. It got bumped in favor of other roadmap items.

**Comment by jseldess** [comment]
Thanks for the update, @arjunravinarayan. Can you update the release target in AirTable then?

**Comment by jseldess** [comment]
No direct doc updates at this time.
