### ISSUE TITLE
cli: Cancel running queries (general and distributed)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1571]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recx2noB8HJXLwbFF
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/query_cancellation.md

PRs: 
- https://github.com/cockroachdb/cockroach/pull/16405
- https://github.com/cockroachdb/cockroach/pull/17003 (`CANCEL` statement)

**Comment by jseldess** [comment]
@vivekmenezes, @cuongdo, who's doing this work? I'd like to ask that person to update this issue once it's docs ready.

**Comment by jseldess** [comment]
@benesch, is it too early to start looking at this from a docs perspective?

**Comment by benesch** [comment]
Most likely too early, I'm afraid. `PAUSE`/`CANCEL` don't actually _do_ anything yet.

cc @itsbilal @jordanlewis

**Comment by sploiselle** [comment]
@jseldess Ah! Sorry I missed this issue. I looked for an issue with "`CANCEL QUERY`" in the title and GitHub missed this.

**Comment by jseldess** [comment]
No problem, @sploiselle. I just took the name from the feature in the backlog.
