### ISSUE TITLE
cli: Inspect connected sessions on a cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1572]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/rec829jnTw7V4oa50

PRs:
- https://github.com/cockroachdb/cockroach/pull/16072

**Comment by jseldess** [comment]
@vivekmenezes, @cuongdo, do we know who's doing this work?

**Comment by jseldess** [comment]
@vivekmenezes, @itsbilal, this item is marked as "done" in AirTable. Can either of you tell me who did this work and point me to the relevant cockroach PR?

**Comment by itsbilal** [comment]
I did the work, and the PR was https://github.com/cockroachdb/cockroach/pull/16072 .

**Comment by jseldess** [comment]
Thanks, @itsbilal!
