### ISSUE TITLE
backup/restore: Local and distributed bulk ingest from CSV

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1576]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recV0TVmYUd41MNvD

PRs: 
- https://github.com/cockroachdb/cockroach/pull/16611 (this isn't distributed, though)
- https://github.com/cockroachdb/cockroach/pull/17496
- https://github.com/cockroachdb/cockroach/pull/17539 (distributed!)
- https://github.com/cockroachdb/cockroach/pull/17700

**Comment by jseldess** [comment]
@mjibson, once this work is ready for docs, please apply the `ready` label and add links to relevant PRs here. Thanks!

**Comment by jseldess** [comment]
@mjibson, with https://github.com/cockroachdb/cockroach/pull/16611 (non-distributed ingest from csv), is this work now complete for 1.1 and ready to be documented? Or will there be additional work?

**Comment by mjibson** [comment]
Oh, sorry about not adding the labels. I forgot about this.

Yes to both. You can document the `load csv` command now, but there will also be additional work for distributed csv loading. We can document that too when it gets done I think.

**Comment by jseldess** [comment]
Thanks, @mjibson. @sploiselle, this is ready to start whenever you have time. No rush though, obviously. Still plenty of time before 1.1, and you have other more immediate priorities.

**Comment by jseldess** [comment]
@mjibson, both local and distributed ingest from CSV are ready for docs now, right?

**Comment by mjibson** [comment]
Yes.

**Comment by jseldess** [comment]
@sploiselle, I know @dianasaur323 spoke to you directly about this, but in case you need it, here's the PR that puts csv import behind a cluster setting while it's beta. We need to document that and the fact that it's free while in beta.

https://github.com/cockroachdb/cockroach/issues/18608

**Comment by mjibson** [comment]
Wait why do we need to document that it's free while in beta? I thought it was going to free forever.

**Comment by jseldess** [comment]
@mjibson, I was just responding what Diana said here: https://github.com/cockroachdb/cockroach/issues/18608. Perhaps this is still in discussion?

**Comment by dianasaur323** [comment]
It will definitely always be free - we were just discussing potentially asking users to sign up to use the feature. We haven't decided on it yet, but I just wanted to make sure we don't close the door on that option with our wording.
