### ISSUE TITLE
backup/restore: Pause, resume, cancel jobs via SQL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1577]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recNgWRVYkYg3Ytr7

PRs: 
- https://github.com/cockroachdb/cockroach/pull/17434

**Comment by jseldess** [comment]
@benesch, once this work is ready for docs, please apply the `ready` label and add links to relevant PRs here. Thanks!

**Comment by jseldess** [comment]
@benesch, based on airtable, this is in development. Just checking to make sure it'll still be in 1.1?

**Comment by benesch** [comment]
Afraid I'm not sure—it depends whether it's too late to land https://github.com/cockroachdb/cockroach/pull/17434!

**Comment by jseldess** [comment]
Thanks, @benesch. Just let me know when you know.

**Comment by jseldess** [comment]
Since https://github.com/cockroachdb/cockroach/pull/17434 landed, marking this as `ready` for docs. @benesch, please let us know if there's anything else still coming.

**Comment by benesch** [comment]
Nope, this is ready to be documented!

**Comment by jseldess** [comment]
Note: pause/cancel/resume schema changes will be in 1.2: https://github.com/cockroachdb/cockroach/issues/16018

**Comment by sploiselle** [comment]
@jseldess @benesch Should this milestone be 1.1 or 1.2?

**Comment by jseldess** [comment]
I'm pretty sure this made it into 1.1, though only for backup/restore, not for schema changes. @benesch?

**Comment by benesch** [comment]
Yup, that's right. Only backup and restore will support pause/resume/cancel in 1.1.

**Comment by jseldess** [comment]
@sploiselle, just noticed this PR, which makes it so that `IMPORT` jobs can't be canceled/paused/resumed. Probably something to call out in these docs. 

https://github.com/cockroachdb/cockroach/pull/18142
