### ISSUE TITLE
backup/restore: Production cookbook documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1579]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/rec8Xznn6jiFnBvX4

PRs:

**Comment by jseldess** [comment]
@dt, when you ready to start working with docs on this, please add the `ready` label and we'll sync.

**Comment by jseldess** [comment]
@sploiselle, from AirTable: 
> Starting this in August post feature freeze (as per our 1.2 catch up)

**Comment by jseldess** [comment]
@dt, @dianasaur323, @Amruta-Ranade, is this something that'll still happen for 2.0?

**Comment by dianasaur323** [comment]
@jseldess how does this overlap with the outline that we created around three months ago with marc?

**Comment by jseldess** [comment]
It doesn't really. This is backup/restore-specific. Whereas the other work I'm doing is broader production guidance.

**Comment by dianasaur323** [comment]
Ah, ok. On the docket is to do a backup / restore white paper, so @dt unless you have time to work on this, let's wait for that to come out and we can see if that addresses these needs, at least partially?
