### ISSUE TITLE
backup/restore: Point in time rollback

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1580]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recHYLyRDqHrOR4Zi

PRs:

**Comment by jseldess** [comment]
@danhhz, once this work is ready for docs, please apply the `ready` label and add links to relevant PRs. Thanks!

**Comment by dianasaur323** [comment]
@jseldess we aren't going to do this in 1.2. Let's close out? We'll do a different approach for now.

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/2008.
