### ISSUE TITLE
User authentication in the Admin UI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1582]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recXCWr6wysvhsGN7
PM: @piyush-singh 
Eng Partner: 

RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/web_session_login.md
PRs: 
- https://github.com/cockroachdb/cockroach/pull/17343

**Comment by jseldess** [comment]
@mrtracy, once this work is ready for docs, please apply the `ready` label and add links to relevant PRs here. Thanks!

**Comment by Amruta-Ranade** [comment]
As per discussion in Admin UI weekly, not to be documented for 1.1

**Comment by jseldess** [comment]
FYI, @amruta, according to our internal roadmap, this has been moved to 1.3.

**Comment by jseldess** [comment]
@Amruta-Ranade, reopening since the initial PR doesn't represented the finished work.

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/28416

From release notes:
> Login is now required by default on secure clusters. [#28416][#28416] {% comment %}doc{% endcomment %}

@Amruta-Ranade, as discussed offline, this is basically ready.
