### ISSUE TITLE
ui: Add tracking/telemetry to admin UI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1583]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/rec6xodFBxAEJLOUe

PRs:

**Comment by jseldess** [comment]
@mrtracy, once this work is done, please add the `ready` label and links to relevant PRs. We'll want to be transparent about these metrics in our docs.

**Comment by dianasaur323** [comment]
We also have an outstanding issue here with some historical chat: https://github.com/cockroachlabs/registration/issues/60

**Comment by Amruta-Ranade** [comment]
As per discussion during the Admin UI weekly, update the existing Diagnostics page with Admin UI part.

**Comment by dianasaur323** [comment]
analytics call({
  userId: [x],
  name: '/jobs',
  properties: {
    path: '/jobs'
  }
});

analytics call({
  userId: [x],
  traits: {
    enterprise: true/false,
    userAgent: client browser,
    version: cockroachdb version
  }
});
