### ISSUE TITLE
Provide list of acceptable values for timezone data types

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/docs#15873]
Jim Hatcher (jhatcher9999) commented:

In the Postgres docs, it's possible to get a list of all acceptable TZ codes: https://www.postgresql.org/docs/7.2/timezones.html

I can't find a list like that in the CRDB docs, but I think it would be helpful.

We accept some codes like: EST & MST
But, we don't accept other standard codes like: PST & CST

We do accept "America/Chicago" but don't accept "America/New York"

So, it would be helpful to have a definitive list of codes with the corresponding offset values (the way it is in that PG doc abolve)

Jira Issue: DOC-6448

**Comment by jhatcher9999** [comment]
Rafi tells me we use this database for timezones: https://www.iana.org/time-zones

**Comment by jhatcher9999** [comment]
Marcus says: Postgres has a `pg_timezone_names` table that lists all the supported timezones, their nicknames, and their offsets. We haven’t implemented this table yet.

**Comment by rafiss** [comment]
> We do accept "America/Chicago" but don't accept "America/New York"

That one is in the timezone database, but needs to be spelled as "America/New_York"

**Comment by rmloveland** [comment]
made a PR to address this: https://github.com/cockroachdb/docs/pull/16483
