### ISSUE TITLE
FAQ: retry errors in client code

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1587]
> Hi I am getting following error while trying to insert a record in the cockroach database
> 2017/06/12 14:20:14 pq: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn "sql txn" id=b883b62a key=/Table/61/1/252991288616976385/0 rw=true pri=0.03176439 iso=SERIALIZABLE stat=PENDING epo=0 ts=1497277214.155826165,1 orig=1497277214.153029112,0 max=1497277214.156661173,0 wto=false rop=false seq=2

**Comment by sploiselle** [comment]
@knz Does `pq: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn "sql txn"` indicate that the client can restart the transaction with `SAVEPOINT`?

**Comment by knz** [comment]
The text of the error has multiple forms (I don't know the exact list) but they should all be reported with the same numeric code on the pgwire protocol that indicates a retry is needed -- I also recall having seen this numeric code on the page that already deals with transactions.

From the top of my head the following messages can appear:

- `restart transaction`
- `retry txn`

@andreimatei do we have an inventory of the various strings that end up as retryable errors?

**Comment by sploiselle** [comment]
@andreimatei I understood that errors were supposed to surface with the `40001` code, but I don't see that listed anywhere in here. Is the error code not printed to `stderr`?

**Comment by knz** [comment]
The issue is that in most client drivers/libraries the numeric code is a non-standard thing that the client has to actively search. Most clients/libraries will simply not print the numeric code by default.

**Comment by andreimatei** [comment]
Besides the fixed error code, the error message as reported by the server always has the `restart transaction:` prefix. The client driver might prepend another prefix (like the "pq: " above); that's out of our control.

Some client drivers give you access to the error code, others give you different error types (in a language-specific way), depending on that code. The code corresponds to Postgres' "SERIALIZABILITY FAILURE", so the error type name should be similar.

**Comment by sploiselle** [comment]
This came up on [the forum](https://forum.cockroachlabs.com/t/insert-failed-on-transaction/831).

We need a page on this specifically to catch searches.

These two terms seem consistent in the error message:

- `restart transaction`
- `TransactionRetryError`

This guidance should also be surfaced more clearly in the getting started docs using the extant code samples for transaction retries ([e.g. Go sample](https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb.html#transaction-with-retry-logic)).

**Comment by knz** [comment]
Also the documentation should add more layers of explanations about:

- why this error exists in the first place
- how and why this differs from pg
- where to push for help when using a client framework that doesn't speak SQL directly (hint: not at cockroach labs)

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5476
