### ISSUE TITLE
sql: introduce SHOW SESSION TRACE, replace EXPLAIN(TRACE) by SHOW TRACE FOR

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1598]
Roadmap item: [Make EXPLAIN(TRACE) useful](https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recbY8dQqTo18U8tj)

PR: https://github.com/cockroachdb/cockroach/pull/16524

**Comment by sploiselle** [comment]
Make sure to integrate this into the troubleshooting content, e.g. https://www.cockroachlabs.com/docs/dev/query-behavior-troubleshooting.html

**Comment by jseldess** [comment]
@andreimatei has agreed to help us out (in our time of 1.1 need) to create a first version of these docs! I'll create a stub page with the diagram and structure in place and he'll take it from there.

**Comment by jseldess** [comment]
Hey @andreimatei, have you had time to get started on this?

**Comment by andreimatei** [comment]
getting started
