### ISSUE TITLE
Incomplete language on the COLLATE page 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1599]
See last paragraph under **Details**:

> However, the COLLATE feature does not require additional disk space because collated strings are stored on disk in the same way as STRING values, i.e.,

@sploiselle, do you have a sense of what's missing there?

**Comment by bdarnell** [comment]
This sentence is also partially outdated: columns that use a collated type do not require extra space *unless they are indexed*.

**Comment by sploiselle** [comment]
@eisenstatdavid Any idea what I would've meant, or suggestions for clarifying given their new indexing behavior?

**Comment by eisenstatdavid** [comment]
Something like "Collated string columns require more space than uncollated string columns with the same data if they are indexed. In this case, collation keys must be stored in addition to the strings from which they are derived, creating a constant factor overhead."

**Comment by bdarnell** [comment]
It might be worth mentioning that collation keys can be quite large. I've done some small tests and they're almost (but not quite) six times the size of the original string. (and it varies depending on what exactly is in the string and in what language. Strings containing the character `é` produce larger collation keys in the french locale than in chinese)

**Comment by jseldess** [comment]
This seems like a quickish fix, so I'm giving it the 1.1 milestone, @sploiselle.

**Comment by sploiselle** [comment]
👍
