### ISSUE TITLE
Deploy CockroachDB on Google Cloud Platform GCE Doc Bug 

### ISSUE THREAD

**Issue by grempe** [cockroachdb/docs#1602]
Re: [Deploy CockroachDB on Google Cloud Platform GCE](https://cockroachlabs.com/docs//deploy-cockroachdb-on-google-cloud-platform.html)

## Issue Description

This how-to, which includes instructions for running a secure cluster, instructs the reader to setup a Google Cloud TCP load balancer with the health checks for that LB pointing to port 8080 and the `/health` endpoint.

However, I don't believe this is possible to make work as the TCP (Network) load balancer that Google offers [only supports legacy HTTP health checks](https://cloud.google.com/compute/docs/load-balancing/health-checks) and if you make a request to the CRDB server with HTTP it redirects the client with a 308 Permanent Redirect to the HTTPS version of that /health check URL. This non-200 response causes the LB health check to fail and all CRDB hosts behind the load balancer are marked as unavailable.

Here is an example request on a CRDB running in secure mode, redirecting all requests to an `http` url to an `https` url.

```
$ curl -k -i http://0.0.0.0:8080/health
HTTP/1.1 308 Permanent Redirect
Location: https://0.0.0.0:8080/health
Date: Sat, 17 Jun 2017 04:32:44 GMT
Content-Length: 63
Content-Type: text/html; charset=utf-8

<a href="https://0.0.0.0:8080/health">Permanent Redirect</a>.

```
The outcome of this is that it appears to be impossible to use the Google TCP load balancer with CRDB, while also having the ability to take CRDB servers out of the rotation if they are no longer healthy.

## Suggested Resolution 

Stop CRDB from redirecting calls the `/health` to an `https` URL. Update the documentation to provide an alternative that works.

**Comment by jseldess** [comment]
Thanks for reporting this, @grempe! We'll take a closer look at required doc updates soon.

**Comment by mberhault** [comment]
For info:
Our current docs suggest using "Network load balancing" which is the legacy service and only support HTTP health checks: https://cloud.google.com/compute/docs/load-balancing/network/?hl=en_US. Another issue is that it cannot balance across zones.

We should switch this to point to the newer load balancer called "TCP Load Balancing", works across zones, and can use HTTP, HTTPS, SSL, or TCP health checks: https://cloud.google.com/compute/docs/load-balancing/tcp-ssl/tcp-proxy

**Comment by dsymonds** [comment]
I think that the fix might be incomplete. If I try to follow the instructions, I get a failure creating the backend service, with a message saying that HTTP(S) health checks can't be used with TCP/UDP/SSL backend services. If the health check has to hit `/health` (via HTTP(S)) then TCP balancing won't work; alternatively, TCP health checking only does an SSL handshake to probe the backend, so won't hit a specific path.
