### ISSUE TITLE
Build an App: Update txn code samples to return values as part of the transaction

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1606]
In our code samples with transaction retry logic, the transaction doesn't return anything but errors or, sometimes, a success message. The code performs a select on the updated account balances *after* the transaction. 

Instead, we should adapt the transaction wrapper to allow values to be returned to the client, and then return the updated account balances as part of the transaction. 

- [ ] [Go](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.go)
- [ ] [Python](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.py)
- [ ] [Ruby](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.rb)
- [ ] [Java](https://github.com/cockroachdb/docs/blob/master/_includes/app/TxnSample.java)
- [x] [Node](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.js) (The wrapper is ready (see https://github.com/cockroachdb/docs/pull/1603), but the transaction itself needs to be updated and the `SELECT` following the transaction needs to be removed) 
- [ ] [C++](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.cpp)
- [ ] [Clojure](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.clj)
- [ ] [PHP](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.php)
- [ ] [Rust](https://github.com/cockroachdb/docs/blob/master/_includes/app/txn-sample.rs)

**Comment by awoods187** [comment]
@vy-ton can PTAL at this?

**Comment by vy-ton** [comment]
@jseldess I'm taking a look at this.

Are you suggesting perform the [select](https://docs.google.com/document/d/1uOsExAcVaGfT_Hh1VPBmFpg1x8R43g3OrKNKAHrCSAs/edit) as part of the transaction itself?

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
