### ISSUE TITLE
Orchestrate CockroachDB with Docker Swarm Doc Update 

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#1617]
Re: [Orchestrate CockroachDB with Docker Swarm](https://cockroachlabs.com/docs//orchestrate-cockroachdb-with-docker-swarm.html)

## Issue Description

The instructions to create a client certificate are very subtle, just a short phrase with link under section 5, bullet 5.

## Suggested Resolution 

Since we have a sample `cockroach sql` invocation, we should have a specific step to create a client certificate as well.

**Comment by tirithen** [comment]
Make sure to also add an explanation on how to use the required parameter --ca-key=<path-to-ca-key> inside of the container since the ca key is to be kept secret and I guess outside of the container because of that. Maybe move it inside temporarily and delete it afterwards? I'm new to this so just giving random suggestions here.

**Comment by tirithen** [comment]
Also take into consideration that /run/secrets are read-only

```
root@fe71ca7e5a87:/cockroach# ./cockroach cert create-client --certs-dir=/run/secrets --ca-key=/root/ca.key root
Error: failed to generate client certificate and key: error writing node server certificate to /run/secrets/client.root.crt: open /run/secrets/client.root.crt: read-only file system
Failed running "cert"
```

So if the root certificate is created inside one of the cockroachdb docker containers it should afterwards be exported and added as a secret.

**Comment by mberhault** [comment]
The certificates are passed to the containers through the secrets mechanism. You should do the same for the client certificate: generate it outside the container, and specify it through secrets.
Copying the ca key onto the containers is a big no-no.

You probably don't need client certificates on the cockroach container either. Whatever client you're using should be running either outside docker swarm entirely, or in its own containers with their own secrets.

**Comment by tirithen** [comment]
Thanks for the input, I deleted the comments since I realized this when reading the guide once again.
