### ISSUE TITLE
dangling docs link from DB Console login screen

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#16176]
Andrei Matei commented:

The login page has a [Read more about configuring login](https://www.cockroachlabs.com/docs/stable/ui-overview.html#db-console-security) link. The section of the docs that the link points to seems to have disappeared.

More generally, I wasn't satisfied with our docs around what one has to do in order to be able to log into a newly created secure cluster. I believe that one way or another, a sql user with a password has to be created, but that doesn't seem to be spelled out very clearly. I can imagine someone who just created a cluster being very confused about what's required from them. There's probably room to sprinkle references to this between the DB Console docs, the new cluster docs, and whatever page is linked to from the UI itself.

Jira Issue: DOC-6833

**Comment by florence-crl** [comment]
closing this issue in favor of: https://github.com/cockroachdb/cockroach/issues/108633
