### ISSUE TITLE
Clarify granting `ON DATABASE` vs. `ON TABLE table.*`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1635]
Clarify in docs: 
- `ON DATABASE` grants are copied to new tables when they are created, but existing tables in the database are not changed.
- `ON TABLE table.*` grants apply to all existing tables in a database but won't affect tables created after the grant.

**Comment by bdarnell** [comment]
We need to document this for now, but I'd also like to see this behavior changed: cockroachdb/cockroach#16790
