### ISSUE TITLE
New/changed in 1.1 callout

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1639]
Once https://github.com/cockroachdb/docs/pull/1605 lands, and we start changing and expanded 1.1 pages, we'll need a way to callout out these changes to users. 

First thought is to design a little intuitive icon that we can place next to a heading or paragraph that, on hover, says `New in 1.1` or `Changed in 1.1`. @kuanluo, thoughts?

**Comment by kuanluo** [comment]
Can you share some examples, @jseldess? I couldn't visualize what a scenario might look like.

**Comment by bdarnell** [comment]
Python is good at labeling changes between versions. They just use a note in the text. Look for "New in version" or "Changed in version" on [this page](https://docs.python.org/3/library/ssl.html)

**Comment by jseldess** [comment]
I like how Python does it, too. I was thinking it could be just as effective, and actually easier for scanning, if we had some type of icon that, on hover, shows text like what Python uses. 

For example, this section is new in our 1.1 docs: https://www.cockroachlabs.com/docs/dev/information-schema.html#user_privileges

It'd be cool if we could put some type of icon in the margin to the left of the "User Privileges" heading and, on hover, show "New in v1.1". Not sure exactly what the icon should be though...

All that said, I'm fine starting off with text and possibly revisiting this feature later.

**Comment by jseldess** [comment]
@kuanluo, @bdarnell, here's an example of justing using words to callout a change/addition. PTAL: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/fcc87c264b57e3346b3595a6aa0e82a6cd940e7d/dev/information-schema.html#user_privileges

If we think that type of approach is sufficient, I'll close this issue.

**Comment by kuanluo** [comment]
The text by itself is a bit hard to notice, and would it be helpful to call out the new section in the green heading area as well? 

I like the icon idea, maybe a little ⭐️ ?

**Comment by jseldess** [comment]
OK, I'm happy to try icons as well. The star might be a little generic. Should we put this in DivisionOf's backlog? In essence, we'll need two icons: one with something like "New in vXX" as the hovertext, and one with something like "Changed in vXX" as the hovertext.

**Comment by kuanluo** [comment]
Good idea, @jseldess! I will put this on the backlog for Division Of.

**Comment by jseldess** [comment]
Sorry for the delay, @kuanluo. Lost track of this. 

Hovertext isn't at all a must. Was just thinking that words sometimes make "icons" bigger than ideal. We can try an icon without hover first, if you prefer.

**Comment by kuanluo** [comment]
@jseldess 

I'm leaning towards using text badges, as people seem to be familiar with them? I will come up with a few variations for you to look over today.

**Comment by kuanluo** [comment]
After looking at this for a bit, @jseldess. I agree that sometimes the tag look too big than ideal. Two proposals: 

## A - Add icon to your proposed solution (could be hover on TOC)
TOC:
![image](https://user-images.githubusercontent.com/1486483/28080235-4005e2fe-6639-11e7-8497-5a3b08d0e206.png)
Body - Insert the icon on the left margin so it's more noticeable:
![image](https://user-images.githubusercontent.com/1486483/28080244-47f5f896-6639-11e7-8660-43c39d65c510.png)

## B - Use badge as hover text
TOC:
![image](https://user-images.githubusercontent.com/1486483/28080389-dc80cffe-6639-11e7-83b5-ebd0c4310bcc.png)
Body:
![image](https://user-images.githubusercontent.com/1486483/28080407-e7b5854a-6639-11e7-9d9e-723a9f362907.png)

What do you think?

**Comment by jseldess** [comment]
Thanks for continuing to think this through, @kuanluo! I like option A better than B. But it won't be easy (or even possible) to get the icon to show up to the right of the topic in the TOC and to the left of the topic on the page. 

But that's an implementation detail. Let's go with this idea, if you're happy with it. What would the next steps be?

**Comment by kuanluo** [comment]
Cool, I like option A better too. Let me talk to Division Of, and see what's the implication of this approach and go from there. I will cc you there.

**Comment by jseldess** [comment]
Once https://github.com/cockroachdb/docs/pull/1721 lands, we'll be able to apply a "new" or "changed" tag both to paragraph text and to headings. We'll need to document this in `CONTRIBUTING.md`:

To add the callout to a paragraph, place `<span class="version-tag">New in v1.1:</span>` at the start of the paragraph, e.g:

```
<span class="version-tag">New in v1.1:</span> The `user_privileges` view identifies global [privileges](privileges.html).
```

To add the callout to a heading, place `<div class="version-tag">New in v1.1</div>` to the right of the heading, e.g.:

```
## This is the heading <div class="version-tag">New in v1.1</div>
```

When calling out a change, rather than something new, you'd just change `New in vX.X` to `Changed in vX.X`.
