### ISSUE TITLE
Monitor CockroachDB with Prometheus Doc Update 

### ISSUE THREAD

**Issue by rydtoft** [cockroachdb/docs#1642]
Re: [Monitor CockroachDB with Prometheus](https://cockroachlabs.com/docs//monitor-cockroachdb-with-prometheus.html)

## Issue Description
Prometheus changed the flag format change to -- instead of -

## Suggested Resolution 
Update examples to reflect the new flag format

**Comment by mberhault** [comment]
It seems flag handling is changing in 2.0 (still alpha). I'm hoping this will be documented somewhere, right now there aren't even detailed release notes.
We still have time before 2.0 is actually released, but `--` will work right now, so we may as well.
