### ISSUE TITLE
cdc: confluent schema registry argument are out of date

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/docs#16431]
Jayant Shrivastava (jayshrivastava) commented:

On [this page](https://www.cockroachlabs.com/docs/stable/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.html), we have this command:
```
confluent kafka topic consume users \
 --value-format avro \
 --from-beginning \
 --sr-endpoint {SCHEMA REGISTRY ENDPOINT URL} \
 --sr-api-key {SCHEMA REGISTRY API KEY} \
 --sr-api-secret {SCHEMA REGISTRY SECRET}
```

In the latest version of the confluent CLI (confluent version v3.3.0), the argument flags have changed:

```
confluent kafka topic consume users \
 --value-format avro \
 --from-beginning \
 --schema-registry-endpoint  {SCHEMA REGISTRY ENDPOINT URL} \
 --schema-registry-api-key {SCHEMA REGISTRY API KEY} \
 --schema-registry-api-secret {SCHEMA REGISTRY SECRET}
```

The docs should mention the confluent CLI version being used in the tutorial and show the updated arguments. 

Jira Issue: DOC-7146

**Comment by amruss** [comment]
Closing as this has been fixed
