### ISSUE TITLE
Feedback: Export Logs From a CockroachDB Dedicated Cluster

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#16557]
Jessie Lin (lin-crl) commented:

Page: https://cockroachlabs.com/docs/cockroachcloud/export-logs.html

## What is the reason for your feedback?

[ ] Missing the information I need

[ ] Too complicated

[ ] Out of date

[ ] Something is broken

[v] Other

log configuration format in the document is incorrect.
## Additional details
I followed step 8.c but the configuration is not correct
```
curl --request POST   --url https://cockroachlabs.cloud/api/v1/clusters/{cluster_id}/logexport   --header "Authorization: Bearer {secret_key}"   --data '{type: AWS_CLOUDWATCH, log_name: default, auth_principal: {role_arn}, redact: true, region: '', groups: [{log_name: sql, channels: [SQL_SCHEMA, SQL_EXEC], redact: false}, {log_name: devops, channels: [OPS, HEALTH, STORAGE], min_level: WARNING}]}'
```
After updating cluster id, role_arn, etc accordingly, I received following error
```
{
  "code": 3,
  "message": "invalid character 't' looking for beginning of object key string",
  "details": []
}%   
```
Search led me to this slack [message](https://cockroachlabs.slack.com/archives/C02GMVC5YUU/p1677537044342049?thread_ts=1676998421.207769&cid=C02GMVC5YUU]
After changing to doublequoting everything except boolean values, I was able to enable the configuration
`--data '{"type": "AWS_CLOUDWATCH", "log_name": "default", "auth_principal": "arn:aws:iam::541263489771:role/aa-globalconfig-LogExportRole", "redact": true, "region": "", "groups": [{"log_name": "cockroach_db_sql_logs", "channels": ["SQL_SCHEMA", "SQL_EXEC","SQL_PERF"], "redact": false}, {"log_name": "cockroach_db_system_logs", "channels": ["OPS", "HEALTH", "STORAGE"], "min_level": "WARNING"})}'

Jira Issue: DOC-7256

**Comment by dhartunian** [comment]
@andf-crl I think the items in 8.c need to be quoted like the other examples using --data. One easy way to check is to make sure that `echo <the data string> | jq '.'` returns a correctly indented JSON string.

**Comment by andf-crl** [comment]
Hi, sure, I'll remove the minifier entirely. I've created DOC-7269 to track this since our GH <--> Jira search is broken again.
