### ISSUE TITLE
Build a Java App with CockroachDB Doc Update - example can only run once

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#1666]
Re: [Build a Java App with CockroachDB](https://cockroachlabs.com/docs//v1.0/build-a-java-app-with-cockroachdb.html)

## Issue Description
If you run the code sample a 2nd time, it fails with `Exception in thread "main" org.postgresql.util.PSQLException: ERROR: duplicate key value (id)=(1) violates unique constraint "primary"`

**Comment by awoods187** [comment]
Closing as out of date
