### ISSUE TITLE
Add "address already in use" to common errors page

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1672]
Need troubleshooting page/info for this error:

`cockroach server exited with error: listen tcp 127.0.0.1:26257: bind: address already in use`

**Comment by jseldess** [comment]
@peeyar, thanks for chiming in. We do have a [Node startup](https://www.cockroachlabs.com/docs/stable/training/node-startup-troubleshooting.html) troubleshooting tutorial that you might find helpful, but it doesn't cover this particular error/scenario. We should and will ad docs on this at some point. 

In the meantime, can you provide more details about your cluster setup? Are you running a local cluster, with multiple nodes on your computer, for testing purposes? Or are you running a real cluster, with one node per VM?

**Comment by Amruta-Ranade** [comment]
Addressing in https://github.com/cockroachdb/docs/pull/4223
