### ISSUE TITLE
Import into existing table via copy from stdin

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1676]
Re: [Import Data](https://cockroachlabs.com/docs//v1.0/import-data.html)

## Issue Description

CockroachDB does support a limited form of copy tablename from stdin for importing a CSV file directly.

## Suggested Resolution 

Below is simpler method to import CSV file using copy from stdin

echo "copy tablename from stdin;" | cat - filename.csv  | psql

**Comment by jseldess** [comment]
This pre-dated our `IMPORT` from CSV feature. Closing. @robert-s-lee, let me know if you disagree and still want this documented.

**Comment by jseldess** [comment]
`IMPORT` is good for initial table creation, but copy from stdin is better for inserts into a non-empty table.

**Comment by jseldess** [comment]
Supplanted by https://github.com/cockroachdb/docs/issues/3982.
