### ISSUE TITLE
Test C# driver with CockroachDB 

### ISSUE THREAD

**Issue by talley** [cockroachdb/docs#1679]
Re: [Install Client Drivers](https://cockroachlabs.com/docs//v1.0/install-client-drivers.html)

## Issue Description
Where is C# driver?

**Comment by sploiselle** [comment]
@talley We haven't tested or vetted Npgsql. If you want to test it out for us, we'd be excited to have the contribution!

**Comment by jseldess** [comment]
@talley, a quick update: We're close to publishing C# code samples and tutorials. Should be within the next week or two. You can take an earlier look at the code samples here: #1991

**Comment by jseldess** [comment]
cc: @BramGruneir, @awoods187

**Comment by jseldess** [comment]
@talley, we just added a tutorial on [building a C# app with CockroachDB](https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html). Please take a look and let us know if you have any questions.
