### ISSUE TITLE
Converting an insecure cluster to a secure cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1681]
As explained in @dianasaur323's onboarding audit, the docs don't explain how to convert an insecure cluster into a secure cluster. Summary:

- You must shut down all nodes, create certs, and then restart all nodes. 
- You can't do this in a rolling fashion.

**Comment by bdarnell** [comment]
We should also reexamine the workflow that leads a user to want to do this. We should encourage security from the beginning (at least before introducing multiple nodes) instead of starting insecure and "securing" it later.
