### ISSUE TITLE
CockroachDB Core sections link to CCL distributable, not OSS

### ISSUE THREAD

**Issue by twrobel3** [cockroachdb/docs#1686]
I noticed on the docs site/project home page that following the "Getting Started" links for the non-enterprise Cockroach versions, users wind up on the "Install CockroachDB" page, which includes links to the CCL distribution.

In particular, starting from the [product options page](https://www.cockroachlabs.com/pricing/), or the [CockroachDB Core](https://www.cockroachlabs.com/product/cockroachdb-core/) product page, the getting started links go to the standard [installation page](https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html).

Downloading the binary from this page and running `cockroach version` shows that it is the CCL distribution, not the OSS:

```
Build Tag:    v1.0.3
Build Time:   2017/07/06 17:44:09
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  b692a7cc7acc57022d1441034b93b85d860b7e86
Build Type:   release
```

This is a very easy mistake to make if a user isn't looking for it, and could lead to quite a few licensing violations.

**Comment by dt** [comment]
Indeed @twrobel3, that's correct! 

We currently only distribute prebuilt binaries under the CCL  -- users or distros who require a pure Apache2 binary can build it from source using `make buildoss`. @spencerkimball [outlined our approach here](https://www.cockroachlabs.com/blog/how-were-building-a-business-to-last/) when we announced the introduction of enterprise features: 
> These features will not be on by default, will be clearly marked in documentation, code, and help messages, and will be enabled only by operator or developer choice. The binary which we distribute will contain these features, but as a result, cannot be distributed under a FLOSS license. However, a “pure” FLOSS distribution will also be available, with enterprise features absent, for those that require it.

Maybe we need to clarify CCL / enterprise usage a bit on the download page and elsewhere.

**Comment by jseldess** [comment]
Added callout about `make buildoss`. And the download workflow has changed for the better in the meantime more generally.
