### ISSUE TITLE
sql: UPSERT and INSERT ON CONFLICT with RETURNING

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1693]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recfh5aGbH5i9kwn9
PR: https://github.com/cockroachdb/cockroach/pull/17149

**Comment by jseldess** [comment]
@couchand, this is ready to be documented for 1.1, right?

**Comment by couchand** [comment]
Yes, I believe so.  What do you need from me for it?

**Comment by jseldess** [comment]
@couchand, I think the PR is a good starting point for us. We'll come back with questions once we get started.
