### ISSUE TITLE
build: give suggestions for installing build from source deps

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1694]
Like `brew install`, `apt-get install`, and `yum install`.

**Comment by jseldess** [comment]
@benesch, can you provide more details here and an update? Is this something that needs to get done for 1.1?

**Comment by benesch** [comment]
Heh, I think you already provided the details on #1670, which I forgot to link here.

> Thanks, @benesch. LGTM. Wonder, though, whether we should provide tips for quickly installing some of the dependencies? Could be a line or two following the requirements, e.g.:
>
> If you're on macOS and use Homebrew, you can install most of these dependencies by running:
> ```
> $ brew install cmake go autoconf automake libtool
> ```
> If you're on Linux, you can install most of these dependencies with:
>
> ```
> $ apt-get install cmake go autoconf automake libtool
> ```

Not urgent!
