### ISSUE TITLE
Put release notes in a separate directory

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#1695]
https://www.cockroachlabs.com/docs/v1.0 is the release notes for version 1.0, while https://www.cockroachlabs.com/docs/v1.0/ with a trailing slash is version 1.0 of the docs home page. It's unconventional for urls that differ only in a trailing slash to lead to different pages. We should probably tweak the naming conventions for either release notes or version directories so they don't collide (at least for future releases)

**Comment by jseldess** [comment]
Good catch, @bdarnell. Would it be acceptable to us the `v1.X` naming convention for release notes, while using just `1.x` for version directories?

This is a side-effect of the release notes being the only non-versioned pages, btw.

cc: @benesch

**Comment by bdarnell** [comment]
Removing the `v` from the version directory names is fine with me. Or we could put the release notes in a subdirectory (`cockroachlabs.com/release-notes/v1.0`)

**Comment by benesch** [comment]
Also not opposed to remove the `v` from the directories, but creating a separate release-notes directory seems less confusing.

**Comment by sploiselle** [comment]
+1 on separate release notes directory

**Comment by jseldess** [comment]
Separate release notes directory sounds best to me, too.
