### ISSUE TITLE
Show the sidebar when javascript is disabled

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1696]
Currently if the browser has javascript disabled, the docs side is mostly fine. Except that the sidebar is completely absent.

This is because the site starts empty and then only the sidebar is populated in javascript.

This is incorrect; instead the basic pages should already include the side bar, and a javascript program should merely overwrite with the dynamic replacement.

**Comment by jseldess** [comment]
@mjibson, once we're on Hugo, I vaguely remember we might have a built-in, non-JS sidebar option, is that right?

**Comment by mjibson** [comment]
Yes, we think hugo will support our current stuff natively.

**Comment by luciaaaaaaa** [comment]
Could you provide a screenshot of the issue? which sidebar is missing

**Comment by knz** [comment]
here's the doc site with missing sidebar, notice how the sidebar on the left is missing.

![image](https://user-images.githubusercontent.com/642886/82432397-4ca3e900-9a90-11ea-8fc0-a1abe28358c5.png)

**Comment by knz** [comment]
As I explained at the top, the issue here is technical:

> This is incorrect; instead the basic pages should already include the side bar, and a javascript program should merely overwrite with the dynamic replacement.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
