### ISSUE TITLE
Add a C example

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1698]
Re: [Build an App with CockroachDB](https://cockroachlabs.com/docs//v1.0/build-an-app-with-cockroachdb.html)

## Issue Description

C is common language without an example.

## Suggested Resolution 

Add a C example.  Will follow-up with the transaction example.

[basic-sample.c.zip](https://github.com/cockroachdb/docs/files/1139739/basic-sample.c.zip)

**Comment by jseldess** [comment]
Thank you, @robert-s-lee! Will get to this soon. We also have an issue open for C#, in case you want to take that, too.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
