### ISSUE TITLE
Build a Ruby App with CockroachDB Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1704]
Re: [Build a Ruby App with CockroachDB](https://cockroachlabs.com/docs//v1.0/build-a-ruby-app-with-cockroachdb-activerecord.html)

## Issue Description

$ ruby activerecord-basic-sample.rb
/var/lib/gems/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:525:in `inherited': Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: (StandardError)

  class Schema < ActiveRecord::Migration[4.2]
        from activerecord-basic-sample.rb:26:in `<main>'

https://github.com/cockroachdb/examples-orms/tree/master/ruby/activerecord does work on this system.

Below is the system config

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

apt-get update
apt-get install git
apt-get install build-essential
apt-get install golang
apt-get install ruby-dev
apt-get install libpq-dev
gem install bundler
gem install pg

go get github.com/pkg/errors
go get github.com/cockroachdb/cockroach-go/testserver

**Comment by jseldess** [comment]
@jordanlewis, do you think this error was due to not having version 0.2.x of our `activerecord-cockroachdb-adapter`, which we call out in our docs as required for ActiveRecord 5+?

**Comment by jordanlewis** [comment]
I think this issue probably pre-dates that fork? I'm not sure. It sounds like there's something wrong with the test ruby environment, but I don't have enough information to know.

**Comment by jseldess** [comment]
@robert-s-lee, without more details, it doesn't look possible to improve the docs here. I'll close for now, but if you can dig up more details, I'm happy to reopen.
