### ISSUE TITLE
Add "No results found" message when search does not return matching results

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#1709]
After performing a search if no matching results are found, the search function returns a blank page. 
Example: https://www.cockroachlabs.com/docs/search.html?q=profile

Need to add an error message saying "No results found".

**Comment by jseldess** [comment]
Thanks for opening this, @Amruta-Ranade!

**Comment by jseldess** [comment]
This is not longer an issue, based on my testing.

<img width="1177" alt="screen shot 2018-04-09 at 1 36 33 am" src="https://user-images.githubusercontent.com/15893490/38480949-7421f0c2-3b96-11e8-8701-4b4463c53d5c.png">
