### ISSUE TITLE
Troubleshooting: server out of memory

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1712]
From @bdarnell on Gitter:

> if you're seeing crashes where the logs in `cockroach-data/logs` just end abruptly, it's probably running out of memory. you can verify this by looking in the output of `dmesg`(grep for `cockroach`)

**Comment by jseldess** [comment]
@Amruta-Ranade, this might tie into your troubleshooting docs project. If so, please feel free to assign to yourself and apply the 2.2 milestone.

**Comment by Amruta-Ranade** [comment]
Yes! Thanks!

**Comment by Amruta-Ranade** [comment]
Addressed in #4223
