### ISSUE TITLE
sql: introduce a new ORDER BY syntax to reuse index orderings

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1713]
PR: https://github.com/cockroachdb/cockroach/pull/17023

**Comment by Amruta-Ranade** [comment]
Possible updates: SELECT, SQL FAQ

**Comment by jseldess** [comment]
Updated by @knz: https://www.cockroachlabs.com/docs/stable/query-order.html#sorting-in-primary-key-order
