### ISSUE TITLE
Investigate options to output plain text

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#1717]
It would be good to be able to read the documentation inline in the SQL shell.

cc @benesch

**Comment by jseldess** [comment]
@knz, have you seen this down for other products? Given how large and rich our docs are, I'm not sure this is possible without extreme effort, and I'm not sure it would meet much a user need.

**Comment by jseldess** [comment]
Closing this for now. If it becomes a common request, we can revisit.
