### ISSUE TITLE
Consider moving docs to cockroachdb/cockroach

### ISSUE THREAD

**Issue by benesch** [cockroachdb/docs#1719]
Apologies for the second sweeping suggestion in an hour. This one is really just floating a thought: are we discouraging engineers from participating in documentation by using a separate repository? I know I've made changes that would require a few sentences of changes to the docs, but I don't bother with the docs update because it requires switching to a separate repository, firing up Jekyll, making the change, and submitting a separate PR. If I could do it all in one PR in cockroachdb/cockroach, I think I'd be _way_ more likely to update the docs alongside my change.

Just food for thought for now! Problems abound:

  * cockroachdb/cockroach has long CI times. We could work around this with "VCS triggers" to run only docs tests when only files in `docs/` have changed. 

  * Docs PRs and eng PRs would be intermingled; we'd have to come up with some labeling scheme to keep everyone sane.

  * Commit message hygiene. We have very strict standards for commit messages over at cockroachdb/cockroach; we'd likely impose this burden on the docs team, too.

**Comment by jseldess** [comment]
There's very little change we'll merge our docs into the main cockroach repo at this point, especially since docs include CC and a fairly complex CI/CD. Closing for now. We can re-open if this becomes a relevant possibility again.
