### ISSUE TITLE
Clock synchronization on Windows

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1726]
From Gitter:

I've been running a 2 Linux node, 1MacOS cluster for a long time without issue (secure mode). I'm trying to add a Windows node and have created the CA and certs accordingly. When trying to join the cluster on Windows it always fails with the error fewer than half the known nodes are within the maximum offset of 500ms (0 of 1)
I should be able to add a Windows host into the mix right?
All machines are time synced to time.google.com
I can start a single node on Windows without the --join command and it works fine

I'm new to running this stuff on windows but wow. Despite being time synced to time.google.com it looks like my offsets are about 1.8 seconds. All machines connected to the same switch in a small network so this shouldn't be a problem

**with a bit of Googling I found w32tm /resync that resync the time (this wasn't working through the GUI). This got the offset down to about 350ms. So now the Windows node launches with no issues!**

**Comment by moderation** [comment]
Gitter commenter here. The `w32tm /resync` originally worked but it wasn't long until the clock drifted beyond 450ms and Cockroach stopped. My latest attempt which has held for 12+ hours is `w32tm /config /syncfromflags:manual /manualpeerlist:"time1.google.com time2.google.com time3.google.com time4.google.com" /reliable:yes /update`. It is not clear if this config will persist beyond a reboot. All testing done on Windows 10 Pro.

**Comment by jseldess** [comment]
Thanks very much for the update, @moderation.

@BramGruneir, @tamird, since you worked on our Windows build, any chance one of you can help find the right approach here?

**Comment by tamird** [comment]
This is beyond my knowledge of Windows.

**Comment by jseldess** [comment]
@mberhault, @bdarnell, our production deployment docs currently don't cover Windows. Have we tested prod clusters on Windows machines. If not, are we likely to do so?

**Comment by mberhault** [comment]
Uh, no. We haven't and we don't intend to. We don't even build CCL binaries for windows.

**Comment by jseldess** [comment]
OK, then closing this issue for the time being.
