### ISSUE TITLE
Document AmbiguousResultErrors

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1727]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recmDbcXFLWEMLsj9

We need better documentation on the meaning of `AmbiguousResultErrors` and how to handle them. 

From @bdarnell: 

> Ambiguous errors are inherent in distributed systems, and a client application with a single-node databases is still a distributed system and may experience ambiguous failure (if the database dies while you're committing your transaction, you can't tell what happens). Since these errors are unavoidable, we mistakenly thought we could introduce them without causing new headaches, and without needing to document them in detail. However, we generate these AmbiguousResultErrors far more often than other systems, so we do need to do a better job of documenting this (unless we can reduce their frequency to some minimal level).

**Comment by jseldess** [comment]
@bdarnell, @petermattis, @jordanlewis, @andreimatei, is this important for 1.1? If so, any of you willing to drive the initial effort?

**Comment by bdarnell** [comment]
It doesn't need to be tied to the release cycle (and in fact this problem is less severe in 1.1 than in 1.0). But it's important enough that we should probably write something up in the 1.1 time frame. I can help with this.

**Comment by jseldess** [comment]
@bdarnell, Docs doesn't have the bandwidth to do anything here. Do you feel it's important for 2.0 and, if so, do you have the bandwidth to write something up?
