### ISSUE TITLE
Add OpenGraph data to template

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1730]
Exalate commented:

Using [the Open Graph protocol](http://ogp.me/)'s docs as reference, we should add OpenGraph meta data to every page on the docs site:

### Data

~~~
og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
og:image - An image URL which should represent your object within the graph.
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".
~~~

### Example

~~~
<head>
<title>The Rock (1996)</title>
<meta property="og:title" content="The Rock" />
<meta property="og:type" content="video.movie" />
<meta property="og:url" content="http://www.imdb.com/title/tt0117500/" />
<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />
...
</head>
~~~

Jira Issue: DOC-2180

**Comment by jseldess** [comment]
@sploiselle, can you provide some background as to why we want to add type of metadata?

**Comment by sploiselle** [comment]
Derp––yeah!

> The Open Graph protocol enables any web page to become a rich object in a social graph. For instance, this is used on Facebook to allow any web page to have the same functionality as any other object on Facebook.

So, implementing this data makes sure that when people share our content on sites that use Open Graph (Facebook, Twitter, LinkedIn, Reddit, etc.), we have control over how the link gets turned into a "card." e.g. controls the image that displays, title, and description.

**Comment by jseldess** [comment]
Thanks, @sploiselle!

**Comment by jseldess** [comment]
@j-low, @jess-edwards, just rediscovered this issue. Thoughts on this?

**Comment by jess-edwards** [comment]
@jseldess I'm for it! We added this to the main site with the 1.1 launch. 

cc @j-low

**Comment by jseldess** [comment]
@jess-edwards, is this something that we still want to happen? Or is it no longer important?

**Comment by jess-edwards** [comment]
@jseldess Yes, this would be a really good addition. Open-graph is the protocol (?) that enables links to look pretty when you paste them into social media sites (Twitter, LinkedIn).

**Comment by jseldess** [comment]
@anagio, do you know how to make this happen? If you can give me guidance, I can't try to get it done, since I know you're busy!

**Comment by jseldess** [comment]
Closing this for now. @anagio, @jess-edwards, let us know if we still want this on the backlog.
