### ISSUE TITLE
Active Record Support for Rails 4

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1731]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwnV9kAGj2ZkcydA/recTWlbFNbwdF2YyZ
Issue: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/11

Summary: We already support Rails 5. We're adding support for Rails 4. At the least, we should call out support of these 2 versions in the Active Record tutorial. But we should also meet with @jordanlewis to discuss how the tutorial might be improved/expanded more generally.

**Comment by jseldess** [comment]
@jordanlewis, once dev is finished here, please add the `ready` label. In the meantime, I'll schedule a meeting to discuss how we might improve the Active Record tutorial more broadly.

**Comment by irfansharif** [comment]
+cc https://github.com/cockroachdb/activerecord-cockroachdb-adapter/tree/0.1.x.

**Comment by jseldess** [comment]
@jordanlewis, any chance you can help out and open a docs PR to update https://github.com/cockroachdb/docs/blob/master/v1.1/build-a-ruby-app-with-cockroachdb-activerecord.md?

**Comment by jseldess** [comment]
Closed by https://github.com/cockroachdb/docs/pull/1949
