### ISSUE TITLE
ui: move the network latency report to the ui

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1733]
PR: https://github.com/cockroachdb/cockroach/pull/16728

**Comment by jseldess** [comment]
@Amruta-Ranade, another troubleshooting/debugging page added to the UI, though I'm not sure we need to document it for 1.1.

**Comment by Amruta-Ranade** [comment]
As per discussion with Diana, not to be documented for 1.1

**Comment by jseldess** [comment]
Thanks, @Amruta-Ranade. If there are any other admin UI issues that you know are not to be documented for 1.1, please change their milestone to 1.2.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2373
