### ISSUE TITLE
distsql, ui: query count metrics

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1734]
PR: https://github.com/cockroachdb/cockroach/pull/17050

**Comment by jseldess** [comment]
New distributed SQL-focused metrics in the UI, @Amruta-Ranade. Not sure if you'll need to document them for 1.1. Depends on the user stories/questions you end up deciding to answer.

**Comment by Amruta-Ranade** [comment]
As per discussion with Diana, not to be documented for 1.1

**Comment by jseldess** [comment]
This should be covered in Amruta's general Admin UI reference doc.

**Comment by Amruta-Ranade** [comment]
As per discussion with @couchand, not to be documented for 1.1

**Comment by Amruta-Ranade** [comment]
We are not documenting distsql for 2.0. Moving to 2.1

**Comment by Amruta-Ranade** [comment]
We are not documenting distsql yet. Punting this issue until we do.

**Comment by jseldess** [comment]
@Amruta-Ranade, will there be some engineering changes tied to our decision to document this? If so, you can close this issue and count on a future issue getting created by our release script.

**Comment by Amruta-Ranade** [comment]
I don't know yet - it depends on the scope of the "document DistSQL plans" project. And the scope of that project hasn't been defined yet. I am okay with closing this issue for now and revisiting it as and when we get to the DistSQL plans project.
