### ISSUE TITLE
Change local deployments to start with single node before connecting app

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1749]
We've received feedback that getting started with a multi-node cluster is difficult or confusing:

- On local deployments, the different ports and stores are unintuitive for users who don't grok that it's simulating a node run on 3 different machines
- On cloud/remote deployments, networking hostnames (and to a lesser extent firewalls) cause a lot of consternation

Changing the getting started and deployment docs to focus on getting everything started an a single node could alleviate a lot of this confusion. 

Additional nodes could then be added in "Scaling" sections, which gives users a clearer mental model of what they're doing––rather than getting 3 nodes set up before doing anything, you get a clearer sense that you're adding functionality to your cluster by completing additional steps.

Separating "Scaling" out into its own section also makes troubleshooting more modular. This gives us a chance to create content to provide troubleshooting if you cannot connect your application to your cluster separately from issues with inter-node communication.

**Comment by jseldess** [comment]
Updating the focus to be on local deployment, since with 1.1's `init` command, it's important for prod deployment tutorials to show multi-node startup and initialization. 

But this is still a valid discussion for our getting started docs, which focus on local clusters.
