### ISSUE TITLE
Include term Postgres on appropriate pages

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1751]
Pages that reference `PG wire` or similar terms should also include the term "Postgres" or "PostgreSQL". This will help with on-site search, as well as SEO.

**Comment by bdarnell** [comment]
`pgwire` is a term I just made up (I've heard it called "the postgres wire protocol", so I abbreviated it), but I don't think anyone else calls it this. We should generally avoid this term in our public docs unless we're specifically referring to our code that implements the protocol. 

The closest thing to an official name for the protocol appears to be the postgres ["Frontend/Backend Protocol"](https://www.postgresql.org/docs/current/static/protocol.html)

**Comment by jseldess** [comment]
Can't find any instances of pgwire or pg wire, and anywhere we use "wire protocol" we also use "Postgres" or "PostgreSQL", so closing this.
