### ISSUE TITLE
Java expects DER and not PEM files

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1757]
From @bdarnell:

> java is annoying because it wants certificates in DER format when everything else uses PEM. you can convert the keys with this command: https://github.com/cockroachdb/cockroach/blob/bd020432a1b8e8a948200900ac21a109593ea958/pkg/acceptance/java_test.go#L189

This information's critical for our deployment and training docs w/r/t using Java driver and ORM.

**Comment by rmloveland** [comment]
Related: #631

**Comment by jseldess** [comment]
Thanks, @sploiselle!

**Comment by tim-o** [comment]
+1 on this issue - just popped up again on Gitter.

**Comment by rmloveland** [comment]
Thanks for the bump Tim - I have a WIP code sample and instructions at
https://github.com/rmloveland/cockroach-hibernate-basic-sample-secure that
I am validating with Bram tomorrow.  Once that is known-good I will be
putting it in a PR along with a bunch of other "secure" code samples for
https://github.com/cockroachdb/docs/issues/631 ASAP.

**Comment by rmloveland** [comment]
Closing as I believe this was addressed by the doc updates in https://github.com/cockroachdb/docs/pull/3271 that show which `openssl` magic strings to type to get the certs Java wants.
