### ISSUE TITLE
Undocumented clauses for CREATE DATABASE

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1765]
As of v1.1 [`CREATE DATABASE`](https://www.cockroachlabs.com/docs/v1.1/create-table.html) supports undocumented clauses

**Comment by jseldess** [comment]
New clauses exclusively for Postgres compatibility: `TEMPLATE`, `ENCODING`, `LC_COLLATE`, `LC_CTYPE`.
 
Supported values: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/create.go#L51

Draft docs:

## Compatibility

For compatibility with PostgreSQL, the `CREATE DATABASE` statement accepts any combination of the following optional clauses. Values for these clauses must be enclosed in single quotes and are case-insensitive.

Clause | Details
-------|------------
`ENCODING` | `UTF-8` is the only supported encoding. The aliases `UTF8` and `UNICODE` are also accepted.
`TEMPLATE` | `template0` is the only accepted template.
`LC_COLLATE` | `C` and `C.UTF-8` are the only accepted collations.
`LC_CTYPE` | `C` and `C.UTF-8` are the only accepted character classifications.

Example:

~~~ sql
> CREATE DATABASE test
TEMPLATE = 'template0'
ENCODING = 'UTF-8'
LC_COLLATE = 'C'
LC_TYPE = 'C';
~~~

**Comment by jseldess** [comment]
@andreimatei, not sure who to ask here, so I'll ask you: If you try to use multiple of these clauses in `create database` and do so not in the order show in the example above, we throw an error: 

```
root@:26257/> create database test template = 'template0' encoding = 'utf8';
CREATE DATABASE

Time: 4.2748ms

root@:26257/> drop database test;
DROP DATABASE

Time: 4.820641ms

root@:26257/> create database test encoding = 'utf8' template = 'template0';
invalid syntax: statement ignored: syntax error at or near "template"
DETAIL: source SQL:
create database test encoding = 'utf8' template = 'template0';
                                       ^
```

Is the order significant? Is that expected?

**Comment by andreimatei** [comment]
No clue. I don't even know what "template" is. Passing along to @vivekmenezes to find someone who does :)

**Comment by awoods187** [comment]
Closing this as out of date
