### ISSUE TITLE
Deploy CockroachDB on Digital Ocean Doc Update 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#1767]
Re: [Deploy CockroachDB on Digital Ocean](https://cockroachlabs.com/docs//v1.0/deploy-cockroachdb-on-digital-ocean.html)

## Issue Description
When we say --advertise-host=<node1 internal IP address> I don't think this actually works unless all the nodes are in the same datacenter. Is there an issue with advertising the external IP address assuming the cluster is secure?

**Comment by sploiselle** [comment]
@nstewart No problem with advertising the external IP, but it's a suboptimization––performance-wise––when all of your nodes are in the same datacenter. When this doc was written, stability was still a big issue, so we didn't want to expressly advocate for multi-DC deployments, ergo the doc we have.

@mberhault Is there a way to get a best-of-both worlds with `--host`/`--advertise-host`? Use the internal address if you're in the same DC, and use the public address if not?

**Comment by jseldess** [comment]
Very old issue. Closing for now.
