### ISSUE TITLE
Networking guidance/scenarios

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1770]
Customers continually experience problems deploying CockroachDB because of issues with networking. While an operator's network lies beyond the purview of CRL, it's crucial the documentation provide best practices and guidance for various scenarios.

Need to cover:

- Basics/best practices 
    - Hostnames/firewalls (as started in https://github.com/cockroachdb/docs/pull/1729)
    - `--host` vs. `--advertise-host` usage (#2883, #1174)
- Scenarios
    - Floating IPs (https://forum.cockroachlabs.com/t/floating-ip-addresses/1518)
    - Changing IPs based on maintenance (happens when racks get moved around, etc.)
    - Private IPs not routable across nodes/datacenters (#2538, https://forum.cockroachlabs.com/t/bind-cannot-assign-requested-address/1152/9)

**Comment by jseldess** [comment]
Suggestion from @dianasaur323: Might want to use networking debug page.
