### ISSUE TITLE
Connection Strings

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1771]
Docs need a page that traps the query "connection strings" with info about how to format the Postgres Wire Protocol connection string to work with CockroachDB.

Should include:
- Format for using certificates
- Mention of using cloud load balancers to maximize survivability

**Comment by knz** [comment]
I think this was addressed in #2853?

**Comment by sploiselle** [comment]
@knz This is exactly what I was looking for. Thank you!
