### ISSUE TITLE
OS boot/process management: systemd

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1772]
Given the importance of process management for CockroachDB deployments, we need to:

- [ ] 1. Create and dogfood a sample `systemd` configuration suitable for production.
- [ ] 2. Expose the config in our docs.

For 2, we have two options:
- (Minimum) Keep manual deployment tutorials as-is but emphasize the importance of using a process manager and reference the sample config. 
- (Preferred) Adjust all of our non-orchestration tutorials to let the user toggle between instructions using `systemd` (new) vs. manual (current). We could do this for other tutorials as well, e.g., rolling upgrades.

Resources:
- [`systemd` wiki](https://www.freedesktop.org/wiki/Software/systemd/)
- Sample `systemd` configuration
    - [From forum](https://forum.cockroachlabs.com/t/ubuntu-service-script-to-start-a-cockroachdb-node-on-boot/1419)
    - [Internal](https://github.com/cockroachlabs/production/pull/483)

**Comment by jseldess** [comment]
See https://forum.cockroachlabs.com/t/ubuntu-service-script-to-start-a-cockroachdb-node-on-boot/1419 for a sample `systemd` service file.

@mberhault, @bdarnell, @dianasaur323, I'd like to make this a 2.1 docs project. No need to answer now, but we'll need to:
- Identify the most popular systems to feature.
- Write scripts for each.

Do we already have some examples internally?

**Comment by jseldess** [comment]
In a Slack discussion with @mberhault and @bdarnell, we decided to focus just on `systemd` for now. In the future, we could cover `supervisord` as well.

**Comment by jseldess** [comment]
@robert-s-lee mentioned that `autosys` is commonly used in almost all large enterprises.

**Comment by Amruta-Ranade** [comment]
Motivation: In production, use process manager.

Almost all steps need to be done as root (hence create VM on Digital Ocean, so you will be root by default). Else, use sudo.

Steps for systemd (for insecure mode): 
1. Download cockroach binaries. Install binaries in the path configured in the systemd file.
2. Create a user named cockroach. (For Linux, there are two commands to create a user. We want the one that doesn't do much (that is doesn't create an actual person user)).
3. Path for the data dir: /var/lib/cockroach (create this dir)
4. Change the ownership of path to cockroach using `chown cockroach /var/lib/cockroach`
5. Grab the example file and put it in /etc/systemd/cockroachdb.service (https://forum.cockroachlabs.com/t/ubuntu-service-script-to-start-a-cockroachdb-node-on-boot/1419)
6. systemctl start cockroach <Marc to double-check> 

Steps for systemd (for secure mode): 
1. Download cockroach binaries. Install binaries in the path configured in the systemd file.
2. Create a user named cockroach.
3. Path for the data dir: /var/lib/cockroach (create this dir)
4. Change the ownership of path to cockroach using `chown cockroach /var/lib/cockroach`
5. Create certs directory and certificates
6. Grab the example file and put it in /etc/systemd/cockroachdb.service (https://forum.cockroachlabs.com/t/ubuntu-service-script-to-start-a-cockroachdb-node-on-boot/1419)
7. systemctl start cockroach <Marc to double-check> 

In the example, change WorkingDirectory=/var/lib/cockroach
User=cockroach

This will start cockroach, restart it if cockroach dies. For upgrade, we just need to replace binaries and this will start cockroach with the new version.

<Note to self>: Create a small VM on Digital Ocean and follow these instructions to test it out.

**Comment by Amruta-Ranade** [comment]
**Note to self:**
Status as of 05/16: Set up secure CRDB cluster on DO using systemd.
To Do: Test cluster (Need Marc's help with this)
