### ISSUE TITLE
Feedback: Logging Overview - Document the KV_DISTRIBUTION channel

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/docs#17752]
Kevin Ngo (kevin-v-ngo) commented:

Internal [slack thread](https://cockroachlabs.slack.com/archives/C02AMU8U76C/p1692904001298259?thread_ts=1692898029.063029&cid=C02AMU8U76C)

The KV_DISTRIBUTION channel is listed in the docs under [logging](https://www.cockroachlabs.com/docs/stable/logging), but not under [logging-overview#logging-channels](https://www.cockroachlabs.com/docs/stable/logging-overview#logging-channels).

Jira Issue: DOC-8678

**Comment by greg-crl** [comment]
also, the KV_DISTRIBUTION channel shows up in documentation as far back as v21.1, although it wasn't introduced till much later.  it would be useful if KV_DISTRIBUTION were noted in the Release Notes of the version in which it was introduced.

similarly, the TELEMETRY channel was added to the docs for v21.1, but is noted in the 21.2 docs as as "new in v21.2".
