### ISSUE TITLE
Improved transaction retry documentation

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1775]
We should revise and expand our documentation to better explain:
- What transaction retries are
- Why they happen in CockroachDB
- Exactly how to handle them properly

In the process, we should also document a comprehensive list of errors for applications to listen on, with an explanation for what causes the error and how to best deal with it.

**Comment by jseldess** [comment]
@awoods187, @rmloveland, @knz, let's repurpose this old ticket for the transaction retry docs project that you all have started discussing. Please feel free to edit or extend my overview above. 

Also note that there are several other docs issues that may or may not tie into this particular work, including:
- https://github.com/cockroachdb/docs/issues/4297
- https://github.com/cockroachdb/docs/issues/4144
- https://github.com/cockroachdb/docs/issues/3266
- https://github.com/cockroachdb/docs/issues/1587
- https://github.com/cockroachdb/docs/issues/4306
- https://github.com/cockroachdb/docs/issues/4300
- https://github.com/cockroachdb/docs/issues/2999

**Comment by rmloveland** [comment]
Per internal discussion regarding "transaction retry ratios", a.k.a. how many transaction retries should one expect to experience as a percentage of total queries:

- it's not a question of whether a workload is "small" or "large", it depends on how much contention there is
- in other words, it varies per workload (TPC-C is high contention and thus there are more retries; some workloads can experience 0 retries if there is no contention)
- it would be good to discuss in the documentation what ratios we expect given various workloads

**Comment by jseldess** [comment]
Recent work by @rmloveland is a big step forward here, but we have plenty left to do around document all possible errors, explaining when to use various approaches (select for update, etc.), and presenting as more intuitive, prescriptive guidance.
