### ISSUE TITLE
Load balancer overview/best practices

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1788]
CockroachDB requires a load balancer in front of it to maximize survivability. Because we depend on the technology so heavily, we should also include an overview of things to consider, as well as best practices when using one.

**Comment by i5heu** [comment]
Client side load balancing through proxy mode
Related: https://github.com/cockroachdb/cockroach/issues/24001

**Comment by jseldess** [comment]
See also multi-threading in HAProxy to scale with client load: https://github.com/cockroachlabs/support/issues/263#event-2395588824

**Comment by jseldess** [comment]
https://www.cockroachlabs.com/docs/v21.2/recommended-production-settings.html#load-balancing
