### ISSUE TITLE
Service Discovery docs

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1793]
For non-orchestrated deployments, we should include docs on using service discovery tools to automatically add new nodes to your load balancer's rotation (as well as whatever other benefits service discovery might have for CockroachDB).

Examples of service discovery tools include `etcd` and `Zookeeper`.

**Comment by milipili** [comment]
Actually just plain DNS resolution can be enough in many cases and will work anywhere

**Comment by jseldess** [comment]
Closing this for now, based on [this feedback](https://github.com/cockroachdb/docs/pull/1729#issuecomment-316194659) from @bdarnell.
