### ISSUE TITLE
Load balancing the admin UI on Digital Ocean

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#1796]
Re: [Deploy CockroachDB on Digital Ocean](https://cockroachlabs.com/docs//v1.0/deploy-cockroachdb-on-digital-ocean.html)

## Issue Description

In the docs for digital ocean we specify port forwarding to ensure SQL commands make it to our droplets. We also need to route TCP traffic on port 8080 for the admin UI to work through the load balancer.

## Suggested Resolution 

Note the additional routing so the load balancer works as expected.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
