### ISSUE TITLE
Add documentation for external storage

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/docs#1797]
We recently introduced the use of temporary storage to store intermediate query results. This is useful when you are executing a memory-intensive task and there is not enough memory to complete this task (error returned was `pq: memory budget exceeded...`). The use of temporary storage has been implemented for `ORDER BY`s without `LIMIT`s (see https://github.com/cockroachdb/cockroach/pull/16717) and joins (see https://github.com/cockroachdb/cockroach/pull/17192).

This enhancement is currently turned `off` by default although I think the plan is to turn it `on` by default for `1.1`. In any case, `sql.defaults.distsql.tempstorage` is a boolean setting that turns this enhancement on for the whole cluster. There are also fine-grained settings for sorts and joins, in the case that some bug crops up in one but the operator would still like to keep the other one on. These are `sql.defaults.distsql.tempstorage.sorts` and `sql.defaults.distsql.tempstorage.joins`.

There is also a per-node environment variable `COCKROACH_WORK_MEM` that defaults to `64MB`. It limits the "working memory" of a processor. For example, if a sorter processor is sorting a bunch of rows, the sorter processor can only consume up to `64MB` of rows before hitting this limit and falling back to disk. It is important to note that this limit **only applies when `sql.defaults.distsql.tempstorage = true`**.

**Comment by jseldess** [comment]
Temp storage on by default: https://github.com/cockroachdb/cockroach/pull/17665

**Comment by sploiselle** [comment]
@asubiotto Can you give me an overview of how this interacts with the `IMPORT` statement's use of "temp" storage? I have a PR open to document that feature #1914

**Comment by asubiotto** [comment]
@sploiselle I believe that the `IMPORT` statement would use the same directory as this, @mjibson can confirm. Both distsql and the `IMPORT` statement use the same RocksDB instance.

**Comment by jseldess** [comment]
There's also a cli flag for overriding the temp store directory: https://github.com/cockroachdb/cockroach/issues/17859

@sploiselle, are you able to cover this feature as a whole, or just in relation to import?

**Comment by sploiselle** [comment]
Here's a rough diagram from a conversation with @asubiotto 

![img_0773](https://user-images.githubusercontent.com/19260003/30878375-85a2f19e-a2ca-11e7-8dee-e34c4ae4a763.JPG)

**Comment by jseldess** [comment]
We already have docs for the `--max-disk-temp-storage` flag on `cockroach start`. 

We need to add details about the cluster settings for turning off temp on-disk storage for joins and sorts, and for changing the max memory size before spilling to disk. 

For 2.0, we need to document the `--temp-dir` flag on `cockroach start`, which users can use to specify the location for temp storage (defaults to the first store's data directory).

**Comment by jseldess** [comment]
@knz, I'm trying to understand the relationship between `--max-disk-temp-storage`, `--max-sql-memory`, and the `sql.distsql.temp_storage.workmem` cluster setting. 

My understanding is that `--max-disk-temp-storage` defines "the maximum on-disk storage capacity available to store temporary data for SQL queries that exceed the memory budget." But is that "memory budget" referring to `--max-sql-memory`, `sql.distsql.temp_storage.workmem`, some combination, or something else entirely?

**Comment by knz** [comment]
If I understand well the --max-sql-memory is a constraint on RAM usage, whereas --max-disk-temp-storage and sql.distsql.temp_storage.workmem are a constraint on disk usage. @asubiotto is this understanding correct?

**Comment by jseldess** [comment]
@knz, that's my understanding of `--max-disk-temp-storage`, but the description for `sql.distsql.temp_storage.workmem` seems to refer to memory and not disk usage...

```
| sql.distsql.temp_storage.workmem                  | 64 MiB        | z    | maximum amount of memory in bytes a processor can use before falling back to temp storage                                                       |
```

**Comment by knz** [comment]
Oh I see. Yes I vaguely understand what's going on here, but I wouldn't be able to explain.

**Comment by asubiotto** [comment]
`--max-sql-memory` is a constraint on RAM usage for the node as a whole (i.e. all processors), `sql.distsql.temp_storage.workmem` is a limit per processor *that can use external storage* (i.e. not applicable to all processors). This means that a processor that can fall back to disk will use at most `sql.distsql.temp_storage.workmem`. However, processors may hit `--max-sql-memory` before this if there are other memory-intensive processors running and will fall back to disk.

`--max-disk-temp-storage` is the only flag that relates to temp storage disk budget. So once a processor falls back to disk, they will use at most this budget before failing a query (to avoid disk blow-ups).

**Comment by jseldess** [comment]
Excellent. Thank you, @asubiotto. Can you give me a few examples of processors limited by `sql.distsql.temp_storage.workmem`?

**Comment by asubiotto** [comment]
The [`HashJoiner`](https://github.com/cockroachdb/cockroach/blob/6bbd2444787ce82842433e4c15b5fe55ebd4f8a4/pkg/sql/distsqlrun/hashjoiner.go#L148) and the [`Sorter`](https://github.com/cockroachdb/cockroach/blob/6bbd2444787ce82842433e4c15b5fe55ebd4f8a4/pkg/sql/distsqlrun/sorterstrategy.go#L60) (however, only for sorting without a limit for now)

**Comment by jseldess** [comment]
This goes back to 1.1, but moving to the 2.1 milestone since we'll work on it in that timeframe.

**Comment by asubiotto** [comment]
Note that external storage has now been added to all sort strategies: https://github.com/cockroachdb/cockroach/pull/27083

**Comment by jseldess** [comment]
@rmloveland, @awoods187, when you look at the full docs backlog for sql, this is another one that probably warrants prioritization.

**Comment by asubiotto** [comment]
I'm wondering what the status of this issue is. Can it be closed?

**Comment by rmloveland** [comment]
> I'm wondering what the status of this issue is.

@asubiotto I haven't looked at this in a very long time.  Based on a quick look at the docs, we have:

- Docs for the [`--max-disk-temp-storage`](https://www.cockroachlabs.com/docs/stable/start-a-node.html) flag on the "Start a node" page

- Rudimentary cluster settings docs for [`sql.distsql.temp_storage.{joins, sorts,workmem}`](https://www.cockroachlabs.com/docs/stable/cluster-settings.html)

> Can it be closed?

I don't claim to understand all of the discussion on this issue, but It looks like yes?  Do you think the docs we already have (linked above) cover this issue?

**Comment by asubiotto** [comment]
Thanks for checking! It seems like it can.
