### ISSUE TITLE
Upgrade a Cluster's Version Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1798]
Re: [Upgrade a Cluster's Version](https://cockroachlabs.com/docs//v1.0/upgrade-cockroach-version.html)

## Issue Description

"and wait at least one minute after it rejoins the cluster to bring down the next node." is very descriptive and leaves room for error.

## Suggested Resolution 

Is there more prescriptive commands and checks that can be provided before moving on to the next node?

**Comment by jseldess** [comment]
Good point, @robert-s-lee. @mberhault, is there something specific we can tell users to look for to confirm that it's ok to move onto the next node?

**Comment by robert-s-lee** [comment]
is waiting for curl -s http://localhost:26258/_status/vars | grep "^ranges_underreplicated" to be all 0 valid?

**Comment by mberhault** [comment]
checking for underreplicated won't work for small (less than 3 nodes) clusters with the default replication config. For larger ones, it would work but upgrading while having underreplicated ranges is not necessarily a bad idea.
I would start by waiting until the admin UI is up.
A simple:
```
$ curl -I http://localhost:8080/_status/vars 
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: text/plain
Date: Fri, 11 Aug 2017 08:21:10 GMT
```

Or for secure mode:
```
$ curl -k -I https://localhost:8080/_status/vars 
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: text/plain
Date: Fri, 11 Aug 2017 08:24:47 GMT
```

**Comment by jseldess** [comment]
@mberhault, I'll add the example for pinging the admin UI. But what's the `wget` equivalent to the `-I` flag for `curl`?

```
-I, --head          Show document info only
```

**Comment by jseldess** [comment]
Closed by https://github.com/cockroachdb/docs/pull/1899.
