### ISSUE TITLE
Error: `exit status 255`

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1805]
From @a-robinson:

> “exit status 255” basically just means look in the logs for the fatal error message

However, it looks like this behavior might change with additional work from @knz

**Comment by bdarnell** [comment]
I think (@knz can confirm) that this has already been fixed for 1.1; @knz was proposing to backport the fix to 1.0.5 (assuming we do one)

**Comment by a-robinson** [comment]
Yeah, going to the logs should only be needed on 1.0.

**Comment by knz** [comment]
Unfortunately the issue also exists in 1.1. Looking at it now.

**Comment by jseldess** [comment]
Now that https://github.com/cockroachdb/cockroach/pull/17588 has landed, this is fixed in 1.0 and 1.1. Closing.
