### ISSUE TITLE
Update CONTRIBUTING - limit each copyable code block to one command

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1807]
For example, if you use the following:

<pre>
{% include copy-clipboard.html %}
~~~ shell
$ ls
$ cd ~/home
~~~
</pre>

When you click COPY on the docs site, you'll get the following on your clipboard:
~~~
lscd
~~~

I would expect it to preserve the line breaks.

We could either fix this issue or we could change the guidance to handle this limitation and allow only one command per code block.

**Comment by jseldess** [comment]
This is a known issue, to me at least, but I realize I didn't document it in [`CONTRIBUTING.md`](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md#copy-to-clipboard). For now, let's just allow one command per code block. We can revisit the fix your suggest later.

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/2688.
