### ISSUE TITLE
sql: Integrate inline/contextual help

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1810]
Roadmap: https://airtable.com/tblD3oZPLJgGhCmch/viwdV1sM5KEK2L14K/recJfXkkUorGJPEKN

PRs:
- https://github.com/cockroachdb/cockroach/pull/16295
- https://github.com/cockroachdb/cockroach/pull/13540

**Comment by jseldess** [comment]
@knz, thanks for adding this to the 1.1 roadmap. I see that one of the related PRs has landed. When everything's done and ready for docs, can you please ping here and add the `ready` label?

**Comment by knz** [comment]
thanks for the reminder.

**Comment by knz** [comment]
gtg
