### ISSUE TITLE
backup/restore: Change to the WITH OPTIONS syntax

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1811]
PR: https://github.com/cockroachdb/cockroach/pull/17528

@sploiselle, looks like in `RESTORE`, the `WITH OPTIONS` syntax has been changed. According to [this comment](https://github.com/cockroachdb/cockroach/pull/17528#issuecomment-321097489) from @dt, though, the old syntax will continue to work for 1.1, so this is low-priority.

**Comment by jseldess** [comment]
@sploiselle, is this covered in your 1.1 updates?

**Comment by Amruta-Ranade** [comment]
For 1.1: Let it be in the diagrams, replace in examples.
Check for 1.2

**Comment by Amruta-Ranade** [comment]
As per discussion with @dt, we are supporting both formats for 2.0 as well. So using the same strategy as for 1.1: Let it be in the diagrams, replace in examples.
