### ISSUE TITLE
Team City: Testing of examples

### ISSUE THREAD

**Issue by tbg** [cockroachdb/docs#182]
The fact that the examples are not self-contained (they rely on some shared nonstandard setup) and only tested at the time of authoring makes it very likely that they will break (or at least are annoying to maintain).

We should set up CI for them. Docker is going to be our best bet (and in fact @mjibson already did a lot of the work required for the acceptance tests).

We could try to pull in the acceptance test framework, but it should be easier to keep it more minimal and independent by running a sequence of docker invocations of form

`docker run -v "$(pwd)/_includes/app:/examples" cockroachdb/examples-test "php /examples/basic-sample.php"`.

where `cockroachdb/examples-test` is just a thin layer on top of `cockroachdb/postgres-test`.

**Comment by jseldess** [comment]
Now that we're using circleci to test the html output for each PR, perhaps we could also find a way to test the examples. @mberhault, @tschottdorf, what would that involve? Having circle ci checkout out and startup cockroach in a container, install various drivers, and then run each example against the cluster?

**Comment by jseldess** [comment]
@dt found something that could help here: https://github.com/campoy/embedmd

Ideally, the runnable samples would live in another cockroach repo, and we'd use comments in that file to start and start embeds in the docs.

**Comment by jseldess** [comment]
Resurrecting this for a possible 2.2 docs project. 

cc @rmloveland and @BramGruneir

**Comment by jseldess** [comment]
Not going to happen for 19.1 Moving to 19.2.

**Comment by jseldess** [comment]
Moving this to 20.1 timeframe.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/7066.
