### ISSUE TITLE
Code blocks: Copy to clipboard button overlaps code

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1821]
[Reported by](https://github.com/cockroachdb/docs/pull/1763#issuecomment-322284639) from @jess-edwards: The "copy" button in code snippets cuts off longer lines. How can we improve this UX?

cc: @kuanluo 

![screen shot 2017-08-14 at 4 51 06 pm](https://user-images.githubusercontent.com/15893490/29291191-cc433342-8110-11e7-9220-822d66003b93.png)

**Comment by kuanluo** [comment]
@jseldess @jess-edwards Can you point me to where this happens? I poked around, and saw longer lines usually have this behavior:
![image](https://user-images.githubusercontent.com/1486483/29320772-8404802e-8195-11e7-8d31-bba015123602.png)
(From https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html)

**Comment by jseldess** [comment]
Yeah, as you've found, it happens wherever we've used copy to clipboard and a line is long enough to be obscured by the "Copy" text and icon. In principle, I think it's ok for long lines to continue past the right margin. The "Copy" text is just pushing the right margin further in. 

A possible solution would be moving the "copy" text and icon outside of the code block, just to the right. I can't remember why we didn't go with this in the first place...

**Comment by kuanluo** [comment]
> Yeah, as you've found, it happens wherever we've used copy to clipboard and a line is long enough to be obscured by the "Copy" text and icon. In principle, I think it's ok for long lines to continue past the right margin. The "Copy" text is just pushing the right margin further in.

Agreed. The screenshot you attached should have the same behavior. That might be a bug? 

> A possible solution would be moving the "copy" text and icon outside of the code block, just to the right. I can't remember why we didn't go with this in the first place...

Might be an overall content width issue. We can reopen the convo with Division Of and see what we can do?

**Comment by luciaaaaaaa** [comment]
@jseldess I think its okay for the copy button to cover some of it (since the user will have to scroll anyways to see the whole line. 

Show the scroll bar when the user is scrolling or on hover would help clarify there is more past the right margin.
Removing the icon from the copy button will also help

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A12946
