### ISSUE TITLE
context-sensitive help points to broken links

### ISSUE THREAD

**Issue by tamird** [cockroachdb/docs#1822]
https://github.com/cockroachdb/cockroach/pull/16295 added links to:

https://www.cockroachlabs.com/docs/show-indexes.html
https://www.cockroachlabs.com/docs/alter-index.html
https://www.cockroachlabs.com/docs/show-backup.html
https://www.cockroachlabs.com/docs/alter-database.html

none of which exist.

**Comment by jseldess** [comment]
@knz, the url to use in all these cases is `https://www.cockroachlabs.com/docs/stable/...`. Let me know if you want me to make the change myself.

**Comment by tamird** [comment]
@jseldess are you sure? https://www.cockroachlabs.com/docs/stable/show-indexes.html doesn't exist, and the same is true of all the others.

**Comment by jseldess** [comment]
Oh, you're right. Didn't look closely. Sorry.

- https://www.cockroachlabs.com/docs/stable/show-index.html (not show-indexes.html - though that probably would be a better filename)
- `ALTER INDEX`, `SHOW BACKUP`, and `ALTER DATABASE` are all new in 1.1. Pages haven't been added yet. But even when we add pages, they'll be at `https://cockroachlabs.com/docs/dev/...` until the release, at which point they'll be at `https://www.cockroachlabs.com/docs/stable/...`. 
   - Should we just not link to them for now and add these links in a post-1.1 patch release?
   - Or should we leave these broken links in the expectation that they'll work as of the release?

**Comment by jseldess** [comment]
Hold on, I was wrong yet again. The only statement not yet documented is `SHOW BACKUP`.

- `ALTER INDEX` should link to https://www.cockroachlabs.com/docs/stable/rename-index.html - `ALTER DATABASE` should link to https://www.cockroachlabs.com/docs/stable/rename-database.html 

For both of the above, `RENAME` is the only sub-statement currently.

**Comment by bdarnell** [comment]
Links in the code should point to the corresponding specific version (1.0, 1.1, etc), not `stable`.

**Comment by knz** [comment]
1) I will make a mechanism which generates the links automatically based on the version being compiled. This will address the question of which prefix to use

2) I will add the missing pages. It doesn't seem right to me that "alter index", which actually contains multiple sub-commands, only has one page "rename index". Ditto for database.

**Comment by jseldess** [comment]
Thanks, @knz. But what additional sub-commands are you referring to for `alter index` and `alter database`. Even in the 1.2 grammar, I still only see the rename commands:

- https://www.cockroachlabs.com/docs/dev/sql-grammar.html#alter_index_stmt
- https://www.cockroachlabs.com/docs/dev/sql-grammar.html#alter_database_stmt

**Comment by knz** [comment]
ALTER INDEX has 4 variants. We only document 1 for now, but more *will* be documented once we have tested the features more thoroughly.

ALTER DATABASE currently has only 1 variant, but then ... it is the case that ALTER is an access mechanism for sub-commands. We are bound to add more variants in the future (for example when we want to copy permissions from one db to another), so it seems logical to me that documentation should have a page called "alter database" and say "for now, ALTER DATABASE only has a single sub-command" and then a "renaming database" section under that.

**Comment by jseldess** [comment]
Thanks for clarification, @knz, and for helping out there. 

When you have a chance, can you point me to info about the other variants of `alter index`? I haven't heard anything about them.

**Comment by jseldess** [comment]
@knz, any updates here? No rush. Just want to make sure I don't miss the corresponding PR.

**Comment by knz** [comment]
Fixed via  cockroachdb/cockroach#17990 and #1869
