### ISSUE TITLE
provide documentation around service discovery tooling

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1824]
Tracking issue for 1.2 - PM investigation needed to see what the most common service discovery tools are, and determine if we should do any documentation. No action needed from docs yet.

Just FYI - these used to sit in the airtable roadmap, but we decided to move product-related doc items out into GitHub issues.

**Comment by sploiselle** [comment]
Duplicate of #1793; do you mind closing this Diana?

**Comment by dianasaur323** [comment]
Yep! Thanks
