### ISSUE TITLE
adjust Getting Started to reduce emphasis on local development

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1825]
Provide two different tracks for users - current Getting Started guide emphasizes local development, which isn't the actual way we want users to run CockroachDB long term.

Just FYI - these used to sit in the airtable roadmap, but we decided to move product-related doc items out into GitHub issues.

**Comment by jseldess** [comment]
Thanks for opening these, @dianasaur323. I'd prefer for the strategically important docs work to also be on the roadmap, though. Why is it a problem to have them there as well?

Also, the issue description doesn't really match the conversations we had. For getting started, a local cluster remains the way to go, but we discussed the need to reduce the emphasis on (or complexity of) running multiple nodes locally.

**Comment by jseldess** [comment]
I think local startup is still the best avenue to getting started with the cockroachdb. I don't forsee changing this anytime soon, but I'll keep this on the backlog for future consideration.

**Comment by jseldess** [comment]
Closing this, as our getting started docs generally get positive reviews from users.
