### ISSUE TITLE
Document common error messages

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1826]
Identify common error messages and provide potential troubleshooting advice. This may be cross posted to StackOverflow if it makes sense from a user perspective.

Just FYI - these used to sit in the airtable roadmap, but we decided to move product-related doc items out into GitHub issues.

**Comment by jseldess** [comment]
@dianasaur323, we added this [Common Errors](https://www.cockroachlabs.com/docs/stable/common-errors.html) page with https://github.com/cockroachdb/docs/pull/2311. 

Do you think that's a sufficient start for 2.0? For 2.1, we could continue identifying common errors and add them with solutions.

**Comment by jseldess** [comment]
With https://www.cockroachlabs.com/docs/stable/common-errors.html as well as the troubleshooting training content at https://www.cockroachlabs.com/docs/stable/training/, considering this done for now.
