### ISSUE TITLE
Backup/restore: document basic resource planning

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1827]
Document how users can access tables and their sizes to determine the capacity needed for a backup and restore in the full and incremental backup set. 

Our customers care about provisioning enough hardware for backup and restore jobs. They need guidance on how to figure out how much storage they should provision for any given backup / restore job.

User story: As an operator, I need to know how large my backups and restores will be so that I can provision enough storage to complete the job. 

This also comes as a direct question from a customer regarding how to provision hardware.

**Comment by jseldess** [comment]
@mjibson, @danhhz, do we have specific recommendations we can make already? If so, can you share so I can add to the docs?

**Comment by mjibson** [comment]
The backup size is the sum of the size of all the tables as shown in the admin UI divided by the replication factor. The restore size is the size of the on-disk backups times the replication factor. Can someone (Dan?) verify that?

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
