### ISSUE TITLE
Import data from mysql

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1831]
## Title

MySQL Migration

## Description

The following will provide table by table DDL and TSV files.

mysqldump  -h localhost -u root --tab=/tmp database_name

## Outline

The DDL should be modified to use CRDB features.
The TSV can be imported using the following assuming t1.txt is the TSV 

echo "copy tablename from stdin;" > copyfrom.sql
cat copyfrom.sql t1.txt | psql

## Expected Audience

Developers and DBA

**Comment by jseldess** [comment]
This is being covered by @rmloveland's 2.1 work: https://github.com/cockroachdb/docs/issues/2936.
