### ISSUE TITLE
Leaseholder rebalancing and leaseholder locality (follow-the-sun)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1843]
RFCs:
- [Leaseholder rebalancing](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/leaseholder_rebalancing.md)
- [Leaseholder locality](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/leaseholder_locality.md)
 
Additional explanations of load-based leaseholder rebalancing (new in 1.1): 
[explanations.pdf](https://github.com/cockroachdb/docs/files/1234759/explanations.pdf)

**Comment by sploiselle** [comment]
@a-robinson Is this good to document for 1.1?

**Comment by a-robinson** [comment]
Follow-the-sun lease rebalancing is good to document. It was already present in 1.0, also.
