### ISSUE TITLE
Feedback: Cluster Single Sign-on (SSO) using JSON web tokens (JWTs)

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#18455]
Jianwei Lin (lin-crl) commented:

Page: https://cockroachlabs.com/docs/v23.2/sso-sql.html

## What is the reason for your feedback?

[ ] Missing the information I need

[ ] Too complicated

[ ] Out of date

[x] Something is broken

[ ] Other

## Additional details

cluster setting `server.server.jwt_authentication.jwks_auto_fetch.enabled` doesn't exist on 23.2.
I've tried `server.jwt_authentication.jwks_auto_fetch.enabled`  it doesn't exist either.

Jira Issue: DOC-10056

**Comment by pritesh-lahoti** [comment]
Regarding `server.jwt_authentication.jwks_auto_fetch.enabled`, the change was backported to 23.2 around March - https://github.com/cockroachdb/cockroach/pull/119768, hence it ended up in v23.2.4 and beyond.
