### ISSUE TITLE
The description about --pretty option should be replaced with a description about --format option for the SQL client

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/docs#1846]
In the SQL client, `--pretty` has been replaced with `--format`. I have verified it in v1.0.4. But https://www.cockroachlabs.com/docs/stable/use-the-built-in-sql-client.html still describes `--pretty` instead of `--format`.

**Comment by jseldess** [comment]
Thanks for reporting, @yaojingguo!

**Comment by jseldess** [comment]
Fixed in https://github.com/cockroachdb/docs/pull/1905.
