### ISSUE TITLE
Improve bulk insert guidance 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1851]
Based on [this comment](https://github.com/cockroachlabs/PremierInc/issues/1#issuecomment-323886647) by @petermattis, the data import docs misleadingly state that 500 is the optimal number for bulk inserts. In reality, 500 is a good place to start, but larger and smaller can be better (depending the schema).

@petermattis, do we have anything more specific we can say? How might a user know that 500 isn't optimal?

**Comment by petermattis** [comment]
> @petermattis, do we have anything more specific we can say? How might a user know that 500 isn't optimal?

There is really only one way: by trying larger and smaller values. Somewhere else in the docs we say that batch sizes of 1,000 to 10,000 have worked well. Perhaps give a range, note that this is schema dependent (row size, column families and number of indexes will affect it) and that testing on the desired production setup is necessary.
