### ISSUE TITLE
Install page should change URL for each option

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#1856]
It's often the case that I want to link to an OS/Install Method combination on https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html. Can we add these options to the URL so we can properly link into a specific option?

**Comment by jseldess** [comment]
@benesch, I can't figure out why the `allowed-hashes` don't work on the install page. They work fine on https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html. Do you have any ideas?

**Comment by benesch** [comment]
IIRC allowed-hashes was a hack to avoid HTML proofer errors when another page linked to a different version. (#linux doesn't actually exist on the page, so HTML proofer would complain.)

I think the install page simply doesn't have the JavaScript necessary to support linking to a particular OS directly.
