### ISSUE TITLE
CANCEL QUERY Doc Update 

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1858]
Re: [CANCEL QUERY](https://cockroachlabs.com/docs//v1.1/cancel-query.html)

## Issue Description

This is more of an ongoing question that we might want to cover: I ran two different queries from two different nodes, but the client address still comes up as 127.0.0.1. How can we configure that?

![image](https://user-images.githubusercontent.com/5768024/29641646-8d26e9e6-8832-11e7-810e-216e4e91a69b.png)

**Comment by jseldess** [comment]
@dianasaur323, looks like you were running both nodes on the same machine? If so, it makes sense that the `client_address` would be the same....

**Comment by bdarnell** [comment]
The `client_address` must be interpreted relative to the `node_id`. In theory, each node has its own view of the network, although in practice this only matters for special addresses like `127.0.0.1`. I'm not sure what we could do to make this clearer aside from calling it out in the docs.

**Comment by jseldess** [comment]
I might still be missing something, but is it worth cluttering the docs with a callout that likely only address running multiple nodes on a single machine (not a realistic case)?

**Comment by bdarnell** [comment]
This happens for nodes on multiple machines too. (I'm not sure how Diana's cluster is configured here).

**Comment by dianasaur323** [comment]
@jseldess I have four separate nodes that are geographically distributed, and was running different queries from each. I only noticed the node id separating the queries later on.

**Comment by jseldess** [comment]
@dianasaur323 and I discussed offline. This is most likely to happen when running the sql client on the same machine as a node. Since this isn't really the encouraged way, we're going to wait and see if users have the same confusion before complicating the description of `client_address`. I'll reopen if that happens.
