### ISSUE TITLE
security: remove cert-principal-map parameter from client commands

### ISSUE THREAD

**Issue by souravcrl** [cockroachdb/docs#18588]
Sourav Sarangi (souravcrl) commented:

We plan to only support cert-principal-map for server start commands start and start-single-node. Hence its use in docs for client commands should be removed. We should remove the reference of cert-principal-map from client side command docs like for [cockroach sql](https://www.cockroachlabs.com/docs/v23.1/cockroach-sql#client-connection) ,  [client connection parameters](https://www.cockroachlabs.com/docs/v23.1/connection-parameters#connect-using-discrete-parameters),  from [cockroach init command](https://www.cockroachlabs.com/docs/v23.2/cockroach-init#client-connection) and for numerous other pages which references the client side commands so customers don't accidentally start relying on them to provide aid in cert management.

Jira Issue: DOC-10345

**Comment by bdarnell** [comment]
Note that in older versions of CockroachDB this flag did have a purpose and was sometimes necessary to avoid warnings about certificate filenames not matching expectations. After https://github.com/cockroachdb/cockroach/pull/124567 lands we should deprecate the flag on client-side commands and plan to remove it in the future.
