### ISSUE TITLE
cli/sql: --safe-updates flag

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1861]
PRs:
- https://github.com/cockroachdb/cockroach/pull/17889
- https://github.com/cockroachdb/cockroach/pull/17604 

Summary: New `cockroach sql` flag called `--safe-updates`. If `true`, the following types of statements are not allowed:

- `DELETE` without a `WHERE` clause
- `UPDATE` without a `WHERE` clause
- `DROP DATABASE` on a non-empty database
- `ALTER TABLE DROP COLUMN`

Defaults to `true`.

**Comment by knz** [comment]
This can also be enabled/disabled within an open session with `SET sql_safe_updates = true/false`, and it will show up in the output of `SHOW SESSION`
