### ISSUE TITLE
Build a Python App with CockroachDB Doc Update 

### ISSUE THREAD

**Issue by EamonZhang** [cockroachdb/docs#1863]
Re: [Build a Python App with CockroachDB](https://cockroachlabs.com/docs//v1.0/build-a-python-app-with-cockroachdb.html)

## Issue Description
python basic-sample.py 
Traceback (most recent call last):
  File "basic-sample.py", line 5, in <module>
    conn = psycopg2.connect(database='bank', user='maxroach', host='locahost', port=26257)
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR:  invalid password
ERROR:  cleartext connections are not permitted

## Suggested Resolution 

cockroach user set maxroach --certs-dir=certs --password 
Enter password: 
Confirm password: 
INSERT 1

python basic-sample.py 
Initial balances:
['1', '1000']
['2', '250']

**Comment by jseldess** [comment]
Thanks for reporting this, @EamonZhang. It's on our roadmap to add secure versions of these code samples, hopefully within the next months.

**Comment by jseldess** [comment]
Secure versions of "build an app" have been live for a while, so closing this.
