### ISSUE TITLE
Feedback: Take and Restore Encrypted Backups: needs more details about GCM implementation

### ISSUE THREAD

**Issue by mikkorantalainen** [cockroachdb/docs#18662]
Exalate commented:

Page: https://cockroachlabs.com/docs/v24.1/take-and-restore-encrypted-backups.html

## What is the reason for your feedback?

[X] Missing the information I need

## Additional details

The page says that backup data at rest is encrypted with AES-GCM-256 and only links to Wikipedia page which explains that GCM mode is not safe to use if data stream is longer than 64 GB. Does that mean that CockroachDB encrypted backups are not safe if you have more than 64 GB of data?

If the encryption routine implements IV rollover or some other measure to avoid this vulnerability, it should be declared explicitly in the documentation.

Jira Issue: DOC-10554

**Comment by alicia-l2** [comment]
Hi! The linked page that you're referring to is how we generate secure keys for encrypted backups. The GCM mode and 64GiB refers to the size of the key, not the data itself. CockroachDB encrypted backups are safe at scale.
