### ISSUE TITLE
Document GCE's non-standard NTP servers

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#1867]
Clusters that span both GCE and other hosting providers can have problems on leap second days, because Google's NTP servers handle leap seconds differently from the standard NTP pool. If you mix GCE and non-GCE nodes in the same cluster, you must either point the GCE nodes at a non-google NTP server or point all the non-GCE nodes at google's (https://developers.google.com/time/).

**Comment by bdarnell** [comment]
Google's NTP servers "smear" the leap second, which is recommended for CRDB (https://github.com/cockroachdb/docs/issues/960#issuecomment-270587565). Therefore it should be preferred to point everything at google's ntp servers instead of the other way around. When using NTP servers that don't smear the leap second, client-side slewing of the leap second should be configured in the same way on each node.

**Comment by petermattis** [comment]
I seem to recall some other cloud providers smear the leap second as well. Looks like [Amazon does](http://www.zdnet.com/article/amazon-find-its-own-way-around-leap-second-problem-by-skewing-time-instead/).

**Comment by bdarnell** [comment]
Amazon smears the leap second on their own systems, but EC2 instances by default use standard NTP and experience a 1-second jump. It doesn't look like amazon provides an NTP server or other way to set your EC2 instances to "AWS Adjusted Time".

Even if they did, this makes things more complicated: smearing the leap second requires a few parameters to be set to determine exactly when and how the clock rate is adjusted. Maybe we should just document that for any cross-cloud scenario you should override the NTP configuration to point to a specific pool (either the public one or google's) instead of using the cloud provider's defaults.
