### ISSUE TITLE
Feedback: Node Shutdown

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#18685]
Page: https://cockroachlabs.com/docs/v24.1/node-shutdown.html

## What is the reason for your feedback?

[ ] Missing the information I need

[ ] Too complicated

[x] Out of date

[ ] Something is broken

[ ] Other

## Additional details
We have changed some clusters setting for node shutdown. Could we update them to keep them consistent w/ cluster setting page? So that it's clear and not confusing. Thanks!

server.shutdown.initial_wait
(alias: server.shutdown.drain_wait)

server.shutdown.connections.timeout
(alias: server.shutdown.connection_wait)

server.shutdown.transactions.timeout
(alias: server.shutdown.query_wait)

server.shutdown.lease_transfer_iteration.timeout
(alias: server.shutdown.lease_transfer_wait)

In addition, we have a new cluster setting on job.timeout. What does it start in the drain process? Could we document it so we can advise customers on it. Thanks!
server.shutdown.jobs.timeout
(alias: server.shutdown.jobs_wait)

**Comment by mdlinville** [comment]
The old setting names continue to work and are ubiquitous. After https://github.com/cockroachdb/cockroach/pull/125643 is backported to a major version, both setting names will appear in the Cluster Settings page for that version, and I can safely update the non-automated docs to use the new names, while still allowing docs for the old setting names to be found. That's being tracked separately.

We discovered together that the new setting can safely be ignored.
