### ISSUE TITLE
Link from data type docs to relevant functions and operators

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/docs#1870]
I was looking for date manipulation functions and stumbled upon https://www.cockroachlabs.com/docs/stable/date.html, but what I really was looking for was https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions. 

Might be a good idea to add a link from the data type to the functions that operate on it under the "See More" section.

This also applies to other data types and not just DATE.

**Comment by Tawishi** [comment]
I would like to work on this issue.

**Comment by Amruta-Ranade** [comment]
@Tawishi Sure. If you are participating in Hacktoberfest, I recommend waiting until at least Tuesday to open a PR. We haven't updated the repo to follow the [new rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update) yet.

**Comment by Tawishi** [comment]
Okay, till Tuesday then. :smiley:

**Comment by shrey27tri01** [comment]
Hello! Is someone working on this issue?
If no, can I take this up? :)

**Comment by Amruta-Ranade** [comment]
Let me check :)
@Tawishi Are you working on this? Feel free to open a PR now -- we marked the repo for hacktoberfest :)

**Comment by Tawishi** [comment]
@Amruta-Ranade  Where are the data types to be linked?

**Comment by Amruta-Ranade** [comment]
I think the work here is to add link to
functions and operators in https://www.cockroachlabs.com/docs/stable/functions-and-operators.html from data types in https://www.cockroachlabs.com/docs/stable/data-types.html

**Comment by jseldess** [comment]
@Amruta-Ranade, @Tawishi, that's not really the solution we're looking for. The request is to link to relevant functions for each data type. For example, link the [array data type](https://www.cockroachlabs.com/docs/v20.1/array) doc to the [array functions](https://www.cockroachlabs.com/docs/v20.1/functions-and-operators.html#array-functions).

Let me open a quick PR to demonstrate how we want this done, @Tawishi.

**Comment by jseldess** [comment]
@Tawishi, please emulate what I've done in this PR for the `ARRAY` type: https://github.com/cockroachdb/docs/pull/8623. You'll need to look through the other type docs and see if there are corresponding sections of the function doc to link to. In some cases, there probably won't be. For a few types, we might already be doing this. 

Please ping here if you have questions.

**Comment by Tawishi** [comment]
Most datatypes do not have a _functions_ section in the contents. Should I insert the links in the See Also section as done for _inet.md_ ?

**Comment by jseldess** [comment]
Yes, if a type doesn't have a corresponding section, it's probably find to link to the general functions and operators page from `See also`. But if there is an explicit group of functions, I think it'd be better to add a section to the type doc. In fact, `INET` does have it's only group of functions, so it'd be best if that type doc had its own `Functions` section. Thanks, @Tawishi!

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
