### ISSUE TITLE
Build a Java App with CockroachDB Doc Update 

### ISSUE THREAD

**Issue by 249550148** [cockroachdb/docs#1879]
Re: [Build a Java App with CockroachDB](https://cockroachlabs.com/docs//v1.0/build-a-java-app-with-cockroachdb.html)

## Issue Description
This doc only talks about connecting to an insecure cluster,   while connect to secure cluster, it fails with "org.postgresql.util.PSQLException: ERROR: cleartext connections are not permitted"

## Suggested Resolution 
Should list example about connecting to secure clusters: how CAs are generated and used; only use user and password to connect a secure cluster, etc.

**Comment by jseldess** [comment]
Thanks for opening this issue, @249550148. We definitely plan to add secure examples to the build an app tutorials. We're tracking that work here: https://github.com/cockroachdb/docs/issues/631
