### ISSUE TITLE
sql: id generating SQL builtin functions 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#188]
I see at least `unique_rowid`, `experimental_uuid_v4`, `experimental_unique_bytes`.
Someone already asked about them, and surely more will follow.
Autoincrement columns might even deserve a FAQ.

**Comment by bdarnell** [comment]
We should also figure out what to do about the experimental functions. Any reason not to just rename `experimental_uuid_v4` to `uuid_v4`? (I'm not sure why it was experimental in the first place; it seems well-defined and useful). Now that we have non-experimental `unique_rowid` is there any reason to keep `experimental_unique_bytes` or should we just get rid of it? (I was the biggest champion of `experimental_unique_bytes` but now that we've improved `unique_rowid` I don't see any reason to keep it around).

**Comment by jseldess** [comment]
I was hoping to get to functions for beta, but time ran out. I'll start on this after finishing `cockroach zone` command docs (and maybe privileges).

**Comment by jseldess** [comment]
Getting lots of questions about this topic, and there have been a bunch of searches on it in our docs. 

Aside from the `unique_rowid()` function doc:
- Add `unique_rowid()` example to `CREATE TABLE` docs.
- Possibly add to other getting started docs.
