### ISSUE TITLE
Feedback: Install CockroachDB on Mac

### ISSUE THREAD

**Issue by idapartners** [cockroachdb/docs#18834]
Page: https://cockroachlabs.com/docs/v24.2/install-cockroachdb-mac.html

## What is the reason for your feedback?

[ ] Missing the information I need

[ ] Too complicated

[ ] Out of date

[ X] Something is broken

[ ] Other

## Additional details
The docs say, `docker pull cockroachdb/cockroach:v24.2.0`; but that tag doesn't exist on DockerHub. I would have just fixed the doc, but I'm not actually sure which tag should currently be recommended.

Jira issue: DOC-10949

**Comment by rickystewart** [comment]
The docs must have been published early, but v24.2.0 is now released and the Docker image is published.
