### ISSUE TITLE
Style guide for diagrams in docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1886]
Now that we're adding diagrams to our docs, we should work with Design ( @kuanluo) to come up with a consistent style and approach. 

Current docs with diagrams:
- [Parallel Statement Execution](https://www.cockroachlabs.com/docs/dev/parallel-statement-execution.html)
- [Remove Nodes](https://www.cockroachlabs.com/docs/v1.1/remove-nodes.html)

**Comment by kuanluo** [comment]
Thank you for flagging, @jseldess! I will take a stab at this next week.

**Comment by nvanbenschoten** [comment]
The parallel statement execution diagrams will also be used in the corresponding blog post, which is slated for release in a few weeks. I'm really excited to see what @kuanluo comes up with!

**Comment by kuanluo** [comment]
Now that's a lot of pressure, @nvanbenschoten. I will put some time on the calendar for us to discuss how to improve the diagrams.

**Comment by jseldess** [comment]
@kuanluo, 2 questions:

1. Would you be willing to redesign the existing images in the docs (removing nodes and parallel statement execution)?
2. Are we doing more work on design templates for 1.2, or should I close this issue?

**Comment by kuanluo** [comment]
To your questions, 

1) There are some component library style update work underway, so I won’t update the diagrams just yet. We will hopefully be able to update existing styles before end of Q4.

2) And yes, feel free to close this issue!

**Comment by jseldess** [comment]
Thanks, @kuanluo!
