### ISSUE TITLE
New Doc Proposal: Build a .NET Core App with CockroachDB

### ISSUE THREAD

**Issue by wub** [cockroachdb/docs#1888]
I'm happy to contribute this documentation when I have time.

## Title
Build a .NET Core App with CockroachDB

## Description
This tutorial shows you how build a simple .NET Core application with CockroachDB using a PostgreSQL-compatible driver or ORM.

## Outline
1. Install/set up .NET Core app
2. Install/set up Cockroach
3. Connect app to db with Npgsql and one of two ORMs:
    - Entity Framework Core
    - Dapper
4. Basic CRUD operations
5. Transactions

## Expected Audience
Web app developers

**Comment by sirajzarook** [comment]
Hi Jarrod

We looking to use CockroachDB for a .Net Core Api (on .Net Core 2.0). Do you have any updates on your attempt with building a Net Core app with this yet or any concern.

Thanks

**Comment by jseldess** [comment]
@sirajzarook, @wub, we're close to publishing C# code samples and tutorials. Should be within the next week or two. You can take an earlier look at the code samples here: https://github.com/cockroachdb/docs/pull/1991

**Comment by jseldess** [comment]
cc: @BramGruneir, @awoods187

**Comment by jseldess** [comment]
@sirajzarook, @wub, we just added a tutorial on [building a C# app with CockroachDB](https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html). Please take a look and let us know if you have any questions.
