### ISSUE TITLE
How to get appropriate timestamp for BACKUP...AS OF SYSTEM TIME

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1893]
Re: [BACKUP](https://cockroachlabs.com/docs//v1.0/backup.html)

## Issue Description

We should be more specific about what the system time is. Particularly in a geo-distributed database, what timestamp should you use for now?

## Suggested Resolution 

Quick suggestion on how to get the time (aka SELECT NOW())

**Comment by sploiselle** [comment]
@tschottdorf You sent in #1549 which removed my use of `current_timestamp()` for a value of `AS OF SYSTEM TIME`; is using `now()` in the same context more viable?

**Comment by tschottdorf** [comment]
@sploiselle I had no issue with that code except that it doesn't work (because you can't specify non-constants in that position, at least you couldn't then). If it works, I'm happy even with the version before my change.

**Comment by sploiselle** [comment]
@dianasaur323 Have you tested that a non-constant works?

**Comment by dianasaur323** [comment]
@sploiselle no I haven't, although this was actually just running SELECT NOW() in sql, and copying it over into the backup / restore command.

The thing is, the better way to run it at "now" would really be to not specify as of system time. The reason for having as of system time is that you are less likely to block transactions if you choose an as of system time >10sec ago. In that context, what are your suggestions on how to make the documentation clearer?

**Comment by sploiselle** [comment]
@dianasaur323 I don't have a suggestion other than what you're recommending here; was simply trying to figure out how to accomplish what you were asking.

I also think I misunderstood your suggestion originally––thought you were recommending `now()` in the statement itself. I realize now you're just recommending to tell people how to get an appropriate timestamp to use, and then pasting it into the statement.

**Comment by dianasaur323** [comment]
Precisely! I'm also open to some other suggestions as well if you think something else might be better.

**Comment by robert-s-lee** [comment]
Examples to start the backup with -10S
```
echo "backup test.* to 'nodelocal:/tmp/me' as of system time '$(date -u -v-10S '+%Y-%m-%d %H:%M:%S')';" | cockroach sql —insecure
```

The same if already in the CLI:
```
cockroach sql —insecure
\| echo "backup test.* to 'nodelocal:/tmp/me' as of system time '$(date -u -v-10S '+%Y-%m-%d %H:%M:%S')’;"
```

**Comment by jseldess** [comment]
The backup docs have changed a lot since this issue was created. Closing for now.
