### ISSUE TITLE
Update AS OF SYSTEM TIME syntax example

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1894]
Re: [BACKUP](https://cockroachlabs.com/docs//v1.0/backup.html)

## Issue Description

Some docs updates needed. In incremental backup, AS OF SYSTEM TIME doesn't work if it's placed after the entire command. It needs to be placed after just the BACKUP command. We also need to be explicit that incremental backups can only be created within the 24 hour GC window.

**Comment by sploiselle** [comment]
@dianasaur323 Are you saying the [SQL diagram](https://www.cockroachlabs.com/docs//v1.0/backup.html#synopsis) on that page is incorrect?

**Comment by dianasaur323** [comment]
The SQL diagram looks fine to me. I'm saying that this example is incorrect. 
![image](https://user-images.githubusercontent.com/5768024/30328844-8ef0f0fc-979e-11e7-9f20-53e3603517b1.png)

**Comment by dianasaur323** [comment]
As of system time should come after the backup command and before the incremental command

**Comment by dianasaur323** [comment]
@jseldess @Amruta-Ranade could we get a fix in for this soon? a user ran into this issue again today.

**Comment by Amruta-Ranade** [comment]
Sure.

**Comment by Amruta-Ranade** [comment]
@dianasaur323 
- This fix is applicable to v1.0, v1.1, and v2.0, right?
- We already talk state that "You can only create incremental backups within the garbage collection period of the base backup's most recent timestamp."
