### ISSUE TITLE
sql: descriptions of built-in functions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#19]
To be part of the SQL Reference section.
- CockroachDB SQL built-in functions: https://github.com/cockroachdb/cockroach/blob/master/sql/parser/builtins.go

Related docs: 
- https://drive.google.com/a/cockroachlabs.com/folderview?id=0B5l6NSPOAeQAejliTk0zeEVXUG8&usp=drive_web
- http://www.postgresql.org/docs/9.5/static/functions.html

**Comment by sploiselle** [comment]
Need to add:
- Descriptions for functions and operators
- `BETWEEN`document
