### ISSUE TITLE
Install CockroachDB Doc Update 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#1926]
Re: [Install CockroachDB](https://cockroachlabs.com/docs//v1.0/install-cockroachdb.html)

The install page should have a link to releases, particularly beta releases.
Otherwise, it took me a while to find the "releases" link on the left bar (and I knew what I was looking for, more or less).

**Comment by andreimatei** [comment]
Sorry, the link already exists. My fail.

**Comment by jseldess** [comment]
Seems like it was hard to spot? Any recommendations about how that could've been more findable? Where did you look for it at first?
