### ISSUE TITLE
Document ENUM limitation with Sequelize

### ISSUE THREAD

**Issue by justinj** [cockroachdb/docs#1929]
Sequelize has an ENUM type. When used with Postgres, this is backed by Postgres's actual `ENUM` sql type, but when used with databases that don't support `ENUM`s (for example, sqlite), it is backed by a `TEXT` field. Since CockroachDB also does not support `ENUM`, [this PR](https://github.com/cockroachdb/sequelize-cockroachdb/pull/17) makes `ENUM`s used with Cockroach backed by `TEXT` fields. This gives less safety than Postgres's `ENUM`s, since the database will not verify that the values come from the set of specified fields. We should document this limitation once the next version of `sequelize-cockroachdb` is published.

**Comment by vy-ton** [comment]
@ericharmeling @rafiss Should this Sequelize workaround be removed from our adapter now that CockroachDB has ENUM support?

**Comment by rafiss** [comment]
Yes, we should remove that workaround. I created this issue: https://github.com/cockroachdb/sequelize-cockroachdb/issues/44

I think this docs limitation could still be published for versions 20.1 and earlier.

**Comment by ericharmeling** [comment]
Not sure we need to document this anymore.
