### ISSUE TITLE
Kubernetes: document how to customize the default configuration

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#1933]
As @mjibson recently pointed out to me, it's pretty likely that users of our Kubernetes configuration may want to know how to customize it (either before or after they've created it). This would mean things like changing the disk size, asking for SSDs instead of HDDs on certain cloud platforms, or putting specific resource limits on the containers. We should include an explanation and/or pointers to the Kubernetes docs on topics like these.

**Comment by mjibson** [comment]
As a note: I successfully resized 3 GCE persistent disks. I manually edited their sizes in the GCE editor, then SSH'd into each and ran `sudo resize2fs /dev/sdb`. Moments later the admin ui showed the new cluster size. Was easy

**Comment by jseldess** [comment]
Thanks for logging this, @a-robinson and @mjibson. Hoping to get back to k8 docs soon.

**Comment by mjibson** [comment]
Second note: when attempting to update the cockroach image, I change the tag in the image line of the yaml file and did a `kubectl apply -f`, but it didn't redeploy the pods. Need to document how to do rolling image updates of the cluster when upgrading versions.

**Comment by mjibson** [comment]
Next problem was attempting to use the BACKUP command from one of these on GKE. I created a bucket in GCS but was not able to figure out permissions. Anything I did yielded: `pq: exporting 3 ranges: write to google cloud: googleapi: Error 403: Insufficient Permission, insufficientPermissions`. There are k8s service accounts and google service accounts and it's unclear how they work together. The pods have some service account thing but I couldn't see what to do with that.

**Comment by mjibson** [comment]
To use SSDs on GCE, add this to the yaml file:

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
```

And change the value of `volume.alpha.kubernetes.io/storage-class` to `fast`

**Comment by a-robinson** [comment]
> Next problem was attempting to use the BACKUP command from one of these on GKE.

Container Engine clusters default to only giving the nodes the read-only storage permission. If you want to do backups from them, the cluster (or more specifically, the "node pool") has to be created with the read-write storage permission. See https://stackoverflow.com/questions/29837531/changing-permissions-of-google-container-engine-cluster for a much more concise answer than the official docs have.

**Comment by mjibson** [comment]
Ugh I spent so many hours working around that permissions problem and asked my own stackoverflow question to try to figure it out. Thanks for the link, and we should definitely have something explaining how to do this.

**Comment by a-robinson** [comment]
Another note from @mjibson's experience in https://github.com/cockroachdb/cockroach/issues/19631 - we should point users at https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ on how to configure CPU/memory requests and limits for their pods. This is considered a standard best practice for running anything production on Kubernetes (i.e. it's not specific to us), but many people don't know best practices for Kubernetes.

**Comment by jseldess** [comment]
This should be covered by https://github.com/cockroachdb/docs/issues/2937.

**Comment by a-robinson** [comment]
Closed by https://github.com/cockroachdb/docs/pull/2896
