### ISSUE TITLE
Email subscription footer covers version switcher

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#1935]
Open a long docs page (may need to be in an incognito window if you've already dismissed the banner) and scroll to the bottom. The email subscription banner covers up the version switcher and the "help" button which are pinned to the bottom of the screen. We should either get rid of the popup or have it push the version switcher up so it stays on the screen.

**Comment by jseldess** [comment]
Version switcher was moved to secondary topnav.
