### ISSUE TITLE
Document new reserved keywords

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#1937]
Adding a reserved keyword is a backwards-incompatible change, so as a part of our upgrade documentation and release notes we need to inform our users about any new reserved words in ([this list](https://github.com/cockroachdb/cockroach/blob/9ffa345826002aaf081112e683756b6fc663790d/pkg/sql/parser/sql.y#L6466)).

For 1.1 there is one new reserved word, `current_schema`.

**Comment by jseldess** [comment]
Thanks for calling this out, @bdarnell. I have an [issue](https://github.com/cockroachdb/docs/issues/1688) to document this, but it looks like we already regenerated the full grammar for 1.1 and so [it's listed already](https://www.cockroachlabs.com/docs/dev/sql-grammar.html#reserved_keyword). Did we call this out as a backwards-incompatible change in the 1.1 alpha that introduced it?

**Comment by bdarnell** [comment]
We called it out as a new feature in the [20170720 release notes](https://www.cockroachlabs.com/docs/releases/v1.1-alpha.20170720.html), but not that it was a new reserved word.

**Comment by jseldess** [comment]
These get picked up when we regenerate the full grammar docs. But going forward, we should probably have a way to identify these and call them out as backward-incompatible changes. Any way to make sure that happens, @bdarnell, aside from asking devs to remember?

**Comment by bdarnell** [comment]
It's possible to automate, but would kind of be a pain. Developers and reviewers should generally be watching for these and call them out. The [blame view](https://github.com/cockroachdb/cockroach/blame/master/pkg/sql/parser/sql.y#L7499) of sql.y is useful for finding what's fallen through the cracks. It looks like we've added ROLE and WORK to the list during 2.0.
