### ISSUE TITLE
Remove `cockroach version` step from install instructions

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#1939]
Re: [Install CockroachDB](https://cockroachlabs.com/docs//v1.0/install-cockroachdb.html)

## Issue Description
Do we really need step 3?

We currently have a third step to the install: "Make sure the CockroachDB executable works" -- how often does this not work? and if it didnt work from here we don't have any other next steps to fix it. I'm thinking we can cut this step and make the third step the add to the email list one. At least AB test having 3 steps instead of 4.

**Comment by nstewart** [comment]
cc @dianasaur323 @kuanluo @jess-edwards

**Comment by sploiselle** [comment]
A more user-friendly solution than removing the step would be to write troubleshooting guides to help users with bungled installation. I have seen a large number of students at Hackathons and at the Local:Host events that only realized the installation "didn't work" when running `cockroach version`.

**Comment by nstewart** [comment]
OK -- I guess what I'm saying is right now that step isnt actionable

**Comment by jseldess** [comment]
@sploiselle, do you remember any details about why installation didn't work for those large number of students at the Hackathons? We rarely (if ever) get such feedback on community channels, and this page gets very few negative feedback submissions, so that detail is a bit surprising to me.

**Comment by jess-edwards** [comment]
@nstewart & @sploiselle 

Backing up a little bit to bring full context: 
The notion of altering / improving the install page came to light (not for the first time) when Nate said that for all the times he's visited the install page, he did not know there was a lead collection form on it. 

**The problem: Only 6% of downloaders give us an email address.**  

Observation / Proposition 1: The lead collection form appears below the fold. With the install instructions as simple as they, scrolling below the fold may no longer be necessary for many/most developers. Can the form be moved above the fold? 

Observation / Proposition 2: The lead collection form blends into the rest of the page. Can it be designed to be more attention-getting? 

Observation / Proposition 3 (and what I think Nate was suggesting in the original post): Are all of the instructions necessary now that install has been simplified? Can any instructions be removed?

**Comment by jseldess** [comment]
Thanks for the context, @jess-edwards. Our instructions are pretty streamlined right now. We could do things like remove the callout about other versions being available to move content up the page. But really, the OS buttons at the top and then the install method tabs below those are pushing the content down the page. I don't think that's a problem in terms of the instructional content, but I can understand that having the signup far down isn't ideal.

Can I ask? Is this page one of the more important touch points for getting users to sign up? Do we get more signups on our release notes?

**Comment by dianasaur323** [comment]
I think the fundamental issue here is that we need to capture more emails in order to better understand our user funnel. Although the way our installation page is designed is great from a docs perspective, we may have to add some marketing flair. Offering up a strawman proposal - perhaps it's time to consider moving install out of docs?

**Comment by nstewart** [comment]
+1 @dianasaur323! -- I think it's a bigger discussion that we should move out of this ticket (and I know @jess-edwards is thinking about this), but I think we should take a look at whatever the industry standard is and use that as a starting point. A cursory glance at a few other databases suggests download does indeed live outside of docs.

**Comment by jseldess** [comment]
Yes, would be great to look at what others do. At a glance, I'm seeing that projects that are NOT open source tend to have a separate download page with a gating step. Examples:

- VoltDB: https://www.voltdb.com/try-voltdb/
- MemSQL: http://www.memsql.com/download/

Mongo takes a different approach, where there's a [Download Center](https://www.mongodb.com/download-center?jmp=tutorials#atlas) (partially gated) as well as [installation docs](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/).
 
My instinct is that it is a bad idea to move this page away from all the rest of the content for which it is a prerequisite.

**Comment by kuanluo** [comment]
+1 to Jesse's point on Install is currently the pre-req, and regardless of where the download lives, there are many opportunities to make the email collection a lot more obvious and appealing. 

We should try those improvements and get the email signup numbers up (or see if they will) before moving download away from docs, which is a BIG change.

**Comment by jseldess** [comment]
@nstewart, if this conversation is continuing elsewhere, can you update this ticket with details or just let me know. Also, we need to focus this ticket back to something actionable. How about I repurpose this to track that fact that where we tell users "confirm the binary" (not only on this page), we eventually need some follow-up guidance in case of problems.

**Comment by sploiselle** [comment]
@jseldess @nstewart I retract my position; the terminal-centric install docs totally alleviate the problem I was thinking of. I'm +1 on removing `cockroach version` if it achieve's PDM's vision.

**Comment by jseldess** [comment]
Ok, I'll remove the `cockroach version` step from this page to at least inch the sign-up form up a bit. I think that it still adds value, in many situations, to have the user confirm the version of the binary just installed, though.
