### ISSUE TITLE
How to make portable binaries

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1943]
From the [forum](https://forum.cockroachlabs.com/t/feasibility-of-pre-built-oss-binaries/979/5):

You can make "portable binaries" with the following command:

~~~
build/builder.sh make buildoss TYPE=release-linux-gnu
~~~

@knz If you think we should integrate this into the docs, please leave open, otherwise, glad to have this closed.

**Comment by knz** [comment]
I think it's a good idea.

**Comment by bdarnell** [comment]
Yes, we should document both the `buildoss` target and the portable build methods somewhere (only `TYPE=release-linux-gnu` or should we document `TYPE=portable` too?)

**Comment by jseldess** [comment]
We added a callout about `buildoss`: https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html (build from source).
