### ISSUE TITLE
storage/ui: disk usage stats are confusing, especially in small/new clusters

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#1945]
Is this something that can be helped with documentation? Or with different UI design? Our UI throws  around storage-related numbers in multiple places that can differ widely from each other, and it's not at all clear to new users how they relate to each other.

Example thread: https://forum.cockroachlabs.com/t/needs-clarification-of-bytes-numbers-in-node-stats/949/5

**Comment by a-robinson** [comment]
The behavior of the disk usage if you leave a new cluster alone is also pretty weird. The "Live Bytes" metric grows continuously (as [documented in our FAQ](https://www.cockroachlabs.com/docs/stable/operational-faqs.html#why-is-disk-usage-increasing-despite-lack-of-writes)), and the actual number of bytes on disk grows at a similar rate until all of a sudden it comes crashing back down when some RocksDB compaction happens, compressing the data down to a small fraction of its previous size. That may also merit an explanation

**Comment by a-robinson** [comment]
And just to record for posterity, I did some measurements of the space taken up by timeseries data on a local 3 node cluster running cockroach-v1.1-beta.20170928 on my macbook.

After about 25 minutes the node was at 25.8 MiB of Live Bytes and 174 MiB of "disk" usage, which was really just memtables. It then flushed the data to on-disk sstables, and the disk usage dropped down to 7.2 MiB (and by that time the Live Bytes had grown to 27.3 MiB, so some of that may have been in uncompressed memtables from new insertions). After another 25 more minutes, the Live Bytes was at 52.6 MiB and another sstable flush brought the disk usage from 178.4 MiB down to 7.7 MiB. That's some very good compression. I'll continue tracking for a while longer and open a non-docs issue if it looks like the resulting compressed disk usage of a long-running cluster would be too high.

**Comment by a-robinson** [comment]
Resolution to the experiment: after a few more hours, it has 19.28 MiB on disk for 209.9 MiB of Live Bytes, which roughly matches the amount of compression seen in the forum post.

**Comment by petermattis** [comment]
I think what we're seeing is that the estimated data size for "merge" operations (which are used by timeseries storage) are quite inaccurate. Not sure what can be done at this point. Changing the low-level code is very difficult. Perhaps we can add an adjustment factor to the `LiveBytes` metric for timeseries ranges.

**Comment by jseldess** [comment]
@Amruta-Ranade, @piyush-singh, any thoughts on this? I can't see any specific docs actions here.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
