### ISSUE TITLE
Schema changes blocking on table leases to expire is confusing

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#1950]
There's an effect in our system where schema changes that normally return successfully very quickly can be arbitrarily delayed behind other schema changes or while waiting for table leases to be released. This is confusing behavior that has made users think their cluster isn't working.

We should include something in our docs about this topic to help explain things, perhaps in the SQL or Operational FAQ or on the DDL statement docs themselves. We have plans to improve this (https://github.com/cockroachdb/cockroach/issues/18983), but those improvements won't be available until 1.2 at the earliest.

I don't understand the finer details of when this does or doesn't happen well enough to feel comfortable documenting it or providing the technical detail, so assigning to @vivekmenezes.

**Comment by jseldess** [comment]
Thanks for reporting this, @a-robinson.

**Comment by rmloveland** [comment]
@vivekmenezes can this be closed since https://github.com/cockroachdb/cockroach/issues/18983 was merged?  Or is there still some documentation work needed here?

**Comment by vivekmenezes** [comment]
This is fixed. Thanks!
