### ISSUE TITLE
Identify important third-party integrations requiring documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1962]
To date, our docs only talk about integrating prometheus/grafana/alertmanager for external monitoring. Those docs need to be improved, but we should also identify the most important other third-party integrations requiring some form of mention/tutorial in our documentation.

- Lightstep

@knz, @andreimatei, @mberhault, @bdarnell, @nstewart, @dianasaur323, please add any ideas you have. 

Also, perhaps we should categorize these (monitoring, sql tools, tracing)?

**Comment by bdarnell** [comment]
- zipkin
- systemd

**Comment by jseldess** [comment]
Closing this in favor of https://github.com/cockroachdb/docs/issues/2979.
