### ISSUE TITLE
Add sql diagram generation to release process

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#197]
@mjibson, should we regenerate our sql diagrams as a part of our standard release process? If so, it'd be great if you would add instructions on how to do that to the **Documentation** portion of the Release Process: https://github.com/cockroachdb/cockroach/wiki/Release-Process

**Comment by mjibson** [comment]
Done.

**Comment by jseldess** [comment]
Thanks, @mjibson! It'd be great to think about how this could eventually become an automated part of the docs build process.
