### ISSUE TITLE
Deploy CockroachDB on Google Cloud Platform GCE Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1988]
Re: [Deploy CockroachDB on Google Cloud Platform GCE](https://cockroachlabs.com/docs//v1.0/deploy-cockroachdb-on-google-cloud-platform.html)

## Issue Description

TCP health check on 26257 is more reliable indicator of database health than the admin port. 

## Suggested Resolution 

Investigate changing recommendation to monitor port 26257.

**Comment by mjibson** [comment]
Note: the health check on port 26257 instead of https://:8080/health was the best opinion that @a-robinson and I had when debugging this problem. It is possible that 8080/health is better because the /health endpoint can check more things than just 26257 can.

**Comment by dianasaur323** [comment]
That's troubling. We've been suggesting users to use the relatively unknown health port since around 6 months back with our first couple users... we haven't ever really tested that though. Perhaps @mberhault might have some thoughts?

**Comment by mjibson** [comment]
Don't worry. There's a really high chance I'm wrong about 26257 and what you've been recommending is better.

**Comment by mberhault** [comment]
I think `:8080/health` is still the right endpoint although we may want to augment it to also check for health of the pg port.
Checking 26257 at the tcp level only checks that the port accepts new connections, saying nothing else about the health of the server.

The issue of exhausted file descriptors should be handled regardless, as a badly configured client (or proxy, scrapper, monitoring, or anything else hitting :8080) could cause issues.

**Comment by bdarnell** [comment]
In 1.0, checking that we accept tcp connections on 26257 would have been safe. In 1.0, it's not true because we open that port earlier to support the `init` command. For 1.1 the health check should either use the health endpoint on the HTTP port or complete a postgres handshake and run a `SELECT 1` query.

**Comment by mjibson** [comment]
Ok. Thanks for the information. Closing because nothing needs to change.
