### ISSUE TITLE
cockroachdb-architecture.html 404s

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2000]
## Issue Description
The first link when googling cockroachdb architecture 404s: https://www.cockroachlabs.com/docs/stable/cockroachdb-architecture.html

![image](https://user-images.githubusercontent.com/894257/31617463-45721e04-b25d-11e7-89ac-b3e4e7617e96.png)

**Comment by sploiselle** [comment]
@benesch I thought this would get caught by the redirect for some reason. How should we handle removing a page and redirecting it to something within a subdirectory? `redirect_from: ../cockroachdb-architecture.html`?

**Comment by benesch** [comment]
Yep! Though I'd recommend just using an "absolute" path (i.e., where a leading `/` means `cockroachlabs.com/docs/`) rather than `..`. This should do it:

```yml
key: cockroachdb-architecture.html
redirect_from: [index.html, /cockroachdb-architecture.html]
```
