### ISSUE TITLE
Role based access control (RBAC)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2007]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rechQFMnSgmcC0ld9

RFC: [20171220_sql_role_based_access_control](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171220_sql_role_based_access_control.md)

Tracking issue: https://github.com/cockroachdb/cockroach/issues/20371 (links to all PRs)

**Comment by mberhault** [comment]
Taking over this one for now. I'll have some draft docs to work from.

**Comment by jseldess** [comment]
From release notes:
> The new `SHOW GRANTS ON ROLE` statement and `pg_catalog.pg_auth_members` table lists role memberships. https://github.com/cockroachdb/cockroach/pull/22205 https://github.com/cockroachdb/cockroach/pull/21780

**Comment by mberhault** [comment]
@jseldess: this is ready any time. The draft docs in #2433 are a start, but obviously nowhere near enough.

**Comment by jseldess** [comment]
Thanks, @mberhault. It's one of the next projects on my list.

**Comment by jseldess** [comment]
@lhirata, best place to start here is a look at marc's draft PR and at the RFC. Then we could sit down and sketch out all new/changed pages. Thanks for taking this on!
