### ISSUE TITLE
PostgreSQL <> CockroachDB schema compatibility tool

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2009]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/reczm4YFYSmKmzwSV

PRs:

**Comment by cuongdo** [comment]
cc @mjibson, friendly reminder that you're assigned to this roadmap item

**Comment by jseldess** [comment]
This is just internal exploration. No docs work needed at this time.
