### ISSUE TITLE
[MH] Query optimizer hints/ extensible optimizer hinting syntax

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2012]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rechsShAEmvPVOzD4
PM: @awoods187 
Eng Partner: @knz

**Comment by lhirata** [comment]
Not in next (June 4) alpha

**Comment by jseldess** [comment]
Moved to 2.2.
