### ISSUE TITLE
SQL sequences

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2014]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recpKacCHw2xQwqzn

**Comment by vilterp** [comment]
Hi Jesse, getting started on implementing this (it will take a few PRs): here's a tracking issue so you can see the progress https://github.com/cockroachdb/cockroach/issues/19723 (it also links to the RFC). Let me know how I can help documenting this once it gets a little further on.

**Comment by jseldess** [comment]
Thanks for the heads up, @vilterp.

**Comment by jseldess** [comment]
@vilterp, `SEQUENCES` is going to be Lauren's starter docs project! She's going to be reaching out sometime next week for an intro.

**Comment by vilterp** [comment]
Great! There are definitely plenty of little details to document — most of which are similar to Postgres at least. Their docs are here as a reference:

- `CREATE SEQUENCE`: https://www.postgresql.org/docs/current/static/sql-createsequence.html
- sequence functions: https://www.postgresql.org/docs/10/static/functions-sequence.html

**Comment by lhirata** [comment]
closing this issue - new issues will be opened for remaining sequence docs.
