### ISSUE TITLE
Row-level CASCADE (ON DELETE/UPDATE)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2015]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recrbVp1XXdE45pFn
  
PRs:
- [sql: Adds ON DELETE CASCADE for foreign key references](https://github.com/cockroachdb/cockroach/pull/20064)
- [sql: add support for ON UPDATE CASCADE for foreign key references](https://github.com/cockroachdb/cockroach/pull/21329)

**Comment by jseldess** [comment]
@lhirata, this feature is getting close to QA and is important. I'd love for you to take it on.

**Comment by jseldess** [comment]
@BramGruneir, can you please let @lhirata know when it's ready to be tested/documented. Also, would be great if you could update the issue description with links to the relevant PRs.

**Comment by BramGruneir** [comment]
@mjibson is the QA buddy for this feature.
Here is the [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171201_cascade.md).

The main PRs: 
* ON DELETE CASCADE #20064
* ON UPDATE CASCADE #21329
* ON DELETE SET NULL
* ON UPDATE SET NULL
* ON DELETE SET DEFAULT
* ON UPDATE SET DEFAULT
