### ISSUE TITLE
inet data types

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2016]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rec591c0mW53jVnYZ

PRs: 
- [sql: Add INET column type and IPAddr datum](https://github.com/cockroachdb/cockroach/pull/18171)
- [sql: Add INET type built-in functions](https://github.com/cockroachdb/cockroach/pull/18585)

**Comment by lego** [comment]
I also want to point out that there are some unfinished parts at https://github.com/cockroachdb/cockroach/issues/18847, the issue goes into the details but operators on INET types were not done with the initial round. They will be done before 1.2, but not immediately.
