### ISSUE TITLE
Support SQL schemas separate from databases (pg compatibility)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2017]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recmkB89sOzx3FDw1

Dev contacts:
- @knz 
- @jordanlewis

**Comment by jseldess** [comment]
From @rytaft:

During QA for #22753, I discovered that many docs pages need to be updated. For example, SHOW DATABASES no longer shows crdb_internal, information_schema and pg_catalog. Any page referencing those virtual schemas will likely need to be updated.

This is also related to #22964, which added the SHOW SCHEMAS command.

**Comment by knz** [comment]
I'd like to contribute to this during docs fixit day

**Comment by jseldess** [comment]
Excellent. Thank you, @knz. I'll assign it to you and add the fixitday label.
