### ISSUE TITLE
explicit lock syntax (SELECT FOR {SHARE,UPDATE} {skip locked,nowait})

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2019]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recfNsXeqgwr1Uv9a

PRs:
- [sql: Support SELECT FOR UPDATE SQL syntax](https://github.com/cockroachdb/cockroach/pull/19650)

**Comment by jseldess** [comment]
@rytaft, this is the docs for `SELECT FOR UPDATE`. I'll try to keep tracking progress, but it'd also help if you could let me know when the feature is ready for testing/docs drafting.

**Comment by rytaft** [comment]
Great.  I think the RFC should be done this week, and hopefully the code will be finished next week or the week after.  I'll keep you posted.  Thanks!
