### ISSUE TITLE
Partitioning (aka geo-partitioning)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2022]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recXpHJaSuHXF4bc3
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170208_sql_partitioning.md

PRs:
- [partitioning: PARTITION BY syntax + PartitioningDescriptor proto + validatePartitioning and tests](https://github.com/cockroachdb/cockroach/pull/19315)
- [sql: support DEFAULT and MAXVALUE in PARTITION definitions](https://github.com/cockroachdb/cockroach/pull/19420)
- [config: split subzones](https://github.com/cockroachdb/cockroach/pull/19551)

**Comment by jseldess** [comment]
@Amruta-Ranade, this forum post on partitioning might help us deal with confusions around terminology: https://forum.cockroachlabs.com/t/partitioned-tables/724/12

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/2482
