### ISSUE TITLE
ORMs and Partitioning via load balancing

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2023]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recsBPdAkc9LSSdCy

**Comment by jseldess** [comment]
Not tied to the 2.0 release, so moving this into the 2.1 timeframe.

**Comment by Amruta-Ranade** [comment]
As discussed with @awoods187, this is not a roadmap feature for 2.1. Labeling it as "Product" to help decide priority.

**Comment by jseldess** [comment]
Thanks, @Amruta-Ranade. I don't think this is a priority for 2.1, and we haven't heard requests for this guidance, so I'm changing this to later.
