### ISSUE TITLE
SQL performance best practices

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2027]
For 1.2, we want to add developer guidance on getting the best SQL performance out of CockroachDB. 

Primary resources: [Robert’s techniques](https://docs.google.com/presentation/d/1G68GQhvMMkCxrBiNHgLOGZL9hqZ-4VpnfjK4ZH-0V_M/edit#slide=id.g2668cfb1b7_1_0)

Other topics that should be covered:
- Overall data model best practices
- Secondary indexes
- Performance implications of constraints
- Merge JOINs
- Interleaved tables/indexes (interleaved indexes must still be documented)
- Data model best practices

**Comment by sploiselle** [comment]
How about adding these?

- Column families
- Geolocation/follow the sun
