### ISSUE TITLE
Track and report in-flight query execution stats

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2039]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recnrbh1GsETw2E7D
PM: @piyush-singh 
Eng Partner:

**Comment by lhirata** [comment]
Will check back with @asubiotto closer to alpha (june 4)

**Comment by lhirata** [comment]
`EXPLAIN ANALYZE (DISTSQL)` added to June 4 alpha and ready to be documented

**Comment by jseldess** [comment]
@lhirata, @piyush-singh, is that statement just one part of this roadmap item, or is it everything for 2.1?

**Comment by lhirata** [comment]
The current alpha only has the statement + the number of rows read from disk at the start of the flow. More stats will be added.

Related issue: https://github.com/cockroachdb/cockroach/issues/19476

**Comment by jseldess** [comment]
@lhirata, @Amruta-Ranade mentioned that there will be an admin ui screen with query stats. I assume the screen will be based on these underlying sql statements. It'd be great if you could check on the status of these for the upcoming alpha and sync with Amruta about how to get it documented. Documenting at the SQL level is probably primary.

**Comment by jseldess** [comment]
I just got confirmation from @piyush-singh that this roadmap item tracks the work Alfonso has done around annotating DistSQL Plans with statistics with query tracing turned on (running EXPLAIN ANALYZE via the CLI). For 2.1, DistSQL plans will not be in the UI, so this is purely @lhirata's work.
