### ISSUE TITLE
Node status should work when majority of nodes are down

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2041]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recRgfUqpnWKG4OrY
PM: @piyush-singh  
Eng Partner: @petermattis

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/28249

From release notes:
> The `cockroach node status` command now works on unavailable/broken clusters. [#28249][#28249] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
This is ready.

**Comment by Amruta-Ranade** [comment]
As discussed on Slack yesterday, I am unsure if we should document the updated `cockroach node status` command until we clarify the terminology (`available` vs. `live`). 

As it stands now, documenting it would be something like: "You can check the status of the cluster if a majority of the nodes are down as long as your `node status` command points to a node that is up. The `node status` output might indicate that the nodes in the cluster are not `live` if the down nodes contain replicas needed to provide quorum for critical system ranges."

Or as Arjun put it: "You can check the status of the cluster even if majority of the nodes are down as long as you get lucky and 2 of the 3 nodes that are randomly selected to be 'required' and totally out of your control are up"

@piyush-singh I need help figuring this out.

**Comment by petermattis** [comment]
> Or as Arjun put it: "You can check the status of the cluster even if majority of the nodes are down as long as you get lucky and 2 of the 3 nodes that are randomly selected to be 'required' and totally out of your control are up"

This isn't quite accurate. If you have a 3 node cluster and 2 nodes are down, you can run `node status` against the 3rd node and you will get some output. Confusingly, the output will report all 3 nodes as `is_live=false`, but note that this is a significant improvement over the prior behavior where `node status` would hang indefinitely. I'm going to see about improving this further. Also note that `node status` will never be able to provide output if you try to connect to a down node.

**Comment by Amruta-Ranade** [comment]
Note to self: Follow-up PR for reference: https://github.com/cockroachdb/cockroach/pull/30081

**Comment by jseldess** [comment]
More related release notes:

> PR: https://github.com/cockroachdb/cockroach/pull/30268
>
> Improved the output of [`cockroach node status`](../v2.1/view-node-details.html) to include separate `is_available` and `is_live` columns. [#30268][#30268] {% comment %}doc{% endcomment %}
