### ISSUE TITLE
Allow users to view query plans in the Web UI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2044]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recijX3LQyP2EvCF8
PM: @piyush-singh 
Eng partners: @couchand, @vilterp 

PRs:

**Comment by jseldess** [comment]
This has been moved to 2.2.

**Comment by Amruta-Ranade** [comment]
From @celiala 's email:

**Logical Plans: Cluster Settings**

sql.metrics.statement_details.plan_collection.enabled
- Boolean, default is true
- Specifies whether to periodically save a logical plan for each fingerprint

sql.metrics.statement_details.plan_collection.period
- Duration, default is 5 minutes
- The time until a new logical plan is collected (e.g. how often we sample a new logical plan for a particular fingerprint)

**Comment by Amruta-Ranade** [comment]
The logical plan is the recent sample but the latency is an average of all SQL statements forming the fingerprint.

**Comment by Amruta-Ranade** [comment]
Reference read: https://www.depesz.com/2013/04/16/explaining-the-unexplainable/

**Comment by jseldess** [comment]
@Amruta-Ranade, can you give a quick update on this project? I know it's at least partially done.

**Comment by Amruta-Ranade** [comment]
Yes, the UI docs are up-to-date with the current implementation. Since I worked on this issue for an alpha release, I wanted to keep the issue open for tracking purposes (in case we tweak the implementation before the final release).

**Comment by Amruta-Ranade** [comment]
Closing this issue since I am not anticipating any doc changes for logical plans for 19.1. Will open a follow-up issue in case something comes up.

**Comment by celiala** [comment]
Hi @Amruta-Ranade  -

Fyi, the functionality will be the same, but based on customer feedback we're doing one more cosmetic change -- see design prototype below:

![logicalPlan-05-cautionExpand](https://user-images.githubusercontent.com/3051672/54754125-28612980-4bb9-11e9-90d2-bb6434a22ead.jpg)

cc @piyush-singh

**Comment by Amruta-Ranade** [comment]
Yes, but I checked the Statements page doc and do not think there's a doc impact.

**Comment by celiala** [comment]
Ah, agreed that there's no doc impact for the cosmetic change :)
