### ISSUE TITLE
Track/maintain table content statistics

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2050]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recGxsQAG6xPXQtep

PRs:

**Comment by jseldess** [comment]
Note from @RaduBerinde:

> We will have SQL commands to inspect statistics as well as commands to force a refresh of statistics on a certain table or database. Though those will only be worth documenting once we have an optimizer that actually uses the statistics.

**Comment by RaduBerinde** [comment]
We will also need to document when and how statistics are calculated automatically, and what "triggers" the system to start collecting a certain statistic.

**Comment by jseldess** [comment]
Moving to 2.1 for docs work, since the user impact depends on optimizer work.

**Comment by jseldess** [comment]
No docs needed at the moment.
