### ISSUE TITLE
Faster INSERT into tables with multiple indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2053]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rec072UNSPAh5TjW4

PRs:

**Comment by cuongdo** [comment]
@jordanlewis This was already assigned to you during roadmapping for the next release. Is this still being worked on?

**Comment by jordanlewis** [comment]
Not actively, but I'm planning on doing something on this before next release.

**Comment by jseldess** [comment]
No docs work in 2.0. Will open a new issue for 2.1 follow-up work: https://airtable.com/tblD3oZPLJgGhCmch/viwfInyLulgiIgaS7/recTmXDAdqwM5j7K0.
