### ISSUE TITLE
Support materialized computed columns for primary keys

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2054]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recz17DReeMym5Wyv

PRs:

**Comment by spencerkimball** [comment]
Note that this work should include an update to `information-schema.md` to link from the `GENERATION_EXPRESSION` column in the `information_schema.columns` view to whichever document is created to document the computed columns feature described here.
