### ISSUE TITLE
Clarify and restrict the txn semantics of statements for bulk I/O

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2056]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recNBM4ZwFJxf258L

PRs: [sqlccl: disallow bulk IO statements in txn](https://github.com/cockroachdb/cockroach/pull/21488)

**Comment by Amruta-Ranade** [comment]
@dt What are the consequences if the user includes the bulk IO statements within a transaction? Will they get an error? Is this related to performance?

**Comment by dt** [comment]
BACKUP, RESTORE and IMPORT will all refuse to run in an open sql txn.
