### ISSUE TITLE
Architecture: command queue

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#2057]
When a leaseholder proposes a write to the Raft leader, the command goes into the Command Queue; the Leaseholder will then not serve reads for involved keys until it gets a response for the proposed write (I believe).

@vilterp Saw that you recently added a debug page for the command queue––are you comfortable with helping me add some detail about it to the [architecture docs](https://www.cockroachlabs.com/docs/v1.1/architecture/overview.html)?

**Comment by vilterp** [comment]
Sorry, was on vacation when you posted this and forgot to respond. Definitely happy to help, although I don't know as much as @nvanbenschoten and others.

**Comment by nvanbenschoten** [comment]
@sploiselle I'm happy to help as well.

> When a leaseholder proposes a write to the Raft leader, the command goes into the Command Queue

The command will actually be in the CommandQueue at the time that the leaseholder proposes the write. Commands are added to the CommandQueue as soon as they reach the leaseholder. They then wait on all prerequisite commands (for instance, writes to the same keys) that are ahead of them in CommandQueue. When a given command no longer has any prerequisite commands in the queue, it will begin executing itself (while remaining in the queue). It's at this time that a write will be proposed to the Raft leader. Once the command has finished executing, it can then be removed from the CommandQueue, freeing up all dependents to begin executing if they don't also depend on any other commands.

**Comment by sploiselle** [comment]
Closed by #4349
