### ISSUE TITLE
ui: update Replicas graph title to Replica Quiescence

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2063]
PR: https://github.com/cockroachdb/cockroach/pull/19224

**Comment by jseldess** [comment]
@Amruta-Ranade, this change just renames the [**Replicas** graph on the Replication Dashboard](https://www.cockroachlabs.com/docs/stable/admin-ui-replication-dashboard.html#replicas) to **Replica Quiescence**. 

Once I've created a 1.2 docs version (soon), can you update the 1.2 version of the Replication Dashboard page?

**Comment by Amruta-Ranade** [comment]
@jseldess Sure.
