### ISSUE TITLE
kv/storage: re-enable meta2 splits (again), replace RangeLookupRequest

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2065]
PR: https://github.com/cockroachdb/cockroach/pull/18970

@nvanbenschoten, is it ok to resolve [this limitation](https://www.cockroachlabs.com/docs/stable/known-limitations.html#maximum-cluster-size) in the 1.2 docs now?

**Comment by nvanbenschoten** [comment]
Yes, this should no longer be a limitation.
