### ISSUE TITLE
sqlccl: support RESTORE DATABASE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2067]
PR: https://github.com/cockroachdb/cockroach/pull/19176

From @dt:
> previously you had to recreate the database, then restore the tables
> now you can restore the whole thing

Once we have 1.2 docs, we'll need to update `restore.md`.

**Comment by jseldess** [comment]
@Amruta-Ranade, this isn't a roadmap item, but it is a change to one of your areas (backup/restore), so I'm assigning to you.

**Comment by jseldess** [comment]
This shows up in the [v1.2-alpha.20171026](https://www.cockroachlabs.com/docs/releases/v1.2-alpha.20171026.html) release notes.

**Comment by jseldess** [comment]
A related bug fix: `RESTORE DATABASE` is now allowed only when the backup contains a whole database.

PR: https://github.com/cockroachdb/cockroach/pull/20023

**Comment by jseldess** [comment]
Copying over from https://github.com/cockroachdb/docs/issues/2410:

From @dianasaur323:
> We just implemented RESTORE DATABASE, which allows users to restore even if the database does not exist. We need to change our code examples going into 2.0.

From @dt:
> Indeed, I think BACKUP DATABASE and RESTORE DATABASE should be our default examples except where we specifically want to show specific tables.

**Comment by Amruta-Ranade** [comment]
- "Restore All Tables and Views from a Database" > "Restore a database"
- "RESTORE bank.* FROM 'gs://acme-co-backup/database-bank-2017-03-27-weekly';" > "RESTORE DATABASE bank FROM 'gs://acme-co-backup/database-bank-2017-03-27-weekly';"
- Add note "RESTORE DATABASE can only be used if the entire database was backed up."
