### ISSUE TITLE
Reduce size of OS tabs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2079]
On our [installation page](https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html), we're trying to move the instructional content further up the screen. We've already made some changes in https://github.com/cockroachdb/docs/pull/2025. The next step is to reduce the size of the OS tabs at the top of the page. Here's a design suggestion from @kuanluo:

![pasted image at 2017_10_18 11_01 am](https://user-images.githubusercontent.com/15893490/31788840-084868ac-b4de-11e7-94ee-114a488b7628.png)

Note that these OS tabs appear on the following pages as well:
- https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html
- https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#file-descriptors-limit

**Comment by kuanluo** [comment]
Thank you, @jseldess for documenting this and context. Assigning to @j-low.

**Comment by jseldess** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/2101.
