### ISSUE TITLE
Build a PHP App with CockroachDB Doc Update

### ISSUE THREAD

**Issue by bluej130** [cockroachdb/docs#2089]
#631 - determine how the listed library accepts certs/keys. parameter names, file formats:

Here is a quick secure example for PHP if needed.

Current insecure example:
```
$dbh = new PDO('pgsql:host=localhost;port=26257;dbname=bank;sslmode=disable',
    'maxroach', null, array(
      PDO::ATTR_ERRMODE          => PDO::ERRMODE_EXCEPTION,
      PDO::ATTR_EMULATE_PREPARES => true,
  ));
```

Secure example:
```
$dbh = new PDO('pgsql:localhost=host;port=26257;dbname=bank;sslmode=require;sslcert=[path]/client.maxroach.crt;sslkey=[path]/client.maxroach.key;sslrootcert=[path]/ca.crt;',
    'maxroach', null, array(
      PDO::ATTR_ERRMODE          => PDO::ERRMODE_EXCEPTION,
      PDO::ATTR_EMULATE_PREPARES => true,
  ));
```

**Comment by jseldess** [comment]
Thanks very much for the contribution, @bluej130. We'll take a look soon.

**Comment by jseldess** [comment]
Copied this guidance over to the main tracking issue: https://github.com/cockroachdb/docs/issues/631. This work will likely happen for the 2.1 release.
