### ISSUE TITLE
Link current release binary to "latest"

### ISSUE THREAD

**Issue by uptimeDBA** [cockroachdb/docs#209]
When a new binary release is built, can we create a link called (something like) cockroach-beta-latest.linux-amd64.tgz pointing to the current beta release. It would enable easy scripted downloads of the latest version and we could include the link in the documentation so it's doesn't have to be updated every time. @jseldess Including @bdarnell as Ben did the latest beta.

**Comment by mberhault** [comment]
I think a redirect may be preferable, but the point still stands, having a way of fetching the latest version easily would help a lot. I'll see what I can do. Our mix of S3 + cloudfront to the binaries restricts us somewhat.

**Comment by uptimeDBA** [comment]
It appears that `wget https://binaries.cockroachdb.com/cockroach.linux-amd64.tgz` will retrieve the latest version.
```
[roachdb@base ~]$ cockroach version | head -3
Build Tag:   beta-20160407-122-g166b7b9
Build Time:  2016/04/11 22:08:40
Platform:    linux amd64
```

**Comment by mberhault** [comment]
yes, but those are built for every merge to master, and I'll probably be turning those off soon.
Instead, I'll add something that points to the latest beta release.

**Comment by sploiselle** [comment]
@arjunravinarayan Would love to get something like `cockroach-beta-latest.[OS slug].tgz`; you'd mentioned you might be able to take care of this simply. Still think that's the case?

**Comment by arjunravinarayan** [comment]
@sploiselle, handing this off to @mberhault as I'm currently swamped right now. I still think it should be relatively simple - we just need to add a step in our beta release process to update a single URL to point to the latest binary at the very end.

**Comment by BramGruneir** [comment]
Wow.  I was just updating my personal fork.  Not sure if this should be closed or not.

**Comment by mberhault** [comment]
it'll get closed when master gets merged back into develop

**Comment by jseldess** [comment]
I think this is done, so I'm closing. @mberhault, please reopen if I'm wrong.
