### ISSUE TITLE
import: Ensure proper encoding for AWS credentials

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#2090]
From [the forum](https://forum.cockroachlabs.com/t/error-doing-import-from-aws/1034/2):

> One gotcha with specifying AWS credentials as query parameters is that they often contain non-URL-safe characters that need to be URL-encoded. In Go, you could use url.QueryEscape; in JavaScript, you could use encodeURIComponent.

h/t @benesch

**Comment by jseldess** [comment]
Called out in docs now: https://www.cockroachlabs.com/docs/stable/import.html#import-file-urls.
