### ISSUE TITLE
Recommend host pinning in Docker Swarm orchestration guide

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#2098]
I've done some more playing around with our secure Swarm guide recently, and the biggest issue with it is that it's far too easy for multiple CockroachDB containers to end up on the same host machine. That's (1) not great for performance (2) really bad for availability, since that one node going down can take the cluster offline. We can't easily fix it in our generic setup instructions for secure mode (we could probably fix it for insecure mode, a la cockroachdb/cockroach#17133) due to Docker's lack of support for strong anti-affinity between different services (moby/moby#26259).

There are a few possible workarounds, but honestly in most production deployments that are using local storage I'd most strongly recommend pinning each Cockroach instance to a particular host. The downside is that the commands would no longer be completely copy-and-pasteable since the hostname constraints will depend on the hostnames being used in the user's cluster.

If that's not an option for whatever reason, or if you're using more persistent storage than just local disk, some alternative solutions would be to:

* Specify `--reserve-cpu` and `--reserve-memory` on the services such that they reserve more than half of a machine's resources, preventing more than one from being put on a host at the same time. This is tough for us to do in a generic way in our docs, since we have no way of knowing machine specs.
* Assign a host port to each service, such that only one can be on a host at any given time. This could mean using the host ports for cockroach's two ports (26257, 8080) or just picking a dummy port as a workaround (e.g. `-p mode=host,published=12345,target=12345`). This could be done more generically in our docs.

Assigning to @jseldess for now, but if you can't get to this for a while I can do it sometime.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
