### ISSUE TITLE
Encourage length limits on string columns

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#2106]
Ben Darnell (bdarnell) commented:

This issues was initially about discouraging length limits. At this point, we should encourage them. From [~accountid:5bd8aaa8a86b3349680e488c]: 

{quote}This has actually become bad advice in the years since it was filed. The reason to discourage length limits was that we didn't support changing them after the initial creation, but we now support that. I would now say that we should *encourage* setting of appropriate length limits, because bad things can happen if a very large value appears in an indexed column.{quote}

The original description has been moved to a comment. 

Jira Issue: DOC-130

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!

**Comment by bdarnell** [comment]
This has actually become bad advice in the years since it was filed. The reason to discourage length limits was that we didn't support changing them after the initial creation, but we now support that. I would now say that we should *encourage* setting of appropriate length limits, because bad things can happen if a very large value appears in an indexed column.
