### ISSUE TITLE
no c# Client Driver?

### ISSUE THREAD

**Issue by yruson** [cockroachdb/docs#2108]
no c# Client Driver?

**Comment by jseldess** [comment]
@yruson, we working on one at this very moment. Hopefully, we should have a tutorial with code samples published soon. You can take an early look here if you like: https://github.com/cockroachdb/docs/pull/1991

**Comment by jseldess** [comment]
cc: @BramGruneir

**Comment by jseldess** [comment]
@yruson, we just added a tutorial on [building a C# app with CockroachDB](https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html). Please take a look and let us know if you have any questions.
