### ISSUE TITLE
sql: add missing columns to information_schema.table_constraints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2113]
PR: https://github.com/cockroachdb/cockroach/pull/19466

**Comment by jseldess** [comment]
Need to update https://www.cockroachlabs.com/docs/v2.0/information-schema.html#table_constraints.

**Comment by lhirata** [comment]
Seems to have been updated already. `table_catalog`, `is_deferrable`, and `initially_deferred` listed.
