### ISSUE TITLE
Code blocks: Improving syntax highlighting

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/docs#2114]
@jseldess originally posted in this [airtable task](https://airtable.com/tblFbdnCTXgR9xAjG/viwHgKuTrS4RlVx87/recDGIBtotLaw22Pe): 
 
1. Rethink the overall contrast of code blocks. Our pages have a white background. Should the blocks be light grey, as they are now? Should they rather be dark (more contrast), for example, https://developer.github.com/v3/guides/getting-started/ and https://devcenter.heroku.com/articles/getting-started-with-python#deploy-the-app? Even better, should we give users the option to choose light or dark, for example, https://developers.google.com/google-apps/tasks/quickstart/python#step_2_install_the_google_client_library (hover over block and change the color theme). 

2. Are we highlighting syntax in a helpful way for SQL, shell, and the various languages we have in examples?

3. Should we include line numbering in cases where we're showing the contents of a file?

4. Should code blocks have a "header" identifying the type of sample or the name of the file, e.g., https://stripe.com/docs/libraries#java-library?

Some explorations below:
- Light/dark background with line numbering
![image](https://user-images.githubusercontent.com/1486483/32181085-f085900c-bd69-11e7-8d7b-bba5feb6cf2d.png)

- Light/dark background with file types on top
![image](https://user-images.githubusercontent.com/1486483/32181116-02e4ba48-bd6a-11e7-824c-d6e739aea3d3.png)

- Option to allow users to pick color modes
![image](https://user-images.githubusercontent.com/1486483/32181181-21419952-bd6a-11e7-884d-30713a637fc2.png)

The full iteration can be view on InVision here: https://invis.io/QBE7BYFDK Commenting directly on InVision welcome!

cc: @Amruta-Ranade @sploiselle @jseldess

**Comment by sploiselle** [comment]
OMG 😍 

My one comment is that I think the dark background could use a brighter blue for strings and a brighter purple for comments (i.e. more contrast).

I also _love_ the idea of letting users choose the mode. I know that some people with different vision abilities bemoan the fact that they're forced to read code with a specific color scheme.

Such great work, @kuanluo!

**Comment by bdarnell** [comment]
My 2¢: I prefer light backgrounds; we don't need the code samples to be *too* differentiated from the main text. Some of the syntax highlight color selections are too low-contrast: the gray comments on the light background and the two shades of blue in the dark background. Maximizing contrast between foreground and background is most important thing; if we choose high-contrast colors we may not need to provide multiple options. 

For the other questions: I generally like line numbers as long as they don't show up if you copy and paste. I wouldn't include a file name/type header most of the time (especially for terminal/shell snippets), but sometimes it's helpful.

**Comment by j-low** [comment]
I concur with @bdarnell re: optimizing contrast.  I personally prefer dark backgrounds however that is usually only in my text editor while working to minimize eye strain.  I think that benefit goes away when the rest of the page is light in background color.  

Also, if we opt to support theme toggling that experience might get to be a bit disruptive to the user (i.e. reselecting the theme for each code snippet).  Typically when I arrive at a docs page my flow is to quickly scan for the information I'm seeking and then dig into details once I've zeroed in on the right blocks of information.  I don't know that I would find theme toggling useful unless I were both a power user and also had the ability to have my preference remembered between sessions.

Re: line numbers: I think we should have them but definitely agree the crux is to avoid having them included in copy/paste ops.

**Comment by sploiselle** [comment]
@j-low w/r/t toggling––could we immediately toggle all on-page code snippets to the user's preference, and then store the preference in their cookie?

**Comment by jseldess** [comment]
Looking awesome, @kuanluo. 

- I agree with everyone that contrast is key. Based on the variety of internal perspectives, I don't think we can predict what "theme" the majority of users will prefer, so I like the toggle if, as @sploiselle suggest, we have a way to remember a user's preference.
- I agree with @bdarnell that file name/type headers should be optional. Would be useful when code samples are exposing a file. 
- I also think it's best to make line numbers optional; feels meaningful for files but not for sql/shell samples.

**Comment by kuanluo** [comment]
Thanks for the feedback, all! Decisions/next steps:

- I will take another stab at refining the light code blocks, so there's more contrast.
- If we have a way to remember user's preference, let's do the toggle. Otherwise, we can stick with light background only. 
- Line numbers and file name/type should be built with ability to show/turn off. 
- Line numbers will not be copied with the code sample. 

@j-low @jseldess and I will sync on implementation.

**Comment by j-low** [comment]
@sploiselle re: editor preference in cookie: yes that would certainly be a possibility.

**Comment by jseldess** [comment]
@j-low, here are a few pages with good sql and cli code blocks:

- SQL: [`SELECT` examples](https://www.cockroachlabs.com/docs/stable/select.html#examples)
- CLI: [`cockroach zone` examples](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#scenario-based-examples)

**Comment by kuanluo** [comment]
Thanks for the examples, @jseldess! 

I quickly checked how the current style will look like for those examples - not sure there's much improvement, but there's better contrast with the tweaked color scheme/new font options.

**SQL:** 

![image](https://user-images.githubusercontent.com/1486483/32381684-af7f3e82-c089-11e7-8bd1-1b60620eec10.png)

**CLI:**
- Dumb question: Why is `database` the only highlighted syntax here?
![image](https://user-images.githubusercontent.com/1486483/32381601-71aed4a0-c089-11e7-9e4f-9932e1d1aa02.png)

**Comment by jseldess** [comment]
@kuanluo, I agree it's not a big change, but the slight increase in contrast is nice. 

I think you mean `datacenter`? Honestly, I don't know why just that word gets picked up. The language for those code blocks is `shell`. Perhaps @j-low will be able to figure out how rouge is determining keywords to highlight for that and other languages.

**Comment by kuanluo** [comment]
Yes, I meant `datacenter` and increase in contrast is definitely a win. I will pass the file onto @j-low and we can get this new syntax style implemented.

**Comment by sploiselle** [comment]
FWIW I have a bunch of small asks for syntax highlighting changes. The current syntax highlighting doesn't do the best job at actually highlighting our syntax: would love to improve that.

**Comment by jseldess** [comment]
@sploiselle, would you be willing to pass those tasks over to @j-low, who's working on this for us?

**Comment by kuanluo** [comment]
@j-low 

- Typeface: **Roboto Mono** or **Source Code Pro**. Both are available via Google Fonts, and we can see which one works better in dev environment. 
- Code block background color: `f6f6f6` 
- Text colors:
Gray: `A2A2A2`
Purple: `A0247A`
Blue: `3C80E1` 
Green: `26A5A5`

**Comment by sploiselle** [comment]
@j-low If you decide to work on creating a custom syntax highlighting package for Cockroach, let me know and we can go over the problems I've seen.

**Comment by j-low** [comment]
@sploiselle Sure thing.  I believe I'll have time to take a look at these issues later this week.  I'll be sure to ping you before then.

**Comment by jseldess** [comment]
@j-low and @kuanluo, any updates on this work?

**Comment by jseldess** [comment]
@j-low, @kuanluo, should we consider this closed after https://github.com/cockroachdb/docs/pull/2323, or is there more we plan to do in the near-term?

**Comment by kuanluo** [comment]
We could, if we break out 1) contrast 2) line number into separate github issues, just to keep track of them, since they're both on the dock (low priority) for this quarter.

**Comment by jseldess** [comment]
Moving this to the "Later" milestone, @kuanluo and @j-low, since I don't think there's a specific plan yet for further improvements.

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2154%3A0

**Comment by lnhsingh** [comment]
QAed by @lnhsingh and @luciaaaaaaa and merged into the `docs-redesign` branch
