### ISSUE TITLE
sql: need to document setting session DB for IMPORT

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#2115]
See: https://forum.cockroachlabs.com/t/import-data-from-csv-file-failing/1059/3

`into_db` is the same as RESTORE, just isn't documented.

**Comment by jseldess** [comment]
Based on @dt's response, though, this is in 1.2, not in 1.1?

**Comment by dt** [comment]
yeah, don't think this this made 1.1

**Comment by mjibson** [comment]
Ah, yes. I read the code to see if it was in 1.1, and thought it was because it's kind of half there.

We should probably note somewhere though that you have to set the session database.

**Comment by dt** [comment]
the error tells you to use `into_db` since it comes from a shared helper, but then `into_db` doesn't actually work :(
