### ISSUE TITLE
Generating certs on AWS EC2

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2118]
Re: [Deploy CockroachDB on AWS EC2](https://cockroachlabs.com/docs//v1.1/deploy-cockroachdb-on-aws.html)

## Issue Description
When generating certs we say
> Create the certificate and key for the first node, issued to all common names you might use to refer to the node as well as to the load balancer instances.

Following the instructions as written errored out as AWS was providing strings like ip-172-31-8-73 (internal host name) rather than 172.31.8.73 (internal IP address) 

## Suggested Resolution 
We should explicitly call out "internal hostname"

**Comment by jseldess** [comment]
@taroface, you recently worked on the AWS deployment docs. Is this issues till valid? It's quite old.

**Comment by taroface** [comment]
This section wasn't updated and the issue may still be valid. I think we should keep it open.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
