### ISSUE TITLE
More robust production deployment docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2120]
Our deployment docs make it easy to get a cluster up and running in various environments. For 1.2, we should expand our guidance to give the full story about what it takes to plan and run cockroach in production, from planning to testing to monitoring. 

[Draft Plan](https://docs.google.com/document/d/1gi39fsCOATjg0MqNWjwEGo2PR0LSXEoowEQuSwLGOUU/edit#)

**Comment by sploiselle** [comment]
FWIW I have a lot of these topics outlined [here](https://docs.google.com/spreadsheets/d/1LUpw4j9r3iavOfcnJki7dCABjdxUy6Ey8tJIVU9pEKQ/edit#gid=1253635576), as well as [an initial PR open for some of this content](https://github.com/cockroachdb/docs/pull/1729).

**Comment by jseldess** [comment]
Yes, thanks for the reminder, @sploiselle. Definitely want to leverage that work.

**Comment by jseldess** [comment]
For 2.0, the focus is a more complete prod checklist with specific details on:
- clock synch
- hardware
- monitoring/alerting

**Comment by jseldess** [comment]
I'm considering this resolved as of https://github.com/cockroachdb/docs/pull/2850. Though there's plenty more work to do around prod docs for 2.1.
