### ISSUE TITLE
java code sample missing release

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#2121]
The "Transaction (with retry logic)" code sample for java seems wrong:
https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb.html#transaction-with-retry-logic

As someone noticed on gitter, it's missing a `releaseSavepoint()` call. Besides that making the sample not handle retriable errors on COMMIT correctly, this user seems to claim that the jdbc driver doesn't even let you run the `db.commit()` method.

@arjunravinarayan, assigning to you since I think you wrote this sample originally.

```
i13026 @i13026 09:13
db.setAutoCommit(false)

val savePoint = db.setSavepoint("COCKROACH_RESTART")

while (true) {
  try {
    // statement 1
// statement 2
// statement 3

    db.releaseSavepoint(savePoint)
    db.commit

    return
  } catch {
    case e: SQLException =>
      if (e.getErrorCode == 40001 || e.getSQLState == "40001") {
        db.rollback(savePoint)
      } else {
        throw e
      }
  }
}
Is this right? In https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb.html#transaction-with-retry-logic the comment says // If we reach this point, commit the transaction, which implicitly releases the savepoint.
conn.commit();
but it without release it does not work

Tobias Schottdorf @tschottdorf 09:15
what error do you get?

i13026 @i13026 11:08
without the releaseSavepoint: org.postgresql.util.PSQLException: ERROR: SAVEPOINT COCKROACH_RESTART

Andrei Matei @andreimatei 11:34
@i13026 our java code sample seems wrong to me. The release statement is indeed needed. I’ll see about fixing it. The idea is that the release call can encounter a retriable error, and at that point we can still restart the txn. If the release is missing, then the commit would encounter that retriable error, except it’s too late to restart after a commit (more precisely, the ROLLBACK TO SAVEPOINT would fail after a COMMIT).
The comment about commit implicitly releasing the savepoint is, in itself, not wrong. If the database sees a COMMIT, then the savepoint is automatically released. I believe this is Postgres behavior which we’re emulating (I have to check that too, though, now that we’re talking).
However, it would appear that jdbc or the jdbc Postgres driver doesn’t let you do that - I interpret your error as the driver insisting that all savepoints are released. Will investigate a bit.
```

**Comment by jseldess** [comment]
Thanks for handling this, @arjunravinarayan!

**Comment by debraj-manna** [comment]
@arjunravinarayan  - I have made the changes as mentioned in this ticket. But I am still getting an exception as discussed in this [community post](https://forum.cockroachlabs.com/t/cockroach-transaction-throwing-exceptions/1071/12). The cockroach db logs and the exception trace are attached in the discussion. 

Also I am getting an error code 0 from cockroach.

**Comment by debraj-manna** [comment]
If we are doing `conn.releaseSavepoint(sp)` before doing `conn.commit();` what if there is an exception durning `conn.commit`. The example in the [JDBC doc](https://docs.oracle.com/javase/tutorial/jdbc/basics/transactions.html#call_rollback) is doing conn.commit() in a try block and doing `conn.rollback(sp)` in a catch block to rollback the changes. How are this supposed to be handled in this case?

I have posted this in gitter also. Just posting this here for completion sake.
