### ISSUE TITLE
Docs search spans all versions

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#2132]
Hey docs team, 

When you search for the admin UI within docs, the first hit is [explore the admin UI](https://www.cockroachlabs.com/docs/v1.0/explore-the-admin-ui.html), which is not intuitively linked to the [monitor cockroachDB with the Admin UI](https://www.cockroachlabs.com/docs/v1.1/admin-ui-access-and-navigate.html) docs you built out for the 1.1 release.

It seems to be caused by the search function searching *all* docs regardless of version, and I'm not sure how to suggest a fix, but happy to talk through it. 

Attached is a screenshot: 
![screen shot 2017-11-06 at 10 36 09 am](https://user-images.githubusercontent.com/6042450/32449196-f0856cc4-c2de-11e7-9394-aa641da9e44f.png)

**Comment by jseldess** [comment]
Good catch, @jess-edwards. It should be possible to filter the results based on the version selected. 

@benesch, do you think it'd be easy to dynamically add the version to the search filter?
https://github.com/cockroachdb/docs/blob/master/_includes/sidebar.html#L84

cc: @j-low

**Comment by benesch** [comment]
Not totally sure it's possible. Need the underlying Google search engine to support filtering by version, somehow. Something like `site:cockroachlabs.com/docs/vCURRENT_VERSION_HERE`.

**Comment by j-low** [comment]
@jess-edwards @jseldess @benesch: next week I will be implementing a new search tool (likely Algolia).  During that implementation I will do some investigating re: adding version filtering.

**Comment by jseldess** [comment]
The switch to algolia is imminent. Let's consider this requirement part of that work: https://github.com/cockroachdb/docs/issues/1217.
