### ISSUE TITLE
Porting from PostgreSQL Doc Update 

### ISSUE THREAD

**Issue by andreis** [cockroachdb/docs#2143]
Re: [Porting from PostgreSQL](https://cockroachlabs.com/docs//v1.1/porting-postgres.html)

## Issue Description

JSON datatype not mentioned

## Suggested Resolution 

Add section about `JSON` and `JSONB` not being supported. The solution AFAICT is to use `STRING` and `BYTES` instead.

**Comment by jseldess** [comment]
Thanks, @andreis. `JSON`/`JSONB` support is coming in the next major release, but for now, let me look into adding such a suggestion.

@awoods187, @justinj, thoughts?

**Comment by justinj** [comment]
I think this page is specifically for features we *do* support, but whose behaviour differs from Postgres. There's a very large list of features (and specifically datatypes) that Postgres has and we don't support, and if we're putting this on here we would probably want to put the rest on here too. cc @mjibson who I believe created this page though, for his thoughts.

**Comment by awoods187** [comment]
Also, we will only be supporting JSONB (not JSON) in the next release.

**Comment by mjibson** [comment]
The purpose of that page is to describe identical, supported syntax that has different results when run in postgres or crdb. I think missing features should not be included in this page.

**Comment by andreis** [comment]
@mjibson it's literally called "porting from Postgres", not "identical supported syntax that has different results when run in pg or cr" 😆

**Comment by jseldess** [comment]
All, based on recent discussions with @awoods187 and others, we will likely end up expanding the purpose of this page to list the major differences to Postgres with justifications and, if possible, workarounds. This will include functional incompatibility (some Postgres feature just doesn't work in Cockroach) and may include non-functional incompatibility (feature works but perhaps with different performance implications).

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2467.
