### ISSUE TITLE
Copy-to-clipboard styled incorrectly when in <div> tags

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2146]
Example:

```
2. Stop Kubernetes:

    <div class="filter-content" markdown="1" data-scope="gce-hosted">

    {% include copy-clipboard.html %}
    ~~~ shell
    $ gcloud container clusters delete cockroachdb
    ~~~

    </div>
```

<img width="854" alt="screen shot 2017-11-09 at 11 30 01 pm" src="https://user-images.githubusercontent.com/15893490/32642977-f2a4d070-c5a5-11e7-9a44-0839ad1ae7fd.png">

It should look like:

<img width="830" alt="screen shot 2017-11-09 at 11 30 39 pm" src="https://user-images.githubusercontent.com/15893490/32642984-07cf8f44-c5a6-11e7-894f-f810fa465934.png">

**Comment by jseldess** [comment]
@j-low, when you have some time, would love you help with this.

**Comment by jseldess** [comment]
@j-low, ping on this, whenever you have time.

**Comment by j-low** [comment]
@jseldess looking into this issue this week

**Comment by jseldess** [comment]
@j-low, this problem has reappeared in more severe form in https://github.com/cockroachdb/docs/pull/2585. In that case, using an include snippet inside a div causes the html to not render properly. 

While looking at that, I found a workaround: Whenever we use an include snippet within a div, changing the `<div></div>` tags to `<section></section>` resolves the problem. However, it seems important to **not** make this change when there's no include within the div. I don't understand what's going on, but I suspect the html generated by the include snippet is somehow invalid and therefore causing chaos when nested in another div.

I think this workaround is sufficient for now, but it'd still be great if you could figure out why this combination creates chaos.

**Comment by luciaaaaaaa** [comment]
does the problem persist if we remove the icon? and have the button just be 'COPY'

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A12946
