### ISSUE TITLE
Homebrew instructions are not version aware

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#2153]
The Homebrew instructions on [dev version of Install CockroachDB](https://www.cockroachlabs.com/docs/dev/install-cockroachdb.html) instead the latest stable version.

@benesch Do you have suggestions for a fix for this that work globally, incl. for versions that are beta-only?

**Comment by benesch** [comment]
Ooh, good point. In general, Homebrew does not allow you to specify the version you want to install. You always get the latest version Homebrew has available.

**Comment by jseldess** [comment]
Hmm, good catch, @sploiselle. Should we just remove the Homebrew option for all version but `stable`? Especially since it's now the first/default method for macOS? Or should we rather add a callout?

**Comment by sploiselle** [comment]
@jseldess Yeah, either that or maintain a homebrew recipe for cockroach-beta (and potentially cockroach-alpha). @benesch Is the latter feasible/an option?

**Comment by jseldess** [comment]
ping, @benesch. Should I just remove the homebrew option for anything but stable?

**Comment by benesch** [comment]
Upon further investigation Homebrew does not "bottle" development releases, so it'll be very, very slow. So yes, I'd just remove the option for everything but stable.
