### ISSUE TITLE
Edit This Page option on Install CockroachDB results in 404

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#2157]
Re: [Install CockroachDB](https://cockroachlabs.com/docs//v1.1/install-cockroachdb.html)

## Issue Description

When clicking the link "edit this page" I get a 404 error on github.

## Suggested Resolution 

Update the "edit this page" link.

**Comment by jseldess** [comment]
Good catch, @knz. This is happening because we replace `.html` with `.md`: https://github.com/cockroachdb/docs/blob/master/_includes/contribute-options.html#L9

But in this case, the source file is `.html`.
