### ISSUE TITLE
verify privilege implementation

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#216]
Before we document all privileges, we should verify what is actually being done.
Specifically, for each statement (and for the major sub-statements), we should:
* audit the code to check what is intended
* make sure we have decent coverage in the sql tests
* verify that we're actually doing the right thing, fix or file bugs when not

From there, we can integrate this information into the docs.

**Comment by mberhault** [comment]
I'll just put all the statements from the [docs](https://www.cockroachlabs.com/docs/sql-statements.html) here and complete them inline:
```
ALTER TABLE	 
BEGIN TRANSACTION	 
COMMIT TRANSACTION	 
CREATE DATABASE
CREATE INDEX	 
CREATE TABLE	 
DELETE	 
DROP DATABASE	 
DROP INDEX	 
DROP TABLE	 
EXPLAIN	 
GRANT	 
INSERT	 
RENAME COLUMN	 
RENAME DATABASE	 
RENAME INDEX	 
RENAME TABLE	 
REVOKE	 
ROLLBACK TRANSACTION	 
SELECT	 
SET DATABASE	 
SET TIMEZONE	 
SET TRANSACTION	 
SHOW COLUMNS	 
SHOW DATABASES	 
SHOW GRANTS	 
SHOW INDEX
SHOW TABLES	 
SHOW TIMEZONE	 
SHOW TRANSACTION ISOLATION LEVEL	 
SHOW TRANSACTION PRIORITY	 
TABLE	 
TRUNCATE	 
UPDATE	 
VALUES
```

**Comment by jseldess** [comment]
@mberhault: is this one still in progress, or are you confident with the privileges I put in the docs (I tested pretty much everything)?

**Comment by mberhault** [comment]
I think we're ok for now.
