### ISSUE TITLE
sql: modify BYTES->STRING casts to match postgres

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2165]
PR: https://github.com/cockroachdb/cockroach/pull/18843

From release notes:

> Casts from BYTES to STRING have been changed and now work the same way as in PostgreSQL. New functions encode() and decode() are available to replace the former functionality.

**Comment by jseldess** [comment]
@justinj, any interest in update the docs on this during docs fixitday next Thursday?

**Comment by justinj** [comment]
Sure!

**Comment by jseldess** [comment]
Given that the docs cover `encode()` and `decode()`, I don't think any other doc updates are needed. Do you, @justinj?
