### ISSUE TITLE
Various PostgreSQL compatibility updates

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2175]
From release notes:
> The `pg_namespace.aclitem` column has been renamed to `nspacl`. `pg_class` now has a `relpersistence` column. New functions `pg_encoding_to_char`, `pg_get_viewdef`, and `pg_get_keywords`. The `pg_tablespace` table is now available. The type name "char" (with quotes) is recognized as an alias for `CHAR`. Session variable `server_version_num` is now available.

PRs:
- https://github.com/cockroachdb/cockroach/pull/18530
- https://github.com/cockroachdb/cockroach/pull/18618
- https://github.com/cockroachdb/cockroach/pull/19127
- https://github.com/cockroachdb/cockroach/pull/19405

**Comment by jseldess** [comment]
> The type name "char" (with quotes) is recognized as an alias for CHAR

Need to update https://www.cockroachlabs.com/docs/dev/string.html#aliases.

> Session variable server_version_num is now available.

Need to update https://www.cockroachlabs.com/docs/dev/show-vars.html#supported-variables and https://www.cockroachlabs.com/docs/dev/set-vars.html#supported-variables.

No updates need for the other changes.

**Comment by knz** [comment]
> The type name "char" (with quotes) is recognized as an alias for CHAR

Let's not document this until https://github.com/cockroachdb/cockroach/issues/24686 is solved.
