### ISSUE TITLE
Various fixes to the interactive SQL shell

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2176]
From release notes:
> Many bugs in the interactive SQL shell have been fixed by switching to libedit for command-line input. The normalize_history option has been removed.

PRs: 
- https://github.com/cockroachdb/cockroach/pull/18531
- https://github.com/cockroachdb/cockroach/pull/19125

**Comment by jseldess** [comment]
@knz, it's a bit hard for me to extract the necessary doc updates here. I know we need to remove [`normal_history`](https://www.cockroachlabs.com/docs/dev/use-the-built-in-sql-client.html#sql-shell-options) from the `cockroach sql` page. Do we also need to resolve these known limitations?

- https://www.cockroachlabs.com/docs/dev/known-limitations.html#repeated-or-combined-commands-in-the-sql-shell-history
- https://www.cockroachlabs.com/docs/dev/known-limitations.html#using-to-perform-a-large-input-in-the-sql-shell

Are there other implications?

**Comment by jseldess** [comment]
@knz, ping.

**Comment by knz** [comment]
I'm so sorry for the late answer!

yes the first known limitaiton is lifted, the second one isn't.

I made the changes in #2790. Thanks for the heads up.
