### ISSUE TITLE
remove array notice from pg_dump

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#2186]
https://www.cockroachlabs.com/docs/stable/import-data.html#import-from-postgresql-dump Step 4 under Reformat SQL File discusses removing arrays, but we support those now.

**Comment by jseldess** [comment]
@mjibson, this is as of 1.2, correct?

**Comment by mjibson** [comment]
Oh yes. The link is wrong.

**Comment by mjibson** [comment]
https://www.cockroachlabs.com/docs/stable/array.html looks like we support arrays in 1.1?
