### ISSUE TITLE
[asap] add LinkedIn advertising pixel to docs site

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#2193]
@j-low or @jseldess -- Can you add this LinkedIn ad pixel to every page of the docs site? It should sit in the body section of the site's HTML, just above the </body> tag.  This can also be installed via GTM if you feel comfortable using Google Tag Manager. This pixel will make it possible to track conversions from LinkedIn ads. 

<script type="text/javascript">
_linkedin_data_partner_id = "150890";
</script><script type="text/javascript">
(function(){var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})();
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=150890&fmt=gif" />
</noscript>

**Comment by jseldess** [comment]
Absolutely, @jess-edwards, but given that we're aiming to keep performance from degrading, can we first review which other tags are no longer needed? I think we have both optimizely and twitter still running on some pages. Is that still necessary or can I turn twitter and optimizely off for now?

**Comment by jess-edwards** [comment]
@jseldess Yes, go ahead and remove Optimizely. We've terminated that contract. 

I don't want to remove the Twitter tag yet, as I may run ad hoc campaigns on Twitter. @j-low has been doing a website performance pixel/performance audit, so I'm going to invite you to our next sync later this month. You should be invited / cc'ed on the project. Joe also put together a doc logging all slow website requests - I'll share it with you.

**Comment by j-low** [comment]
@jseldess, thanks for taking care of this one.  We can talk further next week along with @jess-edwards re: improving performance on docs.

**Comment by jseldess** [comment]
Absolutely, @j-low!
