### ISSUE TITLE
Screenshots in Automatic Rebalancing tutorial are out of date

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#2204]
Re: [Automatic Rebalancing](https://cockroachlabs.com/docs//v1.1/demo-automatic-rebalancing.html)

## Issue Description
Screenshot(s) are out of date: replication2.png, recovery1.png, scalability2.png

## Suggested Resolution 
Update with current view of Admin UI

**Comment by Amruta-Ranade** [comment]
@lhirata Can you verify the changes in https://www.cockroachlabs.com/docs/stable/demo-automatic-rebalancing.html#main-content

**Comment by lhirata** [comment]
LGTM!
