### ISSUE TITLE
Update docs on rolling upgrade to 1.2-alpha

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2213]
From Gitter:

> Hey all, just upgraded cluster to v1.2-alpha.20171113 from v1.1.1. All went well, but now when trying to execute SET CLUSTER SETTING version = '1.2'; I'm getting: pq: cannot upgrade to 1.2: node running 1.1-3. Any thoughts, or next steps for debugging? All nodes are reporting in the UI that they are on the new version.

**Comment by jseldess** [comment]
Internal version number can also be deduced from you can also check the source code: https://github.com/cockroachdb/cockroach/blob/master/pkg/settings/cluster/cockroach_versions.go.

**Comment by jseldess** [comment]
@tschottdorf, when I update the 1.2 rolling upgrade docs, what do you think the easiest way is for me to tell users to get the new cluster setting version for finalizing the upgrade? 
https://www.cockroachlabs.com/docs/dev/upgrade-cockroach-version.html#step-4-finalize-or-revert-the-upgrade

Seems that none of the current options are great:
1. Use an invalid version number and look in the error for the correct version (this is ugly but probably easiest).
2. Look in the source file for the relevant SHA. 
3. Check `ServerVersion` in `/_status/nodes/local`.

cc: @dianasaur323

**Comment by jseldess** [comment]
Still need to update the docs based on this change, so reopening.

**Comment by jseldess** [comment]
@bdarnell, don't I still need to update the docs? Not sure why you closed this...

**Comment by bdarnell** [comment]
That is weird. Tobi's change re-closed the issue when I updated my fork. I didn't think you could close issues across repos like this.

**Comment by jseldess** [comment]
Oh, weird. Well, thanks for reopening.

**Comment by arctica** [comment]
I just ran into this while upgrading to the latest master build and wasn't really sure what version to set the cluster setting to. The queries from the linked merge request worked fine (now apparently on 1.1-8). It would be great if the cluster setting for version was shown in the admin UI overview page. Bonus points for showing a warning/notitce if node versions differ or if a higher cluster version can be set.

Even more internet points for providing a changelog for cluster versions :)
