### ISSUE TITLE
Error in decommissioning command

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#2216]
https://www.cockroachlabs.com/docs/training/start-and-scale-a-cluster.html#step-5-remove-node4

Port should be `--port=26260`

**Comment by jseldess** [comment]
Closed by https://github.com/cockroachdb/docs/pull/2218.

@lhirata, I forgot to show you how to close an issue directly from the PR. Basically, you just need to include `Fixes #<number of issue>` in your PR description or in a commit description. I can help you with that next time.
