### ISSUE TITLE
Encryption at rest / Transparent Data Encryption (TDE)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2220]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwhurBXeM4Eo7mJw/recMNSbGPwfkjg7QJ
PM: @dianasaur323 
Eng Partner: @mberhault 

RFC: [20171220_encryption_at_rest](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171220_encryption_at_rest.md)
Tracking issue: https://github.com/cockroachdb/cockroach/issues/19783 (links to all PRs)

**Comment by mberhault** [comment]
Taking over for now. Will have draft docs to work from.

**Comment by jseldess** [comment]
Add flag to `cockroach start` docs.

**Comment by jseldess** [comment]
Follow-up work tracked in https://github.com/cockroachdb/docs/issues/3526.
