### ISSUE TITLE
DISTINCT ON (distinct on partial columns)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2221]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recuVUy1ggv9TutAt

PRs:
- https://github.com/cockroachdb/cockroach/pull/20463

**Comment by jseldess** [comment]
From https://github.com/cockroachdb/cockroach/pull/20463:

Release notes (feature): the DISTINCT ON clause was introduced for
SELECT statements.

Syntax
```sql
SELECT DISTINCT ON (<distinct-on-exprs>) <select-exprs> FROM x ...
```

Which will retrieve an arbitrary row of <select-exprs> for every distinct
combination of <distinct-on-exprs>.

If the ORDER BY clause is specified in the SELECT statement, DISTINCT ON
will respect that ordering when choosing the "arbitrary row" (that is:
it will choose to first row based on the ordering).

For more examples, see `logic_test/distinct_on` and `logic_test/distsql_distinct_on`.

**Comment by jseldess** [comment]
Depends on being able to generally clean up the `SELECT` diagram: https://github.com/cockroachdb/docs/issues/2719

**Comment by knz** [comment]
The diagram will show up properly in #2762.

**Comment by jseldess** [comment]
Thanks, @knz! Do we also need to update the description under `Parameters`? This is what postgres says:

> SELECT DISTINCT eliminates duplicate rows from the result. SELECT DISTINCT ON eliminates rows that match on all the specified expressions. SELECT ALL (the default) will return all candidate rows, including duplicates.

**Comment by knz** [comment]
yes, indeed. I added a paragraph accordingly, which I believe will close this issue.
