### ISSUE TITLE
[MH] Implement SERIAL and INTEGER as a 32 bit integer 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2222]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recPzC3cBk0PBhZIW
PM: @awoods187 
Eng Partner: @BramGruneir

**Comment by jseldess** [comment]
Slipped to 2.2, @rmloveland.

**Comment by rmloveland** [comment]
Documented in #4317 (set `default_int_size` to 4)
