### ISSUE TITLE
Catch Up: 3-Node, Local, Secure Cluster: Shell prompt missing from code block

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#2224]
Re: [Catch Up: 3-Node, Local, Secure Cluster](https://cockroachlabs.com/docs//training/3-node-local-secure-cluster.html)

## Issue Description

Copy clipboard in https://www.cockroachlabs.com/docs/training/3-node-local-secure-cluster.html#certificate-authority not rendering correctly

**Comment by jseldess** [comment]
@lhirata, can you provide more details here? It's rendering fine for me, though the `$` prompt is missing from the code block...

**Comment by lhirata** [comment]
@jseldess yesterday, the code block looked wonky-- like the copy button was overlapping with the code. Now it looks fine to me too. Looks like just the `$` needs to be added.

**Comment by jseldess** [comment]
Thanks, @lhirata. Want to fix this when you have a chance?
