### ISSUE TITLE
URL-encoding AWS credentials specified as query parameters

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2238]
See https://forum.cockroachlabs.com/t/error-doing-import-from-aws/1034/2

> One gotcha with specifying AWS credentials as query parameters is that they often contain non-URL-safe characters that need to be URL-encoded. In Go, you could use url.QueryEscape; in JavaScript, you could use encodeURIComponent.

**Comment by jseldess** [comment]
I believe this applies for [`IMPORT`](https://www.cockroachlabs.com/docs/stable/import.html#import-file-temp-directory-urls), [`BACKUP`](https://www.cockroachlabs.com/docs/stable/backup.html#backup-file-urls), and [`RESTORE`](https://www.cockroachlabs.com/docs/stable/restore.html#backup-file-urls). Is that right, @benesch?

**Comment by benesch** [comment]
Exactly right.

**Comment by Amruta-Ranade** [comment]
Closed this in #2340
