### ISSUE TITLE
Clarify errexit option in cockroach sql

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#2248]
Re: [Use the Built-in SQL Client](https://cockroachlabs.com/docs//v1.1/use-the-built-in-sql-client.html)

## Issue Description

User reported that \unset errexit is not disabled by default

## Suggested Resolution 

Update docs to remove that statement

**Comment by jseldess** [comment]
More context:

When using `--excute`, if an error occurs in any statement, the command exits with a non-zero status code and further statements are not executed. You can change that behavior by disabling the `errexit` shell option.

**Comment by jseldess** [comment]
@knz, as far as I can tell, the docs are correct to state that `errexit` is disabled (`false`) by default:

```
root@:26257/> \set
+----------------+--------+
|     Option     | Value  |
+----------------+--------+
| display_format | pretty |
| errexit        | false  |
| echo           | false  |
| check_syntax   | true   |
| show_times     | true   |
| smart_prompt   | true   |
+----------------+--------+
(6 rows)
```

Am I missing something? I think the original issue was not from the interactive shell. I think they were using `--execute` from the command line, which seems to always exit upon error. Right?

**Comment by slateraus** [comment]
Let me try and clear up the confusion. The default from a unix command line passing in a file to execute and from within the SQL Client are inconsistent. 

I have an alias set up for cockroach sql.
alias csql='cockroach sql --insecure  --host=host1'

`$ cat a.sql
selectt count(*) from lee.acc;
select count(*) from lee.acc;
$ csql < a.sql
pq: syntax error at or near "selectt"
DETAIL: source SQL:
selectt count(*) from lee.acc;
^
Error: pq: syntax error at or near "selectt"
Failed running "sql"

$ cat a.sql 
\unset errexit

selectt count(*) from lee.acc;
select count(*) from lee.acc;

$ csql < a.sql
pq: syntax error at or near "selectt"
DETAIL: source SQL:
selectt count(*) from lee.acc;
^
count(*)
1450040
# 1 row
`

**Comment by slateraus** [comment]
Test 
'the cat in the hat'

**Comment by knz** [comment]
They are not inconsistent.
The default for `errexit` is `true` when running a list of commands from a file or the command line.
It's `false` when running interactively.

The rationale is that when running interactively, the human has a chance to decide in between each statement whether they want to enter the next statement or not if one fails. When running non-interactively, this choice doesn't exist. Disallowing subsequent statements from running if one fail is better from a data safety perspective. `psql` does the same AFAIK.

**Comment by knz** [comment]
@jseldess maybe we should have a table somewhere that shows the defaults when running interactively and non-interactively. 

This discussion also needs to be put in perspective of the other issue which you have created earlier (and assigned to me) to clarify what "interactive" means precisely (running from a terminal vs. running from the CLI shell).

**Comment by jseldess** [comment]
Excellent idea to clarify defaults for interactive vs. non-interactive. I created an issue: https://github.com/cockroachdb/docs/issues/2263

**Comment by lhirata** [comment]
Closing this issue. The docs are correct, but I'll be working on #2263 to help clarify.
