### ISSUE TITLE
storageccl,sqlccl: make nodelocal paths relative to external-io-dir

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2253]
PR: https://github.com/cockroachdb/cockroach/pull/19865

[nodelocal://](https://www.cockroachlabs.com/docs/v1.2/import.html#import-file-temp-directory-urls) paths in `IMPORT`/`BACKUP`/`RESTORE` now default to relative within the "extern" subdirectory of the first store directory, configurable via the new `--external-io-dir` flag.

**Comment by Amruta-Ranade** [comment]
Closed this in #2340
