### ISSUE TITLE
storageccl: support S3 endpoints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2255]
PR: https://github.com/cockroachdb/cockroach/pull/19860

From release notes:
> Added `AWS_ENDPOINT` and `AWS_REGION` parameters in S3 URIs to specify the AWS endpoint or region for `IMPORT`/`BACKUP`/`RESTORE`. The endpoint can be any S3-compatible service.

**Comment by Amruta-Ranade** [comment]
Closed this in #2340
