### ISSUE TITLE
Changes for PostgreSQL compatibility

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2256]
- PR: https://github.com/cockroachdb/cockroach/pull/19931
  - The `time zone` session variable (with a space) has been renamed `timezone` (without a space), and `SET TIMEZONE` and `SHOW TIMEZONE` are now supported alongside the existing `SET TIME ZONE` and `SHOW TIME ZONE` syntax. Also, `SET TIMEZONE =` can now be used as an alternative to `SET TIMEZONE TO`. 
- PR: https://github.com/cockroachdb/cockroach/pull/19971
  - The `transaction_read_only` session variable is now supported. It is always set to `off`.
- PR: https://github.com/cockroachdb/cockroach/pull/20264
  - The `transaction isolation level`, `transaction priority`, and `transaction status` session variables have been renamed `transaction_isolation`, `transaction_priority`, and `transaction_status`.

**Comment by jseldess** [comment]
Need to update [`SET (session variable)`](https://www.cockroachlabs.com/docs/dev/set-vars.html#supported-variables), [`SHOW (session variable)`](https://www.cockroachlabs.com/docs/dev/show-vars.html#supported-variables), and [`SET TRANSACTION`](https://www.cockroachlabs.com/docs/dev/set-transaction.html#supported-variables), where relevant. 

It looks like we don't list some of the transaction variables on the set/show variables pages. Not sure why not.

**Comment by lhirata** [comment]
It seems like you can't interchangeably use `TIME ZONE` and `TIMEZONE`. @knz, can you help clarify? For example, if I `SET TIME ZONE DEFAULT` and then `SET TIMEZONE EST`, the second `SET` doesn't work unless I use `SET TIMEZONE = EST`.  Why is this?

**Comment by lhirata** [comment]
Also: The `transaction_read_only` can't be changed from `off`, so it seems misleading that you can `SET transaction_read_only = FALSE / TRUE;` and get a `SET` (even though nothing is changed). @justinj, is this just a wonky or should this be changed?

**Comment by justinj** [comment]
Hm, yes, I think I assumed in that PR that attempting to set it would fail, we should fix that. Opened as #24608

**Comment by knz** [comment]
@lhirata: `SET TIME ZONE xxx` is a "special form", which has its own, special cased grammar rule, and gets automagically replaced to `SET timezone = xxx`. 

This is similar to  `SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL xxx` which is a special form that gets automagically replaced to `SET TRANSACTION ISOLATION LEVEL xxx` 

We already mention in the text it's a special form. The only thing that needs to change in the doc page is the name of the variable in the table, and further references to the variable in that page and other pages.

**Comment by knz** [comment]
In the current text we say "`SET TIME ZONE xxx` is a special form for `SET "time zone" = xxx`". This text needs to be changed to "`SET TIME ZONE xxx` is a special form for `SET timezone = xxx`".

**Comment by lhirata** [comment]
@knz thanks for the explanation!
