### ISSUE TITLE
SHOW TRACE FOR SELECT now supports AS OF SYSTEM TIME

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2257]
PR: https://github.com/cockroachdb/cockroach/pull/20162

**Comment by andreimatei** [comment]
I think there's nothing to do here. The tracing docs don't talk about AOST.

**Comment by jseldess** [comment]
@andreimatei, right, this issue was to update the docs to talk about it. Do you not want us to mention AOST support with `SHOW TRACE`?

**Comment by andreimatei** [comment]
Why would we do any special mentions? The point of tracing is that it support everything.
I believe it used to be the case that it didn't support AOST, which could have been mentioned at that dark time.

**Comment by jseldess** [comment]
I'm ok with that, but we have another issue open to clarify that AOST cannot be used in a subquery, of which this is an example, I think? 

https://github.com/cockroachdb/docs/issues/2581

**Comment by andreimatei** [comment]
Indeed, AOST cannot be used in a subquery (except if it matches the one at the top level), but we make an exception for SHOW TRACE FOR.
