### ISSUE TITLE
Figure out SET statements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#226]
Right now, we have individual pages for `SET DATABASE`, `SET TIMEZONE`, and `SET TRANSACTION`. 

Should we also have a page for `SET SESSION`? And would `SET LOCAL` be covered there as well? 

Also, I don't think the current diagram for [`SET TRANSACTION`](https://cockroachlabs.com/docs/set-transaction.html) is helpful; it show the entire `SET` grammar.

**Comment by mjibson** [comment]
From the looks of it, `SESSION` and `LOCAL` are closer to options than separate statements. If that is correct than I think they should not be their own page, but instead live with the rest of their content on the right side.

**Comment by jseldess** [comment]
OK, you're right, Matt. In fact, session and local don't mean anything currently. There's an issue on that: https://github.com/cockroachdb/cockroach/issues/6149

I think there are other parameters a user might want to set aside from database, transaction, and timezone, such as `SYNTAX`. The grammar suggest that you can set other variable, too, but I don't know how that works. Do you see exactly which variables can be set? And if so, how do you think we should handle graphics for these? If there are too many, I wonder whether we're going down the wrong path...?

**Comment by mjibson** [comment]
If it were me, I would reduce the number of `SET` pages we have to `SET TRANSACTION` and one with everything else which can document all of the other options explicitly (i.e., not in a grammar diagram, since not all options have a specific grammar expression).

**Comment by jseldess** [comment]
I think that might make more sense. Do you think we even need to separate out `SET TRANSACTION`? Or should we just have a single `SET` page/diagram where we cover all of these?

**Comment by mjibson** [comment]
One reason I thought to separate `SET TRANSACTION` is that it's quite separate from how the rest of the set stuff works. Everything else is `SET value = name`, but the transaction stuff is `SET TRANSACTION ISOLATION LEVEL snapshot`. That is, the transaction set has no `=`, and is used to modify how the running transaction is working. If it were one page, all the transaction stuff would have to have a separate section describing all its workings, including descriptions of the various priorities and isolation levels and what they do.

**Comment by jseldess** [comment]
OK, let's go with that approach then: One page/graphic for `SET TRANSACTION` and one other page/graphic for `SET`, covering everything but transaction settings. Once you've added the latter, I'll remove the `SET DATABASE` and `SET TIME ZONE` pages in favor of a generic `SET` page. Sound good?
