### ISSUE TITLE
sqlccl: ensure interleave hierarchy in BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2262]
PR: https://github.com/cockroachdb/cockroach/pull/20206

**Comment by jseldess** [comment]
In terms of doc changes, I believe this means we need to update this object dependencies section a bit: https://www.cockroachlabs.com/docs/stable/backup.html#object-dependencies.

As far as I understand, `BACKUP` now someone ensures that parent tables of interleaved children tables are backup up, so there's less room for user error. @dt, can you confirm or correct?

**Comment by dt** [comment]
Correct

**Comment by Amruta-Ranade** [comment]
"Dependent objects should be backed up at the same time as the objects they depend on; otherwise, you cannot restore the dependent objects." > "Dependent objects must be backed up at the same time as the objects they depend on."
