### ISSUE TITLE
Document Kubernetes performance gotchas

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#2265]
I did a performance comparison last night between our default `StatefulSet` Kubernetes config file and an alternative [`DaemonSet` config](https://gist.github.com/a-robinson/ec2b86783ccbf053c83ba83170673d63) on a 3-node v1.7.8 GKE cluster of n1-standard-1 VMs. The performance difference was massive:

```
When running against daemonset with `hostNetwork` and `hostDir` (using the VMs' 100GB pd-standard boot disks):
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   78.8s        0         146093         1853.3    130.0    176.2    486.5          0 / 73356

When running against statefulset (using a 1GB pd-standard, which our config defaults to):
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   52.0s        0          18023          346.5    520.1    704.6   1208.0           0 / 9071

When running against statefulset (using a 100GB pd-standard to be more fair, since GCE disk size affects IOPS):
_elapsed___errors____________ops___ops/sec(cum)__p95(ms)__p99(ms)_pMax(ms)_____seq(begin/end)
   84.4s        0          30822          365.1    570.4    738.2   2147.5          0 / 15426
```

I suspect most of the difference is network-related -- we already know that our RPC layer can be a bottleneck, and going through the Docker bridge is not cheap. I would have expected it to be more like a 2x difference, though, not a 5x difference. It's also possible that the way the `StatefulSet`'s disk gets mounted is a little different from the machine's boot disk, but they were all using the same kind of disk (persistent HDDs).

If any Kubernetes customers are particularly worried about performance, I can try to confirm the hypothesis. Just let me know and I'll do so, otherwise I'll probably let this sit for a while. cc @robert-s-lee

**Comment by robert-s-lee** [comment]
Confirmation would be useful for current reference architecture preparation and provide the right expectations for customers who are in the self-evaluation.

**Comment by jseldess** [comment]
This is part of https://github.com/cockroachdb/docs/issues/2937.
