### ISSUE TITLE
Document known issues when running on Ubuntu 14.04 on EC2

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#2268]
In a privately reported issue, we've seen problems with Cockroach running on Ubuntu 14.04 on EC2 with Xen Networking enabled. The problem materialized with TCP network connections that would get stuck when sending and block for 15 mintues. This is a known issue with Ubuntu 14.04 in this configuration:

- https://blog.stathat.com/2014/12/22/fix_ec2_network_issue_skb_rides_the_rocket.html
- http://www.brendangregg.com/blog/2014-09-11/perf-kernel-line-tracing.html
- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811
- https://forums.aws.amazon.com/thread.jspa?threadID=161807

We found that the recommended fix for this was to disable TSO scatter-gather on each machine using the following command:
```
sudo ethtool -K eth0 sg off
```

We should find a place to document this so that we have somewhere to point users. This would probably be similar in spirit to https://github.com/cockroachdb/docs/issues/1356.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
