### ISSUE TITLE
Secure orchestration with Mesosphere

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2279]
As follow-up to https://github.com/cockroachdb/docs/pull/2277:

- Document secure orchestration with Mesosphere DC/OS
- Add 1.1/2.0 version of tutorial

**Comment by jseldess** [comment]
@a-robinson, is secure orchestration with mesos something we're planning for 2.0 or later?

**Comment by a-robinson** [comment]
The work to implement secure mode on DC/OS is not yet scheduled. 2.0 is unlikely.

**Comment by jseldess** [comment]
Thanks, @a-robinson. Moving this tentatively to the 2.1 milestone then.

**Comment by jseldess** [comment]
Moving this to later, as it's not a priority.
