### ISSUE TITLE
add search

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#23]
There needs to be a way to search across all topics in the docs.

Always planned to get it in there, but just occurred to me that this is pretty important for beta, @spencerkimball and @jess-edwards. Will look into options.

**Comment by mberhault** [comment]
I agree this will definitely be needed, and probably soon.
One (not particularly nice solution) is to have a "all on one page" type of thing to make browser-based search simpler. This may be terrible though.

**Comment by bdarnell** [comment]
There's probably a jekyll plugin for this, but in case there's not both sphinx and mkdocs have a javascript-based search widget.

**Comment by jseldess** [comment]
Yeah, that would make browser search optimal, but I think there are easy
search plugins for multipage outputs, too. In fact, I think the theme I'm
using has one and I just need to put it in place and see if it's sufficient.

**Comment by jseldess** [comment]
Matt got a basic google search in place. I'll open another issue for necessary future work (better control of search results and styling the results page).
