### ISSUE TITLE
3rd party alert management

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2305]
## Description

For customers who are not using Prometheus, Prometheus conversion tools seem to be an option.  Similiar to the ORM compatibility page, CockroachLabs does not own the other tools.  Should these tools be listed as known to work based on customer feedback and may be listed as alpha support?

## Outline

Sysdig can read Prometheus exporters. https://sysdig.atlassian.net/wiki/plugins/servlet/mobile?contentId=64946336#content/view/64946336

Stackdriver can scrape metrics stored in Prometheus text format from one or multiple components   https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd

## Expected Audience

DevOps and Operations

**Comment by jseldess** [comment]
Supports #2120
