### ISSUE TITLE
Search results page shows nothing while loading, add loading spinner

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#2309]
When searching the docs, the page initially shows the "Was this page helpful" dialog while loading. This makes it look like the search came back empty. It then flashes to the results. This is pretty jarring. We should consider a loading spinner while the search results are loading.

cc. @vilterp

**Comment by vilterp** [comment]
@jseldess, @j-low what do we use for docs search?

**Comment by j-low** [comment]
@vilterp we are using Google Site Search (the paid search engine utilizing [Google Custom Search API](https://developers.google.com/custom-search/docs/overview)).  

Incidentally, GSS will be shut down as of 4/1/18 and we will be implementing a new solution Q1 2018 ahead of the service discontinuation, FWIW.

**Comment by vilterp** [comment]
Cool. Maybe you guys are already looking at it, but [Algolia](https://www.algolia.com/) seems to give a really nice UX. So fast!

**Comment by j-low** [comment]
I'm going to experiment with client-side solutions as well but I think Algolia is my initial favorite of the hosted solutions that I was able to find.  Nice docs in particular.

**Comment by jseldess** [comment]
@gedw99, I don't think we've considered CockroachDB as a viable option for our on-site search, compared to something like Algolia, but @j-low probably has more informed opinions.
