### ISSUE TITLE
Combine SHOW TRANSACTION graphics

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#231]
Given that we have one [`SET TRANSACTION`](https://www.cockroachlabs.com/docs/set-transaction.html) page/graphic covering isolation level and priority, seems like we should consolidate the [`SHOW TRANSACTION ISOLATION LEVEL`](https://www.cockroachlabs.com/docs/show-transaction-isolation-level.html) AND [`SHOW TRANSACTION PRIORITY`](https://www.cockroachlabs.com/docs/show-transaction-priority.html) pages into one page/graphic. 

@mjibson, can you take care of the graphic? I'll then take care of consolidating pages.

**Comment by mjibson** [comment]
This got done.

**Comment by jseldess** [comment]
@mjibson, I don't see a PR covering this, and it looks like we still have distinct graphics for these two `SHOW TRANSACTION` statements. Can you point me to your PR so I can figure out why I'm not seeing this change?

**Comment by mjibson** [comment]
Got confused about something. Will do.
