### ISSUE TITLE
Document interleaved joins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2313]
We’ll use an example with two tables, `parent` and `child` to illustrate the first example.

```
CREATE TABLE parent (pid1 INT, pid2 INT, pid3 INT, PRIMARY KEY (pid1, pid2, pid3))

CREATE TABLE child (
	pid1 INT, 
  	pid2 INT, 
  	pid3 INT, 
  	cid1 INT,  
  	PRIMARY KEY (pid1, pid2, pid3, cid1)
) INTERLEAVE IN PARENT parent (pid1, pid2, pid3)
```

The interleaved prefix of `child` is (pid1, pid2, pid3). This is the argument to the clause at the very end of `CREATE TABLE child`.

The stages are ordered from highest to lowest perceived importance to users:

Stage 0 - Currently:
- INNER joins on the “full interleaved prefix”`
	- e.g. USING (pid1, pid2, pid3)` (or `parent.pid1 = child.pid1 AND parent.pid2 = child.pid2 AND parent.pid3 = child.pid3`) is (the only) join clause supported
	- Any other INNER joins with additional/fewer ON expressions will NOT use interleaved joins
		- e.g. `USING (pid1, pid2)` will NOT use interleaved joins (this defaults to a merge join). See “Stage 2 - Prefix Joins”.
		- e.g. `USING (pid1, pid3)` will NOT use interleaved joins (this defaults to a hash join). See “Stage 5 - Subset Joins”.
		- unless of course the ON expression is elided during index selection/plan generation e.g. `ON parent.pid1 = 5`
- Ancestor-descendant tables
	- if we had a `grandchild` table
		```
		CREATE TABLE grandchild (
			pid1 INT,
			pid2 INT,
			pid3 INT,
			cid1 INT,
			gcid INT,
			PRIMARY KEY (pid1, pid2, pid3, cid1, gcid)
		) INTERLEAVE IN child (pid1, pid2, pid3, cid1)
		```
		- `child JOIN grandchild USING (pid1, pid2, pid3, cid1)` works
		- `parent JOIN grandchild USING (pid1, pid2, pid3)` works
		- so again, only joins on the “full interleaved prefix” work (the interleaved prefix of `grandchild` with respect to `parent` of course excludes `cid`)

Everything below is outstanding:

Stage 1 -  OUTER joins:
- Available after https://github.com/cockroachdb/cockroach/pull/20768 (and another PR that removes the gate on planning)
- OUTER joins on “full interleaved prefix”

Stage 2 - Prefix joins:
- Available after https://github.com/cockroachdb/cockroach/issues/20661 addressed for integrating `streamMerger` into `InterleavedReaderJoiner`
- This will support INNER/OUTER joins on a “prefix of the interleaved prefix” or “prefix join”
	- e.g. `USING (pid1, pid2)` and `USING(pid1)` will both be supported

Stage 1 and stage 2 could make it in for 2.0 (hopefully code-complete by the end of this week/beginning of next week). Stage 3+ will probably be 2.1+ work:

Stage 3.- Multi-table joins:
- Still needs to be fully spec-ed out
- Suppose we had `parent`, `child`, and `grandchild` (see “Stage 0” example). Staggered joins between tables in the same interleaved hierarchy can be optimized using interleaved joins
	- e.g. 
	```
	SELECT … FROM parent
		JOIN (SELECT … FROM child
			JOIN grandchild USING (pid1, pid2, pid3, cid1))
		USING (pid1, pid2, pid3)
	

Stage 4 - Sibling joins:
- Haven’t fully spec-ed this out yet but this is described in the RFC	
- Suppose there was another `child2` table
	```
	CREATE TABLE child2 (
		pid1 INT, 
  		pid2 INT, 
  		pid3 INT, 
  		cid2 INT,  
  		PRIMARY KEY (pid1, pid2, pid3, cid2)
	) INTERLEAVE IN PARENT parent (pid1, pid2, pid3)
	```
	- full, prefix, and subset joins should be supported (since this is an issue of planning and bookkeeping)
		- e.g. `child JOIN child2 USING (pid1, pid2, pid3)` or `child JOIN child2 USING (pid1)`

Stage 5 - Subset joins:
- Available after hybrid merge-hash joins are implemented in `streamMerger` (https://github.com/cockroachdb/cockroach/issues/16580)
- This will support INNER/OUTER joins on a “subset of the interleaved prefix”
	- e.g. `USING(pid1, pid3)` will be supported


One can always do an `SELECT “URL” FROM [EXPLAIN (DISTSQL) SELECT …]` to verify if interleaved joins are being used.

Furthermore, there is a `CLUSTER SETTING sql.distsql.interleaved_joins.enabled` that can be toggled to enable/disable interleaved joins.

**Comment by jseldess** [comment]
Available as of 2.0.

**Comment by jseldess** [comment]
@rmloveland, @awoods187, as you consider prioritizing sql docs backlog, this is probably long-overdue.

**Comment by ericharmeling** [comment]
Interleaved tables are being deprecated. We want to discourage users from using them.
