### ISSUE TITLE
sql: support read-only transactions via PostgreSQL-compatible syntax

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2314]
PR: https://github.com/cockroachdb/cockroach/pull/20547

Adds support for:
- `SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY/READ WRITE;`
- `SET TRANSACTION READ ONLY/READ WRITE;`
- `SET default_transaction_read_only;`
- `SET transaction_read_only;`

**Comment by jseldess** [comment]
For `SET TRANSACTION READ ONLY/READ WRITE;` we need to update [`SET TRANSACTION`](https://www.cockroachlabs.com/docs/dev/set-transaction.html). The sql diagram is already up-to-date, but the feature isn't explained.

For `SET default_transaction_read_only;` and `SET transaction_read_only;` need to update [`SET (session variable)`](https://www.cockroachlabs.com/docs/dev/set-vars.html#supported-variables) and [`SHOW (session variable)`](https://www.cockroachlabs.com/docs/dev/show-vars.html#supported-variables).

Don't think we need to make any updates for `SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY/READ WRITE;`, as we already call out `SET SESSION CHARACTERISTICS AS` as a special-syntax case.

**Comment by jseldess** [comment]
Does the above sound right to you, @jordanlewis?

**Comment by jordanlewis** [comment]
Yes, that sounds correct. `SET TRANSACTION` looks like it already contains some explanations for the default behavior of isolation level - so it seems natural to include the analogous explanation for read-only-ness.
