### ISSUE TITLE
Single source for docs on external storage URLs

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#2339]
Compare:

- https://www.cockroachlabs.com/docs/stable/import.html#import-file-temp-directory-urls
- https://www.cockroachlabs.com/docs/stable/backup.html#backup-file-urls
- https://www.cockroachlabs.com/docs/stable/restore.html#backup-file-urls

All document the same things in slightly different ways. We need either:

1. A common file we include into these docs that we change in only one place.
2. A separate page that these link to.

**Comment by jseldess** [comment]
Good point, @mjibson. @Amruta-Ranade, assigning this to you, for when there's time. I think an include may be easiest.

**Comment by jseldess** [comment]
This is done.
