### ISSUE TITLE
Single-use, non-recursive common table expressions (CTEs) - WITH clause

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2350]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/reclGbRZtI6TME4JT
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171206_single_use_common_table_expressions.md

PRs:
- [sql: single-use common table expression support](https://github.com/cockroachdb/cockroach/pull/20359)

**Comment by knz** [comment]
If that's OK, I'd like to take this over and complement #2762 with this new feature. Does this work for you?

**Comment by lhirata** [comment]
@knz - that's fine with me, as long as @jseldess is ok with it. i haven't started writing anything yet, but have been getting familiar with the topic so i can be the reviewer on this. @jseldess, is that ok? if so, i can take over a different topic.

**Comment by jseldess** [comment]
Fine with me, too. Thanks, @knz! 

@lhirata, let's sync on another 2.0 project you can help with.
