### ISSUE TITLE
BACKUP css auto insertion of dashes on newline results in user confusion

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/docs#2352]
In [Backup File Locations](https://www.cockroachlabs.com/docs/stable/backup.html#backup-file-urls), the short column widths results in dashes being inserted, even in code. So `nodelocal` displays as `node-local`. This is a plausible (but incorrect) keyword, which is confusing. I've attached a screenshot.

![screenshot 2018-01-10 14 05 36](https://user-images.githubusercontent.com/1565833/34790302-66c94e38-f60f-11e7-9b07-1adc28b9c21a.png)

cc @Amruta-Ranade

**Comment by Amruta-Ranade** [comment]
@arjunravinarayan Good catch!

**Comment by jseldess** [comment]
Fixed in the meantime.
