### ISSUE TITLE
Improve ARRAY documentation

### ISSUE THREAD

**Issue by justinj** [cockroachdb/docs#2354]
Exalate commented:

@spencerkimball mentioned that using arrays from Go can be quite confusing: with lib/pq you need to wrap your arguments in `pq.Array` (see [this link](https://www.opsdash.com/blog/postgres-arrays-golang.html)), and the error you get if you don't do that very much resembles a pgwire bug (at least to my eyes) and doesn't help you discover the problem. We should consider documenting this.

Additionally, he pointed out that we don't have a link from the array page to the array functions page. Our array function documentation is actually not great at the moment, which is a limitation of our type system (we don't support generic functions, leading to duplicated entries in the documentation). We should figure out a good solution to give users visibility into what functions are available on arrays.

cc @Amruta-Ranade @jseldess

**Comment by justinj** [comment]
@awoods187 pointed out we should also do this for JSONB

**Comment by awoods187** [comment]
I think this is definitely needed

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
