### ISSUE TITLE
Improve EXPLAIN docs

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2362]
Nate Stewart (nstewart) commented:

- [ ] Add clear description of what a plan shows. It's not clear how to read plans. For example, in this plan: https://www.cockroachlabs.com/docs/stable/explain.html#default-query-plans it would be useful to have a plain English description of what the plan is showing. That will make this easier to grok. 
- [ ] Define what spans are (a pair of start,end keys).
- [ ] Add solution/user experience-oriented examples, including guidance on reducing levels of planning required (probably with a `JOIN` example).

**Comment by Amruta-Ranade** [comment]
@CMajeri Hi there! I am planning on taking this up post-release in April. Will keep you posted.

**Comment by rmloveland** [comment]
Via @knz from #4414 which I've just closed in favor of this issue since it overlaps.

> Clarify / over-explain in the reference docs (i.e. not only guides) that the "spans" entry in EXPLAIN for a scan is about read performance (it's not obvious), and spell out over and over that "ALL" is not good

**Comment by awoods187** [comment]
Lets do this as a part of the explain work for 20.2

**Comment by ericharmeling** [comment]
@ianjevans This might be fixed by your work in the last release?

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
