### ISSUE TITLE
distsql session variable is poorly documented

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/docs#2364]
I noticed we don't have good documentation for the `distsql` session variable. It's not mentioned at all in [`set-vars.md`](https://github.com/cockroachdb/docs/blob/master/v2.0/set-vars.md) and is listed without a description in [`show-vars.html`](https://github.com/cockroachdb/docs/blob/master/v2.0/show-vars.md).

**Comment by lhirata** [comment]
Related to #3717
