### ISSUE TITLE
Code blocks must not be hyphenated automatically

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#2372]
See for example:

![schermafdruk_2018-01-19_18-26-43](https://user-images.githubusercontent.com/642886/35163242-5e7afd42-fd46-11e7-9cc0-03622e84eea1.png)

The SE-LECT is hy-phe-na-ted. No good, it makes copy-pasting impossible.

cc @jseldess @j-low

**Comment by j-low** [comment]
Addressed in #2404.  Closing issue.
