### ISSUE TITLE
Document \debug pages

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2373]
Based on https://github.com/cockroachdb/cockroach/issues/20690, we'll expose 4 `/debug` pages to users in 2.0. We should add docs on how to understand and use these pages:

- **Node Diagnostics** page: "I want to know how my nodes are configured"
- **Problem Ranges** report: "I want to know which ranges are causing problems"
- **Network Diagnostics** page: "I want to know if my nodes can talk to each other on the network"
- **Certificates** page: "I want to check if my certificates are configured properly"

**Comment by jseldess** [comment]
@Amruta-Ranade, can you please set up a meeting with @dianasaur323 and myself to discuss what's needed here?

@dianasaur323, is this represented on the 2.0 roadmap? If so, can you send me that link. Also, can you help identify the devs who are experts on each of the 4 debug pages? We probably want to have them in the meeting.

**Comment by dianasaur323** [comment]
Do we still want a meeting here? I'm heading out on Friday! That being said, you can always book me while I'm out during one of my 9-12 open slots marked on my calendar

**Comment by Amruta-Ranade** [comment]
As discussed with Josue, not a priority for 2.0

**Comment by dianasaur323** [comment]
cc @piyush-singh since we just talked about this

**Comment by jseldess** [comment]
Replaced by https://github.com/cockroachdb/docs/issues/2373.
