### ISSUE TITLE
Add functions for postgres compatibility

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2386]
From release notes:

> The following built-in functions are now supported: pg_catalog.pg_trigger(), pg_catalog.pg_rewrite(), pg_catalog.pg_operator(), pg_catalog.pg_user_mapping(), pg_catalog.foreign_data_wrapper(), pg_get_constraintdef(), inet_client_addr(), inet_client_port(), inet_server_addr(), inet_server_port()

PRs:
- https://github.com/cockroachdb/cockroach/pull/21065
- https://github.com/cockroachdb/cockroach/pull/20788

**Comment by jseldess** [comment]
@jordanlewis, do you know why these don't don't show up in our auto-generated function docs?

**Comment by jordanlewis** [comment]
Those are virtual tables, not builtins!

**Comment by jseldess** [comment]
Oh! Thanks for clarifying.

**Comment by jseldess** [comment]
We don't explicitly document `pg_catalog` virtual tables at the moment, so closing this.
