### ISSUE TITLE
sql: new SHOW SYNTAX statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2392]
From release notes:

> The new SHOW SYNTAX statement allows clients to analyze arbitrary SQL syntax server-side and retrieve either the (pretty-printed) syntax decomposition of the string or the details of the syntax error, if any. This statement is intended for use in the CockroachDB interactive SQL shell.

PR: https://github.com/cockroachdb/cockroach/pull/19793

**Comment by jseldess** [comment]
Need to add a new SQL statement page for this. We should also call it out in the description of the [`check_syntax` option](https://www.cockroachlabs.com/docs/dev/use-the-built-in-sql-client.html#sql-shell-options) for `cockroach sql` shell.

**Comment by couchand** [comment]
It sounds like we're choosing not to document this particular statement.
