### ISSUE TITLE
sql: permit table alias use in RETURNING clauses

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2398]
PR: https://github.com/cockroachdb/cockroach/pull/20808

**Comment by jseldess** [comment]
We could update the `RETURNING` parameter description on:
- [`INSERT`](https://www.cockroachlabs.com/docs/dev/insert.html#parameters)
- [`UPSERT`](https://www.cockroachlabs.com/docs/dev/upsert.html#parameters)
- [`UPDATE`](https://www.cockroachlabs.com/docs/dev/update.html#parameters)
- [`DELETE`](https://www.cockroachlabs.com/docs/dev/delete.html#parameters)

**Comment by knz** [comment]
I have reviewed the docs for this. The documentation for AS and RETURNING is already very clear -- the name specified in AS hides the original table name completely, so there is no expectation that RETURNING sees it.

Closing this because I do not believe anything needs to be changed.
