### ISSUE TITLE
sqlccl: include http's configured custom CA setting when using custom s3 endpoints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2400]
From release notes:

> When using HTTPS storage for IMPORT/BACKUP/RESTORE, a custom CA for HTTPS storage providers can now be specified via the cloudstorage.http.custom_ca cluster setting. This is also used when accessing custom s3 export storage endpoints.

PR: https://github.com/cockroachdb/cockroach/pull/21404

**Comment by Amruta-Ranade** [comment]
Need to create a separate page for storage, with sections for each external storage provider. For each provider, we can document their options.

*this* option should just link to the proposed section on HTTP storage where we doc custom certs.
