### ISSUE TITLE
Clarify two-phase transaction protocol

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2405]
Re: [Transaction Layer](https://cockroachlabs.com/docs//v1.1/architecture/transaction-layer.html)

## Issue Description
In this page we have the following sentence:
> Because CockroachDB enables transactions that can span your entire cluster (including cross-range and cross-table transactions), it optimizes correctness through a two-phase commit process

As far as I know, we don't use two-phase commits? Can someone clarify what we are saying here?

**Comment by nstewart** [comment]
cc @bdarnell

**Comment by bdarnell** [comment]
[Two-phase commit](https://en.wikipedia.org/wiki/Two-phase_commit_protocol) (2PC) is a specific distributed transaction protocol. Our transactions do operate in two phases, but our protocol isn't exactly 2PC. I'd call it "a two-phase transaction protocol".

**Comment by jseldess** [comment]
Additional details form chat in another channel:

> Jesse: in regards to `two-phase transaction protocol`: We describe cleanup as a third phase, so should we say `three-phase transaction protocol`? Or `two-phase transaction protocol with asynchronous cleanup` or something?

> Ben: the latter, i think. it's important to describe it as two-phase to convey that two round trips are required from the client's perspective
