### ISSUE TITLE
Code spans should not have custom bg in titles

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#2407]
From https://github.com/cockroachlabs/hugo-website/issues/316

`<code>` spans should be rendered with a monospace font of the proper height, and no particular background, when they are present in titles.

![schermafdruk_2018-01-19_17-32-52](https://user-images.githubusercontent.com/642886/35161869-c6d067ec-fd41-11e7-9b40-784f2f857714.png)

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2251%3A10375

**Comment by elkmaster** [comment]
@luciaaaaaaa, in original issue said that code items in titles should have "no particular background", but in figma I see codespan with bg:
![Screenshot 2020-11-12 at 20 36 27](https://user-images.githubusercontent.com/12850886/98981550-c50ed280-2526-11eb-9478-bdc9da1c92eb.png)

**Comment by anagio** [comment]
@luciaaaaaaa should this follow figma or should background be removed?
