### ISSUE TITLE
Transition from Local to Regional to Global Topology

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2408]
## Title

Migration from Single Datacenter to Regional and Global Locality

## Description

It is common to start functional testing in a single data center.  A single data center deployment provides logical high availability by having 3 or more CockroachDB nodes. 

```
A---C
 \ / 
  B
```

A pilot testing then expands to regional or global cluster topology.    The expansion enables users to take advantage of advanced features such as follow-the-workload and zero-RPO.

```
A---C         A---C
 \ /           \ /
  B             B
  East------West
     \     /  
      \   /  
       \ /  
    Central 
     A---C   
      \ / 
       B
```

## Outline

Assume a cluster has been set up following the documentation without the `--locality` flag
- The West locality has the 3 copies of the replica 
- shutdown the cluster (stop all of the nodes)
- assume this cluster will be assigned the `--locality=region=west`
Restart the West cluster with the `--locality=region=west`

Setup the Central and East localities
- start the east cluster with `--locality=region=east`
- start the central cluster with `--locality=region=central`

Replica distribution
West has all 3 replicas initially
Over time, the replicas will be distributed to the Central and East

## Expected Audience

Developers and DBA

**Comment by bdarnell** [comment]
There is no need to stop all of the nodes in the first DC at once - the first `--locality` flag can be added with a rolling restart.

**Comment by jseldess** [comment]
@robert-s-lee, @nstewart, this could be a good tech demo in addition to tutorial.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
