### ISSUE TITLE
change backup / restore examples for 2.0

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#2410]
We just implemented RESTORE DATABASE, which allows users to restore even if the database does not exist. We need to change our code examples going into 2.0.

cc @dt

**Comment by dt** [comment]
Indeed, I think `BACKUP DATABASE` and `RESTORE DATABASE` should be our default examples except where we specifically want to show specific tables.

**Comment by jseldess** [comment]
Thanks, @dianasaur323 and @dt. We have another ticket on this already open and assigned to @Amruta-Ranade: https://github.com/cockroachdb/docs/issues/2067. 

I just added your comments to that issue. Closing this as a duplicate.
