### ISSUE TITLE
Basic topology patterns

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2411]
## Title

An illustration of common topology patterns 

## Description

A library of common topology patterns.   Can start from a simple local topology and transition to other patterns to meet the requirements.

### Local Topology

3 or more nodes are recommended to provide HA, share the load and spread the capacity.   Dynamically scaling out the nodes from 3 to 4, 4 to 5, or any other intervals is supported.  There are no constraints on the server increments.  Local deployment is a single data center deployment.  The network latency among the nodes is expected to be the same and about 1ms range.

The diagram below depicts a node as a letter (A, B, C, D, E ...)

```
A------C         A-----C           A-----C
 \    /  online  |     |  online   | \ / |
  \  /   ------> |     |  ------>  |  E  |
   \/            |     |           | / \ |
   B             B-----D           B-----D 

```

### Regional Topology
 
Each region defines an availability zone.  3 or more regions are recommended.  Similiar to the Local Topology, more regions can be added dynamically.   It is recommended to have homogenous configuration among the regions for simplified operations.  For sophisticated workloads, each region could have different node count and node specification.  This heterogeneous configuration could better handle regional specific concurrency and load characteristics.    The network latency among the regions is expected to be linear to the distance among the nodes.  T

The diagram below depicts asymmetrical setup where the Central is closer to the West than the East.   This configuration will provide better write latency to the write workloads in the West and Central.

```
A---C         A---C
 \ /           \ /
  B             B
  West---80m---East
     \         /  
    20ms    60ms  
       \    /
        \  /
         \/
       Central 
        A---C   
         \ / 
          B

```

### Global Topology

The global topology connects the multiple regional topologies together to form a single database that is globally distributed.  Transactions are globally consistent.  

```
    West-----East            West-------East
       \      /                \        /
        \Asia/                  \Europe/
         \  /                    \  /
          \/                      \/
        Central                 Central
                Asia------Europe
                   \     /  
                    \   /  
                     \ /  
                   Americas 

               West---------East
                  \          /
                   \Americas/  
                    \      /
                    Central 

```

### High-Performance Regional
Some applications have high-performance requirements.  NJ and NY in the below diagram depict two separate data centers that are connected by a high bandwidth low latency network.  In this topology, NJ and NY have the performance characteristics of the local topology, but the benefit of Zero RPO and near Zero RTO disaster recovery SLA.  CA and NV have been set up with a network capability.   The central region serves as the quorum. 
 
```
   NJ ---1ms--- NY
     \       /  
     20ms  20ms  
        \  /
         \/  
       Central 
         /\  
        /  \
     20ms  20ms  
     /       \  
  CA ---1ms--- NV

```

### n-tier architecture

Modern n-tier architecture is simplified as App and DB layers in the below diagram.   A client connects to geographically close app server via GSLB.   The app servers connect to one of the CockroachDB nodes within their geography via local balancer.  A software-based load balancer, HAProxy, located on the app server, the configuration is provided by CockroachDB.  A Network-based load balancer can also be used.

```
         Clients
           |
          GSLB
           |
  +--------+---------+
West    Central    East
  |        |         |
 App  |   App   |   App
 ---  |   ---   |   ---    
  LB  |    LB   |    LB
      |         |

  West---Central ---East
    \               /
     \ CockroachDB /  
      -------------

```

## Expected Audience

Architects, Developers, DBA, Operations

**Comment by jseldess** [comment]
See @bdarnell's comment here: https://github.com/cockroachdb/docs/pull/2312#issuecomment-360858702

Need to clarify that replication factor and # of nodes is distinct.

**Comment by jseldess** [comment]
Partially addressed in https://github.com/cockroachdb/docs/pull/2850. Moving further work to 2.1.

**Comment by jseldess** [comment]
Also:

# Performance Patterns: Leveraging Partition Feature

The patterns assume the following:
- Understand the function of [CockroachDB Leaseholder](https://www.cockroachlabs.com/docs/stable/architecture/replication-layer.html#leases)
- Understand the impacts of the [leaseholder](https://github.com/cockroachdb/docs/issues/2300#issuecomment-354326834
) on read and write activities
- The leaseholders are local to reader and writers within the data center
- The leaseholder migration among the data centers is minimized using the partitioning feature
- Follow-the-workload tunable is set to properly for the workload
- Application is designed to use the [partitioning feature]()

## Symmetrical

During normal operations:

```
App                App
 \                  /
West ---60ms--- East
     \        /  
     60ms   60ms  
        \   /
         \ /  
       Central 
          |
         App
```

CockroachDB Replicas and Leaseholders:
- rows with the West partition will have the leaseholder in the West DC, the Central partition in the Central DC, and the East partition in the East DC
- the 3 replicas will be evenly distributed among the three data centers

Availability expectations:
- Can survive a single data center failure

Performance expectations:
- The reader can expect to have a couple of ms response time. 
- The writers can expect to have 60ms response time. 
- The latency among the data centers is symmetrical 60ms.

Application expectations:
- West App servers connect to the West CockroachDB nodes
- Central App servers connect to the Central CockroachDB nodes
- East App servers connect to the East CockroachDB nodes


CockroachDB configuration:

Abbreviated startup flag for each data center.
```
--loc=Region=East
--loc=Region=Central
--loc=Region=West
```

## Dual East DCs 

During normal operations:

```
App                App
 \                  /
West ---60ms--- East1
     \           |
       \        5ms
        60ms     |
           \____East2 
```

CockroachDB Replicas and Leaseholders:
- rows with the West partition will have the leaseholder in the West DC, the East partition in the East DC1
- the 3 replicas will be evenly distributed among the three data centers


Availability expectations:
- Can survive a single data center failure

Performance expectations:
- The reader can expect to have a couple of ms response time. 
- The East writers can expect to have 5ms response time. 
- The West writers can expect to have 60ms response time. 

Application expectations:
- West App servers connect to the West CockroachDB nodes
- East App servers connect to the East1 CockroachDB nodes


CockroachDB configuration:

Abbreviated startup flag for each data center.
```
--loc=Region=East,DC=1
--loc=Region=East,DC=2
--loc=Region=West
```

## Dual East and West DCs

During normal operations:

```
App                App
 \                  /
West1 ---60ms--- East1
  |   \        /   |
  5ms  - 60ms -    5ms
  |   /        \   |
West2----60ms----East2 
```


CockroachDB Replicas and Leaseholders:
- rows with the West partition will have the leaseholder in the West DC1, the East partition in the East DC1
- West partitions will have 1 replica each in West1 and West2, then 1 replica in East1 or East2
- East partitions will have 1 replica each in East1 and East2, then 1 replica in West1 or West2


Availability expectations:
- Can survive a single data center failure

Performance expectations:
- The reader can expect to have a couple of ms response time. 
- The writers can expect to have 5ms response time. 

Application expectations:
- West App servers connect to the West CockroachDB nodes
- East App servers connect to the East CockroachDB nodes


CockroachDB configuration:

Abbreviated startup flag for each data center.

```
--loc=Region=West,DC=1
--loc=Region=West,DC=2
--loc=Region=East,DC=1
--loc=Region=East,DC=2
```

## Summary

| Topology | West | Central | East |
| -- | -- | -- | -- |
| Symmetrical  | Read local, Write 60ms| Read local, Write 60ms | Read local, Write 60ms |
| Dual East | Read local, Write 60ms|  | Read local, Write 5ms |
| Dual East and West | Read local, Write 5ms|  | Read local, Write 5ms |

**Comment by jseldess** [comment]
For 2.1, this is part of https://github.com/cockroachdb/docs/issues/2935.
