### ISSUE TITLE
Locality-aware load balancing

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2413]
## Title

Locality aware haproxy configuration

## Description

When locality is enabled, haproxy should be setup to load balance on the database nodes within the same locality as the app servers first.  If all of the nodes this preferred locality is down, then try databases in other localities.

For a regional topology depicted in the below diagram:
 
- the West app servers should connect to the West CockroachDB servers.
- the Central app servers should connect to the Central CockroachDB servers.
- the East app servers should connect to the East CockroachDB servers.

```
         Clients
           |
          GSLB
           |
  +--------+---------+
West    Central    East
  |        |         |
 App  |   App   |   App
 ---  |   ---   |   ---    
  LB  |    LB   |    LB
      |         |

  West---Central ---East
    \               /
     \ CockroachDB /  
      -------------
```

## Expected Audience

DBA, Network, DevOps

**Comment by jseldess** [comment]
For 2.1, this is part of https://github.com/cockroachdb/docs/issues/2935.

**Comment by jseldess** [comment]
This is covered by https://www.cockroachlabs.com/docs/dev/cluster-topology-patterns.html#multiple-regions-basic-pattern. However, we still need guidance on how to set up haproxy to do this. See https://github.com/cockroachdb/docs/issues/4388.
