### ISSUE TITLE
A Simple Database HA Test Pattern

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2414]
## Title

A Simple Database HA Test Pattern

## Description

https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html has steps.  Addition of diagram patterns will aid in the comprehension.  As sophisticated database topology is difficult to grasp and starting from a simple diagram and expanding will help users learning path.  

## Outline

A separate library of patterns that links back to the page would be helpful.

App is an application that access CockroachDB.
HA-Proxy is a software based load balancer.
1, 2, and 3 represents a CockroachDB node.

```
Normal operating mode

      App
       |
    HA-Proxy
  /    |    \ 
 /     |     \
1------2------3 
 \___________/ 
         
Node 1 is down.  Database and app are fully operational.

      App
       |
    HA-Proxy
  /    |    \ 
 /     |     \
x------2------3 
 \___________/ 

Node 2 is down.  Database and app are fully operational.

      App
       |
    HA-Proxy
  /    |    \ 
 /     |     \
1------x------3 
 \___________/ 


Node 3 is down.  Database and app are fully operational.

      App
       |
    HA-Proxy
  /    |    \ 
 /     |     \
1------2------x 
 \___________/ 
```

## Expected Audience

App, DevOps, DBA

**Comment by jseldess** [comment]
For 2.1, this is part of https://github.com/cockroachdb/docs/issues/2935.
