### ISSUE TITLE
storage/ui: add metric and graphs for node liveness heartbeat latency

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2419]
PR: https://github.com/cockroachdb/cockroach/pull/21002

From release notes:
> Added graphs of node liveness heartbeat latency, an important internal signal of health, to the Distributed dashboard.

**Comment by Amruta-Ranade** [comment]
We don't document the **Distributed** dashboard, since it is used primarily for internal use. Moving it to 2.1 in case we decide to document it then.

**Comment by Amruta-Ranade** [comment]
We still haven't documented Distributed dashboard. We might move the node liveness graph to another dashboard as part of the "reorganizing dashboards" project. Punting this issue till the reorg.

**Comment by jseldess** [comment]
@Amruta-Ranade, that reorg will be captured by another issue, I'm sure, so feel free to close this one.

**Comment by Amruta-Ranade** [comment]
SGTM!
