### ISSUE TITLE
sql: don't allow StatementSources to commit the txn

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2425]
PR: https://github.com/cockroachdb/cockroach/pull/20847

From release notes:
> INSERT/UPDATE/DELETE ... RETURNING statements used with the "statement data source" syntax (e.g., SELECT * FROM [INSERT INTO ... RETURNING ...]) no longer ever commit the transaction, causing errors for the higher-level query.

Note from @andreimatei: this introduces a limitation to SHOW TRACE FOR <stmt> that we might want to document.

**Comment by jseldess** [comment]
@andreimatei, do we just need to update [`SHOW TRACE`](https://www.cockroachlabs.com/docs/dev/show-trace.html)? Or are we more generally missing docs on "statement data source" syntax?

**Comment by jseldess** [comment]
@andreimatei, @knz, ping.

**Comment by knz** [comment]
From my perspective the release note is incorrect, because the transaction is indeed commited. @andreimatei ?

**Comment by knz** [comment]
Ok I stand corrected, the release note is correct. 

The following paragraph must be added to the sub-section "SHOW TRACE FOR <stmt>":

"""
When using SHOW TRACE FOR <stmt> with a statement that writes data (e.g. INSERT, etc) outside of an explicit transaction (BEGIN...COMMIT) the changes performed by the statement are not committed. To both observe a trace for these statements and also commit the results, either use BEGIN ... COMMIT, or use SHOW TRACE FOR SESSION as described below.
"""

**Comment by andreimatei** [comment]
Just to make sure we're all on the same page - when you do `SHOW TRACE FOR <stmt>`, outside of a txn, the data is committed; it's just that the 1PC optimization is disabled for the <stmt>, which means that the trace can look quite different from what might happen if <stmt> is a write and it'd be run by itself.

This also applies to statement data sources (and I hope CTEs too), but that probably doesn't need to be documented. Or at least I don't think we discuss 1PC anywhere.

**Comment by knz** [comment]
Aw thanks andrei for the correction. My initial comment above was wrong, corrected now.
