### ISSUE TITLE
sqlccl: support INCREMENTAL BACKUP of added/changed tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2427]
PR: https://github.com/cockroachdb/cockroach/pull/21170

From release notes:
> Incremental backups of a database after a table or index was added is now supported.

I think this affects the last bullet here: https://www.cockroachlabs.com/docs/dev/backup.html#incremental-backups

@dt, does this also impact this known limitation? https://www.cockroachlabs.com/docs/dev/known-limitations.html#enterprise-restores-after-creating-dropping-or-truncating-tables

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/issues/34099#issuecomment-456174154 pointed out we still mention this in some of the docs

**Comment by dt** [comment]
pretty sure this got fixed a while ago.

**Comment by jseldess** [comment]
@dt, aren't the docs still wrong here? https://www.cockroachlabs.com/docs/stable/backup.html#incremental-backups

> It is not possible to create an incremental backup if one or more tables were created, dropped, or truncated after the full backup. In this case, you must create a new full backup.

**Comment by dt** [comment]
oh, ugh, yeah. I searched the page for "schema" and "change" but somehow missed that.

**Comment by dt** [comment]
whoops, this one got lost in the shuffle and a customer just noticed that this known limitation is still in there.

**Comment by dt** [comment]
Managed just hit / started working based on this out-of-date "known limitation" last week, and we've had a couple customers ask about this recently too.

**Comment by jseldess** [comment]
Sorry for the delay, @dt. Taking care of this now.
