### ISSUE TITLE
Update docs on node draining

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#2436]
Re: [Stop a Node](https://cockroachlabs.com/docs//v1.1/stop-a-node.html)

Our nodes do a couple of dances when they're being shut down so that impact on running queries, and on clients continuously sending queries, is minimized. The behavior and the timeouts involved should be documented. I think @asubiotto has become the expert.

**Comment by jseldess** [comment]
@andreimatei, I think this is documented at a high-level under ["how it works"](https://www.cockroachlabs.com/docs//v1.1/stop-a-node.html#how-it-works). Definitely interesting in making this more detailed, though.

**Comment by asubiotto** [comment]
We could enhance that with an explanation of what happens to client connections and in-flight queries (some work being done on the distsql side of things: https://github.com/cockroachdb/cockroach/pull/20450)

**Comment by jseldess** [comment]
Also involves documenting the new `server.drain_max_wait` cluster setting, which sets the max amount of time to wait for distributed queries to finish before the node starts draining.
