### ISSUE TITLE
Part 1: Document SQL Conformance and Postgres Compatibility

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2444]
Added a page with full list of SQL standard features with CockroachDB support level for each. Based on [how Postgres does this](https://www.postgresql.org/docs/8.3/static/unsupported-features-sql-standard.html).

For part 2, see https://github.com/cockroachdb/docs/issues/2467

**Comment by Amruta-Ranade** [comment]
Added full list of SQL standard features with CockroachDB support level for each (#2442)

**Comment by jseldess** [comment]
Page is live at https://www.cockroachlabs.com/docs/dev/detailed-sql-support.html
