### ISSUE TITLE
Remove experimental flag for IMPORT

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#2445]

**Comment by jseldess** [comment]
@Amruta-Ranade, does this tie into [this roadmap item](https://github.com/cockroachdb/docs/issues/2055)?

**Comment by jseldess** [comment]
When you document this, can you sync with @mjibson to make sure we capture the major changes/improvements to IMPORT for 2.0?

**Comment by mjibson** [comment]
After I get my bugs fixed I'm planning on reading through the import document and either sending PRs or opening issues to describe its current status. So yes, this will happen.

**Comment by jseldess** [comment]
This is supplanted by https://github.com/cockroachdb/docs/issues/2599. Looks like we want to call this out as "beta" for 2.0.

**Comment by mjibson** [comment]
This is getting done in #2676.
