### ISSUE TITLE
Backup runbook

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2447]
## Title

Runbook for backup

## Description

Typical operational commands to back up the database 

## Outline

- The full backup should be taken during the least busy hour of the week.  
- The incremental backup is usually taken during the least busy hour of the day. 
- A full backup usually takes longer than an incremental.
- The duration of the backup is dependent of the database size, number of nodes in the cluster, and destination storage’s performance characteristics.  Perform a test to establish expected full and incremental backups durations.

### On Linux

- Cron or similar can used to schedule a backup.
- If using Cron, only one node in the cluster should have the crontab to initiate the backup  
- Below is an example Cron entry for full backup:

```
0 1 * * 6 root ts=$(date -u '+%Y-%m-%d %H:%M:%S'); tsdir=/tmp/full$(echo $ts | tr '[ :]' '-'); mkdir tsdir; echo "backup test.* to 'nodelocal:$tsdir' as of system time '$ts';" | cockroach sql --insecure
```

- Incremental backup example

- [ ] save full backup and incremental in a table 
- [ ] pickup the previous backup and incremental from the table
- [ ] build incremental backup command by using the previous step
 
## Expected Audience
DBA, DevOps

**Comment by jseldess** [comment]
Suggestions from @dianasaur323:
- Cover, full, incremental, point-in-time
- Examples of chron jobs you would write
- K8 backup/restore

PM cluster on DO: each node has chron job for backup/restore.
- [Scripts here](https://github.com/cockroachlabs/pm/tree/master/pm-cluster)

We should probably loop this into our `systemd` project.
