### ISSUE TITLE
Starting client-only node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#245]
From Gitter thread. Not sure where these details might best live (troubleshooting?).

---

When doing PG connection pooling with Cockroach, should I have my app server connect to a single Cockroach instance in the cluster with multiple connections, or should I be doing one-or-more connections per Cockroach instance and round-robin scheduling, or…?
I have many app server instances (stateless, like a typical HTTP server)

kena @knz 13:46
Load balancing is probably appropriate
A TCP load balancer is known to work

Matt Jibson @mjibson 13:47
another approach is to host your database and application on the same machine. your app always connects to localhost. spin up more nodes as needed and connect to existing ones to make a cluster

RaduBerinde @RaduBerinde 13:47
^ Yeah. You can make the client a node as well, even if it doesn't actually store any data

David Taylor @dt 14:01
hm, would a very large number of 0 store nodes clutter gossip?

Andrei Matei @andreimatei 14:02
I guess, but on the flip side you get the benefit of the leader cache close to the client
but I agree that this no-storage node idea doesn’t seem fully thought through

David Taylor @dt 14:03
obviously we could optimize it a bit, I just don’t think we’ve done that

Erich Ocean @erichocean 14:05
I load balance prior to hitting my application servers, so it sounds like co-locating the app server and a Cockroach instance is the way to go, and then having my PG connection pool only connect to Cockroach over localhost.

David Taylor @dt 14:08
If that ends up being a common deployment pattern, we might want to optimize for those client-only nodes so that the cluster doesn’t have to maintain gossip/heartbeat/etc information about them

Erich Ocean @erichocean 14:11
for client-only Cockroach, do I just pass --store=type=mem,size=0% at startup?

Tamir Duberstein @tamird 14:11
i think it won’t let you
there’s a minimum store size IIRC

Erich Ocean @erichocean 14:18
hmm, so how does one launch a client-only node then?
FWIW, the way RethinkDB handles this is with a special "proxy" binary that's more-or-less a client-only node

Tobias Schottdorf @tschottdorf 14:20
I don’t think it’s currently possible. This type of deployment is clearly planned, but we don’t actually have it running.

jseldess @jseldess 14:22
Based on error messages, seems like currently you have to give it a minimum storage size of 640MiB:
JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach start --store=type=mem,size=640MiB
build:     beta-20160428-94-g1b81f2c @ 2016/05/02 15:00:43 (go1.6)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      /var/folders/5t/1rt6nzr17sjg87mz5n0fw15c0000gn/T/
store[0]:  type=mem,size=640 MiB

Erich Ocean @erichocean 14:26
okay, no worries then

**Comment by bdarnell** [comment]
Adding a memory store (with non-zero size) is dangerous: ranges will be rebalanced onto it (unless you're careful with zone configs), and be vulnerable to data loss. We need to support running with no stores for a client-only proxy. (and we should probably also suppress the generation of a node id and turn off any gossip).

Security for such a proxy is tricky - it would need certificates for the `node` user, which gives it full access to the cluster. This seems like an unacceptable risk for any multi-tenant cluster. 

For now we should definitely be steering people towards network-level solutions (dns round-robin, haproxy, etc), or maybe something that understands the postgres protocol like pgbouncer.

**Comment by jseldess** [comment]
Thanks, Ben. Wonder if we should add some details to the "Recommendations" section of [Manual Deployment](https://www.cockroachlabs.com/docs/manual-deployment.html#recommendations)? Or we could create a standalone topic on this. @mberhault, any opinions?

**Comment by mberhault** [comment]
Client-only nodes are really not a thing right now, but we probably do want a story eventually.
What is doable is running a node on the same machine as the client, but it will have the same security requirements as a regular node (certificates in secure mode). The only advantage it provides is that the client can use `localhost` to reach cockroach.

**Comment by jseldess** [comment]
OK, in addition to that approach, should we call out using network-level solutions like the ones Ben mentions?

**Comment by jseldess** [comment]
Closing this for now, until we have an approach, or stronger recommendations, for client-only nodes.
