### ISSUE TITLE
Enhanced SQL query logging (audit/exec logs)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2451]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/rec6Iz3phO10L7NeQ

PRs: https://github.com/cockroachdb/cockroach/pull/22534

**Comment by jseldess** [comment]
@knz, @dianasaur323, please let me know when we have an issue scoping/tracking the product work.

**Comment by knz** [comment]
> @knz, @dianasaur323, please let me know when we have an issue scoping/tracking the product work.

I do not understand this request?

**Comment by jseldess** [comment]
@knz, I just meant an issue in the cockroach repo.

**Comment by dianasaur323** [comment]
Already slacked this to @jseldess, but for longevity's sake: https://github.com/cockroachdb/cockroach/pull/22534
