### ISSUE TITLE
Connecting to a secure cluster inside Kubernetes

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#2458]
From @caseyh on gitter:

> Can anyone point me to docs on best practices to get credentials for applications running on k8s accessing cockroachdb on k8s w/ secure setup? The best path I can think of is to follow the path of the default.client.root request signing via the initContainer and storing that key & certs in a secret for the app?
> 
> [...]
> 
> So regarding docs that one is great for getting a cluster up but the "what's next" of adding a table and authorizing an application to access that table takes a little digging. I find the readme in cockroachdb/cloud#accesing-the-database to get me closer but ultimately the docs themselves don't get you to app hooked up to db but reading the client-secure.yaml config presents one route to generating client certs where kubernetes is handling signing csrs. So I think I'll aim that direction.

It's true that we don't provide much guidance on how to manage client certificates.

**Comment by dt** [comment]
Piling on here:
- We have an example of connecting via running the shell in k8s, but it'd be nice to show how one might connect to the k8s cockroach cluster from an existing app.
- nit: as far as i can tell, we assume the cluster name is "cockroachdb", both in the command line args and in our provided yaml files. We may want to note how/what to replace if you name it something else.

**Comment by a-robinson** [comment]
> We have an example of connecting via running the shell in k8s, but it'd be nice to show how one might connect to the k8s cockroach cluster from an existing app.

You've probably figured this out by now, but in case you haven't, connect to it using `cockroachdb-public` as the hostname and 26257 as the port.

> nit: as far as i can tell, we assume the cluster name is "cockroachdb", both in the command line args and in our provided yaml files. We may want to note how/what to replace if you name it something else.

Sorry if I'm misunderstanding you, but the YAML files don't care at all about the name of the Kubernetes cluster. They create resources named cockroachdb inside of the Kubernetes cluster, but that's independent of what the Kubernetes cluster is named.

Using a different name for the GKE cluster in the docs walkthrough may make things clearer.

**Comment by dt** [comment]
> You've probably figured this out by now, but in case you haven't, connect to it using cockroachdb-public as the hostname and 26257 as the port.

That still uses the k8s network layer though, right? I was thinking if I wanted to connect to my new cockroach cluster from *outside* k8s, i.e. from some existing, deployed-on-bare-metal app.

**Comment by a-robinson** [comment]
> That still uses the k8s network layer though, right?

Correct, you have to be inside the cluster to do that.

**Comment by nickjackson** [comment]
I was just wondering if you have any suggested methods for this at the moment?

I've noticed that [example-app-secure]( https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/example-app-secure.yaml) utilises `request-cert` which is fine in the context of running a single pod, but I don't think this will work when having multiple replicas.

Would your advise be to run `request-cert` as a job first and then consume the secret/certs it generates?

Thanks,
Nick.

**Comment by a-robinson** [comment]
What don't you think works when there are multiple replicas? When I've tested before it's worked fine, although it's possible that if you start them all before the certificate has been created/approved that some of them will fail in the init stage before the certificate has been approved and have to retry.

So if you don't mind the extra yaml in your client pods, it's fine to use `request-cert`. However, I understand it's a lot of yaml to add. Just running it once and using the secret that it creates more directly is also totally fine. That's all that `request-cert` does once the secret exists anyway.

**Comment by nickjackson** [comment]
Ahh, I slightly misunderstood how `request-cert` worked. That all sounds good to me.

**Comment by jseldess** [comment]
Need to add steps for connecting to a secure cluster with non-`root` users, based on the steps documented here: https://github.com/cockroachdb/cockroach/pull/29996/files.

**Comment by jseldess** [comment]
Closing in favor of single issue: https://github.com/cockroachdb/docs/issues/2938
