### ISSUE TITLE
Deploy a Test Cluster - can now select load generator from tempate 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2460]
Re: [Deploy a Test Cluster](https://cockroachlabs.com/docs//v1.1/deploy-a-test-cluster.html)

In https://github.com/cockroachdb/cockroachdb-cloudformation/pull/8 we now let users select the load generator directly in the template. No need to download a separate loadgen.

**Comment by jseldess** [comment]
Thanks for filing, @nstewart.

**Comment by jseldess** [comment]
Need to update the **Start a load generator** step on other versions of the page. Requires testing, of course.
