### ISSUE TITLE
Capacity troubleshooting

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2461]
Performance, availability, and stability issues can be caused by insufficient capacity.  

- "Because capacity is critical to availability ..."  Google SRE https://landing.google.com/sre/book.htm 
- https://github.com/cockroachdb/cockroach/issues/21416 has examples of issues capacity management can solve.

Initial suggestions below:

## Check Out of Capacity Conditions

First, check adequate capacity was available for the incident for the following components.

Type | Linux Command | what to look for
-- | -- | --
file system storage capacity | df -kh | file system at 99%
Storage IOPS / bandwidth capacity | sar -d | consistent non-zero values in avgqu-sz 
RAM capacity | sar -s | any non-zero value in kbswpused and %swpused
CPU capacity | sar  -q | consistent non-zero values in runq-sz 
Network capacity| sar -n ALL |  any non-zero value in rxerr/s, txerr/s, coll/s, rxdrop/s, txdrop/s, txcarr/s, rxfram/s, rxfifo/s, txfifo/s

## Check Near Out of Capacity Conditions

Type | Linux Command | what to look for
-- | -- | --
Storage bandwidth capacity | sar -d | consistently more than 80% or unusually high values in rd_sec/s and wr_sec/s (in 512 bytes sector thus not as accurate as iostat)  
Storage IOPS capacity | sar -d | consistently more than 1ms or unusually high values in await 
RAM capacity | sar -r | consistently more than 80% in %memused
CPU capacity | sar  -u | consistently less than 20% in %idle (ie:80% busy) 
Network capacity| sar -n ALL |  consistently more than 50% line capacity in rxkB/s or txkB/s

## Check for abnormal conditions

Historical measurements are required determine whether a metric is too high or too low.  Maintaining at least 1 month of historical data will be useful.

###  Linix sar in crontab

Enable sar data collected at 1-minute interval 

- Ubuntu
```
sudo bash
apt-get install sysstat
sed -ibak -e 's/ENABLED="false"/ENABLED="true"/g' /etc/default/sysstat
sed -ibak -e 's|5-55/10 \* \* \* \*|\* \* \* \* \*|g' /etc/cron.d/sysstat
```

**Comment by jseldess** [comment]
Merged with https://github.com/cockroachdb/docs/issues/2723
