### ISSUE TITLE
Concurrency throttling provides stable response time when faced with un-predictable concurrency

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2463]
## Overview

Microservices and web applications user concurrency is often not predictable.  Throttling the concurrency into the database at tested concurrency can stabilize the throughput and response in the face of unpredictability.

## Details
Concurrency tests that exceed server's resource capacity worsen's performance.  By throttling concurrency at about 75% of the resource's limit, better performance can be achieved.  Throttling the concurrency limits the context switching that has a negative effect on the performance.

## Results

The graphs below show throughput and response time by 
- varying concurrency from 1 to 8
- throttling concurrency into the database at 3 and no throttling
 - the blue line represents concurrency throttled at 3
 - the red line represents no throttling

By capping the concurrency into the database, the throughput is capped to that of concurrency=3
  
![chart 2](https://user-images.githubusercontent.com/6315124/35950573-30bb5d76-0c45-11e8-8ebf-0b13e5056b5b.png)

By capping the concurrency into the database, the response time shows stable 1ms even at high concurrency whereas, without the throttling, the response time gets worse and worse.

![chart 1](https://user-images.githubusercontent.com/6315124/35950574-30ce8be4-0c45-11e8-943c-5ff24eb8b0cb.png)

## Test Config

Below script was run varying the concurrency from 1 to 8 on i3 CPU with Linux.  The workload was set to 100% read which will stress the CPU.  Concurrency of 3 is expected to be the max for this system.

```
for c in 1 2 3 4 5 6 7 8; do
echo $c
kv -read-percent 100 -duration 20s -concurrency $c 'postgresql://root@localhost:26256?sslmode=disable'
sleep 5
done
```
haproxy.cfg was setup in two different ways.

default which does not limit concurrency
```
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m

listen psql
    bind :26256
    mode tcp
    balance roundrobin
    server cockroach1 127.0.0.1:26257 
```

limit concurrency to 3 into the database
```
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m

listen psql
    bind :26256
    mode tcp
    balance roundrobin
    server cockroach1 127.0.0.1:26257 maxconn 3
```

**Comment by bdarnell** [comment]
With 8 clients and `maxconn 3`, what happened to the clients that were not allowed connections? Did they get to take a turn or did they just get blocked waiting for a connection?

PGBouncer may be better than HAProxy here, since it (in "transaction pooling" mode) demultiplexes the incoming requests across different backend connections.

**Comment by robert-s-lee** [comment]
HAproxy doc indicates the client waits for the next available slot.  The kv load generator did not report any error during the test.  Just looking at PGBouncer -- worth testing and measuring the characteristics.

**Comment by petermattis** [comment]
@robert-s-lee How were you measuring response times in your setup? It makes absolute sense that limiting the concurrent connections to 3 will stabilize the server side response times, but the client side latencies should see a similar rise in both situations. That is exactly what I see in the various "scalability" graphs I produce. When we start hitting the throughput limiting, increasing concurrency results in diminishing returns for throughput but latencies continue to rise.

**Comment by robert-s-lee** [comment]
https://docs.google.com/spreadsheets/d/1BZ9PTrsgTzSl2vUyjq8CzT6EzcHsAZRSasjpvYZt9R8/edit#gid=2103637363 has the raw data of KV output.  The response time is p99 (on the graph).  p95 is also in the spreadsheet.  In this test, KV and CRDB are on the same system.  I have been meaning to rerun so that 1) KV and CRDB are on separate systems to see if the curve look different 2) run longer with bigger data set 3) also do write as the previous is 100% read in order to mimic a specific scenario 4)  try out PGBouncer during the re-run.

**Comment by petermattis** [comment]
@robert-s-lee What linux box were you running on? "i3 CPU" is vague.

**Comment by petermattis** [comment]
As a follow-up, I extended `kv` with `--connections` flag to limit the number of connections to the database (the previous `kv` behavior was to allow a connection per worker). In the graph below, the red line is without limiting the number of connections and the blue line is with `--connections=8`:

<img width="718" alt="screen shot 2018-02-26 at 10 03 51 am" src="https://user-images.githubusercontent.com/6201335/36677560-7fd98d74-1adc-11e8-9d2f-b15645b71ab2.png">

I ran this experiment on 2 n1-standard-4 GCE machines (4 vCPU machines). Throughput flatlines at `concurrency=8` and at that point latencies begin to rise. But notice that allowing more concurrent connections (the red line) provides better (lower) latency than restricting the number of concurrent connections.

This is a single experiment. We've seen with TPC-C that increased concurrency can slow the system down. It is possible that with higher concurrency values, limiting the number of connections would be beneficial. It is possible that allowing lots of concurrent connections but limiting the number of concurrent queries would be beneficial.

**Comment by jseldess** [comment]
@petermattis, @robert-s-lee, I don't understand if there is known docs work here for 2.1. Can one of you clarify?

**Comment by petermattis** [comment]
@jseldess I don't think there is anything to document yet. I think it is likely that we should add some sort of admission control mechanism to query processing on the server side. So far my experimentation has shown that trying to do this on the client side is extremely problematic (see the blue latencies in the chart above).

**Comment by jseldess** [comment]
Moving this to later for re-prioritization.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
