### ISSUE TITLE
Code samples for high concurrency/performance

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2464]
Re: [Build a Go App with CockroachDB](https://cockroachlabs.com/docs//v1.1/build-a-go-app-with-cockroachdb.html)

## Issue Description

For functional test, supplied code samples are sufficient.  In performance testing, the techniques used in the sample is not the best.  When trying out CockroachDB , the sample code is

- copied in verbatim
- then tailored to specific use cases
- then used in high concurrency performance tests

The results not always the ideal.

## Suggested Resolution 

Sample code with high concurrency / performance techniques.  For example, notes or examples of the following would be helpful for performance considerations.

- crdb.ExecuteTx is not required when performing implicit txn such as single statement DML
- use prepared statement to reduce CPU overhead in parsing

**Comment by jseldess** [comment]
From @petermattis in https://github.com/cockroachdb/docs/issues/2855: 

A [forum user](https://forum.cockroachlabs.com/t/double-spending-issues/1484/13) attempted add threading to the [psycopg2 example](https://www.cockroachlabs.com/docs/v2.0/build-a-python-app-with-cockroachdb.html) but didn't take into account the thread safety of psycopg2 connections or the isolation of psycopg2 cursors. At a minimum, we may want to add a sentence about thread-safety (or the lack thereof) to these examples. Going farther, we could add additional per-language examples that include concurrency as we want to encourage users to utilize concurrency in their apps in order to get the best performance out of CockroachDB.

**Comment by jseldess** [comment]
Part of https://github.com/cockroachdb/docs/issues/2943.

**Comment by tim-o** [comment]
Yesssss. Thissssss.

I get about an issue a week from users trying to copy / paste from our test applications and then wondering why we're slower than postgres when they try to pound 10k upserts per second into a single value in a single range.

**Comment by jseldess** [comment]
Java/Hibernate, from https://github.com/cockroachdb/docs/issues/3021:

A complete / tested code to be provided of below:

1) batching

http://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html/ch15.html

2) multirow

```
 Session session = sessionFactory.openSession();
 Transaction tx = session.beginTransaction();

String sqlInsert = "insert into sampletbl (name) values (?),(?),(?) ";
   session.createSQLQuery( sqlInsert )
          .setParameter(1,"name1")
          .setParameter(2,"name2")
          .setParameter(3,"name3")
          .executeUpdate();
tx.commit();
session.close();
```

3) copy from stdin

```
             String sql = "COPY accounts FROM STDIN";

            StringBuilder sb = new StringBuilder();
            PushbackReader reader = new PushbackReader( new StringReader(""), 10000000 );
            int n = startSeq;
            for (int j = 0; j < maxrows / batchsize; j++) {
            for(int i=0; i<batchsize; i++) {
              sb.append(n).append("\t").append(n).append("\n");
              n += 1;
            }
            reader.unread( sb.toString().toCharArray() );
            cpManager.copyIn(sql, reader, sb.length());

            sb.setLength(0); // set length of buffer to 0
            }
```

**Comment by rmloveland** [comment]
Unassigning myself since I probably won't work on this anytime soon.  Happy to take it up later if / when it gets prioritized.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
