### ISSUE TITLE
Change CI for Docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2503]
Currently, `html-proofer` runs against the entire site (all versions of docs) on each PR. This takes around 30 min, which is a long time to wait for link checking. It'll get worse every time we add another version subdirectory.

Proposed change:
- On each PR, run `hmtl-proofer` against new/changed pages only.
- Run a nightly test against the entire site, auto-creating an issue with the failure details. 

@benesch, let me know if you have other ideas.

**Comment by bdarnell** [comment]
Can we distinguish between internal and external links? It would be ideal if we could (quickly) verify internal links on every build but only check external links on a nightly build (or only in changed files).

**Comment by jseldess** [comment]
Good idea. We could set [`disable_external`](https://github.com/gjtorikian/html-proofer#configuration) to `true` for all PRs and then set that to `false` for nightly builds.

**Comment by jseldess** [comment]
Was talking to @spencerkimball during Docs FixItDay. He reasonably pointed out a 30 min wait for TC is a big hit to productivity. I'll spend some time running htmlproofer locally with and without `disable_external` to see if we get a significant speedup. I'll check for other possible speedup mentioned here: https://github.com/cockroachdb/docs/issues/1660

@dt also mentioned that we have a linkchecker in `cockroach`: https://github.com/cockroachdb/cockroach/blob/228dab8f225b925f79389cfa0337103076e70a84/pkg/cmd/urlcheck/main.go#L32-L31

Perhaps we should just repurpose that, or otherwise build a link checker internally.

**Comment by jseldess** [comment]
OK, did some testing:

Test | Config | TC Finished in
-----|--------|---------
1 | Increase to 4 cpus / Disable external link checking / Disable image and script checking | **11m:52s**
2 | No increase in cpus / Disable external link checking / Disable image and script checking | **27m:42s**
3 | Increase to 16 threads / Disable external link checking / Disable image and script checking | **30m:44s**
4 | Increase to 8 cpus (max per gce-agent) / Disable external link checking / Disable image and script checking | **12m:07s**
5 | Increase to 8 cpus (max per gce-agent) / Do not disable external link checking / Do not disable image or script checking | **13m**
6 | Increase to 4 cpus / Do not disable external link checking / Do not disable image or script checking | **14m:30s**

Since disabling external link checking and image and script checking doesn't help much, I'd suggest we go with test 5 for now. It should reduce the TC time by half.

@bdarnell, @benesch, do you agree?

13min still seems ridiculously long for link checking, so we should probably just look at other tools.

**Comment by benesch** [comment]
Test 5 makes sense. We should also explore https://github.com/wjdp/htmltest, which is basically HTML Proofer but rewritten in Go and supposedly much faster.

**Comment by jseldess** [comment]
OK, I'll go with 5 for now. But yes, let's definitely look at `htmltest`!

**Comment by spencerkimball** [comment]
Nice improvement. I still think we should get this down under 5m. When you run this now with 8 cores, are you still CPU bound or is something else going on?

**Comment by jseldess** [comment]
I’m not sure how to measure that, Spencer. Any tips?

I suspect that a big part of the problem is that htmlproofee is ruby, just like Jekyll. Hugo, which is basically Jekyll rewritten in go, builds a site lightening fast compared to Jekyll. I bet the go htmltest tool that nikhil found would get us under 5 min. I’ll need some help getring teamcity to use it though.

**Comment by benesch** [comment]
I basically have it working! I’ll send along a PR later today.

**Comment by spencerkimball** [comment]
@benesch you are **the man**.

**Comment by jseldess** [comment]
For anyone wanting to be blown over by @benesch's greatness, checkout out that linked PR, which gets a docs build/test down to less than 1 min!

**Comment by spencerkimball** [comment]
Fantastic! This is the gift that will keep giving.
