### ISSUE TITLE
sqlccl: remove external storage dependency on RESTORE cleanup

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2504]
PR: https://github.com/cockroachdb/cockroach/pull/21559

From release notes:
> Failed `RESTORE` cleanup no longer causes the `RESTORE` job to perpetually loop if external storage fails or is removed.

Not sure if affects docs.

**Comment by Amruta-Ranade** [comment]
As discussed with Matt J., no docs needed.
