### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#251]
Document all the ways you can constrain column data in CockroachDB.

At first, we can build out the **Constraints** section on data-definition.md. If it feels like the material warrants a separate page, though, we can add one.

For reference:
- Table-level constraints: https://www.cockroachlabs.com/docs/sql-grammar.html#constraint_elem
- Column-level constraints: https://www.cockroachlabs.com/docs/sql-grammar.html#col_qualification_elem
- Test for CHECK constraint: https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/check_constraints
- Test for DEFAULT constraint: https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/default
- Test for PRIMARY KEY: https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/table
- [PostgreSQL constraints](http://www.postgresql.org/docs/9.4/static/ddl-constraints.html)
- [MySQL constraints](http://dev.mysql.com/doc/refman/5.7/en/constraints.html)

**Comment by uptimeDBA** [comment]
I think including constraint syntax diagram(s) on the page where we discuss constraints would be a good idea.  (Same applies to other pieces of syntax.) 
At present all the additional grammar is generated on one large grammar page which makes it hard to include a particular set. I know @mjibson has done a lot of work in this area, parsing the sql grammar into EBNF etc to automatically generate the diagrams and Matt is the first one to admit there is more refactoring to do. I've taken a look and after a little refactoring and in-lining, the diagram looks like:

![col_qualification](https://cloud.githubusercontent.com/assets/17366371/15160255/e585d104-174c-11e6-83b1-164764c4dde1.png)

col_qualification
         ::= ( 'CONSTRAINT' name | ) ( 'NOT' 'NULL' | 'NULL' | 'UNIQUE' | 'PRIMARY' 'KEY' | 'CHECK' '(' a_expr ')' | 'DEFAULT' b_expr )

Easier said than done unfortunately as it would be challenging to produce this programatically and for the general case. I don't have an answer to that but what do you think about generating the grammar  into individual files so we can include the relevant bits on the appropriate pages?
Thanks.

**Comment by jseldess** [comment]
I see what you mean. This would be helpful. @mjibson, should @uptimeDBA just open a separate docs issue to create a standalone "constraints" graphic?

**Comment by mjibson** [comment]
If I'm reading everything right that diagram is easily produced with one new line in https://github.com/cockroachdb/docs/blob/gh-pages/generate/main.go#L168

No need to create anything standalone.

**Comment by uptimeDBA** [comment]
I've had a quick look at [](https://github.com/cockroachdb/docs/blob/gh-pages/generate/main.go#L168) and I think you're right. I'll run these through and see what they give.

`{name: "column_constraint", stmt: "col_qual_list", inline: []string{"col_qualification", "col_qualification_elem"}}`

`{name: "table_constraint", stmt: "table_constraint ", inline: []string{"constraint_elem"}}`

**Comment by uptimeDBA** [comment]
@mjibson If I'm using `generate` correctly, `{name: "column_constraint", stmt: "col_qual_list", inline: []string{"col_qualification", "col_qualification_elem"}}` gives me:
![close](https://cloud.githubusercontent.com/assets/17366371/15279985/d0ba8a4a-1b7e-11e6-9fda-f8aab839c28f.png)

Any chance of removing the recursion? (As I think that's the trouble in the ebnf.)
Statements of the form:
~~~plain
col_qual_list ::=
        col_qual_list col_qualification
        |
~~~

Need to be simplified to:

~~~plain
col_qual_list ::=
         col_qualification?
~~~

in the simplify routines of `extract`.

I'm getting an error with the table_constraint entry so I must be doing something wrong somewhere.

~~~shell
[uptimeDBA@dev generate]$ ./generate 
I160516 16:09:24.553738 main.go:263  generate BNF: https://raw.githubusercontent.com/cockroachdb/cockroach/master/sql/parser/sql.y
I160516 16:09:25.408253 main.go:268  parse: table_constraint , inline: [constraint_elem], descend: false
I160516 16:09:25.410008 main.go:268  parse: rename_stmt, inline: [], descend: false
I160516 16:09:25.410668 main.go:268  parse: stmt_block, inline: [], descend: true
I160516 16:09:25.413907 main.go:221  couldn't find table_constraint 
[uptimeDBA@dev generate]$ 
~~~

**Comment by mjibson** [comment]
Adding `{name: "column_constraint", stmt: "col_qual_list", inline: []string{"col_qualification", "col_qualification_elem"}}` to the spec statement list works correctly for me. Your error references `table_constraint`, so maybe you have some code changes on disk that are not mentioned here.

The recursion in col_qual_list is unlike other kinds of recursion (it's not separated by a comma and supports 0 productions), so our recursion detector doesn't work on it. If you like you can improve it: https://github.com/cockroachdb/docs/blob/67c6566d1668f945a3f0aca233f8a915d37a38f5/generate/extract/extract.go#L295

**Comment by uptimeDBA** [comment]
@mjibson Hi Matt, I've taken a look and I think the diagrams will take a huge leap forward in readability if the following options are added to the `GenerateRR` function in `extract.go`.

~~~
v.Add("options", "eliminaterecursion")
v.Add("options", "factoring")
v.Add("options", "inline")
~~~

I think the bottlecaps guy has made some recent changes to his Railroad Diagram Generator so I don't think these options were available when you originally built it. 
(I haven't raised an issue for this.)

**Comment by mjibson** [comment]
Thanks for the heads up. I've enabled those options. The diagrams look much better.

**Comment by uptimeDBA** [comment]
No worries.
I will take a look at my `table_constraint` error today.
What do you think about moving the `specs := []stmtSpec...` structure out of the code and into a configuration file of some sort that can be passed as a parameter (and a command line option that accepts a single entry so we can test individual diagrams.) so we don't have to re-compile the code to make changes/additions to the diagrams?

**Comment by mjibson** [comment]
I'm ok with that as long as our default case of just running the thing with no arguments does it by default.

**Comment by jseldess** [comment]
Since constraints are documented, I'm closing this. @uptimeDBA, if you want to open another issue for changes to diagram-generation code, go ahead and do that.
