### ISSUE TITLE
sqlccl: merge IMPORT and RESTORE jobs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2511]
PR: https://github.com/cockroachdb/cockroach/pull/21490

From release notes:
> The `IMPORT` function now does not require the temp directory and no longer creates a `RESTORE` job. Additionally, the `TRANSFORM_ONLY` option for `IMPORT` has been renamed to `TRANSFORM` and now takes an argument specifying the target directory.

**Comment by Amruta-Ranade** [comment]
Already documented with the previous IMPORT doc.
