### ISSUE TITLE
server: Signal readiness before waiting for the init command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2512]
PR: https://github.com/cockroachdb/cockroach/pull/21682

From release notes:
> `cockroach start --background` now returns earlier for nodes awaiting the `cockroach init` command, facilitating use of automated scripts.

**Comment by jseldess** [comment]
@bdarnell, do you think this change warrants a doc update? Should we, for example:

- Revert our local startup tutorial to start all nodes in the same terminal, using `--background`, instead of in separate terminals?
- No longer tell users to [run `init` from a separate machine]( https://www.cockroachlabs.com/docs/dev/deploy-cockroachdb-on-premises.html#step-4-initialize-the-cluster)?

**Comment by jseldess** [comment]
Might want to revisit this FAQ as well: https://www.cockroachlabs.com/docs/v2.0/operational-faqs.html#why-is-my-process-hanging-when-i-try-to-start-it-in-the-background.

**Comment by rmloveland** [comment]
@jseldess do we still want to work on this given [this comment](https://github.com/cockroachdb/cockroach/pull/21682#issuecomment-367631514) from Tobias about the current info being "correct in spirit" despite the change?

**Comment by jseldess** [comment]
Oh, right, looks like nothing to do. Feel free to close, @rmloveland.
