### ISSUE TITLE
keys, sql: change sequence key format so backup/restore works

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2516]
PR: https://github.com/cockroachdb/cockroach/pull/21684

From release notes:
> Sequences are now supported in enterprise `BACKUP`/`RESTORE` jobs.
> 
> This changes how sequences are stored in the key-value storage layer, so existing sequences must be dropped and recreated. Since a sequence cannot be dropped while it is being used in a column's `DEFAULT` expression, those expressions must be dropped before the sequence is dropped, and recreated after the sequence is recreated. The `setval` function can be used to set the value of a sequence to what it was previously.

**Comment by lhirata** [comment]
@jseldess - i added sequences to BACKUP / RESTORE docs. do i need add a note to CREATE SEQUENCE regarding the backwards incompatibility?

**Comment by jseldess** [comment]
I'm not sure, @lhirata. @vilterp, @mjibson, do you have opinions?

**Comment by vilterp** [comment]
The note would have to be something like "sequences created in 2.0-alpha builds before <X alpha build>" will have to be dropped and recreated …". Seems like that would affect a very small number of users. I lean toward saying the release note above would be enough for them.

FWIW, looks like the backwards-incompatible change was merged Jan 31. Not sure how to get a sense of if anyone was using sequences before then… Maybe the reg cluster could tell us. But anyway, I'd say just leave the release note.
