### ISSUE TITLE
sql: ALTER TABLE statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#252]
Complete reference documentation for the `ALTER TABLE` statement: alter-table.md

Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

More reference:
- https://github.com/cockroachdb/cockroach/blob/master/sql/alter_table.go
- https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/alter_table
- PostgreSQL: http://www.postgresql.org/docs/9.5/static/sql-altertable.html
- MySQL: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

**Comment by sploiselle** [comment]
Needs to take #874 into account.
