### ISSUE TITLE
Raft Prevote

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2528]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recio3xmxNEsIZJYS

**Comment by jseldess** [comment]
Possible updates to the architecture docs.

**Comment by bdarnell** [comment]
I don't think we discussed raft elections in this much detail in the old architecture docs. (we never mentioned the CheckQuorum feature that PreVote is replacing). I don't think there's anything to do here unless we want to really expand the replication architecture page.

**Comment by jseldess** [comment]
Can you give this a quick read. If nothing is incorrect, and it's not important to expand, I'll close. https://www.cockroachlabs.com/docs/stable/architecture/replication-layer.html#raft

**Comment by bdarnell** [comment]
The old content is still correct; I don't think we need to expand it at this time.
