### ISSUE TITLE
sql: BEGIN statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#253]
Complete reference documentation for the `BEGIN` statement: begin-transaction.md

Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

More reference:
- https://github.com/cockroachdb/cockroach/blob/master/sql/txn.go
- https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/txn
- PostgreSQL docs: http://www.postgresql.org/docs/9.5/static/sql-begin.html
- MySQL docs: http://dev.mysql.com/doc/refman/5.7/en/commit.html

**Comment by uptimeDBA** [comment]
I've un-assigned myself from this due to inactivity on it, giving someone else a chance to pick it up.

**Comment by jseldess** [comment]
@sploiselle, should we mark this closed now that https://github.com/cockroachdb/docs/pull/672 has been merged?

**Comment by sploiselle** [comment]
Closed by #672
