### ISSUE TITLE
IMPORT/RESTORE rate limiting

### ISSUE THREAD

**Issue by dt** [cockroachdb/docs#2533]
Context: If we use 100% of available IO capacity to do bulk IO in IMPORT or RESTORE, we currently make nodes temporarily slow or even unhealthy (liveness failures). This can interfere with those operations directly -- e.g. IMPORT will start over currently, and may be unable to finish -- but in general though, IMPORT jobs are likely to be run on production clusters, where we should try to avoid impacting the health of the cluster or its ability to serve traffic.

To avoid this, we default to limiting the write rate of bulk IO operations with a setting, but the correct value for this setting depends on the hardware's IO capacity for any individual cluster, any other tasks using that IO capacity, the other load on the cockroach nodes, etc. so a one-size-fits-all value is hard to pick here.

We're going to pick a default rate limit based on the expected performance of our recommended cloud hardware
  - [ ] In the recommended hardware docs, we should note that if your hardware is different, you may want to tune the setting accordingly. 
  - [ ] In `IMPORT` docs, we should note that if your cluster is under heavy production load, you may want to lower the limit, such that it does not exceed your spare IO capacity.
  - [ ] A `RESTORE` operation might want to go as fast as possible, regardless of impact on cluster health / ability to serve other traffic, e.g. if you're recovering from backup to get back online or provision a new cluster. In the `RESTORE` docs, we should note that you can up the setting to let the restore go faster in these cases.

We might also want to provide an example of *how* to tune the setting (cc @mberhault for ideas here):
 - benchmarking your device's throughput with something like `dd` and taking some percentage of that
 - looking at utilization with something like `iostat` or other monitoring to determine if you need to lower it

**Comment by jseldess** [comment]
@dt, @dianasaur323, I think it's realistic to get the 3 checkbox items covered for 2.0 but not the detailed guidance around how to benchmark and tune the setting. That's too involved for the time we have left, given the other projects on our plate. OK if I split that work into a separate issue for 2.1?

**Comment by jseldess** [comment]
Also, @dianasaur323, it'd be great to represent this work on the roadmap, if possible, that is, picking and implementing a default rate limit for 2.0.

**Comment by dt** [comment]
oh, and yeah, I don't think we need to have examples of how to tune the setting in the docs by 2.0, it'd just be nice to have in the bulk io docs at some point. In the short term, I imagine we'll have a GitHub issue where we (eng) figure what that process even is, and we can point anyone who asks at that until we have something we think is ready to doc.

**Comment by dt** [comment]
Some additional things to capture here are in interaction between the `write_rate` limit and the concurrent request limits -- e.g. we don't let too many import requests in at once since they'd all fetch and buffer data just to then wait to write it.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
