### ISSUE TITLE
v1.1: add known limitation for large transactions (particularly deletions)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/docs#2535]
https://www.cockroachlabs.com/docs/stable/known-limitations.html

See https://github.com/cockroachdb/cockroach/issues/17921. Users regularly [run into this](https://gitter.im/cockroachdb/cockroach?at=5a85e2aee217167e2c8c8845) or related problems.

Apparently the behavior is better in v2.0 (though I don't think this is adequately tested), but at least for v1.1.x, we should add a known limitation (note: I didn't try any of this SQL so it probably has some errors):

---

Transactions which affect many rows may consume too much memory and may be aborted with an error. The example that occurs most often in practice are deletions of large parts of a table, such as

```sql
DELETE FROM orders WHERE archived < NOW() - INTERVAL '1 WEEK'`
```

where the predicate affects upwards of tens of thousands of rows (for example, when the above query is run for the first time, after the orders table has grown very large over time).

Typically, the solution is to break the operation down into smaller chunks:

```sql
-- A date far enough in the past so that it is known that only few rows are affected.
DELETE FROM orders WHERE archived < '2017-12-30'`;
-- Remove the orders in the week following that date.
DELETE FROM orders WHERE archived >= '2017-12-30'` AND archived <  '2017-12-30' + INTERVAL '1 WEEK';
-- Remove the orders in the next week.
DELETE FROM orders WHERE archived >= '2017-12-30'` + INTERVAL '1 WEEK' AND archived <  '2017-12-30' + INTERVAL '2 WEEKS';
-- iterate until reaching NOW()- INTERVAL '1 WEEK'.
```

This assumes that the number of orders for each week is manageable. When this is not known about the data set, the following workaround still applies:

```sql
DELETE FROM orders WHERE archived < NOW() - INTERVAL '1 WEEK' LIMIT 1000;
DELETE FROM orders WHERE archived < NOW() - INTERVAL '1 WEEK' LIMIT 1000;
-- iterate until zero rows are affected.
```

This is slower as each statement will have to skip over the previously deleted rows.

A combination of both strategies can be used to get the performance of the first approach along with the safety of the second.

Note: handling of this scenario is improving in CockroachDB v2.0., though breaking large deletions up into smaller parts is generally recommended as running such operations in one large transaction can impair performance.

**Comment by bdarnell** [comment]
This limitation is documented on that page (under the heading "Write and update limits for a single transaction"), but it's clear that this is not using the right language to make it easily findable. In particular it makes no mention of "delete", which is one of the easiest ways to run into this problem (and it's not obvious that the number of rows to be deleted counts towards the size of the transaction).

**Comment by jseldess** [comment]
@andreimatei, you recently updated this known limitation with https://github.com/cockroachdb/docs/pull/2851. Did that update resolve this issue, or are there other updates still to be made?

**Comment by jseldess** [comment]
Oh, actually, this issue seems to be concern the 1.1 limitation. Would you be willing to update that one as well, @andreimatei?

**Comment by andreimatei** [comment]
Tobi, how did deletions improve in 2.0 exactly?

**Comment by tschottdorf** [comment]
Deletions are now chunked, so they should not run into out of memory errors any more. Additionally, the span condensing makes sure that large transactions are less of a problem. Finally, the transaction refresh mechanism lets these long-running transactions actually finish.

**Comment by andreimatei** [comment]
Ah, the chunking is what I was failing to see. The "span condensing" stuff I have documented when I updated this known limitation for 2.0.
Sent out #2886 which calls out deletes in 1.1.
