### ISSUE TITLE
Add release note for clusterviz

### ISSUE THREAD

**Issue by couchand** [cockroachdb/docs#2540]
The clusterviz got merged without updating the release note on the commit.  Please add the following note for cockroachdb/cockroach#22763:

Release note (admin ui change, enterprise change): Adds a geographical map to the homepage of the enterprise version, showing the location of nodes and localities in the cluster.  The map is annotated with several top-level metrics: storage capacity used, queries per second, and current CPU usage, as well as the liveness status of nodes in the cluster.

**Comment by couchand** [comment]
cc: @jseldess

**Comment by Amruta-Ranade** [comment]
Closed through https://github.com/cockroachdb/docs/pull/2588
