### ISSUE TITLE
Some code snippets don't format properly on Firefox

### ISSUE THREAD

**Issue by justinj** [cockroachdb/docs#2546]
https://www.cockroachlabs.com/docs/v1.1/cancel-query.html#cancel-a-query-via-a-nested-select-statement in Firefox looks like this:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/409075/36504412-6d24d790-171e-11e8-8629-309b67a72c2a.png">
even if I scroll the pane, it's still wrapped:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/409075/36504425-765f1690-171e-11e8-9df9-ea7b8d5ad9c9.png">
It looks fine in Chrome, though.

**Comment by jseldess** [comment]
Whoa, good find, @justinj!

@j-low, I can reproduce this. Putting it on your radar for an upcoming site bug fix week.

**Comment by jseldess** [comment]
This doesn't seem to be an issue any more. @justinj, if you still see this, please re-open.
