### ISSUE TITLE
CREATE INDEX statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#255]
Complete reference documentation for the `CREATE INDEX` statement: create-index.md

Intro, Synopsis, and Required Privileges are complete. We need to replace or supplement **Parameters** with **Usage** and **Examples** sections. For style reference, see those sections in [`CREATE DATABASE`](https://www.cockroachlabs.com/docs/create-database.html) and [`GRANT`](https://www.cockroachlabs.com/docs/grant.html).

More reference:
- https://github.com/cockroachdb/cockroach/blob/master/sql/create.go
- https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/create_index
- PostgreSQL docs: http://www.postgresql.org/docs/9.5/static/sql-createindex.html
- MySQL docs: http://dev.mysql.com/doc/refman/5.5/en/create-index.html

**Comment by sploiselle** [comment]
If no one else is working on this, glad to pick it up.

**Comment by jseldess** [comment]
Sure, @sploiselle! Thanks for offering. 

Another good resources on indexes in CockroachDB, written by CockroachDB dev: https://www.cockroachlabs.com/blog/index-selection-cockroachdb-2/

Also, I think @uptimeDBA will be cleaning up the grammar diagram, which would affect the parameters you document. @uptimeDBA, is that right?

**Comment by jseldess** [comment]
@sploiselle, just added you as a collaborator on this repo. Once you've accepted, I can assign the issue to you.

**Comment by uptimeDBA** [comment]
I haven't really touched the `CREATE INDEX` diagram. I've added an expansion of the `opt_storing` clause as a separate diagram. That's about all. At that point, everything left is a *name* of some sort. You can take a look [here](http://uptimedba.github.io/cockroach-vb-single/cockroach-vb-single/cockroachdb_syntax_diagrams.html#create-index). Let me know @sploiselle if that's ok and I'll set up a PR and @jseldess can merge.

**Comment by sploiselle** [comment]
@uptimeDBA 👋 The diagrams are an amazing documentation tool. Honestly the best way I've seen of handling any kind of CLI. A million kudos on your work there.

Moving `opt_storing` up like that is great! It would simplify the document even more if we could move the representation all the way into the synopsis diagram. Is that possible? 

I've got a [draft of the document](https://github.com/sploiselle/docs/blob/createIndexSqlStatement/create-index.md#parameters) that tries to address `opt_storing` as a parameter but it feels kludgy. (I also tried putting it in the right-hand column and it feels just about as awkward there.) If moving `STORING` into the diagram's not an option, though, I'll keep massaging it until something makes more sense.

**Comment by sploiselle** [comment]
Example is semi-blocked because of issue with `EXPLAIN SELECT` on decimal columns in indexes. Will come up with another illustrative example that doesn't use decimals.

__Related issue__
- [Encoding issue with EXPLAIN SELECT on decimal columns in indexes](https://github.com/cockroachdb/cockroach/issues/7215)

**Comment by uptimeDBA** [comment]
@sploiselle How's this?
![image 1](https://cloud.githubusercontent.com/assets/17366371/16057830/e4dc8b64-32cf-11e6-8672-2e8f3f7f2202.png)

The diagram wraps around a bit based on the image width but it seems to break at sensible places.
If that's all good, I'll add it to the page.

**Comment by sploiselle** [comment]
@uptimeDBA That looks good to me! Gets all of the keywords on the page. @jseldess – thoughts?

**Comment by jseldess** [comment]
Looks great to me as well. Thanks, @uptimeDBA!

**Comment by uptimeDBA** [comment]
PR #382 for the updated diagram.

**Comment by jseldess** [comment]
PR is merged and live docs include the new diagram.

**Comment by jseldess** [comment]
More improvements just merged with PR #400

**Comment by sploiselle** [comment]
@jseldess To make `create-index.md` a little easier to digest, thinking of expanding `indexes.md` a little bit. Something simple like a section titled "How do indexes work?" that explains that indexes copy and sort a column so SQL can easily find ranges in the column, limiting the number of rows it has to search.

Thinking 2-3 short paragraphs that could be added onto later on. Would then link to this from `create-index` and `create-table` (as well as a sweep for other docs that reference them) as a resource to get more info without burdening the existing docs.

That sound cool?

**Comment by jseldess** [comment]
Yep, great idea. That'll let you keep the statement docs focused more on usage.

**Comment by sploiselle** [comment]
@jseldess Ironing out a few things; curious if you can ping someone who can tell me:
- Are the indexes all B-trees? (I assume so but doesn't hurt to confirm)
- Are tables locked during index creation? Given the prevalence of optimistic concurrency control, I would guess no, but want to make sure.

**Comment by jseldess** [comment]
Sure, @sploiselle. I think think the first answer is yes and, based on @vivekmenezes's [online schema change](https://www.cockroachlabs.com/blog/how-online-schema-changes-are-possible-in-cockroachdb/) blog post, I think the second answer is no. But @RaduBerinde or @vivekmenezes could answer for sure.

Vivek's online schema change blog post leads me to

**Comment by RaduBerinde** [comment]
@sploiselle - the indexes are stored as keys-values in our KV store which is ordered (we implement it on top of RocksDB which is an LSM tree). So they are not technically B-trees but it's the "ordered" property which is important and in that respect they are similar to B-trees.

We don't lock tables during index creation.

**Comment by sploiselle** [comment]
@RaduBerinde Ah! Interesting. Thank you.

**Comment by sploiselle** [comment]
Closed by #432
