### ISSUE TITLE
diagnostics reporting: add a note about version checks

### ISSUE THREAD

**Issue by dt** [cockroachdb/docs#2550]
In the section on disabling diagnostics reporting, we should note that nodes also check for new versions periodically and notify you in the UI / logs if a new version is available.

These checks can be disabled by setting the environmental variable `COCKROACH_UPDATE_CHECK_URL=""`.

**Comment by jseldess** [comment]
Thanks, @dt. Is this new in 2.0, or was it just previously undocumented?

**Comment by jseldess** [comment]
@dt, does disabling diagnostics reporting automatically disable the new version check as well? Or are these separate?

**Comment by dt** [comment]
yep, since filing this, we decided and implemented that disabling diagnostics now also disables version checks, so nothing to do here now.

**Comment by dt** [comment]
will land soon for 2.0 in https://github.com/cockroachdb/cockroach/pull/23007

**Comment by jseldess** [comment]
Hmm, we might still want to mention this somewhere, so I'll reopen.

**Comment by dt** [comment]
I wouldn't worry about it -- I think with the fix (which we're cherrypicking to 1.x) as well it works basically like anyone would expect.
