### ISSUE TITLE
schema for SHOW TRACE FOR is changing

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#2553]
The transaction index component of the `span` column is going away in 2.0 in  https://github.com/cockroachdb/cockroach/pull/22990

**Comment by jseldess** [comment]
Thanks for planning ahead for docs fixitday, @andreimatei! Any chance you'd like to take on these other `show trace` issues while you're at it?

https://github.com/cockroachdb/docs/issues/2289
https://github.com/cockroachdb/docs/issues/2257

**Comment by andreimatei** [comment]
Yup.
