### ISSUE TITLE
docs: lots of fixes required for new schema support

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/docs#2559]
During QA for [#22753](https://github.com/cockroachdb/cockroach/pull/22753), I discovered that many docs pages need to be updated. For example, `SHOW DATABASES` no longer shows `crdb_internal`, `information_schema` and `pg_catalog`. Any page referencing those virtual schemas will likely need to be updated.

This is also related to [#22964](https://github.com/cockroachdb/cockroach/issues/22964), which added the `SHOW SCHEMAS` command.

**Comment by jseldess** [comment]
Thanks, @rytaft. We haven't gotten to this yet (tracked here: https://github.com/cockroachdb/docs/issues/2017), but we'll be sure to update all of those examples.

**Comment by rytaft** [comment]
Thanks! 👍

**Comment by knz** [comment]
Please remind me of this tracking issue during docs fixit day, I'd like to volunteer for it
