### ISSUE TITLE
Partitioning in common deployment topologies

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2565]
Exalate commented:

# Performance Patterns: Leveraging Partition Feature

The patterns assume the following:
- Understand the function of [CockroachDB Leaseholder](https://www.cockroachlabs.com/docs/stable/architecture/replication-layer.html#leases)
- Understand the impacts of the [leaseholder](https://github.com/cockroachdb/docs/issues/2300#issuecomment-354326834
] on read and write activities
- The leaseholders are local to reader and writers within the data center
- The leaseholder migration among the data centers is minimized using the partitioning feature
- Follow-the-workload tunable is set to properly for the workload
- Application is designed to use the [partitioning feature)()

## Symmetrical

During normal operations:

```
App                App
 \                  /
West ---60ms--- East
     \        /  
     60ms   60ms  
        \   /
         \ /  
       Central 
          |
         App
```

CockroachDB Replicas and Leaseholders:
- rows with the West partition will have the leaseholder in the West DC, the Central partition in the Central DC, and the East partition in the East DC
- the 3 replicas will be evenly distributed among the three data centers

Availability expectations:
- Can survive a single data center failure

Performance expectations:
- The reader can expect to have a couple of ms response time. 
- The writers can expect to have 60ms response time. 
- The latency among the data centers is symmetrical 60ms.

Application expectations:
- West App servers connect to the West CockroachDB nodes
- Central App servers connect to the Central CockroachDB nodes
- East App servers connect to the East CockroachDB nodes

CockroachDB configuration:

Abbreviated startup flag for each data center.
```
--loc=Region=East
--loc=Region=Central
--loc=Region=West
```

## Dual East DCs 

During normal operations:

```
App                App
 \                  /
West ---60ms--- East1
     \           |
       \        5ms
        60ms     |
           \____East2 
```

CockroachDB Replicas and Leaseholders:
- rows with the West partition will have the leaseholder in the West DC, the East partition in the East DC1
- the 3 replicas will be evenly distributed among the three data centers

Availability expectations:
- Can survive a single data center failure

Performance expectations:
- The reader can expect to have a couple of ms response time. 
- The East writers can expect to have 5ms response time. 
- The West writers can expect to have 60ms response time. 

Application expectations:
- West App servers connect to the West CockroachDB nodes
- East App servers connect to the East1 CockroachDB nodes

CockroachDB configuration:

Abbreviated startup flag for each data center.
```
--loc=Region=East,DC=1
--loc=Region=East,DC=2
--loc=Region=West
```

## Dual East and West DCs

During normal operations:

```
App                App
 \                  /
West1 ---60ms--- East1
  |   \        /   |
  5ms  - 60ms -    5ms
  |   /        \   |
West2----60ms----East2 
```

CockroachDB Replicas and Leaseholders:
- rows with the West partition will have the leaseholder in the West DC1, the East partition in the East DC1
- West partitions will have 1 replica each in West1 and West2, then 1 replica in East1 or East2
- East partitions will have 1 replica each in East1 and East2, then 1 replica in West1 or West2

Availability expectations:
- Can survive a single data center failure

Performance expectations:
- The reader can expect to have a couple of ms response time. 
- The writers can expect to have 5ms response time. 

Application expectations:
- West App servers connect to the West CockroachDB nodes
- East App servers connect to the East CockroachDB nodes

CockroachDB configuration:

Abbreviated startup flag for each data center.

```
--loc=Region=West,DC=1
--loc=Region=West,DC=2
--loc=Region=East,DC=1
--loc=Region=East,DC=2
```

## Summary

| Topology | West | Central | East |
| -- | -- | -- | -- |
| Symmetrical  | Read local, Write 60ms| Read local, Write 60ms | Read local, Write 60ms |
| Dual East | Read local, Write 60ms|  | Read local, Write 5ms |
| Dual East and West | Read local, Write 5ms|  | Read local, Write 5ms |

**Comment by jseldess** [comment]
For 2.1, this is part of https://github.com/cockroachdb/docs/issues/2935.
