### ISSUE TITLE
Document leaseholder rebalancing 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2568]
From https://github.com/cockroachlabs/support/issues/146#issuecomment-369276765:

* The current leaseholder keeps track of how many requests it receives from each locality as an exponentially weighted moving average.
* Periodically (every 10 minutes by default in large clusters, but more frequently in small clusters) each leaseholder considers whether it should rebalance where the ranges replicas are or transfer the lease to another existing replica.
* The leaseholder considers 3 primary inputs: the number of leases on each node, the number of requests from each locality, and the latency between localities.
* If all the nodes are in the same locality, the decision is made entirely on the basis of the number of leases on each node, trying to achieve a balance across all of them. We basically compare the current leaseholder's number of leases and the potential transferees' numbers of leases to the average number of leases on all the nodes in the cluster to determine which are underfull, overfull, or about right.
* If the nodes are in different localities, then we assign a "weight" to each existing replica's locality based on the fraction of requests that came from that locality or from similar localities
   * For example, if a bunch of requests were received by cockroach nodes in the locality "country=us,region=central" and forwarded to the leaseholder for some range, then a replica of that range in locality "country=us,region=west" would get partial credit (50% credit, to be precise, because the first locality tier is shared) for those requests, whereas a replica in "country=aus,region=central" would get no credit. A replica in "country=us,region=central" would get full credit for the requests.
* We combine the ratio of the weights of the source replica to each potential transferee with the latency between the source replica's locality and the potential transferee's locality to come up with an adjustment factor.
* The greater the disparity between "weights" and the higher the latency between localities, the more we'll favor the node from the locality with the larger weight. We then use that adjustment factor to adjust the underfull/overfull targets such that the favored node is more likely to be chosen as the lease location.

**Comment by a-robinson** [comment]
@benesch noted yesterday that we should also call out the `kv.allocator.lease_rebalancing_aggressiveness` cluster setting, which enables you to change how aggressive the lease rebalancer is about moving leases toward load. He had a scenario where only some of the leases he wanted to move were moved toward their load. By bumping up the aggressiveness setting, he was able to move all the leases he wanted to, which was much more satisfying than being left in the lurch of having the feature not do what he wanted.

We could document the setting in the follow-the-workload demo, or wherever this info ends up.

**Comment by jseldess** [comment]
This is a good "core" topic for us to document in the 2.2 timeframe. Once we describe the basic heuristics, we can revisit documenting the SQL commands for forcing leases to rebalance: https://github.com/cockroachdb/docs/issues/3459

**Comment by sploiselle** [comment]
closed by #4160
