### ISSUE TITLE
Training: Various improvements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2576]
From @a-robinson:

- Make the planned maintenance section use 4 nodes instead of 3 - better matches motivation in slides
- Add step at end of "Cluster Upgrades" lab to show the error you get if you try to downgrade.
    - Potentially even better would be to also try downgrading before finalizing the upgrade.
- Do something less clunky for spinning up clusters in later labs -- they have a lot of repetitive copying and pasting that involves switching back and forth between a browser and a terminal that gets pretty tedious for everyone, particularly after sitting in a training session for hours.
- Show off the interactive sql shell somewhere, preferably early on
- The under-replication lab is completely redundant with fault tolerance section
- The training doesn't provide nearly enough content for two full 6-hours days. Two 4-hour days is more like it. Two 4-hour days would also be less tiring for everyone involved.
- we don't include anything about schema changes. Users familiar with older systems probably assume that schema changes block other operations, so it may be worth including a module to show that they don't.
- We don't include anything about schema changes. Users familiar with older systems probably assume that schema changes block other operations, so it may be worth including a module to show that they don't.
- we should try to better explain in the getting started documentation that all the data is only replicated 3x by default rather than on every node.

**Comment by jseldess** [comment]
@petermattis, I read through your notes on the training, but I didn't see any immediate actions items. Can you help identify any you had in mind?

**Comment by jseldess** [comment]
> Do something less clunky for spinning up clusters in later labs -- they have a lot of repetitive copying and pasting that involves switching back and forth between a browser and a terminal that gets pretty tedious for everyone, particularly after sitting in a training session for hours.

I'd love to start using `roachprod` to spin up local clusters, once it's ready.

**Comment by jseldess** [comment]
Moving these improvements to post-2.1, since we're exposing only the first 5 modules on the site for the 2.0 release.

**Comment by Amruta-Ranade** [comment]
I am going through the training modules for self-learning and coming across some errors/scope-for-improvement. Here are my notes (WIP):

**Fault Tolerance and Automated Repair** 
Step 4 tells us to run this command:
`./cockroach sql --insecure --execute="SET CLUSTER SETTING server.time_until_store_dead = '1m0s';"`
Running the command gives the following error:
`Error: pq: cannot set server.time_until_store_dead to less than 1m15s: 1m0s
Failed running "sql"`

**Locality and Replication Zones**
- We can use the Node Map in the Web UI to explain localities and replication zones 
- Step 3: We can add a sentence between the code blocks for us-central and us-west. Else, I (user) ends up copy-pasting the code blocks without understanding what they are doing. Having a sentence distinguishing the code blocks per region will make them stop and think.
- Step 8: We can use the Web UI's data distribution matrix (http://localhost:8082/#/data-distribution) to show the distribution of data. 

**Data Import**
- Step 2,3: Sub-step 3: We can use UI > Databases > (Click on table name) to view schema
- UI > Jobs page to see status of Import (if required)

**Users and Privileges**
This might be a good doc to discuss creating users with passwords. For 2.1, customers need to create users with passwords to access the UI.

**Cluster Upgrade**
- Docs for 2.1 show the process for upgrading from 1.1 to 2.0

Will add more comments as I go through the training.

**Comment by Amruta-Ranade** [comment]
**Production Deployments**
We don't have a lab for this module. We might want to add guidance about how to view these things on the UI:
- Hardware Recommendations: Hardware dashboard
- Clock sync: Runtime dashboard? 
- Cache and Memory Size: Runtime dashboard
- File descriptors: Storage dashboard
- Cluster topology: Node Map, Data distribution matrix

**Debug logs**
- UI > Node List > Logs
