### ISSUE TITLE
Add documentation about what we mean by "experimental"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2579]
We should document what exactly we mean when we say a feature is "experimental" (e.g., [`IMPORT`](https://www.cockroachlabs.com/docs/stable/import.html) ).

As a user I want to know exactly what your definition of "experimental" is so I can decide whether/how best to use such features.

I had no luck searching the docs site but I did find a mention in [the 'Adding new SQL features with syntax' RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171011_adding_sql_syntax.md) that such items should be "marked clearly as subject to change without notice".

**Comment by dianasaur323** [comment]
Thank you for opening this!

**Comment by jseldess** [comment]
@dianasaur323 and @rmloveland, since we added this include, to be placed wherever we document an experimental feature, I'll consider this resolved. Please re-open if there's really more to do.
