### ISSUE TITLE
DROP INDEX statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#258]
Complete reference documentation for the `DROP INDEX` statement: drop-index.md

Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

More reference:
- https://github.com/cockroachdb/cockroach/blob/master/sql/drop.go
- https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/drop_index
- PostgreSQL docs: http://www.postgresql.org/docs/9.5/static/sql-dropindex.html
- MySQL docs: http://dev.mysql.com/doc/refman/5.7/en/drop-index.html

**Comment by giskarda** [comment]
pull request: https://github.com/cockroachdb/docs/pull/536 added.
