### ISSUE TITLE
How to run CockroachDB hosted on GKE across multiple Google Cloud regions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2590]
This is just a placeholder for now. Lush has documented [their approach](https://gitlab.com/LUSHDigital/open-source/cockroachdb/blob/79ec2f9b88415c66f10a4612925a249b54881301/README.md), but we need to clarify our understanding and approach before adding docs. 

In the meantime, it might be good to more clearly call out the limitation that a k8-orchestrated cluster cannot span multiple Google Cloud regions. Do you agree, @a-robinson?

**Comment by a-robinson** [comment]
I'm neutral on whether we need to explicitly call that out. It can span regions, we just don't offer instructions or tooling to help, and performance may be pretty bad if you do it poorly.

**Comment by jseldess** [comment]
OK, thanks, @a-robinson. I'll hold off for now.

**Comment by jseldess** [comment]
Closing in favor of this 2.1 roadmap work: https://github.com/cockroachdb/docs/issues/2933
