### ISSUE TITLE
Doc updates for /health?ready=1

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2594]
Need to mention in rolling upgrade docs and in load balancer instructions in deployment tutorials.

**Comment by jseldess** [comment]
@a-robinson, @bdarnell, just double-checking here: Should I emphasize the new ready=1 endpoint in instructions for configuring health checks for load balancers? For example: https://www.cockroachlabs.com/docs/dev/deploy-cockroachdb-on-aws.html#step-4-set-up-load-balancing

**Comment by a-robinson** [comment]
Yes, it's the most preferred load balancer health check. We've switched `cockroach gen haproxy` to use it as the default haproxy health check .

**Comment by jseldess** [comment]
@a-robinson, I'd like your input on how to update the rolling upgrade docs to feature `health?ready=1`. Not sure exactly where to call that out. http://www.cockroachlabs.com/docs/dev/upgrade-cockroach-version.html#step-2-prepare-to-upgrade

**Comment by a-robinson** [comment]
If we have a central documentation page around setting up / using a load balancer with us, I'd suggest just including it there and linking to that page. If we don't, it'd be nice to add one :) 

But if we don't have such a page, in the short term I think we could change the paragraph to say:

> Make sure your cluster is behind a load balancer that uses [CockroachDB's readiness health check](monitoring-and-alerting.html#health-ready-1), or your clients are configured to talk to multiple nodes. If your application communicates with a single node, stopping that node to upgrade its CockroachDB binary will cause your application to fail.

**Comment by a-robinson** [comment]
Also, maybe it's just me but it always confuses me that monitoring-and-alerting.html is listed under the "Deploy" heading while all the other monitoring-related pages are under the "Manage" heading.

**Comment by jseldess** [comment]
Add load balancing to the production checklist page, @a-robinson. Also, after Amruta merges an open PR, I'll reorganize the sidenav a bit. I want to list monitoring in the context of deployment, since it's so essential. I think I'll move that stuff up and rename the "Manage" section to "Maintain", making that section all about maintenance tasks (rolling upgrades, decommissioning, etc.).

Also, I'll update the rolling upgrade docs to point to the new section on production checklist.
