### ISSUE TITLE
update import csv documentation as "beta"

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#2599]
Import CSV is no longer going to be experimental, it will be beta. Update docs in 2.0 to reflect that.

Will also need to include the known limitations for 2.0, and how to mitigate them (using transform_only or rate limiting)

**Comment by jseldess** [comment]
@dianasaur323, can you add the specific known limitations to this tracking issue? https://github.com/cockroachdb/docs/issues/2446

**Comment by dianasaur323** [comment]
@mjibson has a lot more insight than I do, and you'll get a better answer from him. Regardless, the import csv docs should contain information on workarounds that are more specific than known limitations, so I think we should still include them here. @mjibson do you mind adding the specific known limitations to the tracking issue @jseldess linked to?

**Comment by mjibson** [comment]
The known limitations should be added to the import page itself, I think, instead of a known limitations page. Do you still want me to add it to that issue?

**Comment by dianasaur323** [comment]
I think we can add a short sentence of known limitations on the 2.0 page so that it's all in the same place, but agree that we should have all the known limitation in detail on the import page itself

**Comment by jseldess** [comment]
@mjibson, we can use an include to display the same content in both places. But don't worry about that. You can just put it on the import page for now and let us deal with the include.

**Comment by mjibson** [comment]
Ok. I'll document it over there then.

**Comment by Amruta-Ranade** [comment]
Closed via #2676
