### ISSUE TITLE
redirect docs. to /docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#26]
It's pretty common for docs to be at docs.company.com, so we should make sure that when users go to docs.cockroachlabs.com, they get redirected to cockroachlabs.com/docs. 

@mberhault, can you help with this at some point?

**Comment by mberhault** [comment]
I can definitely do a url redirect from `docs.cockroachlabs.com` to `cockroachlabs.com/docs`. But we shouldn't do that until we're ready to link to the docs from the rest of the site.

**Comment by jseldess** [comment]
OK, thanks, @mberhault. I'll ping again once we're there. Shouldn't be much longer.

**Comment by jseldess** [comment]
@mberhault put this in place. Thanks, Marc!
