### ISSUE TITLE
Indicate when a link is external

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2607]
As a reader, it's helpful to know if the link I am looking at is internal to the site, or points somewhere else.

In the past I have denoted this with a "little arrow thingy" (its technical name).  For example, see the Github link on http://prebid.org/support/

**Comment by jseldess** [comment]
@j-low, this would be a great UX improvement for the 2.2 timeframe.

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A11441

**Comment by jseldess** [comment]
This is done.
