### ISSUE TITLE
CI link checker may pass with links that are broken on live site

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2614]
See an example at https://github.com/cockroachdb/docs/pull/2613

I'm not claiming that this is common, just that I found one edge case; there may be more.

**Comment by rmloveland** [comment]
I think we should submit some PRs that use this incorrect link syntax and see what the new `htmltest` binary does with them.   Assuming it works as expected, we could close.

**Comment by jseldess** [comment]
Just tested in https://github.com/cockroachdb/docs/pull/4024. This does not seem to be an issue with htmltest, so closing.
