### ISSUE TITLE
Mentions of Golang code/data types in Architecture docs could link to Github sources

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2617]
It's implicit that these are data types/etc. that live in the code, but adding links to source code would make it explicit, and would save the reader who wants to skim some code a context switch.

For example, if we are going to mention a `planNode` explicitly, we could link to [a search of our codebase for `planNodes`](https://github.com/cockroachdb/cockroach/search?utf8=%E2%9C%93&q=planNodes&type=). The same would go for the other mentions of "code things".

**Comment by bdarnell** [comment]
I think that in general linking directly to specific pieces of code is more detail than we want in our docs. Github's search is not very good (maybe sourcegraph or something would work better), and linking to a specific file/line is a pain to keep up to date. On the other hand, if we do want to do this I'll point out that this is something sphinx excels at.

**Comment by jseldess** [comment]
This doesn't sound like something we should do. We can re-open this if we hear desire for users to link from our architecture docs to our code.
