### ISSUE TITLE
Use auto-generated markdown for cluster settings docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2620]
Possible since https://github.com/cockroachdb/cockroach/pull/23531.

Basically, we should copy https://github.com/cockroachdb/cockroach/blob/master/docs/generated/settings/settings.md to a new  `_includes/settings/v2.0/` directory. And then replace that manual table [here](https://github.com/cockroachdb/docs/blob/master/v2.0/cluster-settings.md#settings) with an include, i.e., `{% include setting/settings.md %}`.

**Comment by jseldess** [comment]
@dt, you want to claim this for fixitday, since this is all your generous doing?

**Comment by dt** [comment]
the current settings docs have a bit more detail than our in-code descriptions. I still think we should switch to auto-generation, but we might want to add a long-form description to the code that captures some of what we've done for these by hand.
