### ISSUE TITLE
Add documentation for new statement_timeout session variable

### ISSUE THREAD

**Issue by abhimadan** [cockroachdb/docs#2622]
Recently, a new session variable, `statement_timeout`, was added by https://github.com/cockroachdb/cockroach/pull/23399. It isn't cherry-picked into 2.0, so this is mainly a reminder to add it to the list of session variables later.

It has identical semantics to the [Postgres variable of the same name](https://www.postgresql.org/docs/10/static/runtime-config-client.html) if an int argument is provided, but it also accepts an interval or string argument (where the string can be parsed as a valid interval).

**Comment by jseldess** [comment]
Thanks, @abhimadan. It looks like we'll start auto-generating docs for cluster settings, but perhaps we'll want to call out this setting somewhere else in the docs as well, so leaving this open.

**Comment by jseldess** [comment]
Duplicate of https://github.com/cockroachdb/docs/issues/2046.
