### ISSUE TITLE
Kubernetes implementation guide 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#2630]
The Kubernetes blog as well as original documentation has joint blog posts around stateful sets and the specific DB. Could we do similar joint docs with K8s? 

e.g.,
Mongo also has a few official documentation/ articles in collaboration with K8 on the latter's page: 
http://blog.kubernetes.io/2017/01/running-mongodb-on-kubernetes-with-statefulsets.html

Cassandra documentation on the K8 page: 
https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

**Comment by jseldess** [comment]
@kannanlakshmi, just so I understand, your requesting that we repurpose our docs and submit an article for posting on the Kubernetes blog?
