### ISSUE TITLE
sql: Add information_schema.sequences table.

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/docs#2650]
Need to add another "view" to https://www.cockroachlabs.com/docs/dev/information-schema.html.

**Comment by vilterp** [comment]
@spencerkimball lmk if you don't get to this and I'll do it.

**Comment by spencerkimball** [comment]
Please feel free to snag it

**Comment by jseldess** [comment]
@vilterp, any chance you can add this view to `information-schema.md`?

**Comment by vilterp** [comment]
Finishing up clusterviz onboarding this week; I should be able to do this next week.

**Comment by jseldess** [comment]
@rmloveland, would be great if you can take this as your last 2.0 issue.

**Comment by vilterp** [comment]
Whoops, sorry for never getting around to this!

**Comment by ericharmeling** [comment]
@lnhsingh did this a while ago (https://github.com/cockroachdb/docs/pull/3531).
