### ISSUE TITLE
Jekyll not picking up include on pages with "allowed_hashes"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2659]
On pages like those linked below (which have the `allowed_hashes` key in the YAML header -- maybe the clue) adding an include to the page only works if you click the tabs into the "right-most" option.

<https://github.com/cockroachdb/docs/blob/master/v2.0/install-cockroachdb.html> is a good example, because in order to see the included content (which you can replicate using the patch at the bottom of this comment), you need to click the *Windows* tab, and then the *Use Docker* tab.

This issue also affects <https://github.com/cockroachdb/docs/tree/master/v2.0/start-a-local-cluster-in-docker.md>, which prompted me to file the issue.  In that case I was trying to add the note, but it would only appear when I clicked the *Windows* tab.

```
diff --git a/v2.0/install-cockroachdb.html b/v2.0/install-cockroachdb.html
index 1f449f7c..c0a94bed 100644
--- a/v2.0/install-cockroachdb.html
+++ b/v2.0/install-cockroachdb.html
@@ -563,6 +563,10 @@ $(document).ready(function(){
 <h2 id="whats-next">What's Next?</h2>
 <p><a href="start-a-local-cluster-in-docker.html#os-windows">Quick start</a> a multi-node cluster across multiple Docker containers on a single host, using Docker volumes to persist node data, or explore running a physically distributed cluster in containers using <a href="orchestration.html">orchestration</a> tools.</p>
 
+{{site.data.alerts.callout_info}}
+{% include available-capacity-metric.md %}
+{{site.data.alerts.end}}
+
 {% include diagnostics-callout.html %}
 
 </div>
```

**Comment by jseldess** [comment]
@rmloveland, I don't think this is an issue anymore, but please open if you disagree.
