### ISSUE TITLE
Admin UI docs don't include coverage of the Clock Offset graph

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#2664]
The Distributed dashboard was intentionally not documented because most of its contents aren't useful to users, but in the v2.0 release it contains the "Clock Offset" graph, which is of importance to users given that clock offsets are a real issue cluster admins have to care about.

I'm mentioning it in the FAQ as of https://github.com/cockroachdb/docs/pull/2663, but we may want to either document this separately or move it to a different dashboard if it's a major problem.

**Comment by a-robinson** [comment]
cc @couchand in case he has thoughts on whether the graph should be moved elsewhere, such as onto the Runtime dashboard. We actually have the analogous graph on the Runtime dashboard in our Grafana configs.

**Comment by couchand** [comment]
I guess I'm in favor of moving it to the Runtime dashboard so we don't have to create a new page for a dashboard that is otherwise undocumented.  As long as it fits there, which it sounds like it does.  @Amruta-Ranade do you concur?

**Comment by Amruta-Ranade** [comment]
@couchand Absolutely!

**Comment by a-robinson** [comment]
Alright, we should just add something about it to the Runtime page, then. I've updated https://github.com/cockroachdb/docs/pull/2663 to reference the Runtime page instead of the Distributed page.

**Comment by Amruta-Ranade** [comment]
I opened a Docs Issue to document this. Will get to it before 2.0
