### ISSUE TITLE
ui: cluster capacity usage inaccurate when multi-node cluster runs on same machine

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#2706]
Document #23596

**Comment by jseldess** [comment]
@Amruta-Ranade, I think @rmloveland is already handling this one: https://github.com/cockroachdb/docs/issues/2569

If it's the same, please close this as a duplicate.

**Comment by Amruta-Ranade** [comment]
@jseldess @rmloveland Awesome! Closing it now :)
