### ISSUE TITLE
EXPLAIN Doc Update - need to convert tables to english

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2709]
Re: [EXPLAIN](https://cockroachlabs.com/docs//v1.1/explain.html)

## Issue Description

+-------+------+-------+-------------+
| Level | Type | Field | Description |
+-------+------+-------+-------------+
|     0 | sort |       |             |
|     0 |      | order | +v          |
|     1 | scan |       |             |
|     1 |      | table | kv@primary  |
|     1 |      | spans | ALL         |
+-------+------+-------+-------------+

We show what the table looks like, but what would be really helpful is to convert this into a human understandable sentence after the table, so people understand how to read these as they get complex.

**Comment by jseldess** [comment]
@nstewart, did you see @RaduBerinde's updates to the 2.0 version of the page? Definitely improvements, though we have plenty of room for further work. 

https://www.cockroachlabs.com/docs/dev/explain.html

**Comment by nstewart** [comment]
Ah I didn't. I'll check those out.

**Comment by jseldess** [comment]
I think Radu's 2.0 updates are a significant improvement, so closing this for now. @nstewart, please reopen if you have feedback on the 2.0 version of the page.
