### ISSUE TITLE
Can't generate sql diagram

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2712]
When I try to generate the sql diagram for the `sort_clause.bnf` in cockroach, I get an error:

```
~/src/github.com/cockroachdb$ docgen grammar svg ./cockroach/docs/generated/sql/bnf/ ./docs/_includes/sql/v2.0/diagrams/ --filter=sort_clause
generating svg of sort_clause (cockroach/docs/generated/sql/bnf/sort_clause.bnf)
I180313 17:17:09.596038 34 diagrams.go:201  unfound spec: sort_clause
```

**Comment by mjibson** [comment]
I think this is happening because `name` is in the for loop scope and so changes when the go routine runs. Should be an easy fix.

**Comment by mjibson** [comment]
I wasn't able to repro this, but it's correct anyway. Maybe it'll help?
