### ISSUE TITLE
SQL feature support page should define what various values of 'Supported' mean

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2714]
On https://www.cockroachlabs.com/docs/stable/sql-feature-support.html I was confused about the check mark/black box distinction at first. 

"Alternative" seems deducible from the context but could be more precise. It's not always entirely clear how the alternative feature is used to implement the use case supported by the standard feature.

"Planned" is quite vague, though I'm not sure how to improve that. Do we have a public roadmap to link to? I do appreciate that we link to GH issues when available.

"Potential" is probably just a synonym for the black box in practice? Except that we might someday do it? Maintaining the distinction between the black box and potential implies that we don't plan on ever supporting the black-boxed features. Is that what we intend to communicate? If so we should explicitly add that to the definitions.

The "partial" entries are quite good.

Related: is there automated testing that we refer to when creating/updating the entries on this page?

**Comment by rmloveland** [comment]
This page has a nice legend we might use as an inspiration: https://github.com/ept/hermitage

**Comment by rmloveland** [comment]
Related to #4090.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
