### ISSUE TITLE
Fix the SELECT, INSERT, UPSERT diagrams

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2719]
It's messed up. 

@knz, could we work together on this? Or can you suggest someone who can help? It's been difficult for me to massage the 2.0 grammar into a single intelligible diagram.

**Comment by knz** [comment]
yes I think I understand what's wrong. please put a little spot in my calendar for today we can have a look.

**Comment by knz** [comment]
(30mn)
