### ISSUE TITLE
add hubspot analytics to docs

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#272]
@jseldess 

Can you add HubSpot analytics code to all the docs pages? 

`
  <script type="text/javascript">
    (function(d,s,i,r) {
      if (d.getElementById(i)){return;}
      var n=d.createElement(s),e=d.getElementsByTagName(s)[0];
      n.id=i;n.src='//js.hs-analytics.net/analytics/'+(Math.ceil(new Date()/r)*r)+'/1753393.js';
      e.parentNode.insertBefore(n, e);
    })(document,"script","hs-analytics",300000);
  </script>
`

Instructions for how to add it are available [here](http://knowledge.hubspot.com/getting-started-with-hubspot-v2/how-to-begin-tracking-your-marketing-data-within-hubspot) although I think it's pretty intuitive. 

Thank you!

**Comment by jseldess** [comment]
Adding code to all pages. @jess-edwards, please verify that it's working.

**Comment by jess-edwards** [comment]
@jseldess This is working. Thanks for adding the code! 

I have an SEO tool we can use on the docs pages at some point.
