### ISSUE TITLE
Explain that logs are in UTC

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2728]
This is indirectly indicated [here](https://www.cockroachlabs.com/docs/stable/debug-and-error-logs.html#write-to-file), but we should explicitly call it out somewhere. 

See @dt's answer to this forum post: https://forum.cockroachlabs.com/t/how-to-set-correct-time-zone-in-cockroach-log/1433/4

**Comment by rmloveland** [comment]
@jseldess based on what I'm seeing on [that debug log page](https://www.cockroachlabs.com/docs/stable/debug-and-error-logs.html), I'm thinking of doing something like the following:

1. Break out the log file format into a separate heading (e.g., **Log File Format**) with a little more reference info (this will include that it is in UTC quite explicitly)

2. In the existing *Write to File* section, change the brief format example into a link to the new file format section

3. ???

4. Profit

What do you think of this plan?

**Comment by rmloveland** [comment]
Alternatively, as a quick hit I could revise that section a little bit and add a callout that all log info is written in UTC, and leave it at that for now. (Call it option #2)
