### ISSUE TITLE
SHOW JOBS Doc Update - partitioning schema changes don't show up in jobs table

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#2741]
Re: [SHOW JOBS](https://cockroachlabs.com/docs//v2.0/show-jobs.html)

## Issue Description
We currently say that schema changes via `ALTER TABLE` show up in the jobs table. However, doing `alter table` with  `partition by list` doesnt actually create a job.

## Suggested Resolution 
Document the actual list of activities that create jobs (I don't know what they are)

**Comment by jseldess** [comment]
@Amruta-Ranade, you just updated this page, and you're currently working on the sql statement updates for partitioning, so can you please factor this in?
