### ISSUE TITLE
SQL Feature Support in CockroachDB v2.0 Doc Update 

### ISSUE THREAD

**Issue by Fale** [cockroachdb/docs#2743]
Re: [SQL Feature Support in CockroachDB v2.0](https://cockroachlabs.com/docs//v2.0/sql-feature-support.html)

## Issue Description
From https://github.com/cockroachdb/cockroach/issues/2969 it seems like the JSON support should be marked as present in version 2.0. Did something changes and therefore the feature will not land in 2.0?

## Suggested Resolution 
Mark JSON support as present

**Comment by jseldess** [comment]
Thanks, @Fale. We had this on the plan via https://github.com/cockroachdb/docs/issues/2578. I'll go ahead and make the update real quick.

**Comment by Fale** [comment]
Thanks :)
