### ISSUE TITLE
Docs does not specify how to connect new k8s cluster to each other

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#2750]
From a user survey:

"We are planning to roll out a global cockroach cluster, with each location being a separate Kubernetes cluster (with a locality specified in each kubernetes cluster). What is not clear from the documentation I've so far read is how we can connect the cockroach nodes hosted in the 2nd/3rd k8s clusters to the existing cockroach cluster." 

User runs CRDB on K8s (not production)

**Comment by jseldess** [comment]
Covered by https://github.com/cockroachdb/docs/issues/2933.
