### ISSUE TITLE
Add more detail to "Initialize a Cluster" from the `cockroach init` RFC

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2756]
[Initialize a Cluster](https://www.cockroachlabs.com/docs/stable/initialize-a-cluster.html) currently says that `cockroach init` "performs a one-time initialization", which may be an insufficient level of detail given that:

1. Users are engineers/DBAs who would likely want to know how/why it works a certain way
2. There is a semi-redundant alternative to just use `cockroach start` with no `--join` flag, which is very confusing (IMO) and makes it even more important that we be very explicit / informative about why `init` exists / how it works / what the difference is

To address this we should update [Initialize a Cluster](https://www.cockroachlabs.com/docs/stable/initialize-a-cluster.html) with more detail (including design rationale) from the [init RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170318_init_command.md).

**Comment by bdarnell** [comment]
> There is a semi-redundant alternative to just use cockroach start with no --join flag

I think we should get rid of that alternative: cockroachdb/cockroach#24118. We should at least be using the `init` command in all of our docs for multi-node clusters.

**Comment by jseldess** [comment]
Thanks for trigger this thread, @rmloveland. I'm on board with de-emphasizing startup with `init`, too. We mention it as an option in a few places. In our getting started docs, we should probably be setting expectation right. I actually took this approach in the training. 

I'll revisit this if there's time before the release. If not, directly after.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3395.
