### ISSUE TITLE
Execute SQL from a file

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#276]
karthik-gorthi @karthik-gorthi 10:50
@tschottdorf - Thank you! Is there a way to import a bunch of SQL present in a file in one-go? Like the "source" command in MySQL client?

Example:

```
$ vim file.txt

insert into t values (10);select * from t;

$ ./cockroach sql --database=test < file.txt
+----+
| x  |
+----+
|  0 |
|  1 |
|  2 |
|  3 |
|  4 |
|  5 |
|  6 |
|  7 |
|  8 |
|  9 |
| 10 |
| 10 |
| 10 |
| 10 |
+----+
```
Note, only the result of the last statement in the file is printed to stdout.

@tschottdorf, this right? Any ideas for a realistic example here?

**Comment by tschottdorf** [comment]
This works only with a file of SQL statements.

For example


CREATE DATABASE bank;
SET DATABASE = bank;
CREATE TABLE bank.accounts (id INT PRIMARY KEY, balance VARCHAR);

(hand-typed, so may contain mistakes).

On Mon, May 9, 2016 at 11:52 AM jseldess <notifications@github.com> wrote:

> karthik-gorthi @karthik-gorthi <https://github.com/karthik-gorthi> 10:50
> @tschottdorf <https://github.com/tschottdorf> - Thank you! Is there a way
> to import a bunch of SQL present in a file in one-go? Like the "source"
> command in MySQL client?
>
> Example:
>
> $ vim file.txt
>
> insert into t values (10);select * from t;
>
> $ ./cockroach sql --database=test < file.txt
> +----+
> | x  |
> +----+
> |  0 |
> |  1 |
> |  2 |
> |  3 |
> |  4 |
> |  5 |
> |  6 |
> |  7 |
> |  8 |
> |  9 |
> | 10 |
> | 10 |
> | 10 |
> | 10 |
> +----+
>
> Note, only the result of the last statement in the file is printed to
> stdout.
>
> @tschottdorf <https://github.com/tschottdorf>, this right? Any ideas for
> a realistic example here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/docs/issues/276>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
There's also `\| cat file.sql` to execute commands from a file if you're already in the sql shell. (in psql this can be written `\i file.sql`; maybe we should do the same)

**Comment by jseldess** [comment]
Added to forum: https://forum.cockroachlabs.com/t/execute-sql-from-file/53
