### ISSUE TITLE
Add constraint for K8s node running CockroachDB to not run any other pod

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#2765]
Based on discussion with @bobvawter , we need to add details to the [K8s config example files](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html) to ensure that a node doesn't run anything else besides CRDB.

+ @a-robinson : I couldn't find an existing issue for this, but if it's a dup, please close.

**Comment by bdarnell** [comment]
Why? Running a CockroachDB process on every node alongside your application is one of our target deployment scenarios. It's not our intention that CRDB should always be given an entire machine to itself.

**Comment by a-robinson** [comment]
The "best practice" thing to do is better instruct people how to set resource requests/limits on the cockroach pods.

More detailed thoughts:

1. As @bdarnell said, it's not clear why this behavior is needed/desired. It goes against some totally reasonable use cases for Kubernetes.
1. This would make our configuration unusable on most small clusters. Kubernetes runs a handful of "system" pods that are spread across the nodes when the Kubernetes cluster starts. Not running on a node that has one of these on it would typically rule out most or all of the nodes in a small cluster.
1. If the real desire is to have guaranteed resources for cockroach, that's a desire more directly expressed by asking for said resources with a resource request.
1. If you really do want dedicated nodes for cockroach, it requires a manual process to pick the nodes that the cluster admin wants to be dedicated.

**Comment by a-robinson** [comment]
Closed by https://github.com/cockroachdb/docs/pull/2896
