### ISSUE TITLE
HTML testing should check sidebar TOC entry contents

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2809]
Currently, when working on the docs, you can:

- Forget to rename a page link in the sidebar JSON file (say, you leave a link to a file that no longer exists)
- Build the site fine with no errors showing in Jekyll console
- Run `htmltest` and pass
- Still have a broken link on the live site you don't know about

Relates to #1696

**Comment by jseldess** [comment]
cc @benesch, in case you have ideas about how to update our TC job to account for the links in the sidenav.
