### ISSUE TITLE
Clarify relevant docs for external contributors

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/docs#2811]
A user on our forum suggested adding some info to the docs about the roles of the four sources of docs on internals (arch docs, `design.md`, tech notes, and rfcs). Here's the forum thread: https://forum.cockroachlabs.com/t/how-should-cockroachdb-open-source-contributors-leverage-the-existing-design-documentation/1465/2

Our existing "Contribute To CockroachDB" page seems like a good place to add this.

**Comment by jseldess** [comment]
On further thought, I think it's best that we keep users focused on our arch docs as they are kept most up-to-date.
