### ISSUE TITLE
Searching for 2.0 features like CREATE SEQUENCE fails to return results

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2818]
If I search for `CREATE SEQUENCE` by browsing to <https://www.cockroachlabs.com/docs/search.html?q=create%20sequence> directly after looking at a v1.1 page, the search returns no results.

If I browse to a given docs page and select v2.0 from the dropdown, and then re-run the search above, I do get results for the various `SEQUENCE`-y things. 

This is very confusing, since I have to remember what version of docs page I was last looking at before I searched - but I generally don't notice that.

Since there is a great deal of overlap in the content between, say, v1.1 and v2.0, I expect that if I search for a given string I will get all of the pages from whatever version that contain that string.  A "big bucket of results", if you will.

It would be less confusing if there were a dropdown on the search results page to let me toggle between search results per-version.

However, I would still not like it as much as the previous behavior where I was getting a "bucket of results", since I would now have to use the mouse, whereas before I had a browser [search keyword](https://support.mozilla.org/en-US/kb/how-search-from-address-bar).

Is it possible to get all of the results across all versions somehow?

Barring that, something on the results page that lets users know what set of results from what version they are looking at would also work.

**Comment by jseldess** [comment]
@rmloveland, would you mind putting this in @j-low's QA tracking sheet, so Joe has a central place to start from: https://docs.google.com/spreadsheets/d/1AmgbBSMDNYxcfUhy_qbEzeh9LEOra75OWKBHRNwOoPQ/edit#gid=0. 

I think row 4 ties in already.
