### ISSUE TITLE
Smoothen automatable tasks

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#2819]
- [ ] markup around diagrams to avoid markdown from going haywire
- [ ] js for copy-paste before examples 
  - [ ] clean up extant examples before doing so
- [x] div toc at the beginning
- [ ] automate the layout and indentation of SQL examples

**Comment by jseldess** [comment]
Automating the layout of SQL examples is now possible with sqlfmt. @mjibson has a PR open for this; I need to get back to it. 

The first two items would be nice, but we should wait until after the Hugo migration to reassess.

**Comment by jseldess** [comment]
@knz, I've opened a distinct issue for SQL example formatting: https://github.com/cockroachdb/docs/issues/7059.

When you have time, please open distinct issues for the first two tasks as well. I'd do so, but I don't quite understand them.
