### ISSUE TITLE
PushTxnQueue is now called TxnWaitQueue

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/docs#2828]
Re: [Transaction Layer](https://cockroachlabs.com/docs//v1.1/architecture/transaction-layer.html)

## Suggested Resolution 

Just rename it across the bank.

**Comment by jseldess** [comment]
Thanks, @tschottdorf. This has changed as of 2.0, right? Still called `PushTxnQueue` in 1.1?

**Comment by tschottdorf** [comment]
@jseldess yep!
