### ISSUE TITLE
SQL statements that require privileges on system tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2829]
Some sql statements require users to have privileges on system tables. We don't document this accurately right now. We need to track down these statements and update the privileges in the docs. 

See https://github.com/cockroachdb/docs/pull/2814#issuecomment-377694075

**Comment by lhirata** [comment]
Closing this issue - we searched pkg/sql and also used `git grep 'system\.' and didn't find any other statements that need to be updated.
