### ISSUE TITLE
Clarify usage of client certs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#283]
Feedback from user in Gitter: Secure a Cluster and the Install Client Drivers pages don't mention anything about using the client certificate, at least not for Python. Could also use some clarity... Are client certificates meant to work for only certain users?

**Comment by mberhault** [comment]
Under https://www.cockroachlabs.com/docs/manual-deployment.html, section "6. USE THE BUILT-IN SQL CLIENT", we can probably clarify by saying something along the lines of:
"... client certificate and key generated in step 1. The client certificate and key must be for the user specified in the url".

We may also want to clarify somewhere that the url is a libpq url and link to their docs: http://www.postgresql.org/docs/9.1/static/libpq-connect.html

**Comment by jseldess** [comment]
Our docs have improved here in the meantime. Further work is documented here: https://github.com/cockroachdb/docs/issues/3549
