### ISSUE TITLE
Function definitions could include minimum example code

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2844]
It would be very helpful to have a minimal working example for each of the [functions and operators](https://www.cockroachlabs.com/docs/dev/functions-and-operators.html).

Not a tutorial, just the minimum working code (including any minimum setup, if needed, as in the case of a sequence) that is copy-pasteable.

Perhaps each section could start out with the example data it will be operating on, e.g., everything in the **Sequence Functions** section would operate on the same sequence (if possible), and so on.  This would keep the examples very short.

**Comment by jseldess** [comment]
From @SpicyThrow:

https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#jsonb-functions

On this page, it would be helpful to have code examples for each of the JSONB functions. Many of the functions are not documented anywhere else and it would be difficult to implement them without prior understanding of the arguments.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
