### ISSUE TITLE
Use MovR for docs examples - Phase 1

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2849]
It would be extremely helpful if the entire documentation set could use one actual database that you could run queries against.

Some benefits of this approach would include:

- Better reproducibiliy and manual testability when writing docs, e.g., right now I am working on #2555 and I am re-populating a table "by hand" (possibly on 3 different binary versions) to test a single code snippet wrapped in a transaction

- Better automated testing (see #182)

- Better practices can be enforced if everything is in one jointly-maintained DB (see #190)

- Automation of various kinds can be explored that are not possible right now (related in spirit to #2819)

- Users could run the examples very easily while learning the DB.  For example, if this hypothetical DB were a `cockroach gen` output, they could have their own copy of the exact DB used to document everything running locally, eliminating any time lost to "guess and check" with the example code on the site.  The user can just copy-pasta it right into the prompt and see the exact same results.

- Examples would be "cut from the same cloth", in much the same way that C.J. Date's books use the parts database.  This helps reader comprehension since the context for the example is more easily understood.  Once you learn the parts database you can just focus on understanding the section about `JOIN`s or whatever, you aren't thinking too much about other aspects of the tables.

A drawback is that it might not be that easy to design an example database that covers all of our documented features.  And it could prove hard-ish to maintain for various other reasons, such as needing to update `cockroach gen` (if we went that way, but it seems like that would be the best way in principle to accomplish this).

However, I think the benefits would outweigh the drawbacks.  I think it would be a big win for users.

**Comment by jseldess** [comment]
As discussed offline, this is a very cool idea, but it's a big project that would need extensive planning. @nstewart, you mentioned a standard use case that Product will start using across content. Can you link us to any info on that?

**Comment by jseldess** [comment]
@rmloveland, I think this is a larger project that we're going to have the time for in 2.1, so I'm marking this as "later."  But it's definitely something we should investigate more, perhaps in conjunction with Product.

**Comment by nstewart** [comment]
[This is the database we used for the 2.0 meetup](https://github.com/cockroachlabs/pm/tree/master/2.0-user-meetup)

Bandwidth permitting we are moving things related to MovR [here](https://github.com/cockroachdb/movr)

**Comment by jseldess** [comment]
Now that `Movr` has been open-sourced, it's the obvious choice here: https://github.com/cockroachdb/movr

**Comment by nstewart** [comment]
@danhhz built this into the database directly at this point. This should remove a lot of boilerplate from certain docs.

```
Nathaniels-MacBook-Pro:~ nate$ cockroach demo movr
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB
# instance. Your changes will not be saved!
#
# Web UI: http://127.0.0.1:57764
#
# Server version: CockroachDB CCL v19.2.0-alpha.20190606-273-g95979f7 (x86_64-apple-darwin14, built 2019/06/21 13:46:32, go1.12.5) (same version as client)
# Cluster ID: 2d7ba835-2cc0-4e2a-bab2-dc6074c619e0
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:57763/movr> select * from users limit 1;
                   id                  |   city    |    name     |      address       | credit_card
+--------------------------------------+-----------+-------------+--------------------+-------------+
  c28f5c28-f5c2-4000-8000-000000000026 | amsterdam | Maria Weber | 14729 Karen Radial | 5844236997
(1 row)

Time: 996µs

root@127.0.0.1:57763/movr>
```

**Comment by ericharmeling** [comment]
As the new title suggests, we'll roll this change out in phases...

Breaking down Phase 1 into smaller tasks:
- [ ] Update first example: [Learn CockroachDB SQL](https://www.cockroachlabs.com/docs/stable/learn-cockroachdb-sql.html)
- [ ] Identify other examples that can use the `movr` dataset as-is (starting with [SQL statement](https://www.cockroachlabs.com/docs/stable/sql-statements.html) examples).
- [ ] Identify how the `movr` dataset needs to be updated to accommodate other examples.
- [ ] Start updating first batch of "as-is" examples (likely [SQL statement](https://www.cockroachlabs.com/docs/stable/sql-statements.html) examples).

... Phase 1 might take a couple sprints to complete.

Tentative Phase 2 (not in the scope of this sprint):
- [ ] Update `movr` dataset to accommodate all examples.
- [ ] Identify next batch for updates.

**Comment by ericharmeling** [comment]
I'm going to close this issue.
See #5040, #5041, and #5061 for issue coverage.
See #5075 for first-round updates.
