### ISSUE TITLE
Add FAQ entry on need for 3 datacenters to survive datacenter failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/docs#2854]
Unless I missed it, the current entry on [surviving failures](https://www.cockroachlabs.com/docs/v2.0/frequently-asked-questions.html#how-does-cockroachdb-survive-failures) omits a key point: you need three datacenters in order to survive the failure of a single datacenter. Two datacenters is insufficient. See also https://forum.cockroachlabs.com/t/experiments-on-disaster-recovery/1482/16.

**Comment by jseldess** [comment]
This is covered in https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#basic-topology-recommendations.
