### ISSUE TITLE
Explain how CockroachDB shards data

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2862]
From @WhiteTrashLord in https://github.com/cockroachdb/cockroach/issues/24465#event-1557066152:

Maybe you could add some more information to your documentation how CockroachDB is sharding data. I could not find any specific information. I also just had an idea that it might be good if the users can change the sharding strategy. For example I was thinking that if you can use only the foreign key (if there is any) for the sharding that this might make joins faster.

**Comment by WhiteTrashLord** [comment]
Some more technical details wouldn't be bad in my opinion. I really like the documentation of Redis for example: https://redis.io/topics/cluster-tutorial

**Comment by jseldess** [comment]
@sploiselle, leaving this open, in case you think of ways to explain this better in our architecture docs or elsewhere.

**Comment by slawo** [comment]
One interesting thing to expose would be the way data is distributed across ranges.
ie. if we need to access data in batches, it might make sense for us to batch the ids from the same range together and hit the node which has a replica of the range with our queries.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
