### ISSUE TITLE
Provide GCE and Azure region locations for populating the node map

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#2873]
We provide the lat/long coordinates for AWS regions in our node map docs, but as noted in https://github.com/cockroachdb/docs/pull/2872 they aren't always the same as for GCE/Azure regions. Both the region names and locations differ. We should do this work for at least the three major clouds so that our users don't have to.

**Comment by Amruta-Ranade** [comment]
The locations listed in the table are the common locations across AWS, GCE, and Azure. The reason we did this was because Azure has 36+ locations (and they add more regularly). So we decided to use AWS as the base, and add the common ones from Azure and GCE.

**Comment by a-robinson** [comment]
Hm, that is certainly a lot to deal with. I doubt it'd be a big deal if we fell behind and didn't have the very newest regions included -- it's less likely people will be using them.

And if Azure is the big problem, we could just add the GCE ones. IIRC we see more users on AWS and GCE anyway.

> So we decided to use AWS as the base, and add the common ones from Azure and GCE.

If that's the case, we should at least clarify that the region names aren't the same, or provide different copy-pastable commands for the similarly located ones on GCE/Azure. I ran into this when using GCE, and I blindly copied the commands for the regions that looked like mine (e.g. `INSERT into system.locations VALUES ('region', 'us-east-1', 37.478397, -76.453077)`), then had to figure out why the node map wasn't showing up for me. The commands didn't work because the GCE region name is `us-east1`, not `us-east-1`. Azure's regions are also named differently, e.g. "brazilsouth", "northcentralus", and "eastus2".

I understand that dealing with Azure's long, frequently-changing list would be a pain, and it's definitely your call. My vote would be to at least spell out copy-pasteable commands for the current GCE regions, though, even if the locations aren't all spot-on.

**Comment by bdarnell** [comment]
Azure offers a machine-readable list of regions and locations (`azure location list --json`, although for some reason you have to be logged in), so we could automate the update process for azure.

**Comment by Amruta-Ranade** [comment]
Another way to go (which we debated before choosing the current one) is to take a stand and list only AWS regions. Also, there's a possibility we might pre-feed all locations in the systems table next release onwards, so we won't have to list them in the doc anyways.

**Comment by a-robinson** [comment]
> Azure offers a machine-readable list of regions and locations (azure location list --json, although for some reason you have to be logged in), so we could automate the update process for azure.

Impressive, I wouldn't have expected that to include latitude/longitude info.

**Comment by a-robinson** [comment]
Thanks to @bdarnell's discovery, keeping Azure's list up to date is trivial:

```
~/play 0 $ cat azure_regions.py
import json
import sys

data = json.load(sys.stdin)
for location in data:
    print "|  %s (%s) | `INSERT into system.locations VALUES ('region', '%s', %s, %s)` |" % (location['name'], location['displayName'], location['name'], location['latitude'], location['longitude'])
~/play 1 $ azure location list --json | python azure_regions.py
|  eastasia (East Asia) | `INSERT into system.locations VALUES ('region', 'eastasia', 22.267, 114.188)` |
|  southeastasia (Southeast Asia) | `INSERT into system.locations VALUES ('region', 'southeastasia', 1.283, 103.833)` |
|  centralus (Central US) | `INSERT into system.locations VALUES ('region', 'centralus', 41.5908, -93.6208)` |
|  eastus (East US) | `INSERT into system.locations VALUES ('region', 'eastus', 37.3719, -79.8164)` |
|  eastus2 (East US 2) | `INSERT into system.locations VALUES ('region', 'eastus2', 36.6681, -78.3889)` |
|  westus (West US) | `INSERT into system.locations VALUES ('region', 'westus', 37.783, -122.417)` |
|  northcentralus (North Central US) | `INSERT into system.locations VALUES ('region', 'northcentralus', 41.8819, -87.6278)` |
|  southcentralus (South Central US) | `INSERT into system.locations VALUES ('region', 'southcentralus', 29.4167, -98.5)` |
|  northeurope (North Europe) | `INSERT into system.locations VALUES ('region', 'northeurope', 53.3478, -6.2597)` |
|  westeurope (West Europe) | `INSERT into system.locations VALUES ('region', 'westeurope', 52.3667, 4.9)` |
|  japanwest (Japan West) | `INSERT into system.locations VALUES ('region', 'japanwest', 34.6939, 135.5022)` |
|  japaneast (Japan East) | `INSERT into system.locations VALUES ('region', 'japaneast', 35.68, 139.77)` |
|  brazilsouth (Brazil South) | `INSERT into system.locations VALUES ('region', 'brazilsouth', -23.55, -46.633)` |
|  australiaeast (Australia East) | `INSERT into system.locations VALUES ('region', 'australiaeast', -33.86, 151.2094)` |
|  australiasoutheast (Australia Southeast) | `INSERT into system.locations VALUES ('region', 'australiasoutheast', -37.8136, 144.9631)` |
|  southindia (South India) | `INSERT into system.locations VALUES ('region', 'southindia', 12.9822, 80.1636)` |
|  centralindia (Central India) | `INSERT into system.locations VALUES ('region', 'centralindia', 18.5822, 73.9197)` |
|  westindia (West India) | `INSERT into system.locations VALUES ('region', 'westindia', 19.088, 72.868)` |
|  canadacentral (Canada Central) | `INSERT into system.locations VALUES ('region', 'canadacentral', 43.653, -79.383)` |
|  canadaeast (Canada East) | `INSERT into system.locations VALUES ('region', 'canadaeast', 46.817, -71.217)` |
|  uksouth (UK South) | `INSERT into system.locations VALUES ('region', 'uksouth', 50.941, -0.799)` |
|  ukwest (UK West) | `INSERT into system.locations VALUES ('region', 'ukwest', 53.427, -3.084)` |
|  westcentralus (West Central US) | `INSERT into system.locations VALUES ('region', 'westcentralus', 40.890, -110.234)` |
|  westus2 (West US 2) | `INSERT into system.locations VALUES ('region', 'westus2', 47.233, -119.852)` |
|  koreacentral (Korea Central) | `INSERT into system.locations VALUES ('region', 'koreacentral', 37.5665, 126.9780)` |
|  koreasouth (Korea South) | `INSERT into system.locations VALUES ('region', 'koreasouth', 35.1796, 129.0756)` |
|  francecentral (France Central) | `INSERT into system.locations VALUES ('region', 'francecentral', 46.3772, 2.3730)` |
|  francesouth (France South) | `INSERT into system.locations VALUES ('region', 'francesouth', 43.8345, 2.1972)` |
```

**Comment by a-robinson** [comment]
Google doesn't provide lat/long info via their API, unfortunately.

**Comment by jseldess** [comment]
Heard from a user via a docs feedback submission that it'd be good to include GCE locations as well.

**Comment by jseldess** [comment]
Considering this done with https://github.com/cockroachdb/docs/pull/2872.

Follow-up is https://github.com/cockroachdb/docs/issues/2885.
