### ISSUE TITLE
C# transaction code sample is missing RELEASE SAVEPOINT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2877]
The transaction example is missing the RELEASE SAVEPOINT statement so gives and error saying XX000: SAVEPOINT COCKROACH_RESTART has not been used

Reported via a docs feedback submission.

@BramGruneir, can you help out?

**Comment by rmloveland** [comment]
I think this will be fixed by #4213 ?

The following lines of C# from #4213 appear to handle this case (at least, if they cause `RELEASE SAVEPOINT` to be emitted as I imagine they would):

~~~
catch (NpgsqlException e)
              {
                // Check if the error code indicates a SERIALIZATION_FAILURE.
                if (e.ErrorCode == 40001)
                {
                  // Signal the database that we will attempt a retry.
                  tran.Rollback("cockroach_restart");
                }
                else
                {
                  throw;
                }
              }
            }
~~~

**Comment by BramGruneir** [comment]
Yeah, this should have been fixed  a while ago.  I thought I had fixed it and I didn't know that PR updating the code hadn't been merged yet.  Sorry for not following up earlier.

**Comment by rmloveland** [comment]
@BramGruneir sorry to be dense: are you confirming that this is no longer needed, and this issue can be closed?

**Comment by BramGruneir** [comment]
Just spent some time re-reading all of this.

Release Savepoint shouldn't be needed.  It should be optional.

Do we call it in any other examples?

**Comment by BramGruneir** [comment]
I thought it was optional, but I guess it wouldn't hurt to add the line in the same place in the C# code.
