### ISSUE TITLE
`Insecure` warning should also explain inter-node traffic considerations

### ISSUE THREAD

**Issue by dt** [cockroachdb/docs#2879]
Our FAQ entry on https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#security can lead a user to believe that if they trust their network's transport to be secure, they may not require TLS... but then they still want password verification "like most databases".

We should point out there that since nodes trust each other to enforce auth and proper access control, we need to be able to authenticate *nodes* when they try to join the cluster -- which we do via TLS. No TLS= any node can join / send RPCs = anyone can be root (compile a binary that skips checks and ask it to join).

I tried to explain this in [this forum thread](https://forum.cockroachlabs.com/t/secure-or-insecure-in-production-with-firewalls-loadbalancer-ssl-termination/1493/6), though it appears my explanation might need some help:
> part of the reason we don’t support password auth without TLS is that cockroachdb is a little different than “most databases”, namely in that it is distributed. Specifically the nodes in a cluster generally trust each other – e.g. if node3 connects to node1 and says hello, a equals 5 now, node1 believes it, and sets a=5.
> 
> If you want to ensure that only authorized users have access, in addition to checking their passwords during regular SQL connections, you also need to ensure only nodes you trust are allowed to join the cluster – otherwise someone could recompile a version that skips password verification and permission checks, tell it to join the cluster, and then circumvent the password checks and auth by connecting via that node.
> 
> Currently the way nodes authenticate each other is via TLS, so without TLS enabled, any node with network access can join the cluster, making password verification ineffective.
> 
> Obviously there are a couple ways you could try to fix this – you could do something like using the root user’s password to join a node to the cluster or something – but they add complexity to an area of the system where correctness is absolutely critical, so we don’t want to rush into a flawed solution. So far we have have yet to see a solution that’s as secure as just using TLS for everything.
>

**Comment by bdarnell** [comment]
We could also make it more clear that password-equivalent node authentication would be a new feature that would have to be designed and developed. We're not just saying "certs are better than passwords, so eat your vegetables, they're good for you". (We are kind of saying that when we don't allocate engineering time to this feature, but the point is that there's not some ready-made switch we could flip to enable a password-only mode)

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3549.
