### ISSUE TITLE
Document use of cfssl to generate certs

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#2899]
Still in the investigation phase, we need to determine:
1) how popular [cfssl](https://github.com/cloudflare/cfssl) is
1) how complicated it is to generate acceptable certs

At the very least, it's way simpler than `openssl` and better known than `cockroach cert`, so it would strike a good middle ground.

**Comment by zllovesuki** [comment]
`cfssl` is the tool when you are looking at CoreOS's TLS guide for etcd [1]. Kubernetes also include `cfssl` when you are generating certs [2].

[1]: https://coreos.com/etcd/docs/latest/op-guide/security.html
[2]: https://kubernetes.io/docs/concepts/cluster-administration/certificates/

**Comment by jseldess** [comment]
@mberhault, any more recent thoughts on this? Should we expand our cert docs to cover `cfssl` as well?

**Comment by Amruta-Ranade** [comment]
Also see https://github.com/cockroachdb/docs/issues/2923

**Comment by mberhault** [comment]
Reassigning: this is probably still worthwhile: cfssl is a much more modern and user-friendly method of dealing with certificates than openssl.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
