### ISSUE TITLE
Improve the Docs Doc Update 

### ISSUE THREAD

**Issue by sarfraz-tide-digital** [cockroachdb/docs#2905]
Re: [Improve the Docs](https://cockroachlabs.com/docs//v2.0/improve-the-docs.html)

## Issue Description
Documentation regarding "CREATE STATISTICS" appears to be missing. However syntax does appear under sql grammer.

**Comment by jseldess** [comment]
We added preliminary docs on this: https://www.cockroachlabs.com/docs/v2.1/create-statistics.html.
