### ISSUE TITLE
SQL best practice: SPLIT AT command to split up small hot ranges

### ISSUE THREAD

**Issue by tbg** [cockroachdb/docs#2907]
Re: [SQL Performance Best Practices](https://cockroachlabs.com/docs//v2.0/performance-best-practices-overview.html)

## Issue Description

Benchmarks on tables which are too small to split often result in a hot range and a single node in the cluster that is bottlenecked on CPU.

## Suggested Resolution 

Mention the `SPLIT AT` command to split up small hot ranges. Perhaps also mention that load-based splitting, which would make that obsolete, is on the roadmap.

The TPCC folks (cc @petermattis) can likely give concrete guidance on how to determine where and how much to split.

Thanks @vangheem for the pointer!

**Comment by awoods187** [comment]
We have load-based splitting now and don't need this
