### ISSUE TITLE
Evolve online training

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2919]
Priorities:
- [x] Expose all basic training modules on site.
- [x] Expand basic training to cover developer basics (SQL, drivers, transactions, etc.).
- [x] Update the training modules for 2.1.

**Comment by jseldess** [comment]
After discussions with @spencerkimball and Armen, we've decided to change course and expose all of the current content for maximal onboarding/adoption. In the future, we'll design and deliver more advanced courses for a fee.

We want to put the current content behind a login/email signup, and we want to explore replacing slides with videos.

**Comment by jseldess** [comment]
An option for putting authentication in front of part of our static site: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by Amruta-Ranade** [comment]
I am going through the training modules for self-learning and coming across some errors/scope-for-improvement. Here are my notes (WIP):

**Fault Tolerance and Automated Repair** 
Step 4 tells us to run this command:
`./cockroach sql --insecure --execute="SET CLUSTER SETTING server.time_until_store_dead = '1m0s';"`
Running the command gives the following error:
`Error: pq: cannot set server.time_until_store_dead to less than 1m15s: 1m0s
Failed running "sql"`

**Locality and Replication Zones**
- We can use the Node Map in the Web UI to explain localities and replication zones 
- Step 3: We can add a sentence between the code blocks for us-central and us-west. Else, I (user) ends up copy-pasting the code blocks without understanding what they are doing. Having a sentence distinguishing the code blocks per region will make them stop and think.
- Step 8: We can use the Web UI's data distribution matrix (http://localhost:8082/#/data-distribution) to show the distribution of data. 

**Data Import**
- Step 2,3: Sub-step 3: We can use UI > Databases > (Click on table name) to view schema
- UI > Jobs page to see status of Import (if required)

**Users and Privileges**

**Comment by jseldess** [comment]
Follow-up work:
- [ ] Integrate important 2.1 features
- [ ] Address existing feedback on training.

Moved out of scope:
- [ ] For at least some modules, replace slides with videos. 
- [ ] Put email signup in place.
- [ ] Research and possibly adopt an LMS.

Future:
- [ ] Build out additional intermediate/advanced trainings (possibly paid).
