### ISSUE TITLE
Performance benchmarking

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2920]
- [ ] Reference docs on `workload` and the characteristics and use cases for each included load generator. 
- [ ] Tutorials on benchmarking cockroach with our load generators.

@arjunravinarayan, @bdarnell, does this seem doable as a 2.1 docs project. I'm assuming we'll leverage Arjun's whitepaper and other existing resources.

**Comment by jseldess** [comment]
From @robert-s-lee: Our guidance needs to include graphing concurrency/throughput and resource/consumption for the each workload.

1. Run this workload.
2. Graph it.

**Comment by jseldess** [comment]
Resources:
- https://www.cockroachlabs.com/guides/cockroachdb-performance/
- https://www.cockroachlabs.com/blog/2-dot-0-perf-strides/
- https://www.cockroachlabs.com/blog/performance-part-two/
- https://apple.github.io/foundationdb/performance.html

**Comment by jseldess** [comment]
@arjunravinarayan's whitepaper has the core of what we need.

**Comment by jseldess** [comment]
Core features and performance 2.1 okrs focus on:
- tpcc 
- ycsb 

Do we want to limit our docs to these?

**Comment by lhirata** [comment]
our manual deployment docs now have a step, “Run a sample workload”, that shows how to get the `workload` binary and then use it to run `tpcc` against a cluster: https://www.cockroachlabs.com/docs/dev/deploy-cockroachdb-on-digital-ocean.html#step-9-run-a-sample-workload.

jesse put a callout in there linking readers to the performance white paper for benchmarking guidance, but once we have performance benchmarking docs, we can update that reference.
