### ISSUE TITLE
Description of ORDER BY preservation has invalid query

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/docs#2922]
In this section of the docs: https://www.cockroachlabs.com/docs/stable/query-order.html#order-preservation

The following query is used as an example of when ORDER BY would be preserved even though it's part of a subquery:
`SELECT (1, 2, 3) = (SELECT a.x FROM a ORDER BY a.x);`

However, if I try to run this query in the terminal, I get the error:
`unsupported comparison operator: <tuple{int, int, int}> = <int>`

I think this query should either be removed or replaced with a different one. There is already another example with `ARRAY()` which may be sufficient...

**Comment by knz** [comment]
Need to check how to make the example better. I think it might still be correct but the number of rows in the selected table matters. Or maybe the reporter is right and array() is necessary.

Anyway there is an important point to be made score order preservation in a scalar subquery and that point should not be removed.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
