### ISSUE TITLE
Create Security Certificates Doc Update 

### ISSUE THREAD

**Issue by fire** [cockroachdb/docs#2923]
Re: [Create Security Certificates](https://cockroachlabs.com/docs//v2.0/create-security-certificates-openssl.html)

## Issue Description

Possible to document a way to generate certificates using easyrsa?

## Suggested Resolution 

Document using easyrsa.

It can be based on the openssl instructions.

https://github.com/OpenVPN/easy-rsa/blob/v3.0.5/README.quickstart.md

**Comment by fire** [comment]
Example instructions:

```
wget https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.4/EasyRSA-3.0.4.tgz
tar xvf EasyRSA-3.0.4.tgz
cd EasyRSA-3.0.4
 ./easyrsa init-pki
./easyrsa build-ca
# Type a pass phrase cockroach
# Type the node's name
 ./easyrsa gen-req node nopass
 ./easyrsa gen-req client.root nopass
./easyrsa sign-req server client.root nopass
./easyrsa sign-req server node nopass
mkdir -p ../cockroach-cert
cp pki/ca.crt cert/
cp pki/private/node.key ../cockroach-cert
cp pki/issued/node.crt ../cockroach-cert
cp pki/private/client.root.key ../cockroach-cert
cp pki/issued/client.root.crt ../cockroach-cert
cp pki/private/ca.key ../cockroach-cert
cp pki/ca.crt ../cockroach-cert
```

This fails with `Error: x509: certificate is valid for node, not localhost`, but it's a good start.

Misc
```
./easyrsa revoke client.example
```

**Comment by mberhault** [comment]
I don't think these instructions will work, `node.crt` must be dual-purpose client and server authentication, and `client.root.crt` must be client authentication. Furthermore, `node.crt` must have `CN=node` in it, and any addresses and DNS names used to reach it in the SAN.

We can add it to the list of certificate tools to document alongside cfssl (see #2899), but more work is needed first.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
