### ISSUE TITLE
Time interval now supported in BACKUP ... AS OF SYSTEM TIME

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/docs#2928]
This was added in https://github.com/cockroachdb/cockroach/pull/24768. Our docs (https://www.cockroachlabs.com/docs/stable/backup.html#performance) mention that users in production should be running BACKUPs with a timestamp from 10 seconds ago to avoid affecting running transactions but this was previously manual. It can now be something like `BACKUP .. AS OF SYSTEM TIME '-10s'`.

**Comment by jseldess** [comment]
Thanks, @danhhz. This is 2.1-only, right?

**Comment by mjibson** [comment]
2.1 only. No cherrypick.
