### ISSUE TITLE
Allow users to identify bottlenecks in performance due to CPU / memory / IO / network issues

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2931]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recfqlgjfz58Unln0
PM: @piyush-singh 
Eng Partner: @couchand

**Comment by Amruta-Ranade** [comment]
Addressed by https://github.com/cockroachdb/docs/pull/3419
@piyush-singh @couchand Can I close this issue?

**Comment by Amruta-Ranade** [comment]
As discussed with @piyush-singh , closing this issue since it's addressed by the Hardware Dashboard doc.
