### ISSUE TITLE
Frictionless migration from MySQL to CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2936]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/rec341jbt9b5PVY22
PM: @nstewart 
Eng partner: @dt 

Part of https://github.com/cockroachdb/docs/issues/3140.

**Comment by jseldess** [comment]
- Things that are different and always will be different.
- Things that will improve over time (e.g., we're slow at foreign keys)

**Comment by rmloveland** [comment]
Fixed by #3766
