### ISSUE TITLE
Secure "Build an app" 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2943]
Update the "Build an app" tutorials to offer code samples for secure clusters (this should focus on jdbc/hibernate and expand out if possible) (#631)

**Comment by jseldess** [comment]
Moved performance-based work to a separate issue: https://github.com/cockroachdb/docs/issues/3584.

**Comment by jseldess** [comment]
At this point, we're only missing secure samples for:

- [ ] C++
- [ ] C#
- [ ] Closure
- [ ] Rust

Is that right, @rmloveland? If so, would you be ok with me opening a separate issue to complete that work at a later time?

**Comment by rmloveland** [comment]
> At this point, we're only missing secure samples for:
> 
>  C++
>  C#
>  Closure
>  Rust
> Is that right, @rmloveland <https://github.com/rmloveland>? If so, would you be ok with me opening a separate issue to complete that work at a later time?
> 
> 

Thanks for the reminder @jseldess - just opened https://github.com/cockroachdb/docs/issues/3700 <https://github.com/cockroachdb/docs/issues/3700> to track the remaining languages.
