### ISSUE TITLE
Troubleshoot Query Behavior Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#2953]
Re: [Troubleshoot Query Behavior](https://cockroachlabs.com/docs//v2.0/query-behavior-troubleshooting.html)

The page on troubleshooting perf issues should link to the perf best practices too: https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html

**Comment by jseldess** [comment]
Addressed by @Amruta-Ranade 's https://github.com/cockroachdb/docs/pull/4223, which will be merged soon.
