### ISSUE TITLE
Load-based splitting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2963]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/reciLw7LgFtpHT2oD
PM: @awoods187 
Eng Partner: @nvanbenschoten

**Comment by jseldess** [comment]
Moved to 2.2.

**Comment by jseldess** [comment]
@sploiselle, as of v2.2.0-alpha.20181119, this is on by default:

PR: https://github.com/cockroachdb/cockroach/pull/31413

From release notes:
> Load-based splitting is now enabled by default. In conjunction, the `range_min_bytes` setting in the `.default` replication zone is set to a higher value to prevent ranges from unnecessarily being considered for merging. [#31413][#31413] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@sploiselle, is there anything more to do here, or can we close?

**Comment by sploiselle** [comment]
All good to close; was documented [here](https://www.cockroachlabs.com/docs/v2.2/load-based-splitting.html).
