### ISSUE TITLE
Merge ranges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2964]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recVwbKWUfu87YRE4
PM: @awoods187 
Eng Partner: @benesch

**Comment by jseldess** [comment]
@benesch, I know this work is done, so when you feel like it's stable and ready for documentation, please work with Rich to understand the needed docs updates. Mostly, I think it'll be architecture doc updates.

**Comment by benesch** [comment]
Sounds good. We still haven't committed to turning merges on for v2.1, so
no doc updates yet. I'd say it's 50–50 whether we turn them on. Maybe it
would be easier to prepare the docs ahead of time just in case? I don't
know how swamped you guys are.

**Comment by jseldess** [comment]
Thanks, @benesch. Probably best to wait until we know if the feature is in or out. There's plenty left to do.

**Comment by rmloveland** [comment]
Hey @benesch just checking in: is range merging going to be turned on by default for 2.1?

**Comment by awoods187** [comment]
The plan is on by default unless we discover a bad bug between now and then

**Comment by jseldess** [comment]
Off by default in 2.1.

**Comment by awoods187** [comment]
It should be p-0. Range merges is in 2.1 (but off by default). We will want to recommend some users to try it in 2.1.2

**Comment by sploiselle** [comment]
@sploiselle Merge into 2.2 docs
