### ISSUE TITLE
Support bulk export of data from CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2967]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/reczKXKqVtdt2wHLw
PM: @dianasaur323 
Eng Partner: @dt

**Comment by Amruta-Ranade** [comment]
@dt @jseldess Please review the outline for the doc:

Outline:
- Enterprise feature tag
- Callout box saying this feature is in progress and slated for 2.1, so the flags and behavior are subject to change
- Storage requirements
- Export file location
- Table users and privileges
- Cancelling Export Job
- Synopsis
- Required privileges
- Parameters
  - table_name
  - export_location
  - kv_option
- Export file URLs (same include as IMPORT)
- Export Options
  - delimiter
  - nullas
  - comment
- Examples
  - Export entire table
  - Export part of a table
- Known limitations
   - Select stmt has to be compatible with distsql. If it’s incompatible, use the free version (`cockroach sql -e “select ….” —format=csv > my.csv`)

**Comment by jseldess** [comment]
@Amruta-Ranade, this LGTM to start off. Thanks for pulling it together quickly. One suggestion would be to nest topics similar to how we've done it in `IMPORT`, for example, putting "Storage requirements" and "Export file location" under "Details".
