### ISSUE TITLE
Configs for out of the box monitoring with Prometheus for K8s clusters

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2970]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recsZzJKktTgSfWrB
PM: @kannanlakshmi 
Eng Partner: @a-robinson

**Comment by a-robinson** [comment]
Engineering issue: https://github.com/cockroachdb/cockroach/issues/25185
