### ISSUE TITLE
Merge the two SQL execution engines

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2973]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recqqoaUBAaENck0t
PM: @awoods187 
Eng Partners: @arjunravinarayan, @asubiotto

**Comment by jseldess** [comment]
@jordanlewis, for the 2.1 docs, I think we just need to update the sql layer architecture docs and cleanup any reference to local vs. distsql engines. Does that sound right, and are we good to go at this point?

**Comment by jordanlewis** [comment]
More or less. The local engine is still available as a fallback of last resort (with `set distsql=off`), and will be removed completely in 2.2.

**Comment by jordanlewis** [comment]
But by default, everything now runs through the distributed engine. The old settings for `set distsql` (on/auto/always) now control whether the query will actually be distributed, as opposed to running on the gateway node only, but the queries always run through the distributed engine now. Does that make sense? I'm happy to sync up on this in person, as it's confusing.

**Comment by lhirata** [comment]
Will also want to document the heuristic that determines which queries should be distributed.
