### ISSUE TITLE
Planning Zigzag Joins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2974]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recSXt518uUYSnN8c
PM: @awoods187 
Eng Partners: @andy-kimball

**Comment by lhirata** [comment]
Zigzag joins have an option that Paul added - but they don’t actually get planned even if the option is set. We can’t plan zigzag joins at all right now.

Zigzag joins don't need to be documented for now, based on this info / my conversation with @jordanlewis. Will close this ticket for now, and will still document lookup joins (#3153)

**Comment by jseldess** [comment]
Moved to 2.2.

**Comment by awoods187** [comment]
This is still experimental and we don't recommend it for production use yet. I think this should just be in the list of experimental features
