### ISSUE TITLE
Support open source database tools

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2979]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recQn4SSaisYmtf7e
PM: @awoods187 
Eng Partner:

**Comment by jseldess** [comment]
@awoods187, @rmloveland, we should start planning our docs approach here soon. I think the MVP would be a new section of our docs where we call out various categories of third-party tools that we recommend/know people have been using with us. Thoughts?

**Comment by awoods187** [comment]
yeah i think a good brainstorming session is due. I'll set something up.

**Comment by jseldess** [comment]
In a meeting with @awoods187, @knz, @rmloveland, we decided to add a `Third-party tools` section to our docs and feature details about tools that we have tested in the following categories:

Schema migration
* Flyway

Database GUIs
* DBeaver
* Postico (Mac only)

ORMs
* Fully supported:
    * Hibernate
    * SQLAlchemy
* Beta:
    * GORM (maybe TypeORM)
    * ActiveRecord
    * Sequelize

Drivers
* All on docs
    * pgx as alternative for Go

IDEs
* Not certain yet (being tested):
    * IntelliJ
    * Eclipse

For tools we haven't validated, we should to GitHub issues.

**Comment by jseldess** [comment]
Some other db docs for inspiration/emulation:
- [Snowflake](https://docs.snowflake.net/manuals/user-guide/ecosystem-editors.html)
- [MongoDB](https://docs.mongodb.com/ecosystem/)

**Comment by rmloveland** [comment]
Closing since this is marked as "done" in Airtable.
