### ISSUE TITLE
Support _pg_expandarray

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2980]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recWVHP3qiV5L5ppC
PM: @awoods187 
Eng Partner:

**Comment by rmloveland** [comment]
Related:

- https://github.com/cockroachdb/cockroach/issues/16971
- ??? (will add others as they become apparent)

**Comment by jseldess** [comment]
Closing in favor of https://waffle.io/cockroachdb/docs/cards/5ada03ed281c900044db0406.
