### ISSUE TITLE
CLI tools: Replace the default table formatter

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2985]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recsvWfjWGaM1Pmbe
PM: @piyush-singh 
Eng Partner: @knz

**Comment by jseldess** [comment]
From the http://www.cockroachlabs.com/docs/releases/v2.1.0-beta.20180827.html release notes:

> The `cockroach sql` command and other client commands that display SQL results now use the new `table` result formatter by default, replacing the previous formatter called `pretty`. This provides more compact and more reusable results. 

PR: https://github.com/cockroachdb/cockroach/pull/28465

**Comment by jseldess** [comment]
@lhirata, this is ready.

**Comment by knz** [comment]
there is another relevant release note:

>    Release note (sql change): the `cockroach` sub-commands that print out
>    SQL results now issue a warning if more than 10000 result rows are
>    buffered in the `table` formatter.

this was actually a CLI change, sorry that the release note was miscategorized
