### ISSUE TITLE
Enable users to discover slow queries

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2987]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recdO722BzDq2EYAH
PMs: @piyush-singh 
Eng Partner: @couchand

**Comment by jseldess** [comment]
@Amruta-Ranade, this is the main issue for the Statements page, with https://github.com/cockroachdb/docs/issues/2223 maybe impacting the page as well.

**Comment by Amruta-Ranade** [comment]
From Celia: On this page: "https://www.cockroachlabs.com/docs/dev/admin-ui-access-and-navigate.html#navigate-the-admin-ui
> "The left-hand navigation bar allows you to navigate to the Cluster Overview page, cluster metrics dashboards, Databases page, and Jobs page."
mostly, I thought it'd be nice to mention the statements page (I think it was new for 2.1). so, super tiny nit"

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3886
