### ISSUE TITLE
Recovery from insufficient quorum

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2988]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recsHpZ7MFNX8Y9lX
PM: @rolandcrosby 
Eng Partner: @m-schneider

**Comment by jseldess** [comment]
Moved to 2.2.

**Comment by jseldess** [comment]
Moved to Later.

**Comment by rmloveland** [comment]
@johnrk I think this can be closed since it refers to an old Product roadmap item that was never worked on (at least according to AT?), by people who are no longer with the company.  Do you agree?  If yes, I'll close.

**Comment by johnrk** [comment]
This actually looks like an I/O and Recovery Item.

cc @mwang1026

**Comment by mwang1026** [comment]
Close it for now. Even if we build this tool we'd likely want them to reach out to support anyway until we flesh out the feature.
