### ISSUE TITLE
Install page links broken for users with adblockers

### ISSUE THREAD

**Issue by dt** [cockroachdb/docs#299]
Reported in gitter:
> apscomp @apscomp 15:38
> This link, works if you shift from one tab to another for installing cockroachDB between Mac, Linux, Windows... on IE... but not on chrome...
> https://www.cockroachlabs.com/docs/install-cockroachdb.html
> Even the sub tabs between Binary / Source /etc do not work on chrome
> 
> Andrei Matei @andreimatei 15:44
> "works for me” on chrome on os x
> 
> apscomp @apscomp 15:45
> sorry... forgot to inform... this is windows.... chrome version... : 52.0.2718.0 canary (64-bit)
> let me launch a fresh copy of the browser and check
> 
> David Taylor @dt 15:46
> try after disabling any adblockers?
> 
> apscomp @apscomp 15:47
> thanks david... works...
> had badger up and running...

**Comment by jess-edwards** [comment]
@dt Thanks for flagging. Could be a chrome bug? Let's hold off on any action here until we can confirm this on stable chrome.

**Comment by dt** [comment]
according to their last message it was disabling EFF's badger privacy tool that fixed it.

**Comment by dt** [comment]
Huh, looking at badger, it like it learns what domains are used to serve tracking cookies over time and starts block those, plus it allows the user to control behavior for a domain... so if this could easily vary from user to user, depending on their previous interactions with a given domain that we also happen to use like Google Analytics, CloudFlare, etc.

Playing with it though, I could only reproduce the reported behavior when I blocked CloudFlare CDN (I can't imagine many users go about their day-to-day browsing with cloudflare blocked).

**Comment by jseldess** [comment]
Closing this for now. I'll reopen if other users report this problem.
