### ISSUE TITLE
Cancel schema changes via SQL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2995]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/rec94taBF31uXtRr5
PM: @dianasaur323 
Eng Partners: @mjibson, @bobvawter

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/25571

From release notes:
> [`CANCEL JOB`](../v2.1/cancel-job.html) can now be executed on long-running schema change jobs, causing them to terminate early and roll back. [#25571][#25571]

**Comment by jseldess** [comment]
@Amruta-Ranade, pause and resume have been moved out of scope for 2.1, so cancel is the only focus. Aside from the small update to cancel job that you made in https://github.com/cockroachdb/docs/pull/3231, are there other docs that might need to be updated?

**Comment by Amruta-Ranade** [comment]
I don't think so. @mjibson might have more insight into this.

**Comment by mjibson** [comment]
Nothing else, correct.

**Comment by jseldess** [comment]
@Amruta-Ranade, as mentioned in Slack, my question is more about other docs that might need to be updated, not other features. Here's one page I found with a quick search that needs to be updated: https://www.cockroachlabs.com/docs/stable/manage-long-running-queries.html

**Comment by Amruta-Ranade** [comment]
Closed via:
https://github.com/cockroachdb/docs/pull/3239
https://github.com/cockroachdb/docs/pull/3231
