### ISSUE TITLE
Finalize upgrades automatically

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2996]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recfxL6QVy4FfFnA0
PM: @dianasaur323 
Eng Partner:

**Comment by jseldess** [comment]
Also need to update kubernetes tutorials.

**Comment by windchan7** [comment]
@jseldess Perhaps the following note is useful for users who want to turn off auto upgrade when they upgrade their nodes to v2.1 alpha.

By default, auto upgrade is turned on, so as soon as users do a rolling upgrade for all the nodes, the auto upgrade will take place.

 For users who want to disable auto upgrade, say they have a running cluster with N nodes. They should do a rolling upgrade for the first N-1 nodes, and stop the Nth node. 
Then they should run `SET CLUSTER SETTING cluster.preserve_downgrade_option = OLD CLUSTER VERSION` to prevent upgrade. Finally they can safely start up the last node with the new binary and the cluster version will remain the same.

Hope it helps.

**Comment by jseldess** [comment]
Thanks, @windchan7!

**Comment by bdarnell** [comment]
The preserve_downgrade_option setting is not yet in a 2.0.x release. So we'll need to introduce that setting in 2.0.3 and then you'll need to upgrade to that version to set the setting.
