### ISSUE TITLE
3rd Party Monitoring and Alerting Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2998]
Re: [Monitoring and Alerting](https://cockroachlabs.com/docs//v2.0/monitoring-and-alerting.html)

## Issue Description

Maybe restructuring of the 3rd party monitoring page and starting to list each new one as we encounter them

## Suggested Resolution 

Add DataDog https://docs.datadoghq.com/agent/prometheus/

**Comment by jseldess** [comment]
@robert-s-lee, can you clarify what you'd like the page to look like?

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
