### ISSUE TITLE
Community Forum test with Discourse

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#300]
https://github.com/discourse/discourse/blob/master/docs/INSTALL.md

cc: @jess-edwards

**Comment by jseldess** [comment]
Tested and liked. We now have a hosted version at https://forum.cockroachlabs.com.

**Comment by uded** [comment]
Can you confirm that there is a full support for Discourse with CockroachDB?

**Comment by jseldess** [comment]
@uded, this old issue was to get a Discourse instance started for Cockroach Labs, not to run Discourse on top of CockroachDB. For that question, it's probably best to ask in our Community Slack: https://cockroa.ch/slack
