### ISSUE TITLE
Document how to work with CockroachDB in an autoscaling group

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3000]
See the confusion [here](https://forum.cockroachlabs.com/t/aws-autoscalinggroup-and-networkloadbalancer/1534)

We need an answer for this.

cc @kannanlakshmi

**Comment by nstewart** [comment]
@jseldess adding this to the docs project backlog for production guidance

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
