### ISSUE TITLE
New cluster settings for extra safeguards against clock offset jumps

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3006]
- [Setting for HLC to be monotonic across restarts](https://github.com/cockroachdb/cockroach/pull/24624)
- [Setting for HLC to panic on clock jumps](https://github.com/cockroachdb/cockroach/pull/24606)

This applies to both 2.0 and 2.1 docs.

**Comment by bdarnell** [comment]
The 2.0 branch docs should note that the settings are new in 2.0.1.
