### ISSUE TITLE
Create asciinema screencast - start a local cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#301]
Using [asciinema](https://asciinema.org/docs/usage), run through the instructions on Start a Cluster. Then embed the video on the page.

**Comment by jgannon** [comment]
Hi @jseldess - hope this asciinema file saves you some time :) 
 
[crdbstartcluster.txt](https://github.com/cockroachdb/docs/files/288422/crdbstartcluster.txt)

Let me know if there is anything else I can do to get it over the finish line. Thanks.

**Comment by jseldess** [comment]
Thanks very much, @jgannon. I think this is great. I need to get feedback from a few devs here to make sure we don't want to take an approach different from the page. I'll get back to you. Thanks for helping out!

**Comment by jseldess** [comment]
@jgannon, we finally got this done. We tweaked the steps a bit, and decided to host the asciicast ourselves. Thanks very much for your effort, though!
