### ISSUE TITLE
ALTER INDEX ... RENAME can now be used on the primary index

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3011]
PR: https://github.com/cockroachdb/cockroach/pull/24777

This applies to both 2.0 and 2.1 docs.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

**Comment by jseldess** [comment]
Docs are already correct.
