### ISSUE TITLE
Set minimal height for docs pages

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/docs#3016]
We should set a minimal height for pages so the height spans nicely on the screen, and the footer doesn't show up to add more noise on short pages like this: 
![image](https://user-images.githubusercontent.com/1486483/38104902-a0d71cc8-3358-11e8-82bc-8e18981c2871.png)

cc: @jseldess

**Comment by j-low** [comment]
No longer relevant in current layout.  Closing.
