### ISSUE TITLE
Document PCI TLS minimum version compliance 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3023]
CockroachDB is used in PCI applications.  Maybe useful to document couple of security aspects for application developers.  

CockroachDB requires client to connect with at least TLS 1.2

2018/6/30 is the deadline for disabling SSL/early TLS and implementing a more secure encryption protocol – TLS 1.1 or higher [(TLS v1.2 is strongly encouraged)](https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls) in order to meet the PCI Data Security Standard (PCI DSS) for safeguarding payment data.

@bdarnell @mberhault you may have more input on the topic.

**Comment by jseldess** [comment]
@Amruta-Ranade, this can be factored into https://github.com/cockroachdb/docs/issues/3415.

**Comment by Amruta-Ranade** [comment]
@robert-s-lee The Authentication doc mentions that "CockroachDB uses TLS 1.2 digital certificates for inter-node and client-node authentication". 

Is this enough or should we include more info?

**Comment by mberhault** [comment]
You can say "CockroachDB **requires** TLS 1.2". In the sense that we won't even accept connections using TLS 1.1 or lower.
