### ISSUE TITLE
Floating top nav covers anchor-linked content

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3026]
As a user, it's very confusing to click on an anchor link and the content of the anchor is chopped off at the top.  It's disorienting and leaves me not sure what I'm supposed to look at.

I think we have a few options to address this:

1. If we must float the navbar we could add some logic to slide the page content down by whatever amount of screen the navbar consumes.

2. If floating the navbar in the `/docs` section of the site is not a requirement, we could turn it off.  (I would prefer this option as a frequent reader of the docs, but of course there are other considerations.)

3. Something else?

(Adding some illustrative screenshots as comments below.)

**Comment by rmloveland** [comment]
Blocked anchor content (half of table cell is occluded):

![screenshot 2018-04-25 16 23 58](https://user-images.githubusercontent.com/1312291/39270951-8f9dc792-48a5-11e8-90ba-b11ba0bc8e8d.png)

Without the floating nav:

![screenshot 2018-04-25 16 23 11](https://user-images.githubusercontent.com/1312291/39270977-a405a358-48a5-11e8-8d95-2d254d7473f8.png)

**Comment by jseldess** [comment]
This is a dup of https://github.com/cockroachdb/docs/issues/1451, I believe, so closing. But please comment on the other issue to give it more weight. I definitely agree that this is very annoying.
