### ISSUE TITLE
Improve our Production docs

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3027]
@jseldess Need to identify which production docs we want feedback on. Will update this issue with the links to those docs.

**Comment by lleonard-msft** [comment]
In Step 3 of [Start a Local Cluster](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html), the use of ports for the SQL client is a bit confusing to a newbie.  Perhaps a simple sentence mentioning the default port after starting the session would help.

**Comment by jseldess** [comment]
Updated in the meantime.
