### ISSUE TITLE
Improvements to Getting Started docs

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3028]
1. [Install CockroachDB](https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html)
2. Try out any or all of the following tutorials:
   - [Data replication](https://www.cockroachlabs.com/docs/stable/demo-data-replication.html)
   - [Fault Tolerance and Recovery](https://www.cockroachlabs.com/docs/stable/demo-fault-tolerance-and-recovery.html)
   - [Automatic Rebalancing](https://www.cockroachlabs.com/docs/stable/demo-automatic-rebalancing.html)
   - [Follow the workload](https://www.cockroachlabs.com/docs/stable/demo-follow-the-workload.html)
3. Comment on this issue with your feedback about the clarity, correctness, and ease-of-use of the docs.

**Comment by kbatuigas** [comment]
From [Start a Local Cluster (Insecure)](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html): 

- Code snippet under Step 1. Start the first node copies as `cockroach start --insecure --host=localhost` into Windows Powershell, resulting in an error "The term 'cockroach' is not registered as the name...". Adding `./` (i.e. `./cockroach start --insecure --host=localhost` ) allows the command to run successfully

**Comment by kbatuigas** [comment]
From [Start a Local Cluster (Insecure)](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html): 

- Copying the code snippets into Windows Powershell ISE also copies the backslashes and new lines, resulting in an error

**Comment by dianaprince** [comment]
On step 3, when testing the cluster, I closed the terminal for Node 1 which resulted in "files still in use" errors when attempting to stop the cluster on step 5.

**Comment by dianaprince** [comment]
Minor grammatical notes: write out the number when the number is less than ten. For example, "3 or more nodes" should be "three or more nodes."

Also, punctuation goes inside quotation marks, so on step 5 "failure", should be "failure,"

**Comment by kbatuigas** [comment]
From [Start a Local Cluster (Insecure)](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html): 

- Under Step 3. Test the Cluster: running `./cockroach sql --insecure` in **Windows Powershell ISE (x86)** appears to connect to the SQL shell, but the terminal isn't "responsive" (i.e. the cursor doesn't appear, and nothing happens when you try to type anything). However, it runs and connects fine in Windows Powershell, and I am able to type and run SQL statements.

**Comment by jseldess** [comment]
From @lleonard-msft:

> In Step 3 of Start a Local Cluster, the use of ports for the SQL client is a bit confusing to a newbie. Perhaps a simple sentence mentioning the default port after starting the session would help.

**Comment by jseldess** [comment]
Thank you for this feedback, @dianaprince, @kbatuigas, and @lleonard-msft!

**Comment by jseldess** [comment]
These pages have gone through a few iterations since we received this feedback, and they will be updated again soon. Closing this issue for now.
