### ISSUE TITLE
Improve our Docs contribution process

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3029]
Go through the process described in [Contributing to CockroachDB](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md) docs and comment on this issue with your feedback.

We appreciate feedback about the clarity, understandability, and ease-of-use of the process. if you have suggestions about how we can improve the process, feel free to add them to your comments as well.

**Comment by kbatuigas** [comment]
From [Install CockroachDB](https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html):

- Step 2 under "Download the Binary" - copying to clipboard copies directory path, but only` .\cockroach.exe version` is necessary after having navigated to directory
