### ISSUE TITLE
Document CASCADE/RESTRICT options for DROP CONSTRAINT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3034]
These options are present in the diagram but not in the **Parameters** list. 

See similar statements for guidance:
- [`DROP COLUMN`](https://www.cockroachlabs.com/docs/stable/drop-column.html)
- [`DROP INDEX`](https://www.cockroachlabs.com/docs/stable/drop-index.html)

This info is missing from both 2.0 and 2.1 docs.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

**Comment by jseldess** [comment]
@VickiL is working on this.

**Comment by jseldess** [comment]
```
radu=> create table parent (id int);
radu=> create table child (id int, p_id int);
radu=> alter table parent add constraint foo unique (id);
radu=> alter table child add constraint bar foreign key (p_id) references parent(id);
radu=> alter table parent drop constraint foo restrict;
ERROR:  cannot drop constraint foo on table parent because other objects depend on it
DETAIL:  constraint bar on table child depends on index foo
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
radu=> alter table parent drop constraint foo cascade;
NOTICE:  drop cascades to constraint bar on table child
ALTER TABLE
```

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
