### ISSUE TITLE
Add copy-to-clipboard function to Development docs

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3039]
**Task**
Go through the docs in the **Develop** section of the [CockroachDB docs](https://www.cockroachlabs.com/docs/stable/) and add the Copy-to-Clipboard function for executable code blocks.

**Context:**
Many of our code blocks are written so users can copy and paste them directly into a terminal. To make that easier, add a Copy to Clipboard feature by placing

`{% include copy-clipboard.html %}`
on the line directly preceding the code block, for example:

```
{% include copy-clipboard.html %}
~~~ shell
$ go get -u github.com/lib/pq
~~~
```

Important:
- Use the Copy to Clipboard function only for code blocks with commands that can be executed, not for the code blocks that show the response of the execution.
- If a code block contains more than one command, split it into multiple code blocks, one per command, and use the copy-to-clipboard function for each.

**Comment by Shiwanee** [comment]
Hi Amruta!
I would like to work on this issue. Could you please provide me some more details?
I am new to CockroachDB, but I have gone through the process of basic set-up required for contributing to writing.
Thanks,
Shiwanee

**Comment by jseldess** [comment]
We got though most if not all of this in the meantime. Closing.
