### ISSUE TITLE
server, ui: Move the diagnostics endpoint from admin to status

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3062]
PR: https://github.com/cockroachdb/cockroach/pull/24997

From release notes:
> Added a `/_status/diagnostics/{node_id}` debug endpoint, which returns an [anonymized diagnostics report](../v2.1/diagnostics-reporting.html). [#24813][#24813] [#24997][#24997]{% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
@jseldess Discussed this issue with Bram: We are not sure if we document all endpoints (AFAIK, we don't document *all* endpoints). So unsure if this issue has a doc impact. Can you help us decide please?

**Comment by jseldess** [comment]
Ah, yes. This ties into https://www.cockroachlabs.com/docs/dev/diagnostics-reporting.html. I have another issue about diagnostics reporting, so I can take this, if you want.

**Comment by Amruta-Ranade** [comment]
SGTM!
