### ISSUE TITLE
sql: fix the batching behavior of mutation statements, especially with RETURNING

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3068]
PR: https://github.com/cockroachdb/cockroach/pull/23373

From release notes:
> The [`EXPLAIN`](../v2.1/explain.html) output for [`UPDATE`](../v2.1/update.html) statements now also report [`CHECK`](../v2.1/check.html) expressions, for consistency with `INSERT`. [#23373][#23373] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@knz It's my opinion that this issue does not require a doc update.  Do you agree with that assessment?

For context, I played with the `EXPLAIN DELETE FROM ...` and `EXPLAIN INSERT INTO ...` output from the tests a bit, but  AFAICT we don't currently document the `EXPLAIN` output at the "statement X is EXPLAINed as output Y" level of granularity.  Please let me know if I'm misunderstanding something here, though.

**Comment by knz** [comment]
> It's my opinion that this issue does not require a doc update. Do you agree with that assessment?

correct!
