### ISSUE TITLE
sql: add the ability to access a column from the results of an SRF

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3070]
PR: https://github.com/cockroachdb/cockroach/pull/24832

From release notes:
> Set Returning Functions (SRF) can now be accessed using `(SRF).x`, where `x` is the name of a column returned from the SRF or a `*`. For example, `SELECT (information_schema._pg_expandarray(ARRAY['c', 'b', 'a'])).x` and `SELECT (information_schema._pg_expandarray(ARRAY['c', 'b', 'a'])).*` are now both valid. Also, the naming of the resulting columns from SRFs now provide more information about the resulting tuple. [#24832][#24832] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Relates to #3142
