### ISSUE TITLE
sql: fix the batching behavior of mutation statements, especially with RETURNING

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3075]
PR: https://github.com/cockroachdb/cockroach/pull/23373

From release notes:
> Removed a limitation where `UPDATE`, `INSERT`, or `UPSERT` would fail if the number of modified rows was too large. [#23373][#23373] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Closing this issue; it looks like it has already been addressed in https://github.com/cockroachdb/docs/pull/3013.

@knz or @jseldess, please re-open if I am wrong about this.
