### ISSUE TITLE
backupccl: support restoring views with into_db

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3081]
PR: https://github.com/cockroachdb/cockroach/pull/24555

From release notes:
> It is now possible to [`RESTORE`](../v2.1/restore.html) views when using the `into_db` option. [#24555][#24555] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with David, this is already documented correctly. (#24555 is a bug fix)
