### ISSUE TITLE
jobs: Allow leniency before stealing work

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3082]
PR: https://github.com/cockroachdb/cockroach/pull/23913

From release notes:
> The new `jobs.registry.leniency` [cluster setting](../v2.1/cluster-settings.html) can be used to allow long-running import jobs to survive temporary node saturation. [#23913][#23913] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @benesch, this is not a user-facing change. According to him, it’s safer to not document it. Users would only be expected to change it under the direction of a Cockroach Labs support person.
