### ISSUE TITLE
sql: add SHOW STATISTICS AS JSON, INJECT STATISTICS

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3086]
PR: https://github.com/cockroachdb/cockroach/pull/24488

From release notes:
> The new `SHOW STATISTICS USING JSON` variant of `SHOW STATISTICS` outputs table statistics as a JSON object; it can be used to extract statistics from clusters to reproduce issues. [#24488][#24488] {% comment %}doc{% endcomment %}
>
> The new `ALTER TABLE ... INJECT STATS` command injects table statistics from a JSON object (which can be obtained via `SHOW HISTOGRAM USING JSON`). [#24488][#24488] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
@RaduBerinde, is ` SHOW STATISTICS USING JSON` / `ALTER TABLE ... INJECT STATISTICS` an internal-only feature? They don't appear in `\h SHOW`

**Comment by RaduBerinde** [comment]
The `CREATE STATISTICS` command will be experimental in 2.1. These other commands aren't very useful without using that too. Not sure if that makes these experimental as well. Either way, I don't think they need to be documented for 2.1.

I will make a PR to rename `CREATE STATISTICS` to `CREATE EXPERIMENTAL_STATISTICS` and I will fix the help messages as well.

**Comment by jseldess** [comment]
Thanks, @RaduBerinde. @lhirata, you can go ahead and close this. We'll document these statements once they mature out of experimental status.
