### ISSUE TITLE
cli: add "skip" option to IMPORT CSV DATA

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3093]
PR: https://github.com/cockroachdb/cockroach/pull/23466

From release notes:
> Added the `skip` option to the `IMPORT` command. [#23466][#23466] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
PR: https://github.com/cockroachdb/docs/pull/3510

**Comment by Amruta-Ranade** [comment]
Closed by https://github.com/cockroachdb/docs/pull/3510
