### ISSUE TITLE
ui: clusterviz: correct liveness status text on nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3098]
PR: https://github.com/cockroachdb/cockroach/pull/23255

From release notes:
> The **Node Map** now shows how long a node has been dead. [#23255][#23255] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
IMO, this is already documented to reflect the correct functionality:
https://www.cockroachlabs.com/docs/v2.1/admin-ui-access-and-navigate.html#node-map-enterprise

The way it is documented, we don't explain the details of the components, just what they represent. So  I don't think we need doc updates for the current docs. However, we might want to consider documenting the details of the components as a follow-up, good-to-have-if-time-permits PR.

@jseldess Thoughts?

**Comment by jseldess** [comment]
Sounds good to me, @Amruta-Ranade. Feel free to close this and open a broader issue to explain the details of the components. But only if you think that's necessary and helpful.

**Comment by Amruta-Ranade** [comment]
Thanks! Closing this one for now.
