### ISSUE TITLE
sql: make SHOW TABLES able to inspect arbitrary schemas

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3100]
PR: https://github.com/cockroachdb/cockroach/pull/22994

From release notes:
> `SHOW TABLES` is once again able to inspect virtual schemas. [#22994][#22994] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
I think we already document the expected behavior: https://www.cockroachlabs.com/docs/dev/show-tables.html

@knz Am I right in thinking this issue doesn't need doc updates?

**Comment by knz** [comment]
yes correct!
