### ISSUE TITLE
Don't use --background flag with docker

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#311]
From Gitter:

Michael Hausenblas @mhausenblas
yo, folks, anyone an idea why docker run cockroachdb/cockroach:beta-20160519 start --background is dying on me?
FWIW, I experience the same when I build it from scratch like so:

```
 FROM ubuntu:14.04
MAINTAINER Michael Hausenblas "michael.hausenblas@gmail.com"
ENV REFRESHED_AT 2016-05-22T07:37Z

RUN    apt-get -qq update \ 
    && apt-get -f install \
    && apt-get -y install wget \
    && wget https://binaries.cockroachdb.com/cockroach-beta-20160519.linux-amd64.tgz \
    && tar xfz cockroach-beta-20160519.linux-amd64.tgz

EXPOSE 8080
ENTRYPOINT ["cockroach-beta-20160519.linux-amd64/cockroach"]
CMD ["start", "--background"]
```

Funnily enough, when I start out with a ubuntu:14.04 image and do the steps manually, it works 8->

Ben Darnell @bdarnell 05:56
@mhausenblas Don’t use —background when running under docker (or systemd, or anything else that’s going to monitor the process). —background is just for starting from a plain shell

Michael Hausenblas @mhausenblas 05:56
got it, thanks @bdarnell!
might wanna make this explicit in the docs? also, adding the Dockerfile in https://hub.docker.com/r/cockroachdb/cockroach/ might help
or did I fail RTFMing? 

Ben Darnell @bdarnell 06:02
no, we don’t have good docs for running in docker right now. we still need to sort out the best way to manage volumes, ports, etc
we recommend running without docker for now
also, i understand that we need to document that you should run docker run cockroachdb/cockroach start instead of start —background, but how does putting the Dockerfile on hub.docker.com help? the Dockerfile is all implementation details, not instructions

**Comment by jseldess** [comment]
With @tamird's help, figured out how to run a multi-node cluster, each node in a different container. All on a single host. This will turn into a "Start a Local Cluster in Docker" tutorial. Here's my current process. @petermattis and @mberhault, can you PTAL and let me know what you think about using this for the docs? As Pete mentioned, for a multi-host scenario, we'll need a different approach with Docker Swarm or something else.

```
# Create a bridge network for container communication:
$ docker network create -d bridge mynetwork

# Start first node (`hostname` defines the address to advertise to other containers, -P exposes all ports):
$ docker run --name=roach1 --hostname=roach1 --net=mynetwork -P cockroachdb/cockroach:beta-20160602 start --insecure

# Start second node (`join` uses container 1's hostname):
$ docker run --name=roach2 --hostname=roach2 --net=mynetwork -P cockroachdb/cockroach:beta-20160602 start --insecure --join=roach1

# To verify that they're joined:
# I start the sql client in container 1 and create a new database:
$ docker exec -it roach1 bash
root@roach1:/cockroach# ./cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
+----------+
root@:26257> create database test;
CREATE DATABASE
root@:26257> ^D
root@roach1:/cockroach# exit
exit

# Then I start the sql client in container 2 and show databases:
$ docker exec -it roach2 bash
root@roach2:/cockroach# ./cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| test     |
+----------+
```

The main problem remaining is finding a way to open the admin UI from outside of Docker. I suspect that it'll involve mapping container ports to host ports.

**Comment by tamird** [comment]
It's going to involve more than that - you'll need to map VM ports to host
machine ports.

**Comment by petermattis** [comment]
@tamird Only on Mac/Windows. And I believe that goes away when [docker for mac/windows](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) replaces VM-based docker.

**Comment by tamird** [comment]
Yeah, maybe.

**Comment by jseldess** [comment]
So according to [this](https://www.ctl.io/developers/blog/post/docker-networking-rules/) and other pages, I've found, `-P` should automatically create port mapping rules. 

Once container/node `roach1` is up, for example, I see these mappings:

```
$ docker port roach1
8080/tcp -> 0.0.0.0:32793
26257/tcp -> 0.0.0.0:32792
```
 
But pointing a browser to `0.0.0.0:32793` still gives me `0.0.0.0 refused to connect.` Why is this?

**Comment by tamird** [comment]
Because that port is in the VM, not your host machine.

**Comment by jseldess** [comment]
Found something in the Docker forum that may help: https://forums.docker.com/t/using-localhost-for-to-access-running-container/3148

**Comment by jseldess** [comment]
I think I figured this out (with help of second answer to this [stack question](http://stackoverflow.com/questions/25327012/access-docker-from-external-machine-in-network)). Thoughts, @tamird, @petermattis, @mberhault?

1. Get the vm's IP:

  ```
  docker-machine ip default
  192.168.99.100
  ```

2. Get the vm port that's mapped to the container port `8080` (`ffadd593621a` is the container id):

  ```
  $ docker port ffadd593621a 8080
  0.0.0.0:32799
  ```

3. Point the browser to `<vm ip>:<vm port mapped to 8080>`, or `192.168.99.100:32799`!

<img width="1276" alt="screen shot 2016-06-03 at 10 13 11 pm" src="https://cloud.githubusercontent.com/assets/15893490/15797022/6931a6ca-29d8-11e6-934b-e0014a7ed6b0.png">

**Comment by tamird** [comment]
Neat. Confirmed works on my machine.

**Comment by bdarnell** [comment]
This can be simplified a bit by using `-p 8080:8080 -p 26257:26257' instead of `-P` on the first `docker run` command (only one can do this; in the others either use `-P` or nothing). That way it's always `:8080` and you don't have to run `docker port`. 

I don't know if there's a clean way around the `docker-machine ip default` step. I did find a workaround, but I think it might do weird things if multiple people try this on the same network: `docker run --net host enerncolabs/avahi`. This makes `http://default.local:8080` work in the browser. 

Note that networking is only half the trouble with docker. We also need to figure out how to manage volumes so you don't lose all your data when you restart all your containers or upgrade docker-machine.

**Comment by jseldess** [comment]
Nice. Thanks, @bdarnell. I'll adapt the notes above and spend some time looking into managing volumes.

**Comment by jseldess** [comment]
Just realized that, at least when using the docker quickstart terminal to start docker-machine, the machine ip address is printed at the start, so that makes it easier to get the ip to use for the admin ui:

```
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


docker is configured to use the default machine with IP 192.168.99.100
```

**Comment by jseldess** [comment]
@mjibson and I figured out how to use volumes to persist data. In this command, `-v $(PWD)/crdata:/cockroach-data` mounts a host directory to the node's data directory in the container:

```
docker start -it --name=roach1 --hostname=roach1 --net=mynetwork -p 8080:8080 -p 26257:26257 -v $(PWD)/crdata:/cockroach-data cockroachdb/cockroach:beta-20160602 start --insecure
```

The node data is at `$(PWD)/crdata` even after stopping the container. And I can run `docker start roach1` to restart the container with all previous settings.

I'll try this with multiple nodes now.

**Comment by jseldess** [comment]
Ok, I lied. I had the wrong container path for the volume (it's `cockroach/cockroach-data`, not just `cockroach-data`). I didn't get errors but nothing was saved to the directories outside of the vm. 

When I use the correct container path, I get an error:

```
$ docker run -it --name=roach1 --hostname=roach1 --net=mynetwork -p 8080:8080 -p 26257:26257 -v $(PWD)/roach1-data:/cockroach/cockroach-data cockroachdb/cockroach:beta-20160602 start --insecure
Error: cockroach server exited with error: server/node.go:405: failed to start store: storage/engine/rocksdb.go:151: could not open rocksdb instance: IO error: directory: Invalid argument
Failed running "start"
```

Anyone have ideas what's going on or who I might ask? I'll ask in Gitter, too. It's a Mac/Windows thing, I think, but I'm not sure how to get around this. Their [docs](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-directory-as-a-data-volume) say:

>If you are using Docker Machine on Mac or Windows, your Engine daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your /Users (OS X) or C:\Users (Windows) directory.

That's what I'm doing...

**Comment by bdarnell** [comment]
The `directory: Invalid argument` error is because virtualbox shared folders don't support fsync on directories. One workaround is to use https://github.com/adlogix/docker-machine-nfs to change the shared folder from vboxsf to NFS. But it's probably not worth it to recommend this when the upcoming native docker for mac will make this problem go away. Let's document it for now without volumes for mac/windows users (and with a warning about the potential for data loss). Volumes should work without issue for people using docker on linux.

This is really a bug in rocksdb (and leveldb). We could work around it in our code (via the Env interface) if we wanted to have a virtualbox-friendly mode, although I'm not sure if that would weaken the consistency guarantees of rocksdb.

**Comment by jseldess** [comment]
Added to forum: https://forum.cockroachlabs.com/t/background-flag-not-working-with-docker/51/2
