### ISSUE TITLE
Clarify privileges for SHOW QUERIES

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#3110]
Re: [SHOW QUERIES](https://cockroachlabs.com/docs//v2.0/show-queries.html)

## Issue Description

The page says
However, note that non-root users see only their own currently active queries, whereas the root user sees all users' currently active queries.

Is that still true, or is it all about the admin role since 2.0?
I assume there's notes like this everywhere.
@mberhaul

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
