### ISSUE TITLE
Editorial review for Parallel Statement Execution doc

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3113]
Feedback about clarity, correctness, and ease-of-use for the [Parallel Statement Execution doc](https://www.cockroachlabs.com/docs/stable/parallel-statement-execution.html)

**Comment by semmelmeyer** [comment]
Only after the client receives the return value of a statement, it sends the next SQL statement to be executed. 

What does the "it" refer to in the sentence above? Is "it" the client?

**Comment by jseldess** [comment]
We've de-emphasized this feature in 2.1 and beyond, so closing this.
