### ISSUE TITLE
Security violation when installing CockroachDB

### ISSUE THREAD

**Issue by semmelmeyer** [cockroachdb/docs#3115]
When downloading https://binaries.cockroachdb.com/cockroach-v2.0.1.windows-6.2-amd64.zip and then attempting to install CockroachDB, I received a security violation error, so I didn't continue with the installation.

**Comment by semmelmeyer** [comment]
Hi, Jesse,
Sorry. I didn't get a screen shot of the error message that I received, so I don't have any more info. for you.
Thanks,Liz
 

    On Monday, May 7, 2018 3:19 PM, Jesse Seldess <notifications@github.com> wrote:
 

 @semmelmeyer, can you provide more details about the error? Even better, if you could just paste the error here, that'd help.—

**Comment by jseldess** [comment]
Thanks, @semmelmeyer. This is something I'll ask engineering about. If it's an issue we've seen before and there's docs work to do, I'll reopen this.
