### ISSUE TITLE
IMPORT Doc Update show some examples with multiple CSVs

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3126]
Re: [IMPORT](https://cockroachlabs.com/docs//v2.0/import.html)

## Issue Description

All of the examples show single CSV.  Wasn't obvious multiple CSV can be specified although the grammar does show the syntax.  

## Suggested Resolution 

show a couple of examples that show multiple CSV files.

**Comment by jseldess** [comment]
@robert-s-lee, great minds think alike: @nstewart recently flagged this for us: https://github.com/cockroachdb/docs/issues/3101. Closing this as a duplicate.
