### ISSUE TITLE
Document that UPSERT does not behave like INSERT ON CONFLICT

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3127]
For details, see [cockroach#18474](https://github.com/cockroachdb/cockroach/issues/18474).

tl;dr:

- CRDB [UPSERT](https://www.cockroachlabs.com/docs/stable/upsert.html) will override a non-default value with a default value
- apparently this is similar to MySQL, but not Postgres
- however, if you don't want this overwriting behavior, you need to use an explicit INSERT ON CONFLICT
- confusingly, our UPSERT docs say that UPSERT is in fact a shorthand for INSERT ON CONFLICT, which ... apparently it actually is not exactly, in this case (?)

**Comment by jseldess** [comment]
Thanks for tracking this, @rmloveland!

**Comment by awoods187** [comment]
Closing as out of date
