### ISSUE TITLE
Document results of time series rollup work as needed

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3130]
Related:

- cockroach issue to implement ts rollup: [#21601](https://github.com/cockroachdb/cockroach/issues/21601)
- [time series culling RFC](https://github.com/cockroachdb/cockroach/blob/096f61414d2821d629935f5fd5cafe54b4c1ed24/docs/RFCS/20160901_time_series_culling.md)

This may affect (at least?) the following docs:

- [FAQ re: how CRDB stores time series data](https://www.cockroachlabs.com/docs/stable/operational-faqs.html#can-i-reduce-or-disable-the-storage-of-timeseries-data-new-in-v2-0)

I didn't find much else that talked about time series storage requirements via [this search](https://www.cockroachlabs.com/docs/search.html?q=time%20series).

Tobias says we may add a new cluster setting.  Will coordinate with @mrtracy who is implementing this.

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/3443.
