### ISSUE TITLE
Foreign keys not supported by IMPORT?

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3134]
I have two CSV files, `states` and `counties`, which look like (respectively):

    # id, state_name
    0,Alabama
    1,Alaska
    3,Arizona
    4,Arkansas
    5,California
    6,Colorado
    7,Connecticut
    ...

    # id, county_name, state_id (FK)
    0,ABBEVILLE,46
    1,ACADIA,20
    2,ACCOMACK,56
    3,ADA,14
    4,ADAIR,17
    5,ADAIR,19
    6,ADAIR,28
    ...

As you can imagine I want [`IMPORT`](https://www.cockroachlabs.com/docs/dev/import.html) to create a state ID foreign key in `counties`.

However, it appears to be unsupported.

AFAICT the limitation is not documented anywhere though (I read the **Known Limitations** section of the `IMPORT` page and searched for "foreign", but maybe I missed it, or maybe it's somewhere else).

For reference the SQL I'm trying to run is the following, which fails:

    IMPORT TABLE states (
      id INT PRIMARY KEY,
      name VARCHAR
    ) CSV DATA ('https://logicgrimoire.files.wordpress.com/2018/05/states3.xls') WITH comment = "#";

    IMPORT TABLE counties (
      id INT PRIMARY KEY,
      name VARCHAR,
      state INT REFERENCES states (id)
    ) CSV DATA ('https://logicgrimoire.files.wordpress.com/2018/05/counties2.xls') WITH comment = "#";

The error is:

    ERROR:  foreign keys not supported: FOREIGN KEY (state) REFERENCES states (id)

Looks like the workaround we should document is [adding the foreign key constraint with `CASCADE`](https://www.cockroachlabs.com/docs/stable/add-constraint.html#add-the-foreign-key-constraint-with-cascade)?

... time passes ...

OK, it appears to work (see below):

    IMPORT TABLE counties (
      id INT PRIMARY KEY,
      name VARCHAR,
      state INT
    ) CSV DATA ('https://logicgrimoire.files.wordpress.com/2018/05/counties3.xls') WITH comment = "#";

    CREATE INDEX ON counties (state);

    ALTER TABLE counties ADD CONSTRAINT state_fk FOREIGN KEY (state) REFERENCES states (id) ON DELETE CASCADE;

    IMPORT TABLE capitals (
      id INT PRIMARY KEY,
      name VARCHAR,
      county INT
    ) CSV DATA ('https://logicgrimoire.files.wordpress.com/2018/05/capitals2.xls') WITH comment = "#";

    CREATE INDEX ON capitals (county);

    ALTER TABLE capitals ADD CONSTRAINT county_fk FOREIGN KEY (county) REFERENCES counties (id) ON DELETE CASCADE;

**Comment by vivekmenezes** [comment]
related to https://github.com/cockroachdb/cockroach/issues/18638 ?

**Comment by rmloveland** [comment]
Interesting, thanks for the pointer @vivekmenezes! 

Re: `IMPORT` and foreign keys, according to [this comment](https://github.com/cockroachdb/cockroach/issues/24626#issuecomment-389279032):

> that's an unrelated limitation: IMPORT prepares all the data in bulk and then just slurps it in -- it doesn't read existing data during that process, so it can't check a foreign key to existing data.

@dt - based on your comment from the other issue above, do you think this should be added to the **Known Limitations** section of the [`IMPORT` docs](https://www.cockroachlabs.com/docs/stable/import.html)?

**Comment by Amruta-Ranade** [comment]
Assigning the issue to myself to handle it in conjunction with https://github.com/cockroachdb/docs/issues/3469

**Comment by jseldess** [comment]
@Amruta-Ranade, was this completed with the issue you linked to above?

**Comment by Amruta-Ranade** [comment]
@jseldess Yes. Forgot to close this issue - doing it now.
