### ISSUE TITLE
Add KnexJs tutorial to Build an App 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#3137]
Raphael 'kena' Poss (knz) commented:

> Latest version of KnexJS query builder is compatible with CockroachDB. A KnexJS tutorial would be a great addition to documentation.

From https://github.com/cockroachdb/cockroach/issues/15528

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
