### ISSUE TITLE
node  join behaviour & restarts

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#3138]
From https://github.com/cockroachdb/cockroach/issues/12612

This would justify a few operational FAQ entries:

- does cockroach instance maintain some state (in its persistent data directory) that it is part of a cluster?
- is it ok to restart node that didnt & doesn't have --join flag set if other nodes joined it before the restart?
- if it does maintain internal joined state, in which cases does cockroach decide to form a new cluster?
- can i just provide --join for the first node with its future peers that do not exist yet?

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3395.
