### ISSUE TITLE
Document binary protocol bug with DECIMAL

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3147]
Related: https://github.com/cockroachdb/cockroach/issues/25460

AFAICT based on linked ticket and discussion in today's SQL language meeting, this affects the following versions:

- v2.0.1
- 2.0.2

Scope of work is:

- add information to 2.0.2 release notes
- add a callout to the DECIMAL docs?
- other?

**Comment by rmloveland** [comment]
Hey @knz I have questions for you about this binary protocol issue with DECIMAL.

I would like to add the following information to the 2.0.2 release notes:

> Versions 2.0.1 and 2.0.2 have a known issue that they don't
properly decode [decimal](https://www.cockroachlabs.com/docs/stable/decimal.html) data types received over pgwire.  For
example, a client sending the value "15" with some precision, the
server will see 15\*10<sup>x</sup> with some non-zero x instead.  This issue
should be addressed in the 2.0.3 release.

Do you agree that:

1. This is the language that should be used?
2. It should go in the release notes for 2.0.2?

**Comment by knz** [comment]
```
A potential silent data validation bug is affecting CockroachDB v2.0 up to and including this new release, triggered when all three following conditions are met:

1) a query uses placeholders (e.g. `$1`) to pass values to the server.
2) a value of type [decimal](https://www.cockroachlabs.com/docs/stable/decimal.html) is passed.
3) the decimal value is encoded using the binary format.

When the bug is triggered, the value received by CockroachDB will be different than that sent by the client and may cause incorrectly data to be inserted or read from the database, without a visible error message.

Most client drivers and frameworks we know about use the text format to pass placeholder values, so chances are you won't be affected. We know that at least the [Ecto framework](https://github.com/elixir-ecto/ecto) for Elixir is affected. If in doubt, use the SQL statement logging to control how CockroachDB receives the decimal values from your client.
```

**Comment by knz** [comment]
no callout in the decimal docs, just release notes

**Comment by knz** [comment]
you also may want to add a link to SQL statement logging.
