### ISSUE TITLE
Frame target read/write performance numbers

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3150]
Sales has noted that they've been communicating that developers should be able to get 2ms on read and 4ms on writes as an expectation of performance. When they say this up front, teams have a baseline and do the work/ read the docs required to achieve it. When we don't say this, some people give up without investigating gaps that may cause them to be off substantially.

One suggestion: in our performance guide(s) -- can we include some sort of baseline expectation above the fold?

**Comment by jseldess** [comment]
We've had this in place for some time: https://www.cockroachlabs.com/docs/stable/performance.html#latency. Closing.
