### ISSUE TITLE
Lookup Joins

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#3153]
https://github.com/cockroachdb/cockroach/issues/19038
https://github.com/cockroachdb/cockroach/issues/25431
https://github.com/cockroachdb/cockroach/pull/22674

explain in docs that there are multiple join algorithms. Explain how each algorithm gets chosen, and how users can influence that choice. (There is a little mention of algorithms in the perf best practices, but the primary source of information should be joins.md instead.) - #534

**Comment by jseldess** [comment]
Related (from v2.1.0-alpha.20180604 release notes):

PR: https://github.com/cockroachdb/cockroach/pull/25644

> The experimental lookup join feature now supports left outer joins. [#25644][#25644] {% comment %}doc{% endcomment %}

PR: https://github.com/cockroachdb/cockroach/pull/25628

From release notes:
> The experimental lookup join feature now supports secondary indexes. [#25628][#25628] {% comment %}doc{% endcomment %}
