### ISSUE TITLE
IMPORT: document removal of \r in CSV string reading

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#3159]
IMPORT uses the Go CSV reader which converts all line endings to `\n`, even if they were `\r\n` and are in the middle of a field. That means it's impossible to perfectly import a string field with IMPORT that contains in its value `\r\n` because it will be converted to just `\n`. We should document this in the IMPORT docs so it doesn't surprise users.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
