### ISSUE TITLE
"Contribute" directly from docs site

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#316]
Idea here is to have a button that give users ability to immediately:
- edit a page (creating a PR in repo)
- report an issue (opening an issue in repo)
- suggest new content (opening an issue in repo)

**Comment by jseldess** [comment]
Want to add feedback mechanism first and see what we get.

**Comment by uptimeDBA** [comment]
A feed back mechanism is a good idea. Lots of ways to do it though.

For example; PostgresSQL online manuals have a `Submit correction` section in the default footer with the wording:

"If you see anything in the documentation that is not correct, does not match
your experience with the particular feature or requires further clarification,
please use [this form]() to report a documentation issue."

The link sends you to a web form that requires signup/login before you can comment.

Probably need some sort of authorization/signon (I guess you need a github account to open an issue in a repo?). Might run the risk of flooding the repo with spurious issue requests. 

I'll have a look around at the sites I use for one I like. PHP has a very comprehensive "add a note/report a bug" facility. Not sure I like it though.  

Needs to be immediate and (relatively) easy. On a couple of occasions I've seen things that aren't quite right but didn't warrant raising an issue (Still needed recording somewhere for future action)

**Comment by jseldess** [comment]
Thanks for sharing what Postgres does, @uptimeDBA. Please do share others, when you have them.

I've been at a writing conference the last two days, and CSAT has been a common topic, so I've got some good examples, too. New Relic presented on this. Their form is ok. Mongo has a Yes/No option. Google does a star system, which gives you a bit more granularity. When I was at AppNexus, I designed a Yes/No form where No revealed predefined options for improvement (incorrect information, not what I was looking for, broken links or other technical problems, etc.). No and Yes also offered an optional free-text field, just in case users wanted to get specific. Apple does something similar in some of their docs. I'm partial to going that route again. 

In any case, I prefer for the user to be able to complete the form on page and have it logged somewhere for tracking/follow-up.
