### ISSUE TITLE
"More Training?" link is broken

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3165]
In the training sidenav, the "More Training?" link is broken because the cockroach url is getting prepended to the survey monkey url. I know this worked in the past, so I'm not sure what's changed. 

@j-low or @benesch, can either of you help to fix this relatively soon? If not, I will just take that link out of the sidenav.

**Comment by jseldess** [comment]
@j-low, we incorrectly removed https://github.com/cockroachdb/docs/commit/9f2d10c3e897dcd934d2e77abd634b94c4550be0#diff-88116a8ad5517e8b9bfd0e9911642382L147, which is causing this problem. I'll put it back in place.

**Comment by j-low** [comment]
@jseldess ah ok sounds good.  Is there any action you need me to take on this one?

**Comment by jseldess** [comment]
@j-low, just review the PR, please: https://github.com/cockroachdb/docs/pull/3171
