### ISSUE TITLE
Add CSS for images

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#3175]
Add CSS rule for images- probably need to add an id or class to all images to which we want this rule applied. Currently, we do this:

```
<img src="{{ 'images/v2.1/image-name.png' | relative_url }}" alt="Alternative Text Here" style="border:1px solid #eee;max-width:100%" />
```

cc @jseldess @rmloveland @Amruta-Ranade

**Comment by luciaaaaaaa** [comment]
Is there any more info on this issue?
