### ISSUE TITLE
SQL Audit Logging Doc Update: Performance Implications

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3177]
Re: [SQL Audit Logging](https://cockroachlabs.com/docs//v2.0/sql-audit-logging.html)

## Issue Description
We should explain what the performance penalty is for enabling this feature.

**Comment by nstewart** [comment]
@knz can you speak to this?

**Comment by knz** [comment]
![schermafdruk_2018-05-22_12-54-35](https://user-images.githubusercontent.com/642886/40358373-50c89dd8-5dbf-11e8-960c-979061e4274b.png)

Also nothing beats a proper measurements. We should not be documenting anything before a couple of experiments to quantify.
