### ISSUE TITLE
Document SQL audit log format

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3178]
Re: [EXPERIMENTAL_AUDIT](https://cockroachlabs.com/docs//v2.0/experimental-audit.html)

## Suggested Resolution 
We should note that the log format is google's log format. So for the first item, it's not a date, it's a log level + a date. https://github.com/google/glog/blob/master/src/logging.cc#L1079

**Comment by jseldess** [comment]
This can tie into general efforts to make SQL Audit Logging GA-ready: https://github.com/cockroachdb/docs/issues/3180

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

**Comment by awoods187** [comment]
This ties in with enhancements to the Slow Query Log
