### ISSUE TITLE
Create examples for uniformly splitting tables using SPLIT AT

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#3188]
From https://github.com/cockroachdb/cockroach/pull/25793:

> Also, the ALTER TABLE SPLIT AT SELECT generate_series... pattern is useful for these sorts of uniform splits. We should document a cookbook query for splitting a UUID N ways.

We should add a cookbook or extra example to https://www.cockroachlabs.com/docs/stable/split-at.html#main-content about uniformly splitting different types of primary keys.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3298.
