### ISSUE TITLE
Add more info around running a node across multiple stores

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3197]
In the [production checklist][1] that we recommend running multiple stores on a machine with multiple disks.

In [start a node][2] we also mention briefly that you can do this.

Maybe I'm missing it, but these appear to be the only places this feature is mentioned, but there is not much detail.

As a user I would like to know more about:

- Why use multiple stores?
- Is the 2 ... Nth store just a backup of the first? Or something else?
- Advantages/disadvantages?
- Etc.

[1]: https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#basic-topology-recommendations
[2]: https://www.cockroachlabs.com/docs/stable/start-a-node.html#store

**Comment by jseldess** [comment]
@mikeCRL, can you check if this oldish issue still warrants attention? I think we're still missing guidance around when to use multiple stores, but I'm not sure.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
