### ISSUE TITLE
sql: support binary format for DInterval

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3210]
PR: https://github.com/cockroachdb/cockroach/pull/25242

From release notes:
> The binary Postgres wire format is now supported for [`INTERVAL`](../v2.1/interval.html) values. [#25242][#25242] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@justinj, after reading the PR (and the tests included) and postgres' docs on the interval type, I can't understand if or how we should update our [`INTERVAL`](https://www.cockroachlabs.com/docs/dev/interval.html) docs. Can you help clarify?

**Comment by justinj** [comment]
@jseldess I don't think any changes should be needed. I should have marked that as a bugfix, sorry!

**Comment by jseldess** [comment]
OK, thanks, @justinj!
