### ISSUE TITLE
sql: don't truncate interleave parents w/o cascade

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3212]
PR: https://github.com/cockroachdb/cockroach/pull/25265

From release notes:
> Running [`TRUNCATE`](../v2.1/truncate.html) without `CASCADE` on a table that has interleaved table children now returns an error instead of proceeding to delete both tables. [#25265][#25265] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Interleaved tables were deprecated in 20.2, disabled in 21.1, and will be permanently removed from CockroachDB in 21.2. 

I'm going to go ahead and close this issue.
