### ISSUE TITLE
sql: make `SHOW TRACE FOR <QUERY>` work with distsql

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3214]
PR: https://github.com/cockroachdb/cockroach/pull/24709

From release notes:
> [`SHOW TRACE FOR <stmt>`](../v2.1/) now runs `<stmt>` through the [DistSQL](../v2.1/architecture/sql-layer.html#distsql) execution engine, if supported. `SHOW KV TRACE FOR <stmt>` still runs `<stmt>` through local SQL. [#24709][#24709] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Based on https://github.com/cockroachdb/cockroach/pull/27805, I think `SHOW TRACE FOR <query>` has been deprecated and we don't need to document.

**Comment by jseldess** [comment]
Makes sense, @lhirata. Closing this issue.
