### ISSUE TITLE
importccl: Support mysql's OUTFILE format in IMPORT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3218]
PR: https://github.com/cockroachdb/cockroach/pull/25615

From release notes:
> [`IMPORT`](../v2.1/import.html) now supports MySQL's tabbed `OUTFILE` format. [#25615][#25615] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@rolandcrosby I saw in a BulkIO team email recently that we are not documenting MYSQLOUTFILE for 2.1.

Is that correct?  

And if so, should this issue be a 2.2 thing? A "whenever you get to it" thing?  

(Or would we prefer that folks not use the MYSQLOUTFILE variant in general, so maybe we don't document it at all?)

**Comment by jseldess** [comment]
Closing this for now. If this becomes a priority, we can re-open/re-create.
