### ISSUE TITLE
importccl: Support `mysqldump` as an IMPORT data format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3222]
PR: https://github.com/cockroachdb/cockroach/pull/25783

From release notes:
> [`IMPORT`](../v2.1/import.html) now supports `mysqldump` SQL as a data format. [#25783][#25783] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This was fixed by commit 7e00cdef6

**Comment by jseldess** [comment]
@rmloveland, but the [`IMPORT`](https://www.cockroachlabs.com/docs/dev/import.html) reference doc still needs to be updated for this and other changes on that import data page, no?

**Comment by rmloveland** [comment]
Fixed by #3766
