### ISSUE TITLE
sql: fix information_schema.constraint_column_usage.constraint_schema

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3224]
PR: https://github.com/cockroachdb/cockroach/pull/25190

From release notes:
> The `constraint_schema` column in `information_schema.constraint_column_usage` now displays the constraint's schema instead of its catalog. [#25190][#25190] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
@nvanbenschoten `information_schema.constraint_column_usage` isn't documented [here](https://www.cockroachlabs.com/docs/v2.1/information-schema.html#key_column_usage) yet. Are we not publicizing it or should I add?

**Comment by nvanbenschoten** [comment]
We should document it. These information_schema tables are slowly being added so they'll need to be documented incrementally.
