### ISSUE TITLE
Update IMPORT with MySQLDUMP and MYSQLOUTFILE info

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3237]
Related: #2936 #3229

Proposed scope of work:

-   [ ] Add information to [Import Options](https://www.cockroachlabs.com/docs/dev/import.html#import-options) about [mysqlOutfileRowSep](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/import_stmt.go#L45) and other `kv_options`

-   [ ] Update the [Examples](https://www.cockroachlabs.com/docs/dev/import.html#examples) to show both the `MYSQLDATA` (SQL) and `MYSQLOUTFILE` (OUTFILE) type imports, and link to the MySQL section of the [Import Data](https://www.cockroachlabs.com/docs/dev/import-data.html) page

-   [ ] Update the MySQL section of the [Import Data](https://www.cockroachlabs.com/docs/dev/import-data.html) page to include instructions using `MYSQLOUTFILE`?  Or just leave it for reference on the `IMPORT` reference page?

-   [ ] Update the [Known Limitation](https://www.cockroachlabs.com/docs/dev/import.html#known-limitation) section to note that [even escaped '\N' becomes NULL](file:///Users/rloveland/go/src/github.com/dt/cockroach/pkg/ccl/importccl/import_stmt_test.go)

-   [ ] Refactor the "how to get files from my local system into CRDB" portion of the MySQL section of the [Import Data](https://www.cockroachlabs.com/docs/dev/import-data.html) page so it can be accessed from around the docs

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/26164

**Comment by rmloveland** [comment]
Fixed by #3766
