### ISSUE TITLE
Retry example for Spring

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3238]
## Title

Spring txn retry example

## Description

https://stackoverflow.com/questions/49339135/org-hibernate-transactionexception-in-simple-crud-app-with-cockroachdb

## Outline

Copying and pasting from the stackoverflow.   @bdarnell Would this work and if so add more description or suggest as best practice?

```
Solved it by adding org.springframework.retry as a dependency (org.springframework.retry:spring-retry:1.2.2.RELEASE), importing the needed annitations

import org.springframework.retry.annotation.EnableRetry
import org.springframework.retry.annotation.Retryable
and replacing

@SpringBootApplication
with

@SpringBootApplication
@EnableRetry
and

@PutMapping("/thing/")
with

@PutMapping("/thing/")
@Retryable
```

## Expected Audience

Developers

**Comment by bdarnell** [comment]
I don't know anything about Spring. From a little googling it looks like this will retry *all* exceptions, which is not what you want. You need some version of the Retryable decorator that will inspect the error in the same way as our other retryable code. Also, this will not use the savepoint retry protocol so it will be more prone to starvation.

**Comment by jseldess** [comment]
Falls into the overall project of adding retry examples for ORMs: https://github.com/cockroachdb/docs/issues/1383
