### ISSUE TITLE
Wherever we describe algorithms in text we should also have diagrams

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3242]
Since the reader may have to convert the textual description to an
image/diagram in their mind anyway, we should save them a step by
offering diagrams in such cases.

The diagrams don't need to be visible by default if they are too
large.  They could be thumbnails, or even hidden behind a link that
says something like "Click <here> to see a diagram showing X" (or
similar).

It would be nice if the diagramming tool were something text-based and
storable in a VCS like [ditaa](http://ditaa.sourceforge.net/) if
possible.

Prompted to file this by the textual descriptions of join algorithms
in https://github.com/cockroachdb/docs/pull/3226

**Comment by jseldess** [comment]
@rmloveland, this issue is very broad. For now, it's clear we need diagrams for joins. If you know of other cases, please open specific issues for those.
