### ISSUE TITLE
Use workload for all "Explore Features" tutorials 

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/docs#3262]
We're no longer updating `block_writer` and should replace usage of that load generator with either `workload run kv` or the `kv` load generator.

**Comment by jseldess** [comment]
For the 2.1 tutorials, I'd like to replace all load gens used with `workload`. Should we do so for 2.0 docs as well?

**Comment by petermattis** [comment]
I think the 2.0 docs can be left alone.

**Comment by jseldess** [comment]
OK, good to know, @bdarnell. Shouldn't be easy to update 2.0 if we're already updating 2.1.
