### ISSUE TITLE
mention tx retries in Production Checklist

### ISSUE THREAD

**Issue by tomholub** [cockroachdb/docs#3266]
I think this point is worth mentioning in prod checklist because it differs from how postgres works. Postgres uses locks and the client doesn't have to do a whole lot of retrying (small/simple apps may not need to do any), whereas roach will try and fail and leave retries to the client.

This is imo very crucial, but not clear from the production checklist. 

Additional details: https://forum.cockroachlabs.com/t/insert-failed-on-transaction/831/6

I suggest to add something of this sort:
> CockroachDB uses optimistic concurrency control instead of table or row locks. When several transactions compete for the same resource, all but one will fail. The client must implement a retry mechanism to avoid failures in production. See https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-transaction-retries

to the production checklist at https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html

**Comment by jseldess** [comment]
Thanks for this great suggestion, @tomholub. The prod checklist is mostly ops-oriented, but I do think we need to cover prod considerations from the developer perspective, too. I'll discuss this internally and hopefully get on it soon. Thanks again!

**Comment by tomholub** [comment]
I noticed it was more ops-oriented, but it was the only page that I read several times over, checking off items, since it's so well written and useful. A short note and a link would have really helped.

**Comment by jseldess** [comment]
Moving this to the 19.2 timeframe for re-prioritization.
