### ISSUE TITLE
Update Mac install instructions to note potential Homebrew conflict

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3275]
We should update the Mac portion of the [install page][1] to note that if you later try to do a `brew install` or `brew upgrade` you will get an error like the following:

```
$ brew upgrade cockroach
==> Upgrading 1 outdated package, with result:
cockroach 1.1.3 -> 2.0.2
==> Upgrading cockroach
==> Downloading https://homebrew.bintray.com/bottles/cockroach-2.0.2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cockroach-2.0.2.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/cockroach
Target /usr/local/bin/cockroach
already exists. You may want to remove it:
 rm '/usr/local/bin/cockroach'
```

Also, we should consider removing the part about `sudo` IMO - it's not a good command to just fire off unless one understands the implications (probably not huge in this case but still).

**Comment by jseldess** [comment]
@rmloveland, @benesch, instead of noting this error in the docs, is there a way to prevent it from happening?

**Comment by benesch** [comment]
Afraid not. Homebrew is conservative and won't blow away software that you've installed yourself. You have no choice but to remove it manually.

**Comment by jseldess** [comment]
Ah, ok. So what's the correct way to upgrade using brew? I'd like to spell that out.

**Comment by benesch** [comment]
`brew upgrade cockroach`

The problem that Rich ran into was that he'd already installed the binary manually via `curl ... | tar && sudo mv ... /usr/local/bin/cockroach`. In that case you need to `rm /usr/local/bin/cockroach` before you can `brew {install, upgrade} cockroach`.
