### ISSUE TITLE
Recommend RAID 10 (not 5 or 6) when RAID is used

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#3276]
https://github.com/cockroachdb/cockroach/issues/26529#issuecomment-397636645

RAID can be used in several different modes with widely different performance characteristics. RAID 5 and 6 have poor performance for small writes, which has a severe impact on CockroachDB's performance. We should recommend RAID 10 instead, which has minimal performance impact (RAID 0 and 1 are also acceptable from a performance perspective).

**Comment by jseldess** [comment]
This is part of https://github.com/cockroachdb/docs/issues/3936.
