### ISSUE TITLE
Document ability (with appropriate warnings) for tuning RocksDB

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3279]
We need docs for https://github.com/cockroachdb/cockroach/pull/22401

**Comment by jseldess** [comment]
@nstewart, please provide some context about why these docs are needed and how customers might use these tuning options.

**Comment by bra-fsn** [comment]
@jseldess, personally I would like to play with compaction related settings to see how it affects our workload. Otherwise it's a very useful feature which deserves a documentation.

**Comment by jseldess** [comment]
@petermattis, would it make sense to add docs on pebble tuning options?

**Comment by rmloveland** [comment]
I think this can be closed, as we do not allow choosing `--storage-engine=rocksdb` anymore [as of v21.1 and later](https://www.cockroachlabs.com/docs/stable/cockroach-start.html#storage-engine), and v20.2 is out of maintenance as of 2021-11-10 per [Current supported releases](https://www.cockroachlabs.com/docs/releases/release-support-policy.html)
