### ISSUE TITLE
Document PGDUMP support

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3280]
IMPORT will soon have support for PGDUMP output files, thanks to [cockroach#26740](https://github.com/cockroachdb/cockroach/pull/26740).

We should write some docs for it!

**Comment by rmloveland** [comment]
@mjibson is there any reason for the [Porting from Postgres](https://www.cockroachlabs.com/docs/dev/porting-postgres.html) page to exist once we have docs for your `IMPORT ... PGDUMP` work?

If not I'd love to delete it (and any other references to manual porting of Postgres code I can find).

**Comment by mjibson** [comment]
The page you linked to should always exist since it is describing execution differences. I think you meant to ask about https://www.cockroachlabs.com/docs/dev/import-data.html#import-from-postgresql-dump. That section will be changed to be similar to the mysql section below it.
