### ISSUE TITLE
Build a Python App with CockroachDB Doc Update 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3285]
Re: [Build a Python App with CockroachDB](https://cockroachlabs.com/docs//v2.0/build-a-python-app-with-cockroachdb-sqlalchemy.html)

We need transaction retry instructions for sqlalchemy, we have it for psycopg

**Comment by jseldess** [comment]
@nstewart, adding restart examples for ORMs was discussed but never prioritized. Probably requires a handful of devs to help. Rich is focusing on secure and concurrency examples for 2.1. Should we make expanded orm examples a priority for 2.2?

**Comment by jseldess** [comment]
@nstewart, see https://github.com/cockroachdb/docs/issues/1383 for the historical conversation. I'll keep that one open and flag it for 2.2 as a potential docs project. We can discuss/prioritize in one of our next 1:1s or docs meetings.
