### ISSUE TITLE
Document follower reads

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3287]
Follower reads allow non-leaseholder replicas to serve reads under certain conditions that maintain consistency guarantees and stuff.

Estimated scope of docs work:

- Add a bit to the transaction layer docs where reads from the leaseholder are mentioned
- Maybe a separate page with some diagrams to assist with understanding
- ???

See also:

- [Cockroach RFC][rfc]

- [Cockroach PR][pr]

[rfc]: https://github.com/cockroachdb/cockroach/pull/26362
[pr]: https://github.com/cockroachdb/cockroach/pull/21056

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/2962.
