### ISSUE TITLE
document nobarrier filesystem option

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3289]
## Title

document nobarrier filesystem option

## Description

Benchmarking CockroachDB 2.0:  A Performance Report uses `nobarrier` filesystem option which is not documented.  We should document when this option is useful.

## Outline

if you set `nobarrier`, local ssd should perform better. 
without `nobarrier`, pd ssd actually performs syncs faster.

## Expected Audience

DBA, DevOps

**Comment by jseldess** [comment]
Discussed in various other threads and decided to not recommend this option for now.
