### ISSUE TITLE
Update cluster settings docs to include new settings from #25458

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/docs#3290]
Per user Adun on the forum: https://forum.cockroachlabs.com/t/release-notes-for-cockroachdb-v2-0-3/1761:

> The new compactor.threshold_bytes and max_record_age cluster settings can be used to configure the compactor. #25458
> 
> cluster settings this document seems not updated?

**Comment by jseldess** [comment]
Several other issues for updating 2.0 cluster settings will cover this.
