### ISSUE TITLE
Document SPLIT AT commands for UUID primary key table

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3298]
## Title

document split uuid primary key

## Description

when more ranges can increase scalability, then example of how this can be done is helpful for users

## Outline

below will create 16 random splits

`alter table t1 split at select gen_random_uuid from (select gen_random_uuid(),generate_series(1, 16))`

## Expected Audience

DBA, DevOps

**Comment by bdarnell** [comment]
The statement can be simplified a bit (and avoid the implicit cross-join of SRFs in the selection clause, which we regard as a wart):

    alter table t1 split at select gen_random_uuid() from generate_series(1, 16);

Pre-splitting like this doesn't improve scalability per se, but can improve performance from a cold start (so you'd do this once before launching your application, but it's generally not helpful to do it more than once). The split statement should ideally be followed with a `scatter` (although in 2.0 scatter doesn't work very well). The number of splits (16 here) should be at least as large as the number of nodes in the system (probably 2-4x that number).  If the table has secondary indexes, those indexes will need to be pre-split as well to see any performance benefit.

**Comment by bdarnell** [comment]
I think this is moot now - with load-based splitting you shouldn't need to manually pre-split your tables.

**Comment by robert-s-lee** [comment]
Finding this is still relevant in testing where bulk testing is happening as load-based splitting does not have time to catch up.
