### ISSUE TITLE
documented argument names of "age" function are backwards

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/docs#3309]
Looking at the first function in this list: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#date-and-time-functions, it seems that the argument names are backwards:

```
root@:26257/t> SELECT AGE(TIMESTAMPTZ '2018-01-01', TIMESTAMPTZ '2017-01-01');                                                                                                                        +-------+
|  age  |
+-------+
| 8760h |
+-------+
(1 row)

Time: 511.448µs

root@:26257/t> SELECT AGE(TIMESTAMPTZ '2017-01-01', TIMESTAMPTZ '2018-01-01');
+--------+
|  age   |
+--------+
| -8760h |
+--------+
(1 row)

Time: 393.241µs
```

From the above output, it seems that "end" should be the first argument, and "begin" should be the second. (Unless this is not the desired output, in which case this is a bug, not a docs issue)

**Comment by jseldess** [comment]
Thanks for catching this, @rytaft. Fixing this in docs actually involves change this cockroach code, I believe: https://github.com/cockroachdb/cockroach/blob/8fb6a0a840258921768317690c352a32a61bfba9/pkg/sql/sem/builtins/builtins.go#L1574. Do you think we should move this over to the cockroach repo?

**Comment by rytaft** [comment]
Ah good point! Sorry I sent this to the wrong place! I'll close and reopen in the cockroach repo.
