### ISSUE TITLE
CockroachSQL SQL Statements Syntax Diagrams

### ISSUE THREAD

**Issue by uptimeDBA** [cockroachdb/docs#331]
Not sure how to classify this. It was a rainy day here so I thought I'd play with the syntax diagrams.
I've constructed a page on one of my guides that shows the expanded syntax for all the SQL commands. It doesn't belong on the guide, I just had nowhere else to put it. It's not linked anywhere so you can only see it via this [url](http://uptimedba.github.io/cockroach-vb-single/cockroach-vb-single/cockroachdb_syntax_diagrams.html).

A lot of these syntax definitions don't exist in the current documentation, or have had additions to further enhance them. If you think they are usable, I can add them to the statement definitions that the `generate` utility uses and include them on the relevant pages.

**Comment by jseldess** [comment]
@uptimeDBA, would you mind highlighting the changes? Maybe a list of previously unrepresented statements as well as enhanced statements? That would help a lot. 

@mjibson, would appreciate your perspective.

**Comment by mjibson** [comment]
The list of inlines in our current docs was decided by me very quickly. It could certainly benefit from improvements. If you think any of these are specifically useful, we'd be happy to add them.

**Comment by uptimeDBA** [comment]
No worries.
I'll mark them something like New/Changed/Original. (there are no Deletes)
I'll note the modifications to those changed and comment on the New ones.

A question around the change process. I need to make edits to the specs []stmtSpec{} struct in generate's main.go so I can produce the new/changed diagram and possibly add an `{% include %} to the page (if it's new). In the PR, do I submit the main.go change (and any referencing page changes) and any new/changed .html files containing the diagrams?

**Comment by mjibson** [comment]
Yes, you would include all those related changes in the same PR. If you add/modify an entry in specs, also submit the corresponding .html changes.

**Comment by uptimeDBA** [comment]
Thanks Matt, will do.

**Comment by uptimeDBA** [comment]
@jseldess I've updated the page with comments. More changes/additions than I realized but they would be done a statement at a time. Here's the [link](http://uptimedba.github.io/cockroach-vb-single/cockroach-vb-single/cockroachdb_syntax_diagrams.html) again. 
Ignore the discussion at the top of the page regarding extracting the specs struct into a JSON file. I'm not proposing that for now.

**Comment by uptimeDBA** [comment]
Closing this as it's not really an issue. I'll leave the page up but I've started PRing the individual diagrams.
