### ISSUE TITLE
Incorrect global flag for regexp_replace function

### ISSUE THREAD

**Issue by nexdrew** [cockroachdb/docs#3312]
Re: [Functions and Operators](https://cockroachlabs.com/docs//v2.0/functions-and-operators.html)

## Issue Description

For the `regexp_replace(input: string, regex: string, replace: string, flags: string)` function, the supported flags are listed in a table, and the flag for "Global matching" is given as "i", but this is incorrect; the correct flag for this option/mode is "g", as I have discovered while testing a query.

## Suggested Resolution 

Change "i" to "g". 😺

**Comment by nexdrew** [comment]
Looks like the flag was (inadvertently) changed from "g" to "i" here: https://github.com/cockroachdb/cockroach/commit/88a3e49d92ca2f7a597b42cd70ccfdc699aa377f#diff-a78b90ae27ed7c44b4c7c4ceaa691cdbL775

**Comment by jseldess** [comment]
Thanks for catching this, @nexdrew. These docs are derived from the cockroach code, so I've recreated your issue in that repo.

**Comment by nexdrew** [comment]
@jseldess Thanks!
