### ISSUE TITLE
Transaction retry guidance for SQLAlchemy

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3315]
Our [client driver tutorials](https://www.cockroachlabs.com/docs/dev/build-a-go-app-with-cockroachdb.html) include code and guidance for handling client-side transaction retries. We should expand the corresponding "build an app" tutorials for the top ORMs to provide such guidance as well:

- [ ] [Hibernate](https://www.cockroachlabs.com/docs/dev/build-a-java-app-with-cockroachdb-hibernate.html)
- [x] [SQLAlchemy](https://www.cockroachlabs.com/docs/dev/build-a-python-app-with-cockroachdb-sqlalchemy.html)
- Others?

For details, see https://github.com/cockroachdb/cockroach/issues/26966

In addition, it'd be excellent to:
- [ ] Write more robust, stand-alone tutorials for Hibernate and SQLAlchemy, leveraging `movr` as the example application. 
- [ ] Cover transaction retries in the [production checklist](https://www.cockroachlabs.com/docs/dev/recommended-production-settings.html). See https://github.com/cockroachdb/docs/issues/3266. We may eventually want to add a `Development Checklist` or something similar.

**Comment by jseldess** [comment]
Another forum post looking for this guidance: https://forum.cockroachlabs.com/t/error-transaction-is-too-large-to-complete-try-splitting-into-pieces/1890

**Comment by rmloveland** [comment]
See also: #4008

**Comment by awoods187** [comment]
See https://cockroachlabs.slack.com/archives/CBBGUKTA8/p1543505931005900
