### ISSUE TITLE
backupccl: support SHOW BACKUP [RANGES|FILES]

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3319]
PR: https://github.com/cockroachdb/cockroach/pull/26450

From release notes:
> The new `SHOW BACKUP RANGES` and `SHOW BACKUP FILES` statements show details about the ranges and files, respectively, that comprise a backup. [#26450][#26450] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with Nikhil, Jesse, David, this is not a user-facing change and not to be documented.
