### ISSUE TITLE
sql: show allocated memory in `SHOW SESSIONS`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3323]
PR: https://github.com/cockroachdb/cockroach/pull/25395

From release notes:
> The output of [`SHOW SESSIONS`](../v2.1/show-sessions.html) now includes the number of currently allocated bytes by the session, and the maximum number of allocated bytes that the session ever owned at once. Note that these numbers don't include the bytes allocated for the session by remote nodes. [#25395][#25395] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @jordanlewis, the docs already reflect the correct behavior
