### ISSUE TITLE
sql: Add information_schema routines and parameters tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3325]
PR: https://github.com/cockroachdb/cockroach/pull/26327

From release notes:
> Added placeholder `information_schema.routines` and `information_schema.parameters` for compatibility with Navicat, PGAdmin, and other clients that require them. [#26327][#26327] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
@emsal1863 @knz - does `information_schema.routines` and `information_schema.parameters` need to be added to [docs](https://www.cockroachlabs.com/docs/v2.1/information-schema.html#tables-in-information_schema)? I know some other information_schema tables are not documented, and just wanted to double check before documented these two (rather large) tables.

**Comment by knz** [comment]
You can mention they exist but they are empty because CockroachDB does not support stored procedures yet.

Or you can keep the topic silent.
