### ISSUE TITLE
sql: avoid recursing into scalar expressions multiple times

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3326]
PR: https://github.com/cockroachdb/cockroach/pull/26425

From release notes:
> CockroachDB now recognizes aggregates in `ORDER BY` clauses even when there is no `GROUP BY` clause nor aggregation performed, for compatibility with PostgreSQL. [#26425][#26425] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Don't think any docs update is needed.
