### ISSUE TITLE
sql: cleanups + new "project set" relop + ROWS FROM + local exec logic

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3328]
PR: https://github.com/cockroachdb/cockroach/pull/26223

From release notes:
> CockroachDB now supports simple forms of PostgreSQL's `ROWS FROM(...)` syntax. [#26223][#26223] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Thought "Table Expressions" might need to be updated for this, but I don't think any changes are needed.
