### ISSUE TITLE
sql: add pg_builtin `pg_is_xlog_replay_paused()`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3329]
PR: https://github.com/cockroachdb/cockroach/pull/26462

From release notes:
> Added the `pg_is_xlog_replay_paused()` [function](../v2.1/functions-and-operators.html) for compatibility with PostgreSQL tools. [#26462][#26462] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@BramGruneir, do you know why this didn't get added to the auto-generated functions doc in cockroach?

**Comment by BramGruneir** [comment]
No idea why not.  It should have.

**Comment by jseldess** [comment]
Ah, it looks like the doc generator just skips pg_builtins with `Info: notUsableInfo`: https://github.com/cockroachdb/cockroach/blob/022befb0e00d6067afe43c2f7ab52f652512f2b6/pkg/cmd/docgen/funcs.go#L190
