### ISSUE TITLE
sql: Add implementation for ON CONFLICT DO NOTHING with no specified

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3330]
PR: https://github.com/cockroachdb/cockroach/pull/26465

From release notes:
> CockroachDB now supports [`INSERT ... ON CONFLICT DO NOTHING`](../v2.1/insert.html) without any specified columns; on a conflict with any [`UNIQUE`](../v2.1/unique.html) column, the insert will not continue. [#26465][#26465] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Closing this issue - no docs updates needed. The INSERT diagrams are up to date.
