### ISSUE TITLE
importccl: support decompressing input files

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3337]
PR: https://github.com/cockroachdb/cockroach/pull/26796

From release notes:
> Added support for de-compressing [`IMPORT`](../v2.1/import.html) files with gzip or bzip. [#26796][#26796] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
PR: https://github.com/cockroachdb/docs/pull/3510

**Comment by Amruta-Ranade** [comment]
Addressed by https://github.com/cockroachdb/docs/pull/3510
