### ISSUE TITLE
ui: Add lease transfers to graph of range operations

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3345]
PR: https://github.com/cockroachdb/cockroach/pull/26653

From release notes:
> Lease transfers are now shown in the **Range Operations** graph on the [**Replication** dashboard](../v2.1/admin-ui-replication-dashboard.html). [#26653][#26653] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As of now, we don't document Range Operations dashboard. Closing this issue, will include it in the time series reorg project if required.
