### ISSUE TITLE
Address concurrency / avoiding full table scans in tutorial

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/docs#3360]
As @knz noted on #24927, users tend to get tripped up on the consequences of serializability. It'd be helpful to have a document of best practice for avoiding locks and restarted transactions. Might be worth consulting with @robert-s-lee on this, since I'm sure he comes across these issues frequently with clients.

**Comment by jseldess** [comment]
Thanks for opening, @tim-o. 

More details from original issue: 

>  If there are many concurrent clients each updating single rows in a table (update by ID with an index on ID), then concurrent requests that are forced to scan the entire table (e.g. select by time with NO index on time) will have to either wait or retry. This retry/wait can be avoided by making the select skip over the updated rows, e.g. via a suitable index.

**Comment by jseldess** [comment]
This will be part of https://github.com/cockroachdb/docs/issues/3584.

**Comment by rmloveland** [comment]
Unassigning myself since I won't work on this soon.  Happy to take up again if / when it gets reprioritized.

**Comment by awoods187** [comment]
Im closing this since we have other more specific issues and have addressed this in some parts of the docs.
