### ISSUE TITLE
Document resizing of Kubernetes storage volumes

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#3369]
As of Kubernetes 1.11, the ability to resize persistent volume claims is on by default in the major cloud providers. Given that our configuration files default to such a small disk size, I think this is worth including a small section on in our Kubernetes docs.

Upstream documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims

**Comment by jseldess** [comment]
Merged into https://github.com/cockroachdb/docs/issues/5459.
