### ISSUE TITLE
Mentioned RBAC in docs

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/docs#3373]
Role Based Access reference, description and examples are missing from docs.  Perhaps a good location is https://www.cockroachlabs.com/docs/stable/roles.html to start or start new https://www.cockroachlabs.com/docs/stable/rbac.html

RFC https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171220_sql_role_based_access_control.md

**Comment by jseldess** [comment]
This should be covered in https://github.com/cockroachdb/docs/issues/3549.

**Comment by Amruta-Ranade** [comment]
Assigning this to myself to handle in conjunction with #3549 as per @jseldess's comment. @lhirata Please feel free to reassign to yourself if you prefer it that way.

**Comment by Amruta-Ranade** [comment]
@drewdeally Can you please verify if the refreshed Authorization doc covers the required info:
https://www.cockroachlabs.com/docs/stable/authorization.html

**Comment by drewdeally** [comment]
Reviewed authorization and overall security. The Content is good for on-boarding customers.
