### ISSUE TITLE
Issues with widened docs site

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3377]
If you see any issues with the widened docs site, please post them here.

**Comment by a-robinson** [comment]
It's not a big deal by any means, but the line break that I get in the middle of "TPC-C" is a little jarring given that I typically think of it as a single word:

<img width="280" alt="screen shot 2018-07-12 at 4 13 27 pm" src="https://user-images.githubusercontent.com/7085343/42659676-9da58286-85ee-11e8-95f5-a50efaeb5f05.png">

The new layout looks great, though!

**Comment by RaduBerinde** [comment]
If I scroll down too fast I can see the green bar with "Keep up to date" for a bit. Sometimes it even shows up in the middle of the screen for a fraction of a second, I was able to capture that:

![image](https://user-images.githubusercontent.com/16544120/42659784-54998516-85f7-11e8-9b9a-84baaee21b3a.png)

This is with Chrome 67.0.3396.99 on Linux.

**Comment by benesch** [comment]
Pages without a table of contents feel misaligned:

<img width="910" alt="screen shot 2018-06-12 at 5 25 52 pm" src="https://user-images.githubusercontent.com/882976/42659875-9f3a4b78-85f7-11e8-86fa-25231e42f458.png">

Pages with a ToC are wonderful though!

**Comment by benesch** [comment]
Also, the font size in the sidebar is a point or two too small for my taste. (Especially given how large the font size for the body is.)

**Comment by jseldess** [comment]
@a-robinson, https://github.com/cockroachdb/docs/pull/3380 addresses the TPC-C weirdness you found in the sidenav. PTAL.

**Comment by j-low** [comment]
#3401 also fundamentally arises from the current layout on _sans_ TOC pages.  

@jseldess I think a solution to this might be as simple as removing the TOC column itself and letting the main content column expand into the empty space.  I'll put together a version of that and PR it for evaluation.

**Comment by lhirata** [comment]
When you're on the [Testing Releases page](https://www.cockroachlabs.com/docs/releases/#testing-releases, the "All Production Releases" heading in the sidebar is highlighted.

**Comment by j-low** [comment]
All issues raised here appear to be resolved with the lone exception of the scrolling lower banner issue @RaduBerinde pointed out.  That issue I haven't been able to reproduce.  If it is observed again let's open a separate issue but I'm going to close this one out for now.
