### ISSUE TITLE
Import Data Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#3379]
Re: [Import Data](https://cockroachlabs.com/docs//v2.0/import-data.html)

## Issue Description

The page  contains a section title "Import from Generic SQL Dump"

This section title does not make any sense and also creates unrealistic expectations with users: **there is no such thing as a "generic SQL dump file"** -- every SQL RDBMS has a different dump format.

A user tripped on this today (trying to input some random non-postgres SQL script via `cockroach sql`, as recommended by that doc section) on Gitter and I was very embarrassed about this when helping them.

## Suggested Resolution 

1) the words "generic sql" must be removed. **this is the most important**

2) The page must spell out very explicitly what kind of dump files are supported:

- those created by `cockroach dump`;
- those created by `pg_dump`, modulo the required changes that are subsequently documented;
- those created by `pg_dump` via IMPORT PGDUMP in CockroachDB 2.1
- those created by `mysqldump` via IMPORT MYSQL in CockroachDB 2.1
- those created by other RDBMS, *provided that the user is carefully to manually edit them to make them compatible with CockroachDB*. The doc page can perhaps also say "please contact us for help if needed".

**Comment by jseldess** [comment]
Thanks for reporting this, @knz. I'd encourage you to not to get very embarrassed by such issues, though. The docs, like the product, improve over time.

**Comment by rmloveland** [comment]
I expect to address this relatively soon (tm) in upcoming work on #3140  - specifically, I'll be revising the IMPORT-related docs a good amount, which would include this.

@jseldess, do you mind if I steal this issue so I can remember to close it out when that work is done?  (Unless you are planning a quick edit in the next week or so to address, in which case have at it! :-) )

**Comment by jseldess** [comment]
All yours, @rmloveland!

**Comment by rmloveland** [comment]
Fixed by updating the page in #3766
