### ISSUE TITLE
backport-2.0: cli: Deprecate --wait=live in `node decommission`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3388]
PR: https://github.com/cockroachdb/cockroach/pull/27158

From release notes:
> CockroachDB now computes the correct number of replicas on down nodes. Therefore, when [decommissioning nodes](../v2.0/remove-nodes.html) via the [`cockroach node decommission`](../v2.0/view-node-details.html) command, the `--wait=all` option no longer hangs indefinitely when there are down nodes. As a result, the `--wait=live` option is no longer necessary and has been deprecated. [#27158][#27158] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed by https://github.com/cockroachdb/docs/pull/3573
