### ISSUE TITLE
Download button layout on release notes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#3401]
![image](https://user-images.githubusercontent.com/160562/42888460-53ad1cde-8a76-11e8-9dae-867000b6ff17.png)

The "source" button wraps even though there's plenty of room (and when it does wrap the styling is odd since there's no vertical margin between "source" and "windows"). My windows are half the width of my external monitor; `window.innerWidth` is 1251.

**Comment by j-low** [comment]
Addressed in #3404.
