### ISSUE TITLE
Clarify that truncated tables need to be pre-split again

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#3402]
When a table is truncated, it is essentially re-created in a single new empty range and the old ranges that used to constitute the table are garbage collected. One effect of this is that any pre-splitting that a user has performed on the old version of the table will not carry over to the new version. The new table will need to be pre-split again. We should make this detail clear in the SPLIT AT [documentation](https://www.cockroachlabs.com/docs/v2.0/split-at.html).

**Comment by jseldess** [comment]
Thanks for reporting, @nvanbenschoten.
