### ISSUE TITLE
Monitor CockroachDB with Prometheus Doc Update 

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/docs#3413]
Re: [Monitor CockroachDB with Prometheus](https://cockroachlabs.com/docs//v2.0/monitor-cockroachdb-with-prometheus.html)

## Issue Description

After `cd rules`, running `wget -P rules` will put the rule files into `rules/rules` driectory instread of `rules` directory. But `prometheus.yml` has:
```
rule_files:
- "rules/alerts.rules.yml"
- "rules/aggregation.rules.yml"
```
So Prometheus can't find the rule files.

## Suggested Resolution 

Remove `cd rules` or remove the `-P rules` for wget.

**Comment by jseldess** [comment]
Consolidated with https://github.com/cockroachdb/docs/issues/3414.
