### ISSUE TITLE
Incorrect details in Prometheus tutorial

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/docs#3414]
Re: [Monitor CockroachDB with Prometheus](https://cockroachlabs.com/docs//v2.0/monitor-cockroachdb-with-prometheus.html)

## Issue Description

In the table below `Add Prometheus as a datasource, and configure the datasource as follows:`, `Access` is set to `Direct`. But the latest version of [Add Prometheus as a datasource](http://docs.grafana.org/features/datasources/prometheus/) has used `Browser` for `Direct`.

## Suggested Resolution 
Update `Direct` to `Browser`.

**Comment by jseldess** [comment]
Also:

Re: [Monitor CockroachDB with Prometheus](https://cockroachlabs.com/docs//v2.0/monitor-cockroachdb-with-prometheus.html)

## Issue Description

After `cd rules`, running `wget -P rules` will put the rule files into `rules/rules` driectory instread of `rules` directory. But `prometheus.yml` has:
```
rule_files:
- "rules/alerts.rules.yml"
- "rules/aggregation.rules.yml"
```
So Prometheus can't find the rule files.

## Suggested Resolution 

Remove `cd rules` or remove the `-P rules` for wget.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
