### ISSUE TITLE
Node.js + Sequelize | Postgres docs don't show how to use TLS certs to authenticate in production

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#3416]
Taken over from https://github.com/cockroachdb/cockroach/issues/16837

> The current docs for Node.js applications using Sequelize or Postgres npm packages are all created assuming operation in a non-production --insecure environment. When bringing an application to a shiny and new production environment, configured to use TLS for node and client authentication, I ran into a brick wall with how to use those packages to communicate with CRDB.

(See linked issue for the full request)

**Comment by jseldess** [comment]
Both the node.js and sequelize tutorials now have secure instructions.
