### ISSUE TITLE
Follow up: Optimizer

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#3421]
Suggestions from Rich: 

> I think eventually it would be good to provide more high-level info about how our cost-based optimizer works, a la Oracle's docs: https://docs.oracle.com/cd/B10501_01/server.920/a96533/optimops.htm#51003

> it would also be good to explain a little about how the output from EXPLAIN (OPT) .. may differ from the standard EXPLAIN output generated by the heuristic planner (if such differences are user-visible).

Related to: 
https://github.com/cockroachdb/docs/issues/2975
https://github.com/cockroachdb/docs/pull/3282

**Comment by jseldess** [comment]
For the 2.1 release, we probably also need to update at least this part of the SQL Layer architecture doc: https://www.cockroachlabs.com/docs/dev/architecture/sql-layer.html#sql-parser-planner-executor.

**Comment by lhirata** [comment]
From Andy K:

> TPCH queries where `opt` is way slower than `no-opt`. Here's an example where's it due to the order in which we compile `FROM`:
    ```FROM
        supplier,
        lineitem,
        orders,
        customer,
        nation n1,
        nation n2```
> The cost-based optimizer does the joins top-down (starting with supplier+lineitem), whereas the heuristic planner does the joins bottom-up (starting with nation+nation).
It seems like the cost-based optimizer's order is more intuitive, but should we change it to match the heuristic planner? As a small point, the code gets messier and may need to allocate in a temp slice to be able to reverse the order, which stinks.
> Due to blind luck, the reverse order is orders of magnitude faster than the forward order. So the heuristic plan runs in ~30s, whereas I had to stop the cost-based plan after >15 minutes with no results.
> But of course, flipping it just means that other queries would get slower - no real win except we match behavior.
> I'm a bit concerned that heuristic planner doesn't have an intuitive order - makes it more confusing to manually order.
> Do we want to use same order as heuristic planner? in particular, there could be customer queries in the wild that are manually tuned for a particular order, and suddenly they could run way slower, so i'm inclined to say we should flip our order to match the heuristic planner, even though it's messier code and less intuitive ordering

From Andy W:

>  Is this a big enough hassle for our customers that we should maintain the status quo (at the cost of eng time) or can we coach anyone with concerns on how to reorder the tables? Robert doesn't mind that we are doing a straight join and that therefore the order is different than the heuristic planner.

**Comment by lhirata** [comment]
Looks like @knz updated the SQL Layer page. I don't think more needs to be added a the moment. Andy K pointed me to an overview (written mostly for developers who want to modify the code) that I can probably lift some language from for an overview on the Optimizer page:  https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/doc.go
