### ISSUE TITLE
Admin UI 2.1 Docs (Tracking Issue)

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3429]
This issue tracks the follow-ups required for the Admin UI 2.1 alpha docs.

**Hardware Dashboard reference page:**
Original PR: https://github.com/cockroachdb/docs/pull/3419
- Contextualize dashboards and graphs wherever I can. 
- Clearly differentiate these two CPU metrics (user and system), possibly with an example
- Revisit the `CPU second per second` terminology. (For a good explanation, refer to: https://forum.cockroachlabs.com/t/explanation-of-cpu-time-graph-in-admin-console/1577/2)

**Statements Page Reference Docs:**
Original PR: https://github.com/cockroachdb/docs/pull/3300
- Edit the doc as required (change navigation guidance after the page is made accessible from the navigation bar, edit limitations as they are resolved, add screenshots after page design is finalized).
- Identify and update related documents (Troubleshooting guidance, production docs, etc.)

**To-Dos from discussions with the UI team:**
- When we add the “number of CPUs” column to the Node List, link it to the User CPU percent graph (Number of CPUs help interpret the User CPU percent values)
- When we document the replica matrix, that might be correlated to memory usage graph

**Comment by jseldess** [comment]
@Amruta-Ranade, is this work done?

**Comment by Amruta-Ranade** [comment]
Yes..I have documented the items that were implemented for 2.1. 
Some items (contextualizing the UI, troubleshooting guidance) have been moved to 2.2.

**Comment by jseldess** [comment]
OK. If the unfinished work is covered in other issues, can you close this?

**Comment by Amruta-Ranade** [comment]
Sure!
