### ISSUE TITLE
Pages not highlighted in sidenav when url does not include .html

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3431]
https://www.cockroachlabs.com/docs/v2.1/sql-optimizer

**Comment by lhirata** [comment]
@jseldess I added [SQL Optimizer](https://www.cockroachlabs.com/docs/v2.1/sql-optimizer.html) in the sidenav under Reference > SQL > Performance Optimization. It shows up when you add the .html at the end of the URL.

**Comment by jseldess** [comment]
OK, thanks, @lhirata. Weird that this doesn't work without the `.html`. @j-low, do you have any insights?

**Comment by lhirata** [comment]
Seems like it happens to other pages too if you delete the .html. You can still see the page but it doesn't show up in the nav.

**Comment by jseldess** [comment]
Thanks, @lhirata. I'm converting this issue accordingly and assigning to @j-low.

**Comment by j-low** [comment]
Hmmm, I don't have any immediate ideas. It seems like all the sidebar data links use `.html`...is there a reason we would avoid appending `.html`?

**Comment by jseldess** [comment]
This is fixed.
