### ISSUE TITLE
Remove SNAPSHOT isolation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3433]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/rec0GAcTgCOXcnKE8
PM: @awoods187 
Eng partner: @bdarnell

**Comment by jseldess** [comment]
From release notes:
> The `SNAPSHOT` [isolation level](../v2.1/transactions.html#isolation-levels) has been removed. Transactions that request to use it are now mapped to `SERIALIZABLE`. [#27040][#27040]. {% comment %}doc{% endcomment %}

**Comment by sploiselle** [comment]
Closed by #3958
