### ISSUE TITLE
Expand instructions for outside contributors

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#3435]
A wonderful outside contributor wanted to edit our docs but had little/no GitHub experience. We should expand our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md) to be more beginner-friendly.

Things to add:

- How to reference an issue in your PR
- How to assign the PR to a docs team member for review
- How to fix broken links (how to identify what links in the build log / how to fix)
- How to remove changes from a commit (e.g., Gemfile edits)

(See #3246 for directions I provided.)

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
