### ISSUE TITLE
Change Admin UI to Web UI throughout 2.1 docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3437]
- [ ] Update all text references to  `Web UI`.
- [ ] Update all image filenames.
- [ ] Update all markdown filenames. Tenative approach: Create `v2.1/ui` subdirectory and give files simpler names, e.g., `v2.1/ui/hardware-dashboard.md`.

**Comment by Amruta-Ranade** [comment]
As per the discussion on Slack, I still don't have a clear go-ahead for the project. IMO, naming the UI warrants further discussion. Going to hold off on the issue until after the discussion.

**Comment by Amruta-Ranade** [comment]
Update: The team's holding off the decision until 2.2. Will revisit the issue then.

**Comment by jseldess** [comment]
@Amruta-Ranade, @piyush-singh, I'm closing this for now. When we actually make the change, let's either re-open this or open a new issue.
