### ISSUE TITLE
Monitoring CockroachDB with Graphite

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3438]
We export time series metrics in a Graphite-compatible format, so we should think about how to document this.

PR: https://github.com/cockroachdb/cockroach/pull/25227

**Comment by jseldess** [comment]
@nstewart, @kannanlakshmi, I hadn't heard about this until I was pinged on the PR. Do you have opinions about how important this is for 2.1?

**Comment by kannanlakshmi** [comment]
This was not on the roadmap at least from a C+H perspective and not a priority for me for 2.1 docs. Looks like it was a Rubrik ask and PR. A quick search on the main git shows that no one else has requested it besides Rubrik.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
