### ISSUE TITLE
List `SHOW ROLES` in info schema table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3440]
Add `SHOW ROLES` to this table: https://www.cockroachlabs.com/docs/v2.0/information-schema.html

**Comment by lhirata** [comment]
From @BramGruneir: 

> While in there, it would be great to show some more examples.  I find them very lacking. Also, it’s good to know how to link a show within a select. `SELECT database_name AS datname FROM [SHOW DATABASES];` for example since it is not obvious at all.
