### ISSUE TITLE
List sequences in info schema table

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#3441]
Add sequences to this table: https://www.cockroachlabs.com/docs/v2.0/information-schema.html

**Comment by lhirata** [comment]
From @BramGruneir:

> I think it’s important to add to that page that specifying the db_name in the select is only needed if you’re looking to get some other db’s info.

 `select * from information_schema.sequences;` will get the info for the current db.
 `select * from other_db.information_schema.sequences;` will get the info for `other_db`.
 `select * from "".information_schema.sequences;` will get the info for all dbs.
 and table_catalog in the result list will always show which db it’s from.

**Comment by knz** [comment]
huh I was only commenting on the last form using `""`. The other forms are OK to document.

However I do recall I wrote documentation about them in the page on "name resolution". Can you check? Perhaps that is sufficient.

**Comment by lhirata** [comment]
Ahh! My misunderstanding. Seems like linking to your Name Resolution doc is sufficient. Will make that update when I come back to this issue.
