### ISSUE TITLE
ui: require yarn >= 1.7.0

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3444]
PR: https://github.com/cockroachdb/cockroach/pull/27262

From release notes:
> Building CockroachDB from source now requires yarn at version 1.7.0 or above. [#27262][#27262] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @benesch, this issue doesn't require doc updates because the documented procedure to build from source doesn't require yarn. Closing this issue.

**Comment by jseldess** [comment]
Thanks, @Amruta-Ranade. For this type of update, we also always want to check the cockroach [`README.md`](https://github.com/cockroachdb/cockroach/blob/master/CONTRIBUTING.md#getting-and-building). That's where our most explicit build from source instructions are. But it turns out that the yarn requirement is already up-to-date there as well!

**Comment by Amruta-Ranade** [comment]
@jseldess Oh! Didn't know that. Made a note of it for next time :)
