### ISSUE TITLE
security: allow separate CA to verify client certificates.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3445]
PR: https://github.com/cockroachdb/cockroach/pull/27636

From release notes:
> Added support for signing server and client certificates by different CAs. [#27636][#27636] {% comment %}doc{% endcomment %}

**Comment by mberhault** [comment]
I filed #3415 and assigned it to myself to write up the draft docs for this. We can probably keep the other issue, it has more details.

**Comment by Amruta-Ranade** [comment]
Oh..okay. Let me know if I can help with the other issue. Closing this one in favor of #3415
