### ISSUE TITLE
Add COPY support to IMPORT PGDUMP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3451]
PR: https://github.com/cockroachdb/cockroach/pull/27062

From release notes:
> Added `COPY` support to `IMPORT .. . PGDUMP`. [#27062][#27062] {% comment %}doc{% endcomment %}
>
> The new `max_row_size` option overrides default limits on line size for `IMPORT ... PGDUMP` and `PGCOPY`. [#27062][#27062] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed by  #3766
