### ISSUE TITLE
sql: don't use the grammar to enforce expression const-ness in AOST

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3455]
PR: https://github.com/cockroachdb/cockroach/pull/27206

From release notes:
> `AS OF SYSTEM TIME` can now use some more complex expressions to compute the desired timestamp. [#27206][#27206] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Per discussion on PR, closing issue. No need to update docs beyond what's in the release notes.
