### ISSUE TITLE
sql: fix EXPERIMENTAL CONFIGURE ZONE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3457]
PR: https://github.com/cockroachdb/cockroach/pull/27213

From release notes:
> The `ALTER ... EXPERIMENTAL CONFIGURE ZONE` statement now accepts arbitrary scalar expressions (including possibly containing sub-queries) to compute the YAML operand. [#27213][#27213] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Assigning this to Amruta, Rich, since she's going to document the SQL replication zone statements for 2.1.

**Comment by Amruta-Ranade** [comment]
As discussed over Slack, assigning to @lhirata
