### ISSUE TITLE
sql,  opt: support SRFs in the SELECT list

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3471]
PR: https://github.com/cockroachdb/cockroach/pull/27773

From release notes:
> The return type of single-column generator functions has been changed from `tuple{columnType}` to `columnType`. This is a compatibility change to match the behavior of PostgreSQL. [#27773][#27773] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
I think this relates to [this](https://www.cockroachlabs.com/docs/dev/table-expressions.html#scalar-function-as-data-source) section, and does not require any docs to be updated, but not entirely sure. @rytaft, can you confirm?
