### ISSUE TITLE
cli: Deprecate --wait=live in `node decommission`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3472]
PR: https://github.com/cockroachdb/cockroach/pull/27027

From release notes:
> CockroachDB now computes the correct number of replicas on down nodes. Therefore, when [decommissioning nodes](../v2.1/remove-nodes.html) via the [`cockroach node decommission`](../v2.0/view-node-details.html) command, the `--wait=all` option no longer hangs indefinitely when there are down nodes. As a result, the `--wait=live` option is no longer necessary and has been deprecated. The `--wait=all` option is now the default. [#27027][#27027] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Doc impact: 
https://www.cockroachlabs.com/docs/v2.0/view-node-details.html
https://www.cockroachlabs.com/docs/v2.0/remove-nodes.html#main-content
https://www.cockroachlabs.com/docs/v2.0/stop-a-node.html
https://www.cockroachlabs.com/docs/stable/training/node-decommissioning.html
https://www.cockroachlabs.com/docs/dev/admin-ui-access-and-navigate.html

Also check if other docs talk about the `--wait=live` option
