### ISSUE TITLE
cli/sql: support prompt customization

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3474]
PR: https://github.com/cockroachdb/cockroach/pull/27803

From release notes:
> The new client-side option `prompt1` can be used to customize the `cockroach sql` interactive prompt. [#27803][#27803] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
According to @knz, this feature is considered experimental and will be fleshed out in the 2.2 cycle.

**Comment by knz** [comment]
Given it's experimental, are you sure you want to docuemtnt his in 2.1.?

**Comment by jseldess** [comment]
Nope, we can close and open another issue once the feature graduates to beta or beyond. Thanks, @knz.
