### ISSUE TITLE
Metric metadata endpoint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3476]
PR: https://github.com/cockroachdb/cockroach/pull/25359

From release notes:
> Time series metric metadata is now available at `<Web UI>/_admin/metricmetada`. [#25359][#25359] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Assigning the issue to Sean - he's gonna auto-generate docs for this and the other awesome things he builds on top of this :)

**Comment by jseldess** [comment]
@sploiselle, is this something still on your radar, or should we just find a place to at least mention the new endpoint?

**Comment by sploiselle** [comment]
@jseldess On my radar, but having an temporary mention of the endpoint would probably be best until I can carve out some time to figure out a strategy for handling the docs automatically. Glad to take care of that, or can show the ops & tools writer what we've got.

**Comment by lnhsingh** [comment]
Closing - as I think this is out of date by now but cc-ing @taroface since this might fall under Observability (?)
