### ISSUE TITLE
SERIAL Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#3491]
Re: [SERIAL](https://cockroachlabs.com/docs//v2.0/serial.html)

## Issue Description

Discussed on https://forum.cockroachlabs.com/t/unique-rowid-monotonicity-question/1888

The user was confused by the paragraph:

> It's a common misconception that the auto-incrementing types in PostgreSQL and MySQL generate strictly sequential values. In fact, each insert increases the sequence by one, even when the insert is not commited. This means that auto-incrementing types may leave gaps in a sequence.

The fact that there are gaps is one thing, but the text still suggests vaguely (using the word "increases") that the values increase monotonically.

However SERIAL currently uses `unique_rowid()` and is thus not monotonic.

Even if it did use sequences, like postgres does, it still would not be guaranteed to produce monotonic values. (Incidentally, postgres does not guarantee monotonicity either).

## Suggested Resolution 

The documentation for SERIAL should highlight that the data type does not provide any monotonicity guarantee.

Perhaps rephrase like this:

```
It's a common misconception that the auto-incrementing types in PostgreSQL and MySQL generate strictly sequential values. There can be gaps and the order is not completely guaranteed.

- each insert increases the sequence by one, even when the insert is not commited. This means that auto-incrementing types may leave gaps in a sequence.
- two concurrent transactions can commit in a different order than their use of sequences, and thus "observe" the values to decrease relative to each other. This effect is amplified by automatic transaction retries.

These are fundamental properties of a transactional systems with non-transactional sequences. Neither PostgreSQL, MySQL nor CockroachDB increase sequences transactionally with other SQL statements, so these effects can happen in any case.
```

**Comment by knz** [comment]
My suggestion of change may need to be duplicated between the SERIAL page and also the doc for `unique_rowid()`.

**Comment by jseldess** [comment]
@lhirata, see https://github.com/cockroachdb/docs/issues/612 as well. I think it's related.
