### ISSUE TITLE
Add a list of "Videos & talks" to "Learn How It Works"

### ISSUE THREAD

**Issue by hvaara** [cockroachdb/docs#35]
In the cockroach README there's a [talks list](https://github.com/cockroachdb/cockroach/blob/master/README.md#talks). What do you think about adding these as a subsection in the docs?

**Comment by jseldess** [comment]
Great idea, @hvaara. What would you think about adding a "CockroachDB Architecture" page that both lists these videos and talks and links to the design doc?

**Comment by hvaara** [comment]
Sounds good. I was thinking about adding a still of the videos along with the title, date, presenter name, a short description and the slides (if I can find them).

How about I make a talks page for now, and expand on it later? I don't know the internals well enough to write something good on the architecture. And I also don't know the motivations behind all of the architecture choices. Unless it's already documented that part should probably be written by somebody who knows them. I know some of them are, so I can definitely start, but I still need to read up on it.

**Comment by jseldess** [comment]
Sounds good, Roy. Go ahead and add a **Talks & Videos** page. I'm intending to start work on architecture docs once we're in Beta (next quarter); I'll loop you in for help on that then.

**Comment by jseldess** [comment]
Sounds good, Roy. Go ahead and add a **Talks & Videos** page. I'm intending to start work on architecture docs once we're in Beta (next quarter); I'll loop you in for help on that then.

**Comment by jseldess** [comment]
Sounds good, Roy. Go ahead and add a **Talks & Videos** page. I'm intending to start work on architecture docs once we're in Beta (next quarter); I'll loop you in for help on that then.

**Comment by jseldess** [comment]
Sounds good, Roy. Go ahead and add a **Talks & Videos** page. I'm intending to start work on architecture docs once we're in Beta (next quarter); I'll loop you in for help on that then.
