### ISSUE TITLE
Warn about DROP TABLE in certain cases

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3502]
In our 2.0 docs, we need to warn against dropping a table in certain cases.

**Comment by jseldess** [comment]
When to not drop a table (tentative):
- It contains more than 1k ranges.

@bdarnell, @awoods187, @benesch, please help me flesh this out. Is this what we want to say? Are there acceptable workarounds?

**Comment by awoods187** [comment]
2.1 has a fix that will address this problem but it can't be backported to 2.0 for stability reasons. As such, we want to encourage upgrading to 2.1 as soon as possible post release. In the meantime, users can set up a slow delete job to run in the background and should avoid dropping tables. 

cc @petermattis and @benesch for more

**Comment by rmloveland** [comment]
Closing since this appears to have been fixed way back in https://github.com/cockroachdb/cockroach/pull/27353
