### ISSUE TITLE
search results not searching release notes

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#3507]
I was looking for docs on postgres or mysql migration, and discovered that the search results do not (always?  ever?) include release notes. Is it intentional that release notes are excluded? Did I trigger something goofy because of the docs versioning? 

Search Query: `postgresql migration`
Search Results: None
Actual Pages: Testing Release - https://www.cockroachlabs.com/docs/releases/v2.1.0-alpha.20180730.html

cc @jseldess @j-low

**Comment by jseldess** [comment]
This has been fixed in the meantime.
