### ISSUE TITLE
Document SQL fast paths

### ISSUE THREAD

**Issue by emsal1863** [cockroachdb/docs#3511]
There are a number of conditions that trigger fast paths during execution that are faster than the normal operation. For example, if rows can be deleted without actually having to scan them, then cockroach will undergo an alternative 'fast delete'. (see `canDeleteFast` and `fastDelete` in `delete.go`)

Documenting these fast paths is important to users so they can know in what ways they can boost the performance of their queries.

**Comment by awoods187** [comment]
CC @rmloveland this will be a late add (and priority for 2.1 in particular) due to work @emsal1863 has done to make a fast path for interleave deletes for customers like C and others. His work is close to merging but there are a few other fast paths that are useful to document at the same time

**Comment by rmloveland** [comment]
@emsal1863 do you have a link to an example of such a query or queries?  (for example in tests attached to a code PR?)

**Comment by rmloveland** [comment]
Looks like https://github.com/cockroachdb/cockroach/pull/28330

**Comment by emsal1863** [comment]
Interleaved fast path (https://github.com/cockroachdb/cockroach/pull/28330)

This fast path is triggered when issuing a DELETE statement on a table with interleaved tables that all have ON DELETE CASCADE clauses, have no secondary indices, and aren't foreign key-referenced by any other table. The path is not taken when there is any RETURNING claus in the delete query. When triggered, the delete operation will skip the expensive foreign key check operations, instead opting for using KV `DelRange` requests to delete all of the keys necessary. 

The performance boost from using this fast path is several orders of magnitude, potentially going from second-scale to sub-nanosecond scale.

**Comment by jseldess** [comment]
@rmloveland, what's left here after https://github.com/cockroachdb/docs/pull/3834?

**Comment by rmloveland** [comment]
@knz I recall that there are some other fast paths that you created diagrams for.  Are the other fast path operations in a state that we would want to document them at this time?

**Comment by BramGruneir** [comment]
Yep, I say close it.
