### ISSUE TITLE
Expand docs on common errors

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3515]
https://www.cockroachlabs.com/docs/dev/common-errors.html

**Comment by knz** [comment]
The first two errors currently on the page will not exist (as-is) in 2.1 any more thanks to https://github.com/cockroachdb/cockroach/pull/28200

Instead there are now about 5-6 different messages with clearer instructions about next steps.

**Comment by jseldess** [comment]
Updated the existing page. Closing this for now.
