### ISSUE TITLE
Replace mentions of root with superuser.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#3518]
Since RBAC, SQL permission checks that required the `root` user changed to require a superuser. This [is defined](https://www.cockroachlabs.com/docs/stable/roles.html#terminology) as "a member of the `admin` role" (which includes the `root` user).

For example, `BACKUP` requires a superuser but [currently says](https://www.cockroachlabs.com/docs/stable/backup.html#required-privileges) `root`. This can be misleading for anyone using RBAC.

**Comment by rolandcrosby** [comment]
In the new CDC docs, @lhirata said this, which I think is a good summary that we can use going forward:
> Changefeeds can only be created by superusers, i.e., [members of the `admin` role](create-and-manage-users.html). The admin role exists by default with `root` as the member.

One loose end here: you can only use `GRANT ROLE` when you have an enterprise license. I *think* this implies that `root` is the only superuser you can have in a core installation. @awoods187 can you confirm and help us come up with appropriate language to get this across?

**Comment by mberhault** [comment]
That is correct: roles can only be granted when running enterprise. So `root` is the only member of `admin`.

All (baring bugs) privilege checks at the SQL level that used to check for `root` now check for "member of `admin`".
