### ISSUE TITLE
Use cockroach sql instead of psql in SQL Audit Logging examples

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#3533]
Re: [SQL Audit Logging](https://cockroachlabs.com/docs//v2.0/sql-audit-logging.html)

## Issue Description

The examples in this page (and perhaps in other pages, I have not checked) reveal that the author of the page has used the command `psql` from PostgreSQL instead of `cockroach sql` to derive the examples -- indeed, the "application name" field shows "psql" which is the smoking gun.

I'm not sure I like the impression this gives - that our own product is not good enough to work with?

## Suggested Resolution 

Use `cockroach sql` more, or at least audit all the examples throughout the documentation to find stray occurrences of "psql".

(The application name generally crops up in many places.)

**Comment by jseldess** [comment]
Hmm, I've never used Postgres to generate examples. @rmloveland handled this page, and I think this may be a result of the way he was (or is?) using emacs? Rich, can you chime in?

**Comment by rmloveland** [comment]
> @rmloveland handled this page, and I think this may be a result of the way he was (or is?) using emacs?

Yes, that is correct, it was called by Emacs SQL mode.  I will modify my workflow to make sure `cockroach sql` is used.  Thanks for the heads up.

**Comment by knz** [comment]
Alternatively you can simply search/replace on save to transform "psql" to "cockroach sql". I think it's OK to use `psql` to run your examples through.
