### ISSUE TITLE
Guide for eliminating inconsistent data

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/docs#3536]
Would be helpful to get a quick guide together outlining Raphael's steps here:  https://forum.cockroachlabs.com/t/consistency-check-failed-with-1-inconsistent-replicas/1869

Not high priority, I'll try taking a first stab at it when I get a few cycles.

**Comment by jseldess** [comment]
@mwang1026, closing this. I imagine this will come out of the roadmap at some point. Please reopen if you disagree.
