### ISSUE TITLE
Add section about Compliance with SQL Standard

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#354]
A lot of SQL DBs have SQL spec conformance charts in there documentation:
- https://www.postgresql.org/docs/8.1/static/features.html
- http://doc.nuodb.com/display/doc/Compliance+with+SQL+Standard
- https://docs.oracle.com/database/121/SQLRF/ap_standard_sql003.htm#SQLRF55516

We should consider adding a chart like this.

**Comment by uptimeDBA** [comment]
Hi Nathan,

It would be a useful addition but, in my opinion, one that would take a disproportionate amount of effort to compile and maintain for the benefit it would provide.

At this stage I would suggest a "Statement of Direction" or "Statement of Conformance" regarding the SQL standard. For example; Achieving compliance with PostgreSQL where possible or whatever, etc. 
I should note that PostgreSQL is one of the most compliant implementations of the SQL standard. Even so, their compliance statement/table is based on SQL:2003 which is 3 versions old.
We could mention any (major) deviation from either our Statement of Conformance or the SQL standard in the section of the manual that discusses that particular topic. 

I see more value in aligning with another major player's version of SQL where possible (eg PostgreSQL) than the SQL Standard. This would open up market opportunity around Apps/APIs designed for PostgreSQL while giving us a much clearer target to focus on. (The SQL standard is very vague and ambiguous in many places.)
As background, I've presented at conferences on the topic of the SQL standard and the reasons why no database vendors comply.

**Comment by jseldess** [comment]
Covered by https://www.cockroachlabs.com/docs/sql-feature-support.html.

@nvanbenschoten, if you have suggestions for enhancing that page, please open separate issues.
