### ISSUE TITLE
Collect performance diagnostic information 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3547]
Collect crdb_internal.node_statement_statistics from all nodes.

`
cockroach node status --format tsv --insecure | tail -n +2 | while read id host other; do cockroach sql --format tsv --url postgres://root@$host?sslmode=disable -e "select crdb_internal.cluster_id(), now(),* from crdb_internal.node_statement_statistics;"; 
done > node_statement_statistics.tsv
`

Collect Range Usage Info

[Download 4 scripts](https://gist.github.com/a-robinson/54fbaa6628ae9f1ad9c6185ecd28edb9/archive/eab9570b224474d8cc2b55da8acff4459656b847.zip).  Additional context on the scripts is [available.](https://github.com/cockroachdb/cockroach/issues/26059#issuecomment-393697175) 

```
curl http://localhost:8080/_status/raft > ranges
python hottest_nodes.py ranges > hottest_nodes.txt
python hottest_ranges.py ranges > hottest_ranges.txt
python tables_per_node.py ranges > tables_per_node.txt
```

**Comment by robert-s-lee** [comment]
node status

```
cockroach sql --format tsv --url postgres://root@127.0.0.1?sslmode=disable -e "select * from crdb_internal.kv_node_status;" > node_status
```

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
