### ISSUE TITLE
Overview of security and access control

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#3549]
We have basic mechanical docs on certs and users/privileges, but we're missing a clear overview of CockroachDB's security offerings. This should include:
- [ ] Encryption (TLS and At Rest)
- [ ] Authentication (TLS and passwords)
- [ ] Access Control (users, privileges, and roles)
      - See https://forum.cockroachlabs.com/t/admin-ui-authentication/661/4?u=bdarnell

**Comment by jseldess** [comment]
Thanks, @mberhault. I'll see if I can get this written up for the 2.1 release, given that this is a regular source of confusion. @tim-o, do you agree?

**Comment by tim-o** [comment]
Yes, definitely agree. Connecting to a cluster is a major point of confusion for customers.

**Comment by jseldess** [comment]
Not sure there'll be bandwidth to handle this for 2.1. Will have to wait and see.

**Comment by jseldess** [comment]
In addition to the "how to connect" page, we should write a page summarizing all CockroachDB's security options:

- Encryption (TLS and At Rest)
- Authentication (TLS and passwords)
- Access Control

**Comment by jseldess** [comment]
From @tim-o:

On this doc:
https://www.cockroachlabs.com/docs/stable/create-user.html

This snippet:
```
Users with passwords can authenticate their access by entering their password at the command prompt instead of using their client certificate and key.

If we cannot find client certificate and key files matching the user, we fall back on password authentication.

cockroach sql --user=jpointsman
```

Is inaccurate. Should read something like:
```
If you wish users to authenticate with a password, you can, though users will still need to provide a client certificate and key in order to connect to CRDB.
```

See: https://github.com/cockroachdb/cockroach/issues/22537#issuecomment-364603744

**Comment by mberhault** [comment]
The doc had it right: if a user has a client certificate and key matching their username in the certs-dir (eg: `client.jpointsman.crt` and `client.jpointsman.key`), it will perform certificate authentication. If not present, CockroachDB will fall back on password authentication.

A user **cannot** use password authentication when passing a client cert and key.

What prompted the proposed correction?

**Comment by jseldess** [comment]
You're right, @mberhault. I was trying to consolidate related issues, but that issue isn't correct. I do think there's room to improve how we explain this as part of this project, however.

**Comment by jseldess** [comment]
@lhirata, @rolandcrosby, here's the security docs project for 2.2. Please feel free to clarify and/or expand as needed.

**Comment by Amruta-Ranade** [comment]
Thoughts/Notes from research so far:
- Some of the features are enterprise, some aren't. Need to mark them in the overview doc.
- How does encryption at rest and TLS encryption relate to security certs?
- The encryption at rest doc might need some updates based on the answer to the question above
- We might want to make a separate section in Docs called "Security" and club all relevant docs under it
- Does the RBAC doc exist or is writing it a part of this project?

**Comment by mberhault** [comment]
Thanks for the summary. Let me see if I can chime in on some of your points. My overall take however would be: those features (RBAC, TLS, encryption-at-rest) are all related to security but are not related to each other or dependent on each other. My intention in filing this issue was to find a way to give an overview of the security aspects of CockroachDB, even if the individual features are not inter-connected.

Onto your individual points:
* enterprise: certificates and TLS are all OSS. roles are enterprise. encryption at rest is enterprise.
* encryption at rest and TLS have no relationship or dependency. You could use encryption at rest on an insecure cluster (it would be crazy, but nothing stops you). Certificates are only used for TLS and the only ones that exist are the ones you are now very familiar with.
* it probably needs some improvements in general, but it's listed under "enterprise features", so I think we're ok there. Again, no relation to TLS or certificates, so no changes there.
* RBAC has [its own page](https://www.cockroachlabs.com/docs/stable/roles.html) under "enterprise features". The terms "admin role" and "superuser, aka: the root user or members of the admin role" are sprinkled throughout the docs.
* end-to-end security options: while you can enable (or not) each feature individually, a set of recommendations for "production hardening" (I'm thinking of the nice doc from [Vault](https://www.vaultproject.io/guides/operations/production)) would be nice. Basically a summary (with links to more in-depth content) showing how to make your CockroachDB deployment as safe as possible.
* encryption-at-rest shows up only in the debug pages for now. See [the doc](https://www.cockroachlabs.com/docs/stable/encryption.html#checking-encryption-status) for details.
* another resource is the actual [doc](https://www.cockroachlabs.com/docs/stable/encryption.html)
* license expiration: you mean for encryption at rest? Nothing at all. We do not currently check the enterprise license for encryption at rest.

**Comment by mberhault** [comment]
* when a data key is rotated, it means we start using a new key for all new writes. However, we keep the old keys around to read the files encrypted with it. The regular rocksdb churn will cause old keys to slowly become unused.
* they're kept in the "key registry" which is encrypted using the "store key"
* core files are generated when a process crashes. They contain some (or all) of the program's memory. This can include the areas of memory that store the encryption keys
* ah. uh. yes, the examples may need some clarification
* certs have nothing to do with encryption at rest, they are not required to have encryption enabled.
* oh, I may have had a typo in the port
* yes, one store key per store. You can have one store encrypted, and another not encrypted. If both are encrypted, you could "technically" point them to the same key but you really shouldn't

**Comment by Amruta-Ranade** [comment]
**Questions/Thoughts about the RBAC doc:**
- I don't understand the hierarchy of the roles :( (Role Admin, superuser, root)
- I also don't understand when to create each role (use cases). (I think this might be evident to the users, but it isn't evident to me).

Aha! Found this RFC that makes things a bit clearer: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171220_sql_role_based_access_control.md

**Comment by mberhault** [comment]
Superuser does not technically exist, it just means the set of users that belong to the admin role.
The `root` user by default is the only member of the `admin` role. Both the `admin` role and the `root` user exist by default and cannot be deleted.

**Comment by Amruta-Ranade** [comment]
- Secure clusters: Nodes always use TLS, users can have TLS with certs or TLS without certs but with passwords. In that case, nodes still present node certs that clients verify using ca.crt
- Web UI auth takes only passwords, not certs
- Encryption in flight uses TLS 1.2. (Version number matters because we exceed the PCI data protection std which requires TLS 1.1 or higher (and that's good and needs to be called out)).
- Encryption at rest: uses keys that are stored on every store. Expectation is that users use some sort of key mgmt system. If you have the encryption keys on same disk as data, that's not good.
- Access Control (users and privileges, and RBAC)

How much do people know about PKI, certs, etc.?
- Most people don't have exposure/knowledge about certs, especially client certs
- Good idea to add conceptual doc

- Once TLS connection is established, it generates a new temp key for symmetric encryption.

**Comment by Amruta-Ranade** [comment]
**Roland’s thoughtstream:**

Authentication - what does it mean to connect with a cert vs. username/password
Authorization/RBAC
Encryption at rest/encryption over the wire
Encryption for touchpoints with other services (e.g. S3 backup encryption, encrypted comms with Kafka)
Best practices for security of operations (how to do key management, key rotation, cert rotation, password management, etc.)
Auditing (experimental audit log) - maybe useful for compliance?
How web UI security works (TLS, CA certs, username/password)

How to mimic features like row-level/column-level permissioning (views and grants on views) 

How to use features in CRDB to set up a database that’s compliant with PCI, HIPPA, SOX(?), etc.
- Maybe the answer here is mostly “get your organization/HR stuff compliant first” but need to figure out whether there are technical requirements/guidance we can offer too
