### ISSUE TITLE
Add known limitation about changing the replication factor

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/docs#3552]
See https://github.com/cockroachdb/cockroach/issues/14990 (link was edited)

If a user decides to run with, say, 5x replication and changes the `.default` zone config accordingly, they're still not done. They also need to change the `.liveness` zone config as well as the zone config for the system database, which will have "copied over" the 3x at cluster creation time and won't automatically pick up the 5x. (And losing either of these is fatal).

We should also generally recommend that operators bump the replication factor for those parts of the keyspace to 5x, provided they are running at least a five node cluster.

**Comment by jseldess** [comment]
Grabbed this while I was working on https://github.com/cockroachdb/docs/issues/3699, @rmloveland. Hope that's ok.

**Comment by rmloveland** [comment]
> Grabbed this while I was working on #3699 <https://github.com/cockroachdb/docs/issues/3699>, @rmloveland <https://github.com/rmloveland>. Hope that's ok.
> 
It’s glorious!
