### ISSUE TITLE
document SERIAL column type

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/docs#356]
Added in https://github.com/cockroachdb/cockroach/pull/7032.

Some notes to start with:

A SERIAL column is an INT column with a DEFAULT that is unique per row. Notably, ours is a bit different than Postgres's SERIAL and MySQL's AUTO_INCREMENT, both of which approximate a sequence starting at 1 (or maybe 0?).

Our implementation covers the essential uniqueness property, but the differences may be jarring to users so they should be called out in the docs. One important point to include is that there are two common misconceptions with Postgres's SERIAL and MySQL's AUTO_INCREMENTING. They do have holes and they are not strictly increasing.

#### Example of hole:

    CREATE TABLE ab (a SERIAL PRIMARY KEY, b INT);
    BEGIN; INSERT INTO ab (b) VALUES (1); ROLLBACK;
    BEGIN; INSERT INTO ab (b) VALUES (2); COMMIT;
    SELECT * from ab;
     a | b
    ---+---
     2 | 2

#### Example of out-of-order:

In client 1:

    CREATE TABLE ab (a SERIAL PRIMARY KEY, b INT);
    BEGIN; INSERT INTO ab (b) VALUES (1); SELECT * FROM ab;

In client 2:

    BEGIN; INSERT INTO ab (b) VALUES (2); COMMIT;

In client 3:

    SELECT * FROM ab;
     a | b
    ---+---
     2 | 2

In client 1:

    COMMIT;

In client 3:

    SELECT * FROM ab;
     a | b
    ---+---
     1 | 1
     2 | 2

Note the `(2, 2)` was committed before `(1, 1)`.

**Comment by petermattis** [comment]
Nice. In the "hole" example, I think rollback the first transaction before the second transaction even starts.

**Comment by paperstreet** [comment]
Good point. You can even do it all in one client:

    CREATE TABLE ab (a SERIAL PRIMARY KEY, b INT);
    BEGIN; INSERT INTO ab (b) VALUES (1); ROLLBACK;
    BEGIN; INSERT INTO ab (b) VALUES (2); COMMIT;
    SELECT * from ab;
     a | b
    ---+---
     2 | 2

**Comment by jseldess** [comment]
Notes: 

- Uses timestamp and node id to generate ID. Combination will always be unique.
- Globally unique id without nodes having to talk to each other. Faster than linear sequence (12345). Completely independent.
- Postgres doesn't do sequence strictly. Can be holes. Underlying principles the same.
- This is experiment. Technically, a better solution than doing sequence, cause it's much faster. 
   - We think this will work same as sequence, but it's a little jarring. 
   - If too much user pushback, might change. 
   - If prevents you from using feature or break something, let us know. "If you think this is incompatible with your application, xxx".
- It's technically possible to replicate sequence manually with a transaction, but performance will be very bad. Essentially creating a global write lock on table, for each insert.

**Comment by rbondar** [comment]
Two functions are currently can be used for providing distributed uniqueness: unique_rowid() , returns int or experimental_uuid_v4(), returns bytes .
id SERIAL PRIMARY KEY is currently the best thing to use. it's a wrapper for id INT DEFAULT unique_rowid() PRIMARY KEY .
Thx @mjibson , @dt .
