### ISSUE TITLE
Document virtual sequences for use with SERIAL

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3562]
See [cockroachdb#28575][1], highlights of which include:

> This patch introduces **virtual sequences**, a CockroachDB-specific extension to SQL sequences. Virtual sequences are sequences that do not generate monotonically increasing values and instead produce values like the built-in function `unique_rowid()`.

and

> CockroachDB now supports two experimental compatibility modes with how PostgreSQL handles SERIAL and sequences, to ease reuse of 3rd party frameworks or apps developed for PostgreSQL.

See PR for full details.

Related:

- [Forum post on Hibernate sequences using @Id column spec returning unexpected values][2]
- [Cockroach issue to address Hibernate @Id column spec from forum post][3]

[1]: https://github.com/cockroachdb/cockroach/pull/28575
[2]: https://forum.cockroachlabs.com/t/hibernate-sequence-generator-returns-negative-number-and-ignore-unique-rowid/1885
[3]: https://github.com/cockroachdb/cockroach/issues/28499

**Comment by jseldess** [comment]
This was included in our page on experimental features: https://www.cockroachlabs.com/docs/stable/experimental-features.html.
