### ISSUE TITLE
EXPORT docs notes from QA

### ISSUE THREAD

**Issue by dt** [cockroachdb/docs#3563]
* `EXPORT` doesn't show up in jobs -- it shows up in `SHOW QUERIES` and can be cancelled like other queries. Some day we might make jobs for them, but for now we need to let users know where to look.

From https://github.com/cockroachdb/cockroach/issues/25223:

> * `The `nullas` docs have a typo and read as if they’re still talking about IMPORT

> * Not a bug, but unicode emoji aren’t valid delimiters and that makes me sad :(

We should mention that only valid ascii chars can be used as csv delimiters.

> * The documentation of the GCS parameters doesn’t make sense, and appears incorrect.

>   * It equates not specifying AUTH with setting AUTH=default, which isn’t true in practice:
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://cockroach-alex/csv' WITH delimiter=e'\u03B1' FROM SELECT * from startrek.quotes;
> pq: write to google cloud: googleapi: Error 403: 21965078311-compute@developer.gserviceaccount.com does not have storage.objects.create access to cockroach-alex/csv/n1.0.csv., forbidden
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://cockroach-alex/csv?AUTH=default' WITH delimiter=e'\u03B1' FROM SELECT * from startrek.quotes;
> pq: expected settings value for cloudstorage.gs.default.key
> root@:26257/defaultdb> EXPORT INTO CSV 'gs://cockroach-alex/csv?AUTH=implicit' WITH delimiter=e'\u03B1' FROM SELECT * from startrek.quotes;
> pq: write to google cloud: googleapi: Error 403: 21965078311-compute@developer.gserviceaccount.com does not have storage.objects.create access to cockroach-alex/csv/n1.0.csv., forbidden
> ```

* Should mention that it is important to pick nullas values unlikely to appear in the exported data to avoid collusions.

**Comment by a-robinson** [comment]
I fixed the GCS auth and `nullas` documentation in https://github.com/cockroachdb/docs/pull/3225

**Comment by jseldess** [comment]
@Amruta-Ranade, @lhirata, did either of you document `EXPORT`? If so, maybe you could take this issue?

**Comment by lhirata** [comment]
I can take this
