### ISSUE TITLE
Partition using Secondary Index Correction 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3568]
Re: [Define Table Partitions](https://www.cockroachlabs.com/docs/v2.0/partitioning.html#partition-using-secondary-index)

## Issue Description

- example is missing key words to create the partitioned table
- example does not show an example of correct secondary index

```
CREATE TABLE foo (a STRING PRIMARY KEY, b STRING) PARTITION BY LIST (a) (                                       bar VALUES IN ('bar'), default VALUES IN (DEFAULT));
invalid syntax: statement ignored: syntax error at or near "bar"

CREATE INDEX foo_b_idx ON foo (b) PARTITION BY LIST (b) (
    baz VALUES IN ('baz'),
    default VALUES IN (DEFAULT)
);
invalid syntax: statement ignored: syntax error at or near "baz"
```

after the syntax is correct, the error message will be:
```
pq: PARTITION default: name must be unique (used in both index "primary" and index "foo_b_idx")
```

- is there typo on the example? in the create table ` partition bar VALUES IN ('bar'),` but index has `    partition baz VALUES IN ('baz'),`.  That in `bar` vs `baz`

- it is not clear from this example how the non unique secondary index could benefit from the secondary index.
 
- Does example of partition on unique secondary index help?

## Suggested Resolution 

- correct the syntax error
```
CREATE TABLE foo (
  a STRING PRIMARY KEY, 
  b STRING) 
PARTITION BY LIST (a) (
    partition bar VALUES IN ('bar'),
    partition default VALUES IN (DEFAULT)
);

CREATE INDEX foo_b_idx ON foo (b) 
PARTITION BY LIST (b) (
    partition baz VALUES IN ('baz'),
    partition default VALUES IN (DEFAULT)
);
```

- more explanation should be provided on `Consider using a naming scheme that uses the index name to avoid conflicts`.  This is not obvious that partition name `baz` and `default` defined in table `foo` must to unique across the cluster.  

- show suggested correction to index removing conflicting partition name from the table
```
CREATE INDEX foo_b_idx ON foo (b) 
PARTITION BY LIST (b) (
    partition b_baz VALUES IN ('baz'),
    partition b_default VALUES IN (DEFAULT)
);
```

**Comment by awoods187** [comment]
Closing this as out of date
