### ISSUE TITLE
Docs site blanks intermittently

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3570]
Several users reported blank pages on the docs site this morning around 11 am (Wednesday, August 22, 2018).

Screenshot from a user experiencing the issue of errors in their console:

![image](https://user-images.githubusercontent.com/1312291/44473058-86b33300-a5fd-11e8-80d7-c67b825cbd56.png)

**Comment by rolandcrosby** [comment]
[This particular page](https://www.cockroachlabs.com/docs/stable/training/cluster-upgrade.html) appears to consistently not load -- if you look at the source or try to load it using curl, the source code is cut off right in the middle of an `<input>` tag. No idea how this happened beyond that, though.

**Comment by jseldess** [comment]
@j-low, @mjibson, any ideas as to what's happening? Something with netlify?

**Comment by mjibson** [comment]
I have no idea, but it is almost certainly related to netlify. I think the best we can do is continue to monitor this. Netlify did a major change of their SSL handling a few days ago and maybe this was fallout. We should keep watching and ask our employees to tell us anytime they see a blank page load.

**Comment by jseldess** [comment]
This has been resolved.
