### ISSUE TITLE
Example of using UUID data type for range partitioning

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3572]
It is customary to assign meanings to sections of a primary key . The composition of the primary can be exposed as separate columns and maintained using a composite primary key.  Another approach is a single column with the composition encoded in the single key.  For example, 128 bits UUID is composed of time_low, time_mid, time_hi_and_version, clock_seq_hi_and_res clock_seq_low, node.  

Other uses of this technique could be as follows:

- customer id could be composed on location id, some random id.
- order id could be composed of store id, some random id.

The location id and order id are especially useful when customer or order could be ontained from many sources at the same time.  Each source can maintain them and and even when all of the data is consolidated, conflict resolution is not required.  UUID with a single 128 bits is ideal data type for this technique.   The 128 bits provide provide ample room add may attribute and is supported by CockroachDB. 

CockroachDB's unique feature is single global instance database.  Each locality maintaining its own customers and orders benefit of single database but local performance.  Below is an example to test and setup:  

Let assume the following for the UUID composition:

- Americas has first byte of '\x10'
- Europe has first byte of '\x20'
- Asia has first byte of '\x30'
- The rest of the UUID is used by the application.

- Setup CockroachDB cluster:

```
cockroach start --insecure --port=26257 --http-port=26258 --store=cockroach-data/1 --cache=256MiB --locality=r=americas --background
cockroach start --insecure --port=26259 --http-port=26260 --store=cockroach-data/2 --cache=256MiB --join=localhost:26257 --locality=r=europe --background
cockroach start --insecure --port=26261 --http-port=26262 --store=cockroach-data/3 --cache=256MiB --join=localhost:26257 --locality=r=asia --background
```

- Setup schema
-- note the 16 bytes of UUID specified in byte
-- the beginning of the range is inclusive, the end is exclusive (meaning outside of the range)

```
CREATE TABLE IF NOT EXISTS orders (
  order_id UUID,
  customer_id UUID DEFAULT gen_random_uuid(), 
  PRIMARY KEY (order_id)
) PARTITION BY RANGE (order_id) (
    PARTITION americas VALUES FROM (b'\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00') to (b'\x20\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    ,PARTITION europe VALUES FROM (b'\x20\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00') to (b'\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
    ,PARTITION asia VALUES FROM (b'\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00') to (b'\x40\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
);
```
- Place two replica copies in the source and one remote for fast write

```
ALTER PARTITION americas OF TABLE orders EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+r=americas": 2}';
ALTER PARTITION europe OF TABLE orders EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+r=europe": 2}';
ALTER PARTITION asia OF TABLE orders EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+r=asia": 2}';
```

- Place the leaseholder in the source for fast read and then the secondary preference

```
ALTER PARTITION americas OF TABLE orders EXPERIMENTAL CONFIGURE ZONE 'experimental_lease_preferences: [[+r=americas],[+r=europe]]';
ALTER PARTITION europe OF TABLE orders EXPERIMENTAL CONFIGURE ZONE 'experimental_lease_preferences: [[+r=europe],[+r=asia]]';
ALTER PARTITION asia OF TABLE orders EXPERIMENTAL CONFIGURE ZONE 'experimental_lease_preferences: [[+r=asia],[+r=americas]]';
```

- Insert values from the Americas client to Americas database
-- the insert and read will be fast
```
insert into orders (order_id) values (b'\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'),(b'\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02') returning order_id, customer_id;
select * from orders where order_id in (b'\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01',b'\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02');
```

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
