### ISSUE TITLE
ALTER COLUMN Doc Update 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#3576]
Re: [ALTER COLUMN](https://cockroachlabs.com/docs//v2.0/alter-column.html)

We now apparently support alter table .. alter column ... type <new type> - which allows some trivial but important changes to a column's type. This is not documented.

**Comment by jseldess** [comment]
This is covered by https://github.com/cockroachdb/docs/issues/2992. We'll definitely get it documented for the 2.1 release.
