### ISSUE TITLE
Concurrency guidance and best practices

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3584]
We need to make sure users understand the importance of concurrency and how it impacts performance.

- [ ] Update our [build an app](https://www.cockroachlabs.com/docs/stable/build-an-app-with-cockroachdb.html) tutorials to demonstrate basic best practices.
    - Some users copy and paste our code samples and end up with poor performance. See https://github.com/cockroachdb/docs/issues/2464.
    - See also https://github.com/cockroachdb/docs/issues/3578.
- [ ] Factor concurrency into [performance tuning](https://www.cockroachlabs.com/docs/dev/performance-tuning.html). 
    - This might mean splitting into 2 tutorials: single-region and multi-region.
    - This involves explaining the relationships between concurrency, latency, and throughput. 
    - In the single-region tutorial, we would still use a partitioning-compatible schema because we'll use partitioning as a way to optimize concurrency and throughput (after partitioning, `users` table data will be split across one range per `city`). We therefore won't lose the narrative of "using a schema designed for future scaling".
    - See https://github.com/cockroachdb/docs/issues/3360.
    - See https://github.com/cockroachdb/docs/issues/2463.

**Comment by awoods187** [comment]
Good candidate for early 2.3 project post 2.2 release

**Comment by jseldess** [comment]
@awoods187, I just created the `19.2` milestone. Feel free to assign post-2.2 high prio docs issues to that milestone with `P-1`.

**Comment by jseldess** [comment]
Prioritizing https://github.com/cockroachdb/docs/issues/4693 instead. This will feed into it.

**Comment by rmloveland** [comment]
Unassigning myself since I won't be working on this soon.  Expect we will re-prioritize / re-assign (perhaps even back to me) when we get around to this.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
