### ISSUE TITLE
Drift chat icon covers up help icon on 2.1 docs deployed by teamcity

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#3588]
I haven't seen this on the live production site, but on [the teamcity build of a current code review](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/33d96566e613cc45da463ce86f9f81d598bbd2a7/v2.1/orchestrate-cockroachdb-with-kubernetes-multi-region.html) I'm seeing the Drift chat icon covering up most of the new Help icon in the bottom right of the screen:

<img width="1320" alt="screen shot 2018-08-27 at 11 36 27 am" src="https://user-images.githubusercontent.com/7085343/44672448-125a0480-a9ee-11e8-9c02-8ccbd2d0805f.png">

Sorry if this is something that only affects teamcity builds, but it looks pretty funny so I wanted to make sure we're aware of it.

@j-low

**Comment by jseldess** [comment]
Yeah, this annoys me, too, but it's only a problem on teamcity builds, as you suspected. In the live docs, we actually hide that "help" button on pages with drift, and we use more granular targeting to control where drift shows up. Not sure there's a way around the teamcity problem right now.

**Comment by a-robinson** [comment]
Thanks for explaining. Feel free to close this if you want.
