### ISSUE TITLE
Inline opt_RULE rules in SQL railroad diagrams

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#359]
It would be neat if `opt_RULE` rules were inlined in their parent grammar rules in the SQL railroad diagrams. These rules are usually a single element or empty, so this change wouldn't add much bulk to the generated report. For example: https://www.cockroachlabs.com/docs/sql-grammar.html#opt_name.

**Comment by uptimeDBA** [comment]
I've built a page of refreshed diagrams that I will be pushing one at a time for review. All the `opt_RULE` pieces have been inlined, along with many other alterations. I'm still reworking some but for example, here's the index_def.
![image 1](https://cloud.githubusercontent.com/assets/17366371/15834836/7a682c1a-2c81-11e6-8d02-f4743ede27b4.png)

All the diagrams (one one page for easy viewing) can be found [here](http://uptimedba.github.io/cockroach-vb-single/cockroach-vb-single/cockroachdb_syntax_diagrams.html)

**Comment by jseldess** [comment]
Really appreciate these enhancements, @uptimeDBA. Thanks!

**Comment by jseldess** [comment]
As @uptimeDBA demonstrates above, we can do this in diagrams for specific statements. But you're suggesting we do this across the full grammar, @nvanbenschoten, is that right?

**Comment by nvanbenschoten** [comment]
@jseldess Correct, the suggestion was to generalize the inlining of opt_RULE rules in our railroad diagram generator.

**Comment by jseldess** [comment]
@nvanbenschoten, I think it's most important for us to inline opt_rule in statement-specific diagrams, as we've been doing, so I'm closing this for now. If you see specific cases that need to be addressed, please open separate issues.
