### ISSUE TITLE
Postgres vs CRDB Integer size discrepancy

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3592]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recb9phXYHXAdNeN2
PM: @awoods187 
Eng partner: @knz

**Comment by knz** [comment]
I'll take this doc issue.

**Comment by jseldess** [comment]
Thanks, @knz!

**Comment by jseldess** [comment]
From the http://www.cockroachlabs.com/docs/releases/v2.1.0-beta.20180827.html release notes:

> The cockroach sql command and other client commands that display SQL results now use the new table result formatter by default, replacing the previous formatter called pretty. This provides more compact and more reusable results. 

PR: https://github.com/cockroachdb/cockroach/pull/28465

**Comment by knz** [comment]
@jseldess what about your last comment? does this belong to this PR?

**Comment by jseldess** [comment]
Whoops, no, sorry.

**Comment by jseldess** [comment]
Docs already correct here.
