### ISSUE TITLE
server/storage: Add admin endpoint to manually run range through queue

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3596]
PR: https://github.com/cockroachdb/cockroach/pull/26554

From release notes:
> The new `/_admin/v1/enqueue_range` admin server endpoint runs a specified range through a specified internal queue on one or all nodes. The `skip_should_queue` parameter can also be specified to tell the system to blindly run without first checking whether it needs to be run. This endpoint is intended primarily for debugging purposes. [#26554][#26554] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Is this mostly for internal debugging, @a-robinson?

**Comment by a-robinson** [comment]
Correct, this is for internal debugging.

**Comment by jseldess** [comment]
OK, thanks, @a-robinson. Closing.
