### ISSUE TITLE
Make all internal links relative

### ISSUE THREAD

**Issue by hvaara** [cockroachdb/docs#36]
Making the links relative will make it easier to set up a staging environment as well as (automatically) testing before pushing upstream. Any thoughts?

**Comment by jseldess** [comment]
In this theme, links are relative by default, I think: http://idratherbewriting.com/documentation-theme-jekyll/mydoc/mydoc_hyperlinks.html. Can you say a little more about what you'd like to change?

Automatically testing the html output is definitely a good idea. I was planning to try out https://github.com/gjtorikian/html-proofer, but I'm not yet sure how I'd make it automatic. I agree that ti'd be best to test before pushing upstream. Maybe whenever you run `jekyll serve` or `jekyll build` on your local branch?

**Comment by hvaara** [comment]
What I meant was for the inline html. Seems most of the links there are already relative or external. Any reason the ones in index.md aren't?

Broken links would be nice to test for as well.

**Comment by jseldess** [comment]
Thanks for the clarification, and for catching those links in `index.md`. No good reason why those weren't relative. I just fixed that, so I'll close this issue, but please let me know if you see the problem anywhere else.

And I totally agree that testing for broken links is important. That'll definitely have to be part of #39.
