### ISSUE TITLE
Change IDENT to identifier in grammar diagrams

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#360]
It'd be great to change `IDENT` to `identifier` through the grammar diagrams. 

Example of where this shows up: https://www.cockroachlabs.com/docs/delete.html

Related to: https://github.com/cockroachdb/docs/issues/358

**Comment by uptimeDBA** [comment]
From a diagram point of view, `SCONST` has the same issue. I haven't looked at in in the general case but for example the current `CREATE DATABASE` statement looks like:
![current_create_database](https://cloud.githubusercontent.com/assets/17366371/15878287/c1848430-2d6d-11e6-879d-46699d4d6d4b.png)

opt_encoding_clause expands to:
![opt_encoding_clause](https://cloud.githubusercontent.com/assets/17366371/15878298/dbbf5dfc-2d6d-11e6-8366-e08c0f1600ec.png)

Using the `Replace` functionality of the `generate` utility, I've used this:

~~~
{name: "create_database_stmt", inline: []string{"opt_encoding_clause"}, replace: map[string]string{"'SCONST'": `"'" ('UTF-8'|'UTF8'|'UNICODE') "'"`}},
~~~

To produce this:
![new_create_database](https://cloud.githubusercontent.com/assets/17366371/15878323/1143b6c6-2d6e-11e6-8edc-95d087fd232e.png)

I've essentially replaced `SCONST` with a hardcoded list of acceptable values as the only place they seem to be defined is in [create.go](https://github.com/cockroachdb/cockroach/blob/14db8a615c09b653581c856e3f12b35d183df362/sql/create.go#L51)

Let me know if there's a better way, other than using `Replace`. (apart from changing the grammar file of course.)

**Comment by jseldess** [comment]
Looks great to me, @uptimeDBA. @mjibson, any thoughts?

**Comment by mjibson** [comment]
We also have ICONST, FCONST, BCONST. But for this specific case of SCONST in the ENCODING, I'm not sure of the precedent we want to set. It may make more sense to document the valid values of the encoding in the markdown prose instead of in the grammar diagrams. I'm not sure. I'm a little worried that documenting it in the grammar like above will not document all the possibilities. For example, in MODERN syntax, you can also do: `create database t2 encoding = """UTF8""";`.

**Comment by uptimeDBA** [comment]
No problem. It would be easy to replace the `SCONST` with `encoding` and detail the valid values in the parameter descripton. Something like:
![image 1](https://cloud.githubusercontent.com/assets/17366371/15909846/4dc5d6fc-2e1c-11e6-826c-227211a6ee48.png)

Let me know which one you prefer and I'll make it so.

**Comment by jseldess** [comment]
Let's go with `ENCODING = encoding` and document the possible values in the markdown, as @mjibson  suggests. Thanks, @uptimeDBA.

**Comment by sploiselle** [comment]
With all of the accepted values for ICONST, FCONST, BCONST, and SCONST, they could document be documented alongside keywords and/or identifiers.

@uptimeDBA | @mjibson – Do either of you have a list of all accepted values for ICONST, FCONST, BCONST? Assuming SCONST's values are contained in the `encoding` sample above.

@jseldess – In places similar to `ENCODING = encoding`, but using other constants, it would be useful to at least have these prepped somewhere. I could see this information being used in 'Keywords & Identifiers' – maybe changing it into 'Keywords, Identifiers, & Constants'

**Comment by jseldess** [comment]
Hey @sploiselle, sorry for my delay here. Just talked to @mjibson about those constants. It turns out that `SCONST` is the only one that occurs outside of a generic expression, and I think we're fine to just cover the accepted values in the `CREATE DATABASE` docs, as we've now don.

**Comment by sploiselle** [comment]
@jseldess 👍
