### ISSUE TITLE
sql: add missing sort column to SHOW GRANTS

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3612]
PR: https://github.com/cockroachdb/cockroach/pull/27884

From release notes:
> The output of [`SHOW GRANTS`](../v2.1/show-grants.html) is now fully sorted. [#27884][#27884] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @jordanlewis, the docs already reflect the correct behavior.
