### ISSUE TITLE
opt/sql: support ORDER BY INDEX, change behaviour

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3613]
PR: https://github.com/cockroachdb/cockroach/pull/27812

From release notes:
> The [`ORDER BY INDEX`](../v2.1/query-order.html#sorting-in-index-order) notation now implies an ordering by the implicit primary key columns appended to an index. [#27812][#27812] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Checked with Justin - docs are still correct.
