### ISSUE TITLE
sql: fix the handling of tuples in distsql

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3619]
PR: https://github.com/cockroachdb/cockroach/pull/28143

From release notes:
> CockroachDB now supports empty tuples with the syntax `()`, 1-valued tuples with the syntax `(x,)` in addition to `row(x)`, and the ability to use `IN` with an empty tuple as right operand. This is a CockroachDB extension. [#28143][#28143] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Don't think docs are needed for this
