### ISSUE TITLE
cli: set a timeout delay for SQL connections

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3638]
PR: https://github.com/cockroachdb/cockroach/pull/28326

From release notes:
> Client commands that use a SQL connection (e.g., `cockroach sql`, `cockroach node`, `cockroach user`) now produce an error if a connection could not be established within 5 seconds instead of waiting forever.  [#28326][#28326] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
No docs updates needed
