### ISSUE TITLE
cli: format byte results like in SQL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3639]
PR: https://github.com/cockroachdb/cockroach/pull/28494

From release notes:
> The [`cockroach sql`](../v2.1/use-the-built-in-sql-client.html) command and other client commands that display SQL results containing byte arrays now print them as if they were converted by a SQL cast to the `STRING` type. [#28494][#28494] {% comment %}doc{% endcomment %}

**Comment by knz** [comment]
I'd like to put this on hold as we've found this change may be causing more problems than it solves.

**Comment by jseldess** [comment]
Sounds good, @knz.

**Comment by jseldess** [comment]
Any updates on this, @knz?

**Comment by knz** [comment]
Update: I believe we'll have to revert to the pre-2.1 behavior but that won't happen for the release I fear. So I would recommend against a doc change, since we're going to change it back after the patch is produced into a 2.1.x release.

**Comment by jseldess** [comment]
Closing based on @knz's last comment.
