### ISSUE TITLE
base,server: better UX for server addrs and cert mis-configurations

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3644]
PR: https://github.com/cockroachdb/cockroach/pull/28502

From release notes:
> CockroachDB now attempts to inform the operator if the names and IP addresses listed in the configured certificates do not match the server configuration. [#28502][#28502] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
I think this is a bug fix, not a feature update. Don't see a doc impact. @knz: Thoughts?

**Comment by knz** [comment]
agreed -- unless you want to document errors that users are likely to encounter.

**Comment by mwang1026** [comment]
closing per ^ comments. anyone, feel free to reopen if you disagree.
