### ISSUE TITLE
ui: add disk ops per second graph to hardware dashboard

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3646]
PR: https://github.com/cockroachdb/cockroach/pull/28594

From release notes:
> Added disk read and write time charts to the [**Hardware** dashboard](../v2.1/admin-ui-hardware-dashboard.html). [#27977][#27977] [#28594][#28594] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3744
