### ISSUE TITLE
ui: show sys+user combined cpu, normalized by # cores

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3647]
PR: https://github.com/cockroachdb/cockroach/pull/28596

From release notes:
> The [**Hardware** dashboard](../v2.1/admin-ui-hardware-dashboard.html) now shows system and user CPU summed instead of separately, and normalized by number of CPUs. [#28596][#28596] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3744
