### ISSUE TITLE
ui: link to statements page from sidebar with new icon

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3648]
PR: https://github.com/cockroachdb/cockroach/pull/27928

From release notes:
> Added a link to the [**Statements** page](../v2.1/admin-ui-statements-page.html) from the sidebar. [#27928][#27928] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3745
