### ISSUE TITLE
ui: add "total" values for disk and memory to node list; add num CPUs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3650]
PR: https://github.com/cockroachdb/cockroach/pull/28189

From release notes:
> Added the number of CPUs and percentages of memory and disk usage to the [**Node List**](../v2.1/admin-ui-overview-dashboard.html). [#28189][#28189] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3886
