### ISSUE TITLE
ui: remove "DistSQL Reads" series from QPS graphs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3651]
PR: https://github.com/cockroachdb/cockroach/pull/28350

From release notes:
> Removed "distsql reads" time series from the [**SQL** dashboard](../v2.1/admin-ui-sql-dashboard.html), since execution engines are being merged. [#28350][#28350] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3745
