### ISSUE TITLE
storage, ui: add a problem range state of raft log size too large

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3652]
PR: https://github.com/cockroachdb/cockroach/pull/28034

From release notes:
> The **Problem Ranges** report now shows the number of replicas that have an excessively large log. [#28034][#28034] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
@couchand I need help understanding this issue.

**Comment by couchand** [comment]
Here's my understanding, but I'd check with others to make sure this is accurate and complete.

A range's raft log needs to be maintained for all operations that haven't yet been applied to all replicas.  Usually this is just a small delta of a few commands, but if a range is underreplicated for a while or there's network connectivity issues it can grow unbounded.  As the log gets longer, it causes problems in a few ways, for example, it takes longer to transmit the log between nodes, and it takes longer for a node to catch up.  We've seen some pathological cases where a raft log grows so long that once full replication/connectivity is restored the nodes are unable to keep up with the rate of new commands being added, so we fail to make any progress cleaning it up.

**Comment by Amruta-Ranade** [comment]
As per discussion with @couchand, this issue pertains to the debug pages and we don't document them yet. Moving it to 2.2 for now.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
