### ISSUE TITLE
ui: encryption stats on stores report

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3653]
PR: https://github.com/cockroachdb/cockroach/pull/26890

From release notes:
> The **Stores** report now shows encryption statistics. [#26890][#26890] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Not sure if/how to document this. Might be more for admin ui reference docs, @Amruta-Ranade, not sure.

**Comment by mberhault** [comment]
Already on the encryption page. Not sure we need more than that for now.
