### ISSUE TITLE
cli: ensure user set --password can also modify the password

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3657]
PR: https://github.com/cockroachdb/cockroach/pull/28197

From release notes:
> The [`cockroach user set --password`](../v2.1/create-and-manage-users.html) command can now change the password of existing users. [#28197][#28197] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
@knz I think the intended behavior is already documented: https://www.cockroachlabs.com/docs/dev/create-and-manage-users.html#update-a-users-password

I tested the doc and it works fine.

**Comment by knz** [comment]
cool
