### ISSUE TITLE
cli,deps: bump go-libedit to fix bugs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3658]
PR: https://github.com/cockroachdb/cockroach/pull/28233

From release notes:
> The commands are now properly able to customize the prompt with `~/.editrc` on Linux. [#28233][#28233] {% comment %}doc{% endcomment %}
>
> The commands once again support copy-pasting special unicode character from other documents. [#28233][#28233] {% comment %}doc{% endcomment %}

**Comment by knz** [comment]
These are bug fixes and do not expose new functionality to users.
