### ISSUE TITLE
server: don't drain when decommissioning

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3660]
PR: https://github.com/cockroachdb/cockroach/pull/28707

From release notes:
> [Decommissioning multiple nodes](../v2.1/remove-nodes.html) is now possible without posing a risk to cluster health. Recommissioning a node no longer requires a restart of the target node to take effect. [#28707][#28707] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
@tschottdorf On testing the recommissioning process, I still get the message "The affected nodes must be restarted for the change to take effect." Why is that? 🤔 

Follow-up observation: Recommissioning the node is moving it from the decommissioned nodes list to the dead nodes list on the UI. (I tried it on several nodes). 😳

**Comment by tschottdorf** [comment]
Thanks @Amruta-Ranade. The instructions are outdated (on release-2.1 and on master), I sent [a PR](https://github.com/cockroachdb/cockroach/pull/30867).

> Follow-up observation: Recommissioning the node is moving it from the decommissioned nodes list to the dead nodes list on the UI. (I tried it on several nodes). 😳

I assume you've recommissioned a node that wasn't running, right? That would move it to the dead nodes list. If the recommissioned node was running, you'd expect to see it under live nodes. Is that not what you're seeing?

**Comment by Amruta-Ranade** [comment]
As discussed on Slack, users do need to restart the node after recommissioning the node. Since the doc flow represents exactly that, the `Recommissioning nodes` section should remain unchanged.
