### ISSUE TITLE
Create "Get Started with CockroachDB Enterprise"

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#3667]
After users sign up for CockroachDB enterprise, we should have a document that walks them through the things they need to do:

1. Download CockroachDB
2. Activate license
3. Get pointers on using enterprise features like geo-partitioning and `BACKUP`.

@jseldess Since this is just a concatenation of existing content, should be simple. Glad to take it on after getting any feedback y'all have.

**Comment by jseldess** [comment]
SGTM. Is this a page that we would link users to from an email they receive after submitting a form?

Can you also think about how http://www.cockroachlabs.com/docs/v2.1/enterprise-licensing.html ties into this (or whether it just gets replaced)?

**Comment by Amruta-Ranade** [comment]
IMO, we could update the enterprise licensing page with the content @sploiselle outlined.

**Comment by sploiselle** [comment]
@jseldess Yep––it would be a CTA link in an email users receive along with their license.

@Amruta-Ranade My only apprehension with that suggestion is that the document currently serves two "functions"––both enterprise and trial licenses. I could certainly amend the content to fit both, but I was hoping for something that formed an experience that's contiguous with the email, so would want to keep them separate.

So, my proposal would be to just add a link between them:
- The new doc could have a link that talks about "To manage your license, see..."
- The existing doc could have a link that says, "To get started with your trial license, see..."

#### Sidebar
From a high-level view is that we could improve this documentation set my having one document that maps to each user intent––so splitting things out a whole lot, e.g. "Add an Enterprise License to Your Cluster" and "Renew Your Enterprise License."  I don't think it's worth taking on that work to add a single page, but that would make things easier.

**Comment by Amruta-Ranade** [comment]
But a trial license is still an enterprise license. So the things you outlined: download CRDB, activate license, try out enterprise features - all apply to the for trial license as well. Right? 🤔

**Comment by sploiselle** [comment]
But not all enterprise licenses are trial licenses, and I'm trying to write something targeted specifically to trial license users. That is to say that I wouldn't want enterprise users to be confused by any mention of the term trial in the doc.

**Comment by Amruta-Ranade** [comment]
Got it. In that case, SGTM.
