### ISSUE TITLE
Aggregate expressions in a subquery referring to the outer query

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3679]
PR: https://github.com/cockroachdb/cockroach/pull/28774
Issue: https://github.com/cockroachdb/cockroach/issues/12703

From related [Postgres docs](https://www.postgresql.org/docs/9.4/static/sql-expressions.html): 
> When an aggregate expression appears in a subquery (see Section 4.2.11 and Section 9.22), the aggregate is normally evaluated over the rows of the subquery. But an exception occurs if the aggregate's arguments (and filter_clause if any) contain only outer-level variables: the aggregate then belongs to the nearest such outer level, and is evaluated over the rows of that query. The aggregate expression as a whole is then an outer reference for the subquery it appears in, and acts as a constant over any one evaluation of that subquery. The restriction about appearing only in the result list or HAVING clause applies with respect to the query level that the aggregate belongs to.

cc: @andreimatei, @rytaft, @knz

**Comment by knz** [comment]
I don't think this can be documented easily.

I also think (separately) this is a rather esoteric feature which does not need to be documented right away in 2.1.

**Comment by jseldess** [comment]
Thanks, @knz. Should we move this to `Later` or close altogether?

**Comment by andreimatei** [comment]
Would it be appropriate to give a nod to it and point to the postgres docs?

**Comment by knz** [comment]
Let's do later with indeed a ref to the pg docs.

Documenting aggregations exhaustively is a rather complicated enterprise.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
