### ISSUE TITLE
Improve search UX across docs versions

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3683]
There should be some way to find encryption at rest alpha documentation. This does not return meaningful results: https://www.cockroachlabs.com/docs/search.html?q=encryption+at+rest should return a link to this: https://www.cockroachlabs.com/docs/dev/encryption.html

**Comment by jseldess** [comment]
@j-low, this seems tied to one of the current search limitations, that you can't search across version, or even know which version of the docs you're searching. 

Google, on the other hand, does exactly the right thing. If you're searching for a term that only matches a page in the 2.1 docs, that's the first result:

search: `site: www.cockroachlabs.com encryption at rest`
https://www.google.com/search?source=hp&ei=_L6LW6zlOeKQggeCk4aQCg&q=site%3Awww.cockroachlabs.com+encryption+at+rest&btnK=Google+Search&oq=site%3Awww.cockroachlabs.com+encryption+at+rest&gs_l=psy-ab.3...1434.15387..15561...6.0..0.125.2715.47j1......0....1..gws-wiz.....0..0j0i131j0i10.JBpFaNGg_gI

If you're searching for a term that matches a page in 2.0, which has the canonical reference, that gets the result:

search: `site:www.cockroachlabs.com partitioning`
https://www.google.com/search?ei=Db-LW6_7Bae7ggekpJ_QCg&q=site%3Awww.cockroachlabs.com+partitioning&oq=site%3Awww.cockroachlabs.com+partitioning&gs_l=psy-ab.3...8737.11473..11757...0.0..0.96.682.12......0....1..gws-wiz.7fb0qD2J1Vg

If we can't get Algolia to do the right thing, we may want to reconsider just redirecting to google.

**Comment by jseldess** [comment]
This is still a problem and should be part of our search refactor, @lhirata. Currently, you have to be looking at our dev docs (19.2 currently) to get those pages to return in the results. 

Ideally, search would prioritize the stable version but also include results from dev when necessary.

**Comment by jseldess** [comment]
This has been resolved with our upgraded algolia plan. We now search the stable version but also return relevant results from the dev version.
