### ISSUE TITLE
schema changes: confusion in transactional schema changes

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/docs#3684]
In https://www.cockroachlabs.com/docs/stable/known-limitations.html#schema-changes-within-transactions

It says:
> DDL statements cannot follow DML statements. As a workaround, arrange DML statements before DDL statements, or split the statements into separate transactions.

This seems to be a contradiction. Should it read "as a workaround, arrange DML statements _after_ DDL statements" ..?

I'd submit a PR to fix it, but am unsure as to which direction the fix needs to be applied! Which comes first - the chicken or the DDL transaction?

**Comment by vivekmenezes** [comment]
we want to say DML statements follow DDL statements, or that schema changes need to be the first statements in a transaction that are modifying the database.

**Comment by jseldess** [comment]
@rmloveland, since this ties into recent schema change docs you've written, would you mind making this correction?
