### ISSUE TITLE
Include secure examples in 2.0 docs.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#3685]
2.0 docs are still the default making those examples hard to find for people (see https://github.com/cockroachdb/cockroach/issues/29463).
Since the secure examples are not specific to a CockroachDB version, we should include them in the 2.0 docs.

**Comment by jseldess** [comment]
Good point, @mberhault. 

@rmloveland, is this something you can squeeze in this week?

**Comment by rmloveland** [comment]
> @rmloveland, is this something you can squeeze in this week?

Yep, can do @jseldess - thanks for reporting this @mberhault
