### ISSUE TITLE
SET CLUSTER SETTING inside a transaction

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3689]
PR: https://github.com/cockroachdb/cockroach/pull/29082

From release notes:
> The [`SET CLUSTER SETTING`](../v2.1/set-cluster-setting.html) statement can no longer be used inside a [transaction](../v2.1/transactions.html). It also now attempts to wait until the change has been gossiped before allowing subsequent statements. [#29082][#29082] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
No docs update needed
