### ISSUE TITLE
ALTER TABLE ... SPLIT AT and merge queue

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3690]
PR: https://github.com/cockroachdb/cockroach/pull/29082

From release notes:
> The [`ALTER TABLE ... SPLIT AT`](../v2.1/split-at.html) statement now produces an error if executed while the merge queue is enabled, as the merge queue is likely to immediately discard any splits created by the statement. [#29082][#29082] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Don't think docs are needed.
