### ISSUE TITLE
release-2.1: cli: miscellaneous fixes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3691]
PR: https://github.com/cockroachdb/cockroach/pull/29160

From release notes:
> The [`cockroach start`](../v2.1/start-a-node.html) command now emits the PID of the server process to the file specified by the `--pid-file` flag as soon as it is ready to accept network connections but possibly before it is done bootstrapping (i.e., before [`cockroach init`](../v2.1/initialize-a-cluster.html) completes). To wait for SQL readiness, use the `--listen-url-file` flag instead. [#29160][#29160] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Docs have already been updated.
