### ISSUE TITLE
Update Java secure cluster docs: some users need `sslfactory=org.postgresql.ssl.jdbc4.LibPQFactory`

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3696]
It's not clear in exactly which scenarios this is the case.  For example, when developing the examples in the [existing documentation](https://www.cockroachlabs.com/docs/dev/build-a-java-app-with-cockroachdb.html), I did not need to pass that parameter in order to connect to a secure cluster.  However, according to [this issue](https://github.com/cockroachdb/cockroach/issues/29463) a user had to pass the param, so we should at least add a note that the parameter may need to be specified. (Ideally we will learn **why** this is necessary before cargo-culting it into the page :-} )

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
