### ISSUE TITLE
Update `data replication` guide for latest stable version.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/docs#3699]
The guide expects all ranges across the entire cluster to end up with a replication factor of 5. However, 2.0.5 has three predefined zone configs: `.liveness`, `.meta`, and `system.jobs`.

Changing the `.default` config will not modify the ranges using those custom configs and some ranges will still only be replicated three times. This is confusing as the guide currently shows all ranges replicated 5 times.

**Comment by jseldess** [comment]
Thanks, @mberhault. We made this update in a few places but missed this doc. Did you find this yourself, or is it coming from a support channel?

**Comment by mberhault** [comment]
This came in from gitter, someone thought there was something wrong because the behavior did not match the docs.

**Comment by dvaldivia** [comment]
The resulting replication of each node is different on each node, more over the first 3 nodes which had the same replicas (22) becase 21 and 20 when the 4th and 5th node came online

<img width="1552" alt="screen shot 2018-09-05 at 9 27 46 am" src="https://user-images.githubusercontent.com/18384552/45103904-81261480-b0f6-11e8-99f1-089b90e7d269.png">
