### ISSUE TITLE
Finish secure "build an app" examples

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3700]
Most "Build an app" pages were updated to show how to connect to secure clusters in #2943.

Scope of work for this ticket is to update the "Build an app" pages for the remaining languages:

- [x] C#
- [x] C++
- [x] Clojure
- [x] Rust

**Comment by mberhault** [comment]
CC: @tim-o in case this shows up (hasn't yet)

FYI: C# requires SSL keys and certificates to be bundled together in PKCS#12 format.

```
openssl pkcs12 -export -password "pass:" -in client.root.crt -inkey client.root.key -out client.root.pk12
```
You can find sample secure code for C# at: https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/testdata/csharp/Program.cs

**Comment by rolandcrosby** [comment]
Note for when we pick this up: For C# with npgsql, it's not obvious how to properly validate a server certificate against a CA certificate, as we typically advise. According to [npgsql's documentation](https://www.npgsql.org/doc/security.html#encryption-ssltls), if you're not using the system certificate store, you need to write your own callback to validate the server certificate against the CA certificate. I did a little searching but didn't find a code sample anywhere that does this specifically - most of the examples I found instead just checked the server certificate's fingerprint against a hard-coded value.

So, when we update the C# example, we should be sure to provide a UserCertificateValidationCallback on the NpgsqlConnection to perform the same validation that we do in our other secure examples.

**Comment by rolandcrosby** [comment]
Based on Bram's updated examples I got the secure C# examples working; they're in [this commit](https://github.com/rolandcrosby/docs/commit/a6c4420254a39669cee33f0878f8cfcd974419cc). The text of the documentation page will need to be updated to split the page into secure and insecure examples like we do in other languages. Also, we will need to provide instructions on how to generate a combined client certificate and private key in PKCS#12 format as required by the .Net commands (instructions are in a comment in both of the secure examples).

**Comment by jseldess** [comment]
@rmloveland, customers are asking for docs on using C# with a secure cluster. With @BramGruneir's [long-open PR](https://github.com/cockroachdb/docs/pull/1991) and @rolandcrosby's code (see commit link from comment above), we probably have what we need to get this published. Do you think you can spend a few hours on this before the end of the year?

**Comment by rmloveland** [comment]
Quoth @jseldess 

> Do you think you can spend a few hours on this before the end of the year?

Yes definitely - thanks Roland and Bram!

**Comment by jseldess** [comment]
This isn't going to get done for 19.1. Moving to 19.2 for re-prioritization.

**Comment by jseldess** [comment]
@ericharmeling, this is your next starter project.
