### ISSUE TITLE
Add example featuring negative constraints in replication zones

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3708]
We mention negative constraints [here](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#types-of-constraints}, but we should add an example or two.

cc @robert-s-lee

**Comment by rmloveland** [comment]
We now have at least a few examples on the [replication zones page](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html):

1. An example showing a negative/prohibited zone config in the [Types of constraints](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#types-of-constraints) section:

> Define a required and prohibited definition for the same key-value pair. For example, constraints = '[-region=west, +region=west]' will result in an error.

2. There is also an example of a negative constraint in the [Scope of constraints](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#scope-of-constraints) section:

> `constraints = '[+ssd, -region=west]'`

Closing this issue, but please re-open if you disagree
