### ISSUE TITLE
Define "tuple"

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#371]
Many references to `tuples` in the [functions and operators doc](https://www.cockroachlabs.com/docs/functions-and-operators.html), but tuples themselves don't have their own doc and don't appear to be defined anywhere.

Once I looked up what they were, I realized I knew them by sight but not by name, but having a reference doc doesn't hurt.
- **PostgreSQL** only has a few mailer questions post ([1](https://www.postgresql.org/message-id/C05E7DA1218ED411BF8A00105AC95A8E0599DE96@sv-cntrmail.emis.local), [2](https://www.postgresql.org/message-id/20020628092449.B28070@metalico.drauku.net)).
- **MSDN** has [incomprehensible developer gunk](https://msdn.microsoft.com/en-us/library/ff487118.aspx), which might or might not be proprietary to SQL Server 2016.
- **MySQL** doesn't have anything official showing up on Google pg 1.

However, [simple explanations exist](http://stackoverflow.com/questions/751264/what-does-the-term-tuple-mean-in-relational-databases) and CockroachDB could offer something great to its users.

**Comment by knz** [comment]
I would gladly volunteer to look at this during a docs fixit day.

**Comment by knz** [comment]
Note: the "simple explanation" given as first answer on http://stackoverflow.com/questions/751264/what-does-the-term-tuple-mean-in-relational-databases is actually plainly wrong and inapplicable to cockroachdb.

**Comment by sploiselle** [comment]
No one else has been confused by this, seemingly. Going to close this issue.
