### ISSUE TITLE
sql basics: confusion in transactions example

### ISSUE THREAD

**Issue by changangela** [cockroachdb/docs#3711]
In https://www.cockroachlabs.com/docs/dev/training/sql-basics.html, in the Transactions section, we have:

`
SELECT balance >= 250 FROM bank.accounts WHERE type = 'checking' AND customer_id = 2;
UPDATE bank.accounts SET balance = balance - 250 WHERE type = 'savings' AND customer_id = 2;
`

This seems to not work as expected since we are checking that the "checking" account has over 250, but we're withdrawing from the "savings" account, instead of withdrawing from the account that is being checked.

**Comment by jseldess** [comment]
Thanks, @changangela. 

@lhirata, assigning to you, since this is fresh in your mind.
