### ISSUE TITLE
release-2.1: security: relax checks on certificate fields.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3726]
PR: https://github.com/cockroachdb/cockroach/pull/29223

From release notes:
> CockroachDB no longer checks key usage attributes in [security certificates](../v2.1/create-security-certificates.html). [#29223][#29223] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Can delete this note though:
"Note:
The keyUsage and extendedkeyUsage parameters are vital for CockroachDB functions. You can modify or omit other parameters as per your preferred OpenSSL configuration, but do not omit the keyUsage and extendedkeyUsage parameters."
