### ISSUE TITLE
release-2.1: distsqlrun: bump MinAcceptedVersion to 21

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3727]
PR: https://github.com/cockroachdb/cockroach/pull/29168

From release notes:
> In a mixed-version cluster, nodes running v2.0 no longer schedule distributed SQL work on nodes running v2.1. [#29168][#29168] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Closing this issue - I don't think any docs need to be updated.
