### ISSUE TITLE
backport-2.1: sql: fix two bugs with TRUNCATE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3728]
PR: https://github.com/cockroachdb/cockroach/pull/29262

From release notes:
> When [`TRUNCATE`](../v2.1/truncate.html) or [`DROP TABLE`](../v2.1/drop-table.html) is run while a [schema change](../v2.1/online-schema-changes.html) like `CREATE INDEX` is being processed, the schema change job no longer runs indefinitely. [#29262][#29262] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
No docs needed
