### ISSUE TITLE
release-2.1: cli: periodically flush csv/tsv output

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3729]
PR: https://github.com/cockroachdb/cockroach/pull/29445

From release notes:
> The `csv` and `tsv` formats for `cockroach` commands that output result rows now buffer data for a maximum of 5 seconds. This makes it possible to, for example, view SQL [`CHANGEFEED`s](../v2.1/create-changefeed.html) interactively with [`cockroach sql`](../v2.1/use-the-built-in-sql-client.html) and [`cockroach demo`](../v2.1/cockroach-demo.html). [#29445][#29445] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
No docs updates needed.
