### ISSUE TITLE
Follow up: Subqueries

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#3732]
Add content about what subqueries are/are not supported.

Related to #2976.

**Comment by lhirata** [comment]
Circling back around to this issue:

I'm adding a note (in #3784) to the Subqueries and Cost-Based Optimizer pages that says something along the lines of "Some correlated subqueries are partially supported by the CBO but full support will come with a later release. If you run into an unsupported query, please file an issue." 

@knz, do you still have bandwidth to add a write up about what subqueries are / aren't supported (this would be added to [Subqueries > Correlated Subqueries page](https://www.cockroachlabs.com/docs/dev/subqueries#correlated-subqueries))? I briefly chatted with @awoods187 and he thinks it is still valuable, but not super high priority since this will probably be addressed in 2.2.

**Comment by knz** [comment]
done: #3926
