### ISSUE TITLE
Clarify guidance on replication .meta and .liveness

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3736]
In our [production checklist](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#basic-topology-recommendations), we now suggest replication pre-configured replication zones for system ranges 5 ways for cluster of 5 or more nodes:

> When running a cluster of 5 nodes or more, it's safest to increase the replication factor for important internal data to 5, even if you don't do so for user data. For the cluster as a whole to remain available, the ranges for this internal data must always retain a majority of their replicas.

But in the [replication zones doc](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#create-a-replication-zone-for-a-system-range), we say:

For `.meta`:
> If your cluster is running in multiple datacenters, it's a best practice to configure the meta ranges to have a copy in each datacenter.

For`.liveness`:
> If this range is unavailable, the entire cluster will be unavailable, so giving it a high replication factor is strongly recommended.

We need to find a consistent recommendation.

cc @a-robinson, @bdarnell, for thoughts.

**Comment by bdarnell** [comment]
In version 2.1, we should recommend a replication factor of 5 for these ranges in all cases (and this will be the default for clusters created by 2.1, so users won't have to do anything unless they're upgrading from older versions). I wouldn't recommend going higher than that, and 2.1 will adjust automatically in case there are fewer than 5 nodes in the cluster.

**Comment by jseldess** [comment]
Thanks, @bdarnell. Just want to be sure: A new 2.1 cluster will always have a replication factor of 5 for these ranges, even if there are less than 5 nodes? How does that work?

**Comment by bdarnell** [comment]
The same way it works with the default replication factor of 3 when you only have one node. The change is just that we don't complain about them as underreplicated in this case.

**Comment by jseldess** [comment]
OK, thanks.

**Comment by a-robinson** [comment]
Agreed. I'd just add that the old `.meta` recommendation is still reasonable if you're running with more than 5 datacenters. The old `.liveness` recommendation can definitely be removed, though.

**Comment by bdarnell** [comment]
I'm not sure that the old `.meta` recommendation makes sense now that we no longer use inconsistent (follower) reads. Range lookups will still have to go to the leader, so there's little value in having additional local replicas (but one day we'll use follower reads, and there will be).

**Comment by jseldess** [comment]
Related to https://github.com/cockroachdb/docs/issues/3840.

**Comment by jseldess** [comment]
Important internal ranges are replicated 5x now by default, and docs have been updated in the meantime.
