### ISSUE TITLE
Document why you don't need SELECT FOR UPDATE in CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3741]
Oracle docs: https://docs.oracle.com/cd/E17952_01/mysql-5.1-en/innodb-locking-reads.html
Postgres docs: https://www.postgresql.org/docs/9.0/static/sql-select.html#SQL-FOR-UPDATE-SHARE

In summary, in Oracle and Postgres, when you're doing a read and then an update on a row in a transaction, you need to use `SELECT FOR UPDATE` because the "regular `SELECT` statement does not give enough protection" (from the Oracle docs).

In CockroachDB, our default `SERIALIZABLE` isolation level makes this a moot point. 

To do:
- Add an FAQ on this.
- Add `SELECT FOR UPDATE` as an extension on https://www.cockroachlabs.com/docs/stable/sql-feature-support.html.
- Think of other places to call this out.

cc: @rolandcrosby, @awoods187

**Comment by cbetti** [comment]
I don't follow the premise. Does SERIALIZABLE in cockroachdb work fundamentally differently that in PostgreSQL? How does cockroach know which record is going to be selected a-priori?

**Comment by rmloveland** [comment]
@ericharmeling this is SQL (hence your domain), but I think we can close this based on the fact that we're doing #6000.  Please re-open if you disagree or if I am missing something.
