### ISSUE TITLE
Clarify that IMPORT doesn't work for existing tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3742]
This question/confusion comes up somewhat frequently, so we should find ways to make it clearer in the import-related docs.

For example, see https://forum.cockroachlabs.com/t/import-csv-data-only-to-an-existing-table/2006/2.

**Comment by rmloveland** [comment]
Fixed by  #3766

Note is at the top of the [IMPORT page](https://www.cockroachlabs.com/docs/v2.1/import.html)

(PS @Amruta-Ranade please feel free to re-open if you disagree.)
