### ISSUE TITLE
Explicitly document the certificate formats required by CockroachDB

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#3747]
Our docs about secure clusters push users toward creating a new certificate authority and using that CA to issue client and node certificates. This works fine, and it lowers the barrier to entry of setting up a new cluster, but as far as I can tell our docs don't ever explain how to use CockroachDB with certificates issued by an existing enterprise certificate authority.

Somewhere in the deployment documentation, we should explicitly list the types and formats of certificates and keys needed by nodes and clients, along with details of how the certificate's data fields need to be filled out. We should also update documents like the [Production Checklist](https://www.cockroachlabs.com/docs/dev/recommended-production-settings.html) to acknowledge that integrating with existing certificate infrastructure is possible and supported.

**Comment by jseldess** [comment]
As mentioned in Slack, I think this a great request. One likely docs project for 2.2 is providing an overview and better explanation of our security offerings (encryption, authentication, access control). See #3549. Perhaps we could expand to include certificate formats, if that would unblock customers from doing things we don’t directly document. I think we’d need to leverage @marc or @ben perspectives as well.

**Comment by Amruta-Ranade** [comment]
@rolandcrosby Now that we have merged the security doc updates, can I close this issue?

**Comment by rolandcrosby** [comment]
Yes, this is taken care of by your security doc updates. Thanks!
