### ISSUE TITLE
Update docs on automatic retries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#3748]
Re: [Transactions](https://cockroachlabs.com/docs//v2.1/transactions.html)

> CockroachDB automatically retries individual statements and transactions sent from the client as a single batch.

This is incomplete (which makes it not true). Regardless of how things things are sent, we only ever do automatic retries is the results fit in a 16KiB buffer. Once that overflows, we start streaming results to the client and we forfeit the option of doing automatic retries. Which is really bad is someone relies on this statement being always true, as a client did.

**Comment by andreimatei** [comment]
I think the statement might have been true up to some point (1.0 or 1.1) but definitely incomplete in 2.0.

**Comment by awoods187** [comment]
More info on transaction docs updates needed can be found on the H... slack channel

**Comment by andreimatei** [comment]
Note to self: There might be a special case about selects using a unique index and returning a single value - I think they should be retried automatically regardless of the (single) returned row size.

**Comment by jseldess** [comment]
@sploiselle, you'll probably end up covering this when you redo our transactions docs in 2.2.

**Comment by andreimatei** [comment]
Friendly ping on this - it is a red hot P0 issue; it's really bad. It has bit *several* people that I know of.
I keep wanting to do something about it myself but I can't seem to get around to it.

**Comment by jseldess** [comment]
Thanks, @andreimatei.

@sploiselle, given that this issue is pretty specific, you could probably take a swing at it before or separate from the larger distribution transactions project. Thoughts?

**Comment by sploiselle** [comment]
Will start work on it this week. @andreimatei look for a calendar invite!

**Comment by andreimatei** [comment]
I started pulling on some threads here this morning, and I now have more state on this than I'd like. I think there's some good code changes I want to do around this.
I'll take care of the docs, and then hopefully I can update them further with better guarantees in the near future. I'm taking this over; should have done that from the get go instead of lamenting.
