### ISSUE TITLE
Document changefeed high-water timestamps

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/docs#3752]
Changefeeds are currently shown to users as jobs like backup/restore/import, but changefeed progress is different. Those other kinds of jobs can show an estimated percent completion, but that doesn't make sense with changefeeds, which run forever. (It's a ux wart that we show changefeeds as jobs, but this will unfortunately not be fixed in 2.1)

Changefeed progress is exposed to the user as a "high-water timestamp" which advances as the changefeed makes progress. This is a guarantee that all changes below or at that timestamp have been emitted and shows up in the jobs page of the admin ui as well as in `crdb_internal.jobs`.

Dunno if we want to shoehorn this into #3669 or do it as a followup, but it should ideally be done for 2.1

**Comment by danhhz** [comment]
Oh, we should make sure to tie this back into the `WITH cursor=<timestamp>` option because that option exists to allow a user to pick up from where another changefeed left off, and "where another changefeed left off" is this high-water timestamp.

**Comment by lhirata** [comment]
Thanks for filing the issue! I'll add this to #3669.
