### ISSUE TITLE
Admin UI: Contextual guidance

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3753]
- [ ] A page that poses user questions and where/how to use Admin UI to answer. We can probably repurpose the `Deploy > Monitoring and Alerting > Use the Admin UI`.
- [ ] Integrate these use questions/answers into Admin UI reference docs.

**Comment by Amruta-Ranade** [comment]
Note to self: Once I have the mapping prototype, I should ask Roko and Sales Engg for feedback. (Context: Roko's YCSB presentation)

**Comment by Amruta-Ranade** [comment]
Random thought: There isn't gonna be one-to-one mapping of user stories to UI graphs. 
Possible solution: Update three docs: 
- Use the Admin UI: Selector-sections for each graph/dashboard/debug page > all possible user stories.
- Troubleshooting using the Admin UI: User stories > all possible graphs
- Individual graph/dashboard/debug pages > Intro para = context using user stories.

**Comment by Amruta-Ranade** [comment]
Note to self: I should also explain how we calculate each metric. 
For context: https://github.com/cockroachdb/docs/pull/3744#issuecomment-422473094
https://github.com/cockroachdb/docs/pull/3744#issuecomment-422467752

**Comment by Amruta-Ranade** [comment]
Discussion with Andrew: Start with the custom debug chart doc and propagate the info you get to other pages.
PR for context: https://github.com/cockroachdb/docs/pull/3022

**Comment by Amruta-Ranade** [comment]
For Reference:

Solarwinds:
https://www.solarwinds.com/topics/multi-dimensional-database-performance-analysis
https://database.demo.solarwinds.com/iwc/main.iwc

From the interactive demo:
<img width="1213" alt="screen shot 2018-09-20 at 2 54 49 pm" src="https://user-images.githubusercontent.com/11484018/45840534-2b03c480-bce5-11e8-86cc-1f8f8deb327d.png">

AWS EC2:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring_ec2.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring_get_statistics.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/GetSingleMetricAllDimensions.html

GCP:
https://cloud.google.com/monitoring/api/v3/metrics
https://cloud.google.com/monitoring/api/metrics_gcp

**Comment by Amruta-Ranade** [comment]
For phase 1, focus on:
- Cluster Overview
- Hardware dashboard
- Statements + Statement Details Page
- Latency
- Data distribution matrix

**Comment by Amruta-Ranade** [comment]
https://cloud.google.com/spanner/docs/query-statistics

**Comment by Amruta-Ranade** [comment]
Also look at https://forum.cockroachlabs.com/t/metrics-dashboard-graph-docs/2295/4

**Comment by Amruta-Ranade** [comment]
Follow-up project: Document debug pages (Problem Ranges, Network Latency, Data dist and zone configs). Probably as tutorials instead of reference docs.

**Comment by jseldess** [comment]
@Amruta-Ranade, does it make sense to leave this open, or should we rather close in favor of specific issues prioritized in the future?

**Comment by Amruta-Ranade** [comment]
Closing in favor of specific issues SGTM!
