### ISSUE TITLE
release-2.1: ui: design updates to the Statements pages

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3759]
PR: https://github.com/cockroachdb/cockroach/pull/30115

From release notes:
> Various improvements to the [**Statements**](../v2.1/admin-ui-statements-page.html) pages. [#30115][#30115] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3886
