### ISSUE TITLE
Follow-up: UI User auth 

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#3765]
Need to propagate UI user auth changes to other docs.

**Comment by piyush-singh** [comment]
Adding a note per @Amruta-Ranade's suggestion: we should should include a small section in our documentation around troubleshooting Authentication. This is particularly helpful in the case when a cluster has an outage on nodes that persist login information which will result in a timeout for all login requests. Web UI Auth sessions are persisted in a system range, and if that range loses quorum, users will be locked out of the entire cluster's UI. There might be other issues that could result in a timeout, might be worth following up with Andrew or Pete for further details.

**Comment by Amruta-Ranade** [comment]
Discussion with Jesse: For tutorials and training docs: Add a note for each secure cluster instances saying "create a user and password and then point browser to the admin UI"
