### ISSUE TITLE
Cluster failed to initialize within 300 seconds.

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#3768]
Following the [Orchestrate CockroachDB with Kubernetes](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#gce-manual) and trying to deploy CockroachDB using the Manual GCE I have run into a few problems in the initial set up.  

1) When you create a new VM on gcloud the command on their docs isn't clear that you should also set the scopes.  

2) Their docs are also unclear that you need to install python on the newly created VM in order to run the `kube-up.sh` script.  

3) Even after setting the correct scopes and installing python, I am still unable to bring up the cluster in the manual way.  Not sure if there is something I'm doing wrong but I have not been able to find an answer to this in our docs or theirs.

**Comment by jseldess** [comment]
Thanks, @roncrdb. Can you point out where in their docs you'd expect guidance for 1 and 2? This is the page we link to from our docs: https://kubernetes.io/docs/setup/turnkey/gce/.

If there's a place in there docs where you think these instructions should have been, I can open a PR to update their docs, since they're open source.

**Comment by roncrdb** [comment]
@jseldess  

Not sure as to where we could add them, perhaps just as a note before the link to the Kubernetes docs.

**Comment by jseldess** [comment]
Ah, I meant where in Kubernetes' own docs would you have expected to get these instructions/tips?

**Comment by roncrdb** [comment]
@jseldess, ohh I see, I was would have expected it to in the Before you begin/Prerequisites section.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
