### ISSUE TITLE
backport-2.1: cdc: Retry on certain sink failures

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3776]
PR: https://github.com/cockroachdb/cockroach/pull/30157

From release notes:
> [`CHANGEFEED`s](../v2.1/change-data-capture.html) will retry, rather than abort, in certain cases when failing to emit to a sink. [#30157][#30157] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
No doc updates needed
