### ISSUE TITLE
backport-2.1: paralellize queue uses distsql; add '2.0' setting for distsql

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3778]
PR: https://github.com/cockroachdb/cockroach/pull/30209

From release notes:
> Added the `2.0` value for both the `distsql` [session setting](../v2.1/set-vars.html) and the `sql.defaults.distsql` [cluster setting](../v2.1/cluster-settings.html), which instructs the database to use the 2.0 `auto` behavior for determining whether queries are distributed or run through the gateway node. [#30209][#30209] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Discussed this with @jordanlewis last week and decided that we wouldn't document the `2.0` values since they are mainly for internal use and will be eventually deprecated. Closing the issue!
