### ISSUE TITLE
release-2.1: server: include saved profiles in debug zip

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3780]
PR: https://github.com/cockroachdb/cockroach/pull/30281

From release notes:
> The [`cockroach debug zip`](../v2.1/debug-zip.html) command now also collects heap profiles that were generated and stored when there was high memory usage [#30281][#30281] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @ridwanmsharif, the heap profiles content was already added in the 2.0 docs. The new change is more of an implementation enhancement primarily for CRDB engineers with no major user impact. Hence the change doesn't warrant a doc update. Closing the issue.
