### ISSUE TITLE
Hibernate doesn't work with Java 10; mention this in build an app with java 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#3782]
https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb-hibernate.html#insecure

If you have Java 10 this example will not work because Hibernate will not work (its relying on a package removed in Java 10).

cc @knz

**Comment by knz** [comment]
This is what fails:

```
> Task :run FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
       at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43)
       at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87)
       at org.hibernate.cfg.Configuration.<init>(Configuration.java:123)
       at org.hibernate.cfg.Configuration.<init>(Configuration.java:118)
       at com.cockroachlabs.Sample.<clinit>(Sample.java:16)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
       at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
       ... 5 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

**Comment by knz** [comment]
Relevant SO thread:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

Maybe relevant:
https://stackoverflow.com/questions/48986999/classnotfoundexception-for-javax-xml-bind-jaxbexception-with-spring-boot-when-sw

**Comment by rmloveland** [comment]
@awoods187 we do say on that page that

> The examples on this page assume you are using a Java version <= 9. They do not work with Java 10. 

But do you mean specifically that we should mention Hibernate's compatibility (or not) with Java 10 as well?

**Comment by knz** [comment]
I think given that macOS now comes with java 10 by default we need to tell users what to do to have a successful experience.

**Comment by vy-ton** [comment]
fyi, I hit this recently and was able to build by adding the dependencies myself. However, the code sample itself still does not run for reasons I have yet to figure out.

**Comment by ericharmeling** [comment]
I just ran https://raw.githubusercontent.com/cockroachdb/docs/master/_includes/v20.1/app/hibernate-basic-sample/Sample.java with Java versions 8-14 and Hibernate 5.4.19, and I didn't run into any problems in any of those versions.

Has this since been resolved? I see nothing on the Hibernate website that suggests that it is incompatible with Java 10 (maybe I haven't looked hard enough?).

**Comment by vy-ton** [comment]
Hmm I hit the issue Raphael reported. Did you already have those missing dependencies in your `build.gradle`? I also can't get the code sample to connect to CRDB in secure mode with `openjdk 14.0.2` but was able to connect on Java 8

**Comment by ericharmeling** [comment]
Here are the `dependencies` in my `gradle.build` file:

```
dependencies {
    implementation 'org.hibernate:hibernate-core:5.4.19.Final'
    implementation 'org.postgresql:postgresql:42.2.14'
}
```

Also, in my `hibernate.cfg.xml` file, I have this property set, to use the CockroachDB dialect:
```
        <property name="dialect">org.hibernate.dialect.CockroachDB201Dialect</property>
```

**Comment by vy-ton** [comment]
Not sure what's going on, but I just reran this as well with openjdk 14 and didn't see the same error.

I'm good to close. Maybe @rafiss could do a last sanity check?

**Comment by rafiss** [comment]
Confirmed, it should be working. Hibernate included the required dependencies in their build. See https://github.com/hibernate/hibernate-orm/commit/51ab9f744d2f040cf24000509c4f3152803568ab#diff-5e557ee691468515e39b8969fb567c2f
