### ISSUE TITLE
Determine what to do about our example code vs. Java 10+ 

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#3788]
Related: #3782 (which is narrowed to Hibernate vs. Java 10+)

Right now our examples (and some of their dependencies) don't work with Java 10's modules (and maybe other features, IDK).  It seems like this is a common issue based on a quick glance at the Googles.

We have a few options:

1. Add even more "Branchiness" to the docs to add Java 10+ samples as an option
2. Just wait longer  until Java 8 EOL (see https://www.oracle.com/technetwork/java/javase/eol-135779.html)
3. ??? (something else I can't think of)

cc @awoods187 for your opinion

**Comment by rmloveland** [comment]
Quoth @knz in the related issue (sorry for not pinging you on this one):

> I think given that macOS now comes with java 10 by default we need to tell users what to do to have a successful experience.

**Comment by awoods187** [comment]
Closing this as out of date
