### ISSUE TITLE
Supported MySQL-specific SQL syntax

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3792]
## Title

MySQL specific SQL syntax support
 
## Description

CockroachDB supports certain MySQL extension for convenience.  MySQL and other database developers looking to migrate would benefit if there these non Postgres syntax are documented.  

## Outline

The following is a small list of MySQL extension supported by CockroachDB, but if others are known, we should add them:

`use database;`
`use table;`
`IF ( <cond>, <expr1>, <expr2> ).` https://www.cockroachlabs.com/docs/v2.0/scalar-expressions.html#if-expressions

## Expected Audience

Developers and DBAs

**Comment by jseldess** [comment]
Thanks, @robert-s-lee.

@rmloveland, did we factor this type of guidance into your current migration guides, or is this a good next iteration project?

**Comment by rmloveland** [comment]
> @rmloveland, did we factor this type of guidance into your current migration guides, or is this a good next iteration project?

This info is not in the current PR - would probably have to be in the next iteration.

**Comment by rolandcrosby** [comment]
These aren't just relevant to people migrating from MySQL - we should point them out on some general overview page about our SQL syntax as well.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
