### ISSUE TITLE
Provide memory/RAM size recommendations

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#3795]
Currently, we only recommend at least 2GB of memory per node for a production instance - https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html. This doesn't take into account dataset size or any other factors. We should have some general guidelines for either, amount of memory per core, or amount of memory per data stored.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3936.
