### ISSUE TITLE
PostgreSQL DDL in CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3803]
Add a reference page detailing where Postgres DDL is and is not supported in CockroachDB.

Source by @knz: https://docs.google.com/document/d/1EYGkwAMi7PKzNS41BGA6yFQhFzL1N_q5qLbR042dMV8/edit#heading=h.hvqliffe51ag

Question:
- Does this belong in the `Reference` > `SQL` > [`SQL Feature Support`](https://www.cockroachlabs.com/docs/dev/sql-feature-support.html)?
- How can we tie this into the soon-to-be-published Migrate to MySQL guide?

cc: @rmloveland, @awoods187, @robert-s-lee

**Comment by jseldess** [comment]
@rmloveland, should we push this to 2.2, or are you able to get this down today?

**Comment by rmloveland** [comment]
@jseldess I'm working on it now, and plan to have a PR ready this week.
