### ISSUE TITLE
document caddy instruction expected behavior

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#3805]
https://www.cockroachlabs.com/docs/v2.0/create-a-file-server.html#using-caddy-as-a-file-server

## Issue Description

On osx, installed caddy binary with http.upload  plugin `curl https://getcaddy.com | bash -s personal http.upload`

1) HTTP

```
caddy -root /tmp "upload / {" 'to "/tmp"' 'yes_without_tls' "}"
Activating privacy features... done.
http://:2015
WARNING: File descriptor limit 4864 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```

pointing browser to http://localhost:2015/ returned `404 Not Found`

![screen shot 2018-10-02 at 11 42 48 am](https://user-images.githubusercontent.com/6315124/46360250-0d195680-c639-11e8-9c46-0d1bd069d5cd.png)

2) HTTPS

```
cat > /tmp/Caddyfile <<EOF
tls key cert
root "/tmp"
upload / {
to "/tmp"
}
EOF
```
```
caddy -conf /tmp/Caddyfile
Activating privacy features...

Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you agree to the terms? (y/n): y
2018/10/02 11:50:37 registration error: acme: Error 400 - urn:ietf:params:acme:error:invalidEmail - Error creating new account :: not a valid e-mail address
```

## Suggested Resolution 

Prescriptive instructions for novice caddy users to follow would be useful.

**Comment by jseldess** [comment]
@robert-s-lee, it looks like @rmloveland updated those instructions slightly for 2.1: https://www.cockroachlabs.com/docs/dev/create-a-file-server.html#using-caddy-as-a-file-server

I wonder if that extra guidance would have prevented your issue?

dt, @rmloveland, if either of you have thoughts or ideas, please chime in. If Robert ran into trouble, there's a good chance ordinary users will, too.

**Comment by rmloveland** [comment]
@jseldess I only did some copy edits for 2.1 but did not test extensively.  I suspect there is some additional guidance needed on the Caddy example(s).

Having said that, @robert-s-lee Is there a use case supported by Caddy that is not supported by the PHP, Python, Ruby, and nginx examples in [the 2.1 version of the page](https://www.cockroachlabs.com/docs/dev/create-a-file-server.html)?  (Aside: these examples should be backported to 2.0, I'll open a separate issue)

If there is not, I propose that we remove the Caddy example.  I'd like to find the right balance between "here are quick one-liners to get you going" and "here is how to configure a file server", but mostly skew towards the former.  And Caddy is a somewhat idiosyncratic (IMO) and proprietary option that I'd rather not maintain add'l docs for unless we need to.

Apologies if I'm completely missing something though!  What do y'all think?

**Comment by robert-s-lee** [comment]
No special reason I tried Caddy.  I thought it might be the simplest as the sole criteria for trying and the first example suggested.  Once it did not work, I had to dig around for docs and then quickly gave up as the solution did not seem obvious to me.

**Comment by robert-s-lee** [comment]
verified Caddy does work. For security purposes, directory listing is turned off.  `404` is expected with `browse` not enabled in the example config. exact file name must be specified which backup and restore do and work as expected.
