### ISSUE TITLE
ui: Document the Admin UI

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#384]
It just looks like no one's gotten to it yet, but it doesn't contain a message indicating that content is coming soon (unlike the "Back Up and Restore Data" page) and I don't see any open issues tracking it.

**Comment by jseldess** [comment]
Definitely hope to add content to this page soon, but you're right, we were missing an issue. Thanks, @a-robinson!

**Comment by jseldess** [comment]
Related issues:
- https://github.com/cockroachdb/cockroach/issues/5454
- https://github.com/cockroachdb/docs/issues/1136
- https://github.com/cockroachdb/docs/issues/1118

**Comment by jseldess** [comment]
@Amruta-Ranade, I've assigned this to you. Let's use this issue to plan/track the admin ui docs you'll write for 1.1. We can create a separate issue for 1.2 admin ui docs.

**Comment by Amruta-Ranade** [comment]
Documentation plan:
1. Sort graphs into those useful for customers and those useful for internal developers.
2. After the admin UI research ends on Thursday, identify user stories.
3. Map, understand, and document graphs/views to the user stories.
4. Incorporate issues from Github into UI docs.
5. Add admin UI-specific content to other impacted documents.
