### ISSUE TITLE
Production Checklist Doc Update: IOPS guidance

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3841]
Re: [Production Checklist](https://cockroachlabs.com/docs//v2.0/recommended-production-settings.html)

## Issue Description
Our guides say the types of disks we should use, but for AWS (as an example) there is another variable to consider, which is the number of iops per disk. 

## Suggested Resolution 
Provide some guidance or a formula to help users understand how to properly provision their disks

**Comment by nstewart** [comment]
I ended up using 25:1.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3936.
