### ISSUE TITLE
Recommend M5 instances on ec2

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#3852]
Re: [Deploy CockroachDB on AWS EC2](https://cockroachlabs.com/docs//v2.0/deploy-cockroachdb-on-aws.html)

We should update our hardware recommendations for EC2. `m5` and `m5d` instances use a new hypervisor that resolves the performance problem in https://heapanalytics.com/blog/engineering/clocksource-aws-ec2-vdso

Our old recommendation of `m3.large` is closest to `m5d.large`. However, I don't think we've tested that configuration. Our current main in-house use of EC2 is now on `m5.xlarge` instances with separate attached EBS volumes.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3936.
