### ISSUE TITLE
release-2.1: ui: Add Average QPS per Store graph to Replication dashboard

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3866]
PR: https://github.com/cockroachdb/cockroach/pull/30889

From release notes:
> Added a graph of the average QPS per store to the [**Replication** dashboard](../v2.1/admin-ui-replication-dashboard.html). Note that this uses an exponentially weighted moving average, not an instantaneous measurement. It is primarily of interest because it's the data that's used when making load-based rebalancing decisions. [#30889][#30889] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with Alex, this graph is primarily meant for internal CRDB engineers. Marking it as such in the docs.

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3886
