### ISSUE TITLE
release-2.1: ui: add bar chart for node list memory & capacity

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3867]
PR: https://github.com/cockroachdb/cockroach/pull/31070

From release notes:
> Added a bar chart to the memory and capacity usage columns on the [**Node List**](../v2.1/admin-ui-cluster-overview-page.html#node-list). These columns sort by percentage used. [#31070][#31070] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3886
