### ISSUE TITLE
release-2.1: ui: Add debug page for the EnqueueRange admin endpoint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3868]
PR: https://github.com/cockroachdb/cockroach/pull/31092

From release notes:
> Added a debug page with a form that lets users manually enqueue a range in one of the various store-level replica queues on a specified store. This feature is intended for advanced users only. [#31092][#31092] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closing this issue since we are not documenting advanced debug pages.
