### ISSUE TITLE
Life of a distributed transaction

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#3873]
To make CockroachDB's transaction model more understandable to users, we should:

- [x] Document "the life of a distributed transaction" step-by-step, starting at the client application, and flowing all the way down to RocksDB, and back out.

In conjunction with the above, we should aim to:
- [ ] Create a better explanation of how we handle conflict resolution.
- [ ] Update our docs on [transactions](https://www.cockroachlabs.com/docs/stable/transactions.html) and make them more usable for developers.

Other related issues:
- https://github.com/cockroachdb/docs/issues/3534
- https://github.com/cockroachdb/docs/issues/2300

**Comment by jseldess** [comment]
@sploiselle, @robert-s-lee mentioned that he's particularly interested in documenting some of the topics covered in a lunch and learn that Spencer gave. Could you please reach out to him and make sure the work you're planning covers his needs?

**Comment by jseldess** [comment]
Let's consider this project done and create separate issues for better documenting conflict resolution and the transactions docs.
