### ISSUE TITLE
Make Encryption at Rest warning scarier

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#3877]
The Encryption at Rest feature is going to be "experimental" in 2.1. Right now we have a generic warning at the top of [the page](https://www.cockroachlabs.com/docs/v2.1/encryption.html) that says:
> Warning:
> This is an experimental feature. The interface and output of this feature are subject to change.

We need to make this warning stronger, as it doesn't really convey the danger of using encryption at rest in its current state. Specifically, in the case of a bug or user error, all the data on an encrypted node could be rendered unreadable.

**Comment by jseldess** [comment]
@rmloveland, can you please strenghten that warning prior to the 2.1 release?
