### ISSUE TITLE
Improve decommissioning documentation 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#3885]
We need to improve documentation around the decommissioning process. 

We do not think customers should decommission multiple nodes at once.

Customers should never kill nodes that have not decommissioned. This causes irreparable data loss.

We will also likely invest time in learning about the [speed of the decommissioning process.](https://github.com/cockroachdb/cockroach/issues/31502)

**Comment by tschottdorf** [comment]
> We do not think customers should decommission multiple nodes at once.

They should be able to, but we may not want to recommend it just yet as there might be issues with it.

**Comment by awoods187** [comment]
CC @bdarnell for additional input
