### ISSUE TITLE
release-2.1: sql: make DISTSQL option to EXPLAIN ANALYZE optional

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3900]
PR: https://github.com/cockroachdb/cockroach/pull/31278

From release notes:
> `EXPLAIN ANALYZE <statement>` is now a valid equivalent of [`EXPLAIN ANALYZE (DISTSQL) <statement>`](../v2.1/explain-analyze.html) [#31278][#31278] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Already documented.
