### ISSUE TITLE
release-2.1: sql, ui: include distsql queries in `sql.{service,exec}.latency` metrics 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3901]
PR: https://github.com/cockroachdb/cockroach/pull/31116

From release notes:
> The **Service latency: {90,99}th percentile** graphs on the [**Overview**](../v2.1/admin-ui-overview-dashboard.html) and [**SQL**](../v2.1/admin-ui-sql-dashboard.html) dashboards, as well as the P50 and P99 latency numbers in the time series area sidebar, now reflect latencies of both local and distributed queries. Previously, they only included local queries. [#31116][#31116] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
This was a fix for an implementation bug. No doc impact.
