### ISSUE TITLE
Clean up admin-related privileges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3908]
For some statements, we reference requiring privileges on internal `system` tables, which is not helpful.  For example: https://www.cockroachlabs.com/docs/dev/create-user.html#required-privileges.

In such cases, we should use a formulation like:

> Users can be created only by superusers, i.e., members of the `admin` role. The `admin` role exists by default with `root` as the member.

**Comment by tim-o** [comment]
It'd be helpful to enumerate exactly the permissions available to `admin` (maybe on the `grant roles` page?) Both I and a user did not conclude from the references to the admin role that a) the admin role could be granted and b) that it could be used to create databases (see https://cockroachdb.zendesk.com/agent/tickets/3386)

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
