### ISSUE TITLE
Add import instructions for GCS and S3

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#3910]
Our import docs currently include examples for Azure storage (their equivalent of S3). But given most of our managed customers will be on GCE and AWS, and one of the first things they'll try to do is import, we should have instructions on how to import from S3 and Google Cloud Storage. This is primarily aimed at managed customers on GCP and AWS, but would apply to non-managed customers as well. 

cc: @mberhault

**Comment by jseldess** [comment]
@lhirata, post-release, this would be a great first `import` issue.

**Comment by jseldess** [comment]
@lhirata, some of the migration docs included examples of [importing from aws](https://www.cockroachlabs.com/docs/stable/migrate-from-csv.html#step-3-import-the-csv), in case it helps.
