### ISSUE TITLE
Confusing description of a stored value

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#3912]
At 
https://www.cockroachlabs.com/docs/stable/indexes.html#storing-columns it specifies values from the `FROM` clause, but I believe it should say values returned by the `SELECT` statement. As `FROM` lists the tables which values are retrieved by. This is what I believe it should say: 

---

Storing a column optimizes the performance of queries that retrieve its values but are not used for filtering. This is because indexing values are only useful when they're filtered, but if the index itself is mainly used to retrieve a small subset of the columns from the table, then storing the values along with the index can save a trip to the table to retrieve the values.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).
