### ISSUE TITLE
`generate` should check cockroach version

### ISSUE THREAD

**Issue by dt** [cockroachdb/docs#394]
Since we generate the diagrams and function docs from the cockroach source, we should check that we don't use an old version of cockroach to generate docs.

When generating docs, we could record the cockroach SHA/commit date to a file ("docs generated from cockroach...") then read that in future runs to warn if we're using an older checkout to generate docs.

**Comment by bdarnell** [comment]
We also don't necessarily want to use a newer version. Most of the time we want to generate docs from a beta-tagged version, not necessarily the latest master. (there are exceptions like the new features added to the generator script this week).

**Comment by dt** [comment]
wouldn't the tagged beta still be newer than the _previous_ version used to generate?

**Comment by bdarnell** [comment]
Ah, right. We can and should at least guarantee that we don't move backwards.

**Comment by jseldess** [comment]
K, Thanks, @mjibson.
