### ISSUE TITLE
Describe use cases for Change Data Capture

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3965]
Re: [Change Data Capture (CDC)](https://cockroachlabs.com/docs//v2.1/change-data-capture.html)

## Issue Description
We say this only works for "a targeted use case" but do not clearly explain what that use case is.

## Suggested Resolution 
Explain the use case we support

**Comment by jseldess** [comment]
Thanks, @nstewart. Just a bit down the page, we do say a little more about potential usage of this feature. 

@lhirata, can you work with @rolandcrosby to identify the use cases we want to highlight more clearly? If we're not ready to do so, we could also just remove that clause form the callout Nate is mentioning.
