### ISSUE TITLE
Use latency based routing for global clusters

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3978]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recfXaqHLDhHJG16G
PM: @kannanlakshmi 
Eng partner: @mberhault

**Comment by jseldess** [comment]
Moved to 2.3.

**Comment by lnhsingh** [comment]
@Amruta-Ranade passing to you but feel free to close if no longer relevant.
