### ISSUE TITLE
Per user credentials and storage 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3980]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recmpemZRTlOs3HUS
PM: @rolandcrosby 
Eng partner: @mberhault

**Comment by jseldess** [comment]
Moved out of scope for 2.2.

**Comment by lnhsingh** [comment]
Closing this issue for now - will open when it is added to the roadmap.
