### ISSUE TITLE
GSSAPI (Kerberos) Authentication for LDAP/Active Directory

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3981]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recUW5mVAIz9darfl
PM: @rolandcrosby 
Eng partner: @bdarnell

**Comment by Amruta-Ranade** [comment]
Matt: Look at pg_hba.conf file to understand the implementation.

**Comment by Amruta-Ranade** [comment]
Reference reads: 
https://docs.oracle.com/cd/E19120-01/open.solaris/819-3321/intro-25/index.html
https://en.wikipedia.org/wiki/Kerberos_(protocol)

**Comment by Amruta-Ranade** [comment]
Testing reference: https://docs.bmc.com/docs/sso90/end-to-end-steps-for-configuring-active-directory-kerberos-authentication-474057067.html

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/4562
