### ISSUE TITLE
Asynchronous Job Management

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3986]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/reca0PkS5byrlsUjH
PM: @rolandcrosby 
Eng: @vivekmenezes

**Comment by jseldess** [comment]
Moved out of scope for 2.2.

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
