### ISSUE TITLE
Ability to control impact of jobs on foreground traffic

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3990]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recR3sHlY8rhKZj2k
PM: @rolandcrosby 
Eng: @dt

**Comment by jseldess** [comment]
Moved out of scope for 2.2.

**Comment by lnhsingh** [comment]
Related to: https://cockroachlabs.atlassian.net/browse/CRDB-44?atlOrigin=eyJpIjoiZGRkM2M2N2VhYzNhNDQyZGIwNjJjYTExZmEzZmJhNGIiLCJwIjoiaiJ9

Probably won't make 20.2

**Comment by lnhsingh** [comment]
After discussing with Michael, we won't be documenting anything for the v20.2 release. Closing this issue in lieu of opening a new one when this should be documented later.
