### ISSUE TITLE
Certificate Revocation Support

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3995]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recjB8fKRH3DxSLYY
PM: @rolandcrosby 
Eng: @mberhault

**Comment by jseldess** [comment]
Moved out of scope for 2.2.

**Comment by Amruta-Ranade** [comment]
Duplicate of https://github.com/cockroachdb/docs/issues/8285
