### ISSUE TITLE
[MH] Support mutations/CRUD in cost-based optimizer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3998]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recNRIzZOB081eanC
PM: @awoods187 
Eng: @andy-kimball

**Comment by rmloveland** [comment]
Based on comparing the statements listed in the AirTable entry with our [docs on the types of statements supported by the optimizer](https://www.cockroachlabs.com/docs/v19.1/cost-based-optimizer.html#types-of-statements-supported-by-the-cost-based-optimizer), I think this work is done.

@awoods187 and/or @andy-kimball, please re-open if you think more docs work is needed here.
