### ISSUE TITLE
Test intelliJ ide 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4004]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recLhELw2PiWauIWw
PM: @awoods187 
Eng: @BramGruneir

**Comment by rmloveland** [comment]
See also: https://github.com/cockroachdb/cockroach/issues/31737

**Comment by awoods187** [comment]
I think this verges on P-0 so that we can expand upon our burgeoning third-party listing on the website. It gives us an entry in IDE to go along with Schema Change, WebUI, and ORMs neatly rounding out the main third-party functionality types

**Comment by jseldess** [comment]
@awoods187, P-0 is for urgent issues that need to be addressed in the next 2 weeks. P-1 is for issues that must be addressed before the GA release. I consider all roadmap issues P-1. Does that make sense?

**Comment by jseldess** [comment]
Docs label descriptions are here: https://github.com/cockroachdb/docs/wiki/Issue-Labels

**Comment by awoods187** [comment]
Yeah that makes sense

**Comment by jseldess** [comment]
@rmloveland, @sploiselle can help with this one.

**Comment by sploiselle** [comment]
This works barring the issues identified in cockroachdb/cockroach#31737, namely that you have to go past errors and ignore those that arise.

Given that there are some warts but it is sufficiently supported, do we want to include it in our supported tools? I'll make sure that the doc sets appropriate expectations around these errors if we do want to move forward.

cc @awoods187

**Comment by awoods187** [comment]
Yes we want to document this since it can be used. I'd qualify this as beta as opposed something thats fully supported like Postico or Dbeaver
