### ISSUE TITLE
[MH] Test Spring ORM

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4005]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recUgcKgZew4Z0Lj0
PM: @awoods187 
Eng: @BramGruneir

**Comment by rmloveland** [comment]
See also this CDC example which uses Spring: https://github.com/timveil-cockroach/cdc-example

**Comment by sploiselle** [comment]
@BramGruneir Are there any updates on this for the 2.2 timeframe?

**Comment by BramGruneir** [comment]
Nothing new from my end.  I'm working on SQLAlchemy this week.

@awoods187 what's the status of Spring?

**Comment by jseldess** [comment]
Closing this for issue for 19.1. Documenting this ORM is a larger project that we should prioritize when it makes sense.
