### ISSUE TITLE
Investigate Hibernate performance 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4006]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/rec3AMKSJW6iPuZOE
PM: @awoods187 
Eng: @BramGruneir

**Comment by sploiselle** [comment]
@BramGruneir Are there any updates on this for the 2.2 timeframe?

**Comment by BramGruneir** [comment]
We don't really have any actionable items for this.  
@awoods187?

**Comment by jseldess** [comment]
Moved to 19.2.

**Comment by jseldess** [comment]
Not happening.
