### ISSUE TITLE
Improve docs SEO

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#401]
This is HubSpot's SEO review of the install page: 
![screen shot 2016-06-15 at 12 35 29 pm](https://cloud.githubusercontent.com/assets/6042450/16088568/bb90e1bc-32f5-11e6-80c5-dbad7b6ec698.png)

@jess-edwards

**Comment by jess-edwards** [comment]
@jseldess 
The page DOES have a HubSpot Call-to-Action on it - the email field step that appears as the final step - so disregard that warning. 

Here are some best practices for writing meta descriptions: 

**How to Write Great Meta Descriptions**
Effective meta descriptions drive someone to click when they see your page appear in search results. Persuade the searcher to click while still maintaining accuracy so expectations are met. 

1) Use action-oriented language.
Action-oriented language: Consider starting your meta descriptions with verbs like "Learn" or "Discover," and follow it up with specifics of what exactly they'll get if they click.

2) Provide a solution or benefit.
Write a short sentence previewing the content or telling the searcher why they should read your post. This is your chance to sell them on what you have to offer -- informative, valuable content.

3) Keep it under 155 characters.
[in Google Docs: shift+CMD+C  = WordCount]
Google actually doesn't measure by characters -- it measures by pixels -- but 155 characters is a  benchmark. 

4) Make it specific and relevant.
Use descriptive words -- not unnecessary "fluff" words -- and do your best to connect with your target audience and let them know what they'll get from clicking through on your search result.
