### ISSUE TITLE
Fix/extend INTERVAL, TIMESTAMP(TZ), DATE and TIME

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4010]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recvfLqLfmKdeQpfL
PM: @awoods187 
Eng: @knz

**Comment by rmloveland** [comment]
Related:

- INTERVAL uses microseconds (not nanoseconds): #4375

**Comment by awoods187** [comment]
in https://www.cockroachlabs.com/docs/v2.1/interval.html#main-content we see an output of:
```
SELECT * FROM intervals;
+---+------------------+
| a |        b         |
+---+------------------+
| 1 | 1h2m3.004005006s |
| 2 | 14m3d4h5m6s      |
| 3 | 14m3d4h5m6s      |
+---+------------------+
(3 rows)
```
In master (v19.1.0-beta.20190304-458-g70e3468), I see:
```
root@localhost:26257/tpcc> SELECT * FROM intervals;
  a |               b
+---+-------------------------------+
  1 | 01:02:03.004005
  2 | 1 year 2 mons 3 days 04:05:06
  3 | 1 year 2 mons 3 days 04:05:06
(3 rows)

Time: 3.590604ms
```

**Comment by bobvawter** [comment]
The commit that you link to is mainly about improving our compatibility with documented date-time formats.

@mjibson did remove support for nanosecond-precision intervals in https://github.com/cockroachdb/cockroach/pull/34202 , changing it to be more in line with pgsql's microsecond precision.  That one could have some user-visible impact if someone is relying on maintaining nanosecond values in cockroach.

**Comment by rmloveland** [comment]
> @mjibson did remove support for nanosecond-precision intervals in cockroachdb/cockroach#34202 , changing it to be more in line with pgsql's microsecond precision. That one could have some user-visible impact if someone is relying on maintaining nanosecond values in cockroach.

Ok cool, we already documented that change in https://github.com/cockroachdb/docs/pull/4432.  Thanks Bob!

In that case I will close this issue since (AFAICT) it is a broad compatibility item from the roadmap that does not have specific docs impact.

@knz or @awoods187 please shout if you disagree and I'll re-open

**Comment by awoods187** [comment]
makes sense to me
