### ISSUE TITLE
[MH] Improve the performance of schema change index backfills

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4014]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recez89kyYFXFl8Ih
PM: @awoods187 
Eng: @vivekmenezes

**Comment by awoods187** [comment]
This will present the same to the user as the current implementation. If we decided to add a controllable cluster flag (something that might allow you to prioritize schema changes over foreground traffic for example) we will open a separate docs issue.
