### ISSUE TITLE
Port in-code optimizer docs to website

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4023]
We should investigate what portions of the content in [doc.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/doc.go) should be added to the docs content on the [Cost-based optimizer page](https://www.cockroachlabs.com/docs/v2.1/cost-based-optimizer.html) (or elsewhere as appropriate).

**Comment by awoods187** [comment]
Closing this as out of date
