### ISSUE TITLE
sql: tzinfo can be inconsistent across nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4025]
See https://github.com/cockroachdb/cockroach/issues/31978#issuecomment-437850407.

> CockroachDB relies on each node's tzinfo data for resolving named timezones like America/New_York and for applying daylight-savings rules. This can lead to inconsistent results across a cluster when coercing date/time strings into temporal types.

From @knz:
> until this issue is fixed, we should call out in the docs for operational matters that the OS database should be updated, and all nodes should be restarted when the timezone data changes (e.g. the definition of a timezone changes because of geopolitical matters, or some country decides to change their DST rules).

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!

**Comment by rmloveland** [comment]
This issue is still open in CRDB repo, reopening
