### ISSUE TITLE
Managed CockroachDB Security overview

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4039]
We need to describe the security of a Managed CockroachDB cluster. 

This should leverage the work @lhirata is doing for https://github.com/cockroachdb/docs/issues/3549. It also needs to explain that a managed cluster is single-tenant (no shared machines/cpu) running in a VPC (no shared network). Firewall is only way in.

**Comment by lhirata** [comment]
This isn't really a 19.1 issue - might want to rethink issue labeling for MSO.

**Comment by Amruta-Ranade** [comment]
Note to self: Might need to update CRDB 2.1 as well as 19.1 docs for MSO
