### ISSUE TITLE
Managed CockroachDB schema design best practices

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4040]
For Managed CockroachDB, schema design and replication controls are the two essential "operational" topics that customers need to understand and deal with themselves. They are related in that schema design needs to factor in the distributed nature of CockroachDB. 

This is a gap for the standard CockroachDB docs as well, for which we have [basic SQL best practices](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html), [tuning guidance](https://www.cockroachlabs.com/docs/stable/performance-tuning.html), and [replication control guidance](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html), but no guidance on **how to best design schemas in CockroachDB**, which would synthesize at least some of the other topics.

**Comment by lhirata** [comment]
This isn't really a 19.1 issue - might want to rethink issue labeling for MSO.

**Comment by jseldess** [comment]
This should be part of the developer guide @ericharmeling and @ianjevans are working on, and the training team will build a course on schema design as well.
