### ISSUE TITLE
No Mac workload binary on deployment page

### ISSUE THREAD

**Issue by m-schneider** [cockroachdb/docs#4045]
When following directions on pages such as https://www.cockroachlabs.com/docs/v2.1/deploy-cockroachdb-on-aws-insecure.html#step-8-run-a-sample-workload, the workload binary is Linux specific and doesn't work on Macs.

To fix it we could either add a Mac binary or change the directions to use the workload builtin to Cockroach.

**Comment by jseldess** [comment]
We should update the page to use the `cockroach workload run tpcc` command instead. I'll handle this in conjunction with https://github.com/cockroachdb/docs/issues/3686.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5359.
