### ISSUE TITLE
Wrong google result for "cockroachdb union"

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#4046]
https://www.google.com/search?rlz=1C5CHFA_enUS761US767&ei=Ot7sW4umHqG5ggeY0K_QCA&q=cockroachdb+union&oq=cockroachdb+union&gs_l=psy-ab.3..0i71l8.0.0..90319...0.0..0.0.0.......0......gws-wiz.xRNVIaslLmw

The first hit is https://www.cockroachlabs.com/docs/v2.1/select-clause.html. That page does not have the word "union" in it.
What you want is the 3rd hit: https://www.cockroachlabs.com/docs/v2.1/selection-queries.html#union-combine-two-queries

Feel free to close if not actionable.

**Comment by jseldess** [comment]
Thanks for reporting, @andreimatei. I'm stumped by this. Perhaps the page used to include the term `union` and google is not forgetting. Not sure. @j-low, let me know if you have ideas.

**Comment by jseldess** [comment]
This is working as expected now, possibly since we upgraded our docs search.
