### ISSUE TITLE
Translate to Korean

### ISSUE THREAD

**Issue by hueypark** [cockroachdb/docs#4053]
Many developers in Korea are waiting for CockroachDB. However, due to the lack of Korean language documents, we are facing high entry barriers.

I started to create a localized document, which would be a good starting point for the i18n.

So I forked the docs and started the translate-ko branch(https://github.com/hueypark/docs/tree/translate-ko). I want to create a translate-ko branch at the origin and make PR.

In the future, I hope to see the translated documents on the web(https://www.cockroachlabs.com/docs/stable/).

Is that a good idea? Or give me another suggestion.

**Comment by rytaft** [comment]
Assigning to @jseldess, who may know about plans for translation.

**Comment by Taeeunn** [comment]
Hello, we are undergraduates of Korea SungKyunKwan University Software Major. 
We are taking a class to learn how to use git&github. While we were looking for a Korean translation project, we found the following issue and we thought it was an interesting topic, so we would like to work on it together. This is our team's github page and we've done a little bit of work.
https://github.com/18-2-SKKU-OSS/2018-2-OSS-E4

**Comment by knz** [comment]
@jseldess I went to the repo and I am impressed. These folk are literally translating the docs sites page by page. This is remarkable.

Incidentally there's another contributor who is translating our blog: https://marsettler.com/

**Comment by hueypark** [comment]
I found another good example.
Kubernetes operates a translation page as shown below.
- They placed a link on their homepage to generate a PR(https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/)
- Create l10n pages by language(https://github.com/kubernetes/website/tree/master/content)

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
