### ISSUE TITLE
sql: optionally enable vectorized planning with experimental_vectorize

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4069]
PR: https://github.com/cockroachdb/cockroach/pull/31354

From release notes:
> The new `experimental_vectorize` [session setting](../v2.2/set-vars.html), when enabled, causes columnar operators to be planned instead of row-by-row processors, when possible. [#31354][#31354] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@ericharmeling I know you're working on some of the vectorized stuff.  Does this issue still need to be worked on?  Or is this controlled via some other flag for 19.2 now?

(Grooming my assigned issues, hence the question about this possibly non-release-related thing.)

**Comment by rmloveland** [comment]
Closing since the vectorization cluster settings are up on the docs site for versions [19.1](https://www.cockroachlabs.com/docs/v19.1/cluster-settings.html) and later.
