### ISSUE TITLE
sql: fix (really: add) the handling of bit arrays 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4070]
PR: https://github.com/cockroachdb/cockroach/pull/28807

From release notes:
> CockroachDB now supports the `BIT` and `VARBIT (BIT VARYING)` bit array data types like PostgreSQL. Currently, only the bit array literal notation with a capital B (e.g., `B'10001'`) is supported; the notation with a small `b` (e.g., `b'abcd'`) continues to denote **byte** arrays as in previous versions of CockroachDB. [#28807][#28807] {% comment %}doc{% endcomment %}

**Comment by knz** [comment]
a placeholder for when the work starts: beside the type-specific page, the `sql-constants.md` should be modify to add the new literal format (`B'....'`), a difference should be outlined between `b'...'` (byte array literals) and `B'...'` (bit array literals), and a special notice should be added that there is a divergence from the PostgreSQL syntax (postgres does not support byte array literals, and pg's `b'...'` is also a bit array literal).
