### ISSUE TITLE
cli/sql: improve debuggability

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4072]
PR: https://github.com/cockroachdb/cockroach/pull/31630

From release notes:
> The client-side option `smart_prompt` now controls whether [`cockroach sql`](../v2.2/use-the-built-in-sql-client.html) and [`cockroach demo`](../v2.2/cockroach-demo.html) use the current transaction state to offer a multi-line entry at the start of new transactions. [#31630][#31630] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
From Raphael: Take it up with troubleshooting follow-up PR (also document "when you file an issue, save the trace of sql statements and enable this flag as well".

**Comment by jseldess** [comment]
@Amruta-Ranade, do you need any help with this one?

**Comment by Amruta-Ranade** [comment]
No. This is a part of the followup work for the troubleshooting docs. Other issues took priority over the followup work, so didn't get around to this one.

**Comment by jseldess** [comment]
I don't think this needs to be grouped into a larger project. This is a granular doc change pertaining to a specific option for `cockroach sql` and `cockroach demo`.

**Comment by Amruta-Ranade** [comment]
Yep. Will pick it up next week.

**Comment by Amruta-Ranade** [comment]
Update: Discussed this feature's UX with Andrei yesterday. Need to follow-up with Raphael next week to resolve some open questions.

**Comment by Amruta-Ranade** [comment]
@knz I discussed this issue with Andrei last week, and we individually came to the same conclusion: the feature is not user-friendly and we should reconsider taking it out. 
(Reference:
https://github.com/cockroachdb/cockroach/issues/31567#issuecomment-431391652)

 Thoughts?

**Comment by knz** [comment]
The feature is meant for troubleshooting mainly by "Advanced" CockroachDB users and/or engineering team members.

I believe it's desirable to have it present in the product but not desirable to document it.

**Comment by Amruta-Ranade** [comment]
Oh..I see. Thanks for the clarification! Closing this issue since it doesn't have a doc impact.
