### ISSUE TITLE
ui: make cluster overview layout more fluid

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4074]
PR: https://github.com/cockroachdb/cockroach/pull/31512

From release notes:
> Improved the layout of the [**Cluster Overview**](../v2.2/admin-ui-cluster-overview-page.html) page for large clusters with many nodes and ranges. [#31512][#31512] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
I don't think this PR has a doc impact. @couchand ?

**Comment by Amruta-Ranade** [comment]
As discussed with @celiala, this issue doesn't require a docs change.
