### ISSUE TITLE
ui, server: add remaining stats to Non-Table data

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4076]
PR: https://github.com/cockroachdb/cockroach/pull/31830

From release notes:
> The **Non-Table Cluster Data** section of the [**Databases**](../v2.2/admin-ui-databases-page.html) page now includes all non-table data types. Previously, this section only showed Time Series data. [#31830][#31830] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Requires a screenshot update - will take this up when I update all screenshots for 2.2
