### ISSUE TITLE
release-2.1: opt: Decorrelate Zip with correlated EXISTS subquery

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4078]
PR: https://github.com/cockroachdb/cockroach/pull/32026

From release notes:
> CockroachDB now de-correlates and successfully executes many queries containing correlated `EXISTS` subqueries. Previously, these queries caused a de-correlation error. [#32026][#32026] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
I think our correlated subquery support doc update in #4654 takes care of this - we documented that we support most of them, and listed those we don't instead as exceptions.
