### ISSUE TITLE
Document storage savings of sparse column

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4089]
There are couple of benefits to CockroachDB's [key/value storage encoding](https://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage/) 
1. reduce storage space for sparsely populated columns.   CockroachDB consumes 176 MB.  Postgres consumes 1,119 MB on the same 4 million rows.
2. reduce CPU consumption vs using JSONB

Spares columns are often NULLable.  Some databases requires spares columns to be organized so that all of the trailing NULLs are defined in the schema at the end of the schema.  This ensures trailing null columns in a table consume zero bytes of storage.  For a wide column tables, complex table reorganization to re-order the columns is a daunting tasks.

JSON is popular with schema-less  design where attributes (or numbers of columns could vary based on service or users).  For some applications that have high concurrent write and read of few columns, the CPU cost of serializing and de-serializing could be high.

The following test artificially limits to 1,500 columns so that examples can be run on Postgres.

- Create DDL with 500 integers column, 500 float columns and 500 string columns.

```
echo "create table t1 ( id uuid PRIMARY KEY DEFAULT gen_random_uuid() " > /tmp/widetable.sql
for i in `seq -f %04g 500`; do
  echo ", i${i} int"  >> /tmp/widetable.sql
  echo ", f${i} float"  >> /tmp/widetable.sql
  echo ", s${i} text"  >> /tmp/widetable.sql
done
echo ");" >> /tmp/widetable.sql
```
- Define the table and randomly populate 4 million rows.  75% has data in the beginning, middle or end and 25% had day in the beginning, middle and end.
```
cat /tmp/widetable.sql | cockroach sql --insecure
cockroach sql --insecure <<EOF
insert into t1 (i0001) select generate_series(1, 1000000);
insert into t1 (f0250) select generate_series(1, 1000000)::float;
insert into t1 (s0499) select generate_series(1, 1000000)::text;
insert into t1 (i0001, f0250,s0499) select generate_series(1, 1000000), generate_series(1, 1000000)::float, generate_series(1, 1000000)::text;
EOF
```

- Postgres space via [modified script](https://wiki.postgresql.org/wiki/Disk_Usage) is below.
```
SELECT *, pg_size_pretty(total_bytes) AS total
    , pg_size_pretty(index_bytes) AS INDEX
    , pg_size_pretty(toast_bytes) AS toast
    , pg_size_pretty(table_bytes) AS TABLE
  FROM (
  SELECT *, total_bytes-index_bytes-COALESCE(toast_bytes,0) AS table_bytes FROM (
      SELECT c.oid,nspname AS table_schema, relname AS TABLE_NAME
              , c.reltuples AS row_estimate
              , pg_total_relation_size(c.oid) AS total_bytes
              , pg_indexes_size(c.oid) AS index_bytes
              , pg_total_relation_size(reltoastrelid) AS toast_bytes
          FROM pg_class c
          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE relkind = 'r' and relname = 't1'
  ) a
) a;
```
- Postgres storage consumption below
```
  oid   | table_schema | table_name | row_estimate | total_bytes | index_bytes | toast_bytes | table_bytes |  total  | index  |   toast    | table
--------+--------------+------------+--------------+-------------+-------------+-------------+-------------+---------+--------+------------+--------
 251612 | public       | t1         |   4.0002e+06 |  1173004288 |   163733504 |        8192 |  1009262592 | 1119 MB | 156 MB | 8192 bytes | 963 MB
```

**Comment by jseldess** [comment]
@sploiselle, assigning to you for prioritization.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and re-open
the issue. Thank you for your contribution to CockroachDB docs!
