### ISSUE TITLE
Update homepage content

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#4100]
We should update the home page to surface the following content.

Aim to have this list completed (i.e. items current linked to issues instead link to pages in production) by Jan. 14, 2019.

### Get Started @sploiselle 

- What is CockroachDB? (Overview) #4042
- [Install CockroachDB](https://www.cockroachlabs.com/docs/stable/install-cockroachdb-mac.html)
- [Start a Cluster](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html)
- [Build an app](https://www.cockroachlabs.com/docs/stable/build-an-app-with-cockroachdb.html)

### SQL @rmloveland 

[SQL Statements](https://www.cockroachlabs.com/docs/stable/sql-statements.html)
Top 3 SQL statement pages #4099

### Migrate to CockroachDB @lhirata 

- [Migration Overview](https://www.cockroachlabs.com/docs/v2.1/migration-overview.html)
- [Migrate from Postgres](https://www.cockroachlabs.com/docs/v2.1/migrate-from-postgres.html)
- [Migrate from MySQL](https://www.cockroachlabs.com/docs/v2.1/migrate-from-mysql.html)
- [Migrate from CSV](https://www.cockroachlabs.com/docs/v2.1/migrate-from-csv.html)

### Deployments @lhirata 

- Deployment Overview #1786
- [AWS](https://www.cockroachlabs.com/docs/v2.1/deploy-cockroachdb-on-aws.html)
- [Production Checklist](https://www.cockroachlabs.com/docs/v2.1/recommended-production-settings.html)
- [Kubernetes](https://www.cockroachlabs.com/docs/v2.1/orchestrate-cockroachdb-with-kubernetes.html
)

### Troubleshooting @Amruta-Ranade 

- [Troubleshooting Overview](https://www.cockroachlabs.com/docs/v2.1/troubleshooting-overview.html)
- [SQL Troubleshooting](https://www.cockroachlabs.com/docs/v2.1/query-behavior-troubleshooting.html)
- [Deployment Troubleshooting](https://www.cockroachlabs.com/docs/v2.1/cluster-setup-troubleshooting.html)
- Security Troubleshooting (issue TBD by @Amruta-Ranade)

### Security @Amruta-Ranade 

- Security Overview #3549
- [Certificates](https://www.cockroachlabs.com/docs/v2.1/create-security-certificates.html)
- [Users](https://www.cockroachlabs.com/docs/v2.1/create-and-manage-users.html)
- [Encryption at Rest](https://www.cockroachlabs.com/docs/v2.1/encryption.html)

**Comment by jseldess** [comment]
Picking this back up, on the assumption that providing more orientation on the docs landing page, however imperfect, will make more users happy.
