### ISSUE TITLE
How to ORDER BY or GROUP BY json data

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4102]
To apply the `ORDER BY` or `GROUP BY` clauses to json data, you must use the `->>` operator to cast the result to a string. We could add an example to https://www.cockroachlabs.com/docs/v2.1/jsonb.html.

This came up on the forum: https://forum.cockroachlabs.com/t/order-by-and-group-by-clauses-on-jsonb-data/2211

**Comment by Shiwanee** [comment]
@Amruta-Ranade, Can I give it a try?  :-)
Thanks.

**Comment by Amruta-Ranade** [comment]
Go for it!

**Comment by Shiwanee** [comment]
@Amruta-Ranade I have created a PR, #8679 for this issue. Could you please look into it and let me know the further steps?
Thanks,
Shiwanee :-)

**Comment by Shiwanee** [comment]
Hi @Amruta-Ranade ! I have implemented the review comments! 

Thanks,
Shiwanee

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8679

**Comment by Shiwanee** [comment]
Thank you so much @Amruta-Ranade and @ericharmeling :-)

Shiwanee

**Comment by Amruta-Ranade** [comment]
Thanks for your contribution, @Shiwanee !
