### ISSUE TITLE
CDC: Document workaround for consolidating Kafka data into a single topic

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#4105]
A prospective customer who's interested in CDC expressed interest in putting all of their CockroachDB CDC data in a single Kafka topic. CockroachDB currently requires that each table's changefeed be published to a separate Kafka topic. One workaround for people who want their data in this form would be setting up CockroachDB CDC for each table to its own topic, then building a simple application (using Kafka Streams or as a standalone program) that consumes all the individual CDC topics and consolidates them to a single topic. There are some subtleties around buffering, timestamps, and message format (the app would probably need to inject a table name into the keys/values written to Kafka, and it would need to do something sensible to preserve message ordering); we should document what they'd need to do to accomplish this.

**Comment by robert-s-lee** [comment]
Is there an option to add constant key:value on the rows emitted (even when the rows are deleted) so that table name can be embedded in the data stream?

**Comment by jseldess** [comment]
@rolandcrosby, can you assign the `P-<riority>` label that you think is correct?

**Comment by amruss** [comment]
In 21.2 we're adding support for arbitrary kafka topic naming, so you will be able to write multiple tables to a single topic through that feature
