### ISSUE TITLE
EXPORT/IMPORT/BACKUP/RESTORE credentials show up in SHOW QUERIES

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4108]
We need to add a note to the relevant bulk i/o docs stating that credentials passed in the URL show up in `SHOW QUERIES` output. 

For background, see https://github.com/cockroachdb/cockroach/issues/28187.

**Comment by mwang1026** [comment]
answer here also might be to obfuscate them in `show queries` as an enhancement. i'll dig more here

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
