### ISSUE TITLE
Change Data Capture (CDC) Doc Update experimental_avro

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4115]
Re: [Change Data Capture (CDC)](https://cockroachlabs.com/docs//v2.1/change-data-capture.html)

## Issue Description

```
CREATE CHANGEFEED FOR TABLE foo INTO 'kafka://localhost:9092' WITH format = experimental_avro, confluent_schema_registry = 'http://localhost:8081';

pq: unknown format: experimental_avro
```

running CockroachDB 2.1.1 on OSX

Build Tag:    v2.1.1
Build Time:   2018/11/19 18:20:16
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin13)
Go Version:   go1.10.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  4523f9819d2dde9b054fc8faf1568e107f130986
Build Type:   release

## Suggested Resolution

**Comment by robert-s-lee** [comment]
Apparently, 2.2.0 is required per @danhhz

**Comment by rolandcrosby** [comment]
I believe it’s experimental-avro in older builds - it’s now
experimental_avro to match our conventions for identifiers and to avoid
requiring quotes in the WITH options section.

**Comment by jseldess** [comment]
Yep, @rolandcrosby's right. @robert-s-lee, in 2.1, this works:

```
root@:26257/defaultdb> SET DATABASE = cdc_demo;
SET

Time: 486.507µs

root@:26257/cdc_demo> CREATE CHANGEFEED FOR TABLE office_dogs INTO 'kafka://localhost:9092' WITH format = 'experimental-avro', confluent_schema_registry = 'http://localhost:8081';
        job_id
+--------------------+
  404622960202219521
(1 row)

Time: 45.251114ms
```

**Comment by robert-s-lee** [comment]
With 2.2.0 Instructions in the current doc worked.  :)
