### ISSUE TITLE
How to update one table from another

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4117]
See https://forum.cockroachlabs.com/t/how-to-update-one-table-from-another/2217 for @knz's solution. This should be somewhere in our sql docs and faqs.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

**Comment by awoods187** [comment]
Closing this since we have CDC now
