### ISSUE TITLE
Inserting/importing large rows

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4118]
See https://forum.cockroachlabs.com/t/very-slow-mysql-import/2152/5?u=knz.

Summary: 100KB/row is on the upper side what CockroachDB can insert with decent performance. Around that size and up may result in bad performance or unexpected blockages. Also, even if you're lucky and there is a happy case for the write path, decoding the large rows upon reading will make read queries subsequently unhappy (both in throughput and memory usage).

cc: @knz

**Comment by knz** [comment]
Note that @nvanbenschoten and @jordanlewis have more fine-grained, better informed knowledge/understanding about this than my own.

**Comment by jseldess** [comment]
@mwang1026, can you check this oldish issue and decide if there's still a doc improvement to make?

**Comment by mwang1026** [comment]
I think we can punt on this for now -- especially since we don't have concrete guidance on what works better for different sizes and AFAIK we improved insert performance. Closing for now
