### ISSUE TITLE
Index selection for composite primary and secondary keys

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4121]
If you have a composite primary key (e.g., `id, uuid`), selecting just the first column of the key will use the primary index, but selecting just the second column won't. Same is true of a secondary index. We should find a way to document this.

**Comment by jseldess** [comment]
@jordanlewis, can you check the above for me?

**Comment by jordanlewis** [comment]
Not quite right - merely selecting one or the other of the columns doesn't impact index selection. Filtering on one or the other does. The database can only use an index if there are constraints on a prefix of the columns in that index.

**Comment by ericharmeling** [comment]
I believe this is covered in the first bullet point under https://www.cockroachlabs.com/docs/v20.2/indexes#indexing-columns. Please re-open if this is insufficient.
