### ISSUE TITLE
Duplicate documentation for Timestamp cache 

### ISSUE THREAD

**Issue by arjunrao87** [cockroachdb/docs#4124]
In documentation for `Transaction Layer`, the section for Timestamp cache is repeated twice, with no difference in documentation

Full path to docs : `Concepts -> Architecture -> Transaction Layer`. Attached below are the highlighted sections in a screenshot

<img width="255" alt="screen shot 2018-12-02 at 5 53 36 pm" src="https://user-images.githubusercontent.com/2516336/49346129-ca392680-f65b-11e8-9337-450a30ab4705.png">

**Comment by rmloveland** [comment]
Thanks for reporting this @arjunrao87 - I've made a PR to fix this which I hope will merge soon: https://github.com/cockroachdb/docs/pull/4126
