### ISSUE TITLE
Clarify topic naming in CDC doc

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#4129]
See: https://www.cockroachlabs.com/docs/stable/change-data-capture.html#create-a-changefeed-connected-to-kafka

In the CDC doc related to`kafka`, we should call out that the `topic` name must equal the `table` name.  In the examples provided they are the same but we should be explicit about this requirement because CDC will not work if the `topic` name does not match the `table` name.

**Comment by rolandcrosby** [comment]
Right now you can only specify a topic name prefix; I believe I asked @danhhz about explicitly specifying a table name and he gave me a good reason why that wasn't supported, but I can't recall exactly what it was. (Maybe it had something to do with creating multiple changefeeds at once via the currently-unsupported `CREATE CHANGEFEED ON DATABASE dbname`?)

This is likely to be a more important issue in production deployments, where Kafka brokers often have automatic topic creation disabled, so we should at least be sure that the docs are explicit about this.

**Comment by danhhz** [comment]
Even today, you can specify multiple tables in one `CREATE CHANGEFEED` command, but you almost certainly don't want them going to the same topic (there's no good way to separate them back out from what gets published). This has come up as a question often enough that we should probably do something, but I still don't feel like I have a good idea what.

**Comment by amruss** [comment]
addressed in this PR https://github.com/cockroachdb/docs/pull/10292
