### ISSUE TITLE
DOTNET 2.1 with CockroachDB 2.1.1 using Npgsql 4.0.3

### ISSUE THREAD

**Issue by alexevon** [cockroachdb/docs#4139]
Just installed cockroachDB 2.1.1 and running .NET core 2.1 with the example code on:

https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html

Cockroach itself appears fine as we imported a test mariaDB database into with ZERO issues (great job btw!), but trying out the C# code from above results in:

cockroachdb-test-app# dotnet run
Initial balances:

Unhandled Exception: System.InvalidCastException: Can't cast database type bigint to String
at Npgsql.NpgsqlDefaultDataReader.GetFieldValue[T](Int32 column) in C:\projects\npgsql\src\Npgsql\NpgsqlDefaultDataReader.cs:line 154
at Cockroach.MainClass.Simple(String connString) in /root/cockroachdb-test-app/Program.cs:line 45
at Cockroach.MainClass.Main(String[] args) in /root/cockroachdb-test-app/Program.cs:line 16

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>cockroachdb_test_app</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="4.0.3" />
  </ItemGroup>

</Project>

Thank you!

**Comment by jseldess** [comment]
I transferred this to the docs repo. @BramGruneir, can you validate this small change?

**Comment by BramGruneir** [comment]
Yep, the change LGTM.
