### ISSUE TITLE
Duplicate paragraph of [build-a-go-app-with-cockroachdb-gorm.md]

### ISSUE THREAD

**Issue by melrose98** [cockroachdb/docs#4140]
### **[build-a-go-app-with-cockroachdb-gorm.md]**
(https://github.com/cockroachdb/docs/blob/master/v2.1/build-a-go-app-with-cockroachdb-gorm.md)

- **There are exact same duplicates. I think one of them should be removed.**

<section class="filter-content" markdown="1" data-scope="insecure">

## Step 2. Create the `maxroach` user and `bank` database

{% include {{page.version.version}}/app/insecure/create-maxroach-user-and-bank-database.md %}

</section>

<section class="filter-content" markdown="1" data-scope="insecure">

## Step 2. Create the `maxroach` user and `bank` database

{% include {{page.version.version}}/app/insecure/create-maxroach-user-and-bank-database.md %}

**Comment by rmloveland** [comment]
Thanks for filing this issue @melrose98!

I have a fix in PR #4157 which we'll merge as soon as possible.
