### ISSUE TITLE
Transaction retries doc updates

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#4144]
In 2.2 there's two new things that need to be documented:
- there's now a cluster setting controlling how large a connection's buffer is before we stream results to the client (and we forfeit the ability to do automatic retries)
- some queries that return a single results (unique index select, limit 1) are guaranteed to not return retriable errors

**Comment by jseldess** [comment]
Thanks, @andreimatei! Will these changes be included in release notes? If so, I may end up creating separate issues for them and linking them here.

**Comment by jseldess** [comment]
Also, @sploiselle's the writer for core, so you can work with him on this, if you like.

**Comment by andreimatei** [comment]
The changes happened and I'm sure I wrote release notes in the respective commits. From there on, not sure.

**Comment by jseldess** [comment]
@andreimatei, is your first bullet the same as https://github.com/cockroachdb/docs/issues/4373? Do you still want to make any doc updates for this?

**Comment by andreimatei** [comment]
Almost. This was about a cluster setting that affects all new sessions. #4373 is about a session variable (except it's not a real session variable unfortunately; I think you can only set it through the connection string, not through a `SET` statement) that overrides the cluster setting, which was introduced more recently).

**Comment by jseldess** [comment]
Well, #4373 is actually a session variable, and this PR takes care of that: https://github.com/cockroachdb/docs/pull/4553

The cluster setting you're referring to is already in our docs: https://www.cockroachlabs.com/docs/dev/cluster-settings.html

Is that enough, or do you think the setting needs to be explicitly called out in our retry docs?

**Comment by jseldess** [comment]
@andreimatei, ping.

**Comment by andreimatei** [comment]
I think it'd be nice to say something about it in the retry docs, because the retry docs already talk about the size of the results buffer:
> CockroachDB automatically retries individual statements (implicit transactions) and transactions sent from the client as a single batch, as long as the size of the results being produced for the client (including protocol overhead) is less than 16KiB
> ... and continues
