### ISSUE TITLE
Add documentation for operating on multiple clouds

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4159]
Andy Woods (awoods187) commented:

https://forum.cockroachlabs.com/t/cockroach-clusters-across-multiple-cloud-providers/2241

We have several customers currently or are planning to do this--we should get out in front. 

Jira Issue: DOC-215

**Comment by jseldess** [comment]
cc @taroface, @piyush-singh, not sure if this is currently in focus.
