### ISSUE TITLE
bulkio: add SESSION_TOKEN to S3 config.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4174]
PR: https://github.com/cockroachdb/cockroach/pull/32455

From release notes:
> It is now possible to use AWS S3 temporary credentials for `BACKUP`/`RESTORE` and `IMPORT`/`EXPORT` using the `AWS_SESSION_TOKEN` parameter in the URL. [#32455][#32455] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via #4600
