### ISSUE TITLE
sql: automatically add index for fk constraint on empty table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4177]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwCRxl2NcZZqWlu3/recW0rpfQpLQy0nB1
PM: @awoods187 
Eng: @lucy-zhang 

PR: https://github.com/cockroachdb/cockroach/pull/32234

From release notes:
> An `ALTER TABLE` statement to add a foreign key constraint now automatically creates the necessary index if the referencing table is empty and the index does not already exist. [#32234][#32234] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed by #4599
