### ISSUE TITLE
cli/sql: make the final time printer more informative

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4185]
PR: https://github.com/cockroachdb/cockroach/pull/32663

From release notes:
> `cockroach sql` and other commands that print query results and query execution latency will now exclude the time required to prepare the display client-side from the latency measurement. [#32663][#32663] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @jordanlewis, this issue doesn't warrant a docs change.
