### ISSUE TITLE
Production-ready SCRUB tool

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4195]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recw7pJDSUG8LLA1B
PM: @rolandcrosby 
Eng: @lucy-zhang

**Comment by jseldess** [comment]
@rolandcrosby says this won't make it in for 2.2.

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
