### ISSUE TITLE
Preferring an index which is in the same locality

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4198]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/reciGBpx3eC5Vgc1g
PM: @awoods187 
Eng: @andy-kimball

**Comment by awoods187** [comment]
Make sure to specify you need enterprise license to take advantage of

**Comment by jseldess** [comment]
@rmloveland, this is the ticket for the topic we discussed in our 1:1 yesterday.

@awoods187, this is something that the optimizer just does automatically, right? Are you saying that it won't do this unless you have an enterprise license?

**Comment by awoods187** [comment]
Yes--you need to create per-index zones which is an enterprise feature in order to take advantage of the Optimizer doing this automatically.

So the docs issue should be to tell people to do this to make a global reference table (eg., zip codes) low latency

**Comment by jseldess** [comment]
OK, that makes sense. @rmloveland, here's pretty much the only mention of creating replication zone for secondary indexes, and it is called out as an enterprise feature: https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#create-a-replication-zone-for-a-secondary-index.
