### ISSUE TITLE
Improve Admin UI user experience for clusters up to 50 nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4201]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recI1Dx4y7FQi05HA
PM: @piyush-singh 
Eng: @couchand

**Comment by Amruta-Ranade** [comment]
As discussed with @celiala , we are not doing this for 2.2. Marking it as later.
