### ISSUE TITLE
Document open source workload generators (YCSB and Sysbench)

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4220]
Database evaluators are using familiar and widely available workload generators.  Often, scalability test is conducted with [YCSB](https://github.com/brianfrankcooper/YCSB) and [Sysbench](https://github.com/akopytov/sysbench).  

A common evaluation progression is to get familiar with the products by testing in a local environment.  Next step is a scale out testing in clouds or on-prem.  The final step might be to produce a scalability curve.   

The scalability curve typically show control on the x-axis which is usually the concurrency.  The results on the y-axis are TPS and response time.  On the infrastructure resource, CPU, RAM, IOPS, IO bandwidth, IO service queue  and Network bandwidth.  Most workloads are bound by CPU and RAM.  Write heavy workloads (insert, delete, updates) are bound by IOPS and IO bandwidth.   When the concurrency is push high in presence of resource limits, the TPS will start to drop.   [TPC-C blog](https://www.cockroachlabs.com/blog/cockroachdb-2dot1-performance/) demonstrates this with ![scalability curve]( https://d33wubrfki0l68.cloudfront.net/29bb1b7647b182925a0876483e6870fe7b94660f/cfd70/uploads/2018/11/cockroachdb2dot1_tpcc_3-node.png). 

Typical components necessary are workload generator, load balancer, database.  The components  can be single instance or distributed.  Single instance is common as it is easier test when they don't consume a lot of resource; however, distributed is necessary at extreme concurrency and scale. Below are detailed notes on configuring the workload generators.

| workload | single instance | distributed | geo partitioned |
| - | - | - | - |
sysbench | https://github.com/cockroachdb/docs/issues/4221 | https://github.com/cockroachdb/docs/issues/4222 | N/A |
ycsb |https://github.com/cockroachdb/docs/issues/4350 | https://github.com/cockroachdb/docs/issues/4436| https://github.com/cockroachdb/docs/issues/3574 |

**Comment by jseldess** [comment]
@johnrk, @mwang1026, @rmloveland, closing this for now. If this topics comes out of your Product Areas' problems to solve or priorities in the future, we can create a new issue with more context.
