### ISSUE TITLE
Document sysbench single node

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4221]
Examples below uses _sysb which is defined as a bash function available at the bottom of this doc.  

- [function test](###functional-test)
- [concurrency test of one workload](###concurrency-test-one-workload)
- [concurrency test of multiple workloads](###concurrency-test-multiple-workloads)
- [concurrency test of multiple workloads with transaction enabled](###concurrency-test-multiple-workloads-txn)

Couple of notes:
- CockroachDB has insecure and secure mode.  sysbench supports insecure mode for now.  Secure mode requires certification authentication which is not currently supported.
- Open `ssh` session
- Open CockroachDB admin UI
- `auto_inc` is `off` in most runs as CockroachDB generated numbers do start start from 1
- The performance listed here is for illustration purposes only.  The actual performance is dependent on hardware and database setup and other factors. 
- workload generator and database are running on the same hardware.  This will sometimes prevent prevent the workload generator from pushing the database as the CPUs is starved.  

### functional-test

- Start a [local CockroachDB cluster](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html)
- run one iteration
```
cockroach sql --insecure  -e "drop table if exists sbtest1"
_sysb oltp_read_write --auto_inc=off prepare
_sysb oltp_read_write --auto_inc=off run
_sysb select_random_points --auto_inc=off run
_sysb oltp_insert --auto_inc=off run
```
- take a look at CockroachDB Admin UI for workload and hardware metrics.  Hardware metrics are used to identify resource constraints that prevents better performance.   

  - `oltp_read_write --auto_inc=off prepare` will not register  
  - the first bump `_sysb oltp_read_write --auto_inc=off run`
  - the second bump is `_sysb select_random_points --auto_inc=off run`
  - the third bump is `_sysb oltp_insert --auto_inc=off run is` 

<img width="776" alt="screen shot 2019-01-07 at 1 55 32 pm" src="https://user-images.githubusercontent.com/6315124/50787314-13485000-1284-11e9-865f-cf1fb9ddedd0.png">
<img width="760" alt="screen shot 2019-01-07 at 1 55 57 pm" src="https://user-images.githubusercontent.com/6315124/50787316-13485000-1284-11e9-8437-dadf57f17ae4.png">

### concurrency-test-one-workload
- run the test by stepping the concurrency from 1,2,4,8,16,32,64 and 128
`
for t in 1 2 4 8 16 32 64 128; do 
  _sysb_threads=$t _sysb oltp_read_write --auto_inc=off run
  sleep 10 
done
`

- take a look at CockroachDB Admin UI for workload and hardware metrics

<img width="478" alt="screen shot 2019-01-07 at 2 35 41 pm" src="https://user-images.githubusercontent.com/6315124/50790210-4f7fae80-128c-11e9-8ea3-2e2d09f69bd1.png">

<img width="467" alt="screen shot 2019-01-07 at 2 36 01 pm" src="https://user-images.githubusercontent.com/6315124/50790193-42fb5600-128c-11e9-8985-024bc99a6967.png">

threads | CPU | TPS | P99 Latency (ms)
-- | -- | -- | --
1 | 14% | 1,800 | 1.2
2 | 24% | 3,100 | 1.7
4 | 46% | 5,900 | 2
8 | 80% | 9,300 | 4
16 | 79% | 8,700 | 6
32 | 79% | 9,100 | 9
64 | 77% | 8,300 | 23
128 | 75% | 6,900 | 54

- Using the information from the AdminUI, the following graphs show the relationship.  In order to understand the constraints, understanding of hardware and workload are required.  
  - the hardware has Intel i7 which has 4 physical cores.
  - workload is mostly read which will be CPU and RAM bound.   Typically CPU bound workload can scale to 2x to 4x the number of cores before degrading.  

The graphs show to 2x the CPU then degrading after that.

![chart 5](https://user-images.githubusercontent.com/6315124/50790074-e8fa9080-128b-11e9-9576-c6205936a3b6.png)
![p99 latency ms vs threads](https://user-images.githubusercontent.com/6315124/50790049-d4b69380-128b-11e9-810a-43a2c1bd5b03.png)

### concurrency-test-multiple-workloads

- `oltp_read_write` works off the primary index.  The ratio of read:update:delete:insert is 8:4:1:1 as fast as possible.
- `select_random_points` works off the secondary index.  rate is 10 per sec.
- `--rand-type=uniform` which reduces conflict for small dataset test

```
for t in 1 2 4 8 16 32 64 128; do 
  _sysb_threads=$t
 _sysb --rand-type=uniform  oltp_read_write \
    --point_selects=8 --non_index_updates=4 --delete_inserts=2 \
    --distinct_ranges=0 --index_updates=0 --order_ranges=0 --range_selects=off \
    --simple_ranges=0 --sum_ranges --auto_inc=off run &
   _sysb --rate=10 select_random_points --random_points=1  --auto_inc=off run &
  wait
  sleep 10
done
```

<img width="978" alt="screen shot 2019-01-07 at 3 58 15 pm" src="https://user-images.githubusercontent.com/6315124/50794808-2a923800-129a-11e9-8a71-07ec1096617a.png">
<img width="978" alt="screen shot 2019-01-07 at 3 58 23 pm" src="https://user-images.githubusercontent.com/6315124/50794809-2a923800-129a-11e9-9b64-89ca47b7f7ab.png">

### concurrency-test-multiple-workloads-txn

CockroachDB is serializable isolation only database.  Consistency violations are strictly prevented when multiple threads have read/write/update/delete on same rows.  

- `--skip_trx=off` which reduces conflict for small dataset test

```
for t in 1 2 4 8 16 32 64 128; do 
  _sysb_threads=$t
  _sysb --rand-type=uniform  oltp_read_write \
    --point_selects=8 --non_index_updates=4 --delete_inserts=2 \
    --distinct_ranges=0 --index_updates=0 --order_ranges=0 --range_selects=off \
    --simple_ranges=0 --sum_ranges --skip-txn=off --auto_inc=off run &
   _sysb --rate=10 select_random_points --random_points=1  --auto_inc=off run &
  wait
  sleep 10
done
```

<img width="977" alt="screen shot 2019-01-07 at 4 09 35 pm" src="https://user-images.githubusercontent.com/6315124/50794837-43025280-129a-11e9-9477-80ed63ac97ad.png">
<img width="981" alt="screen shot 2019-01-07 at 4 09 45 pm" src="https://user-images.githubusercontent.com/6315124/50794838-43025280-129a-11e9-9418-d3db46942eda.png">

### txn-on-off-compare

With transactions enables, there is some drop off in the TPS as seen below.

<img width="349" alt="screen shot 2019-01-07 at 4 10 21 pm" src="https://user-images.githubusercontent.com/6315124/50794345-e5213b00-1298-11e9-8a8c-bf5c49a7d8de.png">

Serializable Isolation at work to prevent data anomalies and these can ben seen.  The bottom chart shows the number of transactions.  The top chart shows how many transactions were prevented from return wrong results by having the transaction and serializable enabled.

<img width="621" alt="screen shot 2019-01-07 at 4 29 55 pm" src="https://user-images.githubusercontent.com/6315124/50794590-890ae680-1299-11e9-8ddd-cfbaa58344b9.png">

### txn-on-off-compare

With transactions enables, there is some drop off in the TPS as seen below.

<img width="349" alt="screen shot 2019-01-07 at 4 10 21 pm" src="https://user-images.githubusercontent.com/6315124/50794345-e5213b00-1298-11e9-8a8c-bf5c49a7d8de.png">

Serializable Isolation at work to prevent data anomalies and these can ben seen.  The bottom chart shows the number of transactions.  The top chart shows how many transactions were prevented from return wrong results by having the transaction and serializable enabled.

<img width="621" alt="screen shot 2019-01-07 at 4 29 55 pm" src="https://user-images.githubusercontent.com/6315124/50794590-890ae680-1299-11e9-8ddd-cfbaa58344b9.png">

Scripts:

- `_sysb` script

`sysb() {
sysbench --db-driver=pgsql --threads=${_sysb_threads:-1} --events=0 --pgsql-host=${_sysb_host:-localhost} --pgsql-port=${_sysb_port:-26257} --pgsql-user=${_sysb_user:-root} --pgsql-db=${_sysb_db:-defaultdb} --delete_inserts=${_sysb_inserts:-0} --index_updates=${_sysb_updates:-0} --non_index_updates=${_sysb_non_index_updates:-0} --table-size=${_sysb_table_size:-1222} --db-ps-mode=disable --report-interval=${_sysb_report_interval:-1} --histogram=on --time=${_sysb_time:-60} --debug=${_sysb_debug:-off} --verbosity=${_sysb_verbosity:-3} $*
}
`
- Replace the `localhost:port` of the custom chart below with the proper address of the AdminUI:

`http://localhost:26258/#/debug/chart?charts=%5B%7B%22metrics%22%3A%5B%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A1%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.txn.restarts.serializable%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A1%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.txn.autoretries%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A1%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.txn.abort.count%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A1%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.txn.rollback.count%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A1%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%7D%5D%2C%22axisUnits%22%3A0%7D%2C%7B%22metrics%22%3A%5B%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A1%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.txn.begin.count%22%7D%5D%2C%22axisUnits%22%3A0%7D%5D`

**Comment by robert-s-lee** [comment]
@jseldess I am using this page more frequently with customers.  @BramGruneir @glennfawcett check if this is useful.

**Comment by jseldess** [comment]
@johnrk, @mwang1026, @rmloveland, closing this for now. If this topics comes out of your Product Areas' problems to solve or priorities in the future, we can create a new issue with more context.
