### ISSUE TITLE
Lazy transaction records

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#4225]
@nvanbenschoten Do we have a tech note or anything to use as a reference for this, or should we grab some in-person time?

**Comment by nvanbenschoten** [comment]
This change's corresponding RFC is [here](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20181209_lazy_txn_record_creation.md). I don't think we need any explicit documentation on this and I don't think the word "lazy transaction record" should show up in our docs. Instead, we should go back and update the documentation on distributed transactions (including your new doc!). The only real change is that we no longer create the transaction record at the beginning of a transaction. Instead, we write it at the end of a transaction with the "switch" already flipped to COMMITTED.

**Comment by jseldess** [comment]
@sploiselle, is this resolved by https://github.com/cockroachdb/docs/pull/4397?

**Comment by jseldess** [comment]
Closing, since the corresponding PR was merged.
