### ISSUE TITLE
BACKUP example URL's need to be updated

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#4228]
https://www.cockroachlabs.com/docs/stable/backup.html#example-file-urls

the "Example file URLs" all include `employees.sql` as the destination for the backup but this can cause a bit of confusion.  `BACKUP` is really writing to a "path" and creating files and subdirectories in that path.  By including `employees.sql` as the "path" it suggests that `BACKUP` is generating a file called `employees.sql` which is not the behavior.   Where as i would expect cockroach to create and populate a file called `employees.sql` the actual behavior is that the destination path must exist on disk prior to calling the command and have the proper permissions.  I think we need to be more explicit about what we require to on disk (permissions) and what is created when a backup is executed.

**Comment by jseldess** [comment]
@lhirata, I suspect we're using an include for the `Example file URLs` section across the import, backup, and restore docs, and that we'll need to create statement-specific examples instead. I think the current examples are import-specific, but I could be wrong.

**Comment by mwang1026** [comment]
Already addressed https://www.cockroachlabs.com/docs/v20.2/use-cloud-storage-for-bulk-operations
