### ISSUE TITLE
Backup and Restore a managed cockroachDb cluster [Managed Console]

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4240]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recMqMMMAa40NtWXw
PM: @mwang1026 , @kannanlakshmi 
Eng:

**Comment by lhirata** [comment]
This isn't really a 19.1 issue - might want to rethink issue labeling for MSO.
