### ISSUE TITLE
On-page links break when url ends with /

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4243]
https://www.cockroachlabs.com/docs/stable/set-transaction.html/

**Comment by jseldess** [comment]
@mjibson, @j-low, this is actually a broader problem than I initially thought. If you add a `/` to the end of any docs page URL, all of the links on the page break. Examples:

https://www.cockroachlabs.com/docs/stable/set-transaction.html/
https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html/

That final `/` seems to change all on-page links to include the current page in the target link path. So a link that should be `https://www.cockroachlabs.com/docs/stable/start-a-node.html` ends up `https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html/start-a-node.html`.

Any ideas what's happening?

**Comment by mjibson** [comment]
ok i think what may have happened is when the original link was posted into slack someone accidentally pushed `\` right before enter. I'm just going to close this unless someone knows for sure that those bad links are showing up somewhere.
