### ISSUE TITLE
pgwire: support hba.conf auth configuration

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4252]
PR: https://github.com/cockroachdb/cockroach/pull/32892

From release notes:
> Added support for configuring authentication via an `hba.conf` [cluster setting](../v2.2/cluster-settings.html). [#32892][#32892] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Need to add it to cluster settings page.

**Comment by jseldess** [comment]
This has to be done in cockroach repo. I can explain more in person

**Comment by Amruta-Ranade** [comment]
Check with eng about the setting

**Comment by jseldess** [comment]
Already in our live 19.1 docs: https://www.cockroachlabs.com/docs/dev/cluster-settings.html. Has a different name: `server.host_based_authentication.configuration`.
