### ISSUE TITLE
sql: Add default_int_size to control INT alias

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4254]
PR: https://github.com/cockroachdb/cockroach/pull/32848

From release notes:
> Added the `default_int_size` [session variable](../v2.2/set-vars.html) and `sql.defaults.default_int_size` [cluster setting](../v2.2/cluster-settings.html) to control how the `INT` and `SERIAL` types are interpreted. The default value, `8`, causes these types to be interpreted as aliases for `INT8` and `SERIAL8`, which have been the historical defaults for CockroachDB.  PostgreSQL clients that expect `INT` and `SERIAL` to be 32-bit values can set `default_int_size` to `4`, which will cause `INT` and `SERIAL` to be aliases for `INT4` and `SERIAL4`. Please note that due to issue [#32846](https://github.com/cockroachdb/cockroach/issues/32846), `SET default_int_size` does not take effect until the next statement batch is executed. [#32848][#32848] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #4317
