### ISSUE TITLE
opt: support string_agg

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4257]
PR: https://github.com/cockroachdb/cockroach/pull/33172

From release notes:
> The `string_agg()` aggregate function is now supported by the [cost-based optimizer](../v2.2/cost-based-optimizer.html). [#33172][#33172] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@awoods187 I don't think this specific BIF having optimizer support needs to be mentioned in the docs. 

Do you agree with that assessment?

**Comment by jseldess** [comment]
I just peeked as well and agree there's no doc work here. Closing. @awoods187, ping if you want this re-opened.
