### ISSUE TITLE
opt: Add optimizer support for UPSERT and INSERT..ON CONFLICT statements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4264]
PR: https://github.com/cockroachdb/cockroach/pull/33339

From release notes:
> The new `experimental_optimizer_updates` [cluster setting](../v2.2/cluster-settings.html) controls whether `UPDATE` and `UPSERT` statements are planned by the cost-based optimizer rather than the heuristic planner. Also note that when the setting is set, check constraints are not checked for rows skipped by the `INSERT ... DO NOTHING` clause. [#33339][#33339] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This was done as part of the work that closed #3998 and is already live in [the CBO docs](https://www.cockroachlabs.com/docs/dev/cost-based-optimizer.html#types-of-statements-supported-by-the-cost-based-optimizer).
