### ISSUE TITLE
Document that BYTES can use normal chars

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#427]
`select b'123'` works fine. The current BYTES docs page implies it's only valid with octets and hex digits.

**Comment by jseldess** [comment]
@mjibson, @knz, can either of you help me understand when you'd want to use an escape format and when a text format for a `BYTES` column? Is it just a matter of preference, or are there other considerations (sorting, etc.)?

**Comment by mjibson** [comment]
In general, if being manually typed by a human: you will use escape bytes for any character that's not on your keyboard, and the actual character otherwise. Just so there's no confusion, you can do both at the same time:

`select b'12\x01HELLO\xff\xab'` is valid.'
