### ISSUE TITLE
Add ALTER PARTITION page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4278]
We have a page on the [`CONFIGURE ZONE`](https://www.cockroachlabs.com/docs/stable/configure-zone.html) subcommand that includes working with zone configs for partitions, but we're missing the page for the top-level `ALTER PARTITION` statement. 

This page should just redirect users to `CONFIGURE ZONE` (and any other available subcommands of `ALTER PARTITION`, though I don't think there are any), like we do for [`ALTER DATABASE`](https://www.cockroachlabs.com/docs/stable/alter-database.html) and other `ALTER` statements.

**Comment by jseldess** [comment]
Also, `ALTER PARTITION` seems to be missing form the [full sql grammar](https://www.cockroachlabs.com/docs/stable/sql-grammar.html#alter_ddl_stmt) page. We should fix that as well.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

**Comment by solongordon** [comment]
Fixed by #5871
