### ISSUE TITLE
Training notes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#4282]
I gave the current training content to an audience of 10 two weeks ago. Here are some rough notes:

- The audience was mainly windows users. We really need to add first-class windows support for this training.
  - Instead of using a local VM, they were running linux VMs on AWS. We told them beforehand this would be OK, but forgot that this would complicate access to the admin UI.
  - Opening multiple terminal windows is awkward (and exacerbated by the use of remote VMs). There's little rhyme or reason about which modules use multiple terminals and which run everything in the background of a single terminal. I'd generally recommend making everything run in a single terminal.
- As presenter, it was awkward juggling my browser and terminal windows. I first tried to split my screen with the docs on top and the terminal below, but there's a lot of fixed-size navigational cruft on the docs site that takes up screen real estate here. Splitting the screen vertically worked better for the docs (because when the window is narrow enough it switches to "mobile" mode and loses the nav cruft), but it meant a lot of ugly line wrapping in the terminal. We may want to think about a "presenter view" of this content with presentation-like formatting.
- The new k8s content should probably be moved to the end. It references a lot of more advanced topics (security, decomissioning) that haven't been introduced at its current point in the sequence. 
  - The k8s module doesn't fully clean up after itself - it remembered past CSR approvals and skipped that step the second time I ran through it. 
  - The slides that accompany the k8s module say it runs in insecure mode, although that has changed now.
- The new TPCC module takes too long (10m setup and 5m to run) for a classroom setting. It should probably use an even smaller dataset and shorter benchmark run (or at least interleave the prep work with other modules)
- The process of wiping and recreating a cluster for most (but not all) modules is tedious. I'd like to reuse clusters more. Maybe even rearrange the content to support this: move all the locality-related content to the end, so that you can get through most of the content with a single 3-node cluster, then go through the last module with a 9-node cluster.
  - Similarly, there are a lot of different datasets, all generated differently. It would be nice to standardize on one (movr?)
- It would be nice to use env vars as much as possible so the client commands aren't as repetitive (I'd like to see this change throughout the docs). Maybe also use the interactive sql shell more instead of `cockroach sql -e`.
- The "how CRL debugs" presentation should be updated to talk about the gear icon and debug page index
  - A module on the statements page and basic perf tuning would be nice. 
- The SQL Basics module breaks the flow of the training. It feels like it's just running through a random subset of sql functionality. It's more dev-y than ops-y and I'm not sure it's going to be useful to the same audience as the rest of the training. We might just want to get rid of it, but if we keep it I'd move it earlier in the sequence.
- For secure clusters (including the k8s and node startup troubleshooting modules), a username/password is now required to access the web UI. We need to make sure to create one for each module that uses secure mode (another reason to try and reuse clusters as much as possible).
- Decommissioning is a surprisingly hot topic, with lots of questions about it from early on. It's currently introduced near the very end; I think we should probably move it as early as the fault tolerance module.

**Comment by jseldess** [comment]
We're not longer using or maintaining the content for the live training, so closing this for now.
