### ISSUE TITLE
GORM example doesn't include fund transfer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4283]
As pointed out by a user, the [GORM example](https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb-gorm.html#step-4-run-the-go-code) does not include the transaction logic to transfer funds. See the [Go pq](https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb.html#transaction-with-retry-logic) or [SQLAlchemy](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html#step-4-run-the-python-code) samples for comparison.

**Comment by rmloveland** [comment]
Fixed in https://github.com/cockroachdb/docs/pull/5084
