### ISSUE TITLE
Reference IMPORT PGDUMP "ignore foreign keys" option in docs for `cockroach dump`

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#4284]
We taught `IMPORT PGDUMP` to handle the dump files written by `cockroach dump`, and the docs have a brief reference to this (see #4029). We should add an explicit note to the `cockroach dump` docs to indicate that `IMPORT PGDUMP` is the best-supported way to bring in `cockroach dump` data. We should also note that the `WITH skip_foreign_keys` option may be necessary, if the user wants to import a subset of the data that is affected by foreign key constraints.

**Comment by jseldess** [comment]
Closing since `cockroach dump` has been deprecated.
