### ISSUE TITLE
Frequently Asked Questions Doc Update - perfformance of writes in geo-dist setting

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#4286]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//v2.1/frequently-asked-questions.html)

## Issue Description

Users on gitter and elsewhere who ask "if there are multiple nodes in different places, does that mean I need to pay the price of a world-wide latency when I modify data?"

No FAQ on this yet.

## Suggested Resolution 

New FAQ saying:

- only a quorum is required to acknowledge a write (with reference to relevant section of arch docs)
- in case the use case requires fast writes in every region (to local data) we recommend partitioning (with links to relevant docs) although there's currently a known limitation where apps must specify the index explicitly during mutations (`INSERT INTO tbl@idx_in_region ...`)

**Comment by jseldess** [comment]
@rmloveland, @awoods187, I'm closing this for now, since we're completely refactoring multi-region in 21.1, but it's worth considering whether we need a multi-region FAQ, or at least an addition to the main FAQ.
