### ISSUE TITLE
Document query execution processors

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4288]
Currently our [`EXPLAN (DISTSQL)`](https://www.cockroachlabs.com/docs/v2.1/explain.html#distsql-option) output shows a diagram of a query plan that uses a bunch of SQL execution nodes (e.g., `TableReader/0`, `Aggregator/6`, etc.) that are not documented anywhere.

We should, like, document them.

Estimated scope of work:

- Add documentation listing the set of processors and what each of them does/means, along with examples showing them used in the context of full queries which output multiple nodes in `EXPLAIN (DISTSQL)`.

See also:

- [Spanner query execution operators docs](https://cloud.google.com/spanner/docs/query-execution-operators?hl=en_US)

**Comment by knz** [comment]
Let's be mindful of terminology: spanner calls these "operators" but this term is overloaded and ambiguous in the field (also it's a symptom of NIH syndrome at Google)

The word "processor" used in cockroachdb is more ubiquitous.

See also the nuances detailed here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/56098854/SQL+Syntax+semantics+Menagerie

**Comment by jordanlewis** [comment]
I disagree with Raphael on operators vs processors. Processor is something that we made up. Operator is what everybody in the databases field calls them.

And, we don't want to document the physical processors. We want to document the logical plan components, that you see in explain - the operators.

**Comment by knz** [comment]
We want to describe also what comes out of explain(distsql).
Relational operators have 0 or more operands and 1 result.
The things that come out of explain(distsql) often have more than one output


Ergo, the things in explain(distsql) are not operators.

Moreover, the distsql physical plan is a dataflow network.
There's an entire field of computer theory called dataflow science. In that field the nodes in such a network are called processes. The templates to instantiate these precesses are often called processors (or programs).

I stand my ground.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ericharmeling** [comment]
I recently updated the processor descriptions at https://www.cockroachlabs.com/docs/v20.2/explain-analyze#distsql-plan-viewer. If that work is insufficient, please re-open this.
