### ISSUE TITLE
Repeated updates to a row can cause issues

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4295]
Users should know that because we’re MVCC, we keep a history of every SQL row. This means that repeated updates to a row will preserve history, and this history can’t grow without bound. It can only grow to the size of a single range before causing issues.

I ran into this in a python app I'm building where I was repeatedly trying to update a text column, with the value growing in size with each update. Too many repetitions caused this error:

```
psycopg2.InternalError: split failed while applying backpressure: could not find valid split key
```

Same problem is reported [here](https://github.com/cockroachdb/cockroach/issues/30956#issuecomment-427189107), but in my case, it's pure user error.

We should figure out a place to cover this in our docs, perhaps in the SQL best practices. In essence, not a good idea to do frequent updates to a single row. 

Thanks, @nvanbenschoten and @tbg for helping me understand this.

**Comment by tbg** [comment]
Not sure if this would've helped, but it certainly wouldn't have hurt:

https://github.com/cockroachdb/cockroach/pull/34295

**Comment by nvanbenschoten** [comment]
> We should figure out a place to cover this in our docs, perhaps in the SQL best practices. In essence, not a good idea to do frequent updates to a single row.

My concern with the SQL best practices is that they're not about general SQL, they're specifically about performance. Perhaps this would be better suited for the SQL FAQs: https://www.cockroachlabs.com/docs/stable/sql-faqs.html/.

**Comment by jseldess** [comment]
As part of this work, we should also update the [error message](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/replica_backpressure.go#L156) to link to the relevant docs.
