### ISSUE TITLE
Search returns blank results page intermittently (but regularly)

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4296]
I'm seeing blank search results intermittently, but on a regular basis.

For example, browsing directly to https://www.cockroachlabs.com/docs/search.html?q=optimizer results in an empty results page _unless_ I have already visited some particular docs page on the site (e.g., [Perf best practices](https://www.cockroachlabs.com/docs/v2.1/performance-best-practices-overview.html) ).

If I have browsed to a particular docs page (such as the best practices link above), and I then visit the above search URL directly, I get results.  Browsing to an actual page seems to set some kind of state that search cares about (?).

The "workaround" is to spend a few seconds clicking through the TOC to an actual docs page whenever I see the blank results, and then run my search again.

As a user, my desired state of affairs is that visiting a search URL (such as via a browser bookmark) does not result in different results depending on some state that I'm not aware of.

Sorry if this is a dupe, I searched and didn't find any open issues about this.

**Comment by jseldess** [comment]
@j-low, another search issue for you. Not sure if we already have a similar issue open. If so, feel free to close.

**Comment by j-low** [comment]
@jseldess @rmloveland thanks for the heads up.  This is definitely strange and I'm not sure what to make of it yet but I'll see if I can reproduce and investigate.  

One thing that occurs to me is that this is happening on our search index which lives on the DocSearch app administrated by Algolia.  The downside is that this mean we don't have analytics or logs available to us however this will be solved once we complete the migration to using an index hosted on our own app.

**Comment by rmloveland** [comment]
Thank you @j-low !!!

**Comment by jseldess** [comment]
Closing this for now. Let's reopen if we still see this happening, especially after upgrading to the paid search service.
