### ISSUE TITLE
Transaction retry guidance for Hibernate

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4297]
Hibernate follow-up to https://github.com/cockroachdb/docs/issues/3315.

**Comment by jseldess** [comment]
As discussed with @awoods187, @rmloveland, and @timveil, moving this to later, pending further Product work.

**Comment by rmloveland** [comment]
See discussion in https://github.com/cockroachdb/cockroach/issues/27274 for some example code

**Comment by jseldess** [comment]
@rmloveland, is this out of scope for 19.2 at this point, given that we are de-emphasizing savepoint?

**Comment by rmloveland** [comment]
@jseldess I think integrating the SAVEPOINT protocol with Hibernate will be too large / difficult for 19.2.

However I think it's possible that I can update the Hibernate example with an "app-level retry loop" as part of #5035 (probably the last work item for that ticket we can get in for 19.2 before moving on to product work).

**Comment by awoods187** [comment]
+1 @rmloveland We should only deemphasize savpoint with hibernate (but show how to do it via #5035 ) for 19.2

**Comment by rmloveland** [comment]
@awoods187 the [Java/Hibernate page](https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb-hibernate.html) shows how to write a retry loop.  That work would seem to cover "transaction retry guidance for Hibernate".  Any objection to closing this?

**Comment by awoods187** [comment]
I'm good @rafiss are we missing anything else here?

**Comment by rafiss** [comment]
This looks fine to close, to me.
