### ISSUE TITLE
sql: EXPLAIN statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#430]
Document the `EXPLAIN` statement.

Some nuggets from Gitter:

kena @knz Jun 30 16:16
guys
who invented explain(debug)?
who can explain what it is supposed to do and what its output means?

RaduBerinde @RaduBerinde Jun 30 16:19
it is supposed to show the exact keys and values that are processed
i can answer any specific questions
the columns are rowid, key, value, and the last one indicates if the key corresponds to the end of a row, and if so what happens to that row (filtered, buffered, or a result)

kena @knz Jun 30 16:22
what do you mean with "processed"?
what does filtered mean? what does buffered mean?

RaduBerinde @RaduBerinde Jun 30 16:26
the SQL layer does KV ops and receveis KVs, right? then our code processes those KVs to form rows and whatnot
the debug output has an entry for each KV that our code looks at
filtered means that a row is thrown out because of a filter like WHERE
buffered means it is stored in memory in some node (e.g. sortNode). it willl show up again if that node outputs it

kena @knz Jun 30 16:28
aha
ok this becomes clearer now
but here you're talking about k/v reads
what about writes?

RaduBerinde @RaduBerinde Jun 30 16:32
reads. i have never used it on anything other than a SELECT, I am not sure if it even works

kena @knz Jun 30 16:32
yeah
ok

**Comment by knz** [comment]
Another nugget from Gitter:

(18:34) < knz> @jseldess regarding explain. I'd recommend explaining (hah!) explain(plan) and explain(types), which are both useful to end users. Then simply 
               mention that explain(trace) and explain(debug) also exist but are mostly for our internal use. Then invite the reader to come and ask on 
               gitter if they think they need to know.

**Comment by jseldess** [comment]
Explain now works correctly for `VALUES` containing subqueries. https://github.com/cockroachdb/cockroach/pull/8970. If relevant, you can just wrap this into your open work on `EXPLAIN`, @sploiselle.

**Comment by jseldess** [comment]
Additional improvements to `EXPLAIN` in https://github.com/cockroachdb/cockroach/pull/12506.

**Comment by knz** [comment]
Hold onto EXPLAIN for a little bit, there's a rather larger change upcoming.

**Comment by jseldess** [comment]
K. Thanks, @knz.

**Comment by jseldess** [comment]
Latest improvements have landed: https://github.com/cockroachdb/cockroach/pull/12553

**Comment by jseldess** [comment]
More improvements: https://github.com/cockroachdb/cockroach/pull/12637
