### ISSUE TITLE
Clarify minimum requirements: Production Checklist Doc Update 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#4301]
Re: [Production Checklist](https://cockroachlabs.com/docs//v2.1/recommended-production-settings.html)

## Issue Description
We talk about min CPU requirements. Do we mean 2 scheduling units (ie vCPUs/hyperthreads) or do we actually mean two physical cores (in which case we may have 4 vCPUs as the minimum)?

## Suggested Resolution 
Please clarify the minimum requirements. 

cc @jseldess

**Comment by bdarnell** [comment]
Yes, I would avoid the word CPU because it's ambiguous: it's used both for the low-level scheduling units (vCPUs) and the high-level physical chip.
