### ISSUE TITLE
Cluster sizing and hardware calibration

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4303]
Jesse Seldess commented:

This will be an internal product marketing engineering project first to create a sustainable well to generate good numbers and guidance. Eventually, this might make it into customer-facing docs.

See: https://docs.google.com/document/d/1RUdDcE6jQfA9QzMLFZ2ta2JWK1D-mJ7afABAluQXtAo/edit#heading=h.4chbev4vd0oz

Jira Issue: DOC-228

**Comment by jseldess** [comment]
@robert-s-lee, @timveil, @rkruze, @drewdeally, please give a thumbs up if the above makes sense; otherwise, add comments to help me clarify this work.

**Comment by jseldess** [comment]
In describing the characteristics of a workload, we should be sure to include expected txn retry ratios.

**Comment by jseldess** [comment]
Meeting schedule to discuss next steps here.

**Comment by jseldess** [comment]
@Amruta-Ranade, how much does this overlap, or not, with your performance scaling project? https://github.com/cockroachdb/docs/issues/5155

**Comment by Amruta-Ranade** [comment]
Significant overlap, I'd say.
