### ISSUE TITLE
Performance Benchmarking with TPC-C Doc Update 

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#4305]
Re: [Performance Benchmarking with TPC-C](https://cockroachlabs.com/docs//v2.1/performance-benchmarking-with-tpc-c.html)

## Issue Description

This doc recommends using a cluster of 16-cpu nodes to run TPCC-1000. I think this is based on older versions of CRDB; it is now possible (according to @awoods187) to run TPCC-1000 on 8-CPU machines. 

## Suggested Resolution 

Update this page (and maybe others?) to use n1-highcpu-8 instances when running TPCC-1000. Consider doing the same for TPCC-10k, although this probably needs to be confirmed first.

**Comment by jseldess** [comment]
@awoods187, since the performance benchmarking doc is gcp-specific, does your comment above mean there's no action to take here and we should close?

**Comment by awoods187** [comment]
@jseldess yes that's my view. But, we might either want to switch to AWS (to show better performance) or at least show it in conjunction with GCP so that the nuance can be seen. That is a larger project and can likely be kicked down the road a bit to post 2.2

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5475.
