### ISSUE TITLE
Document Transaction Retry Errors emitted by Postgres Drivers

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#4306]
When running a Java app it is quite common to see the following errors from the Postgres Driver: 

```org.postgresql.util.PSQLException: ERROR: restart transaction: HandledRetryableTxnError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY):```

Or 

```ERROR: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE):```

We should document these and state that the user needs to make use of client-side transactions retry logic.

**Comment by jseldess** [comment]
@rmloveland, @awoods187, any chance this will be covered by the current transaction retry doc project?

**Comment by awoods187** [comment]
I think one of the outputs from @bdarnell and @rmloveland 's work will be to produce a list of all of the possible errors along with an explanation of why they occur and if any action can be taken to reduce them

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5476.
