### ISSUE TITLE
Write multi-region EKS (Amazon) Kubernetes tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4314]
Our current multi-k8s deployment guidance focused on GKE and requires a stable public load balancing IP to hook together DNS servers from different clusters. As seen on our forum, this approach  might not be possible on AWS, and as @bdarnell has mentioned, there are probably other, better options for achieving what we want anyway. 

- We should identify the right way to load balancer across multiple k8s clusters, likely via a load balancer hostname that is resolvable and routable from all the clusters. 
- We should then create a separate tutorial for AWS, and consider updating the GKE tutorial and configs.

**Comment by realvz** [comment]
Hi, 
Are you still looking to write a tutorial for EKS? If yes we can collaborate and publish it on AWS container blog.

**Comment by taroface** [comment]
@realvz, this is definitely still planned, and we'd definitely be interested in collaborating. Would you mind emailing me at ryank@cockroachlabs.com, or letting me know how I can reach you directly?

**Comment by realvz** [comment]
@taroface You should have an email from me.

**Comment by taroface** [comment]
@realvz just followed up with you!
