### ISSUE TITLE
Add docs on contention errors (ReadWithinUncertaintyIntervalError). Why they exist and how to handle and reduce them

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4331]
In https://github.com/cockroachdb/cockroach/issues/34517, it became apparent that receiving contention errors like ReadWithinUncertaintyIntervalError can be quite confusing to our users. 

As discussed in https://github.com/cockroachdb/cockroach/issues/34517, this process is working by design. We should explain that retry errors are always possible and users need to be prepared to address them via retry loops in their application, if they do not already have one. Note that retry loops are good hygiene for any application even if they were to not use CRDB. (Let's make sure this point itself is a well covered in docs). We should also explain how CRDB has worked to reduce the number of these errors. 

The first select in any transaction can return an uncertainty error. 

https://github.com/cockroachdb/cockroach/issues/34517 reminded us that the second select can also cause an uncertainty error. The uncertainty window has decreased between the first select and the second but it is not zero and therefore can trigger this occurrence. While it will be rare to see a transaction with the same select twice, foreign key checks can create an implicit second select which can also demonstrate this behavior. 

The longer a transaction goes, the less likely it is for a user to experience this error. This is because while the amount of concurrent data can increase, it is significantly outweighed by the reduction in the uncertainty window. 

To address these contention errors users can:
- Redesign their schema and queries to reduce contention (beneficial for performance as well)
- Read at historical time stamps using AS OF SYSTEM TIME

**Comment by bdarnell** [comment]
> [cockroachdb/cockroach#34517](https://github.com/cockroachdb/cockroach/issues/34517) reminded us that the second select can also cause an uncertainty error.

It was always clear that the second select in a transaction could cause an uncertainty error if it touched different data. The surprising part of 34517 is that a second read of *exactly the same data* can return an uncertainty error even if it had previously succeeded in the same transaction.

**Comment by awoods187** [comment]
We also need to note that CRDB users will see this error more than in another database that offers serializability because of geo-distribution. Uncertainty is a concept that only comes into play in a distributed database--in a non-distributed database, it's cheap to globally order everything.

**Comment by rmloveland** [comment]
When https://github.com/cockroachdb/docs/pull/4321 merges it will add some infrastructure to the docs site (a new txn retry page) that will make addressing this issue easier as well.  (For reference when this gets worked on.)

**Comment by rmloveland** [comment]
Everything from this issue except the exact error string `ReadWithinUncertainty...` was added in #4402, AFAICT.
