### ISSUE TITLE
Provide guidance on using heterogeneous clusters

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4338]
Andy Woods (awoods187) commented:

Some customers want to create clusters with mixed cpus. This can cause problems as CRDB often expects homogenous nodes--we can help explain how to do this better in production. 

Customers can use numa zones to avoid issues with different nodes.

CC @rkruze who had a good workaround 

Jira Issue: DOC-236

**Comment by jseldess** [comment]
In our production checklist, we say:

> To ensure consistent SQL performance, make sure all nodes have a uniform configuration.

@nvanbenschoten, do we want to ever encouraging heterogeneous nodes?

**Comment by nvanbenschoten** [comment]
> do we want to ever encouraging heterogeneous nodes?

Unless someone is a power user and knows exactly what they're doing with zone configurations, we should not recommend heterogeneous nodes to them. Internally, CRDB does not do a good job making balancing decisions in these setups.

**Comment by mdlinville** [comment]
This is already addressed by https://github.com/cockroachdb/docs/pull/16354.
