### ISSUE TITLE
Extra release note for the next 2.2 (after 0211)

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#4345]
This:

> (sql change) The generation algorithm for the OID column for tables in `pg_catalog` has been modified. As with previous CockroachDB releases, we guarantee that the OID values are consistent between `pg_catalog` tables (so that tables can be joined together) but we do not guarantee that they are stable across CockroachDB versions. Avoid storing them in client apps.

**Comment by jseldess** [comment]
Including this in next Monday's release candidate. Forgot to in the previous beta. What's the source PR for this change, @knz?

**Comment by knz** [comment]
That would be #33697.

**Comment by jseldess** [comment]
Thanks, @knz.
