### ISSUE TITLE
Rename parameters in CREATE INDEX diagram

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#435]
To add clarity to the docs, let's rename the parameters in the [`CREATE INDEX`](https://cockroachlabs.com/docs/create-index.html) diagram as follows:

Current Name | New Name
--------------------|---------------
`name` (first instance) | `index_name`
`name` (second instance) | `column_name`
`name` (third instance) | `column_name`
`qualified_name` | `table_name`

@sploiselle

**Comment by sploiselle** [comment]
LGTM – didn't realize those strings themselves were configurable!

**Comment by jseldess** [comment]
Yeah, I should write up how to change these. In this case, though, since multiple parameters are named identically, Matt's going to have to do some fancy regex to make this work. Once he's done that, we can use it as a model for similar changes in the future.

**Comment by jseldess** [comment]
@sploiselle, you can update your pr branch to get this change.
