### ISSUE TITLE
Document open source YCSB single node

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4350]
Examples below uses _sysb which is defined as a bash function available at the bottom of this doc.

* [function test](###functional-test)
* [concurrency test of one workload](###concurrency-test-one-workload)
* [concurrency test of multiple workloads](###concurrency-test-multiple-workloads)

Couple of notes:

* Open `ssh` session
* Open CockroachDB admin UI
* YCSB has workloads a,b,c,d,e,f.  Workloads D and E during the test run making them [not entrant](https://github.com/brianfrankcooper/YCSB/wiki/Core-Workloads). The recommended sequence load a, run a,b,c,f,d load e, run e
* `insertorder=ordered` as CockroachDB's sharding does not require hashed primary key. 
* The performance listed here is for illustration purposes only.  The actual performance is dependent on hardware and database setup and other factors.
* workload generator and database are running on the same hardware.  This will sometimes prevent prevent the workload generator from pushing the database as the CPUs is starved.
* use the latest (0.16 snapshot) YCSB which has support [multi-row insert](https://github.com/brianfrankcooper/YCSB/pull/1220)

### functional-test
* Start a [local CockroachDB cluster](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html)
* run one iteration

```
cockroach sql --insecure  -e "drop table if exists usertable"
_ycsb load a
_ycsb run a

```
* take a look at CockroachDB Admin UI for workload and hardware metrics.  Hardware metrics are used to identify resource constraints that prevents better performance.

<img width="931" alt="screen shot 2019-02-11 at 3 45 54 pm" src="https://user-images.githubusercontent.com/6315124/52592688-0d123a00-2e15-11e9-8a1f-2ac071110642.png">
<img width="830" alt="screen shot 2019-02-11 at 3 46 08 pm" src="https://user-images.githubusercontent.com/6315124/52592787-4cd92180-2e15-11e9-8ef1-0afa387e10eb.png">
<img width="1132" alt="screen shot 2019-02-11 at 3 51 24 pm" src="https://user-images.githubusercontent.com/6315124/52592726-261aeb00-2e15-11e9-925e-1bd1cdc205de.png">

* the first bump `_ycsb load a`.  Note each insert statement contains 500 rows.  
* the second bump is `_ycsb run a`

### concurrency-test-one-workload
- run the test by stepping the concurrency from 1,2,4,8,16,32,64 and 128
```
for t in 1 2 4 8 16 32 64 128; do 
  _ycsb_threads=$t; _ycsb run b
  sleep 10 
done
```

### concurrency-test-multiple-workloads
```
for t in 1 2 4 8 16 32 64 128; do 
  _ycsb_threads=$t
  _ycsb run a &
  _ycsb run b &
  _ycsb run c &
  _ycsb run f &
  wait
  sleep 10
done
```

[ycsb.sh.zip](https://github.com/cockroachdb/docs/files/2853265/ycsb.sh.zip)

**Comment by jseldess** [comment]
@robert-s-lee, does this tie into the larger project to show how to use cockroach workloads to calibrate a cluster? https://github.com/cockroachdb/docs/issues/4303

Or is this something distinct?

**Comment by robert-s-lee** [comment]
https://github.com/cockroachdb/docs/issues/4220 is the master issue to document YCSB and sysbench.  Two purposes:  one is to document YCSB ad sysbench, the other is to step through the methodology of starting with a functional test, then adding more concurrency gradually before going too big.

**Comment by jseldess** [comment]
@johnrk, @mwang1026, @rmloveland, closing this for now. If this topics comes out of your Product Areas' problems to solve or priorities in the future, we can create a new issue with more context.
