### ISSUE TITLE
changefeed: add `envelope=wrapped` support everywhere and make it the default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4358]
PR: https://github.com/cockroachdb/cockroach/pull/34309

From release notes:
> The `CHANGEFEED` `envelope=row` option is now deprecated and will be removed in the Fall 2019 release. The default envelope for new changefeeds is now `wrapped`. [#34309][#34309] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@lhirata, is this done already or covered by another issue? If so, feel free to close.

**Comment by lhirata** [comment]
Closed by #3992
