### ISSUE TITLE
Recommended Production Settings

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#436]
Page to list recommendations for production environments. 

Possible topics:
- [File descriptor limits](https://github.com/cockroachdb/docs/issues/53)
- Clock synchronization

For reference:
- Cassandra's [production recommendations](https://docs.datastax.com/en/cassandra/2.0/cassandra/install/installRecommendSettings.html)

**Comment by jseldess** [comment]
@bdarnell, @cuongdo, @mberhault, @petermattis, @spencerkimball, @jordanlewis, I'd like help identifying essential topics for a page on production recommendations. The two I know of right now are file descriptor limits and clock synchronization. Please add any other important topics to this ticket.

**Comment by BramGruneir** [comment]
For OSX:
Programmatically, there is a hard limit of 10,240, it can be changed, but we should show a warning if we are below the recommended settings:
http://krypted.com/mac-os-x/maximum-files-in-mac-os-x/

**Comment by BramGruneir** [comment]
For CentOS:
http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/
For Ubuntu:
https://underyx.me/2015/05/18/raising-the-maximum-number-of-file-descriptors
For windows:
https://serverfault.com/questions/249477/windows-server-2008-r2-max-open-files-limit
