### ISSUE TITLE
sql: run check constraint mutations and validation by schema changer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4362]
PR: https://github.com/cockroachdb/cockroach/pull/32504

From release notes:
> Table data is now validated against a newly added [`CHECK`](../v2.2/check.html) constraint asynchronously after the transaction commits. [#32504][#32504] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, not sure if/how this affects docs.

**Comment by lucy-zhang** [comment]
That PR was reverted and replaced by #34238, which does the same thing from a user's perspective.

**Comment by jseldess** [comment]
Thanks, @lucy-zhang. Since we already announced this change in the previous alpha, and it hasn't changed from a user perspective, I'm going to remove it from the 19.1 beta release notes.
