### ISSUE TITLE
sql: add support for AS OF SYSTEM TIME clause in BEGIN and SET TRANSACTION

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4376]
PR: https://github.com/cockroachdb/cockroach/pull/34305

From release notes:
> Added support for [`AS OF SYSTEM TIME`](../v2.2/as-of-system-time.html) clauses in [`BEGIN TRANSACTION`](../v2.2/begin-transaction.html) and [`SET TRANSACTION`](../v2.2/set-transaction.html) statements, which enables entire read-only transactions to be run against a historical timestamp. This functionality simplifies performing complex analytics against a consistent snapshot of historical data and eases the burden to use historical reads with ORMs which generally make modifying the syntax of generated `SELECT` statements difficult. [#34305][#34305] {% comment %}doc{% endcomment %}
>
> Also, the behavior of the `now()` [built-in function](../v2.2/functions-and-operators.html) inside of historical `SELECT ... AS OF SYSTEM TIME` queries now reflects the historical timestamp at which the query is being run rather than the current clock time when the statement is executed. [#34305][#34305] {% comment %}doc{% endcomment %}

**Comment by ajwerner** [comment]
Relates to #4650
