### ISSUE TITLE
sql: enable automatic statistics by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4379]
PR: https://github.com/cockroachdb/cockroach/pull/34529

From release notes:
> Enabled automatic statistics collection. [#34529][#34529] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, is this done or covered by another issue? If so, feel free to close this.

**Comment by rmloveland** [comment]
@jseldess it looks like this is not explicitly stated in the recent docs update on the CREATE STATS page (which surprised me!) so I'll leave this open and work on it.

**Comment by rmloveland** [comment]
Fixed in #4441
