### ISSUE TITLE
server: Add HotRanges status endpoint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4383]
PR: https://github.com/cockroachdb/cockroach/pull/33336

From release notes:
> Added a debug endpoint listing the hottest ranges by QPS on each node/store. [#33336][#33336] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
From @rolandcrosby: "i don't think we need to talk about it yet, it's more a feature that the web ui might use in the future and that we might ask people to use for debugging" 

Closing the issue.
