### ISSUE TITLE
Database renames are not transactional

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4393]
Database renames, in contrast to pretty much everything else, are not transactional in CockroachDB.

According to @knz on [this forum post](https://forum.cockroachlabs.com/t/renaming-database-in-a-transaction/2397/7):

> There are two phases during a database rename:

> 1. the database descriptor is updated, and announced to every other
>    node

> 2. the system.namespace table is updated

> The name of a database is both in the descriptor and the
> system.namespace table.

> Step 1 is non-transactional. The rename will be announced to other
> nodes even if the transaction is aborted.

> Step 2 is transactional, and will be rolled back if the transaction
> aborts.

> This yields a surprising and undesirable behavior: when run inside
> beginâ¦commit, itâs possible for a rename to be half-done - not
> persisted in storage, but visible to other nodes or other
> transactions. This violates A, C and I in ACID. Only D is
> guaranteed: if the transaction commits successfully, the new name
> will persist after that.

Estimated scope of work:

- Update [`ALTER DATABASE .. RENAME`](rename-database.html)

- Update a central list (if such exists?) of things that are not txnal
  in CockroachDB.  (This information is also in the linked forum
  post.)

**Comment by knz** [comment]
Let's be clear, this is merely a known limitation which we're aiming to remove, it's not a feature that users can rely on.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
