### ISSUE TITLE
Document DataGrip usage

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4394]
DataGrip supports CRDB in their latest EAP release (https://blog.jetbrains.com/datagrip/2021/03/11/datagrip-2021-1-eap-3/).

It looks like CRDB support will be in DataGrip 2021.1.

JIRA issue: https://cockroachlabs.atlassian.net/browse/CRDB-1432

**Comment by rmloveland** [comment]
@awoods187 let me know if this is different than the IntelliJ work in #4004 (my understanding is that DataGrip is a separate product)

**Comment by ericharmeling** [comment]
@vy-ton 

As of 4/1/21, https://youtrack.jetbrains.com/issue/DBE-5449 and https://youtrack.jetbrains.com/issue/DBE-11773 are still open.

Also, from https://www.jetbrains.com/datagrip/whatsnew/ (taken 4/1/21): 
![image](https://user-images.githubusercontent.com/27286675/113330161-6e930c80-92ec-11eb-85c3-b448d2c07903.png)

It looks like CRDB support in DataGrip is not quite "Full" for their 2021.1 (in their words "This is the first step to full CockroachDB support, which is coming in one of the future releases."). I can update the recommended version on our [tooling page](https://www.cockroachlabs.com/docs/stable/third-party-database-tools.html#integrated-development-environments-ides), but we might want to wait before declaring DataGrip support as "Full".
