### ISSUE TITLE
current_timestamp() listed twice

### ISSUE THREAD

**Issue by mbertschler** [cockroachdb/docs#4396]
Re: [Functions and Operators](https://cockroachlabs.com/docs/v2.1/functions-and-operators.html#special-syntax-forms)

## Issue Description

`current_timestamp()` is listed twice in the section

## Suggested Resolution 

Remove one. As I tried to look into the doc .md file, I saw that the files in the `/sql/` folder don't exist in the repo, so they are probably autogenerated and I couldn't find a quick way to fix that.

**Comment by jseldess** [comment]
Thanks for reporting, @mbertschler. The relevant file is in the repo but in the `_includes` directory. I'm about to open up a PR to fix this.
