### ISSUE TITLE
Bulk import: recommend 128 inserts per batch for java

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#4399]
PGJDBC's batching support is bizarre and magical: it only works with [powers of two](https://github.com/pgjdbc/pgjdbc/blob/7b52b0c9e5b9aa9a9c655bb68f23bf4ec57fd51c/pgjdbc/src/main/java/org/postgresql/jdbc/PgPreparedStatement.java#L1597), and will split batches of other sizes up into multiple sub-batches. This means that a batch of size 128 can be 6x faster than a batch of size 250. We should adjust our docs to recommend batches of exactly 128 for java users (for other languages, around 500 is still optimal. Maybe change the recommendation to 512 in case other libraries are sensitive to powers of two).

**Comment by jseldess** [comment]
@rmloveland, can you factor this in while working on https://github.com/cockroachdb/docs/issues/4621 with @timveil?

**Comment by rmloveland** [comment]
Fixed by #4855
