### ISSUE TITLE
Document best practice for geo-distributed schema design

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4404]
- [ ] natural key to surrogate key conversion

allow an existing natural key to be used in the new database
surrogate key has side benefits of changing natural keys as needed

- [ ] pinning the natural key to surrogate key  conversion table to multiple localities

fast conversion of the key

- [ ] compare and contrast list and range partitions for geo partitioned tables

- [ ] examples of CRUD queries

- [ ] examples delete DMLs based on date ranges 

@drewdeally

**Comment by drewdeally** [comment]
Robert has you made any feature request on partition pruning ?
