### ISSUE TITLE
release-2.1: sql: allow specifying scan direction in index hint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4411]
PR: https://github.com/cockroachdb/cockroach/pull/34121

From release notes:
> It is now possible to force a reverse scan of a specific index using `table@{FORCE_INDEX=index,DESC}`. [#34121][#34121] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Closing, as this is documented here: https://www.cockroachlabs.com/docs/v20.1/table-expressions.html#force-index-selection
