### ISSUE TITLE
release-2.1: sql,sqlbase: fix the introspection for pre-2.1 BIT columns

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4412]
PR: https://github.com/cockroachdb/cockroach/pull/34201

From release notes:
> The value of `information_schema.columns.character_maximum_column` is set to `NULL` for all integer types, for compatibility with PostgreSQL. [#34201][#34201] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Closing as issue is out-of-date.
