### ISSUE TITLE
storage: hook rangefeed iter limiter to a cluster setting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4428]
PR: https://github.com/cockroachdb/cockroach/pull/34890

From release notes:
> The new `kv.rangefeed.concurrent_catchup_iterators` [cluster setting](../v19.1/cluster-settings.html) limits the number of rangefeed catchup iterators a store will allow concurrently before queueing. [#34890][#34890] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Is the Cluster Settings page automatically updated? Do I need to do anything to pull changes?

**Comment by jseldess** [comment]
It is auto-generated in the cockroach repo and copied over. I took care of it with today’s release notes, so we can close this.
