### ISSUE TITLE
changefeedccl: support more columns types with avro

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4429]
PR: https://github.com/cockroachdb/cockroach/pull/34918

From release notes:
> The [`CHANGEFEED` `experimental_avro`](../v19.1/create-changefeed.html#options) format now supports SQL columns of type `DATE`, `TIME`, `UUID`, `INET`, and `JSONB`. [#34918][#34918] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Already documented.
