### ISSUE TITLE
Document `tzdata` as a dependency

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#4433]
Certain features of CockroachDB require the `tzdata` package (sometimes called `zoneinfo`) to be installed (specifically, the ability to use place names as time zone identifiers). We had thought this was installed by default in all major linux distributions but in https://github.com/cockroachdb/cockroach/issues/32415#issuecomment-467196857 an ubuntu user reported that it was missing. We should document this dependency (and recommend that it be kept up to date, since the time zone/DST rules change several times a year).

**Comment by jseldess** [comment]
@lhirata, I can take this one.
