### ISSUE TITLE
Update node shutdown guidance

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4435]
Jesse Seldess (jseldess) commented:

From customer:

> What's the best way to know that a cockroach node has been completely decommissioned? gossipped_replicas = 0 isn't reliable as it can be 0 for dead nodes is_decommissioning = true doesn't mean decommission has completed is_live / is_available is unrelated to decommission
> 
> One way is to run the decommission command again and see that it immediately returns. Is there a more read only way to verify this?
>
> In docs https://www.cockroachlabs.com/docs/stable/view-node-details.html#node-status, it says
> gossiped_replicas    The number of replicas on the node that are active members of a range. After decommissioning, this should be 0.

From @tbg:

> `gossiped_replicas` in `node status` can’t be trusted because that info originates from the node itself, which may well be down. The `decommission` command scans the meta2 ranges and thus gives the real answer. Using the `decommission` command is the correct way to check.

Jira Issue: DOC-248

**Comment by neeral** [comment]
It seems the recommended way to check whether decommission was successful is to run `cockroach node decommission <id>` again and see if it returns immediately. This isn't clean. From an automation perspective, we will have another process managing the decommission. How can we tell whether "it returns immediately"? It seems flaky to measure how long the command takes to run and verify it is within some bound.

**Comment by mvijaykarthik** [comment]
It would be good to have a more read-only way to check this. Accidentally if we give the wrong node id for decommission verification, we may end up decommissioning the wrong node.

**Comment by neeral** [comment]
Is this issue still present while using `--wait=all`? Could `cockroach node decommission` return early?
@tbg

**Comment by tbg** [comment]
@neeral 

> It seems the recommended way to check whether decommission was successful is to run `cockroach node decommission <id>` again and see if it returns immediately.

If `./cockroach node decommission X` returns success, the node has no more replicas (`--wait=all` is implied). You don't need to check anything else.

> For 2, this is a harder problem. `node status --decommission` reads from `crdb_internal.gossip_nodes`. What is the reason for this, as opposed to scanning the meta2 ranges? I assume perf?

Yeah, perf and just the history of how it used to work. The output of `./cockroach node status` is mostly gossip-based and I wouldn't recommend it to automate against, at least not for decommissioning.

> It would be good to have a more read-only way to check this. Accidentally if we give the wrong node id for decommission verification, we may end up decommissioning the wrong node.

I hope that this is less of an issue if all it takes is to wait for the original decommission command to finish, but in principle this can be done. Feel free to make suggestion for what you think this should look like. (I can't promise we'll have the bandwidth for this anytime soon, but it could also be an OSS contribution).

**Comment by neeral** [comment]
Yes, this is fine. Our process is always to decommission a node even if it is crashed. We don't assume that because a node is crashed, its replicas will have been moved.

@jseldess, could you close this issue.

**Comment by awoods187** [comment]
So what I'm hearing is we need a definitive way to know decommission has occured that is programmatically reliable for scripting.

**Comment by jseldess** [comment]
Leaving this open for further investigation in 19.2.
