### ISSUE TITLE
Unlink changed grammar elements in create-index.md

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#444]
@mjibson Thanks for changing the labels in `create-index.md`. Can I also get them unlinked in the same way you did for `encoding` in [this PR](https://github.com/cockroachdb/docs/commit/ec6510b58239880e5a82cf2c3f3107a7fca2c31d)?

The ones I need unlinked are in `create-index.md`:

- `index_name`
- `table_name`
- `column_name`

**Comment by jseldess** [comment]
@sploiselle, he actually did unlink the create index parameters in that last PR. You'll just need to fetch the updates.
