### ISSUE TITLE
Add nuance to join choice algorithm 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4443]
In our docs today we say `By default, CockroachDB uses merge joins whenever possible because they are more performant than hash joins, computationally and in terms of memory.`  https://www.cockroachlabs.com/docs/dev/joins.html

`Whenever possible` is kind of misleading, I think it was supposed to say whenever the results are ordered for a merge. Technically merge join is always possible if you resort both sides but we don't do that

The sentence that follows implies that we can only do merge joins when both sides are already ordered, in which case "whenever possible" is correct. This was true with the HP, but this needs updating with more nuance.

**Comment by awoods187** [comment]
cc @RaduBerinde

**Comment by jseldess** [comment]
@awoods187, moving this to 19.2. Adding more work to the 19.1 scope should come with removing something as well. We have a lot on our plate.
