### ISSUE TITLE
Add an example of adding constraints for multiple regions to the Configure Replication Zones page

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#4447]
## Description

Currently today the only example of an array I could find on the page is the following: 
`constraints = '[+ssd, -region=west]'` I think it would be great to perhaps show something like: 

`constraints = '[+region=west, +region=central]'` to make it clear how this could be used. Showing this in an alter statement down the page would also be great.

## Expected Audience

Users who are looking to work with zone constraints.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/4459.
