### ISSUE TITLE
cdc: replace changefeed.min_high_water with changefeed.max_behind_nanos

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/docs#4457]
We previously were recommending that users set up an alert for changefeed health on changefeed.min_high_water, but this was difficult to do because the alert really had to be on `now()-changefeed.min_high_water`. In #35257, we deprecated changefeed.min_high_water in favor of changefeed.max_behind_nanos, which is literally just `now()-changefeed.min_high_water` and so much easier to alert on.

**Comment by lhirata** [comment]
Closing in favor of #3791.
