### ISSUE TITLE
Clarify cockroach start docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#446]
Our docs don't explain this well:

- When starting a node without `--insecure` and without certs, the node listens on `localhost` by default. 
- When starting a node with `--insecure`, the node listens on all interfaces by default.
- When starting a node with certs, the node listens on all interfaces by default.

Note from @knz: 
> we don't only listen to all addresses; we do so on both ipv4 and ipv6; and on linux this is also a bit more intricate so regular networking tools get confused, so I wasn't reading their output right.

**Comment by knz** [comment]
re. the linux confusion. `netstat -a` will not report an ipv4 listen if it's a combined ipv6+ipv4 listen by the app; instead that will show up as a listen for tcp6 with `:::*` as remote address (but for which the linux kernel will accept tcp4 connections.)
