### ISSUE TITLE
Clarify backups that must be specified for incremental backups and restores

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4460]
Question for a customer: 
> When doing incremental backups, I only need to supply a full backup and a name for the incremental. And then when doing a restore from incremental I need to specify the full backup and all the incremental backups based off of it?

Answer: 
> Yes, incremental requires previous full and incremental for both backup and restore.  example at https://www.cockroachlabs.com/docs/v2.1/backup-and-restore.html#manual-full-and-incremental-backups. 

We should make this an explicit statement in the docs above and wherever else it makes sense.

**Comment by sploiselle** [comment]
This is answered in the [`RESTORE` docs](https://www.cockroachlabs.com/docs/v2.1/restore.html#restore-from-incremental-backups).

**Comment by jseldess** [comment]
Good point, we should make sure we're linking to the specific section of the restore doc, but we should also make the overview "back and restore" page more explicit.

**Comment by jseldess** [comment]
@lhirata, going to move this back over to you, since I wasn't able to get it done ahead of the 19.2 release.

**Comment by lhirata** [comment]
@jseldess no problem, i'll get to it this week. Thanks!
