### ISSUE TITLE
Clarify Hardware Dashboard doc for process vs system metrics

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4465]
Re: [Hardware Dashboard](https://cockroachlabs.com/docs//v19.1/admin-ui-hardware-dashboard.html)

## Issue Description

CockroachDB measurement of underlying hardware resources can be either per process or per node view.  The process view means the measurements only includes consumption related to CockroachDB process.  The node view means the measurements includes consumption by all processes running on the node.  

The process metrics are meaningful as long as there are no other processes consuming significant resources on the node.  For an example, an applicaiton running on the same node as CockroachDB can take a lot of CPU and RAM.  The dashboard could show low CPU and RAM usage.  This could lead to conclusion of ample headroom which is misleading.  

## Suggested Resolution 

For any metrics that is process view, it is advised a separate monitoring tool be used to measure the node metric.   Below is a summary of process and node metrics.

| Category | Metric | Process or Node View
| -- | -- | -- |
| CPU | CPU Percent | Process |
| Memory | Memory Usage | Process |
| Disk | Disk Read Bytes | Node |
| Disk | Disk Write Bytes | Node |
| Disk | Disk Read Ops | Node |
| Disk | Disk IOPS in Progress | Node |
| Disk | Available Disk Capacity | Node |
| Network | Network Bytes Received | Node |
| Network | Network Bytes Sent | Node |

**Comment by Amruta-Ranade** [comment]
Closed through https://github.com/cockroachdb/docs/pull/5579
