### ISSUE TITLE
Encryption at Rest: Validating and getting to GA

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4471]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/reccas5UqyT0V2RID?blocks=hide
PM: @rolandcrosby 
Eng: @mberhault 

@Amruta-Ranade, there are no feature changes. Just removing the experimental status, once Marc is ready.

**Comment by mberhault** [comment]
Some small additions since last time:
https://github.com/cockroachdb/cockroach/pull/35234: `cockroach debug encryption-active-key ` which outputs the current encryption key ID (without needing to know it)
https://github.com/cockroachdb/cockroach/pull/35506: adds the `rocksdb.encryption.algorithm` per-store metric

**Comment by mberhault** [comment]
I don't think we make much mention of the performance impact of encryption-at-rest.
In general, we will see an extra 5-10% CPU utilization on modern CPUs (in the last 10 years or so). This extra utilization depends a lot on load of course.
A "normal" sql load will have higher cpu utilization for writes (no choice there) and will often not change for reads as rocksDB will have all this cached.
An extreme example is a full backup which reads all the data in the cluster.

Here is an example of cpu utilization over 4 days. Before the big dip (firewall mishap), everything is in plain text. The daily increases in CPU are full backups. The hourly (smaller) increases in CPU are incremental backups.

We can see a slight increase in CPU usage overall (half read/half write workload) but a much greater CPU utilization increase when Full backups are running.

The machines at m5.large (2vcpu) which is the lowest recommended.

We do not have good benchmarks to show the impact of encryption at rest, but we should at least mention "higher cpu utilization". We should also mention (and probably measure) the impact of backups on cluster performance.

**Comment by jseldess** [comment]
Removing "experimental" label in https://github.com/cockroachdb/docs/pull/4531.

**Comment by Amruta-Ranade** [comment]
Closed via #4577
