### ISSUE TITLE
Explain node liveness

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4475]
Explain the causes of node liveness, how to diagnose that its the problem, and what to do as a result.

**Comment by awoods187** [comment]
this needs to go wherever we store frequent problems for people to debug

**Comment by jseldess** [comment]
@awoods187, can you please provide more details about the specific problem or resources to look at?

**Comment by awoods187** [comment]
Node liveness is a frequent problem users encounter. See:
A [customer](https://cockroachdb.zendesk.com/agent/tickets/3070) experienced an outage due to node liveness
Another [customer](https://cockroachdb.zendesk.com/agent/tickets/3067) experienced a dead node due to node liveness 
General[ node liveness problems](https://github.com/cockroachdb/cockroach/issues/19699)

Node liveness is often a symptom of other problems. We should have a page that people can search for when they get node liveness errors that says that they are symptoms, here are some common causes, and what information they should collect and share with us for support when needed.

**Comment by rmloveland** [comment]
Related to (but really a subset of) #6319 .
