### ISSUE TITLE
List WITH under SQL statements

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#4477]
Re: [SQL Statements](https://cockroachlabs.com/docs//v2.1/sql-statements.html)

## Issue Description

The WITH statement isn't listed on this page or the SQL statements section of the sidebar. This sometimes [leads users to believe that we don't support it](https://stackoverflow.com/questions/55047689/sum-of-differences-over-a-jsonb-array-field-in-cockroachdb). Instead, it's documented under SQL Syntax -> Common Table Expressions, which is not necessarily a name that users know. 

## Suggested Resolution 

Refer to the WITH statement (by that name, not just as CTE) in the lists of statements. It's not quite a regular statement but it looks enough like one that that's how users think of it.

**Comment by Shiwanee** [comment]
@Amruta-Ranade Can I give it a try?

Thanks,
Shiwanee

**Comment by Shiwanee** [comment]
Hi @ericharmeling ! Can I give it a try?

Shiwanee

**Comment by ericharmeling** [comment]
Hi @Shiwanee.

So sorry for the delay. Go for it! :)

**Comment by Shiwanee** [comment]
Thanks @ericharmeling! Could you or @Amruta-Ranade , please assign it to me? :-)

Shiwanee

**Comment by Shiwanee** [comment]
Hi @ericharmeling ,

I have created PR #8850 to fix this issue.
Could you please take a look at it and let me know if this solution works?

Thanks,
Shiwanee

**Comment by Shiwanee** [comment]
> Hi @ericharmeling ,
> 
> I have created PR #8850 to fix this issue.
> Could you please take a look at it and let me know if this solution works?
> 
> Thanks,
> Shiwanee

Hi @ericharmeling , do you have any inputs on this?
Thanks,
Shiwanee
