### ISSUE TITLE
Cross-Cloud Migration Doc Update 

### ISSUE THREAD

**Issue by randmark** [cockroachdb/docs#4478]
Re: [Cross-Cloud Migration](https://cockroachlabs.com/docs//v2.1/demo-automatic-cloud-migration.html)

## Issue Description
In the text: 

Install the CockroachDB version of YCSB: go get github.com/cockroachdb/loadgen/ycsb

This doesn't seem to work as a link.

## Suggested Resolution 

Use the current YCSB, which might need a different method considering that it was put into the workload app.

**Comment by jseldess** [comment]
We switched to using the built-in workload in the meantime.
