### ISSUE TITLE
How are sql queries divided among nodes?

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#448]
From Gitter:

> how are sql queries divided amongst nodes? Let's say I have 30 queries and 30 nodes. How is it decided how work will be split?

@andreimatei's answer: 

> the queries will be executed by the server to which the client app has opened a connection. There’s postgres balancers you can put in front of your servers so that clients connect to random servers.

**Comment by andreimatei** [comment]
If we're gonna put this in some docs, we should a) figure out what one of
those postgres balancers is and test that it indeed works with CRDB (I
think someone here has tried that before) and b) also mention how we're in
the process of distributing SQL computation throughout the cluster, to
serve as a nuance of what "a client connecting to a server" means - the
server to which the client connects does have a special role and bears some
specific burden, but other servers also do work on behalf of that client.
So perfect balancing of the connections does not ensure perfect balancing
of work in the cluster.

**Comment by bdarnell** [comment]
Anecdotally, `pgbouncer` appears to be one of the most common postgres load balancers, and I verified that it works with cockroachdb.

**Comment by jseldess** [comment]
We have decent load balancing docs at this point, but connection pooling is still missing. Closing this in favor of https://github.com/cockroachdb/docs/issues/978.
