### ISSUE TITLE
Geo-partioning training error

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#4483]
While going through the CockroachDB training, I came upon the below error. I simply copy and pasted from the directions, so there may be something wrong with the commands.

As you can see, Seattle was not properly partitioned.
![Screen Shot 2019-02-14 at 5 08 22 PM](https://user-images.githubusercontent.com/47570638/54153537-3b843480-4416-11e9-9a8e-3de9c81de63c.png)

**Comment by jseldess** [comment]
The training pages have been archived in the meantime.e
