### ISSUE TITLE
Per-language connection guidance

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4485]
A connection pool contains a group of connections that are created when the connection pool is registered, usually when starting up a server. Applications borrow a connection from the connection pool, use it, then returns it to the connection pool by closing it.

We should explain how this works, what ~~our~~ client driver/library default settings are, and why (not) to change them.

For C#:
The default setting of ConnectionIdleLifetime is 300 seconds--we should warn users away from changing this setting. A user recently tried to adjust this down arguing that they didn't see connection counts adjust with traffic flow. That's a good thing! Idle connections are cheap, churning them costs.

**Comment by bdarnell** [comment]
The settings and defaults here aren't "ours", they're specific to each client driver/library. (The ConnectionIdleLifetime setting discussed here happens to be in the `c#` driver). There are some universals (we should give some guidance around how many connections to allow per node, for example), but for the most part any recommendations here would be adding more details to our per-language connection guidance.

**Comment by ianjevans** [comment]
I added some general guidance about connection pool sizing to the new Connection Pooling topic (part of the Dev Guide v2 work).
https://www.cockroachlabs.com/docs/dev/connection-pooling.html#sizing-connection-pools

@awoods187 does the new section adequately explain the concept?

**Comment by awoods187** [comment]
Yes I think this can be safely closed!
