### ISSUE TITLE
Upgrading SQLAlchemy needs additional information

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4496]
@nstewart pointed out that https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html says to upgrade but points to a repo with no instructions (https://github.com/cockroachdb/cockroachdb-python).  We need to either provide instructions in this part of the docs or work with @bdarnell to provide instructions in the repo

**Comment by vy-ton** [comment]
@ericharmeling @vy-ton Note that we should update this before the SQLAlchemy relaunch

**Comment by ericharmeling** [comment]
Only v2.1 docs instruct users to upgrade the adapter (and not the versions before/after). The adapter README includes instructions for installing the latest version of the adapter using `pip`. I think we can close this issue.
