### ISSUE TITLE
CockroachDB in Comparison Doc Update 

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#4498]
Re: [CockroachDB in Comparison](https://cockroachlabs.com/docs//v2.1/cockroachdb-in-comparison.html)

## Issue Description
When we compare ourselves against DynamoDB we state that they need an external transaction library for Distributed Transactions and say they only provide ACID semantics. As of November of 2018 DynamoDB does provide these features: https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/

## Suggested Resolution 

Update to reflect the current comparison between CockroachDB and DynamoDB.

**Comment by jseldess** [comment]
cc @jaymce
