### ISSUE TITLE
Experimental Features Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#4500]
Re: [Experimental Features](https://cockroachlabs.com/docs//v2.1/experimental-features.html)

## Issue Description

The section "Show statement fingerprints" has been mangled erroneously.

It ~has become~ is a mash-up of two *completely unrelated topics*:

- **Table fingerprints** are used to compute an identification string (really, a fingerprint) of an entire table, for the purpose of gauging whether two tables have the same data (useful e.g. when restoring a table from backup). This is an experimental feature. It also belongs to that section.

- **Statement fingerprints** are used to determine whether a cached logical plan can be reused. This is used internally in CockroachDB, **it is not visible to users** and *should not be documented* (i.e. the first sentence in that section must not exist).

## Suggested Resolution 

Clean up the section, restore clean cut information about table fingerprints.

**Comment by jseldess** [comment]
I'll take this one, @rmloveland.
