### ISSUE TITLE
Geo-partitioning training should module use of availability zones

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4505]
Currently using 9 nodes across 3 localities, with only one datacenter in each locality. Instead, we should use 3 datacenters/availability zones in each locality to ensure that a region stays available even if one of its availability zones fails. 

Something like: 

```
--locality=region=us-east,datacenter=us-east1-a
--locality=region=us-east,datacenter=us-east1-b
--locality=region=us-east,datacenter=us-east1-c

--locality=region=us-west,datacenter=us-west1-a
--locality=region=us-west,datacenter=us-west1-b
--locality=region=us-west,datacenter=us-west1-c

--locality=region=us-west,datacenter=us-west2-a
--locality=region=us-west,datacenter=us-west2-b
--locality=region=us-west,datacenter=us-west2-c
```

**Comment by robert-s-lee** [comment]
@jseldess https://github.com/cockroachdb/docs/issues/4506 for additional suggestions.
