### ISSUE TITLE
Decommissioning docs steps may not be in the correct order 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4507]
In https://www.cockroachlabs.com/docs/v2.1/remove-nodes.html#step-2-recommission-the-nodes it says that you need to recommission the nodes before restarting them.

I recently had to restart the node before recommissioning them:
```
ubuntu@ip-172-31-46-167:~$ ./cockroach node status --decommission --insecure
Error: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

dial tcp 127.0.0.1:26257: connect: connection refused
Failed running "node status"
```
Andrews-MBP-2:~ andrewwoods$ roachprod start $CLUSTER:2
andy-decommission: starting 1/1
```
ubuntu@ip-172-31-46-167:~$ ./cockroach node status --decommission --insecure
  id |        address         |               build                |            started_at            |            updated_at            | is_available | is_live | gossiped_replicas | is_decommissioning | is_draining
+----+------------------------+------------------------------------+----------------------------------+----------------------------------+--------------+---------+-------------------+--------------------+-------------+
   1 | ip-172-31-44-207:26257 | v19.1.0-beta.20190304-458-g70e3468 | 2019-03-15 13:42:21.158994+00:00 | 2019-03-15 22:53:54.16743+00:00  |         true |  true   |             10128 |       false        |    false
   2 | ip-172-31-46-167:26257 | v19.1.0-beta.20190304-458-g70e3468 | 2019-03-15 22:53:42.640637+00:00 | 2019-03-15 22:53:56.154312+00:00 |         true |  true   |                 0 |        true        |    false
   3 | ip-172-31-34-136:26257 | v19.1.0-beta.20190304-458-g70e3468 | 2019-03-15 13:42:21.215819+00:00 | 2019-03-15 22:53:54.249815+00:00 |         true |  true   |              9896 |       false        |    false
   4 | ip-172-31-39-219:26257 | v19.1.0-beta.20190304-458-g70e3468 | 2019-03-15 13:42:21.21787+00:00  | 2019-03-15 22:53:54.226065+00:00 |         true |  true   |              9935 |       false        |    false
   5 | ip-172-31-32-62:26257  | v19.1.0-beta.20190304-458-g70e3468 | 2019-03-15 13:42:21.244388+00:00 | 2019-03-15 22:53:54.280265+00:00 |         true |  true   |             10128 |       false        |    false
   6 | ip-172-31-41-84:26257  | v19.1.0-beta.20190304-458-g70e3468 | 2019-03-15 13:42:21.260492+00:00 | 2019-03-15 22:53:54.292789+00:00 |         true |  true   |             10128 |       false        |    false
(6 rows)
```
```
ubuntu@ip-172-31-46-167:~$ ./cockroach node recommission 2 --insecure
  id | is_live | replicas | is_decommissioning | is_draining
+----+---------+----------+--------------------+-------------+
   2 |  true   |        0 |       false        |    false
(1 row)
```

**Comment by rmloveland** [comment]
@taroface is this method for node decommissioning (1) going away as part of your current work on node rolling restarts?  or (2) is this something else unrelated?

Asking before digging in b/c I am not very familiar with the decommissioning / etc. stuff.  If you don't know offhand, no worries.

**Comment by taroface** [comment]
@rmloveland This documentation was actually incorrect and has been updated as of 19.1: https://www.cockroachlabs.com/docs/stable/remove-nodes.html#recommission-nodes

Recommissioning is strictly meant to cancel an active decommissioning process. If all ranges have been moved off a node, or a node is dead, then a new node should just be started. See thread: https://cockroachlabs.slack.com/archives/CA8H95NUU/p1590087380058400?thread_ts=1590087247.056500&cid=CA8H95NUU

Also #6476 is related, but not sure if recommissioning still warrants a full page

**Comment by rmloveland** [comment]
> This documentation was actually incorrect and has been updated as of 19.1: https://www.cockroachlabs.com/docs/stable/remove-nodes.html#recommission-nodes

Really glad to hear, thanks Ryan!  And thanks for the add'l info.

Andy, since the more recent docs have been updated, and that link you posted is to instructions from the 2.1 docs, and there is other ongoing work around this, I'm gonna close this particular issue.
