### ISSUE TITLE
stats: add ability to pause all create stats jobs

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4515]
PR: https://github.com/cockroachdb/cockroach/pull/35243

From release notes:
> Added the ability to pause all automatic statistics jobs by pausing the currently running job. [#35243][#35243] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
I think I addressed this in https://github.com/cockroachdb/docs/pull/4611

**Comment by jseldess** [comment]
Yep. Closing.
