### ISSUE TITLE
sql: add support for pg_catalog.{current_setting,set_config}

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4518]
PR: https://github.com/cockroachdb/cockroach/pull/35121

From release notes:
> The `pg_catalog.current_setting()` and `pg_catalog.set_config()` [built-in functions](../v19.1/functions-and-operators.html) are now supported for compatibility with PostgreSQL. Note that only session-scoped configuration changes remain supported (`set_config(_, _, false)`). [#35121][#35121] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Currently, `pg_catalog.` functions are not included in the auto-generated docs: https://github.com/cockroachdb/cockroach/pull/35121#issuecomment-475127873.

Closing.
