### ISSUE TITLE
sql: rearchitecture ALTER TABLE RENAME, add support for renaming constraints

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4520]
PR: https://github.com/cockroachdb/cockroach/pull/35091

From release notes:
> CockroachDB now supports `ALTER TABLE ... RENAME CONSTRAINT`. Only indexes that are not depended on by views can be renamed. [#35091][#35091] {% comment %}doc{% endcomment %}
>
> The [`RENAME COLUMN`](../v19.1/rename-column.html) command can now be used alongside other table commands in a single [`ALTER TABLE`](../v19.1/alter-table.html) statement. This makes it possible to, for example, atomically add a computed column based on an existing column, and rename the columns so that the computed column "replaces" the original column. [#35091][#35091] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, I can take this one.
