### ISSUE TITLE
jobs: separate description from command

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4521]
PR: https://github.com/cockroachdb/cockroach/pull/35439

From release notes:
> [`SHOW JOBS`](../v19.1/show-jobs.html) now returns an extra `statement` column, which is populated when the description is not the statement. [#35439][#35439] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Taking this off your hands, @rmloveland.
