### ISSUE TITLE
sql: improve error message for Test{Active,Idle}CancelSession

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4522]
PR: https://github.com/cockroachdb/cockroach/pull/35504

From release notes:
> [`SHOW QUERIES`](../v19.1/show-queries.html) and [`SHOW SESSIONS`](../v19.1/show-sessions.html) now omit internal queries and sessions by default. Use `SHOW ALL QUERIES` or `SHOW ALL SESSIONS` to include internal queries in the output. [#35504][#35504] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
No doc changes needed.
