### ISSUE TITLE
sql: provide table comments for virtual tables

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4524]
PR: https://github.com/cockroachdb/cockroach/pull/34764

From release notes:
> CockroachDB now provides usable comments with optional documentation URLs for the virtual tables in `pg_catalog`, `information_schema`, and `crdb_internal`. Use `SHOW TABLES [FROM ...] WITH COMMENT` to read. Note that `crdb_internal` tables remain an experimental feature subject to change without notice. [#34764][#34764] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@knz, is this something we want to feature in our documentation?

**Comment by knz** [comment]
I recommend pushing this doc to 19.2, when our support for comments and introspection will be more mature.

**Comment by jseldess** [comment]
OK. Thanks, @knz. Delaying to 19.2.

**Comment by jseldess** [comment]
@knz, I can't figure out how to get comments on virtual tables to return. The straightforward `show tables from information_schema with comments` (like we do for user-create tables) doesn't work. And I don't think there's a `select` for this. Any tips?

**Comment by knz** [comment]
it's `with comment`.

**Comment by jseldess** [comment]
Ah, I see. Thanks, @knz.

**Comment by jseldess** [comment]
@rmloveland, I'll take this one.
