### ISSUE TITLE
sql: hints for CROSS JOIN

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4549]
PR: https://github.com/cockroachdb/cockroach/pull/35700

From release notes:
> It is now possible to specify a `HASH` / `MERGE` / `LOOKUP` [join hint](../v19.1/cost-based-optimizer.html#join-hints) with cross joins (`CROSS <hint> JOIN`). [#35700][#35700] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #4560 but for some reason not picked up by Github.  (I think it's because I edited the PR description? Oh, computers.)
