### ISSUE TITLE
Create "CockroachDB Performance" overview page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4558]
This page should have `cockroachdb-performance.md` as the title, and serve as an index for all of the performance-related topics, such as performance benchmarking, performance tuning, performance best practices, etc.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).
