### ISSUE TITLE
sql: Expand automatic statistics documentation

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4570]
Document the knobs users can set to adjust automatic statistics collection (introduced in this [pr](https://github.com/cockroachdb/cockroach/pull/36085)) either in the main issue https://www.cockroachlabs.com/docs/v19.1/cost-based-optimizer.html#table-statistics or via cluster settings/session variables.

New settings:
sql.stats.automatic_collection.fraction_stale_rows 
sql.stats.automatic_collection.min_stale_rows

**Comment by jseldess** [comment]
@awoods187, we've already updated the cluster settings page to cover these new settings: https://www.cockroachlabs.com/docs/dev/cluster-settings.html. Is that enough, or do you think they're important enough to call out in the cost-based optimizer page as well?

**Comment by awoods187** [comment]
I think it might be nice to have one sentence that says "you can configure automatic statistics using these cluster settings X and Y" with a link to the cluster settings page.

**Comment by jseldess** [comment]
@rmloveland, are you touching the cost-based optimizer docs still for 19.1? If so, can you factor this in?

**Comment by rmloveland** [comment]
> are you touching the cost-based optimizer docs still for 19.1? If so, can you factor this in?

Yes and yes.

**Comment by rmloveland** [comment]
Fixed by #4635
