### ISSUE TITLE
Add TypeScript example to "Build an App"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4572]
Now that we have TypeORM support, this would be really nice to have.

See also:

- #4571

**Comment by vy-ton** [comment]
@ericharmeling Moving this to P-1 based on recent interest from hackathons and our general strategy to prioritize Javascript/Typescript tooling.

**Comment by vy-ton** [comment]
@ericharmeling Let me know if this is something that could be prioritized in the next month. Marketing is interested in featuring a Node.js ORM and TypeORM is something we have full support for.

**Comment by ericharmeling** [comment]
I think we could get something out over the next month, based on this:

https://github.com/typeorm/cockroachdb-example
