### ISSUE TITLE
Topology Pattern Library

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4574]
We have a [v1 of topology patterns](https://www.cockroachlabs.com/docs/stable/cluster-topology-patterns.html). We need to make sure we're presenting the right patterns with the right dimensions and guidance 

- Docs goal: Making it easier for users to know how to configure CockroachDB to get the latency and resiliency they require in a variety of contexts. 
- Marketing goal: Showing that CockroachDB can do things that other databases can't. Tying topology patterns into real customer stories.

RAIC:
- R (Responsible): Jesse
- A (Accountable): Jesse
- C (Consulted): Roko, Tim V, Robert, Ben, Core Eng team
- I (Informed): Rest of SE team, Jim W, Kurt H, MSO team, Support team, Nate, Spencer

**Comment by jseldess** [comment]
Original description:

Edits to existing doc:
- De-emphasize availability expectations ([more info](https://github.com/cockroachdb/cockroach/issues/12768))

New info to consider adding:
- Examples of each cluster

New patterns to consider adding:
- [High performance regional](https://github.com/cockroachdb/docs/issues/4665)
- [More partitioned clusters](https://github.com/cockroachdb/docs/issues/2565)

Follow up to #2935.

**Comment by jseldess** [comment]
See https://docs.google.com/document/d/1--Hm7ehq2oaxLi1H7sYrhhjQ3mUkj_uWDD5Y9Vs-Ips/edit.

**Comment by thatnerd** [comment]
Anti-Pattern:

* Creating a 3-node distributed cluster (jacks up write latency b/c consensus must be formed across regions)
  * Solution: Have 3 nodes in each region (probably in different zones) and co-locate the relevant tables/indexes in order to ensure that consensus can occur close together.
