### ISSUE TITLE
Warn users that they can't use hombrew until go 1.12.2 lands

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4575]
Go 1.12.1 has a bug that impacts our ability to use hombrew. We won't be able to offer 19.1 on homebrew until homebrew upgrades to Go 1.12.2. Go 1.12.2 is in development but not yet fully available.

We should tell users in release notes and other places to avoid homebrew until the Go fix lands.

**Comment by awoods187** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/35657

**Comment by bdarnell** [comment]
Specifically, we can't upgrade homebrew until Go 1.12.2 is out, but the version that's currently there is fine. Homebrew installs will stay at CockroachDB 2.1.5 until 1.12.2 is out, so for the first few weeks of 19.1's life the homebrew installation option will not be available for that version.
