### ISSUE TITLE
Cluster Topology Patterns Doc Update 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#4578]
Re: [Cluster Topology Patterns](https://cockroachlabs.com/docs//v19.1/cluster-topology-patterns.html)

## Issue Description
In the multi region deployment, in the image and in the text we switch between 6 nodes spread across 3 regions and 9 nodes spread across 3 regions. 

![image](https://user-images.githubusercontent.com/894257/55028182-7d4bd800-4fdd-11e9-87bf-d16b79c3e57f.png)

## Suggested Resolution 
Find a way to make this consistent. Either have 6 nodes throughout, 9 nodes throughout, or 2 separate examples.

**Comment by jseldess** [comment]
Thanks for the catch, @nstewart.

@lhirata, the first map image needs to show 3 nodes in each region, and that `6 nodes are spread across 3 regions` text needs to be `9 nodes are spread across 3 regions`.

**Comment by jseldess** [comment]
@lhirata, I'll handle this real quick.
