### ISSUE TITLE
release-19.1: ui: adjust QPS Summary to match Time Series and Node Map values.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4588]
PR: https://github.com/cockroachdb/cockroach/pull/35905

From release notes:
> The **Queries per second** metric in the **Summary** bar now summarizes only the query types displayed in the **SQL Queries** graph and **Node Map**. [#35905][#35905] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed via #4597
