### ISSUE TITLE
mso: how to connect to the global LB of a cluster

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#4591]
Currently, there is no way to connect to the global LB of a multi regional cluster. This might be necessary for some ad-hoc queries. 
Ben doesn't think we should document this till we have an intelligent routing mechanism (something like AWS Route 53) installed. Filing an issue so we remember to update. 

![image](https://user-images.githubusercontent.com/36172966/55168684-a2f5f000-5149-11e9-99c5-678859e80ee9.png)

**Comment by lnhsingh** [comment]
@kannanlakshmi is this issue still relevant?

**Comment by kannanlakshmi** [comment]
Nope!
