### ISSUE TITLE
Add recommendations about file systems

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#46]
So our product promises to behave nicely assuming the user is storing their files in a properly-behaved filesystem / persistent storage.

However as discussed in this paper: https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-pillai.pdf

operating systems have bugs in how they implement file systems, and sometimes the OS promises that data written by an application is actually written to disk while there is a bug which causes this data to not be saved. Or the OS promises something about the order in which I/O operations issued by the DB are performed on disk, and instead actually does things in a different order. This is Real Bad.

Our docs need to explain what we assume from the underlying storage and make recommendations about which file systems are known to work sufficiently well.

**Comment by jseldess** [comment]
Thanks for adding this, @knz!

**Comment by jseldess** [comment]
@knz, @robert-s-lee, @rkruze, is this something we need to add to our [Production Checklist](https://www.cockroachlabs.com/docs/dev/recommended-production-settings.html#hardware)? If so, who can help me track down the right guidance, in general and per cloud?

**Comment by robert-s-lee** [comment]
@drewdeally can you share results of various filesystem options and the recommendations from the test?

**Comment by drewdeally** [comment]
I will put it together and share with the team once I test it - but will use one standard which is ext4.  not xfs or others.

**Comment by drewdeally** [comment]
We are also missing kernel settings do you want that added under another topic?

**Comment by jseldess** [comment]
Sure, @drewdeally. Feel free to open a separate docs issue for kernel settings, if you feel that's important to include in our Production Checklist.

**Comment by drewdeally** [comment]
the FS mount options which should cover most cases will be found here https://docs.google.com/document/d/171XnKag1xkIh59MkU8g8_7abg0pQfV2O7nUfTIixssA/edit along with the OS settings.  Many mount options exist, these should work across all platforms for ext4.
