### ISSUE TITLE
Online schema change best practices and troubleshooting

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4601]
Andrew Woods (awoods187) commented:

Schema changes, by their nature, consume additional resources. We should provide recommendations for when to run schema changes, how much available CPU is needed, and what to expect performance wise. If schema changes are run near peak capacity, latency spikes can occur. It's important we help users understand what is needed to ensure online schema changes don't impact foreground traffic.

Jira Issue: DOC-262

**Comment by awoods187** [comment]
@drewdeally suggest cpu > 55% because if a node fails, now you will bump all surviving nodes to 80% (or something high) and the system will be under stress

It can be avoided perhaps by sizing for a run rate of 20-40%

When planning we need to add in node failure overhead

**Comment by awoods187** [comment]
The new schema change index backfill is highly susceptible to spikes of latency as CPU usage of the cluster increases (https://github.com/cockroachdb/cockroach/issues/34744#issuecomment-484319495). We need to provide guidelines around when to run a schema change and what to do if latency spikes. It probably makes sense to do so here (https://www.cockroachlabs.com/docs/v2.1/online-schema-changes.html#main-content)

We cover running with sufficient headroom above--this is the most important piece of information. 

In the event that latency spikes (either due to insufficient headroom or other occurrences) we should update the limitations section to recommend the following:
1. Cancel the index backfill job (`show jobs` `cancel job foo`). 
2. Add capacity to the cluster (horizontal scale by adding nodes to the cluster)
3. Try again.
4. If this doesn't work, or you are unable to add capacity, you can turn the new index backfill off and use the older backfill implementation.

cc @lhirata @vivekmenezes @dt

**Comment by jseldess** [comment]
@lhirata, is this out of scope for 19.2 at this point, given your focus on oracle migration, training, and ops and tools features?

**Comment by lhirata** [comment]
Yes, this is now out of scope

**Comment by mwang1026** [comment]
moving to SQL since Schema owned by SQL now

**Comment by jseldess** [comment]
@awoods187, for your triage and prioritization. Feel free to close if we've improved docs here in the meantime or you don't think this is worthwhile anymore.

**Comment by awoods187** [comment]
@vy-ton and @ericharmeling can you prioritize or close this item?

**Comment by ericharmeling** [comment]
IMO, this information best fits as a new section in the [Online Schema Changes](https://www.cockroachlabs.com/docs/stable/online-schema-changes.html) page.

We could alternatively create a new page and place that beneath the Online Schema Changes page in the **Develop** ToC.
