### ISSUE TITLE
cbo: clarify that to use the nearest index every column the query uses must be part of the index 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4605]
As discovered in https://github.com/cockroachdb/cockroach/issues/35923#issuecomment-478128117, to use the nearest index every column the query uses must be part of the index. 

We should modify the example to have a third column in the table and then limit the query to only the things in the index. We should also add this explicit warning to the user here so that they know how to plan their queries and indexes.

**Comment by rmloveland** [comment]
I agree the example can be improved.  [The current CBO docs](https://www.cockroachlabs.com/docs/v19.1/cost-based-optimizer.html#preferring-the-nearest-index) do already tell the user that the columns they want to query need to be part of the index (perhaps not loudly/explicitly enough, however).

> To take advantage of this feature you need to:
> ...
> 3. Create multiple indexes on the reference tables. Note that the indexes need to include (in key or using STORED) the columns that you wish to query.

**Comment by awoods187** [comment]
Yeah that's a good point Rich. I think maybe we could just make this point a little louder in the short-term (since it's there) and then change the example at a lower priority in the future
