### ISSUE TITLE
Training: Update labs that gave GUI URLs to include navigation steps

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#4625]
**Is your feature request related to a problem? Please describe.**
This is a suggestion to make it easier to learn the Admin UI from the labs

**Describe the solution you'd like**
Many of the labs include navigaytion steps. For instance, https://www.cockroachlabs.com/docs/stable/training/under-replication-troubleshooting.html shows the UI navigation in steps 1-3.

Some just give a URL. https://www.cockroachlabs.com/docs/stable/training/data-unavailability-troubleshooting.html step 5 incudes the URL http://localhost:8080/#/reports/problemranges.

The problem with only giving the URL is that I could not figure out how to navigate to that screen. I can only get to it if I type in the url.

From @gpasmore

**Comment by jseldess** [comment]
These training pages are no longer public now that we have Cockroach U, so closing this.
