### ISSUE TITLE
Enable synonyms in google custom search

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#464]
Looks like our custom search doesn't pick up meta keywords. But we might be able to use the built-in [synonyms](https://cse.google.com/cse/search/synonyms?cx=014222686769097698638%3Ai_krv_mjv4w) feature instead.

**Comment by vivekmenezes** [comment]
The link doesn't work

**Comment by jseldess** [comment]
Hmm, it works for me. Probably requires login.

**Comment by vivekmenezes** [comment]
https://developers.google.com/custom-search/docs/queries

describes it

**Comment by jseldess** [comment]
That's a great page. Thanks, @vivekmenezes. Interestingly, they don't mention that you can add synonyms directly in the UI; they only focus on a custom xml file. I think I'll stick with the UI for now, since it's working.

**Comment by jseldess** [comment]
Started adding synonyms in the custom search console, and it's working. Closing this for now. Will open issues to add specific synonyms as we see the need.
