### ISSUE TITLE
Known Limitations in CockroachDB v2.1 Doc Update 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#4641]
Re: [Known Limitations in CockroachDB v2.1](https://cockroachlabs.com/docs//v2.1/known-limitations.html)

## Issue Description

For the section

```
After using cockroach dump to dump the schema and data of an interleaved table, the output must be edited before it can be imported via IMPORT. See #35462 for the workaround and more details.
```
We should clarify that the workaround is only for indices, not tables.

**Comment by jseldess** [comment]
We missed this one, but the limitation was resolved in the meantime, so closing.
