### ISSUE TITLE
Key value storage example shows all keys on same line

### ISSUE THREAD

**Issue by danielcompton** [cockroachdb/docs#4642]
On https://www.cockroachlabs.com/docs/stable/interleave-in-parent.html#key-value-storage-example all of the example keys are on the same line:
<img width="941" alt="Screenshot of Safari (9-04-19, 6-15-25 AM)" src="https://user-images.githubusercontent.com/811954/55746824-df511680-5a8e-11e9-89e7-07bb1bb4bdd5.png">

I think the intention was for each key to be on a separate line. That's how it shows in GitHub's [markdown rendering](https://github.com/cockroachdb/docs/blob/4ca8a8a51773b03d1ab82aeb18f4d4741c65d930/v19.1/interleave-in-parent.md), but not in the published version.

<img width="934" alt="Screenshot of Safari (9-04-19, 6-17-14 AM)" src="https://user-images.githubusercontent.com/811954/55746921-22ab8500-5a8f-11e9-9c77-17b765fbc421.png">

**Comment by rmloveland** [comment]
@danielcompton thanks for filing this, have a PR up to fix now.  Hope it merges soon.  Thanks for your patience!
