### ISSUE TITLE
Unclear Changefeed known limitation

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4647]
Re: [Known Limitations in CockroachDB v2.1](https://cockroachlabs.com/docs//v2.1/known-limitations.html)

## Issue Description

Please clarify  `Changefeed behavior under most types of failures/degraded conditions is not yet tuned.`

**Comment by jseldess** [comment]
@lhirata, passing this to you.

**Comment by rolandcrosby** [comment]
@lhirata Dan notes that this was originally related to cockroachdb/cockroach#31200. I think we should clarify that this just means that we haven't empirically optimized the backoff/retry behavior in the face of partial or intermittent sink unavailability. If you think it's necessary, we can reiterate that the overall guarantees (at-least-once delivery and per-partition ordering of messages that you haven't seen before) will still hold for as long as a changefeed remains active in the jobs table.
