### ISSUE TITLE
Make decommissioning docs production-ready

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#4649]
Reference: Slack convo on the docs channel. Suggested action items:

- Replace the use of `quit --decommission` with `node decommission --wait`, followed by killing the node when that's done
- Account for process managers (the way we do for backup/restore and upgrade docs). Consider systemd and Kubernetes
- Refactor the docs to use either AWS or GCE (or both)

**Comment by taroface** [comment]
Closing as this has been covered by #7542.
