### ISSUE TITLE
sql: update AOST docs

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4650]
Our docs say:
`Currently, CockroachDB does not support AS OF SYSTEM TIME in explicit transactions. This limitation may be lifted in the future`
https://www.cockroachlabs.com/docs/v19.1/as-of-system-time.html#main-content

This is not true. With the addition of https://github.com/cockroachdb/cockroach/issues/20266 by @ajwerner it can be done.

cc @nstewart

**Comment by awoods187** [comment]
Also, we will need to include that ORM's should work.

From @ajwerner "The SET/BEGIN work was added to ease adoption of follower reads when using ORMs. Maybe we need some more documentation about how to use follower reads with some ORMs because the code will need to manually set up the transaction first:

**Comment by jseldess** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/4653.
