### ISSUE TITLE
Cost-Based Optimizer Doc Update 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#4652]
Re: [Cost-Based Optimizer](https://cockroachlabs.com/docs//v19.1/cost-based-optimizer.html)

## Issue Description
we should just come out and call this an enterprise feature.

> The optimizer preferring the nearest index is not an enterprise feature, but in order to take advantage of it you need to be able to create a replication zone for a secondary index, which is an enterprise feature. 

This language is frustrating since it is saying I have to pay to use it BUT its not enterprise - what is the purpose of the additional nuance here? Is there any situation when I can use this functionality without paying?

## Suggested Resolution 

Just call this an enterprise feature rather than saying “its free, but to use it you have to pay”

**Comment by jseldess** [comment]
@rmloveland, I know you have plenty on your plate, so let me know if you want me to make this edit.

**Comment by rmloveland** [comment]
Thanks Jesse, I got it :-)
