### ISSUE TITLE
More obviously discourage less than 3 nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4657]
Created after a discussion with @randmark:

Our canonical deployment tutorials are cluster pattern-agnostic, but they don't do enough to discourage obviously bad patterns, like running a 2 node cluster, or running across 2 datacenters. 

At the minimum, [when we recommend reviewing the production checklist](https://www.cockroachlabs.com/docs/dev/deploy-cockroachdb-on-premises.html#recommendations), we should discourage these basic anti-patterns as not providing the resiliency benefits of CockroachDB.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).
