### ISSUE TITLE
SQL Audit Logging Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#4658]
Re: [SQL Audit Logging](https://cockroachlabs.com/docs//v2.1/sql-audit-logging.html)

## Issue Description

A user who lands on this page will be unaware that CockroachDB provides other facilities for query logging.

## Suggested Resolution 

Add a notice with link to https://www.cockroachlabs.com/docs/v2.1/query-behavior-troubleshooting.html#cluster-wide-execution-logs

**Comment by Harshi7016** [comment]
Hello @Amruta-Ranade , 
This looks interesting,Could I work more on this ?
Thanks

**Comment by Amruta-Ranade** [comment]
@Harshi7016 Sure! Assigning the issue to you. 
You correctly identified both to-do items: Add a link to the Troubleshoot SQL Behavior page in the See Also list and also add a note earlier in the doc linking to the page.

A couple points to note:
- The issue has been created for CockroachDB 2.1, a version that's no longer actively supported. Update the 19.2, 20.1, and 20.2 docs instead.
- If you are participating in Hacktoberfest, you might want to hold off on opening the PR until at least Tuesday. I need time to update the repo as per the [new rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by Harshi7016** [comment]
Hi @Amruta-Ranade , I am really sorry but I need to unassign myself from this issue as I am facing hardware issues when I tried to run it locally.
Sorry again for not completing the issue

**Comment by Amruta-Ranade** [comment]
No worries!

**Comment by deeptikorwar** [comment]
@Amruta-Ranade, can I work on this one?

**Comment by Amruta-Ranade** [comment]
Sure!

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8759
