### ISSUE TITLE
AWS clock sync clarification

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4659]
Re: [Production Checklist Clock](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#considerations)

## Issue Description

Verify whether [Amazon Time Sync Service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) is sufficient 

## Suggested Resolution 

if additional steps are required, possibly suggest a note

**Comment by keith-mcclellan** [comment]
Default RHEL AMIs from red hat point chrony to red hat ntp servers with the following lines:

server 0.rhel.pool.ntp.org iburst
server 1.rhel.pool.ntp.org iburst
server 2.rhel.pool.ntp.org iburst
server 3.rhel.pool.ntp.org iburst

we should advise redhat users to convert to the Amazon Time Sync service server when solely on AWS

**Comment by keith-mcclellan** [comment]
basically, we want them to replace those lines with:

Open the /etc/chrony.conf file using a text editor (such as vim or nano). Verify that the file contains the following line:

server 169.254.169.123 prefer iburst

If this line is not present, add it. Comment out any other server or pool lines. Restart the chrony service.

**Comment by keith-mcclellan** [comment]
customers can confirm the change by running the command: 

chronyc sources -v

the top return line should look similar to: 

^* 169.254.169.123               3   6    17    43    -30us[ -226us] +/-  287us

The * indicated that it's the preferred time server.  If they properly commented out the other ntp servers they shouldn't see any other sources

**Comment by taroface** [comment]
@keith-mcclellan Looking at the [Amazon doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html) for this and a few additional parameters are included in the required line:

`server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4`

Are these necessary?

**Comment by keith-mcclellan** [comment]
Necessary, no - they just control how frequently chrony polls the time server.  I think they should be fine to add but I haven't tested with those options set.

**Comment by taroface** [comment]
OK, thanks. I will keep those parameters in our doc, just to be consistent with the Amazon guidelines that we link.
