### ISSUE TITLE
Foreign keys

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#466]
Starting points:

- [RFC](https://github.com/cockroachdb/cockroach/pull/6309)
- [Postgres docs](https://www.postgresql.org/docs/9.5/static/ddl-constraints.html)
- [MySQL docs](http://dev.mysql.com/doc/refman/5.7/en/constraint-foreign-key.html)

Dev: @dt  (David Taylor)

**Comment by sploiselle** [comment]
Closed by #528
