### ISSUE TITLE
Typo/grammar error on 'Life of a Distributed Transaction' page

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4666]
In [Life of a distributed transaction](https://www.cockroachlabs.com/docs/dev/architecture/life-of-a-distributed-transaction.html#resolving-write-intents) there is a paragraph with some breakage.  Looks like it was supposed to be a bulleted list item, but it's not part of a list, and results in some ungrammatical language in this paragraph (seems to start at " - Missing, "):

> The incoming transaction can only continue once the blocking transaction completes (i.e., commits or aborts). - Missing, the resolver consults the write intent's timestamp. If it was created within the transaction liveness threshold, it treats the transaction record as exhibiting the PENDING behavior, with the addition of tracking the push in the range's timestamp cache, which will inform the transaction that its timestamp was pushed once the transaction record gets created.

**Comment by lhirata** [comment]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

**Comment by Shiwanee** [comment]
Hi @lnhsingh , I would like to take up this issue. Could you please assign it to me?
Thanks,
Shiwanee

**Comment by Shiwanee** [comment]
Hi, I've created Pull Request #8284 to fix this issue, but in that PR, I see the "assignees" and "Reviewers" fields are not editable.
I am neither able to assign it to jseldess nor add anyone as reviewer.
Can you please help me identify what I have missed, or whether I need some permissions to take those actions?
