### ISSUE TITLE
Add how to install `brew` in training

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#4673]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

On: https://www.cockroachlabs.com/docs/stable/training/cluster-startup-and-scaling.html

The first step asks you to use "brew" to install haproxy. This isn't in the MAC terminal by default. It would be good to point folks to where or how to get it, if they don't already have it. I used the following command:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

**Comment by chelsealee** [comment]
@lnhsingh Is this still valid? I looked at the page and there is no reference to "brew".

**Comment by lnhsingh** [comment]
Seems to be outdated. Closing, thanks-- you just closed your second issue!
