### ISSUE TITLE
gcp internal load balancing

### ISSUE THREAD

**Issue by tzilist** [cockroachdb/docs#4682]
In quite a few places in the docs, it is referenced that gcp does not support internal load balancing for k8s, namely here:

https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#exposing-dns-servers

gcp now supports internal load balancers (in beta, however).
https://cloud.google.com/load-balancing/docs/internal/

It might be worth updating the docs and any of the scripts associated with deploying to gcp to reflect this change!

Thanks for all your hard work!

**Comment by tzilist** [comment]
Closing this issue, misread what the problem with GCP internal load balancing was. Sorry!

**Comment by rmloveland** [comment]
No problem @tzilist - please feel free to file an issue anytime you think something needs attention.  Thanks for your interest in making sure the docs are correct!
