### ISSUE TITLE
Start a Node Doc Update -- Handle Multiple Data Stores

### ISSUE THREAD

**Issue by randmark** [cockroachdb/docs#4684]
Re: [Start a Node](https://cockroachlabs.com/docs//v2.1/start-a-node.html#store)

## Issue Description

It's not currently clear in the doc that users can run the --store attribute multiple times to add multiple data stores. This is usually done to add more space or provide slower or faster data stores to the same node rather than adding them as separate nodes entirely. If someone were to want to add more --store attributes they might not be sure that it's a repeatable attribute based on how it's written currently.

## Suggested Resolution 
The doc needs to make it clear how to run it multiple times, which is similar to the following:

cockroach start --store=path=/blah,attrs=ssd --store=path=/blah2,attrs=hdd ...

Also, there are a number of caveats that might need to be be handled for this: 

- Multiple data stores are not necessarily balanced evenly and if a user wants to do this because they want an easier way to handle adding new storage capacity we recommend using LVM or ZFS with a virtual storage volume to solve those issues instead of adding new data stores. See this internal slack discussion: https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1556123389004300

- The doc needs to specify the reasons to do multiple stores, such as if you want to make some slow disks available, in which case you really should use attributes so you can set Zone configs. Note the following internal thread: https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1556123453005600

- Possibly, we'd need to clarify how Zone configs interact with these --store attributes so this is clear.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/7666 and https://github.com/cockroachdb/docs/issues/7889
