### ISSUE TITLE
docker: document default database creation in docker hub

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#4687]
[This](https://github.com/cockroachdb/cockroach/issues/19826) is a very popular community request. We document this in our docs site, but Lush pointed out that they went to Docker hub and expected to find it there or in the readme. Unclear who edits the docker hub details (is it docs or eng or someone else) or read me. But would be good to document this in docker hub as well as since its a popular workflow. Lush specifically requested that we do so.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/48647 and https://github.com/cockroachdb/cockroach/issues/19826
