### ISSUE TITLE
MSO-specific UI guidance

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4690]
- Update the monitoring doc with MSO-specific UI guidance
- Update the Connect to your cluster with a Monitoring section. Might have to rework the doc a bit).

**Comment by jseldess** [comment]
@Amruta-Ranade, is this still in scope for 19.2, or should we push it to later?

**Comment by Amruta-Ranade** [comment]
This project's priority keeps moving -- we deprioritized this project in favor of the "Build an app" project, but customer feedback seems to suggest that I need to pick this up soon-ish. Can we keep this for 19.2 and revisit it in a few days?

**Comment by jseldess** [comment]
Sure.
