### ISSUE TITLE
Using logical plans / EXPLAIN

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4692]

**Comment by rmloveland** [comment]
@Amruta-Ranade is this the issue that we just discussed that will cover the Admin UI portion of `EXPLAIN`? 

(but not necessarily the SQL reference doc portion?)

**Comment by Amruta-Ranade** [comment]
Discussion with Jesse:
- First identify which problems we want to walk the users through (like full table scans) and then talk about those.
- Might not be limited to the Admin UI. Don't leave out other EXPLAIN options that need to be run via the SQL prompt. 
- Look at the perf tuning tutorial and see how EXPLAIN is being used there. Incorporate them into this EXPLAIN tutorial. https://www.cockroachlabs.com/docs/stable/performance-tuning.html#step-6-test-tune-read-performance

**Comment by Amruta-Ranade** [comment]
> @Amruta-Ranade is this the issue that we just discussed that will cover the Admin UI portion of `EXPLAIN`?
> 
> (but not necessarily the SQL reference doc portion?)

Yes

**Comment by Amruta-Ranade** [comment]
Scope:  Write a tutorial to use EXPLAIN/Logical plans for SQL tuning
Success criteria: We guide users through using EXPLAIN to tune SQL in most common problematic scenarios

Need to figure out what are the problems to focus on

Resources:
-https://cockroachlabs.atlassian.net/wiki/spaces/TS/pages/118751375/Troubleshooting+Performance+Issues
- https://www.cockroachlabs.com/docs/stable/performance-tuning.html#step-6-test-tune-read-performance

**Comment by awoods187** [comment]
I really liked this guide on query plans https://rockset.com/blog/sql-query-planning-for-operational-analytics/
