### ISSUE TITLE
Document that cloud storage SDKs use TLS

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#4699]
A customer noted that we don't explicitly mention whether CockroachDB's connections to external cloud storage systems are encrypted. We should add a note to the table of cloud storage providers indicating that the S3, Google, Azure, and HTTPS cloud storage providers all use TLS under the hood.

**Comment by lhirata** [comment]
From Roland: the encryption in transit issue should be as straightforward as saying "TLS is used for encryption in transit when transmitting data to or from s3/google storage/azure", and the at-rest one could just be like "if your cloud provider offers transparent data encryption, e.g. [link to aws transparent data encryption page], you can use that to ensure that your backups aren't stored on disk in cleartext"

**Comment by mwang1026** [comment]
P-1 since this is a small task
