### ISSUE TITLE
Automate testing of SQL commands on a subset of SQL reference docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4705]
This should go hand-in-hand with https://github.com/cockroachdb/docs/issues/2849. If we can use the built-in `movr` data set for a subset of SQL docs, we should focus on automating the testing of that subset.

**Comment by jseldess** [comment]
@ericharmeling, @rmloveland, as we think about next steps for dev docs, following up on Eric's use of Movr, we should think about whether we aim to do more in terms of automated testing. I know you guys did research about how to approach this, but I'm not sure if we can do much more for 19.2. Something for us to talk about in our sync on dev docs.

**Comment by rmloveland** [comment]
@jseldess I agree we can't do more on this for 19.2 beyond the research that's already been done.  Moving to 20.1 milestone.

**Comment by jseldess** [comment]
Putting this on YZ's backlog, @rmloveland. Hope you and @ericharmeling will collaborate with them on the right approach, when the time comes.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/7067.
