### ISSUE TITLE
End-to-end MSO tutorial including using our CA.crt to connect a client from a separate Kubernetes cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4708]
Suggested approach:
Start by getting an MSO cluster, getting the CA.crt, and then starting a separate kubernetes cluster with the cockroach binary in a single pod. And try to start the sql shell from there pointing the MSO cluster.
The trick is figuring out how to get the CA.crt into that cluster and accessible to cockroach running in that pod.

**Comment by Amruta-Ranade** [comment]
1. `kubectl create secret generic <secret__name> --from-file <directory containing the ca cert> `
2. Edited the `client-secure.yaml` file:
~~~ 
volumes:
  - name: ca-certs
    secret:
      secretName: <secret_name> 
~~~

~~~
volumeMounts:
  - mountPath: "/data/certs"
    name: ca-certs
    readOnly: true
~~~
3. `kubectl create -f client-secure.yaml`
4. `kubectl exec -it cockroachdb-client-secure -- ./cockroach sql --url 'postgres://amruta@gcp-us-east1.josh-test.crdb.io:26257/audit_log_test?sslmode=verify-full&sslrootcert=/data/certs/josh-test-ca.crt'`

**Comment by Amruta-Ranade** [comment]
Discussion with Joel: We might want to create separate Kubernetes client docs (instead of referring users to K8 CRDB docs)

**Comment by Amruta-Ranade** [comment]
[Context: Jesse's user-testing feedback] We had discussed including language-specific connection strings in the doc. I am now wondering if we should have a "connect to your app" section and list the connection strings for all languages and K8 cluster.

**Comment by kannanlakshmi** [comment]
@Amruta-Ranade I think this would be a great video tutorial too (totally understood that the lift on that is different) and I am happy tp help when we get to it.
