### ISSUE TITLE
Geo-Partitioning Doc Update 

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4720]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

Re: [Geo-Partitioning](https://cockroachlabs.com/docs//v19.1/training/geo-partitioning.html)

`Step 1.  Enable a trail enterprise license` should be `Step 1.  Enable a trial enterprise license`

**Comment by kgorryhines** [comment]
I'm claiming this one
