### ISSUE TITLE
Improve write performance of secondary index (parallel commits)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4723]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec0Bd8ImPCLEKExx?blocks=hide
PM: @awoods187 
Eng: @nvanbenschoten, @tbg 

Subtasks:

- [x] #5465 (Transaction Layer)
- [x] #5466 (Reads and Writes in CockroachDB)
- [ ] #5467 (Life of a Distributed Transaction)

**Comment by jseldess** [comment]
Closing this, @rmloveland. If there's still work to do, please open a separate issue describing that.

**Comment by rmloveland** [comment]
Makes sense - this work can happen on #5467
