### ISSUE TITLE
Improve decommissioning, recommissioning, and recovery of killed nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4725]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recuzwzDMoLDci14t?blocks=hide
PM: @awoods187 
Eng: @knz, @andreimatei

**Comment by rmloveland** [comment]
@knz I have some questions about this work (please redirect me as needed):

- Based on my reading of the related CRDB issues in Airtable (copied below for reference), it seems like this work falls in the category of "make decommissioning etc. magically work better" and does not necessarily affect user-facing docs.  Do you agree with that assessment?
- Based on the fact that most of the issues below are still open, and given their likely lack of documentation impact, I'm inclined to close this docs issue as there is not (yet) anything concrete to take action on. Do you agree with that assessment?

/cc @johnrk FYI

Related CRDB issues (copied from Airtable):
- https://github.com/cockroachdb/cockroach/issues/36676
- https://github.com/cockroachdb/cockroach/issues/36583
- https://github.com/cockroachdb/cockroach/issues/36623
- https://github.com/cockroachdb/cockroach/issues/35890
- https://github.com/cockroachdb/cockroach/issues/36397
- https://github.com/cockroachdb/cockroach/issues/35938

**Comment by knz** [comment]
I agree this air table entry does not seem to require doc changes.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rmloveland** [comment]
> I agree this air table entry does not seem to require doc changes.

Thank you!  In that case I'll close.
