### ISSUE TITLE
Raft proposal pipeline 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4726]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recOygjP3oTDIW6BK?blocks=hide
PM: @awoods187 
Eng: @ajwerner, @nvanbenschoten

**Comment by rmloveland** [comment]
@nvanbenschoten I took a look at the ['Raft' section of our replication layer docs][1] and it looks like it only discusses "raft logs"; it does not mention the distinction between "Raft log commit" vs. "state machine apply" you mention in your PR [cockroach#38954][2]:

> When writes receive a quorum, and are committed by the Raft group leader, they're appended to the Raft log. This provides an ordered set of commands that the replicas agreed on and is essentially the source of truth for consistent replication.

> Because this log is treated as serializable, it can be replayed to bring a node from a past state to its current state. This log also lets nodes that temporarily went offline to be "caught up" to the current state without needing to receive a copy of the existing data in the form of a snapshot.

Based on the above, it looks like this change is an optimization that does not require an update to our existing documentation.  Do you agree with that assessment?

[1]: https://www.cockroachlabs.com/docs/v19.2/architecture/replication-layer.html#raft
[2]: https://github.com/cockroachdb/cockroach/pull/38954

**Comment by nvanbenschoten** [comment]
Yes, I think you're correct. We don't go into enough detail in that section for the optimizations to have an effect.

They probably would have some impact on https://www.cockroachlabs.com/docs/v19.2/architecture/life-of-a-distributed-transaction.html, but that page seems a little confused to me in certain places, and could really use some diagrams.

**Comment by rmloveland** [comment]
> They probably would have some impact on https://www.cockroachlabs.com/docs/v19.2/architecture/life-of-a-distributed-transaction.html, but that page seems a little confused to me in certain places, and could really use some diagrams.

Thanks for confirming.  In that case it sounds like the scope of work for this issue is:

- Update [Life of a distributed transaction](https://www.cockroachlabs.com/docs/v19.2/architecture/life-of-a-distributed-transaction.html) to ensure that its description of how our Raft protocol works is correct.

- To be thorough I think we should also update the replication layer docs as well to include the information about this optimization, lest they lag too far behind reality.  

Do you agree with the above?

**Comment by nvanbenschoten** [comment]
I agree, although I don't think either doc is incomplete without mentioning the optimization.

**Comment by rmloveland** [comment]
> I don't think either doc is incomplete without mentioning the optimization.

@nvanbenschoten I've just reviewed both docs again and agree with your assessment.  I don't think this level of detail needs to be documented.

Therefore I'm closing this issue.  Please re-open if you disagree.
