### ISSUE TITLE
Better insight into constraint conformance

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4730]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/reckmMLBqVHuJjlVn?blocks=hide
PM: @awoods187, @piyush-singh 
Eng: @andreimatei

**Comment by rmloveland** [comment]
@andreimatei I see that the [constraint conformance RFC PR][1] is still open.  Has any user-facing development happened that would require docs work for the 19.2 release?

[1]: https://github.com/cockroachdb/cockroach/pull/38309

**Comment by andreimatei** [comment]
Yes. We're scrambling to get a couple of new system tables in.
