### ISSUE TITLE
Atomic replication: ETCD Changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4731]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recEjVou4DKjRbShz?blocks=hide
PM: @awoods187 
Eng: @tbg, @bdarnell

**Comment by rmloveland** [comment]
Closing this as it's the same basic issue as #4722 AFAICT.

@tbg I can't see any reason why this would have doc impact given that #4722 did not.  No need to respond unless you disagree with that assessment.
