### ISSUE TITLE
Core Error Handling Improvements 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4732]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recdHB5suEm5yU6gN?blocks=hide
PM: @awoods187 
Eng: @knz

**Comment by rmloveland** [comment]
@knz I saw the [error handling RFC][1] was merged.  Is there code in CRDB I can look at to see what has changed and determine whether / if docs which include error messages will need updates?  I [searched for the RFC issue ID][2] but didn't see much.

[1]: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md

[2]: https://github.com/cockroachdb/cockroach/issues?utf8=✓&q=is%3Aissue+%2336987

**Comment by knz** [comment]
There is no doc work needed for this item.
