### ISSUE TITLE
Trace Information on Statements Page in Admin UI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4736]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recDDX3AlQ7rNqPja

Description: On the statements page in the Admin UI, users will be able to view a trace of statement(s). The traces displayed will either be a randomly sample to help users understand the tool or specifically requested ones.

Addressing the problem of observability, the traces will help users understand why queries are slow, whether your mental model of CRDB is correct (e.g. was this query served from the locality that I want).

Internally, the traces will help CRDB engineers find ways to improve CRDB's query execution.

**Comment by taroface** [comment]
cc'ing @piyush-singh

**Comment by taroface** [comment]
Update Statements page:

- https://github.com/cockroachdb/cockroach/issues/45248
- https://github.com/cockroachdb/cockroach/issues/45249
- https://github.com/cockroachdb/cockroach/issues/45246
- https://github.com/cockroachdb/cockroach/issues/45247
- https://github.com/cockroachdb/cockroach/issues/45250

**Comment by rmloveland** [comment]
@taroface it looks like you are documenting the Admin UI access to CockroachDB SQL statement trace information via this issue.

If I understand this issue correctly, the work you are doing here will fix issue #6253  (Which is great if true, by the way!)

Do you agree with this assessment?

**Comment by taroface** [comment]
@rmloveland Yes, it is true! 

That said, the current implementation downloads a statement trace as a JSON and we don't yet provide any help on visualizing or interpreting the trace. One of your requirements for #6253 was to explain "how to read the available traces" - do our docs have any existing context on this, or should I just do some research? From what I can tell, we basically recommend that people [send the trace to support](https://www.cockroachlabs.com/docs/stable/query-behavior-troubleshooting.html#query-is-sometimes-slow).

**Comment by rmloveland** [comment]
> was to explain "how to read the available traces" - do our docs have any existing context on this, or should I just do some research?

As far as I can tell, the things that can read these trace files are called (confusingly) "tracers", and there is a list here:  https://opentracing.io/docs/supported-tracers/

I think in general the (an?) expectation is that you use an "APM" (application performance management) tool like Datadog or one of the others listed on the above link to see what the trace info actually means.

Re: whether we should recommend that folks download this file and send it to Support on request the same way we do with `SHOW TRACE`, I'm not sure.  Although if we are just sticking a link in the Admin UI, it seems like the answer is yes?

@piyush-singh what do you think of the above?

**Comment by taroface** [comment]
Just remembered that @piyush-singh told me on Slack:

> We are mostly expecting users to send this data to us at CRL so we can diagnose issues for them. 
> ...
> In the future we will build some comprehensions on top of this JSON to extract information in a way that is easier for users to understand (e.g. this txn was slow because it was in the txn wait queue behind txn ID = '12345').
