### ISSUE TITLE
Improve time selection capabilities for time series dashboards

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4737]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec5q3DBXUVInHcL0?blocks=hide
PM: @piyush-singh 
Eng: 

User stories:
- S473: As a developer, I want to be able to easily view any historical slice of time on my time series dashboards for post-mortem analysis of issues in my cluster.
- S472: As a developer, I want to be able to share links to the time series dashboards that preserve my time selection so that I can easily share information from a specific time window with my colleagues when doing a post-mortem.

**Comment by taroface** [comment]
Duplicates #6218
