### ISSUE TITLE
Locality-aware backup and restore

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4743]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recZY1atACrLiKG5Z?blocks=hide
PM: @rolandcrosby 
Eng:

**Comment by lhirata** [comment]
https://github.com/cockroachdb/cockroach/pull/39250

**Comment by jseldess** [comment]
@rmloveland, from https://github.com/cockroachdb/docs/issues/5275#issuecomment-527560705:

> When documenting this, be sure to note that for geo-partitioning use cases, the user should verify that the leaseholders are in the expected location before starting the backup. They can do this via the data distribution page in the web UI or the show ranges statement.

**Comment by rmloveland** [comment]
Thanks @jseldess !  Updating the docs PR now, which currently only implies this.
