### ISSUE TITLE
Incremental IMPORT (append to existing tables)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4744]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec61l6R44P4iVk17?blocks=hide
PM: @rolandcrosby 
Eng:

User stories:
- S421: As a DBA, I want to migrate my data from an existing database to CockroachDB in incremental chunks, so I don't need to allocate the storage space required for a full dump of my existing database.
- S301: As a developer, I want to migrate and synchronize my production database so I can swap technologies without downtime or data loss.
- S251: As a DBA, I want to import CSV data into existing tables so that I can update CockroachDB with bulk data that was produced by another upstream application.
- S245: As a DBA, I want to be able to import bulk data quickly into CockroachDB so that I can keep it up to date with data generated by other systems.

**Comment by lhirata** [comment]
Prototype for alpha: https://github.com/cockroachdb/cockroach/pull/37451

**Comment by jseldess** [comment]
Great work getting a draft merged for the alpha, @lhirata! How do you want to handle follow-up work? For example, I think we should look for other places where we want to highlight this feature, including the SQL Best Practices page.

**Comment by lhirata** [comment]
@jseldess - good idea. I will open a new issue to track the follow up work.
