### ISSUE TITLE
 Schema changes within transaction

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4748]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recKJCGJH3eZEqzLD?blocks=hide
PM: @awoods187 
Eng:

**Comment by lnhsingh** [comment]
@ericharmeling passing to you but reassign if you think this is incorrect!

**Comment by ericharmeling** [comment]
Closing in favor of future roadmap docs issue.
