### ISSUE TITLE
Support ALTER TABLE ALTER COLUMN SET NOT NULL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4752]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec60gTZQrwQ0Eylz?blocks=hide
PM: @rolandcrosby, @awoods187

**Comment by lhirata** [comment]
https://github.com/cockroachdb/cockroach/issues/28751
https://github.com/cockroachdb/cockroach/pull/37554

**Comment by lhirata** [comment]
Added support for ALTER TABLE ... ALTER COLUMN ... SET NOT NULL, which adds a non-null constraint to an existing column.
