### ISSUE TITLE
Improve interaction of automatic statistics and import/restore

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4754]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/reckx8mw3RCJuTHeA?blocks=hide
PM: @rolandcrosby, @awoods187 
Eng: @RaduBerinde

**Comment by lhirata** [comment]
Chatted with @rolandcrosby today about this. No docs changes needed.
