### ISSUE TITLE
Improved cancellation/failure behavior for bulk I/O and schema change jobs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4756]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recutpteYEwc1DneC?blocks=hide
PM: @rolandcrosby 
Eng:

**Comment by jseldess** [comment]
@lnhsingh, according to AT, this got done in 19.2. Were any doc updates required?

**Comment by lnhsingh** [comment]
No docs updates needed- no user facing changes in 19.2. This was more for laying groundwork for more schema/jobs changes in 20.1
