### ISSUE TITLE
Backup and Restore Doc Update 

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4764]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

Re: [Backup and Restore](https://cockroachlabs.com/docs//v19.1/training/backup-and-restore.html)

In the heading for Step 2, "Core" should be "core"

**Comment by MGHinoveanu** [comment]
Gabi is working on this

**Comment by lhirata** [comment]
1. Fork the cockroachdb/docs repo
2. Clone your fork of the repo: `git clone docs_url`
3. edit the files you want to edit, e.g., `open v2.1/bytes.md`
4. run `git status` to see what changes were made and verify they are what you wanted
5. once you’re happy with the changes run `git add v2.1/bytes.md` (or whatever files you edited)
6. run `git status` again to make sure you added what you want (it should say “changes staged for commit”)
7. run `git commit -m "MY COMMIT MESSAGE"` with whatever commit message you prefer
8. run `git push origin master` to push your changes to your forked copy on Github
9. in git web UI, click “make pull request”
10. follow the prompts in the UI to make the pull request
