### ISSUE TITLE
Granular Roles and Privileges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4766]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recCHyCs4TR6kO3gs?blocks=hide
PM: @rolandcrosby 
Eng: @mberhault 

Github Tracking Issue: cockroachdb/cockroach#15005 cockroachdb/cockroach#20149 cockroachdb/cockroach#29633 #4766 cockroachdb/cockroach#41380 #5960

**Comment by mberhault** [comment]
AFAIK this isn't even scheduled for 19.2. Is this a "make sure all airtable entries had docs issues" thing, or is it premature?

**Comment by jseldess** [comment]
@mberhault, it's on the 19.2 roadmap; thus, this issue. @rolandcrosby, do you have additional insight?

**Comment by rolandcrosby** [comment]
Hey @jseldess, sorry for the miscommunication, but the list of things in the 19.2 milestone for Ops & Tools currently contains items that do not have engineering resources budgeted. This is one of them. You can hold off on creating additional docs issues for Ops & Tools for the moment until I get this cleaned up.

**Comment by jseldess** [comment]
Ok. Thanks for the clarification, @rolandcrosby. I already created issues for each ops and tool roadmap item, so please let me know which to close when you know.

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/5960
