### ISSUE TITLE
Split client SQL and internal GRPC ports

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4771]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recgQzvNRyRwXRCJS?blocks=hide
PM: @rolandcrosby 
Eng:

**Comment by jseldess** [comment]
Copied over from https://github.com/cockroachdb/docs/issues/5307:

PR: https://github.com/cockroachdb/cockroach/pull/39305

From release notes:
> [`cockroach start`](../v19.2/start-a-node.html) now accepts a `--sql-addr` [flag](../v19.2/start-a-node.html#flags), which makes it possible to accept connections by clients on a separate TCP address and/or port number from the one used for intra-cluster (node-node) connections. This is aimed to enable firewalling client traffic from server traffic. [#39305][#39305] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@lhirata, this got done. Can you take it, or should I?

**Comment by jseldess** [comment]
@taroface, @Amruta-Ranade, this docs gap has come up multiple times recently. Any updates on a plan forward here?

**Comment by aaron-crl** [comment]
cc @thtruo

**Comment by jseldess** [comment]
@Amruta-Ranade, this came up again from our field colleagues: https://github.com/cockroachdb/docs/issues/7716. Any updates? I think you have a PR open?

**Comment by Amruta-Ranade** [comment]
Yep! https://github.com/cockroachdb/docs/pull/7537

**Comment by Amruta-Ranade** [comment]
Update: Discussed with Aaron, Raphael, and Jesse -- decided to move the new flags after the existing flags in the Network flags table and mark them as "Advanced"
