### ISSUE TITLE
Client certificate cluster name validation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4772]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recJ1E7P6sFZkqU3y?blocks=hide
PM: @rolandcrosby 
Eng:

**Comment by lhirata** [comment]
Added the ability to restrict joining based on cluster name. If you specify cluster name, only certs with that cluster name will be valid. the rest did not make it in.

**Comment by lhirata** [comment]
https://github.com/cockroachdb/cockroach/pull/39828 - on hold for now.

**Comment by jseldess** [comment]
Def not in 19.2. Moving to 20.1 milestone for now.

**Comment by jseldess** [comment]
Closing for now
