### ISSUE TITLE
Minor edits: Life of a Distributed Transaction

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4775]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

On the `v2.1/architecture/life-of-a-distributed-transaction.md` and `v19.1/architecture/life-of-a-distributed-transaction.md` pages, make the following edits:

- (line 140) Add a comma after `i.e.`
- (line 140) Change `timestmap` to `timestamp`
- (line 172) Add a comma after `i.e.`
- (line 188) Add a comma after `e.g.`

**Comment by kgorryhines** [comment]
I'm claiming this one

**Comment by lhirata** [comment]
Closed by #4827
