### ISSUE TITLE
Minor edits: Common Errors

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4777]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

On the `v2.1/common-errors.md` and `v19.1/common-errors.md` pages, make the following edit:

- (line 60) Change `can't` to `cannot`

**Comment by liscobeck** [comment]
I'm claiming this one.

**Comment by lhirata** [comment]
Closed by #4826
