### ISSUE TITLE
Minor edits: Contribute to CockroachDB

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4778]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

On the `v2.1/contribute-to-cockroachdb.md` and `v19.1/contribute-to-cockroachdb.md` pages, make the following edits:

- (line 26) Change `don't` to `do not`
- (line 27) Change `don't` to `do not`
- (line 30) Change `won't` to `will not`
- (line 56) Change `don't` to `do not`

**Comment by allisongisinger** [comment]
I'll take this.
