### ISSUE TITLE
Minor edits: Create Index

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4779]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

On the `v2.1/create-index.md` and `v19.1/create-index.md` pages, make the following edit:

- (line 113) Change `don't` to `do not`

**Comment by Tubetti** [comment]
I'll take this one.

**Comment by lhirata** [comment]
1. Fork the cockroachdb/docs repo
2. Clone your fork of the repo: `git clone repo_URL`
3. edit the files you want to edit, e.g., `open v2.1/bytes.md`
4. run `git status` to see what changes were made and verify they are what you wanted
5. once you’re happy with the changes run `git add v2.1/bytes.md` (or whatever files you edited)
6. run `git status` again to make sure you added what you want (it should say “changes staged for commit”)
7. run `git commit -m "MY COMMIT MESSAGE"` with whatever commit message you prefer
8. run `git push origin master` to push your changes to your forked copy on Github
9. in git web UI, click “make pull request”
10. follow the prompts in the UI to make the pull request
