### ISSUE TITLE
Minor edits: Encryption

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#4781]
If you are contributing to the Cockroach Labs docs for the first time, thank you! To get started, check out our [Contributing guide](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md).

Edits: 

On the `v2.1/encryption.md` and `v19.1/encryption.md` pages, make the following edit:

- (line 225) Remove `:` from the end of the heading

**Comment by Hq190204** [comment]
Hong is working on this.

**Comment by chelsealee** [comment]
This issue has been resolved.
