### ISSUE TITLE
truncated Contribute menu

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#4782]
Here's how it looks at the default zoom level on my laptop:

<img width="646" alt="Screenshot 2019-05-09 23 01 56" src="https://user-images.githubusercontent.com/377201/57499710-b058db00-72ae-11e9-8f50-35052375ce73.png">

Re: [Install CockroachDB on Mac](https://cockroachlabs.com/docs//v19.1/install-cockroachdb-mac.html)

**Comment by jseldess** [comment]
Fixed in the meantime. @andreimatei, please re-open if this is still happening for you.
