### ISSUE TITLE
Install CockroachDB on Mac Doc Update

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#4783]
Andrei Matei (andreimatei) commented:

Re: [Install CockroachDB on Mac](https://cockroachlabs.com/docs//v19.1/install-cockroachdb-mac.html)

The installation page doesn't link to the old releases page. In fact I've had difficulties finding the old releases page. It should be front and center.

Jira Issue: DOC-2341

**Comment by jseldess** [comment]
First sentence links to the relevant release notes page, which exposes the other options in the sidenav. I think it's ok now, but please re-open if you disagree, @andreimatei.

**Comment by andreimatei** [comment]
> think it's ok now, but please re-open if you disagree,

I do respectfully disagree :)
Clicking on "release notes", then using the sidenav, is far from ideal :P
I conjecture that the releases page is the one that most people want to get to. We need to make link to it much more prominently.
