### ISSUE TITLE
Automatic app reconnection when node restarts

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4784]
## Title

When a connection is established to a CockroachDB node and that node goes away for planned or un-planned reasons, then the client needs to re-establish the connection.  

## Description

Connection can be re-established automatically by some load balancer and connection pool managers.  If not, then application should re-establish the connection.

## Outline

- provide example of load balancer that has automatic reconnection 
- provide example of connection pool manager that has automation reconnection 

## Expected Audience

Application developers

**Comment by ianjevans** [comment]
Fixed with #6706.
