### ISSUE TITLE
Improve FK Performance

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4788]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recyD7SfclLIqbF2B?blocks=hide
PM: @awoods187 
Eng:

**Comment by rmloveland** [comment]
@awoods187 and @RaduBerinde,

it looks like `sql.defaults.experimental_optimizer_foreign_keys.enabled` is already captured in the 19.2 [cluster settings docs](https://www.cockroachlabs.com/docs/v19.2/cluster-settings.html).

If I remember our convo from a little while back, we're planning to hold off on any documentation around this setting and optimizer FKs in general until 20.1.  Is that correct?

**Comment by RaduBerinde** [comment]
Yup!
