### ISSUE TITLE
Productionize vectorization prototype

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4790]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec6XtFIj6grDDHAS?blocks=hide
PM: @awoods187 

Create a new section with the following information:
- [x] Document settings, link to cluster setting docs
- [x] Explain how vectorized execution works conceptually and mechanically similarly to other non-user facing architectural changes (e.g. parallel commits)

**Comment by ericharmeling** [comment]
AFAICT, the documentation impact of vectorization will be minimal.

Quote from the Airtable entry:
> This is not a customer facing feature--queries will be automatically faster to users.

Vectorization looks to be more of a performance improvement thing that we can really only document conceptually (which could still be very important!).

@awoods187 Am I missing something? Thoughts?

**Comment by awoods187** [comment]
we will need to document the following:

- how to turn off the default setting and return to DistSQL only
- how to turn on the full setting for testing the further out prototype
- how to return to the default setting with vec on for some queries 

We should also begin to explain how vectorized execution works conceptually and mechanically similarly to other non-user facing architectural changes. We should document this, in the same manner, we would parallel commits from core.

Does that make sense?

**Comment by ericharmeling** [comment]
Awesome. Thanks. Just added these as tasks in the issue. overview.
