### ISSUE TITLE
Recommend homogenous nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4791]
Jesse Seldess commented:

It's somewhat common knowledge, internally, that CockroachDB does better when nodes are running across homogenous machines. We should document this recommendation, why and to what extent it's important, and the drawbacks of heterogeneous machines. 

Jira Issue: DOC-273

**Comment by keith-mcclellan** [comment]
honestly, we should probably do some testing on the impact of heterogeneity on performance... we're going to have some in multi-cloud deployments.  But 100% agree we should recommend that the nodes be as similar as possible.

**Comment by bdarnell** [comment]
As a simple rule of thumb, a heterogenous N-node cluster can be expected to perform as if it were N copies of its slowest node. It's possible to exceed this with careful use of zone configs to ensure that hot data is constrained to the faster nodes, but this is basically uncharted territory.
