### ISSUE TITLE
Support third-party development of Hibernate dialect (+Spring)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4792]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec7gNK6fdZFFkqG0?blocks=hide
PM: @awoods187

**Comment by rmloveland** [comment]
@awoods187 it seems like this is a Product task that does not require any docs update at this time.  Do you agree with that assessment?  If so I'd like to close.

**Comment by awoods187** [comment]
I think that's fine for now. We can open more specific docs issue as we progress.
