### ISSUE TITLE
Support third-party development of Liquibase 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4793]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recMl27xd8py3IKYX?blocks=hide
PM: @awoods187

**Comment by ericharmeling** [comment]
https://github.com/timveil-cockroach/liquibase-example

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/5989.
