### ISSUE TITLE
Make the CockroachDB integer types more compatible with postgres (take advantage of the new type changes)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4794]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec0wacu7aB3fOIeR?blocks=hide
PM: @awoods187

**Comment by ericharmeling** [comment]
https://github.com/cockroachdb/cockroach/issues/26925

**Comment by ericharmeling** [comment]
@awoods187 

@jordanlewis listed the following items for doc for this issue in 19.2:

> 1. cockroachdb in 19.2 sends the correct byte-width for all integer types. if you retrieve an int8 you’ll get 8 bytes, int2 you’ll get 2 bytes. before 19.2, we always sent 8 bytes which confused clients.
> 2. cockroachdb in 19.2 differs from postgres by default in that if you make a column of type `int` or `integer` we’ll give you an 8-byte integer column. in postgres it gives you a 4-byte integer column.
> 3. if you need to make this the same as postgres, you can use the setting `default_int_size=4`


These are all already documented at https://www.cockroachlabs.com/docs/dev/int.html. I'm going to close this issue. Please re-open if either of you disagree.
