### ISSUE TITLE
SQL: Support Core Admission Control

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4795]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recCJCwvu39T4a39Q?blocks=hide
PM: @awoods187

**Comment by rmloveland** [comment]
@awoods187 after our discussion today my understanding is that this is not happening for 19.2.  Is that correct?

**Comment by awoods187** [comment]
The work to support from SQL did happen but doesn't need documentation. The full feature isnt happening in 19.2 and is tracked via another issue

**Comment by rmloveland** [comment]
Thanks Andy!  Since it doesn't need documentation I will remove this from the current milestone.

**Comment by jseldess** [comment]
Closing for now.
