### ISSUE TITLE
Make it easy to focus queries onto partitioned data 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4796]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recKgsWJj2YKGBh50?blocks=hide

PM: @awoods187

**Comment by rmloveland** [comment]
Per AT this is now 20.2

**Comment by ericharmeling** [comment]
@rmloveland I think there are duplicate airtable entries for this, or that we have the wrong one in the issue description.

The one in the issue description has a different title than this issue and says 20.2 is the milestone. [This one](https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recKgsWJj2YKGBh50?blocks=hide) has the same title and says that it's already merged.

@awoods187 Correct me if I am wrong.

**Comment by ericharmeling** [comment]
Err... my mistake.

This one
<https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recKgsWJj2YKGBh50?blocks=hide>
has
the same title and says 19.2 that it's already merged.

**Comment by awoods187** [comment]
@ericharmeling this one https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recKgsWJj2YKGBh50?blocks=hide is in scope and already merged as you said and should be reflected in the top part of this issue

**Comment by ericharmeling** [comment]
Got it. Fixed the issue description and updated the milestone.

**Comment by awoods187** [comment]
Note the slack channel conversation about the release notes here--we want to avoid confusing users on what's changed. https://cockroachlabs.slack.com/archives/CEUB78J7M/p1570129220011500

**Comment by ericharmeling** [comment]
@jseldess 
After reading through the partitioning docs, I'm not finding anywhere where we explicitly query partitioned tables using SQL statements. In most partitioning docs (e.g. [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html) and [Geo-Partitioned Replicas](https://www.cockroachlabs.com/docs/dev/topology-geo-partitioned-replicas.html#steps)), there is a simple "Verify table partitions" section after partitioning is complete (simple `SHOW RANGE` and `SHOW PARTITIONS` statements). In the performance-testing partitioning docs (e.g. [Performance Benchmarking](https://www.cockroachlabs.com/docs/dev/performance-benchmarking-with-tpc-c.html#step-7-run-the-benchmark) and [Low-latency Reads and Writes](https://www.cockroachlabs.com/docs/dev/demo-low-latency-multi-region-deployment.html#step-9-re-check-latency)), we check latencies with a command-line utility or with the Admin UI. So it doesn't look like we need to update any existing examples AFAICT. Please correct me if I am wrong.

@awoods187 
It could be the case that calling this out in documentation might be more confusing than clarifying. I was pretty confused about what the actual update in behavior was here. And an end user was confused enough from the release notes to ask us. If we do have doc on this change, I think we should make it minimal (just a sentence or two on the [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html) or [PARTITION BY](https://www.cockroachlabs.com/docs/dev/partition-by.html) pages).

**Comment by awoods187** [comment]
As discussed offline, I think we need to add some examples of querying partitioned data. We don't need to highlight the difference from 19.1 just focus on a couple of things. The best query will have a WHERE predicate that limits the query to a specific partition. If developers are unsure where data is located (for example if its passed in from another service) or they forget to add this kind of predicate, the CBO will be smart enough to check each partition in parallel. This returns results much faster than one giant sequential table scan because of parallelism.
