### ISSUE TITLE
Allow users to partition a table and all secondary indexes with a single command

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4797]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec6WkrR0y6cUsfML?blocks=hide
PM: @awoods187

**Comment by rmloveland** [comment]
Looks like this one has also been bumped to 20.1 also

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/5981
