### ISSUE TITLE
Multi-column stats 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4798]
https://cockroachlabs.atlassian.net/browse/CRDB-187

**Comment by rmloveland** [comment]
Per Airtable, this has been bumped to 20.1

**Comment by ericharmeling** [comment]
Per Airtable, this has been bumped to 20.2

**Comment by ericharmeling** [comment]
GH tracking issue:
https://github.com/cockroachdb/cockroach/issues/34422

Related to:
- https://github.com/cockroachdb/docs/issues/7611
- https://github.com/cockroachdb/docs/issues/7617
