### ISSUE TITLE
CSR approval missing from Kubernetes training

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4803]
From a user:

> In the kubernetes scaling section, the approval of the csr request is missing.
https://www.cockroachlabs.com/docs/v19.1/training/orchestration-with-kubernetes.html
The rest is working very well.

**Comment by ikzelf** [comment]
also  in removing nodes: suddenly  there is --insecure.
Should have been 
kubectl exec -it cockroachdb-client-secure -- ./cockroach node decommission <node id> --certs-dir=/cockroach-certs --host=cockroachdb-public

**Comment by jseldess** [comment]
Thanks for catching this errors, @ikzelf. Just opened a PR with fixes: https://github.com/cockroachdb/docs/pull/4812
