### ISSUE TITLE
performance: cluster recommendations page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4806]
Add a page on cluster size that includes:

Short-term:
- [ ] Node Sizes (CPU, Memory)
- [ ] Machine Types  (GCP: n1-standard, AWS: c/m series, Azure: F series)
- [ ] 3 node minimum
- [ ] Homogenous nodes
- [ ] Leverage [production checklist](https://www.cockroachlabs.com/docs/v19.1/recommended-production-settings.html#file-descriptors-limit)

Medium Term:
- [ ] Link to topology patterns

Long term:
- [ ] Benchmark information on a handful of representative topology patterns on the topology pattern page (mention here that guidelines exist elsewhere)

**Comment by awoods187** [comment]
Yugabyte docs https://docs.yugabyte.com/latest/benchmark/performance/

**Comment by awoods187** [comment]
TiDB: https://github.com/pingcap/docs/blob/master/v2.1/op-guide/recommendation.md

**Comment by jseldess** [comment]
@awoods187, can you clarify this request? Almost everything in your list is covered in the production checklist at this point.

**Comment by awoods187** [comment]
Well, they weren't there when I made this request in May 2019 :) . I think we can close this.
