### ISSUE TITLE
Typo in create-user.md

### ISSUE THREAD

**Issue by imjching** [cockroachdb/docs#4807]
See `Considerations`.

Should be "Usernames:" instead of "Role names:".

<img width="916" alt="Screen Shot 2019-05-14 at 4 37 21 PM" src="https://user-images.githubusercontent.com/6175557/57730498-9597b500-7666-11e9-8eed-877424a3d335.png">

Seems like this was taken from `CREATE ROLE`: https://www.cockroachlabs.com/docs/stable/create-role.html.

**Comment by jseldess** [comment]
Thanks for reporting this, @imjching!
