### ISSUE TITLE
Reasonable defaults for GKE node pool instance size in Kubernetes docs

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/docs#4811]
Our [orchestrate CockroacdhDB with Kubernetes](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html) docs has users create a new GKE cluster with a default node pool. This node pool runs [n1-standard-1](https://cloud.google.com/compute/docs/machine-types) instances, which are woefully underprovisioned for running CockroachDB. 

We should have users create a node pool with a more reasonable default instance type, such as an n1-standard-4. This can be done by passing a `--machine-type` flag to the `gcloud container clusters create cockroachdb` CLI invocation, e.g.
```
gcloud container clusters create cockroachdb --machine-type n1-standard-4
```

**Comment by tim-o** [comment]
Yeah, it also looks like the helm chart values.yaml doesn't specify a storageclass either, which (AFAICT) will result in a regional persistent disk rather than a local ssd. We probably want to at least note that they'll need to adjust the storageclass if they want to reproduce our benchmarks (or optimize performance).

**Comment by DuskEagle** [comment]
Using a local SSD means that the node's storage will be lost when the instance is stopped. There's a tradeoff to be made, so I think it should be treated as more of an advanced option.

**Comment by jseldess** [comment]
@DuskEagle, thanks for opening this. Can we also set this in the StatefulSet config? I think it'd be great to use a recommended machine type and then explicitly tell users about it in case they want to downgrade or upgrade it. Thoughts?

**Comment by DuskEagle** [comment]
Hey @jseldess, setting the machine type unfortunately can't be done within the StatefulSet. This is because the machine type is decided when you create a node pool, which is a collection of GCP virtual machines. GCP creates one node pool for you automatically when you run `gcloud container clusters create ...`, which is where I propose we tell users to set the machine type.

You can also create [additional node pools](https://cloud.google.com/sdk/gcloud/reference/container/node-pools/create), which you'd want to do if you wanted to run VMs of different sizes within a single Kubernetes cluster. If a user goes that route, they will need to use the `--node-label` flag when creating the node pool to mark that node pool as the one CockroachDB should run on, and then they'd need to match that up to the [NodeSelector](https://github.com/helm/charts/tree/master/stable/cockroachdb#configuration) option in our helm chart when creating the pods.

If you're interested in documenting this further I can work with you on hashing out the details. But for a user that's creating a Kubernetes cluster just for CockroachDB by following the docs, using the default node pool that's created via `gcloud container create ...` and passing in a custom machine type is the way to go.

**Comment by jseldess** [comment]
Got it. Thanks for the clarification, @DuskEagle. This is a relatively easy doc fix then.
