### ISSUE TITLE
Deleting large amounts of data

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4818]
There are two opportunities here:
- [ ] For deleting all rows in a table, consistently recommend `TRUNCATE` instead of `DELETE` without a `WHERE` clause.
    - The [SQL Best Practices](https://www.cockroachlabs.com/docs/v19.1/performance-best-practices-overview.html#use-truncate-instead-of-delete-to-delete-all-rows-in-a-table) doc already says this. Can probably say it clearer.
    - Our [`TRUNCATE`](https://www.cockroachlabs.com/docs/stable/truncate.html) doc suggest that, when deleting all rows from a table, it's best to use `TRUNCATE` for larger tables and `DELETE` for smaller tables. Based on feedback from @petermattis, we should stop encouraging any use of `DELETE` without `WHERE` and always recommend `TRUNCATE`. 
    - Given the above, the [`DELETE`](https://www.cockroachlabs.com/docs/v19.1/delete.html) page should much more clearly point to `TRUNCATE` for removing all rows of a table. Probably needs to be a callout in intro or something. And the [Delete all rows](https://www.cockroachlabs.com/docs/v19.1/delete.html#delete-all-rows) example needs to be adjusted as well.
-  [ ] For deleting large chunks of data from a table, do we need any recommendations or best practices beyond what's already called out in the `DELETE` docs about [disk space and select performance](https://www.cockroachlabs.com/docs/v19.1/delete.html#disk-space-usage-after-deletes)?

**Comment by jseldess** [comment]
@tim-o, @timveil, the above was worked out with @petermattis, but for the second item in particular (deleting large chunks but not an entire table), are there other considerations or recommendations we need to make?

**Comment by rmloveland** [comment]
Unassigning myself since I won't work on this soon.  Happy to take up again if / when it gets reprioritized.
