### ISSUE TITLE
Clarify utility of indexes for UPDATES and DELETES

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4819]
@thatnerd clarified why secondary indexes can slow down inserts, but in conversation, he also clarified the potential speed up for the seek portion of an update or delete when not filtering on the primary key. I just read our [main index doc](https://www.cockroachlabs.com/docs/v19.1/indexes.html) and [SQL best practices](https://www.cockroachlabs.com/docs/v19.1/performance-best-practices-overview.html#indexes-best-practices) and this guidance is completely missing, I think. We only talk about the impact of indexes on "queries", which I think is too vague. We should fix that.

**Comment by jseldess** [comment]
@thatnerd, you want to take this?

**Comment by thatnerd** [comment]
On it.

**Comment by thatnerd** [comment]
Going to try to figure out the previous PR first, then do this.

**Comment by thatnerd** [comment]
Created a branch for this: https://github.com/cockroachdb/docs/tree/wc-clarify-utility-of-indexes-for-updates-and-deletes

**Comment by rmloveland** [comment]
Is this really P-1?  I agree that we should provide this guidance in our docs, but it's not clear it "needs to be done this release" (the P-1 standard) since it's a worthy but IMO non-urgent performance optimization tip.  Gonna bump to P-2 and remove from milestone, shout if you strongly disagree.

**Comment by awoods187** [comment]
Closing this in favor of the new documentation on batch deletes.
