### ISSUE TITLE
CSV import: be explicit about column ordering

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#4838]
When importing data from CSV files, the order of the columns in the input file needs to match the column order in the schema defined by the user. A customer ran into problems with this and pointed out that this requirement isn't explicit in the documentation. The fact that we allow import of CSVs with headers (via the `WITH skip='1'` option) may also give users the wrong impression about how IMPORT works.

**Comment by rolandcrosby** [comment]
We should ensure that this gets updated on both the "Migrate from CSV" page and the IMPORT documentation.

**Comment by jseldess** [comment]
@lnhsingh, @mwang1026, is this still a doc need?

**Comment by mwang1026** [comment]
Still relevant and is a small-ish change. We can figure out when to prioritize.

**Comment by lnhsingh** [comment]
Just change the column order in the CREATE TABLE statement. Same with IMPORT INTO (order in SQL statement should match the file)
