### ISSUE TITLE
[MSO docs] Minor update to CIDR docs 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#4848]
Currently our docs say that you have to use CIDR notation to whitelist IPs in the networking page. We are working on a set up that allows users to enter IPV4 into the field and in the backend we convert them to CIDR. We need to 
1. update the docs page to say that they can enter IPV4 or CIDR and both should work
2. Depending on what the [solution](https://github.com/cockroachlabs/managed-service/pull/622) here ends up being, mention that if they entered iPV4 they might see CIDR in the network page when they next come in (this is if we decide to expose this in the front end) 
3. Update microcopy on the console which currently tells users to use CIDR notation. This should read "enter IPV4 or CIDR" . 

Question - do we also need to explain IPV4 v IPV6 v CIDR in the docs page or is that an overkill? 

We expect this to land to customers by June 3 but will be behind a feature flag in terms of timing for docs. Its also okay if this gets pushed w/out docs update for the first week or two.

**Comment by joshimhoff** [comment]
#622 updates the microcopy and makes the BE change. Amruta, I am happy to review the docs change if that makes things easier!

> Question - do we also need to explain IPV4 v IPV6 v CIDR in the docs page or is that an overkill?

If we don't mention that in general we don't support IPv6 on MSO, I think it's worth adding that. But it's a broader issue that IP whitelist.

> We expect this to land to customers by June 3 but will be behind a feature flag in terms of timing for docs. Its also okay if this gets pushed w/out docs update for the first week or two.

I don't think this needs to be behind a feature flag. If someone discovers ahead of time that we convert in our BE from plain IP to CIDR notation, I don't think it's a big deal.

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/4995
