### ISSUE TITLE
Complete Index pull request (hot ranges related)

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#4863]
[Pull request here](https://github.com/cockroachdb/docs/pull/4846)

* May need to incorporate additional information from [Ben's blog post](https://docs.google.com/document/d/1vNCVtOzDzF7cKpVypUcJpu04_rswlk_IeqWgpTMtR0Q/edit#)

DoD
* All content around indexes is in 1-2 pull requests and those PRs are approved.

**Comment by rmloveland** [comment]
@thatnerd can I steal this issue?  I would like to shepherd that PR.  I will add this issue to the upcoming Education sprint

**Comment by jseldess** [comment]
@rmloveland, Ben's [blog post on choosing index keys](https://www.cockroachlabs.com/blog/how-to-choose-db-index-keys/) is now live. It'd be great for you to review that and incorporate insights/guidance as appropriate.

**Comment by rmloveland** [comment]
@jseldess roger that

**Comment by rmloveland** [comment]
Related: Interesting potential confirmation from customer POV of "composite PKs are faster than UUIDs" in the forum at https://forum.cockroachlabs.com/t/performance-of-insert-statements/2949

**Comment by thatnerd** [comment]
Looks like I missed your original request to steal this. Glad you took it on @rmloveland
