### ISSUE TITLE
Document the importance of an appropriate idle connection limit 

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/docs#4875]
A customer recently was seeing higher than expected latency on their application. After further inspection it became somewhat clear that the reason for this latency was that they had their idle connection limit for their DB driver set to 2 (the [default in go's db/sql](https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns)) and were doing hundreds of concurrent operations. This meant that roughly every operation had to dial a new connection. In their specific case this required communicating with a remote range, adding ~200ms to each operation. I'm not sure that having docs about setting the idle connection limit would have helped in this case but in general it seems like something we should document.

This situation was made clear by inspecting the Statements page where the user authentication shows up at the top. We should probably make the rate of connection creation more visible which would make it easier for users to detect the situation but at the least, for now, we should recommend setting this limit to be high if the user expects the amount of concurrent work to be high. 

![Screenshot_2019-06-05 Details Statements Cockroach Console](https://user-images.githubusercontent.com/1839234/58983331-92df3a00-87a4-11e9-9677-6336c0e70a0c.png)

**Comment by ajwerner** [comment]
Relates directly to #4485

**Comment by ajwerner** [comment]
Maybe even duplicates, feel free to close this if the feeling is that it does.

**Comment by jseldess** [comment]
@rmloveland, I know we've had a plan to build out more robust concurrency guidance, but we might consider just adding a section to the production checklist on this and provide the most important high-level guidance. Not sure if this is actually sql or more ops/tools, so assigning @lhirata as well.

**Comment by rmloveland** [comment]
@lhirata are you taking this one?

**Comment by lhirata** [comment]
@rmloveland - Sure, I can add this as high-level guidance on the Production Checklist
