### ISSUE TITLE
sql: Unify the SQL type system

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4884]
PR: https://github.com/cockroachdb/cockroach/pull/36598

From release notes:
> Locale names in `COLLATE` clauses now have dash characters mapped to underscore when printed as part of SQL syntax. [#36598][#36598] {% comment %}doc{% endcomment %}
>
> The `information_schema.columns` table now gives more conformant output for `varbit`, `char`, `timestamp`, and `time` types. [#36598][#36598] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@awoods187 this looks like an internal refactoring of the code, and thus has no doc-relevant work attached.  Do you agree with that assessment?

**Comment by awoods187** [comment]
yes--i know we have more compatibility as a result but i dont think we have anything from this listed as a known limitation

**Comment by rmloveland** [comment]
Cool, thanks! In that case I'll close.
