### ISSUE TITLE
sql: Add crdb_internal.locality_value builtin function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4890]
PR: https://github.com/cockroachdb/cockroach/pull/37369

From release notes:
> Added a new `locality_value` [built-in function](../v19.2/functions-and-operators.html) that returns the value of the locality key given as its argument. [#37369][#37369] {% comment %}doc{% endcomment %}

**Comment by robert-s-lee** [comment]
@jseldess @rmloveland created an example for sharing with customers.

**Comment by ericharmeling** [comment]
@robert-s-lee Noted.
