### ISSUE TITLE
cli: Include collected goroutine dumps in debug zip

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4898]
PR: https://github.com/cockroachdb/cockroach/pull/36813

From release notes:
> Included collected goroutine dumps in [`cockroach debug zip`](../v19.2/debug-zip.html). [#36813][#36813] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @tbg, this doesn't have a user-facing doc impact. Closing the issue.

**Comment by jseldess** [comment]
Was thinking, if anywhere, this might be called out in the list of things included in a debug zip: https://www.cockroachlabs.com/docs/stable/debug-zip.html. But fine to leave out, if that's the consensus.
