### ISSUE TITLE
Build a Java application on CockroachDB with Spring Boot

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4904]
The Spring framework is very popular with Java developers, and SEs and customers have asked for a Spring-focused tutorial several times. We should add a third "Spring Boot" option to our [Build a Java App with CockroachDB](https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb.html) tutorial.

Note that this guidance would be fundamental, similar to the other "Build an App" tutorials. Spring Boot might also be in focus for a more robust, realistic sample app/tutorial, which is tracked by #4693.

**Comment by jseldess** [comment]
Reference for getting started with Spring Boot: https://spring.io/guides/gs/spring-boot/

**Comment by jseldess** [comment]
From @awoods187 in https://github.com/cockroachdb/docs/issues/5354: We should develop getting started docs with spring. Here is an example of the type of content we could cover: https://stackoverflow.com/questions/57771603/how-to-fix-password-problem-with-cockroachdb-and-spring-boot#comment101979392_57771603

**Comment by awoods187** [comment]
Looping in @rafiss 

I think this is important and we have a couple of design considerations. Are we going to use an ORM? If so, which one? Hibernate, jOOQ, and MyBatis are all popular. Today we have the best support for Hibernate but will have jOOQ in the next quarter. I'd like to see eventually one with each but we will prioritize for now. I think we should also take a step back and think a bit more about what documentation we want to produce and how that plays out with our new team. I'll organize a meeting for that and come with a proposal.

**Comment by rafiss** [comment]
My understanding is that in real-usage, Spring Boot is most commonly used with Hibernate. That doesn't have to make it our choice, but useful to keep in mind.

**Comment by ericharmeling** [comment]
We might be able to close this, thanks to @kai-niemi. https://github.com/cockroachlabs/roachbank

To track tutorial documentation, let's use https://github.com/cockroachdb/docs/issues/6046.
