### ISSUE TITLE
Clarify known limitation on schema changes within transactions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4905]
This [known limitation](https://www.cockroachlabs.com/docs/stable/online-schema-changes.html#no-schema-changes-within-transactions) states that arranging DML statements so they come after DDL statements should work, but it contradicts a few of [these examples](https://www.cockroachlabs.com/docs/stable/online-schema-changes.html#examples-of-statements-that-fail). And @joshimhoff confirmed that you can't, for example, add a column and then update its value within a single transaction.

**Comment by rafiss** [comment]
The docs on [the known limitations page](https://www.cockroachlabs.com/docs/stable/known-limitations.html#schema-changes-within-transactions) should also be updated. The same wording is used in [this section of the page linked in the original issue](https://www.cockroachlabs.com/docs/stable/online-schema-changes.html#limited-support-for-schema-changes-within-transactions).

https://github.com/cockroachdb/cockroach/issues/26508 tracks the mized DDL/DML transactions issue.

Here are some super simple cases that don't work:

```
create table t (a int primary key);
begin;
savepoint cockroach_restart;
alter table t add column e int;
select a,e from t;

ERROR: column "e" does not exist
SQLSTATE: 42703
```

```
create table t (a int primary key);
begin;
savepoint cockroach_restart;
alter table t add column e int;
update t set e = 1;

ERROR: column "e" does not exist
SQLSTATE: 42703
```

Note that the example in [this section of the docs](https://www.cockroachlabs.com/docs/stable/online-schema-changes.html#run-schema-changes-inside-a-transaction-with-create-table) DOES work. (I.e., if the table is created inside the transaction, it works.)
```
  BEGIN;
  SAVEPOINT cockroach_restart;
  CREATE TABLE fruits (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name STRING,
        color STRING
    );
  INSERT INTO fruits (name, color) VALUES ('apple', 'red');
  ALTER TABLE fruits ADD COLUMN inventory_count INTEGER DEFAULT 5;
  ALTER TABLE fruits ADD CONSTRAINT name CHECK (name IN ('apple', 'banana', 'orange'));
  SELECT name, color, inventory_count FROM fruits;
  RELEASE SAVEPOINT cockroach_restart;
  COMMIT;
```
