### ISSUE TITLE
CREATE TABLE Doc Update 

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#4912]
Re: [CREATE TABLE](https://cockroachlabs.com/docs//v19.1/create-table.html)

## Issue Description

The first example creates a table with no primary key, but this is never desirable in CRDB. 

## Suggested Resolution 

Swap the order of the with/without primary key examples. Add a warning to the "no primary key" example indicating that this is supported for compatibility with other databases, but that it's always better to specify a primary key.

**Comment by ericharmeling** [comment]
Resolving this as a part of this PR: #5075 

Will reference this issue in that PR.
