### ISSUE TITLE
sql: ROLLBACK statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#493]
Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

**Comment by jseldess** [comment]
@sploiselle, should this be closed now that https://github.com/cockroachdb/docs/pull/672 has merged?

**Comment by sploiselle** [comment]
Closed by #672
