### ISSUE TITLE
Pre-configured MSO configurations/ t shirt sizes of nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4940]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recoU3unp8O0VJ9vU?blocks=hide
PM: @kannanlakshmi

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/5680
