### ISSUE TITLE
CRDB online training typos

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#4943]
1. https://www.cockroachlabs.com/docs/stable/training/locality-and-replication-zones.html

On step 3 after starting nodes 7,8,9 the docs state "You started nodes 7, 8, and 9 in the East region."

They should say "You started nodes 7, 8, and 9 in the **West** region." as the datacenter is us-west.

Additionally, on Step 7 the configure zone SQL statements are missing the **./** on both SQL statements.

2. https://www.cockroachlabs.com/docs/stable/training/planned-maintenance.html

the note below is from step 2, the word mot should be **not**

![image](https://user-images.githubusercontent.com/51930844/60130193-c50d0780-9764-11e9-9979-e93487a3b631.png)

**Comment by rmloveland** [comment]
FYI I moved this into the [current sprint](https://github.com/cockroachdb/docs/projects/14?card_filter_query=assignee%3Armloveland) so it should be done by 7/4
