### ISSUE TITLE
CC: Create a cluster in the managed console  V1

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4944]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/recnbQn3CTHOOt4xQ?blocks=hide
PM: @kannanlakshmi 

To-do:

- [ ] Incorporate Tim V.'s feedback: https://docs.google.com/document/d/1p4ZSR8Ris2ak0-PlEW1JGSlkHwfSXly9Innn79FqkFs/edit
- [ ] Ask CC FE team to add doc links from the console to the price comparison doc and hardware guidance doc

**Comment by Amruta-Ranade** [comment]
Also, incorporate Tim V.'s feedback: https://docs.google.com/document/d/1p4ZSR8Ris2ak0-PlEW1JGSlkHwfSXly9Innn79FqkFs/edit
