### ISSUE TITLE
Create Kubernetes-specific production checklist

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/docs#4954]
Keith McClellan (keith-mcclellan) commented:

In addition to a few [known topics we want to factor into the docs quickly](https://github.com/cockroachdb/docs/issues/5459], we need to:

- [ ] Identify a comprehensive list of production topics for Kubernetes deployments. In some cases, this might just be Kubernetes versions of what we have on our generic production checklist. 
- [ ] Create a Kubernetes-specific production checklist, mapping to configuration settings in the statefulset yaml and helm chart ([README has default] values(https://github.com/helm/charts/tree/master/stable/cockroachdb#configuration]. 
- [ ) Thread the production recommendations and best practices through our tutorials.
- [ ) Update our Kubernetes configs and Helm charts to reflect production best practices. 

Eng support is required for all of this, on top of SE support, but especially for updating our configs. 

Jira Issue: DOC-283

**Comment by keith-mcclellan** [comment]
Jesse - Nate asked that I put this in.  This is coming up quite a bit in our partner integrations where we need to give additional guidance on how to deploy our charts in {insert k8s environment here} scenarios.  Happy to discuss.

**Comment by jseldess** [comment]
Thanks for opening this, @keith-mcclellan. Are we looking for something like [this](https://www.cockroachlabs.com/docs/stable/kubernetes-performance.html) but helm-specific?

cc @kannanlakshmi, @dicej, @joshimhoff

**Comment by taroface** [comment]
These additions will essentially supplant https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#orchestration-kubernetes and be addressed in part by refactoring/updating https://www.cockroachlabs.com/docs/stable/kubernetes-performance.html per #6165

**Comment by taroface** [comment]
Also see: https://www.cockroachlabs.com/blog/experience-report-running-across-multiple-kubernetes-clusters/
