### ISSUE TITLE
Consider a move to branch-based versioning

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4959]
Jesse Seldess commented:

Our **current versioning approach**: Keep source files for all versions in `master` via subdirectories (e.g., v2.1, v19.1, v19.2), use custom Jekyll logic to generate the site structure properly, and rebuild the entire site on each merge to `master`. 
- The main benefit is that writers can easily edit multiple versions of a file in a single PR. 
- The main downside is that, with each new version, `master` grows in size and complexity and the Jekyll build slows (though this doesn't matter too much for TeamCity builds, and we implemented a [workaround for local builds](https://github.com/cockroachdb/docs/pull/4823]].

The current approach made good sense early in our history, when we were working across doc versions constantly. It makes less sense now, as our team and content has grown and will continue to grow. We should look into a **branch/tag-based approach** instead. 
- The main benefit would be a cleaner, more manageable repo. `master` would house only the very latest version for which we offer documentation, similar to how versioning in the `cockroach` repo works. 
- The main downside would be added git complexity when needing to apply a change across versions (separate PR to backport, etc.).

Tentative plan:
- [ ] Choosing and designing the new branch/tag-based approach.
- [ ) Identifying required changes to our repo.
- [ ) Identifying required changes to our build process. There's a chance that we could [leverage Netlify](https://www.netlify.com/docs/continuous-deployment/#branches-deploys] more than we are currently.
- [ ] Implementing the changes to our repo.
- [ ) Implementing the changes to our build process.  

Jira Issue: DOC-284

**Comment by ianjevans** [comment]
Just putting in some background context here from other formats/publishing pipelines and how they deal with the versioning problem.

In Antora + asciidoc, the site config file includes different sources, and each source has a version. The site file can include both local and remote sources. The sources consist of Antora modules, which can also be either local or remote. Antora consolidates all the sources on build into a single doc set, with a version switcher based on the versions defined in the source config files.

At a previous company, we authored in Dita and used a versioned `-dev`/`-release` branch for development. Backporting fixes involved multiple PRs to each affected version. For example, the most current release is 20.2, and a doc fix is needed for 20.2, 20.1, and 19.2. The writer opens a PR to the `20.2-dev` branch. After the PR is squashed/merged, the writer would cherry-pick the merge commit to `20.1-dev` and `19.2-dev`, then open PRs for each version.

At each point release, the `-dev` branch would merge into `-release`. High priority doc fixes that needed to be published outside of the point release cycle required additional cherry-picks/PRs to `-release`. This was eventually automated by tagging the -dev PRs with a "hotfix" label, which would trigger a GitHub Action that would automatically branch, cherry-pick, and open a PR to `-release` after the -dev PR w/ "hotfix" label was squashed and merged.

As you can see, it was a complicated system, and it became a pain-point as the number of supported versions grew.

**Comment by ianjevans** [comment]
A better approach would be to use GitHub tags for each version. Each version has a branch, and when the content is ready to be published, we'd push a tag.

You still need to backport changes to the different branches. This could easily be automated with a GitHub Action (or equivalent), similar to what I described above.

The publishing pipeline would then pull in the tags to assemble everything.

One possibility is to use https://github.com/netrics/jekyll-remote-include to include remote .md files from the tag trees.
