### ISSUE TITLE
Update JSONB page with examples for UPDATE statements

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4961]
Richard Loveland (rmloveland) commented:

Via user feedback from the forum post [UPDATE statement documentation for JSONB](https://forum.cockroachlabs.com/t/update-statement-documentation-for-jsonb/2871].

Examples should show update scenarios, including the best way to update an empty JSONB field (if possible -- I haven't tested at all yet).

--- 

[6/23/21 update)

More user feedback relating to missing `UPDATE` examples for JSON-typed column values: 
https://forum.cockroachlabs.com/t/update-a-value-for-a-key-in-jsonb-object-which-has-an-array-of-arrays/4651

This feedback is specific to updating a JSONB object which has an array of arrays.

From @kernfeld-cockroach:

> [the existing thread](https://forum.cockroachlabs.com/t/update-statement-documentation-for-jsonb/2871) is about using UPDATE and `json_object`, but [the question i’m referring to](https://forum.cockroachlabs.com/t/update-a-value-for-a-key-in-jsonb-object-which-has-an-array-of-arrays/4651) is about `jsonb_set`

> an important difference is that `jsonb_set` requires a “path,” whereas `json_object` doesn’t

Jira Issue: DOC-285

**Comment by tim-o** [comment]
Zendesk ticket #[3450](https://cockroachdb.zendesk.com/agent/tickets/3450) has been linked to this issue.

**Comment by samstride** [comment]
Hi, would it be possible to have examples for all JSONB functions?

https://www.cockroachlabs.com/docs/v19.1/functions-and-operators.html#jsonb-functions

**Comment by ericharmeling** [comment]
@mattcrdb fielded a customer question from the CRDB forums (https://forum.cockroachlabs.com/t/how-do-i-map-a-json-array-into-rows/2960) about JSONB functions, exposing a fairly under-documented supported feature of CRDB: [Functions and Operators](https://www.cockroachlabs.com/docs/v19.2/functions-and-operators.html).

**Comment by SpicyThrow** [comment]
This would be very helpful! Without examples, this page https://www.cockroachlabs.com/docs/v19.1/functions-and-operators.html#jsonb-functions is useful for understanding what's possible, but without the help of @jordanlewis I would not have been able to create the query I needed.

**Comment by sandeep280993** [comment]
Hi @Amruta-Ranade,
I am new to GitHub and Open source documentation. The issue shows Open. 
I would like to work on this issue. Is it possible for me to work on this issue?  
Thanks,

**Comment by Amruta-Ranade** [comment]
@sandeep280993 Yep!
