### ISSUE TITLE
Document workaround for MySQL FIELD function

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4962]
We should document a workaround for users who are using the [MySQL FIELD function](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_field) and want to [migrate to CockroachDB from MySQL](https://www.cockroachlabs.com/docs/stable/migrate-from-mysql.html).
 
According to [this forum post on Sorting using FIELD](https://forum.cockroachlabs.com/t/sorting-using-field/2865) there may be a workaround using `array_position`.

**Comment by tim-o** [comment]
Zendesk ticket #[3462](https://cockroachdb.zendesk.com/agent/tickets/3462) has been linked to this issue.

**Comment by deeptikorwar** [comment]
@Amruta-Ranade, can I work on this one?

**Comment by deeptikorwar** [comment]
@rmloveland, I am an external contributor and I don't have access to this Zendesk ticket: [#3462](https://cockroachdb.zendesk.com/agent/tickets/3462)

Based on [this forum post on Sorting using FIELD](https://forum.cockroachlabs.com/t/sorting-using-field/2865), I'm planning to add a new section under "Considerations" in [migrate to CockroachDB from MySQL](https://www.cockroachlabs.com/docs/stable/migrate-from-mysql.html).

### FIELD function
The MYSQL FIELD function is not supported in CockroachDB. Instead, you can use the `array_position` function, which returns the index of the first occurrence of element in the array.

While MYSQL returns 0 when the element is not found, CockroachDB returns `NULL`. So if you are using the `ORDER BY` clause with the `array_position`  function, the caveat is that sort is applied even when the element is not found. As a workaround, you can use the COALESCE operator.

Example:
`SELECT array_position(ARRAY[4,1,3,2],1);`

  `array_position`
`------------------`
  `             2`
`(1 row)`

`SELECT * FROM table_a ORDER BY COALESCE(array_position(ARRAY[4,1,3,2],5),999);`

Will this work? Is there anything else that I can add on this workaround?

**Comment by rmloveland** [comment]
Hy @deeptikorwar thanks for pulling this together.  I think that works.  Mind putting it in a PR so we can test and review?  Thanks!

**Comment by rmloveland** [comment]
Fixed by #8751
