### ISSUE TITLE
Research tools for pulling code samples from a separate repo into a static site

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4963]
If we are going to [host code samples in a separate repo](https://github.com/cockroachdb/docs/issues/3203), we need to research the tools/techniques for doing that.

Estimated scope of work:

- Investigate state of the art in general for static sites (guess: SSG-specific plugins)
- Look at Jekyll plugins specifically (e.g., https://github.com/bwillis/jekyll-github-sample - there are likely many others)
- Also review if Hugo has any such plugins (since we may be moving to this port of our docs site to Hugo at some point: https://github.com/mjibson/hugo-docs)
- Talk to people at CRL
- Talk to people on WTD Slack
- ???
- Profit!!!1!

This is a sub-task of #3203

**Comment by rmloveland** [comment]
/cc @ericharmeling since @jseldess mentioned that you have mentioned hosting our code samples externally as well

If you have ideas / suggestions / general comments please feel free to chime in!  I'm planning to work on this issue in the [current sprint](https://github.com/cockroachdb/docs/projects/14)

**Comment by ericharmeling** [comment]
Thanks @rmloveland ... 
I do have a couple comments:

- If we are moving from Jekyll to Hugo, should we limit our research to Hugo to avoid learning plugins for both? The move to Hugo seems more imminent than moving example code over to a new repo, but I'm not sure?
- We should definitely at other repos with example ORM code to see what their testing set-up is like. E.g. [examples-orms](https://github.com/cockroachdb/examples-orms).

**Comment by jseldess** [comment]
@ericharmeling, @rmloveland, the move to Hugo is dependent on @mjibson having time and energy to get us over the finish line, which isn't trivial. If this is crucial for making a decision about storing code samples, we should discuss more in person. If we were to move to [branch-based versioning](https://github.com/cockroachdb/docs/issues/4959), Jekyll would probably be fine to stick with. The main problem is we don't have in-house Ruby expertise, whereas Hugo is Go.

**Comment by rmloveland** [comment]
@ericharmeling I finally wrote up my findings / opinions on this topic so far in a wiki page: https://cockroachlabs.atlassian.net/wiki/x/jAD6C

Please take a look and let me know what you think via comments on that page (since I think it will be easier to track the discussion there in one place).

**Comment by rmloveland** [comment]
Since the task was "research this thing", and I've completed a writeup of my initial findings in https://cockroachlabs.atlassian.net/wiki/x/jAD6C, I'm gonna move this one to done.
