### ISSUE TITLE
Partitioning docs have invalid syntax

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/docs#4964]
From https://www.cockroachlabs.com/docs/stable/partitioning.html:

```
CREATE TABLE foo (a STRING PRIMARY KEY, b STRING) PARTITION BY LIST (a) (
    bar VALUES IN ('bar'),
    default VALUES IN (DEFAULT)
);
```

`bar` and `default` here need to be prefixed by `PARTITION`.

**Comment by lucky-c** [comment]
Hi, may I take this one?
I assume the given link is for version 19.1.11 and under, because current stable version does not include that query anymore. Therefore, only old version docs will be affected.
