### ISSUE TITLE
Post link to upcoming K8 blog on relevant pages

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#4976]
We have an upcoming K8 video (https://www.cockroachlabs.com/webinars/deploy-cockroachdb-on-kubernetes). We should put a banner on top of the following pages:

https://www.cockroachlabs.com/docs/v19.1/orchestrate-cockroachdb-with-kubernetes.html#main-content
https://www.cockroachlabs.com/docs/v19.1/kubernetes-performance.html#main-content
https://www.cockroachlabs.com/docs/v19.1/training/orchestration-with-kubernetes.html#before-you-begin

After the event, we should modify the banner to say watch the previous event.

**Comment by jseldess** [comment]
@maria-toft, thoughts?

**Comment by maria-toft** [comment]
@awoods187 I'm presenting this to the Docs this morning (how we can launch relevant Kubernetes content on those Docs pages) including the webinar you mentioned in rotation with the exiting Kubernetes webinar that Alex presented and our Kubernetes guide. We are hoping to go live this week. I'll post here once live. @jseldess

**Comment by maria-toft** [comment]
@awoods187 relevant cross-promotional content is now live on the docs site (on certain pages). We are rotating the kubernetes content and it will include today's webinar. Here are the kubernetes pages where the relevant content promotion is live: 

https://www.cockroachlabs.com/docs/v19.1/orchestrate-a-local-cluster-with-kubernetes-insecure.html
https://www.cockroachlabs.com/docs/v19.1/orchestrate-a-local-cluster-with-kubernetes.html
https://www.cockroachlabs.com/docs/v19.1/orchestrate-cockroachdb-with-kubernetes-insecure.html
https://www.cockroachlabs.com/docs/v19.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html
https://www.cockroachlabs.com/docs/v19.1/orchestrate-cockroachdb-with-kubernetes.html
https://www.cockroachlabs.com/docs/v19.2/orchestrate-a-local-cluster-with-kubernetes-insecure.html
https://www.cockroachlabs.com/docs/v19.2/orchestrate-a-local-cluster-with-kubernetes.html
https://www.cockroachlabs.com/docs/v19.2/orchestrate-cockroachdb-with-kubernetes-insecure.html
https://www.cockroachlabs.com/docs/v19.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html
https://www.cockroachlabs.com/docs/v19.2/orchestrate-cockroachdb-with-kubernetes.html

**Comment by jseldess** [comment]
Thanks, @maria-toft!
