### ISSUE TITLE
cockroach debug rocksdb is not fully documented

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/docs#4985]
**Is your feature request related to a problem? Please describe.**
`cockroach debug rocksdb` is not a fully documented command, but we refer to it in the data corruption troubleshooting module: https://www.cockroachlabs.com/docs/stable/training/data-corruption-troubleshooting.html 

**Describe the solution you'd like**
a page under the CLI reference for `cockroach debug rocksdb` that is similar to the other `cockroach debug` pages.

**Comment by jseldess** [comment]
We currently only document three `debug` subcommands that are clearly useful to users and claim that the rest of the subcommands are:
> useful only to CockroachDB's developers and contributors.

https://www.cockroachlabs.com/docs/stable/debug-zip.html#subcommands

@piyush-singh, @tim-o, I think this is a visibility and troubleshooting topic, so what's your opinion on documenting more `debug` subcommands. 

@keith-mcclellan, do you see this particular subcommand being useful in a particular type of doc? Perhaps if we have a doc explicitly about data corruption?

**Comment by piyush-singh** [comment]
What is the likelihood that users will be able to successfully interpret the output of the `cockroach debug rocksdb` command? If we think this truly should be used almost entirely by internal engineers, the simplest solution is removing the reference from the recovery from data corruption tutorial that Keith linked to above. On the other hand, if this is something that we expect CRDB operators to be able to understand and use, we should document the page. 

I haven't played around with this debug tool much, but a casual glance suggests this exposes a direct interface into the rocksdb instance on a local store - users could easily cause more problems in their cluster by removing keys or key ranges that CRDB needs. My suggestion is to keep this undocumented and remove the reference from the guide mentioned. Might be worth checking in with whoever created the debug interface or someone with more rocksdb experience (maybe Peter or Andrew Kryczka?).

**Comment by rmloveland** [comment]
I think this can be closed, as we do not allow choosing `--storage-engine=rocksdb` anymore [as of v21.1 and later](https://www.cockroachlabs.com/docs/stable/cockroach-start.html#storage-engine), and v20.2 is out of maintenance as of 2021-11-10 per [Current supported releases](https://www.cockroachlabs.com/docs/releases/release-support-policy.html)

(@taroface standard disclaimer please re-open if you disagree etc)
