### ISSUE TITLE
sql: UPDATE statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#499]
Intro, Synopsis, and Required Privileges are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [`INSERT`](insert.html) or [`DELETE`](delete.html).

**Comment by jseldess** [comment]
Comment from https://github.com/cockroachdb/docs/pull/813: We should provide language-specific examples of using `RETURNING` with `UPDATE`. An example query could be `UPDATE photos SET likes = likes + 1 WHERE id= $1 RETURNING likes`.

**Comment by sploiselle** [comment]
A quick note here that `a_expr` in the `UPDATE` diagram is similar to `target_elem` in [`SELECT`](https://www.cockroachlabs.com/docs/select.html) in that it supports a number of different types of input, including subqueries, as identified in #1282
