### ISSUE TITLE
MSO: Rethink Information Arch

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#4993]
Orphan pages that need to be consolidated/restructured/deleted:

- managed-clusters-page.md
- managed-cluster-overview.md
- managed-cluster-management.md
- managed-networking-page.md
- managed-sql-users-page.md

**Comment by Amruta-Ranade** [comment]
Action items (as discussed in OKR meeting with Jesse, Jeremy, Lakshmi):

- [ ] Amruta to map out the main educational phases for a CockroachCloud single-region cluster (e.g., account creation, cluster creation with hardware selection, schema design, application porting, relevant monitoring, etc.).

- [ ] Amruta to map out where guidance should be in-UI vs in-docs, or both, and where we have existing content that can be repurposed vs where we need new content.

- [ ] Amruta and Jeremy to design and drive new Docs landing page with equal CockroachDB and CockroachCloud weighting

**Comment by Amruta-Ranade** [comment]
From Cal Hacks event report: "The end-to-end tutorial is the MVP of the CC doc set. It was extremely helpful (to hackers as well as our engineers), but it’s difficult to find it in the sidebar nav since they don’t know what to search for.
I wonder if I should move it from the Tutorials category and pull it into the main menu. "

**Comment by lnhsingh** [comment]
Closing this, as it seems out of date now.
