### ISSUE TITLE
system.users is not included with backup

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#5002]
Re: [BACKUP](https://cockroachlabs.com/docs//v19.1/backup.html)

## Issue Description

It seems that in version 19.1.1 of CRDB that systems.users is not included with a backup. You will have to explicitly include it. 

## Suggested Resolution 

We should remove the section mention that this is included with every backup and then provide guidance on how to backup the users table when needed. The same should be done to the `RESTORE` documentation as well.

**Comment by jseldess** [comment]
@lhirata, making this a P-0 because an enterprise customer ran into it and it's been a known bug in our docs for a long time (see https://github.com/cockroachdb/docs/issues/2701). Shouldn't take very long to fix this. Let's try to get it into one of the next sprints. 

cc @rolandcrosby
