### ISSUE TITLE
storage/sql: Added WITH EXPIRATION option for SPLIT AT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5007]
PR: https://github.com/cockroachdb/cockroach/pull/38004

From release notes:
> Added `WITH EXPIRATION` option for [`SPLIT AT`](../v19.2/split-at.html). [#38004][#38004] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
> @ericharmeling, since you're working on split stuff, you should take this. Perhaps it's already part of your open PR?

I can add it in there for sure!
