### ISSUE TITLE
sql: support ALTER COLUMN SET NOT NULL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5010]
PR: https://github.com/cockroachdb/cockroach/pull/37554

From release notes:
> Added support for `ALTER TABLE ... ALTER COLUMN ... SET NOT NULL`, which adds a non-null constraint to an existing column. [#37554][#37554] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
Related to #4752
