### ISSUE TITLE
ui, sql: surface Implicit Transactions for Statements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5012]
PR: https://github.com/cockroachdb/cockroach/pull/36341

From release notes:
> Added `Implicit Transaction` flag to [Statements](../v19.2/admin-ui-statements-page.html) and [Statement Details](../v19.2/admin-ui-statements-page.html#statement-details-page) page. [#36341][#36341] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed through #5579
