### ISSUE TITLE
Docs pages have no scrollbar

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/docs#5029]
At least in Chrome (linux), the docs pages have no scrollbar. This can be very annoying for people who use that instead of a touchpad or scroll wheel.

![image](https://user-images.githubusercontent.com/16544120/60902792-39a07580-a23e-11e9-8235-d54242605888.png)

**Comment by jseldess** [comment]
Users in the community have mentioned this UX issue as well:

<img width="529" alt="Screen Shot 2020-02-03 at 10 46 54 AM" src="https://user-images.githubusercontent.com/15893490/73667634-8fbd8600-4672-11ea-9ed0-402444cbf528.png">

**Comment by jseldess** [comment]
Another example:

> Lack of a scroll bar is really annoying. Especially when dealing with very long pages like this one, for example: https://www.cockroachlabs.com/docs
