### ISSUE TITLE
follower reads page isn't returned in search

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5030]
![image](https://user-images.githubusercontent.com/22278911/60908025-eaac0d80-a248-11e9-9ebd-12271b55de4d.png)

In fact, you can't even get to the page from the first link.

https://www.cockroachlabs.com/docs/v19.1/follower-reads.html

**Comment by jseldess** [comment]
Hmm, strange. When I search normal and in-cognito, it's the first result...

<img width="1228" alt="Screen Shot 2019-07-10 at 2 52 07 AM" src="https://user-images.githubusercontent.com/15893490/60947121-cd655680-a2bd-11e9-93ec-d2b815e83089.png">

**Comment by awoods187** [comment]
It seems to be inconsistent. I just saw it come up first. 

@mjibson had a recent problem searching for as of system time too.

**Comment by awoods187** [comment]
Here's another example:
![image](https://user-images.githubusercontent.com/22278911/61058351-105e2180-a3c5-11e9-9797-c53828d6db4c.png)

When we want users to get to this page: https://www.cockroachlabs.com/docs/v19.1/window-functions.html

**Comment by jseldess** [comment]
This is now working fine, post-search upgrade.
