### ISSUE TITLE
Follower Reads: one-sentence description could be easier to parse

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5037]
I had a very hard time understanding the lede from [Follower Reads](https://www.cockroachlabs.com/docs/v19.1/follower-reads.html), particularly the latter clause after "at the expense":

> To reduce latency for read queries, you can use the follower reads feature, which lets the closest replica serve the read request at the expense of only not guaranteeing that data is up to date.

I think the lede is a bit confusing and might not highlight the feature's benefits as much as we would like.

Later on the page this sentence made much more sense to me:

> In widely distributed deployments, using follower reads can reduce the latency of read operations (which can also increase throughput) by letting the replica closest to the gateway serve the request, instead of forcing the gateway to communicate with the leaseholder, which could be geographically distant.

Scope:

- Rewrite lede
- Possibly also do other stuff too, IDK

**Comment by rmloveland** [comment]
cc @awoods187 FYI

**Comment by awoods187** [comment]
heavy +1 on this

**Comment by rmloveland** [comment]
Closing this, since this phrasing no longer exists in the latest versions of the [Follower Reads docs](https://www.cockroachlabs.com/docs/v21.1/follower-reads.html)
