### ISSUE TITLE
Follower Reads nit: experimental functions are not future-proof

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5038]
This is a total nit, but it really struck me (from the [Follower Reads](https://www.cockroachlabs.com/docs/stable/follower-reads.html) page):

> To future-proof this feature in your code, we've also included a convenience function (experimental_follower_read_timestamp()) that runs your queries at a time as close as possible to the present time while remaining safe for follower reads.

IIUC experimental functions can be removed / changed at any time, so it is explicitly *not* future-proofing your code to use them, since even in the best case you would have to update your code to use e.g. `follower_read_timestamp()`, and in the worst case we remove it or change it, which is the contract we've committed to for experimental features.

I think we should change the phrasing to say something like

> To make it easier to know when it's safe for your application to make follower reads, we've also included a convenience function (experimental_follower_read_timestamp()) that runs your queries at a time as close as possible to the present time.

... or something even better you come up with

**Comment by awoods187** [comment]
+1

**Comment by ndeevy** [comment]
I would like to try to fix this issue please.

**Comment by ndeevy** [comment]
And to clarify, the content to change exists and should be changed in version 19.2 [1], right?
 @rmloveland 
[1] https://www.cockroachlabs.com/docs/v19.2/follower-reads

**Comment by Amruta-Ranade** [comment]
Yep

**Comment by ndeevy** [comment]
This is fixed and merged now @Amruta-Ranade if you want to close the issue. Thanks!

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8560
