### ISSUE TITLE
Document how to augment CockroachDB dialect in SQLAlchemy

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5039]
For instructions, see [this stackoverflow post](https://stackoverflow.com/questions/56662626/how-can-i-add-a-custom-arbitrary-option-to-a-table-in-sqlalchemy).

For the record: We should def credit the author of that post in any doc update

**Comment by rmloveland** [comment]
cc @nstewart FYI - feel free to shout if you think the prioritization should be higher

also cc @ericharmeling since you are a Python wizard and may want to work on this one if/when it bubbles up in the queue :-}

**Comment by nstewart** [comment]
I'll defer to @awoods187 re-prioritization. I'm a fan of anything that makes CockroachDB + python a smoother dev experience.

**Comment by awoods187** [comment]
I think this is a great idea--at least until we have more resources. I like the idea of doing this in the meantime.

**Comment by awoods187** [comment]
Closing this as out of date.
