### ISSUE TITLE
Document or caveat schema change rollbacks

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#5044]
@lucy-zhang pointed out that some schema changes are not completely rolled back when run inside a transaction that fails. For example, it's possible that an ALTER TABLE RENAME COLUMN operation would succeed despite other statements in a transaction being rolled back. We now have an error code to alert users that this may occur, but this has not yet been added to the docs; we should add a "known limitation" to the schema change docs in the meantime.

**Comment by awoods187** [comment]
Piggybacking on top of this, we don't actually document anywhere that I can find what happens when a schema change fails. Does the index need to be dropped? Is it rolled back automatically? What should the appdev do next?

**Comment by lnhsingh** [comment]
Error code mentioned above is documented (as of [Rich's PR](https://github.com/cockroachdb/docs/pull/5803)).

Still need to fill out the schema docs, per Andy's questions.

**Comment by lnhsingh** [comment]
from awerner: I believe that the answer is that it should be cleaned up automatically and the user does not need to do anything. paul is working on making sure this is true in the upcoming release right now.
lzhang: yeah, what andrew said, except that there are problems with rolling back schema changes in transactions to watch out for, already documented here: https://www.cockroachlabs.com/docs/v19.2/online-schema-changes.html#schema-change-ddl-statements-inside-a-multi-statement-transaction-can-fail-while-other-statements-succeed

will follow up with paul.
