### ISSUE TITLE
Reconsider documentation around password authentication

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#5046]
A customer pointed out that the [Client Connection Parameters](https://www.cockroachlabs.com/docs/v19.1/connection-parameters.html) page doesn't have any examples of how to connect to a secure cluster with a password. The password parameter is only shown in the URL spec, along with the vague warning "It is not recommended to pass the password in the URL directly."

Do we still have a reason to warn against password authentication? (@bdarnell and @mberhault may have opinions on this one way or the other.) If not, we should add an example next to the examples using client certificates. If we do want to discourage password authentication, we should explain why in more detail.

(Drive-by change to make while updating this page: we should also update the `sslmode=require` explanation to explicitly indicate that it forces a secure connection but does not verify the server's identity according to any CA.)

**Comment by bdarnell** [comment]
We do not want to actively discourage password authentication (we use it in MSO because it's easy to revoke access by changing a password but we don't yet support certificate revocation). On the other hand, we might want to mention that establishing a connection with a certificate will be faster than logging in with a password.

**Comment by Amruta-Ranade** [comment]
Slack convo with Raphael: The documented guidance is correct.
Updating the `sslmode=require` explanation.

**Comment by Amruta-Ranade** [comment]
As discussed on Slack: Remove warning but don't add example.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7704
