### ISSUE TITLE
SQL support matrix

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#505]
CockroachDB SQL's support for standard SQL features.

References to get us started:
- [Postgres](https://www.postgresql.org/docs/8.3/static/features.html)
- [MySQL](http://dev.mysql.com/doc/refman/5.7/en/compatibility.html)

**Comment by sploiselle** [comment]
Forgot to close issue when published:
https://www.cockroachlabs.com/docs/sql-feature-support.html
