### ISSUE TITLE
Update INTERLEAVE doc with suggestions from Ben's index keys blog post

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5051]
We may want to update the
[INTERLEAVE](https://www.cockroachlabs.com/docs/stable/interleave-in-parent.html)
page's 'Recommendations' section with the suggestions from [Ben's
recent index keys blog
post](https://www.cockroachlabs.com/blog/how-to-choose-db-index-keys/),
namely:

> Interleaved tables (a CockroachDB extension to SQL) change the
> cost/benefit analysis of the different key options. A top-level
> table with interleaved children cannot perform scans that take
> advantage of ordered keys, while the children inherit any scattering
> from their parentsâ keys. Therefore, when using interleaving, itâs
> usually best to use random (UUID) keys on the top-level table, and
> ordered keys (SERIAL or timestamp) on all child tables.

However, we should verify with @bdarnell: does this advice apply to
interleaved table usage generally?  Or is it tailored to your social
media example from the post?

**Comment by bdarnell** [comment]
That applies to interleaved tables generally.

**Comment by nvanbenschoten** [comment]
We should also consider drawing a direct comparison between foreign keys and interleaved tables like Spanner does [here](https://cloud.google.com/spanner/docs/foreign-keys/overview#fk-and-table-interleaving).

**Comment by vy-ton** [comment]
Closing this since there are plans to remove the feature
