### ISSUE TITLE
Improve search relevance of new vs old docs versions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5056]
Google sometimes ranks old versions of pages higher than newer version. To try to prevent this, we can tell search engines to not index, follow, archive, or cache pre-stable versions of our docs by adding [`block_search: true`](https://github.com/cockroachdb/docs/blob/master/_includes/head.html#L6) to the front-matter of those pages.

**Comment by bdarnell** [comment]
If the pages from old versions are showing up in results, it probably means they have pagerank from inbound links. If we block them, that pagerank would just be lost. We should try to have a link (on-page, not just the canonical tag) from every old page to its latest-version counterpart to help pagerank flow forward, and where we can, find old links and point them to the `stable` versions (these old pages are often getting most of their pagerank from our blog). 

Canonical links can help, but they only work when the pages are substantially similar. If google decides that the content is different, it will still index both pages separately. 

We should also look at titles and other changes to ensure the latest versions out-rank old versions. De-listing old versions from google should be a last resort.
