### ISSUE TITLE
Nav bar dropdown for "Product" needs updating

### ISSUE THREAD

**Issue by meagan-g** [cockroachdb/docs#5057]
The dropdown menu when you hover over "Product" in the navigation bar needs updating to make it consistent with the rest of the site

Recently, the dropdown menu for the rest of the site was updated so it now looks like this:
<img width="375" alt="Screen Shot 2019-07-16 at 10 07 00 AM" src="https://user-images.githubusercontent.com/52716054/61301334-ade49700-a7b1-11e9-8d62-5ab21cceb17a.png">

The dropdown on the docs site is still the old version:
<img width="496" alt="Screen Shot 2019-07-16 at 10 06 51 AM" src="https://user-images.githubusercontent.com/52716054/61301367-bf2da380-a7b1-11e9-9d8b-24942530dcda.png">

Please note also that in the new version of the dropdown, the green header reading "CockroachDB" is going to be updated so it is regular black text, and is clickable, directing to this link: https://www.cockroachlabs.com/product
So in the updated dropdown on the docs site, please add these changes as well

Thank you!

**Comment by jess-edwards** [comment]
Giving this issue a bump. Is there someone who can make this update while @jseldess is on vacation? Maybe @rmloveland ?

**Comment by jseldess** [comment]
Sorry for dropping this before heading out on vacation. I'll update the topnav now. Coloring might have to wait for someone else.
