### ISSUE TITLE
"Unsupported version" banners link to mac install page

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#5060]
The "unsupported version" banners link to the mac version of the install page. This should link to https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html instead so the visitor gets the auto-detected platform page.

Alternately, in light of #5056, it would be better for pagerank purposes if these links pointed to the corresponding page in the current version docs.

**Comment by jseldess** [comment]
We now link to https://www.cockroachlabs.com/docs/releases/release-support-policy from the unsupported version callout.
