### ISSUE TITLE
IPv6 [...] notation does not work correctly in cockroach start --join flag

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#5064]
The issue was submitted by a user in https://github.com/cockroachdb/cockroach/issues/38882

A known workaround is to use the join flag without brackets, I reproduced the issue locally and can confirm that the node will start without the brackets. 

The user brings up a good point where we support IPv6 but have certain areas where bracket notation is supported and other areas where it is not. 

Additionally, another workaround is to use a DNS name for the IPv6 address. 

[Here](https://www.cockroachlabs.com/docs/stable/start-a-node.html#start-a-multi-node-cluster) is a link to the docs page that specifically speaks about the cockroach start command and flags associated with it. 

I think we should mention this until somewhere the issue is resolved. 

It seems like we've seen this issue before relating to the hostname seen here. However, this issue is related to the join flag. https://github.com/cockroachdb/cockroach/issues/33008

**Comment by knz** [comment]
bug will be fixed in 19.2. https://github.com/cockroachdb/cockroach/pull/38924

However the change will not be backported to 19.1 so perhaps some highlight in the 19.1 doc would be useful

**Comment by jseldess** [comment]
We missed this, but since 19.1 is no longer supported, it's not worth updating those docs.
