### ISSUE TITLE
Document workaround for some types of location queries

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5066]
We don't yet support location queries with geospatial indexing (see [#19313](https://github.com/cockroachdb/cockroach/issues/19313)), but there are workarounds that cover some use cases discussed in the comments starting [here](https://github.com/cockroachdb/cockroach/issues/19313#issuecomment-480084606).

Estimated scope of work:

- Understand the workarounds discussed in that thread.
- Implement/test some of them, if possible.  Need to understand perf characteristics and limitations.
- Add them to a suitable location in the docs.

**Comment by petermattis** [comment]
The "workaround" in #19313 is going to be fairly inefficient. AFAICT, each object has a `lat` and `long` column. A search for objects within a radius of a particular point is done by adding `lat BETWEEN ? AND ?` and `long BETWEEN ? and ?` filters to the query. The problem with doing this is using indexes efficiently. If you have an index on `lat` you can't use the index to filter on `long` and vice versa. And a given bounds of `lat` or `long` can contain a lot of objects. Real geospatial indexing uses something like geohashing. Something like http://s2geometry.io/. The s2 library decomposes the world into cells in a very clever way such that you can efficiently compute the cells that make up an arbitrary region and then perform a query that efficiently finds objects tagged with those cells. In many ways this is like full-text search or the json indexing we already have. Note that you can use a library like s2 and do the indexing and searching entirely in the application. This is onerous, but will be much faster than the approach in #19313.

**Comment by rmloveland** [comment]
Closing this in favor of docs for the geospatial support we are working on for 20.2.

(Peter, a belated thank you for that explanation from last summer BTW.)
