### ISSUE TITLE
References to workload should use `cockroach workload` instead of a separate bin

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#5067]
As `workload` has changed, we've found it increasingly hard to keep the binary backward-compatible with all prior releases of CockroachDB. This results in errors like we see in https://forum.cockroachlabs.com/t/workload-fixture-import-failing-on-version-error/2927.

To address this, we began packaging `workload` inside of `cockroach` distributions, which ensures that it stays in-sync with the version of Cockroach that is being used. Users can access this by running the `cockroach workload` subcommand. We should update all documentation to use `cockroach workload ...` instead of `workload ...` to ensure that users don't continue to run into issues like the one linked above when trying to follow our documentation.

Another option is to update the docs to pull specific versions of `workload` depending on the corresponding release instead of always pulling the latest `workload` binary. I don't think this is quite as good of a solution, but we can consider it.

cc. @danhhz

**Comment by danhhz** [comment]
`cockroach workload` also has the added bonus of working on all platforms. IIRC, the `workload` standalone binary was only ever built for linux

**Comment by jseldess** [comment]
The only place we still use the separate `workload` command is on our TPC-C benchmarking docs: https://www.cockroachlabs.com/docs/v20.2/performance-benchmarking-with-tpcc-small

Thoughts on this, @nvanbenschoten

**Comment by nvanbenschoten** [comment]
We should be able to switch those over as well, which would allow us to eliminate the use of the `workload`  binary entirely in the docs.

**Comment by jseldess** [comment]
These tutorials leverage `./workload fixtures import tpcc` to load lots of data before running the benchmark. Do we just do the same thing via 

```
cockroach workload init tpcc \
--warehouses=xxx \
'postgresql://root@localhost:26257?sslmode=disable'
```
?

I don't think there's a fixtures option with the built-in workload, but I see you can set `--data-loader="import"`. Is that the way?

**Comment by nvanbenschoten** [comment]
`cockroach workload fixtures import tpcc` should work. Are you seeing issues with that approach?
