### ISSUE TITLE
Update training installation instructions

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#5069]
Currently, the training exercises instruct students to install the binary into a local directory, in conflict with our documentation. Updating the instructions, and related items.

Working in [this branch](https://github.com/cockroachdb/docs/tree/wc-change-training-installation-directory).

DoD:
[x] Installation exercise updated
[0] Update everywhere it says `$ ./cockroach` to be `$ cockroach`, and test the new configuration.

**Comment by jseldess** [comment]
@thatnerd, is this something you still want to do? Given that we'll retire the current training content soon, probably can close?

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
