### ISSUE TITLE
Bug: Training: Fault Tolerance and Automated Repair, Step 9

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#5070]
[Link to training page](https://www.cockroachlabs.com/docs/stable/training/fault-tolerance-and-automated-repair.html).

Step 9 assumes a TPCC workload that includes inserts, but that's not what the instructions have done. Changing it to perform a manual insert. Rolling this change into [this branch](https://github.com/cockroachdb/docs/tree/wc-change-training-installation-directory) I'm using in [Issue 5069](https://github.com/cockroachdb/docs/issues/5069).

DoD:
[x] New instructions are added
[x] New instructions have been tested

**Comment by jseldess** [comment]
@thatnerd, is this something you still want to do? Given that we'll retire the current training content soon, probably can close?

**Comment by jseldess** [comment]
These training pages are no longer public now that we have Cockroach U, so closing this.
