### ISSUE TITLE
Emphasize that `GRANT .. ON db` only works for new tables in `db`

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5083]
Richard Loveland (rmloveland) commented:

Our [GRANT docs][grant] mention that

> When a role or user is granted privileges for a database, new tables
> created in the database will inherit the privileges, but the
> privileges can then be changed.

However, it's not emphasized visually and is easy to miss in a bullet
in the "Supported Privileges" section.  For example, [this forum
post][forum] shows a user who was not aware of this behavior.

Estimated scope of work:

- Add emphasis to make clear that `GRANT ALL ON db ...` only applies
  to tables created after the privileges are granted
  
- Show how to use `GRANT ALL ON db.old_table ...` to add the perms to
  existing tables (as needed)

[grant]: https://www.cockroachlabs.com/docs/stable/grant.html
[forum]: https://forum.cockroachlabs.com/t/creating-a-user-with-database-access/2951/

Jira Issue: DOC-295

**Comment by mattcrdb** [comment]
Awesome! I'm going to reference this docs issue in the SQL Issue.

**Comment by rafiss** [comment]
This is no longer relevant - `GRANT ... ON db` no longer has any notion of inheritance to tables.
