### ISSUE TITLE
Fix Drift widget and header in print stylesheet

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#5110]
If you print a page from the docs, the header appears superimposed on the content on all pages, and the Drift widget shows up floating in the bottom corner of every page. The Drift widget should be hidden and the header should only display on the first page. (It'd probably be worth making some other opportunistic fixes while editing the print styles, such as hiding the table of contents, hiding "copy" buttons and the feedback form, and setting the font size to something more appropriate for print.)

**Comment by jseldess** [comment]
NO longing using drift, so closing this.
