### ISSUE TITLE
Document environment variables

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#5111]
Exalate commented:

Re: [Cockroach Commands](https://cockroachlabs.com/docs//v19.1/cockroach-commands.html)

## Issue Description

customers sometimes have set CockroachDB recognized environment variable that inadvertently used.  For example:

In 19.1.3 this:

``` 
cockroach sql --host $(hostname).cockroach --certs-dir /certs/dir 
```

Fails with:

``` 
Error: invalid argument "hostname" for "--host" flag: address hostname:tcp://127.0.0.1:26257: too many colons in address 
Failed running "sql" 
```

## Suggested Resolution 

Document environment variable and where they could be used within CockroachDB

**Comment by jseldess** [comment]
@robert-s-lee, we do mentioned env variables in the docs already, albeit at a high level: https://www.cockroachlabs.com/docs/stable/cockroach-commands.html#environment-variables. Do you think we need some specific examples?

**Comment by robert-s-lee** [comment]
We should document which env variables we honor.  One customer somehow had a env setting that was used as a part of connection string.   A document showing a list of env variables and where/how they are used would have been useful in the troubleshooting.

**Comment by jseldess** [comment]
Community user also asked for better docs here: https://forum.cockroachlabs.com/t/what-is-the-environment-variable-for-http-addr-flag/3498/2.
