### ISSUE TITLE
Update SHOW SCHEMAS docs to note that users must have DB privs

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5118]
Via [cockroach#37443][bug], it seems that running [`SHOW SCHEMAS`][schemas] as user X will only show schemas if user X has been granted privileges on the database.  Our docs currently say that

> No privileges are required to list the schemas

which is a bit confusing, and led to the linked CRDB issue being opened.

Estimated work here is:

- Verify above behavior re: needing to grant a user privs on the DB
- Update `SHOW SCHEMA` doc to note the above explicitly
- ???
- Profit

[bug]: https://github.com/cockroachdb/cockroach/issues/37443
[schemas]: https://www.cockroachlabs.com/docs/stable/show-schemas.html

**Comment by jeffugo** [comment]
@Amruta-Ranade  I already indicated interest just now on a on an open issue, but it seems that someone has indicated interest before me. If it happens to be assigned to that person, I'll like to work on this one.

**Comment by Amruta-Ranade** [comment]
oh..sure..assigning this to you

**Comment by jeffugo** [comment]
@Amruta-Ranade thanks. Will get to it.

**Comment by jeffugo** [comment]
Hello @Amruta-Ranade I see that the setup requires me to install Homebrew, and it looks like it is only available for macOS and I use windows. Please is there a way around this? Thank you.

**Comment by Amruta-Ranade** [comment]
Yep! 
https://www.cockroachlabs.com/docs/v20.1/install-cockroachdb-windows

**Comment by jeffugo** [comment]
Thank you!

**Comment by Amruta-Ranade** [comment]
@jeffugo Heads-up: The Hacktoberfest organizers are changing the rules to combat spam. To have your PR count for Hacktoberfest, hold off on opening the PR until at least Tuesday to give us time to implement the new rules.

**Comment by jeffugo** [comment]
Alright.

**Comment by jeffugo** [comment]
Hello @Amruta-Ranade the setup has been challenging so far and I'm still on it. I know I have questions but I'm trying to narrow them down. Thank you.

**Comment by Amruta-Ranade** [comment]
No worries! Take your time :) 
Also, feel free to join the CockroachDB Slack community for help if you need it: https://cockroa.ch/slack

**Comment by jeffugo** [comment]
Thank you for the link!

**Comment by Amruta-Ranade** [comment]
Hey @jeffugo, do we have an update on the issue? Anything I can help with?

**Comment by jeffugo** [comment]
@Amruta-Ranade I'm so sorry I couldn't finish this. I got very sick and was discharged only yesterday. Again, apologies.

**Comment by Amruta-Ranade** [comment]
Oh no! Hope you feel better soon! 
Don't worry about the issue. My awesome colleague (@ericharmeling ) handled it already :)

**Comment by jeffugo** [comment]
Alright. Thank you!
