### ISSUE TITLE
Remove hedging note from 'Learn CockroachDB SQL'

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5125]
In [Learn CockroachDB SQL][sql], we say

> CockroachDB aims to provide standard SQL with extensions, but some
> standard SQL functionality is not yet available. See our SQL Feature
> Support page for more details.

I think our SQL support is mature enough for the 95% of use cases that
this sort of warning is not necessary anymore.

Whomever ends up working on this can confirm or disconfirm that
opinion with folks in Product / Engineering, of course. :-)

[sql]: https://www.cockroachlabs.com/docs/stable/learn-cockroachdb-sql.html

**Comment by ericharmeling** [comment]
I can do this for 19.1... For 19.2 I already removed it as a part of #5075.

**Comment by rmloveland** [comment]
Eric Harmeling <notifications@github.com> writes:

> I can do this for 19.1... For 19.2 I already removed it as a part of
> #5075.

Awesome, thanks Eric!

**Comment by ericharmeling** [comment]
@awoods187 

Any reason why we should keep this note in current stable docs (i.e. 19.1)?

**Comment by awoods187** [comment]
I'm fine with removing it. I think we still run into some problems of unsupported features but they can easily be found. No reason to spook someone with this language.

**Comment by ericharmeling** [comment]
See #5175
