### ISSUE TITLE
Remove hedging notes from SQL documentation re: feature support, etc.

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5126]
Richard Loveland (rmloveland) commented:

In [Learn CockroachDB SQL][learn], we say

> CockroachDB aims to provide standard SQL with extensions, but some
> standard SQL functionality is not yet available. See our SQL Feature
> Support page for more details.

I think our SQL support is mature enough for the 95% of use cases that
this sort of warning is not necessary anymore in most cases.

Estimated scope of work for this ticket is:

1. Make a list of all hedging statements in our SQL documentation
2. Go through the list and verify which of them are still accurate / needed
3. Delete the rest

This can be a parent issue for the overall project, with tickets like
#5125 (and eventually others) used to track smaller chunks of work.

Note: Obviously we are not looking to mislead users (or ourselves)
about the state of our product; the idea is to clean up any
unnecessarily hedging language in our documentation that may no longer
be valid due to improvements that have occurred over the past few
releases.

[learn]: https://www.cockroachlabs.com/docs/stable/learn-cockroachdb-sql.html

Jira Issue: DOC-299

**Comment by rmloveland** [comment]
@awoods187 FYI - this seems like a thing it would be good to do.  Please shout if you disagree

**Comment by awoods187** [comment]
+1 @rmloveland
