### ISSUE TITLE
Updates to training... (based on my Week 2 notes)

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5130]
# Training notes from Week 2

@thatnerd as promised...

I'm going to leave out smaller things (typos, links) - I can just quickly get to those myself.

## Global notes
- Throughout the training docs, we use "./cockroach", rather than "cockroach" in our CLI examples… It might be best to assume (or instruct/notify people at the beginning of the training) to add the "cockroach" binary to PATH (we assume that other utilities, like haproxy, minikube, etc. are added to PATH), so they can run cockroach from any directory they choose.

## [Orchestration with Kubernetes](https://www.cockroachlabs.com/docs/stable/training/orchestration-with-kubernetes.html)
- Each VM that you use, you need to install a driver and configure Kubernetes to use that driver (https://kubernetes.io/docs/setup/learning-environment/minikube/#managing-your-cluster).

## [Performance Benchmarking](https://www.cockroachlabs.com/docs/stable/training/performance-benchmarking.html)
- We should probably go through and update our time estimates on how long it takes certain commands to complete, or just remove those comments entirely ? (e.g. cockroach workload init tpcc —warehouses=10 took a lot longer than 10 minutes for me, even though it says that it would "take about ten minutes to load.")

## [Data Import](https://www.cockroachlabs.com/docs/stable/training/data-import.html)
- Under [Import a PostgreSQL dump file](https://www.cockroachlabs.com/docs/stable/training/data-import.html#step-3-import-a-postgresql-dump-file), are steps 1-3 necessary? I think we should remove these steps. They don't really add anything.
- Same thing as above, but steps 1-2, under [Import a MySQL dump file](https://www.cockroachlabs.com/docs/stable/training/data-import.html#step-4-import-a-mysql-dump-file) dump file.

## [Client Connection Troubleshooting](https://www.cockroachlabs.com/docs/stable/training/client-connection-troubleshooting.html)
- Probably a global note, but... some output messages are different than how we describe them in the docs e.g. instead of this error:
```
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp [::1]:20000: connect: connection refused
Failed running "sql"
```
I got:
```
Error: cannot dial server.

Is the server running?
If the server is running, check --host client-side and --advertise server-side.

dial tcp [::1]:20000: connect: connection refused
Failed running "sql"
```
It might be best to leave out messages in their entirety, and instead just say "you might get a connection error"

**Comment by jseldess** [comment]
We're no longer using or maintaining these old training pages, so closing this.
