### ISSUE TITLE
MSO: Remove docs versioning

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#5131]

**Comment by jseldess** [comment]
@Amruta-Ranade, do we want to completely remove doc versioning or just have stable and dev?

**Comment by Amruta-Ranade** [comment]
My opinion on the issue has evolved since I filed it. The initial thought was that since we don't have console versioning, we could remove docs versioning completely. However, we do have some CRDB docs in the CC section, so we need to support 19.1 and 19.2 CRDB docs post-beta. 

Another consideration is that the CC docs structure is closely tied with CRDB docs -- since we don't have a separate CC folder, the CC docs are versioned along with CRDB docs for every release. I am not sure if removing versioning would impact our docs structure as well.

As of now, I think we can let the versioning be and revisit this issue at a later date (probably close to CC GA). Totally open to other suggestions.

**Comment by jseldess** [comment]
We recently changed CC docs to show only stable and dev versions. Closing this for now.
