### ISSUE TITLE
search results return empty for key kerberos terms

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#5132]
searching the docs site for key terms like `kerberos`, `gssapi` or `kdc` all return "no results" even though these terms are used frequently in this docs page: https://www.cockroachlabs.com/docs/v19.1/gssapi_authentication.html

**Comment by timveil** [comment]
`ldap` also returns "no results"  i think we need to include a blurb about how we support `ldap` if that does not already exist in the docs site.

**Comment by jseldess** [comment]
@j-low , need your advice again here. That particular page doesn’t ever seem to show up in search results, even if you search for language in the title. Any idea why or what we might do?

**Comment by j-low** [comment]
@jseldess how recently was this page included in the docs?  It might be the case that we need to reach out to the DocSearch maintainer for Algolia and ask them to reindex the site.  There is nothing that jumps out at me in our config that would suggest this page being ignored by the indexer (i.e. the selectors on the GSSAPI page are the same as other pages and therefore should be indexed).

**Comment by timveil** [comment]
is it possible to have the site automatically re-indexed on a schedule like nightly?

**Comment by j-low** [comment]
@timveil Daily recrawling happens but per the issue I filed it apparently was broken recently and is now fixed.  I was advised by the maintainer to alert them if results are still empty in another day or so.

**Comment by jseldess** [comment]
Thanks for helping with this, @j-low. I'll check again in the morning and close if the page is indexed properly.

**Comment by j-low** [comment]
Sounds great.  Let me know if there are still issues and I will follow up.

**Comment by rolandcrosby** [comment]
Filed #5138 to track the update to the GSSAPI page to mention LDAP.

**Comment by jseldess** [comment]
@j-low, that page has been around for quite some time, so I don't know why it wasn't indexed.

**Comment by timveil** [comment]
this looks resolved.   curious about the solution and the root cause.

**Comment by jseldess** [comment]
@timveil, quick explanation: We currently use algolia's free [docs search](https://community.algolia.com/docsearch/), which is a great offering for open source docs but is somewhat limited in our control of the search experience. We maintain a [config](https://github.com/algolia/docsearch-configs/blob/master/configs/cockroachlabs.json) that they use to determine how to index our docs, but they drive the actually indexing, which is suppose to happen daily. In this case, their daily crawler was broken.

In the near future, we're planning to upgrade our subscription to be able to better control our destiny. @lhirata gave a 5-min presentation on this at a recent team meeting and can point you to more info if you like.
