### ISSUE TITLE
Fix command to remove data dir on Windows

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5167]
A user pointed out a potential error in [docker setup instructions for windows](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html#os-windows).

The user states that `rm -rf cockroach-data` is not a windows command. They mention that in other sections  we mention Powershell and offer up this input that the correct command may be:

`Remove-Item C:\Users\<username>\cockroach-data -recurse`

**Comment by jseldess** [comment]
Just heard this from an SE candidate as well! 

@BramGruneir, is the command above the proper power shell syntax?
