### ISSUE TITLE
Improve documentation for operators and functions

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5174]
@mattcrdb fielded a customer question from the CRDB forums (https://forum.cockroachlabs.com/t/how-do-i-map-a-json-array-into-rows/2960) about JSONB functions, exposing a fairly under-documented supported feature of CRDB: [Functions and Operators](https://www.cockroachlabs.com/docs/v19.2/functions-and-operators.html).

We should improve documentation for functions and operators with the following:
[] Better descriptions of input and usage for each function
[] Simple examples

**Comment by jseldess** [comment]
This is a great overarching project, @ericharmeling, but note that there are some automation aspects given how these docs are generated. Here are a bunch of related issues: https://github.com/cockroachdb/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+functions

**Comment by ericharmeling** [comment]
This is perhaps too broad an issue. I'm going to be opening others that are more specific. Closing for now.
