### ISSUE TITLE
Update 19.2 code samples to note `crdb_internal.force_retry()` does not require root anymore

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5176]
See https://github.com/cockroachdb/cockroach/issues/39243

Estimated scope of work here is:

- Update any 19.2 code samples that make use of this function, since some of the comments note the old behavior (they can't just be copypasta'd directly from 19.1 in at least 1-2 cases)
- Update 19.1 code samples when and if  https://github.com/cockroachdb/cockroach/pull/39246 is backported in an upcoming 19.1.x point release
- Verify that our 19.2 docs (and 19.1.x as applicable) do not make mention of this function needing to be the root user (I don't think this is mentioned outside code samples, but IDK)

**Comment by ericharmeling** [comment]
FYI: The entry for `force_retry` in the functions doc doesn't mention privileges: https://www.cockroachlabs.com/docs/v19.2/functions-and-operators.html#system-info-functions.

All of those function descriptions are really unhelpful though. That's a separate issue.
