### ISSUE TITLE
Search results include pages with links including the search term

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5179]
When you search our docs, if a page contains a link containing the keyword, it shows up in the results. For example, searching "mysql" will show the CockroachDB home page in the results because it contains the "Migrate from MySQL" link. These types of results should either be excluded totally from results or should be strongly de-ranked.

**Comment by jseldess** [comment]
I believe we just need to update the algolia config to exclude these cases, if that's possible: https://github.com/algolia/docsearch-configs/blob/master/configs/cockroachlabs.json

**Comment by jseldess** [comment]
@j-low, could use your input here. Looks like we're already excluding links in "see also" sections: https://github.com/algolia/docsearch-configs/blob/master/configs/cockroachlabs.json#L35. Would there be an easy way to exclude pages that otherwise just include links with the search term? Feel free to point me to where to look to try to answer this myself.

**Comment by j-low** [comment]
@jseldess I think [this](https://community.algolia.com/docsearch/config-file.html#scrape_start_urls-optional) is what we're looking for.  I'm going to file a PR to their repo to test it out so we should know if it's successful in the usual amount of time (~1 day).  I'm fairly sure that's the option we're looking for so if we're still seeing issues there may be more changes that need to be made to the config (that are not clear to me at the moment).

**Comment by jseldess** [comment]
Hmm, I read that option differently. Seems to not be about links as much as which urls to start scraping at, which is why we have each version directory listed?

**Comment by j-low** [comment]
@jseldess the option indicates whether or not to scrape the URL at the start URL location which is what is being returned in this case and  is causing the strangeness.  It's not about links but I'm wondering if we really want our config to exclude links?  We would either have to apply a broad exclusion rule to all links (which seems prone to side effects) or collecting a list of instances in which we do/don't want links scraped and distilling some rule(s) from those cases.

The current PR to Algolia would handle the case of not having the landing page show up in the results.

**Comment by jseldess** [comment]
Ah, I see. I think that's definitely a great step to take. I do think that it would be great to NOT return pages if the search terms are only mentioned in links on those pages. But I understand that's not trivial to accomplish and probably not worth looking at right now.

**Comment by j-low** [comment]
Agreed.  I don't have much of an idea how to approach that in the config-based context we're currently on but I do wonder about the future when we theoretically have more knobs to fiddle with when we've migrated to the self-admin'd context.

**Comment by jseldess** [comment]
This particular issues was resolved, so closing.
