### ISSUE TITLE
Update docs to reference importing into an existing table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5180]
We now have 19.2 docs on using `IMPORT INTO` to import into an existing table, but we still have statements throughout the docs that it's not possible to import into an existing table. We need to find and update all of these. We also need to update any reference to import best practices, for example, https://www.cockroachlabs.com/docs/dev/performance-best-practices-overview.html#bulk-insert-best-practices and https://www.cockroachlabs.com/docs/dev/sql-faqs.html#how-do-i-bulk-insert-data-into-cockroachdb.

@lhirata, if you already have an issue to polish our import into docs, feel free to close this.

**Comment by bdarnell** [comment]
It all comes down to whether you can tolerate taking the table offline for the duration of the import. If that's acceptable to you, IMPORT will be the fastest option. But I think that's rarely going to be the case, so I'd assume/recommend INSERT by default.
