### ISSUE TITLE
sql: Loose index scan table reader

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5182]
PR: https://github.com/cockroachdb/cockroach/pull/38216

From release notes:
> Added support for a table reader that performs a loose index scan over the underlying table. The index scan table reader uses information about the index being scanned to skip unnecessary rows while scanning the table, allowing for some optimizations to be used for some types of queries. [#38216][#38216] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rohany From the referenced PR, this feature looks like it is not externally visible/configurable, correct? If so, I think we should close this issue, as no documentation would be needed.

**Comment by rohany** [comment]
Correct, the feature is not directly configurable -- the optimizer will just plan it whenever it can.

**Comment by ericharmeling** [comment]
Awesome. Thanks!
