### ISSUE TITLE
exec: Add vectorized support for IN

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5185]
PR: https://github.com/cockroachdb/cockroach/pull/38546

From release notes:
> Added vectorized support for the `IN` selection operator. [#38546][#38546] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
From the user's perspective, IN and NOT IN are already [supported operators](https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#operators)... It looks like we don't need documentation support for this particular item, unless there is a behavior change that I'm missing. All vectorized execution documentation will be addressed in #4790. Please reopen if you disagree!
