### ISSUE TITLE
cli: IPv6-related fixes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5193]
PR: https://github.com/cockroachdb/cockroach/pull/38924

From release notes:
> CockroachDB now requires square brackets to specify IPv6 addresses in `--join`, `--host`, `--listen-addr` and similar [flags](../v19.2/start-a-node.html#flags), for example `--listen-addr=[::1]`. The syntax without square brackets had been deprecated since CockroachDB 2.1. [#38924][#38924] {% comment %}doc{% endcomment %}

**Comment by lhirata** [comment]
No docs updates needed. Notes about IPv6 addresses have already been added.
