### ISSUE TITLE
ui: add a "Last 2 days" option to the duration picker

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5194]
PR: https://github.com/cockroachdb/cockroach/pull/38852

From release notes:
> Dashboard [graphs](../v19.2/admin-ui-overview.html) now offer a "Last 2 days" option in the time selector. [#38852][#38852] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Closed through #5579
