### ISSUE TITLE
Support guidance and policy

### ISSUE THREAD

**Issue by randmark** [cockroachdb/docs#5205]
We need a single doc with clear guidance on how to get support and, for enterprise customers, what our Support policies are, e.g., 
- Support tiers
- Hours
- SLAs
- What is and is not supported

We should also call out Support portal requirements (from #5209):

- Zendesk supports the following browsers:
    - Google Chrome: latest two versions
    - Safari: latest two versions
    - Firefox: latest two versions

- Zendesk no longer supports IE 11 only the latest Microsoft Edge browser is supported (latest two versions).

Please also make sure your browser has the following configurations:
- JavaScript must be enabled
- Cookies must be enabled
- Local storage must be enabled
- TLS v1.2 or above

Cookie:

add the https://cockroachdb.zendesk.com address explicitly to the list for allowed cookies, rather than just “support.cockroachlabs.com”

---
See VMware's policy page as an example of the types of policy info that customers, and potential customers, expect to see.

https://www.vmware.com/support/services.html

**Comment by jseldess** [comment]
@Amruta-Ranade, can you take this in the next sprint?

**Comment by jseldess** [comment]
@Amruta-Ranade, as an extension of this, I'm assigning you https://github.com/cockroachdb/docs/issues/4697, which should be pretty easy.

**Comment by jseldess** [comment]
Discussed in the CS/Education monthly sync yesterday (notes below). I'm closing this issue for now, given that it's unclear whether this content should be docs, on the support portal, or on the general marketing site. If Support decides this belongs in docs, we can revive this issue.

> We recently published our official Release support policy, explaining the company’s commitments to support specific versions of CockroachDB. We discussed the need to document Customer Support policies as well, including different service levels and SLAs available via an enterprise contract. Docs and Support started a collaboration on this months ago but it was put on hold while Customer Success was finalizing their support offerings and internal support handbook. We also debated the best channel for communicating this information, whether docs, support portal landing page, or general marketing site. No consensus was reached, but it’s in CS’s court to make a decision and loop Docs in if needed
