### ISSUE TITLE
Create public-facing security policy doc

### ISSUE THREAD

**Issue by randmark** [cockroachdb/docs#5206]
Customers and potential customers look for a security policy on our website. We need to create one that matches what other enterprise vendors provide. Currently there are two pages that might have some of the material needed but other parts may require us to develop this policy.

- MSO Security Policy: https://www.cockroachlabs.com/security/
- Security disclosure policy: https://www.cockroachlabs.com/security/responsible-disclosure-policy

Neither of these answer the following for using the self-hosted software similar to what other vendors provide. See VMware's as an example: https://www.vmware.com/support/policies/security_response.html

- Classes of vulnerabilities (low, medium, high)
- How to report vulnerabilities (we have this page)
- Notification policies
- SLAs
- Fix policy
- Which versions are covered (usually one or two versions back)

Also, there is often a blog or page for security vulnerabilities notifications and often a mailing list. Here's the info on VMware's: 

> Note: VMware Security Alerts are posted at www.vmware.com/security/alerts and are sent to subscribers of the VMware Security Announce mailing list. One can subscribe to this list by entering their email address in the “Sign-up for Security Notifications” box on www.vmware.com/security.

**Comment by jseldess** [comment]
Checked with Adam Brennick, our compliance manager. He thinks what we have now is sufficient. There's more work to do, but it's in his court. Closing this.
