### ISSUE TITLE
document support portal requirements

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#5209]
## Title

Document support portal requirements 

## Description

Some customers are not login in the support portal.  document requirements.

## Outline

@roncrdb  can provide more info on below.

Zendesk supports the following browsers:

Google Chrome: latest two versions
Safari: latest two versions
Firefox: latest two versions 

Zendesk no longer supports IE 11 only the latest Microsoft Edge browser is supported (latest two versions).

Please also make sure your browser has the following configurations: 
JavaScript must be enabled
Cookies must be enabled
Local storage must be enabled
TLS v1.2 or above

Cookie:

add the https://cockroachdb.zendesk.com address explicitly to the list for allowed cookies, rather than just “support.cockroachlabs.com”

## Expected Audience

customers requiring support

cc @BramGruneir

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5205, which we've agreed to tackle in the next few weeks.
