### ISSUE TITLE
Distributed transactions doc could use more information

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#5219]
This is the page: https://www.cockroachlabs.com/docs/v19.1/distributed-transactions.html

**Background:**
A forum user was looking for more information about distributed deadlock detection, discovered the term on [this](https://www.cockroachlabs.com/docs/v19.1/distributed-transactions.html) page. 

This is the forum question: https://forum.cockroachlabs.com/t/transaction-deadlocks-in-crdb/3013/2

**Solution:**
I believe the concurrency protocol has moved from optimistic to pessimistic. So we should consider rewording this page. 

Adding some links would be awesome too:
1. https://www.cockroachlabs.com/docs/stable/architecture/transaction-layer.html (specifically the part about the [txnwaitqueue](https://www.cockroachlabs.com/docs/dev/architecture/transaction-layer.html#txnwaitqueue))
2. https://www.cockroachlabs.com/docs/stable/transactions.html#serializable-isolation
3. For understanding the whole picture: https://www.cockroachlabs.com/docs/stable/architecture/life-of-a-distributed-transaction.html#resolving-write-intents

**Comment by jseldess** [comment]
@mattcrdb, sorry for the extreme delay here. Do you think the docs still need updating?

**Comment by mattcrdb** [comment]
I think its ok to leave it as is, I haven't heard this come up since.
