### ISSUE TITLE
Rust driver documentation incorrect for secure cluster

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#5223]
https://www.cockroachlabs.com/docs/stable/build-a-rust-app-with-cockroachdb.html

The cockroach start command should reflect that of a secure cluster when `secure` is selected. 

Currently, there is no change between the two options and the insecure cockroach start command is there by default.

**Note:** on steps 2-5 the flags are using insecure commands, but the driver code reflects a secure connection. 

The issue persists on v2.1, v19.1, and v19.2.

Today I filed a PR for the driver code download being incorrect for insecure clusters, we can wait until this merges to finish up the rest of the rust driver documentation. My PR is https://github.com/cockroachdb/docs/pull/5222#issuecomment-521397555

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3584](https://cockroachdb.zendesk.com/agent/tickets/3584) has been linked to this issue.
