### ISSUE TITLE
Search: Investigate if search terms embedded in a table displays 

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#5227]
We have an inkling that when a search term is embedded in a table, it does not display in the search results. We should look into this and figure out if it's due to Algolia or something else.

For example: --safe-updates (or any flags)

**Comment by jseldess** [comment]
I believe we're indexing table entries now: https://github.com/cockroachdb/docs/blob/master/jekyll-algolia-dev/lib/jekyll/algolia/configurator.rb#L15.

@yingzhuchin, please reopen this if you disagree.
