### ISSUE TITLE
sql: deemphasize GORM

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5238]
A customer of ours experienced four major issues with [GORM](https://github.com/jinzhu/gorm
): consistency violation, two swallowed errors with downstream impacts, and a major bug. 

This has caused them to lose confidence in GORM and we should consider recommending other tools. 

We've heard some good things about https://github.com/go-pg/pg.

**Comment by awoods187** [comment]
Another user is usinghttps://github.com/doug-martin/goqu

**Comment by ericharmeling** [comment]
I'm a little confused about the ask here.

Are we asking:
- To remove GORM from the list of supported ORMs?
- To remove our GORM hello world tutorial?
- To add a new hello world tutorial for pg?

Currently, our GORM hello world tutorial is listed as the third option of the "Build a Go app" tutorials: https://www.cockroachlabs.com/docs/v20.2/build-a-go-app-with-cockroachdb. The default is PGX. 

Also, keep in mind that our GORM adapter is actively maintained: https://github.com/cockroachdb/cockroach-go/tree/master/crdb/crdbgorm. @rafiss 

We do need to update the GORM hello world to use GORM v2, but there is a separate issue tracking that: https://github.com/cockroachdb/docs/issues/8228.

**Comment by rafiss** [comment]
I'd be in favor of adding a new hello world tutorial for go-pg when there is time for that. IMO I don't think we should remove GORM from anything in our docs.

**Comment by ericharmeling** [comment]
@rafiss 

>I'd be in favor of adding a new hello world tutorial for go-pg when there is time for that.

Right on. That sounds like a separate issue though.

> IMO I don't think we should remove GORM from anything in our docs.

Sounds good.

I'm going to close this issue for now. We've de-emphasized GORM (as I wrote above, our GORM hello world tutorial is listed as the third option of the "Build a Go app" tutorials).
