### ISSUE TITLE
End-to-end app development tutorial (Python - SQLAlchemy)

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5243]
We need an end-to-end tutorial about developing applications that work with CockroachDB (i.e. how to actually use a compatible ORM to develop a full application). [MovR](https://github.com/cockroachdb/movr) is a great place to start.

The tutorial should cover:
- [ ] Brief introduction to web development using Python and Flask/Django
- [ ] Connecting to CockroachDB (engines and sessions)
- [ ] Mapping
- [ ] APIs (constructors in view functions)
- [ ] UI

The tutorial should __not__ go into detail about:
- Python and Flask/Django development
- HTML and CSS

__Leverage existing [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/13/orm/tutorial.html) for this!__
__Be sure to consult SE's on common problems/scenarios from customer experiences.__

**Comment by jseldess** [comment]
Thanks for mapping this out, @ericharmeling. Once we get closer, I'd love for you to write up a docs project plan using [this template](https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/158040072/Docs+Project+Planning+Framework).

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/6056
