### ISSUE TITLE
Update partition documentation to show support for partition name reuse

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5245]
https://github.com/cockroachdb/cockroach/pull/39332

- [x] [`SHOW PARTITIONS`](https://www.cockroachlabs.com/docs/dev/show-partitions.html)
- [x]  [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html)
- [x] [Configure Replication Zones](https://www.cockroachlabs.com/docs/dev/configure-replication-zones.html)
- [x]  [Geo-Partitioning demo](https://www.cockroachlabs.com/docs/dev/demo-geo-partitioning.html)
- [x] [Geo-Partitioning (Training Module)](https://www.cockroachlabs.com/docs/stable/training/geo-partitioning.html)

@solongordon We can talk offline if needed.

**Comment by solongordon** [comment]
I would say that note no longer applies, and the best practice would be to use `north_america` as the name across all indexes.

**Comment by ericharmeling** [comment]
Awesome. That's reflected in the PR (#5336)

**Comment by awoods187** [comment]
Agreed with @solongordon . We have further enhancements this direction that will take advantage of this.
