### ISSUE TITLE
Change double-click select highlighting behavior to only highlight commands

### ISSUE THREAD

**Issue by WillHaack** [cockroachdb/docs#525]
Throughout the docs page, there are convenient code snippets that appear in gray boxes such as:

![image](https://cloud.githubusercontent.com/assets/766792/17258746/5d3450fe-5596-11e6-9f26-d58f138c3e39.png)

Unfortunately, when you attempt to highlight by double clicking the command, the bash symbol $ gets highlighted as well. This forces the user to manually highlight the command if they want to copy and paste it directly into terminal, costing them a bit of time. It would be nice if when you double clicked anywhere in the command, it only copied the command as you'd want to paste it into your terminal. Also, ideally a series of commands could be copied with newlines separating them so that you can paste it into your terminal and have them be run in sequence. There may be better solutions, but a google search came up with:

https://css-tricks.com/almanac/properties/u/user-select/

IMO this is low priority, and not something where time should be wasted trying to get it working for out of date, unpopular browsers.

**Comment by jseldess** [comment]
Thanks, @WillHaack. @sploiselle, feel free to take a swing at this once DivisionOf has merged their site restyle. They're using scss, so if you have questions about the right files to edit, you can reach out to @eballeste.
