### ISSUE TITLE
Multi-region app in a multi-region Kubernetes deployment

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5251]
We need to show how to run a multi-region app in a multi-region Kubernetes deployment. The best route is to expand our multi-region tutorial featuring MovR and geo-partitioning and duplicate indexes to a Kubernetes-based deployment. We'd end up with two options for the same tutorial: Manual vs. Kubernetes.

---

Based on feedback from @drewdeally, it would be good to expand our multi-region K8s tutorial to include multi-region app deployment (`movr`, `ycsb`, etc.) as well.

**Comment by drewdeally** [comment]
https://github.com/cockroachdb/docs/issues/5348
