### ISSUE TITLE
opt: support CREATE VIEW

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5284]
PR: https://github.com/cockroachdb/cockroach/pull/39169

From release notes:
> [`CREATE VIEW`](../v19.2/create-view.html) now supports all queries supported by the optimizer, including those containing [correlated subqueries](../v19.2/subqueries.html#correlated-subqueries). [#39169][#39169] {% comment %}doc{% endcomment %}
>
> Mutations are no longer allowed inside [views](../v19.2/views.html). [#39169][#39169] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@justinj 

It doesn't look like this needs any doc support, other than maybe a note: 
"Mutations are not allowed inside views." on the [views doc page](https://www.cockroachlabs.com/docs/dev/views).

But I also don't see anything about mutations in views in the docs on views right now anyways... 
Thoughts?

**Comment by jseldess** [comment]
@ericharmeling, I think this and some other issues related to expanded CBO support require us to revisit how we talk about the CBO. For example, do we even need to [call out statements that are not  yet supported by CBO and still use the heuristic planner](https://www.cockroachlabs.com/docs/v19.2/cost-based-optimizer.html#main-content)? 

> If your query uses functionality that is not yet supported by the cost-based optimizer. For more information about the types of queries that are supported, see Types of statements supported by the cost-based optimizer.

Also:
- https://www.cockroachlabs.com/docs/v19.2/cost-based-optimizer.html#types-of-statements-supported-by-the-cost-based-optimizer
- https://www.cockroachlabs.com/docs/v19.2/cost-based-optimizer.html#known-limitations

**Comment by ericharmeling** [comment]
@rmloveland Assigning this to you, per our discussion earlier.
