### ISSUE TITLE
sql: Add pg_collation_for info function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5285]
PR: https://github.com/cockroachdb/cockroach/pull/39198

From release notes:
> Added the `COLLATION FOR` syntax and `pg_collation_for()` [built-in function](functions-and-operators.html). [#39198][#39198] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I think we can put it in both places... 

- In the [special syntax forms](https://www.cockroachlabs.com/docs/v19.2/functions-and-operators.html#special-syntax-forms) table, I can just add an entry.
- On the [COLLATE](https://www.cockroachlabs.com/docs/v19.2/collate.html) page, I'll add a link, and some prose/example.
