### ISSUE TITLE
sql: Update show create to show table and partition zone configs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5293]
PR: https://github.com/cockroachdb/cockroach/pull/39102

From release notes:
> Updated [`SHOW CREATE`](../v19.2/show-create.html) to display information about partition and table zone configurations. [#39102][#39102] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I just combed the docs and found them to be up-to-date on `SHOW CREATE` output for partitioned tables.

Also, we already document that the output for `SHOW CREATE TABLE` should include partitions and zone configs (if relevant) on these pages:
- [`SHOW PARTITIONS`](https://www.cockroachlabs.com/docs/dev/show-partitions.html#examples)
- [`SHOW ZONE CONFIGURATIONS`](https://www.cockroachlabs.com/docs/dev/show-zone-configurations.html#view-the-replication-zone-for-a-table)
- [`SHOW CREATE`](https://www.cockroachlabs.com/docs/dev/show-create.html#show-the-create-table-statement-for-a-table)
