### ISSUE TITLE
Remove admin privilege for force_retry #39243

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5296]
PR: https://github.com/cockroachdb/cockroach/pull/39246

From release notes:
> The `force_retry()` function, which previously required admin privileges, is now available to all users to test their transaction retry loops. [#39246][#39246] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rmloveland opened https://github.com/cockroachdb/docs/issues/5176 earlier last month, which will take care of this. Closing this issue.
