### ISSUE TITLE
cli,rpc,server: verify cluster names

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5306]
PR: https://github.com/cockroachdb/cockroach/pull/39270

From release notes:
> [`cockroach start`](../v19.2/start-a-node.html) now accepts a `--cluster-name` flag. If specified, it must match when a node connects to a cluster. This feature is meant for use in combination with the cluster ID, which is still checked in any case, to protect newly created nodes (that don't have a cluster ID yet) from joining the wrong cluster. To introduce a cluster name into an existing cluster without one, the new flag can be temporarily paired with `--disable-cluster-name-verification`. [#39270][#39270] {% comment %}doc{% endcomment %}

**Comment by mberhault** [comment]
I can't find this in the 19.2.0 release notes. Did we miss it?

**Comment by jseldess** [comment]
It's in https://www.cockroachlabs.com/docs/releases/v19.2.0-beta.20190930.html#command-line-changes. We just haven't documented it yet. Will get to this soon.

**Comment by jseldess** [comment]
@taroface, an old 19.2 issue for an flag that eventually should be documented.

**Comment by jseldess** [comment]
This was documented at some point: https://www.cockroachlabs.com/docs/v21.1/cockroach-start.html
