### ISSUE TITLE
NULL Handling Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#5330]
Re: [NULL Handling](https://cockroachlabs.com/docs//v19.2/null-handling.html)

The following sentence:

> The remaining cases are described in the next question.

Can be edited to:

> The remaining cases are described in the next section.

**Comment by aniketrb-github** [comment]
Hi @Amruta-Ranade,
Can you please assign me this issue?
I would like to contribute to this issue towards the hacktoberfest event.

Thanks,
Aniket Bharsakale.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8521
