### ISSUE TITLE
Not Null Constraint Doc Update 

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#5331]
Re: [Not Null Constraint](https://cockroachlabs.com/docs//v19.2/not-null.html)

## Issue Description

This page does not refer to the page on [NULL handling](https://www.cockroachlabs.com/docs/dev/null-handling.html)

## Suggested Resolution 

Add a link to null handling at the first mention of "NULL" at the top, and one more in "See also" at the bottom.

**Comment by aniketrb-github** [comment]
Hello @Amruta-Ranade 
I understood this issue, and I am willing to contribute for the same.
Can you please assign it to me for the hacktoberfest event? 
Thanks.

**Comment by Amruta-Ranade** [comment]
@aniketrb-github Hey! We are asking participants to work on one issue at a time. Once you finish working on the comparison page issue, check back to see if this one is available :)

**Comment by aniketrb-github** [comment]
hi @Amruta-Ranade can I work on this issue?
or do I have to wait till [my previous PR](https://github.com/cockroachdb/docs/pull/8521) gets merged? because it's still open as of now. Please let me know. Thanks.

**Comment by jeffugo** [comment]
@Amruta-Ranade I'd like to work on this if it's available.

**Comment by Amruta-Ranade** [comment]
@aniketrb-github I am merging your PR now but do you mind if @jeffugo took this one? I am trying to let more folks contribute and you already made an excellent contribution!

**Comment by aniketrb-github** [comment]
Oh okay. Fine.
I'll work on it. Thanks @Amruta-Ranade.

**Comment by aniketrb-github** [comment]
@Amruta-Ranade 
**Q1)** As per my understanding of this issue description:
Actual: [Null Handling hyperlink](https://www.cockroachlabs.com/docs//v19.2/not-null.html) points to Not Null HTML file from v19.2
Expected: We need it to point it to the Not Null HTML file from v20.2

**Q2)** And on the same page in the **"See Also" section**: [ See Also --> Constraints --> Change Constraints --> Not Null ]
Even here the Not Null hyperlink refers to the Not Null HTML file from v19.2
Whereas we need it to point to the Not Null HTML page of v20.2

Please correct me if I'm wrong regarding my understanding here, So that I can proceed. 
Thanks.

**Comment by Amruta-Ranade** [comment]
Yep..you are on the right track. Please update the 20.1 and 20.2 files as well.

**Comment by aniketrb-github** [comment]
> Yep..you are on the right track. Please update the 20.1 and 20.2 files as well.

Thanks for the go-ahead.
I raised a PR, but I will do the changes for the v.20.2 and v.20.1 also shortly.

**Comment by aniketrb-github** [comment]
Do we need to handle it for v19.1 as well?
I have made changes currently for v19.2, v20.1, and v20.2

**Comment by Amruta-Ranade** [comment]
Umm..it's okay if you don't. I think we support two previous versions, so v19.1 docs need not be updated. If it turns out I am wrong, I will update them later :)

**Comment by aniketrb-github** [comment]
okay. it's just a small thing for me. If you want I can fix it and maybe save a few minutes of yours. No problem.

**Comment by Amruta-Ranade** [comment]
Go for it then :) And thank you!

**Comment by aniketrb-github** [comment]
> Go for it then :) And thank you!

Sure. Not a problem. :)

**Comment by Amruta-Ranade** [comment]
Addressed in #8529
