### ISSUE TITLE
Global Load Balancer (GSLB) topology from user to app

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#5332]
## Title

haproxy, nlb are often used as load balancer from app to database.  for geo-distributed databases, GSLB is also required.  GSLB is used to connect users to the application.
 
## Description

a simple round-robin is not suitable for GSLB.  GSLB needs to route the user to the closest leaseholder for that user.  

## Outline

- describe GSLB topology
- describe challenging networking topology such as: 
- changing egress IP that could make identification of closest leaseholder difficult
- a user who is an equal distance away from two leaseholders and bounces back and forth between two regions

**Comment by jseldess** [comment]
@awoods187, @ericharmeling, I'm closing this, given it's focus on self-hosted deployment, but if you think it's worth tackling, please re-open.
