### ISSUE TITLE
memory settings

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/docs#5337]
This page [https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html) discusses memory but doesn't show how to set `--cache` or `--max-sql-memory`.

We should have some discussion regarding these settings and how to adjust.

**Comment by jseldess** [comment]
@glennfawcett, we have a section on these flags: https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#cache-and-sql-memory-size. I'll close this, but if you have specific suggestions, pleases reopen.
