### ISSUE TITLE
Recommendations for composite indexes

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/docs#5338]
Glenn Fawcett (glennfawcett) commented:

I answered this question for a customer....

_On the composite index, if the leading columns are low cardinality, is the order of the index important?_
Typically, you want to lead with the “highest” cardinality if that column is always one of the predicates.  If it is not, it depends on the query mix.  I would test it both ways with your workload and use the “Storing” clause as well when needed to support index only reads.

Jira Issue: DOC-313

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
