### ISSUE TITLE
Does CRDB support Functional Indexes?

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/docs#5339]
Glenn Fawcett (glennfawcett) commented:

Had this question from a customer and answered accordingly... not sure where to put this in the docs.

_Does CRDB support functional indexes?_
The best approach is to use a computed column and index the column.  This allows you to compute the function ONCE and use it many times.
https://www.cockroachlabs.com/docs/stable/computed-columns.html

Jira Issue: DOC-314

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
