### ISSUE TITLE
Expand Join docs

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#534]
Enhance the existing docs on [Join Expressions](https://www.cockroachlabs.com/docs/stable/joins.html):

Need to cover: 
- Interleaved joins ([RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_interleaved_table_joins.md), #2313) 
- Add real examples to different types of joins
- Add diagrams for algorithms
- Expand algorithm technical descriptions

Might also want to factor in important points from:
- https://www.cockroachlabs.com/blog/better-sql-joins-in-cockroachdb/
- https://www.cockroachlabs.com/blog/cockroachdbs-first-join/
- https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#use-indexes-for-faster-joins

**Comment by awoods187** [comment]
Include interleaving work, semi, anti, zizzag (2.1), etc.

**Comment by knz** [comment]
Some work on this started in #2762 so that 2.0 will have some (if not all) information on joins.

**Comment by jseldess** [comment]
For 2.1, this is part of https://github.com/cockroachdb/docs/issues/2944.

**Comment by sploiselle** [comment]
This doc's [current iteration](https://www.cockroachlabs.com/docs/v2.1/joins.html) looks pretty good! Going to close this issue, though anyone is obviously free to re-open it with more detail about what they'd like to see included.
