### ISSUE TITLE
Clarify that SHOW PARTITIONS doesn't show inherited constraints 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#5342]
Re: [SHOW PARTITIONS](https://cockroachlabs.com/docs//v19.2/show-partitions.html)

This page should call out the fact that inherited constraints are not shown.

**Comment by jseldess** [comment]
Good point. @ericharmeling, this is for you.

**Comment by ericharmeling** [comment]
@andreimatei Do we plan to show inherited constraints for 19.2? Also, when you say "inherited constraints" are you talking about zone constraints?

**Comment by andreimatei** [comment]
> Do we plan to show inherited constraints for 19.2 (with SHOW PARTITIONS)?

Don't know. The tracking issue is https://github.com/cockroachdb/cockroach/issues/40349

> Also, when you say "inherited constraints" are you talking about zone constraints?

yes.

**Comment by ericharmeling** [comment]
OK - thanks. I added a note (see #5364).

From [this issue](https://github.com/cockroachdb/cockroach/issues/40377), it looks like zone constraints are not inherited from parent partitions. Where else would they be inherited from?

**Comment by andreimatei** [comment]
> From this issue, it looks like zone constraints are not inherited from parent partitions. Where else would they be inherited from?

The parent table/index, then the database, then from the default zone.
