### ISSUE TITLE
Change Data Capture (CDC) Doc Update - Provide more clarity around kv.rangefeed.enabled

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#5345]
Re: [Change Data Capture (CDC)](https://cockroachlabs.com/docs//v19.1/change-data-capture.html)

## Issue Description

Provide more clarity around the topic discussed here: https://www.cockroachlabs.com/docs/v19.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency

As it is currently written it does sound like the "long-lived" connection could be in reference to the downstream sink, namely to http or one of the cloud sinks. 

## Suggested Resolution 

It should be stated that this is just an optimization internally for cockroach and has no effect on downstream sinks.

**Comment by jseldess** [comment]
@lnhsingh, @mwang1026, is this issue still valid?

**Comment by mwang1026** [comment]
Closing. We updated that section.
