### ISSUE TITLE
Function and operator descriptions

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#535]
Add one-sentence descriptions to each [operator and function](https://www.cockroachlabs.com/docs/functions-and-operators.html).

**Comment by jseldess** [comment]
Glad you're starting this, @sploiselle! Is this different than #19? If not, can you close one or the other?

**Comment by sploiselle** [comment]
@jseldess The doc looked so done I didn't realize there would be an open issue for it! This is totally duplicative.
