### ISSUE TITLE
Provide more guidance about restart protection in the systemd example configuration

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#5350]
Raphael ‘kena’ Poss (knz) commented:

Requested by customer: 

- the example systemd configuration provided in the doc site recommends `Restart=always`. 
- this seeems to suggest that systemd will keep retrying to (re)start a node, even if there is some kind of permanent error
- questions:
  - what mechanism is available to limit the amount of (re)start attempts
  - how will the user be informed/notified if a (re)start fails

(Note: I have recommended relying on systemd's settings `StartLimitIntervalSec=` and `StartLimitBurst=` which have suitable defaults, but these should be explained  / detailed in the docs nonetheless)

Jira Issue: DOC-319

**Comment by knz** [comment]
cc @jseldess for triage

**Comment by bdarnell** [comment]
> this seeems to suggest that systemd will keep retrying to (re)start a node, even if there is some kind of permanent error

Correct. It's difficult to distinguish permanent and temporary errors so it usually makes sense to just always restart. 

> what mechanism is available to limit the amount of (re)start attempts

Just the settings you pointed out, I think. 

> how will the user be informed/notified if a (re)start fails

Our [prometheus alert rules](https://www.cockroachlabs.com/docs/stable/monitor-cockroachdb-with-prometheus.html) cover the case of permanent failures (alerting on 5 minutes downtime or 5 restarts in 10 minutes). They could also set FalureAction or StartLimitAction if they want a systemd-only solution (or something that's sensitive to a single restart. 

We should perhaps be more aggressive in promoting prometheus alerting. Using prometheus (or translating these rules into another external alerting system) should be a requirement for any production-grade deployment. 

> (Note: I have recommended relying on systemd's settings StartLimitIntervalSec= and StartLimitBurst= which have suitable defaults, but these should be explained / detailed in the docs nonetheless)

These settings have reasonable defaults (allowing up to 5 restarts in 10 seconds); I wouldn't recommend changing them. I don't think we can or should inform our users about *everything* in systemd. We should limit our docs to things that are particularly relevant for CRDB users and refer them to systemd's own docs for everything else.
