### ISSUE TITLE
Shell copy-to-clipboard doesn't remove the prompt

### ISSUE THREAD

**Issue by randmark** [cockroachdb/docs#5353]
Re: [Deploy CockroachDB On-Premises](https://cockroachlabs.com/docs//v19.1/deploy-cockroachdb-on-premises.html)

## Issue Description
The Auto-copy doesn't work, it includes the $ prompt which messes up the commands.

## Suggested Resolution 
Fix the auto-copy sections.

**Comment by jseldess** [comment]
All code samples with `shell` syntax highlighting no longer strip the `$` character from the paste output.

**Comment by jseldess** [comment]
I think this problem started after this Jekyll upgrade PR was merged: https://github.com/cockroachdb/docs/pull/5239/files.

It looks like the JavaScript we use to remove the `$` prompt from `shell` code blocks, when the copy-to-clipboard button is used, is not longer working: https://github.com/cockroachdb/docs/blob/master/js/customscripts.js#L315

**Comment by jseldess** [comment]
@randmark, https://github.com/cockroachdb/docs/pull/5358 should fix this. Once those changes are live on the site, I'll retest and, if all's well, close this.

**Comment by jseldess** [comment]
All good now! @randmark, if you see this problem again, please re-open this.
