### ISSUE TITLE
sql: document Flyway 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5356]
CockroachDB now works well with Flyway as of version 6.2.3.

Pre- 6.2.3 Flway:
Flyway creates one transaction per config file.  This can be problematic as CRDB doesn't always handle schema changes inside transactions well.

We should recommend that when using Flyway customers separate schema changes into separate config file.

Similarly, when using Flyway and services like K8s it can cause multiple current changes to occur at the sametime. We should recommend that CREATE TABLE (and other similar statements) should use IF NOT EXISTS to prevent this. Alternatively, you could do this in an init file in which the schema changes apply first before spinning up additional nodes. 

cc @BramGruneir for other points here

**Comment by awoods187** [comment]
@jordanlewis can you add your comments on transaction rollbacks and concerns here

**Comment by jordanlewis** [comment]
Many databases support atomic transactions with schema changes inside. I believe that most people probably expect that Flyway will act that way - in other words, if a particular schema change in a migration file fails, the whole transaction will roll back and none of the migration will be applied.

This will not be true with CockroachDB as we're planning to remove the transaction wrapping the migrations entirely.

Some databases like MySQL also operate this way, we think, but it's important to document this so we don't confuse people.

**Comment by BramGruneir** [comment]
Here is what flyway has for Undo documentation:
https://flywaydb.org/documentation/command/undo

**Comment by jseldess** [comment]
@ericharmeling, is this on your radar? Not sure if we have a specific flyway sql issue from the sql roadmap...

**Comment by awoods187** [comment]
@jseldess we didn't make changes in CRDB here so it wouldn't be on the roadmap. I thought the way to signal that this was important was by adding the p-1?

**Comment by jseldess** [comment]
Ah, thanks, @awoods187. I think sometimes non-crdb things have been on the roadmap in the past. But yes, creating an issue with high priority is the right thing to do, but maybe assign it directly to Eric or Rich for quicker triage.

**Comment by awoods187** [comment]
Will do!

**Comment by ericharmeling** [comment]
This wasn't on my radar, but now it is! I'll follow up with questions @awoods187 (or @jordanlewis).

**Comment by awoods187** [comment]
All known issues will be fixed as of the next version of flyway (presumptively 6.4.2). This is now ready to document and we should prioritize it based on customer use.
