### ISSUE TITLE
Using an underscore in a database or username breaks kubernetes CSRs/secrets

### ISSUE THREAD

**Issue by bhechinger** [cockroachdb/docs#5365]
I was having trouble with an application trying to connect to a secure cluster.

The init-cert container would request the CSR. I would approve the CSR but then I would get this message:

```
2019/09/03 12:00:56 failed to get certificate: CertificateSigningRequest.Create(chremoas-dev.client.chremoas_dev) failed: certificatesigningrequests.certificates.k8s.io "chremoas-dev.client.chremoas_dev" already exists
```

Deleting the CSR would result in the same thing happening over and over.

I got lucky catching the following error message that would typically disappear before I could see it or I'd still be trying to figure this out.

```
2019/09/03 12:00:51 could not store secrets: Secret "chremoas-dev.client.chremoas_dev" is invalid: metadata.name: Invalid value: "chremoas-dev.client.chremoas_dev": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Once I changed my database username to `chremoas-dev` everything started working perfectly.

Due to kubernetes killing and re-creating containers when they fail unless you have your logs being shipped off somewhere this is very difficult to debug.

It is likely a very good idea to mention in the documentation about database and user names that if you are running a secure cluster in Kubernetes then you can not use underscores in them or you will be unable to get the certificates to access the cluster.

**Comment by knz** [comment]
cc @jseldess for triage - this is a convo on gitter and I thought this may be useful to call out in our k8s deployment docs

**Comment by jseldess** [comment]
Thanks for reporting this, @bhechinger.
