### ISSUE TITLE
Feedback on left nav

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#5367]
I just went looking for our "build a python app" page and clicked around the left nav for a minute before giving up and using search. I thought there was a "develop" section, but there's not (at least not any more). I was confused by the presence of both "guides" and "tutorials" as top-level sections - what's the difference? The page I was looking for was under Guides/Get Started. I didn't look there because I assumed (incorrectly) that that section was just about installing and starting your first cluster. I think the per-language guides are more evergreen than "getting started" and should be hoisted up to a higher level.

**Comment by jseldess** [comment]
The sidenav has changed quite a bit in the meantime.
