### ISSUE TITLE
Next/previous links on release note pages

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#5368]
Ben Darnell (bdarnell) commented:

I realize that this is a fairly idiosyncratic use case, but one of my top activities on our docs site is to review all release notes since version X to see if a user-reported issue has already been fixed. This is currently a little cumbersome since only the latest version is in the sidebar. I have to go to "all releases" and then open each sub-version from there. It would be nice if each release note page had a link to the next/previous release in the same branch.

I'd also be happy if all of the patch release notes for a branch were consolidated into a single page (for better ⌘F searching) but that's a more intrusive change and might make the pages too unwieldy. 

Jira Issue: DOC-320

**Comment by fabiog1901** [comment]
I had a case with a client who commented he couldn't find the Release Notes he was looking for, claiming they were taken down while actually they were moved to the general All Releases section. 

I think a `/docs/releases/latest` page that aggregates all patch Release Notes for the latest major version would be very helpful:
- a one stop shop for customers to read the Release Notes for a major version + all its patches;
- easy to search&find a GH issue number in the document.
