### ISSUE TITLE
v2.1.9 Release Notes

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5369]
https://github.com/cockroachdb/cockroach/issues/40491

Tentative release: 9/23

**Comment by ericharmeling** [comment]
@rmloveland @bdarnell 

I'm passing these notes off to Rich, as he is on rotation for release notes this upcoming week (9/17-9/23). @kenliu Rich will also be doing release notes for 19.1.5, which I understand is also going out 9/23.

Rich, we can discuss what changes need to be made offline.

**Comment by bdarnell** [comment]
The commit for this release has moved to cockroachdb/cockroach@42d307e191ff6787a45e058be164fa452c47f368, which adds a few more changes.
