### ISSUE TITLE
Known Limitation: You cannot add stores to an existing node

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#5371]
In https://github.com/cockroachdb/cockroach/issues/39415, we see that adding a store to an existing node does not work correctly. We plan to improve the UX around this issue (instead of stalling), but will not be able to get a fix into 19.2. Because of that, we should document this as a known limitation for the upcoming release.

**Comment by israellot** [comment]
I've learned this limitation the hard way
