### ISSUE TITLE
sql: add width_bucket builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5373]
PR: https://github.com/cockroachdb/cockroach/pull/39263

From release notes:
> Added the `width_bucket()` builtin function. [#39263][#39263] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This function is already documented on the [Functions and Operators](https://www.cockroachlabs.com/docs/dev/functions-and-operators.html#math-and-numeric-functions) page.
