### ISSUE TITLE
sql: Add range size to SHOW RANGES command.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5374]
PR: https://github.com/cockroachdb/cockroach/pull/40281

From release notes:
> Added range size information to [`SHOW RANGES`](../v19.2/show-ranges.html). [#40281][#40281] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I'll close this and https://github.com/cockroachdb/docs/issues/5406 in the same PR.
