### ISSUE TITLE
Helm docs should describe how to set up TLS

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/docs#5387]
Encryption is disabled by default and we don't document how to enable this even though it's an extremely common requirement.  there is a secure.enabled flag that is accepted by the helm chart but is undocumented.  we should remedy this:

https://github.com/helm/charts/blob/d0fc388575a75936bb96c0024f7772e7ada434ce/stable/cockroachdb/templates/cluster-init.yaml

```
Secure.Enabled | Whether to run securely using TLS certificates | false
-- | -- | --
Secure.RequestCertsImage | Image to use for requesting TLS certificates | cockroachdb/cockroach-k8s-request-cert
Secure.RequestCertsImageTag | Image tag to use for requesting TLS certificates | 0.4
Secure.ServiceAccount.Create | Whether to create a new RBAC service account | true
Secure.ServiceAccount.Name | Name of RBAC service account to use | ""
```

**Comment by keith-mcclellan** [comment]
specifically, we should describe how to use user provided certs

**Comment by jseldess** [comment]
@keith-mcclellan, see step 3 here: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#step-2-start-cockroachdb. 

> Install the CockroachDB Helm chart, providing a "release" name to identify and track this particular deployment of the chart and setting the `Secure.Enabled` parameter to `true`.

That's the helm view of the secure version of the tutorial. Definitely enabling security. Are you saying something else is missing?

**Comment by jseldess** [comment]
I think the user-provided cert question is covered by https://github.com/cockroachdb/docs/issues/4696?

**Comment by jseldess** [comment]
@keith-mcclellan, ping on the above.
