### ISSUE TITLE
sql: cluster_logical_timestamp doc

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#539]
[`cluster_logical_timestamp`](https://www.cockroachlabs.com/docs/functions-and-operators.html#system-info-functions) is proprietary to CockroachDB and doesn't have an explanation of its purpose or details of its implementation

@andreimatei suggests:
- Recategorizing with other [Date and Time Functions](https://www.cockroachlabs.com/docs/functions-and-operators.html#date-and-time-functions)
- At least having an explanation of its function
- At most giving it its own document because it's unclear its original intent and how it works

@knz is the original dev, so need to research with him.
### Related issues
- [operators and functions](https://github.com/cockroachdb/docs/issues/19)

**Comment by dt** [comment]
as mentioned offline, choice of putting it in "system info" category was intentional at one point, since it doesn't (directly) provide a `date` or `time` that a user could actually use, but it does describe an attribute/state of the system.

**Comment by andreimatei** [comment]
Well but whatever state it's trying to expose, it is tied to a transaction. So it's not a pure system introspection function... Anyway, yeah, the point of this is for @knz or @tschottdorf to tell us what this chump is for.

**Comment by knz** [comment]
This is a function we'd rather not advertise at this time. My preference would be to not have this function listed in any section at all. If we decide to have a documentation page for it, perhaps the user should be able to only find it if they search for it using the search box, ie they already know it exists.

The documentation page should probably contain a mash-up of the following points:

- this is an internal function which is used for testing at Cockroach Labs, not intended for use in production;

- its semantics are subject to change without further/advance notice; 

- despite its name, you cannot use it to measure time in any useful fashion;

- **if you think that you have any reason to want to use this function or anything like it, please contact us first and see if we can provide a new, supported, documented function for your use case.**

**Comment by sploiselle** [comment]
@knz Thanks! Maybe documenting it in the [Wiki](https://github.com/cockroachdb/cockroach/wiki) is a good idea? Or maybe just inline in [builtins.go](https://github.com/cockroachdb/cockroach/blob/67ca5c9eb243068b78198b2aa67ce9cc2406b111/sql/parser/builtins.go)? Not sure what other internal spots we have set up for documenting test procedures.

@dt Is it possible to hide the function from the Functions and Operators page?

**Comment by dt** [comment]
Would just special-case it in the docs generation code if we really want to hide it, though my 2¢ would be not to. but either leave it where it is (imo "system info" rather than "date and time" should already indicate that it is not for measuring time) or make a "internals and debugging" category, and when we add descriptions to these, we can include a "this function is intended for inspecting CockroachDB internals during debugging, and should not be used in production" warning.

**Comment by jseldess** [comment]
I like the idea of putting this in a new "Internals and Debugging" section with a clear disclaimer that it's not intended for use in production. @knz, would you be good with that? Are there perhaps other functions that would be better grouped under "Internals and Debugging" as well?

**Comment by knz** [comment]
There are the two experimental functions:

- `experimental_unique_bytes` for which I'm not sure what to say
- `experimental_uuid_v4` which is a deprecated name for another function which we do support (`uuid_v4`) - we keep the old name for backward compatibility with previous dbs already using it.

**Comment by jseldess** [comment]
Marked as for Cockroach devs only.
