### ISSUE TITLE
SQL Tuning with EXPLAIN Doc Update 

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#5401]
Re: [SQL Tuning with EXPLAIN](https://cockroachlabs.com/docs//v19.2/sql-tuning-with-explain.html)

## Issue Description

When talking about the full table scan in the first second, I believe it would be helpful to point out the `spans ALL` as the clear indicator of a full table scan. Also a quick refresher on what the `<table>@<index>` syntax means would also be helpful. 

## Suggested Resolution 

Add information on what `span` and `<table>@<index>` means.

**Comment by jseldess** [comment]
Thanks for the feedback, @rkruze.

@Amruta-Ranade, this should be a quick, easy update. Would be great to get to it before too long, since the missing details sounds important.
