### ISSUE TITLE
Licensing FAQ: update language around free tier for educational orgs

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#5402]
Link: https://www.cockroachlabs.com/docs/stable/licensing-faqs.html#i-work-for-a-non-profit-as-a-student-or-in-academia-and-i-would-like-to-use-cockroachdb-do-i-need-a-license-to-access-enterprise-features

In the above question, we point out that CockroachDB can be provided for free to select institutions. We should clarify this language to point out that the free offering is only for our on-prem deployed version of CockroachDB. We can offer discounted pricing on CockroachCloud, but it will not be free. In both cases, contacting us is the correct next step.

cc @kannanlakshmi who is figuring out next steps for CockroachCloud after a request from a prospective customer

**Comment by jseldess** [comment]
@piyush-singh, @kannanlakshmi, how important is this update? Needed in the 19.2 timeframe?

**Comment by kannanlakshmi** [comment]
Its nice to have but by no means blocking for 19.2 It would also be simply updating this sentence "Cockroach Labs is willing to offer CockroachDB enterprise features free of charge to select non-profit organizations and non-commercial academic projects. To learn more, please contact us." 
to read "Cockroach Labs is willing to offer CockroachDB enterprise features free of charge for select non-profit organizations and non-commercial academic projects that are hosting the database themselves. To learn more, please contact us." 

I think adding the phrase "hosting the database themselves" is the only change necessary and clarifies that this doesn't include cloud.
