### ISSUE TITLE
sql: Reorder show ranges output to be clearer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5406]
PR: https://github.com/cockroachdb/cockroach/pull/40501

From release notes:
> Reordered columns in [`SHOW RANGES`](../v19.2/show-ranges.html) output [#40501][#40501] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I'll close this and https://github.com/cockroachdb/docs/issues/5374 in the same PR.
