### ISSUE TITLE
sql: SHOW CREATE TABLE warns on partitioned tables without zone configs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5407]
PR: https://github.com/cockroachdb/cockroach/pull/40475

From release notes:
> [`SHOW CREATE TABLE`](../v19.2/show-create.html) now warns users if they have a partitioned table that does not contain zone configurations [#40475][#40475] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@jseldess Does this need to be documented?

**Comment by jseldess** [comment]
I think so, yes. This is a way to find out if any partitions do not yet have zone configs. Let’s talk about this in person and figure out the right place to document it.
