### ISSUE TITLE
sql: COPY FROM sql statement

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#546]
- Document [sql: support COPY FROM](https://github.com/cockroachdb/cockroach/issues/8585)

Another relevant PR: https://github.com/cockroachdb/cockroach/pull/12723

**Comment by jseldess** [comment]
One thing that just occurred to me, @sploiselle: This new content mentions that `COPY` will be in the `.sql` file from PostgreSQL, but do we need to add a standalone page on using `COPY`?

**Comment by sploiselle** [comment]
@mjibson Is `COPY` supported in other contexts?

**Comment by mjibson** [comment]
Yes, `COPY` is supported by any driver that supports the COPY protocol. I'm not sure what else there is to say there...
