### ISSUE TITLE
Update 'Reads and Writes in CockroachDB' with Parallel Commits info, as needed

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5466]
Subtask of #4723.

**Comment by rmloveland** [comment]
@nvanbenschoten I've reviewed [Reads and Writes in CockroachDB](http://www.cockroachlabs.com/docs/v19.2/architecture/reads-and-writes-overview.html) (esp. the **Writes** section) and I don't think the Parallel Commits changes affect anything that is written there, since it is pretty high level, e.g.,

> As soon as one follower has appended the write to its Raft log (and thus a majority of replicas agree based on identical Raft logs), it notifies the leader and the write is committed to the key-values on the agreeing replicas.

Do you mind looking at that doc and letting me know if you agree with that assessment?

**Comment by nvanbenschoten** [comment]
Nope, it doesn't change anything in that doc.
