### ISSUE TITLE
sql: Recommended ORMs with tutorials

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#547]
Page listing the ORMs we've tested and officially support, similar to the [Install Client Drivers](https://www.cockroachlabs.com/docs/install-client-drivers.html) page. 

@nvanbenschoten recommends we not provide detailed docs on using an orm with cockroach as we'd mostly be documenting other people's software. At the least, we could link to our [Cockroach ORM examples](https://github.com/cockroachdb/examples-orms). We may also want to write a single tutorial or blog post for one of the most popular orms. 

- [x] SQLize (node.js - @cuongdo as resource)
- [ ] Active Record (ruby - @tamird as resource)
- [x] Hibernate (java - @jordanlewis as resource)
- [x] Gorm (go - @cuongdo as resource)
- [x] SQLAlchemy (python - @bdarnell & @cuongdo as resource)

**Comment by dianasaur323** [comment]
@jseldess I just chatted to @cuongdo about this. We should find a way to surface this more quickly to users so that they know we have it. Development isn't ready yet, so likely a mid- to end- Q1 goal.

**Comment by jseldess** [comment]
Sounds good, @dianasaur323. Thanks for the update.

**Comment by jseldess** [comment]
Take-aways from meeting with @cuongdo, @nvanbenschoten, @knz, and @jordanlewis:

Docs to be created:
1. Page listing recommended ORMs (similar to our list of recommended client drivers).
2. Tutorial for each of the following ORMs:
  - SQLize (node.js - @cuongdo as resource)
  - Active Record (ruby - @tamird as resource)
  - Hibernate (java - @jordanlewis as resource)
  - Gorm (go - @nvanbenschoten as resource)
  - SQLAlchemy (python - @bdarnell & @cuongdo as resource)

We'll probably put each tutorial on a distinct page but make it look like it's a single page with toggles (see https://www.cockroachlabs.com/docs/deploy-cockroachdb-on-aws.html for reference).

Other notes:
- Start with SQLAlchemy and Gorm. Write and publish these as they're ready, in conjunction with a blog post.
- 2 main pieces of tutorial: getting started (link to ORM's docs) and steps to configure with CockroachDB (our docs - using [examples-orms repo](https://github.com/cockroachdb/examples-orms)).
- Important not to oversell compatibility. Basic support. Request customer feedback.
- Rely on third-party docs where we can (as we do for k8, prometheus, etc.).
