### ISSUE TITLE
Deploy CockroachDB on AWS EC2 Doc Update 

### ISSUE THREAD

**Issue by petervandivier** [cockroachdb/docs#5480]
Re: [Deploy CockroachDB on AWS EC2](https://cockroachlabs.com/docs//v19.1/deploy-cockroachdb-on-aws.html)

## Issue Description

Code block lines that have an unpaired `>` character following a space in source markdown have the code snippet truncated after that character in the rendered html on the official docs page.

For example:

https://github.com/cockroachdb/docs/blame/master/v19.2/add-constraint.md#L58

```
~~~ sql
> ALTER TABLE orders ADD CONSTRAINT check_id_non_zero CHECK (id > 0);
~~~
```

The final rendered output as seen at https://www.cockroachlabs.com/docs/stable/add-constraint.html#add-the-check-constraint is...

<img width="537" alt="Screenshot 2019-09-25 at 13 24 14" src="https://user-images.githubusercontent.com/10898767/65600506-2331cc80-df98-11e9-94b8-5e6d013e3c98.png">

You will note that the `>` character has been stripped. 

A more problematic example can be seen at https://www.cockroachlabs.com/docs/stable/create-security-certificates-openssl.html#create-the-ca-key-and-certificate-pair 

The source https://github.com/cockroachdb/docs/blame/master/v19.2/create-security-certificates-openssl.md#L174

```
~~~ shell
$ echo '01' > serial.txt
~~~
```

...renders to...

<img width="305" alt="Screenshot 2019-09-25 at 13 31 18" src="https://user-images.githubusercontent.com/10898767/65600844-d7cbee00-df98-11e9-903b-c72f49f6ffd3.png">

...where the command is no longer useful.

## Suggested Resolution 

As a workaround, it is in many cases possible to pull up the source markdown and follow along side-by-side to confirm the accuracy of commands to be executed. However in some cases sections are inlined referenced documents and in at least one I've been unable to find the source markdown for an inlined reference.

At https://github.com/cockroachdb/docs/blame/master/v19.2/deploy-cockroachdb-on-aws.md#L116

we see...

```
## Step 9. Run a sample workload

{% include {{ page.version.version }}/prod-deployment/secure-test-load-balancing.md %}
```

...sub-step `Step 8.` of which is...

```
wget -qO- https://raw.githubusercontent.com/cockroachdb/docs/master/_includes/v19.1/prod-deployment/securecockroachdb.service
```

I assume there's meant to be a redirected `> securecockroachdb.service` but I cannot verify this because the `secure-test-load-balancing.md` does not appear to exist in the `/_includes` resources at this time 

```
[0925 13:43:26+0100 ~/repos/git/cockroachdb-docs]$ git rev-parse HEAD
62f2864878271076542ce6541f3fd14169c43e4d

[0925 13:43:33+0100 ~/repos/git/cockroachdb-docs]$ find . -name secure-test-load-balancing

[0925 13:43:52+0100 ~/repos/git/cockroachdb-docs]$
```

**Comment by jseldess** [comment]
Thank you very much for reporting this, @petervandivier! We are working on a fix. 

We think this is caused by some JavaScript that tries to remove the `>` prompt from SQL code blocks and the `$` prompt from shell code blocks. Hope to have it fixed soon.

**Comment by jseldess** [comment]
@petervandivier, https://github.com/cockroachdb/docs/pull/5487 should have fixed this. Please let us know if you run into this issue again.
