### ISSUE TITLE
Consider removing copy-paste buttons from code snippets

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5481]
After looking at #5480 I am not convinced that the convenience provided by the copy-paste buttons are worth the risk.

They are essentially using regular expressions to "parse" (but not really, because they can't) the content of SQL or shell snippets, which is not the Right Thing (tm), and very hard to get right for arbitrary text.

This class of bugs is possibly dangerous to a user (see #5480), whereas using the built-in "copy and paste stuff with your mouse" functionality that computers already have works as expected.  Or at least, it does not lead the user into a false sense of security.  They copy exactly the text that is painted by the mouse selection.

Based on the above, we should consider removing the copy-paste buttons.

**Comment by jseldess** [comment]
As mentioned in another channel, I definitely do not want to remove the copy/paste buttons. It’s a huge UX win/time-saver for users, and it's common in other docs, so if we're not doing it right, there should be a good solution.

**Comment by petervandivier** [comment]
Fwiw - the behavior I describe in #5480 is not assisted by this suggestion. copy-paste from browser is equally impacted by the markdown->html conversion as is the click-to-copy button.

There is some minor behavioral variance between the two, but the #5480 big impacts both
