### ISSUE TITLE
Document workaround for known issue: import ignores role memberships when checking for DB `CREATE` privileges.

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#5484]
Reference: https://github.com/cockroachdb/cockroach/issues/37447

Known issue: Importing data as a user (not `root`) requires CREATE TABLE privileges even if user is assigned to the admin role.

Workaround: Grant `CREATE` to a user with the admin role and it will import successfully.

**Comment by mwang1026** [comment]
Fixed via another issue
