### ISSUE TITLE
Examples of log file format

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#5486]
## Title

Customers have expressed interested in parsing the log file.  https://www.cockroachlabs.com/docs/stable/debug-and-error-logs.html has broad info, but does not provide enough info.

## Description

A bit more detail on log file format [outlined here](https://github.com/timveil-cockroach/log-analyzer) could be useful. cc @timveil @tbg 

## Outline

Below info could be useful:

For example, a typical line in a CockroachDB log file looks like this...

I181220 15:30:03.971234 1 util/log/clog.go:1176  [config] running on machine: us-central1-node-0003
Where the first character is either I, W, E or F, signifying an INFO, WARN, ERROR or FATAL statement. Immediately following the log level is the custom timestamp, which is equivalent to %y:%m:%d %H:%M:%S.%6N in standard Unix strptime() parlance. The rest of the log statement is application specific.

## Expected Audience

**Comment by jseldess** [comment]
@taroface, @knz, I think this issue will be resolved with the 21.1 logging work?

**Comment by knz** [comment]
yes thanks
