### ISSUE TITLE
Geo-Partitioned Leaseholders Topology Doc Update 

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#5488]
Re: [Geo-Partitioned Leaseholders Topology](https://cockroachlabs.com/docs//v19.1/topology-geo-partitioned-leaseholders.html)

## Issue Description
While working with a prospect they were confused on this topology since they thought they would have to geo partition on a row basis and wouldn't have the option to do database or table level partitioning if needed. 

## Suggested Resolution 

Add information on how to pin leaseholders on a given table, database or whole cluster.

**Comment by jseldess** [comment]
@rkruze, thanks for this feedback. I'm unsure as to whether that's the same topology or something distinct. Are you thinking we should have one topology to cover "pinning leaseholders", and it covers all possible levels?
