### ISSUE TITLE
import: defaults are not accepted when importing

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#5494]
Examples of using import on our docs site look like this: 

```
IMPORT TABLE customers (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name TEXT,
        INDEX name_idx (name)
)
CSV DATA ('s3://acme-co/customers.csv?AWS_ACCESS_KEY_ID=[placeholder]&AWS_SECRET_ACCESS_KEY=[placeholder]&AWS_SESSION_TOKEN=[placeholder]')
;
```

However defaults are not accepted when importing. This will throw an error similar to this:
 
`pq: s3://acme-co/customers.csv?AWS_ACCESS_KEY_ID={PLACEHOLDER}&AWS_SECRET_ACCESS_KEY={PLACEHOLDER}: row 2: expected 2 fields, got 1`

We should either remove this example, or make a note that if you want to use a gen function with as a default, you're file should contain values for that column initially.

**Comment by jseldess** [comment]
@lnhsingh, we need to handle this in the current stable docs as well. Got this feedback submission from a user:

![Screen Shot 2020-01-23 at 11 54 53 AM](https://user-images.githubusercontent.com/15893490/73005583-31251c00-3dd7-11ea-8cc8-a0f90dfa9b46.png)
