### ISSUE TITLE
Update Nav: Add "CONTACT US" and Resources::Events

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#5509]
We are updating the main nav to include: 

1. a CONTACT US button (see mocks here https://www.figma.com/file/waGiUrAg49yiPRezGRoxbT/CRL_HP) that should click to https://www.cockroachlabs.com/contact)

2. Adds "events" (https://www.cockroachlabs.com/community/events/) under the Resources tab -- underneath "Forum".

We will wait to push the new homepage live until you've had a chance to make the changes to the nav. Can you let me know if you need anything from me on the changes, and when you can make them?

[edited to add]
Can you also revert the "GET COCKROACHDB" button to click to https://www.cockroachlabs.com/get-cockroachdb/ ?

Thank you!

**Comment by jseldess** [comment]
I'll handle this in just a bit, @jess-edwards.
