### ISSUE TITLE
sql: check privileges in CONFIGURE ZONE commands

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5511]
PR: https://github.com/cockroachdb/cockroach/pull/40879

From release notes:
> [`CONFIGURE ZONE`](../v19.2/configure-zone.html) statements now fail if the user does not have sufficient privileges. If the target is a `system` range, the `system` database, or a table in the `system` database, the user must have an admin role. For all other databases and tables, the user must have the `CREATE` privilege on the target database or table. This change might be backward-incompatible for users running scripted `CONFIGURE ZONE` statements with restricted permissions. To add the necessary permissions, use [`GRANT` &lt;privileges&gt;](../v19.2/grant.html) or [`GRANT` &lt;roles&gt;](../v19.2/grant-roles.html) as a user with an admin role. For example, to grant a user the admin role, run `GRANT admin TO <user>`. To grant the `CREATE` privilege on a database or table, run `GRANT CREATE ON [DATABASE | TABLE] <name> TO <user>`. [#40879][#40879] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This was fixed by #5609.

When I merged that PR, I referenced the wrong issue that it fixed.
