### ISSUE TITLE
opt,sql: disallow column references in ROWS/RANGE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5514]
PR: https://github.com/cockroachdb/cockroach/pull/40832

From release notes:
> Column references are no longer allowed in `ROWS` and `RANGE` clauses in [window functions](../v19.2/window-functions.html). [#40832][#40832] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rmloveland Assigning to you, per our discussion earlier.

**Comment by ericharmeling** [comment]
@justinj (see https://github.com/cockroachdb/docs/pull/5790).
Our behavior before this change was undocumented and not postgres-like. I don't think we should document this change.
