### ISSUE TITLE
opt: disallow mutations under union

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5517]
PR: https://github.com/cockroachdb/cockroach/pull/40975

From release notes:
> Mutations under `UNION` or `UNION ALL` are now disallowed; `WITH` should be used on top of the union operation instead. This restriction is temporary and will be lifted in a future release. [#40975][#40975] {% comment %}doc{% endcomment %}

**Comment by RaduBerinde** [comment]
The change is being reverted in https://github.com/cockroachdb/cockroach/pull/41356.
