### ISSUE TITLE
cli: fix the demo licensing code

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5521]
PR: https://github.com/cockroachdb/cockroach/pull/41029

From release notes:
> Added support for redirecting license acquisition to a replacement server (e.g. a suitably configured HTTP proxy), with the environment variable `COCKROACH_DEMO_LICENSE_URL`. This enables [`cockroach demo`](../v19.2/cockroach-demo.html) with enterprise features in firewalled network environments. [#41029][#41029] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@knz Do we want to document `COCKROACH_DEMO_LICENSE_URL`? It seems to be for testing purposes. If we do document it, we should probably specify what the response of a "suitably-configured" HTTP server would need to be. (E.g. "The endpoint response must be a JSON object of the following form:..." or "The endpoint must return a string properly-formatted for `enterprise.license`").

**Comment by knz** [comment]
I would list it in the release note but not add it to the documentation otherwise.

**Comment by ericharmeling** [comment]
Noted. Thanks!
