### ISSUE TITLE
sql: Add command to show range information about a row/rows

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5534]
PR: https://github.com/cockroachdb/cockroach/pull/40954

From release notes:
> Added `FOR ROW` clause to [`SHOW RANGES`](../v19.2/show-ranges.html) to show range information for a particular row. [#40954][#40954] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
As noted by @knz in https://github.com/cockroachdb/cockroach/pull/40954, this should be noted as "experimental".

**Comment by ericharmeling** [comment]
More detail from release note:
>This is particularly useful for validating the location of a specific piece of data when using partitions to control data location for improved performance or GDPR compliance. Note that this new statement is experimental and its interface and output are subject to change.
