### ISSUE TITLE
Update generated docs for crdb_internal.force_retry

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5538]
Currently the docs for `crdb_internal.force_retry()` state:

> This function is used only by CockroachDB's developers for testing purposes.

However this is not entirely accurate.  It is useful to developers when writing and testing app retry loops as described in #5035. Thanks to the fix for https://github.com/cockroachdb/cockroach/issues/39243, you also don't need to be root anymore to run it.

I'm not sure exactly what the doc should be, but maybe something like 

> Triggers a transaction retry.  Useful for testing purposes.

Or something even better :-}

To update this you will need to edit `pkg/sql/sem/builtins.go` in the CRDB repo. You'll need to edit the `Info` key shown below.

```golang
// If force_retry is called during the specified interval from the beginning
// of the transaction it returns a retryable error. If not, 0 is returned
// instead of an error.
// The second version allows one to create an error intended for a transaction
// different than the current statement's transaction.
"crdb_internal.force_retry": makeBuiltin(
    tree.FunctionProperties{
        Category: categorySystemInfo,
        Impure:   true,
    },
    tree.Overload{
        Types:      tree.ArgTypes{{"val", types.Interval}},
        ReturnType: tree.FixedReturnType(types.Int),
        Fn: func(ctx *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
            minDuration := args[0].(*tree.DInterval).Duration
            elapsed := duration.MakeDuration(int64(ctx.StmtTimestamp.Sub(ctx.TxnTimestamp)), 0, 0)
            if elapsed.Compare(minDuration) < 0 {
                return nil, ctx.Txn.GenerateForcedRetryableError(
                    ctx.Ctx(), "forced by crdb_internal.force_retry()")
            }
            return tree.DZero, nil
        },
        Info: "This function is used only by CockroachDB's developers for testing purposes.",
    },
),
```

**Comment by jseldess** [comment]
@rmloveland, you planning to do this, or should I take it?

**Comment by rmloveland** [comment]
Feel free to grab!  I didn't plan on working on this yet.

**Comment by awoods187** [comment]
I'm coming around to the notion that we should document this sooner rather than later. It would be immensely useful for developers to be able to prove that their retry logic works with a quick and deterministic test. 

Also, worth noting here, you need to set the value to be longer than the duration of the transaction:
```SQL
root@localhost:26257/tpcc  OPEN> select crdb_internal.force_retry('10 s')
                              -> ;
  crdb_internal.force_retry
-----------------------------
                          0
(1 row)

Time: 886µs
```
As you can see above, when its too short it doesn't work. Proper behavior looks like this:
```SQL
root@localhost:26257/tpcc  OPEN> select crdb_internal.force_retry('10 m')
;
ERROR: restart transaction: crdb_internal.force_retry(): TransactionRetryWithProtoRefreshError: forced by crdb_internal.force_retry()
SQLSTATE: 40001
```

**Comment by rmloveland** [comment]
For those reading along, we have some examples of its use for testing retry loops in some of the example apps.  For example, on the [Build a Python app with CockroachDB](https://www.cockroachlabs.com/docs/v20.1/build-a-python-app-with-cockroachdb) page (which uses psycopg2), see the function `test_retry_loop(conn)`.

There is also some logic in [the JDBC example](https://www.cockroachlabs.com/docs/v20.1/build-a-java-app-with-cockroachdb.html) if you search for the `FORCE_RETRY` variable that was used to toggle retries during that example's development.
