### ISSUE TITLE
Update docs on epoch based leases

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5563]
The [replication layer docs](https://www.cockroachlabs.com/docs/stable/architecture/replication-layer.html#epoch-based-leases-table-data) state that epoch based leases help us avoid "tracking leases for every range".

We should clarify exactly **how** epoch based leases help us avoid tracking leases for every range, since it isn't obvious from the current description.

**Comment by irfansharif** [comment]
Here's my attempt at explaining epoch based vs. expiration based leases elsewhere. Let me know if I can further elaborate. It also clarifies the following sentence in the docs "However, instead of using epochs, they [system ranges] have an expiration-based lease." (no reason provided for why we do this).

> To avoid having to perform lease extensions on a per range basis, CRDB implements a notion of "epochs", defined as the period between a node joining and disconnecting from a cluster. When a node disconnects, the epoch is considered changed, and the node immediately loses all of its leases. Each node is then simply responsible for periodically updating its liveness record (simply a system range key), which has the effect of automatically extending all its leases. By assuming leases don't expire until a node loses connection, we eliminate a substantial amount of traffic and Raft processing we would otherwise incur. [...]
>
> [...] Since system ranges containing the liveness records cannot themselves use epoch-based leases (circular dependency, the system ranges themselves are used for epoch tracking), they fall back to using expiration-based leases.
