### ISSUE TITLE
We should steer Windows customers away from PowerShell ISE

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#5571]
Task: We should steer users away from PowerShell ISE and towards regular PowerShell.

Issue: PowerShell ISE won't run the SQL shell, but PowerShell will. Unfortunately, the two are easy to conflate.

This is a problem because if users conflate the two, they may get frustrated while using PowerShell ISE and stop exploring CockroachDB.

Steps to reproduce
-------------------

* Start up Windows 10
* Download and unpack the executable
* Start typing PowerShell in the Windows Search bar in the bottom-left hand corner, with the hourglass.
* Select the top result (which was PowerShell ISE for me)
  * Note: PowerShell also came up, but it wasn't the top item
* Run a `cockroach start-single-node --insecure` command (possibly with other flags) and see the node start up
* Open a new tab in PowerShell ISE
* Run `cockroach sql --insecure`

Expected Result
----------------

PowerShell ISE connects to the SQL shell and allows the user to run SQL commands

Actual Result
-------------

PowerShell ISE connects to the SQL shell and then hangs

Possible Solution(s)
--------------------

* A possible solution would be to make it clear what the distinction is between PowerShell ISE and PowerShell, and steer users toward the latter.
* (We could also steer users toward the command prompt, but I think this is an inferior choice)

Relevant links:

* This Server Fault issue: [How to run mysql prompt in windows powershell ISE?](https://serverfault.com/questions/654806/how-to-run-mysql-prompt-in-windows-powershell-ise), showing that it is a longstanding, known issue with PowerShell ISE.
* Our [Windows installation docs](https://www.cockroachlabs.com/docs/stable/install-cockroachdb-windows.html)
* Our [Start a Local Cluster docs](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html), which lack Windows instructions at all.

**Comment by jseldess** [comment]
We haven't received any comments or complaints on this topic, so closing for now.
