### ISSUE TITLE
Document how site build and deployment works

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5584]
This morning we experienced some broken links on the [Releases page](https://www.cockroachlabs.com/docs/releases/).  The links to the individual release notes for 19.1.5, 19.1.4, etc. were broken.

Specifically, they pointed to https://www.cockroachlabs.com/docs/v19.1.5.html (and similar) when they should have pointed to https://www.cockroachlabs.com/docs/releases/v19.1.5.html (which was up and working as expected).

Further, the "broken" links were not our 404 page, but some weird non-functional HTML page with some text from our nav and the "busted image link" picture that browsers show when an image link doesn't work.

As part of investigating this, I ran a build of the site locally from the latest `master` branch as of this morning.  The links from the releases page were working as expected on a locally running copy of the site.

Approximately 20 minutes later (from when I first noticed the broken links and messaged our team on Slack), I refreshed https://www.cockroachlabs.com/docs/releases/ and checked the links again.  Now the links were pointing to the correct targets (e.g., https://www.cockroachlabs.com/docs/releases/v19.1.5.html).

There are several important things to note about this:

- we have no way of knowing how long those links were broken before I noticed it at approximately 11:20 am today
- nothing ever alerted us to the fact that links were broken (AFAICT, please correct me if I'm not aware of something)
- According to git, the Jekyll template logic that generates that list of links hasn't changed since 2017, and there does not appear to be anything in that logic that would point links to https://www.cockroachlabs.com/docs/v19.1.5.html, so it's not clear what "thing" rewrote those links
- As a user who is pretty familiar with how the site's HTML is built, I had no way to troubleshoot this, and no mental model for what was wrong other than "just wait longer and hope it's ok" followed by "ask for help in Slack"

I think our team should create internal documentation on:

- How the site is actually deployed (I think Netlify?)
- What to look at when stuff breaks like this
- Explicit troubleshooting steps (e.g., look in Netlify deployment dashboard or whatever is actually true) that our team can use in case things don't resolve.

Apologies if we already have docs on this and I haven't seen it yet.  I did a search on our internal wiki for "netlify" and didn't see anything.

**Comment by jseldess** [comment]
@yingzhuchin did this: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/464453705/Docs+CI+CD
