### ISSUE TITLE
Document batch DELETEs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5592]
A customer pointed out that our `DELETE` doc doesn't have any mention of how to best delete multiple rows. 

![Screen Shot 2019-10-10 at 9 08 38 AM](https://user-images.githubusercontent.com/15893490/66571612-995c3480-eb3d-11e9-99ed-63792624e963.png)

This is a gap. 

- Our SQL best practices call out "Delete multiple rows" in the ["Multi-row DML best practices"](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#multi-row-dml-best-practices) section, but don't link to a meaningful example. 
- Also on that page, there's no mention of this in the ["Bulk deletion best practices"](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#bulk-deletion-best-practices) section, in contrast to the "Insert delete best practices" section.  

Suggestion:

1. Extend the [`DELETE`](https://www.cockroachlabs.com/docs/stable/delete.html) doc to include a "Performance best practices" section similar to on [`INSERT`](https://www.cockroachlabs.com/docs/stable/insert.html#performance-best-practices), and add an explicit "Delete multiple rows" example similar to what we have on [`INSERT`](https://www.cockroachlabs.com/docs/stable/insert.html#insert-multiple-rows-into-an-existing-table) and [`UPSERT`](https://www.cockroachlabs.com/docs/stable/upsert.html#upsert-multiple-rows).
2. Update the SQL Best Practices doc (issues described above).
3. Feature this ability in the ["Delete rows in a table"](https://www.cockroachlabs.com/docs/stable/learn-cockroachdb-sql.html#delete-rows-in-a-table section of "Learn CockroachDB", like we do for [`Insert rows into a table`](https://www.cockroachlabs.com/docs/stable/learn-cockroachdb-sql.html#insert-rows-into-a-table).

Sidenote: As a follow-up, we may want to investigate doing similar work for `UPDATE` and `UPSERT`.

**Comment by jseldess** [comment]
@ericharmeling, marking this for the 20.1 timeframe, but feel free to pull into 19.2, if you have the bandwidth.

**Comment by awoods187** [comment]
I'm promoting this to P-1 after concerns from @rkruze that customers frequently run into this project. Also could overlap with developer guide cc @rmloveland

**Comment by rmloveland** [comment]
Thanks @awoods187, will make sure to coordinate with @ericharmeling and have an example in the developer guide.
