### ISSUE TITLE
CC: Update FAQs

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#5594]
Update CC FAQs with this question: 

Q:Why can't I use region X in AWS or region Y in GCP?
A: We run CockroachCloud in the managed Kubernetes offerings available in AWS and GCP and support all regions that the two offerings are available in. If a particular region is not available on the CockroachCloud console, that is due to the cloud provider not supporting the managed kubernetes offering in that region. See here for a full list of regions that EKS and GKE are available in: 

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/
https://cloud.google.com/about/locations/

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/5734
