### ISSUE TITLE
Follower reads should mention SET TRANSACTION syntax

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#5613]
https://www.cockroachlabs.com/docs/stable/follower-reads.html doesn't currently mention https://www.cockroachlabs.com/docs/v19.1/set-transaction.html#use-the-as-of-system-time-option, which is an important syntax to enable follower reads for ORMs. We should include it in that doc.

**Comment by jseldess** [comment]
We should also update https://www.cockroachlabs.com/docs/stable/topology-follower-reads.html#configuration.
