### ISSUE TITLE
Vet/update multi-region GKE (Google) Kubernetes tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5616]
Jesse Seldess (jseldess) commented:

- [ ] Update any problems found in following tutorial
- [ ] Improve explanations around DNS and multi-cloud complexities (ask Daniel for other topics)
- [ ] Change to use region-level instead of AZ-level clusters (relates to info below)
- [ ] Expand scaling guidance to cover scaling into a new region.
    - Our docs show how to [scale existing k8s clusters of a multi-region deployment](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#scale-the-cluster). But some users have asked about adding an entirely new region, which involves adding a new k8s cluster.
    - Spinning up a new k8s cluster should be similar to [these instructions](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#step-1-start-kubernetes-clusters). But we need to figure out how to get CockroachDB nodes running in that new cluster. It'll be different than the approach we take for the initial creation of the multi-region cluster via a `setup.py` config. 

---- 
Our multi-region GKE tutorial uses AZ-specific kubernetes clusters. Instead, we should use regional clusters, which is what CockroachCloud does. 

This was trigged by feedback from a user:

![Screen Shot 2019-10-14 at 5 27 57 PM](https://user-images.githubusercontent.com/15893490/66784301-09551c80-eea8-11e9-9aa6-a31ba23bae31.png)

Notes from @DuskEagle:

> There’s a couple of weird edges, that we might need to discuss.

> Like, in step 1, instead of running gcloud container clusters create cockroachdb1 --zone=<gce-zone>, we should run gcloud container clusters create cockroachdb1 --region=<gce-region> --num-nodes=1. This will actually create a 3 node cluster, not a 1 node cluster, because the num-nodes flag controls the amount of nodes per zone

> Our Kubernetes manifests also don’t support having different locality flags for pods running in different AZs in a regional cluster, which could affect the Geopartitioning story. We’ve solved that in Cockroach Cloud, but I should open an issue to fix that in the main CockroachDB repo

Also, @mattcrdb pointed out this related forum post: https://forum.cockroachlabs.com/t/instructions-for-multi-regional-deployment-on-regional-gke-kubernetes-cluster/3207

Jira Issue: DOC-343

**Comment by mdlinville** [comment]
No, this will be very out of date. I'm confused about how Exalate was even involved in this because there doesn't seem to be a JIRA.
