### ISSUE TITLE
document DDL features not support by IMPORT command

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#5623]
## Title

document DDL features not support by import command

## Description

https://www.cockroachlabs.com/docs/stable/import.html

## Outline

List DDL constraints that are not supported by the `IMPORT` command:

- [computed column](https://www.cockroachlabs.com/docs/stable/computed-columns.html)
- [default value constraints](https://www.cockroachlabs.com/docs/stable/default-value.html)

**Comment by jseldess** [comment]
As of 20.2, `IMPORT INTO` supports both computed columns and default values. `IMPORT` supports computed columns for Avro and Postgres dump files only, but that's called out in the docs: https://www.cockroachlabs.com/docs/stable/import.html#create-table
