### ISSUE TITLE
custom charts: metrics listing out of date

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#5624]
Irfan Sharif (irfansharif) commented:

Looking at our custom charts [page](https://www.cockroachlabs.com/docs/dev/admin-ui-custom-chart-debug-page.html), I notice a lot of the listed "Available Metrics" are out of date. For e.g. any and everything command queue related is no longer a thing (`replicas.commandqueue.combinedqueuesize`, `replicas.commandqueue.combinedreadcount`, etc.). That aside, other metrics also no longer exist, such as `txn.abandons`. 

To determine what exists and what doesn't, I was looking at the metrics I'm able to track on our custom charts page (`/debug/chart`).

Jira Issue: DOC-344

**Comment by irfansharif** [comment]
This also seems to be a thing for our prior releases. I only checked as far back as 19.1, but wouldn't be surprised if it's been around for longer (the command queue was removed ages ago).

**Comment by rmloveland** [comment]
bump
