### ISSUE TITLE
sql: provide documentation on row-level ttl workarounds 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5647]
We don't yet support [row-level TTL](https://github.com/cockroachdb/cockroach/issues/20239). This feature is useful in that it cuts down on the effort developers need to take to delete and manage data.

In the meantime, we should document workarounds such as using cron jobs to periodically delete certain data in a performance first manner. 

cc @rkruze who was asking about this.

**Comment by drewdeally** [comment]
@awoods187 any progression on this?

**Comment by awoods187** [comment]
We haven't prioritized the doc work here given the opportunity cost for other work. Do you want to make a case for increasing the prioritization?

**Comment by awoods187** [comment]
I'm making this p-1 and grouping it with various delete issues:
https://github.com/cockroachdb/docs/issues/5592
https://github.com/cockroachdb/docs/issues/4819
https://github.com/cockroachdb/docs/issues/4818

**Comment by awoods187** [comment]
Here's a customer ticket related to needing better recommendations around batch deleting https://cockroachdb.zendesk.com/agent/tickets/5882

**Comment by mgartner** [comment]
Some guidance on why and how to batch large writes would be great. For example, with Postgres you'd batch writes to avoid holding row-level locks on a huge number of rows for a long time, which would block other concurrent writes to those rows. By batching you reduce the max number of rows locked at any given time, and those locks are held for a shorter time-frame. I'm not sure if CRDB has similar behavior for large writes, but an explanation of this form would be great.

**Comment by jordanlewis** [comment]
Since @rohany's change that adds `crdb_internal_mvcc_timestamp`, we can recommend this pattern:

```
root@127.0.0.1:55288/defaultdb> delete from t where crdb_internal_mvcc_timestamp > 1597173188127148000.0000000000 LIMIT 10000;
```

**Comment by drewdeally** [comment]
Very nice
