### ISSUE TITLE
sql: break docs navigation into DML, DDL, etc. 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5650]
Our current docs navigation lumps together many different sql statements:
![image](https://user-images.githubusercontent.com/22278911/67107939-65b38700-f19b-11e9-8dae-ccc7a363ce4d.png)

We should consider grouping them in layers based on their types. For example, like this chart: 
https://www.geeksforgeeks.org/sql-ddl-dql-dml-dcl-tcl-commands/

**Comment by jseldess** [comment]
@awoods187, this would add too much hierarchy to the sidenav, in my opinion. The overview page already does what you're asking for, however: https://www.cockroachlabs.com/docs/stable/sql-statements.html

**Comment by vy-ton** [comment]
Should we close this? cc @ericharmeling
