### ISSUE TITLE
Implement inclusive open source community practices

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#5653]
In "Building a (Better) Open Source Community", Lisa Tagliaferri offers suggestions on how to create a more inclusive and equal open source repo.

Actionable items for CockroachDB docs:
- Add a contributors.md with a list of everybody who has contributed to our docs / running our docs
- Create a Code of Conduct
- Possibly review / rework the Contributing.md file and docs that help people get started

Notes:

Building a (Better) Open Source Community
Presented by Lisa Tagliaferri (Digital Ocean)

Good communities:
Inclusion
Equity

Bad communities:
Gatekeeping
Lack of mentoring
Bias

GitHub Repos:
10M in 2013
1000M in 2018

Open Source participation:
95% men
3% women
1% nonbinary
1% non-binary

Community-focused docs help create inclusion / equity (good thing we already do this!). Should include the following:
Read.me
Project summary, goals, install/dependencies
This might be the only doc people read. Make sure most important stuff is there!
Pytorch is a good example
Contributing.md
Guidelines, best practices, style
Jupyterlab is a good example
Contributors.md
Recognize contributors, incentivize engagement, ack people who might help/contribute outside of the repo
Ack people equally for both docs and code
This can be alphabetized by role, team, or name 
Code-of-conduct.md
Set expectations, reflect values
Drupal CoC, Geek Feminism CoC are good examples 
End-user docs
Tutorials, guides, FAQs, release notes, planned features

In general, make sure doc language is welcoming and unbiased
A11y compliant
Remember screen readers, country agnostic, no cultural expectations

Issue tracking
Should be concrete tasks
Include labels
Foster conversation / collaboration
Prioritize issues based on need and bandwidth

Code reviews should be iterative feedback
Show gratitude for newcomers
Give general and holistic feedback first
Use line-by-line comments
Avoid nits in the first reviews
Encourage multiple voices to empower community

Funding open source
Grant funding: Mozilla Grants, Sloan Foundation, Google Summer of Code, Python Software Foundation
Pitch impact, traction, value. State how funds will be used.

Hacktoberfest
4 PRS for GitHub public repos
`hacktoberfest` label

Misc. notes
Good first PRs: do_community/haiku
do.co/w4do - Teach others and grow as an author while supporting non-profit / charity

**Comment by aniketrb-github** [comment]
@lnhsingh 

I can provide a `CODE_OF_CONDUCT.md` template from the above-mentioned resource to start with which can be revised and corrected in the process. (Looking to contribute to the Hacktoberfest2020 event as well 😄 )
The required Code of Conduct can be adapted from any of the following: 
1) [Contributor Covenant - code of conduct ](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)
2) [Drupal - code of conduct ](https://www.drupal.org/dcoc) 
3) [Geek Feminism - code of conduct ](https://geekfeminismdotorg.wordpress.com/about/code-of-conduct/)
4) [Go Lang - code of conduct](https://golang.org/conduct)
Or any other more appropriate code of conduct guidelines.

**Comment by lnhsingh** [comment]
Hi @aniketrb-github, thank you for volunteering to take this issue! Since I filed this, we've actually developed a [Code of Conduct](https://www.cockroachlabs.com/slack-code-of-conduct) for our community slack channel that I think can also be repurposed here. Can you create a `CODE_OF_CONDUCT.md` file with this info? Most of the information should be the same-- the only difference is on the last bullet point. For our doc, it should be:

```
Finally, if you notice or are experiencing violations of this code of conduct or harassment of any kind, please reach out to @jseldess on GitHub or email docs[at]cockroachlabs.com to help resolve the situation.
```

**Comment by aniketrb-github** [comment]
sure @lnhsingh . I can tweak it as you've suggested. Thanks.
And, can we add a **`hacktoberfest`** label to this task? Just asking if it is doable. :D

**Comment by aniketrb-github** [comment]
Hi @lnhsingh 
Currently, for me, the [Citizen CoC link](http://citizencodeofconduct.org/) from [CockroachDB Community Slack CoC](https://www.cockroachlabs.com/slack-code-of-conduct) is not working/reachable.1
Can you please confirm this once and let me know if whether to exclude it or to keep it as is.
