### ISSUE TITLE
Updating the Nav and Footer for November 12 Launch Date

### ISSUE THREAD

**Issue by meagan-g** [cockroachdb/docs#5675]
Hey there,

For November 12, when we'll be launching 19.2 and Cockroach University, we have a few nav and footer changes planned for the marketing site. It would be great if we could add them to the docs site as well, so they go live on November 12.

Please let me or Jessica know if you have any questions. Thank you!

**Nav Bar**
1. Remove "Docs" from the nav bar

2. Add a new item called "Learn"

3. In a dropdown menu beneath Learn, add two items

-  Docs, which links to: https://www.cockroachlabs.com/docs/stable/

- Cockroach University, which links to: university.cockroachlabs.com

4. Remove "Training" from the dropdown menu "Resources"

5. Add "What's New in 19.2" to the "Products" dropdown menu underneath "Compare Products" 

- Link: https://www.cockroachlabs.com/blog/cockroachdb-19dot2-release/

6. Add "Sign In" on the nav bar to the immediate left of the "Get CockroachDB" button. It should be green text with an arrow on the right of the text. See the screenshot below for reference (note that in the screenshot, the text is black, but it will be green in real life, and the text says "login" but it will say "sign in" in real life)

<img width="1426" alt="Screen Shot 2019-11-02 at 4 40 38 PM" src="https://user-images.githubusercontent.com/52716054/68339755-2b127f80-00b3-11ea-9cf0-a41d338f4d7d.png">

- "Sign In" links to: cockroachlabs.cloud

- The arrow character is: &#8594;

- The text is the green color: #54B30E

7. Please add an "s" after "Product" in the nav, so it reads "Products"

**Footer**
1. Remove "Training" from the "resources" section

2. Remove "Docs" from the "resources" section

3. Add a new section above "Support Channels" with the header "learn" and the items "docs" and "university" underneath -- see below:

<img width="665" alt="Screen Shot 2019-10-23 at 12 10 05 PM" src="https://user-images.githubusercontent.com/52716054/67412990-57e07600-f58e-11e9-8fa5-6b0299022a5e.png">

cc @jseldess

**Comment by jseldess** [comment]
@meagan-g, @jess-edwards, should we also add "Slack" under "Support Channels" in the footer and maybe under "Resources" in the topnav?

**Comment by jess-edwards** [comment]
@jseldess I'm inquiring with Dan Kelly. Please hold.

**Comment by jess-edwards** [comment]
@jseldess 
Please add slack to the Footer under 
Support: 
Forum
Slack
Support Portal
Contact Us
