### ISSUE TITLE
Release links point to a 404

### ISSUE THREAD

**Issue by jeffreyroach** [cockroachdb/docs#5678]
On this page:
https://www.cockroachlabs.com/docs/stable

There are two links that are returning a 404 as they are missing the /docs/ slug.
- All Stable Releases https://www.cockroachlabs.com/releases/#production-releases
- All Testing Releases https://www.cockroachlabs.com/releases/#testing-releases

The links should be point to these two, respectively:
- All Stable Releases: https://www.cockroachlabs.com/docs/releases/#production-releases
- All Testing Releases: https://www.cockroachlabs.com/docs/releases/#testing-releases

**Comment by rmloveland** [comment]
Thanks for filing this @jeffreyroach !

@jseldess, I'm not sure how but apparently this busted link got past our CI tests.  It's broken on the 19.1 (stable) and 19.2 (dev) pages.

**Comment by rmloveland** [comment]
After inspecting the source of that page, I am seeing that it hasn't changed in a long time.  Here are the links in question in `v19.2/index.md`

```html
      <div class="landing-column-content">
        <p><a href="../releases/{{page.release_info.version}}.html">Latest Stable Release</a></p>
        <p><a href="../releases/#production-releases">All Stable Releases</a></p>
        <p><a href="../releases/#testing-releases">All Testing Releases</a></p>
        <p><a href="known-limitations.html">Known Limitations</a></p>
      </div>
```

Further info:
- Links work in a locally running Jekyll build
- Links work fine on older versions of the page (e.g., [2.1.8](https://www.cockroachlabs.com/docs/v2.1/))

Seems like a possible build / CI issue

**Comment by rmloveland** [comment]
@mjibson does this look familiar to you from having looked at some of our previous CI / build issues?

AFAICT by visual inspection of the Markdown / HTML, the working links on the 2.1 page and the broken links on the 19.1 page are both using the same text, i.e.

```html
        <p><a href="../releases/#production-releases">All Stable Releases</a></p>
        <p><a href="../releases/#testing-releases">All Testing Releases</a></p>
```

**Comment by jseldess** [comment]
As mentioned in Slack, this is getting passed our link checker on PRs because it's being considered an "external" link since it doesn't have `/docs` in the url. We have a nightly test to check external links, but it looks like that one has been failing for some reason. @mjibson, do you have any insight into why the nightly is failing to check external links? https://teamcity.cockroachdb.com/viewLog.html?buildId=1554237&buildTypeId=Internal_Docs_Nightly&tab=buildLog

I'll just fix these links on the docs home.

**Comment by jseldess** [comment]
Actually, these links seem to working now, which is very strange. Can someone else confirm?

**Comment by mjibson** [comment]
The links aren't working for me. I added a redirect for this at https://github.com/cockroachlabs/website-atrenet/commit/300191ec5e6d4415052f8c5cc25b508120c93cd0. Will test in a bit after it deploys.

**Comment by jseldess** [comment]
@mjibson, I see now that they work when on https://www.cockroachlabs.com/docs/stable/ but not when on https://www.cockroachlabs.com/docs/stable.

**Comment by mjibson** [comment]
All the links work for me now?

**Comment by jseldess** [comment]
Yeah, working for me, too. Thanks for adding that redirect. Couldn't we have added it to the redirects file in our repo, though?

**Comment by rmloveland** [comment]
Links are working for me now too (on both /stable and /dev).

OK to close this issue @jseldess?  Or best to wait? Don't want to interrupt the convo with Matt.

**Comment by mjibson** [comment]
No, adding it to this repo wouldn't have worked because the redirect needs to happen on /, not /docs.

**Comment by jseldess** [comment]
@mjibson fixed this with a redirect. Closing.
