### ISSUE TITLE
Add support for using CockroachDB with Python, Java, and Go to w3 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5682]
W3 shows examples for Python and MySQL or Python and MongoDB. https://www.w3schools.com/python/python_mysql_insert.asp

We should create this content and work with W3 to show it as well.

**Comment by jseldess** [comment]
@awoods187, this feels like something more for dev rel or marketing at this point. @Amruta-Ranade, do you have thoughts?

**Comment by Amruta-Ranade** [comment]
Yep! I can help with that!

**Comment by jseldess** [comment]
@Amruta-Ranade, I'll close this, but let me know if I should rather move it or recreate it somewhere for devrel.
