### ISSUE TITLE
Cockroach Cloud not found page copy

### ISSUE THREAD

**Issue by laurenbarker** [cockroachdb/docs#5684]
[Mocks](https://app.zeplin.io/project/5c3bf1d79ebc14be7741eae6/screen/5da9f2f66e02d7f112c9b3f0)

Right now the not found page is only displayed when the user is logged in and the route is invalid. The below are subject to change with the delete cluster feature that is currently being worked on.

**Deleted cluster:**
<img width="1551" alt="deleted-cluster" src="https://user-images.githubusercontent.com/7131985/67497707-5c6b6400-f64c-11e9-9f97-325362f1b9d1.png">

**Invalid cluster:**
<img width="1503" alt="invalid-cluster-uuid" src="https://user-images.githubusercontent.com/7131985/67497778-77d66f00-f64c-11e9-83a5-5e59df8185fa.png">

**Comment by Amruta-Ranade** [comment]
"We can't find the page you are looking for. You may have typed the wrong address or found a broken link."

Action:
"Go to Clusters page" (I am assuming we want them to go here; feel free to point to another page)
"Contact us" (links to Support page)"

**Comment by laurenbarker** [comment]
This is probably obvious... @Amruta-Ranade where is the support page?

**Comment by Amruta-Ranade** [comment]
Sorry..my bad..should have linked to it. Here you go: https://support.cockroachlabs.com/hc/en-us

**Comment by laurenbarker** [comment]
PR is up with current copy so I think this is good to close!
