### ISSUE TITLE
Add "breaking changes" page for release N vs. release N-1

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5685]
We should start explicitly documenting "breaking changes" that occur between a release N and the previous release N-1.

Users should have a simple way to see what existing integrations/scripts/etc. with the database may break or need to be updated from one release to the next.

This is related to but not the same thing as the "API Stability" work happening via https://github.com/cockroachdb/docs/pull/4326.  That work is conceptual whereas this is purely tactical: "give me one doc to look at so I know what is going to break."

To use a concrete example that prompted the filing of this issue, we have made changes to the permissions for how `CONFIGURE ZONE` statements work in 19.2, and it's getting added to our docs via https://github.com/cockroachdb/docs/pull/5609.

However, it's not clear that any other notification of this change for the average user will occur except via our release notes, and asking that users pore over release notes looking for things that would be breaking changes from their POV may be too much to ask, especially since we do not currently (AFAICT?) explicitly define or use that term anywhere (and in fact #4326 does not seem to do that either - at least I did not find the text "breaking change" anywhere in it).

**Comment by jseldess** [comment]
We always aggregate all breaking changes in a release in the GA release notes, e.g., https://www.cockroachlabs.com/docs/releases/v20.1.0.html#backward-incompatible-changes. I think that's sufficient for now, and we haven't heard any complaints about this. I think the bigger issues, as we know, is that we don't define what constitutes a breaking change. @rmloveland, please reopen if you feel strongly.
