### ISSUE TITLE
Change "datacenter" to "availability zone"

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#5686]
When talking about cloud topologies, we should say "availability zone" instead of "datacenter".

Docs that need to be changed:
- https://www.cockroachlabs.com/docs/dev/configure-replication-zones.html
- https://www.cockroachlabs.com/docs/dev/partitioning
- https://www.cockroachlabs.com/docs/v19.2/training/geo-partitioning.html
- etc.

**Comment by Shiwanee** [comment]
Hi @lnhsingh , I would like to take up this issue. Could you please assign it to me? 

Thanks,
Shiwanee

**Comment by Shiwanee** [comment]
@lnhsingh ,
I was doing some research for this issue and looks like we can use both the terms AZ and DC, but we will go ahead with AZ as most of the customers will be looking for it. (Ref: PR#4235)

Also, I see some pages in the documentation where we have some examples with DC attribute for the --locality flag. So, is it OK if I leave those instances as DC and replace others? or do you want me to update the examples and the relevant text?

Thanks,
Shiwanee

**Comment by aniketrb-github** [comment]
Hi @Amruta-Ranade @lnhsingh , Is this task available?
I would be glad to work on it. Do let me know.

**Comment by Amruta-Ranade** [comment]
I think @Shiwanee 's working on it.

**Comment by Shiwanee** [comment]
Yes, I am working on it @Amruta-Ranade, @aniketrb-github

**Comment by Shiwanee** [comment]
Hi @lnhsingh , do you have any inputs on this?

Reference: https://github.com/cockroachdb/docs/issues/5686#issuecomment-699150680

Thanks,
Shiwanee

**Comment by lnhsingh** [comment]
Hi @Shiwanee, sorry for the delay! I must've missed this in my inbox. We want to change the terminology from "datacenter" to "availability zone" when talking about cloud topologies (vs. on-premise), so you don't need to update every mention of "datacenter".

In the prose, "datacenter" should be replaced with "availability zone", but in the examples, please replace "datacenter" with "az" (e.g., `--locality=region=east,datacenter=us-east-2` should be `--locality=region=east,az=us-east-2`).

I did a quick audit of our docs and I think you should focus on updating mentions of "datacenter" on these pages:

- `partitioning.md`
- `configure-replication-zones.md`
- `cockroach-start.md` (note: I notice here that some of the examples have `zone=eu-west-1b`, so you can update the locality flag examples to match and say `zone=` instead of `az=`)

Also, you only need to update the v20.1 and v20.2 of these pages. Hope this helps! Let me know if you have any questions along the way and I promise to be more responsive :)

**Comment by Shiwanee** [comment]
@lnhsingh No problem at all :-)

I have created a PR #8765 to fix this issue.

Along with the three files you have mentioned some other files are also changed because of the links in these three files.

Please let me know your comments :-)

Thanks,
Shiwanee
