### ISSUE TITLE
Correct the command to move cockroach onto PATH 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#5697]
Re: [Install CockroachDB on Mac](https://cockroachlabs.com/docs//v19.1/install-cockroachdb-mac.html)

## Issue Description
This command `cp -i cockroach-v19.1.5.darwin-10.9-amd64/cockroach /usr/local/bin` actually names the `bin` `cockroach` if `/usr/local/bin` doesn't exist. Just tried it on a new mac

```
Nates-MacBook-Air:Looker nate$ /usr/local/bin
CockroachDB command-line interface and server.

Usage:
  cockroach [command]

Available Commands:
  start       start a node
  init        initialize a cluster
  cert        create ca, node, and client certs
  quit        drain and shutdown node
```

## Suggested Resolution 
make the one-liner robust enough to handle this case. Adding a trailing slash fixes this as far as I can tell, but there may be a better way
`cp -i cockroach-v19.1.5.darwin-10.9-amd64/cockroach /usr/local/bin/`

**Comment by jseldess** [comment]
Thanks for reporting, @nstewart.

@bdarnell, do you have tips here about how we should change the command?

**Comment by bdarnell** [comment]
Adding a trailing slash will prevent the (very confusing) outcome of the executable being named `bin`, but it will still fail with an error like `/usr/local/bin/` doesn't exist. Maybe that's enough, but to really make it work in this case we need instructions to do something like `sudo mkdir -p -m 755 /usr/local/bin` if it doesn't exist.

The same issue exists on linux, BTW.

**Comment by jseldess** [comment]
I think it's going to far to help people create `/usr/local/bin`. I'd prefer to just use the trailing slash.
