### ISSUE TITLE
copy: create cluster empty state

### ISSUE THREAD

**Issue by laurenbarker** [cockroachdb/docs#5709]
[Mock](https://app.zeplin.io/project/5d409f0c0c69c94bf6502fd1/screen/5d83a9b78a509e881f7806f1)

When a user creates a cluster they are taken to the [empty state](https://app.zeplin.io/project/5d409f0c0c69c94bf6502fd1/screen/5d83a9b78a509e881f7806f1) of the detail view. The user can return to the empty state page from the "All clusters" view by clicking on the related row.

<img width="1254" alt="clusters-all" src="https://user-images.githubusercontent.com/7131985/67687181-4ae8cb80-f96e-11e9-997b-f40378324fd0.png">

**Comment by Amruta-Ranade** [comment]
Closed via https://app.zeplin.io/project/5d409f0c0c69c94bf6502fd1/screen/5d83a9b78a509e881f7806f1
