### ISSUE TITLE
cli: clarify --insecure flag for all client commands

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#573]
Docs for client commands currently suggest that you need `--insecure` when connecting to a secure cluster. That's not true. 

`--insecure` is not necessary for any client commands. If connecting to an insecure cluster, don't pass cert flags. If connecting to a secure cluster, pass cert flags. 

Client commands to update:
- `quit`
- `sql`
- `zone`
- `node`
- `dump`
- `version`

**Comment by sploiselle** [comment]
Help text is:

> Run over non-encrypted (non-TLS) connections. This is strongly discouraged for production usage and this flag must be explicitly specified in order for the server to listen on an external address in insecure mode.

Need to research how this works with issuing commands to a remote server via `--host`

**Comment by jseldess** [comment]
Resolved this when `--insecure=false` became default.
