### ISSUE TITLE
CC: Adapt CRDB app tutorials for CC

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#5738]
From Cal Hacks event report: "The switch between CRDB and CC docs is frustrating and confusing. Users (hackers and our engineers) try to use CRDB dev tutorials for CC and get stuck on the certs part. I need to prioritize CC-specific and language-specific dev tutorials post-beta."

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4034](https://cockroachdb.zendesk.com/agent/tickets/4034) has been linked to this issue.

**Comment by mattcrdb** [comment]
Just ran into this problem with a customer, see above support ticket.

Solution for sequelize node.js ORM in the ticket.

cc @rmloveland for any input of his on this subject.

**Comment by Amruta-Ranade** [comment]
Plan:
Iteration 1: Add connection code snippets for each language to the "connect to your cluster" doc
Iteration 2: Adapt CRDB "hello world" apps for CC

**Comment by Amruta-Ranade** [comment]
Breaking this issue into smaller issues for better project management:

- [ ] Iteration 1: Add connection code snippets for each language to the "connect to your cluster" doc

- [ ] Adapt Django-CRDB app for CC
