### ISSUE TITLE
document 2020 cloud report repro steps

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5740]
@jseldess we would like to document the cloud repro steps separate from the blog post and report (and including links to this documentation). @pbardea and @nvanbenschoten have scripts as well as detailed steps that can be used to produce this information. 

We are targeting 12/9 for the report but it would be nice to have these docs done ahead of time so that we could share them out with others.

Could we do a collaboration project here where @pbardea @nvanbenschoten and I help docs to go through and update?

**Comment by awoods187** [comment]
@jseldess @nvanbenschoten also floated the idea of having a separate repo that has reproduction steps. Then we could have a docs page that links to the repo and explains what is there. This would shorten the complexity and work needed to document the cloud report.

**Comment by jseldess** [comment]
@awoods187, @nvanbenschoten, it's very hard for me to assess this work without more details. Can either of you point me to whatever we have internally as far as repro steps? I'm happy to collaborate on this, but if the instructions are going to be in our docs, I think a writer needs to be involved to ensure they're digestible and reproducible by non-experts.

**Comment by nvanbenschoten** [comment]
> if the instructions are going to be in our docs, I think a writer needs to be involved to ensure they're digestible and reproducible by non-experts.

I don't see a strong reason to put the reproduction steps in our docs, especially if it means shifting more work on to your team. I think it's more than sufficient for a project like this to have a standalone github repository with a small README.

**Comment by jseldess** [comment]
I don't mean to deflect this work from my team, cause I'm sure we can help, but I just don't understand the nature of this report and the repro steps. Can we talk through it briefly?

**Comment by awoods187** [comment]
Closing this since we are going with the repo approach
