### ISSUE TITLE
Update SHOW CREATE for 19.2

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5747]
The docs don't cover the fact that [`SHOW CREATE`](https://www.cockroachlabs.com/docs/dev/show-create.html) now includes partition definitions and replication zones.

**Comment by jseldess** [comment]
@ericharmeling, did this slip through the cracks somehow?

**Comment by ericharmeling** [comment]
I think this would be a duplicated effort, with #5293 and #5407 already closed.

**Comment by jseldess** [comment]
@ericharmeling, the reason I opened this issue is in the issue description:

> The docs don't cover the fact that SHOW CREATE now includes partition definitions and replication zones.

Do you not think we need to address this?

**Comment by ericharmeling** [comment]
We do cover this in several places:

- [`SHOW PARTITIONS`](https://www.cockroachlabs.com/docs/dev/show-partitions.html#examples)

> You can also use SHOW CREATE TABLE to view partitions on a table ...

- [`SHOW ZONE CONFIGURATIONS`](https://www.cockroachlabs.com/docs/dev/show-zone-configurations.html#view-the-replication-zone-for-a-table)

> You can also use SHOW CREATE TABLE to view zone configurations for a table...

- [`SHOW CREATE`](https://www.cockroachlabs.com/docs/dev/show-create.html#show-the-create-table-statement-for-a-table)

> SHOW CREATE TABLE also lists any partitions and zone configurations defined on primary and secondary indexes of a table....

We don't have an example on the SHOW CREATE TABLE page though. I can add one to close this issue.

**Comment by jseldess** [comment]
Ah, you're totally right. No action needed. Sorry for the confusion.
