### ISSUE TITLE
Clickable hyperlink area on major headings is too large

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#575]
On a bunch of our docs pages, the clickable link on a major heading within the page expands pretty far above the actual text of the heading. Normally this isn't a big deal, but on some pages that clickable area goes over top of the scroll bar of a code sample, making it very hard to scroll sideways within the code sample with a mouse.

For example, on https://www.cockroachlabs.com/docs/view-node-details.html#see-also, see this quick video of how my cursor stays focused on the link even while hovering over the scroll bar: https://goo.gl/photos/r8echbKwJPVkHjNC6

@jseldess

**Comment by a-robinson** [comment]
This is on OS X 10.11.5, Chrome 52.0.2743.116 (64-bit)

**Comment by sploiselle** [comment]
Noticed this as well. Part of the problem might also be the negative margins on some headers, but requires some digging to confirm.
