### ISSUE TITLE
Write an on-prem (Openshift) Kubernetes tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5752]
Jesse Seldess (jseldess) commented:

This is coming up as a requirement in the field. Not yet clear if Openshift is the focus or something else, and not yet certain this is a priority for Q4/20.1. Will revisit with the virtual Kubernetes team in coming weeks. 

Jira Issue: DOC-353

**Comment by taroface** [comment]
For reference: https://github.com/chriscasano/cockroach-openshift
