### ISSUE TITLE
Restructure docs ToC to be task-oriented, and to better fit reader personas

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#5767]
@awoods187 and I discussed making some larger changes to the ToC, to better guide readers, loosely based on tasks and reader personas.

-----
## Get Started
- Overview
- Install Cockroach
- etc.
- Tutorials
- Troubleshoot
## Develop
- Overview
- Languages
- 3rd-party Tools
- Debug
- Tutorials
- Best Practices
## Deploy
- Overview
- Topology Patterns
- etc.
- Tutorials
- Troubleshoot
## Administer
- Overview
- Set Permissions
- etc.
- Tutorials
- Troubleshoot
## Migrate
- Overview
- Migrate from ...
- etc.
- Tutorials
- Troubleshoot
## Reference
- Overview
- CLI
- SQL
- etc.
## Learn
- Architecture
- etc.
## Releases

----- 

This is very much a WIP issue, open for discussion.

**Comment by awoods187** [comment]
I'm excited for this work! Happy to help however I can.

**Comment by jseldess** [comment]
Nice, @ericharmeling. Really like this experiment. Feel free to prototype in a PR.

**Comment by jseldess** [comment]
One thing I didn't share when we discussed in our team meeting: I think each top-level section should be heavily task-oriented. So in addition an overview and tutorials, the majority of topics should be <do this>, <do that>. Similar to how Get Started currently works: `Install CockroachDB`, `Start a Local Cluster`, `Learn CockroachDB SQL`, etc. 

For the Develop section in particular, which is a particular focus for Q4/Q1, this is a crucial aspect. Topics like `Query Data`, `Filter and Sort Data`, `Paginate Results`, `Insert Data`, etc.

**Comment by awoods187** [comment]
+1 @jseldess I think a good framing question is: "how do I do X?"

**Comment by jseldess** [comment]
Long-term, the task-based topics can also offer language variations, to be really dev friendly: https://rethinkdb.com/docs/cookbook/python/

**Comment by jseldess** [comment]
Closing this in favor of the docs UX redesign project being lead by @luciaaa and @lnhsingh.
