### ISSUE TITLE
Add information on connection pooling for Go - pq 

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#5769]
## Description
Opening new connections can be pretty expensive when running on a secure cluster with passwords. We should recommend that people set https://golang.org/pkg/database/sql/#DB.SetMaxIdleConn to something higher than 2. Ideally, this should be something like 100, as keeping connections open is not expensive.

**Comment by ericharmeling** [comment]
Related to #9033.

**Comment by vy-ton** [comment]
@ericharmeling Since we are deemphasizing lib/pq , should we close this? We have the pgxpool connection example.

**Comment by ericharmeling** [comment]
> should we close this?

Yes. Thanks!
