### ISSUE TITLE
Cockroachcloud: updating hardware per node copy

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#5770]
We should update the node selection copy to : 

1. remove where we say contact us if you want to change node size. since its just two compute options, i dont expect many people to want to change. 
2. add that if they want different hardware configs than whats here, contact us 
3. we can still link to perf docs but unsure how you want to frame that - maybe as is?

**Comment by Amruta-Ranade** [comment]
I think they still might need to change node size if their storage requirements change or they select the wrong option while creating the cluster. So I'd want to retain that line. 

here's the new copy suggestion: 
"The choice of hardware per node depends on the amount of unreplicated data you need to store. To change the hardware configuration after the cluster is created, you will have to contact us. To learn more about selecting the right hardware configuration, see [link]."
