### ISSUE TITLE
CC: Existing user sign up email

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/docs#5771]
To resolve https://github.com/cockroachlabs/managed-service/issues/1419, CockroachCloud will send an email to existing users when their email us used to sign up. I need some help with the copy of this email. The email will use our standard _Call to action_ email template that looks like this ...

![Screen Shot 2019-11-01 at 15 34 51](https://user-images.githubusercontent.com/397448/68052907-130cbb80-fcc1-11e9-84fd-1514b00ffafe.png)
![Screen Shot 2019-11-01 at 15 34 57](https://user-images.githubusercontent.com/397448/68052924-186a0600-fcc1-11e9-8ad8-da60eb5c776d.png)

The copy is broken down as thus,
- Email Subject (_You already have an account_)
- Heading (_You can't sign up twice_)
- Subtext (_You are recieving this email ..._)
- Call to action (_Login now_)

**Comment by Amruta-Ranade** [comment]
I wonder if we need to send them an "account already exists" email. We can send them the "sign in to your account" email instead. (I am assuming we have a sign in to your acct email -- I remember reviewing it a while ago, but don't know if it is still a part of the workflow. LMK if it isn't and I can help you draft one).

**Comment by nathanstilwell** [comment]
The only email I see currently generated by CockroachCloud are,
- _"You have been invited to join [Org Name] on CockroachCloud"_
- _"Reset your password for CockroachCloud"_
- _"Verify your CockroachCloud account"_

Perhaps there may have been another mock that never got created. None of the above feel quite right for this scenario.

**Comment by Amruta-Ranade** [comment]
Ahh..okay. Here's the suggested text:

Email Subject: Security alert: Account creation
Heading: Someone tried to create a new account with this email
Subtext: An account with this email already exists. Someone tried to create a new account with this email. If that was you, sign in to your existing account. 
Call to action 1 (Login now): Sign In
Call to action 2: Reset password

cc @rolandcrosby @kannanlakshmi 
Does this look okay/make sense?

**Comment by rolandcrosby** [comment]
Sounds fine to me. @Amruta-Ranade one consideration: the user specifies the name of an org to create at the time they sign up. Do you think we need to mention that we didn't create the requested org, or is that obvious from the fact that we didn't create the account?

**Comment by Amruta-Ranade** [comment]
I want to say it is clear (since we say sign into your existing account), but I am open to being more specific.

How about this:
"Someone tried to create a new account with this email, but the request was denied since an account with this email already exists. If that was you, sign in to your existing account."
