### ISSUE TITLE
Cockroachcloud FAQs update : add question on backup

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#5773]
One question we've been asked a few times is:
I have a self hosted CRDB cluster, can you please restore this to CC? 
A user can do this themselves today and don't need any CC specific help. But this seems to trip up our users. We should add this to the FAQs and specify that they need a cloud bucket such as s3. 

cc @rolandcrosby

**Comment by kannanlakshmi** [comment]
@Amruta-Ranade Not sure if this is FAQ only or requires a separate section but we really should provide guidance around how to restore CC. See thread here for soe relevant convo https://cockroachlabs.slack.com/archives/C21PV4PD1/p1573057086002600

**Comment by kannanlakshmi** [comment]
also @mberhault has opinions on what we should guide / document, so I'd get his input too.

**Comment by Amruta-Ranade** [comment]
Yep..I realized that the FAQ isn't enough and opened an issue to add a separate section: https://github.com/cockroachdb/docs/issues/5788

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/5824
