### ISSUE TITLE
SAVEPOINT Doc Update 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#5786]
Re: [SAVEPOINT](https://cockroachlabs.com/docs//v19.1/savepoint.html)

This page should state that, when `savepoint cockroach_restart` is used, a future `release savepoint cockroach_restart` is a *commit* - i.e. the only thing that can follow it is a `commit` statement (which is a no-op), and rolling back afterwards is not possible. All of this is not compatible with Postgres.

**Comment by awoods187** [comment]
Closing as out of date.
