### ISSUE TITLE
Core changefeeds: clarify that multiple tables can be watched

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#5806]
A user of the `experimental changefeed` statement pointed out that our documentation doesn't clearly indicate that multiple tables can be watched by a single core changefeed. We should clarify this in the documentation and perhaps include an example.

**Comment by jseldess** [comment]
Thanks, @rolandcrosby. I think core changefeed is actually one of the primary candidates for a dev tutorial in Q4, so this is helpful.

**Comment by jseldess** [comment]
@lnhsingh, @mwang1026, is this still a docs need?

**Comment by mwang1026** [comment]
It's still relevant and it's a small enough change. We can bundle this into our next "CDC updated" bundle.
