### ISSUE TITLE
Document how we test CRDB

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5807]
Andy Woods (awoods187) commented:

Some other databases (https://www.sqlite.org/testing.html) have a specific page that outlines how they are tested. We should create a docs page that explains our test strategy to help developers and dbas have confidence that CRDB is well tested. cc @isaactwong @jordanlewis 

Jira Issue: DOC-363

**Comment by jseldess** [comment]
@taroface, something to consider with @johnrk.
