### ISSUE TITLE
CC: Update screenshots

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#5808]
Need to add/update screenshots throughout CC docs.

**Comment by laurenbarker** [comment]
https://github.com/cockroachlabs/managed-service/issues/1614 removes the confirm password field on the add sql user modal.

**Comment by laurenbarker** [comment]
@Amruta-Ranade the changes to the sql user modal are on staging now. A lot of the staging clusters where deleted last week though (will just error when you click on the sql user tab) so you might need to create a new test cluster to see the modal changes.

**Comment by Amruta-Ranade** [comment]
Fixed in #6523
