### ISSUE TITLE
cockroachcloud number of node selection

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#5817]
Right now the number of node selection for CC goes from 1 to 3 i.e., there is no 2. We know why we did this bc two doesn't actually give you any more resiliency than one. But as a user esp a new one, this is confusing. Let's add this as an FAQ or under create cluster doc - why we do 1 and then 3+

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/5680
