### ISSUE TITLE
Docs landing page and sidebar have fallen out of sync

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#5839]
There’s a mismatch between the listing in the side bar and the listing on the landing page (“Performance” for e.g. is missing, and there are others). This has bitten me before, and I only knew to check because I remember seeing the performance page specifically before. I believe this applies to all previous releases as well.

![image](https://user-images.githubusercontent.com/10536690/68704456-56391b00-055a-11ea-8932-b6596910c4ee.png)

**Comment by awoods187** [comment]
I was looking at it this morning to make a pr but couldn't figure out which page to update. @jseldess would you mind showing me or adding this in? I don't think people are finding the performance page as easily as they could
