### ISSUE TITLE
Node.js cockroachdb package is out of date

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5843]
We received this feedback via the Cockroach University slack. The Node.js build an app tutorial leverages this [CockroachDB Node.js package](https://github.com/cockroachdb/sequelize-cockroachdb) to account for some minor differences between CockroachDB and PostgreSQL. However, it's based on an older version of Sequelize. We should update and revisit this the package and tutorial.

**Comment by intech** [comment]
I am that person from slack and am ready to answer questions and help with node.js

**Comment by jseldess** [comment]
@intech, would you be willing to speak to us via phone about the trouble you had an the work you've done? If so, please shoot me an email at jesse@cockroachlabs.com and I'll set something up with some relevant folks on our end.

**Comment by intech** [comment]
> @intech, would you be willing to speak to us via phone about the trouble you had an the work you've done? If so, please shoot me an email at [jesse@cockroachlabs.com](mailto:jesse@cockroachlabs.com) and I'll set something up with some relevant folks on our end.

Better text, I have bad English for phone calls.

**Comment by jseldess** [comment]
Thanks, @intech. I'll reach out soon.

**Comment by jseldess** [comment]
More details from our Slack conversation:
> I want to make the maximum compatibility with postgres, but the implementation of some things in sequelize is simply not designed for the distributed cockroachdb architecture, and we still have to figure out how to do all this correctly and conveniently.

**Comment by awoods187** [comment]
cc @vy-ton this basically covers the sequelize work

**Comment by vy-ton** [comment]
Closing this in favor of https://github.com/cockroachdb/docs/issues/8440#issuecomment-839351732
