### ISSUE TITLE
Range merges page should offer more explicit guidance to users

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5846]
The [Range Merges][merge] page tells me that this feature exists, and why it's good.  However it also tells me how to turn it off, but without making it clear why I should ever do that?  Based on reading the page, merging ranges is only ever good.

Estimated scope of work for this issue:

- Small option (quick & dirty): We should update this page to provide guidance to users about whether they should ever mess with this, or perhaps a note saying "you probably shouldn't touch this" (my guess is 99% should never touch this, and only then if on the advice of CRL support/engineering)
- Large option (slower but better): This information should live on the [Distribution Layer][dist] page in the architecture docs.  It should probably be a new section following **Range Splits**.  The cluster setting should probably not be mentioned.  The separate "Range Merges" page should be deleted.

[merge]: https://www.cockroachlabs.com/docs/v19.2/range-merges.html
[dist]: https://www.cockroachlabs.com/docs/stable/architecture/distribution-layer.html

**Comment by rmloveland** [comment]
@bdarnell I have questions re: the range merge cluster setting:

1. Other than in 19.1 where you still have to [turn off range merging to do manual splits](https://github.com/cockroachdb/docs/pull/5642) is there any reason why a user should disable the range merge setting in 19.2+?

2. Related to the above, does disabling range merges fall into the category of "cluster settings most users should not be changing"?  (Except when working with CRL support/engineering perhaps?)

**Comment by bdarnell** [comment]
There are no known reasons why a user would want to turn off range merges in 19.2. (Hypothetically if we discovered a horrible bug in range merges this setting would give us a quick way out but now that merges have been stable for several releases this is unlikely). 

Most users should not be changing this setting (this is true of most settings!). We should probably deprecate and remove it.

> Large option (slower but better): This information should live on the Distribution Layer page in the architecture docs. It should probably be a new section following Range Splits. The cluster setting should probably not be mentioned. The separate "Range Merges" page should be deleted.

Agreed.

**Comment by jseldess** [comment]
Totally agree with this, too, Rich. Thank you!
