### ISSUE TITLE
search: Not seeing "SQL tuning with EXPLAIN" when I search for "performance"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#5847]
If I [search for 'performance'][search] I do not see the (new?) [SQL tuning with EXPLAIN][tuning] in the first page of results.

(Note: today is Wednesday, November 13, 2019)

[search]: https://www.cockroachlabs.com/docs/search.html?q=performance
[tuning]: https://www.cockroachlabs.com/docs/v19.2/sql-tuning-with-explain.html

**Comment by rmloveland** [comment]
cc @lhirata for appropriate labelling etc.

**Comment by jseldess** [comment]
Should we retitle this to `SQL Performance Tuning with EXPLAIN`, use "performance" a few times on the page, and include it as a meta keyword?

**Comment by rmloveland** [comment]
> Should we retitle this to SQL Performance Tuning with EXPLAIN, use "performance" a few times on the page, and include it as a meta keyword?

IDK - I assume you and Lauren know more than I do about whether those actions would help Algolia out (presumably yes?).  I defer to your knowledge. FWIW the term "performance" appears in the text of the page a few times.

**Comment by jseldess** [comment]
Yeah, you're right it's there, but those few instances aren't enough given the other results pretty much all have "Performance" in their titles. We'll definitely be able to tweak this once we upgrade algolia. For now, we should make other general changes to influence this, also on Google.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5852, which is broader.
