### ISSUE TITLE
billing invoice email change 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#5855]
Currently we ask for the billing email address as part of the credit card process. This is the email that gets invoices. Anyone can change this -- you can also enter an email that's not your email. So I can create a cluster using my credit card but put in vilterp@cockroachlabs.com. This is all quite confusing. 

The new proposal: 
We use the default email of the person who created the org to be the billing email instead of asking for this as part of the billing process. 

Docs change: 
We should document in our billing docs (think link below) that if they want to change this email (ie change who gets invoices) they should go to the billing tab. Let's wait on Joe or Chris to confirm that they've built this before changing current docs though.

https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-create-your-cluster.html#step-6-enter-your-billing-details

**Comment by Amruta-Ranade** [comment]
Addressed in https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-console-access-management.html#manage-billing-for-the-organization
