### ISSUE TITLE
Edit CDC examples

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#5861]
https://www.cockroachlabs.com/docs/stable/change-data-capture#create-a-changefeed-connected-to-kafka

Tim V: i'd like to create a standard java library that easily converts CDC responses into java objects.  This is generally pretty simple and common stuff.  the problem i'm having is that our basic json message doesn't seem to me to be proper JSON and thus, makes this much more complex to deal with.  for example we emit something like [1] {"after": {"id": 1, "name": "Petee"}} but standard parsers treat this string as invalid because it starts with [1] instead of the traditional { to start a json object.  furthermore after is both a key and value here which makes things difficult.  what about a format that looks more like this {"keys": [1], "value": {"type":"after","content":{"id": 1, "name": "Petee"}}}

Our usage examples have `property print.key=true`, which prints both the key and value, which are separate fields. If you remove that flag, the changefeed will only print the value.

Dan says he'd be okay with simply removing the `--property print.key=true` from our examples and updating the output to match 

Roland: note that examples of deletes get really confusing if you omit keys

**Comment by lhirata** [comment]
Roland: there's also a key.separator property, so i think you could set that to an arbitrary string to make it more explicit (silly example:  --property print.key=true --property key.separator='<--- key / value --->' )
Dan: looks like CHANGEFEED FOR is already okay, we use commas there between them
Roland: yeah in that case we're just writing our usual table output
Dan: could just use a comma as key.separator?
Roland: ya, the main thing is you need to make it clear that it's two json values, not one weird one
