### ISSUE TITLE
Known limitation: cannot add sequence-based columns to existing table, + risk of XXA00 error

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#5867]
See this issue: https://github.com/cockroachdb/cockroach/issues/42508

cc @rmloveland

**Comment by jseldess** [comment]
This known limitation was document some time ago, based on an issue that was meanwhile closed as duplicate: https://github.com/cockroachdb/cockroach/issues/22508.

**Comment by jseldess** [comment]
Need to confirm that the language is still correct and sufficient. Doing as part of https://github.com/cockroachdb/docs/issues/6835.
