### ISSUE TITLE
Vulnerability disclosure process

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#587]
It has become common practice and expected that any open source software meant to run on a network explain their vulnerability disclosure process to users in their public-facing documentation.

This is the part of the docs where someone who found a security bug in the product can learn how they can best report this. Obviously in many cases a security bug cannot be filed in a public forum like the Github issue tracker, so another communication channel must be created with indications on how to use it. This should also state how long the reporter of an issue has to wait for the vendor to fix it before they announce the bug to the public themselves.

Some examples:
- Apache: https://www.apache.org/security/
- PostgreSQL: https://www.postgresql.org/support/security/
- EFF: https://www.eff.org/security
- Firefox/Mozilla: https://www.mozilla.org/en-US/about/governance/policies/security-group/bugs/
- Oracle: https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html
- Mongo: https://www.mongodb.com/security?jmp=footer

(Requested by @fuzzie)

**Comment by jseldess** [comment]
Thanks for adding this, @knz. I'll follow your thread with the team.

**Comment by bdarnell** [comment]
We had one (at cockroachlabs.com/security/), but it looks like it got lost in a website redesign. The page is still there in WP but marked as a draft. @jess-edwards?

**Comment by jseldess** [comment]
Assigning to @jess-edwards, who want to think about a rewrite and where to publish (footer of main site or docs).

**Comment by jseldess** [comment]
@jess-edwards, any updates here?

**Comment by jess-edwards** [comment]
@jseldess Sent to Peter, Spencer, and Ben for final review.

**Comment by jseldess** [comment]
Great, @jess-edwards. Please just close this once that page is live.

**Comment by jess-edwards** [comment]
@jseldess @knz This page is now live. Edits can of course be made. 

https://www.cockroachlabs.com/security/

**Comment by knz** [comment]
Guys this page is excellent. I'm glad to see what is has become!
Congrats to you all.

-- 
Raphael 'kena' Poss

**Comment by jseldess** [comment]
Nice, @jess-edwards. When are we planning to update the "PGP key" link?

**Comment by jseldess** [comment]
@jess-edwards, I just noticed that email signup is rendering incorrectly. Scroll all the way to the bottom of the page, and you should see:

<img width="1280" alt="screen shot 2016-11-04 at 11 57 37 pm" src="https://cloud.githubusercontent.com/assets/15893490/20027413/85aeed2c-a2ea-11e6-9a93-291695cc3655.png">

**Comment by jess-edwards** [comment]
@jseldess 

I'm actually not sure how to properly put the PGP key link in. I've got it - it's quite a long string (8+ lines). Ideas on how to properly add it? 

The website footer (newsletter form, docs feedback widget) are working just fine in Safari, but they're broken in Chrome. Seems like it's HubSpot that's at fault. I don't have any other browsers that I can check on, so I can't verify whether the website is appearing OK on Firefox and IE.

**Comment by knz** [comment]
The PGP key is meant to be delivered to users as an independent text files.
So put the text of it in a .txt file somewhere and give a link to this text file in the security page.

**Comment by jess-edwards** [comment]
@knz Fixed!
