### ISSUE TITLE
How to check network latency

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5870]
The network latency debug page is very valuable, and we need to feature it in our docs. This is long-overdue.

**Comment by taroface** [comment]
@taroface to follow up with @piyush-singh

**Comment by taroface** [comment]
- Add a Network Latency article explaining the Admin UI page
- Link to Network Latency from relevant articles (e.g. Performance, Topology Patterns, Performance Tuning, Follower Reads)
