### ISSUE TITLE
Upgrading from 19.1 to 19.2 using homebrew doesn't work

### ISSUE THREAD

**Issue by kenliu** [cockroachdb/docs#5873]
I tried to upgrade from 19.1 to 19.2 on my machine using `brew cask upgrade` and nothing happened with the `cockroach` installation. I believe this might be because we moved from the central brew cask to our own tap. I wound up fixing this by running `brew uninstall cockroach` and then `brew install cockroachdb/tap/cockroach`

We may need to patch our Mac install instructions to make it clear when upgrading that you have to use the new tap.

I'm not able to reproduce this on my laptop since I am not able to reinstall 19.2 from homebrew since it was [removed from homebrew-core](https://github.com/Homebrew/homebrew-core/pull/46660) as part of the new licensing.

cc @bdarnell

**Comment by jseldess** [comment]
@bdarnell, do you have a sense of how that note at the end of the homebrew section should be updated? https://www.cockroachlabs.com/docs/stable/install-cockroachdb-mac.html#use-homebrew-1

**Comment by bdarnell** [comment]
I thought I had tested this upgrade and it worked, but now it's too late for me to test again. If anyone is in a position to test this and can tell me exactly how it failed I might be able to do something about it but we should probably just update the docs:

"If you installed CockroachDB via Homebrew before version 19.2.0, run `brew uninstall cockroach` before installing the new version. If you previously installed using a different method, you may need to remove the binary before installing via Homebrew."
