### ISSUE TITLE
import: add an example of DELIMITED with escaping

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#5895]
We ran into an input file like this today, with `|` characters as delimiters, and `\|` representing a literal `|`:

```
k1|v1
k2|v2
k3\|k3|v3
k4|v4\|\|\|v4
```

The proper way to import this is something like:
`import table kv (k string primary key, v string) delimited data ('nodelocal:///thing.psv') with fields_terminated_by='|', fields_escaped_by='\';`. It's possible to piece this together from the documentation of `delimited`, but we should at least include one example of how this works.

**Comment by jseldess** [comment]
@rolandcrosby, for i/o topics, please assign directly to @lnhsingh.
