### ISSUE TITLE
sql: fix sub-second EXTRACT behaves differently from postgres

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5903]
PR: https://github.com/cockroachdb/cockroach/pull/41069

From release notes:
> The `extract()` [built-in function](../v20.1/functions-and-operators.html) with sub-second arguments (millisecond, microsecond) is now Postgres-compatible, and will return the total number of seconds in addition to sub-seconds. Anyone who was previously relying on `extract()` to return only sub-second data will need to adjust their applications. [#41069][#41069] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
As of https://github.com/cockroachdb/docs/pull/6470, all 20.1 function tables are up-to-date. 

The PR for this was a bug fix that I don't think needs to be documented. Please re-open if you disagree.
