### ISSUE TITLE
sql: no longer require CASCADE for dropping a unique index created explicitly

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5914]
PR: https://github.com/cockroachdb/cockroach/pull/42001

From release notes:
> Dropping a unique index that was created via `CREATE UNIQUE INDEX` statement no longer requires the `CASCADE` option. [#42001][#42001] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/6106. (Related to 19.2 backport https://github.com/cockroachdb/docs/issues/5916).
