### ISSUE TITLE
Copy changes for cockroachcloud

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#5919]
From Nate's UX feedback on CC: 

-- For "Regions & nodes" in the "Create cluster page" the copy is not clear. In particular, we introduce single v multi region here but users probably will not know what that is. 
"You may create a one node cluster" -- what does this mean? Maybe this should talk about # of nodes rather than region. And then keep a sentence about multi-region. 

--S/M/ L naming convention seems to be based on disk alone which is weird. Note that once we get rid of the third option for beta, this won't be an issue. https://github.com/cockroachlabs/managed-service/issues/1732 

--Suggested change copy of adding SQL user to be "Add SQL user" rather than just "Add user" 
https://github.com/cockroachlabs/managed-service/issues/1741 This is an FYI for you Amruta, no specific action required unless you have some ideas to make this clearer. 

--Network type language https://github.com/cockroachlabs/managed-service/issues/1742 
This needs new language. What are we permissioning exactly? 

@Amruta-Ranade when these are done, can you let Jeremy / FE know? Not sure the best to track these.

**Comment by Amruta-Ranade** [comment]
Copy changes for "Regions & Nodes":
- First bullet point: Change "For single-region application development and testing, you may create a one-node cluster." to "For application development and testing, you may create a one-node cluster."
- Second bullet point: Change "For single-region production deployments, we recommend a minimum of three nodes." to "For production deployments, we recommend a minimum of three nodes."
- Keep third bullet point as it is.
- Fourth bullet point: Change "If you don't see the region you are looking for, look here." to "If you don't see the region you are looking for, see [this FAQ](https://www.cockroachlabs.com/docs/cockroachcloud/dev/cockroachcloud-frequently-asked-questions.html#why-cant-i-use-certain-regions-in-aws-and-gcp)."
