### ISSUE TITLE
Update performance docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5920]
As discussed with @rmloveland, @awoods187, @bdarnell, and @jaymce, we should:

- [ ] Edit performance landing page, toning down certain bold claims.
- [ ] Edit the benchmarking instructions. Ideas discussed:
    - In sidenav, rename from "Benchmarking Instructions" to something more explicit, and less generally applicable, like "TPC-C Benchmarking in AWS". Also probably move to bottom of Performance section.  
    - Don't use `workload.LATEST`. Ideally use `cockroach workload`.
    - Justify/explain special cluster configurations. Figure out if they're more broadly applicable, and, if so, document them as such. 

Later: Identify and document data size per node production limit.

**Comment by jseldess** [comment]
@nathanstilwell, @ajwerner, about the "Later" above, based on the discussion with @bdarnell, it sounds like the current maximum data size per node is 1-2TB. Is that your current understanding? Are you comfortable with us documenting this limit? I think it would be helpful to users and especially our field colleagues because you can figure out scale with this in mind. Of course, when this max data size per node changes, we would change the docs as well.

**Comment by nvanbenschoten** [comment]
> Is that your current understanding? Are you comfortable with us documenting this limit?

Yes, given the limits of our testing, I don't think we'd want to encourage anyone to push much past this at the moment. Hopefully, we can make significant strides in the next release.

**Comment by jseldess** [comment]
Thanks, @nvanbenschoten. So should we say max `1TB`, `2TB`, or `1-2TB` per node? This is given the default range size, right? How does this change if users manually increase or decrease that?

**Comment by nvanbenschoten** [comment]
Yes, we should say 2TB. This is based on the default range size and it's probably pretty harmless to change that to something like 128MB to double the system capacity, but I don't think we should advertise this because it's not something we test.

**Comment by jseldess** [comment]
@rmloveland, given your current work on the benchmarking and performance pages, I'll close this.
