### ISSUE TITLE
cli: guidance on the setting --max-sql-memory flag 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#5923]
Exalate commented:

## Title

guidance on the setting --max-sql-memory flag 

## Description

Current [recommendation](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#cache-and-sql-memory-size) for `--max-sql-memory` is 25% or RAM minimum, but `--cache + --max-sql-memory` should be less than equal to 75%.   An empirical guidance can help balance amount of [disk spill](https://www.cockroachlabs.com/docs/v19.2/vectorized-execution.html). 

## Outline

Adding up the below can show how much of `--max-sql-memory` is used.  

```
sql_mem_admin_current
sql_mem_admin_session_current
sql_mem_admin_txn_current
sql_mem_bulk_current
sql_mem_conns_current
sql_mem_conns_session_current
sql_mem_conns_txn_current
sql_mem_distsql_current
sql_mem_internal_current
sql_mem_internal_session_current
sql_mem_internal_txn_current
sql_mem_sql_current
sql_mem_sql_session_current
sql_mem_sql_txn_current
```

## Expected Audience

Jira Issue: DOC-373

**Comment by robert-s-lee** [comment]
All of the variable in [Custom Chart](http://localhost:26258/#/debug/chart?charts=%5B%7B%22metrics%22%3A%5B%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.admin.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.admin.session.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.admin.txn.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.bulk.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.conns.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.conns.session.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.conns.txn.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.distsql.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.internal.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.internal.session.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.internal.txn.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.sql.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.sql.session.current%22%7D%2C%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.sql.txn.current%22%7D%5D%2C%22axisUnits%22%3A0%7D%5D)

**Comment by jseldess** [comment]
cc @taroface, @piyush-singh. Not sure if/how our thinking has evolved on memory flags. See https://github.com/cockroachdb/docs/issues/5924 as well.
