### ISSUE TITLE
cloud docs reference Postgres ORM and not CockroachDB 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5926]
```
The Parameters tab is displayed by default. You can use the parameters to connect to the cluster using a Postgres driver such as the psycopg2 driver.
```

```
Click Connection String to view the application connection string. You can use the application connection string to connect to the cluster using a Postgres ORM such as the SQLAlchemy ORM.
```

https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html

**Comment by Amruta-Ranade** [comment]
I think it should be Postgres driver and ORM, right? The Build an App docs say "..PostgreSQL-compatible driver or ORM."

**Comment by awoods187** [comment]
Well we now have some CockroachDB dialects. Perhaps we could say `CockroachDB compatible Postgres driver` or `CockroachDB compatible Postgres ORM` ?

Maybe its too premature since we only have a few examples but many more are in progress. I just want to highlight the CRDB nature. What do you think?

**Comment by Amruta-Ranade** [comment]
I would prefer to wait until we have more I think. IIUC, they can't use CRDB dialects just yet, so we need to give them info about what they can use.
