### ISSUE TITLE
"Build a test app" horizontal scroll bar won't work

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/docs#593]
https://www.cockroachlabs.com/docs/build-a-test-app.html#step-3-execute-basic-statements-from-a-client

The pane with the CREATE TABLE command won't scroll if you click on the horizontal scroll bar.

**Comment by jseldess** [comment]
Thanks for reporting, @nictuku. Looks like we need to improve styling of code blocks in other ways as well. For example, a single line wraps in firefox, whereas it doesn't in safari.

**Comment by jseldess** [comment]
Just realized that I can get that horizontal scroll bar to work, but it's not easy because the scroll bar disappears quickly.

**Comment by jseldess** [comment]
Scrolling seems to work fine on all major browser in the meantime, so closing this issue.
