### ISSUE TITLE
Enterprise Trial –– Get Started Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#5934]
Artem Ervits (dbist) commented:

Re: [Enterprise Trial –– Get Started](https://cockroachlabs.com/docs//v19.2/get-started-with-enterprise-trial.html)

## Issue Description
There's no mention of Community Slack and/or Cockroach University on this page.
## Suggested Resolution 
Add Slack Channel

**Comment by jseldess** [comment]
@meagan-g, are we sending trial users to this page still?
