### ISSUE TITLE
Network diagnostic debugging

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5942]
Andy Woods (awoods187) commented:

We met with a customer today as described in https://github.com/cockroachdb/cockroach/issues/42788 and https://github.com/cockroachdb/cockroach/issues/42790

The customer was seeking guidance on how to debug a network partition in a multi-region Kubernetes cluster. We likely need an example and generic steps for how to debug these types of problems. 

- What logs should they look at?
- What admin ui pages?
- How do they discover more information?

Jira Issue: DOC-378

**Comment by awoods187** [comment]
cc @BramGruneir

**Comment by jseldess** [comment]
@piyush-singh, @taroface, for consideration for 20.1 or beyond.

**Comment by taroface** [comment]
Per @piyush-singh we should definitely highlight one-way network partitions
