### ISSUE TITLE
Create Django getting started document

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/docs#5946]
This can be based off of the example here: https://github.com/cockroachdb/docs/blob/master/v20.1/build-a-java-app-with-cockroachdb-hibernate.md

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6041, which points to the airtable record.

**Comment by jordanlewis** [comment]
Oops, sorry

**Comment by jseldess** [comment]
Np, @jordanlewis. That other issue was created just today.
