### ISSUE TITLE
Incorrect syntax documented for ALTER/DROP INDEX

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/docs#5948]
The following pages have a bug in the syntax documentation:
- https://www.cockroachlabs.com/docs/stable/rename-index.html
- https://www.cockroachlabs.com/docs/stable/drop-index.html

They both say the syntax looks like this:
![image](https://user-images.githubusercontent.com/1320573/69674359-56f9a300-106a-11ea-8e22-82b5757760d8.png)

This one is also incorrect:
- https://www.cockroachlabs.com/docs/stable/partition-by.html
![image](https://user-images.githubusercontent.com/1320573/69675047-c2904000-106b-11ea-95af-9b5284381721.png)

However, the syntax should look like it does on the [CONFIGURE ZONE](https://www.cockroachlabs.com/docs/stable/configure-zone.html) page:
![image](https://user-images.githubusercontent.com/1320573/69674451-7db7d980-106a-11ea-8cde-14722daddb1e.png)

That is, the `table_name` and `@` are optional, but can be used to disambiguate indexes with the same name that are in different tables.

Also, these pages don't have an incorrect syntax, but they express the correct syntax in a different way, so perhaps they should also be made consistent.
- https://www.cockroachlabs.com/docs/stable/split-at.html
- https://www.cockroachlabs.com/docs/stable/unsplit-at.html

**Comment by jseldess** [comment]
Thanks, @rafiss!
