### ISSUE TITLE
Enable SQL Savepoints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5953]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recxI0iMnCxdfpS2h

Description: This feature is KV supporting SQL's adding Savepoint syntax.

A Savepoint is a marker within a transaction that allows rolling back to a specific point in a transaction. At the moment, we use Savepoint keyword for rolling back only to the beginning of a transaction in a way that a client can begin again, helping users handle transaction retry errors.

The problem is CRDB's lack of compatibility with ORMs. For application developers depending on ORMs like Django, SQLAlchemy and Hibernate, this represents a significant barrier to adoption. More specifically, Savepoint support is required for passing third-party test suites.

Team: John Kendall, Andrew Kimball, Andrew Woods, Raphael 'kena' Poss, Andrei Matei, Bilal Akhtar

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/10735 https://github.com/cockroachdb/cockroach/issues/16491 https://github.com/cockroachdb/cockroachdb-python/issues/25 https://github.com/cockroachdb/docs/issues/5953

**Comment by rmloveland** [comment]
Estimated scope of work:

- Update SAVEPOINT docs to mention the support for nesting, add examples showing how
- Search for other mentions of the "no nested transactions" limitation and see if / how to update them
- Remove from known limitations page, if this is mentioned there

**Comment by jseldess** [comment]
@rmloveland, there are a bunch of savepoint-related updates in the next beta release notes. Pasting them here rather than opening distinct issues.

```
- CockroachDB now collects separate sets of metrics for usage of [`SAVEPOINT`](../v20.1/savepoint.html): one set for regular SQL savepoints and one set for uses dedicated to CockroachDB's client-side transaction retry protocol. [#45566][#45566] {% comment %}doc{% endcomment %}
- SQL [savepoints](../v20.1/savepoint.html) are now supported. `SAVEPOINT <foo>`, `RELEASE SAVEPOINT <foo>`, and `ROLLBACK TO SAVEPOINT <foo>` now work. `SHOW SAVEPOINT STATUS` can be used to inspect the current stack of active savepoints. [#45566][#45566]
- CockroachDB now provides preliminary support for SQL savepoints: the `SAVEPOINT`, `ROLLBACK TO SAVEPOINT`, and `RELEASE SAVEPOINT` statements. The support is limited in the following ways: (1) certain retry errors cannot be erased by `ROLLBACK TO SAVEPOINT` if the corresponding savepoint was not taken at the very begin of the transaction. (2) `ROLLBACK TO SAVEPOINT` cannot be used to cancel the effects of a DDL statement unless the savepoint was taken at the very begin of the transaction. [#45791][#45791]
- CockroachDB supports a new statement `SHOW SAVEPOINT STATUS` which reveals the current stack of active savepoints. This can be used to teach savepoint usage. [#45791][#45791]
```
