### ISSUE TITLE
[MH] CockroachDB Dialect/Adapter for Django

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5954]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec2FWDRcTEzFVntB

Description: CockroachDB will create a dialect adapter for the popular Python ORM Django. This dialect will be a fork of the Postgres adapter and it will remove unneeded PG functionality, replace PG functionality with better supported CRDB functionality, and provide a clear contract to developers about the supported features. 

It is too hard for developers to use CockroachDB with Postgres drivers and ORMs. There are three main reasons for this: 
- Bugs in our implementation
- Missing PG functionality 
- Different underlying architecture 

Conceptually, this is hard for developers to understand because we use the same wire protocol as Postgres. Developers will interact with CRDB and Postgres in the same manner but have different results based on bugs in our implementation, missing functionality, or the underlying differences in the architecture.

Django, a popular Python ORM, does not work for these reasons.

Team: Andrew Woods, Jordan Lewis, Rafi Shamim

Github Tracking Issue: https://github.com/cockroachlabs/cockroach-django/issues https://github.com/cockroachdb/docs/issues/5954

**Comment by ericharmeling** [comment]
I believe this if fixed by #6359.
