### ISSUE TITLE
[SH] WITH RECURSIVE CTE (common table expression) support 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5956]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec06cPoJb6dHNk5a

Description: CockroachDB supports using RECURSIVE (WITH). This means that a query can refer to its own output. A very simple example is this query to sum the integers from 1 through 100:

WITH RECURSIVE t(n) AS (
    VALUES (1)
  UNION ALL
    SELECT n+1 FROM t WHERE n < 100
)
SELECT sum(n) FROM t;

The general form of a recursive WITH query is always a non-recursive term, partnered with a UNION ALL.  This is a recursive term that can contain a reference to the query's own output. CockroachDB will support both tree structured data and more general graphs as well. Note, CockroachDB will not support recursive CTEs with UNION.

CockroachDB does not support recursive CTEs. This can be confusing to developers because CRDB does support single and multi-use CTEs. In particular, recursive CTEs can reduce the burden on the developer when working with graph, hierarchical or tree-structured data. It can shorten the lines of code needed to express the same idea by a large amount. In addition, recursive CTEs are commonly used in third-party tooling. 

Team: Andrew Woods, Jordan Lewis, Radu Berinde, Justin Jaffray

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/21085 https://github.com/cockroachlabs/support/issues/88 https://github.com/cockroachlabs/support/blob/master/dreamworks/with_recursive.md https://github.com/cockroachdb/cockroach/issues/21085  https://github.com/cockroachdb/docs/issues/5956

**Comment by ericharmeling** [comment]
From release note issue:

> PR: cockroachdb/cockroach#41368

> 
> From release notes:
> 
> Added support for WITH RECURSIVE with UNION ALL. [#41368][#41368] {% comment %}doc{% endcomment %}
