### ISSUE TITLE
[NH] Implement support for "soft" LIMIT in distributed queries 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5958]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recahSRbb3K4QbpIZ

Description: The CBO now supports "soft" limits. Soft limits allow the CBO to incorporate an estimate of the likely number of rows that are needed resulting in a better cost estimate. Developers do not need to take any action for the CBO to take advantage of this information, instead, the CBO is now has additional data puts as inputs into its cost model resulting in better planning.

"Hard limits" put an absolute cap on the number of rows returned by an operator. "Soft limits" indicate the likely maximum number of rows that will be returned by an operator.

While the CBO currently supports hard limits, it does not support soft limits. Without this information, the CBO can make poor cost estimates resulting in suboptimal join types.

Team: Andrew Woods, Radu Berinde

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/34811  https://github.com/cockroachdb/docs/issues/5958

**Comment by ericharmeling** [comment]
@RaduBerinde 

This doesn't look like a feature that needs documentation. Other than performance gains, are there any user-facing aspects that we should point out in the docs?

**Comment by RaduBerinde** [comment]
Yeah, it's just the optimizer creating better plans. I don't think there is anything we need to document.
