### ISSUE TITLE
Granular roles and privileges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5960]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recCHyCs4TR6kO3gs

Description: The permissions that CockroachDB administrators can grant to users are now more granular. Instead of granting superuser access, administrators can assign narrower permissions for specific operations like IMPORT or BACKUP.

Enables non-admin users to perform the cluster administration/management tasks they need to do. IMPORT is the big-ticket item here but this should also take into account the other cluster operations (CDC, backup, restore, partition) that are currently restricted to admin users. We are also getting more requests for the ability to grant narrower sets of privileges from enterprises with serious security controls.

Team: Marc Berhault, Jesse Seldess, Roland Crosby, Lakshmi Kannan, Lauren Hirata

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/15005 https://github.com/cockroachdb/cockroach/pull/20149 https://github.com/cockroachdb/cockroach/issues/29633  https://github.com/cockroachdb/docs/issues/4766 https://github.com/cockroachdb/cockroach/issues/41380 https://github.com/cockroachdb/docs/issues/5960

**Comment by Amruta-Ranade** [comment]
Dupe of #4766

**Comment by jseldess** [comment]
@Amruta-Ranade, this is the one that's connected to the 20.1 roadmap. Notice the "milestone". Let's leave this one open and close the other, which is a leftover from previous roadmaps.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
