### ISSUE TITLE
Import from Avro format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5961]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recoR5m8evEz6tMhG

Description: Enable Spanner users to migrate to CockroachDB by providing a facility to import the Avro + JSON format that Spanner uses for exports.

Team: 

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5961

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/43104

From release notes:

> - CockroachDB now supports [importing](../v20.1/import.html) Avro data. [#43104][#43104]

@lnhsingh, looks like this one is ready for docs.

**Comment by lnhsingh** [comment]
Docs updates:
- Add Avro to the list of file types you can IMPORT
- Add example to IMPORT doc on how to import an Avro file
- Add a `migrate-from-avro` doc
