### ISSUE TITLE
VPC Peering for GCP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5966]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recdR3aCPlygf3iPj

Description: Allow customers to connect to their managed CockroachDB cluster without going through the internet, rather by connecting their application private network in GCP to the cluster private network in GCP 

Customers don't have stable IPs if they are running on GKE. VPC peering is one solution for this. 

Team: Lakshmi Kannan, Roland Crosby

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5966

**Comment by Amruta-Ranade** [comment]
Note to self: Revisit the copy and docs for Networking. Change "Authorize network" to "Whitelist IP"
