### ISSUE TITLE
Improve FK Performance and Compatibility

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5967]
Background: https://cockroachlabs.atlassian.net/browse/CRDB-779

Team: Andrew Woods, Radu Berinde

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/15157 https://github.com/cockroachdb/cockroach/issues/25809 https://github.com/cockroachdb/cockroach/issues/26786 https://github.com/cockroachdb/cockroach/issues/26795 https://github.com/cockroachdb/cockroach/issues/23580 https://github.com/cockroachlabs/support/issues/224 https://github.com/cockroachdb/cockroach/issues/33467 https://github.com/cockroachdb/cockroach/issues/16491 https://github.com/cockroachdb/docs/issues/4003  https://github.com/cockroachdb/cockroach/issues/36859 https://github.com/cockroachdb/docs/issues/4788 https://github.com/cockroachdb/docs/issues/5967

**Comment by ericharmeling** [comment]
I'm going to bump this item to 20.2, as not all of these feature updates are going to be ready for 20.1.

We can document the individual improvements in FK performance as they come up in release notes.

**Comment by jseldess** [comment]
@ericharmeling, I'm sorry it's hard to track this one. Can you track down the relevant release note issues and confirm with @awoods187 and devs that they cover all of the improvements in 20.1?

**Comment by awoods187** [comment]
Hey @ericharmeling. We do have a bit of work to do here. Foreign Keys are now planned by the CBO and no longer require an experimental flag. What got bumped is Foreign Key Cascade which still use the old implementation. This is a small docs project to remove the experimental flag and mention that they are planned using the CBO. After FK cascade lands in 20.2, we will have another small project to update that FKs don't use an extra index but mostly the user will just experience better FK performance. cc @RaduBerinde
