### ISSUE TITLE
[NH] Support virtual computed columns

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5969]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recGSCwmBVrUHJSlz

Description: Virtual computed columns are columns that aren't stored on disk, but are computed on-demand from the other columns in their table. Virtual computed columns enable much cheaper indexing on sub-fields of JSON columns.

Currently, using indexes on JSON requires you to store JSON data three times: the original JSON, the Computed Column, and the Index. This is expensive  

Team: Andrew Woods, Radu Berinde

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/24455 https://github.com/cockroachdb/docs/issues/5969

**Comment by ericharmeling** [comment]
@awoods187 
I don't see this issue on the JIRA roadmap. Should we close this issue for now?

**Comment by awoods187** [comment]
this is the same as expression based indexes but we also cut that recently
