### ISSUE TITLE
[NH] Vectorization: Data Types

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5970]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/reciDxEVXj4Y68MCz

Description: Allows the SQL Vectorization Engine to work with more data types. SQL Vectorized Execution now works with the following data types:
Timestamp
UUID

Team: Andrew Woods, Jordan Lewis

**Comment by ericharmeling** [comment]
This is a duplicate of https://github.com/cockroachdb/docs/issues/5917.

Fixed with https://github.com/cockroachdb/docs/pull/6107.
