### ISSUE TITLE
Increase maximum storage per node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5971]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recO3yD744y8oNI3Y

Description: In 19.2, CockroachDB default range size is 64MiB and falls over at roughly 1TB per node. With this change, CockroachDB has a default range size that's higher than 64MiB and stores up to 10TB per node.

--

Customer Problem: Cost

The problem that his feature addresses is cost for customers with on-prem hosts that can store significantly more than 1TB. When running CRDB, they are forced to add more nodes to their deployments than necessary if Cockroach could support more data per node. Ultimately, customers have to pay more than necessary because they have to pay for more nodes.

Team: John Kendall, Andrew Werner, Andrew Kryczka

Github Tracking Issue: https://github.com/cockroachdb/cockroach/pull/31663 https://github.com/cockroachdb/docs/issues/5971

**Comment by rmloveland** [comment]
Estimated scope of work:

- Review all mentions of default range size in docs
- Revise mentions to use an include wherever possible
- Update everything to note the new default range size, total cluster data size enabled by new limit
- Update production deployment docs re: storage, as/if needed

**Comment by jseldess** [comment]
From release notes:

> New clusters will have a larger default range size of 512 MB, which will result in fewer ranges for the same amount of data. [#45209][#45209]

**Comment by rmloveland** [comment]
@ajwerner as Jesse noted, the recent release note says 

> New clusters will have a larger default range size of 512 MB, which will result in fewer ranges for the same amount of data. [#45209][#45209]

Do we have updated guidance on the maximum amount of data to store in a cluster as well?  I note the wording of this release note makes sure to avoid mentioning that. :-)

**Comment by rmloveland** [comment]
Update: i have been informed by Andrew that this is an active area of investigation.  Standing by to await the results of that work before proceeding here
