### ISSUE TITLE
Improve time selection capabilities for time series dashboards

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5972]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec5q3DBXUVInHcL0

Description: The Web UI will offer improved time selection capabilities for timeseries dashboards. Users will be able to select concrete begin and end times for historical analysis of performance. This will enable better post-mortem troubleshooting for time periods in the past few days.

The current time picker in the Web UI only allows selection of historical time periods by clicking arrows on either side of the time window size selection. This can cause problems when trying to troubleshoot an incident that occurred a few days in the past: selecting a time window and then repeatedly clicking the arrows to find the correct slice of time during which incident occurred is inefficient and cumbersome.

This is further complicated by the fact that selections are not preserved when navigating away from the page and back (you will need to click over to the same slice again) and they are not encoded in query parameters in the URL, so it is impossible to share your view of the dashboard with colleagues who are attempting to help you with a post-mortem.

Team: Roko Kruze, Piyush Singh, Jeremy Bloom, Amruta Ranade, Anne Birzin

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/7778 https://github.com/cockroachdb/docs/issues/4737 https://github.com/cockroachdb/docs/issues/5972

**Comment by taroface** [comment]
Duplicates #6218
