### ISSUE TITLE
Scale clusters in/out on the managed console (add/ remove nodes)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5973]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recs6ScCAd1ZHWJKe

Description: Customers can make edits to their current managed cockroachdb cluster from the console. CockroachCloud users can now add and remove nodes in the same region to their CockroachCloud cluster directly from the console. 

There are many parts to editing a cluster --  

1. Scale out i.e., adding (or removing) nodes. 
2. Scale up (changing the node size whether thats increasing or decreasing what was originally chosen). This is tracked here separately. https://airtable.com/tblD3oZPLJgGhCmch/viwTBy1c8OnK6G6t4/rechmiQfoXTbajvfw 
3. Adding or removing nodes in other regions. This is out of scope for this entry. 

When the traffic received by an application increases dramatically, a user should be able to scale their application. An important piece of this is adding more servers/ nodes to the current cluster. An example of this can be Black Friday or a big sale where the developer expects increased traffic ahead of time. After the event (e.g., sale), they may want to bring their cluster back down to the size it was before so as to not pay for extra resources they are not using, 

Team: Lakshmi Kannan, Jeremy Bloom, Josh Imhoff, Joel Kenny, Joe Lowinske, Amruta Ranade, Lucia Cozzi

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5973

**Comment by Amruta-Ranade** [comment]
Closing in favor of #6356
