### ISSUE TITLE
Status of instances of MSO - user facing

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5974]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recOVotey8JhJe9G8

Description: Customers and prospects can understand the status of the CockroachCloud console as well as their specific CockroachCloud cluster. This is publicly facing on the website. 

Customers need to know when their clusters are experiencing problems so they can change their workflow. Per most legal contracts w/ our hosted customers, we need a process for how to let customers know of disruption. 

Team: Lakshmi Kannan, Marc Berhault, Josh Imhoff, Joel Kenny, Amruta Ranade

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/4938

**Comment by Amruta-Ranade** [comment]
As discussed on Slack, closing this issue for now. Will reopen if/when the team picks it up.
