### ISSUE TITLE
[SH] Distribution awareness in the CBO/route local

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5978]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rechHp0xaOyKv6fa1

Description: This feature increases the CBO's awareness of latency and factors it into the cost of query planning. This allows the CBO to routes queries to the local node first (when possible) to reduce latency. 

Currently, the CBO plans queries and distributes them based upon available resources among other decisions. This can be problematic because some queries could be executed entirely locally. Queries can need to travel across localities and pay a significant latency penalty when, if locality were factored into the decision making, they could be executed locally. 

Team: Andrew Woods, Radu Berinde, Rebecca Taft

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/41207

**Comment by ericharmeling** [comment]
@awoods187 
I don't see this in the JIRA roadmap. Should we close this issue for now?

**Comment by awoods187** [comment]
yeah this got cut recently
