### ISSUE TITLE
Single sign on / federated sign on

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5979]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec8a5wld8haS59Rm

Description: Enterprise customers can use single sign on / federation to sign into the MSO console

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Closing this for now - this is partially addressed by new GitHub sign-in. More work to be done later but will open a new issue.
