### ISSUE TITLE
[SH] New partitioning syntax 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5981]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec6WkrR0y6cUsfML

Description: You can now partition a table and all of its secondary indexes with one simple command. CRDB still provides comprehensive tools for maximum flexibility. It simply pairs that with default table settings which will be used by the majority of deployments. 

Note, we are iterating on this syntax and the majority of the work will be in its design. 

It is very easy to miss partitioning of a secondary index when geo-partitioning a table today. If a table has 10+ indexes, partitioning by hand will require large amounts of copy pasting or typing commands, and it is easy to accidentally skip over a secondary index that needs to be partitioned.

Beyond this, when a table has a secondary index that was accidentally not partitioned, it can be difficult to determine that it is the root cause for latency spikes in certain kinds of queries.

Having a simple way to partition a table and its secondary indexes in the same exact way improves the UX by reducing repetition and eliminating opportunities for mistakes.

In addition to missing secondary indexes, the current syntax can require hundreds of lines of SQL to accomplish a conceptually simple goal: partitioning a table into the known localities. 

Team: Andrew Woods, Richard Loveland, Jordan Lewis, Solon Gordon

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/4797

**Comment by ericharmeling** [comment]
@awoods187 
I don't see this on the JIRA roadmap. Should we close this issue for now?

**Comment by awoods187** [comment]
yup
