### ISSUE TITLE
Continuous Backup

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5982]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recYssNX9BRC78kEt

Description: Enables a user to continuously stream all changes to a table or database to a cloud storage location, and restore to any point in time within that stream.

Team: Roko Kruze, Daniel Harrison, David Taylor, Roland Crosby

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/36290

**Comment by lnhsingh** [comment]
Deprioritized for v20.1
