### ISSUE TITLE
[SH] Improve zone configuration syntax via SQL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5983]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec58IuCfg2dQEAIQ

Description: The current method is something like: CONFIGURE ZONE USING lease_preferences='[[+cloud=aws,-region=us_east], [+cloud=gce,+region=us_west]]' as described in #37429 

We can modify the current SQL to CONFIGURE ZONE USING LEASE PREFERENCES ON cloud='aws' AND region<>'us_east', FALLBACK TO cloud='gce' AND region='us_west'as tracked in #37429 to make it similar to using SQL. 

Note, we are iterating on this syntax and the majority of the work will be in its design. 

Setting zone configurations is currently done via a confusing syntax that is not entirely SQL as it also includes YAML.  Developers want to set locality or other zone configuration information via syntax that is familiar and consistent with SQL so that they don’t have to learn a new syntax and to limit user error.

Team: Andrew Woods, Jesse Seldess, Jordan Lewis, Solon Gordon

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/37429

**Comment by ericharmeling** [comment]
@awoods187 
I don't see this on the JIRA roadmap. Should we close this issue for now?

**Comment by awoods187** [comment]
yeah this got cut from an old release.
