### ISSUE TITLE
[SH] Find ranges for a specific row

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5984]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recoqxtzH1FW7DfGu

Description: SHOW RANGE ID FROM PK

This information will need to include locality, node, range id, etc. 

Currently, developers can see how a table maps to underlying key-value ranges (show ranges). But developers cannot see which range contains the data for a specific row. This ability would let users validate, for example, that when you change the partition value of a row (e.g., chicago to new york), we move that record to the correct partition.

In addition to observability, this is also needed for compliance (e.g., GDPR) as developers are unable to prove where the data is located. Developers can only show that they configured the system accordingly. Then they must hope the data actually ended up in the correct regions, but we can't show it.

Team: Andrew Woods, Jordan Lewis, Solon Gordon

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/40679

**Comment by ericharmeling** [comment]
I believe this was fixed by https://github.com/cockroachdb/docs/pull/5612. Please re-open if I've got that wrong.
