### ISSUE TITLE
Support third-party development of Liquibase 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5989]
Background: https://cockroachlabs.atlassian.net/browse/CRDB-1354

Description: Liquibase recently added support for Postgres. This work will result in CockroachDB either working with the Postgres dialect out of the box or include a CRDB specific dialect for using with Liquibase. Either way, this work will result in a Liquibase version that works natively with CockroachDB. 

It is too hard for developers to use CockroachDB with Postgres drivers and ORMs. There are three main reasons for this: 
- Bugs in our implementation
- Missing PG functionality 
- Different underlying architecture 

Conceptually, this is hard for developers to understand because we use the same wire protocol as Postgres. Developers will interact with CRDB and Postgres in the same manner but have different results based on bugs in our implementation, missing functionality, or the underlying differences in the architecture. 

Liquibase, a popular schema migration tool like Flyway, does not work out of the box with CockroachDB due to the reasons described above. 

Team: Andrew Woods, Eric Harmeling, Jordan Lewis, Rafi Shamim

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/13991 https://github.com/cockroachdb/cockroach/issues/37460 https://github.com/cockroachdb/docs/issues/4793

**Comment by jseldess** [comment]
https://github.com/timveil-cockroach/liquibase-example

**Comment by awoods187** [comment]
This is close to being ready. We are awaiting two issues currently in-progress:
The first issue is https://github.com/liquibase/liquibase/issues/1021
The second is https://github.com/liquibase/liquibase/issues/1022
