### ISSUE TITLE
[SH] Optimize reference tables in geo-distributed deployments

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5991]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recrzkQSwZJ0hIug1

Description: We can increase the performance of reference tables by:
- pushing joins to one dc to avoid multiple roundtrips
- lookup join use local region
- do local FK checks when inserting new rows

We promote reference tables as a primary deployment pattern in CRDB. This requires the user to create duplicate indexes in each region and partition those indexes. Reference tables can only be used in some limited settings. They cannot be used with lookup joins in the same region or when using Foreign Keys to do local inserts on new rows.

Team: Andrew Woods, Radu Berinde, Rebecca Taft, Justin Jaffray

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/41208

**Comment by ericharmeling** [comment]
Closing this roadmap issue in favor of a new issue.
