### ISSUE TITLE
CockroachDB Dialect/Adapter for Hibernate

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5992]
Background: https://cockroachlabs.atlassian.net/browse/CRDB-1356

Description: CockroachDB will create a dialect adapter for the popular Java ORM Hibernate. This dialect will be a fork of the Postgres adapter and it will remove unneeded PG functionality, replace PG functionality with better supported CRDB functionality, and provide a clear contract to developers about the supported features. 

It is too hard for developers to use CockroachDB with Postgres drivers and ORMs. There are three main reasons for this: 
- Bugs in our implementation
- Missing PG functionality 
- Different underlying architecture 

Conceptually, this is hard for developers to understand because we use the same wire protocol as Postgres. Developers will interact with CRDB and Postgres in the same manner but have different results based on bugs in our implementation, missing functionality, or the underlying differences in the architecture.

Hibernate, a popular Java ORM, does not work for all use cases for the reasons described above.

Team: Andrew Woods, Jordan Lewis, Rafi Shamim

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/16491

**Comment by ericharmeling** [comment]
@rafiss @awoods187 

Is this in scope for 20.1?

**Comment by awoods187** [comment]
Yes--we are awaiting approval to merge it into the mainline hibernate repo

**Comment by awoods187** [comment]
We are still waiting merging into the mainline repo. When it merges, the only real changes needed will be in the method for downloading and calling this dialect.

**Comment by ericharmeling** [comment]
@vy-ton 
FYI, I'm doing this in two steps:

- [ ]  Updating Java/Hibernate Hello World example code.
- [ ]  Updating Spring/JPA roach-data example code.

**Comment by vy-ton** [comment]
To highlight in our docs,
```
the version of the dialect corresponds to the min crdb version but no harm in upgrading the db. upgrading the dialect will allow for more feature usage in the same way as upgrading the db allows for more feature usage.
```
