### ISSUE TITLE
Build and expose CockroachCloud APIs (CUD ops on clusters) 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5995]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recj1LiETc6zBOGqe

Description: Developers can now programmatically access CockroachCloud and do CUD ops on them using APIs. Specifically they can take the following actions: 
1. Create single region cluster in AWS or GCP from 1 to 24 nodes
2. Edit single region clusters from step 1. 
3. Delete clusters from step 1. 

(We could also expose our APIs for observability, that is out of scope in this epic/ V1). 

Currently for developers who are using CC as part of their CI/CD pipeline, there is no way to programmatically access CockroachCloud. An application developer has to go to the CockroachCloud console and click through the UI to generate a cluster and its connection string. This breaks the workflow of the app developer who likely prefers to do this via a programmatic interface. 
This is also the industry standard for infrastructure services, e.g., see mongo atlas API docs https://docs.atlas.mongodb.com/api/ 
https://www.elastic.co/guide/en/cloud-enterprise/1.1/ece-api-reference.html 

Team: Jeremy Bloom, Lucia Cozzi

Github Tracking Issue:

**Comment by Amruta-Ranade** [comment]
As discussed on Slack, closing this issue for now. Will reopen if/when the team picks it up.
