### ISSUE TITLE
SOC 2 Type I For CockroachCloud

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5996]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recjO3sEzsPOKXxYw

Description: Cockroach Labs engaged with an auditor to receive our first SOC 2 Type 1 report. This report will be available to customers and prospects who ask for it and allows us to mark CockroachCloud as SOC 2 Certified. Following this engagement, we will undergo the Type 2 audit, and plan to go through the type 2 audit process annually.

Customers, especially CockroachCloud customers, want to know that their data is secure and that Cockroach Labs maintains secure development and data handling practices. By undergoing a SOC2 audit, we are able to demonstrate to customers and prospects that we meet a generally accepted level of security and that we have taken the right measures to secure their data and will continue to do so.

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Closing this, as it seems out of date
