### ISSUE TITLE
Enable CRDB to run on one node that is already replicated by cloud

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5999]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recIr6gWMBfh5m4uJ

Description: This feature is also known as "1x Replication." Today, the usual CRDB configuration consists of at least 3 virtual machines (VMs), each with attached storage. However, when running in a Cloud (e.g. AWS or Google) provider that offers network storage (e.g. EBS), it is generally more cost-efficient to run only 1x VM and let the network storage take care of data replication.

--

Customer Problem: Cost

The problem is CRDB could be run cheaper by not paying for replication twice. It's unnecessary redundancy for customers that are concerned with cost. Amazon's EBS and Google's persistent disk SSD both already do the replication for us.

Team: John Kendall, Darin Peshev

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5999

**Comment by rmloveland** [comment]
Closing - this work describes a test that was performed but that will not be part of CRDB 20.1.

(cc @johnrk)
