### ISSUE TITLE
Enable “SELECT FOR UPDATE” Statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6000]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recnmogESIC5147Jf

Description: This feature is implementing SELECT FOR UPDATE statement, making it usable by application developers. At the moment, SELECT FOR UPDATE explicitly does not do anything when executed. In its implemented state, SELECT FOR UPDATE provides one exclusive access when executing an UDPATE statement.

The important problem is retry errors because our customers consistently express it as a pain point. As of September 2019, 4.5% of our customers’ long-running clusters experience transaction retry errors. Application developers are accustomed to other databases, such as Oracle, that cause less cases of contention that are the root cause of these errors.

As a result, their applications are not setup to handle the additional retry errors that are inherent to our design. Customers have the burden of added application logic to handle this case. While this expected behavior and best practices for handling is well-documented (https://www.cockroachlabs.com/docs/stable/advanced-client-side-transaction-retries.html
), it’s still a pain point for customers because this type of change feels invasive.

Team: John Kendall, Nathan VanBenschoten

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/6000

**Comment by rmloveland** [comment]
Estimated scope of work:

- Write new docs for `SELECT FOR UPDATE` statement, with examples showing how it works
- Maybe update architecture docs storage layer (via another issue) re: new concurrency control package that (AIUI as of this writing) is enabling this SQL work
- Update various transaction retry loop docs (including example app pages) to mention and link to SFU docs
- Update various SELECT query docs to mention and link to SFU docs

**Comment by rmloveland** [comment]
See also:
https://github.com/cockroachdb/cockroach/pull/45159
