### ISSUE TITLE
Make follower reads less stale

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6001]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recTs7cmwrMLBd5pZ

Description: This feature enables customers to have follower reads become only 1 second - 5 seconds stale instead of 30 seconds.

Team: John Kendall, Andrew Werner

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/43147

From release notes:

> - Shortened the default interval for the `kv.closed_timestamp.target_duration` [cluster setting](../v20.1/cluster-settings.html) from `30s` to `3s`, which allows for follower reads at 4.8 seconds in the past rather than the previous 48 seconds. [#43147][#43147]

@rmloveland, looks like this is ready for docs work.

**Comment by rmloveland** [comment]
Estimated scope of work:

- Update Follower Reads doc to note the new interval
- Review other docs for follower reads content, update as/if needed
