### ISSUE TITLE
Safer backups independent from ttl zone config

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6003]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recXZ8sKfgRGaKe6Y

Description: Enables capturing a snapshot at a point in time that garbage collection won't collect from.

Garbage collection has no guards for how far back it can go in time. We lack a mechanism for defining a time to not garbage collect from.

Team: John Kendall, Andrew Werner

Github Tracking Issue:

**Comment by rmloveland** [comment]
Estimated scope of work:

- Update various backup docs to mention the independence from gcttl zone config
- Update zone config docs as/if needed
- Review architecture docs and see if update is needed
- Check if there are AOST changes, update as needed
- Update production docs around backups as needed

**Comment by rmloveland** [comment]
@ajwerner I am working on some docs for protected timestamps and I have questions:

1. protectedts enables shorter gc intervals, but has the default ttl actually changed?  at least right now it looks like it's still 25 hours in [zone.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/config/zonepb/zone.go) on `master`

2. Given the existence of protected timestamps, do we have any new recommendations about what a safe shorter GC ttl might be?  or is the answer "it depends"?

3. Right now I'm working on an update to the architecture docs - specifically the [Storage layer](https://www.cockroachlabs.com/docs/dev/architecture/storage-layer.html) in the section on GC.  I am considering whether we should add some information about the fact that you *can* lower the GC TTL to [AOST docs](https://www.cockroachlabs.com/docs/dev/as-of-system-time.html) or the [backup docs](https://www.cockroachlabs.com/docs/dev/backup-and-restore.html).  However this probably hinges on the answer to #2. 

4. Related to above: if we do allow lower GC TTLs how come we did not (apparently?) lower the default?  Or is the existence of protected timestamps more focused on e.g. allowing daily backups to run safely if they take longer than an hour?  (as implied by our current 25 hour window)

Happy to set up a meeting if that would be easier, also.  I'm mostly working from the RFC and code comments so I may be missing some obvious things.

**Comment by ajwerner** [comment]
The protected timestamp work was a prerequisite to enabling shorter GC intervals but did not in itself change the default. There is more work to be done w.r.t. user stories around incremental backups and backup policies.

> @ajwerner I am working on some docs for protected timestamps and I have questions:
> 
>     1. protectedts enables shorter gc intervals, but has the default ttl actually changed?  at least right now it looks like it's still 25 hours in [zone.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/config/zonepb/zone.go) on `master`

Correct, we did not change the default in this release.

>     2. Given the existence of protected timestamps, do we have any new recommendations about what a safe shorter GC ttl might be?  or is the answer "it depends"?

The answer is that it depends on backup procedures. You can lower the GC TTL to whatever frequency you intend to perform backup plus a relatively small window. 

>     3. Right now I'm working on an update to the architecture docs - specifically the [Storage layer](https://www.cockroachlabs.com/docs/dev/architecture/storage-layer.html) in the section on GC.  I am considering whether we should add some information about the fact that you _can_ lower the GC TTL to [AOST docs](https://www.cockroachlabs.com/docs/dev/as-of-system-time.html) or the [backup docs](https://www.cockroachlabs.com/docs/dev/backup-and-restore.html).  However this probably hinges on the answer to #2.

It is probably worth mentioning it somewhere given it is in a public zone config.

>     4. Related to above: if we do allow lower GC TTLs how come we did not (apparently?) lower the default?  Or is the existence of protected timestamps more focused on e.g. allowing daily backups to run safely if they take longer than an hour?  (as implied by our current 25 hour window)

Very much the latter. Also critically important is that it applies to `CHANGEFEED`s and `IMPORT INTO` which could experience failure or catastrophic bugs if data had been GC'd. 

> Happy to set up a meeting if that would be easier, also. I'm mostly working from the RFC and code comments so I may be missing some obvious things.

That may be worthwhile. Happy to do it.
