### ISSUE TITLE
Full Cluster Backup (not just table data) 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6005]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recMpaRQ1jNupgZVe

Description: Users can now back up and restore an entire cluster's data, preserving configuration and metadata information that is not currently included in backups.

CockroachDB's backup functionality currently works on a per-database or per-table basis - it does not preserve most system table information, and there is not a well-supported path to backing up and restoring all the metadata in a table. This means that a user needs to manually document permissions/grants/cluster settings/etc in their original cluster, and then manually reapply those settings in the restored cluster; it's not a good user experience and we don't even really document how to do this.

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Related issue: https://github.com/cockroachdb/docs/issues/6440

**Comment by jseldess** [comment]
From release notes:

> - Added the ability to restore a full cluster backup to a new cluster, including all configuration and system information such as user privileges, zone configurations, and cluster settings. Restoring a full cluster backup to an existing cluster is not supported. [#43828][#43828]

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/43767

From release notes:
> Added `BACKUP TO <location>`, which allows you to [backup](../v20.1/backup.html) all relevant system tables as well as all user data in a cluster. [#43767][#43767] {% comment %}doc{% endcomment %}
