### ISSUE TITLE
Make IMPORT resilient to transient network failures

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6006]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec9YAtbhynNkQY2x

Description: When running the IMPORT statement, if a network request (e.g. for a data file in cloud storage) fails, CockroachDB will retry the failed request instead of immediately causing the entire job to fail.

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Out of scope for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
