### ISSUE TITLE
Improve IMPORT pause/resume behavior

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6007]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recVxU7R2tqplmneJ

Description: 

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Related issue: https://github.com/cockroachdb/docs/issues/6456

**Comment by lnhsingh** [comment]
Note added already to [`IMPORT` docs](https://www.cockroachlabs.com/docs/dev/import.html#viewing-and-controlling-import-jobs)
