### ISSUE TITLE
Enable column reordering in IMPORT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6008]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recqmZW3rhSPRFiyN

Description: 

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Out of scope for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
