### ISSUE TITLE
Improve IMPORT error messaging

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6009]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec8ORHbLO5zVqTbu

Description: 

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Out of scope for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
