### ISSUE TITLE
Enable single-node nodelocal:// storage

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6010]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec28gbgAEdR3V8vY

Description: 

Team: Michael Wang

Github Tracking Issue:

**Comment by jseldess** [comment]
PR: https://github.com/cockroachdb/cockroach/pull/42966

From release notes:

> - Added a `nodelocal` command that can be used to upload file: `cockroach nodelocal upload location/of/file destination/of/file`. [#42966][#42966]

@lnhsingh, looks like this is ready for docs.

**Comment by lnhsingh** [comment]
Doc updates:
- Create new page called `cockroach-nodelocal-upload.md`
- This page should include an extended example on how to use `cockroach nodelocal upload`
