### ISSUE TITLE
Key/passphrase-based backup encryption

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6011]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec9MI1KAGEUnvmLV

Description: Users can specify an encryption key when creating and restoring backups, causing CockroachDB to encrypt the data in the backup files.

CockroachDB provides mechanisms to encrypt all data in the database using Encryption at Rest, but its backups store all data in cleartext. This presents a problem for organizations that have security controls requiring data to be encrypted at all times, or that prefer to have an additional layer of security on top of their backup storage.

**Comment by lnhsingh** [comment]
Docs changes:
- Add section to `backup-and-restore.md` on how to backup and restore an encrypted file
- Add section to `backup.md`
- Add example to `backup.md`
- Add section to `restore.md`
- Add example to `restore.md`

**Comment by jseldess** [comment]
From release notes:

> - Added support for encrypting `BACKUP`/`RESTORE` files via the `encryption_passphrase` option. [#44177][#44177]
