### ISSUE TITLE
Enable I/O from client-local storage

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6012]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recWTNxhHICHDrmvy

Description: 

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
This is already documented for [IMPORT](https://www.cockroachlabs.com/docs/dev/import#import-a-table-from-a-local-file) via https://github.com/cockroachdb/docs/pull/6287.
