### ISSUE TITLE
Backup scheduling

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6013]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec7dpGqIaGAophb7

Description: Users can issue a single statement to schedule a cadence for CockroachDB backups, and CockroachDB will automatically execute the backups on that schedule without requiring external intervention.

Currently, CockroachDB doesn't have any internal job scheduling mechanism. This means that all production environments need to deploy an external system that issues SQL statements (e.g. a backup script running on a cron job). This commonly-reported pain point takes unnecessary effort to set up, and undermines CockroachDB's  promise of operational simplicity.

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
> We're confident we'll be able to complete the part of this Epic that will make it easier to do incremental backups, but the automatic scheduling will likely NOT make it into 20.1

**Comment by lnhsingh** [comment]
Based on priorities unlikely to make it into 20.1

**Comment by lnhsingh** [comment]
Closing in favor of #7927
