### ISSUE TITLE
Support SQL PK change effort

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6014]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recf3lQuxsS2zdpcZ

Description: This is the Bulk I/O side of the work to support the SQL team's work to change primary keys.

See the SQL record for primary key changes. Partitioning a table requires all fields being partitioned on to be in the primary key; this is not typically how users design their schemas, and since primary keys can't currently be changed, an ugly workaround (export followed by import) is required to make this work.

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
No docs needed for this.
