### ISSUE TITLE
Make schema changes jobs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6015]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recTcKA9ymjKImgaB

Description: 

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Related to #6894

**Comment by lnhsingh** [comment]
Closing this issue - will make use #6017 to track changes
