### ISSUE TITLE
Pause/restart for schema change jobs 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6017]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recUpBr66N0LAlKD7

Description: Allow for pause and restart for schema change jobs.

Schema changes are an important feature and selling point for using CockroachDB in production. We should make sure the UX of schema changes is good by covering all use cases that are considered schema changes and adding them as a job.

Team: Michael Wang

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/22652#issuecomment-366315564 https://github.com/cockroachdb/docs/issues/4015

**Comment by lnhsingh** [comment]
Docs changes:
- Need to remove note on PAUSE JOB / RESUME JOB that says "you cannot pause schema changes"
- Add schema changes to the list of jobs you can pause / resume

**Comment by jseldess** [comment]
From beta.3 release notes:

> - Schema changes are now scheduled and run fully like other [jobs](../v20.1/show-jobs.html): they now can be [canceled](../v20.1/cancel-job.html), [paused](../v20.1/pause-job.html), and [resumed](../v20.1/resume-job.html). Some other UI differences come with this implementation change; notably, all schema changes now have an associated job, failed schema changes are now rolled back within the "Reverting" phase of the same job, and GC for dropped indexes and tables is deferred to a later job. [#45870][#45870]
