### ISSUE TITLE
Improve interaction of job/schema changes and transaction timestamps

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6018]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec7Zs8YLZeDuTgme

Description: 

Team: Roland Crosby

Github Tracking Issue:

**Comment by lnhsingh** [comment]
This seems to have been de-prioritized for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
