### ISSUE TITLE
Pebble (Storage Engine) Integration

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6019]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/reco0pI5FW8zAqIsz

Description: This feature transitions KV Storage from RocksDB to Pebble. Customers will be able to enable Pebble or RocksDB via a command line flag. In this release, it will run with RocksDB by default.

The problem is RocksDB is not the ideal storage engine for the long haul. There are issues internally and for our customers.

Internally:
RocksDB is difficult to maintain. It has over 260k lines of code with only one engineer that has expertise in. In addition, it is written in C++, when the rest of our codebase is written in Go. This impacts performance, and it is a burden for engineering to interface between C++ and Go.

For Customers:
With it being harder to support, RocksDB is susceptible to stability issues. Facebook has introduced 6 bugs recently with RocksDB, so it appears quality has gone down. In addition, RocksDB is less performant than Pebble. Customers are hurt when they have slower queries than necessary.

Team: Andrew Kryczka, Peter Mattis, John Kendall, Bilal Akhtar

Github Tracking Issue:

**Comment by rmloveland** [comment]
Estimated scope of work:

- Since Pebble is unlikely to be the default storage engine for 20.1, document the flag to toggle between Pebble and RocksDB (if needed - it may already be done).

**Comment by rmloveland** [comment]
Fixed in #6769.
