### ISSUE TITLE
[Docs] MovR via Flask and SQLAlchemy [code]

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6030]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recsExQhNHYTo6qHm

Description: MovR is a fictional vehicle-sharing company created to demonstrate CockroachDB's features. We expanded upon MovR to provide a more “real-world” example application for developers to evaluate. We now provide a code repo as well as a tutorial for application developers to better understand how to build an application using CockroachDB.

It will also serve as a template for expansion to other ORMs and languages.

The MovR example consists of the following:
- The movr dataset, which contains rows of data that populate tables in the movr database. The movr dataset is built into cockroach demo and cockroach workload.
- The MovR application, a fully-functional vehicle-sharing application, written in Python. All of MovR application source code is open-source, and available on the movr GitHub repository.

While a great example application for the database, MovR is not built as a robust full stack application. 

Team: Andrew Woods, Rafi Shamim, Eric Harmeling

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5687  https://github.com/cockroachdb/docs/issues/5610

**Comment by ericharmeling** [comment]
See https://github.com/cockroachlabs/movr-flask.
