### ISSUE TITLE
[Docs] Updated docs page that lists all third-party tools

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6032]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recseiOcZshSc0jZk

Description: CockroachDB's third-party tooling page now contains an up-to-date via of support for drivers, ORMs, database migration tools, GUIs, IDEs, etc. 

People will look for driver and ORM content outside of the specific language landing pages (e.g., Python page). 

Team: Andrew Woods, Rafi Shamim, Eric Harmeling, Richard Loveland

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5626

**Comment by awoods187** [comment]
Closing this as a dupe of https://github.com/cockroachdb/docs/issues/6326
