### ISSUE TITLE
[Docs] Golang ORM Tutorial 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6037]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recZkhgX2ZhxFsrXK

Description: We now have a sample getting started guide for using this ORM.

CockroachDB will suppor the Go lang ORM in 20.1. Currently, there is no getting started tutorial for this ORM. 

Team: Andrew Woods, Rafi Shamim, Eric Harmeling

Github Tracking Issue:

**Comment by ericharmeling** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6038
