### ISSUE TITLE
[Docs] Re-launch GORM Tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6038]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rec6KFW4phSE2s4we

Description: We now have an improved getting started guide for using this ORM.

CockroachDB will provide more support for GORM in 20.1. Currently, there is a tutorial for getting started but it may need significant updates given the increase in functionality.

Team: Andrew Woods, Rafi Shamim, Richard Loveland

Github Tracking Issue:

**Comment by ericharmeling** [comment]
Closing, as this is no longer on the AppDev roadmap.
