### ISSUE TITLE
[Docs] Django Tutorial 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6041]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recPtOOg7ouJRD68C

Description: We now have a sample getting started guide for using this ORM.

CockroachDB will support the Django ORM in 20.1. Currently, there is no getting started tutorial for this ORM. 

Team: Andrew Woods, Rafi Shamim, Eric Harmeling

Github Tracking Issue:

**Comment by jseldess** [comment]
This can be based off of the example here: https://github.com/cockroachdb/docs/blob/master/v20.1/build-a-java-app-with-cockroachdb-hibernate.md

**Comment by jseldess** [comment]
@rafiss, please let @ericharmeling or I know if you need any support here.

**Comment by jseldess** [comment]
@dbist also wrote up some instructions that may come in handy: https://docs.google.com/document/d/1GHU9OiFe8DECRYA26kx1c1kveLbTRY29ZzLuWPbbmzM/edit?ts=5ddedcf9

**Comment by dbist** [comment]
better examples https://blog.ervits.com/2019/11/how-to-use-cockroachdb-with-django-and.html and https://blog.ervits.com/2019/11/how-to-use-cockroachdb-with-your-django.html

**Comment by jordanlewis** [comment]
@apantel is planning to get this done the week of January 6th.

**Comment by ericharmeling** [comment]
I believe this is fixed by #6359.
