### ISSUE TITLE
[Docs] Peewee Tutorial 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6042]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recOxcYmSvhTwFrVO

Description: We now have a sample getting started guide for using this ORM.

CockroachDB will support the Peewee ORM in 20.1. Currently, there is no getting started tutorial for this ORM. 

Team: Andrew Woods, Rafi Shamim, Eric Harmeling

Github Tracking Issue:

**Comment by awoods187** [comment]
Peewee now supports CockroachDB. We should add it to the docs page.

https://www.cockroachlabs.com/blog/peewee-orm-cockroachdb/
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#cockroach-database
