### ISSUE TITLE
[Docs] Re-launch SQLAlchemy Tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6044]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recLSjxOweOZhITO1

Description: We now have an improved getting started guide for using this ORM.

CockroachDB will provide more support for SQLAlchemy in 20.1. Currently, there is a tutorial for getting started but it may need significant updates given the increase in functionality.

Team: Andrew Woods, Rafi Shamim, Richard Loveland

Github Tracking Issue:

**Comment by ericharmeling** [comment]
@rafiss @awoods187 
Are there any updates that need to be made to our SQLAlchemy docs? If not, I'm going to close this.

**Comment by rafiss** [comment]
Yes, we will want to update some things. One item I definitely would like to do is rename the package in pypi -- right now the package is named `cockroachdb`. It should be renamed to `sqlalchemy-cockroachdb`. Also @awoods187 we should see if we can get on this page, once we're ready: https://docs.sqlalchemy.org/en/13/dialects/

**Comment by ericharmeling** [comment]
@rafiss @awoods187 

Is this in scope for 20.1?

**Comment by awoods187** [comment]
Yes--I don't think the docs lift is heavy at all. It'll mostly be a rename of our dialect.

**Comment by ericharmeling** [comment]
@rafiss We updated the docs following the adapter rename. Are there any other updates that we might need to make to docs? If not, I'll close this issue.

**Comment by rafiss** [comment]
There shouldn't be anything else. Thanks!
