### ISSUE TITLE
[Docs] Re-launch Hibernate Tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6045]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recUwgqwu9ozzLnSi

Description: We now have an improved getting started guide for using this ORM.

CockroachDB will provide more support for Hibernate in 20.1. Currently, there is a tutorial for getting started but it may need significant updates given the increase in functionality.

Team: Andrew Woods, Rafi Shamim, Eric Harmeling

Github Tracking Issue:

**Comment by ericharmeling** [comment]
I'm closing this in favor of #5992.
