### ISSUE TITLE
[Docs] Remove of savepoints from Java, Ruby, and Node driver/ORM documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6047]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recziV8w8VyG54oRz

Description: CockroachDB docs examples now do not mention savepoints in their retry logic examples. 

Team: Andrew Woods, Rafi Shamim, Richard Loveland

**Comment by ericharmeling** [comment]
This issue is covered by #6057.
