### ISSUE TITLE
[Docs] Complete all removal of savepoints from remaining driver/ORM documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6057]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recT97d2o3ZqZEnWP

Description: CockroachDB docs examples now do not mention savepoints in their retry logic examples. 

Team: Andrew Woods, Rafi Shamim, Richard Loveland

**Comment by ericharmeling** [comment]
Duplicate of #6271.
