### ISSUE TITLE
Onboarding V2 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6060]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recgk0npN9S9w0M6z

Description: When CockroachCloud users sign in to the console for the first time, they are presented with various onboarding material. This depends on the type of user they are (developer, or admin) and the number of times they've already visited the console (first time v nth time) and if they've previously done any onboarding tasks. 

When a user signs into the console for the first time, its not obvious what they need to do. Onboarding helps remove friction for first time users (as well as nth time users) and helps increase adoption and customer success. 

Team: Lucia Cozzi, Jeremy Bloom

Github Tracking Issue:

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7454/
