### ISSUE TITLE
Provide full support for "delimited" IMPORT format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6063]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recrfAbhSAqoYUmjI

Description: 

Team: 

Github Tracking Issue:

**Comment by lnhsingh** [comment]
it seems like nothing further needs to be added to [documentation](https://www.cockroachlabs.com/docs/dev/import.html#delimited-data-files).
