### ISSUE TITLE
Make EXPORT operations jobs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6065]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/reckJOuIfaskEA6r0

Description: The long-running parallel EXPORT statement functions as a job, so it shows up in the jobs view and can be paused, resumed, and canceled like other jobs.

Long-running EXPORT jobs do not provide any indication of their progress or status. They can produce files to a cloud storage location without the user being able to validate that the full set of data has been written.

Team: 

Github Tracking Issue: https://github.com/cockroachdb/cockroach/issues/28213

**Comment by lnhsingh** [comment]
This seems to have been de-prioritized for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
