### ISSUE TITLE
Jobs UX improvements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6067]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recNJgRQMFykcmrVv

Description: Improve jobs UX, debuggability, control. May entail a jobs debug page, improvements to the web UI jobs view, and other fixes.

Team: 

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Seems like the changes made for v20.1 won't need docs or are covered in CLI. @mwang1026, can you confirm/correct?

**Comment by mwang1026** [comment]
That's right. No documentation.

**Comment by lnhsingh** [comment]
Thanks, closing this issue.
