### ISSUE TITLE
Improve IMPORT parallelism when reading a single file

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6068]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recaC3IUv9vbR8ge1

Description: When importing data, CockroachDB can utilize resources across all CPUs of all nodes regardless of how many input files are present.

Team: 

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Out of scope for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
