### ISSUE TITLE
Add 19.2 slides to Release page

### ISSUE THREAD

**Issue by meagan-g** [cockroachdb/docs#6080]
We'd like to add the "What's New in 19.2" slides to the 19.2 Release page: https://www.cockroachlabs.com/docs/releases/v19.2.0.html

These are the slides to add: https://docs.google.com/presentation/d/18PwQDEpOGTsgd3Nyzv2wXha3FNl6Ev7Ff7pp4tGztcw/edit?usp=sharing

Thank you!

**Comment by meagan-g** [comment]
cc @jseldess

**Comment by jseldess** [comment]
@meagan-g, I'm sorry I missed this. I assume we don't want to do this so late, so I'll close. But please let me know if you disagree, or if you want me to add slides to the 20.1 release notes.
