### ISSUE TITLE
Create IMPORT/BACKUP examples without cloud storage

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6083]
A user on our community Slack:

> I'm looking at the docs about importing a database from an existing database dump from another database type, what's the easiest way without cloud storage and just a few containers? I'm just trying to test an import. I looked at the nodelocal stuff but not sure I fully understand how that works or whether it's what I need

My response: 

> we really need to improve our end-to-end IMPORT guidance for different scenarios, including using local storage. Have you seen the options here https://www.cockroachlabs.com/docs/stable/import.html#import-file-location
>
> Option 1, using a local file server, might be easiest: https://www.cockroachlabs.com/docs/stable/create-a-file-server.html. Unfortunately, we don’t have explicit instructions on leveraging that for IMPORT. I’ll make sure we get that docs work on the backlog. 

This comes up fairly regularly, I think, for import, backup, and restore testing. 

Related 20.1 roadmap items:
- https://github.com/cockroachdb/docs/issues/6010
- https://github.com/cockroachdb/docs/issues/5905

Related docs improvement requests:
- https://github.com/cockroachdb/docs/issues/3724
- https://github.com/cockroachdb/docs/issues/4814

**Comment by jseldess** [comment]
cc @rolandcrosby

**Comment by jseldess** [comment]
More details from the Slack thread, from @dt: 

Anyway, in 19.x, my suggestions would be
a) single-node cluster while  nodelocal and copying to extern dir woks as expected.
b) multi-node cluster, and spin up a tiny local http server to make your import files network-accessible to your cluster (e.g python3 -m http.server or caddy is my personal favorite).
c) multi-node cluster and use nodelocal after manually copying every file to every extern dir

**Comment by lnhsingh** [comment]
Related issue: #6086

**Comment by dt** [comment]
fwiw, in 20.1, this is going to be much simpler -- you will be able to just put files on any one node and then reference them -- so if the docs changes discussed here wouldn't be happening in 19.x docs anyway, we might want to just hold off and document the new flow when it lands?

**Comment by jseldess** [comment]
From https://github.com/cockroachdb/docs/issues/6086:

> Nodelocal information for doing import is not intuitive. Based on conversations in the community slack, good to create official document until a more permanent solution is being developed in the future release. Here's a good starting [point](https://blog.ervits.com/2019/12/using-cockroachdb-with-nodelocal-storage.html).
