### ISSUE TITLE
CC accept invite error message

### ISSUE THREAD

**Issue by laurenbarker** [cockroachdb/docs#6085]
What should the language be for the title of the error message? Right now it's "Accept Invite Failed".

Related to https://github.com/cockroachlabs/managed-service/pull/1792

<img width="602" alt="accept-invite-from-error--after" src="https://user-images.githubusercontent.com/7131985/69978682-e1bf1f80-14fa-11ea-8f25-1543a631b048.png">

**Comment by laurenbarker** [comment]
@Amruta-Ranade

**Comment by Amruta-Ranade** [comment]
What are the reasons for the failure and what do they need to do to fix it?

**Comment by laurenbarker** [comment]
The user would only see this error if something went wrong on the backend so they probably wouldn't be able to do anything to fix it. They would likely have to contact to support. Right now it's set to display the error that is thrown but we could display a consistent message instead.

**Comment by Amruta-Ranade** [comment]
Okay..in that case, I suggest "We could not process the request. Please contact [Support](https://support.cockroachlabs.com/)."
