### ISSUE TITLE
Improve nodelocal documenation

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6086]
## Description
Nodelocal information for doing import is not intuitive. Based on conversations in the community slack, good to create official document until a more permanent solution is being developed in the future release. Here's a good starting [point](https://blog.ervits.com/2019/12/using-cockroachdb-with-nodelocal-storage.html).

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6083.
