### ISSUE TITLE
Memory management and best practices

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#6087]
Exalate commented:

## Title

Fine-tune `max-sql-memory` best practice.
 
## Description

Encountered `getting Error: pq: windower-limited: memory budget exceeded: 112146104 bytes requested, 10240 currently allocated, 67108864 bytes in budget` while running `insert into fac_chrg select row_number() OVER () as fac_id,* from (select current_date(), random()::string, chrg_id from chrg_cd limit 7985445);`

## Outline

`max-sql-memory` describes how much RAM all SQL processors can take up on the whole cluster whereas `sql.distsql.temp_storage.workmem` is how much memory a single processor of a single query can use, so the former is “global” whereas the latter is “local”

There are couple other settings that describe how much memory joins and sorts can use before they are forced to spill to disk, but all other memory-intensive operations look at `sql.distsql.temp_storage.workmem`

cc https://cockroachlabs.slack.com/archives/C8HD41C82/p1575302414002600

potentially other issues to consolidate this:

- https://github.com/cockroachdb/docs/issues/5923

## Expected Audience

Developers and DBAs

Jira Issue: DOC-383

**Comment by robert-s-lee** [comment]
@drewdeally @a-entin might be a worthwhile to write a blog on this.   I can capture the info from YCBS and TPCC tests and start to gather some data points.

**Comment by drewdeally** [comment]
ycsb perhaps not - no joins or query which use memory - not even sure on TPCC.  I would think TPCH

**Comment by intech** [comment]
I need your expertise in investigating an [explain query](https://cockroachdb.github.io/text/decode.html#eJzsW-ty4sgV_j08xSn-WMpKslro2hOyYbC8ywbjKWAmO3G5KBkarDWWKF3W602laivP4J95unmSVOsCEnfJY2Zsr3-4UJ9z-nR_59YNRzwPH4nn266DoekObzzXGl6fvINmsw2_SqKABA2Y33R1oMp86Nw47p3DT20n_I2fOCEHV6E9DUASJfEYicdIAqRiUcaSxMHERQKqCQZbqfA8eMT1RsQb_OLajj-Y2rd2ANeWD8E1gREZW-E0gF-taUgwyJSfONbVlAx-tye_W5NIahO761B-dxbYt_bvxBuMXY_YE2dwQ-79LTKVZtds9E3oN961TfCvLY_4wFTehKE9gg8fWifQOe9D50O7DSfmaeNDuw8T4gw8yxm5twPKxbBc5U019IlXzQtwlTd3rndDvJXhq6k7vFkZHdnjsT0Mp8E9tDp9PUvyyJ3ljeBjo9v8sdFlkMhmqUOPWAEZQb91Zvb6jbP3_X-trnoYeh5xgkFg3xI_sG5nDIsxzohwlTfN806v3220Ov0EicHsBt53W2eN7if4h_kJmAiWRq_JruWmIPiD8Q2cnnfN1g-dWCbGhoWueWp2zU7T7EHEGE3GwnkHTsy22Teh2eg1GycmHfnw_qSxGFmrLMZ2VV08nlOXsD5SYWS1VX3RcE5dzPhIbbHJV9XF4zl9CSvjWLdkX4Wtzon5c6rLCgN3YDsj8ttg2ZKJ9VKb7xDL2CSxw56CC2xjPPcUy4CUAJMKnjbOWu1PUJ159q3l3Vdj1-Ug3g6XuAQX24qDRexxCZwcJGHFVti3leb52ZnZ6VMoc5mi1YOjXvzRHceTHb2tVBrtvtlNOGehR66CoTALr6b2UEgFOz-ZzT70-o1-q9dvNXtwdFEBAPh39J_-VYfuNLx1_CqGi_lgRKBbqc6HLrmMSLzmgRVUMVRpQuaRyEsiSBIWdSypgqYZWq32nShiUaxmJEe2H9jOMBgM3dCh0rqhqaqe4bi2_cAdDN3pILifETo_zWDZOagD0vFBbKpBjhZOp_O5xQzBc-_m44ZI_yLaf7j94aAmfWo4kGEg4zmgEXv20-OhIwWpzwGQKCqfHg_lOWAR57YnB6O2FYtev9vq_PANoLHI-k-OiIy2QvINgJFs9smRoKtTtzvIN4BGuRKLJCxKgiqrkmH8WWKLwvHiS2xRPF56iS2Kx4susQXBeAUltiAiL7jEFkTieZTY8mjUsKgKsqaoGtorjYpINrbnji8KB9IPWWMLgnH4GlsSjtJFtqh3HL7IlnWQcmfSgnhohioZ2rMApHSpLQbJwUttSTgeVWuLQXLIWlsSjbJn0oLhcuAz6aFSBwJRxIqCZU1QtZqqyC8sdRQutqUAecnFthQgz6fYFk8fpQB5HumjRKEtg8YLL7RlIHkGhbbMPa5c8ngm97hytVbFSk0wFF1WpD3AkFRD0uTtAfPFs4ekHbLWFgPkK9TaknCUrrUFAfkKtbYkImVrbUFADlxrS4JRutYWQ-PgtbYkHI-qtcUgOWStLYlG-VpbsLxoNSQp8lfCo3J59HapMzNuECvRmXlt-deLxklFZOddk67tbOqovCb25DpYacPc3aF5YjZbZ402g0ROz804JmQDcb560eR1jHHCxVXe-IEVhD5VJa3hxhjTRTxR_2fSkLdn_2fCPYy6eun_lbZFOphrWox4k-EiLYvVd7GuTDPgOu3VWOWudkDqHVy0Fg5io6_vBRwTwkFsjx2NgYmjtnpwdGY7tjNJRna0BaZih24LRFjWMDKEmowMQ9kjM4iHywnFs6NrO68aAOrOrxuAKIZfNQTlfwV4UTCU-23oRUEwJuRV7z-u168agpI9Fs8Ag_iOYP78vt1odYA5f9_n4KPZfXfeMzkwOx9Z6JltepYKhL9w4Ie38Nc6SHDaPT8DJiH5CYnxhczR_hiuMo8snH80u8Ccd0_MLrz7BL6QnrdPzF6ThUYvmj2aOHm5gw5B2zztw0_nrU56JGz04IqeE6-E6BRdBz8-9cE_fzS7JvhCcoeow9FsNnX8o2juICUnO3hb4Xmer8w89xcyDCrw-eF_nx_--PzwByROgIFOj1H0khWWkjddcC1eBpYz51usJAdcrKaHWqxRTRhpUP0-nvD7KkZGVo9vjwhPxmMyDPzceGAFPoYLz73z68jQZf0yvzw_wIBkDYmiLMh6lnZD7jEwiM2OjUcYGJbn_8aoLEeJ9KPEK5zGIY1DRo555oUOoVPw66g-mSZY_Zf6zhrIfGEHaFkPwcrcWFhd-MMCOj-8HaCB5U0QRvoatcsILpNXgKSXkjjiGKSx6RgNl-hZvFy7twRvURU1QUFrWLKwL5F2oK-vk7mznZF7BzPLC-zAdp06w0L0uqftTOq8Bu4sYNSs4Ne1xn5G2WYbxVBkOWsbNhqSBEOTpdQ-bF3MsEjUeiJSBAMpKGGR8iw1tq5IUk0UJKSnVq7lWWS2ngrLeYrC1uWUpORJ6kJIzVM0Nt1KRNXyVLRERst0PaOTPuTccaNXikgSRHUz5xrnLOCj-ha5RbJQOaRtZZwn2TzDRsfNutoXcuOd2rc77p_-u5d_bndTZafAZm99pNNu9N39-G3HIR4fvTjPTF33Jpwlh5TNok-clePjD9ZzpyyMpH3Xc0PuF2u6QJdQp__3lU4wSCYAyyN0wn2lX2H06As5fUkZh6SsvuhxS2xtCDFV1yUkoDWVoGSk7R1w9FGPHpFEP8tsvc7o8Wi9zsh7q9gYZH_f_cL7TiU7wzENv7KBtTW-9Ci-5J1W3XqEjfoo8pGCNMPQa4KsGOsjZbOPb3ZI6n_zPL-XL651yZqqSdQj5eLA7eWY6_wz64axh8qlPHLZDEPLgas9hTY52iP9aqtnPK1d12ccAdXKyccG3lJ0C9i53Bxp9de5wlM8zHNVQDxCkZ3ML2c-Bua7vfeVzjS2pwHxfGACLyQ7hZektrNDXiZzkph_OQIXbhgQrx5l9aHr-IFn2U7g15ljFcPFccrGQ_rx8i0E9uQ6YDkYj-ppSdjsSw_5W4DtOptWvbLc3DnoeDlw4MLy67mrAgfJZqIiyuWO9GsW-JC7cK-sank54W2qESNtrgrpq3uH9eJrr8-bDLoqTi_h0ZdvqcmQtmIzpGFgjqNfrHk4lua2ipa41hLb9Fh-Pff11WLTGntZ-X8AAAD__z4lW50=). It is necessary to understand whether this problem takes place?
The request is associated with error 532000 windower-limited: memory budget exceeded.

The graph was built from the message above.
![Снимок экрана от 2020-10-21 04-31-56](https://user-images.githubusercontent.com/451306/96662200-7c645f00-1356-11eb-887b-7f1768e8dd59.png)

And how can the memory size for the window request be increased?

**Comment by yuzefovich** [comment]
We have a private cluster setting (i.e. not explicitly documented) `sql.distsql.temp_storage.workmem` that determines how much memory a single processor in the query can use before it must spill to disk or bail on the execution. By default it is `64MiB`.

**Comment by intech** [comment]
@yuzefovich thanks!
Increasing to 100Mb solved the problem
`SET CLUSTER SETTING sql.distsql.temp_storage.workmem = '100MB';`

**Comment by intech** [comment]
Is it possible to set this parameter by default somewhere? Or can it be configured only through a query?

**Comment by yuzefovich** [comment]
Great to hear that it helped!

No, this cluster setting can only be changed via a query, but note that it is a "cluster setting" meaning that once set, it'll be that new value for all connections of the cluster.

**Comment by robert-s-lee** [comment]
@intech this can be verified by running `show cluster setting sql.distsql.temp_storage.workmem;`.  The example below showing the difference between `MB` use to set and `MiB` used in show. 

```
> SET CLUSTER SETTING sql.distsql.temp_storage.workmem = '100MB';
show cluster setting sql.distsql.temp_storage.workmem;
  sql.distsql.temp_storage.workmem
------------------------------------
  95 MiB


> SET CLUSTER SETTING sql.distsql.temp_storage.workmem = '100MiB';
SET CLUSTER SETTING

Time: 10.601ms

root@:26257/defaultdb> show cluster setting sql.distsql.temp_storage.workmem;
  sql.distsql.temp_storage.workmem
------------------------------------
  100 MiB

```

**Comment by intech** [comment]
@robert-s-lee oh, good point!

**Comment by intech** [comment]
@robert-s-lee tell me how the memory allocation in the window function will work:
1. the required amount will be allocated depending on the ranges located on the node.
2. the virtual table will be created on one of the nodes and the required memory limit will be needed only on this node.
3. memory will be allocated on each node according to the virtual table

**Comment by yuzefovich** [comment]
@intech here is some info. Keep in mind that we distribute the computations of the window function based on `PARTITION BY` clause (all rows belonging to the same partition must end up on the same node), so if the query doesn't specify `PARTITION BY`, then all the computations is done on a single node (the gateway).

There are three big users of memory space when computing the window functions:
1. we buffer up all the input data belonging to partitions that are assigned to the node, with no `PARTITION BY` clause that will be all of the input data
2. we separate out those - possibly multiple - partitions on the node and compute window functions one at a time
3. for every partition on the node we compute each window function and store the result of computation in memory.

Note that we don't emit any output until we have fully processed all window functions of all partitions on the node.

Going back to the discussion about the memory, we use disk-backed data containers for steps 1 and 2 (meaning that we can use temporary disk storage to store that data), but step 3 always keeps the result of computation of window functions in memory. It's likely that you're hitting a limit in that third step. Additionally, while looking through the code right now, I'm currently not sure whether we correctly fall back to disk in steps 1 and 2 in all of the cases (there might be a bug that would force us to mistakenly think we're still using the memory although we have spilled to disk and prevent new memory allocations for step 3 to occur even though they are within `workmem` limit), I'll need to double check that.

**Comment by intech** [comment]
Very detailed and helpful answer. Many thanks.
If there is new information, leave in this issue, please.

I have some questions about the operation of the window function, I noticed that indexes are not used and all data inside the window function itself is selected, although there is a `where` in the query and the result really comes filtered.

At the same time, I see that instead of using the `where` clause of 900k records, total records (2.7kk) are selected, and after that it filters.

I tried to specify the index manually, then the request time increases several times, it selects 2 times. From the main index and specified by me and then combines from it.

I don't understand why this is happening, and even more questions arise about the correctness of such behavior.
![2020-10-22 23-05-57](https://user-images.githubusercontent.com/451306/96924419-4c829c00-14bb-11eb-9286-8cb2a89e91ea.png)

**Comment by yuzefovich** [comment]
`Windower` processor itself doesn't read the data from disk at all - all scan operations are done by the `TableReader` processor, and it is up the optimizer to decide which index to use in order to scan all the required data.

In the first case, the optimized chose to do a full table scan (on the primary index) with a filter on top, so that's why we see that 2.7m rows were read by the table reader but only 900k by the windower - other 1.8m were filtered out.

In the second case you forced the use of a secondary index, so now the optimizer use it for scanning, and the table reader scanned the desired 900k rows. However, that index doesn't contain all the columns that are needed to populate the end result (for window functions - arguments and ORDER BY clause - and for the final projection), so now we need to do a lookup join - from `shares_reward_index` we can only obtain `reward` and  `uuid` columns, but we also need `created` and `difficulty`, so we are performing a lookup using `uuid` column into the primary index to get those. And regarding the running time, it appears that the optimizer correctly estimated that the second plan is less efficient and only the index hint forced it to use that.

Hope this makes sense.

**Comment by intech** [comment]
@yuzefovich I can't remember the last time I received such prompt and high-quality support! You are best!

Based on your comment, I can make an index with the necessary `storing(uuid, difficulty, created)` fields and thereby reduce the number of readable records? Since this base is just a small test, in the original billions of records.

**Comment by yuzefovich** [comment]
Yes, I believe if you make such an index, then that index should be used by the table reader and there will be no filtering needed. Glad I could help :)

**Comment by intech** [comment]
@yuzefovich We have reduced the time several times!
![2020-10-23 02-26-18](https://user-images.githubusercontent.com/451306/96939987-308cf380-14d7-11eb-8353-2ed5d7a541f2.png)

**Comment by robert-s-lee** [comment]
@drewdeally try `SET CLUSTER SETTING sql.distsql.temp_storage.workmem = '100MB';`

**Comment by jseldess** [comment]
@awoods187, @ianjevans, @ericharmeling, I think we need to think about a more holistic doc around memory management and best practices. I've renamed this issues accordingly, but if you feel this issue should remain more specific, please change back.

**Comment by awoods187** [comment]
Yes, I agree. It partners nicely with https://github.com/cockroachdb/docs/issues/7221 which we view as a p1 for this release.
