### ISSUE TITLE
sql: Clarify how BYTES and STRING types differ

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#609]
Jesse:

> It looks like the `string` and `bytes` types are identical. Each seems to accept the same inputs. And Matt Jibson tells me the internal format is the same for them, too. Do you happen to know why we've kept them as distinct types instead of making one an alias for the other?

@tamird:

> They’re not identical. In particular, some functions behave differently for `string` and `bytes`. For example `LEFT(<thing of type bytes>, 5)` will return the 5 leftmost bytes, while `LEFT(<thing of type string>, 5)` will return the 5 leftmost characters. The result is the same if the string is comprised only of ASCII characters, but not if it contains 2,3, or 4-byte characters.

**Comment by jseldess** [comment]
Watch https://github.com/cockroachdb/cockroach/issues/9059 for further details.

**Comment by jseldess** [comment]
Demo that some functions behave differently for `string` and `bytes`:

```
root@:26257> create table f (x string, y bytes); 
CREATE TABLE 

root@:26257> insert into f (x, y) values ('\xff', b'\xff'); select length(x), length(y) from f;
+-----------+-----------+
| length(x) | length(y) |
+-----------+-----------+
|         4 |         1 |
+-----------+-----------+
(1 row)
```

**Comment by jseldess** [comment]
Summarization from very helpful discussion with @knz:
1. both `string` and `bytes` columns use bytes internally
2. but some functions behave differently for `string` and `bytes` columns, e.g., `length()`
3. and there are some combinations of bytes that are valid in a `bytes` column but invalid in a `string` column

Demo of point 3:

```
root@:26257> create table e (x string, y bytes);
CREATE TABLE
root@:26257> insert into e(y) values (b'\xff');
INSERT 1
root@:26257> select CAST(y AS string) from e;
pq: invalid utf8: "\xff"
```

**Comment by knz** [comment]
yep, that's it.

For LENGTH the difference can be phrased as follows: LENGTH(bytes) measures the number of bytes; whereas LENGTH(string) measures the number of characters, or more specifically "unicode code points" present in the string.  Each character (or unicode code point) can be encoded using multiple bytes, hence the difference in output between thet wo.
