### ISSUE TITLE
test Helm chart refactor + document as needed

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#6091]
A community member has refactored the Helm charts to add various improvements. 

https://github.com/helm/charts/pull/18993/files

This may impact our documented guidance and/or examples when using Helm:

- `--set` commands will no longer work, as parameters have changed to conform to the Helm standard. Instead, we should instruct users to create a custom .yaml and use the `--values` flag to override the defaults.

Relates to #5931

Note: The chart version has been updated to `3.0.0` but this is not related to the Helm 3.0 update.

**Comment by MichaelHudgins** [comment]
The helm instructions on the secure install appear to be incorrect now.
https://github.com/cockroachdb/docs/blob/master/_includes/v20.1/orchestration/start-cockroachdb-helm-secure.md

At a minimum the helm instructions now leave you with an insecure instance.  It appears tls.enabled needs to be set to true.  Still doing an initial eval of cockroach so I am unsure of other settings.

**Comment by jseldess** [comment]
@randmark, this is the issue we were talking about. @taroface, we should prioritize this over the next few weeks given our secure instructions result in an insecure cluster.

**Comment by taroface** [comment]
This is addressed in https://github.com/cockroachdb/docs/pull/6121
