### ISSUE TITLE
Prep for Docs Fixit session

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6098]
**Description:** Did you know our docs are open-source and that anyone can help improve them? In the Docs Fixit session, that's just what we'd like you to do! If you're close to the product, you can help us fill gaps in our coverage or correct inaccuracies in our content. If you don't know our product deeply but are a close reader, you can help us find and fix spelling and grammar mistakes and otherwise suggest changes to improve clarity. For people new to GitHub, you can also take this opportunity to get your feet wet with that tool and workflow; we'll have materials to get you set up, and several Education team members will be present to offer support along the way. 

**Awards:** We'll award three distinct awards. One will go to the person who's contributions most benefit developers. One to the person who fixes the worst error. And one to the person who makes the greatest impact for the Docs team.

**Comment by jseldess** [comment]
@lnhsingh, @Amruta-Ranade, can you two send me any resources you have from past sessions at WTDs or elsewhere?

**Comment by lnhsingh** [comment]
I can't seem to find the Google Doc, but here's the published description I posted, which lifted some language from Amruta's, the year before: https://www.writethedocs.org/conf/portland/2019/writing-day/#write-cockroachdb-docs

**Comment by jseldess** [comment]
Thanks for that, @lnhsingh. And do you remember what resources we used to get people up and running?

**Comment by lnhsingh** [comment]
@jseldess we just pointed them to the [Contributing guide](https://github.com/cockroachdb/docs/blob/gh-pages/CONTRIBUTING.md), which seems to be missing?
