### ISSUE TITLE
Update `zone set` command in troubleshoot.md

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#611]
troubleshoot.md contains an outdated command for configuring the cluster for a single replica. The new command is 

`cockroach zone set .default -f - <<< 'replicas: [attrs: []]'`

**Comment by bdarnell** [comment]
@knz suggests the following instead, which is compatible with non-bash shells:

`echo 'replicas: [attrs: []]' | cockroach zone set .default -f -`

**Comment by jseldess** [comment]
Thanks, @bdarnell and @knz. I missed this in https://github.com/cockroachdb/docs/pull/602.

**Comment by jseldess** [comment]
@sploiselle, would you mind including this in your open PR https://github.com/cockroachdb/docs/pull/610?
