### ISSUE TITLE
fixit: rust driver code examples have wrong cockroach start instructions for secure/insecure

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#6125]
v19.2.1 docs look good but 19.1.5 and 2.1.9 have the insecure steps for the secure option.

The fix: 
1. Change the flags
2. Add a step about generating certificates.

See https://www.cockroachlabs.com/docs/v19.1/build-a-rust-app-with-cockroachdb.html

**Comment by nvanbenschoten** [comment]
@mattcrdb this was fixed by https://github.com/cockroachdb/docs/pull/6128, right?

**Comment by mattcrdb** [comment]
Yep!

**Comment by nvanbenschoten** [comment]
Great! Feel free to close this then 😄

**Comment by mattcrdb** [comment]
Absolutely, thanks for checking in.
