### ISSUE TITLE
fixit: covering indexes

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#6127]
Exalate commented:

We have sometimes heard the term, covering indexes, but it's not clear from our docs whats this means or when it is needed. 

Here's and older [forum post](https://forum.cockroachlabs.com/t/select-query-not-responding/672/32?u=ronarev) that seems to be related to creating a covering index. 

We reference the key word in our docs, but do not explain why this is beneficial for improving SQL performance. 

Jira Issue: DOC-389

**Comment by andreimatei** [comment]
I'd add a definition if somebody tells me where.

FWIW, a "covering index for a query" is an index that stores all the columns needed by that query - so a join with the PK is not needed if that index is used. We accept `COVERING` as a synonym for `STORING` in index definitions.
