### ISSUE TITLE
fixit: Cockroach Cloud upgrade process documentation 

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/docs#6141]
It would be worthwhile to have a separate documentation page specifically for the process of upgrading when using a Cockroach Cloud cluster. Specifically, what the SRE process is and how to opt-in, opt-out of the upgrade process if desired from a customer perspective. The only page that mentions upgrades currently is [here](https://www.cockroachlabs.com/docs/cockroachcloud/stable/).

**Comment by Amruta-Ranade** [comment]
Addressed in https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-upgrade-to-v20.1.html
