### ISSUE TITLE
CREATE CHANGEFEED Doc Update 

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#6151]
Re: [CREATE CHANGEFEED](https://cockroachlabs.com/docs//v19.2/create-changefeed.html)

## Issue Description
It is not very clear today that you have to specify `experimental-http` or `experimental-s3`, especially when looking at https://www.cockroachlabs.com/docs/stable/create-changefeed.html#cloud-storage-sink. Also, we don't list them here either: https://www.cockroachlabs.com/docs/stable/create-changefeed.html#example-file-urls. 

Also, it looks like we copied this information from the `IMPORT` documentation because we provide URLs like `http://localhost:8080/employees.sql`, which is not correct for CDC. 

## Suggested Resolution 

We should add `experimental` to all the URLs which need them on the page. We should also not referrer to specific files as part of the URL.

**Comment by jseldess** [comment]
@mwang1026, @lnhsingh, is this still a docs need?

**Comment by mwang1026** [comment]
Unfortunately ya. We hoped to remove experimental in 20.2 but didn't. So probably a good candidate for the 'CDC batch of small changes'

**Comment by lnhsingh** [comment]
@gemma-shay this might be a good issue for you to take. Feel free to ping me for more info if you decide to pick this one up.
