### ISSUE TITLE
double `$` prompt showing in 19.2 upgrade instructions

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#6161]
In our 19.2 upgrade docs, we have a double `$` prompt for the mac & linux instructions. [Link here](https://www.cockroachlabs.com/docs/v19.2/upgrade-cockroach-version.html).

It's on step 4 of upgrading from a previous version. 

> If you use cockroach in your $PATH, rename the outdated cockroach binary, and then move the new one into its place:

```$ $ i="$(which cockroach)"; mv "$i" "$i"_old```

**Comment by jseldess** [comment]
Good find. I'll fix real quick.
