### ISSUE TITLE
release-19.2: cli, sql: allow usernames to start with digits

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6177]
PR: https://github.com/cockroachdb/cockroach/pull/42989

From release notes:
> Client usernames can now be defined to start with a digit; in particular, all-digit usernames are now permitted. [#42989][#42989] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/6284.
