### ISSUE TITLE
release-19.2: opt: backport two pg compatibility fixes for GROUP BY

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6181]
PR: https://github.com/cockroachdb/cockroach/pull/42694

From release notes:
> It is now supported to specify selection target aliases as `GROUP BY` columns. Note that the `FROM` columns take precedence over the aliases, which are only used if there is no column with that name in the current scope. [#42694][#42694] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
See https://github.com/cockroachdb/docs/issues/6180.
