### ISSUE TITLE
opt: inline constant variables in Select filters

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6188]
PR: https://github.com/cockroachdb/cockroach/pull/42151

From release notes:
> Filters of the form `x = D` (as in `SELECT * FROM t WHERE x = D AND f(x)`), where `D` is a constant and `x` is a column name, will now cause `D` to be inlined for `x` in other filters. [#42151][#42151] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This looks like an optimizer thing that doesn't really need documentation.

@RaduBerinde Do you disagree?

**Comment by RaduBerinde** [comment]
I agree.
