### ISSUE TITLE
sql: fill in pg_catalog.pg_index.indoption

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6191]
PR: https://github.com/cockroachdb/cockroach/pull/42343

From release notes:
> `pg_index.indoption` now correctly conveys ascending/descending order and nulls the first/last positioning of columns in an index. [#42343][#42343] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
This function isn't exposed in our auto-generated docs. Not sure if that's a problem.

**Comment by ericharmeling** [comment]
We don't expose any `pg_catalog` functions in documentation. These are internal functions that (as far as I know) we support for postgres compatibility. This is an area that #https://github.com/cockroachdb/docs/issues/6272 can elucidate.

Here's the postgres docs on `pg_index` functions in particular: https://www.postgresql.org/docs/current/catalog-pg-index.html
