### ISSUE TITLE
opt: populate autocommit correctly under EXPLAIN

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6194]
PR: https://github.com/cockroachdb/cockroach/pull/42500

From release notes:
> `EXPLAIN (VERBOSE)` now indicates if auto-commit will be used for mutations. [#42500][#42500] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Explain https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/rec4nN8PXF6Tkge92

**Comment by rmloveland** [comment]
Hi @RaduBerinde 

I have questions about the "auto-commit added to EXPLAIN" functionality after looking at the PR cockroachdb/cockroach#42500:

1. I found a comment in `pkg/sql/tablewriter.go` that says "An auto-txn can commit the transaction with the batch. This is an optimization to avoid an extra round-trip to the transaction coordinator."  This makes it read like "auto-commit" is an optimization in the transaction protocol.  Is that correct?
2. In general, these sorts of optimizations are something that I would consider internal, not user-facing.  Especially at the level of a user looking at an EXPLAIN statement, I would not expect them to be able to jump down layers conceptually to the transaction protocol and the transaction coordinator.  Do you agree with this assessment?
3. In the PR you (seem to?) say the purpose is "We can now test the planning part of auto commit without using traces".  This also makes it seem like the change is for internal testing purposes, not necessarily for users.

All of the above add up to me thinking this is not something that should end up in SQL-user-level `EXPLAIN` docs, and we can close this issue.  Do you agree?  Or am I missing something?

**Comment by RaduBerinde** [comment]
I agree - this is mostly for our benefit and for internal testing.
