### ISSUE TITLE
opt: hoist WITHs to the top level

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6195]
PR: https://github.com/cockroachdb/cockroach/pull/41033

From release notes:
> Mutations in CTEs not at the top level are no longer allowed. This restriction is also implemented by Postgres. [#41033][#41033] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
related to recursive ctes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/rec06cPoJb6dHNk5a
