### ISSUE TITLE
builtins: fix extract from timestamptz to be ctx time zone aware

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6199]
PR: https://github.com/cockroachdb/cockroach/pull/42632

From release notes:
> Changed [`extract()`](../v20.1/functions-and-operators.html) on a `TIMESTAMPTZ` to match the environment's location in which `extract()` is executed. Previously, it would always perform the operation as if it was in UTC. Furthermore, `timezone`, `timezone_hour` and `timezone_minute` are added to the `extract()` command. [#42632][#42632] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Closed by #6785.
