### ISSUE TITLE
ccl/changefeedccl: Re-order columns in the Avro format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6201]
PR: https://github.com/cockroachdb/cockroach/pull/41793

From release notes:
> The fields in the Avro format for [`CHANGEFEED`](../v20.1/change-data-capture.html) records have been re-ordered to allow for optimized parsing. This is a backwards compatible change. [#41793][#41793] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
No docs changes needed. Fields that have been reordered: `before`, `after`, `updated`, `resolved`
