### ISSUE TITLE
builtins: support current_timestamp with precision

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6202]
PR: https://github.com/cockroachdb/cockroach/pull/42633

From release notes:
> Users can now use the [`current_timestamp()` function](../v20.1/functions-and-operators.html) with a given precision from 0-6, e.g. `SELECT current_timestamp(4)`. [#42633][#42633] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Not really called out in the auto-generated docs. Not sure if this is a problem.

**Comment by ericharmeling** [comment]
https://www.cockroachlabs.com/docs/v20.1/functions-and-operators.html lists precision syntax for `current_timestamp`. Also, we call out supporting precision for `TIMESTAMP` in this PR: https://github.com/cockroachdb/docs/pull/6784
