### ISSUE TITLE
storage: create cluster setting for a minimum lease transfer interval

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6205]
PR: https://github.com/cockroachdb/cockroach/pull/42724

From release notes:
> Added the `kv.allocator.min_lease_transfer_interval` cluster setting, which allows the minimum interval between lease transfers initiated from each node to be configured. [#42724][#42724] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@nvanbenschoten I have a question about this cluster setting, `kv.allocator.min_lease_transfer_interval`.

Based on what I'm seeing in v20.1.0-beta.4, it looks like this is currently a non-public setting:

```
> SHOW ALL CLUSTER SETTINGS;
...
  kv.allocator.min_lease_transfer_interval                 | 1s                                   | d            | false  | controls how frequently leases can be transferred for rebalancing. It does not prevent transferring leases in order to allow a replica to be removed from a range.
```

Lately we have been avoiding docs for non-public settings.  Therefore I'm inclined to close this issue and leave this setting out of the docs.

Do you agree with that assessment?

**Comment by nvanbenschoten** [comment]
Yes, I agree with the assessment. We haven't experimented enough with the setting to publicize it.
