### ISSUE TITLE
Allow implicit casting to int[], decimal[]

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6206]
PR: https://github.com/cockroachdb/cockroach/pull/42704

From release notes:
> Users can now use the `cast()` function to cast strings to `int[]` or `decimal[]`, when appropriate. [#42704][#42704] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw
