### ISSUE TITLE
sql: Fix for invalid value for parameter "TimeZone": "GMT-08:00" #41776

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6207]
PR: https://github.com/cockroachdb/cockroach/pull/42781

From release notes:
> `SET TIME ZONE` now accepts inputs beginning with `GMT` and `UTC`, such as `GMT+5` and `UTC-3:59`. This was previously unsupported. [#42781][#42781] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw
