### ISSUE TITLE
opt: add support for numeric references in mutations

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6208]
PR: https://github.com/cockroachdb/cockroach/pull/42683

From release notes:
> It is now possible to reference tables by table descriptor ID in mutations using `INSERT`/`UPSERT`/`UPDATE`/`DELETE`, in a similar way to what is already allowed in `SELECT` statements. For example: `INSERT INTO [53 AS foo] VALUES (1, 2, 3)`. [#42683][#42683] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I'm not sure that this needs to be documented. We currently don't document using table descriptor IDs in `SELECT` statements.

@RaduBerinde Please re-open if you disagree. :)
