### ISSUE TITLE
Tools for managing schema changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#621]
Asked on Gitter:

Hi! I'm using CockroachDB for a side project and ran into a problem regarding migrations. Are there any recommended migration tools that will work with CockroachDB? None of the ones I have tried have worked so far

**Comment by jseldess** [comment]
From @knz: sorry for the late answer. Unfortunately we do not have streamlined migration programs yet. Probably what you could use now is create a SQL dump of your original data then load this SQL in the Cockroach database.

**Comment by bdarnell** [comment]
I think this question is about tools like [flyway](http://flywaydb.org) or [south](http://south.readthedocs.io) (which are about managing schema changes), not moving your data from one database to another.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/2979
