### ISSUE TITLE
cli: add ability to kill and restart nodes in demo

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6210]
PR: https://github.com/cockroachdb/cockroach/pull/42230

From release notes:
> Users can now use `cockroach demo` to shut down and restart nodes. This is available in `cockroach demo` only as `\demo_node <decommission|recommission|shutdown|restart> <node_num>`. This command is not available in other CLIs, e.g. `cockroach sql`. **This feature is experimental**. [#42230][#42230] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/6646
