### ISSUE TITLE
Document that you cannot pass AS OF SYSTEM TIME (AOST) queries directly to EXPLAIN

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6224]
For an explanation of the behavior, see https://github.com/cockroachdb/cockroach/issues/43294

Estimated scope of work:

- Update `AS OF SYSTEM TIME` docs to note that you can't just "slap an `EXPLAIN` on" with queries that use AOST
- Update `EXPLAIN` to note this limitation as well
- Find various other uses of AOST and consider whether they should be updated (probably not once the reference pages are done, but it depends on context)
- Check if this is already in the Known limitations docs for 19.2
- Verify which other versions of CRDB have this limitation, and update those docs as well

**Comment by rmloveland** [comment]
I suspect this is related to the known limitation described here:

https://www.cockroachlabs.com/docs/stable/known-limitations.html#as-of-system-time-in-select-statements

**Comment by ajwerner** [comment]
It also tangentially relates to this issue https://github.com/cockroachdb/cockroach/issues/39275

**Comment by ericharmeling** [comment]
This was fixed and backported:
https://github.com/cockroachdb/cockroach/pull/43305
https://github.com/cockroachdb/cockroach/pull/43296
