### ISSUE TITLE
Remove CDC warning/limitation about correctness issue

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#6230]
Re: [Change Data Capture (CDC)](https://cockroachlabs.com/docs//v19.2/change-data-capture.html)

## Issue Description

The following no longer applies in 19.2

```
There is an open correctness issue with changefeeds connected to cloud storage sinks where new row information will display with a lower timestamp than what has already been emitted, which violates our ordering guarantees.
```

## Suggested Resolution 

Remove the caution
cc @rolandcrosby @ajwerner  https://cockroachlabs.slack.com/archives/C9TGBJB44/p1576774184010400?thread_ts=1576723055.001300&cid=C9TGBJB44

**Comment by jseldess** [comment]
This is a warning [here](https://www.cockroachlabs.com/docs//v19.2/change-data-capture.html#create-a-changefeed-connected-to-a-cloud-storage-sink) and the last bullet [here](https://www.cockroachlabs.com/docs//v19.2/change-data-capture.html#known-limitations).

**Comment by jseldess** [comment]
@lnhsingh, reassigning this to you. Not sure if it's still an issue. 

cc @mwang1026
