### ISSUE TITLE
Clarify when node does hard shutdown

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/docs#6234]
Exalate commented:

Re: [cockroach quit](https://cockroachlabs.com/docs//v19.2/cockroach-quit.html)

## Issue Description

In the "How it works" section, we specify that the nodes times out after a specific time. I've learned that the node will go into a "hard shutdown" mode after 60s, regardless of any settings which are set for the node for shutdown. Please see https://github.com/cockroachdb/cockroach/issues/43015 for reference. 

## Suggested Resolution 
We should specify that a node does a hard shutdown regardless of lease transfers or queries after 60s. 

Jira Issue: DOC-401

**Comment by johnrk** [comment]
@knz , is this issue still valid?
