### ISSUE TITLE
Images need to be updated

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#6236]
https://www.cockroachlabs.com/docs/stable/training/cluster-startup-and-scaling.html

For Step 7.2 on this page the images that I got were:
<img width="1262" alt="Screen Shot 2019-12-20 at 12 04 24 PM" src="https://user-images.githubusercontent.com/58752716/71272313-8e820500-2321-11ea-8c37-6fcce93fcae3.png">

For Step 9, I got these 2 images:
<img width="1333" alt="Screen Shot 2019-12-20 at 12 12 16 PM" src="https://user-images.githubusercontent.com/58752716/71274165-110ac480-2322-11ea-85f5-e763c15fd664.png">

<img width="852" alt="Screen Shot 2019-12-20 at 12 13 47 PM" src="https://user-images.githubusercontent.com/58752716/71274689-35ff3780-2322-11ea-9165-ad4084745871.png">

NOTE: the number of replicas do NOT go down when 2 additional nodes are added because there is ONLY system data in the database (not user data). System Data now has a default of 5 replicas.

**Comment by jseldess** [comment]
These training pages are no longer public now that we have Cockroach U, so closing this.
