### ISSUE TITLE
Add reference to Debug page on Admin UI

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#6237]
https://www.cockroachlabs.com/docs/stable/training/locality-and-replication-zones.html

In the Note in Step 8, there is a link to http://localhost:8080/#/data-distribution
Note:
You can also use the Web UI's Data Distribution matrix to view the distribution of data across nodes.

Instead of directly linking to the page, would it be possible to advise the user to access the page by going to the Admin UI, click on the Gear Icon to go to the Debug page and select Data Distribution and Zone Configs?
 
<img width="1012" alt="Screen Shot 2019-12-20 at 12 20 56 PM" src="https://user-images.githubusercontent.com/58752716/71277607-5ed3fc80-2323-11ea-8f4d-d9f617a6b816.png">

**Comment by jseldess** [comment]
These training pages are no longer public now that we have Cockroach U, so closing this.
