### ISSUE TITLE
Incorrect description of behaviour with clock skews greater than threshold

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#6241]
Looking at https://www.cockroachlabs.com/docs/dev/operational-faqs.html#what-happens-when-node-clocks-are-not-properly-synchronized, we have the following:

> For this reason, when a node detects that its clock is out of sync with at least half of the other nodes in the cluster by 80% of the maximum offset allowed (500ms by default), it spontaneously shuts down. This avoids the risk of violating serializable consistency and causing stale reads and write skews, but it's important to prevent clocks from drifting too far in the first place by running NTP or other clock synchronization software on each node.

Even with clock skew greater than the upperbound, we never violate serializable consistency. We may however violate single-key linearizability, which is what I believe "causing stale reads and write skews" alludes to. 

+cc @nvanbenschoten

**Comment by irfansharif** [comment]
I'm also not sure if we _can_ have write skews. Thinking about it for 30s tells me no, we can't, given we don't violate serializability.

**Comment by nvanbenschoten** [comment]
> I'm also not sure if we can have write skews. Thinking about it for 30s tells me no, we can't, given we don't violate serializability.

That's exactly correct.

**Comment by jseldess** [comment]
@irfansharif, would you mind taking a swing at a quick rewrite of the paragraph above?

**Comment by irfansharif** [comment]
@jseldess: #6329.
