### ISSUE TITLE
CC: Study developer persona and customer journey to inform CC docs arch

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#6247]
Resources:
- https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/196083779/12+17+19+-+Education+Weekly
- https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/181698675/Application+Developer
- https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/194347059/Database+Performance+Engineer
- https://aws.amazon.com/rds/aurora/resources/?nc=sn&loc=5
- https://cloud.google.com/spanner/docs/
- https://www.cockroachlabs.com/case-studies/european-electronic-lock-manufacturer-modernizes-iam-system-with-managed-cockroachdb/
- Lush case study
- EF case study

**Comment by lnhsingh** [comment]
Going to close this for now too. Will open a new one if we decide to revisit the sidebar architecture
