### ISSUE TITLE
CC: Update FAQs based on Support feedback

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#6249]
Reference: https://cockroachlabs.slack.com/archives/CBE9QQC4S/p1576769779002000

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4336](https://cockroachdb.zendesk.com/agent/tickets/4336) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4235](https://cockroachdb.zendesk.com/agent/tickets/4235) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4296](https://cockroachdb.zendesk.com/agent/tickets/4296) has been linked to this issue.

**Comment by Amruta-Ranade** [comment]
Hey @mattcrdb, I looked at the linked tickets where we suggest that the user run the cluster with Cloud NAT and whitelist the external NAT IP, and in all cases, they say the solution is not feasible for them. Do we still want to document the solution given that it probably be helpful to the users? Or would it be useful for some users?

**Comment by mattcrdb** [comment]
IMO yes, that is our only workaround currently. cc @kannanlakshmi for her thoughts on moving forward with the documentation in FAQ.

**Comment by kannanlakshmi** [comment]
We are going to fix in 2 quarters. That said, Cloud NAT is a reasonable solution for a lot of people. If its not too much trouble to document, would be nice to document Amruta.

**Comment by lnhsingh** [comment]
@gemma-shay some of the FAQs that were requested to be added via Slack (awhile ago now) might be relevant to your AWS PrivateLink docs. I can't view the Zendesk tickets, but you might be able to reach out to Matt to view those.

**Comment by mattcrdb** [comment]
I just gave Gemma the access to read the tickets, let me know if you'd like me to add you as well Lauren.

**Comment by lnhsingh** [comment]
@gemma-shay - Will this issue be addressed by changes made for PrivateLink? If not, you can follow up with a separate PR.
