### ISSUE TITLE
Trace Information on Statements Page in Admin UI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6253]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recDDX3AlQ7rNqPja

Description: On the statements page in the Admin UI, users will be able to view a trace of statement(s). The traces displayed will either be a randomly sample to help users understand the tool or specifically requested ones.

Addressing the problem of observability, the traces will help users understand why queries are slow, whether your mental model of CRDB is correct (e.g. was this query served from the locality that I want).

Internally, the traces will help CRDB engineers find ways to improve CRDB's query execution.

Team: John Kendall, Piyush Singh, Anne Birzin, Andrei Matei, Raphael 'kena' Poss, Vlad Artamonov, Pete Vilter

Github Tracking Issue:

**Comment by rmloveland** [comment]
Estimated scope of work:

- Update the Admin UI statement page docs to explain how to read the available traces (including: what even are traces? trace format, add links to what to do in certain cases, etc.)

**Comment by jseldess** [comment]
Closed in favor of https://github.com/cockroachdb/docs/issues/4736.
