### ISSUE TITLE
[Docs] Robust application beyond MovR

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6256]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/rechIVKu3mZqI74Jc

Description: CockroachDB now has a more detailed full application example that can be expanded out to other languages and ORMs 

CockroachDB provides very few application examples. MovR has been improved (and will continue to be improved) but it is only one attempt at a robust application. In many ways it may not live up to many of the more robust application examples available for other databases. 

Team: Andrew Woods, Rafi Shamim, Jesse Seldess

Github Tracking Issue:

**Comment by ericharmeling** [comment]
This isn't going to make 20.1. In the upcoming months, we should think about how we want to dedicate documentation resources on a 20.2 project.

**Comment by jseldess** [comment]
Closing this for now. It's likely that that Training team will build additional sample apps. cc @dweatherbee.
