### ISSUE TITLE
[Docs] Improve testing for example ORMs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6259]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recMTtPYZv1Q9Wcuc

Description: CockroachDB will replace the examples ORMs code with MovR. This will include a full test suite for Movr than can be run via an API for each language. 

We have a large number of code samples spread throughout the docs site. We also have plans to dramatically increase the number of these examples. We currently don't have a way to test these code samples to ensure that they are always accurate.

Team: Andrew Woods, Rafi Shamim, Eric Harmeling, Richard Loveland

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/4705 https://github.com/cockroachdb/docs/issues/3943  https://github.com/cockroachdb/docs/issues/3301  https://github.com/cockroachdb/docs/issues/3203

**Comment by ericharmeling** [comment]
Closing this for now.
