### ISSUE TITLE
[Docs] Complete all removal of savepoints from remaining driver/ORM documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6271]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recT97d2o3ZqZEnWP

Description: CockroachDB docs examples now do not mention savepoints in their retry logic examples. 

We recommend the use of Savepoints as part of the retry logic needed to address transaction retries. This is unnecessarily confusing for application developers at it offers little benefit beyond simple application retry logic. 

Team: Andrew Woods, Rafi Shamim, Richard Loveland

Github Tracking Issue: https://github.com/cockroachdb/docs/issues/5035

**Comment by jseldess** [comment]
@rmloveland, seems that this is a docs project that we should move to 20.2? Thoughts?

**Comment by rmloveland** [comment]
yes please!

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5035
