### ISSUE TITLE
[placeholder] process to upsert output of CDC

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6275]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recWlUcAiGC1nr4uj

Description: 

Team: 

Github Tracking Issue:

**Comment by lnhsingh** [comment]
Out of scope for 20.1

**Comment by lnhsingh** [comment]
Closing for now - will open a new issue whenever this is added to the roadmap.
