### ISSUE TITLE
Upgrades of CC cluster to the latest version of CRDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6277]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recP3PDo0reKIsfIn

Description: 

Team: 

Github Tracking Issue:

**Comment by Amruta-Ranade** [comment]
As discussed on Slack, closing this issue for now. Will reopen if/when the team picks this up.
