### ISSUE TITLE
Replace the social image for Getting Started

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#6279]
Currently, our "Getting Started" image is a green cylinder, and it's what's getting shown on social media. We need to replace this with something better just for social media.

**Comment by thatnerd** [comment]
Crossman's ticket w/ Learndot: https://help.learndot.com/servicedesk/customer/portal/1/SUP-10893

**Comment by thatnerd** [comment]
cc @SpicyThrow

**Comment by SpicyThrow** [comment]
LearnDot Support said to edit this page https://university.cockroachlabs.com/admin/system_setting/view/185.html following the guidelines on this page https://css-tricks.com/essential-meta-tags-social-media/

**Comment by SpicyThrow** [comment]
I've updated the LearnDot html to fix this issue. Directions on how to make this change can now be found here: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/233144602/Updating+LearnDot+Social+Media+Images
