### ISSUE TITLE
Put together a game plan for leveraging Cockroach U. with new employees

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#6292]
Meeting w/ Chelsea 1/7

DoD
- We decide what the expectations are for new employees (which ones will take the course, what the standards are)
- Loop in managers on the plans based on Chelsea's advice
- Draft a list of expectations for Training (what info will go to managers)

**Comment by jseldess** [comment]
Closing since this has been moved to "Done" in the [sprint board](https://github.com/cockroachdb/docs/projects/33?card_filter_query=assignee%3Athatnerd).
