### ISSUE TITLE
Auto-close feedback success modals

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#630]
When clicking "Yes" or "No" to provide feedback, the modal that displays at the end "Thank you" must be manually exited. Adding an automatic dismissal at the .5 or 1 second mark would improve the UX.

Modal HTML:

```
<div class="submitted-message" data-reactid=".hbspt-forms-1">Thank you!</div>
```

Button HTML:

```
<button title="Close (Esc)" type="button" class="mfp-close">×</button>
```

**Comment by jseldess** [comment]
Now that we've gotten rid of the modals, closing this.
