### ISSUE TITLE
Add Kubernetes to release notes and release list

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6300]
Jesse Seldess (jseldess) commented:

Follow-up to https://github.com/cockroachdb/docs/issues/5792, based on note from @bdarnell:

> In addition, since helm is our most popular installation method (and is attractive for short-term testing usage even if your production installation is orchestrated differently), we should have instructions somewhere of how to run the beta with helm (i.e. edit the Image and ImageTag lines in values.yaml).

We need to figure out which instructions to add to [release notes](https://www.cockroachlabs.com/docs/releases/v19.2.2.html) and how to represent this on the [release list](https://www.cockroachlabs.com/docs/releases/) page. Font awesome doesn't provide a Kubernetes or helm icon right now, unfortunately.  

Jira Issue: DOC-408

**Comment by jseldess** [comment]
@taroface, could use your input about how to add Kubernetes to release notes.

**Comment by taroface** [comment]
@jseldess How about adding a Helm button/icon and putting the Helm chart link (https://github.com/helm/charts/tree/master/stable/cockroachdb) under the Downloads column? The Helm chart README would need to be vetted/updated to match the production guidance on our docs. I have #6315.

**Comment by jseldess** [comment]
I like that idea, but we can't rely on a free font-awesome icon like we do for the others, unfortunately: https://fontawesome.com/icons?d=gallery. Neither Kubernetes nor Helm are available, which means we'll have to use an image. Do you feel comfortable trying that out, or should we get a web dev to help?

**Comment by taroface** [comment]
Does it need to be an icon from font-awesome? The Kubernetes logo seems to be available as a vector file: https://github.com/kubernetes/kubernetes/tree/master/logo
