### ISSUE TITLE
Quiz suggests that building a db to handle transactions and joins is easy

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6304]
Feedback from @petermattis:

> I’m working through the Cockroach University courses and failed the first quiz:
>> Answer to Quiz Yourself: Shortcomings of Traditional SQL Databases
>>Traditional SQL databases delivered ACID transactions and joins easily, but scalability and high >>availability were difficult to implement.
>There are many PhDs and folks in industry which would argue that ACID transactions and joins were not delivered easily in traditional SQL databases.

The easy/difficult angle is misleading here.

**Comment by thatnerd** [comment]
Clarifying whose perspective to view:

> What features are difficult for application developers to implement with traditional SQL databases? Select all that apply.
> * **Scalability**
> * **Availability and Durability**
> * ACID transactions
> * Joins

Hopefully this will make it clear that we're not implying that transactions were easy to implement even in a single server environment.

**Comment by thatnerd** [comment]
Peter's additional comment,

> Traditional SQL databases are difficult to set up in a high availability configuration, but most people would probably believe they provided durability.

is still not addressed. The course didn't clarify durability models very well, but yes: many database gurus would argue that an fsync means data is durable, and it would take an unjustifiable quantity of new content to clarify this for students. Nixing the "durability" term from the quiz.

**Comment by thatnerd** [comment]
> What features are difficult for application developers to implement with traditional SQL databases? Select all that apply.
> 
> * **Scalability**
> * **Availability**
> * ACID transactions
> * Joins

**Comment by thatnerd** [comment]
Pinged Peter on slack & got an LGTM.

**Comment by thatnerd** [comment]
(& updated in Learndot)
