### ISSUE TITLE
Quiz suggests traditional SQL dbs aren't durable

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6305]
From @petermattis:

> Another quiz question uses the term “Availability and Durability”. Traditional SQL databases are difficult to set up in a high availability configuration, but most people would probably believe they provided durability.

Peter, can you identify the name of the quiz?

**Comment by petermattis** [comment]
"NoSQL Database Features"

**Comment by SpicyThrow** [comment]
Adjusted the answer to just "Durability"
