### ISSUE TITLE
SQL Tuning with EXPLAIN page inconsistency

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#6308]
Florence Morris (florence-crl) commented:

I followed this tutorial https://www.cockroachlabs.com/docs/v19.2/sql-tuning-with-explain.html#solution-provide-primary-key-to-allow-lookup-join
The expected result is a lookup-up join.

My result was a hash join:
<img width="1049" alt="Screen Shot 2020-01-08 at 11 27 51 AM" src="https://user-images.githubusercontent.com/58752716/71996579-7871b100-320a-11ea-8144-3a1f6db9a0f4.png">

Is the problem with the SQL command below or with the system? 
`EXPLAIN SELECT * FROM vehicles JOIN rides ON rides.vehicle_id = vehicles.id and rides.city = vehicles.city limit 1;`

I reviewed this with Tim O'Brien and he said to include the additional info in the following comments.

**Comment by florence-crl** [comment]
`root@127.0.0.1:51442/movr> EXPLAIN (OPT, VERBOSE) SELECT * FROM vehicles JOIN rides ON rides.vehicle_id = vehicles.id and rides.city = vehicles.city limit 1;
                                                                                                                              text
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  limit
   ├── columns: id:1 city:2 type:3 owner_id:4 creation_time:5 status:6 current_location:7 ext:8 id:9 city:10 vehicle_city:11 rider_id:12 vehicle_id:13 start_address:14 end_address:15 start_time:16 end_time:17 revenue:18
   ├── cardinality: [0 - 1]
   ├── stats: [rows=1]
   ├── cost: 726.938056
   ├── key: ()
   ├── fd: ()-->(1-18)
   ├── prune: (3-9,11,12,14-18)
   ├── inner-join (hash)
   │    ├── columns: vehicles.id:1 vehicles.city:2 type:3 owner_id:4 creation_time:5 status:6 current_location:7 ext:8 rides.id:9 rides.city:10 vehicle_city:11 rider_id:12 vehicle_id:13 start_address:14 end_address:15 start_time:16 end_time:17 revenue:18
   │    ├── stats: [rows=55.5555556, distinct(1)=15, null(1)=0, distinct(2)=9, null(2)=0, distinct(10)=9, null(10)=0, distinct(13)=15, null(13)=0]
   │    ├── cost: 726.918056
   │    ├── key: (9,10)
   │    ├── fd: (1,2)-->(3-8), (9,10)-->(11-18), (1)==(13), (13)==(1), (2)==(10), (10)==(2)
   │    ├── prune: (3-9,11,12,14-18)
   │    ├── scan rides
   │    │    ├── columns: rides.id:9 rides.city:10 vehicle_city:11 rider_id:12 vehicle_id:13 start_address:14 end_address:15 start_time:16 end_time:17 revenue:18
   │    │    ├── stats: [rows=500, distinct(9)=500, null(9)=0, distinct(10)=9, null(10)=0, distinct(13)=15, null(13)=0]
   │    │    │   histogram(10)=  0      55       0     56     0       56        0      56      0    56     0    55    0        55         0     56      0        55
   │    │    │                 <--- 'amsterdam' --- 'boston' --- 'los angeles' --- 'new york' --- 'paris' --- 'rome' --- 'san francisco' --- 'seattle' --- 'washington dc'
   │    │    ├── cost: 700.02
   │    │    ├── key: (9,10)
   │    │    ├── fd: (9,10)-->(11-18)
   │    │    ├── prune: (9-18)
   │    │    └── interesting orderings: (+10,+9) (+10,+12,+9) (+11,+13,+10,+9)
   │    ├── scan vehicles
   │    │    ├── columns: vehicles.id:1 vehicles.city:2 type:3 owner_id:4 creation_time:5 status:6 current_location:7 ext:8
   │    │    ├── stats: [rows=15, distinct(1)=15, null(1)=0, distinct(2)=9, null(2)=0]
   │    │    │   histogram(2)=  0       2       0     2      0        1        0      2       0     2     0    1     0         2         0      2      0         1
   │    │    │                <--- 'amsterdam' --- 'boston' --- 'los angeles' --- 'new york' --- 'paris' --- 'rome' --- 'san francisco' --- 'seattle' --- 'washington dc'
   │    │    ├── cost: 19.82
   │    │    ├── key: (1,2)
   │    │    ├── fd: (1,2)-->(3-8)
   │    │    ├── prune: (1-8)
   │    │    └── interesting orderings: (+2,+1) (+2,+4,+1)
   │    └── filters
   │         ├── vehicle_id = vehicles.id [outer=(1,13), constraints=(/1: (/NULL - ]; /13: (/NULL - ]), fd=(1)==(13), (13)==(1)]
   │         └── rides.city = vehicles.city [outer=(2,10), constraints=(/2: (/NULL - ]; /10: (/NULL - ]), fd=(2)==(10), (10)==(2)]
   └── const: 1
(39 rows)

Time: 6.163ms
`

**Comment by florence-crl** [comment]
`root@127.0.0.1:51442/movr> SHOW STATISTICS USING JSON FOR TABLE vehicles;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    statistics
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  [{"columns": ["city"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 9, "histo_buckets": [{"distinct_range": 0, "num_eq": 2, "num_range": 0, "upper_bound": "amsterdam"}, {"distinct_range": 0, "num_eq": 2, "num_range": 0, "upper_bound": "boston"}, {"distinct_range": 0, "num_eq": 1, "num_range": 0, "upper_bound": "'los angeles'"}, {"distinct_range": 0, "num_eq": 2, "num_range": 0, "upper_bound": "'new york'"}, {"distinct_range": 0, "num_eq": 2, "num_range": 0, "upper_bound": "paris"}, {"distinct_range": 0, "num_eq": 1, "num_range": 0, "upper_bound": "rome"}, {"distinct_range": 0, "num_eq": 2, "num_range": 0, "upper_bound": "'san francisco'"}, {"distinct_range": 0, "num_eq": 2, "num_range": 0, "upper_bound": "seattle"}, {"distinct_range": 0, "num_eq": 1, "num_range": 0, "upper_bound": "'washington dc'"}], "histo_col_type": "STRING", "name": "__auto__", "null_count": 0, "row_count": 15}, {"columns": ["id"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 15, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 15}, {"columns": ["type"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 3, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 15}, {"columns": ["owner_id"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 15, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 15}, {"columns": ["creation_time"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 1, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 15}, {"columns": ["status"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 3, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 15}, {"columns": ["current_location"], "created_at": "2020-01-08 18:25:07.539902+00:00", "distinct_count": 15, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 15}]
(1 row)`

**Comment by florence-crl** [comment]
`root@127.0.0.1:51442/movr> SHOW STATISTICS USING JSON FOR TABLE rides;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      statistics
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  [{"columns": ["city"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 9, "histo_buckets": [{"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "amsterdam"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "boston"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "'los angeles'"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "'new york'"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "paris"}, {"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "rome"}, {"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "'san francisco'"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "seattle"}, {"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "'washington dc'"}], "histo_col_type": "STRING", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["vehicle_city"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 9, "histo_buckets": [{"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "amsterdam"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "boston"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "'los angeles'"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "'new york'"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "paris"}, {"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "rome"}, {"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "'san francisco'"}, {"distinct_range": 0, "num_eq": 56, "num_range": 0, "upper_bound": "seattle"}, {"distinct_range": 0, "num_eq": 55, "num_range": 0, "upper_bound": "'washington dc'"}], "histo_col_type": "STRING", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["id"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 500, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["rider_id"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 50, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["vehicle_id"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 15, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["start_address"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 500, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["end_address"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 500, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["start_time"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 30, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["end_time"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 367, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}, {"columns": ["revenue"], "created_at": "2020-01-08 18:25:07.634957+00:00", "distinct_count": 100, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 500}]
(1 row)`

**Comment by florence-crl** [comment]
```
root@127.0.0.1:51442/movr> EXPLAIN ANALYZE SELECT * FROM vehicles JOIN rides ON rides.vehicle_id = vehicles.id and rides.city = vehicles.city limit 1;
  automatic |                                                                                                                                                                                                                                                                                                                                                                                                    url
+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    true    | https://cockroachdb.github.io/distsqlplan/decode.html#eJyck91u2kwQhs-_qxjNEXyaJqwJhFiKtLShqlMCaeCgP0KVw06TVW0v3V23QRGX1RvolVVe5w8aUqVnnpn33X12ZnyN7luGMQ7enw77yQj6o_7ww8cBNI6SyXTybtiEyWA4eDWF_-H12fgEvvOlnmfs4HicjMBqxQ7GI2iEr52b6met4PBOuqNVE_qjo1vRXPvlw3IVN2GYnCRTEEhYGMWjNGeH8ScUOCNcWDNn54ytUtdBkKgrjFuEuliUvkrPCOfGMsbX6LXPGGOcpucZn3Gq2O62kFCxT3UWjl1Ynad2KQMREk4WaeFieIGE1vxwYDlVMfSQ0Pk0y8DrnGM4EJ1fPyv5-dLznagLb_VLnK0ITenvaZxPLxhjsaJ_IxaPE9-2bSu06GxQi270J3W0034SO9qKfU9bFsYqtqzWSGeV82-SR97-JnWXx0YXbHej9adn_MU3ZIdk1Dy0-uLSN6SoAiQclz4GKQRJEZEUbZJij6TokBRdkmKfpOhRUJNsk9yj6pguyX2SPZIHJEW1GEOdax92r7oKNjYg5NYaerMFgQU2W19nH-p7e7XeeWNZgdOKYwgyJMzTK8g5N3YJpWMVQ6cVBlNXlHZfb_It2D6t9nOW7IzdwhSON6f26MmtalSsLrgevTOlnfOpNfNwTR2Ogy8kFDtfV6M6SIpQCn_BQ7N4hjnaNEdPmttr5tZqtvrvdwAAAP__VZ6RdQ==
```

**Comment by justinj** [comment]
This plan doesn't seem crazy to me, we probably tweaked some costing that resulted in a change to the plan chosen. I think this is a docs issue, rather than an optimizer issue. In general it will be hard to guarantee stability of plans as small a dataset as MovR (because the data is so small it doesn't matter very much what plan we choose).

**Comment by jseldess** [comment]
I'll go ahead and update the tutorial to match what users currently see, but to @justinj's point, we may not be able to keep up with this for every patch release, etc.

**Comment by justinj** [comment]
This page shouldn't be updated to include this plan—the point of the page is that it shows a lookup join. I don't know what the right solution is for that.

**Comment by jseldess** [comment]
I see. Sorry, didn't read closely enough. @justinj, how big would the dataset need to be for us to consistently see the optimizer choose lookup joins?

**Comment by justinj** [comment]
I experimenting 10xing the size of the `rides` table (both row and distinct counts) and saw a lookup join, I would guess that would be a safe size but I couldn't say for sure in a way that would definitely be future-proof.

**Comment by jseldess** [comment]
@ericharmeling, this is something to investigate when there's time. The last tip of this tutorial is about getting the optimizer to use a lookup join instead of a hash join, but the example is no longer demonstrating this. Not sure if the solution is finding a way to update the example to reliably show this behavior, changing this tip somehow, or removing it entirely.

**Comment by vy-ton** [comment]
@kevin-v-ngo for awareness, this might be covered in the work you're doing with Ian
