### ISSUE TITLE
Certificate of Completion's "copy link to clipboard" button not working

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#6309]
Our Certificate of Completion's "copy link to clipboard" button in the email isn't working.

From Florence:
"I followed the directions to add it to my linkedin profile. fyi...the copy link to clipboard gives copies this link: https://university.cockroachlabs.com/award/completion/c0b99339-b45e-3b7b-acba-71f07d87e797/preview"

**Comment by thatnerd** [comment]
https://help.learndot.com/servicedesk/customer/portal/1/SUP-10933

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
