### ISSUE TITLE
cloud: update the pricing page in docs to reflect the latest options

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6310]
https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-create-your-cluster.html will need to be updated with the latest update on the create cluster page here https://github.com/cockroachlabs/managed-service/issues/1763#issuecomment-557567732

**Comment by Amruta-Ranade** [comment]
https://github.com/cockroachlabs/managed-service/pull/2123
