### ISSUE TITLE
ALTER TABLE ... IF EXISTS ... RENAME COLUMN has incorrect description

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#6318]
Spotted by a Cockroach user:

>Hi, noticed a possible docs issue. In https://www.cockroachlabs.com/docs/stable/rename-column.html it says about IF EXISTS, "Rename the column only if a column of current_name exists; if one does not exist, do not return an error."
>But actually this only renames the column if the *table* exists. Renaming a column that doesn't exist still fails.

This observation aligns with the code, so the docs look off here.

**Comment by jseldess** [comment]
Thanks, @nvanbenschoten. 

@ericharmeling, this is quick fix.
