### ISSUE TITLE
appdev: Update third-party tooling page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#6326]
Update third-party tooling page:

- [ ] [Add Prometheus and Grafana page to the toc here](https://www.cockroachlabs.com/docs/v19.2/monitor-cockroachdb-with-prometheus.html#step-5-visualize-metrics-in-grafana)
- [ ] Add [Datadog](https://www.datadoghq.com/blog/monitor-cockroachdb-performance-metrics-with-datadog/)
- [ ] [Add visualizer](https://github.com/cockroachdb/cockroach/issues/25467)s: [Postico, dbglass, PGWeb, PSequel, TablePlus, and Valentina studio.](url)
- [ ] Add ORMs
- [ ] Add IDEs

**Comment by ericharmeling** [comment]
Closing this in favor of https://github.com/cockroachdb/docs/issues/6866
