### ISSUE TITLE
Admin UI-related security changes

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#6331]
Investigate if the Admin UI-related security changes have a doc impact (already documented in release notes):
Changes: https://www.cockroachlabs.com/docs/releases/v19.2.2.html#admin-ui-changes
~Workaround: https://github.com/cockroachdb/cockroach/issues/43870~
~Proposed fix: https://github.com/cockroachdb/cockroach/pull/43893~
Existing Docs PR: https://github.com/cockroachdb/docs/pull/6321#issuecomment-573760638
Also relates to #6517

**Comment by knz** [comment]
Amruta we should talk :)

**Comment by Amruta-Ranade** [comment]
Yes, please! Should I set up some time for next week?

**Comment by knz** [comment]
Sure that works

**Comment by knz** [comment]
More changes: https://www.cockroachlabs.com/docs/releases/v19.2.2.html#security-updates

**Comment by Amruta-Ranade** [comment]
@taroface Handing it over to you since this seems more Admin UI-related than security. Feel free to hand it back if you think I am mistaken.

The primary change is explaining the difference between insecure, secure (non-admin), and secure (Admin user) access to the admin UI. And then a follow-up project of finding out and documenting which exact pages can each of them see.

Note: This might also affect CC-Admin UI docs.

**Comment by jseldess** [comment]
@knz requests that: 
> the doc work for https://github.com/cockroachdb/cockroach/pull/44345 should include a proactive explanation of why we don't allow more flexibility, so that users don't come to us with that question.

**Comment by taroface** [comment]
> finding out and documenting which exact pages can each of them see.

@piyush-singh is collecting this info and I'll update docs from his materials!

**Comment by taroface** [comment]
Related: 

- #6517
- https://github.com/cockroachdb/cockroach/issues/45089

**Comment by taroface** [comment]
Docs work:

- Add a 'secure cluster access' subheading to [Admin UI Overview](https://www.cockroachlabs.com/docs/stable/admin-ui-overview.html) page explaining why we limit access & listing the Admin UI sections accessible only to admin users of a secure cluster (listed below)
- Link also to workarounds referenced in the release notes
- Add "privileges" columns to any Admin UI tables that list specific Admin UI sections
- Update & cross-link tutorials that reference these sections

List of Admin UI pages not accessible to non-admin users on secure clusters:

- Node map (with enterprise license)
- Databases (Tables, Grants)
- Statements
- Jobs
- Node Logs #/node/1/logs
- Data Distribution and Zone Configs (in adv debug) #/data-distribution
- Localities #/reports/localities 
- Certificates #/reports/certificates
- Range Status #/reports/range/[range_id]
- Raft for all ranges #/raft/ranges
- logs on nodes /_status/logs/[node_id]
- /_status/logfiles/[node_id]
- /_status/logfiles/[node_id]/[filename]
- Hot ranges /_status/hotranges and /_status/hotranges?node_id=[node_id]
- Stores	/_status/stores/[node_id]
- Gossip	/_status/gossip/[node_id]
- Ranges	/_status/ranges/[node_id]
- Stacks	/_status/stacks/[node_id]
- Engine Stats	/_status/enginestats/[node_id]
- Certificates	/_status/certificates/[node_id]
- Raft	/_status/raft
- Range	/_status/range/[range_id]
- Range Log	/_admin/v1/rangelog?limit=100
- Range Log for Specific Range	/_admin/v1/rangelog/[range_id]?limit=100
- Simulated Allocator Runs on a Specific Node	/_status/allocator/node/[node_id]
- Simulated Allocator Runs on a Specific Range	/_status/allocator/range/[range_id]
