### ISSUE TITLE
Update all mentions of Gitter to point to new community Slack instance

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6347]
Currently on pages like [Troubleshoot query behavior](https://www.cockroachlabs.com/docs/stable/query-behavior-troubleshooting.html), we link to the old Gitter chat room.  We should update all such links to point to the new [community Slack instance](https://cockroachdb.slack.com).

**Comment by vy-ton** [comment]
I no longer see a Gitter link on the Troubleshoot page so closing this
