### ISSUE TITLE
Django app/tutorial with Python 2

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#6375]
Re: [Build a Python App with CockroachDB and Django](https://cockroachlabs.com/docs//v20.1/build-a-python-app-with-cockroachdb-django.html)

## Issue Description

`The example code and instructions on this page use Python 3.` Investigate whether the instruction would work with Django2 and note limitations.

**Comment by jseldess** [comment]
@ericharmeling, @apantel, do you have this answer already?

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4540](https://cockroachdb.zendesk.com/agent/tickets/4540) has been linked to this issue.

**Comment by jseldess** [comment]
@robert-s-lee, is this about python 2, django 2, or both?

**Comment by apantel** [comment]
We haven't tested at all with python 2. Django 2 (with django-cockroachdb 2) works.

**Comment by robert-s-lee** [comment]
Good news on Django 2.  Can we be specific on what version we tested with so that we can provide situations under which customers could re-produce working examples.

**Comment by awoods187** [comment]
Python 2 is deprecated...I think we want to focus on Python 3 support only.

@robert-s-lee we specify everything in the readme: https://github.com/cockroachdb/django-cockroachdb

**Comment by robert-s-lee** [comment]
ack on not having python 2 support.  want to get on the same page on Django 2 support.  https://docs.djangoproject.com/en/3.0/releases/2.0/ has Django 2.0 supports Python 3.4, 3.5, 3.6, and 3.7.

**Comment by ericharmeling** [comment]
@robert-s-lee Are you OK with closing this issue, as we want to encourage users to use Python 3?

**Comment by jseldess** [comment]
@ericharmeling, do you think it makes sense to mention different versions of django, though? The readme has more specific syntax for installation...

**Comment by robert-s-lee** [comment]
https://github.com/cockroachdb/django-cockroachdb/tree/stable/2.2.x seems to have Django 2.2 instructions.  Any thoughts to adding Django 2.2 in the instructions?

**Comment by jseldess** [comment]
@ericharmeling, can you pick this thread back up? Not sure what we want to do here.

**Comment by awoods187** [comment]
We want to provide instructions for Django 2.2 and Django 3.0. Python is not germane at all.

**Comment by ericharmeling** [comment]
I'll open a PR to specify that we, in fact, support Django 2 and 3, with instructions re: versioning.
