### ISSUE TITLE
Diagnostics Reporting Doc Update 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#6378]
Re: [Diagnostics Reporting](https://cockroachlabs.com/docs//v19.2/diagnostics-reporting.html)

## Issue Description
Need to update docs to show include turning off `diagnostics.reporting.send_crash_reports` which also sends cluster information to 3rd party. 

Currently, it only tells users to diable `SET CLUSTER SETTING diagnostics.reporting.enabled = false;`

## Suggested Resolution 

Add a new line to read:

`SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;`

**Comment by mattcrdb** [comment]
worth noting @knz has confirmed that the env variable `COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING` will disable panic/crash reports as well.
So we just need to update that page for the second cluster setting. The idea that the diagnostics reporting page is a catch-all for disabling phone-home.

**Comment by rmloveland** [comment]
@taroface this seems like it falls under "Ops" - do you mind snagging this one?

**Comment by taroface** [comment]
Closing this issue per comments in #6800.
