### ISSUE TITLE
"Follower Reads topology" syntax error + query error

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#6383]
The original issue fielded from a customer was that the query on [this](https://www.cockroachlabs.com/docs/stable/topology-follower-reads.html) page shows:
```sql
SELECT code FROM postal_codes
WHERE id = 5
AS OF SYSTEM TIME experimental_follower_read_timestamp();
```
It should read:
```sql
SELECT code FROM postal_codes
AS OF SYSTEM TIME experimental_follower_read_timestamp()
WHERE id = 5;
```

Additionally, this create table:
```sql
CREATE TABLE postal_codes (
    id INT PRIMARY KEY,
    code STRING,
);
```
Should not have a comma after `code STRING`.

Lastly, the query assumes we've inserted data into this table. However, it doesn't seem like we've inserted any data to support the experimental follower read  timestamp query.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4547](https://cockroachdb.zendesk.com/agent/tickets/4547) has been linked to this issue.
