### ISSUE TITLE
Cloud - incorrect code sample to connect with Node.js and Postgres driver

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6392]
The [Node.js](https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html#js) code for connecting to your cluster is missing two library imports and some cert information.

As shown in [Build a Node.js app with CockroachDB](https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb.html#step-4-run-the-node-js-code) the code should look like:

```javascript
var fs = require('fs');
var pg = require('pg');

var config = {
    user: 'maxroach',
    host: 'localhost',
    database: 'bank',
    port: 26257,
    ssl: {
        ca: fs.readFileSync('certs/ca.crt')
            .toString(),
        key: fs.readFileSync('certs/client.maxroach.key')
            .toString(),
        cert: fs.readFileSync('certs/client.maxroach.crt')
            .toString()
    }
};
```

**Comment by rmloveland** [comment]
Update: did not need the additional cert fields: CC only needs the CA, based on the doc.

**Comment by emily-horing** [comment]
If you keep the example we have, you can make it work by adding:

Const fs = require(“fs”);
Const { Client } = require(“pg”);
// current example code here
Var client = new Client(config);

**Comment by emily-horing** [comment]
@rmloveland I see in [these](https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb.html#step-4-run-the-node-js-code) docs we suggest using pool instead of Client. I'm not aware of what the differences are or why you would use one over the other, we just tried with client and got it to work. It may or may not be better to use pool 🤷‍♀

**Comment by rmloveland** [comment]
ok thanks @emily-horing - I'm not 100% sure either.  As long as we have something that folks can get up and running with that does not cause an error, I think it will be an improvement either way :-} (shared 🤷‍♂)
