### ISSUE TITLE
Information about replication settings is outdated

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#641]
Regarding: https://www.cockroachlabs.com/docs/configure-replication-zones.html#replicaton-zone-format

1) typo in title "replicaton"

2) the setting is different now, it's called `num_replicas`.

**Comment by knz** [comment]
New syntax with examples to be found here:
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/expressive_zone_config.md#constraint-system

**Comment by jseldess** [comment]
@knz, I've been working on updates this week. Hope to have a PR opened early next week. But the changes are only on `develop`, so the current docs are correct for anyone using an official beta binary. I'm rewriting the page to accommodate both cases. 

I have #617 open for this work already, so I'll close this issue. I'll make sure to correct the typo as well. Thanks for catching that.
