### ISSUE TITLE
Determine & Implement Internal Feedback Method

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#6414]
Our course-end survey should not be the same for CockroachDB employees

Problem: Currently, we have a survey in place & designed for external feedback
* Engineering students use the same course (& get the same survey) as external users
* Non-program-y hires use a separate course (currently pointed to the same survey)
* We want external feedback to be separable from internal
* We want to minimize the stack
  * Creating new courses leads to maintenance overhead
  * We already have two

DoD
* Decide on a plan
* Explain the plan on the wiki w/ advantages, disadvantages
* Get LGTM from Crossman

**Comment by thatnerd** [comment]
Doc: https://docs.google.com/document/d/1hhtVqFZ3BtxnA0KcNM0a-75RCs_UX8ONBFHRaL8WeCI/edit#

**Comment by thatnerd** [comment]
Handing off implementation to @SpicyThrow

**Comment by thatnerd** [comment]
^ Decision is to go with existing offerings, but redirect internal non-programmers to a separate survey to filter out their perspective.

**Comment by SpicyThrow** [comment]
The survey is implemented on the internal course, but I need to work with support to create custom emails for the course that link to the correct survey.

**Comment by SpicyThrow** [comment]
This work was completed a few days ago. The survey is implemented and the emails now direct users based on the course they completed.
