### ISSUE TITLE
Add a note to secure guide that user can bring their own certs and keys

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6419]
Artem Ervits (dbist) commented:

## Expected Audience

Jira Issue: DOC-418

**Comment by jseldess** [comment]
@taroface, check with @dbist for more details.

**Comment by taroface** [comment]
@dbist can you specify which document "secure guide" refers to?

**Comment by dbist** [comment]
Step 2 https://www.cockroachlabs.com/docs/v19.2/deploy-cockroachdb-on-premises.html. I am actually thinking a tutorial detailing step by step how to leverage outside certs is more welcome.
