### ISSUE TITLE
SHOW EXPERIMENTAL_FINGERPRINTS documentation is inaccurate

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/docs#6422]
Our documentation for this experimental feature looks incorrect. It claims that these fingerprints are used by the optimizer for plan caching, but that is not the case. In this case the fingerprint is a hash of a table's contents. We only use this for testing, for instance to verify that a table's contents do not change after backing it up and restoring it.

**Comment by ericharmeling** [comment]
I think this was fixed by #5692.
