### ISSUE TITLE
APPLY JOIN docs

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#6426]
Eric Harmeling (ericharmeling) commented:

Related to this issue, I think we should also have documentation for "apply join". Apply join is the operator that actually executes a lateral join if the optimizer is not able to decorrelate it (i.e., rewrite the query to use a regular join). Most of the time, customers would not need to know about apply joins since the optimizer can decorrelate most queries. However, there are some cases where the optimizer cannot perform this rewrite, and therefore "apply join" would show up in the EXPLAIN output for the query. The optimizer also replaces correlated subqueries with apply joins, and therefore "apply join" may appear in the EXPLAIN output even if LATERAL was not used. 

I bring this up because a customer using 19.2 saw "apply join" in their EXPLAIN plan and didn't know what it was.

_Originally posted by @rytaft in https://github.com/cockroachdb/docs/issues/5990#issuecomment-572775694_

**Comment by rytaft** [comment]
I think this is still an issue. Googling "cockroachdb apply join" brings up this forum post: https://forum.cockroachlabs.com/t/apply-join-and-hash-join-difference/3597, so it seems like this info may not be available in the docs.

cc @stbof since I'm guessing you might end up working on this.

**Comment by stbof** [comment]
@rytaft, this is still assigned to @ericharmeling
