### ISSUE TITLE
roleccl: WITH ADMIN check no longer bypassed on admin role

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6437]
PR: https://github.com/cockroachdb/cockroach/pull/41218

From release notes:
> Users [`GRANT`ing](../v20.1/grant.html) and [`REVOKE`ing](../v20.1/revoke.html) admin roles must be members of the admin role with `ADMIN OPTION`. This check was previously bypassed. [#41218][#41218] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7003
