### ISSUE TITLE
*: implement protectedts.Storage 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6438]
PR: https://github.com/cockroachdb/cockroach/pull/42829

From release notes:
> Added system tables `system.protected_ts_meta` and `system.protected_ts_records` to support the implementation of [protected timestamps](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20191009_gc_protected_timestamps.md), a subsystem used to ensure that data required for long-running jobs is not garbage collected. [#42829][#42829] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, I'm not sure if this is something for you to document.

**Comment by rmloveland** [comment]
Closing since (1) these are system tables (as you alluded to Jesse, I think) - and (2) the docs around protected timestamps for 20.1 were all handled in the update for #6003
