### ISSUE TITLE
colexec: skip over unneeded columns in cfetcher

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6441]
PR: https://github.com/cockroachdb/cockroach/pull/42616

From release notes:
> [Vectorized queries](../v20.1/vectorized-execution.html) that execute only on supported types (even if those types form part of a table with unsupported types) are now run through the vectorized engine. This would previously fall back to the row-by-row execution engine. [#42616][#42616] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reciDxEVXj4Y68MCz
