### ISSUE TITLE
sql: Add column family support for secondary indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6442]
PR: https://github.com/cockroachdb/cockroach/pull/42073

From release notes:
> CockroachDB now allows stored columns in [secondary indexes](../v20.1/indexes.html) to respect the [column family](../v20.1/column-families.html) table definitions that they are based on. [#42073][#42073] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #6556.
