### ISSUE TITLE
sql, *: allow table scoping under pg_temp_<session_id> physical schema

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6444]
PR: https://github.com/cockroachdb/cockroach/pull/41977

From release notes:
> `CREATE TABLE pg_temp.abc(a int)` now creates a temporary table. See [temp tables RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20191009_temp_tables.md) (guide-level explanation) for more details about the search path semantics. [#41977][#41977] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
temp tables https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recokw8S2pkhwhPP2
