### ISSUE TITLE
opt: show cross joins in EXPLAIN

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6445]
PR: https://github.com/cockroachdb/cockroach/pull/43061

From release notes:
> The output of [`EXPLAIN`](../v20.1/explain.html) now shows [joins](../v20.1/joins.html) where there are no equality columns, such as "cross" instead of "hash". This kind of join can be very expensive and should be avoided. [#43061][#43061] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Explain https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/rec4nN8PXF6Tkge92
