### ISSUE TITLE
backupccl: change the error code for "file already exists" errors

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6446]
PR: https://github.com/cockroachdb/cockroach/pull/43221

From release notes:
> The error code for [backups](../v20.1/backup.html), which would overwrite files, changed from class 58 (`"system"`) to class 42 (`"Syntax or Access Rule Violation"`). [#43221][#43221] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
No docs needed.
