### ISSUE TITLE
execinfrapb: print out input types for EXPLAIN (DISTSQL, TYPES)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6447]
PR: https://github.com/cockroachdb/cockroach/pull/43193

From release notes:
> Column types are now displayed in the box for the input synchronizer in the flow diagram obtained via [`EXPLAIN (DISTSQL, TYPES)`](../v20.1/explain.html). [#43193][#43193] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Explain https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/rec4nN8PXF6Tkge92

**Comment by jseldess** [comment]
@rmloveland, since you're taking a few other explain changes, would you mind taking this as well?
