### ISSUE TITLE
sql: add precision and duration field support for INTERVAL type

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6448]
PR: https://github.com/cockroachdb/cockroach/pull/43130

From release notes:
> CockroachDB now supports [interval types](../v20.1/interval.html) with precision (e.g., `INTERVAL(5)`, `INTERVAL SECOND(5)`), and storing intervals with duration fields (e.g., `INTERVAL x TO y`). [#43130][#43130] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw
