### ISSUE TITLE
sql: enable optimizer-driven foreign key checks

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6449]
PR: https://github.com/cockroachdb/cockroach/pull/43263

From release notes:
> [Foreign key](../v20.1/foreign-key.html) checks that don't involve cascades are now performed after the mutation is complete, allowing self-referential foreign keys, or referential cycles. The execution plans for foreign key checks are now driven by the [optimizer](../v20.1/cost-based-optimizer.html), which can make better planning decisions. In particular, if there is a suitable duplicated index, the one in the current locality will be used for foreign key checks. [#43263][#43263] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs documentation.

@RaduBerinde 
Please re-open if you disagree. :)
