### ISSUE TITLE
tree: fix incorrect parsing of MM:SS.ff and MINUTE TO SECOND intervals

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6450]
PR: https://github.com/cockroachdb/cockroach/pull/43292

From release notes:
> `MINUTE TO SECOND` is now parsed as `MM:SS` instead of `HH:MM`. Additionally, [interval syntax](../v20.1/interval.html), such as `INTERVAL "01:02.123"`, is now parsed correctly as `MM:SS.fff`. This matches Postgres behavior. [#43292][#43292] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw
