### ISSUE TITLE
sql: return duplicate constraint error for duplicate FK names

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6451]
PR: https://github.com/cockroachdb/cockroach/pull/43210

From release notes:
> Previously, CockroachDB returned error code `42830` and `23503` for duplicate [foreign key](../v20.1/foreign-key.html) names. It now returns `42710`, which matches Postgres. [#43210][#43210] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't require documentation.
