### ISSUE TITLE
cli,deps: bump tablewriter and fix misc SQL table rendering bugs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6453]
PR: https://github.com/cockroachdb/cockroach/pull/43728

From release notes:
> The `table` format, used to display the results of CLI shell queries, has been updated. [#43728][#43728] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This will need to gradually be picked up, as it affects almost all example output.
