### ISSUE TITLE
CDC: Document backfill behavior

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6458]
Jesse Seldess commented:

PR: https://github.com/cockroachdb/cockroach/pull/43037

From release notes:
> [Changefeeds](../v19.1/create-changefeed.html] now emit backfill row updates for a dropped column when the table descriptor drops that column. [#43037][#43037) {% comment %}doc{% endcomment %}

Jira Issue: DOC-423

**Comment by mwang1026** [comment]
Coopting this doc to document when we backfill vs. when we don't

**Comment by mwang1026** [comment]
@amruss @mwang1026 add some detail here

**Comment by jseldess** [comment]
@amruss, @mwang1026, should we keep this open? If so, we might want to remove the 19.1 milestone. This issue was originally tied to a release note for 19.1 that we never documented.
