### ISSUE TITLE
release-19.2: sql: return duplicate constraint error for duplicate FK names

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6463]
PR: https://github.com/cockroachdb/cockroach/pull/43425

From release notes:
> Previously, we error-coded duplicate foreign key constraint names with `42830` or `23503`. We changed this to be `42710` to be in line with PostgreSQL. [#43425][#43425] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we need to document this.
