### ISSUE TITLE
release-19.2: sql: fix locality information in show ranges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6465]
PR: https://github.com/cockroachdb/cockroach/pull/44312

From release notes:
> [`SHOW RANGES`](../v19.2/show-ranges.html) now shows locality information consistent with the range descriptor when node ID and store ID don't match. [#44312][#44312] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is a bug fix that doesn't change expected (and documented) behavior.
