### ISSUE TITLE
release-19.2: allocator: increase rebalance threshold 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6467]
PR: https://github.com/cockroachdb/cockroach/pull/44359

From release notes:
> The kv.allocator.range_rebalance_threshold setting, which controls how far away from the mean a store's range count must be before it is considered for rebalance, is now subject to a 2-replica minimum. If, for example, the mean number of replicas per store is 5.6 and the setting is 5%, the store won't be considered for rebalance unless the number of replicas is lesser than 3 or greater than 8. Previously, the bounds would have been 5 and 6. [#44359][#44359] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, not sure if this affects docs.

**Comment by rmloveland** [comment]
Closing per discussion in #6591
