### ISSUE TITLE
CC: Rethink CC/CRDB Docs structure

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#6473]
Repeated comments at the Education offsite and 1:1 conversations have indicated that CC docs are not easy to spot and that it might be better to nest them within CRDB docs. Want to set aside some time to investigate and think through it.

**Comment by jseldess** [comment]
This is large in scope and warrants being called out as a docs-project. It's also something we should do in collaboration with Design.

**Comment by Amruta-Ranade** [comment]
Yep. I opened issues for things that came out of the Education offsite/1:1 conversations so I won't forget about them later. Need to be thought through/triaged though.

**Comment by Amruta-Ranade** [comment]
@lnhsingh Is this a part of your and Lucia's docs redesign project? If yes, should I assign this issue to you?

**Comment by Amruta-Ranade** [comment]
Related issue: https://github.com/cockroachdb/docs/issues/5739

**Comment by lnhsingh** [comment]
Closing this since the side nav and general redesign work has resolved this for the most part.
