### ISSUE TITLE
Fix Course Navigation

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#6475]
There's a bug in the LearnDot navigation where the state of the sidebar navigation is not persistent. When navigating the course, the sidebar opens and closes. This has been reported to LearnDot support and their engineering team is triaging.

**Comment by SpicyThrow** [comment]
No timeline on a fix from LearnDot.

**Comment by SpicyThrow** [comment]
Our account manager, Mel, is nudging this support ticket but no update on the timeline for a fix.

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
