### ISSUE TITLE
Separate recommission and decommission docs

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#6476]
When looking up how to "Recommission" nodes, I stumbled a bit before realizing it's in the same page titled "Decommission Nodes". There's also no mention of "Recommission" in the left hand side nav bar as a result. Google SEO also behaves badly as a result. Perhaps we should change the title to reflect both Recommissioning and Decommissioning, or move it to a separate page entirely.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/10536690/73953901-0a82dd00-48cf-11ea-966c-dee80d7a0541.png">

As a separate point, the docs page shows screenshots of a UI that has been changed in v20.1. What's shown below is no longer present/applicable.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/10536690/73954014-3900b800-48cf-11ea-9d6a-8279c69359b1.png">

It now looks like the following:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10536690/73955081-cb558b80-48d0-11ea-8342-050ad40ad0cc.png">

**Comment by irfansharif** [comment]
Also, I think this page is a good place to outline how long the decommissioning process is expected to take (proportional to the number of replicas on the to-be-decommissioned node, and is in the order of several minutes).

**Comment by irfansharif** [comment]
Assigning @rmloveland for triage.

**Comment by rmloveland** [comment]
Thanks for filing @irfansharif !  Going into the queue for the 20.1 release.
