### ISSUE TITLE
Pass/Fail Communications

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#6477]
Learndot doesn't enable sending different emails to users who pass v. fail the final exam. As a workaround, we are sending a generic email to both groups upon completion, with a follow-up email to passing learners including their certificate. The better solution would be to have one email sent to each group: for failed learners, a notice that they didn't pass the exam (ideally including what their final score was so they know how close they were/weren't) and encouragement to take it again at any time; for passed learners a message of congratulations, their certificate, and instructions to add the cert to their socials. Both learners should be asked to fill in feedback forms (ideally in-email forms so they don't have to open another page)

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
