### ISSUE TITLE
Docs for generating example database

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#648]
On `develop` branch as of Sept. 13.

Command is:
`cockroach gen example-data | cockroach sql`

According to @knz: "gives you 2 tables, a foreign key, some random data with nice opportunities for grouping and aggregation."

PR: https://github.com/cockroachdb/cockroach/pull/9231

Think this has some potential for improving the [Learn CockroachDB SQL](https://www.cockroachlabs.com/docs/learn-cockroachdb-sql.html) docs with a second set of more advanced instructions.

**Comment by jseldess** [comment]
Great idead, @sploiselle. Thanks for adding this.
