### ISSUE TITLE
Upload all training content to YouTube

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#6488]
Upload content from "Getting Started with CockroachDB" to YouTube. 

1. Work with Dan to develop a format for the content description. 
2. Upload all video content and apply a unique description for each adapted from their description in LearnDot. 
3. Upload script file for each video.

**Comment by SpicyThrow** [comment]
Touched base with Dan and he is interested in assisting this project. We need to re-write all of the content descriptions to take advantage of the YouTube algorithm. This will be work intense, but it should worth it if we can catch the interest of the algorithm. 

Working document for this effort can be found here: https://docs.google.com/document/d/1VqFgWRsIA_N04Uu5BbZskfxaOeIzrlFKZNfCLI1La7I/edit?usp=sharing

**Comment by SpicyThrow** [comment]
I sent content to Dan Kelly for review.

**Comment by SpicyThrow** [comment]
Dan reviewed the content and suggested minor changes. 

I will now:

• upload them and add the descriptions. 
• Add them all to the Cockroach University Playlist
• Let Dan know when they're all in there. 

Then Dan will:

• Add tags
• Add Cards
• Add End Screens
• Publish
• Schedule Social Media

**Comment by jseldess** [comment]
This is awesome, @SpicyThrow! Have you chatted with Dan about how to socialize these videos? We should create a docs issue to cross-reference these videos where relevant. Are you in favor of that?

**Comment by SpicyThrow** [comment]
@jseldess Yes, I just spoke with Dan and he is formulating some social media posts. 

As discussed, yes would be good to cross-reference, but would need to identify appropriate docs and implementation strategy.

**Comment by SpicyThrow** [comment]
All content is now uploaded. Dan has been notified and will implement the items listed above sometime next week. Content is tentatively scheduled for release on Feb 28.

**Comment by SpicyThrow** [comment]
Content is now live.
