### ISSUE TITLE
CC: Getting Started video(s)

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#6496]
Sync with Lakshmi and Dan to figure out responsibilities and next steps for CC getting started video(s).

**Comment by Amruta-Ranade** [comment]
Meeting notes: https://docs.google.com/document/d/1ASFt_fYBDfSqPpg64DD16jfY4Gzbwsbxs-ux9HQJyDM/edit?usp=sharing

**Comment by lnhsingh** [comment]
Closing, as this seems out-of-date now. We can revisit later / open a new Jira issue to track
