### ISSUE TITLE
Clarify index creation for FK

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#6498]
Re: [CREATE TABLE](https://cockroachlabs.com/docs//v19.1/create-table.html)

## Issue Description

> Foreign key columns must be indexed when creating the table using INDEX, PRIMARY KEY, or UNIQUE.

This makes it sound like an index on the outgoing columns must be explicitly created. The index is created automatically.

**Comment by jseldess** [comment]
Somewhat related to https://github.com/cockroachdb/docs/issues/6344.
