### ISSUE TITLE
Storage layer garbage collection wrong gc.ttl

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#6505]
https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#garbage-collection states: `the garbage collection period is 24 hours, but it can be set at the cluster, database, or table level through replication zones.`.

The default garbage collection period is 25 hours (90000 seconds).

**Comment by jseldess** [comment]
Default is correctly documented here: https://www.cockroachlabs.com/docs/v19.2/configure-replication-zones.html#replication-zone-variables
