### ISSUE TITLE
start a local cluster missing information

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#6517]
https://www.cockroachlabs.com/docs/v19.2/secure-a-cluster.html#step-5-access-the-admin-ui

this doc on step 5 states:

`Use the Databases, Statements, and Jobs pages to view details about your databases and tables, to assess the performance of specific queries, and to monitor the status of long-running operations like schema changes, respectively.`

the user that is created like so: `CREATE USER max WITH PASSWORD 'roach';` will require the same sql priveledges they need on the shell in order to view the databases and tables pages respectively. this behavior was changed in 19.2.3 and 19.1.8(i believe).

**Comment by rmloveland** [comment]
@taroface my uninformed reading is that this might be part of / relate to #6331  - do you agree?

**Comment by taroface** [comment]
@rmloveland Yes, I think so. Feel free to assign this to me!
