### ISSUE TITLE
Add more context on the purpose of each cert in the certificates document

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6533]
Artem Ervits (dbist) commented:

## Title
Additional context for certificates

## Description
We had multiple inquiries from a single customer on the purpose of each cert, for example (what cert goes with a load balancer configuration, what's needed for intra-cluster communication, etc). We also need to be more specific in terms of what end-user cert is required, perhaps giving an example with user Mary as ETL user, vs. Bob the admin, vs. a node and their associated certs?

Also it is unclear whether loadbalancer cert requires new nodes added to the cert every time a node goes in and out of the cluster. That should be highlighted in the document.

## Expected Audience

Jira Issue: DOC-428

**Comment by Amruta-Ranade** [comment]
https://docs.google.com/document/d/1pqObpgbU0KGwrWJxWXEMjWfE7nz9TzYiJY1ig3cd_OU/edit?ts=5e4466ce

**Comment by Amruta-Ranade** [comment]
https://cockroachdb.zendesk.com/agent/tickets/4638

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4638](https://cockroachdb.zendesk.com/agent/tickets/4638) has been linked to this issue.
