### ISSUE TITLE
What's New in v2.1.0 Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#6536]
Re: [What's New in v2.1.0](https://cockroachlabs.com/docs//releases/v2.1.0.html)

## Issue Description

`Therefore, this version will no longer be supported after the Spring 2020 release.` is ambiguous.  

## Suggested Resolution 

For each release, provide an exact date when the support ends. A page with table listing all versions of the following would be helpful.

| Version | Release Date | EOSL Date | Suggested Upgrade Path |
| -------  | ------------- | -----------| -------------------------- |
| 2.1.x | 10/30/2018  | xx/xx/xxxx |...  |
| 19.1.x  | 4/30/2019  | xx/xx/xxxx |...  |

**Comment by jseldess** [comment]
We're now more specific about dates for end of support and EOL. We've also added an explicit table with support expiration details in the meantime: https://www.cockroachlabs.com/docs/releases/release-support-policy.html#current-supported-releases.

**Comment by robert-s-lee** [comment]
Awesome.  Thank you.
