### ISSUE TITLE
Whitelist IPs: can we give more detail here?

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6537]
@timveil is running his app in K8s and was trying to connect to a CockroachCloud cluster. He mentioned that if you're running in K8s, its very unclear which IP to use to whitelist. We know that K8s pod IPs might change and so whitelisting them isnt a great idea, and most of our K8s app users just leave their network open. That said, we should provide guidance : 
1. how to find the right IP of the k8s pods (Tim said he checked which client was connecting to the DB to figure it out) 
2. then caveat it by saying, this probably changes often, so its not super dependable. 

In the long term, as we know we are just going to eliminate this requirement but in the short term, its worth providing more guidance.

**Comment by lnhsingh** [comment]
Closing in favor of CC-2693
