### ISSUE TITLE
Changing DB settings for Cloud 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6538]
Users can currently change certain settings on the DB like replication factor. I learnt recently that they can even drop the SQL prober table (monitoring_table) which they probably shouldn't (talked to SREs about it). Can we say somewhere what the settings in the DB a user can change, and what they can't change and maybe even more importantly what we recommend they DON'T change? Could be two questions in FAQs.

**Comment by kannanlakshmi** [comment]
cc @timveil  @joshimhoff for visibility

**Comment by Amruta-Ranade** [comment]
Yes! Do we have a list already or should I find a source for the list?

**Comment by kannanlakshmi** [comment]
I don't believe we have a list anywhere. Source would be the engineering team, maybe @celiala can help you find one contact?

**Comment by joshimhoff** [comment]
Longer term, we should make it impossible to change settings that we want to control. With enough CC clusters, not having this control would hurt us a lot. 

Do we think the docs page will help? I'm not against it, but I don't know if I think people will check it.

**Comment by Amruta-Ranade** [comment]
I agree with @joshimhoff . The docs page can be a stop-gap measure, but changing DB settings should be disallowed in the product.

**Comment by joshimhoff** [comment]
I would suggest skipping the stopgap, letting ourselves feel the pain of not having true control, and eventually prioritizing the engineering work once we are sick of the pain!

Part of why I think this is that I believe it will be hard to document all these things.

**Comment by Amruta-Ranade** [comment]
Well, we are doing the users a disservice if we don't provide guidance when we have the knowledge. Also, it's not only our external users who refer to docs -- Support and SEs refer to docs as well. They appreciate all the information we can give them.

**Comment by joshimhoff** [comment]
Hmm I see you point. Thinking more, I can see the value to the customer of having a page that says "these are things you can change, here are things we suggest you don't change, if you want to have a good CC experience".

**Comment by Amruta-Ranade** [comment]
Yep. And we will link to the page from multiple places (production checklist, FAQs, etc.) to make it as hard-to-miss as possible. But, just to reiterate, these are all stop-gap measures and the best-case scenario would be disallowing it in the product.

**Comment by lnhsingh** [comment]
Seeing as this issue is now a year old, do we still need a doc update for this? Or have we implemented some controls?

cc @joshimhoff @kannanlakshmi

**Comment by joshimhoff** [comment]
I don't really feel this is worth doing right now. I don't think we have a good answer to the cluster setting split, and I think we should focus on putting technical controls in place. Other SREs could disagree; you could post to our team slack and see if anyone cares enough to engage. But to me I'd close for now!

**Comment by lnhsingh** [comment]
I will close this for now :) Thanks Josh!
