### ISSUE TITLE
Authentication Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6553]
Re: [Authentication](https://cockroachlabs.com/docs//v19.2/authentication.html)

## Issue Description
example for password authentication still points to a certificate authentication example
## Suggested Resolution 
create a password authentication example

**Comment by dbist** [comment]
@Amruta-Ranade I'm on time crunch today otherwise I'd contribute an example.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7704/
