### ISSUE TITLE
document Tibco Composite and CockroachDB connection setting

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#6554]
Exalate commented:

A customer was able to connect Tibco Composite to CockroachDB with configuration setup on the driver level.  Should get the setting and document for reference.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4711](https://cockroachdb.zendesk.com/agent/tickets/4711) has been linked to this issue.

**Comment by jseldess** [comment]
cc @vy-ton, @ericharmeling, @ianjevans for triage.
