### ISSUE TITLE
Upgrade policy for cloud

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6559]
Currently we don't say anything about our upgrades policy for CockroachCloud customers. We are working on a feature that allows upgrades to be automated. But meanwhile (and even after this feature is ready), we want to say *something* about our policy in the docs. We've also had customers ask us what the policy is. 

@emily-horing is working on finalizing the policy, we also have a version in Confluence. Can we put a version of that in docs?

**Comment by Amruta-Ranade** [comment]
https://github.com/cockroachlabs/managed-service/pull/2101

**Comment by Amruta-Ranade** [comment]
https://docs.google.com/document/d/1xXCqDMxjwmgoh6uHgHjFLNd-RxjvUqxp0UYO3RQC-jA/edit?ts=5e4c4d33#heading=h.3un11yvn9xp3

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/6717
