### ISSUE TITLE
sql: Document how to consistently page through results

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/docs#657]
The usual way to do this is one SELECT query per page that uses LIMIT/OFFSET, but since it doesn't make sense to run this in a sql transaction, any insertions/deletions could make this an inconsistent view of the table.

CockroachDB has AS OF SYSTEM TIME implemented, which means we can let the user iterate over a consistent version of their database without a transaction. This would work by selecting `cluster_logical_timestamp()` in the first SELECT, passing it through the page (like limit and offset are) and using it in subsequent queries. @mjibson has already implemented paging exactly like this for the `./cockroach dump` command.

See the discussion in https://github.com/cockroachdb/cockroach/issues/9227#issuecomment-246157219

**Comment by jseldess** [comment]
Duplicate of https://github.com/cockroachdb/docs/issues/1067
