### ISSUE TITLE
Document new approach to locking and queueing in the key value layer

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6571]
We need to update the architecture documentation to discuss the new approach to locking and queuing in the key-value layer.

AFAICT this new approach is enabled by the new concurrency control package/lock table referred to by [this PR][wip_sfu] (and [this one][sumeer_locktable], and probably others).

Estimated scope of work:
  
- [ ] Update the architecture docs (probably the [storage layer][storage layer]) to describe the new concurrency manager / how locking and queuing works

- [ ] Review other areas of the architecture docs to ensure they reference (or do not reference) this new layer, as appropriate

[wip_sfu]: https://github.com/cockroachdb/cockroach/pull/43775
[sumeer_locktable]: https://github.com/cockroachdb/cockroach/pull/43740
[storage layer]: https://www.cockroachlabs.com/docs/dev/architecture/storage-layer.html

**Comment by jseldess** [comment]
Thanks for being proactive here, @rmloveland. Is this not reflected on the KV product roadmap? I'm surprised we don't already have a docs issue for it.

**Comment by rmloveland** [comment]
> Is this not reflected on the KV product roadmap? 

I did some searching in AT but was not able to find anything beyond the SQL-level description of the work.
