### ISSUE TITLE
Underscore how dangerous "Insecure" mode

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6574]
Jesse Seldess (jseldess) commented:

We call out the dangers of "insecure" mode in our [production checklist](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#security) and in the [recommendations sections of our insecure deployment guides](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises-insecure.html#recommendations). However, we don't education users about these dangers in any of our getting started docs or tutorials, e.g., https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html, https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb.html#insecure, https://www.cockroachlabs.com/docs/stable/demo-replication-and-rebalancing.html. 

We should fix this and probably default to secure everywhere. 

Jira Issue: DOC-432

**Comment by aaron-crl** [comment]
It would help if our getting started story had something to automatically handle certificate issuing and node provisioning. Let's also add similar warning markings to the getting started as we have in the production checklist.

Possibilities:

- Add red warning text to getting started Insecure page
- Improve user story for local testing and development (with certificates)
  - Add getting started provisioning script to create local cluster with a prompt for local primitives
- Coordinate with product to make default secure mode as simple as secure (and remove need for feature - or at least this incarnation of it)

I think the warning and script are probably the best in the short term. I can pick up the script work myself.

In addition, I'll work https://github.com/cockroachdb/cockroach/issues/32448 to see if we can improve the experience and ultimately remove the need for this warning.

**Comment by Amruta-Ranade** [comment]
From @knz on Slack:

CockroachDB's "insecure mode" is not a production feature
- Users must be strongly, very strongly discouraged from using --insecure in production deployments
- Users must be informed in no uncertain terms that their data is completely at risk of loss and breach of privacy when they run with --insecure
- We are never going to make this better
- if users want certain combinations of security features, they must ask for them without referring to the word "insecure"
Tips:
- use the phrase "I prefer my connections not to be encrypted"
- use the phrase "I don't want to use certificates"
- use the phrase "I would like more flexibility in privilege management"
- everytime, provide example use cases so we understand what customers need
- in  100% of cases what our customer needs is not related to "insecure mode"

**Comment by awoods187** [comment]
I think its really important to distinguish insecure mode is not good for production and insecure mode is bad. Insecure mode is quite useful for quick testing and in particular is quite useful for new users trying the product out. I'm fully on board with promoting secure mode in production, but emphasizing it as never being useful seems to be going too far and will likely hurt adoption given the complexity in setting up secure mode.

**Comment by knz** [comment]
This was discussed today: "insecure mode" can go away once we have a pleasant UX for the alternative:

- online web playground to try out CockroachDB features without installation
- proper password support including secure SCRAM authentication
  - then the password is embedded in the conn URL and no need to set up certs
  - NB: `cockroach demo` already sets up secure clusters now, with passwords

All in all the plan is that "insecure mode" will be removed from the user-facing product.

**Comment by awoods187** [comment]
Yeah, that sounds great @knz. It will be a real differentiator to have an easy secure mode on by default for our customers. In the meantime, until we have that pleasant UX, let's not jump too aggressively in our documentation.

**Comment by jseldess** [comment]
Working on a playground and easy in-Docs interactive tutorials now. Rough example: https://deploy-preview-7770--cockroachdb-docs.netlify.app/docs/stable/learn-cockroachdb-sql.html

**Comment by jseldess** [comment]
Marking this as "Later" since it's best to wait for the future security UX before making broad changes here.
