### ISSUE TITLE
duration,builtins: fix interval cast involving years to match postgres

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6579]
PR: https://github.com/cockroachdb/cockroach/pull/43923

From release notes:
> Previously, intervals cast to integers and floats would rely on a year being 365 days. To match `extract('epoch' from interval)` behavior in PostgreSQL/CockroachDB to 365.25 days, casting to integers and floats now values a year at 365.25 days in seconds instead of 365 days. [#43923][#43923] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw

**Comment by ericharmeling** [comment]
Fixed by #6785.
