### ISSUE TITLE
ui: reserve the statements endpoint to admin users

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6580]
PR: https://github.com/cockroachdb/cockroach/pull/44349

From release notes:
> An admin user is now required to access statement details in the Admin UI and HTTP endpoint. Previously, any user could access these details, which could result in users accessing data that they didn't have privileges to see. [#44349][#44349] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@jseldess I think this should be covered by #6640, so I'll add this to the list of issue fixes on that PR.
