### ISSUE TITLE
cli: new command `auth-session {login,logout,list}`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6584]
PR: https://github.com/cockroachdb/cockroach/pull/43872

From release notes:
> The new command `cockroach auth-session login` (reserved for administrators) creates authentication tokens with an arbitrary expiration date. Operators should be careful to monitor `system.web_sessions` and enforce policy-mandated expirations by either using SQL queries or the new command `cockroach auth-session logout`. [#43872][#43872] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Merged with https://github.com/cockroachdb/docs/issues/6631
