### ISSUE TITLE
server,cli,sql: enable setting a password for the root user

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6586]
PR: https://github.com/cockroachdb/cockroach/pull/43893

From release notes:
> The `root` user can now have a password, like any other member of the admin role. However, as in previous versions, the HBA configuration cannot be overridden to prevent `root` from logging in with a valid TLS client certificate. This special rule remains enforced in order to ensure that users cannot "lock themselves out" of administrating their cluster. [#43893][#43893] {% comment %}doc{% endcomment %}
> The `root` user remains special with regard to [authentication](../v20.1/authentication.html) when some system ranges are unavailable. In that case, password authentication will fail, subject to a timeout set to the minimum of 5 seconds and the configured value of `system.user_login.timeout`, because the password cannot be retrieved from a system table. However, certificate authentication remains available. [#43893][#43893] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
