### ISSUE TITLE
import,backup: show redacted secrets in job UI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6587]
PR: https://github.com/cockroachdb/cockroach/pull/44737

From release notes:
> `SHOW JOBS` and the Jobs page in the Admin UI now show the parameters used for connecting to external storage, with only the values of parameters classified as secrets redacted. [#44737][#44737] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - no docs updates needed.
