### ISSUE TITLE
jobs: allow blocking job adoption via sentinel file

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6588]
PR: https://github.com/cockroachdb/cockroach/pull/44786

From release notes:
> It's now possible to disable job execution on a node in emergency cases. To do so, place a `DISABLE_STARTING_BACKGROUND_JOBS` file in the node's first store directory. [#44786][#44786] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing this issue - chatted with @dt and @mwang1026. Both are 50/50 on if we need to document it or not. Michael brought up that even if we do document it, people might be hesitant to use the file and reach out to support anyway. I think leaving this undocumented (for now) is fine.
