### ISSUE TITLE
server,sql,pgwire: let client conns timeout on unavailable clusters

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6590]
PR: https://github.com/cockroachdb/cockroach/pull/44022

From release notes:
> CockroachDB will now report a timeout error when a client attempts to connect via SQL or the Admin UI and some system ranges are unavailable. The previous behavior was to wait indefinitely. The timeout is configurable via the [cluster setting](../v20.1/cluster-settings.html) `server.user_login.timeout` and is set to 10 seconds by default. The value "0" means "indefinitely" and can be used to restore the pre-v20.1 behavior. This timeout does not apply to the `root` user, which is always able to login on unavailable clusters. [#44022][#44022] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Closing since this variable's documentation is already up on the [20.1 cluster settings page](https://www.cockroachlabs.com/docs/dev/cluster-settings.html).
