### ISSUE TITLE
sql: add percent complete estimate to SHOW QUERIES

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6593]
PR: https://github.com/cockroachdb/cockroach/pull/42518

From release notes:
> Added a rough estimation of execution progress to [`SHOW QUERIES`](../v20.1/show-queries.html). [#42518][#42518] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@dt 
David, which response column of `SHOW QUERIES` displays percent complete estimate information? I recently [updated the example output](https://github.com/cockroachdb/docs/pull/6764), and didn't see it anywhere

**Comment by dt** [comment]
it shows up in the `executing` field once it is non-zero. small/fast queries likely complete before it is every updated.

**Comment by ericharmeling** [comment]
Ah. OK. Thank you!
