### ISSUE TITLE
builtins: add extract functionality for intervals

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6596]
PR: https://github.com/cockroachdb/cockroach/pull/43293

From release notes:
> Extract can now be called on an interval (e.g., `extract(day from interval '254 days')`). This follows the PostgreSQL implementation. Furthermore, this deprecates `extract_duration`, which will be removed at a later date. [#43293][#43293] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #6785.
