### ISSUE TITLE
timeutil: unify parsing of AT TIME ZONE and SET TIME ZONE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6597]
PR: https://github.com/cockroachdb/cockroach/pull/43414

From release notes:
> CockroachDB previously did not support `AT TIME ZONE` parsing for anything other than precise location strings (e.g., `AT TIME ZONE 'Australia/Sydney'`). CockroachDB now supports parsing `AT TIME ZONE` with various other offset behaviors supported by `SET TIME ZONE` (e.g., `AT TIME ZONE '+3'`, `AT TIME ZONE 'GMT+4'`). [#43414][#43414] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't require documentation/
