### ISSUE TITLE
timeutil: unify parsing of AT TIME ZONE and SET TIME ZONE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6598]
PR: https://github.com/cockroachdb/cockroach/pull/43414

From release notes:
> CockroachDB now supports `SET TIME ZONE` with colons (e.g., `+4:00`). [#43414][#43414] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't require documentation.
