### ISSUE TITLE
sql: Non-materialized Views Overview

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#660]
Reference:
- Dev: @a-robinson 
- RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/views.md
- Issue: https://github.com/cockroachdb/cockroach/issues/2971
- PRs:
  - https://github.com/cockroachdb/cockroach/pull/9212
  - https://github.com/cockroachdb/cockroach/pull/9355
  - https://github.com/cockroachdb/cockroach/pull/9724
  - https://github.com/cockroachdb/cockroach/pull/10009
  - https://github.com/cockroachdb/cockroach/pull/9988

**Comment by a-robinson** [comment]
Ah, sorry for not putting the docs-todo label on the PRs that have gone out so far! I was going to wait until more of the support was in. Since I haven't gone through this before, what's my role in the documentation process?

**Comment by jseldess** [comment]
Np, @a-robinson. We don't have a super strict/consistent process yet. It's best if you'd put that label on doc-relevant PRs going forward, perhaps with an comment to me if the feature isn't docs-ready. 

Typically, once a feature is ready, Sean or I look through the relevant PRs/RFCs/etc and then go to the dev with questions. 

Once views are ready for us to test and document, would you mind updating this ticket?

**Comment by a-robinson** [comment]
Sure, will do. Assigning to myself for tracking purposes until the feature is ready

**Comment by jmank88** [comment]
FYI the RFC link points to a dead branch: s/develop/master
[https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/views.md](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/views.md)

**Comment by jseldess** [comment]
Thanks for catching that, @jmank88. Fixed.
