### ISSUE TITLE
sql: enable clearing user password

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6605]
PR: https://github.com/cockroachdb/cockroach/pull/43892

From release notes:
> [`CREATE USER`](../v20.1/create-user.html) and [`ALTER USER`](../v20.1/alter-user.html) now accept the parameter `[WITH] PASSWORD NULL` to indicate the user's password should be removed, thus preventing them from using password authentication. This is compatible with PostgreSQL. [#43892][#43892] {% comment %}doc{% endcomment %}
>
> Previously, when setting a user's password to enable password authentication for the user, it was not possible to revert this choice. The only way to disable password authentication was to either drop the user or add a specific per-user HBA rule. This has been fixed and the PostgreSQL-compatible [`ALTER USER WITH PASSWORD NULL`](../v20.1/alter-user.html) statement can now be used to clear the user's password. [#43892][#43892] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with Raphael and Richard on Slack, there isn't any use case for documenting `CREATE USER WITH PASSWORD NULL` since it is already the default value when a password is not specified. We decided to document the `ALTER USER` use-case only.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
