### ISSUE TITLE
colserde: add simple serialization for DECIMALs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6606]
PR: https://github.com/cockroachdb/cockroach/pull/43311

From release notes:
> Previously, [`DECIMAL`](../v20.1/decimal.html) types could not be sent over the network when the computation was performed by the [vectorized engine](../v20.1/vectorized-execution.html). This has been fixed, and the vectorized engine now fully supports `DECIMAL` type. [#43311][#43311] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #6327.
