### ISSUE TITLE
sql: remove restriction of foreign key on multiple outbound columns

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6607]
PR: https://github.com/cockroachdb/cockroach/pull/43417

From release notes:
> Previously, there was a restriction that foreign keys could only reference one outbound column at any given point in time (e.g., in `CREATE TABLE test(a int)`, having two foreign keys on column `a` was not allowed). This restriction is now removed. [#43417][#43417] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
FK https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recLQknmolY1ZtTaX
