### ISSUE TITLE
sql: introduce localtime and localtimestamp functionality

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6611]
PR: https://github.com/cockroachdb/cockroach/pull/44042

From release notes:
> Added `localtime`, which by default returns the current time as the [`TIME`](../v20.1/time.html) data type (as opposed to `current_time`, which returns the [`TIMETZ`](../v20.1/time.html) data type). [#44042][#44042] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #6785.
