### ISSUE TITLE
tree: fix H:M:S related bugs for intervals

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6612]
PR: https://github.com/cockroachdb/cockroach/pull/43924

From release notes:
> Added support for having `D:H:M`, `D:M:S.fff`, or `D:H:M:S.fff` for interval parsing if the first element is a decimal or empty (e.g., `:04:05` and `1.0:04:05` would be `04:05:00` and `1 day 04:05:00` respectively). [#43924][#43924] {% comment %}doc{% endcomment %}
>
> Previously, floats were supported in `H:M:S` formats for interval parsing (e.g., `1.0:2.0:3.0`), which did not make sense. Floats are no longer allowed for the M field. [#43924][#43924] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw
