### ISSUE TITLE
sql: allow booleans in SET tracing and friendlier error message

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6614]
PR: https://github.com/cockroachdb/cockroach/pull/44260

From release notes:
> Previously, CockroachDB would return an internal error when using [`SET tracing`](../v20.1/set-vars.html#set-tracing) with any type other than string. Now it will return a regular query error. Additionally, boolean arguments are now supported in `SET tracing`, and `true` is mapped to `on` mode of tracing whereas `false` is mapped to `off`. [#44260][#44260] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is a bug fix that does not require documentation.

Also, I think it's helpful to unify the "on"/"off" session variables in our documentation, even if booleans are supported. This PR helps with this: https://github.com/cockroachdb/cockroach/pull/46219.
