### ISSUE TITLE
sql: remove explicit index IDs in foreign key descriptors

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6615]
PR: https://github.com/cockroachdb/cockroach/pull/43332

From release notes:
> Indexes that reference, or are referenced by, a foreign key constraint can now be dropped if there is another suitable index for the constraint. [#43332][#43332] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
FK compatibility https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recLQknmolY1ZtTaX
