### ISSUE TITLE
builtins: support custom bases log function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6616]
PR: https://github.com/cockroachdb/cockroach/pull/41848

From release notes:
> Added a `log` [builtin](../v20.1/functions-and-operators.html) for any base (e.g., `log(2.0, 4.0)`). [#41848][#41848] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Picked up in https://github.com/cockroachdb/docs/pull/6470.
