### ISSUE TITLE
sql,ui: enable non-admin users to see their own jobs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6617]
PR: https://github.com/cockroachdb/cockroach/pull/44345

From release notes:
> Non-admin users can now query [`SHOW JOBS`](../v20.1/show-jobs.html) and `crdb_internal.jobs` and see their own jobs. [#44345][#44345] {% comment %}doc{% endcomment %}
> Non-admin users can now use the [Jobs](../v20.1/admin-ui-jobs-page.html) page of the Admin UI to see their own jobs. [#44345][#44345] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Update Jobs page:

- https://github.com/cockroachdb/cockroach/issues/45017
