### ISSUE TITLE
colexec: add unordered distinct

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6618]
PR: https://github.com/cockroachdb/cockroach/pull/42522

From release notes:
> [Vectorized execution engine](../v20.1/vectorized-execution.html) now supports `DISTINCT` on unordered input. [#42522][#42522] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recagjuRqKN5Jxh1n
