### ISSUE TITLE
builtins,timeutil: fix AT TIME ZONE and timezone builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6619]
PR: https://github.com/cockroachdb/cockroach/pull/44099

From release notes:
> CockroachDB now supports `AT TIME ZONE` and the `timezone` [builtin](../v20.1/functions-and-operators.html) for `time` and `timetz` methods. [#44099][#44099] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Time fixes https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recgAULbWY1898miw
