### ISSUE TITLE
builtins,timeutil: fix AT TIME ZONE and timezone builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6620]
PR: https://github.com/cockroachdb/cockroach/pull/44099

From release notes:
> CockroachDB supports `timezone(timestamp(tz), str)`, but PostgreSQL supports the inverse `timezone(str, timestamp(tz))`. Both are now supported, and the former version will be deprecated at a later stage. - CockroachDB now supports `str AT TIME ZONE str`, removing the need for an explicit cast. [#44099][#44099] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #6785.
