### ISSUE TITLE
colexec: add bool_or/bool_and operators

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6621]
PR: https://github.com/cockroachdb/cockroach/pull/44164

From release notes:
> The [vectorized execution engine](../v20.1/vectorized-execution.html) now supports `bool_and`/`bool_or` [builtin](../v20.1/functions-and-operators.html) aggregation functions. [#44164][#44164] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recagjuRqKN5Jxh1n
