### ISSUE TITLE
sql: add ZONECONFIG privilege for allowing users to edit zone config at the database level

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6622]
PR: https://github.com/cockroachdb/cockroach/pull/43941

From release notes:
> Non-admin users can now use the `ZONECONFIG` privilege to create, edit, and delete zone configurations. [#43941][#43941] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
privileges zone config https://airtable.com/tblD3oZPLJgGhCmch/viwOj1Qb7D4gjtemc/recCHyCs4TR6kO3gs

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
