### ISSUE TITLE
MovR Improvement: Create v20.1 version

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#6637]
MovR-Flask currently runs on a multi-region CockroachCloud cluster running CRDB v19.2.

To create a v20.1 version, we need to do one of the following:

a. Deploy CRDB v20.1 manually on GCP (pre-release)
b. Wait until CC upgrades to v20.1 (post-release)

**Comment by jseldess** [comment]
@ericharmeling, CC will soon offer the ability to upgrade your cluster for 20.1 from the CC Console. I know because I've been writing the docs for that.
