### ISSUE TITLE
Review TW interview loop for Associate level

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6638]
- [x] Take home exercise
- [x] Phone screen with Jesse
- [x] Information design with Amruta
- [x] Technical learning with eng
- [x] Technical editing with Lauren
- [x] Review / iterate on loop
- [x] Send to recruiting

**Comment by lnhsingh** [comment]
@jseldess - took a stab at reworking the interview loop for the Associate Tech Writer position. A summary of the changes:

- [Interview Plan](https://docs.google.com/document/d/1hEi4U0v_WLrlFx3OCCcQYFcTisb8topP6ZDYdrGJwmY/edit#): Updated links
- [Take-home exercise](https://docs.google.com/document/d/18XPjfdgIXkcb91EyuzsNXqX4KFbu_MbqsQqdmLC5SFs/edit): No additional edits
- [Phone Screen](https://docs.google.com/document/d/12Y9UXptCVL-ElXnutLgWwQARDU_ttS_V3yit-1r7qf0/edit#heading=h.m57ifnp610ce): No edits
- [Information Design](https://docs.google.com/document/d/1yThAx9qjr97wnaUuAGGv5LYNzy03Rpg3aDkKnv5YVJ0/edit#): Edited "Corresponding job responsibilities/requirements" section
- [Technical Learning](https://docs.google.com/document/d/1puCJy3QswdIWJkuHK_DYyCSQKlvCy0aTcy0547SVoC0/edit#heading=h.c0gfergqw24h): Combined the two sessions to focus on one topic. Second half of the interview would be done with a tech writer.
- [Technical Editing](https://docs.google.com/document/d/1q9nJkSfeoI6icJ-zc4o2TQi4TRkWpLsudYS1B6PMPlQ/edit#): Changed the raw text and updated competencies / assessment questions.

**Comment by jseldess** [comment]
Thanks, @lnhsingh! Just reviewed and most everything looks great. I have a few questions about the technical learning exercise still, in the doc.
