### ISSUE TITLE
CockroachCloud best practices audit

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#6650]
Ryan Kuo (taroface) commented:

Collect information from the CockroachCloud team on best practices for Kubernetes deployments. 

The CC docs have great documentation of SQL performance tuning, but this would focus on deployment guidance, like VM types, memory and CPU requests in different scenarios, use of load balancers, monitoring endpoints, etc. 

Relates to #4954 

Jira Issue: DOC-437

**Comment by jseldess** [comment]
@taroface, there are some CC GCE best practices [here](https://github.com/cockroachlabs/managed-service/issues/495#issuecomment-484277201).

**Comment by taroface** [comment]
Google doc questionnaire for @DuskEagle: https://docs.google.com/document/d/1W5VsvvjpxCJRQUMD8Tb7stLK_MgNQxpEsp4BFZlbZE0/edit

Also attaching Markdown version.

**Comment by taroface** [comment]
Also tagging @DuskEagle on this, just for visibility. Thank you!
