### ISSUE TITLE
cloud: copy for hardware choice

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6653]
![image](https://user-images.githubusercontent.com/36172966/75044075-04742b00-548f-11ea-9c26-7a5ac50d936b.png)

We should add a sentence that says that if a user does not find a hardware config they like, they should contact us. 
Same for cloud provider -- the FAQs tell you why we don't offer something. But technically we can still create clusters in eu-west-3 (which is a constrained region), can we add a line that says so?

**Comment by Amruta-Ranade** [comment]
How about "For custom configurations, contact us."

**Comment by kannanlakshmi** [comment]
Yes sounds great!

**Comment by Amruta-Ranade** [comment]
@laurenbarker for making the copy edit I think. Please reassign as you see fit.

**Comment by laurenbarker** [comment]
Should "contact us" be a link to an email?

**Comment by kannanlakshmi** [comment]
yes, sales@cockroachlabs.com
