### ISSUE TITLE
Frequently Asked Questions Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6655]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//v19.2/frequently-asked-questions.html)

## Issue Description
Add JSONB key ordering statement to FAQ due to it's common nature.

## Suggested Resolution 
```
This question has been asked a few times and the general response is that there isn't a concept of ordering among json fields
10:47
the internal representation changes the ordering to enable more efficient access into the fields, and can do it because jsonb doesn't have any ordering gaurantees on its fields
```

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6654.
