### ISSUE TITLE
Windows Installation Guide

### ISSUE THREAD

**Issue by katedoebler** [cockroachdb/docs#6656]
When following the windows installation guide, the flow to install and get the product up and running is confusing and leads to errors: 

![image](https://user-images.githubusercontent.com/60902507/75051914-bb2ad800-549c-11ea-8312-c210d184fb31.png)

**Comment by jseldess** [comment]
@katedoebler, it looks like you missed this:
> navigate to the directory containing the executable. 

Can you move into the directory with the executable and then try .\cockroach.exe version again?
