### ISSUE TITLE
Developer Guide v2

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6667]
This issue tracks tasks we'd like to add to the Developer Guide for v2 (the version in #5865 represents "v1").

- [ ] Show examples of `UPSERT`, and when to use
- [ ] Update 'Insert data' page with more info about e.g., `INSERT`s when there are uniqueness conflicts (`INSERT ... ON CONFLICT` or the aforementioned `UPSERT`)
- [ ] Update the 'Schema Design' section of the 'Make Queries Fast' page with an illustrative example (like we have for SQL tuning)
- [ ] Add batch write and delete loops
- [ ] Connection pooling

**Comment by ericharmeling** [comment]
All topics mentioned in the description of this issue are included in the proposed content plan for the Developer Guide v2 (see the [Developer Guide Overhaul Atlassian page](https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/1076002864/Developer+Guide+Overhaul) and linked tracking docs).

We'll be tracking this project with more granular issues. For high-level planning view, see https://github.com/cockroachdb/docs/projects/63.
