### ISSUE TITLE
sql: SAVEPOINT SQL document

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#667]
Document `SAVEPOINT cockroach_restart` so it's visible in the SQL grammar.

Reference [Transaction retries](https://www.cockroachlabs.com/docs/transactions.html#transaction-retries)

**Comment by jseldess** [comment]
Should this be closed now that https://github.com/cockroachdb/docs/pull/672 has merged?

**Comment by sploiselle** [comment]
Closed by #672
