### ISSUE TITLE
windows: LoadLocation doesn't work on windows if Go is not installed

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#6676]
Two users have run into this error: 

org.postgresql.util.PSQLException: ERROR: invalid value for parameter "TimeZone": "GMT"
org.postgresql.util.PSQLException: ERROR: invalid value for parameter "TimeZone": "America/Regina" Detail: timezone data cannot be found\

Both users are on windows, it seems that they are running into [this](https://github.com/golang/go/issues/21881). 

A potential workaround is: 

1) Installing GO and setting the GOROOT

2) Download zoneinfo.zip and make a pseudo GO install

We have some timezone docs for Linux users but nothing for windows.

**Comment by jseldess** [comment]
@roncrdb, isn't this known limitation the right doc? https://www.cockroachlabs.com/docs/stable/known-limitations.html#location-based-time-zone-names-on-windows

If yes, we should find a way to improve that and make sure Windows users can find it.

**Comment by roncrdb** [comment]
@jseldess that looks about right.

**Comment by jseldess** [comment]
This came up again. I think we should have a tip about it on the install page for Windows. Also, @knz, do you think we can provide more explicit instructions, or are there good resources to look to? Or is it sufficient to tell users to install Go and leave it at that?

**Comment by knz** [comment]
I believe the best approach is to provide a copy of the zip file for download on the web site, and point to that doc web page from the error message.

**Comment by mattcrdb** [comment]
There are some steps [here](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1587443188329000)

**Comment by jseldess** [comment]
From @tv:

alright got it working but clearly there is some things we need to clarify.  I had to manually set both GOROOT and GOPATH on my machine.  The big gotcha here is that a prerequisite is you must install Go and get paths right.  once i did it worked.  here was the relevant output...

```
PS E:\timve\Downloads\cockroach-v20.1.0.windows-6.2-amd64\cockroach-v20.1.0.windows-6.2-amd64> $env:GOROOT                                                        
C:\Go
PS E:\timve\Downloads\cockroach-v20.1.0.windows-6.2-amd64\cockroach-v20.1.0.windows-6.2-amd64> $env:GOPATH                                                        
C:\Go\bin
PS E:\timve\Downloads\cockroach-v20.1.0.windows-6.2-amd64\cockroach-v20.1.0.windows-6.2-amd64> go version                                                         
go version go1.13.9 windows/amd64
PS E:\timve\Downloads\cockroach-v20.1.0.windows-6.2-amd64\cockroach-v20.1.0.windows-6.2-amd64> .\cockroach.exe demo                                               
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 1 node.
#
# This demo session will attempt to enable enterprise features
# by acquiring a temporary license from Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
#
# Beginning initialization of the movr dataset, please wait...
#
# The cluster has been preloaded with the "movr" dataset
# (MovR is a fictional vehicle sharing company).
#
# Reminder: your changes to data stored in the demo session will not be saved!
#
# Connection parameters:
#   (console) http://127.0.0.1:50772
#   (sql/tcp) postgres://root@127.0.0.1:50774?sslmode=disable
#
#
# Cockroach demo is running in insecure mode.
# Run with --insecure=false to use security related features.
# Note: Starting in secure mode will become the default in v20.2.
#
# Server version: CockroachDB CCL v20.1.0 (x86_64-w64-mingw32, built 2020/05/05 00:17:05, go1.13.9) (same version as client)
# Cluster ID: 8df510ed-b2ae-46a0-b398-32c1deac6bc8
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:50774/movr>   
``` 
i think we just need add these prereqs to the docs and we will be ok for now

**Comment by knz** [comment]
Using just the zip is FAR MUCH SIMPLER.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by jseldess** [comment]
ok for the record it does seem like ZONEINFO alone works.  i removed GOROOT and GOPATH and only have ZONEINFO and demo starts properly.  unlike the GO variables, for this to work it needs to point to the exact file not just the directory C:\Go\lib\time\zoneinfo.zip.  so somewhat simpler but still either have to install go or have this file laying around.  Again go versions didn't seem to matter.

**Comment by knz** [comment]
That is why I suggested giving a link to download that one file

**Comment by knz** [comment]
(NB for correctness this file should be refreshed about every six months. That's how frequently the international TZ database is updated.)
