### ISSUE TITLE
Research docs impact of geo-spatial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6677]
AT: https://airtable.com/tblD3oZPLJgGhCmch/viwJAeQYJPyTNLctb/recMNcrvFLgiUiX62?blocks=hide

Initial GH issues:
- https://github.com/cockroachdb/cockroach/issues/19313
- https://github.com/cockroachdb/cockroach/issues/21286

Planning/research docs:
- https://docs.google.com/document/d/1s20-udCs4pftaAOiPXqHr3pao9U7M-Pr4coMk6Qddr0/edit?ts=5dcc4d1b#heading=h.km6dbq8se2y2
- https://docs.google.com/document/d/1CCb5jabCG2iFZELBSV56mNECKsKl2_aPX8zQ49Ume5c/edit?ts=5d8d03aa#heading=h.3s6s8g4cnifq

PostGIS docs: https://postgis.net/docs/

Questions:
- What reference docs do we need? (e.g., SQL statements, data types, new index type, etc.)
- What developer guidance do we need? (e.g., loading geo-spatial, querying geo-spatial , troubleshooting, etc.)
- What third-party tools do we want to call out or document?
- What end-to-end tutorials would be helpful?

**Comment by rmloveland** [comment]
Calling this one done now that we have a plan for spatial docs for 20.2 which is available to view as [a prioritized list of Spatial Docs issues](https://github.com/cockroachdb/docs/projects/50).
