### ISSUE TITLE
docs on migration tooling

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#6679]
Per @johnrk it may be useful to document external tools that can facilitate database migrations.

cc @jseldess in case this has previously been planned or discussed.

**Comment by taroface** [comment]
@johnrk Were there any example tools that came up in your discussions with Kai?

**Comment by awoods187** [comment]
We need to document [Flowable](https://github.com/cockroachdb/docs/issues/6865) and [Flyway](https://github.com/cockroachdb/docs/issues/5356).

**Comment by taroface** [comment]
Duplicates #6866.
