### ISSUE TITLE
Remove "beta" tag from production-ready ORMs and drivers

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#6689]
The following drivers/ORMs are production-ready and should *not* be marked as beta in our docs:

Python:
- psycopg
- SQLAlchemy
- Django
- PonyORM

Java:
- jdbc
- jOOQ
- Hibernate

**Comment by ericharmeling** [comment]
@awoods187 @rafiss 
Please edit/update this list as needed.

**Comment by awoods187** [comment]
This would help sales and better reflects our current state. Thanks for spearheading this work.
