### ISSUE TITLE
Update Dev Guide code samples to be more vertically compact

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6698]
Got some feedback that the code in Developer Guide pages like [Insert Data](http://cockroachlabs.com/docs/v20.1/insert-data.html) should be visible directly below the tabs.

In other words: put the code samples closer to the heading buckets so that developers can see the code on the same page.

**Comment by jseldess** [comment]
Related: https://github.com/cockroachdb/docs/issues/6711
