### ISSUE TITLE
Recommended Linux distros and kernel versions

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6702]
We need to provide a recommendation in our docs for which Linux distributions and kernel versions work well and are tested with CockroachDB.

This is necessary in case a given Linux kernel version has a bug in a system call we depend on (e.g., `fsync`).

This will make life easier for users (since they will have a vetted kernel version) and us (since we will be able to point to that recommendation if users are running on a kernel with a bug).

Regarding the current state: Just did a bunch of grepping in the docs repo, a web search, and read our [Recommended Production Settings][prod], [Operational FAQ][ops], and [Install CRDB on Linux][linux] pages.  Did not find anything about kernel versions.

The most specific we seem to get is mentioning specific C libraries etc. in the Ops FAQ here:

https://www.cockroachlabs.com/docs/v19.2/recommended-production-settings.html#dependencies

Estimated scope of work:

- Update [Recommended Production Settings][prod], [Operational FAQ][ops], and [Install CRDB on Linux][linux] with a recommended Linux kernel version
- (This can probably be an include for reusability)
- Investigate where else this information needs to be shared (Kubernetes pages?), and update as needed

See also:

- #4209
 - #2268

[prod]: https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html
[ops]: https://www.cockroachlabs.com/docs/stable/operational-faqs.html
[linux]: https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html

**Comment by jseldess** [comment]
cc @johnrk

**Comment by taroface** [comment]
Tested by @dbist:

- distribution: ubuntu 18.04 
- kernel: 4.15.0-109-generic

- distribution: centos 7.6
- kernel: 3.10.0-957.12.2.el7.x86_64
