### ISSUE TITLE
Add production guidance on connection pooling

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6706]
The CockroachCloud docs make recommendations around [connection pooling](https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-production-checklist.html#use-a-small-pool-of-persistent-connections). We should vet those recommendations, update and expand them if necessary, and expose them in the CockroachDB [Production Checklist](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html) as well, with adjustments as needed.

There's a general sense from SEs that it's more expensive to open connections than to maintain them and that a larger default pool (e.g., 50 or 100) per app instance may be best.

Once possible factor is password vs. cert-based auth. CC intentionally uses a cpu heavy hash algorithm (bcrypt) to make it difficult to brute force a password match.

**Comment by Amruta-Ranade** [comment]
Yep! @tim-o and Marc came up with the equation.

**Comment by jseldess** [comment]
Thanks, @Amruta-Ranade. @tim-o, do you remember anything about the process and rationale for that equation?

**Comment by jseldess** [comment]
@tim-o, ping.

**Comment by vy-ton** [comment]
@tim-o any background here would be helpful. The AppDev team is planning to design internal tests for max connection usage and connection pool recommendations.

**Comment by tim-o** [comment]
@vy-ton @jseldess we got it from https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing, Marc Berhault verified it at the time.

The optimal pool size is going to be workload and environment dependent, so we really should encourage people to use the formula as a starting point, and increase the pool size until they can identify the point of diminishing returns.

**Comment by jseldess** [comment]
@vy-ton, I remember seeing you link to a document by @a-entin with different guidance on connection pooling. Do you know what I mean and, if so, can you add that here?

**Comment by vy-ton** [comment]
![image](https://user-images.githubusercontent.com/13694532/91648970-497baa00-ea3c-11ea-8df8-b08f2ad25829.png)

**Comment by jseldess** [comment]
@vy-ton, can you provide a link to the source for more context?

In @a-entin's [vmware doc](https://docs.google.com/document/d/1Ub3sajyG5E4223KgVVX1x0nBrZSoJVkRajnupfaLLAQ/edit#), he also says:

> The True concurrency-to-vCPU ratio should not exceed 4. Users are encouraged to implement connection pooling or similar techniques to ensure the number of always-active connections per CockroachDB node does not exceed 4 times vCPU count.

**Comment by taroface** [comment]
Additional notes from @a-entin:

> - “True” Concurrency is a characteristic of a workload where database clients open connections and execute SQL statements back-to-back, as in a stress test
> 
> - As opposed to connections with a significant share of idle time, such as in interactive user connections, for example
> 
> - Alternatively, “true” concurrency may be referred to as the number of "always-active connections" or as the "number of actively executing statements".
> 
> - The True concurrency-to-vCPU ratio should not exceed 4. Users are encouraged to implement connection pooling or similar techniques to ensure the number of always-active connections per CockroachDB node does not exceed 4 times vCPU count.
> 
> - The ratios provided are recommendations, not hard requirements. Experienced users with insightful understanding of their real-world workload should take these recommendations as a starting point and adjust them to best fit their application’s specific workloads. Development environments, for example, may or may not be provisioned with the same ratios as a production environment.

**Comment by taroface** [comment]
The Sessions UI page being documented with #8218 is relevant here, as it displays active connections (sessions).

**Comment by jseldess** [comment]
@ianjevans, assigning this to you since you covered connection pooling in the new dev guide. Can you think about corresponding updates to the prod checklists?
