### ISSUE TITLE
Code blocks: Improve the UX of code toggles

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6711]
Our code toggles are very basic "buttons" of various sizes. We should look to emulate more efficient and intuitive toggles found in other docs.

**Examples**

[Stripe](https://stripe.com/docs/payments/accept-a-payment#web-setup):
<img width="799" alt="Screen Shot 2020-02-28 at 7 41 33 AM" src="https://user-images.githubusercontent.com/15893490/75549530-e3b35480-59fd-11ea-8e28-f37e6f13dc13.png">

[Google](https://developers.google.com/assistant/conversational/helpers#df_nodejs_permission_reason):
<img width="860" alt="Screen Shot 2020-02-28 at 7 46 49 AM" src="https://user-images.githubusercontent.com/15893490/75549798-8075f200-59fe-11ea-884b-ecd590546e22.png">

[Google](https://cloud.google.com/kubernetes-engine/docs/quickstart):
<img width="866" alt="Screen Shot 2020-02-28 at 7 48 39 AM" src="https://user-images.githubusercontent.com/15893490/75549914-c16e0680-59fe-11ea-8e77-73df626bb52c.png">

**Comment by luciaaaaaaa** [comment]
adding this issue as a discussion topic for next weeks Docs re-design checking @lnhsingh @jseldess

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A12437

**Comment by luciaaaaaaa** [comment]
Looking at this branch http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/3b815aac49aec9cf84a25609b6fc9a1fefa22fbd/stable/query-data.html#go 

We still need to update the 'Copy' button, (to just the icon). 
I also noticed that the tabs to toggle between different languages is very tall, 60px, can we make it 40px?

@jseldess you have a lot of historical insight into the updated for the code blocks, so a second pair of eyes on this one would be very helpful! 

Thank you

**Comment by jseldess** [comment]
The code toggles looks great overall! I agree with @luciaaaaaaa's two points:
- The high of the toggles could be less.
- We should remove "COPY" from the copy icon. That will also reduce the width of the area at the right border that code can't extend into.

**Comment by anagio** [comment]
@luciaaaaaaa updated tab heights is on the way to preview, the copy text is also removed
