### ISSUE TITLE
Improve the UX of page-level toggles

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6712]
As opposed to step-level or code-level toggles.

**Examples**

[Stripe](https://stripe.com/docs/payments/accept-a-payment#ios):
<img width="1018" alt="Screen Shot 2020-02-28 at 7 50 17 AM" src="https://user-images.githubusercontent.com/15893490/75550098-1d388f80-59ff-11ea-8816-a928b1c248e4.png">

**Comment by luciaaaaaaa** [comment]
@lnhsingh @jseldess is this issue around this component: 
![image](https://user-images.githubusercontent.com/48258790/82349433-14d16e80-99c8-11ea-83f1-f9d2ff73e09d.png)
if not, could you provide an example showing how we currently handle this?

**Comment by lnhsingh** [comment]
@luciaaaaaaa yep, it's that component

**Comment by jseldess** [comment]
I'd say also these:

<img width="1014" alt="Screen Shot 2020-05-20 at 11 27 09 AM" src="https://user-images.githubusercontent.com/15893490/82465103-e1a4e300-9a8c-11ea-96fe-51faf5d64575.png">

<img width="957" alt="Screen Shot 2020-05-20 at 11 26 59 AM" src="https://user-images.githubusercontent.com/15893490/82465114-e49fd380-9a8c-11ea-9c63-46ba088e3ed1.png">

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A12437
