### ISSUE TITLE
Export chunk rows

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/docs#6716]
We don't have any documentation on how to chunk rows in exports.  Right now it's a hidden feature.

https://github.com/cockroachdb/cockroach/blob/60666bdd7e3f7ed6ab6118c030c4a9973a5019ad/pkg/sql/export.go#L55

We probably should highlight it here in our docs.

https://www.cockroachlabs.com/docs/dev/export.html#parameters

**Comment by BramGruneir** [comment]
Assigning to @jseldess for triage

**Comment by jseldess** [comment]
Good catch, @chriscasano!

**Comment by jseldess** [comment]
@lnhsingh, @mwang1026 for prioritization.

**Comment by kathancox** [comment]
Closing this issue, as I think this was covered in a recent PR... here: #10615. Feel free to reopen is more detail is needed @chriscasano
