### ISSUE TITLE
Figure out how to generate `SELECT FOR UPDATE` diagram

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6720]
Subtask of #6000.

At the moment (2020-03-02) there does not seem to be an easily consumable/generatable diagram of `SELECT ... FOR UPDATE`.

(This may just be a matter of waiting for the `SELECT ... FOR UPDATE` work to merge, at which point we can generate the diagrams in the usual way.)

However, if it's not that easy, we will need to figure out what to do.

In the CockroachDB grammar this construct appear to be named `for_locking_strength` and refers to:

- `FOR UPDATE`
- `FOR NO KEY UPDATE`
- `FOR SHARE`
- `FOR KEY SHARE`

... of which `FOR UPDATE` is the one we want.

Unfortunately at the moment (AFAICT) that clause only lives in `stmt_block.bnf` and is not hooked into any of the BNF files that we use to generate diagrams for the various `SELECT` statements, namely:

- `select_clause.bnf`
- `select_stmt.bnf`
- `simple_select_clause.bnf`

Estimated scope of work:

- Figure out if / how to generate this particular diagram
- If you can't figure it out, ask for help from Engineering: perhaps file an issue against the `docgen` package of CRDB

**Comment by ericharmeling** [comment]
I think we should close this, since we are moving away from SQL diagrams.
