### ISSUE TITLE
Upate comparison matrix

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6721]
https://docs.google.com/spreadsheets/d/1oZO-2LfLOloPBP_TU_bgL4sLr7flDuxwonxcd-wTjVQ/edit#gid=0

**Comment by jseldess** [comment]
@anagio, can you help out with this? We need to update the last few versions of https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html based on @jaymce's new spreadsheet.

**Comment by anagio** [comment]
yes sure i'll take this
