### ISSUE TITLE
Add Slow Query Log

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6725]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw1DKmbKhg2MIECH/recWWKTPul8OhJXq0?blocks=hide

PM: @piyush-singh, @awoods187 
Dev: @jordanlewis

**Comment by jseldess** [comment]
From release notes:

> Added a slow query log facility to CockroachDB, configurable by setting the `sql.log.slow_query.latency_threshold` [cluster setting](../v20.1/cluster-settings.html). When used, each node of your cluster will record queries that exceed the specified service latency to a new file called `cockroach-sql-slow.log`. [#44816][#44816]

**Comment by taroface** [comment]
- Document use case and steps for activating & collecting slow query log
- Describe steps for viewing log via Admin UI
- Possibly link & update https://www.cockroachlabs.com/docs/stable/sql-audit-logging.html
- Update https://www.cockroachlabs.com/docs/stable/experimental-audit.html#audit-log-file-format for correctness
- Consider linking to:
  - https://www.cockroachlabs.com/docs/stable/make-queries-fast.html
  - https://www.cockroachlabs.com/docs/stable/query-behavior-troubleshooting.html#sql-logging
  - https://www.cockroachlabs.com/docs/stable/sql-tuning-with-explain.html
