### ISSUE TITLE
sql: native support for creating hash sharded indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6730]
PR: https://github.com/cockroachdb/cockroach/pull/42922

From release notes:
> Added native support of hash-sharded indexes with new `USING HASH WITH BUCKET_COUNT = <n>` syntax for indices (including the primary index of a table). This feature allows users to easily relieve write hot-spots caused by sequential insert patterns at the cost of scan time for queries over the hashed dimension. [#42922][#42922] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
hash sharded index https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recOb3JQTLxMJxnmH
