### ISSUE TITLE
sql: enable primary key change into a hash sharded primary key

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6731]
PR: https://github.com/cockroachdb/cockroach/pull/44993

From release notes:
> Added support for primary key changes into hash sharded indexes. [#44993][#44993] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
hash sharded index https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recOb3JQTLxMJxnmH
online primary key change https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckXe8OwbdVi8WzH
