### ISSUE TITLE
sql: disable interleaved hash sharded indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6732]
PR: https://github.com/cockroachdb/cockroach/pull/44996

From release notes:
> Disabled creating a hash sharded index that is also interleaved. [#44996][#44996] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Hash sharded index https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recOb3JQTLxMJxnmH
