### ISSUE TITLE
opt: use conflict column IDs rather than names

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6738]
PR: https://github.com/cockroachdb/cockroach/pull/45280

From release notes:
> `INSERT..ON CONFLICT` index column names can now be specified in any order, rather than only in the same order as the index. [#45280][#45280] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
The limitation lifted by https://github.com/cockroachdb/cockroach/pull/45280 was not previously documented, and it doesn't look like the PR otherwise changes any expected behavior or syntax of the `INSERT ... ON CONFLICT` statement.

Closing this issue. @andy-kimball please reopen if you disagree.

**Comment by andy-kimball** [comment]
It turns what was previously an error case into a working case. And fixes a compat issue with PG.
