### ISSUE TITLE
jobs,webui: define a new endpoint for registry status

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6743]
PR: https://github.com/cockroachdb/cockroach/pull/45030

From release notes:
> Endpoint `/_status/registry/{node_id}` will now display status info about the jobs running on this `node_id`. [#45030][#45030] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
This would be an endpoint for the Advanced Debug page, but I believe Jobs status is better accessed on the Jobs page. This is already covered in the UI documentation.
