### ISSUE TITLE
Incorrect link from CC connect modal

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6749]
<img width="590" alt="Screen Shot 2020-03-02 at 9 23 25 PM" src="https://user-images.githubusercontent.com/15893490/75736785-23af5b80-5ccc-11ea-8de5-8e22699c2f87.png">

Last "see our docs" doesn't point to an existing anchor.

**Comment by Amruta-Ranade** [comment]
cc @laurenbarker Feel free to reassign as you see fit.

**Comment by laurenbarker** [comment]
What should the "see docs" link be? Right now it's https://www.cockroachlabs.com/docs/managed/stable/managed-connect-to-your-cluster.html#generate-the-connection-string

It doesn't seem like our docs talk about `sslmode=require` except for https://www.cockroachlabs.com/docs/v19.2/connection-parameters.html#secure-connections-with-urls

There is a section that discusses connection methods though. Is that the link we want?
https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html#step-3-select-a-connection-method

**Comment by Amruta-Ranade** [comment]
TBH, I am not sure we need the docs link there. We already link to the connection method docs from the first "see our docs".

**Comment by laurenbarker** [comment]
Oh gotcha, so just remove the second docs link 👍

**Comment by Amruta-Ranade** [comment]
Yeah. I need to talk to Jeremy about reworking the text on that page anyways. We can take this up as part of the larger overhaul.

**Comment by jseldess** [comment]
@Amruta-Ranade, is this still an issue?

**Comment by Amruta-Ranade** [comment]
I don't think this has been fixed yet. Let me check with Lauren.

**Comment by lnhsingh** [comment]
Closing - the link now works / redirects to https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster.html
