### ISSUE TITLE
Search Project: Tracking Issue

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#6758]
Please report any bugs, index degradation, or other unexpected wonkiness here.

**Comment by jseldess** [comment]
- The old "training" pages are showing up in search results, both on the live site and test site. Can we exclude them for algolia results? That's anything in the `/training` subdirectory, e.g., https://www.cockroachlabs.com/docs/v19.2/training/orchestration-with-kubernetes.html. We could also stop building them to the site, but I think we want to leave those pages available for potential classroom trainings, @thatnerd?

**Comment by jseldess** [comment]
- `import` returns no results on the test site (http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ff93b38f97aeaf39d9bb9798fae68010eb4aa50c/search.html?query=import), whereas results are returned on the live site (https://www.cockroachlabs.com/docs/search.html?q=import).

**Comment by lnhsingh** [comment]
Searching`import` is fixed.

**Comment by lnhsingh** [comment]
Old training pages removed from search results.

**Comment by jseldess** [comment]
I think we can close this now, since no new issues have been reported. Please re-open if you disagree, @lnhsingh.
