### ISSUE TITLE
update Admin UI storage metrics

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#6777]
Relates to #1323 and #6227.

- Update Admin UI names & tooltips
- Update corresponding info in docs

The tables below collect metrics (via @dhartunian), current & suggested UI names, and suggested new tooltips for storage-related metrics in the Admin UI.

These are also on a Google doc: https://docs.google.com/document/d/1fn_MZH0YNhBY3Uirh-Icp5Psgkz_7uXwiStaDArMHaI

Note: all URLs should dynamically point to the correct docs version.

### Capacity Usage
|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Capacity Usage |Store Capacity |Usage of total store capacity.<br><br>Store capacity is disk space allocated to CockroachDB data. It is set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).
|`cr.store.capacity.used` / (`cr.store.capacity.used` + `cr.store.capacity.available`) |bar that displays `cr.store.capacity.used` (Used) and (`cr.store.capacity.used` + `cr.store.capacity.available`) (Usable) capacity |bar that displays `cr.store.capacity.used` (Used) with (`cr.store.capacity.used` + `cr.store.capacity.available`) (Usable) capacity *and* `cr.store.capacity` (Total disk capacity) (this would be more useful IMO, but would change the tooltip specified here and is probably out of scope) |Percentage of total store capacity in use by CockroachDB data.
|`cr.store.capacity.used` + `cr.store.capacity.available` |Usable Capacity |Allocated |Total disk space allocated to CockroachDB data across all nodes.<br><br>This is set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).
|`cr.store.capacity.used` |Used Capacity |Used |Total disk space in use by CockroachDB data across all nodes.<br><br>This excludes the Cockroach binary, operating system, and other system files.

### Node List

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
|`cr.store.capacity.used` / (`cr.store.capacity.used` + `cr.store.capacity.available`) |Capacity Use |Capacity Usage | Percentage of \<locality> / node \<node> store capacity in use by CockroachDB data.<br><br>Store capacity is disk space allocated to CockroachDB data. It is set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).

### Node detail

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Live Bytes |Live Bytes |Number of logical bytes stored in live [key-value pairs](https://www.cockroachlabs.com/docs/architecture/distribution-layer.html#table-data) on node \<node>.<br><br>Live data excludes historical and deleted data.
| |Key Bytes |Key Bytes |Number of bytes stored in keys on node \<node>.
| |Value Bytes |Value Bytes |Number of bytes stored in values on node \<node>.
| |Intent Bytes |Intent Bytes |Number of bytes stored in [write intents](https://www.cockroachlabs.com/docs/architecture/transaction-layer.html#write-intents) of uncommitted values.
| |Sys Bytes | | Number of physical bytes stored in [system key-value pairs](https://www.cockroachlabs.com/docs/architecture/distribution-layer.html#meta-ranges) on node \<node>.
|`cr.store.capacity.used` |Used Capacity |Used Capacity |Disk space in use by CockroachDB data on node \<node>.<br><br>This excludes the Cockroach binary, operating system, and other system files.
|`cr.store.capacity.available` |Available Capacity |Available Capacity |Free disk space allocated to CockroachDB data on node \<node>.
|`cr.store.capacity` |Total Capacity |Total Capacity |Total disk capacity on node \<node>.<br><br>This is distinct from store capacity, which is disk space allocated to CockroachDB data and set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).

### Node Map

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
|`cr.store.capacity.used` / (`cr.store.capacity.used` + `cr.store.capacity.available`) |Capacity |Store Capacity |Percentage of \<locality> / node \<node> store capacity in use by CockroachDB data.
|`cr.store.capacity.used` |`cr.store.capacity.used` |`cr.store.capacity.used` used |Disk space in use by CockroachDB data at \<locality> / on node \<node>.<br><br>This excludes the Cockroach binary, operating system, and other system files.
|(`cr.store.capacity.used` + `cr.store.capacity.available`) |(`cr.store.capacity.used` + `cr.store.capacity.available`) |(`cr.store.capacity.used` + `cr.store.capacity.available`) allocated |Total disk space allocated to CockroachDB data at \<locality> / on node \<node>.

### Sidebar

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
|`cr.store.capacity.used` / (`cr.store.capacity.used` + `cr.store.capacity.available`) |Capacity Used |Capacity usage |Percentage of total store capacity in use by CockroachDB data.<br><br>Store capacity is set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).
|`cr.store.capacity.used` and (`cr.store.capacity.used` + `cr.store.capacity.available`) |"You are using `cr.store.capacity.used` of (`cr.store.capacity.used` + `cr.store.capacity.available`) usable storage capacity across all nodes." |"You are using `cr.store.capacity.used` of your (`cr.store.capacity.used` + `cr.store.capacity.available`) store capacity across all nodes." |

#### Available Disk Capacity graph
|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Available Disk Capacity |Available Store Capacity |Free disk space allocated to CockroachDB data on each node.<br><br>Store capacity is not used by the Cockroach binary, operating system, and other system files. It is set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).
|`cr.store.capacity.available`  |\<node> |\<node> | |

#### Capacity graph

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Capacity |Disk Capacity |Usage of disk capacity across all nodes / on node \<node>.
|`cr.store.capacity` |Capacity |Total |Total disk capacity across all nodes / on node \<node>.<br><br>This is distinct from store capacity, which is disk space allocated to CockroachDB data and set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).
|`cr.store.capacity.available` |Available |Available |Free disk space allocated to CockroachDB data across all nodes / on node \<node>.
|`cr.store.capacity.used` |Used |Used |Disk space in use by CockroachDB data across all nodes / on node \<node>.<br><br>This excludes the Cockroach binary, operating system, and other system files.

#### Capacity graph

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Capacity |Disk Capacity |Usage of disk capacity across all nodes / on node \<node>.
|`cr.store.capacity` |Capacity |Total |Total disk capacity across all nodes / on node \<node>.<br><br>This is distinct from store capacity, which is disk space allocated to CockroachDB data and set per node using [`--store`](https://www.cockroachlabs.com/docs/cockroach-start.html#store).
|`cr.store.capacity.available` |Available |Available |Free disk space allocated to CockroachDB data across all nodes / on node \<node>.
|`cr.store.capacity.used` |Used |Used |Disk space in use by CockroachDB data across all nodes / on node \<node>.<br><br>This excludes the Cockroach binary, operating system, and other system files.

#### Live Bytes graph
|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Live Bytes |Live Bytes |Amount of data that can be read by applications and CockroachDB across all nodes / on node \<node>.
|`cr.store.livebytes` |Live |Live |Number of logical bytes stored in live [key-value pairs](https://www.cockroachlabs.com/docs/architecture/distribution-layer.html#table-data) across all nodes / on node \<node>.<br><br>Live data excludes historical and deleted data.
|`cr.store.sysbytes` |System |System |Number of physical bytes stored in [system key-value pairs](https://www.cockroachlabs.com/docs/architecture/distribution-layer.html#meta-ranges) across all nodes / on node \<node>.

#### Logical Bytes per Store graph
|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Logical Bytes per Store |Logical Bytes per Store |Number of logical bytes stored in [key-value pairs](https://www.cockroachlabs.com/docs/architecture/distribution-layer.html#table-data) on each node.<br><br>This includes historical and deleted data.
|`cr.store.totalbytes` | |\<node> | |

## Databases

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Database Size |Database Size |Total disk size of the CockroachDB cluster.

### Non-table Cluster Data Sizes

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
| |Time Series |Time Series |Total disk size of Admin UI metrics.
| |Internal Use |Internal Use |

### Tables & Table Details

|Metric |UI element (current) |UI element (suggested) |Tooltip
|----|----|----|----
|sum of `approximateDiskBytes` on each node |Size |Replicated Size |Approximate disk size of all replicas of table \<table> on the cluster.

**Comment by taroface** [comment]
Got sign-off on these from @itsbilal.

**Comment by taroface** [comment]
@rmloveland Can you give these new tooltips and UI names a review? It's not a PR, but I can share the Google Doc with you. Definitely welcome your suggestions on how to refine any/all wordings.

**Comment by taroface** [comment]
Also to update:

Corresponding definitions on 

- Cluster Overview page docs
- Storage page docs
- etc.

**Comment by rmloveland** [comment]
@taroface the doc looks good to me modulo my various comments about the `--store` flag.

**Comment by taroface** [comment]
Closing now that definitions have been approved and are being input (tracked in other issues).
