### ISSUE TITLE
coupon codes copy 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6786]
We need to finalize copy here, let's call it promotions instead of coupon codes. 

![image](https://user-images.githubusercontent.com/36172966/76242906-d2dcbd00-620d-11ea-9a23-58735b09ad3b.png)

**Comment by Amruta-Ranade** [comment]
As discussed on Slack, I need to review the copy holistically. Also need to come up with a better term for coupon code.

**Comment by Amruta-Ranade** [comment]
Term finalized: "Trial Code"

**Comment by Amruta-Ranade** [comment]
Copy suggestions: https://github.com/cockroachlabs/managed-service/issues/2269
