### ISSUE TITLE
No documentation/examples for cluster setting: "server.host_based_authentication.configuration"

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#6799]
This was fielded by https://github.com/cockroachdb/cockroach/issues/45961

We accept the strings listed in the pg config file, the format and parameters are documented [here](https://www.postgresql.org/docs/12/auth-pg-hba-conf.html).

for example: 

```
root@127.0.0.1:53096/test> set cluster setting server.host_based_authentication.configuration = 'host all all 172.20.143.89/32 cert';
SET CLUSTER SETTING

Time: 4.099ms
```

worth also documenting that we don't support hostname resolution and can't restrict database space as well. So cockroach has it's limitations but I think it's worth documenting the use of this cluster setting somewhere. The idea with this cluster setting is you can force cockroach to not accept password authentications and instead require client certs for your secure cluster auth.

cc @knz

**Comment by jseldess** [comment]
@mattcrdb, I think this belongs in this other roamdap issue? https://github.com/cockroachdb/docs/issues/5957 

If so, would you mind closing here and posting there?

**Comment by mattcrdb** [comment]
Yeah, looks like it!

I'll move it over.
