### ISSUE TITLE
sql: enhance dbeaver docs to show insecure connection

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#6816]
Our [current documentation](https://www.cockroachlabs.com/docs/stable/dbeaver.html) focuses only on secure mode using ssl. This is a blocker for people testing out the tool and cockroachdb. We should show how to connect not using secure mode.

Its as simple as removing ssl:
![image](https://user-images.githubusercontent.com/22278911/76477603-40d6df00-63dc-11ea-982d-58274d27f2a4.png)

Also, dbeaver has a different look with their update so we could update our images at the same time.

**Comment by awoods187** [comment]
Also, we should include a section on doing it with `cockroach demo`

This requires finding your host on demo:
root@127.0.0.1:63302/movr>
9:20
127.0.0.1:63302

Note, the host is random so we will have to clarify that

**Comment by awoods187** [comment]
this is a reminder to myself of what the setup looks like with demo:
![image](https://user-images.githubusercontent.com/22278911/81030854-530f4f80-8e58-11ea-90df-32fab286cccd.png)

**Comment by ericharmeling** [comment]
We are de-emphasizing/removing "insecure" mode from all Cockroach docs.

See #6574 and #7772.
