### ISSUE TITLE
Start a Local Cluster (Secure) Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6827]
Re: [Start a Local Cluster (Secure)](https://cockroachlabs.com/docs//v19.2/secure-a-cluster.html)

## Issue Description
example of creating a client certificate for max user and connection steps for user max would be welcome in this post.

## Suggested Resolution 
Add steps to create client certificate
Add steps to demo how a max user can access CLI.

**Comment by dbist** [comment]
# Create Client certificate
`cockroach cert create-client max --certs-dir=certs --ca-key=my-safe-directory/ca.key`

# Login to CLI using max user
`cockroach sql --url  'postgresql://max@localhost:26257?sslcert=certs%2Fclient.max.crt&sslkey=certs%2Fclient.max.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt'`

**Comment by jseldess** [comment]
@dbist, why is this necessary in the start a local cluster tutorial? Can you provide more background here? Did a customer run into a problem?

In our hello world tutorials, we do have a step on creating this user and a cert for the user. For example, see https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb.html#step-2-create-the-maxroach-user-and-bank-database.

**Comment by dbist** [comment]
yes that's correct, these steps are available in other tutorials but chance is start a secure cluster will be one of the first ones to try by a user. This will achieve the following:
1. encourage best practices by leveraging a non-root user to query a database.
2. demonstrate how to access CLI with non-root user, using `--user` flag, rather than relying on a root user.
3. close the loop on the entire create user scenario, this tutorial shows how to create user and access Admin UI but it runs the workload as root user, it'd be better if it was executed as max. 
4. shows how to pass `--url` with `postgres://` scheme to CLI, something I had challenge finding in our docs. 

If you do feel this is redundant and of small value, feel free to close, I scrambled to find this information.

**Comment by jseldess** [comment]
@mikeCRL, @taroface, I'm closing this for now, but as part of encouraging the user of non-root users, we need to also revisit the local cluster tutorial.
