### ISSUE TITLE
Document checkpoint file usage

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#6831]
## Title

document checkpoint file 

https://www.cockroachlabs.com/docs/stable/backup.html

## Description

checkpoint file was present because there was an interruption in the backup process.

## Outline

- Whenever a backup runs CockroachDB creates BACKUP-CHECKPOINTS while the backup is running. 
- Once the backup is complete CockroachDB writes a file called BACKUP and all BACKUP-CHECKPOINT files should be gone. 
- The presence of  BACKUP-CHECKPOINT files it either means that the backup isn't complete or failed backup jobs.

@roncrdb's explanation above

## Expected Audience

DBA

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4929](https://cockroachdb.zendesk.com/agent/tickets/4929) has been linked to this issue.

**Comment by jseldess** [comment]
Thanks for opening this, @robert-s-lee.

@lnhsingh, @mwang1026, is something on the 20.1 docs backlog, or something we just failed to document previously?

**Comment by lnhsingh** [comment]
@jseldess I think this is something that I never documented. Thanks, @robert-s-lee!
