### ISSUE TITLE
Identify known limitations that have been resolved

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6837]
In addition to documenting new 20.1 known limitations, we need to review the "unresolved" limitations, figure out if any have been resolved in the meantime, and update our [20.1 doc](https://www.cockroachlabs.com/docs/dev/known-limitations.html) as appropriate.

**Comment by piyush-singh** [comment]
All limitations mentioned for the Admin UI are still valid. Did a full run through and to the best of my knowledge the limitations for Observability and Security in general are still valid.

**Comment by jseldess** [comment]
Thanks, @piyush-singh!

**Comment by johnrk** [comment]
From @andreimatei :
"_**Write and update limits for a single statement**_ - I’d probably get rid of this one. There hasn’t been a limit per statement for a long time. The limit is now per… I think groups of 10k rows being written by the statement.
_**Cold starts of large clusters may require manual intervention**_ - This one probably needs to be adjusted based on the new default range size. Also I think we should probably nudge people with existing clusters to up their range size limits to match the defaults."

**Comment by jseldess** [comment]
Thanks, @johnrk. I'll hand the former. @rmloveland, can you handle the latter update related to range size? I think you have a PR open on the topic.

**Comment by rmloveland** [comment]
>  @rmloveland, can you handle the latter update related to range size? I think you have a PR open on the topic.

Sure, filed #7188 to work on this.
