### ISSUE TITLE
sql: TIMESTAMPTZ is incorrect

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#685]
The docs for TIMESTAMPTZ say: "TIMESTAMPTZ stores a date and time pair with a time zone offset from UTC" however this isn't correct as both TIMESTAMP and TIMESTAMPTZ are stored in the same way: number of seconds and nanoseconds since the epoch. No timezone information is stored at all in either case.

In general the TZ type cares about the session offset and normal TIMESTAMP doesn't, but that's not always true. Ping me when you'd like to go over specifics of how these two types differ, as there are many edge cases here and pretty much only David knows how it all works.

**Comment by jseldess** [comment]
@mjibson, here's the related issue I mentione: https://github.com/cockroachdb/cockroach/issues/9266

**Comment by mjibson** [comment]
A user just hit this issue. We need to correct the docs, because they are incorrect and misleading.

**Comment by jseldess** [comment]
@mjibson's response in forum:

> Our docs for the WITH TIME ZONE type are incorrect (see https://github.com/cockroachdb/docs/issues/685). Both the WITH and WITHOUT types of TIMESTAMP are stored as UTC without any timezone info. The only difference is that the WITH TIME ZONE variety will send back data in whatever time zone your SQL session is using. (And I'm not sure if it defaults to UTC or the system's time zone.)
>
> Our recommendation is to never ever use the WITH TIME ZONE type, but always use just TIMESTAMP, which does everything in UTC.

**Comment by dt** [comment]
I'd change the first sentence from `The TIMESTAMP data type stores a date and time pair in UTC, whereas TIMESTAMPTZ stores a date and time pair with a time zone offset from UTC.` something like:

> 
> The TIMESTAMP data type stores a date and time in UTC.
> 
> The TIMESTAMP type has two variants: `TIMESTAMP WITH TIME ZONE` and `TIMESTAMP WITHOUT TIME ZONE`. Both are always stored in UTC -- the difference between them is that `WITH TIME ZONE` uses the session offset, if set, when sending timestamps to clients, and when parsing received timestamps if they do not contain an explicit offset, while the `WITHOUT TIME ZONE` version ignores the session offset.
>
> The `WITHOUT TIME ZONE` variant can sometimes lead to unexpected behaviors when it ignores a session offset, so it is generally recommended to use the `WITH TIME ZONE` variant.
>
>`TIMESTAMP` with no specifier is a shorthand for the `WITHOUT TIME ZONE` variant for legacy compatibility reasons, `TIMESTAMPTZ` is a shorthand for `TIMESTAMP WITH TIME ZONE`.

**Comment by mjibson** [comment]
I like the suggestion above, but I think it should also note as Ben brought up that some functions like `extract` will extract the day or whatever the parameter is in the time-zone converted timestamp, which happens before data is sent to the client.

**Comment by sploiselle** [comment]
@mjibson Does that David's suggestion work for you?

**Comment by mjibson** [comment]
Yes.
