### ISSUE TITLE
Make a full Hello World app and tutorial for peewee

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#6850]
peewee supports CockroachDB. We have announced peewee support in a [blog post](https://www.cockroachlabs.com/blog/peewee-orm-cockroachdb/).
peewee documents their [`CockroachDatabase` extension on their docs site](http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#cockroach-database).

We should make a Hello World app and an accompanying tutorial, as has been done for all other supported Python ORMs.

**Comment by vy-ton** [comment]
@ericharmeling What are your thoughts on closing issues in the deep backlog that are unlikely to rise in priority?

**Comment by ericharmeling** [comment]
> What are your thoughts on closing issues in the deep backlog that are unlikely to rise in priority?

Some of the deep backlog issues turn into good issues for community contributors (especially during hackathons), for docs fixit days, or for new writers. So, I don't think we should close all deep backlog issues across the board. 

I do think we should close this issue, as this doc would be particularly susceptible to decay. But for other deep backlog issues, I think we should close things on a case-by-case basis.
