### ISSUE TITLE
Include VPC peering availability in CC release notes for april '20

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6854]
Let's make sure April release notes have a line that says "VPC peering is now available for all new clusters created in GCP. If you want to enable VPC peering for your cluster in GCP, please open a support ticket at support.cockroachlabs.com."

CC @DuskEagle

**Comment by Amruta-Ranade** [comment]
Done: https://www.cockroachlabs.com/docs/cockroachcloud/releases/cockroachcloud-04062020.html
