### ISSUE TITLE
Technical Advisory 43870 Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6856]
Re: [Technical Advisory 43870](https://cockroachlabs.com/docs//advisories/a43870.html)

## Issue Description
The mitigation steps should include example to generate session cookie

## Suggested Resolution 

```bash
cockroach auth-session login maxroach --certs-dir=certs
```

```bash
  username |     session ID     |                           authentication cookie
+----------+--------------------+----------------------------------------------------------------------------+
  maxroach | 538994200482643969 | session=CIGAjv7pi7m9BxIQIpYyFNH5pRcqf2Y6kEgv6A==; Path=/; HttpOnly; Secure
(1 row)
#
# Example uses:
#
#     curl [-k] --cookie 'session=CIGAjv7pi7m9BxIQIpYyFNH5pRcqf2Y6kEgv6A==; Path=/; HttpOnly; Secure' https://...
#
#     wget [--no-check-certificate] --header='Cookie: session=CIGAjv7pi7m9BxIQIpYyFNH5pRcqf2Y6kEgv6A==; Path=/; HttpOnly; Secure' https://...
#
```

**Comment by knz** [comment]
The explanation for `cockroach auth-session` should be in the reference docs for the CLI, and linked in the advisory. The advisory itself is not the right place to provide reference documentation.

I don't recall who's responsible to document the new command, or if there's a doc issue already. @Amruta-Ranade do you recall?

**Comment by Amruta-Ranade** [comment]
This one?
https://github.com/cockroachdb/docs/issues/6631

**Comment by dbist** [comment]
there's already [effort](https://github.com/cockroachdb/docs/issues/6631) to do that and will close this issue.
