### ISSUE TITLE
Wrong port on encryption page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6869]
https://www.cockroachlabs.com/docs/stable/encryption.html#checking-encryption-status

<img width="781" alt="Screen Shot 2020-03-19 at 10 38 40 AM" src="https://user-images.githubusercontent.com/15893490/77079083-d91d2700-69cd-11ea-9b54-0439bb00d93e.png">

Should be `8080`, not `8888`. 

Reported by a customer:

<img width="504" alt="Screen Shot 2020-03-19 at 10 39 54 AM" src="https://user-images.githubusercontent.com/15893490/77079181-fd790380-69cd-11ea-816f-77f133fdd51e.png">

**Comment by Amruta-Ranade** [comment]
Versions to be updated: 19.2, 20.1, 20.2

**Comment by dgabriel123** [comment]
Hello @Amruta-Ranade, would it be alright to work on this issue?

Also, is it just 19.2, 20.1, and 20.2 that need the fix? 2.1 and 19.1 also appear to have the same issue. Thanks!

**Comment by Amruta-Ranade** [comment]
Sure! Assigning the issue to you. 2.1 and 19.1 docs aren't actively maintained now, so don't worry about updating them.

**Comment by dgabriel123** [comment]
@Amruta-Ranade created a PR with the changes.

**Comment by Amruta-Ranade** [comment]
Thank you, @dgabriel123 !
