### ISSUE TITLE
sql: release note for ZONECONFIG

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6876]
PR: https://github.com/cockroachdb/cockroach/pull/45201

From release notes:
> Admin users can now [grant](../v20.1/grant.html) `ZONECONFIG` to non-admin users on specific SQL objects (databases/tables). When set, the user is authorized to modify that object's [zone configuration](../v20.1/configure-replication-zones.html) and decide data placement on specific nodes or groups thereof. [#45201][#45201] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
