### ISSUE TITLE
cli: validation rule for principal names was extended to support periods

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6878]
PR: https://github.com/cockroachdb/cockroach/pull/45575

From release notes:
> The validation rule for principal names was extended to support periods and thus allow domain name-like principals. For reference, the validation rule is currently the regular expression `^[\p{Ll}0-9_][---\p{Ll}0-9_.]+$`, and limited to a size of 63 UTF-8 bytes (larger usernames are rejected with an error); for comparison, PostgreSQL allows many more characters and truncates at 63 characters silently. [#45575][#45575] {% comment %}doc{% endcomment %}
>
> [Usernames](../v20.1/create-user.html) can now contain periods, for compatibility with certificate managers that require domain names to be used as usernames. [#45575][#45575] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
