### ISSUE TITLE
sql: prevent arbitrary writes to system.comments

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6879]
PR: https://github.com/cockroachdb/cockroach/pull/45712

From release notes:
>  All users can now *view* any comments on any object (bypassing other privileges), but modifying comments require write privilege on the target object. Previously, any user could modify any database/table/view/index comment via direct SQL updates to `system.comments`. This was unintended and a form of privilege escalation, and is now prevented. The privileges required for the [`COMMENT`](../v20.1/comment-on.html) statement, `pg_description`, `col_description()`, `obj_description()`, and `shobj_description()` are operating as in PostgreSQL and are unaffected by this change.[#45712][#45712] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We currently don't document `system.comments`, or really any `system` tables. We actually don't document privileges on any internal tables. I think we can close this issue, in favor of #6272. 

Also related: #1291 and #2957
