### ISSUE TITLE
sql: ensure that GRANT/REVOKE can only propagate allowed privs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6880]
PR: https://github.com/cockroachdb/cockroach/pull/45697

From release notes:
> The [`GRANT`](../v20.1/grant.html) statement has been changed to be more like a capability-based system: it can only propagate privileges that the requesting user already has. Previously, it could be used to grant any other bit to any user, even to the requesting user. Note that the pseudo-privilege `ALL` includes `GRANT`, so `GRANT ALL`, in effect, preserves the previous behavior: it grants `GRANT` and every over privileges, so all privileges can be re-granted transitively. [#45697][#45697] {% comment %}doc{% endcomment %}
> The [`GRANT`](../v20.1/grant.html) and [`REVOKE`](../v20.1/revoke.html) statements now require that the requesting user already have the target privileges themselves. For example, `GRANT SELECT ON t TO foo` requires that the requesting user already have the `SELECT` privilege on `t`. [#45697][#45697] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7003
