### ISSUE TITLE
blobs: enforce disabled external-io-dir

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6885]
PR: https://github.com/cockroachdb/cockroach/pull/45858

From release notes:
> The `--external-io-dir=disabled` now applies to `nodelocal upload` requests. [#45858][#45858] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Need to update https://www.cockroachlabs.com/docs/dev/cockroach-start.html#general and add reference to `cockroach nodelocal upload`
