### ISSUE TITLE
sql: Role management, CREATEROLE privilege

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6890]
PR: https://github.com/cockroachdb/cockroach/pull/44232

From release notes:
> Modified the [`CREATE ROLE`](../v20.1/create-role.html) statement to add the `CREATEROLE` option. Also added the `ALTER ROLE` statement and the `CREATEROLE` privilege. It is managed by choosing options when creating and altering a role. Example: `CREATE ROLE role WITH CREATEROLE;` [#44232][#44232] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7061
