### ISSUE TITLE
cloud: require nodeID in nodelocal URIs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6893]
PR: https://github.com/cockroachdb/cockroach/pull/45764

From release notes:
> `nodelocal://` URIs now require a node ID be specified in the hostname field. The special node ID of `'self'` is equivalent to the old behavior of when the node ID was unspecified. [#45764][#45764] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - already documented.
