### ISSUE TITLE
sql, jobs: add schema change job resumer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6894]
PR: https://github.com/cockroachdb/cockroach/pull/45870

From release notes:
> Non-running [`jobs`](../v20.1/show-jobs.html) are now considered for adoption in randomized order instead of in a determistic order by creation time, to avoid potential deadlocks when schema change jobs need to execute in a specific order. This is a preemptive change, not a bug fix, but it affects all jobs. [#45870][#45870] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
> Release note (general change): Schema changes are now scheduled and run
fully like other jobs and can take advantage of recent improvements in
stability in the job framework, so they now can be canceled, paused,
resumed after a crash or after being paused, and so on. Some other UI
differences come with this implementation change; notably, all schema
changes now have an associated job, failed schema changes are now rolled
back within the Reverting phase of the same job, and GC for dropped
indexes and tables is deferred to a later job.

**Comment by lnhsingh** [comment]
Docs changes:
- pause-job.html
- resume-job.html
- cancel-job.html
