### ISSUE TITLE
backupccl: allow appending incremental layers to backups

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6896]
PR: https://github.com/cockroachdb/cockroach/pull/45255

From release notes:
> [`BACKUP`](../v20.1/backup.html) can be re-run with the same destination path to automatically append an incremental backup to that path. [#45255][#45255] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - dupe of #6532
