### ISSUE TITLE
Mobile topnav menu flashes when scrolling on safari

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#69]
When you scroll down a large page in Safari, the mobile topnav menu flashes along the right margin of the page. @dt mentioned that Safari, unlike Chrome, loads the content as you scroll. We could solve this by limiting that version of the topnav to mobile devices, not just by screen width. 

Sample page: https://www.cockroachlabs.com/docs/sql-grammar.html

**Comment by jseldess** [comment]
@dt, I'm not seeing this anymore. Are you?

**Comment by dt** [comment]
Yeah, still happening for me on https://www.cockroachlabs.com/docs/sql-grammar.html

**Comment by jseldess** [comment]
OK, I see that, too.

**Comment by sploiselle** [comment]
@dt Still happening? There's been some redesign of the header and I'm not seeing anything funny in Safari.

**Comment by dt** [comment]
yes, still happening.

**Comment by sploiselle** [comment]
Saw this demoed and it's a flickering that's only visible when you're scrolling _really_ fast down a _long_ page. Fixing this is just a vanity issue. However, determined the culprit of this is `js/customscripts.js`’s line:

`$mobile_menu.css('visibility', 'visible’);` 

This leaves the expanded mobile menu visible at all times and toggles the menu’s visibility when you click `.hamburger`.

It’s possible to just change this JavaScript behavior to not have that menu loaded on the page at all times, so there’s nothing to flicker behind the redrawing of the page.

**Comment by sploiselle** [comment]
@jseldess Thanks for closing this! Thought it would happen automagically when #910 merged? I'll look into why that failed.

**Comment by jseldess** [comment]
Np!
