### ISSUE TITLE
backupccl: adopt protected timestamps for BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6900]
PR: https://github.com/cockroachdb/cockroach/pull/45859

From release notes:
> [`BACKUP`](../v20.1/backup.html) will no longer fail if the GC window for a table is exceeded while backing the table up. [#45859][#45859] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - No docs changes needed
