### ISSUE TITLE
server: separate SQL statistics from being refreshed with telemetry

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6902]
PR: https://github.com/cockroachdb/cockroach/pull/45082

From release notes:
> The new `diagnostics.sql_stat_reset.interval` [cluster setting](../v20.1/cluster-settings.html) controls the rate at which SQL statement statistics are refreshed. Additionally, the setting `diagnostics.forced_stat_reset.interval` was renamed to `diagnostics.forced_sql_stat_reset_interval`. [#45082][#45082] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Not sure if this warrants callout. Possibly on the diagnostics reporting page, if anywhere.

**Comment by awoods187** [comment]
There isn't a roadmap item for this--its more like tech debt that will enable roadmap work in 20.2. I don't think this needs to be documented.

**Comment by jseldess** [comment]
This type of issue just lets us know that we need to refresh our auto-generated cluster settings docs.

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/6802.
