### ISSUE TITLE
sql/opt/exec: add implicit SELECT FOR UPDATE support for UPDATE statements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6903]
PR: https://github.com/cockroachdb/cockroach/pull/45159

From release notes:
> [`UPDATE`](../v20.1/update.html) statements now acquire locks using the `FOR UPDATE` locking mode during their initial row scan, which improves performance for contended workloads. This behavior is configurable using the `enable_implicit_select_for_update` [session variable](../v20.1/set-vars.html) and the `sql.defaults.implicit_select_for_update.enabled` [cluster setting](../v20.1/cluster-settings.html). [#45159][#45159] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed by #7176
