### ISSUE TITLE
sql: allow adding a primary key when table has default rowid primary key

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6904]
PR: https://github.com/cockroachdb/cockroach/pull/45514

From release notes:
> The [`ALTER TABLE .. ADD PRIMARY KEY ...`](../v20.1/alter-table.html) command can now be used when the target table has the default rowid [primary key](../v20.1/primary-key.html). [#45514][#45514] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
online primary key change https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckXe8OwbdVi8WzH
