### ISSUE TITLE
colexec: plan disk-spilling enabled operators when vectorize=auto

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6905]
PR: https://github.com/cockroachdb/cockroach/pull/45582

From release notes:
> Hash joins and sorts are now run using the vectorized engine when `vectorize=auto` (default configuration). [#45582][#45582] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recagjuRqKN5Jxh1n
