### ISSUE TITLE
sql: make cleanup jobs spawned by alter primary key not cancelable

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6907]
PR: https://github.com/cockroachdb/cockroach/pull/45595

From release notes:
> The cleanup job spawned by [`ALTER .. PRIMARY KEY`](../v20.1/alter-primary-key.html) in some cases cannot be cancelled. [#45595][#45595] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs to be documented.
