### ISSUE TITLE
sql: disallow other schema changes during an in progress primary key change

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6911]
PR: https://github.com/cockroachdb/cockroach/pull/45397

From release notes:
> The use of schema changes when a [primary key](../v20.1/primary-key.html) change is in progress is now disabled. This includes the following: (1) running a primary key change in a transaction and then starting another schema change in the same transaction, and (2) starting a primary key change on one connection and then starting a schema change on the same table on another connection while the initial primary key change is currently executing. [#45397][#45397] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
alter pk https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckXe8OwbdVi8WzH
