### ISSUE TITLE
sql: disable primary key changes when a schema change is in progress

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6912]
PR: https://github.com/cockroachdb/cockroach/pull/45513

From release notes:
> CockroachDB has now disabled [primary key](../v20.1/primary-key.html) changes when a concurrent schema change is executing on the same table, or if a schema change has been started on the same table in the current transaction. [#45513][#45513] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
alter pk https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckXe8OwbdVi8WzH
