### ISSUE TITLE
sql: allow for primary key dropping if alter primary key is present

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6914]
PR: https://github.com/cockroachdb/cockroach/pull/44511

From release notes:
> You can now drop a [primary key](../v20.1/primary-key.html) as long as you add another primary key within the same [transaction](../v20.1/transactions.html). This feature is intended to be used when you do not want the existing primary key to be rewritten as a secondary index by [`ALTER PRIMARY KEY`](../v20.1/alter-primary-key.html). [#44511][#44511] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
alter primary key https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckXe8OwbdVi8WzH
