### ISSUE TITLE
opt: remove conflicting input rows in ON CONFLICT DO NOTHING case

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6917]
PR: https://github.com/cockroachdb/cockroach/pull/45443

From release notes:
> Duplicate rows in the input to an [`INSERT..ON CONFLICT DO NOTHING`](../v20.1/insert.html) statement will now be ignored rather than triggering an error. [#45443][#45443] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Don't think this requires a doc update, but we should check.

**Comment by ericharmeling** [comment]
Just looked over https://www.cockroachlabs.com/docs/stable/insert.html#on-conflict-clause. I think you are right, no docs needed.
