### ISSUE TITLE
sql: user/role refactor to match postgres

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6918]
PR: https://github.com/cockroachdb/cockroach/pull/44968

From release notes:
> [`USER`s](../v20.1/create-user.html) and [`ROLE`s](../v20.1/create-role.html) are now the same (which is PostgreSQL behavior). This means `CREATE`/`ALTER`/`DROP` `ROLE`/`USER` can be used interchangeably. [#44968][#44968] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7003
