### ISSUE TITLE
kv: support unreplicated locks, hook up SELECT FOR UPDATE end-to-end

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6920]
PR: https://github.com/cockroachdb/cockroach/pull/45701

From release notes:
> [`SELECT FOR UPDATE`](../v20.1/select-for-update.html) now hooks into a new leaseholder-only locking mechanism. This allows the feature to be used to improve performance of [transactions](../v20.1/transactions.html) that read, modify, and write contended to rows. Similarly, [`UPDATE`](../v20.1/update.html) statements now use this new mechanism by default, meaning that their performance under contention is improved. This is only enabled for `UPDATE` statements that can push their filter all the way into their key-value scan. To determine whether an `UPDATE` statement is implicitly using `SELECT FOR UPDATE` locking, look for a `locking strength` field in the `EXPLAIN` output for the statement. [#45701][#45701] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #7176
