### ISSUE TITLE
colserde: add Interval serialization

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6921]
PR: https://github.com/cockroachdb/cockroach/pull/45776

From release notes:
> Vectorized distributed flows and disk spilling now support the [`INTERVAL`](../v20.1/interval.html) type. [#45776][#45776] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reciDxEVXj4Y68MCz
