### ISSUE TITLE
colexec: add disk spilling to merge joiner

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6922]
PR: https://github.com/cockroachdb/cockroach/pull/45784

From release notes:
> Queries with [`MERGE` join](../v20.1/joins.html) can now run via the vectorized engine when `vectorize` is set to `auto`. [#45784][#45784] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recagjuRqKN5Jxh1n
