### ISSUE TITLE
sql: introduce EXPLAIN BUNDLE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6923]
PR: https://github.com/cockroachdb/cockroach/pull/45735

From release notes:
> [`EXPLAIN BUNDLE`](../v20.1/explain.html) can now be used to run a query and collect execution information in a support bundle, which can be downloaded via the Admin UI. [#45735][#45735] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
explain https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/rec4nN8PXF6Tkge92
