### ISSUE TITLE
Document inconsistent time zone environment variable for testing

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6928]
PR: https://github.com/cockroachdb/cockroach/pull/45640

From release notes:
> CockroachDB now refuses to start if named time zones are not properly configured. It is possible to override this behavior for testing purposes, with the understanding that doing so will cause incorrect SQL results and other inconsistencies, using the environment variable `COCKROACH_INCONSISTENT_TIME_ZONES`. [#45640][#45640] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This will be documented as part of #5111 - I had made a PR to add this to `cockroach start`, but after discussion in the PR (#7177 ) we decided to punt on this for now, as it's sufficiently esoteric.
