### ISSUE TITLE
sql: introduce sending NOTICE commands through pgwire

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6929]
PR: https://github.com/cockroachdb/cockroach/pull/45679

From release notes:
> `NOTICE` commands can now be sent by CockroachDB servers using the Postgres client/server protocol. We add notices for two basic cases: (1) [Creating a view](../v20.1/create-view.html) on a temporary table without using `TEMP VIEW` implicitly makes the view temporary. This now sets a notice, as per Postgres. (2) [`DROP INDEX`](../v20.1/drop-index.html) now prints information that indexes are not dropped immediately and instead dropped after GC TTL. These notices will print when using the CockroachDB CLI.  These notices can be disabled using the [cluster setting](../v20.1/cluster-settings.html) `sql.notices.enabled = false`. [#45679][#45679] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
The `sql.notices.enabled` cluster setting is documented with https://github.com/cockroachdb/docs/pull/6802.

I'm of the opinion that we not explicitly document these notices in our docs.

@otan @awoods187 

Let me know if you disagree.

**Comment by otan** [comment]
i agree we should not be documenting when notices are printed (unless it's part of the functionality of a builtin)

but the cluster setting should probably be.

**Comment by awoods187** [comment]
that's fine with me.
