### ISSUE TITLE
cli/start: make SIGQUIT dump the stacks

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6934]
PR: https://github.com/cockroachdb/cockroach/pull/36378

From release notes:
> CockroachDB will now dump the stacks of all goroutines upon receiving `SIGQUIT` prior to terminating. This feature is intended for use while troubleshooting misbehaving nodes. [#36378][#36378] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@jseldess Also not sure docs are needed here. This seems like more of a backend change. But I can dig for details if you think it merits inclusion somewhere in Troubleshooting.

**Comment by taroface** [comment]
Closing as this seems like more of a low-level change than we usually document.
