### ISSUE TITLE
cli: deprecated `quit --decommission`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6935]
PR: https://github.com/cockroachdb/cockroach/pull/45903

From release notes:
> The `--decommission` flag for [`cockroach quit`](../v20.1/cockroach-quit.html) is now deprecated. It will be removed altogether in a next stable release. Deployments should use [`cockroach node decommission`](../v20.1/cockroach-node.html) followed by either `cockroach quit` or an equivalent form of server shut down. [#45903][#45903] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
- Update decommissioning guidance to use `cockroach node decommission` followed by `cockroach quit` (or equivalent server shutdown) and never `cockroach quit --decommission`
- Clarify distinction between decommissioning and stopping a node
- Update `cockroach quit` documentation to match changes in https://github.com/cockroachdb/docs/pull/6825/files

**Comment by taroface** [comment]
@jseldess Working through terminology here. I understand when a node is decommissioning, but when it is officially “decommissioned” seems unclear to me.

Do we consider a node decommissioned when `replicas=0` independently of the `is_draining` value, or do we consider a node decommissioned (like the UI) once it is stopped?

It is also possible the way node status is interpreted in the UI is open to change, but I'm not sure yet.

**Comment by jseldess** [comment]
These are excellent questions, @taroface, that I don't think we have consistent answers to. I think the technical answer is that we consider a node decommissioned when `replicas=0`, regardless of whether it has been stopped or not. The node could still be live and able to serve as a gateway, though without any of its own data. That said, I don't know if that's the way we should frame it externally. Let me ask around.

**Comment by taroface** [comment]
Hi @knz, do I have the following correct?

Regarding #7422
- `cockroach quit` has a new flag in 19.1-20.1, and the command is being deprecated in v20.2.
  - we nonetheless aren't recommending use of `cockroach quit` in v20.1.
- when decommissioning a node, `cockroach node drain` should be run after `cockroach node decommission` successfully completes. (or can it be run simultaneously?)
- the combination of `cockroach node drain` + node shutdown via process manager supplants `cockroach quit` for the purposes of shutting down a node.
- the "drain" in `cockroach node drain` refers to SQL connections and not range removal.

Regarding #7384 and [this thread](https://cockroachlabs.slack.com/archives/CA8H95NUU/p1590087247056500)
- `cockroach node recommission` is used while `cockroach node decommission` is running/hanging and effectively cancels the latter process
  - (is there a way to cancel `cockroach node drain` in a similar way, or would you have to wait for it to finish and then manually restart the node?)

**Comment by knz** [comment]
>    cockroach quit has a new flag in 19.1-20.1, and the command is being deprecated in v20.2.

correct

>        we nonetheless aren't recommending use of cockroach quit in v20.1.

correct

>    when decommissioning a node, cockroach node drain should be run after cockroach node decommission successfully completes. (or can it be run simultaneously?)

after, yes (not simultaneously)

>    the combination of cockroach node drain + node shutdown via process manager supplants cockroach quit for the purposes of shutting down a node.

correct

>    the "drain" in cockroach node drain refers to SQL connections and not range removal.

SQL connections + rebalancing of ranges + execution of distributed SQL queries on behalf of other nodes


>   cockroach node recommission is used while cockroach node decommission is running/hanging and effectively cancels the latter process

yes

>       (is there a way to cancel cockroach node drain in a similar way, or would you have to wait for it to finish and then manually restart the node?)

no `node drain` cannot be cancelled. You have to wait and restart.

**Comment by irfansharif** [comment]
As of https://github.com/cockroachdb/cockroach/pull/49668, we'll have marked the entirety of `cockroach quit` as deprecated. We're now advising users to instead use `cockroach node drain` and send out termination signals to the crdb process, in order to replicate what was previously done via `cockroach quit`.

**Comment by irfansharif** [comment]
To that end I think what we want to happen here, in this issue, is to start scrubbing our docs of any mention of `cockroach quit`.

**Comment by irfansharif** [comment]
I see we already have https://github.com/cockroachdb/docs/pull/7304 inflight to change our 20.1 and earlier docs. Should I file separately to track this scrubbing of `cockroach quit` from our v20.2 docs?

**Comment by jseldess** [comment]
I don't think so, @irfansharif. We have https://github.com/cockroachdb/docs/issues/6951, and with the first 20.2 alpha, I'm sure we'll generate other related issues.
