### ISSUE TITLE
jobs,webui: define a new endpoint for job statusJobs endpoint

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6937]
PR: https://github.com/cockroachdb/cockroach/pull/45094

From release notes:
> The end point `/&#95;status/job/{job_id}` will now display status info about a job. [#45094][#45094] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@piyush-singh Wondering for your opinion:

- I feel that job status is already best handled by the Jobs UI, and that we can settle for documentation of the latter (already done)
- Should this endpoint be added to the Advanced Debug page?

**Comment by piyush-singh** [comment]
- SGTM!
- Yes we probably should. Filed #48228. Added to the backlog, we'll pick this up at some point during 20.2.

**Comment by taroface** [comment]
Closing this issue per above.
