### ISSUE TITLE
server: make UI customizations work for non-admin users

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6938]
PR: https://github.com/cockroachdb/cockroach/pull/45127

From release notes:
> The display options are now saved separately for each authenticated user. **Note:** When upgrading to a version with this change, all current display customizations for admin users are lost. [#45127][#45127] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
As discussed with @knz , this is a backend bug fix that doesn't require docs update.
