### ISSUE TITLE
pprofui: allow downloading via ?download=true

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6939]
PR: https://github.com/cockroachdb/cockroach/pull/45790

From release notes:
> The pprof endpoints now allow downloading the binary profiles. To do so, attach `?download=true` to the URL. [#45790][#45790] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@jseldess I don't think we document these debug endpoints. Unless you think that we should, maybe no action is needed here? Let me know what you think.
