### ISSUE TITLE
[sql] In Ruby App Tutorial, activerecord-cockroachdb-adapter is not up to date

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#6945]
It appears our activerecord-cockroachdb-adapter is out of date and not compatible with our new implementation of Savepoints.

Ruby App Tutorial with CRDB and Active Record: https://www.cockroachlabs.com/docs/stable/build-a-ruby-app-with-cockroachdb-activerecord.html#insecure

When running the script provided on the wiki with 20.1's Savepoints, it didn't roll back. KV Engineering has suggested that we use the off-the-shelf adapter.

The output should have been just "7 2300"

script: 
![image](https://user-images.githubusercontent.com/1663752/77119324-9a5a9180-6a0c-11ea-9db5-2202b3ff8ea8.png)

output: 
![image](https://user-images.githubusercontent.com/1663752/77119336-a0507280-6a0c-11ea-9b81-0a6d8a6536bb.png)

**Comment by johnrk** [comment]
This may be resolved with this issue: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/42

**Comment by awoods187** [comment]
Hey @johnrk, thanks for taking a look! We have a contractor working on this now. I'd skip testing with active record and let him work through that.

**Comment by johnrk** [comment]
@awoods187 , oh ok great, any other ORMs that I should skip?

**Comment by johnrk** [comment]
@awoods187 , to clarify, only skip Active Record? and the remaining ones are fair game?

**Comment by awoods187** [comment]
Yes skip Active Record. I'd only test with those ORMs mentioned in the comment above.

**Comment by ericharmeling** [comment]
I've going to close this, because I think this is more of an adapter issue than a docs issue, and is already covered by https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/42.

Please reopen if need-be.
