### ISSUE TITLE
Secure local cluster Admin UI is not accessible on Chrome

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6946]
When running a secure local cluster, following our [getting started docs](https://www.cockroachlabs.com/docs/dev/secure-a-cluster.html), it's no longer possible to access the Admin UI on Chrome. Seems to work fine on FF and Safari.

Given Chrome's popularity and the importance of helping users have a quick and easy getting started experience via our docs and otherwise, I consider this a significant problem, potentially a release blocker, though that's not my call. At the least, we need to figure out how to adjust the docs so that copy/paste works for spinning up a local cluster and accessing the admin UI for new users. 

Steps:

```
~$ mkdir certs my-safe-directory

~$ cockroach cert create-ca --certs-dir=certs --ca-key=my-safe-directory/ca.key

~$ cockroach cert create-node localhost $(hostname) --certs-dir=certs --ca-key=my-safe-directory/ca.key

~$ cockroach cert create-client root --certs-dir=certs --ca-key=my-safe-directory/ca.key

~$ cockroach start --certs-dir=certs --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
*
* INFO: initial startup completed.
* Node will now attempt to join a running cluster, or wait for `cockroach init`.
* Client connections will be accepted after this completes successfully.
* Check the log file(s) for progress.
*

~$ cockroach start --certs-dir=certs --store=node2 --listen-addr=localhost:26258 --http-addr=localhost:8081 --join=localhost:26257,localhost:26258,localhost:26259 --background
*
* INFO: initial startup completed.
* Node will now attempt to join a running cluster, or wait for `cockroach init`.
* Client connections will be accepted after this completes successfully.
* Check the log file(s) for progress.
*

~$ cockroach start --certs-dir=certs --store=node3 --listen-addr=localhost:26259 --http-addr=localhost:8082 --join=localhost:26257,localhost:26258,localhost:26259 --background
*
* INFO: initial startup completed.
* Node will now attempt to join a running cluster, or wait for `cockroach init`.
* Client connections will be accepted after this completes successfully.
* Check the log file(s) for progress.
*

~$ cockroach init --certs-dir=certs --host=localhost:26257
Cluster successfully initialized

~$ grep 'node starting' node1/logs/cockroach.log -A 11
CockroachDB node starting at 2020-03-19 15:07:58.540333 +0000 UTC (took 11.5s)
build:               CCL v20.1.0-beta.2-937-g1ae9b8d2cd @ 2020/03/19 03:25:00 (go1.13.7)
webui:               https://localhost:8080
sql:                 postgresql://root@localhost:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
RPC client flags:    cockroach <client cmd> --host=localhost:26257 --certs-dir=certs
logs:                /Users/jesseseldess/node1/logs
temp dir:            /Users/jesseseldess/node1/cockroach-temp947498966
external I/O path:   /Users/jesseseldess/node1/extern
store[0]:            path=/Users/jesseseldess/node1
storage engine:      rocksdb
status:              initialized new cluster
clusterID:           aa69e24b-ffbd-4716-a49a-fb7371ba80fc
```

When you go to https://localhost:8080 in Chrome and click "Advanced" on the initial "Your connection is not private" warning page, you get:

<img width="699" alt="Screen Shot 2020-03-19 at 11 10 48 AM" src="https://user-images.githubusercontent.com/15893490/77082337-4f238d00-69d2-11ea-9626-13b987fb9fa4.png">

In contrast, when you do the same think in FF, you have the option to "Accept risk and continue" and can create the Admin UI login page. Same basic path on Safari. 

As suggested by @knz, I tried listing `$(hostname)` before `localhost` in the cert and starting nodes with `--http-addr=$(hostname):8080` and then directing browser to `https://<hostname>:8080`, but no luck. 

**Environment:**
CockroachDB version:  v20.1.0-beta.2-937-g1ae9b8d2cd
Server OS: MacOS
Chrome version: Version 80.0.3987.149 (Official Build) (64-bit)
FF version: 72.0.2 (64-bit)
Safari versio: 13.0.5 (15608.5.11)

**Comment by knz** [comment]
Note that changing the chrome settings degrades the user's browser security for everything, not just crdb. Some eyebrows will be raised. We need to acknowledge this is not a panacea and recommend users to reset the change when they actually deploy.

**Comment by jseldess** [comment]
@knz, I'm glad you're mentioning this. It's pretty unfortunately that we need to degrade security in that way just to maintain a decent getting started experience. Before moving forward, I'd like to understand if there's anything else we can do. @aaron-crl's workaround would let us avoid degrading the user's security, but it's just too complex for getting started. Users should be able to use our cockroach-created certs and access the admin UI locally. 

cc @piyush-singh

**Comment by knz** [comment]
so Piyush and i were talking about the user journeys yesterday and we figured there were two separate stories:

- user sets up fresh cluster in the cloud - then we want real security, no shortcuts

- user sets up test cluster on own laptop - then we don't care about transport security, just proper authentication and authorization

So something I could see happening is this:

- crdb opens a non-TLS listener for the UI on `localhost` (access via local browser only)
- set up a TLS-strenghtened conn for non-localhost connections (probably non-applicable for the laptop journey)

**Comment by knz** [comment]
xref #44842

**Comment by knz** [comment]
note that [my above proposal](https://github.com/cockroachdb/docs/issues/6946#issuecomment-601901208) (auto-start a non-TLS listener for the UI on the local interface) could be introduced via an opt-in command-line flag.

this way the doc can advise "for testing locally, use the flag `--local-ui` and then use the URL printed by the server" and get moving forward without caring about the browser config in any way.

**Comment by knz** [comment]
I too am sensing this could escalate into the status of release blocker.

This is a relatively minor product change, both low effort and low risk, but it does correspond to a new feature, and thus would require special approval (product? @petermattis?) to squeeze it in during the stability period.

**Comment by aaron-crl** [comment]
I concur with @knz on both the user stories and the proposal. Moving the starter guide to use http would remove most of the frication. We could have the more extensive workaround presented for cloud accessible starting instructions - where the security should be a concern.
