### ISSUE TITLE
Create how-to on shutting down a node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6951]
Jesse Seldess (jseldess) commented:

We are overloading the `cockroach quit` command to double as command reference and broader explanation of the process of shutting down a node. Instead, we should have a distinct page, `Stop a node`, that explains best practices and exactly what happens during the shut down process, and how to do it. 

Jira Issue: DOC-466

**Comment by knz** [comment]
xref: https://github.com/cockroachdb/cockroach/pull/45149
xref: https://github.com/cockroachdb/cockroach/pull/46396

**Comment by knz** [comment]
update on this: the new flag `--only-drain` to `cockroach quit` introduced in https://github.com/cockroachdb/cockroach/pull/45149 now reports a progress indicator, which can be used to determine when it's safe to stop the process.

**Comment by taroface** [comment]
- Add links to this article from `cockroach-quit.md`, `planned-maintenance.md`.

**Comment by taroface** [comment]
Also this thread: https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1635774345034000
