### ISSUE TITLE
release-19.2: roleccl: enable GRANT/REVOKE for roles without a license

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6960]
PR: https://github.com/cockroachdb/cockroach/pull/45395

From release notes:
> Non-licensed users are now able to add more principals to the special superuser role/group `admin`. [Creation of additional roles](../v19.2/create-role.html) is still a licensed feature. [#45395][#45395] {% comment %}doc{% endcomment %}
>
> It is now possible to use [`GRANT`](../v19.2/grant.html) and [`REVOKE`](../v19.2/revoke.html) to add users to the `admin` role without a valid license. This change aims to enable use of the Admin UI and other privileged features without a license. [#45395][#45395] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7003
