### ISSUE TITLE
backup: re-enable fast incremental BACKUP via TBI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6970]
PR: https://github.com/cockroachdb/cockroach/pull/46108

From release notes:
> Incremental [`BACKUP`](../v20.1/backup.html) can quickly skip unchanged data, making frequent incremental backups 10-100x faster, depending on data size and frequency. [#46108][#46108] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - no docs needed
