### ISSUE TITLE
sql: add CREATE SCHEMA IF NOT EXISTS for existing schemas

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6972]
PR: https://github.com/cockroachdb/cockroach/pull/42703

From release notes:
> Now allow no-op `CREATE SCHEMA IF NOT EXISTS` statements. [#42703][#42703] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This syntax is no-op (i.e., it will return "ERROR: unimplemented: new schemas are unsupported"). We shouldn't document it (with a page, examples, diagram, etc) until we actually support it (potentially tracked by this issue: https://github.com/cockroachdb/cockroach/issues/26443).

In the meantime, we do call out that we do not support `CREATE SCHEMA`: https://www.cockroachlabs.com/docs/dev/detailed-sql-support.html
