### ISSUE TITLE
 sql: re-add GC job on schema element deletion

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6973]
PR: https://github.com/cockroachdb/cockroach/pull/45962

From release notes:
> Previously, after deleting an index, table, or database, the relevant schema change job would change its running status to waiting for GC TTL. The schema change and the GC process are now decoupled into two jobs. [#45962][#45962] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
AFAICT, https://github.com/cockroachdb/cockroach/pull/45962 does not affect the user-facing syntax/behavior/output of online schema changes. 

@pbardea Please reopen if you disagree. :)
