### ISSUE TITLE
sql: add ability to alter primary key of a new table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6975]
PR: https://github.com/cockroachdb/cockroach/pull/46015

From release notes:
> It is now possible to [create a table](../v20.1/create-table.html) and then add or alter a [primary key](../v20.1/primary-key.html) within the same transaction. [#46015][#46015] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Alter PK https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckXe8OwbdVi8WzH
