### ISSUE TITLE
sql: Move RBAC into the BSL license.

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6976]
PR: https://github.com/cockroachdb/cockroach/pull/46042

From release notes:
> All [role-based access control (RBAC) features](../v20.1/authorization.html#roles) (`CREATE ROLE`, [`ALTER ROLE`], `DROP ROLE`, `GRANT ROLE`, `REVOKE ROLE`) are now available to non-enterprise users. All RBAC features are now [BSL features](../v20.1/licensing-faqs.html). [#46042][#46042] {% comment %}doc{% endcomment %}
>
> The statement tag returned to the client upon success for [`CREATE USER`](../v20.1/create-user.html), [`ALTER USER`](../v20.1/alter-user.html), and [`DROP USER`](../v20.1/drop-user.html) now include the word "ROLE" instead of "USER", for compatibility with PostgreSQL. These three statements are now aliases for `CREATE ROLE`, `ALTER ROLE`, `DROP ROLE`. [#46042][#46042]  {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7003
