### ISSUE TITLE
sql: remove experimental prefix from opt-driven FK settings

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6978]
PR: https://github.com/cockroachdb/cockroach/pull/46174

From release notes:
> Renamed `experimental_optimizer_foreign_keys` [session variable](../v20.1/set-vars.html) and `sql.defaults.optimizer_foreign_keys.enabled` [cluster setting](../v20.1/cluster-settings.html) to remove the experimental prefix. [#46174][#46174] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckMh49RgMbRHhDs
https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recagjuRqKN5Jxh1n
