### ISSUE TITLE
sql: make some tweaks to using the vectorized engine

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6979]
PR: https://github.com/cockroachdb/cockroach/pull/46080

From release notes:
> `experimental_on` option for `vectorize` [session variable](../v20.1/set-vars.html) has been renamed to `on`. The only things that will not run with `auto`, but will run with `on`, are unordered [`DISTINCT`](../v20.1/select-clause.html#eliminate-duplicate-rows) and two [window functions](../v20.1/window-functions.html) (`percent_rank` and `cume_dist`). The two options are otherwise identical. [#46080][#46080] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
vectorized execution https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/reckMh49RgMbRHhDs
https://airtable.com/tblD3oZPLJgGhCmch/viwNg2fK3NU3DUY6Z/recagjuRqKN5Jxh1n
