### ISSUE TITLE
Make links absolute instead of relative

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#698]
For @jess-edwards

**Comment by sploiselle** [comment]
Talked to Matt about this. We can achieve it with a shell script that runs on Team City (CircleCI's being retired) before moving the updated contents into the root. Let's talk about this once you're back in the office.

**Comment by jseldess** [comment]
@mjibson, @sploiselle, doing this via TeamCity sounds good. It might be possible to set `url: "https://cockroachlabs.com"` in `_config.yaml` and then prepend `{{% site.url %}}` to all links.

**Comment by jseldess** [comment]
@sploiselle, the Test Doc teamcity config has a step to replace relative with absolute links, but something in the regex is failing. @mjibson tells me that you were planning to go in and figure that out. Just putting this back on your radar.

**Comment by jseldess** [comment]
This is done, thanks to @sploiselle and @mjibson, so I'm closing.
