### ISSUE TITLE
sql,cli: improve the handling of notices

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6984]
PR: https://github.com/cockroachdb/cockroach/pull/46124

From release notes:
> The [`cockroach sql`](../v20.1/cockroach-sql.html) and [`cockroach demo`](../v20.1/cockroach-demo.html) client commands now display out-of-band server notices at the end of execution. [#46144][#46144] [#46124][#46124] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I'm of the opinion that we not explicitly document these notices in our docs.

@knz @awoods187

Let me know if you disagree.
