### ISSUE TITLE
Release support/EOL policy

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6993]
We need a universal landing page for all up to date EOL releases for (CC and self hosted). Today, self hosted may live in contracts but not publicly facing.
@jseldess @robert-s-lee @tim-o

**Comment by dbist** [comment]
There's an example of CC EOL statement but we should have a landing site https://github.com/cockroachdb/docs/issues/6992

**Comment by jseldess** [comment]
We're publishing a Release Support Policy for CockroachDB. We will need to have a separate CC page for now, but I'll make sure it reflects/leverages the policy as necessary.
