### ISSUE TITLE
Node Decommissioning references a non existant command

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/docs#6996]
I was reading through [Node Decommissioning](https://www.cockroachlabs.com/docs/stable/training/node-decommissioning.html) and was trying to hunt down the `cockroach decommission` command.

It took a bit of digging but it looks like the correct command is `cockroach node decommission`.

**Comment by jseldess** [comment]
Thanks, @chrisseto. I'll fix this as part of broader decommission doc improvements.

**Comment by jseldess** [comment]
This page has been taken offline in the meantime. Our decommissioning docs should be up-to-date: https://www.cockroachlabs.com/docs/v20.1/remove-nodes.html
