### ISSUE TITLE
install client drivers

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7]
Call out recommended postgres drivers (those we've tested) for:
- python
- ruby
- go
- c
- javascript (node.js)
- java
- php
- closure

Also mention that any postgres driver should work and suggest getting in touch if any problems.

**Comment by jseldess** [comment]
Done: https://www.cockroachlabs.com/docs/install-client-drivers.html

**Comment by bladefist** [comment]
Was there any reason c# was left off this list?

**Comment by sploiselle** [comment]
@bladefist Only because we haven't tested or vetted Npgsql. If you want to test it out for us, we'd be excited to have the contribution!

**Comment by bladefist** [comment]
@sploiselle I don't have the cockroachdb or Npgsql expertise to be the one to do that.  I'm just beginning my journey and felt it odd that a major platform that businesses use was left out and wanted to make sure it wasn't a mistake.  Hopefully someone can contribute this!
