### ISSUE TITLE
guidance for shutting down a whole cluster

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#7002]
Matthew Vardi (mattcrdb) commented:

the motivation for this is that resources are expensive, some users of cockroach would like to shut down the whole cluster and restart it the following day.

In 3 node cluster given 3x replication there shouldn't be any upreplication and the shutdown will invalidate the leases anyway.

our docs only discuss shutting down one node for planned maintinence.

i encourage a discussion with another kv engineer to see what the process would be for a cluster with > 3 nodes.

IMO the section would expand on this section https://www.cockroachlabs.com/docs/stable/operational-faqs.html#how-do-i-prepare-for-planned-node-maintenance

Jira Issue: DOC-472

**Comment by mattcrdb** [comment]
xref: https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1585231354008300

related to https://github.com/cockroachdb/docs/issues/6951

**Comment by jseldess** [comment]
cc @johnrk, @taroface
