### ISSUE TITLE
sql: require admin in COPY-based nodelocal upload

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7026]
PR: https://github.com/cockroachdb/cockroach/pull/46265

From release notes:
> The `admin` role is now required to use the new [`cockroach nodelocal upload`](../v20.1/cockroach-nodelocal-upload.html) functionality. [#46265][#46265] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - already documented
