### ISSUE TITLE
backup: re-enable fast incremental BACKUP via TBI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7027]
PR: https://github.com/cockroachdb/cockroach/pull/46390

From release notes:
> Incremental [`BACKUP`](../v20.1/backup.html) can now quickly skip unchanged data. This makes frequent incremental backups 10-100x faster depending on data size and frequency. [#46390][#46390] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - no docs needed
