### ISSUE TITLE
sql: Added support for the stddev_samp aggregate builtin function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7033]
PR: https://github.com/cockroachdb/cockroach/pull/46279

From release notes:
> Added support for the `stddev_samp` aggregate [builtin function](../v20.1/functions-and-operators.html), which is the same as `stddev` (according to PostgreSQL documentation, the latter is actually the historical alias of the former). [#46279][#46279] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
The docs for these BIFs are already up on the website here:

https://www.cockroachlabs.com/docs/dev/functions-and-operators.html#aggregate-functions

Calling this one good!
