### ISSUE TITLE
[Cloud] How does a user cancel a CC account?

### ISSUE THREAD

**Issue by celiala** [cockroachdb/docs#7037]
A CC customer opened a Zendesk ticket to ask us how to cancel their CC account. Creating a ticket for the Education team to assess how we might want to document.

Note that part of the solution (a global delete button) is still in staging only.

Here's the full [Slack thread](https://cockroachlabs.slack.com/archives/CBE9QQC4S/p1585663074058700)

**Comment by lnhsingh** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/7037

**Comment by unusualevent** [comment]
wait, @lnhsingh  7037 references itself? and there's still no global delete button, 3 years later, or any documentation on the matter?
