### ISSUE TITLE
Understand and document our Algolia search integration

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7048]
@lnhsingh, this is an issue for YZ to learn about, and take over, our Algolia integration. Can you please add a link to the docs the contractors created? Perhaps it'd also make sense for YZ to sit down with you and Peter to learn the basics?

- [ ] Research and understand our Algolia integration
- [ ] Document how it works, and how to troubleshoot problems, on our Education wiki.

**Comment by lnhsingh** [comment]
Sorry, just getting around to this. I added the doc the contractor wrote to [the wiki](https://cockroachlabs.atlassian.net/wiki/x/0ATUGQ) and will add more info this week.

**Comment by yingzhuchin** [comment]
This is ready for review here: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/479232056/Search+Integration

**Comment by jseldess** [comment]
Aside from a broken link, this looks excellent. Thank you, @yingzhuchin!
