### ISSUE TITLE
Understand and document our Jekyll build

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7049]
- [ ] Research and understand how Jekyll builds our docs, including:
    - How CockroachDB and CockroachCloud docs are built using the [Makefile](https://github.com/cockroachdb/docs/blob/master/Makefile), `_config_xxx.yml` files, and front-matter fields.
    - How versioning works.
    - How the sidenav is built.
    - How CSS works.
    - Other Jekyll-specific and JS customizations.
- [ ] Document how it works, and how to troubleshoot problems, on our Education wiki.

Resources:
- [Docs initial setup](https://github.com/cockroachdb/docs/wiki/Docs-Initial-Setup)
- [Basic docs tasks](https://github.com/cockroachdb/docs/wiki/Common-Docs-Tasks) (fairly out-dated)
- [CONTRIBUTING.md](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md) (with external contributor guidelines and explanation of docs structure, front-matter, etc.).

**Comment by yingzhuchin** [comment]
Hi Jesse, here's a quick and dirty draft: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/452264584/Jekyll

I'll continue to work on this tomorrow and beyond as I have time to do so. Any feedback appreciated!

**Comment by jseldess** [comment]
This is excellent, @yingzhuchin! Thank you for pulling this together. I think this is the right foundation. You can dive deeper, and expand these docs, when relevant projects arise. But I'll also ask the rest of the team to take a look and leave comments/questions. Once any raised questions are addressed, you can close this issue.
