### ISSUE TITLE
Move docs testing from TeamCity to Netlify

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7050]
Netlify builds test sites for each PR, so if we can figure out how to run our link checking and prose linting via Netlify or GitHub actions, we might simplify our pipeline and move off of TC entirely. 

However, for other CI work, such as automated testing of code on docs, TeamCity might remain the best option.

**Comment by yingzhuchin** [comment]
Netlify has a built-in support for checking links: https://github.com/munter/netlify-plugin-checklinks/blob/master/README.md

Work is needed to test and understand whether Netlify's solution works for us, and whether that solution requires additional tuning.

**Comment by jseldess** [comment]
If we move entirely to Netlify, we should make sure we can run tests on both PRs and at other times. In TC, we currently run a nightly test to check all of our external links (only internal links are checked on PRs because it's faster). We could expand our nightly test to also validate all HTML: https://github.com/cockroachdb/docs/issues/3301. Perhaps we should check git merge conflict markers in PRs as well: https://github.com/cockroachdb/docs/issues/7066

It's also worth thinking about how we drive other non-docs-site automation, such as testing sample app code: https://github.com/cockroachdb/docs/issues/7066. For that, we may need to continue using TeamCity.
