### ISSUE TITLE
Understand and document our docs CI/CD (TeamCity and Netlify)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7051]
- [ ] Research and understand how we use TeamCity to test docs, including:
    - Building test sites per PR and syncing to S3
    - Link checking (htmltest)
    - Prose linting (vale)
- [ ] Research and understand how Netlify deploys our docs, including
    - Server-side redirects and integration with the marketing site
- [ ] Document how the above works, and how to troubleshoot problems, on our Education wiki.

Note: Previously, we used TeamCity to also build our live site. There are lots of artifacts left from that time that should eventually be removed. Also, Netlify builds test sites for each PR, so if we can figure out how to run our link checking and prose linting via Netlify or GitHub actions, we might simplify our pipeline and move off of TC entirely. Related project: https://github.com/cockroachdb/docs/issues/7050

**Comment by yingzhuchin** [comment]
Hi @jseldess, how may I gain access to docker.io/cockroachdb/docs-builder? Thanks!

**Comment by jseldess** [comment]
@bobvawter or @mjibson, can either of you help @yingzhuchin with this?

**Comment by mjibson** [comment]
I don't have permissions to add users. A devinf person will need to do this I think.

**Comment by bobvawter** [comment]
@yingzhuchin What is your dockerhub account name?

**Comment by yingzhuchin** [comment]
@bobvawter yzdocs

Thank you!

**Comment by bobvawter** [comment]
Added you to the employees group on DH

**Comment by yingzhuchin** [comment]
Thanks, Bob! Sorry I didn't include this in my earlier ask, but is there also separate access for Netlify? I tried synching with my GitHub credentials but not seeing any established team settings.

**Comment by bobvawter** [comment]
I don't have any knowledge of Netlify.

**Comment by mjibson** [comment]
I've invited @yingzhuchin to our netlify account.

**Comment by yingzhuchin** [comment]
Thanks, @mjibson!

**Comment by yingzhuchin** [comment]
My draft is up here: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/464453705/Docs+CI+CD
