### ISSUE TITLE
Understand and document SQL help text generation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7052]
"Document how the textual version works and sketch out the questions we want to answer through user testing" (From Jesse during Slack discussion)

**Comment by jseldess** [comment]
@yingzhuchin, based on our docs biweekly today, this is definitely the next priority for docs, after the product ops project that you can @katedoebler will identify.

**Comment by yingzhuchin** [comment]
Changing Issue description since we are exploring pivoting from SQL Diagrams to SQL help text.
