### ISSUE TITLE
example is missing table name@index

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#7070]
[This example](https://www.cockroachlabs.com/docs/stable/online-schema-changes.html#examples-of-statements-that-fail) incorrectly has this statement:
```
 SELECT * from foo_idx;
```
It should be
```
 SELECT * from foo@foo_idx;
```

The results incorrectly has:
```
ERROR:  relation "foo_idx" does not exist
```
It should be
```
pq: index "foo_idx2" not found
```

**Comment by rmloveland** [comment]
Hi @florence-crl thanks for filing this issue!  This statement is definitely incorrect, and I'm making a PR now to update it to `SELECT * from foo@foo_idx` as you mentioned.

However, even with the updated "select from an index" syntax I am still getting the error

```
ERROR: relation "foo_idx" does not exist
SQLSTATE: 42P01
```

and not the same one you are seeing (i.e. `pq: index "foo_idx2" not found`)

Here are the exact statements I'm running:

```
root@localhost:26257/defaultdb> SELECT VERSION();
                                            version
-----------------------------------------------------------------------------------------------
  CockroachDB CCL v20.1.0-beta.4 (x86_64-apple-darwin14, built 2020/03/24 01:31:53, go1.13.5)
(1 row)
root@localhost:26257/defaultdb> CREATE TABLE foo (id INT PRIMARY KEY, name VARCHAR);
  BEGIN;
  SAVEPOINT cockroach_restart;
  CREATE INDEX foo_idx ON foo (id, name);
  SELECT * from foo_idx;
  RELEASE SAVEPOINT cockroach_restart;
  COMMIT;
CREATE TABLE
root@localhost:26257/defaultdb> BEGIN

root@localhost:26257/defaultdb  OPEN> SAVEPOINT

root@localhost:26257/defaultdb  OPEN> CREATE INDEX

root@localhost:26257/defaultdb  OPEN> ERROR: relation "foo_idx" does not exist
SQLSTATE: 42P01
root@localhost:26257/? ERROR> ERROR: current transaction is aborted, commands ignored until end of transaction block
SQLSTATE: 25P02
root@localhost:26257/? ERROR> ROLLBACK
```

Summing up:
- syntax in the docs is wrong, will fix
- error message appears to stay the same once syntax is fixed (but maybe I'm missing something?)

Can you share the exact version and SQL statements you are running that produce the error `pq: index "foo_idx2" not found` ?
