### ISSUE TITLE
Clipped `CONTRIBUTE` modal

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7072]
Looking at https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb.html on Firefox, the modal when clicking Contribute is clipped.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/10536690/78401336-898e4c00-75c6-11ea-899d-6353bb340b68.png">

**Comment by jseldess** [comment]
Thanks for reporting, @irfansharif. We're tracking this here: https://github.com/cockroachdb/docs/issues/6870
