### ISSUE TITLE
Add automatic sitemap generation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#71]
We need to add a sitemap to make sure Google and other search engines know about the organization of our site. 

It might be best to start by having GitHub automatically generate our sitemap: https://help.github.com/articles/sitemaps-for-github-pages/. 

Here are the docs for the plugin itself: http://www.rubydoc.info/gems/jekyll-sitemap/0.10.0

**Comment by mjibson** [comment]
This got done.
