### ISSUE TITLE
Document window functions

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#710]
We need to complete our page on [window functions](https://www.cockroachlabs.com/docs/stable/window-functions.html). Our implementation is similar to [Postgres](https://www.postgresql.org/docs/9.1/static/tutorial-window.html), so we can start by testing everything on that page.

Also need to update the [SQL feature table](https://www.cockroachlabs.com/docs/sql-feature-support.html).

**Comment by jseldess** [comment]
PRs:
- https://github.com/cockroachdb/cockroach/pull/8928
- https://github.com/cockroachdb/cockroach/pull/9321
- https://github.com/cockroachdb/cockroach/pull/9335

**Comment by jseldess** [comment]
Source code: 
- https://github.com/cockroachdb/cockroach/blob/8ac54961ab8edc641e41880f8e410032dc1843eb/pkg/sql/window.go#L31
- https://github.com/cockroachdb/cockroach/blob/1c0a035d17d12d37379c54a9e7a648f2171bfab0/pkg/sql/parser/window_builtins.go

**Comment by jseldess** [comment]
Stub docs put in place with https://github.com/cockroachdb/docs/pull/1948.

**Comment by tlvenn** [comment]
Hi @jseldess ,

Could you clarify if there is feature parity with what Postgres is offering ? If not, is there a todo list related to this somewhere ?

Thanks !

**Comment by jseldess** [comment]
@tlvenn, so sorry for my extreme delay here. I believe there is feature parity with Postgres, but I'm not 100% certain. We'll build out more robust docs on window functions soon.

**Comment by tlvenn** [comment]
no worry, thanks for the feedback @jseldess

**Comment by jseldess** [comment]
For 2.1, this is part of https://github.com/cockroachdb/docs/issues/2944.

**Comment by jseldess** [comment]
@rmloveland, in [this PR](https://github.com/cockroachdb/docs/pull/3493
), I just added the auto-generated docs on windows functions: 
https://www.cockroachlabs.com/docs/v2.1/functions-and-operators.html#window-functions.

Feel free to cross-reference in your window functions doc updates.

**Comment by rmloveland** [comment]
This was fixed in #3426 (at least for now - could always be improved, window functions are a big topic).
