### ISSUE TITLE
Fix Captioning for multiple videos

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7102]
1:09 && 1:13 “rights” instead of “writes”
1:53 “sequel” instead of “SQL”

**Comment by SpicyThrow** [comment]
The Raft Protocol in CockroachDB
0:35 “it’s” instead of “its”
1:52 “upends” instead of “appends”

Availability and Durability in a Three Node Cluster
0:10 “dated,” instead of “data”
1:03 “clients” instead of “client’s”
1:09 “operations” instead of “operation”
2:46 missing “to” between “it” and “get”

Fault Tolerance and Automated Recovery
0:32 “sequel” instead of “SQL”

Introduction to Secondary Indexes
3:35 “all” instead of “I’ll”
4:48 “asset” instead of “ACID”

Localities
0:23 “copper” instead of “cockroach”
0:44 “lease” instead of “least”
3:01 “mover” instead of “movr”

Geo-partitioning
1:02 “mover” instead of “movr”

CockroachDB: A True Distributed SQL Database
Onscreen graphic: resiliency is spelled wrong at :08

**Comment by SpicyThrow** [comment]
I've corrected these issues in the downloadable script files and updated them on AWS. I've also corrected these issues on the YouTube subtitles. 
I provided the changes to Grant but I noted these fixes are lower priority than net-new content creation so I don't expect fixes any time soon.

**Comment by SpicyThrow** [comment]
Have Grant check "right" vs "write" in "Future of Databases".

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
