### ISSUE TITLE
Clarify that CDC / changefeeds are not intended to be a low latency pub sub mechanism

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7105]
Our [CDC docs][1] say that it

> provides efficient, distributed, row-level change feeds into a configurable sink for downstream processing such as reporting, caching, or full-text indexing.

Although it's (perhaps?) implied by the text above, we should say explicitly that

> CDC is not a low latency pub sub mechanism
> CDC is for high-latency data export from the database to a data warehouse

This came up via internal discussion, so it's possible that some users will need this clarified / made more explicit as well.

[1]: https://www.cockroachlabs.com/docs/dev/change-data-capture.html

**Comment by rmloveland** [comment]
@lnhsingh please feel free to unassign if you are no longer the CDC person!

**Comment by lnhsingh** [comment]
@rmloveland - nope, still me. thanks for filing!
