### ISSUE TITLE
incorrect default for kv.range_split.load_qps_threshold

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#7108]
On this page https://www.cockroachlabs.com/docs/v19.2/load-based-splitting.html#control-load-based-splitting-threshold, the default for `kv.range_split.load_qps_threshold`
incorrectly says `250` should be `2500` as per the code (line 33) in
https://github.com/cockroachdb/cockroach/blob/fe495eeaf2746507f27073c9c911d861a8ec9428/pkg/kv/kvserver/replica_split_load.go.

This example

```
SET CLUSTER SETTING kv.range_split.load_qps_threshold = 200;
```

 should probably also be modified to

```
SET CLUSTER SETTING kv.range_split.load_qps_threshold = 2000;
```

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5100](https://cockroachdb.zendesk.com/agent/tickets/5100) has been linked to this issue.
