### ISSUE TITLE
cli/demo: make `cockroach demo` use secure mode by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7128]
PR: https://github.com/cockroachdb/cockroach/pull/46472

From release notes:
> The new `--unencrypted-localhost-http` flag for [`cockroach start`](../v20.1/cockroach-start.html) and [`cockroach start-single-node`](../v20.1/cockroach-start-single-node.html) forces the HTTP listener to bind to `localhost` addresses only and disables the TLS protocol. In secure clusters, this makes the Admin UI reachable with an `http://` URL without requiring certificate or CA setup. [#46472][#46472] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@jseldess Am I right in thinking the release notes snippet does not correspond to the linked PR?

**Comment by jseldess** [comment]
It connects to one of the commits in that PR: https://github.com/cockroachdb/cockroach/pull/46472/commits. Not sure if/how it relates to `cockroach demo`, though.

**Comment by johnrk** [comment]
cc @thtruo
