### ISSUE TITLE
release-20.1: backupccl: add is_full_cluster to SHOW BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7130]
PR: https://github.com/cockroachdb/cockroach/pull/46768

From release notes:
> [`SHOW BACKUP`](../v20.1/show-backup.html) now shows whether a `BACKUP` is a full cluster backup or not. [#46768][#46768] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - already documented.
