### ISSUE TITLE
release-20.1: backupccl: add privileges to SHOW BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7131]
PR: https://github.com/cockroachdb/cockroach/pull/46853

From release notes:
> [`SHOW BACKUP`](../v20.1/show-backup.html)  now shows the privileges assigned to tables and databases in a backup and, if the `WITH privileges` option is specified, lists which users and roles had which privileges. [#46853][#46853] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - already documented
