### ISSUE TITLE
release-20.1: backupccl: prevent automatically narrowing full backups

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7133]
PR: https://github.com/cockroachdb/cockroach/pull/46966

From release notes:
> The new, appending [incremental backup syntax](../v20.1/backup.html#create-incremental-backups) does not allow converting a [full cluster backup](../v20.1/backup.html#backup-a-cluster) to a specific table or database backup. [#46966][#46966] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - no docs needed.
