### ISSUE TITLE
Script for Physical Explain Plans

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7156]
Write a script that covers the following:
• Generate a physical EXPLAIN plan with EXPLAIN ANALYZE
• Find the index used in a query with an EXPLAIN ANALYZE plan
• Determine which nodes are involved in a query with the physical EXPLAIN ANALYZE plan
• Given a query, use the EXPLAIN ANALYZE plan and determine: 
  • how many index points were touched by the query
  • how many rows were touched by the query
  • how many records are returned by the query

**Comment by SpicyThrow** [comment]
Script drafted. Hoping to connect with Will tomorrow for edits.

**Comment by SpicyThrow** [comment]
Sent to Will for review.

**Comment by SpicyThrow** [comment]
Reviewed script with Will. Visuals drafted and ready for the review team.

**Comment by SpicyThrow** [comment]
Submitted all assets to Grant for editing.

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
