### ISSUE TITLE
need to curate release notes for changes in develop not yet in master (for beta-20161013)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/docs#716]
This will be much more work than usually, so I created an extra issue.

**Comment by jseldess** [comment]
@tschottdorf, @knz: I believe @bdarnell started this work last week: https://github.com/cockroachdb/docs/pull/694

**Comment by jseldess** [comment]
This is duplicate of https://github.com/cockroachdb/cockroach/issues/9781
