### ISSUE TITLE
Clarify when and when not to use partitioning

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7170]
We need to be explicit about `when to use table partitioning` and `when not to use table partitioning`, so users coming from other dbs don't think it's necessary to explicitly partition in non-multi-region cases. As @andy-kimball mentioned, in most non-multi-region cases, we partition (split) by default on key columns.

https://www.cockroachlabs.com/docs/v19.2/partitioning.html#why-use-table-partitioning

**Comment by jseldess** [comment]
Assigning to @rmloveland, who's working on multi-region for 21.1. This issue may become obsolete.

**Comment by rmloveland** [comment]
@awoods187 I think this issue to improve the partitioning docs is obsoleted by the new [multi-region capabilities](https://www.cockroachlabs.com/docs/v21.1/multiregion-overview) and can be closed.

please re-open if you disagree!
