### ISSUE TITLE
fix typo on Configure Replication Zones page

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#7174]
```
range_max_bytes | The maximum size, in bytes, for a range of data in the zone. When a range reaches this size, CockroachDB will spit it into two ranges.
```

`spit` should be `split`

**Comment by Shiwanee** [comment]
@florence-crl  I would like to take up this issue, could you please assign it to me?
Thanks

**Comment by Amruta-Ranade** [comment]
@memon07 Shiwanee gets dibs :)
@Shiwanee Are you still interested in the issue?

**Comment by Shiwanee** [comment]
@Amruta-Ranade , thanks :-). Yes, I am still interested.

**Comment by Amruta-Ranade** [comment]
@Shiwanee Just a note: If you are participating in Hacktoberfest, wait until October 1st to open the PR.
@memon07 Here are more issues for your consideration: https://github.com/cockroachdb/docs/labels/good-first-issue

**Comment by Shiwanee** [comment]
@Amruta-Ranade , sounds good.

**Comment by Amruta-Ranade** [comment]
@Shiwanee Are you working on this?

**Comment by Shiwanee** [comment]
@Amruta-Ranade yes!

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8538
