### ISSUE TITLE
Faulty link formatting on "Production Checklist Doc Update" page

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7180]
Look around "NUMA](https://en.wikipedia.org/wiki/Non-uniform_memory_access)(non-uniform memory access)", we missed a brace somewhere.

**Comment by Shiwanee** [comment]
@Amruta-Ranade , Could you please assign this issue to me?

**Comment by Amruta-Ranade** [comment]
@Shiwanee Since you already have an issue assigned to you, I'd like other participants to have a shot at this one. Feel free to check back in a few days to see if the issue is still available :)

**Comment by Shiwanee** [comment]
@Amruta-Ranade , Sure!
Thanks,
Shiwanee

**Comment by Shiwanee** [comment]
@Amruta-Ranade I was just checking back as Hacktoberfest is now around the corner :-)

**Comment by Amruta-Ranade** [comment]
Oh, I meant check back in mid-October 😄 I need time to publicize the issues and want to give folks time to evaluate them.

**Comment by jseldess** [comment]
This issue is out-dated. The issue was fixed in the meantime.

**Comment by Shiwanee** [comment]
@Amruta-Ranade Okay! I think I am too excited for Hacktoberfest! 😄 This is my first time and so was not aware of timelines for publishing the issues and way they are assigned! Sorry about that. 
If you think I can take up any other issues in future, please feel free to assign them to me. I would like to work on all 4(+) issues from Cockroach Labs for Hacktoberfest :-)
