### ISSUE TITLE
Update Go tutorial to use pgx driver

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#7185]
Re: [Build a Go App with CockroachDB the Go pg Driver](https://cockroachlabs.com/docs//v19.2/build-a-go-app-with-cockroachdb.html)

We should be recommending the `pgx` driver instead of `lib/pq`. It's better.

Separately, `pgx` can also be used directly as a library, not only as a driver for the Go `database/sql` package. We should also encourage that. There's native support for using `pgx` as a library in the `cockroach-go/crdb/crdbpgx` package.

**Comment by jseldess** [comment]
@andreimatei, can you please say more about using this as a library, what that means, and what we should be encouraging exactly? 

@awoods187, is this work connected to the appdev backlog in any way?

**Comment by awoods187** [comment]
I believe w've already tested it and it works well (cc @rafiss). It should be another option on the page as Andrei mentions. I've added it to the meta-issue of docs backlog for appdev.

**Comment by andreimatei** [comment]
> @andreimatei, can you please say more about using this as a library, what that means, and what we should be encouraging exactly?

The standard way to connect to SQL databases in Go is through the `databases/sql` package. The package is generic, allowing you to connect to any database. When you do
```
db, err := sql.Open("postgres", connStr)
```
what happens under the hood is that `sql.Open` looks for a driver registered for the name "postgres". `lib/pq` is such a driver, which registers itself when the program says `import _ "github.com/lib/pq"`. 
`jackc/pgx` is an alternative driver; it registers itself when you `import "gopkg.in/jackc/pgx.v4/stdlib"`. It uses the name "pgx" instead of "postgres", but otherwise which driver you use is supposed to be transparent to the application.

You can also use pgx directly, not through the `database/sql` package. Instead of `sql.Open()`, you do `pgx.Connect()`, and then you have a slightly different, more powerful interface for interacting with the database. I personally would use this interface if I'm OK with being married to Postgres (or CRDB). Go's standard interface is pretty inefficient and lacks all sorts of powers.

> It should be another option on the page as Andrei mentions.

I think it should be more than *another option*. Using pgx as a driver instead of lib/pq should be the default option. I think `lib/pq` is not developed any more, and it's also not the best code. I think @mjibson , who actually seems to have became `lib/pq`'s maintainer, will agree.
Using `pgx` directly, not as a driver, should also be encouraged. We don't necessarily need to provide code samples for it, but pointing to the `cockroach-go/crdb/crdbpgx` package would be good.

**Comment by rafiss** [comment]
To the question about testing -- yes, we have this tested in our nightlies and it is stable.

For what it's worth, based on my anecdotal experience lurking in the Golang slack, `pgx` usually comes up as the recommended path when a question comes up about database drivers for Postgres.
