### ISSUE TITLE
Update "cold starts of large clusters" known limitation

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7188]
As discussed in https://github.com/cockroachdb/docs/issues/6837:

> Cold starts of large clusters may require manual intervention - This
> one probably needs to be adjusted based on the new default range
> size. Also I think we should probably nudge people with existing
> clusters to up their range size limits to match the defaults."

Estimated scope of work:

- Investigate existing limitation

- Update accordingly, with input from engineering (looks like
  @andreimatei) and with info re: new range size

See also:

- #5971

**Comment by rmloveland** [comment]
FWIW there is no evidence (on GH) that this known limitation has actually been resolved.  The linked issues in the CRDB repo are still open.

However, at the very least the recommendation on the known limitations page to increase the range size to 128 MiB needs to be removed, since the default on 20.1 is now 512 MiB.  I'm doing that work as part of #5971

**Comment by ericharmeling** [comment]
This limitation has been resolved in 21.1 (https://github.com/cockroachdb/cockroach/pull/56860) and backported to 20.2 and 20.1. I'll close this issue with a forthcoming 21.1 known limitations PR.
