### ISSUE TITLE
document problems with rolling back schema changes that drop columns

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/docs#7192]
In 20.1 and 19.2 (and probably in 19.1, I need to check), some schema changes which drop columns can't be rolled back properly. (That is, rolling back the schema change involves bringing the column back, and we don't do this correctly.) Specifically:
1. In some cases, the rollback will succeed, but the column data might be partially or totally missing, or stale due to the async nature of the schema change. This is https://github.com/cockroachdb/cockroach/issues/46541. We can't make any guarantees about the state of the data in the column if the column was attempted to be dropped and that change was rolled back.
2. In other cases, the rollback will fail in such a way that it'll never get cleaned up properly, leaving the table descriptor in a state where no other schema changes can be run successfully. This is https://github.com/cockroachdb/cockroach/issues/47712. The issue provides an example; basically, this happens because we don't try to recover the data for the column that was attempted to be dropped, and some combination of default/computed values and constraints makes bringing back the column impossible.

    An indication this has happened is if the jobs table entry for the schema change has an error prefaced with `cannot be reverted, manual cleanup may be required` (in 20.1), or if they see `error purging mutation` repeatedly in the logs (in 19.2).

    I don't think there's a good way to recover from this aside from _possibly_ doing `CREATE TABLE AS` to copy over the contents of the table. I need to investigate this, at which point I'll follow up.

The second issue is a bug we really need to fix, or at least mitigate, so the situation will likely change for future point releases. But this is the state of things right now.

**Comment by rmloveland** [comment]
mentioning https://github.com/cockroachdb/cockroach/issues/46541 so these are linked
