### ISSUE TITLE
CC: "Try out CC" docs

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#7206]
https://airtable.com/tblD3oZPLJgGhCmch/viwTBy1c8OnK6G6t4/recRsegigkmOja6ZN?blocks=hide

https://airtable.com/tblD3oZPLJgGhCmch/viwTBy1c8OnK6G6t4/recgBcKEmT14IkmyJ?blocks=hide

https://airtable.com/tblD3oZPLJgGhCmch/viwTBy1c8OnK6G6t4/recmaoqpaauLYlfbo?blocks=hide

**Comment by lnhsingh** [comment]
Closing this as I think it's out of date
