### ISSUE TITLE
Incorrect command in "Step 6. Stop the cluster"

### ISSUE THREAD

**Issue by EKranjec** [cockroachdb/docs#7207]
Re: [Start a Cluster in Docker (Insecure)](https://cockroachlabs.com/docs//v19.2/start-a-local-cluster-in-docker-windows.html)

## Issue Description
At _"Step 6. Stop the cluster"_ after _"If you do not plan to restart the cluster, you may want to remove the nodes' data stores:"_ there is a mistake in the command _"Remove-Item C:\Users\username> cockroach-data -recurse"._

## Suggested Resolution 
Replace this line with: _"PS C:\Users\username> Remove-Item cockroach-data -recurse"_

**Comment by Shiwanee** [comment]
Hi @EKranjec,
I would like to take up this issue. Could you please assign it to me?
Thanks,
Shiwanee

**Comment by JayStag** [comment]
@Amruta-Ranade I think I can help with this issue.

**Comment by Amruta-Ranade** [comment]
Addressed in #8532
