### ISSUE TITLE
Change of Default: Range Splits in 20.1

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#7211]
CockroachDB 20.1 changes the default size at which ranges split. We need to make sure the courseware is consistent with this change.

I've already added a lecture note to the video, but we should make it consistent everywhere and create a list of all of the things to change in circumstances like this (lecture notes, possible change of video which we then upload to Learndot as well as YouTube, possibly add a note to the YouTube video, etc).

<img width="1289" alt="lecture-note-range-split-default" src="https://user-images.githubusercontent.com/1966010/80139740-ef8e4380-8574-11ea-80e2-31262d75a4a5.png">

Artifacts that may need to be touched:
- [Lesson: Cluster Concepts: They Keyspace, Ranges, and Replicas](https://university.cockroachlabs.com/admin/e_learning_component/edit/70.html?_http_return_to_url=https%3A%2F%2Funiversity.cockroachlabs.com%2Fadmin%2Fe_learning_component%2Fview%2F70.html)
- [S3 bucket with the .srt and .txt scripts](https://s3.console.aws.amazon.com/s3/buckets/cockroach-university-public/Scripts/?region=us-east-1)
- [The lesson on YouTube](https://youtu.be/LgbrmIjH0cU?list=PL_QaflmEF2e8Prn7r7CIyBKsHPgsgNO_1&t=96)

DoD:
- [x] Add Lecture note to the lesson on Cockroach U
- [ ] Determine whether changes to the video are called for, and generate tickets for those as appropriate.
- [ ] Add a note to the YouTube video
- [ ] Draft a checklist for changes like this and put it into the training wiki
- [ ] Get any changes reviewed by someone on Education

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
