### ISSUE TITLE
Technical Advisory 43870 Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7216]
Re: [Technical Advisory 43870](https://cockroachlabs.com/docs//advisories/a43870.html)

## Issue Description
the following statement does not add user to admin group
`INSERT INTO system.role_members(role, member, "isAdmin") VALUES ('admin', 'someuser', false);`
## Suggested Resolution 
change to:
`INSERT INTO system.role_members(role, member, "isAdmin") VALUES ('admin', 'someuser', true);`

**Comment by dbist** [comment]
@knz FYI

**Comment by knz** [comment]
that's not correct. the `isAdmin` bit is something else entirely - it grants permission to the member to add more members to the role.

Also I think that the entire idea to use INSERT should be removed from the TA and instead using GRANT should be recommended.

**Comment by jseldess** [comment]
Let's loop @taroface in. He updated the main docs about this in the meantime, to use `GRANT` instead, as @knz says. Looks like we just missed this advisory.

However, tech advisories are dated by nature. In the docs, they even have a "Publication date" to correspond with the date on which we send an equivalent communication to customers. I think it's amazing that we've started sending these types of communications, but I'm honestly still conflicted about having them in the docs in this way, given this temporal nature. In this case, for example, do we update the publication date? Do we leave the original date and add an "updated date" or something? 

We don't have to answer these questions right now. @taroface can help update this advisory. But in the future, we should work this out. An alternate approach to publishing dated tech advisories in our docs might be:

1. Documenting the problem as known limitations for the appropriate versions. Perhaps calling them out as severe and production-impacting somehow.
2. Sending a tech advisory email communication.
3. Updating the known limitations when they change. 

Let's think about this more together.

**Comment by dbist** [comment]
just came up in a customer interaction, we should move to `GRANT ADMIN to user` syntax for the entirety of 19.2 and call out that it's available starting with 19.2.6

**Comment by taroface** [comment]
If the `GRANT` syntax is only available from 19.2.6, and this technical advisory specifies "v2.1.10, v19.1.6, and v19.2.2 onward", should the `INSERT` syntax not still apply to earlier versions than 19.2.6?

@jseldess I feel that if we update this TA, we should have an "Updated: [date]" underneath the original publication date.

**Comment by dbist** [comment]
your question is valid. Honestly, at this point I defer to docs how to better go about it. `INSERT` is valid across every version but `GRANT` is more in line with SQL. Maybe adding an update section is best?

**Comment by knz** [comment]
The GRANT is strictly better.
The INSERT solution is not great because it requires to also restart the nodes (to refresh the grant cache). GRANT does not require restarting the nodes.

**Comment by dbist** [comment]
I was not aware of the restart, that clarifies a whole lot. We should call that out in the TA.

**Comment by taroface** [comment]
I'm trying to understand exactly which versions can use `GRANT`. In [this comment](https://github.com/cockroachdb/cockroach/pull/45325#issuecomment-590942574) Raphael told me that it would be backported to 19.1 and 19.2, and I updated both docs versions to use this workaround. 

However, this TA states that the `GRANT` solution applies starting in v19.2.5 and v20..1. @knz which is correct?

Another topic: While we're updating this TA, then perhaps we should also specify that `root` can now use the password `admin` to access the UI in 20.1. The TA references a GitHub issue that has since been closed.

I'm inclined to agree with @jseldess that keeping both a historical list of tech advisories and current known limitations, when the latter (in combination with the CRDB docs) could suffice on its own, introduces potentially confusing overlap _if_ we also want to update the TAs. In this case, the `GRANT` solution is already documented where relevant, and it looks to me like we may need to update/correct multiple sections of the TA.

**Comment by knz** [comment]
> However, this TA states that the GRANT solution applies starting in v19.2.5 and v20..1. @knz which is correct?

The GRANT backport was done independently from the TA edits. It's possible the TA is out-of-date compared to the released product.

@RichardJCai  can you advise Ryan which exact versions of crdb make it possible to use `GRANT admin` without a license?

**Comment by knz** [comment]
>  While we're updating this TA, then perhaps we should also specify that root can now use the password admin to access the UI in 20.1.

This is incorrect. In a default configuration, `root` has no password. The addition of a password for the `root` user must be done manually, at which point the password can be arbitrary.  We *certainly do not recommend using `admin`  as a password*, as that password is terribly unsafe.

(You must be confused with the behavior of `cockroach demo` which offers no security whatsoever and thus can pre-populate a password for `root` without second thought.)

**Comment by taroface** [comment]
I was confused by using `cockroach demo`! Thank you for the correction.

**Comment by RichardJCai** [comment]
> > However, this TA states that the GRANT solution applies starting in v19.2.5 and v20..1. @knz which is correct?
> 
> The GRANT backport was done independently from the TA edits. It's possible the TA is out-of-date compared to the released product.
> 
> @RichardJCai can you advise Ryan which exact versions of crdb make it possible to use `GRANT admin` without a license?

@taroface
I just checked which exact versions support `GRANT admin`, it's correct that 19.2.5 and onward will support it. Also it doesn't seem like any currently released version of 19.1 supports it. It should be supported in the next release(?) of 19.1 so 19.1.9 and onward.

**Comment by dbist** [comment]
> The GRANT is strictly better.
> The INSERT solution is not great because it requires to also restart the nodes (to refresh the grant cache). GRANT does not require restarting the nodes.

@taroface @florence-crl @jseldess I just had a customer on 2.1 run into this issue and after following the original tech advisory they still could not access the privileged information in the UI. Seeing @knz comment, I advised the customer to restart each node and the problem resolved itself. The original tech advisory has correct language but we should add to the advisory that if `INSERT` is followed as advised in the mitigation steps for earlier releases, a reboot is required for grant cache to clear out.
