### ISSUE TITLE
CC: Architecture docs

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#7218]
Based on https://docs.google.com/document/d/1dlxi0_oNhpVPVVU6mq4UMOEFbjf9VPQScVJVS54IcdU/edit

**Comment by Amruta-Ranade** [comment]
From the CC product council: We might want to prioritize it for GA.

**Comment by jseldess** [comment]
Moving this to @rmloveland since it's architecture. @kannanlakshmi, @andy-kimball, eventually, we should plan public-facing docs on the architecture of CC serverless.

**Comment by lnhsingh** [comment]
Duplicated by CC-3695

**Comment by jseldess** [comment]
Closing since this already exists in Jira.
