### ISSUE TITLE
Clarify "Retries" on the Statements console page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7223]
Andy Woods (awoods187) commented:

On the statements page docs we say that `The cumulative number of retries to execute the SQL statement (or multiple statements having the same fingerprint) within the last hour or the specified time interval.`

A customer recently inquired if these were in the database or to the application or both? We should clarify which is the correct answer. 

We should clarify that “Retries” on the Statements page reflect the number of automatic (internal) retries from CockroachDB. [https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#statements-table](https://www.cockroachlabs.com/docs/stable/ui-statements-page.html#statements-table) 

Jira Issue: DOC-499

**Comment by knz** [comment]
Discussed with @timveil  today.
The "retry counter" in the statements page is mis-designed and is bound to become more and more broken as we push users away from using `SAVEPOINT cockroach_restart` to retry transactions.

This should be scrapped entirely and replaced by:

- a counter of how many retry errors have been produced by cockroachdb to the client on that statement key (i.e. count the errors, not the retries)
- how many internal retries were performed

**Comment by dbist** [comment]
saw the same thing, if we recommend against `SAVEPOINT cockroach_restart`, I'd like that sooner than later so that customers don't walk down the rabbit hole. I've spent 3 days digging into it without much success and find this issue after the fact.

**Comment by dbist** [comment]
I recommend to get a consensus on what the right messaging is. From my exploratory analysis, `SAVEPOINT cockroach_restart` is not being advised anymore and my ask is to remove that language from the docs.
