### ISSUE TITLE
Audit CC docs before GA

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#7224]
We should review all our docs pages prior to GA to make sure they are up to date and don't reference beta anywhere. For example, on the CC docs home page it still says "SOC 2 Compliance (in progress)" but we received our Type I report and are able to share it with customers/prospects under NDA.

**Comment by lnhsingh** [comment]
Closing this, since this is being taken care of by the Docs Redesign project that should be going live in a couple of days.
