### ISSUE TITLE
Script for "Updating your Schema"

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7232]
Write a script with the following learning objectives:

- Describe CockroachDB's online schema migration functionality
- Adding a column or taking a column away doesn't ground the DB
- Create an array column
- Evaluate when an array is appropriate

**Comment by SpicyThrow** [comment]
Reviewed draft with Will. Formulating a storyboard.

**Comment by jseldess** [comment]
Training issues are now in Jira. Closing this.
