### ISSUE TITLE
sql: document/explain the missing syntax for ALTER PARTITION OF INDEX

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#7235]
Due to the quirks of the current implementation the syntax `ALTER PARTITION <index_partition_name> OF TABLE <tablename>` should be used, but that is surprising.

What's even more surprising is that all the execution logic is there so there is no obvious reason for asymmetry. It breaks the flow of someone trying to "guess" what they have to do.

There is a technical explanation here of why the syntax does not exist: 8713585c5eb1c42ac21ca9136de0843ef03c554a

(It used to exist previously, and was removed)

This explanation should be propagated to:

- [ ] the interactive help invoked with `\h ALTER`
- [ ] the online documentation

Requested by @robert-s-lee

**Comment by jordanlewis** [comment]
Hi @jseldess, I'm transferring this issue to the docs team. Let me know if that makes sense, thanks!

**Comment by jseldess** [comment]
I think the docs are correct on this now https://www.cockroachlabs.com/docs/v20.2/configure-zone#create-a-replication-zone-for-a-partition. Please reopen if you disagree, @knz.
