### ISSUE TITLE
availability of certain GCP cloud regions language update

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#7237]
"Known issue: In addition to the non-GKE regions, we had to temporarily disable the following 4 GCP regions due to technical limitations that we are actively trying to resolve:"
We say this today, but can we change this to explicitly explain that the restrictions are due to resource constraints by GKE rather than any other technical limitation on the Cloud/ CRL side. This makes it sound like a Cloud issue when its really a resource issue for GCP.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7454/
