### ISSUE TITLE
Revisit help copy for CockroachCloud "create cluster"

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#7238]
It feels like we have too much text in the "Create cluster" page for CC. We overexplain things assuming zero knowledge from our users to the point that the page feels cluttered. Let's revisit this and see if we really need to explain things like "The choice of hardware per node determines the throughput and performance characteristics of your cluster." That particular sentence, for example feels very self explanatory.

**Comment by lnhsingh** [comment]
Closing in favor of CC-3699
