### ISSUE TITLE
fix install methods wrapping problem on install page

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#724]
On the install page, the install methods blocks wrap awkwardly when the window is midway between full-width and tablet-sized. 

See screenshot: 
![screen shot 2016-10-06 at 10 44 28 am](https://cloud.githubusercontent.com/assets/6042450/19157036/f85f3bc4-8bb1-11e6-9001-e91c9d2fc225.png)

**Comment by jseldess** [comment]
This is no longer a problem since we converted the install method buttons to tabs.
