### ISSUE TITLE
search: improper clipping for the search bar

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7253]
We're improperly clipping the display in the search bar for search terms wider than the modal.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/10536690/80745920-07267880-8aef-11ea-9812-e1eae80e1e9a.png">

**Comment by jseldess** [comment]
I think this has been fixed, if I understand this issue right: A search query wider than the box remains there and can be keyed through. @irfansharif, please re-open if you were reporting something different.
