### ISSUE TITLE
sql: document that dropped table descriptors are only deleted after the GC TTL interval

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#7254]
Found while investigating cockroachdb/cockroach#27135 and also in my own cluster while investigating  cockroachdb/cockroach#26983 : `crdb_internal.tables` reports a bunch of tables in state DROP without a valid parent database. These are tables that were created against databases since then deleted.

(See what vivek writes below)

**Comment by jordanlewis** [comment]
Heads up, I'm moving this issue to the docs issue.

**Comment by jseldess** [comment]
cc @ericharmeling, @awoods187 for prioritization.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
