### ISSUE TITLE
List out private cluster settings in docs

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7257]
Re: [Cluster Settings](https://cockroachlabs.com/docs//v20.1/cluster-settings.html)

## Issue Description

Not all cluster settings are present here. `kv.closed_timestamp.target_duration` for example is missing.

**Comment by jseldess** [comment]
@irfansharif, that file is auto-generated by cockroach, and that cluster setting is not included: https://github.com/cockroachdb/cockroach/blob/release-20.1/docs/generated/settings/settings.html. I'm not sure why. Is it classified as a private setting?

**Comment by irfansharif** [comment]
It is a private setting, yep. Sorry for not understanding that we don't list private settings, though I think we should. https://github.com/cockroachdb/docs/issues/7306#issuecomment-625876551.
