### ISSUE TITLE
Search: Lateral doesn't return correct results

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7262]
In 20.1, we added docs on lateral joins:
- https://www.cockroachlabs.com/docs/dev/joins.html#lateral-joins
- https://www.cockroachlabs.com/docs/dev/subqueries.html#lateral-subqueries

However, searching for "lateral" doesn't return these results: https://www.cockroachlabs.com/docs/search.html?query=lateral

And searching for "lateral join" doesn't return any results: https://www.cockroachlabs.com/docs/search.html?query=lateral+join

I suspect it may be because "lateral" in the respective headers is wrapped in `<code>`. This may be a place where we need to tune our indexing.

cc @yingzhuchin, @luciaaaa, @lnhsingh

**Comment by yingzhuchin** [comment]
<img width="1380" alt="Screen Shot 2020-08-05 at 5 28 50 PM" src="https://user-images.githubusercontent.com/63265176/89466053-2281cf00-d741-11ea-99c1-190368e0f782.png">

This appears to have been fixed by one of the search improvements we did in May and June, so I will close the issue now.
