### ISSUE TITLE
Add more caveats around interleaved table usage

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7263]
Right now, our [docs for `INTERLEAVE IN PARENT`](https://www.cockroachlabs.com/docs/dev/interleave-in-parent.html) make it seem like a pure speed win to use interleaving.  They begin with the very inviting paragraph:

> Interleaving tables improves query performance by optimizing the key-value structure of closely related tables, attempting to keep data on the same key-value range if it's likely to be read and written together.

Followed by the encouraging note that:

> Interleaving tables does not affect their behavior within SQL.

Unfortunately, interleaved tables may not provide users with as much of a win as they expect.  They can be faster, but they are not heavily exercised internally, and some have even wondered if they should be marked as "experimental" given the (perceived?) lack of internal focus.

Estimated scope of work from a docs POV here is:

- Make it clear early on in the document that using interleaved tables is not as clear a win as it may seem

- Investigate the existing list of caveats on this page and add to it as needed - for example, there are a number of interleaved table issues [open in the CRDB repo](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen++interleave).

- In particular, we need to document any "footguns" that may exist in the open issues list

This issue is prompted by the recent bugs:

- cockroachdb/cockroach#48280
- cockroachdb/cockroach#48281

**Comment by rmloveland** [comment]
cc @RaduBerinde, @ajwerner
 @awoods187 as SQL PM
and @ericharmeling as SQL Docs maven

**Comment by awoods187** [comment]
I'm a heavy +1 on this line of work. I think most of the challenge of interleaving is determining when it should be used and when it should not

**Comment by ericharmeling** [comment]
We are deprecating interleaved tables in a future release. Closing this for now. Please re-open if needed.

FYI @vy-ton .
