### ISSUE TITLE
Give examples in Cost-Based Optimizer -> Join Hints section

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#7267]
Nathan VanBenschoten (nvanbenschoten) commented:

https://www.cockroachlabs.com/docs/dev/cost-based-optimizer.html#join-hints says a lot of very important information, but it doesn't adhere to our standard practice of also providing examples that readers can copy directly from. After reading the section, I'm aware that join hints exist and why I might use them, but I'm no closer to understanding how to actually use them.

@jseldess for triage.

**Comment by jseldess** [comment]
@ericharmeling, @awoods187, I should've routed this to you long ago. Sorry for the delay.
