### ISSUE TITLE
sql: create one summary page for appdev tooling

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7279]
@BramGruneir points out that our SEs and customers would benefit from one page that highlights all supported tools and as of which versions. We have a much longer-term project to document all of these tools outlined in this [meta issue](https://github.com/cockroachdb/docs/issues/6866), but, until its completed, we could fast track a summary page that lists the tool and the version.

**Comment by awoods187** [comment]
cc @vy-ton and @ericharmeling

**Comment by BramGruneir** [comment]
yay!
