### ISSUE TITLE
Describe physical maximum limits for column names, table names, row width

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7280]
## Title
Describe physical maximum limits for column names, table names, row width

## Description
Describe physical maximum limits for column names, table names, row width

## Expected Audience
developers

**Comment by dbist** [comment]
@jseldess FYI, coming from customer

**Comment by ajwerner** [comment]
With regards to names, in light of cockroachdb/cockroach#48443, we should document that while there is currently no limit, 63 characters is a good guideline and may be enforced in future versions. Longer names will not fundamentally cause a problems especially if the names remain shorter than kilobytes.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/1830.
