### ISSUE TITLE
Self Service Evaluation Document

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/docs#7281]
Chris Casano (chriscasano) commented:

The SE team put together a document that outlines the common items prospect and customer like to evaluate with CockroachDB.  The doc is organized by typical success criteria prospects have as part of their evaluation process with a database.  The goal here is to efficiently enable new users & evaluators to get an evaluation done quickly and accurately.  

[The CockroachDB Evaluations Short Guide - Google Docs.pdf](https://github.com/cockroachdb/docs/files/4581885/The.CockroachDB.Evaluations.Short.Guide.-.Google.Docs.pdf)

**Comment by jseldess** [comment]
Sorry for the extreme triaging delay on this one, @chriscasano.

cc @piyush-singh, @taroface, @mikeCRL
