### ISSUE TITLE
Add an example for filtering on values in JSON columns

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7294]
On this page, https://www.cockroachlabs.com/docs/v19.2/jsonb.html another useful example would be to show how to filter on the values in the key-value pairs. Currently, this page only shows queries against the keys. 

Something like: 

`SELECT id, last_latitude, last_longitude, vehicle_info -> 'wear' FROM vehicles WHERE vehicle_info @> '{"wear":"damaged"}';`

The `@>` is illustrated on the page, but it's unclear that this can be used for filtering on the value.

**Comment by dgabriel123** [comment]
Hey @Amruta-Ranade , I'd like to give this a try. I know JSON pretty well, but I may need some guidance if you have the bandwidth to help me with this. Thanks!

**Comment by Amruta-Ranade** [comment]
I know nothing of JSON 😅.  But give it a try -- we can ask for help if we need it :)

**Comment by dgabriel123** [comment]
> I know nothing of JSON 😅. But give it a try -- we can ask for help if we need it :)

Looking at the issue more, this is definitely more complicated than I expected 😅 I will opt out for now, thanks!

**Comment by vipulgupta2048** [comment]
Hey @Amruta-Ranade saw your post on WTD, I can take this issue up. Will make a PR.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8696
