### ISSUE TITLE
Docs don't work well on narrow windows (Mobile nav)

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7295]
A customer recently posted to [Slack](https://forum.cockroachlabs.com/t/extreme-newbie-demo-in-virtualbox-vm/3659/2) that docs "don't work too well on narrow windows (like on a smartphone, or a browser window that isn't maximized) text in the main body gets cut off and so on."

The new docs site should be optimized for different devices / screen sizes.

**Comment by luciaaaaaaa** [comment]
Taking a look at the site on my phone. Text in main section is responsive, and is not getting cut off for me. Having difficulty exploring the navigation as other options disappear once I select one. See two reference screenshots: 

![IMG_7906](https://user-images.githubusercontent.com/48258790/82483966-3d7c6580-9aa7-11ea-87bb-727106abd7a3.PNG)
![IMG_7907](https://user-images.githubusercontent.com/48258790/82483975-3f462900-9aa7-11ea-8379-bdb1e17b2af6.PNG)

**Comment by luciaaaaaaa** [comment]
also, the version toggle is missing

**Comment by lnhsingh** [comment]
@luciaaaaaaa can you add the Figma links for the mobile nav/layout?

**Comment by luciaaaaaaa** [comment]
Link to designs: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2886%3A530
