### ISSUE TITLE
In-docs interactive tutorials

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7296]
Launch an in-docs interactive CockroachDB sandbox to get developers interacting with our product even before downloading a binary or signing up for CockroachCloud. This will likely leverage the [repl.it](https://repl.it/site/ide) service, with CockroachDB running as an in-memory demo cluster ([example](https://cockroach-demo.jseldess.repl.run/)). 

Each "repl" can have a distinct configuration. That might mean starting a cluster and loading specific data, or it might mean starting a repl for running an app, with all dependencies pre-installed, starting a cluster in a separate repl, and networking the two. This latter approach could be especially cool in ORM tutorials. I need to dig in and experiment.

This should also be considered as part of the Docs UX redesign project lead by @lnhsingh and @luciaaa. Note from @lnhsingh: 
Irfan forwarded a [tweet](https://twitter.com/patrickc/status/1253031147459604482) about [Stripe's experimental tutorial format](https://stripe.com/docs/payments/integration-builder) as an example of where we can go with our own tutorials and code samples/blocks.

**Comment by jseldess** [comment]
Examples:

- Open full-width in a new tab, with the materialize topnav and branding: https://materialize.io/docs/get-started/ (click "Try the demo in your browser")
- Open full-width as an adjustable panel: https://learn.hashicorp.com/tutorials/vault/getting-started-first-secret (click "Show terminal")
- Embedding into main body of docs, with normal sidenav, etc.: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
