### ISSUE TITLE
Fix privileges for SHOW RANGES

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/docs#7297]
Re: [SHOW RANGES](https://cockroachlabs.com/docs//v19.2/show-ranges.html)

## Issue Description

Says that `SHOW RANGES` requires SELECT privileges but when a user has it you get an error: 

```
ron@:26257/system> show ranges from table defaultdb.t1;
pq: only users with the admin role are allowed to read crdb_internal.ranges_no_leases
```

<img width="557" alt="Screen Shot 2020-05-06 at 4 46 12 PM" src="https://user-images.githubusercontent.com/43149297/81226639-2a529b80-8fb9-11ea-8eda-ab862bb67759.png">

## Suggested Resolution 

Clarify that admin role is needed.

**Comment by jseldess** [comment]
Thanks, @roncrdb. Please give this a quick review: https://github.com/cockroachdb/docs/pull/7310
