### ISSUE TITLE
Update CC docs to talk about generic coupon codes

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#7299]
Our docs currently talk about getting codes from sales. We are releasing generic coupon codes for 20.1 that enable free trial without talking to CRL. We should update docs to indicate this by 20.1 if possible. It should be 1-2 sentences here Step 6 herehttps://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-create-your-cluster.html#step-6-enter-your-billing-details

**Comment by kannanlakshmi** [comment]
Another option is to add this to the "Get started" page so its more central and outside of CC.

**Comment by kannanlakshmi** [comment]
Update after talking to @meagan-g 
PMM thinks adding it to the top of the create cluster would be great to get more visibility. Something like "This page walks you through the process of creating a CockroachCloud cluster and beginning a 30-day free trial."

**Comment by meagan-g** [comment]
@kannanlakshmi @Amruta-Ranade if you add that at the top, then i think it could link down to brief instructions on how to use the generic 30-day trial code

**Comment by Amruta-Ranade** [comment]
Eng issue: https://github.com/cockroachlabs/managed-service/issues/2731

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/7454/
