### ISSUE TITLE
Add information to SERIAL docs re: `*serial_normalization` settings

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7300]
We should update [the docs for the `SERIAL` data type](https://www.cockroachlabs.com/docs/stable/serial.html) to mention the following settings:

- `sql.defaults.serial_normalization`
- `experimental_serial_normalization` (NOTE: in v20.2, it is just `serial_normalization`.)

Also, for v20.2, we should remove `experimental_serial_normalization` from the [experimental features](https://www.cockroachlabs.com/docs/stable/experimental-features.html) page.

Related:

- #3630
- #3923

**Comment by rafiss** [comment]
To clarify, the [docs page](https://www.cockroachlabs.com/docs/stable/serial.html) already points to the `experimental_serial_normalization` session variable. But it should also point to the `sql.defaults.serial_normalization` cluster setting.

**Comment by ericharmeling** [comment]
I think all of these are addressed in https://github.com/cockroachdb/docs/pull/9219, https://github.com/cockroachdb/docs/pull/9148, and https://github.com/cockroachdb/docs/pull/10219.
