### ISSUE TITLE
Add a JSON example for querying a nested key value pair

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7301]
Crossman Wilkins commented:

https://www.cockroachlabs.com/docs/v19.2/jsonb.html

On this page, it would be useful to show a query example on a nested key/value pair. 

Something like:

`SELECT id, vehicle_info->'purchase_information'->'purchase_date' `

Jira Issue: DOC-506

**Comment by jseldess** [comment]
Got related feedback from a user:

> Just explain how you select a value from a jsonb that it multiple levels deep into the jsonb structure. Your examples only cover the first level.

**Comment by awoods187** [comment]
We are making other enhancements to using JSON/indexes and i think it'd be nice to enhance this one in 21.1.
