### ISSUE TITLE
Document Jaeger tracing on the Diagnostics page

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7309]
## Description
In 20.1, we're getting additional capability for self-service analysis of statements. There's an option to spin up a Jaeger instance in a Docker container and run tracing analysis of the SQL statements. This will be a welcome addition to our [docs](https://www.cockroachlabs.com/docs/dev/admin-ui-statements-page.html#diagnostics).

Would be good to describe the whole process of collecting the debug zip, spinning up the Jaeger container and tracing an issue with contention. Similar to the Andrei Matei's demo.

**Comment by piyush-singh** [comment]
note this was added in v20.1.1 and is _not_ available in v20.1.0

**Comment by jseldess** [comment]
@piyush-singh, was this on the 20.1 roadmap?

**Comment by taroface** [comment]
@dbist @andreimatei Could one of you point me to the Jaeger demo?

**Comment by piyush-singh** [comment]
@jseldess this wasn't planned for 20.1, I think Andrei managed to squeeze this in as a follow up for 20.1.1. @taroface there are some instructions Andrei added to the trace file itself, and I think the SE team has a recording of the meeting although I can't seem to find it. We can reach out to Keith or Tim to grab a copy. I can also spin up a test cluster using master so that we can try this out.

**Comment by jseldess** [comment]
Thanks, @piyush-singh. 

Also cc @vy-ton, as this is another form of third-party tooling we may want to call out.

**Comment by andreimatei** [comment]
I did a little demo at the Eng Team Meeting on 04/30. @isaactwong said the recording will be here sometime today: https://drive.google.com/drive/folders/1unZIXZIBB1drC7qGlgfkGjUkHUappRsY

**Comment by jseldess** [comment]
Mentioned in the 20.1.1 release notes:

PR: https://github.com/cockroachdb/cockroach/pull/47432

From release notes:
> The [statement diagnostics](../v20.1/admin-ui-statements-page.html#diagnostics) bundle now contains a new file, `trace-jaeger.json`, that can be manually imported in Jaeger for visualization. [#47432][#47432] {% comment %}doc{% endcomment %}

**Comment by vy-ton** [comment]
@piyush-singh @taroface I'm about to merge a revamp of the [Third-Party Database Tools](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ec30290a8bfc2448a2b21f38d54d7c382570c078/v20.1/third-party-database-tools.html) page to include a summary of supported appdev tooling and their recommended versions.

Going forward, thoughts on adding observability tools as a new section? Could the Observability team add this section after the initial PR merges?

**Comment by piyush-singh** [comment]
@vy-ton I think a new section on Observability tool would be great - I think we can include tools and integrations for monitoring/alerting, distributed tracing, and logging. I think having that added as a follow on PR makes sense on my end, but will defer to @taroface on the logistics.

**Comment by taroface** [comment]
Yes, a new PR for Observability tools makes sense to me. @vy-ton is there a GitHub issue attached to your PR? If so, we could use the same.

**Comment by vy-ton** [comment]
Yes, its #7279
