### ISSUE TITLE
Track installs from release notes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#731]
Add google analytics tracking of mac and linux binary downloads from release notes pages.

**Comment by jseldess** [comment]
Create 4 new Tags/Triggers:
- [Mac left click](https://tagmanager.google.com/?hl=en#/container/accounts/180262940/containers/2012025/workspaces/78/tags/77)
- [Mac right click](https://tagmanager.google.com/?hl=en#/container/accounts/180262940/containers/2012025/workspaces/78/tags/79)
- [Linux left click](https://tagmanager.google.com/?hl=en#/container/accounts/180262940/containers/2012025/workspaces/78/tags/78)
- [Linux right click](https://tagmanager.google.com/?hl=en#/container/accounts/180262940/containers/2012025/workspaces/78/tags/80)

Repurposed two old/unused GA goals:
- [install-mac-release-notes](https://analytics.google.com/analytics/web/#management/Settings/a63775601w99440101p119439298/%3Fm.page%3DGoals%26m-content-goalList.rowShow%3D10%26m-content-goalList.rowStart%3D0%26m-content-goalList.sortColumnId%3Dconversions%26m-content-goalList.sortDescending%3Dfalse%26m-content.mode%3DEDIT%26m-content.goalId%3D33084526/)
- [install-linux-release-notes]( https://analytics.google.com/analytics/web/#management/Settings/a63775601w99440101p119439298/%3Fm.page%3DGoals%26m-content-goalList.rowShow%3D10%26m-content-goalList.rowStart%3D0%26m-content-goalList.sortColumnId%3Dconversions%26m-content-goalList.sortDescending%3Dfalse%26m-content.mode%3DEDIT%26m-content.goalId%3D32979789/)

Added corresponding `data-eventcategory` attributes to the `beta-20160929` release notes, for testing: https://github.com/cockroachdb/docs/pull/730

**Comment by jseldess** [comment]
@eballeste, I'm not seeing the expected events or goal completions in GA, and I'm not sure what I've done wrong. When you have time, would you take a look at the above (tag/trigger setup, goal setup, and `data-eventcategory` attributes on the page) and help me find the error(s)?

**Comment by eballeste** [comment]
@jseldess, looking into it

**Comment by eballeste** [comment]
@jseldess

If you were trying to fix the anchor tag not registering the click event, the fix would be to set the trigger to **Just Links**. However, you are also trying to register the context menu, right-click event which is being hijacked by the button inside of the anchor tag. 

My recommendation is to set the `data-eventcategory` attribute to the button and removing it from its parent anchor tag. In GTM, the trigger should be left, as is, on **All Elements**. 

`<a href="https://binaries.cockroachdb.com/cockroach-beta-20160929.darwin-10.9-amd64.tgz"><button id="mac" data-eventcategory="mac-binary-release-notes">Mac</button></a>`. 

This will ensure that both left and right click events are registered.

**Comment by jseldess** [comment]
Thanks, @eballeste. I'll try that.

**Comment by jseldess** [comment]
@eballeste, I push out that change. When I look at install-linux-release-notes and install-mac-release-notes on Conversions > Overview in GA, I now see 2 events for the install-mac-release-notes goal. But I've left/right clicked more than that, also on the linux button, since pushing this change. So something still seems off. Also, the events still aren't showing up in the Real Time > Events feed. 

Perhaps I just need to wait a bit longer?

**Comment by eballeste** [comment]
![screen shot 2016-10-07 at 5 57 13 pm](https://cloud.githubusercontent.com/assets/6924108/19206590/ed7ddfa6-8cb7-11e6-89a3-f45853e4e642.png)

@jseldess it seems to be working, I did a quick test and was able to see 4 right clicks + 1 left click in real time. I was informed that the goals however are not in real time and might take some time to reflect.

**Comment by jseldess** [comment]
Great. Thanks, @eballeste!

**Comment by jseldess** [comment]
@jess-edwards, this looks to be working now, so I updated all past release notes pages. Let me know if you see problems.
