### ISSUE TITLE
Technical Advisory: Document issue 48860

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7330]
https://docs.google.com/document/d/1dG954t74RaYfas_zUJxFWuJ0j0JKVKMALEKB6N8x5p0/edit?ts=5ebd9f7a

**Comment by jseldess** [comment]
@taroface, sorry to toss this over to you with such short noticed, but we need to add this to the docs soon after 19.1.7 is released, and that is scheduled for Monday.
