### ISSUE TITLE
where can I get Railroad.jar

### ISSUE THREAD

**Issue by XuHuaiyu** [cockroachdb/docs#734]
hi, all
When I run "go run main.go" in ./generate/, I got error message "column_def: exit status 1: Error: Unable to access jarfile Railroad.jar", what should I do now?

P.S.:yyextract is mentioned to convert a yacc file into EBNF format in this article (https://www.cockroachlabs.com/blog/efficient-documentation-using-sql-grammar-diagrams/), can I run yyextract on Mac?

**Comment by jseldess** [comment]
@mjibson, can you chime in here?

**Comment by mjibson** [comment]
Sadly we are not able to provide this file to non-employees. Use `go run main.go -railroad ''` to use the web service instead.

**Comment by XuHuaiyu** [comment]
@mjibson 
Thank you
Sorry to bother you again, but when I run this command in ./generate/, I still got error message
>"Error: unknown shorthand flag: 'r' in -railroad"

**Comment by mjibson** [comment]
Oops, `--railroad`.
