### ISSUE TITLE
Add Django-specific instructions to the "connect to your cluster" doc

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#7350]
Add connection instructions for a Django app to https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html#use-a-postgres-driver-or-orm

**Comment by pallavithakare28** [comment]
Hey @Amruta-Ranade, I would like to work on this issue.

**Comment by Amruta-Ranade** [comment]
Oh, I already added the link in the See Also section but forgot to close the issue. Sorry!

**Comment by pallavithakare28** [comment]
@Amruta-Ranade Sorry I didn't notice, I am new to open source contribution and looking forward to contribute on cockroachdb issue.

**Comment by Amruta-Ranade** [comment]
No worries! We still have some Hacktoberfest issues open: https://github.com/cockroachdb/docs/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest
