### ISSUE TITLE
"Beyond Hello World" sample applications

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7353]
We currently have very basic "Hello World" apps for 

For developer education, we should provide more complex, idiomatic sample applications built on CockroachDB. Each sample app should have an accompanying end-to-end tutorial. For example, [flask-sqlalchemy tutorial](https://github.com/cockroachdb/examples-python/tree/master/flask-sqlalchemy) and its [https://www.cockroachlabs.com/docs/cockroachcloud/stable/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html).

The apps would be available for download/clone in a forkable repo. The tutorials would be available on our documentation website, in [the ToC under "Develop"](https://www.cockroachlabs.com/docs/stable/developer-guide-overview.html)->"Sample Applications", or something to that effect.

Here is a list of languages/frameworks we should prioritize:

- [x] Java/Spring Boot
- [ ] Python/Django
- [ ] Ruby on Rails

**Comment by vy-ton** [comment]
Let's keep this tracking issue for now, but eventually we can close this in favor of the actual applications we want to prioritize

**Comment by vy-ton** [comment]
@ericharmeling Thoughts on closing this
