### ISSUE TITLE
Documentation for HTTP endpoints

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#7357]
We are seeing more and more requests from customers for documentation to understand what data is contained in our HTTP endpoints so that they can consume that information in scripted actions. 

One customer was asking whether our hot range endpoints' QPS metric includes read data only, or reads and writes, so that they could root cause hotspotting in a test cluster. @timveil has been running into issues when trying to consume this information for his dogfooding project because he isn't sure what is available and where to access which metrics. Tim also pointed out that the JSON outputs can be formatted in an unintuitive way for consumption outside of our UI. Finally, @florence-crl was surprised to see nodes' CLI startup flags in one of our JSON endpoints, and asked that we document what is available so the support team can make full use of the available data (it is awkward and almost impossible to find what is in there today).

This will likely be a huge project. We will probably want to work out a strategy for adding docs on these endpoints over time, and we may even want to work on some system of automation so that we do not have to manually edit our docs every time we make adjustments to any of these API endpoints. Realistically, I think documenting a single endpoint to start would help us understand how this will work going forward.

Some things to consider:
- Which endpoints are highest priority to document? Telemetry may help us identify these somewhat, however, production endpoint usage may differ from non-prod usage, and our customers tend to disable telemetry in prod. We can also survey our customers for which docs they are most interested in via our community slack, forum, or twitter. We could also add links to documentation in the UI for each endpoint and put placeholder pages on our docs site for each of them and track clicks through to the docs pages to gauge demand.
- If we partially document these pages, how will we indicate that a page is undocumented in our docs site?
- If we start documenting these fields, does it make sense to make changes to response formats now (based on Tim's and customers' feedback)? Would we expect these endpoints to change substantially in the future? How will we handle docs for changes?

cc @taroface and @dhartunian

**Comment by jseldess** [comment]
This is a great project, but I agree it's large and requires a lot of thought both on the eng and docs side. If we document these endpoints, they should be stable, for example, and I agree we should automate api docs as much as possible. I'll mark this is a docs project for 20.2, but it might just be a planning project.

**Comment by jseldess** [comment]
+1 on piloting docs on a single endpoint to start.

**Comment by dhartunian** [comment]
Node status endpoint might be a good place to start.
http://localhost:8080/_status/nodes

I'm also unsure of how "usable" the current endpoints are. How do we decide between carefully documenting a complex endpoint not designed for public consumption and creating a more usable endpoint that's easy to document?

**Comment by jseldess** [comment]
I think you raise a good point, @dhartunian. We really shouldn't document any endpoint that we don't feel confident in and that we're not committed to stabilizing for external usage. @piyush-singh, I wonder if this needs to first be a PM/Eng discussion? If we are confident in one or two endpoints and we want to start a pilot, though, that's fine by me.

**Comment by piyush-singh** [comment]
> I'm also unsure of how "usable" the current endpoints are. How do we decide between carefully documenting a complex endpoint not designed for public consumption and creating a more usable endpoint that's easy to document?

Agree this is worth some thought. We can work with our users/customers to see how they consume any endpoints as part of automation today and we can ask about the largest or most frequent issues with consuming data that way. I have a few customers in mind that I think would be happy to work with us to improve this. 

I think the KV team is actually updating how the node health/status endpoints are checked under the hood to better support rolling restarts and upgrades for 20.2 (see cockroachdb/cockroach#44206). Because we are making a change here anyways, I think this could be a great candidate as our first endpoint to document. cc @johnrk in case there are already plans on the KV side for docs and for deployments overlap

In terms of policy for how we approach documenting and stabilizing external APIs, I think we are still in the early days of defining that. Raphael had some thoughts that he collected and proposed as a docs PR in #4326. We can test out ideas for process with a single endpoint to start and iterate from there.

**Comment by knz** [comment]
A better example starting point would be the health endpoint.

(We don't really want to document node status because some of the things it returns are unstable.)

As discussed with Piyush today, providing the information about the endpoints could be a good deliverable for the "dev interfaces" community service team.

**Comment by jseldess** [comment]
Working with dev interfaces sounds great to me. I also would love for us to put thought into automation here, to some extent, even if longer term. Depending on the nature of these endpoints, we might want to consider tools like [swagger](https://swagger.io/), for example.

**Comment by knz** [comment]
Yes automation is top of mind for me as well. The two hard requirements I have are the following:

1. the primary source of the technical content, where the semantics of APIs are defined, must be expressed close in the source code to where the API code is written. This is because otherwise there's no incentive for engineers to keep it up to date. This probably mandates some special syntax in function comments.

2. all these doc strings must be mined automatically for further processing by docs.

**Comment by taroface** [comment]
cc @dhartunian 

David, what do you estimate the workload would be for us to adopt a tool like swagger to generate API docs for these endpoints? Two notes from a docs perspective:

- In my previous encounters with swagger, at least, I've found the generated reference pages hard to edit and not well integrated with docs sites (swagger pages had to open in separate tabs with different formatting). Ideally an automation tool would allow us to customize the output to match our usual docs.
- It would ideally be straightforward to edit endpoint and parameter descriptions directly.

**Comment by dhartunian** [comment]
@taroface I've successfully generated swagger definitions for our Admin UI endpoints before just to see if it was possible. I agree they're a bit tough to embed/modify.

I think the smoothest course of action will be for us to generate swagger JSON (like in the example here https://editor.swagger.io/) and then modify manually if you want to add your own data or remove endpoints we don't want to publish docs for yet.

Here's an example. Let me know if that's a good place to start:
https://gist.github.com/dhartunian/3bb3652dde2f405441d714a2393f0edd

I think the output is compatible with OpenAPI and can use generators listed here https://openapi-generator.tech/docs/generators#documentation-generators. See if any of those could meet our needs.

You can paste it into the editor link above and then browse the generated doc.

**Comment by knz** [comment]
So in practice there are 3 things to consider:

1) the filter on whether to document something or not is not on endpoints (URLs) but instead individual fields inside request and response objects. Can Swagger do this? 

   (If not, we'd need to create a shadow API definition inside CockroachDB which only exposes those particular fields that we want to document. I wonder if that expense would be affordable compared to e.g. writing our own JSON generator.)

2) we need to delineate a boundary between things that we can explain but don't want to support, and things that we can both explain and also where we provide a support guarantee. What would be a good way to express this difference? 

  (Again, this boundary can be per field in request/response objects, not just per endpoint.)

3) From an engineering process perspective, it's rather important that the documentation and guarantees offered for various endpoints are close in the code to their implementation. The reason for this is to ensure that a future maintainer that perform changes is careful to either preserve the preserved guarantees, or update the documentation, or both.


A direction that Peter and I were considering was to provide these nuances as protobuf field annotations, and then use the field annotations in a documentation generator (based off the protobuf library). Can Swagger read and automate the processing of protobuf field annotations?

**Comment by taroface** [comment]
Protobuf -> Docs template is at https://github.com/cockroachdb/cockroach/pull/51803

**Comment by jseldess** [comment]
FYI, @mikeCRL, this is the issue about documenting http endpoints from last release.

**Comment by jseldess** [comment]
I believe @mikeCRL's api doc work for 21.1 resolves this issue. Please re-open if that's not right.
