### ISSUE TITLE
Document process for building an integration with Snowflake for Looker

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7361]
- [x] Research the process for building an integration with Snowflake for the purpose of Looker. Supported by https://github.com/cockroachdb/docs/issues/7241
- [x] Document how the above works, with general steps and best practices that other engineers can follow, on our Product wiki (location TBD).

cc @katedoebler

**Comment by yingzhuchin** [comment]
So sorry, I forgot there's already a ticket open for the work.

The documentation is here: https://cockroachlabs.atlassian.net/wiki/spaces/PROD/pages/579305473/Suggested+Steps+For+Looker+ETL+Projects

Please let me know if you'd like me to move it into a different space within Product wiki.
