### ISSUE TITLE
Wrong default value of range_min_bytes and range_max_bytes

### ISSUE THREAD

**Issue by kota2and3kan** [cockroachdb/docs#7367]
Re: [Configure Replication Zones](https://cockroachlabs.com/docs//v20.1/configure-replication-zones.html)

## Issue Description
In CockroachDB v20.1, it seems that the default range size is changed from 64/16 MB to 512/128 MB.
https://github.com/cockroachdb/cockroach/commit/660b3e7e0d05d31ab1cf6ec001f6f5121bd20fa6

However, in the Replication zone variables section of configure-replication-zones.html, it seems that the docs states the default value of range_min_bytes is '`16777216` (16MiB)'.

And, docs states the default value of range_max_bytes is '`67108864` (512MiB)'. (512MiB is correct, but it looks like the bytes 67108864 is incorrect.)

## Suggested Resolution
I think that the docs should state the default values like the following.

- range_min_bytes is '`134217728` (128MiB)'.
- range_max_bytes is '`536870912` (512MiB)'.

**Comment by jseldess** [comment]
Thanks for catching this, @kota2and3kan! We'll get this corrected soon.
