### ISSUE TITLE
Node Decommissioning Doc Update 

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7375]
(Looking at https://cockroachlabs.com/docs//v20.1/training/node-decommissioning.html)

Flag --decommission has been deprecated, we should update our docs to use 'cockroach node decommission' then 'cockroach quit' instead.

**Comment by jseldess** [comment]
Thanks, @irfansharif. This is in progress. @taroface will wrap it up once he's back from vacation. https://github.com/cockroachdb/docs/pull/7304
