### ISSUE TITLE
Assemble certification resources

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7377]
## Certification programs

**Open Source Computing Foundation**
- Kubernetes Admin Certification
    - [Overview](https://www.cncf.io/certification/cka/)
    - [Exam Curriculum](https://github.com/cncf/curriculum/blob/master/CKA_Curriculum_V1.18.pdf)
- Kubernetes Application Developer Certification
    - [Overview](https://www.cncf.io/certification/ckad/)
    - [Exam Curriculum](https://github.com/cncf/curriculum/blob/master/CKAD_Curriculum_V1.18.pdf)

**HashiCorp**
- Terraform Certification (Infrastructure Automation)
    - [Overview](https://www.hashicorp.com/certification/terraform-associate/)
    - [Study guide/curriculum path](https://learn.hashicorp.com/terraform/certification/terraform-associate-study-guide)
    - [Review guide](https://learn.hashicorp.com/terraform/certification/terraform-associate-review)
- Vault Certification (Security Automation )
    - [Overview](https://www.hashicorp.com/certification/vault-associate/)
    - [Study guide/Curriculum path](https://learn.hashicorp.com/vault/certification/vault-associate#study-guide)
    - [Review guide](https://learn.hashicorp.com/vault/certification/vault-associate#review-guide)

**MongoDB**
- Developer Certification
    - [Overview](https://university.mongodb.com/certification/developer/about)
    - [Study guide](https://university.mongodb.com/exam/guide)
- DBA Certification
    - [Overview](https://university.mongodb.com/certification/dba/about)
    - Study guide (same as above)

## Internal resources

**Customer Success**
- [New hire technical onboarding](https://drive.google.com/drive/u/0/folders/1V6Nbc-73d6Pn6D7vLz3lPM8pM8uqjmQk)
- [Health check index (operator best practices)](https://docs.google.com/spreadsheets/d/1g5kiX3FIZ2V64BsvNsOjYuu1Adab2WmJlaZbFzH34w8/edit#gid=1500191980)
- [Advanced Developer workshop](https://cockroachlabs.atlassian.net/wiki/spaces/CS/pages/188645434/Advanced+Developer+Workshop)

**Sales Engineering**
- [Developer workshop](https://docs.google.com/presentation/d/15CAJNKVjn7wYX-hEQHFVi7MDuWUSuLbHEWg5ze73ULA/edit#slide=id.g5dc5a76470_0_250)
- [Q&A](https://docs.google.com/document/d/1F4g7ObMqc7bhb-LOPvX2XH7mHPfzcaOleOvo3UWexSk/edit?ts=5ecf0100#)

**Training**
- Getting Started with CockroachDB
    - [Course on Cockroach U](https://university.cockroachlabs.com/course/getting-started-with-cockroachdb)
    - [Lesson plan](https://docs.google.com/spreadsheets/d/18kQEN9QpZ4JnAoMPpNH8elrVMY-NRse1CEAAnwNN438/edit#gid=0)
- CockroachDB for Python Developers
    - [Course overview](https://docs.google.com/document/d/1ad1IbdvwxfTidACYG9-zdAfMEfW6TFCBlSn3S4wM5QY/edit#heading=h.v3stgeo4xxs3)
    - [Lesson plan](https://docs.google.com/spreadsheets/d/1xU6YPODxyMM6h_gH1UUl98RmoHzoIKwilnGW0hqEV5I/edit#gid=0)

**Comment by thatnerd** [comment]
*Cloudera*
- [Cloudera Certification](https://www.cloudera.com/about/training/certification.html)
- Has Developer & DBA certification programs
- Focused on very "realistic" hands-on exercises, but still had some flaws
- Difficult to update
