### ISSUE TITLE
Better motivate usage of `recommissioning` nodes

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7384]
Looking at https://cockroachlabs.com/docs//v20.1/remove-nodes.html, it's unclear to me what the real motivation is for using recommissioning. See this [internal](https://cockroachlabs.slack.com/archives/CA8H95NUU/p1590087247056500) thread for some discussion on the matter.

Specifically, it's unclear what's the benefit of recommissioning a fully decommissioned node, instead of starting afresh. I don't think there is any, aside from re-using NodeIDs, which I'd assume as an operator, I wouldn't much care for. Yet, our only [example](https://www.cockroachlabs.com/docs/stable/remove-nodes.html#recommission-nodes) for recommissioning a node is resurrecting a fully decommissioned node. I think the real motivation for having this recommissioning thing is to have an out of bound cancellation + undo mechanism for an ongoing decommissioning process.

**Comment by irfansharif** [comment]
(I just spammed the labels that seem appropriate here - I'm probably off)

**Comment by irfansharif** [comment]
I'll bump again for https://github.com/cockroachdb/docs/issues/6476, which I keep getting confused by.

**Comment by taroface** [comment]
Relates & will be addressed with #6935.
