### ISSUE TITLE
Add example of creating computed column from nested JSON

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7389]
Crossman Wilkins commented:

Re: [Computed Columns](https://cockroachlabs.com/docs//v20.1/computed-columns.html)

## Issue Description

An example for creating a computed column from nested JSON would be helpful. The syntax isn't immediately intuitive.

## Suggested Resolution 

Add something like:
`alter table vehicles add column purchase_date string as (vehicle_info->'purchase_information'->>'purchase_date') STORED;`

Jira Issue: DOC-519

**Comment by awoods187** [comment]
Bumping this up since its the primary way people use indexes in production. This can be potentially downgraded if expression-based indexes lands in 21.1.
