### ISSUE TITLE
Consistent size recommendations for STRING and BYTES

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#7395]
The [string](https://www.cockroachlabs.com/docs/stable/string.html) docs recommend that values be kept under 64KB while the [bytes](https://www.cockroachlabs.com/docs/stable/bytes.html) docs recommend up to 1 MB. The underlying implementation is the same, so there's no reason I can see for the limits to be so different here. I would update the string docs to the higher limit. (Actually the advice I've always given is to keep the total row size under 1 MB, regardless of how that data is distributed across columns)

**Comment by jseldess** [comment]
@ericharmeling, @rmloveland, who wants to take this one?

**Comment by rmloveland** [comment]
snagged it

**Comment by rmloveland** [comment]
@bdarnell is it possible that the `DECIMAL` data type also needs this update?

Asking because it's the only other use of the string "keep values under 64 kilobytes to ensure performance" in the docs, so it stuck out.

**Comment by bdarnell** [comment]
Probably? That language does look like it was copied from the string docs and so the same rationale would apply for updating it. But 64KB is already an awful lot of number, and it sounds ridiculous to my ears to talk about numbers in terms of kilobytes and megabytes. I think it may be better to set a limit on the precision and scale parameters instead of allowing true arbitrary precision. [Postgres, for example, has limits](https://www.postgresql.org/docs/10/datatype-numeric.html) that imply an upper bound of no more than a couple hundred KB for the size of their decimal type. If we used the same limits we wouldn't need a separate disclaimer about data size. 

@mjibson, any thoughts?

**Comment by mjibson** [comment]
While I think this is a theoretical problem for our decimals, I think it's a distraction to put it in the docs. But if you want to account for certain users doing edge-case things, then I guess? I'd just leave it out.

**Comment by rmloveland** [comment]
Got it, thanks Matt.  PR incoming for STRING and BYTES
