### ISSUE TITLE
Separate section about how we authenticate third party "tools"?

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#7398]
Michael Wang (mwang1026) commented:

I think it'd be valuable for searchability and whatnot to extract the subsection we have about how to `AUTH` to GCS, S3, etc. into their own docs. Today they're buried as footnotes within each of the docs where 3rd party auth is necessary.

I'm not 100% sold on this but wanted to get a conversation started. This will only grow as we grow our list of 3rd party connections (Kafka, Confluent and certs, other CDC sinks etc.)

Thoughts welcome! cc @piyush-singh @thtruo since there are some security implications here

**Comment by lnhsingh** [comment]
Semi-related feedback we got on the BACKUP docs: backup whole cluster to GCS bucket but no information how to pass ServiceAccount to access the GCS bucket
