### ISSUE TITLE
20.1.0 Incorrect default for range_max_bytes

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#7400]
On this page https://www.cockroachlabs.com/docs/v20.1/configure-zone.html#variables
<img width="693" alt="Screen Shot 2020-05-26 at 3 06 18 PM" src="https://user-images.githubusercontent.com/58752716/82940339-aad63d80-9f62-11ea-8ceb-18d40f207e79.png">
is incorrectly:
```
Default: 67108864 (512 MiB)
```

Should be
```
Default: 536870912 (512 MiB)
```

**Comment by jseldess** [comment]
Thanks, @florence-crl. We're tracking this in another issue, so I'll close this as a duplicate. https://github.com/cockroachdb/docs/issues/7367
