### ISSUE TITLE
release-20.1: cli/zip: misc fixes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7417]
PR: https://github.com/cockroachdb/cockroach/pull/48094

From release notes:
> [`cockroach debug zip`](../v20.1/cockroach-debug-zip.html) now tries multiple times to retrieve data using SQL if it encounters retry errors and skips over fully decommissioned nodes. It also supports two command-line parameters `--nodes` and `--exclude-nodes`. When specified, they control which nodes are inspected when gathering the data. This makes it possible to focus on a group of nodes of interest in a large cluster, or to exclude nodes that `cockroach debug zip` would have trouble reaching otherwise. Both flags accept a list of individual node IDs or ranges of node IDs, e.g. `--nodes=1,10,13-15`. [#48094][#48094] {% comment %}doc{% endcomment %}
>
> The copy of `system` and `crdb_internal` tables extracted by [`cockroach debug zip`](../v20.1/cockroach-debug-zip.html) is now written using the `TSV` format (inside the .zip file), instead of an ASCII-art table. [#48094][#48094] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as `--nodes` and `--exclude-nodes` have already been documented, and I think the rest don't require documentation.

**Comment by taroface** [comment]
Reopening because I realized this is for a v20.1 backport!
