### ISSUE TITLE
release-20.1: cli: Support cluster name flags in all non-sql client commands

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7418]
PR: https://github.com/cockroachdb/cockroach/pull/48016

From release notes:
> Client commands such as [`cockroach init`](../v20.1/cockroach-init.html) and [`cockroach quit`](../v20.1/cockroach-quit.html) now support the `--cluster-name` and `--disable-cluster-name-verification` flags in order to support running them on clusters that have been configured to use a cluster name. Previously it was impossible to run such commands against nodes configured with the `--cluster-name` flag. [#48016][#48016] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Duplicates #7649.
