### ISSUE TITLE
release-20.1: cli: Resolve past engine type correctly with encryption-at-rest

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7425]
PR: https://github.com/cockroachdb/cockroach/pull/49073

From release notes:
> Made `--storage-engine` sticky (i.e. resolve to the last used engine type when unspecified) even when specified stores are encrypted at rest. [#49073][#49073] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
closing. bug fix.
