### ISSUE TITLE
Update lavish bootstrap

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#743]
During research into why #719 happened, I found some problems. In a recent commit I removed bootstrap.css because we were already including lavish-bootstrap.css. Lavish is a site that generates a bootstrap file based on some colors, but otherwise it is identical to the stock bootsrap. We generated our lavish from an old 3.0.X version of bootstrap, but were including bootstrap 3.3.4. This meant that any changes in bootstrap from 3.0 to 3.3.4 were not in our lavish file. Hence when we removed the stock bootstrap from the CSS includes, some things like this broke (maybe others too that we have not yet found).

The correct fix for this is to regenerate our lavish file. However I don't know the colors it was originally generated with. We could find this out with a small amount of effort.

But there's a larger problem because people have been editing our lavish-bootstrap file with random additions. Ideally our lavish-bootstrap file will remain unchanged from the generator, and any additions or changes we want to make will be in customstyles.css. This will allow us to upgrade the lavish file without stomping on the other various change we've made over time.

This is a larger effort and maybe not worth the trouble now. Just putting the issue here so we are aware of what the current state is.

**Comment by jseldess** [comment]
A larger questions is whether we should do a large-scale refactor of our CSS, which probably has a lot of legacy and inconsistent details. @petervandivier, it'd be great if you could eventually partner with our new Prod Ops Eng to assess this.

**Comment by petervandivier** [comment]
@jseldess - typo’d `@` I think

**Comment by jseldess** [comment]
Sorry @petervandivier. I meant @anagio.

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
