### ISSUE TITLE
Stop building old training pages

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7432]
People keep finding our old training pages, and we should delete them.  AFAIK nobody is maintaining or updating them anymore.

I did find [a PR to remove them from search results](https://github.com/cockroachdb/docs/pull/7409) but I think we should delete them altogether instead.

Since they are in our git history, we can always resurrect anything we need in there later.

But as usual, perhaps there is something I don't understand here. :-)  Do we keep these old training pages around because something important links to them?

**Comment by jseldess** [comment]
Copying related thread from Slack:

> I’m sorry for this confusion. I thought Google was ignoring those pages, but just yesterday opened a PR to make that happen: https://github.com/cockroachdb/docs/pull/7409
>
> I have been delaying removing these from the site because some field teams were still pointing people there directly. I also don’t want to delete the pages as some of them should really be converted to how-tos in our official docs. I’d rather stop building them for now.
...
> I’ve asked the field teams if they still use those pages or point customers there. If not, we can stop building them, at least, for now.
