### ISSUE TITLE
cockroach start Doc Update 

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/docs#7436]
Re: [cockroach start](https://cockroachlabs.com/docs//v20.1/cockroach-start.html)
cockroach start page still doesn't describe how and when to set the --sql-addr flag to use a separate SQL port from the RPC port.

## Issue Description
https://github.com/cockroachdb/cockroach/issues/30828
https://www.cockroachlabs.com/docs/releases/v19.2.0-beta.20190930.html
## Suggested Resolution 
Add the description of this flag to the docs for cockroach start

**Comment by jseldess** [comment]
This is a known docs gap from 19.2. It's on @Amruta-Ranade's backlog: https://github.com/cockroachdb/docs/issues/4771. Amruta, we should look at adding docs on the flags at a minimum, even if we don't adapt any examples/tutorials.
