### ISSUE TITLE
Licensing FAQs Doc Update 

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#7438]
Re: [Licensing FAQs](https://cockroachlabs.com/docs//v20.1/licensing-faqs.html)

## Issue Description

20.1 is not listed in the table of releases

## Suggested Resolution 

Add 20.1 to this page, and add a task to update this page to the checklist for each major release. 

Alternately, this page "Licensing FAQs" seems like an awkward place to have as the reference for licenses and change dates. Maybe we should remove the table from this page and add it to the "all releases" table. Or just give people instructions about how to find the date in the file `licenses/BSL.txt` from whichever version they're using.

**Comment by jseldess** [comment]
cc @piyush-singh

**Comment by gemma-shay** [comment]
Resolved by #9338.
