### ISSUE TITLE
License summary in main repo README.md

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#7441]
We should have a clear summary of our licenses in the main repo's README.md. See cockroachdb/cockroach#49615 for an external contributor's take on this. It's a good start, but I think it needs some work to clarify that each release is under two licenses (not three) and emphasize the current state instead of starting with the old 19.1 releases. (The main audience for the github readme is potential contributors who need to understand the license terms for the repo they're contributing to).

**Comment by jseldess** [comment]
cc @piyush-singh
