### ISSUE TITLE
cluster setting mentioned in one page and not another

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/docs#7452]
In https://www.cockroachlabs.com/docs/stable/show-jobs.html we mention the cluster setting `jobs.retention_time` and even link to the cluster settings page.
But on the cluster settings page, there is no mention of this setting.

What's going on?

**Comment by mattcrdb** [comment]
I had some discussion about this [here](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1590680300449300)

**Comment by johnrk** [comment]
@BramGruneir , do you think that cluster setting should be recategorized as public? In 20.1 ([categorized public/non-public cluster settings](https://github.com/cockroachdb/cockroach/pull/42520)), we defined that one as non-public and intentionally have hidden that from our public docs to discourage  users from using settings that are not intended to be changed.

**Comment by BramGruneir** [comment]
Yes.  I think so.  Since we refer to it and suggest people adjust it.

**Comment by johnrk** [comment]
Sounds good. Let's change it then.
