### ISSUE TITLE
Fix wording in Backups around full cluster backups

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/docs#7469]
https://www.cockroachlabs.com/docs/stable/backup.html#parameters

Currently this note exists:

> Note: It is not possible to create an incremental backup if one or more tables were created, dropped, or truncated after the full backup. In this case, you must create a new full backup.

This is not the case when using full cluster backups and needs to be fixed.  At least as an immediate fix.

However, longer team, this whole section should be split up into either multiple pages or some type of selector at the top, as full backup is significantly different than one off, and this is only going to get even more complicated with the backup jobs coming in 20.2.  I'm more inclined to go with a different strategy altogether, about what the user's intent is.  And of course, this will have to be mirrored with restore documentation as well.  And we know that restoring a full cluster backup has special requirements that need to be more explicit.

**Comment by lnhsingh** [comment]
Slack convo here: https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1591128831064600 for ideas on how to split this in the future.
