### ISSUE TITLE
Add in FAQs or "create cluster" pricing page that we do not charge for data transfer costs

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#7470]
We get this question a lot on CockroachCloud - do we charge separately for data costs. The answer is we don't but we should explicitly say that, maybe under "FAQs"? https://cockroachlabs.slack.com/archives/CBE9QQC4S/p1591278383299000

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8045
