### ISSUE TITLE
Document bug upgrading from 19.2 to 20.1.x breaks an Admin UI page

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/docs#7481]
See https://github.com/cockroachdb/cockroach/issues/49882

This bug affects anyone upgrading from 19.2 to 20.1.0, 20.1.1, or 20.1.2 -- even if they aren't doing schema changes during the upgrade.

**Comment by jseldess** [comment]
Passing to @taroface and @piyush-singh for prioritization. Since I've handled upgrade docs recently, let me know if you want me to take this.
