### ISSUE TITLE
19.1 Start a Local Cluster (Insecure) is missing initialization step

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7499]
Re: [Start a Local Cluster (Insecure)](https://cockroachlabs.com/docs//v19.1/start-a-local-cluster.html)
these instructions are missing initialize a cluster step

## Issue Description
missing init steps

## Suggested Resolution 
add steps similar to 19.2.7

**Comment by jseldess** [comment]
Actually, the 19.1 tutorial starts the first node without the `--join` flag, which implicitly initializes the cluster. This was still accepted in 19.1. Nonetheless, I'll adapt this to send a consistent message.

**Comment by jseldess** [comment]
On further thought, this isn't worth the time right now relative to other work, and as of 11/20, 19.1 will be EOL. If you see this causing confusion for customers, please reopen this, @dbist.
