### ISSUE TITLE
Enable remote file includes in jekyll build

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7500]
Related to #7066. 

Jekyll [requires all included files to be local](https://jekyllrb.com/docs/includes/). We should look into make a custom plugin that enables including remote files. This would make including code samples from external repos (with automated testing!) possible

Here is a discussion on this topic, with some possible solutions to work off of:
https://stackoverflow.com/questions/14958294/including-external-files-in-a-jekyll-template

**Comment by ianjevans** [comment]
This Jekyll plugin handles remote includes. It would be pretty straightforward to add to our toolchain.
https://github.com/netrics/jekyll-remote-include
