### ISSUE TITLE
Document how to know when upgrade finalization has completed

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/docs#7502]
Bram Gruneir (BramGruneir) commented:

In: https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#step-2-prepare-to-upgrade

It would be really useful to know when the finalize step has completed and the upgrade has finished.

This can be accomplished by `SHOW CLUSTER SETTING version`.

I think we should add two things to this page, 1, when talking about upgrading a cluster, to know which version you are on, check that setting.

And as a final step, confirm everything has been upgraded and finalized by again checking that setting.

Jira Issue: DOC-534

**Comment by BramGruneir** [comment]
I don't know who was working on that page, so assigning to @jseldess for triage.

**Comment by jseldess** [comment]
Thanks, @BramGruneir. 

Passing on to @taroface and @johnrk for further triage and prioritization.
