### ISSUE TITLE
Scrollbar position for main content

### ISSUE THREAD

**Issue by yingzhuchin** [cockroachdb/docs#7518]
Right now, the scrollbar for docs main content is all the way to the right of the page:

<img width="1440" alt="Screen Shot 2020-06-16 at 2 52 35 PM" src="https://user-images.githubusercontent.com/63265176/84815566-33d01a00-afe1-11ea-853f-bc70f80f7fbf.png">

We have pages with table of contents (TOCs), and pages without, and the scrollbar position is the same for both kinds of pages:

<img width="1440" alt="Screen Shot 2020-06-16 at 2 56 10 PM" src="https://user-images.githubusercontent.com/63265176/84815770-86113b00-afe1-11ea-841e-707d8c0efdec.png">

There's a design decision to be made here. On pages with TOCs, should the scrollbar exist between the main content and the TOC? (Instead of existing to the right of the TOC, as it is today.)

cc @luciaaaaaaa and @lnhsingh for potential inclusion in site overhaul work

Also cc @jseldess as FYI

**Comment by luciaaaaaaa** [comment]
Hey, I think this is resolved in our re-design right?

**Comment by jseldess** [comment]
Nope, the scrollbar for the main body is still all the way at the right of the TOC.

**Comment by jseldess** [comment]
Chatted with @nathanstilwell about this:

> Yeah, this going to be tough. The scrollbar itself is controlled by the browser, so they may look or behave differently depending on which browser it is. The only way I could imagine pulling this off would be to have the layout be a fixed height and then have an overflow-y: scroll container for the content pane, but the browser might still display the scroll bar at the right edge of the screen. I'm playing with it now, but there are elements (the TOC on the right) that get position: fixed applied to them through some kind of javascript scroll listener. TLDR, You would have to alter the layout pretty heavily and I'm still not convinced it would work.

Given that this will be hard to achieve without a major refactor of the layout, and given that we aren't hearing reports of this as a problem, I don't think it's worth our focus. Closing for now.
