### ISSUE TITLE
Remove warning about collated strings in indexes or PKs

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#7519]
Re: [STRING](https://cockroachlabs.com/docs//v20.1/string.html)

## Issue Description

The warning "You cannot current use collated strings in indexes or primary keys" links to a closed issue, and the collation docs show examples of collated string primary keys. I think this warning is out of date (and has been for some time)

## Suggested Resolution 

Remove the warning.

**Comment by jseldess** [comment]
@ericharmeling, @awoods187 for triage.

**Comment by awoods187** [comment]
I think we should remove this warning sooner rather than later. I'd say p-1 but it seems small enough that we could include it in this milestone.

**Comment by ericharmeling** [comment]
Yeah wow this has been fixed since v1.1... https://github.com/cockroachdb/docs/pull/8459
