### ISSUE TITLE
sql: improve slow query log documentation for cockroachcloud

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7525]
Andy Woods (awoods187) commented:

This is related to https://github.com/cockroachdb/docs/issues/7512.

CockroachCloud users can’t access their logs in the webui or directly by SSHing into the cluster. However, the slow query log is still available via an endpoint:

`http:///_status/logfiles/local/.log (linked on the Advanced Debug page)`

Note that the endpoint will only be accessible locally without turning on the cluster setting to allow remote debugging (as a security precaution). You can flip the setting via:

`SET CLUSTER SETTING server.remote_debugging.mode = any`

Also, a bit orthogonal to this issue, but how do plan to keep crdb and cc in sync for things like this? cc @jseldess 

Jira Issue: DOC-540

**Comment by knz** [comment]
@bdarnell what do you think about that? security implications?

**Comment by bdarnell** [comment]
The `remote_debugging` setting predates our support for proper auth in the web UI. Endpoints shouldn't both require a login *and* be subject to `remote_debugging`. So when we added auth to these endpoints (in https://github.com/cockroachdb/cockroach/pull/42563), we should have removed the GatewayRemoteAllowed checks. 

We should not be setting this to `any` on CC; we should add proper authentication to any remaining endpoints that rely on it and then remove this setting.

**Comment by knz** [comment]
@aaron-crl can you queue this for review in our upcoming backlog review

**Comment by aaron-crl** [comment]
@thtruo for tracking. Thanks!

**Comment by jseldess** [comment]
Although I've recently realized that this feature falls under sql rather than observaility, @taroface was the writer to handle this initially, so it probably make sense for him to think about the CC implications as well. 

To @awoods187 point, this does raise a good question about how we know when and how a feature should be documented, perhaps differently, for CC. For now, I'll add this to the Docs Biweekly and ask writers to keep this in mind and ask themselves for each feature their documenting.

**Comment by bdarnell** [comment]
> this does raise a good question about how we know when and how a feature should be documented, perhaps differently, for CC

But even more importantly, we should think at the time we're designing a feature about how to do it in a way that works the same across both cloud and self-hosted environments. This often means thinking about the cloud version first - a slow query log that doesn't assume the admin has access to the local filesystem would almost certainly be exposed in a way that would work in both cloud and on-prem.

**Comment by jseldess** [comment]
@bdarnell, I think your last comment is important and think it should be shared more broadly, but I'm not sure with whom. Tech Leads? Product Managers?

**Comment by knz** [comment]
One of the new dev interfaces CS team's objectives is to set up a set of design guidelines for the http apis, for future additions or modifications. It looks to me like Ben's suggestion is a prime candidate for that list.
