### ISSUE TITLE
Automate Maxmind file updates for Registrations

### ISSUE THREAD

**Issue by yingzhuchin** [cockroachdb/docs#7526]
See https://github.com/cockroachlabs/registration/issues/233.

Automate steps 1. and 2. of that process.

For step 3., open PRs for geoip.go in both `registration` and `managed-service`.

After merging former, deploy both API Canary and API Fleet under TeamCity > Internal > Telemetry Server.

**Comment by yingzhuchin** [comment]
This is now running as a cronjob on my machine. I'm not putting the cronjob on Kubernetes because each update still requires manual steps at the end, which are to open a PR for the `registration` repo and deploy two clusters.

Will close this issue if/when I confirm the cronjob runs as expected for the next month (July 2020).

**Comment by davidmargolin** [comment]
The cockroach cloud team is now accessing the mmdb file as well for [our own ip geolocation purposes](https://github.com/cockroachlabs/managed-service/blob/master/pkg/geoip/geoip.go). Im not sure who owns the update process but it would be great if they could ping us in the management console repo when there's an update.

**Comment by yingzhuchin** [comment]
Hi @davidmargolin, I'm currently owning the Maxmind update process for registration. Under our subscription plan, we get a new mmdb file every month. I'd be happy to open a monthly PR in `geoip.go` if that helps (just let me know who should be reviewing), or I can Slack if you let me know which channel to post in.

cc @jseldess

**Comment by davidmargolin** [comment]
A PR would be great. The CC platform team would be happy to review (@alyshanjahani-crl, @laurenbarker, and myself)

**Comment by yingzhuchin** [comment]
You got it!

**Comment by yingzhuchin** [comment]
Cronjob ran as expected, everything looks good.
