### ISSUE TITLE
Automate ETL of telemetry Clusters and Updates data into Looker

### ISSUE THREAD

**Issue by yingzhuchin** [cockroachdb/docs#7527]
1. https://cockroachlabs.cloud/cluster/6dd63ee2-f9be-4c5c-b79c-4f386191982d/overview, "Connect" on upper right
2. https://docs.google.com/document/d/1cdwktazwKIWjEOWUGyri8PCBd_m5598pij_FKxvfeMU/edit?ts=5eea4d3d

- Skip automation for `stmtstats` and `features` tables because those are terabytes-large
- Do `PURGE = TRUE` in steps 4e. and 4f.

Dashboard showing how recently data was loaded from each table: https://cockroachlabs.looker.com/dashboards/98

Might want to add Looker alerts to that dashboard after automation (X days since last updated).

**Comment by yingzhuchin** [comment]
This is now running as a local cronjob on my personal machine. Pending https://github.com/cockroachdb/dev-inf/issues/146, we may or may not be able to productionalize.

**Comment by jseldess** [comment]
Thanks, @yingzhuchin! Do you need any support on that pending dev inf issue? Do you have insight into whether that will happen or who is considering it?

**Comment by yingzhuchin** [comment]
Yes, I had a call with James Linder and he says he should have some cycles in August to pick up the open Dev Inf issue.

**Comment by yingzhuchin** [comment]
Will be replaced by CDC job set up by Abbey H.
