### ISSUE TITLE
Automate Wootric NPS surveys

### ISSUE THREAD

**Issue by yingzhuchin** [cockroachdb/docs#7528]
1. Grab list of new users from [Hubspot](https://app.hubspot.com/contacts/1753393/lists/771?query=nps) via API (find out last fetch date from Piyush)
2. Push list to [Wootric](https://dashboard.wootric.com/?account_token=NPS-dd64b25b#/) via API, which triggers the sending of NPS survey emails

Wootric auth:
```curl -i https://api.wootric.com/oauth/token \
     -F grant_type=password \
     -F username=<username> \
     -F password=<password>
```

Send NPS survey emails:
```curl "https://api.wootric.com/v1/email_survey" \
-d "access_token=<generated access token>" \
-d "survey_settings[sampling][response_throttle]=180" \
-d "emails[]=<email>" \
```

See http://docs.wootric.com/api/#email-survey.

Wootric should then take care of pushing all those NPS survey responses into Looker.

**Comment by jseldess** [comment]
Closing in favor of https://cockroachlabs.atlassian.net/browse/PROPS-86.
