### ISSUE TITLE
CREATE CHANGEFEED clarify schema_change_policy=stop

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#7532]
Re: [CREATE CHANGEFEED](https://cockroachlabs.com/docs//v20.1/create-changefeed.html)

## Issue Description

`schema_change_policy=stop`  only applies to schema changes that require a backfill.  For example:
- adding nullable would allow CDC to continue.
`alter table ycsb.usertable add column field11 string;`
- adding not nullable would does stop CDC.
`alter table ycsb.usertable add column field12 string not null default '1';`
This results in `cockroach.log` entry
`W200618 21:54:49.880708 2211 ccl/changefeedccl/changefeed_stmt.go:571  [n1,job=565062134557048833] CHANGEFEED job 565062134557048833 returning with error: schema change occurred at 1592517285521397000.   0000000000`

## Suggested Resolution 

1. clarify below on behavior only applies if backfill is required.
`stop: Wait for all data preceding the schema change to be resolved before exiting with an error indicating the timestamp at which the schema change occurred.`
2. provide an example of backfill (null vs not null default 1)
3. provide an example of an error message expected.

cc @ajwerner

**Comment by jseldess** [comment]
CC @lnhsingh and @mwang1026 for triage and prioritization.
