### ISSUE TITLE
Document new logging flags

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#754]
Missing some logging flags from [current documentation](https://www.cockroachlabs.com/docs/cockroach-commands.html#logging-flags):

```
--log-backtrace-at traceLocation    when logging hits line file:N, emit a stack trace (default :0)
--verbosity level                   log level for V logs
--vmodule moduleSpec                comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by jseldess** [comment]
Below that table, there's this line: 
> The `--log-backtrace-at`, `--verbosity`, and `--vmodule` flags are intended for internal debugging.

Earlier guidance (from @petermattis or @bdarnell, I think) was to leave those undocumented. But it's definitely worth checking into this now. Or, at the least, we should add them to the table with a generic description like "For internal debugging". The current sentence is clearly easy to miss.

**Comment by sploiselle** [comment]
@jseldess Totally missed that line! This is a non-issue then and I'll chalk it up to being kind of ill.
