### ISSUE TITLE
Consolidated list of errors

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7541]
## Title
Common Error Codes

## Description
A consolidated list of common errors spanning multiple topics: security, authentication, connection refused, retries, etc. Any error that has an associated code with it should be listed.

## Expected Audience
Developers and Ops

**Comment by jseldess** [comment]
@dbist, is this the same as https://github.com/cockroachdb/docs/issues/806 or https://github.com/cockroachdb/docs/issues/5476, or are you thinking of something different?

**Comment by dbist** [comment]
This is a good start, feel free to consolidate the docs issues now :).

**Comment by jseldess** [comment]
Thanks, @dbist. I'll close in favor of https://github.com/cockroachdb/docs/issues/806.
