### ISSUE TITLE
Document how GC TTL of jobs table affects incremental cluster backups

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/docs#7545]
In 20.1 we changed the default GC TTL of the jobs table from 5 minutes to the default 25h. This was to enable incremental cluster backups that were taken more than 5 minutes after the last cluster backup. However, if the cluster was created on an earlier version, they'll still have the old GC TTL.

We should add a section to incremental backups to call out for cluster backups on clusters that were created on an earlier version that they would need to change the GC TTL period of the jobs table (`ALTER TABLE system.jobs CONFIGURE ZONE USING gc.ttlseconds=90000`).

**Comment by mwang1026** [comment]
Closing as Dupe since @gemma-shay  is working on this from error message side instead https://github.com/cockroachdb/docs/issues/8994
