### ISSUE TITLE
typo in CockroachDB in Comparison page

### ISSUE THREAD

**Issue by AdamEr8** [cockroachdb/docs#7546]
I noticed a minor typo (tra**_b_**saction instead of tra**_n_**saction) on the [CockroachDB in Comparison](https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html) page, in the tooltip for "Cost Based Optimization"

different version occurrences can be found using [repo search](https://github.com/cockroachdb/docs/search?q=trabsaction&unscoped_q=trabsaction).

**Comment by jseldess** [comment]
Thanks, @AdamEr8. We'll fix this asap.
