### ISSUE TITLE
Filter out Netlify preview pages from Google Analytics page views data

### ISSUE THREAD

**Issue by yingzhuchin** [cockroachdb/docs#7549]
Our Netlify previews, which are generated on every commit to a GitHub branch, result in /docs/stable/ URLs which are then shortened and parsed by GA so that they are indistinguishable from production URLs.

For example, this is a current live Netlify preview page: https://deploy-preview-[redacted]--cockroachdb-docs.netlify.app/docs/stable/build-a-spring-app-with-cockroachdb-jdbc.html

Notice how /docs/stable/  is part of the preview URL

If you click on that preview link and check GA/Looker stats again, you will see a corresponding increase, so that should be our proof that the preview pages are what's populating GA/Looker data

Proof -- I generated views of the pages below on Jun 24:
<img width="1145" alt="Screen Shot 2020-06-24 at 12 56 07 PM" src="https://user-images.githubusercontent.com/63265176/85599039-24248700-b61a-11ea-9ccf-80224b104b80.png">

Figure out how to filter out Netlify preview pages from GA and subsequently Looker data.

**Comment by jeffreyroach** [comment]
In GA admin, just need to create a hostname filter to include the following:
www\.cockroachlabs\.com|forum\.cockroachlabs\.com|docs\.cockroachlabs\.com

I've added this to the view that's connected to Looker, but keep in mind, this is not retroactive.

**Comment by yingzhuchin** [comment]
Thanks so much for taking care of this, @jeffreyroach! I'll close this issue out.

@jseldess, it doesn't look like I have the right access level to create filters. Is that something you think I need?
