### ISSUE TITLE
sql, tracing: save traces in Jaeger format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7559]
PR: https://github.com/cockroachdb/cockroach/pull/47303

From release notes:
> [Statement diagnostics zip bundles](../v20.2/admin-ui-statements-page.html) now contain a representation of the statement trace that can be imported into [Jaeger](https://www.jaegertracing.io) for visualization. [#47303][#47303] {% comment %}doc{% endcomment %}

**Comment by piyush-singh** [comment]
This was documented in 20.1.x by Ryan already.
