### ISSUE TITLE
Blog code snippets don't scroll on mobile

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/docs#756]
I was just reading https://www.cockroachlabs.com/blog/running-cockroachdb-on-kubernetes/ and I noticed that you can't scroll the code segments on mobile leading to not being able to read them.

Might be a good idea to enable scrolling or wrapping on small screens.

Not sure if this is the correct place since the blog isn't actually docs.

Might be related to #593.

**Comment by jseldess** [comment]
@jess-edwards, who's in charge of the blog.

**Comment by jess-edwards** [comment]
@d4l3k @jseldess 

Thanks for flagging. I'll see if that's a quick fix.

**Comment by jess-edwards** [comment]
@d4l3k @jseldess 

Line wrapping enabled - in all cases. I couldn't find a setting for just mobile. What do you think?

**Comment by jseldess** [comment]
Horizontal scrolling might keep the blocks cleaner visually. The wrapping makes them quite hard to read on a small screen. Just my 2 cents.

If you want to try scrolling instead, I think it would just be a CSS change, but @mjibson or @sploiselle would be able to say for sure.

**Comment by sploiselle** [comment]
Thought through this with @jseldess a little and think we could "fix" the issue with a best practice:

Code comments should be manually line-broken at 35 characters (which is where wrapping happens on mobile on the blog). Words that would break the 35th character get moved to the next line.

For example, that would turn the existing post into:

```
# This service is meant to be used
# by clients of the database. 
# It exposes an IP address and DNS 
# name within the cluster that will 
# automatically load balance
# connections to the different
# database pods.

# This service only exists to 
# create DNS entries for each pet 
# in the petset such that they can
# resolve each other's IP 
# addresses. 
# It does not create a 
# load-balanced ClusterIP and
# should not be used 
# directly by clients in most
# circumstances.
```

Far from perfect, but solves the problem in a LCD kind of way.

**Comment by jess-edwards** [comment]
Alright, let me take a look at how some other tech blogs and docs sites approach this. I'd prefer to not permanently alter all views of the code snippets to serve the few who read them on the blog. 

It looks like the docs site allows for horizontal scroll. Let me see if crayon (the code snippet highlighter) allows for horizontal scrolling on mobile.

**Comment by jess-edwards** [comment]
@sploiselle @jseldess 

Horizontal scroll added; forced line wrap removed. Works on mobile.
