### ISSUE TITLE
kvserver,reports: change how constraint conjunctions are reported on

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7560]
PR: https://github.com/cockroachdb/cockroach/pull/47389

From release notes:
> The `system.replication_constraint_stats` report now treats conjunctions of [replication constraints](../v20.2/configure-replication-zones.html) as a single unit of reporting, whereas before there was a report entry for each constraint in the conjunction. For example, given a zone with a replication constraint like `{"+region=us,+az=az1":1}` (meaning, one replica in a node with locality `region=us,az=az1`), now there will be a report entry for `"+region=us,+az=az1"` where before there was a separate entry for `"+region=us"` and another one for `"+az=az1"`. [#47389][#47389] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
I'm not convinced -- since none of our examples have mention of "conjunction-constraints" (they're all region level rather than AZ). maybe not worth updating?

cc @awoods187 feel free to close

**Comment by awoods187** [comment]
I'm okay closing this
