### ISSUE TITLE
kubernetes: add additional init-certs addresses

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7561]
Jesse Seldess commented:

PR: https://github.com/cockroachdb/cockroach/pull/47610

From release notes:
> The Kubernetes manifests now generate node certificates with additional addresses `'cockroachdb-public.<namespace>'` and `'cockroachdb-public.<namespace>.svc'`. [#47610][#47610] {% comment %}doc{% endcomment %}

Jira Issue: DOC-546

**Comment by johnrk** [comment]
cc @thtruo

**Comment by thtruo** [comment]
cc @aaron-crl for awareness
