### ISSUE TITLE
storage: change default engine type from RocksDB to Pebble

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7562]
PR: https://github.com/cockroachdb/cockroach/pull/48145

From release notes:
> Changed the default engine type for new storage directories from RocksDB to Pebble. Existing stores will continue to use the previously specified storage engine, and an explicit specification (via `--storage-engine=...`) will override the default. [#48145][#48145] {% comment %}doc{% endcomment %}

**Comment by johnrk** [comment]
@itsbilal, can you help @rmloveland with defining what we should include in our docs for Pebble being enabled by default in 20.2?

**Comment by itsbilal** [comment]
Sure! Happy to help with that.

Basic takeaway: The `--storage-engine` flag is no longer sticky, and Pebble is no longer experimental or opt-in. We always use Pebble on 20.2 unless `--storage-engine=rocksdb` is specified at every node start. Bidirectional compatibility between the two engines still exists. Happy to elaborate on any other specifics!

**Comment by rmloveland** [comment]
Thank you Bilal!  I think that is enough for me to get started with, and I will reach out with specific questions as needed.

**Comment by rmloveland** [comment]
Hey @itsbilal I am working up a docs PR for this - I have a few
questions for you that will inform the PR:

1.  In the 'Memory Leak' section of [Troubleshoot Cluster Setup](https://www.cockroachlabs.com/docs/v20.1/cluster-setup-troubleshooting.html#suspected-memory-leak),
    where it discusses suspected memory leaks, can we now delete
    the section on CGo allocated memory from the **Suspected memory
    leak** section?
    -   (possibly incorrect assumption: RocksDB was the main reason
        for the mention of CGo allocated memory)
2.  Has the `running_status` field reported by [`SHOW JOBS`](https://www.cockroachlabs.com/docs/v20.2/show-jobs.html) been
    updated to say 'Pebble compaction'?  Alternatively, is it
    staying 'RocksDB compaction' but actually referring to Pebble?
3.  Are the names of the various `rocksdb.*` cluster settings
    staying the same, but now controlling Pebble settings?
    -   Not sure they're actually documented explicitly anywhere, but
        we do [reference them in the TPC-C instructions docs](http://localhost:4000/docs/v20.2/performance-benchmarking-with-tpc-c-100k-warehouses.html#step-3-configure-the-cluster)
4.  Are the various [metrics described on the Custom Chart Debug
    Page](https://www.cockroachlabs.com/docs/v20.2/admin-ui-custom-chart-debug-page.html) (on my machine available at
    <http://localhost:8888/#/debug/chart>) still going to to be called
    `rocksdb.*`? Presumably yes, but they will now be referring to
    things happening in Pebble?
