### ISSUE TITLE
backupccl: add is_full_cluster to SHOW BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7563]
PR: https://github.com/cockroachdb/cockroach/pull/45860

From release notes:
> [`SHOW BACKUP`](../v20.2/show-backup.html) now shows whether a [`BACKUP`](../v20.2/backup.html) is a full cluster backup or not. [#45860][#45860] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closed - this was documented for 20.1
