### ISSUE TITLE
backupccl: add privileges to SHOW BACKUP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7564]
PR: https://github.com/cockroachdb/cockroach/pull/45862

From release notes:
> The privileges assigned to a given table/database are now visible through [`SHOW BACKUP`](../v20.2/show-backup.html). `SHOW BACKUP` will list which users and roles had which privileges on each table/database in the backup if the `WITH privileges` option is specified. [#45862][#45862] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - this was added in 20.1
