### ISSUE TITLE
Need example Java code for transaction retry logic using JDBC

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/docs#757]
We seem to have code for every platform short of Java, which is probably the most popular for SQL-based applications.

**Comment by jseldess** [comment]
Missing from https://www.cockroachlabs.com/docs/build-a-test-app.html#step-4-execute-transactions-from-a-client

**Comment by petermattis** [comment]
Ping. This is fairly high priority. What is the status?

**Comment by jseldess** [comment]
@arjunravinarayan, that ping was for you, since you've been doing the actual work here.

**Comment by arjunravinarayan** [comment]
Working on this now.
