### ISSUE TITLE
builtins: introduce builtins for some binary predicates

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7570]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/47584

From release notes:
> Added support for `ST_Covers`, `ST_CoveredBy`, `ST_Contains`, `ST_Crosses`, `ST_Equals`, `ST_Intersects`, `ST_Overlaps`, `ST_Touches` and `ST_Within` for `GEOMETRY` geospatial types. [#47584][#47584] {% comment %}doc{% endcomment %}

Jira Issue: DOC-549

**Comment by rmloveland** [comment]
The following predicates are now documented:

- `ST_Covers` (#8576)
- `ST_CoveredBy` (#8575)
- `ST_Contains` (#8572)
- `ST_Intersects` (#8574)
- `ST_Overlaps` (#8579)
- `ST_Touches` (#8580)
- `ST_Within` (#8573)

Leaving the following to be done:

- `ST_Equals`
- `ST_Crosses`
