### ISSUE TITLE
builtins: implement swathe of I/O functions for Geometry/Geography

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7571]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/48015

From release notes:
> Added the following geospatial functions: `ST_GeomFromText`, `ST_GeometryFromText`, `ST_GeogFromText`, `ST_GeographyFromText`, `ST_GeomFromWKB`, `ST_GeomFromEWKB`, `ST_GeomFromEWKT`, `ST_GeomFromGeoJSON`, `ST_GeogFromWKB`, `ST_GeogFromEWKB`, `ST_GeogFromEWKT`, `ST_GeogFromGeoJSON`, `ST_AsText`, `ST_AsBinary`, `ST_AsEWKB`, `ST_AsEWKT`, `ST_AsKML`, `ST_AsGeoJSON`. [#48015][#48015] {% comment %}doc{% endcomment %}

Jira Issue: DOC-550

**Comment by rmloveland** [comment]
Some of these are partially addressed (or at least mentioned or show an example):

- `st_geomfromtext` (#8747)
- `st_astext` (#7736)
- `st_asgeojson` (#8617, #8782)
