### ISSUE TITLE
builtins: add Geography builtins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7575]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/48529

From release notes:
> Introduced the following functions that work on `GEOGRAPHY` types: `ST_Covers`, `ST_CoveredBy`, `ST_Intersects`, `ST_Distance`, `ST_DWithin`, `ST_Perimeter`, `ST_Area`, and `ST_Length`. [#48529][#48529] {% comment %}doc{% endcomment %}

Jira Issue: DOC-554

**Comment by rmloveland** [comment]
The following functions from this issue are documented (for `GEOGRAPHY` types):

- ST_Covers (#8576)
- ST_CoveredBy (#8575)
- ST_Intersects (#8574)
