### ISSUE TITLE
Add close cursor statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7591]
PR: https://github.com/cockroachdb/cockroach/pull/45662

From release notes:
> Added syntax for `DECLARE` and `CLOSE`. `CLOSE ALL` is a no-op, as there are no cursors to close. `CLOSE <cursor>` and `DECLARE` raise unimplemented errors. [#45662][#45662] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Not sure we need to call this out, as it's a no-op and affects no syntax pages.
