### ISSUE TITLE
sql: add CONCURRENTLY syntax to CREATE INDEX and DROP INDEX

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7593]
PR: https://github.com/cockroachdb/cockroach/pull/46695

From release notes:
> Added support for `CREATE INDEX CONCURRENTLY` and `DROP INDEX CONCURRENTLY` syntax. These statements are no-ops, as all indexes are created concurrently. [#46695][#46695] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This was a documented change in 20.1: https://github.com/cockroachdb/docs/pull/7196
