### ISSUE TITLE
sql: remove deprecated timezone builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7594]
PR: https://github.com/cockroachdb/cockroach/pull/46748

From release notes:
> Previously, we implemented the timezone builtin as `timezone(<time type>, <timezone>)`. However, this is the opposite from the Postgres implementation (which allowed `timezone(<timezone>, <time type>`). In 20.1, we supported both permutations to aid with this migration, but with this change we will only support the timezone first. You can also use `AT TIME ZONE`, which is compatible with the `timezone` function in all versions. [#46748][#46748] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is already documented.
