### ISSUE TITLE
colexec: rename vectorize setting 192auto to auto and make it the default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7597]
PR: https://github.com/cockroachdb/cockroach/pull/46845

From release notes:
> The [vectorized execution](../v20.2/vectorized-execution.html) engine will only run queries with streaming operators. Issue `SET vectorize=on` to enable the vectorized execution engine for buffering operators. [#46845][#46845] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We currently have this documented.
