### ISSUE TITLE
sql: add bit support for bit_and aggregate function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7600]
PR: https://github.com/cockroachdb/cockroach/pull/46954

From release notes:
> The `bit_and()` [aggregate function](../v20.2/functions-and-operators.html#aggregate-functions) now supports [`BIT`](../v20.2/bit.html) and `VARBIT` data types. [#46954][#46954] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This supported is already documented at https://www.cockroachlabs.com/docs/dev/functions-and-operators.html.
