### ISSUE TITLE
sql: add bit support for bit_or aggregate function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7601]
PR: https://github.com/cockroachdb/cockroach/pull/47023

From release notes:
> The `bit_or()` [aggregate function](../v20.2/functions-and-operators.html#aggregate-functions) now supports [`BIT`](../v20.2/bit.html) and `VARBIT` data types. [#47023][#47023] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This support is already documented at https://www.cockroachlabs.com/docs/dev/functions-and-operators.html.
