### ISSUE TITLE
sql: allow strpos() builtin function to support bit and bytes array

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7602]
PR: https://github.com/cockroachdb/cockroach/pull/46875

From release notes:
> Modified the `strpos()` function to allow it to support [`BIT`](../v20.2/bit.html) and [`BYTES`](../v20.2/bytes.html) arrays. [#46875][#46875] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This support is already documented at https://www.cockroachlabs.com/docs/dev/functions-and-operators.html.
