### ISSUE TITLE
Undocumented feature: Interleaved secondary indexes

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#761]
Our [Interleave in Parent](https://www.cockroachlabs.com/docs/interleave-in-parent.html) docs focus on interleaving tables. They need to be expanded to cover interleaving secondary indexes as well. 

RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_interleaved_tables.md

**Comment by jseldess** [comment]
In interviewed with a client, this feature was referenced as an example of something to consider in good sql design using CockroachDB.

**Comment by jseldess** [comment]
@sploiselle, @danhhz, just remembered that we never covered interleaving indexes. Is this an important feature to cover for v1?

**Comment by danhhz** [comment]
Just so we're all on the same page, can we call this "secondary indexes" please? Interleaving a primary index is already documented at https://www.cockroachlabs.com/docs/interleave-in-parent.html (I was genuinely confused for a minute or so)

In an ideal world, this should get documented for 1.0, yeah. Though it's not a tragedy if it doesn't make it

**Comment by jseldess** [comment]
Thanks for the clarification, @danhhz.

**Comment by jseldess** [comment]
@danhhz, @sploiselle, are either of you interested in adding docs on interleave indexes as part of the docs fixitday?

**Comment by sploiselle** [comment]
Will need some tl;dr from @danhhz, but would be glad to!

**Comment by danhhz** [comment]
> Will need some tl;dr from @danhhz, but would be glad to!

👍

**Comment by sploiselle** [comment]
Forgot that cockroachdb/cockroach#23593 landed and I have the diagram for this. Just pinging myself to do it.

**Comment by vy-ton** [comment]
@ericharmeling are you ok with closing this with the impending deprecation?
