### ISSUE TITLE
rowexec: remove settings for disabling temp storage in sorts and joins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7610]
PR: https://github.com/cockroachdb/cockroach/pull/47357

From release notes:
> Removed two public [cluster settings](../v20.2/cluster-settings.html) `sql.distsql.temp_storage.joins` and `sql.distsql.temp_storage.sorts` that can disable usage of temporary on disk storage of intermediate results of query execution. [#47357][#47357] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/7940.
