### ISSUE TITLE
sql: collect multi-column stats on index prefixes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7611]
PR: https://github.com/cockroachdb/cockroach/pull/47729

From release notes:
> Added support for collection of multi-column statistics. By default, statistics are now collected on all prefixes of each index, in addition to 100 other individual columns. This feature can be disabled by setting the [cluster setting](../v20.2/cluster-settings.html) `sql.stats.multi_column_collection.enabled` to false. [#47729][#47729] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Related to #4798.
