### ISSUE TITLE
sql: add square and cube root unary operators (|/ and ||/)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7612]
PR: https://github.com/cockroachdb/cockroach/pull/47680

From release notes:
> Added square root and cube root unary operators `|/` and `||/`. [#47680][#47680] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/commit/d8fe0a67c2b7e48507f711ef939b1205500a093e
