### ISSUE TITLE
kvclient: disallow savepoint rollback after most errors 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7615]
PR: https://github.com/cockroachdb/cockroach/pull/47724

From release notes:
> [`ROLLBACK TO SAVEPOINT`](../v20.2/rollback-transaction.html) is no longer permitted after miscellaneous internal errors. [#47724][#47724] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
I'm going to close this since it's a bit of a "bug fix"
