### ISSUE TITLE
sql: don't copy old pk when changing bucket size on sharded index

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7620]
PR: https://github.com/cockroachdb/cockroach/pull/45894

From release notes:
> Caused [primary key changes](../v20.2/alter-primary-key.html) to not create a copy of the old primary key if the primary key change only changes the bucket count of a [hash sharded index](../v20.2/indexes.html#hash-sharded-indexes). [#45894][#45894] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't require docs.

(See comments in https://github.com/cockroachdb/docs/pull/8718).
