### ISSUE TITLE
sql: add postgres enum builtins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7627]
PR: https://github.com/cockroachdb/cockroach/pull/49086

From release notes:
> Added the Postgres supported `ENUM` builtins `enum_first`, `enum_last`, and `enum_range`. [#49086][#49086] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/commit/d8fe0a67c2b7e48507f711ef939b1205500a093e
