### ISSUE TITLE
sql: add the `crdb_internal.create_type_statements` table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7634]
PR: https://github.com/cockroachdb/cockroach/pull/49771

From release notes:
> Added the `crdb_internal.create_type_statements` virtual table. It holds create statements for user defined types. [#49771][#49771] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We currently do not document the `crdb_internal.create_statements` table, or in general document the `crdb_internal` schema tables. So I don't think we should document `create_type_statements`.
