### ISSUE TITLE
demo: display connection urls for nodes in the demo cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7636]
PR: https://github.com/cockroachdb/cockroach/pull/46913

From release notes:
> The [`cockroach demo`](../v20.2/cockroach-demo.html) command now displays a connection URL to the demo cluster, and in a multi-node cluster it displays connection strings for all of the nodes in the cluster. [#46913][#46913] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@ericharmeling, I can take this.

**Comment by ericharmeling** [comment]
@jseldess Thank you!

**Comment by jseldess** [comment]
This was actually resolved by your 20.1 `demo` updates, @ericharmeling: https://github.com/cockroachdb/docs/pull/7191/files. But I'll open a PR with some other tweaks.
