### ISSUE TITLE
cli/demo: make the secure mode controllable via COCKROACH_INSECURE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7637]
PR: https://github.com/cockroachdb/cockroach/pull/46922

From release notes:
> It is now possible to pre-configure the secure mode of [`cockroach demo`](../v20.2/cockroach-demo.html) using the environment variable `COCKROACH_INSECURE` like other client commands. [#46922][#46922] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Because `--insecure` mode is deprecated for `cockroach demo`, I don't think we should document this.
