### ISSUE TITLE
hlc: use PTP user space API as HLC clock

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7644]
PR: https://github.com/cockroachdb/cockroach/pull/46942

From release notes:
> Added a new [`cockroach start`](../v20.2/cockroach-start.html) option `--clock-device` that allows CockroachDB's hybrid logical clock (HLC) to use an IEEE 1588 PTP clock device for the HLC current time. [#46942][#46942] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@taroface, @johnrk, not sure what the plans are for this one in terms of full deployment guidance.

**Comment by johnrk** [comment]
This is more of a KV issue. cc @rmloveland

**Comment by jseldess** [comment]
@johnrk, the reason I consider this deploy and ops is that, as far as I remember, this was added to accommodate VMWare-based deployment, so it's part of deployment setup.
