### ISSUE TITLE
cli/quit: bump the default for --drain-wait

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7648]
PR: https://github.com/cockroachdb/cockroach/pull/46396

From release notes:
> The default value of the parameter `--drain-wait` for [`cockroach quit`](../v20.2/cockroach-quit.html) has been increased from 1 minute to 10 minutes, to give more time for nodes with thousands of ranges to migrate their leases away. [#46396][#46396] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@taroface, please add a comment about this if it's not closed by a PR.

**Comment by taroface** [comment]
The `10m` default value was already documented.
