### ISSUE TITLE
cli: Resolve past engine type correctly with encryption-at-rest

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7655]
PR: https://github.com/cockroachdb/cockroach/pull/48721

From release notes:
> Made the `--storage-engine` flag to [`cockroach start`](../v20.2/cockroach-start.html) sticky (i.e. resolve to the last used engine type when unspecified), even when specified stores are encrypted at rest. [#48721][#48721] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
I don't think this is needed because of `pebble` being default now
