### ISSUE TITLE
sql: additional docs for `RETURNING` SQL syntax

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/docs#766]
There's no explanation here https://www.cockroachlabs.com/docs/insert.html for how to get the value from `INSERT ... RETURNING` when using a SQL driver such as Go's. Is it possible?

**Comment by bdarnell** [comment]
The Go driver (like most drivers) has two methods, `Query()` for statements that return results, and `Exec()` for ones that don't. Normally you use `Query()` for `SELECT` and `Exec()` for `INSERT`, but an `INSERT` with `RETURNING` works more like a `SELECT`, so you'd run it with `Query()`.

**Comment by jseldess** [comment]
@bdarnell, @spencerkimball, should we add driver-specific examples to some of the SQL statement pages? Currently, they're all pure SQL examples...

**Comment by spencerkimball** [comment]
Thanks @bdarnell 
@jseldess yes an example demonstrating @bdarnell's answer would be very helpful.
