### ISSUE TITLE
kv: re-tune Raft knobs for high throughput WAN replication

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7662]
PR: https://github.com/cockroachdb/cockroach/pull/49619

From release notes:
> Default [replication configurations](../v20.2/configure-replication-zones.html) have been tuned to support higher replication throughput in high-latency replication quorums. [#49619][#49619] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Unless we previously documented the defaults for this setting, I think we can close this issue. If anything, the default value changes should have been documented in the release notes for 20.2. Feel free to reopen if you disagree.
