### ISSUE TITLE
Document that we do not balance replicas among multiple stores per node

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7666]
For details, see https://github.com/cockroachdb/cockroach/issues/6782

tl;dr: we do not rebalance replicas among multiple stores on the same node.

Estimated scope of work:

- Update `cockroach start` docs where it talks about multiple stores per node
- Seek out and update other mentions of this feature
- Update them all with a note (perhaps an include)

Related issues:

- #3197
- #4684

**Comment by ericharmeling** [comment]
This appears to have been resolved. Please re-open if I'm mistaken.

**Comment by rmloveland** [comment]
Probably (?) but I need to look more closely at this to be sure - reopening so it doesn't fall off my radar.

**Comment by ericharmeling** [comment]
Going through the known limitations issues as I'm documenting 21.1 known limitations, and this appear to have been resolved by https://github.com/cockroachdb/cockroach/commit/ed34965b3622d551cd56403838ebe3024036d848. I'm going to close for now, if that's okay?
