### ISSUE TITLE
the Strong Consistency page is a bit optimistic

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#767]
As reported by @aphyr, the "no stale reads" phrase on our Strong Consistency page is technically not true. We should find a better phrasing.

 https://www.cockroachlabs.com/docs/strong-consistency.html

**Comment by andreimatei** [comment]
I was thoroughly when I opened this. I now think "no stale reads" is correct. I'll let @aphyr reopen if he feels otherwise.

**Comment by aphyr** [comment]
Yeah, after extensive staring I think you're right too. The causal reverse phenomenon is... something *like* a stale read, but it's... more its own behavior.
