### ISSUE TITLE
Expand Examples of Array Operators

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/docs#7671]
[https://www.cockroachlabs.com/docs/stable/array.html](https://www.cockroachlabs.com/docs/stable/array.html)

There were no examples of using a specific element in an array, but was able to figure it out with Postgres documentation.

```
select * from crdb_internal.jobs where job_type = 'CHANGEFEED' and descriptor_ids @> ARRAY[288];
```

maybe consider an example like so based on the existing docs:

```
root@:26257/defaultdb> INSERT INTO c VALUES (ARRAY[10,20,30]);
INSERT 1

Time: 11.439951ms

root@:26257/defaultdb> INSERT INTO c VALUES (ARRAY[42,99]);
INSERT 1

Time: 2.646631ms

root@:26257/defaultdb> SELECT * from c where d @> ARRAY[42];
     d
-----------
  {42,99}
(1 row)

Time: 1.274903ms
```

**Comment by jseldess** [comment]
Thanks, @glennfawcett! @ericharmeling, @awoods187, on to you for further triage and prioritization.

**Comment by awoods187** [comment]
I think this is a great example of a type of enhancement we could make to our docs for some of the bigger features (e.g., JSON, ARRAY). We should provide at least one example query per operator. I'd rate this as more important than general reference information but less important than documenting new features or fully following a jobs-to-be-done approach.

**Comment by deeptikorwar** [comment]
@Amruta-Ranade, can I work on this one?

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8697
