### ISSUE TITLE
typo of reverse scan

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#7674]
typo in the docs at https://www.cockroachlabs.com/docs/stable/table-expressions.html#force-index-selection
```
Forcing a reverse can is sometimes useful during performance tuning. 
```
Should probably be:
```
Forcing a reverse scan is sometimes useful during performance tuning. 
```

**Comment by jseldess** [comment]
cc @ericharmeling, @awoods187 for triage and prioritization.

**Comment by awoods187** [comment]
Seems like a quick and easy change--i think we should go ahead and knock it out.
