### ISSUE TITLE
Update lib/pq doc with a section for known issues and limitations

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7685]
Artem Ervits (dbist) commented:

## Description
More context in the following [link](https://cockroachlabs.slack.com/archives/CPD3ANLMB/p1593463883400900?thread_ts=1593461270396800&cid=CPD3ANLMB).

## Outline
pgx is superio to lib/pq, we need to highlight that.

## Expected Audience

Jira Issue: DOC-577

**Comment by jseldess** [comment]
cc @vy-ton, @ericharmeling, @ianjevans
