### ISSUE TITLE
Improve "Hello World" tutorial docs

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7687]
"Hello World" refers to a basic, getting-started-type code sample (historically, an application that just prints "Hello World" to the console). 

The [tutorials we call "Hello World"](https://www.cockroachlabs.com/docs/stable/hello-world-example-apps.html) do much more than just print "Hello World".  A lot of these apps go beyond the very basics, into some pretty advanced stuff (e.g., transaction retries). As such, I'd like to suggest renaming this group of apps as "Getting Started". 

Additionally, I think it would be super helpful to create a page that introduces the example use case (i.e., A small bank needs to store data) and the database schema (i.e., `bank`). @vy-ton pointed out that this context was missing from the docs.

**Comment by ericharmeling** [comment]
FYI
@awoods187 @jseldess

**Comment by awoods187** [comment]
This sounds good to me--in particular giving more initial context. I do like the name "Hello World" but I don't feel strongly about it.

**Comment by vy-ton** [comment]
@ericharmeling for awareness as you're thinking about modular code samples
