### ISSUE TITLE
Covered Queries - CREATE INDEX Doc Update

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7694]
Crossman Wilkins commented:

Re: [CREATE INDEX](https://cockroachlabs.com/docs//v20.1/create-index.html)

## Issue Description

Covered queries should probably have their own section here or potentially their own page. The concept is alluded to with the "storing" example, but it's not explained and it's not clear from the documentation that you don't need to use storing or covering to have covered queries. 

## Suggested Resolution 

I would have a section that clearly defines covered queries (Mongo documentation does this well). Have some examples that are covered by an index, and build on the example that explains how to use "storing"/"covering". 

Jira Issue: DOC-580

**Comment by jseldess** [comment]
I'm not sure this belongs (only) on the page about creating an index, but it would be great to document this better in the context of query optimization at the least.

**Comment by jseldess** [comment]
cc @ericharmeling and @awoods187 for triage and prioritization.

**Comment by awoods187** [comment]
I think this is probably more of a developer guide than reference doc. Ideally, we want to explain when to do this in addition to how to do it. This seems like another good docs project candidat.e

**Comment by awoods187** [comment]
This would fit well with the developer guide

**Comment by rmloveland** [comment]
@SpicyThrow I recently made some changes along these lines in https://github.com/cockroachdb/docs/pull/12534 ?

Part of the change is adding a description of "covering index" to `CREATE INDEX` here: https://www.cockroachlabs.com/docs/v21.2/create-index.html#store-columns

We now (as of this writing) get search results for:

- ["covered query"](https://www.cockroachlabs.com/docs/search.html?query=covered+query)
- ["covering index"](https://www.cockroachlabs.com/docs/search.html?query=covering+index)

I think this meets 1/2 of your requirements (description), and [there is an example (if brief) on the CREATE INDEX page](https://www.cockroachlabs.com/docs/v21.2/create-index.html#store-columns)

Do you think this meets the need?  Or would you like to see more examples / explanation?

**Comment by SpicyThrow** [comment]
I think this basically addresses my issue. I might add an additional sentence that says something like, "This is what's known as a covered query."
