### ISSUE TITLE
Document CockroachDB geospatial support for 20.2

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7695]
This is a tracking issue for all of the work to document geospatial features for the 20.2 release.

To see the current status, take a look at the [Spatial Docs board](https://github.com/cockroachdb/docs/projects/50).

See also:

- cockroachdb/cockroach#19313

**Comment by rmloveland** [comment]
@awoods187 FYI - using this as the tracking issue for all geospatial-related docs work.  As more issues accumulate I will edit the description to break the issue list into subsections, etc.

**Comment by awoods187** [comment]
Let me know if you think we should make a geospatial docs project board or if that's overkill. I would like to see the meta-issue grouped above in priority similar to our meeting yesterday.

**Comment by rmloveland** [comment]
I think that's a great idea.  I will create a docs project board and take a shot at prioritizing the issues and send you a link to review.

**Comment by rmloveland** [comment]
FYI I'm punting on listing all the spatial issues here -- added a link to the project board instead.
