### ISSUE TITLE
Add specific IAM policies required for backup/restore to cloud provider buckets

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/docs#7696]
Ricardo Rocha (ricardocrdb) commented:

For backing up and restoring to Google and AWS buckets, certain IAM policies and roles are required to prevent errors from occurring and making the experience much smoother for the user. The documentation currently doesn't outline the specific policies required for backups and restores when using a storage bucket from GCP, AWS, etc.

Example - [Veeam](https://www.veeam.com/kb3032) defines the policies required and listed in json for easy copy/pasting into AWS IAM.

gz#11859

Jira Issue: DOC-581

**Comment by jseldess** [comment]
@lnhsingh, @mwang1026 for triage and prioritization.
