### ISSUE TITLE
cleanup bnf simplify/reduce

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#77]
Currently the BNF generator has a few steps:

1. Parse the sql.y yacc file
2. Print a EBNF from it
3. Parse the EBNF
4. Simplify the EBNF
5. Generate the RR diagrams with simplified EBNF

This is because before we had to use an external program for step 1. Now that we have our own parser, there's no need to convert to EBNF and back. Instead we can simplify the yacc AST in memory and only output an EBNF once.

**Comment by jseldess** [comment]
Is this still something you want/plan to do, @mjibson?

**Comment by mjibson** [comment]
Maybe, but no need for an issue.
