### ISSUE TITLE
K8s Helm command incorrect for insecure cluster

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#7702]
Now that we are hosting our own helm chart the install command is wrong.  For example see here: https://www.cockroachlabs.com/docs/stable/orchestrate-a-local-cluster-with-kubernetes-insecure.html#step-2-start-cockroachdb

to install an insecure instance of crdb using helm the docs say `helm install my-release stable/cockroachdb`

however, when using the new chart repo, `stable/cockroachdb` is no longer valid.  the above command should now be `helm install my-release cockroachdb/cockroachdb`

It appears the install command for the secure cluster is already correct

**Comment by timveil** [comment]
also docs link to invalid url for the actual chart... https://github.com/cockroachdb/helm-charts/blob/master/Chart.yaml

**Comment by jseldess** [comment]
Thanks, @timveil! @taroface, @johnrk, I thought we were tracking this doc work somewhere already, but I can't find it. If the new chart repo is already live, I think this is high priority docs work.

**Comment by taroface** [comment]
@jseldess The commands and links were updated with #7683 yesterday, but the path to the charts actually changed today. Also, I missed updating the docs specifically for a local, insecure deployment using Helm (my search terms weren't broad enough). I'm updating both now.
