### ISSUE TITLE
clarify that UI dates are shown in UTC

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#7707]
Relates to https://github.com/cockroachdb/cockroach/issues/27065 and https://github.com/cockroachdb/cockroach/issues/51013

**Comment by james-sabel** [comment]
Hello! Maybe I could give this issue a go, if that's ok.

I was thinking of adding a side note somewhere in the [Overview Dashboard page](https://www.cockroachlabs.com/docs/v20.1/admin-ui-overview-dashboard.html).

On the other hand, since all timestamps are UTC perhaps the note could go in the main [Admin UI Overview page](https://www.cockroachlabs.com/docs/v20.1/admin-ui-overview.html).

What do you think?

**Comment by Amruta-Ranade** [comment]
@james-sabel Assigning the issue to you :)
@taroface Can you recommend the course of action here?

**Comment by james-sabel** [comment]
@Amruta-Ranade @taroface hey, I'm just checking back in. If one of you have any recommendations about this issue it will be greatly appreciated.
But I could also just make a suggestion for one of those pages I mentioned and send it through a PR.

**Comment by Amruta-Ranade** [comment]
Oh..I just realized @taroface is on vacation this week. Sorry, my bad. Feel free to open a PR with the caveat that we might have to make changes to it later. Alternatively, you can work on another issue from this list until next week: https://github.com/cockroachdb/docs/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue

**Comment by james-sabel** [comment]
No worries! ;) I guess we'll just wait until then, so we can be more assertive.

Thanks!

**Comment by taroface** [comment]
Hi @james-sabel, thank you for taking this on! I agree that the [Overview Dashboard](https://www.cockroachlabs.com/docs/v20.1/admin-ui-overview-dashboard.html) page would be appropriate for this. I think we can leave it out of the Admin UI Overview page.

**Comment by james-sabel** [comment]
@Amruta-Ranade @taroface thank you both!

I forgot to link to this issue in my commit, but I opened PR #8556 to fix it.

Let me know if you feel I should be making any changes.

**Comment by taroface** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/8556.
