### ISSUE TITLE
Redirect loop on GSSAPI doc

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#7708]
https://www.cockroachlabs.com/docs/stable/gssapi_authentication.html is the first google result for [cockroachdb gssapi], but it doesn't load. It appears to redirect to itself over and over. Other docs pages are working fine for me.

**Comment by jseldess** [comment]
Hmm, this isn't happening for me. @Amruta-Ranade, can you check as well?

**Comment by Amruta-Ranade** [comment]
Loaded correctly for me!

**Comment by bdarnell** [comment]
Huh, it's working for me now too.
