### ISSUE TITLE
release-20.1: changefeedccl: change default flush interval to 5s

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7710]
PR: https://github.com/cockroachdb/cockroach/pull/50251

From release notes:
> The default flush interval for [changefeeds](../v20.1/change-data-capture.html) that do not specify a `RESOLVED` option is now 5s instead of 200ms to more gracefully handle higher-latency sinks. [#50251][#50251] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Add with warning on memory impact if flush interval is too high

**Comment by mwang1026** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6682
