### ISSUE TITLE
Document --sql-addr flag

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7716]
## Document `--sql-addr` flag which was mentioned in https://www.cockroachlabs.com/docs/releases/v19.2.0-beta.20190930.html
https://www.cockroachlabs.com/docs/v19.2/cockroach-start.html#flags

## Description
https://github.com/cockroachdb/cockroach/pull/39305

**Comment by dbist** [comment]
@a-entin @ajwerner

**Comment by jseldess** [comment]
@dbist, we're using another issue to track this work, so I'll close this as duplicate. #4771.
