### ISSUE TITLE
Deployment tutorials: missing systemd step to start node when system reboots

### ISSUE THREAD

**Issue by dufcrule** [cockroachdb/docs#7717]
Exalate commented:

Re: [Deploy CockroachDB On-Premises (Insecure)](https://cockroachlabs.com/docs//v20.1/deploy-cockroachdb-on-premises-insecure.html)

## Issue Description

I'd like to propose a small improvement to the following doc: https://github.com/cockroachdb/docs/blob/35062a627063ca6bccd14a57da5f0329c870b14a/_includes/v20.1/prod-deployment/insecure-start-nodes.md

It seems that a final `enable` step (or a side note) could be added to make it clear that the service starts up only when you reboot the computer.

In step 9 it says: 

"Start the CockroachDB cluster:"

I would also include a final step or a side note to say something like:

"Run the command `sudo systemctl enable cockroachdb` to ensure that the service starts up whenever the system reboots."

Or something similar.

If you don't do this step you have to the start it up every time you reboot and I don't think it's the expected result for someone following the guide.

Jira Issue: DOC-585

**Comment by jseldess** [comment]
Thanks for reporting this, @dufcrule! 

@taroface, @johnrk, passing to you for triage and prioritization. Seems like an easy but important fix.
