### ISSUE TITLE
Document error codes in cockroach.log

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7722]
the customer has a tool that scrapes logs and is not capable of using regex to scrape specific node statuses (node down, node restart, etc). They need explicit codes, i.e. E000000 codes with start letter `E` or `F` for ERROR and FATAL as well as the meaning for the 6 digit code that follows the error.

**Comment by dbist** [comment]
Those are apparently not error numbers but dates

**Comment by jseldess** [comment]
@dbist, given there are no codes to scrape, should we close this?

**Comment by jseldess** [comment]
I see @bdarnell's comment in the email thread:
> Those six digits aren't an error code, they're a date. We don't have anything like an error code in our logs.  

Closing this for now.
