### ISSUE TITLE
Document how to get 20.2 alpha version of CRDB with geospatial support up and running

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7723]
We need installation docs so users can try out early versions of the geospatial capabilities we are planning for 20.2.

Right now (July 2020), the way to do this is to run a special build from within a Docker container as follows:

1. Start the Server

```
docker run -d --name=geo --hostname=geo-host -p 26257:26257 -p 8080:8080  -v "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"  otanatcockroach/cockroachdb-geospatial start-single-node --insecure
```

2. Connect from a SQL client

3. ???

4. Profit!

Estimated scope of work:

- Add a new section to the 20.2 docs called "Geospatial something something" where this can live
- Write a bit of overview / intro text
- Write the instructions

**Comment by rmloveland** [comment]
@awoods187 FYI - let me know what you think / if you have additional opinions.  will def want your review on it, of course

**Comment by awoods187** [comment]
I think we want something like this:
Set up the binary
```SQL
docker pull otanatcockroach/cockroachdb-geospatial
docker run -d --name=geo --hostname=geo-host -p 26257:26257 -p 8080:8080  -v "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"  otanatcockroach/cockroachdb-geospatial start-single-node --insecure
```
Converting shapefile data to SQL
```SQL
Download a file (1950-2018-torn-initpoint) https://www.spc.noaa.gov/gis/svrgis/
cd ~/Downloads/1950-2018-torn-initpoint
shp2pgsql  1950-2018-torn-initpoint tornadoes | cockroach sql --insecure
shp2pgsql -help --lets you make configurations
--shapefiles dont put an SRID on a file. -s 4326 is an argument to make it lat/long.
```
Or you can load SQL data (this uses NYC data from the PostGis tutorial)
```SQL
git clone https://github.com/otan-cockroach/otan-scripts/
cd otan-scripts/geospatial/geospatial_sql
cat *sql |cockroach sql --insecure --host=localhost --port=26257
cockroach sql --insecure --host=localhost --port=26257
```
We can also highlight GeoJSON.

You can try out the PostGis tutorial except GML and KML, up to chapter 20.

**Comment by rmloveland** [comment]
@awoods187 I think I got most of this into the linked PR, let me know what you think!
