### ISSUE TITLE
Add --region flag to hosted GKE steps in Orchestrate CRDB in a Single Kubernetes Cluster doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7724]
Re: [Orchestrate CockroachDB in a Single Kubernetes Cluster](https://cockroachlabs.com/docs//v20.1/orchestrate-cockroachdb-with-kubernetes.html)

## Issue Description
for hosted GKE steps, you must pass `--region` flag otherwise command fails with

```bash
ERROR: (gcloud.container.clusters.create) One of [--zone, --region] must be supplied: Please specify location.
```

at the end of the tutorial, it asks to delete the cluster and again the steps `gcloud container clusters delete cockroachdb` will fail without `--zone` or `--region` flag.

## Suggested Resolution 
below command works
```bash
gcloud container clusters create cockroachdb --machine-type n1-standard-4 --region us-east1-c
```
 or pass `--zone`

likewise for delete cluster

`gcloud container clusters delete cockroachdb --region us-east1-c`
and/or the associated `--zone`

**Comment by taroface** [comment]
Relates to #5616.

**Comment by taroface** [comment]
This was resolved by recommending regional (not zonal) clusters.
