### ISSUE TITLE
Edit note in Step 4.6 to follow INSERT mitigation steps instead of CREATE USER

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7729]
Re: [Upgrade to CockroachDB v19.1](https://cockroachlabs.com/docs//v19.1/upgrade-cockroach-version.html)

## Issue Description
step 6 advising to create user with password for accessing Admin UI doesn't apply on versions below 19.2.5. You actually have to follow advisory https://www.cockroachlabs.com/docs/advisories/a43870.html and issue `INSERT` statement in the mitigation steps as well as rebooting each node after that to access the Admin UI.
## Suggested Resolution 
Add a note to follow mitigation steps in the tech advisory and reboot.

I would add these changes to 2.1 upgrade doc as well but being EOL, I leave it to docs for judgment.

**Comment by lnhsingh** [comment]
This is in regards to #6 of [Step. 4 Perform the rolling upgrade](https://www.cockroachlabs.com/docs/v19.1/upgrade-cockroach-version.html#step-4-perform-the-rolling-upgrade)

**Comment by dbist** [comment]
> This is in regards to # 6 of [Step 4. Perform the rolling upgrade](https://www.cockroachlabs.com/docs/v19.1/upgrade-cockroach-version.html#step-4-perform-the-rolling-upgrade)

yes except `GRANT` approach only works on 19.2.5 and up, not 19.1.11. From the advisory,
```
Starting in v19.2.5 and v20.1, no license is required any more to add more users to the admin role using the GRANT statement. Users are encouraged to upgrade and use GRANT. For deployments using previous versions, a workaround is available in the Mitigation section below.
```
