### ISSUE TITLE
Document that constraints are now eagerly validated

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#7730]
Re: [ADD CONSTRAINT](https://cockroachlabs.com/docs//v20.1/add-constraint.html)

## Issue Description

In the notes section of the add foreign key constraint, it should be noted that the database validates the foreign key constraint when it's added. There's no sign that this is happening when one does this and it's good to know the validation is happening.

**Comment by jseldess** [comment]
Looks like `NOT VALID` still needs to be documented as well: https://github.com/cockroachdb/docs/issues/5187.

**Comment by ajwerner** [comment]
I stumbled into this recently. It's definitely confusing. I'd start by changing a few words in the following example and having it create the constraint `NOT VALID`.

https://www.cockroachlabs.com/docs/v21.1/validate-constraint#examples

**Comment by jseldess** [comment]
Thanks, @ajwerner. This is a known gap. I started a PR a long, long time ago and then let that go state. @ericharmeling is on it now. Closing in favor of https://github.com/cockroachdb/docs/issues/5187.
