### ISSUE TITLE
Add info about deprecated flags to upgrade release doc(s)

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7734]
Re: [Upgrade to CockroachDB v19.1](https://cockroachlabs.com/docs//v19.1/upgrade-cockroach-version.html)

## Issue Description
customer question was whether they should make a switch from the deprecated start-up scripts using `--host` and `--port` to `--listen-addr:port` and/or `--advertise-addr:port` as part of the upgrade. The only area of the docs this is mentioned is in [cockroach start](https://www.cockroachlabs.com/docs/v19.1/start-a-node.html#networking).
## Suggested Resolution 
 Change in behavior like moving from deprecated flags/commands/etc certainly should be a part of upgrade doc and/or known limitations for a particular release. I also recommend adding this section to every upgrade release doc for 19.2, 20.1, etc.

**Comment by dbist** [comment]
CC @jseldess this is another customer corner case

**Comment by ericharmeling** [comment]
IDK if I'd classify deprecated flags/features as a "known limitation". We document the deprecations on relevant pages, and on our GA release notes page for each release. For example: https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations 

If a deprecated feature results from (or is the result of) a known limitation, we should add that individual limitation to the page.

I'm going to remove the T-known-limitation flag from this issue.

**Comment by jseldess** [comment]
Yes, deprecated flags should be called out in our GA release notes, and we've been trying to do that as of 20.2. This issues is about flags deprecated several releases ago, so I think it's ok to close. But @dbist, your point is well taken.
