### ISSUE TITLE
Increase query information (when executed, why failed)

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7748]
https://cockroachlabs.atlassian.net/browse/CRDB-382

**Comment by ericharmeling** [comment]
@awoods187 

The JIRA epic for this (https://cockroachlabs.atlassian.net/browse/CRDB-382) has the feature marked a "In review/testing". Is this feature complete for v20.2? I haven't seen any docs release note issues for it.

**Comment by awoods187** [comment]
This didn't make it into 20.2

**Comment by jseldess** [comment]
Moving this to `Later`.
