### ISSUE TITLE
Transaction page/transaction timing metrics

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7749]
https://cockroachlabs.atlassian.net/browse/CRDB-401

@taroface @awoods187 
This roadmap item is on the SQL JIRA board, but I think it's more relevant to admin UI docs rather than SQL docs.

**Comment by awoods187** [comment]
Well let's talk about this in our meeting. These are definitely a part of the SQL Product Area even if they touch the webui so we'd definitely need to track them in this project. However, if they should be done by another writer who works with the UI, then we can assign it to that writer but keep it in this project. Let's talk more about it.

**Comment by jseldess** [comment]
FWIW, I think it's fine, and probably preferable, to have people working on UI docs that relate to their area.

**Comment by ericharmeling** [comment]
@awoods187 

The JIRA epic for this (https://cockroachlabs.atlassian.net/browse/CRDB-401) has the feature marked a "In review/testing". Is this feature complete for v20.2? I haven't seen any docs release note issues for it.

Also, this feature doesn't appear to be new in 20.2, as transaction timing metrics were documented as far back as 19.2 (see #5549).

**Comment by awoods187** [comment]
There is one more PR that will go in. This is completely new--we now have a transactions page. I believe @taroface is documenting this feature.

**Comment by taroface** [comment]
Closed with #8721.
