### ISSUE TITLE
Separate statement metrics by database

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7750]
https://cockroachlabs.atlassian.net/browse/CRDB-396

@taroface @awoods187 
This roadmap item is on the SQL JIRA board, but I think it's more relevant to admin UI docs rather than SQL docs.

**Comment by awoods187** [comment]
Adding this comment from the other issue:
>Well let's talk about this in our meeting. These are definitely a part of the SQL Product Area even if they touch the webui so we'd definitely need to track them in this project. However, if they should be done by another writer who works with the UI, then we can assign it to that writer but keep it in this project. Let's talk more about it.

**Comment by jseldess** [comment]
@ericharmeling, it's ok that multiple writers will start touching UI docs. This is similar to CC, where writers are contributing to docs depending on the product area. Let's have you try documenting UI changes coming from your area. You can discuss and coordinate with @taroface.

**Comment by ericharmeling** [comment]
@awoods187 

The JIRA epic for this (https://cockroachlabs.atlassian.net/browse/CRDB-396) has the feature marked a "In review/testing". Is this feature complete for v20.2? I haven't seen any docs release note issues for it.

**Comment by awoods187** [comment]
This didn't make it into 20.2. In Jira, I asked @solongordon  to update us on the status of the backend.

**Comment by jseldess** [comment]
Moving this to the `Later` milestone. We can pull it into 21.1 if relevant.

**Comment by ericharmeling** [comment]
The JIRA epic is marked as "not started", so I'm assuming this have been descoped.
