### ISSUE TITLE
Remove remaining high-latency items from "overhead" bucket and differentiate them

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7752]
https://cockroachlabs.atlassian.net/browse/CRDB-402

@taroface @awoods187 
This roadmap item is on the SQL JIRA board, but I think it's more relevant to admin UI docs rather than SQL docs.

**Comment by awoods187** [comment]
Adding this comment from the other issue:
>Well let's talk about this in our meeting. These are definitely a part of the SQL Product Area even if they touch the webui so we'd definitely need to track them in this project. However, if they should be done by another writer who works with the UI, then we can assign it to that writer but keep it in this project. Let's talk more about it.

**Comment by jseldess** [comment]
@ericharmeling, it's ok that multiple writers will start touching UI docs. This is similar to CC, where writers are contributing to docs depending on the product area. Let's have you try documenting UI changes coming from your area. You can discuss and coordinate with @taroface.

**Comment by ericharmeling** [comment]
@awoods187 

The JIRA epic for this (https://cockroachlabs.atlassian.net/browse/CRDB-402) has the feature marked a "In review/testing". Is this feature complete for v20.2? I haven't seen any docs release note issues for it.

Also, this feature appears to be documented, thanks to https://github.com/cockroachdb/docs/pull/6821 from @taroface .

**Comment by awoods187** [comment]
This is part of the enhancements to statements and transaction pages. @solongordon can you confirm this work is complete?

**Comment by taroface** [comment]
@solongordon ping on the above question!

**Comment by taroface** [comment]
Per @solongordon the fix that had been committed was later reverted. There is some work pending on this.

**Comment by awoods187** [comment]
https://github.com/cockroachdb/cockroach/issues/40675 is being worked on to re-address this
