### ISSUE TITLE
search: histograms doesn't return the same results as histogram

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7757]
Andy Woods (awoods187) commented:

Histogram will give you the search return that we are looking for with the CBO:
![image](https://user-images.githubusercontent.com/22278911/87879327-f253d580-c9b7-11ea-80bd-6653562f2924.png)

Histograms however will not:
![image](https://user-images.githubusercontent.com/22278911/87879335-fb44a700-c9b7-11ea-8684-c5c58893923b.png)

We should make sure the CBO also surfaces for histograms

**Comment by yingzhuchin** [comment]
<img width="1358" alt="Screen Shot 2020-07-20 at 10 52 56 AM" src="https://user-images.githubusercontent.com/63265176/87951912-2d690e00-ca77-11ea-96f5-eb8aa3727c44.png">

"histograms" does return Cost-Based Optimizer in search results, but it's punted to the second page. There's backlog work to figure out whether we can manually rank search results with Algolia, so this would definitely fall under that.
