### ISSUE TITLE
search:  Add "(CBO)" to cost based optimizer docs to improve search results

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7758]
Searching for CBO does not return the cost based optimizer:
![image](https://user-images.githubusercontent.com/22278911/87879362-35ae4400-c9b8-11ea-8fca-79c52ff5e268.png)

**Comment by yingzhuchin** [comment]
The quickest fix here would be to add "(CBO)" after first references to cost-based optimizer in our articles.

**Comment by lnhsingh** [comment]
@yingzhuchin Good idea. I'll update the issue

**Comment by lnhsingh** [comment]
@jseldess yeah, we can start trying synonyms but maybe that should be tracked as a separate issue / project?

**Comment by yingzhuchin** [comment]
Created https://github.com/cockroachdb/docs/issues/7759!

**Comment by yingzhuchin** [comment]
(Posting in correct Issue)

Should this be a one-way or two-way synonym? i.e. We want user to get "cost-based optimizer" if they search "CBO." Should they also get "CBO" if they search "cost-based optimizer?"

**Comment by lnhsingh** [comment]
Yeah, I'd say it's beneficial to do it two-way, but idk if "CBO" would
appear on any pages that don't also have "cost-based optimizer"

**Comment by yingzhuchin** [comment]
Thanks! This is now done.
