### ISSUE TITLE
locality preferences are case sensitive

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#7761]
Matthew Vardi (mattcrdb) commented:

We should document that the locality preferences are case sensitive.

In the case that a user sets their localities like so: --locality=datacenter=us-east-1 and --locality=datacenter=US-EAST-1 the replica preferences would see this as two separate localities and this might not be so straightforward.

I ran into this with a customer today where one of their DC locality preferences was a variation of the one they wanted (it was all lowercase)

We can probably write something here: https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html

under the `Descriptive attributes assigned to nodes` section.

cc @irfansharif just to confirm that this is correct as you are L2 this wee.

Jira Issue: DOC-593

**Comment by irfansharif** [comment]
Yup, they're case-sensitive.

**Comment by jseldess** [comment]
@lnhsingh, can you route this to the right person?
