### ISSUE TITLE
Consolidate wiki pages

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#7768]
We currently have two wiki pages that have the same information:
- https://github.com/cockroachdb/docs/wiki
- https://github.com/cockroachdb/docs/wiki/Common-Docs-Tasks

These are starting to get out of sync (mostly due to updates I've been making to one or the other page!)

**Comment by jseldess** [comment]
Oh, this is a weird mistake on my part. Please feel free to remove one. I'd suggest keeping the dedicated page called "Common Docs Tasks".
