### ISSUE TITLE
Make it visually clearer which releases are EOL on Release Support Policy Doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7775]
Re: [Release Support Policy](https://cockroachlabs.com/docs//releases/release-support-policy.html)

## Issue Description
EOL dates are implicit

## Suggested Resolution 
Provide visual guides to highlight EOL releases and dates.

**Comment by jseldess** [comment]
@dbist, I don't understand this request. Can you please explain further?

**Comment by dbist** [comment]
I'd like to see a red banner across the branches that were determined to be EOL, today we're seeing 2.0, 2.1, 19.1, 19.2, 20.1 but there's no indication which ones are EOL except for reading each column. Adding a strike through or a red line across the EOL releases would be quick and to the point.

**Comment by lnhsingh** [comment]
@taroface - This is probably a quick update like Artem suggests, but feel free to loop in Lucia if you'd like design help

**Comment by taroface** [comment]
@dbist I think using an asterisk might be clearest:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/8740013/88982850-5bc8c380-d297-11ea-8c25-1e64dc9af1b0.png">

What do you think?

**Comment by jseldess** [comment]
I like this. I think some kind of key (like you have) is key.
