### ISSUE TITLE
Make replication zone constraints error more visible in docs

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#7781]
According to the documentation [here](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-zone-variables) about the `constraints` variable:

> To prevent hard-to-detect typos, constraints placed on store attributes and node localities must match the values passed to at least one node in the cluster. If not, an error is signalled.

Please make the error more visible in the documentation by mentioning something like:

"The preferred way to prevent this error is to configure Replication Zones constraints after at least one active node in the cluster matches the passed in values. The `constraints` variable is evaluated when the ALTER...CONFIGURE ZONE statement is run."

**Comment by zuliatowoade** [comment]
Hello, I will like to work on this issue. Can you please assign it to me? Thank you.

**Comment by Amruta-Ranade** [comment]
Hi @zuliatowoade ..we are asking folks to work on one issue at a time. Feel free to check back after you work on #8018

**Comment by dgabriel123** [comment]
Hello @Amruta-Ranade, may I work on this issue?

**Comment by Amruta-Ranade** [comment]
@dgabriel123 Yep!

**Comment by dgabriel123** [comment]
Thanks @Amruta-Ranade! By the way, there are 5 versions of the file. Should I edit all or just 19.2 + 20.1 + 20.2?

**Comment by Amruta-Ranade** [comment]
Only 19.2, 20.1, 20.2 :)

**Comment by dgabriel123** [comment]
> Only 19.2, 20.1, 20.2 :)

### OK thanks! I have a question about linking from an include file. I'm adding [`ALTER ... CONFIGURE ZONE`](configure-zone.html) to variables.md, but I think because the file is an include, the link is sending me to a 404 page when I click it in Preview mode. Does this URL change once the file is updated on the back end, or should I maybe use an absolute link (https://www.cockroachlabs.com/docs/v20.1/configure-zone) instead?

Sorry if this was confusing.

**Comment by dgabriel123** [comment]
> Only 19.2, 20.1, 20.2 :)

thanks @Amruta-Ranade, ready for review.

**Comment by florence-crl** [comment]
This docs issue was originally created due to zendesk [ticket 5880](https://cockroachdb.zendesk.com/agent/tickets/5880).

**Comment by Amruta-Ranade** [comment]
Thanks for helping me understand the issue, @florence-crl !

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8537
