### ISSUE TITLE
Publish list of untested and unsupported drivers ORMs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7784]
Would we consider publishing a list of drivers we haven’t tested yet or even drivers we know are not yet supported? Developers searching the docs for specific driver support would at least get insight.
I’m asking because I just noticed this Docs CSAT submission where someone was looking for ODBC and obviously didn’t find it. We've heard several times that devs prefer to know what's not going to work or what's going to work differently.

<img width="396" alt="Screen Shot 2020-07-24 at 10 54 43 PM" src="https://user-images.githubusercontent.com/15893490/88550007-feaae480-cfee-11ea-9341-bbcd23a2623a.png">

cc @vy-ton, @ericharmeling, @awoods187

**Comment by awoods187** [comment]
I'll defer to @vy-ton and @ericharmeling  on this one.

**Comment by vy-ton** [comment]
@ericharmeling With the addition of the community page, I would like to close this. Now that the community page exists, we can favor mentioning tools with no commitment to support

**Comment by ericharmeling** [comment]
> I would like to close this

SGTM!
