### ISSUE TITLE
Change sslmode in example(s) on GSSAPI Authentication (Enterprise) doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7785]
Re: [GSSAPI Authentication (Enterprise)](https://cockroachlabs.com/docs//v20.1/gssapi_authentication.html)

## Issue Description
in our doc, we recommend to use the following connection string

```bash
psql "postgresql://localhost:26257/defaultdb?sslmode=require" -U carl
```

Problem with this is that `sslmode=require` is susceptible to MITM attack. It is advisable to use `sslmode=verify-ca` or better yet `sslmode=verify-full` instead.

## Suggested Resolution 
Change the example to fit the following
```bash
psql "postgresql://localhost:26257/defaultdb?sslmode=verify-full&sslrootcert=/certs/ca.crt" -U carl
```

**Comment by zuliatowoade** [comment]
Hello, I will like to work on this issue. Can you please assign it to me? Thanks

**Comment by dgabriel123** [comment]
Hey @Amruta-Ranade , is this issue still open?

**Comment by zuliatowoade** [comment]
@Amruta-Ranade #8018 has been merged. Can I take this on now? Thanks

**Comment by Amruta-Ranade** [comment]
Yep!

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8632
Thanks, @zuliatowoade !
