### ISSUE TITLE
Embedding tutorial videos in appropriate docs pages

### ISSUE THREAD

**Issue by dankellycockroach** [cockroachdb/docs#7804]
Hey @ericharmeling,

Recently we made some tutorial videos that would fit nicely in the corresponding docs pages. Jesse mentioned that there is not an existing convention for how to make this happen. But maybe we can invent one!?

Anyways, here is what I'm thinking:

Embed this Schema Migration demo ( https://youtu.be/xz4j5tU0ZRU) into this docs page: https://www.cockroachlabs.com/docs/stable/flyway.html

Here are a couple existing examples of how that should look:

• https://www.cockroachlabs.com/docs/v20.1/topology-duplicate-indexes.html
• https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-upgrade-to-v20.1.html 
• https://www.cockroachlabs.com/docs/stable/demo-automatic-cloud-migration.html

If this goes well, I have a list of other videos to embed (https://docs.google.com/spreadsheets/d/1hdXbwPtVrcUHr6HMsQ6WUSkxBBdpdbK4vck6uSCgO1w/edit?usp=sharing). And there will be more on the way. But I don't want to get too far ahead of myself....

**Comment by ericharmeling** [comment]
@dankellycockroach 
Thanks for opening this issue! And thanks for sharing your doc - it's awesome. 

I think I can add these videos pretty quickly. Expect a PR soon!
