### ISSUE TITLE
Build a Node.js App with CockroachDB and the Node.js pg Driver Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7805]
Re: [Build a Node.js App with CockroachDB and the Node.js pg Driver](https://cockroachlabs.com/docs//v20.1/build-a-nodejs-app-with-cockroachdb.html)

## Issue Description
Sample app `basic-sample.js` will produce multiple lint warnings for javascript. 

## Suggested Resolution 
running the following commands against `basic-sample.js` will address most of them

```js
npm install standard --save-dev
RUN npx standard --fix *.js
```

sample output of errors can be found [here](https://github.com/dbist/cockroach-docker/issues/36)

**Comment by vy-ton** [comment]
We're promoting Javascript in 21.1 so should fix this

**Comment by ericharmeling** [comment]
Recently rewrote/linted this app... https://github.com/cockroachlabs/hello-world-node-pg/pull/1

**Comment by vy-ton** [comment]
@ericharmeling Based on your last comment, can we close this?

**Comment by ericharmeling** [comment]
> @ericharmeling Based on your last comment, can we close this?

I believe so.
