### ISSUE TITLE
Contribute dropdown gets cut off on pages with longer titles

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7806]
Re: [Build a Node.js App with CockroachDB and the Node.js pg Driver](https://cockroachlabs.com/docs//v20.1/build-a-nodejs-app-with-cockroachdb.html)

## Issue Description
Contribute button is cut off

## Suggested Resolution 
Fix the contribute window

![image](https://user-images.githubusercontent.com/461296/88724021-cba04800-d0f7-11ea-8c81-89bf51d2ff41.png)

**Comment by lnhsingh** [comment]
Seems like this happens on docs with titles that wrap

**Comment by yingzhuchin** [comment]
This was previously fixed with https://github.com/cockroachdb/docs/pull/7189, but that fix seems to have been accidentally(?) undone by https://github.com/cockroachdb/docs/pull/7776. Will repush the fix.

**Comment by jseldess** [comment]
Sorry about that, @yingzhuchin!

**Comment by yingzhuchin** [comment]
No worries! I figured it was an accident but just to make sure. Thank you!
