### ISSUE TITLE
document Admin UI notifications

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#7809]
Important production metrics will be surfaced as notifications in the Admin UI.

- Document notification types
- Document how notifications are enabled and responded to
- Provide copy for notification descriptions and help text, as well as docs links

Roadmap issue: https://cockroachlabs.atlassian.net/browse/CRDB-915

**Comment by jseldess** [comment]
This was moved to "Later" in Jira. Closing this for now. It will come back once it's planned for a release.
