### ISSUE TITLE
Inaccurate reference to two-phase commit in distributed transactions overview

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#781]
https://www.cockroachlabs.com/docs/distributed-transactions.html includes a bullet point that says "Efficient two phase commit", but as far as I'm aware, CockroachDB specifically does not use two-phase commit anywhere (at least not a traditional two-phase commit protocol). Unless I'm mistaken, we should probably remove that bullet from our public docs.

@tamird for confirmation
@jseldess

**Comment by jseldess** [comment]
Not sure why that's there, to be honest. I think it may have been leftover from some early web copy.  Happy to remove, with confirmation from @tamird.

**Comment by a-robinson** [comment]
I mean, you could frame our transaction protocol as having two phases involved in committing, but that seems like a bit of a stretch.

**Comment by tamird** [comment]
What is that bullet list even _of_?

> - Easily build consistent applications // as a developer, I care about this
> - Optimistic concurrency without locking // as a developer, I do not care about this
> - Efficient two phase commit // as a developer, I do not care about this
> - Serializable default isolation level // as a developer, I care about this

Perhaps all the "I don't care about this" bullets can be removed, and we could clarify what it is we're enumerating there.

I also agree that the term "two phase commit" is misplaced here, and should definitely be removed, regardless of opinion on what I mention above.

**Comment by jseldess** [comment]
We're going to completely replace/overhaul these pages, probably this quarter, so for now, I'll just remove the bullet on `two phase commit`.

cc @jess-edwards, since this language was originally on the main site.

**Comment by jess-edwards** [comment]
@jseldess Sounds like the right call. Better to have this page at least be not wrong while we're building out revised content.
