### ISSUE TITLE
SSO in Admin UI

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#7812]
SSO will be implemented for the Admin UI.

- Document new auth flow
- Update any existing sign-on procedures, if necessary

Roadmap issue: https://cockroachlabs.atlassian.net/browse/CRDB-211
config and permissions docs: https://docs.google.com/document/d/1K7X1OBqlOAMsy12NlEOKu_wxXpu6TXa53L3bFJZYiIE/edit#
how-to steps: https://github.com/cockroachdb/cockroach/pull/52609

**Comment by jseldess** [comment]
2 related release notes:

PR: https://github.com/cockroachdb/cockroach/pull/54659

> Added ability to login via [OIDC](https://openid.net/connect/) provider. [#54659][#54659] {% comment %}doc{% endcomment %}
>
> Added ability to login via [OIDC](https://openid.net/connect/) provider: Operators can now configure a single OIDC authentication provider using a collection of [cluster settings](../v20.2/cluster-settings.html) that can provide authentication for users into **the Admin UI only** (not for SQL). The user must exist as a SQL user in the database for the authentication to work. [#54659][#54659] {% comment %}doc{% endcomment %}
