### ISSUE TITLE
sql/kv: warn users about long-running transactions

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7815]
Customers have recently encountered problems with long-running transactions. Imagine a company that has a long-running bulk insert transaction (e.g., write transaction) that is causing contention for short-lived transactions (e.g., read + writes) that service their UI. CockroachDB does not handle long-running transactions well often resulting in [RETRY_COMMIT_DEADLINE_EXCEEDED](https://www.cockroachlabs.com/docs/v20.1/transaction-retry-error-reference.html#retry_commit_deadline_exceeded) or ["transaction deadline exceeded" and error code 40001](https://www.cockroachlabs.com/docs/v20.1/common-errors.html#transaction-deadline-exceeded) as well as generally poor performance. We counsel our customers to break these transactions into smaller batches so that they will complete quickly. 

Long-running transactions can be particularly problematic when they are write transactions that block shorter-lived transactions like the ones being surfaced by the UI above. We need to encourage companies to break up their bulk insert transaction into smaller transactions so that they won't cause contention, and therefore retries and poor performance on their other transactions. 

It's also fortuitous timing because we plan to add a transactions page in 20.2 which will surface long-running transactions making it easier to find and troubleshoot these types of problems.

**Comment by awoods187** [comment]
I'm ccing @rmloveland into this issue (even though its the SQL product area) because it touches the KV engineering team and I think he has the most familiarity with the transaction model.

**Comment by rmloveland** [comment]
Related: now that the work for #5476 Transaction retry guidance and error reference is ~done (for now), we have the [Transaction retry error reference](https://www.cockroachlabs.com/docs/dev/transaction-retry-error-reference.html), which includes info about how to handle `RETRY_COMMIT_DEADLINE_EXCEEDED` in particular, for which we have the following guidance (tl;dr: shrink transaction running time, OR tweak your closed ts settings, if you can):

> The RETRY_COMMIT_DEADLINE_EXCEEDED error is one case where the standard advice to add a retry loop to your application may not be advisable. A transaction that runs for long enough to get pushed beyond its deadline is quite likely to fail again on retry for the same reasons. Therefore, the best thing to do in this case is to shrink the running time of your transactions so they complete more quickly and do not hit the deadline.
> If you encounter case 3 above, you can increase the kv.closed_timestamp.target_duration setting to a higher value. Unfortunately, there is no indication from this error code that a too-low closed timestamp setting is the issue. Therefore, you may need to rule out cases 1 and 2 (or experiment with increasing the closed timestamp interval, if that is possible for your application - see the note below).
