### ISSUE TITLE
cli/start: make SIGTERM idempotent

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7822]
PR: https://github.com/cockroachdb/cockroach/pull/50539

From release notes:
> Previously, issuing a `SIGTERM` signal twice or after another signal initiated a hard shutdown for a node. Now the first `SIGTERM` signal initiates a graceful shutdown and further occurrences of `SIGTERM` are ignored. To initiate a hard shutdown, issue `SIGINT` two times (or issue a `SIGINT` signal once after a `SIGTERM` signal). [#50539][#50539] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@bdarnell Should we include information on performing a hard shutdown with `SIGINT` in our node shutdown steps (e.g. https://www.cockroachlabs.com/docs/v20.1/upgrade-cockroach-version.html#step-4-perform-the-rolling-upgrade)?

**Comment by bdarnell** [comment]
`SIGINT` basically means `ctrl-c`. If you're running in a terminal you'd send a SIGINT by pressing ctrl-c (which we already have in the docs); in other environments you'd use SIGKILL for a hard shutdown. I don't think we need any doc updates for this change.
