### ISSUE TITLE
sql: Switch BACKUP statement to use allowed options

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7823]
PR: https://github.com/cockroachdb/cockroach/pull/50723

From release notes:
> Specifying the same option multiple times in the `WITH` clause of the [`BACKUP`](../v20.2/backup.html) statement now results in an error message. Additionally, quoted option names are not allowed anymore. [#50723][#50723] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Related to #7927

**Comment by lnhsingh** [comment]
Closing - no docs updates needed.
