### ISSUE TITLE
geos: dlopen libgeos.so before libgeos_c.so

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7826]
PR: https://github.com/cockroachdb/cockroach/pull/50362

From release notes:
> The docker image available with CockroachDB now includes the GEOS files required to work with [Geospatial types](https://www.cockroachlabs.com/docs/v20.2/spatial-data.html) in CockroachDB. [#50362][#50362] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This is implied by what is in the docs already
