### ISSUE TITLE
changefeedccl: change default flush interval to 5s

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7829]
PR: https://github.com/cockroachdb/cockroach/pull/49770

From release notes:
> The default flush interval for [changefeeds](../v20.2/change-data-capture.html) that do not specify a `RESOLVED` option is now 5s instead of 200ms to more gracefully handle higher-latency sinks. [#49770][#49770] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6682
