### ISSUE TITLE
cli: default host to "localhost" in client commands 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#783]
PR: https://github.com/cockroachdb/cockroach/pull/10134

@sploiselle, this ties into issues you were having with secure deployments, I think.

**Comment by sploiselle** [comment]
@asubiotto Does cockroachdb/cockroach#10134 change  the behavior of the `--host` flag in a way that it no longer listens on all interfaces? ([Here's how the docs talk about the default `--host` behavior](https://www.cockroachlabs.com/docs/start-a-node.html#flags))

**Comment by jseldess** [comment]
@sploiselle, I think the line in this week's release notes answers this: 

> The `--host` argument now defaults to `localhost` in both secure and insecure modes. #10134 

I can update the flag description as part of pulling together release notes, though, so I can take this one.

**Comment by sploiselle** [comment]
@jseldess I think there's a level of complication here because it wasn't listening on `localhost` previously, despite the documentation saying it listened on all interfaces. I might be overthinking it, though.

**Comment by bdarnell** [comment]
This is a client side change. It affects the host that client commands connect to, but doesn't change (or isn't supposed to change) what the server listens on.

**Comment by jseldess** [comment]
Ah, right, @bdarnell, as stated in the description. Sorry if I caused confusion, @sploiselle. But I do think this ties into one of the problems you were having on secure clusters. I think you said that, when trying to start the sql shell on the same machine as a node, you had to explicitly set `--host`. Now you shouldn't, if I understand correctly.
