### ISSUE TITLE
backupccl: allow for remapping backed up types to existing types

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7830]
PR: https://github.com/cockroachdb/cockroach/pull/50349

From release notes:
> [`RESTORE`](../v20.2/restore.html) now remaps user-defined types within the backup to existing types in the cluster. [#50349][#50349] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I don't think any docs updates are needed. Closing.
