### ISSUE TITLE
importccl: add support for SQLFns in pgdump

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7840]
PR: https://github.com/cockroachdb/cockroach/pull/50850

From release notes:
> Added support for `AddGeometryColumn` and other functions that mutate schema in `IMPORT PGDUMP`. [#50850][#50850] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
This relates to geospatial. @rmloveland do you want to take?

**Comment by rmloveland** [comment]
> This relates to geospatial. @rmloveland do you want to take?

Yes!  I added it to my various things, not sure how to remove from your I/O board tho.

**Comment by lnhsingh** [comment]
Removed, thanks!

**Comment by rmloveland** [comment]
Closing since support for this function is implied by the fact that `shp2pgsql` works as shown in https://www.cockroachlabs.com/docs/dev/migrate-from-shapefiles.html and elsewhere
