### ISSUE TITLE
opt: add rules to eliminate a do-nothing join under a Project

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7846]
PR: https://github.com/cockroachdb/cockroach/pull/49788

From release notes:
> The [optimizer](../v20.2/cost-based-optimizer.html) can now remove an unnecessary [join](../v20.2/joins.html) from the input of a `Project` operator. [#49788][#49788] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs to be documented. 
@DrewKimball Please reopen if you disagree. :)
