### ISSUE TITLE
opt: add rule to fold limits

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7847]
PR: https://github.com/cockroachdb/cockroach/pull/49931

From release notes:
> The [optimizer](../v20.2/cost-based-optimizer.html) can now fold two `Limit` operators together. [#49931][#49931] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs to be documented. 
@DrewKimball Please reopen if you disagree. :)
