### ISSUE TITLE
Edit language around strong consistency

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#785]
In our FAQ on [how CockroachDB is strongly-consistent](https://www.cockroachlabs.com/docs/frequently-asked-questions.html#how-is-cockroachdb-strongly-consistent), and in `strong-consistency.md`, we say: 

> CockroachDB replicates your data multiple times and guarantees consistency between replicas using the Raft consensus algorithm, a popular alternative to Paxos. A consensus algorithm guarantees that any majority of replicas together can always provide the most recently written data on reads. Writes must reach a majority of replicas (2 out of 3 by default) before they are considered committed. If a write does not reach a majority of replicas, it will fail, not be permanent, and will never be visible to readers. **This means that clients always see a consistent view of your data (i.e., no stale reads).**

As @spencerkimball mentioned in Slack, if "consistent" implies that "every observer must see the same order of events", the last sentence above may be misleading since, as aphyr mentions, "transactions on disjoint keys are observed contrary to real-time order".

So the short-term proposal is to change that last sentence to:

> This means that clients always see serializable consistency when viewing data (i.e., stale reads are not possible).

@bdarnell, @petermattis, thoughts?

**Comment by petermattis** [comment]
Sounds good to me.

**Comment by spencerkimball** [comment]
Hmm now that I see the rest of that context maybe we shouldnt change
anything. Talking about serializability there doesn't really make sense. We
need another FAQ explaining that we provide serializable histories.
