### ISSUE TITLE
sql: timestamp should accept DB2 formatted timestamps

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7850]
PR: https://github.com/cockroachdb/cockroach/pull/50011

From release notes:
> The `pgdate` util can now parse `db2` formatted timestamps. This can be used to import `db2` dumps. [#50011][#50011] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Not sure if this will needs docs updates but I'll take this one.

**Comment by lnhsingh** [comment]
Closing for now - doesn't seem like docs updates are needed.
