### ISSUE TITLE
opt: track regclass dependencies in views

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7855]
PR: https://github.com/cockroachdb/cockroach/pull/50213

From release notes:
> `RegClass` expressions are now tracked as dependencies in views. For example, `CREATE VIEW v AS SELECT 't'::regclass;` will now add a dependency on table `t` for view `v`. [#50213][#50213] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs to be documented, as this seems like expected behavior. Also, we do not document `regclass` casts.

@rytaft 

Please re-open if you disagree.
