### ISSUE TITLE
sql: add a view dep on sequence string arguments

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7856]
PR: https://github.com/cockroachdb/cockroach/pull/50103

From release notes:
> Sequences passed as a string argument into views are now tracked as a dependency. For example, `CREATE VIEW v AS SELECT nextval('s')` will now add a dependency on sequence `s`. [#50103][#50103] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't change expected or documented behavior. I believe https://github.com/cockroachdb/cockroach/pull/50103 fixes a bug where views were not properly tracking sequence dependencies (https://github.com/cockroachdb/cockroach/issues/24556).
