### ISSUE TITLE
cli: delete `cockroach node decommission --wait=live`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7867]
PR: https://github.com/cockroachdb/cockroach/pull/49666

From release notes:
> `cockroach node decommission --wait=live` is no longer supported. It was deprecated in an earlier release. [#49666][#49666] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@taroface, please add a comment if this isn't closed by a PR.

**Comment by taroface** [comment]
This value was already not documented.
