### ISSUE TITLE
cli: deprecate `cockroach quit`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7868]
PR: https://github.com/cockroachdb/cockroach/pull/49668

From release notes:
> `cockroach quit` is now deprecated. Use the subcommands for [`cockroach node`](../v20.2/cockroach-node.html) instead, and use termination signals to quit the `cockroach` process. [#49668][#49668] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
This was addressed with #7304.
