### ISSUE TITLE
cli: add support for `cockroach dump` to operate on UDTs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7869]
PR: https://github.com/cockroachdb/cockroach/pull/49808

From release notes:
> Allowed [`cockroach dump`](../v20.2/cockroach-dump.html) to dump tables and databases that contain user-defined types. [#49808][#49808] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I don't think any docs updates are needed. Closing.
