### ISSUE TITLE
ui: remove compactor queue graphs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7876]
PR: https://github.com/cockroachdb/cockroach/pull/50245

From release notes:
> The `Queues` dashboard in the Admin UI no longer shows a `Compaction Queue` graph, and the `Queue Processing Failures` and `Queue Processing Times` graphs no longer include the `Compaction` queue metrics. [#50245][#50245] {% comment %}doc{% endcomment %}

**Comment by piyush-singh** [comment]
The Queues dashboard page is not documented, so this does not require any net new work.
