### ISSUE TITLE
ui: Typo for std deviation labels on Network Latency page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7878]
PR: https://github.com/cockroachdb/cockroach/pull/50275

From release notes:
> Changed the label for `std deviation` from `<` to `>` for positive values. [#50275][#50275] {% comment %}doc{% endcomment %}

**Comment by piyush-singh** [comment]
We may want to update the screenshot on this page to fix the typo: https://www.cockroachlabs.com/docs/v20.1/admin-ui-network-latency-page.html

**Comment by dgabriel123** [comment]
Hello @Amruta-Ranade @taroface I would be happy to change the screenshot. Just to clarify: [this](https://d33wubrfki0l68.cloudfront.net/7e9b4a977b17d24f6a69d4deca13824a85cb104c/3741c/docs/images/v20.1/admin_ui_network_latency_collapsed_nodes.png) is the screenshot that needs to be changed, correct?

**Comment by dgabriel123** [comment]
> We may want to update the screenshot on this page to fix the typo: https://www.cockroachlabs.com/docs/v20.1/admin-ui-network-latency-page.html

![admin_ui_network_latency_collapsed_nodes](https://user-images.githubusercontent.com/65077020/95680706-8beee580-0ba9-11eb-99cd-21382d488251.png) How does this look?

**Comment by Amruta-Ranade** [comment]
cc @taroface

**Comment by taroface** [comment]
@dgabriel123 Thanks for picking this up! This has actually changed beyond the description in the ticket:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/8740013/95775777-047ca180-0c91-11eb-8f78-fe501968bb2a.png">

I would suggest replacing the screenshot you linked with the above image. Note that this should be present in both the v20.1 and v20.2 docs.

**Comment by dgabriel123** [comment]
> @dgabriel123 Thanks for picking this up! This has actually changed beyond the description in the ticket:
> 
> <img alt="image" width="733" src="https://user-images.githubusercontent.com/8740013/95775777-047ca180-0c91-11eb-8f78-fe501968bb2a.png">
> 
> I would suggest replacing the screenshot you linked with the above image. Note that this should be present in both the v20.1 and v20.2 docs.

Thank you @taroface . I created a PR with the updated screenshot, but I am getting a TeamCity error. Do you know what might be happening?

**Comment by taroface** [comment]
@dgabriel123 The build error in TeamCity does not make sense to me. Your update looks good. Would you be able to try pulling from master, rebasing your branch on master, and pushing your changes again? Let me know if you're not sure what that means.

**Comment by dgabriel123** [comment]
> @dgabriel123 The build error in TeamCity does not make sense to me. Your update looks good. Would you be able to try pulling from master, rebasing your branch on master, and pushing your changes again? Let me know if you're not sure what that means.

I'm only somewhat acquainted with rebase, would you mind elaborating please?

**Comment by taroface** [comment]
Fixed by #8666.
