### ISSUE TITLE
The SELECT doc page is confusing the forest for the tree

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#788]
I have reviewed the SELECT doc page as if I was a newcomer to SQL and overall I am not too fond of the impression it gives me: namely, the first thing I see is this humongous syntax diagram and parameter table where everything is listed, both important and less important things side by side, overwhelming me.

There is some elegance/beauty in the way SELECT was designed and this is currently completely missing from this page. Namely, although SELECT looks like just one statement it is a composition of multiple _separate_ processing steps in a pipeline, which can be enabled/disabled separately to achieve all kinds of queries:
1. data source combination, including joins: FROM
2. filtering: WHERE
3. grouping and aggregation: GROUP BY 
4. filtering (again): HAVING
5. windowing
6. result deduplication: DISTINCT
7. set operations: UNION / INTERSECT / EXCEPT
8. sorting: ORDER BY
9. result truncation: LIMIT

The data produced as output by each step is consumed as input by the step after that. To understand (and thus explain) each step it is possible to completely ignore the steps that come afterwards, and sometimes even the steps before.

Now what makes SQL difficult is that these steps do not all correspond 1-to-1 to specific keywords in the grammar.  Some do, for example LIMIT. However grouping and aggregation is determined either by the the presence of aggregate function in "render expressions" before FROM, or the presence of the GROUP BY clause, or both. Then you have the keyword DISTINCT, which has a completely different meaning depending on whether it appears just after SELECT (this enable the 6th step above) or within the argument list of an aggregation function (this merely changes the behavior of aggregation in step 3)

Even worse, the order of the elements in the syntax is very poorly related to the order of the processing steps above.

Therefore, in order to construct an explanation/tutorial of SELECT it is not wise to start with the syntax and then try to make sense of it. Because when you do this you probably can't capture the flow of data through the 7 steps, and likely won't get in which order the data is processed.

Incidentally the PG documentation for SELECT achieves this by placing an overview of these processing steps first thing at the start of the Description section. I'd certainly recommend something like that in our doc. Also, the PG syntax presentation, albeit primitive, (attempts to) shows the corresponding different clauses on separate lines which clarifies visually. 

Only after that we can introduce all the examples, which are good.

**Comment by jseldess** [comment]
Thanks for this detailed, thoughtful feedback @knz. 

@sploiselle, we should discuss next steps with `SELECT` sometime soon.

**Comment by sploiselle** [comment]
Thanks, @knz –– very clearly articulated. I can see pretty clearly how to integrate your feedback into the doc.

@jseldess Sounds good!

**Comment by jseldess** [comment]
@knz did a major refactor of our select docs some time ago, resulting in:

- https://www.cockroachlabs.com/docs/stable/select-clause.html
- https://www.cockroachlabs.com/docs/stable/selection-queries.html
- https://www.cockroachlabs.com/docs/stable/query-order.html
- https://www.cockroachlabs.com/docs/stable/limit-offset.html
- https://www.cockroachlabs.com/docs/stable/subqueries.html

and a few other pages. I'd say the forest and tress are both more visible at this point, so I'm closing this. That's not to say there aren't more opportunities, but I believe the core of this issue is resolved.

**Comment by knz** [comment]
it is! thanks
