### ISSUE TITLE
Make Follower Reads non-experimental

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7887]
Currently, various parts of the Follower Reads UX are "experimental", and/or can be difficult to get working properly.  There is engineering work happening to move the feature into fully-supported, non-experimental status.  We will need to document the output of that engineering work.

Estimated scope of work:

- Remove `experimental_` from the name of the timestamp-generating function that users are expected to call
- Document architecture updates related to this work, if any
- Document user-facing behavior changes related to this work as needed.  In particular, we may need to revise the FR docs to remove the current limitations/caveats (and perhaps add others, not sure - investigation is needed).

Related issues:

- #5210
- #6808
- #6793
- #5024
- #6753

**Comment by jseldess** [comment]
@rmloveland, linking https://github.com/cockroachdb/docs/issues/8166 with this roadmap issue.

**Comment by rmloveland** [comment]
@andreimatei, it looks like #8816 (which you are about to review) will also close this issue, but to confirm:

AFAICT dropping the `experimental_` from the function name is the only user-facing docs change that is needed to make FR "not experimental anymore".  The FR-related badnesses you mention in https://github.com/cockroachdb/cockroach/pull/52359 are all fairly low-level things that were/are not mentioned in the user documentation.

Do you agree with the above assessment?

**Comment by andreimatei** [comment]
Correct
