### ISSUE TITLE
Update copy on CockroachCloud Upgrade Policy page

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#7892]
New copy is highlighted in [this doc](https://docs.google.com/document/d/1_TQZgz5C3RE3F6zdv9ABXjrJ-KTRkRqBHzbt46wfCgc/edit#).

Feel free to tweak the language -- the gist is that SREs won't support older versions. I wasn't sure if we mention SRE much in docs so I used "24/7 support" & "SLA guarantees" as a proxy

**Comment by emily-horing** [comment]
Hey @Amruta-Ranade let me know if you have any questions about this issue. I'd like to get it done sooner rather than later so we can send a reminder/notification email to users that their support will be changing

**Comment by Amruta-Ranade** [comment]
Oh, I didn't know this was a priority. Will try to get to it this week.

**Comment by emily-horing** [comment]
Thanks!
