### ISSUE TITLE
general: add visible anchor links on session variable pages

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7897]
Andy Woods (awoods187) commented:

There is no way to weblink to a particular [session or cluster setting variable](https://www.cockroachlabs.com/docs/v20.1/set-vars.html). Consider if I want to link the information from this doc directly to a customer:

![image](https://user-images.githubusercontent.com/22278911/89057444-a72cb180-d32b-11ea-87b1-5d9b6671cc62.png)

cc @jseldess for triage 

Jira Issue: DOC-616

**Comment by lnhsingh** [comment]
Thanks for filing @awoods187! I'm triaging incoming docs issues now, so you can cc me on any future issues.
