### ISSUE TITLE
Document how to install a CockroachDB with spatial capabilities

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7916]
Right now, we are punting to Docker for the 20.2 alphas.

For the 20.2 GA release, we will need to get clear on exactly what
this new install process entails. Since we are losing the "download
one binary and go" experience, we must document the necessary steps
while trying to keep it as simple as possible.

We also need to be clear in the docs about what exactly CockroachDB
will do if you run a `cockroach` binary that cannot find the C
libraries necessary for geospatial support.  E.g. will everything run
"fine" as long as you don't try any spatial stuff?  Will it return an
error if you try to load spatial data, or call a spatial function? Are
there situations where it will crash? Will monkeys fly out of your
nose? Etc.

**Comment by rmloveland** [comment]
@otan what is the best way to get started on this? Is there a doc written up anywhere?  Is there something in the CockroachDB Makefile I should look at?

I am in that strange but not unfamiliar state of being unable to build CockroachDB from the main branch on my machine right now, for $MYSTERIOUS_REASON

**Comment by otan** [comment]
the RFC should have mention the new way (see update on https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:rfc_update)
it is available on docker by default.
