### ISSUE TITLE
release-20.1: sql: don't write to slow query log if disabled

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7921]
PR: https://github.com/cockroachdb/cockroach/pull/50941

From release notes:
> CockroachDB no longer writes to slow query log unless explicitly enabled. [#50941][#50941] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't require docs, as the cockroachdb PR is a bug fix.
