### ISSUE TITLE
Backup Scheduling

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7927]
Users can issue a single statement to schedule a cadence for CockroachDB backups, and CockroachDB will automatically execute the backups on that schedule without requiring external intervention.

Currently, CockroachDB doesn't have any internal job scheduling mechanism. This means that all production environments need to deploy an external system that issues SQL statements (e.g. a backup script running on a cron job). This commonly-reported pain point takes unnecessary effort to set up, and undermines CockroachDB's  promise of operational simplicity.

Backup scheduling includes:
- `CREATE` schedule backup
- Controls (Pause, resume, drop)
- Introspection (`SHOW SCHEDULE`, `SHOW JOBS FOR schedule X`)
- Monitoring and alerting (especially, Prometheus counters with alerting in yaml)
- New syntax: `BACKUP INTO`, `INTO LATEST`
- Backup history file
- New syntax: `WITH detached`

cc: @mwang1026 @miretskiy

**Comment by mwang1026** [comment]
If you create a schedule that includes both FULL and INCREMENTAL backups, we actually create two scheduled under the hood.

**Comment by lnhsingh** [comment]
On schedule name uniqueness/duplicate confusion: 
- migration to rename `name` to `label` 
- use the same value for the full and inc schedules, i.e. either what they provide or the autogenerated, just with no appended suffix for the second schedule. Using the same value on both means you can now do `PAUSE SCHEDULES SELECT... label = 'foo'` since both have `foo` as their label. Renaming from `name` to something like `label` that does not carry the connotation of uniquely identifying should avoid the need to suffix it and associated confusion.

**Comment by mwang1026** [comment]
A few more notes:
* Changing the file structure to be year / month / day subdirectories when you use the `INTO` syntax
* We now support `SHOW BACKUPS IN` and `SHOW BACKUP <full backup subdirectory> IN <backup collection directory>`. The first lists the full backups' subdirectories, the second is effectively a `SHOW BACKUP` for a particular full backup and its incrementals.

**Comment by mwang1026** [comment]
New option: `ignore_existing_backups` lets you create a schedule into a directory that already has backups

```
root@localhost:26257/defaultdb> CREATE SCHEDULE FOR BACKUP INTO 'nodelocal://2/ahh' RECURRING '@daily';
ERROR: backups already created in nodelocal://2/ahh; to ignore existing backups, the schedule can be created with the 'ignore_existing_backups' option

root@localhost:26257/defaultdb> CREATE SCHEDULE FOR BACKUP INTO 'nodelocal://2/ahh' RECURRING '@daily' WITH EXPERIMENTAL SCHEDULE OPTIONS ignore_existing_backups;
     schedule_id     |       name        |                     status                     |            first_run             | schedule |                       backup_stmt
---------------------+-------------------+------------------------------------------------+----------------------------------+----------+----------------------------------------------------------
  586551361339817985 | BACKUP 1599071669 | PAUSED: Waiting for initial backup to complete | NULL                             | @daily   | BACKUP INTO LATEST IN 'nodelocal://2/ahh' WITH detached
  586551361364262913 | BACKUP 1599071669 | ACTIVE                                         | 2020-09-02 18:34:29.940549+00:00 | @weekly  | BACKUP INTO 'nodelocal://2/ahh' WITH detached
(2 rows)

Time: 130.406ms
```

**Comment by mwang1026** [comment]
Thought on docs -- how much do we want to talk about GC and setting up schedules here? For example, say you set up recurring `@daily` but your GC window is < 1 day -- all your incremental backups will fail. In lieu of a protection, worth a mention in the docs to pay attention to that?

**Comment by mwang1026** [comment]
Note syntax change: it's not `WITH SCHEDULE OPTIONS` vs `WITH EXPERIMENTAL SCHEDULE OPTIONS`

**Comment by miretskiy** [comment]
NO.  It's with SCHEDULE OPTIONS; I dropped EXPERIMENTAL
