### ISSUE TITLE
KMS Support for Encrypted Backups

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7928]
Add general support for key management systems, including but not limited to:
- AWS KMS
- Google Cloud KMS
- Hashicorp Vault

We could enable the user to:
1. use implicit, IAM of the machine based authorization to talk to the KMS, or
2. explicitly provide the URL to authorize to the KMS

Functionality will need to include the ability to:
1. Specify the way to authorize to the KMS (implicit vs. explicit)
2. Which KMS they want to use
3. The same on the decryption for RESTORE

cc: @mwang1026 @adityamaru

**Comment by adityamaru** [comment]
@lnhsingh 20.2 will likely only see support for AWS KMS. We will, however, allow users to specify multiple region-specific AWS KMSs to encrypt their data, so that in the case of a single KMS region outage, the data can be decrypted with any of the other supplied KMS keys.

**Comment by lnhsingh** [comment]
The current implementation expects the Master Key to be symmetric.
