### ISSUE TITLE
Make Nodelocal Storage user-scoped and permissioned

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#7929]
Currently most I/O has to go to/from an "external" store but users sometimes want to get/put files to their local machine without external buckets/servers. `nodelocal` is shared / insecure / unmanged. We need per-user bulk file storage and management to prevent DOS type attacks that overload storage, and otherwise rampant use of nodelocal.

The workaround today is to disable local storage and force users to access files on external file storage (s3, gcs, etc.)

cc: @mwang1026 @adityamaru

**Comment by mwang1026** [comment]
https://github.com/cockroachdb/cockroach/issues/47211
https://github.com/cockroachdb/cockroach/issues/51222

**Comment by mwang1026** [comment]
Note: Userfile is not built for large files and may fail. I think we should push engineers on how to word that warning.

**Comment by mwang1026** [comment]
We want to doc the `list` and `delete` syntaxes, not the `ls` and `rm` syntaxes
