### ISSUE TITLE
Update sample code on Build a Node.js App with CockroachDB and the Node.js pg Driver doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#7931]
Re: [Build a Node.js App with CockroachDB and the Node.js pg Driver](https://cockroachlabs.com/docs//v20.1/build-a-nodejs-app-with-cockroachdb.html)

## Issue Description
There's a code smell, see [here](https://github.com/dbist/cockroach-docker/pull/53). Need to rename `err` to something unique across functions

## Suggested Resolution 
In my example, I renamed `err` to `errConn` for the connection block and `errInsert` for the insert block.

**Comment by dbist** [comment]
abbreviated code with fix below

```js
pool.connect(function (errConn, client, done) {
  // Close communication with the database and exit.
  var finish = function () {
    done()
    process.exit()
  }

  if (errConn) {
    console.error('could not connect to cockroachdb', errConn)
    finish()
  }
  async.waterfall([
    function (next) {
      // Create the 'accounts' table.
      client.query('CREATE TABLE IF NOT EXISTS accounts (id INT PRIMARY KEY, balance INT);', next)
    },
    function (results, next) {
      // Insert two rows into the 'accounts' table.
      client.query('INSERT INTO accounts (id, balance) VALUES (1, 1000), (2, 250);', next)
    },
    function (results, next) {
      // Print out account balances.
      client.query('SELECT id, balance FROM accounts;', next)
    }
  ],
  function (errInsert, results) {
    if (errInsert) {
      console.error('Error inserting into and selecting from accounts: ', errInsert)
      finish()
    }
```

**Comment by ericharmeling** [comment]
Recently rewrote the sample app for this driver (https://github.com/cockroachlabs/hello-world-node-pg/pull/1), so I'm not sure that this is still an issue?

**Comment by vy-ton** [comment]
@ericharmeling Let's close this issue?
