### ISSUE TITLE
geospatial: document geospatial file type converting tools

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7933]
There are many different geospatial data types. We won't support all of them natively by default. However, there are tools which can convert popular data types to those we do support. We should focus on adding documentation for these tools early on in out documentation journey.

[ogr2ogr](https://github.com/cockroachdb/cockroach/issues/52382) - allows conversion of Geopackage and Geodatabase data.
[osm2pgsql](https://github.com/cockroachdb/cockroach/issues/51818) - allows import of OSM data
`shp2pgsql` - specialisation of shape data to postgres

**Comment by awoods187** [comment]
@rmloveland i added this issue for early prioritization once @otan finishes the work to add support here

**Comment by otan** [comment]
note: for anything involving PGDUMP that results in
```

root@:26257/defaultdb> import pgdump 'nodelocal://0/census.sql'
;
ERROR: postgres parse error: line too long
```

run with increased size: https://www.cockroachlabs.com/docs/v20.1/migrate-from-postgres.html#max-row-size
