### ISSUE TITLE
Production Checklist: Update how connection pool size should be determined

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/docs#7936]
[https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#connection-pooling](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#connection-pooling
)

Connection pooling helps resolve this dilemma by creating a set of authenticated connections that can be reused to connect to the database. To determine the size of the maximum connection pool, our recommendation is to start your testing with a pool size of (core_count * 2) + ssd_count), where core_count is the total number of cores in the cluster, and ssd_count is the total number of SSDs in the cluster. The optimal pool size will vary based on your workload and application, and may be smaller than that.

**Comment by lnhsingh** [comment]
Hi @glennfawcett, thanks for filing an issue. Can you provide more context / information around how the connection pool size should be determined if SSD count is not a factor?

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/6706.
