### ISSUE TITLE
Update Java support to include a minimum version

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/docs#7937]
On the current "build a java app" page, we say we support Java <=9 but it sounds like TLS 1.2 is only on by default for Java 8.  We should update the minimum support for Java in our docs so users don't use an older unsupported version.

https://www.cockroachlabs.com/docs/stable/build-a-java-app-with-cockroachdb.html

**Comment by bdarnell** [comment]
Also, java 10 is 2 years old; we should update the example to work with current releases of java.
