### ISSUE TITLE
add wget/curl prompts to release note pages

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#7942]
Our release note pages include direct download links for Mac, Win, Linux, and Source. However, a `wget` or `curl` prompt like those we include on our full "Install CockroachDB" pages, and similar to the Docker link on release notes, would be more beneficial for scripting purposes.

- Consider using more space on release note pages to include these commands
- Update the Python script that generates the release note Markdown to include this content
- Consider cleaning up the URL by streamlining the naming scheme for the binaries

Context: https://cockroachlabs.slack.com/archives/C65RYUY3Z/p1596640325086200

**Comment by lnhsingh** [comment]
Related to #7948

**Comment by taroface** [comment]
Closing as docs team determined this isn't a priority, since the prompts are already available on the install pages.
