### ISSUE TITLE
document impact of transaction contention on BACKUPs

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#7943]
Our docs cover [transaction contention](https://www.cockroachlabs.com/docs/v20.1/performance-best-practices-overview.html#understanding-and-avoiding-transaction-contention) and mentions that this [BACKUPs can be affected](https://www.cockroachlabs.com/docs/dev/backup.html#performance) by this. 

However, we don't go into detail on what happens when a BACKUP is prevented by transaction contention, and how this can be prevented or resolved.

**Comment by lnhsingh** [comment]
This relates to hanging backups.

Solve for when it hits kv layer - "range not available". Now, the errors will be more verbose (open intent or if range is missing). David worked on this. If theres a hanging intent (long running or not closed). Now we add to the end of the queue. If you have a long running transaction, you can set it artificially high
