### ISSUE TITLE
Create Your CockroachCloud Cluster Doc Update 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#7947]
Re: [Create Your CockroachCloud Cluster](https://cockroachlabs.com/docs//v20.1/cockroachcloud-create-your-cluster.html)

The pricing is wrong. It says "per month" but it's really per hour. Quite the difference... Maybe we want to say "per hour, billed monthly" (if that's true).

**Comment by Amruta-Ranade** [comment]
Excellent catch, Andrei! Thank you!

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8045
