### ISSUE TITLE
`wget` prompt on release pages to download binaries

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#7948]
It would be really nice to have a `wget` prompt on our release pages to fetch the binaries. Looking at https://www.cockroachlabs.com/docs/releases/v20.1.4.html, we have this button today that lets you click to download the tarballs for each kind of operating system, but wouldn’t it be super nice if we had something like below that was copyable in the same way our docker image link is?
```
wget https://binaries.cockroachdb.com/cockroach-v20.1.4.darwin-10.9-amd64.tgz
```

Also, a nicer url would be swell, so you could do something like:
```
wget -O cockroach https://binaries.cockroachdb.com/cockroach-v20.1.4.darwin-amd64
```

I’m not sure how other people distribute binaries, but I think having this structure called out would be super nice for scripting purposes. we use something similar in our tests and it could probably be "delightful" for others looking for the same. We already have these commands on the install pages (https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html), I think it should take up space on the release notes page as well.

**Comment by lnhsingh** [comment]
Thanks for submitting this, @irfansharif! Closing this issue in favor of the one @taroface just opened: #7942
