### ISSUE TITLE
cockroachdb-in-comparison.html page - typos in tooltips

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/docs#7958]
Jim Hatcher (jhatcher9999) commented:

In: https://www.cockroachlabs.com/docs/v20.1/cockroachdb-in-comparison.html

Cost-based Optimization - tooltip typo: Optimize exectuion of queries based on transaction analytics (should be "execution")
Data Geo-partitioning - tooltip typo: Tie data to an instance/node to complu with regulations or optimize access latency (should be "comply")

**Comment by lnhsingh** [comment]
@jaymce @anagio - I was told that Marketing owns this page now, so routing this issue to you!
