### ISSUE TITLE
backup/restore Tables and User Defined Types (20.2)

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#7962]
Here's the original issue https://github.com/cockroachdb/cockroach/issues/48689
and the main PRs https://github.com/cockroachdb/cockroach/pull/50064 https://github.com/cockroachdb/cockroach/issues/50324

The big difference here is that now restore takes into account the current state of your cluster, in a sense
Nothing really changes for fullcluster and database restores
but for individual table backup, we collect all of the user defined types that the target table references (in columns or default expressions etc)
so if your table was `create table t (x int, y myenum)`, we'll include `myenum` in your backup
when restoring the backup, check to see if a type named `myenum` exists already
if not, then we just restore `myenum` from the backup
if it does exist, then we attempt to point all references to `myenum` in your back to the existing type `myenum` in the cluster.

**Comment by lnhsingh** [comment]
Related tests to see the behavior: https://github.com/cockroachdb/cockroach/blob/8bfb50d3ffa803286d0909abf64f65773bca379f/pkg/ccl/backupccl/backup_test.go#L1407
