### ISSUE TITLE
typo on K8s multi-cluster setup page

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/docs#7967]
Page:
https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html

Text:
At the top of the setup.py script, fill in the contexts map with the zones of your clusters and their "context" names, for example:

context = {
    'us-east1-b': 'gke_cockroach-shared_us-east1-b_cockroachdb1',
    'us-west1-a': 'gke_cockroach-shared_us-west1-a_cockroachdb2',
    'us-central1-a': 'gke_cockroach-shared_us-central1-a_cockroachdb3',
}

Issue: "context =" should be "contexts ="

**Comment by Geet-writes** [comment]
Hi @Amruta-Ranade I could start with this one, a simple typo-fix. Can you please assign it to me?
Thanks,
Geetanjali

**Comment by Amruta-Ranade** [comment]
@Geet-writes Heads-up: The Hacktoberfest organizers are changing the rules to combat spam. To have your PR count for Hacktoberfest, hold off on opening the PR until at least Tuesday to give us time to implement the new rules.

**Comment by dgabriel123** [comment]
Hello, is this issue still being worked on?

**Comment by Amruta-Ranade** [comment]
@Geet-writes Hi! Are you working on the issue?

**Comment by Geet-writes** [comment]
Hey hi,
Sorry to delay.
Yes I will fix it.
Got busy in other things.

Thanks.
