### ISSUE TITLE
Recommend disabling swap on production machines

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/docs#7969]
https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html

In the "CPU and memory" hardware requirements section, it would be useful to add something like the following:

> We recommend minimizing the use of virtual memory swapfiles when deploying CockroachDB into a production environment.  CockroachDB manages its own caches (configured via the `--cache` and `--max-sql-memory` flags), independently of the operating system.  Over-allocating memory on production machines can lead to unexpected (and hard to reproduce) performance hits when memory pages have to be read back into memory.  Disabling swap can be accomplished by executing `sudo swapoff --all` or removing swap devices from `/etc/fstab`.  Operators that wish to leave swap enabled are encouraged to set the `vm.swappiness` sysctl to 0, in order to minimize opportunistic page-outs.

**Comment by a-entin** [comment]
I suggest limiting guidance to a concise sentence that we recommend disabling Linux swap. We are not recommending "minimizing the use of swap" and we don't really need to provide instructions how to disable swap.

**Comment by jseldess** [comment]
This looks like a quick fix, so I'll take it.
