### ISSUE TITLE
Standardize on "spatial" or "geospatial", and add synonyms to site search

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#7975]
Right now our alpha docs use "spatial" in some places, and "geospatial" in others.

The team internally uses the term "geospatial", but I would like to standardize on "spatial" since that is used by established DBs.  Also, I found very few DB resources via internet search that use "geospatial".

Further, we do need to make sure that our docs website search returns results for both "spatial" and "geospatial" since the latter term is not entirely unheard of.

Estimated scope of work:

- Standardize on "spatial" and edit everything to match
- Check in with engineering team re: updating the site search index to add the necessary synonyms

**Comment by jseldess** [comment]
This was previously added to our search synonyms: https://github.com/cockroachdb/docs/blob/master/jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb#L294
