### ISSUE TITLE
sql: inverted indexes cannot be partitioned (known limitation) 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#7993]
We learned a few months ago that the intersection of inverted indexes and partitioning would be valuable to customers like S who’s tenants each place different importance on fields within a JSONB column. Because no one field is important to all tenants, we cannot extract any fields to build a computed column with an index, something which can be geo-partitioned. 

Similarly, while developers will be able to partition the underlying tables which contain spatial data in 20.2, they will not be able to partition the indexes used to query spatial data. This will mean that developers who hope to use both spatial data and geo-partitioning will suffer from poor performance.

**Comment by jseldess** [comment]
Thanks for recording this, @awoods187. These need to be called out clearly as limitations for both partitioning and the sql features (json, spatial).
