### ISSUE TITLE
Install CockroachDB on Windows Doc Update 

### ISSUE THREAD

**Issue by WALLOUD** [cockroachdb/docs#7996]
Re: [Install CockroachDB on Windows](https://cockroachlabs.com/docs//v20.1/install-cockroachdb-windows.html)

**Comment by lnhsingh** [comment]
Hi @WALLOUD, is there a particular update you would like to see made on the Install CockroachDB on Windows page?

**Comment by lnhsingh** [comment]
Closing this issue for now - will reopen if we get more info
