### ISSUE TITLE
Improve our CockroachDB license management docs

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/docs#7997]
Exalate commented:

Our current guidance on how to [renew an enterprise license](https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html#renew-an-expired-license) covers how you're production setup is unaffected, how the enterprise features stop working, a link to contact sales to renew, and a link to set a license.

But, a customer has raised the gap of our needing clarity on: 

- how to monitor licenses

- are they version agnostic?

- "are no scenarios in which CRDB needs to or would call-home for licence validation/enforcement?"

- Is there a grace period? and when would restrictions be enfored.

- We could be explicit of all the enterprise features that become disabled.

Jira Issue: DOC-636

**Comment by piyush-singh** [comment]
Related: #8017
