### ISSUE TITLE
frequently asked questions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8]
Concise answers to questions we think prospects might be most immediately interested in, such as how does cockroach scale, how does it survive failures, why is is sql, etc.

**Comment by jseldess** [comment]
Draft at http://www.cockroachlabs.com/docs/frequently-asked-questions.html

**Comment by jseldess** [comment]
Feedback from @vivekmenezes:

will not be permanent and will never be visible to readers

could be:

will faill, not be permanent and will never be visible to readers

Nice FAQ!

**Comment by jess-edwards** [comment]
@jseldess 
What do you think of adding a table of contents to the top of the FAQ? It will make it easier to hop to questions that are relevant.

**Comment by tschottdorf** [comment]
* successor to Paxos -> alternative to Paxos
* wonky sentence: When failures occur, replication ensures the continued availability of replicas and Raft ensures the consistency of replicas.
  Suggestion: Raft replication ensures that when failures occur, another replica can resume operation consistently.
* This means that concurrent transactions on the same data, whether reads or writes, will never result in anomalies: there's still the commit timestamp reordering anomaly (only linearizable mode gets rid of that). Not sure if it's worth mentioning.
* Consistency: I think this point should focus on our optimistic concurrency model. Raft is really more about keeping consistent replicas (which is another meaning of "consistent")
* Durability: again there is a mixup of Raft and Replication which I think could be clarified.

**Comment by jseldess** [comment]
PR #111 gets this almost final. Leaving this issue open so @tschottdorf can help me rewrite the texts for how Cockroach DB supports the C and D in ACID.

**Comment by tschottdorf** [comment]
Could you point me towards the segments of text you want me to look at in particular? Thanks.

**Comment by jseldess** [comment]
Sure, @tschottdorf: https://github.com/cockroachdb/docs/blob/gh-pages/frequently-asked-questions.md#does-cockroachdb-have-acid-semantics. See your earlier comments about the **Consistenty** and **Durability** explanations. It'd be great if you could offer some basic revisions.
