### ISSUE TITLE
Update Python code on the Build a Python App with CockroachDB and Django Doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8002]
Re: [Build a Python App with CockroachDB and Django](https://cockroachlabs.com/docs//v20.1/build-a-python-app-with-cockroachdb-django.html)

## Issue Description
running a flake8 linter against the code produced multiple [errors](https://github.com/dbist/cockroach-docker/issues/64).
## Suggested Resolution 
address the errors based on this [code](https://github.com/dbist/cockroach-docker/tree/master/cockroach-gssapi-django/myproject).

**Comment by ericharmeling** [comment]
@dbist 

I'm a little confused by this issue. Are you saying the code isn't formatted properly?

See https://github.com/cockroachdb/examples-orms/pull/124.

**Comment by ericharmeling** [comment]
FYI, after https://github.com/cockroachdb/docs/issues/8898, the code in our docs will pull directly from https://github.com/cockroachdb/examples-orms.
