### ISSUE TITLE
cockroach debug zip Doc Update for CockroachCloud

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#8004]
Re: [cockroach debug zip](https://cockroachlabs.com/docs//v20.1/cockroach-debug-zip.html)

## Issue Description

It would be good to have a cockroach debug zip page specific to CockroachCloud. On this page there is a description of the --url option that could potentially be used to get a debug out of cloud (I haven't test this) but it's unclear that one might use that for cloud. 

## Suggested Resolution 

Create a cloud specific page with directions for getting a debug zip.

**Comment by lnhsingh** [comment]
Closing in favor of CC-3692
