### ISSUE TITLE
multi-region topology section on two regions 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#8016]
I've sat on a few different customer calls where we get the question "Can I run 6 nodes in two regions?" This seems like something we should have docs on. It could be under our current multi-region topology section.

**Comment by lnhsingh** [comment]
@jseldess assigning this to you since I think you are the latest writer to work on topology patterns. Feel free to re-assign.

**Comment by jseldess** [comment]
2 regions is an anti-pattern that we mention here: https://www.cockroachlabs.com/docs/v20.2/topology-patterns#anti-patterns. We definitely need to surface this info better and more explicitly. Closing this in favor of https://github.com/cockroachdb/docs/issues/6651
