### ISSUE TITLE
Better examples of how to authenticate to gs://

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#8019]
Users aren't clear on the options they have here, and examples or pointing to what something should look like. For example, how do you get the json key? How do you base64 encode? What does that encoding look like?

All of our gs:// examples assume implicit auth, and even then we have two types -- one that looks at gsutil settings and another that looks at an env variable, but also requires that file / auth to be on EVERY node.

More examples could be helpful here.

**Comment by kathancox** [comment]
Closing this as a result of #10761 and #10770. Together these provide more detail on authentication to gcs and more examples in the bulk operation pages. Feel free to reopen if you feel more detail is needed.
