### ISSUE TITLE
Repaving a node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8025]
"Repaving" is the process of updating a host to the latest OS and dependent libraries. Some customers do this by policy. 

We need to add a how-to with the recommended steps for repaving the host that a node is running on without interrupting the cluster's operations. This is similar to decommissioning in part. 

We need to provide instructions for doing this manually, using `systemd, and in Kubernetes. 

This [wiki page](https://cockroachlabs.atlassian.net/wiki/spaces/CS/pages/776503600/Amazon+EKS+-+EC2+Node+Repaving) by @cjireland's is a helpful start, though there are some changes that need to be made, based on feedback from @bdarnell:

> it looks like you're removing the node without decommissioning, only draining. that's dangerous because it leaves everything in an underreplicated state while recovery happens. if you're repaving by removing persistent volumes, you need to decommission the nodes before draining and removing the pods (if you're repaving by transferring persistent volumes, that's another story, but it doesn't seem to be what you're doing here)

cc @taroface and @piyush-singh for triage and prioritization.

**Comment by taroface** [comment]
cc @johnrk

**Comment by BramGruneir** [comment]
This would be wonderful to have.

**Comment by taroface** [comment]
Relevant: https://github.com/cockroachdb/cockroach/issues/53410

**Comment by taroface** [comment]
Per @johnrk this is no longer on the 20.2 roadmap for docs.

**Comment by cjireland** [comment]
Hi @johnrk , when do you think this can be addressed, 21.1?

**Comment by johnrk** [comment]
@cjireland , we weren't planning on doing it. @knz owned this work and determined that this is an antiquated practice.

**Comment by taroface** [comment]
I'm going to close this issue. Will reopen when and if repaving becomes a broader customer concern.
