### ISSUE TITLE
Need to explain CC SQL user permissions in docs

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#8027]
I couldn't find anywhere where we explain what the privileges of a SQL user added in the console are. This is something our users will want to know before granting access to new users or services (it even came up in one of our user interviews). We should have a description of these privileges either in the "getting started" section or "managing your cluster".

cc @thtruo

**Comment by Amruta-Ranade** [comment]
We've documented SQL user permissions in the "Create SQL users" section of the "Connect to your cluster" doc: https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html#step-2-create-a-sql-user

The Authorization doc explains it in greater detail: https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-authorization.html#user-authorization

However, I do agree the UX and the related docs are confusing to new users. @thtruo: Fodder for the Operator role conversation?

**Comment by thtruo** [comment]
+1 @Amruta-Ranade definitely relates to the operator role conversation. Will link to this GH issue in our internal doc

**Comment by lnhsingh** [comment]
Closing in favor of #9017
