### ISSUE TITLE
Update docs on support resources and how to file an issue

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#8032]
Exalate commented:

We need to revisit the pages in our docs that describe [support resources](https://www.cockroachlabs.com/docs/v21.2/support-resources) and [how to file an issue](https://www.cockroachlabs.com/docs/v21.2/file-an-issue). A lot of the guidance is very out-dated at this point. 

Jira Issue: DOC-1643

**Comment by jseldess** [comment]
@nickelnickel, we should probably revisit how we guide people to support in our docs:

https://www.cockroachlabs.com/docs/v20.2/support-resources
https://www.cockroachlabs.com/docs/v20.2/file-an-issue.html

Do you want to guide next steps here?

**Comment by mattcrdb** [comment]
https://www.cockroachlabs.com/support/
