### ISSUE TITLE
Create a "Performance Overview" page with instructions for several benchmarks

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8034]
Currently (August 2020), our [performance overview section](https://www.cockroachlabs.com/docs/dev/performance.html) only lists [how to run TPC-C](https://www.cockroachlabs.com/docs/dev/performance-benchmarking-with-tpc-c-10-warehouses.html) at various warehouse counts.

We should update the performance section to include instructions for running at least the following benchmarks (which are available via `cockroach workload`):

- [YCSB](https://en.wikipedia.org/wiki/YCSB)
- KV (CRL-devised key-value benchmark)

**Comment by jseldess** [comment]
@johnrk, @mwang1026, @rmloveland, closing this for now. If this topics comes out of your Product Areas' problems to solve or priorities in the future, we can create a new issue with more context.
