### ISSUE TITLE
Replication Reports Doc - text truncated 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#8041]
Re: [Replication Reports](https://cockroachlabs.com/docs//v20.1/query-replication-reports.html)

The text on this page is not displayed properly, regardless of window size. The first letters are cut off.
<img width="964" alt="Screen Shot 2020-08-21 at 4 38 36 PM" src="https://user-images.githubusercontent.com/377201/90932552-f31fc300-e3cc-11ea-86d5-70a4a0308644.png">

**Comment by jseldess** [comment]
OK, weird. Thanks, @andreimatei. We can reopen if we see this again.
