### ISSUE TITLE
oracle date type conversion issue

### ISSUE THREAD

**Issue by seadba** [cockroachdb/docs#8046]
Hello, testing oracle->crdb migration using oracle sample HR schema - csv import seems to work fairly well, except for date conversion - 

oracle column
 HIRE_DATE                                 NOT NULL DATE

Crdb column 
hire_date      | DATE        

ex 
oracle 
select hire_date, to_char(hire_date,'DD-MON-YYYY') sdate from employees
  2  where rownum  = 1;

HIRE_DATE SDATE
--------- --------------------
17-JUN-03 17-JUN-2003

crdb 
HR@:26257/hr> select hire_date from employees limit 1;
          hire_date
-----------------------------
  2017-06-03 00:00:00+00:00

im assuming i have a formatting issue on my end but havent found it yet - any idea? thanks

**Comment by seadba** [comment]
here is the import statement - different table but same issue

HR@:26257/hr> import into job_history
csv data (
'nodelocal://self/job_history.csv') with skip = '1', nullif = '';
ERROR: nodelocal://self/job_history.csv: error parsing row 3: parse "start_date" as DATE: parsing as type date: field day value 97 is out of range (row: "101,21-SEP-97,27-OCT-01,AC_ACCOUNT,110")

**Comment by lnhsingh** [comment]
Hi @seadba, thanks for reaching out. This is the CockroachDB docs repo (for filing issues re: docs bugs, additions, etc.). For help troubleshooting, you can reach out on [Slack](https://app.slack.com/client/TP86H0JSH/CP4D9LD5F), in the [Forum](https://forum.cockroachlabs.com/), or [contact Support](https://support.cockroachlabs.com/hc/en-us/requests/new?).
