### ISSUE TITLE
sql: give more examples of RETURNING as substitute for mysql's LastInsertID()

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#805]
Requested on Gitter:

(01:21) < clanstyles> Hey, I'm trying to create a table. I see primary key of INT and also BYTES DEFUALT uuid, what's the proper way to create a new record and return the ID in Go?
(01:21) < clanstyles> INSERT INTO homepages (id, url, text, timestamp) VALUES(DEFAULT, $1, $2, NOW())
(01:21) < clanstyles> I tried this, but it's not creating an ID
(01:23) < clanstyles> None of the examples project shows how to create a unique id and then return it (LastInsertID()) or re-query the ID.

Note: LastInsertID is a MySQL feature. Usually users asking for this do not know about RETURNING.

(02:18) < knz> clanstyles: try RETURNING
(02:19) < knz> clanstyles: INSERT INTO homepages (id, url, text, timestamp) VALUES(DEFAULT, $1, $2, NOW()) RETURNING id

**Comment by jseldess** [comment]
Thanks for capturing this, @knz!
