### ISSUE TITLE
SQL Error Code docs

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#806]
Create document that is a searchable reference of errors that surface from using CockroachDB:
- [`sql/sqlbase/errors.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/errors.go)
- [`pgwire/pgerror/codes.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pgwire/pgerror/codes.go)

gz#9901

gz#10264

**Comment by jseldess** [comment]
@bdarnell, do you think some of the errors in the code linked above should be covered on https://www.cockroachlabs.com/docs/stable/common-errors.html? We could also consider changing that page from "Common Errors" to "Error Reference" or something similar.

**Comment by jseldess** [comment]
@ericharmeling, @awoods187, for future prioritization.

**Comment by awoods187** [comment]
I think this would be a good project to work on so that people can google for help and find CRDB documentation. That being said, we do have quite a lot on the backlog so I think this is borderline p1/p2. I'm going to mark it p2 for now.

**Comment by rmloveland** [comment]
Via an internal convo just now that resulted in me filing the smaller-scoped #11683, @knz said that we should autogenerate the list of these errors since the list of possible errors can change per release, so we'd need to invest some engineering time

**Comment by jseldess** [comment]
Closing in favor of #11683, which is a more practical place to start.
