### ISSUE TITLE
Document historical reads on RESTOREd tables as a known limitiation

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8090]
If https://github.com/cockroachdb/cockroach/issues/53044 isn't fixed by v20.2 release, document as a known limitation

**Comment by mwang1026** [comment]
Let's doc this now. tl;dr is that it's a pretty bad experience insofar as a user can issue an `AS OF SYSTEM TIME` query on a restored database but it will "lie" in that we don't actually have historical data to query after a RESTORE.
