### ISSUE TITLE
cli: remove auto-init with `cockroach start` without `--join`

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8098]
PR: https://github.com/cockroachdb/cockroach/pull/51245

From release notes:
> A CockroachDB node started with [`cockroach start`](../v20.2/cockroach-start.html) without the `--join` flag no longer automatically initializes the cluster. The `cockroach init` command is now mandatory. The auto-initialization behavior had been deprecated in version 19.2. [#51245][#51245] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@taroface, when you close issues, can you please either link to the PR that resolves it (easiest to do this via the PR itself), or add a note?

**Comment by taroface** [comment]
Sorry, yes. Closed this one because the 19.2-20.2 docs had already been updated to reflect this change. I honestly can't recall whether I did it or if it was already there.
