### ISSUE TITLE
heapprofiler: properly preserve heap dumps, refactor some code

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8101]
PR: https://github.com/cockroachdb/cockroach/pull/50446

From release notes:
> The file names for heap profile dumps now use the naming scheme `memprof.<date-and-time>.<heapsize>`, where previously they were named `memprof.<heapsize>.<date-and-time>`. [#50446][#50446] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
This was resolved with #10873. Nice!
