### ISSUE TITLE
release: ship libgeos.* and libgeos_c.* files

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8104]
PR: https://github.com/cockroachdb/cockroach/pull/51108

From release notes:
> The [CockroachDB tarballs](#downloads) now include the `libgeos` and `libgeos_c` static libraries, which are required to be copied to `/usr/local/lib/cockroach` for UNIX/MacOS systems to [perform certain geospatial operations](../v20.2/spatial-data.html). The Windows location will be finalized at a later date. This location is configurable with the `--geo-libs` flag to `cockroach start`. [#51108][#51108] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
@rmloveland Would this belong in your area?

**Comment by rmloveland** [comment]
Fixed in #8831
