### ISSUE TITLE
backupccl: Support BACKUP and RESTORE TENANT

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8109]
PR: https://github.com/cockroachdb/cockroach/pull/50967

From release notes:
> Added support for `BACKUP TENANT` and `RESTORE TENANT`. [#50967][#50967] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I think we want to hold off on documenting this right now since Backup/Restore/Import as a TENANT is scheduled for v21.1. Can you confirm @mwang1026?

**Comment by mwang1026** [comment]
Hold. We're not exposing this to end users.

**Comment by lnhsingh** [comment]
Thanks. Closing this for now then.
