### ISSUE TITLE
sql: Add the `CREATE SCHEDULE FOR BACKUP` grammar

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8123]
PR: https://github.com/cockroachdb/cockroach/pull/50631

From release notes:
> Added a `CREATE SCHEDULE FOR BACKUP` statement. This statement can be used to specify a recurring backup schedule. [#50631][#50631] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I'll take this one

**Comment by ericharmeling** [comment]
Thank you @lnhsingh !

**Comment by ericharmeling** [comment]
Note that all new statements qualify for using help text rather than diagrams. (See https://github.com/cockroachdb/docs/pull/8486/files#diff-2a674e8a9cdb7d7df6bb342d4b84a2a4 for an example)

**Comment by lnhsingh** [comment]
Closing this - addressed by https://github.com/cockroachdb/docs/pull/8245
