### ISSUE TITLE
opt: remove SYMVARS modifier to EXPLAIN

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8124]
PR: https://github.com/cockroachdb/cockroach/pull/51349

From release notes:
> Removed the `SYMVAR` modifier to [`EXPLAIN (PLAN)`](../v20.2/explain.html). [#51349][#51349] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This removal doesn't need documenting because the argument was never documented.
