### ISSUE TITLE
sql: move interleaved join planning in the optimizer

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8131]
PR: https://github.com/cockroachdb/cockroach/pull/51469

From release notes:
> Interleaved table joins now show up in [`EXPLAIN (PLAN)`](../v20.2/explain.html) output. [#51469][#51469] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Latest EXPLAIN example output is up-to-date.
