### ISSUE TITLE
sql: remove ccl-only from grant/revoke role help message

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8132]
PR: https://github.com/cockroachdb/cockroach/pull/51465

From release notes:
> Made a minor change to remove the outdated CCL-only message from the [`GRANT`](../v20.2/grant-roles.html) and [`REVOKE ROLE`](../v20.2/revoke-roles.html) help messages. [#51465][#51465] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs documenting.
