### ISSUE TITLE
builtins: add num_nulls, num_nonnulls builtins

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8133]
PR: https://github.com/cockroachdb/cockroach/pull/51515

From release notes:
> Added the `num_nulls` and `num_nonnulls` builtin functions, which count the number of arguments that are passed to them which are _NULL_ or non-_NULL_, respectively. [#51515][#51515] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is already documented.
