### ISSUE TITLE
sql: implement idle_in_session_timeout setting to cancel sessions

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8135]
PR: https://github.com/cockroachdb/cockroach/pull/51223

From release notes:
> Added support for the `idle_in_session_timeout` variable to allow automatically terminating [sessions](../v20.2/show-sessions.html) that idle past a certain threshold. [#51223][#51223] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/7940.
