### ISSUE TITLE
builtins: add a builtin to convert the hlc.Timestamp decimal to timestamp

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8139]
PR: https://github.com/cockroachdb/cockroach/pull/51662

From release notes:
> Added the builtin function `crdb_internal.approximate_timestamp` to convert the `DECIMAL` returned from the `crdb_internal_mvcc_timestamp` system column into a [`TIMESTAMP`](../v20.2/timestamp.html). [#51662][#51662] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is already documented.
