### ISSUE TITLE
Improve syntax highlighting for CLI flags

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#814]
Currently all CLI flags and their parameters are treated as un-highlighted text. I suggest changing it so that the flag and its parameter are treated as distinct items by the syntax highlighter.

**Comment by luciaaaaaaa** [comment]
hey @lnhsingh @jseldess could you add a reference screenshot to understand what this refers to?

**Comment by lnhsingh** [comment]
this refers to the synopsis and examples on the [cockroach command](https://www.cockroachlabs.com/docs/dev/cockroach-commands.html) pages:

![image](https://user-images.githubusercontent.com/15386648/82579101-534b6280-9b5b-11ea-83ee-d24e271ef165.png)

![image](https://user-images.githubusercontent.com/15386648/82579258-8a217880-9b5b-11ea-90a8-2d6c6ada2eef.png)

(these screenshots are from [`cockroach start`](https://www.cockroachlabs.com/docs/dev/cockroach-start.html#synopsis)

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2154%3A0

**Comment by elkmaster** [comment]
@luciaaaaaaa, from a link provided not exactly clear how this flags should look like
