### ISSUE TITLE
sql,ui: add bytes, rows read to web ui

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8145]
PR: https://github.com/cockroachdb/cockroach/pull/51630

From release notes:
> The 'bytes' and 'rows read' metrics are now tracked with mean and variance, similar to the other per-statement metrics. `crdb_internal.node_statement_statistics` has been updated to remove the `bytes_read` and `rows_read` columns, replacing them with `bytes_read_avg`, `bytes_read_var`, `rows_read_avg`, and `rows_read_var`. [#51630][#51630] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We don't document the `node_statement_statistics` directly in docs. Closing this issue.
