### ISSUE TITLE
rowexec: add missing disk stats to join reader

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8151]
PR: https://github.com/cockroachdb/cockroach/pull/52237

From release notes:
> Query statistics now include the disk bytes and rows read from lookup and index [joins](../v20.2/joins.html), in addition to ordinary table scans. [#52237][#52237] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this needs documenting. @jordanlewis please reopen if you disagree. :)

**Comment by jordanlewis** [comment]
I agree. it's more of a bug fix
