### ISSUE TITLE
importccl: allow ALTER TABLE ... ALTER COLUMN ... SET NULL

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8152]
PR: https://github.com/cockroachdb/cockroach/pull/52442

From release notes:
> Added support for `ALTER TABLE ... ALTER COLUMN ... SET NULL` syntax for [`IMPORT PGDUMP`](../v20.2/import.html#import-a-postgres-database-dump) type backups. [#52442][#52442] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
This can be included in 21.1 docs for PGDUMP

**Comment by mwang1026** [comment]
No need to doc this
