### ISSUE TITLE
Permission based object ownership

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8153]
Roadmap: https://cockroachlabs.atlassian.net/browse/CRDB-888

PR: https://github.com/cockroachdb/cockroach/pull/51856

From release notes:
> Added "ownership" concept objects. Objects must now have an owner; all objects that do not have owners currently will have `admin` set as the default owner except system objects. System objects without owners will have `node` as their owner. By default, owners are the creator of the object. Owners have all privileges to the objects they own. Similarly, any [roles](../v20.2/authorization.html#create-and-manage-roles) that are members of the owner role also have all privileges on the object. Roles cannot be dropped if they own objects. This PR does not add support for changing the ownership of objects; that will be added in a future PR to support dropping roles. [#51856][#51856] {% comment %}doc{% endcomment %}

Update: Related issues:
- release-20.2: sql: don't allow cross-database sequence owners #8511
- release-20.2: sql: disallow role/user drops if they own a schema or a type #8506

**Comment by ericharmeling** [comment]
@Amruta-Ranade FYI, @RichardJCai is back in school for the semester.

**Comment by jseldess** [comment]
@Amruta-Ranade, this is an IAM user journey, so it's on your plate, but the work was done by SQL and has impact on backup/restore work, so please reach out to @ericharmeling and @lnhsingh for support as needed.

**Comment by jseldess** [comment]
@Amruta-Ranade, are there any docs I can glance at? I'm trying to write up the 20.2 release note features summaries, and I'm not sure how to capture this.

**Comment by Amruta-Ranade** [comment]
Yes! Eric's doc: https://www.cockroachlabs.com/docs/dev/owner-to.html

**Comment by jseldess** [comment]
Ah, ok. This issue is assigned to you. Are you doing additional work on this?

**Comment by Amruta-Ranade** [comment]
Yep..working on updating IAM docs based on Eric's doc.
