### ISSUE TITLE
sql: support BINARY format in COPY

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8155]
PR: https://github.com/cockroachdb/cockroach/pull/51890

From release notes:
> Added support for the `BINARY` format for `COPY FROM`. [#51890][#51890] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I'll take this one

**Comment by ericharmeling** [comment]
Thank you @lnhsingh !

**Comment by lnhsingh** [comment]
Doesn't seem like docs updates are needed since we don't document the `COPY FROM` statement.
