### ISSUE TITLE
sql:  add notice for Alter TYPE ADD VALUE IF NOT EXIST command

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8157]
PR: https://github.com/cockroachdb/cockroach/pull/52534

From release notes:
> Added a notice that is displayed to the user when she tries to add a value which already exists in an `ENUM`. [#52534][#52534] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This will show up in a notice and doesn't need to be explicitly documented.
