### ISSUE TITLE
geo/geomfn: implement ST_MakePolygon({geometry,_geometry})

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8167]
Lauren Hirata Singh (lnhsingh) commented:

PR: https://github.com/cockroachdb/cockroach/pull/50979

From release notes:
> Implemented the `ST_MakePolygon` function for `GEOMETRY` types. [#50979][#50979] {% comment %}doc{% endcomment %}

Jira Issue: DOC-659

**Comment by rmloveland** [comment]
Partially addressed in #8747
