### ISSUE TITLE
parser: allow USING GIST syntax for creating inverted indexes

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8172]
PR: https://github.com/cockroachdb/cockroach/pull/51516

From release notes:
> Added support for the `USING GIST` syntax to create an [inverted index](../v20.2/inverted-indexes.html) on `GEOMETRY` and `GEOGRAPHY` columns. [#51516][#51516] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rmloveland This looks like a spatial feature?

**Comment by rmloveland** [comment]
yes, snagged

**Comment by rmloveland** [comment]
Fixed in #8617
