### ISSUE TITLE
geo: order geospatial objects by Hilbert Curve index

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8182]
PR: https://github.com/cockroachdb/cockroach/pull/51898

From release notes:
> When [ordering by](../v20.2/query-order.html) geospatial columns, they will now be ordered by the [Hilbert Space-filling Curve](https://en.wikipedia.org/wiki/Hilbert_curve) index so that points which are geographically similar are clustered together. [#51898][#51898] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #8617.
