### ISSUE TITLE
builtins: implement the ST_MakeLine aggregate

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8185]
Lauren Hirata Singh (lnhsingh) commented:

PR: https://github.com/cockroachdb/cockroach/pull/52631

From release notes:
> Implemented the `ST_MakeLine` aggregate builtin function. [#52631][#52631] {% comment %}doc{% endcomment %}

Jira Issue: DOC-673

**Comment by rmloveland** [comment]
Partially addressed in #8747
