### ISSUE TITLE
ui: Show Time range selector in UTC instead of local time

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8206]
PR: https://github.com/cockroachdb/cockroach/pull/51056

From release notes:
> The time range selector (on the **Metrics** page) now shows time in UTC instead of local time, with a "(UTC)" prefix after the time to highlight this in the UI. [#51056][#51056] {% comment %}doc{% endcomment %}

**Comment by piyush-singh** [comment]
Minor UX update, no docs necessary.
