### ISSUE TITLE
stats: don't delete stale cache entries, update them asynchronously instead

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8207]
PR: https://github.com/cockroachdb/cockroach/pull/51616

From release notes:
> Queries no longer block during planning if cached table statistics have become stale and the new statistics have not yet been loaded. Instead, the stale statistics are used for planning until the new statistics have been loaded. This improves performance because it prevents latency spikes that may occur if there is a delay in loading the new statistics. [#51616][#51616] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Not sure we need to document this. @rytaft Please reopen if you disagree.
