### ISSUE TITLE
Generic retry loop example does not have a way to exit where no retry is needed

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8211]
Feedback from a user on the generic transaction retry loop logic:

<img width="570" alt="Screen Shot 2020-08-27 at 6 08 36 AM" src="https://user-images.githubusercontent.com/15893490/91427448-eca9a500-e82b-11ea-918f-b065efad9c4e.png">

**Comment by jseldess** [comment]
@rmloveland, assigning this to you since you worked on it originally, but I'm unclear if transaction docs should rather shift under sql/app dev going forward? It's a grey area. cc @awoods187, @johnrk, @ericharmeling.

**Comment by rmloveland** [comment]
IDK re: where it should go, but I think this is a quick one (1-line change)

This comment is referring to pseudocode that does not include all of the necessary logic for an application; it only shows explicitly how to do the retries. The part where the user's app would exit in the normal situation where no retry is needed is in the block that looks like

```
try:
  # add logic here to run all your statements. <--- This is where the user code goes
  conn.exec('COMMIT')
```

The key is that the application developer adds their logic to exit where the comment goes.

Aaaaaand after writing all this I think I understand what the user is saying: the work item here is to add a fake `exit` statement after the `COMMIT` statement, which I can definitely go ahead and do! (1-line change) so it will become

```
conn.exec('commit')
exit # exit the while loop
```

or similar
