### ISSUE TITLE
sql: examples of inverted index for ARRAY

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/docs#8216]
I would like to use an inverted index on an array column. I see in the [inverted index doc](https://www.cockroachlabs.com/docs/v20.1/inverted-indexes) that this is supported, but I don’t see examples.

Given what is documented about using inverted indexes with JSON, I can probably figure it out , but would love to see an  example for ARRAY.

**Comment by deeptikorwar** [comment]
@Amruta-Ranade, can I work on this one?

**Comment by Amruta-Ranade** [comment]
Sure! Assigning it to you :)

**Comment by deeptikorwar** [comment]
@Amruta-Ranade, can you please help me with the last part of this example?

`CREATE TABLE students (
    student_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    marks INT ARRAY,
    INVERTED INDEX student_marks (marks)
  );`

`INSERT INTO students (marks) VALUES
    (ARRAY[10,20,50]),
    (ARRAY[20,40,100]),
    (ARRAY[100,20,70]);` 

`SELECT * FROM students;`

The below code doesn't work. I tried it in `cockroach demo`
`SELECT * FROM students where marks @> 100;`

**Comment by rytaft** [comment]
Hi @deeptikorwar, 
I think the query you want is `SELECT * FROM students where marks @> ARRAY[100];`. The data type on the right hand side of `@>` must match the type on the left hand side.

**Comment by ericharmeling** [comment]
Fixed by #8630.
