### ISSUE TITLE
SQL ref: provide example on how to specify columns with INSERT

### ISSUE THREAD

**Issue by dianacarroll** [cockroachdb/docs#8236]
https://www.cockroachlabs.com/docs/stable/insert.html#examples

In the examples for the INSERT command, it shows how to insert when providing all values in column order, like this:

```
INSERT INTO users VALUES
    ('c28f5c28-f5c2-4000-8000-000000000026', 'new york', 'Petee', '101 5th Ave', '1234567890');
```

But it doesn't show how you would insert a row specifying particular columns, like this:

```
INSERT INTO users (id, name) VALUES
    ('c28f5c28-f5c2-4000-8000-000000000026', 'Petee');
```

This would be helpful. 

The docs hint that the first example does specify columns, even though it doesn't:

> If you do not list column names, the statement will use the columns of the table in their declared order:

This implies to me that the section above would have shown column names, and the one below would specify without, but in fact the examples are both are inserting without column names.

**Comment by ericharmeling** [comment]
> it doesn't show how you would insert a row specifying particular columns

There are a lot of examples on this page that show how to insert into specific columns:

- https://www.cockroachlabs.com/docs/v20.1/insert.html#insert-multiple-rows-into-an-existing-table
- https://www.cockroachlabs.com/docs/v20.1/insert.html#insert-multiple-rows-into-an-existing-table
- https://www.cockroachlabs.com/docs/v20.1/insert.html#insert-default-values

This is generally something that you can only do when you have `NULL`able columns and `DEFAULT` values specified for `NOT NULL` columns.

> The docs hint that the first example does specify columns, even though it doesn't:

> > If you do not list column names, the statement will use the columns of the table in their declared order:

The docs here are talking about the declared order of the columns in the table's definition, not in the statement. But you're right - this is pretty confusing and we should update it!

**Comment by pratikSethi** [comment]
Hi Everyone, I would like to work on this. Can I take this up?

**Comment by Amruta-Ranade** [comment]
Sure!

**Comment by Amruta-Ranade** [comment]
@pratikSethi Heads-up: The Hacktoberfest organizers are changing the rules to combat spam. To have your PR count for Hacktoberfest, hold off on opening the PR until at least Tuesday to give us time to implement the new rules.

**Comment by pratikSethi** [comment]
@Amruta-Ranade thanks for the heads-up. I was having some difficulty while setting up jekyll. I'll have some time over the weekend to wrap this up. 

Also, the scope of this issue is to ensure that the example mentioned should have the particular columns listed, right?

**Comment by Amruta-Ranade** [comment]
@ericharmeling @dianacarroll Need your advice :)

**Comment by ericharmeling** [comment]
@pratikSethi 

Yeah that sounds right! I think just updating that example to specify the columns into which you are inserting.

**Comment by pratikSethi** [comment]
@ericharmeling @Amruta-Ranade 
Thanks for the clarification. I have created a [PR](https://github.com/cockroachdb/docs/pull/8633) but couldn't find an option to assign it to `jseldess` as mentioned in [Contributing.md](https://github.com/cockroachdb/docs/blob/master/CONTRIBUTING.md#build-and-test-the-docs-locally). Please suggest if there is anything else that needs taken care of :)
