### ISSUE TITLE
Field `schema_name` not described by documentation in `SHOW GRANTS`

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#8237]
In `show-grants.md`, the `SHOW GRANTS` command returns a table with several fields, but it doesn't define them. The most confusing are `schema_name` and `privilege_type`, as it's not obvious what they refer to. This is a problem for all examples on this page.

This is a problem because users may be confused about what they're seeing even after using the docs.

Steps to reproduce:
* Go to https://www.cockroachlabs.com/docs/v20.1/show-grants#show-all-grants
* Look at the first example, `SHOW GRANTS;`

Expected result: columns in the table returned get defined

Actual result: columns are not defined anywhere.

**Comment by lnhsingh** [comment]
@ericharmeling not sure if this would fall under SQL or security, so feel free to re-assign if you think @Amruta-Ranade should handle this. thanks!

**Comment by HugoLiconV** [comment]
The solution for this issue would be to define what `database_name`, `schema_name`, `table_name`, `grantee`, and `privilege_type` mean?

**Comment by Amruta-Ranade** [comment]
`database_name` and `table_name`are defined in the "Parameters" table. I think the solution here is to expand the example's description text to explain what `schema_name`, `grantee`, and `privilege_type` mean.

**Comment by HugoLiconV** [comment]
@Amruta-Ranade thanks for clarifying. I'll be fixing that.

**Comment by HugoLiconV** [comment]
I created a PR but I only updated the version 20.2, should I update the other versions? @Amruta-Ranade
