### ISSUE TITLE
Scheduled backups: Need update permissions

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8238]
To use the BACKUP INTO syntax on scheduled backups, you must have update permissions (in the bucket)

[Slack convo](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1599081001113200)

cc: @mwang1026

**Comment by ericharmeling** [comment]
Is this a known limitation, or just a privileges requirement? That is, does it differ from expected behavior and do we intend to change that behavior?

**Comment by lnhsingh** [comment]
I think at the time I made this issue, @mwang1026 mentioned it as a known limitation but after re-reading the convo, it seems like this is just a privileges requirement. Michael, can you confirm?

**Comment by mwang1026** [comment]
I think it's a privileges requirement, but specifically a *storage* level requirement rather than a CockroachDB requirement. For example, the IAM user you're using to talk to s3 for your backups must have update to whatever directory you're backing up to.
