### ISSUE TITLE
Update Migrate from Oracle Doc to reflect v20.1+ changes 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8240]
Re: [Migrate from Oracle](https://cockroachlabs.com/docs//v20.1/migrate-from-oracle.html)

## Issue Description
These are some of the suggested changes with 20.1+

## Suggested Resolution 
1. The document references `fix-example.py` but command states
`python2 fix.py CUSTOMERS.lst ADDRESSES.lst CARD_DETAILS.lst WAREHOUSES.lst ORDER_ITEMS.lst ORDERS.lst INVENTORIES.lst PRODUCT_INFORMATION.lst LOGON.lst PRODUCT_DESCRIPTIONS.lst ORDERENTRY_METADATA.lst`. Maybe also a good time to change the command to python3 as well.
2. Change `SELECT Transaction_timestamp(), clock_timestamp();` to `SELECT transaction_timestamp(), clock_timestamp();`

**Comment by mwang1026** [comment]
Labeling P-1 because this is very small. We can separate out the python3 part (RIP python2)
