### ISSUE TITLE
hibernate.cfg.xml should set "update" property instead of "create"

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#8247]
In our Hibernate "Hello World" code sample, the following property is set
```
<property name="hibernate.hbm2ddl.auto">create</property>
```

We should use `update` instead of `create` so that the existing schema/data is not dropped if a user reruns the example

**Comment by ianjevans** [comment]
Unfortunately, the example hard codes the PKs of the account it creates, so rerunning the example will throw exceptions regardless of whether the `hibernate.hbm2ddl.auto` setting is `create` or `update`.

We can, however, set it to `create-drop`, which will create the tables if necessary and then drop them when the application session closes, allowing the user to rerun the example with the same results. This allows us to avoid having to refactor the account handling code.
