### ISSUE TITLE
Update docs: BACKUP / RESTORE / EXPORT are core features in 20.2+

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8259]
- Remove enterprise license notes
- Update Enterprise Features doc
- Remove information about `cockroach dump` as the core equivalent to backup
- Add deprecation note to `cockroach dump`

Related to #8088. cc @mwang1026

**Comment by mwang1026** [comment]
Let me know if you need help delineating what is ENTERPRISE vs CORE as it relates to BACKUP. We might want to think about how we organize things as well as result of this. The tl;dr is that only basic, full backup is CORE.

Incremental, Locality aware, Encrypted, Revision history are all still ENTERPRISE

**Comment by lnhsingh** [comment]
Also related to #8144
