### ISSUE TITLE
Outdated follower reads interval in Duplicate Indexes Topology doc 

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/docs#8262]
Re: [Duplicate Indexes Topology](https://cockroachlabs.com/docs//v20.1/topology-duplicate-indexes.html)

## Issue Description

in the Alternative section https://www.cockroachlabs.com/docs/v20.1/topology-duplicate-indexes.html#alternatives the seconds are 48 instead of 4.8.

> If reads from a table can be historical (48 seconds or more in the past), consider the Follower Reads pattern.
 
## Suggested Resolution

> If reads from a table can be historical (4.8 seconds or more in the past), consider the Follower Reads pattern.

**Comment by bdarnell** [comment]
I believe 48 seconds was correct in 19.2; the follower read threshold was reduced in 20.1.

**Comment by jseldess** [comment]
@rmloveland, looks like we forgot to update this 20.1 page when we reduced the follower reads interval.
