### ISSUE TITLE
set GOMAXPROCS when multiple nodes are on 1 machine

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#8265]
Ryan Kuo (taroface) commented:

When multiple nodes are on a single machine, GOMAXPROCS must be set in order to split CPU usage between the nodes. Not doing so can lead to constant context switching.

- Clarify in local deployment tutorials
- Add to troubleshooting doc?

Issue: https://github.com/cockroachdb/cockroach/issues/54034
Thread: https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1599740291177100

Jira Issue: DOC-692

**Comment by jseldess** [comment]
@taroface, mind sharing where this knowledge came from? I'm not sure we want to ever recommend running multiple nodes on a single machine. We do that in local tutorials for educational purposes only but have a disclaimer about not doing this in production.

**Comment by taroface** [comment]
Yes, please see the issue linked in the description (thought I had updated with this earlier, but it was somehow lost). It's based on a customer evaluating CRDB. 

My sense is that we already clearly describe multiple nodes on one machine as an anti-pattern (will double-check how and where in docs), but maybe less so in the context of local testing?

**Comment by asubiotto** [comment]
I think the user is aware that it is an anti-pattern (see https://github.com/cockroachdb/cockroach/issues/54034#issuecomment-689081027) and ran into this.
