### ISSUE TITLE
Add step to install sqlalchemy driver to Connect to Your CockroachCloud Cluster Doc 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8267]
Re: [Connect to Your CockroachCloud Cluster](https://cockroachlabs.com/docs//cockroachcloud/connect-to-your-cluster.html)

## Issue Description
sqlalchemy instructions on this page are missing the steps to install the driver. It only says to replace the `postgresql` url scheme with `cockroachdb`.

## Suggested Resolution 
Include the step to install sqlalchemy cockroachdb driver

```python
pip install sqlalchemy sqlalchemy-cockroachdb psycopg2
```

**Comment by jseldess** [comment]
I think that's by design, based on this sentene:
> The following language-specific versions assume that you have installed the relevant client drivers.

But I could see the value in providing the install instructions so there's nowhere else to go to get through the tutorial.

**Comment by lnhsingh** [comment]
Closing - as this is no longer relevant (sqlalchemy steps are no longer included on this doc)
