### ISSUE TITLE
Deployment docs: Issue commands to nodes remotely

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#827]
In all of the [cloud deployment docs](https://www.cockroachlabs.com/docs/cloud-deployment.html), instead of having the user SSH into the machine, issue all of the commands locally.

This change also obviates the need to SCP the client certificate to each node, so that would need to be removed from the document, as well.

**Comment by jseldess** [comment]
@mberhault, what are you thoughts here?

**Comment by mberhault** [comment]
What's the proposal here? What do we replace SSH/SCP with?

**Comment by jseldess** [comment]
I'm not certain. I suspect Sean's suggestions apply to the start node steps, but I'm not sure: https://www.cockroachlabs.com/docs/v2.1/deploy-cockroachdb-on-premises.html#step-3-start-nodes. 

@sploiselle, can you clarify?
