### ISSUE TITLE
security: Certificate revocation is now supported via OSCP

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8285]
PR: https://github.com/cockroachdb/cockroach/pull/53218

From release notes:
> Certificate revocation is now supported via OSCP and the [cluster setting](../v20.2/cluster-settings.html) `security.ocsp.mode`. This makes a call to the OCSP server on every connection attempt and may wait for up to value specified with the setting `security.ocsp.timeout`. [#53218][#53218] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
https://cockroachlabs.atlassian.net/browse/CRDB-59

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8495/
