### ISSUE TITLE
importccl: support IMPORT INTO for DELIMITED

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8290]
PR: https://github.com/cockroachdb/cockroach/pull/52628

From release notes:
> [`IMPORT INTO`](../v20.2/import-into.html) is now supported for `DELIMITED` and `PGCOPY` file formats. [#52628][#52628] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
PGCOPY can only include data for one table

**Comment by mwang1026** [comment]
Just don't doc PGCOPY for now. We should with delimited
