### ISSUE TITLE
sqlmigrations: remove 19.2 -> 20.1 schema change migration

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8292]
PR: https://github.com/cockroachdb/cockroach/pull/52968

From release notes:
> As part of the transition to v20.2, the migration to upgrade schema change jobs started prior to v20.1 is no longer run. [#52968][#52968] {% comment %}doc{% endcomment %}

**Comment by lucy-zhang** [comment]
https://github.com/cockroachdb/cockroach/pull/54902 supersedes this change and is the more relevant one to point out to users, since it actually marks jobs as failed (as opposed to merely not running them).
