### ISSUE TITLE
backupccl: add support for backups of UDT with revision_history

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8294]
PR: https://github.com/cockroachdb/cockroach/pull/53160

From release notes:
> [`BACKUP`](../v20.2/backup.html)s with `revision_history` now support including UDTs. [#53160][#53160] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
cc @mwang1026 fill in more details here

**Comment by lnhsingh** [comment]
Doesn't seem like docs are needed
