### ISSUE TITLE
 backupccl: add revision history backup support for user defined schemas

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8295]
PR: https://github.com/cockroachdb/cockroach/pull/53241

From release notes:
> User-defined schemas now support being backed up with revision history and restored with `AS OF SYSTEM TIME`. [#53241][#53241] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Doesn't need to be doc'ed. It's implied
