### ISSUE TITLE
backupccl: list of what's included in a cluster backup

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8296]
PR: https://github.com/cockroachdb/cockroach/pull/53203

From release notes:
> Scheduled jobs are now included in [cluster backups](../v20.2/backup.html#backup-a-cluster). [#53203][#53203] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Add info on what is included in a cluster backup to these sections:

- https://www.cockroachlabs.com/docs/v20.2/backup#backup-a-cluster
- https://www.cockroachlabs.com/docs/dev/take-full-and-incremental-backups.html#full-backups

**Comment by lnhsingh** [comment]
This might be a good issue for you to take, @gemma-shay. I think we need to add a list of what is included (and also maybe what is _not_ included) in a cluster backup. @mwang1026 or @dt should be able to help you with the details.
