### ISSUE TITLE
backupccl: remove enterprise check in SHOW

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8297]
PR: https://github.com/cockroachdb/cockroach/pull/53356

From release notes:
> As part of making basic [`BACKUP`](../v20.2/backup.html) and [`RESTORE`](../v20.2/restore.html) free to use without an enterprise license, [`SHOW BACKUP`](../v20.2/show-backup.html) and `SHOW BACKUPS IN` no longer require a license. [#53356][#53356] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing - already done.
