### ISSUE TITLE
sql: add CONTROLJOB role option

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8312]
PR: https://github.com/cockroachdb/cockroach/pull/52804

From release notes:
> Added the `CONTROLJOB` role option. When creating/altering roles, `CONTROLJOB` can be passed as a role option. For example, [`CREATE USER <user> CONTROLJOB CREATEROLE`](../v20.2/create-user.html). `NOCONTROLJOB` can be used to remove `CONTROLJOB` from the role when altering the role. `CONTROLJOB` allows the user to pause/resume and cancel jobs owned by non-admin users. `CONTROLJOB` also allows seeing all jobs owned by non-admin users, i.e., when running [`SHOW JOBS`](../v20.2/show-jobs.html). [#52804][#52804] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Not sure if @Amruta-Ranade or @lnhsingh should take this. Please discuss.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
