### ISSUE TITLE
colexec: add support for DISTINCT and FILTER hash aggregation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8315]
PR: https://github.com/cockroachdb/cockroach/pull/50721

From release notes:
> The [vectorized execution engine](../v20.2/vectorized-execution.html) now supports `DISTINCT` and `FILTER`ing hash aggregation. [#50721][#50721] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #8009.
