### ISSUE TITLE
sql: automatically add indexes needed by FKs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#832]
PR: https://github.com/cockroachdb/cockroach/pull/9572

@sploiselle, since you documented foreign keys, this would probably be a quick update for you.

**Comment by sploiselle** [comment]
@dt Just to clarify:
- Automatically creates index on the table that owns the constraint
- The referenced table is unaffected
- Dropping the constraint with `CASCADE` does not remove the index from the table that owns the constraint

LMK if I've got that square so I can update the docs.

**Comment by dt** [comment]
nit: Automatically creates index on constrained (referencing) columns _if one does not exist_, otherwise yes.

**Comment by sploiselle** [comment]
@dt Gotcha. What's the "if DNE" criteria? An index of only those columns in the same order as the constraint, or will it also check if that an eligible prefix of an existing index?

**Comment by dt** [comment]
Eventually it shouldn't care about order, just that the set are a prefix, but IIRC it does right now.
