### ISSUE TITLE
sql: disallow non-admin users from dropping admins

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8320]
PR: https://github.com/cockroachdb/cockroach/pull/52881

From release notes:
> Non-admin users with `CREATEROLE` are no longer permitted to drop users with the admin role. [#52881][#52881] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
