### ISSUE TITLE
colexec: add support for DISTINCT ordered aggregation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8323]
PR: https://github.com/cockroachdb/cockroach/pull/53145

From release notes:
> The [vectorized execution engine](../v20.2/vectorized-execution.html) now supports ordered aggregation with the `DISTINCT` clause. [#53145][#53145] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #8009.
