### ISSUE TITLE
sql: add CONTROLCHANGEFEED role option

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8324]
PR: https://github.com/cockroachdb/cockroach/pull/52869

From release notes:
> Introduced a new `CONTROLCHANGEFEED` role option. This grants non-admin roles the ability to create new changefeeds, as long as they have `SELECT` privileges on the target table. It can be conferred via `ALTER ROLE <role> CONTROLCHANGEFEED` and revoked via `ALTER ROLE <role> NOCONTROLCHANGEFEED`. [#52869][#52869] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Not sure if @lnhsingh or @Amruta-Ranade should take this. Please discuss.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
