### ISSUE TITLE
sql: support alter type owner

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8325]
PR: https://github.com/cockroachdb/cockroach/pull/52656

From release notes:
> Added support for `ALTER TYPE <type> OWNER TO <owner>`. The command changes the owner of a type. To use the conditions, the following conditions must be met: The user executing the command must be the owner of the type. The user executing the command must be a member of the new owner role. The new owner role must have `CREATE` on the schema the type belongs to. [#52656][#52656] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by #8022.
