### ISSUE TITLE
sql: add CREATEDB role option

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8326]
PR: https://github.com/cockroachdb/cockroach/pull/52831

From release notes:
> Introduced a new `CREATEDB` role option. This grants non-admin roles the ability to create new databases. It can be conferred via `ALTER ROLE <role> CREATEDB` and revoked via `ALTER ROLE <role> NOCREATEDB`. [#52831][#52831] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
