### ISSUE TITLE
sql: add VIEWACTIVITY and CANCELQUERY role options

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8329]
PR: https://github.com/cockroachdb/cockroach/pull/53291

From release notes:
> Introduced a new `VIEWACTIVITY` role option. This grants non-admin roles the ability to see other users' sessions and queries through [`SHOW SESSIONS`](../v20.2/show-sessions.html), [`SHOW QUERIES`](../v20.2/show-queries.html), and the [Admin UI Statements page](../v20.2/admin-ui-statements-page.html). [#53291][#53291] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
