### ISSUE TITLE
sql: add VIEWACTIVITY and CANCELQUERY role options

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8330]
PR: https://github.com/cockroachdb/cockroach/pull/53291

From release notes:
> Introduced a new `CANCELQUERY` role option. This grants non-admin roles the ability to cancel other users' queries and sessions. Note that non-admins are not allowed to cancel the queries or sessions of admins. [#53291][#53291] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
