### ISSUE TITLE
opt: add INSERT ON CONFLICT WHERE syntax for selecting arbiter indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8333]
PR: https://github.com/cockroachdb/cockroach/pull/53067

From release notes:
> An [`INSERT ... ON CONFLICT DO UPDATE`](../v20.2/insert.html#on-conflict-clause) statement without a list of column names after `ON CONFLICT` now results in a SQL syntax error with the error code `42601`. Previously, it errored with the message "there is no unique or exclusion constraint matching the ON CONFLICT specification" and the error code `42P10`. [#53067][#53067] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Only the error code changed on this (the syntax remains the same), so I don't think this needs documentation.
