### ISSUE TITLE
sql: support the `USAGE` privilege on schemas

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8337]
PR: https://github.com/cockroachdb/cockroach/pull/53358

From release notes:
> Added support for the `USAGE` privilege on schemas. [#53358][#53358] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Since this is a new feature, not sure if you want to handle this or pass over to @Amruta-Ranade. Please discuss.

**Comment by vy-ton** [comment]
@Amruta-Ranade Eric mentioned that you were helping SQL with these docs. I wanted to share the user acceptance that has been done with privileges and schemas, [here](https://docs.google.com/document/d/10rE85P65UtMz0rLGgzPQj2jNNhsVbjDFRm-Fv5TL1Fk/edit#) and [here](https://docs.google.com/document/d/1ViT3MwzqSK8Ofc8WQrH0tPI4zrmFwIz4fJdtHqE-5mw/edit#heading=h.l4q8cfhgrgtd). Let me know if I can answer any questions

**Comment by Amruta-Ranade** [comment]
This is very helpful! Thanks, Vy!!
