### ISSUE TITLE
sql: add cluster setting for maximum read buffer size

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8339]
PR: https://github.com/cockroachdb/cockroach/pull/53445

From release notes:
> Added an invisible [cluster setting](../v20.2/cluster-settings.html) `sql.conn.max_read_buffer_message_size`, which allows users to configure [SQL statement](../v20.2/sql-statements.html) maximum sizes across the cluster. This effect will take place upon connection restart. [#53445][#53445] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This is not a public cluster setting.
