### ISSUE TITLE
sql: add SHOW TRANSACTIONS

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8342]
PR: https://github.com/cockroachdb/cockroach/pull/51902

From release notes:
> Added the `SHOW TRANSACTIONS` statement, similar to [`SHOW SESSIONS`](../v20.2/show-sessions.html) and variants. It shows the currently active transactions in the node or cluster, and some information about them. [#51902][#51902] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
I can take this one (unless you were planning on working on it this week @ericharmeling?)

**Comment by ericharmeling** [comment]
Note that all new statements qualify for using help text rather than diagrams. (See https://github.com/cockroachdb/docs/pull/8486/files#diff-2a674e8a9cdb7d7df6bb342d4b84a2a4 for an example)
