### ISSUE TITLE
sql: allow non-admins to perform some RESTOREs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8349]
PR: https://github.com/cockroachdb/cockroach/pull/53650

From release notes:
> Non-admin users are now permitted to execute [`RESTORE`](../v20.2/restore.html) statements as long as the restore does not depend on implicit credentials and the user has the appropriate privileges to create all of the resulting database objects. For database restores, this means the user must have the `CREATEDB` role privilege. For table restores, the user must have `CREATE` privileges on the parent database. Full cluster restores still require admin privileges. [#53650][#53650] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Closing in favor of #8432
