### ISSUE TITLE
sql: add MODIFYCLUSTERSETTING role option

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8352]
PR: https://github.com/cockroachdb/cockroach/pull/53930

From release notes:
> Introduced a new `MODIFYCLUSTERSETTING` role option. This grants non-admin roles the ability to modify certain [cluster settings](../v20.2/cluster-settings.html), currently limited to settings with the "sql.defaults" prefix. [#53930][#53930] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8629
