### ISSUE TITLE
sql: support specifying custom index parameters for geospatial indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8356]
PR: https://github.com/cockroachdb/cockroach/pull/52800

From release notes:
> Introduced the `s2_max_level`, `s2_level_mod`, and `s2_max_cells` storage parameters for modifying the S2 parameters for indexing [`GEOMETRY` and `GEOGRAPHY`](../v20.2/spatial-data.html) data types in an inverted index. [#52800][#52800] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #8617
