### ISSUE TITLE
sql: support specifying custom index parameters for geospatial indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8357]
PR: https://github.com/cockroachdb/cockroach/pull/52800

From release notes:
> Introduced the `geometry_min_x`, `geometry_min_y`, `geometry_max_x`, `geometry_max_y` storage parameters for indexing GEOMETRY data types in an inverted index. [#52800][#52800] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #8617
