### ISSUE TITLE
builtins: use ST_Union as aggregate

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8371]
PR: https://github.com/cockroachdb/cockroach/pull/53127

From release notes:
> Implemented the `ST_Union` [builtin](../v20.2/functions-and-operators.html#built-in-functions) as an aggregate. The previous alpha-available `ST_Union` for two arguments is deprecated. [#53127][#53127] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #8582
