### ISSUE TITLE
server: Make --storage-engine flag non-sticky, use Pebble by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8392]
PR: https://github.com/cockroachdb/cockroach/pull/52944

From release notes:
> The [`--storage-engine`](../v20.2/cockroach-start.html#storage-engine) CLI flag no longer defaults to using the last-used storage engine when unspecified. Instead, Pebble is used by default unless otherwise specified using the `--storage-engine` flag. [#52944][#52944] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed in #8833
