### ISSUE TITLE
cli: add aliases for userfile commands and switch ls to list

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8393]
PR: https://github.com/cockroachdb/cockroach/pull/53074

From release notes:
> Added alias commands `ls` and `rm` for `userfile list` and `userfile delete`. [#53074][#53074] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
We aren't documenting the `ls` and `rm` aliases for now.
