### ISSUE TITLE
sql: use the new EXPLAIN infrastructure for UI plans

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8402]
PR: https://github.com/cockroachdb/cockroach/pull/52956

From release notes:
> Improved how [SQL statement plans](../v20.2/admin-ui-statements-page.html#logical-plan) in the Admin UI are populated, using the new `EXPLAIN` infrastructure. [#52956][#52956] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing as I don't think this will have a user-facing change.
