### ISSUE TITLE
Minor grammar/format edits on Basic Production Topology Doc 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8407]
Re: [Basic Production Topology](https://cockroachlabs.com/docs//v20.1/topology-basic-production.html)

## Issue Description
I spotted three various issues in this document

1. This statement is repeated twice, once in the Tip section and once in the prerequisites.

Tip:
If you haven't already, review the full range of topology patterns to ensure you choose the right one for your use case.

2. Missing `the`

App and load balancer in same region as VMs for CockroachDB

3. The bullet formatting for the last item is different from the rest.

Provision hardware as follows:

 - 1 region with 3 AZs
 - 3+ VMs evenly distributed across AZs; add more VMs to increase throughput
 - App and load balancer in same region as VMs for CockroachDB
 * The load balancer redirects to CockroachDB nodes in the region

**Comment by lnhsingh** [comment]
@jseldess assigning this to you since (I think) you were the last to work on this doc, but I also marked it as a `good-first-issue` for Hacktoberfest

**Comment by jseldess** [comment]
I'm good with this being for external contributors, @lnhsingh! Thanks for checking.

**Comment by dgabriel123** [comment]
I made the proposed changes to the Topology Doc [here](https://github.com/cockroachdb/docs/pull/8470). Let me know what you think.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8470
