### ISSUE TITLE
Technical Advisory 54418

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#8418]
@dbist 

Advisory 54418 - Incorrect behavior with large batch Upserts

[Copied from internal tracking doc]

**Description**

CockroachDB release 20.1.4 introduced a bug when handling UPSERT, UPSERT RETURNING, and INSERT … ON CONFLICT DO UPDATE SET x = excluded.x  statements involving more than 10,000 rows.  Processing of a single UPSERT statement will halt without a visible error after reaching 10,000 rows. The reported number of affected rows will be incorrect, reported as 0.  Additionally, any single UPSERT … RETURNING statement will also return at most 10,000 rows.
This bug was introduced in PR #51944, which was intended to correct a previously-identified error in UPSERT handling.  A fix has been committed in PR #54418 and will be available in the 20.1.6 release.

**Statement**

This public issue is tracked as PR #54418, which corrects the aforementioned bugs.

**Mitigation**

This regression is critical as it may silently corrupt SQL data without remediation. All unaffected customers are urged to skip releases 20.1.4 and 20.1.5 or ensure their application code processes at most 10000 rows per UPSERT statement. Customers running versions 20.1.4 or 20.1.5 are strongly encouraged to upgrade to 20.1.6, available now<<link goes here>>.

**Impact**

All deployments running CockroachDB 20.1.4 and 20.1.5 are affected.  Cockroach Labs acknowledges the issue and has issued a fix that will be available in the next maintenance release. All of the other supported releases (19.1.X, 19.2.X, 20.1.0-20.1.3) are not impacted.

---- 

This should go out with the [v20.1.6 release notes](https://github.com/cockroachdb/docs/issues/7985). 

In addition to creating a new [technical advisory page](https://www.cockroachlabs.com/docs/advisories/index.html), we need to:

* Remove links to binaries from the [releases page](https://www.cockroachlabs.com/docs/releases/#production-releases), and from the respective release note pages. 
* Add a warning callout to the affected release note pages.

**Comment by ericharmeling** [comment]
@jseldess 

> this might mean we should post a warning to the v20.1.4 and v20.1.5 release notes pages themselves pointing at the tech advisory. We may also want to add a note to the v20.1 rolling upgrade doc.

**Comment by bobvawter** [comment]
Also will want to walk back the LATEST tags in DockerHub.

**Comment by ericharmeling** [comment]
Closed by #8435
