### ISSUE TITLE
schedules: prometheus metrics and alerting rules

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#8420]
Placeholder for now and I'll add metrics here

cc @miretskiy

**Comment by mwang1026** [comment]
these metrics are aggregates across all schedules

`schedules_BACKUP_failed` - counter for # of backups started by a schedule that failed
`schedules_BACKUP_started` - counter for # of backups started by a schedule (total)
`schedules_BACKUP_succeeded` - counter for # of backups started by a schedule that succeeded

alerting recommendation:
- when `schedules_BACKUP_failed` increments, run `SHOW SCHEDULES` to check which schedule and inspect the error in the "status" column

**Comment by miretskiy** [comment]
The exported metrics fall into 2 categories (for now): backup schedules specific metrics, described above by @mwang1026, and the scheduler specific metrics.

In addition to monitoring backup schedule metrics above (particularly, failed counters), it might also be helpful to monitor:
  
  * schedules.round.reschedule-wait -- 
     The number of schedules that were rescheduled due to currently running job. This corresponds to schedule 
    `on_previous_running=wait` policy:  https://www.cockroachlas.com/docs/v20.2/create-schedule-for-backup
     It's a gage that changes every scheduling "round".  Basically, having >0 value here for some period of time indicates
     that when the next backup starts, the previous one is still running.
  * schedules.round.reschedule-skip
     Similar to the above, but instead of waiting, number of schedules that were rescheduled (because the previous job still 
    running).

There are other metrics, but I think they are internal enough (i.e. schedules.malformed -- number of schedules that we just couldn't parse.  This should always be 0.  The only way to get that is if the schedules table was mutated directly to somehow "corrupt" the data).
