### ISSUE TITLE
BACKUP INTO: Document new syntax

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#8431]
The new `BACKUP INTO` syntax needs to be created. Organization here could be tricky -- maybe it's a different section but we prefer `INTO` to be the preferred syntax we highlight, as we plan to deprecate `TO` in the future.

Things to note:
- Permissions needed -- same as `TO` where we need list access so HTTP won't work
- The structure of the directories created by `INTO` and `INTO LATEST`
- Potential wonky impact of backing up two different backups (groups of DBs, two clusters, etc.) to the same base directory (as in, don't do it)
- How to to `SHOW BACKUPS IN` and `SHOW BACKUP X IN Y` (and how `SHOW BACKUPS IN` gives you a durable -- as long as you don't move files -- implied backup history)
- How this maps to `RESTORE` syntax when restoring from a collection

**Comment by lnhsingh** [comment]
Per our discussion, I'm holding off on this update until after the 20.2 release, when we have time to put a deprecation plan in place for `BACKUP TO`. For v20.2:

- We'll keep `BACKUP TO` on the `BACKUP` statement page
- Only surface the new `INTO` syntax on the `CREATE SCHEDULE FOR BACKUP` page
- The `SHOW BACKUPS` page will be updated to include `SHOW BACKUPS IN y` for scheduled backups (this will need to be changed/expanded upon in the future)
- Update the `RESTORE` page to show to how restore from a collection
