### ISSUE TITLE
permissions for bulk features: Changes in 20.2

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#8432]
With the new `operator` role created, we wanted to make certain Bulk IO features non-admin since there's a future where CC users won't have `admin` access. We should update our docs to clearly delineate what requires `admin` and what doesn't.

IMPORT
BACKUP
RESTORE
CREATE SCHEDULE FOR BACKUP
SHOW commands for jobs, schedules, backups
CREATE CHANGEFEED
EXPORT

**Comment by lnhsingh** [comment]
cc @mwang1026 to fill in

**Comment by lnhsingh** [comment]
@mwang1026 - do you have time to list the changes here / delineate what needs admin access? Or, can you point me to the right person / PRs that address this?

**Comment by lnhsingh** [comment]
Related to #8349:

PR: cockroachdb/cockroach#53650

From release notes:

Non-admin users are now permitted to execute RESTORE statements as long as the restore does not depend on implicit credentials and the user has the appropriate privileges to create all of the resulting database objects. For database restores, this means the user must have the CREATEDB role privilege. For table restores, the user must have CREATE privileges on the parent database. Full cluster restores still require admin privileges. [#53650][#53650] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Here's a text version. Let me dig up the PRs. There were a mix of bulk-io and SQL so... a bit of a mess

RESTORE
do not allow full cluster restores (have to be admin)
do not allow tenant restores (admin)
database RESTORE require CREATEDB

external storage paths allowed
	cloud storage with explicit credentials
	userfile

external disallowed
	implicit cloud storage
	http, https and custom endpoints
	nodelocal

IMPORT
external storage destination with same restrictions as RESTORE
CREATE privilege

IMPORT INTO
external storage destination with same restrictions as RESTORE
INSERT, DROP

BACKUP
external storage destination with same restrictions as RESTORE

database - select
table - select
type, schema - usage

do not allow full cluster (must be admin)
do not allow tenant (must be admin)





CONTROLCHANGEFEED role option required, if non-admin, to create changefeed. To remove use NOCONTROLCHANGEFEED 

https://github.com/cockroachdb/cockroach/pull/52869

CONTROLJOB role option required because you can't manage jobs without this (pause, show jobs, etc.). NOCONTROLJOB role option used to remove that ability.

https://github.com/cockroachdb/cockroach/pull/52804

both needed for changefeed

**Comment by lnhsingh** [comment]
Chatted with Michael yesterday -- this update can wait until after the release since it's tied more to adding the `operator` role for CC.

**Comment by lnhsingh** [comment]
Closing this issue in favor of https://github.com/cockroachdb/docs/issues/9179
