### ISSUE TITLE
Development Topology Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8434]
Re: [Development Topology](https://cockroachlabs.com/docs//v20.1/topology-development.html)

## Issue Description
The following language is repeated twice. "If you haven't already, review the full range of topology patterns to ensure you choose the right one for your use case."

## Suggested Resolution 
Either remove the Tip section or remove the language from the Prereqs.

**Comment by Anita-ihuman** [comment]
I’d love to tackle this

**Comment by dgabriel123** [comment]
I made the change already in #8470

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8470
