### ISSUE TITLE
Update relevant docs with new permission schemes

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#8439]
We introduced a few more role permissions to alleviate the need for admin across IMPORT, BACKUP, RESTORE and CHANGEFEED. We should embed these rules into the features themselves and point to the relevant `ALTER` or `GRANT` pages to give folks those roles to perform those tasks.

**DETAILS COMING AS I TEST THE DETAILS :D **

**Comment by lnhsingh** [comment]
Closing because this is a dupe of #8432
