### ISSUE TITLE
Add supported Sequelize version to Build a Node.js App with CockroachDB and Sequelize doc 

### ISSUE THREAD

**Issue by mosmaall** [cockroachdb/docs#8440]
Re: [Build a Node.js App with CockroachDB and Sequelize](https://cockroachlabs.com/docs//v20.1/build-a-nodejs-app-with-cockroachdb-sequelize.html)

## Issue Description
Demo not working with `sequelize` version 4, 5 and 6.
Nothing happen after run command `node sequelize-basic-sample.js`.
But for `pg` demo it working as expected.

**Comment by lnhsingh** [comment]
Thanks for submitting this issue @mosmaall. I think this sample app only works with Sequelize v3, but @ericharmeling can confirm.

Eric - I think we should add what version we support (and/or update the app to support v4+). If we are just adding the supported version, this might be a `good-first-issue`. I'll let you decide-- feel free to unassign yourself and label!

**Comment by rafiss** [comment]
I would have expected v4 and v5 to work already. cc @vy-ton

**Comment by 2bit-hack** [comment]
I replaced `npm install sequelize sequelize-cockroachdb` with `npm install sequelize@3 sequelize-cockroachdb` and followed the remaining instructions, but still did not get any output at all. The installed version of `Sequelize` was `3.35.1`.

**Comment by vy-ton** [comment]
Our goal is to have a GA release of Sequelize 5 and 6 support by 5/15. We should updated our examples to use the latest adapter

**Comment by vy-ton** [comment]
@ericharmeling I believe we can close this now that we have Sequelize support up to v6, which the [docs](https://www.cockroachlabs.com/docs/v21.1/third-party-database-tools.html) reflect
