### ISSUE TITLE
Incorrect RPO on comparison page

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/docs#8451]
Chris Casano (chriscasano) commented:

On our database comparison page, we have a rather large typo.  For the "Automated Repair and RPO" category, we have "Automated Repair RPO <10 sec" for CockroachDB.   This should say "Automated Repair, RPO = 0".  For CockroachDB RTO is < 10 sec and RPO is 0.  This should be a quick fix.

https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html

**Comment by chudro** [comment]
We should change the title for that line item to: "Database Repair and RPO"? And if we add RTO, should we add that to both the title and values to all of the entries?

**Comment by mcallica** [comment]
Another change for the comparison page: Add Aurora info.

**Comment by lnhsingh** [comment]
The comparison page is maintained by Product Marketing so alerting @jaymce to this.
