### ISSUE TITLE
SHOW GRANTS only shows for current database

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/docs#8452]
Paul Logan (pxlogan) commented:

In the documentation we say that show grants list all grants for all users and roles on all databases and tables.  This is not true, it will only show the grants for the users and roles on the current database.  

To list all grants for all users and roles on all databases and tables you need to set the flag sql_safe_update to false, which allows you to set the current database to null, at that point you can list all grants for all users and roles on all databases and tables.

I am not sure we want to publicise this, but the documentation should be updated to say that show grants list all grants for all users and roles on the current databases and its tables at least.

**Comment by lnhsingh** [comment]
@ericharmeling - not sure if this falls under SQL or security. Feel free to discuss with @Amruta-Ranade or reassign.

**Comment by thtruo** [comment]
Picking this up for fixit
