### ISSUE TITLE
Sidebar not expanding to current page

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8454]
When you visit a page, The sidebar is not automatically expanding to show the position of that page in the left-nav hierarchy.

Reproduction:

1. Visit [Duplicate Indexes Topology](https://www.cockroachlabs.com/docs//v20.1/topology-duplicate-indexes.html)
2. Notice that the left-nav sidebar is closed, and only the headings *CockroachDB* and *CockroachCloud* are visible.

It was mentioned to me that the two `/` characters in the URL may be the cause, but I am also seeing this behavior on the [Releases page](https://www.cockroachlabs.com/docs/releases), which should (I think) have the left-nav tree opened to the *Production Releases* heading.

**Comment by rmloveland** [comment]
FYI @jseldess and @yingzhuchin 

YZ should I apply a specific label so it comes to the correct backlog? Or assign to you directly?

Happy to do what is best, sorry I don't know this already

**Comment by jseldess** [comment]
I see the issue. In your link, there are two forward slashes after `/docs`: https://www.cockroachlabs.com/docs//v20.1/topology-duplicate-indexes.html. That seems to confuse the sidenav. For normal urls, it works fine. 

@yingzhuchin, any ideas?

@rmloveland, how did you land on that url?

**Comment by yingzhuchin** [comment]
I'm not sure how we would end up with two forward slashes. It would be great to know how that page was reached.

As for the Releases page, looks like it's because there is no sidenav item linking to that exact URL ("/releases"). We have sidenav items linking to anchor positions "releases/#production-releases" but our script doesn't seem sophisticated enough to handle those.

**Comment by yingzhuchin** [comment]
This is the same behavior as before the CC sidenav merge: https://5f4d423a451a5b0008adcbff--cockroachdb-docs.netlify.app/docs/releases/#production-releases, so it is not something we recently broke.

**Comment by rmloveland** [comment]
re: how are we getting the two forward slash URLs? that URL was generated by the issue creation button on the docs site - I clicked through from the link here: https://github.com/cockroachdb/docs/issues/8262

re: the releases page - good to know!  guess I had missed that fact, so nothing to do there I guess - sorry for the noise on that one

**Comment by yingzhuchin** [comment]
I think we should still try to fix/improve the releases page wonkiness, even though it's behaving as it had been!
