### ISSUE TITLE
Update recommendation for storage per vCPU to 150GiB on the Production Checklist doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8466]
Re: [Production Checklist](https://cockroachlabs.com/docs//v20.1/recommended-production-settings.html)

## Issue Description
we have two contradicting recommendations for storage per vCPU
1. 60GB per vCPU
2. 150GB per vCPU

## Suggested Resolution 
Please clarify

**Comment by dbist** [comment]
cc: @a-entin

**Comment by a-entin** [comment]
It was recently updated from 60 (as of 19.x) to 150 (as of 20.x). one place was apparently overlooked. Should be 150 in both places as of 20.x of course

**Comment by AninditaBasu** [comment]
@Amruta-Ranade Can I work on this doc update?

**Comment by jseldess** [comment]
@AninditaBasu, I'd actually prefer that @taroface takes this issue, as it relates to updates he recently made.

@taroface, I think we updated to 150 in some places but not in all places on the checklist. Can you please take a look?

**Comment by taroface** [comment]
Fixed. Thanks @dbist for filing.
