### ISSUE TITLE
Modify --background flag in cockroach start(-single-node) documentation

### ISSUE THREAD

**Issue by cubuzz** [cockroachdb/docs#8472]
Re: [cockroach start-single-node](https://cockroachlabs.com/docs//v20.1/cockroach-start-single-node.html)

## Issue Description
On Windows, `cockroach start-single-node` does not accept the --background flag
## Suggested Resolution 
Add info that `--background` is not available on the Windows binary.

**Comment by Snackomat** [comment]
It appears that this only affects the Windows binary and also occurs in other contexts, such as `cockroach start`.

**Comment by mikeCRL** [comment]
Taking on this issue. I've confirmed this with CockroachDB v.20.2.3 in a Windows VM. Getting `ERROR: unknown flag: --background` when using it with both `start` and `start-single-node`. I'm able to start the node successfully when I drop the flag.

**Comment by mikeCRL** [comment]
@piyush-singh Would you like to review the [PR](https://github.com/cockroachdb/docs/pull/9247) and/or ask an engineer to? Also, do you know if this should be considered a known limitation or bug? If a limitation, we should consider adding it [here](https://www.cockroachlabs.com/docs/v20.2/known-limitations). I'd be happy to test prior versions of CRDB to confirm whether this was always the case or when it changed, if that would be helpful.
