### ISSUE TITLE
sql/catalog, backupccl: support offline descriptors, add all new restored descriptors in offline state

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8474]
PR: https://github.com/cockroachdb/cockroach/pull/54296

From release notes:

> - Databases being restored will now be in the offline state, invisible to users, until the data has been restored. This is the same as the existing behavior for restored tables. (This change is also applied to enums and user-defined schemas being restored, which is a change relative to only the v20.2 alpha releases.) [#54296][#54296]

**Comment by mwang1026** [comment]
Closing for now. We should bundle this with a "restore steps" update if we choose to do that, rather than just adding one note about one step.
