### ISSUE TITLE
release-20.2: kvserver/rangefeed: use pointers for events

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8498]
PR: https://github.com/cockroachdb/cockroach/pull/54631

From release notes:
> Reduced the memory overhead of rangefeeds (i.e., long-lived requests) which reduces the memory overhead for running [CHANGEFEED](https://www.cockroachlabs.com/docs/v20.2/stream-data-out-of-cockroachdb-using-changefeeds.html)s over large tables. [#54631][#54631] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Don't need to doc.
