### ISSUE TITLE
release-20.2: sql/catalog: disallow uncached resolution of draining names

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8499]
PR: https://github.com/cockroachdb/cockroach/pull/54384

From release notes:
> After renaming a database, schema, or type, the old names are now immediately inaccessible from other sessions when referred to in schema change statements as soon as the new name is committed. This matches the existing behavior for tables. **This is a change from earlier 20.2 beta releases.** [#54384][#54384] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we necessary need to document this, as it's expected behavior.

@lucy-zhang Please reopen if you disagree.
