### ISSUE TITLE
release-20.2: sql: disable interleaved joins by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8504]
PR: https://github.com/cockroachdb/cockroach/pull/54162

From release notes:
> [Interleaved joins](../v20.2/interleave-in-parent.html) are now disabled by default and will be entirely removed in the 21.1 release, because they are often slower than the [merge join](../v20.2/joins.html#merge-joins). [#54162][#54162] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
We don't currently document a special type of join for interleaved tables. 

@yuzefovich 

> I think we can keep all the previous guidance because in all cases when an interleaved join can be planned, we can also plan a merge join

Closing.
