### ISSUE TITLE
release-20.2: backupccl: change CREATE SCHEDULE output `name` column to `label`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8505]
PR: https://github.com/cockroachdb/cockroach/pull/54397

From release notes:
> [`CREATE SCHEDULE`](../v20.2/create-schedule-for-backup.html) output now has a column called `label` which was previously called `name`. [#54397][#54397] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
This was already documented.
