### ISSUE TITLE
release-20.2: sql: disallow role/user drops if they own a schema or a type

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8506]
PR: https://github.com/cockroachdb/cockroach/pull/54511

From release notes:
> If a user/role has ownership over a type or a schema, it is no longer possible to drop them using [`DROP ROLE`](../v20.2/drop-role.html). [#54511][#54511] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8767
