### ISSUE TITLE
release-20.2: sql: don't allow cross-database sequence owners

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8511]
PR: https://github.com/cockroachdb/cockroach/pull/54585

From release notes:
> [Creating sequences](../v20.2/create-sequence.html) that are `OWNED BY` columns in tables in other databases is now disallowed (and can be re-enabled via the `sql.cross_db_sequence_owners.enabled` cluster setting). [#54585][#54585] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@Amruta-Ranade FYI, the cluster settings should be up-to-date as of https://github.com/cockroachdb/docs/pull/8544.

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/cockroachdb/docs/pull/8767
