### ISSUE TITLE
Convert the docs website to a Progressive Web App

### ISSUE THREAD

**Issue by Manaswini1832** [cockroachdb/docs#8528]
ISSUE / FEATURE REQUEST:
We could convert the website to a PWA (Progressive web app) by providing an "Add to Homescreen" button, which when clicked, can add  it to our home screen to be read whenever needed. 

WOULD YOU LIKE TO WORK ON IT? 
Yes, I'd like to take this issue up and work on it.

**Comment by Amruta-Ranade** [comment]
Can you elaborate on what value this will add to the user experience? 
Also, if you are looking for Hacktoberfest projects, the to-do apps repo might be of more interest to you: https://github.com/cockroachdb/cockroachdb-todo-apps

**Comment by Manaswini1832** [comment]
It might not add much to the user experience, but since a PWA also works offline, the docs can be read by the user whenever they want and also since PWAs have access to a user's phone's push notifications, it can lead to higher reach. 
Talking about the to-do repo, yeah I've looked into it. I'll start working on it soon😊

**Comment by Amruta-Ranade** [comment]
Users can bookmark the site and access it when they need it. Not sure we need an app that pushes notifications to drive readership to the docs -- we don't want to spam the users.

**Comment by Manaswini1832** [comment]
OK cool then. I'll work on the to-do app👍

**Comment by lnhsingh** [comment]
Closing this issue for now!
