### ISSUE TITLE
Orchestrate CockroachDB Across Multiple Kubernetes Clusters Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8533]
Re: [Orchestrate CockroachDB Across Multiple Kubernetes Clusters](https://cockroachlabs.com/docs//v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html)

## Issue Description
`python teardown.py`
step is missing copy option

**Comment by dufcrule** [comment]
I'd be happy to take this one on as a first pull request for CockroachDB @Amruta-Ranade
