### ISSUE TITLE
Add hyperlink to FAQ Page

### ISSUE THREAD

**Issue by dankellycockroach** [cockroachdb/docs#8540]
Hey @jseldess ,

I'm working on an SEO campaign in which I am trying to optimize our website for the keyword: "Distributed SQL" 

In the [FAQ page]([https://www.cockroachlabs.com/docs/v20.1/frequently-asked-questions.html], under the section "What is CockroachDB?" there is a reference to distributed sql. I'd simply like to hyperlink that text with this url: https://www.cockroachlabs.com/blog/what-is-distributed-sql/

The goal is to create a series of internal and external backlinks that all lead to that one URL. 

Let me know if you are okay with this or not. Thanks!

**Comment by lnhsingh** [comment]
Thanks for submitting this issue @dankellycockroach! This update seems fine to me and is a good issue for Hacktoberfest :)

**Comment by Shiwanee** [comment]
@lnhsingh , I can help you with this one.

Thanks,
Shiwanee

**Comment by lnhsingh** [comment]
Closed by #8589. Thank you @Shiwanee!
