### ISSUE TITLE
HTTP_PROXY environment variable possibly harmful

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/docs#8583]
https://www.cockroachlabs.com/docs/stable/export.html

If the user is going to specify an `HTTP(S)_PROXY` environment variable, this will also affect inter-node GRPC traffic.  The proxy must be configured to transparently pass HTTP/2+GRPC inter-node traffic.  The issue below has been filed to look into bypassing the proxy environment variables for inter-node communications.

X-Ref: https://github.com/cockroachdb/cockroach/issues/55289

**Comment by bdarnell** [comment]
Update from cockroachdb/cockroach#55289: CRDB 20.1 and older do not use the `HTTP(S)_PROXY` variables for intra-node communication. Current 20.2 prereleases use it only for the "join RPC" when adding a node to the cluster, which prevents new clusters from starting or adding nodes to an existing cluster. This will be fixed soon so proxies will once again be ignored for all intra-node traffic (unclear at this point whether it'll get in to 20.2.0 or if it'll be 20.2.1).

**Comment by lnhsingh** [comment]
@taroface I _think_ this falls more in deploy ops but I added myself as an assignee too

**Comment by ericharmeling** [comment]
It looks like this was fixed by https://github.com/cockroachdb/cockroach/pull/55502. Closing. Please re-open if I'm mistaken.
