### ISSUE TITLE
release-20.2: sql: update search_path semantics to match pg now that we support UDS

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8590]
PR: https://github.com/cockroachdb/cockroach/pull/54586

From release notes:
> The default search path for all sessions is now `$user, public` (as opposed to just `public`). This affects our name resolution semantics; now, if a table is present in both the `public` schema and the schema named the current user's username, an unqualified object name will be searched/placed in the user's schema. This doesn't impact the search semantics of tables in `pg_catalog`/`information_schema`/`temp_schema` -- these continue to be searched before checking the `$user` schema and the `public` schema. [#54586][#54586] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I believe this was resolved by #8273.
Does that sound right, @arulajmani ?

I also opened a follow-up PR that clarifies the naming resolution page quite a bit (#8493).

**Comment by arulajmani** [comment]
Yup!
