### ISSUE TITLE
release-20.2: cli/sql: further polish statement statistics

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8591]
PR: https://github.com/cockroachdb/cockroach/pull/54765

From release notes:
> The display of statement timings in the SQL shell ([`cockroach sql`](../v20.2/cockroach-sql.html) and [`cockroach demo`](../v20.2/cockroach-demo.html)) has been simplified. [#54765][#54765] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I think this is covered by https://github.com/cockroachdb/docs/issues/8514, for which I've opened https://github.com/cockroachdb/docs/pull/8586.
