### ISSUE TITLE
Document /_status/nodes endpoint

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#8602]
Related to #7357, #7824, and #6631.

As part of our effort to improve documentation of our HTTP API endpoints, we will start with `/_status/nodes`. We expect this endpoint to be useful for scripting automated health checks for clusters. As part of documenting this endpoint for secure clusters, we should show a full example that walks through the authentication workflow. Reproducing Ron's steps from a recent support ticket below:

```
What you'll want to do is use cockroach auth-session login if you use the environment variable COCKROACH_DISABLE_WEB_LOGIN=true it will disable the login for the web ui.
In order to use cockroach auth-session login you'll need to create a user you can do so by running the command:
CREATE USER <YOUR USER> WITH PASSWORD '<YOUR PASSWORD';
Once you have created the user you'll run the following in your CLI:
cockroach auth-session login <YOUR USER> --certs-dir=certs
This will generate a session ID and an authentication cookie that looks something like this:
  username |     session ID     |                       authentication cookie
-----------+--------------------+---------------------------------------------------------------------
  craig    | 593920174630502401 | session=CIGAqM6I6IGfCBIQKS/ul2Wvx6D/qiVPp7lpeA==; Path=/; HttpOnly
(1 row)
#
You'll then want to take that authentication cookie and use it for your curl command like this:
curl -k -v --cookie  "session=CIGAqM6I6IGfCBIQKS/ul2Wvx6D/qiVPp7lpeA==; Path=/; HttpOnly" https://localhost:8080/_status/nodes
```

**Comment by jseldess** [comment]
@taroface, if we want to get this done for the 20.2 release, we should set up time within the next week or two to look at the generation process together.

**Comment by taroface** [comment]
@piyush-singh We'll also need to make sure the description fields are populated for the API parameters. cc @knz

**Comment by taroface** [comment]
@piyush-singh Do you know if the auth flow Ron described should apply to all our HTTP endpoints? Or will there be any endpoint-specific details other than the actual resource?

**Comment by aayushshah15** [comment]
The auth flow should be required for all our endpoints except for the `/health` ones (unless the customer is running with the `--insecure` flag. We can explain the auth flow, as described here, at the top of our `admin` and `status` proto files.

**Comment by taroface** [comment]
Resolved by the Cluster API docs.
