### ISSUE TITLE
v20.1 BACKUP Doc Update misleading example name

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/docs#8603]
Re: [BACKUP](https://cockroachlabs.com/docs//v20.1/backup.html)

## Issue Description

In section https://www.cockroachlabs.com/docs/v20.1/backup.html#example-file-urls, the example file 'employees.sql' is a bit misleading as the output of BACKUP is not a sql dump file (where the extension for that file would be indeed '.sql') but instead is a set of .sst files in a more complex dir structure.

## Suggested Resolution 

I suggest we change the name from 'employees.sql' to 'cluster-name' or 'database-name'.

**Comment by lnhsingh** [comment]
Thanks for filing this issue @fabiog1901! I updated [v20.2 docs](https://www.cockroachlabs.com/docs/v20.2/use-cloud-storage-for-bulk-operations#example-file-urls) already but didn't port the changes back.

**Comment by mwang1026** [comment]
Moving to P-1 because might be small change. If not feel free to ignore.
