### ISSUE TITLE
Update version toggle

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8640]
Figma link: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2087%3A12650

**Comment by lnhsingh** [comment]
@luciaaaaaaa can you add the Figma link? Thanks!

**Comment by anagio** [comment]
@lnhsingh the version switched from vlads branch is on the way to preview I merged locally fixed conflicts and sent it to our dev branch
