### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8641]
Figma link: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2232%3A10579

**Comment by lnhsingh** [comment]
@luciaaaaaaa can you add the Figma link? Thanks!

**Comment by luciaaaaaaa** [comment]
Hi -- I think we might want to update this to match the overall marketing site.
