### ISSUE TITLE
Edit Docker command on Low Latency Reads and Writes in a Multi-Region Cluster Doc

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8647]
Re: [Low Latency Reads and Writes in a Multi-Region Cluster](https://cockroachlabs.com/docs//v20.1/demo-low-latency-multi-region-deployment.html)

## Issue Description

the following command is incorrect

```bash
sudo docker run -it --rm cockroachdb/movr:19.09.2 --app-name "movr-load" --url "postgres://root@<address of HAProxy in US East>:26257/movr?sslmode=disable" load --num-users 100 --num-rides 100 --num-vehicles 10 --city-pair us_east:"new york" --city-pair central:chicago --city-pair us_west:seattle
```
it fails with unrecognized argument error

## Suggested Resolution 

change to 

```bash
sudo docker run --rm cockroachdb/movr:19.09.2 --app-name "movr-load" --url "postgres://root@10.142.0.38:26257/movr?sslmode=disable" load --num-users 100 --num-rides 100 --num-vehicles 10 --city "new york" --city "chicago" --city "seattle"
```

**Comment by lnhsingh** [comment]
@taroface I think this is relevant to deploy ops, but feel free to reroute if you think otherwise.

**Comment by mokaixu** [comment]
Will `<address of HAProxy in US East>` now be hardcoded as 
`root@10.142.0.38:26257`?

**Comment by taroface** [comment]
@mokaixu Thank you for taking this issue! I think you're right that `--city-pair` is what needs to be updated and not `<address of HAProxy in US East>`.

**Comment by mokaixu** [comment]
@taroface Cools! Changed as per your comments :)

**Comment by taroface** [comment]
@dbist Can you clarify which version you used to run the revised command?

**Comment by dbist** [comment]
must've been 20.1 at the minimum, this was back in October, my memory fails me.
