### ISSUE TITLE
Update 20.1 release notes and upgrade doc re: bumping default range size on existing clusters

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8658]
Our [20.1 beta.2 release notes](https://www.cockroachlabs.com/docs/releases/v20.1.0-beta.2.html#general-changes) mention that we bumped the default range size to 512 MB.

Some users were under the impression that the large range size would come automatically with the upgrade to 20.1. 

However, this is only true for newly created 20.1+ clusters.

We should make explicitly clear the conditions/actions required to use the larger range sizes.

Estimated scope of work:

- Update the 20.1 beta.2 release notes (linked above) to mention the steps required to enable larger default range sizes

- Update the [Upgrade to v20.1 doc](https://www.cockroachlabs.com/docs/v20.1/upgrade-cockroach-version.html) to mention that this step is required if you want to take advantage of the new larger default range size.

**Comment by mwang1026** [comment]
mmmm we should either close this or do it :)

**Comment by rmloveland** [comment]
at this point 2 releases later, since nobody has been shouting I will close :-)
