### ISSUE TITLE
release-20.2: ui: show tables from user defined schemas in web ui

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8692]
PR: https://github.com/cockroachdb/cockroach/pull/54901

From release notes:
> The [Admin UI's Databases page](../v20.2/admin-ui-databases-page.html) now includes tables that live within user-defined schemas. [#54901][#54901] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as this doesn't need docs.
