### ISSUE TITLE
update nav & footer: add Developers, Resources (resources.cockroachlabs.com)

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#8712]
Hi team! (cc @jseldess )
A few minor updates to the header nav and footer: 

**Header Nav:** 
Learn
>> Docs
>> University
>> Developers (https://www.cockroachlabs.com/developers/) [this is new]

Resources (https://resources.cockroachlabs.com) [this is new]
>> Guides (https://resources.cockroachlabs.com/guides) [this is new]
>> Webinars (https://www.cockroachlabs.com/community/tech-talks/)
>> Videos (https://resources.cockroachlabs.com/videos) [this is new]
>> Partners
>> Forum

**Footer:** 
Learn
>> Docs
>> University
>> Developers (https://www.cockroachlabs.com/developers/) [this is new]

Resources
>> Guides (https://resources.cockroachlabs.com/guides) [this is new]
>> Webinars (https://www.cockroachlabs.com/community/tech-talks/)
>> Videos (https://resources.cockroachlabs.com/videos) [this is new]
>> Partners
>> Architecture Overview
>> FAQ
>> Security

**Comment by lucky-c** [comment]
Hello, may I work on this?

**Comment by yingzhuchin** [comment]
@jess-edwards, @lnhsingh, I think the Header Nav has to be worked on by Marketing. I can work on the Footer.

**Comment by yingzhuchin** [comment]
@jess-edwards, we currently do not have "Partners" listed on the Footer. Would you like that to be added? If so, could you provide the link please? Thanks!

**Comment by yingzhuchin** [comment]
> @jess-edwards, @lnhsingh, changes to the Header Nav need to be made from the Marketing repo. I can work on the Footer.

Sorry, this is my bad. It's actually in the docs repo after all.
