### ISSUE TITLE
Error pulling Docker v20.1.8 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#8730]
Re: [What's New in v20.1.8](https://cockroachlabs.com/docs//releases/v20.1.8.html)

## Issue Description

```
% docker pull cockroachdb/cockroach-stable:v20.1.8
Error response from daemon: pull access denied for cockroachdb/cockroach-stable, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by jseldess** [comment]
We need to remove `cockroachdb/cockroach-stable` from the docs. That doesn't work. We have `cockroachdb/cockroach:<version>` for stable versions and `cockroachdb/cockroach-unstable:<version>` for alphas/betas/rcs.
