### ISSUE TITLE
Split ALTER TABLE into subcommands

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/docs#874]
This may just be me being dumb, but this is a small issue I ran into today.

I wanted to look at the docs for renaming a column. Knowing that `RENAME COLUMN` is part of an `ALTER TABLE` statement, I first went to the `ALTER TABLE` docs and struggled to find a way to get to what I wanted, since there was no reference to `RENAME COLUMN` on the page at all. I instead had to find the separate page for it in the list on the left navigation bar.

There were two things could have improved my experience:

1. A reference from the `ALTER TABLE` page to the `RENAME COLUMN` page
2. Consistency around what's included in the `ALTER TABLE` syntax diagram. If I didn't know better and had just looked at that page, I might conclude that cockroach doesn't support renaming columns, because other `ALTER TABLE` subcommands such as `ADD/ALTER/DROP COLUMN` are all included there.

**Comment by sploiselle** [comment]
Thanks, @a-robinson! This is an item on my backlog that I didn't have an explicit issue for. Will definitely be taking care of this as soon as I start tackling SQL statements again.
