### ISSUE TITLE
Create YAML tag that always points to "latest testing release"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8744]
Richard Loveland (rmloveland) commented:

It would be nice when getting early pre-release docs out to be able to reference the latest testing release automagically from YAML, similar to how we apparently do it for the [Install CockroachDB](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-mac.html) page, where we use 

```
{{page.release_info.version}}
```

For example, I'd like to be able to type something like the following and have it refer to our latest alpha/beta/RC.

```
docker pull {{page.release_info.testing_version}}
```

I can probably try to figure out how to do this (?), but wanted to capture in an issue since I'm stuck working on something else right now.

Jira Issue: DOC-809

**Comment by jseldess** [comment]
@rmloveland, I'm not clear on what you're trying to accomplish. Can you say more or give a specific example?

**Comment by rmloveland** [comment]
Sure!  Let's say you are working on something like multi-region or spatial and you publish some early docs.  It would be great to be able to avoid hardcoding a specific release such as `docker pull cockroach:unstable-v21.1.apha-1` or whatever because once it's hardcoded in the docs it has to be updated several times in the run-up to the release.

It's not a major issue but more of a minor pain point if you are trying to get users of a specific subset of features to always install "the latest testing release" to see how it is progressing

maybe another way of saying it: having it would be nice if it meant we could more easily experiment with encouraging users to install testing releases if they want to try out a feature.  right now one is slightly disincentivized because publishing a hardcoded version creates a little maintenance/upkeep burden
