### ISSUE TITLE
incorrect docs for database and table renames in versions <=20.1

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/docs#8760]
See https://github.com/cockroachdb/docs/pull/8715#pullrequestreview-517288403 for context.

The descriptions of table and database renames added in https://github.com/cockroachdb/docs/pull/4442 are incorrect:

https://www.cockroachlabs.com/docs/v20.1/rename-table.html#table-renaming-considerations
https://www.cockroachlabs.com/docs/v20.1/rename-database#database-renaming-considerations

We should remove the warning on the tables page, since it doesn't actually apply. (I think we could add a note that renaming tables is an online schema change, along with a link to that page: https://www.cockroachlabs.com/docs/v20.1/online-schema-changes.html).

For the database page we should say something like

> If an `ALTER DATABASE ... RENAME` statement is issued on one gateway node and a successful result is returned, it may still be possible to observe the old database names in transactions on other gateway nodes for a short amount of time afterward. This issue is specific to databases, which have their metadata stored in an incoherent cache, unlike tables. This limitation is lifted in v20.2.

I think avoiding the word "transactional" may be best here.

**Comment by ericharmeling** [comment]
@lucy-zhang Thank you for opening this!

> We should remove the warning on the tables page, since it doesn't actually apply.

Should we just remove the note, or scrap the note and the entire "Table renaming considerations" section (https://www.cockroachlabs.com/docs/v20.1/rename-table.html#table-renaming-considerations) and just point to online schema changes docs (https://www.cockroachlabs.com/docs/v20.1/online-schema-changes.html)?

**Comment by lucy-zhang** [comment]
I think we should remove the "Table renaming considerations" section and just link to the online schema changes docs. The limitations for renaming/dropping tables and databases are basically covered by that page.
