### ISSUE TITLE
CC FAQ: Add note on type of access SREs have to clusters

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8772]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//cockroachcloud/frequently-asked-questions.html)

## Issue Description

add a note on the type of access SREs have to the clients's clusters

## Suggested Resolution 

SREs operate under NDA, they have direct access to the clusters and this is not much different than any cloud service provider.

**Comment by lnhsingh** [comment]
@kannanlakshmi - I'm not sure what to put for this one, can you help? I assume "who has access to my cluster data?" is answered in our terms of service - can we link to our terms of service? Also, is it correct to assume that SREs (and whoever else has access to data) would never access customer data without customer consent?

**Comment by kannanlakshmi** [comment]
I am currently reviewing a fully updated T&C, give me another day to respond to this part. 

Re: `Also, is it correct to assume that SREs (and whoever else has access to data) would never access customer data without customer consent?` We dont get customer consent every time we do this but again its part of the T&C.

**Comment by dbist** [comment]
your earlier comment was deleted but to respond to that, this question has come up at least three times across various fintech and healthcare prospects. I think it makes sense to have some info highlighted in the FAQ and more detailed response left for contract or T&C.

**Comment by lnhsingh** [comment]
Closing in favor of CC-3684
