### ISSUE TITLE
CC FAQ: Clarify observability options in CC

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8773]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//cockroachcloud/frequently-asked-questions.html)

## Issue Description

clarify observability options in CC. We do not expose endpoints today.

## Suggested Resolution 

Provide clarity on the roadmap

**Comment by lnhsingh** [comment]
@thtruo - I know we don't support Prometheus endpoints in CC today-- do we need to talk about other endpoints?

**Comment by lnhsingh** [comment]
@thtruo - bump - do you think we need to add docs on this? We don't normally cover clarity on the roadmap in our docs (since we don't want to be held to timelines, etc. if we change our minds)

**Comment by thtruo** [comment]
@lnhsingh I see, that's good to know about not mixing in roadmap commitments into docs. For the most part, endpoints that are accessible for self-hosted clusters (that can be found in DB Console's [advanced debug page](https://www.cockroachlabs.com/docs/stable/ui-debug-pages.html)) are generally not exposed to Cloud clusters. Or more accurately, they're not 100% supported for Cloud clusters.

**Comment by lnhsingh** [comment]
Ok, thanks for the info, Tommy! I think I will close this issue for now. We can revisit if we get more feedback on any confusion.
