### ISSUE TITLE
Clarify that hash-sharded indexes are an implementation of hash partitioning, not hash indexing

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#8774]
Eric Harmeling (ericharmeling) commented:

@ajwerner 
@a-entin 
@awoods187 

Hash-sharded indexes are an implementation of hash partitioning, not hash indexing. This isn't exactly clear in the docs (https://www.cockroachlabs.com/docs/stable/indexes.html#hash-sharded-indexes and https://www.cockroachlabs.com/docs/stable/create-index#parameters). We should clarify that "`BUCKET_COUNT`" in the `USING HASH WITH BUCKET_COUNT` clause impacts the distribution of the index across cluster nodes, not a hash table implementation on individual nodes.

Jira Issue: DOC-811

**Comment by a-entin** [comment]
Alternatively we may consider using a different keyword or adding an extra keyword for the implicit clarity of the SQL syntax we use. Surely there is user impact on syntax change, yet the feature is still experimental so there may still be an opportunity for syntax change before the feature is mainstream

**Comment by ajwerner** [comment]
@mari-crl should this have been closed?
