### ISSUE TITLE
cloud storage url: Clarify how to use cloudstorage.gs.default.key

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/docs#8791]
John Sheaffer (sheaffej) commented:

For customers in GCP or GKE, the natural storage for backups is Google cloud storage `gs://`.

It's not obvious in the CockroachDB docs about backup how to configure the cluster and the Google project so the database can write to Google storage. There is a footnote, but:
1) It's a footnote, and therefore easy to miss
2) It's a little difficult to follow. Could use a simple example.

Few suggestions:
a) Right in the section showing the URL examples: https://www.cockroachlabs.com/docs/v20.1/backup.html#backup-file-urls put a more obvious link such as "Configuring Google Storage authentication" which sends the reader to the footnote or paragraph
b) I the Cluster Settings page, provide an example. Currently there is no example of what the contents of the `cloudstorage.gs.default.key` should look like.  https://www.cockroachlabs.com/docs/v20.1/cluster-settings.html#settings

Example:
```
-- Set the setting to the contents of the json key created in the Google Cloud console for the service account
SET CLUSTER SETTING cloudstorage.gs.default.key='{
  "type": "service_account",
  "project_id": "my-google-project", 
  "private_key_id": "11111111111111111111111111111",
  "private_key": "-----BEGIN PRIVATE KEY----- XXXXX -----END PRIVATE KEY-----\n",
  "client_email": "xxxx@my-google-project.iam.gserviceaccount.com", 
  "client_id": "bigint", 
  "auth_uri": "https://accounts.google.com/o/oauth2/auth", 
  "token_uri": "https://oauth2.googleapis.com/token", 
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", 
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service_account%40your-peojct.iam.gserviceaccount.com"
}';
```

**Comment by sheaffej** [comment]
Also see internal Slack thread:
https://cockroachlabs.slack.com/archives/CC5CX8EKE/p1604018439327100

**Comment by jseldess** [comment]
cc @lnhsingh and @mwang1026.
