### ISSUE TITLE
OpenSSL/custom CA cert pages are not in TOC

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8800]
The following pages are not in the TOC for the website:

- https://www.cockroachlabs.com/docs/v20.1/create-security-certificates-openssl

- https://www.cockroachlabs.com/docs/v20.1/create-security-certificates-custom-ca

- https://www.cockroachlabs.com/docs/v20.2/create-security-certificates-custom-ca.html

- https://www.cockroachlabs.com/docs/v20.2/create-security-certificates-openssl

(Meta: we should consider whether things like this should fail the build.)

**Comment by Amruta-Ranade** [comment]
This is by design. They are toggle-pages for the `cockroach cert` (https://www.cockroachlabs.com/docs/v20.2/cockroach-cert) page. IIUC, toggle pages don't show up in the TOC.

**Comment by lnhsingh** [comment]
Seems like this can be closed. Please feel free to reopen if you think there needs to be work done here.
