### ISSUE TITLE
Deploying CockroachDB on IBM Cloud Kubernetes

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#8821]
Provide a tutorial for deploying CRDB on [IBM Cloud Kubernetes](https://www.ibm.com/cloud/container-service/) (single-region). We have an external contribution (TBC) drafted on this topic.

**Comment by haephrati** [comment]
Here it is:


https://www.dropbox.com/s/jeubv3qgtte8f7s/Deploy%20CockroachDB%20on%20IBM%20Cloud%20Kubernetes%20SingleNode%20Insecure.docx?dl=0


https://www.dropbox.com/s/7yd514lrhfokboe/Deploy%20CockroachDB%20on%20IBM%20Cloud%20Kubernetes%20MultiNode%20Secure.docx?dl=0

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/8761.
