### ISSUE TITLE
sql: specify ogr2ogr minimum version

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#8822]
Add the minimum ogr2ogr version needed when using 20.2.0. In 20.2.1, this limitation will be lifted. 

cc @rmloveland this is needed for the nov. 13th deadline
cc @keith-mcclellan 

related to https://github.com/cockroachdb/cockroach/pull/55921/files

**Comment by rmloveland** [comment]
What is the minimum version? @otan do you know?

**Comment by otan** [comment]
3.1.0

**Comment by rmloveland** [comment]
Fixed in #8892
