### ISSUE TITLE
CC FAQ: Add How to access your cluster

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8830]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//cockroachcloud/frequently-asked-questions.html)

## Issue Description

It is unclear the type of access end-users have to their environments.

## Suggested Resolution 

document that end-users do not have shell (ssh) access to their clusters, only `cockroach sql` CLI.

**Comment by lnhsingh** [comment]
@thtruo - I know we don't support Prometheus endpoints in CC today-- do we need to talk about other endpoints?

**Comment by lnhsingh** [comment]
@kannanlakshmi - If I understand correctly, most managed services do not offer SSH access to their VMs, and most users probably won't expect this. Do you think we need to add an FAQ on this?

**Comment by kannanlakshmi** [comment]
I am okay not including this, @dbist do you think this is necessary? I am curious if this was a one off or if you've encountered this question many times.

**Comment by lnhsingh** [comment]
Going to close this for now.
