### ISSUE TITLE
logo / branding updates

### ISSUE THREAD

**Issue by jess-edwards** [cockroachdb/docs#8843]
I know you've got a major Docs update that is eminent. Would it be possible to sneak a placeholder update in before your major change goes live? 

Favicon: ![CockroachLabs_Shorthand-Logo_Color-80px](https://user-images.githubusercontent.com/6042450/98398951-979dc280-2016-11eb-9ffe-bc8612b6db69.png)
Logo: ![CockroachLabs_Full-Logo-Horizontal_Full-Color-Light-BG](https://user-images.githubusercontent.com/6042450/98399121-d2075f80-2016-11eb-9e3d-d9a12e89f8c5.png)

If you need other logos, let me know. 

cc @lnhsingh

**Comment by lnhsingh** [comment]
@anagio can these updates be included in your current nav fix?
