### ISSUE TITLE
Create Your CockroachCloud Cluster Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8845]
Re: [Create Your CockroachCloud Cluster](https://cockroachlabs.com/docs//cockroachcloud/create-your-cluster.html)

## Issue Description

sizing example could use an estimate on the index strategy as well as online schema changes

## Suggested Resolution 

when users report large numbers of indexes, it throws the sizing calculation off and we need a better example in that case. For schema changes, when new version of a large table is created, we need to account for the double of the amount of space needed to perform an online schema change.

**Comment by dbist** [comment]
cc: @jseldess

**Comment by jseldess** [comment]
@kannanlakshmi, @Amruta-Ranade, can you take a look at this in your next grooming/prioritization?

**Comment by lnhsingh** [comment]
Closing - as this is no longer relevant (sqlalchemy steps are no longer included on this doc)

**Comment by lnhsingh** [comment]
Closing in favor of CC-3704
