### ISSUE TITLE
Update show databases documentation to state users need select privileges

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/docs#8852]
The documentation for show databases states currently that no privileges are required 
https://www.cockroachlabs.com/docs/stable/show-databases.html#required-privileges

However this is wrong, for a user to be able list the database with this command they must have been granted select privilege on the database

pl_test@localhost:26257/defaultdb> show databases;
  database_name
-----------------
(0 rows)

root@localhost:26257/defaultdb> grant select on database movr to pl_test;
GRANT

Time: 22.287154ms

pl_test@localhost:26257/defaultdb> show databases;
  database_name
-----------------
  movr
(1 row)

Thanks
Paul

**Comment by jseldess** [comment]
Passing to @ericharmeling for further grooming.

**Comment by thtruo** [comment]
I'll pick this up for fixit

**Comment by ericharmeling** [comment]
This was fixed by https://github.com/cockroachdb/docs/pull/9197.
