### ISSUE TITLE
Figure out a nice way to hide complexity of spatial install steps

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8861]
... such that users who are not interested in spatial features don't have to look at the rather complicated series of manual install steps.

Some good suggestions from @ericharmeling:

- Add a different button
- Add another level 2 header for a "spatial" download workflow, and folding the optional spatial steps under that

**Comment by jseldess** [comment]
I think we need to look at all of the other install methods as well and make sure we're not missing anything. It came up today that we don't know if this works with homebrew. I'm also curious about build from source.

**Comment by rmloveland** [comment]
Closing since this got solved at the time of the 20.2 release - at least it seems like a non-issue at this point
