### ISSUE TITLE
Document intention to deprecate cross-database referencing

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#8874]
We need to call out the intention to deprecate cross-database referencing in 21.2 (see https://github.com/cockroachdb/cockroach/issues/55791). 

As a first step towards deprecation, 20.2 introduces gating via the following cluster settings that disallow cross-database referencing for foreign keys, views, and sequences (all are `false` by default): 

- `sql.cross_db_fks.enabled`
- `sql.cross_db_sequence_owners.enabled`
- `sql.cross_db_views.enabled`

I can add an additional bullet here in the docs so users know that the deprecation is coming:

- https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations

We should also call out the gating and deprecation intention to users who are upgrading from 20.1:

- https://www.cockroachlabs.com/docs/v20.2/upgrade-cockroach-version#features-that-require-upgrade-finalization

FYI
@vy-ton @ajwerner @lucy-zhang

**Comment by vy-ton** [comment]
We should also document the alternatives/migration steps that a user can take.
