### ISSUE TITLE
Orchestrate CockroachDB in a Single Kubernetes Cluster - prometheus issue

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8888]
Re: [Orchestrate CockroachDB in a Single Kubernetes Cluster](https://cockroachlabs.com/docs//v20.2/orchestrate-cockroachdb-with-kubernetes.html)

## Issue Description
this step `kubectl port-forward prometheus-cockroachdb-0 9090` is not working as there's no resource with that name available

## Suggested Resolution 
is there a step missing?

**Comment by jhatcher9999** [comment]
this section: https://www.cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes#configure-prometheus

**Comment by keith-mcclellan** [comment]
I dont think that the prometheus endpoint is currently being exposed by the operator. There probably needs to be an enhancement request made to the operator

**Comment by taroface** [comment]
I think this PR I opened on our `prometheus.yaml` might be the needed fix? https://github.com/cockroachdb/cockroach/pull/56025

With the `serviceAccountName` field is commented out, I'm able to apply the manifest and run the `port-forward` command.

**Comment by taroface** [comment]
@keith-mcclellan Do you think the above is a relevant fix?
