### ISSUE TITLE
Orchestrate CockroachDB in a Single Kubernetes Cluster - missing cockroachdb-client-secure pod

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8889]
Re: [Orchestrate CockroachDB in a Single Kubernetes Cluster](https://cockroachlabs.com/docs//v20.2/orchestrate-cockroachdb-with-kubernetes.html)

## Issue Description

there is no `cockroachb-client-secure` pod in this tutorial, the following command does not work `kubectl exec -it cockroachdb-client-secure -- ./cockroach node decommission 4  --certs-dir=/cockroach-certs --host=cockroachdb-public`

## Suggested Resolution 

the proper command in lieu of having a client-secure pod `kubectl exec -it cockroachdb-2 \
-- ./cockroach sql \
--certs-dir cockroach-certs` similar to the original command for opening SQL shell.

**Comment by keith-mcclellan** [comment]
I would prefer we enhance the operator to launch a client container (or have the operator container act as the client container ) as telling people to exec into one of the DB containers is very dangerous.

**Comment by taroface** [comment]
@keith-mcclellan I originally had the instructions using a client container, but was advised to remove them. Do you think the `client-secure.yaml` [here](https://github.com/cockroachdb/cockroach-operator/pull/142/commits/2c01ae5e234f8a080699fac6f01f0e2008f28a74) would suffice until the Operator can launch/act as the client container?

**Comment by taroface** [comment]
cc @johnrk - can you help us determine the right guidance here?

**Comment by taroface** [comment]
To follow up, I need verification on the correct YAML for the secure client pod on GKE. Here is one I created previously: https://github.com/cockroachdb/cockroach-operator/blob/af5f13c90b3c8b58a6452d149be9c7f2cec7fe16/manifests/client-secure-byoc.yaml

Will this still work or should any parameters be changed?
