### ISSUE TITLE
Document intention to deprecate interleaved tables

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#8891]
After https://github.com/cockroachdb/cockroach/issues/56579 closes, we should add interleaved tables as a deprecation

**Comment by vy-ton** [comment]
cockroachdb/cockroach#56579  has closed, we should coordinate with @lucy-zhang and @ajwerner on the recommended steps to de-interleave a table.

**Comment by ericharmeling** [comment]
@lucy-zhang @ajwerner 

Do y'all have any guidance for "de-interleaving", or should we just leave this as a notice and a recommendation to not interleave newly-created tables?

**Comment by lucy-zhang** [comment]
I believe all that needs to be done to de-interleave a table is to issue an `ALTER PRIMARY KEY` statement on the table with the same preexisting list of primary key columns, without `INTERLEAVE IN PARENT`. This only works on interleaved children that are not interleaved parents themselves (i.e., they are leaf nodes in the interleave hierarchy), so users will have to start from the bottom of the hierarchy and go up.

We could conceivably have a tool that displays the trees of interleaved tables or generates the `ALTER PRIMARY KEY` SQL statements for users somehow. I'm not sure if this is worth it. Maybe it's better for users to have to explicitly specify what they want in writing their own `ALTER PRIMARY KEY` statement.

**Comment by lucy-zhang** [comment]
We also have to get rid of interleaved secondary indexes. We don't have a way of rewriting those in an automated way. Users will just have to create new non-interleaved indexes and drop the old ones.

**Comment by vy-ton** [comment]
> to issue an `ALTER PRIMARY KEY` statement on the table with the same preexisting list of primary key columns, without `INTERLEAVE IN PARENT`

@lucy-zhang Does this mean that child tables keep the interleave prefix as part of their primary key?

**Comment by lucy-zhang** [comment]
> Does this mean that child tables keep the interleave prefix as part of their primary key?

Yes, if they want to keep their existing schema and not have to make changes to their queries. But, of course, they can also use `ALTER PRIMARY KEY` to change the primary key to whatever they want.
