### ISSUE TITLE
Add docs on impacts of and mitigations for disk stalls

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8901]
We currently mention the phrase "disk stall" in one place, on our [Cluster Troubleshooting](https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html) page, where we note that it is one of the things that will cause node liveness issues.  Based on a quick search we do not seem to mention the term `fsync` at all except in some obscure no-longer-visible-in-20.2+ cluster settings.

However, we should probably add more information about this area, including but not limited to:

- What is a disk stall?
- Why does it happen?
- What can you do about it, if anything?

At a high level it seems like a thing that is more likely to happen if you are underprovisioned on IOPS, but there are apparently other reasons, including hardware failures and possible SELinux interactions, that we should also write up.

**Comment by mwang1026** [comment]
As a part of 21.2 Storage is working on some OOD type stuff. Maybe we create an "epic" around "disk issues and how to handle them?"
