### ISSUE TITLE
Add naming conventions to FAQs

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8902]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//cockroachcloud/frequently-asked-questions.html)

## Issue Description

cluster names must be in lower case letters

## Suggested Resolution 

add a note that cluster naming convention requires lower case names and 6-20 chars long, accepting dashes

**Comment by lnhsingh** [comment]
@ericharmeling I think this is relevant to SQL but feel free to re-route if you think otherwise
