### ISSUE TITLE
Edit Show a specific user or role's grants example on SHOW GRANTS

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/docs#8903]
Re: [SHOW GRANTS](https://cockroachlabs.com/docs//v20.2/show-grants.html)

## Issue Description

`SHOW GRANTS FOR USER max;` looks invalid.

## Suggested Resolution 

correct syntax is 

`SHOW GRANTS FOR max;`

## Example
```
root@:26257/defaultdb> SHOW GRANTS for user test_user;
invalid syntax: statement ignored: at or near "user": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SHOW GRANTS for user test_user
                ^
HINT: try \h SHOW GRANTS
root@:26257/defaultdb> SHOW GRANTS for test_user;
  database_name | schema_name | relation_name | grantee | privilege_type
----------------+-------------+---------------+---------+-----------------
(0 rows)

Time: 26ms total (execution 26ms / network 0ms)
```

**Comment by lnhsingh** [comment]
@ericharmeling assigning to you, even though this kind of falls between Security/SQL

**Comment by ericharmeling** [comment]
Thanks for filing this, @fabiog1901!

Fixed by https://github.com/cockroachdb/docs/pull/9023.
