### ISSUE TITLE
Build a Java App with CockroachDB and JDBC Doc Update

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8946]
Artem Ervits (dbist) commented:

Re: [Build a Java App with CockroachDB and JDBC](https://cockroachlabs.com/docs//v20.2/build-a-java-app-with-cockroachdb.html)

## Issue Description

in secure mode, instead of `sslRootCert` being `ca.crt`, we suggest to use `client.root.crt`. 

## Suggested Resolution 
fix with `ds.setSslRootCert("certs/ca.crt");`

Jira Issue: DOC-828

**Comment by jseldess** [comment]
@ianjevans, you've been working on these docs, so assigning to you.

**Comment by ianjevans** [comment]
We just modified the example to remove the certificate login for the time being. It now matches the other `hello-world` examples that use password authentication. We will, however, add certificate authentication back at some point, so leaving this open.
