### ISSUE TITLE
Build a Java App with CockroachDB and JDBC Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#8954]
Re: [Build a Java App with CockroachDB and JDBC](https://cockroachlabs.com/docs//v20.2/build-a-java-app-with-cockroachdb.html)

## Issue Description

we are using `int` data type to represent monetary data type here where in our docs, we suggest to use [`decimal`](https://www.cockroachlabs.com/docs/v20.2/decimal.html) and the associated `BigDecimal` Java data type to represent money.

## Suggested Resolution 

convert this application to use `decimal` data type instead of `int` for handling monetary data types, similar to [this](https://www.cockroachlabs.com/docs/v20.2/build-a-spring-app-with-cockroachdb-jpa) example.

**Comment by jseldess** [comment]
@ianjevans, you've been working on these docs, so assigning to you.
