### ISSUE TITLE
Document that we do not support schema'd type names with typmods

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#8955]
As noted by @otan in cockroachdb/cockroach#56492:

> We currently do not support schema'd type names with typmods, e.g. public.geometry(linestring, 4326) in CREATE TABLE t(g public.geometry(linestring, 4326)). Users seeing this in v20.2 from IMPORT PGDUMP must remove the public. to get this to work (i.e. use geometry(linestring,4326) instead). Note public.geometry works today.

> This is because complex_type_name does not take any optional attrs.

We should document the above limitation, and the workaround mentioned.

Not clear whether this only affects users of spatial features, or is just more likely to affect them due to the output of various spatial file tools (?).  TBD.

**Comment by otan** [comment]
it's because pg_dumps will output the public schema in this way for geometry/geography types.
