### ISSUE TITLE
Style/rebrand Katacoda CTAs and scenarios

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8956]
We currently have 3 in-browser interactive tutorials in our docs, available from these pages:

- https://www.cockroachlabs.com/docs/v20.2/learn-cockroachdb-sql
- https://www.cockroachlabs.com/docs/v20.2/demo-json-support.html
- https://www.cockroachlabs.com/docs/v20.2/build-a-python-app-with-cockroachdb.html

We need to update the style of the CTAs as well as the embedded scenarios themselves. For the latter, we may not have all the control we'd like, but I can try to help figure that out. 

Figma reference: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=3279%3A535

**Comment by lnhsingh** [comment]
CTAs have been updated. Styles within the scenarios still need to be updated, but closing this issue in favor of #9379
