### ISSUE TITLE
produce a single-file document for offline use

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#896]
Found requested on gitter:
```
(10:21) < baskara8> [edit] @irfansharif  actually i have run step by step, btw cockroach lab have a offline document?
(10:38) < knz> @baskara8: not yet, but thanks for asking 
```

Markdown is not ideal as starting point for creating a PDF, but I'm sure we can bake something.

**Comment by knz** [comment]
Perhaps producing an ebook could do the trick though

**Comment by dt** [comment]
In the mean time, fwiwiw, we can point to https://github.com/cockroachdb/docs/archive/gh-pages.zip

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/1484.
