### ISSUE TITLE
troubleshooting: detecting txn contention

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#8961]
Finalize guidance: https://cockroachlabs.atlassian.net/wiki/spaces/TS/pages/1080820085/Detect+transaction+contention+in+a+statement+trace

Relates to https://github.com/cockroachlabs/support/issues/666

**Comment by taroface** [comment]
Hi @jordanlewis, see linked guidance above. I shared the page with Andrei and Andrew, who were both participating in the relevant Slack thread (linked in the wiki).

Going forward my plan is to create a docs ticket for each Support issue tagged as a Troubleshooting topic, and to add this ticket to the Troubleshooting Docs project I've created. Let me know if that sounds OK to you.

**Comment by jordanlewis** [comment]
Thanks, @taroface! This process sounds good to me. The doc looks good to me too.

But, I think we should get a review from @tim-o. Tim, how does the doc look to you? is this going to be a helpful format for your team?

**Comment by taroface** [comment]
This article has been reviewed by TSE and ENG.

**Comment by taroface** [comment]
Reopening as @andreimatei noted that we should cover latching.

Relevant: https://github.com/cockroachlabs/support/issues/710#issuecomment-737607669

**Comment by taroface** [comment]
Closing as this has been addressed in the internal doc!
