### ISSUE TITLE
Refactor Storage for Bulk Operations Docs

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8962]
Currently, the flow from [Take Full and Incremental Backups](https://www.cockroachlabs.com/docs/v20.2/take-full-and-incremental-backups#full-backups) to backup location docs (i.e., cloud storage, nodelocal, userfile) isn't intuitive.

General updates needed:

- Link Take Full and Incremental Backups to available backup location docs
- Maybe refactor the Full Backups section to include an example for each storage type
- Break nodelocal out into own doc
- Expand Cloud Storage doc so each cloud has its own section (with more examples, etc.)
- Include updates for IMPORT, EXPORT 

[Related feedback](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1605660153488800)

Related to:
- https://github.com/cockroachdb/docs/issues/8019
- https://github.com/cockroachdb/docs/issues/4228
- https://github.com/cockroachdb/docs/issues/7398
- https://github.com/cockroachdb/docs/issues/7696
- https://github.com/cockroachdb/docs/issues/8239

**Comment by kathancox** [comment]
Closing this issue in favor of #10544. Feel free to reopen if needed!
