### ISSUE TITLE
Document maximal possible value for `ttlseconds`

### ISSUE THREAD

**Issue by asd-and-Rizzo** [cockroachdb/docs#898]
`ttlseconds` from [configuration](https://www.cockroachlabs.com/docs/configure-replication-zones.html#replicaton-zone-format) does not specify suggestion for maximal possible value. Searching source code or docs for `ttlseconds` does not reveal any limitation. May be some recommendation like for smallest value `It is not recommended to set this below 600 (10 minutes).`.

I want to have `ttlseconds` to be month or even several months for some specific tables as part of audit or billing.

**Comment by jseldess** [comment]
@petermattis, @bdarnell, any insights here? Do we have recommended lower/upper limits for `ttlseconds`? 

Is `ttlseconds` the right feature for holding onto specific tables for auditing or billing, or would `dump` or another feature be more suitable?

**Comment by petermattis** [comment]
I'm not aware of any upper limit recommendation for `ttlseconds`. The one downside to a larger `ttlseconds` setting is that the old values will slow down reads if you are frequently overwriting or deleting rows. Using `ttlseconds` for auditing or billing sounds reasonable at a high-level, but I'd need to hear more details to be able to say whether it makes sense for @asd-and-Rizzo.

The lower limit recommendation still seems reasonable.

**Comment by jseldess** [comment]
From @bdarnell, in a thread on Gitter:

> You can use the `ttlseconds` in the zone configuration to keep more versions of data. However, it is not advised to use this with rapidly-changing data - keeping too many historical versions can lead to memory spikes on the server because all versions of a row are currently kept together. As a rule of thumb you should avoid setting the `ttlseconds` field so high that all the changes to a row in that time period could add up to 64MB.

**Comment by asd-and-Rizzo** [comment]
Thanks, things are much clear now.

Let pretend I have table DOCUMENT. It has 2 rows. Row 1 and row 2. Let pretend I have updated row 1 with some data 5K times and row 2 only 10 times within day.  Will row 1 make selects from row 2 noticeably slower?

Anyway seems part of our use cases [are not supported](https://forum.cockroachlabs.com/t/accessing-rows-at-an-older-timestamp/389/2):

> There isn't an API for listing the older versions of a row.

I was thought about grabbing all changes of some table from time to time, remembering last timestamp and grab next changes later again. I do not have option to miss some updates. This is `audit`. We could put that data into `ElasticSearch` or to slower version of `cockroachdb` for analytics and reporting.

So will have (as on forum link)
> implementing that in the application layer

**Comment by bdarnell** [comment]
> Will row 1 make selects from row 2 noticeably slower?

Selects that identify a single row by primary key are generally unaffected by other rows. Queries that use secondary indexes or more complex filtering expressions could be slowed down by keeping more versions of other rows.

We'll keep the audit use case in mind. We don't have a way to list all the older versions of a row now, but it would be feasible to add in the future.
