### ISSUE TITLE
Kubernetes tutorial: Broken code block formatting

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8983]
See Step 4, substep 1: https://www.cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes#step-4-access-the-db-console

<img width="800" alt="Screen Shot 2020-11-21 at 7 24 45 AM" src="https://user-images.githubusercontent.com/15893490/99877229-a6fe3d80-2bca-11eb-88aa-525517364686.png">

**Comment by mokaixu** [comment]
<img width="1038" alt="Screen Shot 2020-12-15 at 4 04 04 PM" src="https://user-images.githubusercontent.com/19556673/102272822-5e971e80-3eef-11eb-915e-5afe0dee60ea.png">

Looks like a flakey bug? The shell formatting works on my end.

**Comment by taroface** [comment]
Closing, as this seems to be resolved on the site.
