### ISSUE TITLE
Docs need to clarify the difference between CCL paid and CCL free

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/docs#8990]
Currently, we have code that's licensed in 3 ways in cockroachdb:

1) BSL
2) CCL (free)
3) CCL (paid)

Now that CCL (free) is more than "just IMPORT" we need to document which features fall into the CCL (free) bucket and what that means for core users.  This came up on a customer call today for an OEM use case where they're concerned about being reliant on CCL free features (thinking we might chose to make them paid in the future).

Also we need to clarify if core users have the same rights to CCL (free) features as they do BSL features.

**Comment by keith-mcclellan** [comment]
Slack thread: https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1606163851093400

**Comment by mwang1026** [comment]
cc @jseldess not sure who'd own this? I think all the Free CCL features are in Bulk IO

**Comment by keith-mcclellan** [comment]
Some sort of a table would be helpful listing out the rights you have to BSL, CCL Free, and CCL paid source if you're a paying user or a core user as well

**Comment by jseldess** [comment]
We don't really have anyone to handle licensing holistically. @lnhsingh, do you think this could be a started project for our new Associate writer, with you doing some up-front planning and coaching? 

We probably need to step back and completely rethink the way we explain licensing. Right now, we have this [FAQ](https://www.cockroachlabs.com/docs/v20.2/licensing-faqs.html) and this page summarizing [enterprise features and how to get and set a license](https://www.cockroachlabs.com/docs/v20.2/enterprise-licensing.html). 

Related issue: https://github.com/cockroachdb/docs/issues/8943
