### ISSUE TITLE
cache size options

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#90]
Document the `cache-size` field at the store level.

**Comment by spencerkimball** [comment]
Let's leave out memtable-cache for now.

**Comment by jseldess** [comment]
@spencerkimball, you mean even if @BramGruneir adds it as a store-level field? I'm fine leaving it out of docs in that case, but should we also leave it out of the command line help?

**Comment by spencerkimball** [comment]
@BramGruneir let's hold off on adding `memtable-cache` as a store level field. I'm fine adding `cache-size` as one, but a knob for `memtable-cache` is not something we want to release into the wild now.

**Comment by BramGruneir** [comment]
Sure, can do.
@bdarnell was arguing for keeping it last night.

**Comment by petermattis** [comment]
The RocksDB cache can be shared amongst a number of RocksDB instances. I think sharing the cache would be better than sharding it.

**Comment by bdarnell** [comment]
I'm fine with leaving `memtable-budget` as a constant for now, and agree that sharing the rocksdb cache would be best as long as it can be arranged easily.
