### ISSUE TITLE
Typo on Frequently Asked Questions page

### ISSUE THREAD

**Issue by jmeehan7** [cockroachdb/docs#9004]
Re: [Frequently Asked Questions](https://cockroachlabs.com/docs//v20.2/frequently-asked-questions.html)

## Issue Description
Under the "Since CockroachDB is inspired by Spanner, does it require atomic clocks to synchronize time?" section, the second paragraph has a misspelling in the first sentence. 

![image](https://user-images.githubusercontent.com/75221288/100552023-6e0d3b00-3252-11eb-93fa-44cee18a31af.png)

## Suggested Resolution 
The first sentence should have "unsychronized" replaced with "unsynchronized" as the sentence is referring to clock synchronization.

**Comment by BethMyre** [comment]
PR submitted https://github.com/cockroachdb/docs/pull/9063
