### ISSUE TITLE
binary commands to distinguish between types of connections (sql conn, gRPC)

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#9007]
Matthew Vardi (mattcrdb) commented:

We've learned from a customer inquiry that our cockroach binary command documents don't specify what type of connection each command is using.

For example, `cockroach node ls` uses a SQL conn while `cockroach debug gossip-values` uses a gRPC connection.

This lead to unexpected results in the set up of certain environments where there are restrictions in place for the types of ports cockroach uses.

An example can be found here: https://github.com/cockroachlabs/support/issues/699

For this particular customer, the [cockroach node](https://www.cockroachlabs.com/docs/v20.2/cockroach-node.html) page is the most important. Followed by the [debug.zip](https://www.cockroachlabs.com/docs/v20.2/cockroach-debug-zip.html#general) and [cockroach quit](https://www.cockroachlabs.com/docs/v20.2/cockroach-quit.html)(the customer is aware of our plans for `cockroach quit` but is still using it for now.)

cc @knz who helped with the investigation and can provide further detail if required.
 

Jira Issue: DOC-836

**Comment by knz** [comment]
I agree we need to document this.

In v21.1 we are going to seriously reduce our usage of the RPC port directly, but it will not be entirely removed, so the need for documentation will exist.

Here is my understanding:

| Command | Port used |
|--|--|
| `node ls` | SQL |
| `node status` | SQL |
| `node decommission` | RPC |
| `node recommission` | RPC |
| `node drain` | RPC |
| `init` | RPC |
| `quit` (deprecated) | RPC |
| `nodelocal` | SQL |
| `userfile` | SQL |
| `gen haproxy` | RPC |
| other `gen` sub-commands | N/A (entirely local) |
| `workload` | SQL |
| `import` | SQL |
| `debug tsdump` | RPC |
| `debug doctor` | SQL |
| `debug gossip-values` | RPC |
| `debug zip` | RPC *and* SQL |

All other commands as of 20.2 are strictly local and do not connect to a server. 

New commands added after 20.2 may also use the network and this needs to be fished out from release notes or the individual PRs.

**Comment by knz** [comment]
This db issue is tracking this: https://github.com/cockroachdb/cockroach/issues/51454

**Comment by knz** [comment]
Yes
