### ISSUE TITLE
CC: document github auth option

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#9014]
We're adding Github Authentication so users can sign up with their existing GH account.

Epic [here](https://cockroachlabs.atlassian.net/browse/CC-2897)

**Comment by lnhsingh** [comment]
I don't think docs will be needed for this, as we just link users to the sign up / login pages and it's pretty self-explanatory. Going to close this issue for now but feel free to reopen if you think otherwise!

**Comment by lnhsingh** [comment]
Re-opening. Doing some investigation on if a page is worth adding for "Create a CC account", which would include the different ways to log in
