### ISSUE TITLE
CC: document what DB privileges a SQL user has

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#9017]
SQL users created in the console are always granted the same permission set on the DB, even if the user is a Developer in CC's permission structure. We should document this so that our users can easily determine if they want to edit those users' permissions afterwards or create them via SQL to limit access to their DBs/schemas.

See [Jira issue](https://cockroachlabs.atlassian.net/browse/CC-2855)

**Comment by lnhsingh** [comment]
Closing in favor of CC-3688
