### ISSUE TITLE
Document that you should never 'DROP system.users'

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#9019]
We recently had a user encounter an issue where they (apparently) did a

    DROP TABLE system.users

It's possible that they misread the [instructions on the `RESTORE` page](https://www.cockroachlabs.com/docs/v20.2/restore.html#restoring-users-from-system-users-backup), which have users doing some (IMO) kinda tricky stuff manually "in the vicinity of" the `system.users` table.

We have a number of options about what to do from docs (probably more, just some ideas):

- Update the instructions to remove the (strictly not 100% necessary) step that says to `DROP TABLE newdb.users`, which is easy to misread (IMO)

- Add a note that says something along the lines of "please do not ever `DROP system.users`, you will brick the cluster"

- Update other language on that page that says you "cannot" drop `system.users`, since you apparently actually can (and it's bad).

Or probably some combination of all of the above.

**Comment by rmloveland** [comment]
Lauren assigned to you since AFAICT you are the primary person making edits in this area.  There's an email about this which I can point you to via means other than here.

**Comment by rmloveland** [comment]
(See also: https://github.com/cockroachdb/cockroach/issues/57176)

**Comment by mwang1026** [comment]
It seems like that bug was fixed so user shouldn't be able to drop system tables

```
root@localhost:26257/defaultdb> drop table system.users;
ERROR: user root does not have DROP privilege on relation users
SQLSTATE: 42501
```

closing
