### ISSUE TITLE
sql: Document COPY statement

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/docs#9022]
CockroachDB has supported the COPY statement for the past few releases, but it is not documented.

Code changes:
https://github.com/cockroachdb/cockroach/pull/8756
https://github.com/cockroachdb/cockroach/pull/51890

Other docs issues:
https://github.com/cockroachdb/docs/issues/546
#3058 
https://github.com/cockroachdb/docs/issues/1676
https://github.com/cockroachdb/docs/issues/1831
https://github.com/cockroachdb/docs/issues/8156
https://github.com/cockroachdb/docs/issues/8155

**Comment by rafiss** [comment]
cc @ericharmeling

**Comment by ericharmeling** [comment]
@rafiss I'm a little confused here. https://github.com/cockroachdb/cockroach/issues/16392 suggests that we do not support `COPY FROM STDIN`, but the grammar allows the syntax: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/sql.y#L2859

**Comment by rafiss** [comment]
The distinction there is that the `cockroach` CLI tool does not support `COPY` statements, but if you have an app or some other tool that sends a `COPY` statement to a CockroachDB server, we do support that. (Though we don't support _all_ of the `COPY` syntax that Postgres has. See https://github.com/cockroachdb/cockroach/issues/41608

**Comment by ericharmeling** [comment]
> The distinction there is that the `cockroach` CLI tool does not support `COPY` statements, but if you have an app or some other tool that sends a `COPY` statement to a CockroachDB server, we do support that. (Though we don't support _all_ of the `COPY` syntax that Postgres has. See [cockroachdb/cockroach#41608](https://github.com/cockroachdb/cockroach/issues/41608))

I see. Thanks for the clarification!

This type of support seems fairly particular. Are there any other statements that you know of that are only supported if issued by some third-party clients?

**Comment by rafiss** [comment]
Hmm no, off the top of my head I'm not familiar of other syntax that we support in that way, but COPY is a rather odd/special statement.

**Comment by ericharmeling** [comment]
@rafiss Another question... do we only support executing `COPY FROM` (and *not* `COPY TO`)?

**Comment by rafiss** [comment]
Correct, just `COPY FROM`
