### ISSUE TITLE
PARTITION BY Doc use single copy and pastable example 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#9028]
Re: [PARTITION BY](https://cockroachlabs.com/docs//v20.2/partition-by.html)

## Issue Description

[Querying partitions](https://www.cockroachlabs.com/docs/stable/partition-by.html#querying-partitions) uses `movr` as the example allowing copy and paste examples to work.  
[Define a list partition on a table or secondary index](https://www.cockroachlabs.com/docs/stable/partition-by.html#define-a-list-partition-on-a-table-or-secondary-index) uses `students_by_list` which is a part of [`RoachLearn` ](https://www.cockroachlabs.com/docs/stable/partitioning.html#step-4-create-the-roachlearn-database-and-students-table)

It is nice to see two separate schema examples or `movr` and `RoachLearn`. but it takes searching around to perform easy cut and paste for learning.

## Suggested Resolution 

One option might be to have a dedicated page on how to set up `movr`, `RoachLearn`, and other application schemas. Then examples can reference them.

**Comment by jseldess** [comment]
cc @awoods187 and @ericharmeling for triage.

**Comment by awoods187** [comment]
I'm going to close this since we will be significantly changing the UX in 21.1 and it's better covered under multi-region. cc @rmloveland
