### ISSUE TITLE
Guidance on what to specify for n_buckets

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#9029]
Exalate commented:

Re: [Indexes](https://cockroachlabs.com/docs//v20.2/indexes.html)

## Issue Description

`USING HASH WITH BUCKET_COUNT` requires  `n_buckets`.  [Hash Sharded Indexes Unlock Linear Scaling for Sequential Workloads](https://www.cockroachlabs.com/blog/hash-sharded-indexes-unlock-linear-scaling-for-sequential-workloads/) uses 8.   It is not clear what is the best practice.  

## Suggested Resolution 

More explanation on how to choose `n_buckets` and the trade-offs to be considered.  For example:

- specifying 1 sounds like it is the same as not using hashing.   
- what are the trade-offs when 2,3,4 or any other numbers are specified?  
- Does the number of ranges on hash index multiply by the number of `n_buckets`.  For example, if a regular index were to have 10 ranges, does `n_buckets`=16 results in 10*16 = 160 ranges?
- should the bucket be powers of `^2`?  

cc @aayushshah15 

Jira Issue: DOC-839

**Comment by jseldess** [comment]
@ericharmeling and @awoods187 for prioritization.
