### ISSUE TITLE
incorrect link on Deploy CockroachDB on Microsoft Azure (Insecure) page

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#903]
The `Secure` button on the new [Deploy CockroachDB on Microsoft Azure (Insecure) page](https://www.cockroachlabs.com/docs/deploy-cockroachdb-on-microsoft-azure-insecure.html) points to the secure GCE instruction page instead of the secure Azure instruction page.

**Comment by sploiselle** [comment]
Thanks for catching that!
