### ISSUE TITLE
usability issues with JPA hello world tutorial

### ISSUE THREAD

**Issue by dianacarroll** [cockroachdb/docs#9031]
Exalate commented:

I am working through the JPA tutorial and have a few things I noticed that I think would improve it.

1) The README.md steps and the steps on the docs page are out of sync:
* docs have you choose your own user name, the readme specifies maxroach
* The docs have you start "cockroach demo", the readme has you start a secure cluster, with a link to https://www.cockroachlabs.com/docs/stable/secure-a-cluster

2) I believe that demo mode, by nature, means that if I stop and restart cockroach, my schema changes disappear. Although that is well-documented elsewhere, I think it would be helpful to mention here as well, because it's a non-intuitive way for a DB to work. Maybe just a link to what demo mode is.

3) I was confused about what port to configure in the .cfg file. The instructions say "Where {port} is the port number on which the CockroachDB demo cluster is listening." I looked at the CRDB startup output to find the port (which I think is the only way to do that?) However, the actual output when starting cockroach looks like this:

```
# Connection parameters:
#   (console) http://127.0.0.1:58979
#   (sql)     postgres://root:admin@?host=%2Fvar%2Ffolders%2F56%2Fd9tz0kvd59s3vhrw67lqvhkr0000gp%2FT%2Fdemo923542301&port=26257
#   (sql/tcp) postgres://root:admin@127.0.0.1:58981?sslmode=require
```
there are two different ports it shows: 58979 (for "console" and "sql/tcp") and 26257 (for "sql"). I used the wrong one (26257) and nothing worked. It would be helpful if the instructions were more explicit, such as something like "use the port as specified when you started cockroach in the sql/tcp connection parameter".

(Is that a CRDB bug?)

Jira Issue: DOC-841

**Comment by dianacarroll** [comment]
Wait! The port issue is user error. I see that at the very beginning of the exercise, it explains where to get the port.  I had lost that from my brain by the time I got to the end where you actually edit the config file. (Might still be nice to have something like "where port is the port number you took note of in step 1 when starting cockroach" for people of limited brain such as myself.)

**Comment by ianjevans** [comment]
@ericharmeling I can add some clarification text to the `start-cockroachdb.md` include to address points 2 & 3, which will cascade to the other tutorials. Just a heads up.

**Comment by ianjevans** [comment]
It may not necessarily be a goal to have the code project README exactly match the tutorials. E.g. we may want simplified instructions in the README that work with minimal or no code changes.

That's not to say I'm against changing the README to use a demo cluster and unspecified user, just that we may want to think about whether users coming across the `cockroachlabs/hello-world-X` repos are different than the ones reading our docs.

**Comment by ianjevans** [comment]
I'll also point out that I wasn't consistent about this with the other hello-world examples, which track the docs more closely.

**Comment by dianacarroll** [comment]
The user name issue is minor but running in demo mode or not is pretty
significant. Given the depreciation of insecure mode, if the run a
persistent (non demo) cluster, they will need to generate certificates and
pass them in the URL and so on. Not to mention the need to start a shell
separately rather than having it just come up when crdb starts.

**Comment by ianjevans** [comment]
The secure version of the examples are using basic auth, not certificates. So it's over SSL, but with usernames and passwords. If we used explicit usernames and passwords as defaults in the code, and demo mode had a non-transient port number by default (which we've asked for), the only thing the user would need to do is grant privileges to maxroach on the bank database. The code could run unmodified.

**Comment by ianjevans** [comment]
I don't believe demo mode supports certificate authentication, fwiw.

**Comment by ericharmeling** [comment]
FYI, https://github.com/cockroachdb/cockroach/pull/56737 fixes the transient port issue with cockroach demo.

**Comment by awoods187** [comment]
Bumping to P1 to match Java's importance and due to changes made in 21.1.
