### ISSUE TITLE
Maybe document "prevent stale reads due to observed timestamps"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#9042]
There is work ongoing to update our timestamp mechanism to prevent a scenario wherein a user could observe a stale read anomaly.

However it is not clear yet if this work will require that we update our transaction layer docs, which only mention "timestamps" generically, and (at a quick glance) do not appear to discuss some of the more esoteric concepts mentioned in the linked issue.

Estimated scope of work:

- Investigate whether there is docs work needed here
- If so, possibly update the architecture docs to include some of these new concepts / mechanisms

See also:

- https://github.com/cockroachdb/cockroach/issues/36431

**Comment by jseldess** [comment]
No docs work. Fixing a rare bug.
