### ISSUE TITLE
cockroach dump Doc Update include example for --url

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/docs#9046]
Re: [cockroach dump](https://cockroachlabs.com/docs//v20.2/cockroach-dump.html)

## Issue Description
The page does not have an example that shows how to use this functionality with CockroachCloud. 

## Suggested Resolution 
Include an example that uses the --url flag and a connection string from CockroachCloud.

**Comment by lnhsingh** [comment]
I'm not sure if we should add an example (/update these docs in general) since `cockroach dump` is deprecated in 20.2+. What are your thoughts here @mwang1026?

**Comment by mwang1026** [comment]
Ya. Not priority since it's deprecated.
