### ISSUE TITLE
Installation instructions (binary/mac) incomplete

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#9059]
William Cross (thatnerd) commented:

I tried installing CockroachDB on a clean mac, and the installation broke because of a missing `/usr/local/bin/` directory.

Environment
-------------

* Macbook Air (Retina, 13-inch, 2018) 
* MacOS 10.14.6 (Mojave)

Steps to reproduce
-------------------

* Wipe the mac & started from scratch.
* Go to [our installation page](https://www.cockroachlabs.com/docs/stable/install-cockroachdb-mac.html#download-the-binary-1) for installing the binary.
* Perform the `curl` command to get the binary (for me it was `curl https://binaries.cockroachdb.com/cockroach-v20.2.2.darwin-10.9-amd64.tgz | tar -xJ`).
* Attempt to copy the binary to `usr/local/bin/` with the provided command (for me it was `cp -i cockroach-v20.2.2.darwin-10.9-amd64/cockroach /usr/local/bin/`).

Expected result
----------------

Binary gets copied there, or maybe it gives me a permission error & it copies with `sudo`

Actual result
-------------
```
$ cp -i cockroach-v20.2.2.darwin-10.9-amd64/cockroach /usr/local/bin/
cp: directory /usr/local/bin does not exist
$
```

Possible solution
-----------------

Add a step for `sudo mkdir /usr/local/bin` in the instructions, and change the `cp` command to `sudo cp`.

Jira Issue: DOC-849

**Comment by jseldess** [comment]
@taroface, @piyush-singh, this feels like something we should prioritize, given it concerns the installation workflow.

**Comment by jseldess** [comment]
From @bdarnell:

>between this and the geo libraries our "simple single binary" isn't so simple anymore. i think we should steer mac users to brew and leave the tarball as an advanced use case
>
>personally i wouldn't install from the tarball into `/usr/local`; i'd put it somewhere else and add that directory to my `$PATH`
>
>and for users for whom that is sufficient instruction, it works great. but if you want to provide more hand-holding, it gets complicated fast because of all the shell init files and the fact that macos switched from bash to zsh by default recently
