### ISSUE TITLE
sql: add metrics to schema changer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9079]
PR: https://github.com/cockroachdb/cockroach/pull/54855

From release notes:
> Added some metrics surrounding schema changes. [#54855][#54855] {% comment %}doc{% endcomment %}

Kind of related to https://cockroachlabs.atlassian.net/browse/CRDB-104.

**Comment by ericharmeling** [comment]
Potentially resolved by https://github.com/cockroachdb/docs/pull/8909. This doesn't seem to touch anything user-facing beyond some `crdb_internal.*` tables. 

Closing for now. @ajwerner Please re-open if you disagree.
