### ISSUE TITLE
timeutil: embed Go time zone data into CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9082]
PR: https://github.com/cockroachdb/cockroach/pull/56634

From release notes:
> The timezone data is now built in to the CockroachDB binary, which is the fallback source of time if `tzdata` is not located by the default Go standard library. [#56634][#56634] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@otan, does this change also apply to the Windows binary? https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-windows#download-the-executable

**Comment by otan** [comment]
yes, that problem is now gone

**Comment by jseldess** [comment]
@taroface, I can take this.
