### ISSUE TITLE
backupccl: add feature flag support for BACKUP, RESTORE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9084]
PR: https://github.com/cockroachdb/cockroach/pull/56533

From release notes:
> Added cluster settings to enable/ disable the `BACKUP` and `RESTORE` commands. Attempts to use these features while they are disabled returns an error indicating that the database administrator has disabled the feature. Example usage: `SET CLUSTER SETTING feature.backup.enabled = FALSE; SET CLUSTER SETTING feature.backup.enabled = TRUE; SET CLUSTER SETTING feature.restore.enabled = FALSE; SET CLUSTER SETTING feature.restore.enabled = TRUE;`. [#56533][#56533] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Hmm.... I think SQL did this project?

**Comment by lnhsingh** [comment]
I'm going to kick this over to the SQL writers for now

**Comment by ericharmeling** [comment]
@mwang1026 

> I think SQL did this project?

I believe that it is.

@vy-ton 

From https://cockroachlabs.atlassian.net/browse/CRDB-2219:

> We don’t plan on publicly documenting these cluster settings but we should document them internally for CC SREs.

Closing this for now.
