### ISSUE TITLE
changefeedccl, importccl, sql: IMPORT/EXPORT/changefeed feature flags

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9085]
PR: https://github.com/cockroachdb/cockroach/pull/56872

From release notes:
> Added cluster settings to enable/ disable the `IMPORT`, `EXPORT`, and changefeed  commands. Attempts to use these features while they are disabled returns an error indicating that the database administrator has disabled the feature. Example usage: `SET CLUSTER SETTING feature.import.enabled = FALSE; SET CLUSTER SETTING feature.import.enabled = TRUE; SET CLUSTER SETTING feature.export.enabled = FALSE; SET CLUSTER SETTING feature.export.enabled = TRUE; SET CLUSTER SETTING feature.changefeed.enabled = FALSE; SET CLUSTER SETTING feature.changefeed.enabled = TRUE;`. [#56872][#56872] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
I think SQL did this? I don't recall

**Comment by jseldess** [comment]
@mwang1026, do you know what these were added? They will be covered in our auto-generated cluster settings docs, assuming they're public settings, but I'm curious if an operator/admin would want to hear about this in the context of bulk i/o docs?

**Comment by mwang1026** [comment]
IIRC it was in 20.2?  Maybe later? But the intention was to give SRE tools to combat against bad clusters (e.g. a user keeps running a TON of backups and takes down the cluster).

AFAIK all cluster settings are "public" in the sense that if you know about it and are `admin` you can change them (although we don't doc all of them)

**Comment by ericharmeling** [comment]
@mwang1026 

>I think SQL did this?

I believe so.

@vy-ton 

From https://cockroachlabs.atlassian.net/browse/CRDB-2219:

> We don’t plan on publicly documenting these cluster settings but we should document them internally for CC SREs.

Closing this for now.
