### ISSUE TITLE
settings: patch backwards incompatible short type identifier change

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9098]
PR: https://github.com/cockroachdb/cockroach/pull/56546

From release notes:
> Changed the underlying type for the version cluster setting. Previously, it was of an internal type representing "state machine", but now it's simply "version". This has no operational implications, but the `Type` column in `cockroach gen settings-list` now shows "version" instead of "custom validation". [#55994][#55994],[#56546][#56546] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as this is outside the scope of our docs and "has no operational implications".
