### ISSUE TITLE
sql: resolve error due to drop table after schema change in same txn

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9111]
PR: https://github.com/cockroachdb/cockroach/pull/56589

From release notes:
> A table can now successfully be dropped in a transaction following other schema changes to the table in the same transaction. [#56589][#56589] {% comment %}doc{% endcomment %}

This is kind of related to https://cockroachlabs.atlassian.net/browse/CRDB-104.

**Comment by ericharmeling** [comment]
AFAIK, we never documented this bug as a known limitation. No docs required.
