### ISSUE TITLE
parser: allow optional = for SURVIVE x FAILURE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9116]
PR: https://github.com/cockroachdb/cockroach/pull/56881

From release notes:
> Added support for an optional `=` character for `SURVIVE`, e.g. `ALTER DATABASE d SURVIVE = ZONE FAILURE`. [#56881][#56881] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@awoods187 do you mind if we close this?  alternative syntax of `SURVIVE = REGIONAL FAILURE` does not seem essential to doc, would rather not increase size of docs with this unless you think it's important to mention.  Probably some context I'm missing here.

**Comment by awoods187** [comment]
yeah im fine with that
