### ISSUE TITLE
sql: add feature flag for CREATE STATISTICS/ANALYZE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9119]
PR: https://github.com/cockroachdb/cockroach/pull/57076

From release notes:
> Adds a feature flag via cluster settings for the `CREATE STATISTICS` and `ANALYZE` feature. If a user attempts to use the command while disabled, an error indicating that the database administrator had disabled the feature is surfaced. Example usage: `SET CLUSTER SETTING feature.stats.enabled = FALSE; SET CLUSTER SETITNG feature.stats.enabled = TRUE;`. [#57076][#57076] {% comment %}doc{% endcomment %}

Related to From https://cockroachlabs.atlassian.net/browse/CRDB-2219.

**Comment by ericharmeling** [comment]
From https://cockroachlabs.atlassian.net/browse/CRDB-2219:

> We don’t plan on publicly documenting these cluster settings but we should document them internally for CC SREs.

@vy-ton 
What is the plan around internal documentation work? Please let me know if I can help in any way. I'll leave this issue open for now.

**Comment by ericharmeling** [comment]
(see comment above)

Closing for now.
