### ISSUE TITLE
sql, featureflag: add schema change feature flag

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9121]
PR: https://github.com/cockroachdb/cockroach/pull/57040

From release notes:
> Added a feature flag via cluster settings for all schema change-related features. If a user attempts to use these features while they are disabled, an error indicating that the database administrator has disabled the feature is surfaced.  Example usage: `SET CLUSTER SETTING feature.schema_change.enabled = FALSE; SET CLUSTER SETTING feature.schema_change.enabled = TRUE;`. [#57040][#57040] {% comment %}doc{% endcomment %}

Related to https://cockroachlabs.atlassian.net/browse/CRDB-2219.

**Comment by ericharmeling** [comment]
From https://cockroachlabs.atlassian.net/browse/CRDB-2219:

> We don’t plan on publicly documenting these cluster settings but we should document them internally for CC SREs.

@vy-ton 
What is the plan around internal documentation work? Please let me know if I can help in any way. I'll leave this issue open for now.

**Comment by ericharmeling** [comment]
(see comment above)

Closing for now.
