### ISSUE TITLE
sql: feature flag for ALTER TABLE/INDEX SPLIT/UNSPLIT

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9122]
PR: https://github.com/cockroachdb/cockroach/pull/57142

From release notes:
> The `ALTER TABLE...SPLIT/UNSPLIT` and `ALTER INDEX...SPLIT/UNSPLIT` commands are now gated by a schema change feature flag. If a user attempts to use these features while they are disabled, an error indicating that the system administrator has disabled the feature is surfaced. Example usage: `SET CLUSTER SETTING feature.schema_change.enabled = FALSE SET CLUSTER SETTING feature.schema_change.enabled = TRUE;`. [#57142][#57142] {% comment %}doc{% endcomment %}

Related to https://cockroachlabs.atlassian.net/browse/CRDB-2219.

**Comment by ericharmeling** [comment]
From https://cockroachlabs.atlassian.net/browse/CRDB-1504:

> We don’t plan on publicly documenting these cluster settings but we should document them internally for CC SREs.

@vy-ton 
What is the plan around internal documentation work? Please let me know if I can help in any way. I'll leave this issue open for now.

**Comment by vy-ton** [comment]
I have an action item here, so will get back to you

**Comment by ericharmeling** [comment]
(see comment above)

Closing for now.
