### ISSUE TITLE
sql: enum introspection improvements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9127]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/57197

From release notes:
> The multi-region enum, created implicitly for all multi-region databases, can be introspected using the `pg_catalog.pg_enum` table. It is also displayed in `SHOW ENUMS`. [#57197][#57197] {% comment %}doc{% endcomment %}

Related to https://cockroachlabs.atlassian.net/browse/CRDB-1504.

Jira Issue: DOC-859

**Comment by ericharmeling** [comment]
@rmloveland 

Are you planning to document this "multi-region enum"?

**Comment by rmloveland** [comment]
> Are you planning to document this "multi-region enum"?

YOINK
