### ISSUE TITLE
backupccl: add cluster setting to exclude stats from backup

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9152]
PR: https://github.com/cockroachdb/cockroach/pull/55879

From release notes:
> Added a setting to opt in or out of including [SQL statistics](../v20.1/create-statistics.html) in [backups](../v20.1/backup.html). [#55879][#55879] {% comment %}doc{% endcomment %}

**Comment by dt** [comment]
@mwang1026 do we need to doc this at all? it was mostly just added so we had it at our disposal in support interactions for 20.1 clusters, but I don't think we expect users to find/use it on their own. I didn't mark it public so it isn't in the settings list for 20.1.

**Comment by mwang1026** [comment]
I don't think we need to doc. Closing.
