### ISSUE TITLE
release-20.2: pgwire: decorate TransactionRetryWithProtoRefreshError with docs URL

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9157]
PR: https://github.com/cockroachdb/cockroach/pull/56049

From release notes:
> Updated the `TransactionRetryWithProtoRefreshError` to include a `HINT` field that links to [a web page containing useful information to resolve the error](../v20.2/transaction-retry-error-reference.html). [#56049][#56049] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we need to document this.
