### ISSUE TITLE
release-20.2: backupccl: add opt-in last-backup-time metric

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9159]
PR: https://github.com/cockroachdb/cockroach/pull/54987

From release notes:
> Added an option to [scheduled backups](../v20.2/manage-a-backup-schedule.html) to maintain a timeseries metric for last backed up timestamp. [#54987][#54987] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
We put this in for SRE, didn't intend for this to be used broadly necessarily so P3. How in general do we handle stuff like that? Do we doc it / hide it / make it abundantly obvious that it exists?

**Comment by lnhsingh** [comment]
For something like this, we usually don't doc it unless we want external users to use it. In this case, I'm gonna close this issue for now. If we want to surface this to external users, we can reopen later (or open a new ticket more likely)
