### ISSUE TITLE
release-20.2: s/Active Sessions/Sessions/ and move Tx link

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9165]
PR: https://github.com/cockroachdb/cockroach/pull/56652

From release notes:
> Rename **Active Sessions** to **Sessions** on the [Session Details page](../v20.2/ui-sessions-page.html). [#56652][#56652] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing as this doesn't need a docs update.
