### ISSUE TITLE
release-20.2: auth: add autoLogin ability to OIDC configuration

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9167]
PR: https://github.com/cockroachdb/cockroach/pull/56510

From release notes:
> Added a new [cluster setting](../v20.2/cluster-settings.html) called `server.oidc_authentication.autologin` which enables an automatic redirect to the OIDC login flow instead of showing a password login prompt. A query parameter can force disable this feature in the browser by appending `?oidc_auto_login=false` to the login path. [#56510][#56510] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as this was added to the auto-generated doc.
