### ISSUE TITLE
Add a temporary unlinked docs page on free tier

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#9169]
We want to enable free tier beta for a subset of new organizations before we release it broadly in our marketing launch in January. To support users who get this early access, we want to have a docs page that covers the key points of information but we don't want this page to be broadly accessible to the public. Instead, it should be hidden in the docs nav, and we will simply link to this page from the Console.

The content should basically just cover what we've been emailing customers about, including tenant architecture basics, known limitations, and a request for feedback. This does not need to be as polished as our January docs will be!

Feel free to reach out to Emily with questions.

**Comment by lnhsingh** [comment]
Related to the work that needs to be done for https://cockroachlabs.atlassian.net/browse/CC-3121
