### ISSUE TITLE
Duplicate Indexes based on column(s) different from the primary index

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#9171]
Florence Morris (florence-crl) commented:

This [documentation page](https://www.cockroachlabs.com/docs/stable/topology-duplicate-indexes.html#steps) describes an example where the secondary indexes are based on column(s) the SAME AS THE PRIMARY INDEX. In this case, secondary indexes should be created on ALL OTHER localities, NOT INCLUDING where the primary index is located.

Please add clarification to that page that secondary indexes based on column(s) DIFFERENT FROM THE PRIMARY INDEX should be created on ALL localities INCLUDING where the primary index is located. This case was pointed out in this support ticket: https://cockroachdb.zendesk.com/agent/tickets/6985.

To test both cases, I used these sql files in a multi-region cluster:
[CREATE INDEX state_idx_central ON postal.sql.txt](https://github.com/cockroachdb/docs/files/5675748/CREATE.INDEX.state_idx_central.ON.postal.sql.txt)
[INSERT INTO postal_codes VALUES.sql.txt](https://github.com/cockroachdb/docs/files/5675749/INSERT.INTO.postal_codes.VALUES.sql.txt)
 

Jira Issue: DOC-870

**Comment by taroface** [comment]
@ericharmeling Would this belong to your area? I'm not sure who previously worked on these docs, but I can also see them belonging to my area.

**Comment by ericharmeling** [comment]
I think Jesse wrote these docs, but they are in the "multi-region" area, which belongs to @rmloveland. Rich, I'm sure this page is on your radar for scheduled multi-region updates?

**Comment by rmloveland** [comment]
This usage pattern will be replaced by something much simpler for end users in 21.1, but we will need to fix bugs in this doc for now.  I'll assign to myself.

**Comment by rmloveland** [comment]
@taroface I hope that's ok that I snagged this.  I need to learn more about these old multi-region patterns as part of writing docs for the new ones.

**Comment by taroface** [comment]
@rmloveland For sure! Thanks for taking it on.
