### ISSUE TITLE
sql/observability: document a list third-party observability tools 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#9176]
We should make a page similar to https://www.cockroachlabs.com/docs/v20.2/third-party-database-tools.html for observability tools. We can think work on filling it in with links to feature-rich documentation like the existing [Prometheus and Grafana](https://www.cockroachlabs.com/docs/v20.2/monitor-cockroachdb-with-prometheus.html) pages. We've recently learned about customers using https://chronosphere.io/ , https://www.honeycomb.io/, [Thanos ](https://thanos.io/) among others and I'm sure that @piyush-singh and @thtruo are aware of others.

**Comment by taroface** [comment]
Also for reference: https://docs.google.com/document/d/1PyX2-5eWZtNKy8RFxrXAWJiXluQRiK8UtuQmB7ihkOg/edit?ts=5fcfd199
