### ISSUE TITLE
Create a "getting started curriculum" resources page in docs to mirror our email campaign

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#9183]
We recently updated our CC getting started emails to include a short (4 emails over 4 weeks) curriculum to get people started and focused on the fundamentals and key resources to be successful with CC. We want to be able to host these resources all in one page in docs as well so that we can also let people follow along at their own pace.

This page could be framed as a "trial guide" or something along those lines and can include links to all the content we highlight in the emails in one page. It would be fine to simply port the emails themselves into a doc with just a few tweaks.

Email copy can be found [here](https://docs.google.com/document/d/1mHhnUr3uHSejcoaONOOtCJjxsrlNqWt4uPm2i6AXU5Q/edit#)

**Comment by lnhsingh** [comment]
In briefly thinking through this request, I'm wondering if it is really necessary. We already have a "Get Started" section in the sidenav under CockroachCloud:

![image](https://user-images.githubusercontent.com/15386648/109237656-035f9300-77a0-11eb-8963-55cbdb2a7d48.png)

This seems sufficient to me, and reading through the email copy, it seems like a lot of the links are covered in the Get Started section and/or are linked within the docs in the "See Also" / "What's Next" sections ([example](https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-a-free-cluster.html#whats-next)).

My worry is that adding a "trial guide" would then confuse users-- how would a new user know the difference between the Quickstart and a Trial Guide? 

I'm going to close this issue for now - if you disagree, please comment / feel free to reopen!
