### ISSUE TITLE
Typo on ALTER TABLE doc

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9184]
Under [Subcommands](https://www.cockroachlabs.com/docs/v20.2/alter-table#subcommands), the third column for ALTER PRIMARY KEY says `Yesnes.html) for a table.` and seems to have an extra column in the markdown. I think this should just say `Yes`.

Needs to be updated on v21.1 and v20.2

**Comment by thtruo** [comment]
I'll try this for fixit

**Comment by ericharmeling** [comment]
Closed by https://github.com/cockroachdb/docs/pull/9190
