### ISSUE TITLE
Use docker volumes in docker instructions

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/docs#9185]
In the [Start a Cluster in Docker (Insecure)](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html) instructions, we provide instructions for starting three nodes in docker containers all writing through to the host filesystem. There is a bug (see cockroachdb/cockroach#57192, [docker/for-mac#5124](https://github.com/docker/for-mac/issues/5124#issuecomment-745393800)) in the current default Docker for Mac implementation of file sharing. The bug causes missing files and permanent crashes of the nodes.

Disabling the gRPC FUSE file sharing option in Docker for Mac is one workaround. Another workaround, recommended by a Docker engineer, is to use docker volumes: https://github.com/docker/for-mac/issues/5124#issuecomment-745211978 . This is also expected to be more performant.

I think we should update the documentation to instruct users to create a separate volume per container:
```
docker volume create roach1
docker volume create roach2
docker volume create roach3
```

And then update the `-v` flag to pass the volume identifer:
```
-v "roach1:/cockroach/cockroach-data" \
```

**Comment by jseldess** [comment]
@taroface, this fixes a bad UX problem running us in docker on mac. Can you squeeze in this fix?
