### ISSUE TITLE
Add Contributor Section to Kubernetes Operator README

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#9188]
To serve our growing set of contributors for the Operator, let's add two things:
1. Good First Issues
2. Known Issues

For both items, let's either embed the list or point to query that gets the existing list of them.

To complement this contributor section in the README, @Amruta-Ranade will be pointing to our Operator good first issues from the overall CockroachDB contributor page.

**Good First Issues:**
We maintain our set of good first issues with the Github issue label. One can see the existing list of good first issues with [this query](https://github.com/cockroachdb/cockroach-operator/labels/good%20first%20issue).

**Known Issues**
Second, let's be transparent about our known issues. I've put together this list of known issues that includes relevant bugs and/or known unimplemented features in the Operator:

1. VMware Tanzu, EKS and AKS have not been tested.
2. The Operator has not been tested with Istio.
3. It does not support multiple clusters for multi-region (e.g. multi-cluster k8s docs without Operator)
4. [No support for pod security policy](https://github.com/cockroachdb/cockroach-operator/issues/216)
5. [Migrating from a deployment using the Helm Chart to the Operator has not been defined nor tested.](https://github.com/cockroachdb/cockroach-operator/issues/140)
6. [There is no support for an ingress object.](https://github.com/cockroachdb/cockroach-operator/issues/76)

**Comment by taroface** [comment]
Closed by https://github.com/cockroachdb/cockroach-operator/pull/281
