### ISSUE TITLE
Define Table Partitions Doc Update - remove enum limitation

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#9206]
Re: [Define Table Partitions](https://cockroachlabs.com/docs//v20.2/partitioning.html)

> Partitions cannot be created on columns of type ENUM. See tracking issue.

The tracking issue has been recently closed 🎆 and the limitation will not be there in 21.1.
cc @ajwerner

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/10164.

**Comment by ericharmeling** [comment]
- [ ]
