### ISSUE TITLE
system.jobs maintains 600 seconds gc.ttl when upgrading from 19.2

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/docs#9210]
Matthew Vardi (mattcrdb) commented:

If you upgrade your cockroach cluster from 19.2 to a later major version we don't update the gc.ttl on the `system.jobs` table from 600 seconds to 90000 seconds (the default on 20.1+).

This causes users to run into replica gc errors on the `system.jobs` table (table 15) when they take hourly incremental backups.

we should call out in the upgrade path to 20.1 that users should change this when they stop upgrading (in case they go from 19.2 all the way to 20.2).

the error looks like this: `ERROR: exporting 13627 ranges: exporting /Table/15/{1-2}: start timestamp 1608073151.471327928,0 must be after replica GC threshold 1608077595.924001245,0` (note the `/Table/15`).

gz#7432

Jira Issue: DOC-875

**Comment by jseldess** [comment]
@piyush-singh, @taroface, for prioritization.

**Comment by mattcrdb** [comment]
Another customer ran into this issue in their production cluster this past weekend.
