### ISSUE TITLE
Replace minikube with k3d in local k8s cluster examples

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#9213]
Piyush Singh commented:

We use minikube to spin up local clusters in our guides to deploying locally with Kubernetes. For example, our "Orchestrate a Local Cluster with Kubernetes" [guide references minikube](https://www.cockroachlabs.com/docs/v20.2/orchestrate-a-local-cluster-with-kubernetes.html). Instead, [our SRE team prefers](https://cockroachlabs.slack.com/archives/CJX8V9SJ2/p1608237457344500) using [k3d](https://github.com/rancher/k3d) as it is lightweight and fast compared to minikube.

We should update our docs to follow the best practice recommendations from our SRE team.

Jira Issue: DOC-876

**Comment by taroface** [comment]
Per @keith-mcclellan the various K8s emulators have pros/cons for different use cases, and we should discuss (maybe with SREs) which we want to recommend on our public docs.
