### ISSUE TITLE
Function description not on new line

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#922]
Just noticed that the function description for `replace`, which is the only long-form description we have right now, is not on a new line. 

cc @sploiselle 

<img width="845" alt="screen shot 2016-12-13 at 11 37 55 am" src="https://cloud.githubusercontent.com/assets/15893490/21149175/9d0d9606-c128-11e6-86bb-f8177b146991.png">

**Comment by dt** [comment]
is there some caching on customstyles.css?

**Comment by sploiselle** [comment]
Cleared CloudFlare cache, hard-refreshed browser, and issue's resolved.

**Comment by jseldess** [comment]
Thanks, @sploiselle and @dt.
