### ISSUE TITLE
Fix broken external links

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9220]
Jesse Seldess commented:

@yingzhuchin got our nightly TC test working again before going on leave. The nightly test has `htmltest` check all links, including external links, whereas TC ignores external links when checking PRs. We have lots of broken external links that need to be fixed. 

Jira Issue: DOC-1650

**Comment by lnhsingh** [comment]
@taroface assigning this to you since it looks like it affects deployment docs, but feel free to pull others in to help too.
