### ISSUE TITLE
Expand the CC FAQs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9224]
We have an external CockroachCloud FAQ in our docs: https://www.cockroachlabs.com/docs/cockroachcloud/frequently-asked-questions.html. And we have an internal CC FAQ for the field: https://docs.google.com/document/d/1foKgViAVMbXF15SROF3JFKEeWFvX3f4cyCL6dUPgFlo/edit.

We should check whether anything in the internal FAQ should be reused or adapted for the external FAQ.

cc @lnhsingh, @kannanlakshmi, @jaymce

**Comment by kannanlakshmi** [comment]
CC FAQ needs some corrections including updating "how to add nodes" 
https://www.cockroachlabs.com/docs/cockroachcloud/frequently-asked-questions.html#how-do-i-add-nodes

**Comment by jseldess** [comment]
Got this note via email from @kannanlakshmi. Adding to the ticket:

> CC FAQ needs some corrections including updating "how to add nodes"
https://www.cockroachlabs.com/docs/cockroachcloud/frequently-asked-questions.html#how-do-i-add-nodes

**Comment by lnhsingh** [comment]
Closing in favor of CC-3707
