### ISSUE TITLE
release-20.2: sql,builtins: add builtin functions to perform descriptor repair

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9231]
PR: https://github.com/cockroachdb/cockroach/pull/56937

From release notes:
> Added admin-only `crdb_internal` [functions](../v20.2/functions-and-operators.html) to enable descriptor repair in dire circumstances. [#56937][#56937] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This doesn't seem like a function for external users. Closing for now.

@vy-ton 
Please re-open if you disagree from a product perspective.

@taroface 
Please re-open if you believe this is essential to operator docs.
