### ISSUE TITLE
Start a Local Cluster (Insecure): slow shutdown

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9241]
Steven Hand (hand-crdb) commented:

Re: [Start a Local Cluster (Insecure)](https://cockroachlabs.com/docs//v20.2/start-a-local-cluster.html)

## Issue Description

For step <span>#</span>7, "[Stop the Cluster](https://www.cockroachlabs.com/docs/v20.2/start-a-local-cluster#step-7-stop-the-cluster)", I experienced two issues going through this:

1. The slowness in shutdown that is mentioned started with the 3rd node that was shut down, not the 4th node as described.
1. The shutdown process for each of the nodes 3, 4, and 5 took much longer than "about a minute".  Each took well over 10 minutes.

## Suggested Resolution 

- Verify with the development team whether the slowness in shutdown is expected to be with the 3rd or with the 4th node that is shut down.
- Verify with the development team what the expected shutdown time should be for the latter nodes, and document accordingly.

Note: This occurred using a 2020 MacBook Pro with 32GB RAM.

<img width="1430" alt="shutdown slowness couple issues 2020-12-23" src="https://user-images.githubusercontent.com/76179780/103234237-27703680-490d-11eb-9a0f-1223bd2fb278.png">

Jira Issue: DOC-885

**Comment by jseldess** [comment]
cc @taroface
