### ISSUE TITLE
Add ability to submit qualitative feedback with a negative vote (Was this page helpful? No) 

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9242]
Steven Hand (hand-crdb) commented:

Re: [Start a Local Cluster (Insecure)](https://cockroachlabs.com/docs//v20.2/start-a-local-cluster.html)

## Issue Description

I pressed the "No" button in response to the question at the bottom of the page that asked, "Was this page helpful?".  I expected to be offered an opportunity to suggest feedback to improve the page.  Instead, all it said was, "Thanks for the feedback!".  

The potential consequence of this behavior is that, after the first time a user receives such a response, they may stop responding to similar feedback opportunities on other pages.

## Suggested Resolution 

When a user presses the "No" button, solicit additional information on why the page was not helpful and what would improve the page.

<img width="1502" alt="doc no button just replied Thanks for the feedback 2020-12-23a" src="https://user-images.githubusercontent.com/76179780/103291121-111fb480-49b9-11eb-8c2f-ae2ce15d1c66.png">

<img width="1430" alt="doc no button just replied Thanks for the feedback 2020-12-23" src="https://user-images.githubusercontent.com/76179780/103291141-1bda4980-49b9-11eb-8f76-b51faf044e52.png">

Jira Issue: DOC-886

**Comment by jseldess** [comment]
Yes, totally agree. Previously, we had an additional form for submitting such feedback. However, we were using Hubspot for that, which the Marketing team recently moved off of to Marketo. We need to put find another solution to put this back in place. 

@luciaaaaaaa, @lnhsingh, @anagio, this wasn't part of the docs redesign, of course, but if you have ideas, please chime in.

**Comment by lnhsingh** [comment]
Thanks for submitting this @hand-crdb. I'll add it to our [Docs Redesign feedback board](https://github.com/cockroachdb/docs/projects/64) and we'll investigate a solution.

**Comment by jseldess** [comment]
@lnhsingh, we can hold off on this until after the redesign launch as we need to figure out what tool to use for this form.
