### ISSUE TITLE
Rollover popup menus hinder effective use of the web pages

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9243]
Re: [Hello World Example Apps](https://cockroachlabs.com/docs//v20.2/hello-world-example-apps.html)

## Issue Description

The dropdown menus ("Why CockroachDB", "Product", and "Resources") hinder effective use of the web pages, for two reasons:

1. The menus display by simply moving a pointer over them, instead of clicking on them.  While many in the the Web UI community accept this, please reconsider.  Users generally move their pointer in order to, well, simply move it; to get it to another part of the screen.  It violates the "don't surprise" principle of UI design to have menus display as a side-effect of a user acting on their intention to simply move their pointer.  This is exacerbated when the menu hides the very content they intend to move their pointer to, which brings up a second reason:
1. The menus are too large, with too much white space, and have no visible border.  These effects combine to make it hard to distinguish between the menu itself and the background web page.  Given that the user probably did not consciously cause the menu to appear, the user has to 1: recognize that they are looking at a page that contains a menu instead of the expected content, 2: discern the boundaries of the menu, and 3: figure out where to move their pointer to make the menu go away.  It interrupts their "flow" by creating a kind of "puzzle" that they have to solve before they can continue what they intended to do.

## Suggested Resolution 

Action to display:

- Display drop-down menus by clicking on them, not by rolling over them.  
- If you wish to keep the rollover functionality, reduce the active "trigger" area the menu words themselves, because moving the pointer in the white space that is well above the menu words also causes the menus to display.

Menu design/content:

- Reduce the size of the menus
- Remove large blank areas
- Make menus more conspicuous and distinct (perhaps by having a border)

Example:

<img width="1232" alt="dislike rollover menus A 2020-12-23" src="https://user-images.githubusercontent.com/76179780/103293778-817d0480-49be-11eb-8774-7e2522f033f8.png">

<img width="1233" alt="dislike rollover menus B 2020-12-23" src="https://user-images.githubusercontent.com/76179780/103293788-85108b80-49be-11eb-9eca-10bb221d25f7.png">

**Comment by lnhsingh** [comment]
Marketing is currently updating their top nav to drop down on **click** instead of on **rollover**. We need to update the Docs top nav once this change is made, to mirror their updates (since the navigation is not global on the backend).
