### ISSUE TITLE
Make Queries Fast Doc Update 

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#9245]
Jessie Lin (lin-crl) commented:

Re: [Make Queries Fast](https://cockroachlabs.com/docs//v20.2/make-queries-fast.html)

## Issue Description
explain results of the first join sql shows estimated row counts.
I followed the instruction but after initiate movr workload and ran explain, it showed missing stats on both rides and users tables

## Suggested Resolution 
Validate the results of explain and update accordingly. Here's the results I got.

                                                    info
-------------------------------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • limit
  │ count: 10
  │
  └── • sort
      │ order: -count_rows
      │
      └── • group
          │ group by: name
          │
          └── • hash join
              │ equality: (id) = (rider_id)
              │
              ├── • scan
              │     **missing stats**
              │     table: users@primary
              │     spans: FULL SCAN
              │
              └── • filter
                  │ filter: (start_time >= '2018-12-31 00:00:00') AND (start_time <= '2019-01-01 00:00:00')
                  │
                  └── • scan
                        **missing stats**
                        table: rides@primary
                        spans: FULL SCAN
(27 rows)

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
