### ISSUE TITLE
Fix internal webpage broken lInk

### ISSUE THREAD

**Issue by saintmalik** [cockroachdb/docs#9249]
Navigating to Product Page of [CockroachDB on Kubernetes](https://www.cockroachlabs.com/product/kubernetes)

![Screenshot 2021-01-01 at 12 38 40 PM](https://user-images.githubusercontent.com/37118134/103438007-6284a980-4c2e-11eb-9fce-a0e43c8b5b75.jpg)

Clicking on **More about Kubernetes Operator learn more** button, which is a link text to the full details of Kubernetes Operator leads to a dead link that is caused by a little typo.

![Screenshot 2021-01-01 at 12 38 18 PM](https://user-images.githubusercontent.com/37118134/103438010-6e706b80-4c2e-11eb-9121-352d31777b63.jpg)

Here is the dead Link caused by the "space typo" which got encoded to "%20" https://www.cockroachlabs.com/docs/stable/orchestra%20te-cockroachdb-with-kubernetes.html#install-the-operator

Here is the correct link that should be there: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#install-the-operator

**Comment by jseldess** [comment]
Thanks for reporting this, @saintmali. This fix needs to be made by our Marketing team, so I'll pass it over to them.

**Comment by saintmalik** [comment]
Thank you @jseldess, Glad the dead URL will be fixed now😊

**Comment by jseldess** [comment]
This is logged in Marketing's internal tracker, so closing this.

**Comment by saintmalik** [comment]
Okay, thanks ✌️
