### ISSUE TITLE
Create repo for Sequelize "Hello World" example

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#9253]
The [code in our docs](https://www.cockroachlabs.com/docs/v20.2/build-a-nodejs-app-with-cockroachdb-sequelize#step-4-run-the-node-js-code) should be available in Github so that our contractor can submit edits for review.

**Comment by vy-ton** [comment]
@ericharmeling Any chance you can create the repo this week? Our Sequelize contractor needs it

**Comment by ericharmeling** [comment]
I created a repo: https://github.com/cockroachlabs/hello-world-node-sequelize

We might also want to point the contractor to https://github.com/cockroachdb/examples-orms/tree/master/node.
