### ISSUE TITLE
Confirm that we use cloud provider EAR for CC

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#9256]
Add to FAQs as well as the security section here https://www.cockroachlabs.com/docs/cockroachcloud/security-overview.html

Some context https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1609698452215500

This one is time sensitive, so if we can add this week, that would be great. 

cc @piyush-singh

**Comment by piyush-singh** [comment]
Notes on our encryption at rest in Cockroach Cloud:

- We do not enable EAR within CockoachDB by default. Note that this means in the CockroachDB admin UI, encryption will appear disabled. This is only for CRDB specific EAR - the Admin UI is not aware of cloud provider encryption. Note: This problem should go away after we embed admin UI pages into Cloud as we are not planning to embed advanced/debug pages.
- All data is encrypted at rest using the encryption tools provided by the cloud providers that a customer's cluster is running in
- End users cannot enable EAR as it requires access to the CLI which is not possible in Cloud. EAR requires starting nodes in the cluster with specific encryption flag, and rotating keys also requires a rolling restart with keys swapped in flags on restart.
