### ISSUE TITLE
Remove cockroach quit from tutorials (it is deprecated)

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/docs#9261]
Fabio Ghirardello (fabiog1901) commented:

`cockroach quit` is [deprecated](https://www.cockroachlabs.com/docs/stable/cockroach-quit.html) in the latest release.

I found it here and in other sections, too.
https://www.cockroachlabs.com/docs/stable/demo-fault-tolerance-and-recovery.html#step-5-simulate-a-single-node-failure

Jira Issue: DOC-890

**Comment by jseldess** [comment]
cc @taroface, @mikeCRL
