### ISSUE TITLE
update batch INSERT guidance

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9276]
Ryan Kuo (taroface) commented:

[This guidance](https://www.cockroachlabs.com/docs/v20.2/insert#performance-best-practices) on batching may not be correct in all cases. Per @nvanbenschoten:

> There are very real cases, especially when a table has no secondary indexes, where single-row INSERTs perform best in terms of total system throughput. 

- Update this guidance to mention that while people should test with multiple row batches, they should also be sure to test with single row batches as well. Skipping straight to multiple rows per insert may miss the optimal batch size.

Source/context: https://cockroachlabs.atlassian.net/wiki/spaces/TS/pages/1139081478/High+execution+time+on+batch+updates (see comments)

Jira Issue: DOC-893

**Comment by taroface** [comment]
@ericharmeling Feel free to unassign/reassign!

**Comment by ericharmeling** [comment]
No you're right - this should go to me. Thanks!

**Comment by ericharmeling** [comment]
@ianjevans Would be good to incorporate in https://github.com/cockroachdb/docs/issues/9860.
