### ISSUE TITLE
Add details on how to request data deletion to docs

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#9277]
Users have requested to remove profile information from CC, including credit card details and email associations. We should add information in docs on how to do this, so it's clear what users' options are.

1. Delete your SQL user (self-service) - deletes your user and any permissions they had on the cluster/databases
2. Delete your cluster (self-service) - deletes all the data in the cluster, backups are deleted after a period (I think ~30 days)
3. Delete your organization (self-service) - deletes all the clusters within your organization, removes the association between email accounts 
4. Remove your credit card (support ticket) - we keep a card on file even when a user deletes their organization so we can process pending charges. Users can request the card be removed once their charges are settled through a ticket
5. Remove your email address (support ticket) - we don't currently allow users to delete their accounts self-service. To remove record of a user's email they can create a support ticket and we can scrub their account record.

cc @aaron-crl for visibility. This is in response to customers requesting data removal in the past month, but I think it puts us in a slightly better position for GDPR to have a clear process here.

**Comment by lnhsingh** [comment]
Should we also add info on how to delete your account entirely (if you can do so)?

**Comment by aaron-crl** [comment]
cc @adbrenn for compliance considerations.

**Comment by emily-horing** [comment]
> Should we also add info on how to delete your account entirely (if you can do so)?

You can't really. I think we could remove your data from our db but there's nothing the user can really do other than contact support I don't think.
