### ISSUE TITLE
Group releases by major version

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/docs#9278]
Fabio Ghirardello (fabiog1901) commented:

Re: [Releases](https://cockroachlabs.com/docs//releases/)

## Issue Description

confusion on "Latest": as of today, the latest release is either v20.2.3, or v20.1.10, depending on what you mean by latest: the former in terms of product features, the latter in chronological order.

## Suggested Resolution 

Group the releases by major version, example below, as it is more likely that customers might want to check the latest in both absolute terms, and the latest of their current version. Then it will be immediately obvious which version is the latest in terms of prod features (the top item on the top group), and the latest for each major version.

### v20.2

v20.2.3 | Dec 14, 2020 | Precompiled 64-bit Binary
v20.2.2 | Nov 25, 2020 | Precompiled 64-bit Binary
v20.2.1 | Nov 20, 2020 | Precompiled 64-bit Binary
v20.2.0 | Nov 10, 2020 | Precompiled 64-bit Binary

### v20.1
v20.1.10 | Dec 21, 2020 | Precompiled 64-bit Binary
v20.1.9 | Dec 1, 2020 | Precompiled 64-bit Binary
v20.1.8 | Oct 21, 2020 | Precompiled 64-bit Binary

Jira Issue: DOC-894

**Comment by jseldess** [comment]
Thanks for opening this, @fabiog1901. I just fixed the ordering: https://github.com/cockroachdb/docs/pull/9295. There's some automation to the way the page is built, so restructuring the page to be more clearly grouped by release will be a larger effort. I'll put this on the backlog for our product ops engineer.
