### ISSUE TITLE
default kubernetes documentation needs to move to a 3 port config (--sql-addr)

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/docs#9284]
Our default kubernetes docs and configs do not split GRPC and SQL ports nor provide a way to do this.  As more customers want to provide SQL access outside of kubernetes, this is increasingly important for customers to be able to meet our production guidelines when running in an orchestrated environment.

**Comment by taroface** [comment]
Three-port configuration is now described in our docs: https://www.cockroachlabs.com/docs/stable/operate-cockroachdb-kubernetes.html#configure-ports

Closing this issue.
