### ISSUE TITLE
Migrate from Oracle Doc Update 

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/docs#9293]
Re: [Migrate from Oracle](https://cockroachlabs.com/docs//v20.2/migrate-from-oracle.html)

## Issue Description

Discrepancy for the Delimiter.  Oracle migration docs show "|" and generic CSV migration says tab `WITH delimiter = e'\t'` 

## Suggested Resolution 

Change migration example to use `WITH delimiter = e'\t'` delimiter.

**Comment by jseldess** [comment]
cc @mwang1026, for prioritization once we have an IO writer again.
