### ISSUE TITLE
Add docs for ALTER TABLE .. {ADD,REMOVE} NON-VOTING REPLICAS

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#9302]

**Comment by rmloveland** [comment]
@aayushshah15, @andreimatei and/or @nvanbenschoten:

Based on the draft milestone F doc it looks like the SQL statement(s) `ALTER TABLE ... ADD/REMOVE NON-VOTING REPLICAS` is not happening in v21.1.  Is that correct?

If so I'd like to close this.

**Comment by nvanbenschoten** [comment]
Yes, that's correct. The syntax is not going to land in this release.
