### ISSUE TITLE
Wrong link on main doc page to Availability FAQs

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9310]
Re: [CockroachDB Docs](https://www.cockroachlabs.com/docs/stable/)

## Issue Description

On the main doc page at https://www.cockroachlabs.com/docs/stable/, the link to **Availability FAQs** takes you to the page for **Operational FAQs** at https://cockroachlabs.com/docs//v20.2/operational-faqs.html

## Suggested Resolution 

- Create a page for Availability FAQs if it does not yet exist
- Update the **Availability FAQs** link on the main doc page to point to this page

Here's a screen shot:

<img width="1254" alt="wrong link for availability FAQs 2021-01-04" src="https://user-images.githubusercontent.com/76179780/103797522-8e30d680-5016-11eb-9855-61c9145ef824.png">

**Comment by lnhsingh** [comment]
I _think_ think should be resolved by our Docs Redesign project, but will add this to our board to make sure we follow up on this. Thanks for filing this!
