### ISSUE TITLE
poor performance on macos when using the pebble engine

### ISSUE THREAD

**Issue by Lukens4242** [cockroachdb/docs#9311]
When doing a simple insert on macos (big sur), the performance is poor when using the pebble storage engine.  When auto_trace is turned on, the poor performance disappears.

Select all that apply:

* is there a difference between the performance you expect and the performance you observe?
* are you surprised by your performance results?

**Observed performance**

What did you see? How did you measure it?

I created a simple table with a single column 'id' of type int.
```
root@:26257/tpcc> \set auto_trace off
root@:26257/tpcc> insert into dml (id) values (19);
INSERT 1
Time: 100ms total (execution 100ms / network 1ms)
```
The above performance is horrible.

If I set auto_trace on, it reports that it took both 172ms and 3ms (see the beginning and end).
```
root@:26257/tpcc> \set auto_trace on
root@:26257/tpcc> insert into dml (id) values (20);
INSERT 1

Time: 172ms total (execution 171ms / network 0ms)
```
Trace output is now in [this comment](https://github.com/cockroachdb/docs/issues/9311#issuecomment-954921939). (Moved for reasons related to a sync between GH and Jira.)

**Time: 3ms total (execution 1ms / network 2ms)**

Why does one part of this output say the insert took >100ms and the last line say it took 3ms?

If I do this same exercise with rocksdb as the engine, I get predictable 2ms insert times.

When/how would you consider this issue resolved? 

We will be having customers that do initial tests on macos, and we need to understand the expected behavior and potential guidance for how to evaluate the performance of the db engine.

Select all that applies:

* I mostly seek information: data, general advice, clarification.

@petermattis

**Comment by jseldess** [comment]
Since this issue is quite old, we're have a different storage engine now (pebble), and this problem hasn't been raised by other users, I'll close this issue for now.
