### ISSUE TITLE
Update movr app and examples in docs to use new multi-region features

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#9313]
Richard Loveland (rmloveland) commented:

We should update [movr](https://www.cockroachlabs.com/docs/stable/movr.html) to use the new multi-region features coming in 21.1

The exact scope of this work is TBD

Jira Issue: DOC-903

**Comment by ericharmeling** [comment]
FWIW:
https://github.com/cockroachlabs/movr-flask/pull/16

**Comment by ericharmeling** [comment]
We should also coordinate with engineering to update the built-in movr schema so that it uses the new multi-region syntax.
