### ISSUE TITLE
Start a Cluster in Docker: Incorrect command to get node startup details from logs

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#9318]
Re: [Start a Cluster in Docker (Insecure)](https://cockroachlabs.com/docs//v20.2/start-a-local-cluster-in-docker-mac.html)

## Issue Description
The path to log file is incorrect
In step 5 the path of the log file is documented as
`grep 'node starting' _cockroach-data/roach1/logs/cockroach.log_ -A 11`

## Suggested Resolution 
The log file is in path cockroach-data/logs/cockroach.log

**Comment by jseldess** [comment]
@taroface, I just reproduced this. The current `grep` command doesn't work. Neither does the recommended correction. We need to investigate further.

**Comment by lin-crl** [comment]
The following command worked for me. Hope it helps!

grep 'node starting' cockroach-data/logs/cockroach.log -A 11

**Comment by jseldess** [comment]
We recently switched to using docker volumes, so that doesn't work with the current instructions since we lost direct access to the files. We need to run the `grep` inside the container with `docker exec` or `docker logs`.

**Comment by jseldess** [comment]
@taroface, just opened a PR to fix this. Please review.
