### ISSUE TITLE
Update kubernetes docs for 1.5

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#932]
In kubernetes 1.5, PetSets have been renamed to StatefulSets; we should update our docs accordingly.

http://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/

**Comment by a-robinson** [comment]
The biggest difference is that it's now usable on all clusters (rather than only on clusters with alpha features enabled). I'll check out what else has changed this week.

**Comment by jseldess** [comment]
OK, thanks, @a-robinson.
