### ISSUE TITLE
Working with Spatial Data Doc Update - Broken link

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/docs#9320]
Re: [Working with Spatial Data](https://cockroachlabs.com/docs//v20.2/spatial-data.html)

## Issue Description

The link to the [tornado start points data set](https://www.spc.noaa.gov/gis/svrgis/zipped/1950-2018-torn-initpoint.zip) is broken.

## Suggested Resolution 

They updated the link to <https://www.spc.noaa.gov/gis/svrgis/zipped/1950-2019-torn-initpoint.zip>

**Comment by rmloveland** [comment]
Thanks @fabiog1901 - I have emailed the folks who run https://www.spc.noaa.gov/gis/svrgis/ and asked if they will replace the old file.  If they can't, I'll update this ASAP!
