### ISSUE TITLE
Clarify whether assistance support includes security patches

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#9323]
On our [release support policy page](https://www.cockroachlabs.com/docs/releases/release-support-policy.html), we outline the different levels of support we offer for CockroachDB releases. It is not currently clear from this page whether we will continue to offer security patches for releases in the "assistance support" window. We should add a bullet that indicates that we _do_ still offer critical security fixes to all releases in the support window, including releases in the "assistance support" window.

**Comment by KapedRebooster** [comment]
Yes
