### ISSUE TITLE
v20.2/upgrade-cockroach-version.md: note regarding schema changes

### ISSUE THREAD

**Issue by nick-jones** [cockroachdb/docs#9333]
In the `v20.1` documentation we are explicitly warned that schema changes will be blocked and return an error whilst the upgrade is not finalized: https://github.com/cockroachdb/docs/blob/master/v20.1/upgrade-cockroach-version.md#review-temporary-limitations - it also indicates this restriction only applies to this version (`Note that these limitations are specific to upgrades from v19.2 to v20.1; they do not apply to other upgrades.`)

The v20.2 doc makes no such assertions around schema changes being blocked and returning an error, so my assumption is this no longer a restriction. However the doc still states under Step 5: (https://github.com/cockroachdb/docs/blob/master/v20.2/upgrade-cockroach-version.md#step-5-finish-the-upgrade)

> If you disabled auto-finalization in step 3, monitor the stability and performance of your cluster for as long as you require to feel comfortable with the upgrade (generally at least a day) and remember to prevent new schema changes and changes to user privileges. If during this time you decide to roll back the upgrade, repeat the rolling restart procedure with the old binary.

This seems to be slightly contradictory - and given this is the only reference to this, it's a bit late in the document to be indicating this. Feels like this either needs removing or adjusting to be a bit clearer of what is being suggested here?

**Comment by lnhsingh** [comment]
@taroface I _think_ this falls under Deployments & Operations but feel free to re-assign / re-tag.

**Comment by nick-jones** [comment]
This ended up being fixed as part of https://github.com/cockroachdb/docs/pull/9827
