### ISSUE TITLE
Add security risk section to CockroachCloud connection docs

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#9336]
![image](https://user-images.githubusercontent.com/21692034/104631871-dd0beb00-566a-11eb-9eb4-8024b3043c64.png)
In the CockroachCloud connection modal, we specifically call out the security risks of setting `ssl-mode=require` and link to our docs to learn more. The link, however, is only to the [generic connection modal docs](https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster.html). Instead we should add a section that explains the risks of different `ssl-mode` settings and link directly to that. For an example of existing docs, [postgres has a great table](https://www.postgresql.org/docs/current/libpq-ssl.html) that we may be able to reuse:

![image](https://user-images.githubusercontent.com/21692034/104645369-f453d400-567c-11eb-98cd-63dfe35c45e6.png)

**Comment by piyush-singh** [comment]
@aaron-crl - Gemma is picking up this issue and asked if we want to share the full set of SSL modes listed in the issue above. My suggestion is to only include `require` and `verify-full` for now because anything weaker than `require` we almost certainly don't want to recommend, and users will get most of the UX benefit by dropping to `require` (not having to specify a cert). I'm less certain about `verify-ca` though, I don't know if that is something we should include in the docs. What are your thoughts?

**Comment by aaron-crl** [comment]
I think `require` and `verify-full` are appropriate. `verify-ca` should be avoided in the managed service context.

From pg: "If a public CA is used, `verify-ca` allows connections to a server that somebody else may have registered with the CA. In this case, `verify-full` should always be used."

More practically, if we're trusting public root stores, **any** validly issued certificate for **any** site will satisfy `verify-ca`, even if the hostname does not match. That's essentially equivalent to `require`.
