### ISSUE TITLE
ADD COLUMN statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#934]
Complete reference documentation for the `ALTER TABLE .. ADD COLUMN` statement.

**Intro**, **Required Privileges**, and **Synopsis** are complete. We need to complete **Parameters** and **Examples**. For style reference, see those sections in [INSERT](https://www.cockroachlabs.com/docs/insert.html) or [DELETE](https://www.cockroachlabs.com/docs/delete.html).

More reference:

- https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_table.go
- https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/testdata/alter_table
- PostgreSQL: https://www.postgresql.org/docs/9.6/static/sql-altertable.html
- MySQL: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html

**Comment by sploiselle** [comment]
@jseldess ping! Did anyone submit viable content for this page? @andreimatei noticed it doesn't have details about constraints inline, which is confusing.

**Comment by jseldess** [comment]
Yes! I think Amruta's content was great. This could be a good starter PR for her.

**Comment by jseldess** [comment]
@Amruta-Ranade, assigning this to you! Please let us know if you have any questions as you get started. The relevant file is `add-column.md`.
