### ISSUE TITLE
Cluster regions can be added, removed, displayed

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#9341]
Jira issue: https://cockroachlabs.atlassian.net/browse/CRDB-1544

Related issues:

- [x] #9095
- [x] #9113
- [x] #9124
- [x] #9308
- [x] #9564
- [x] #9600

**Comment by rmloveland** [comment]
This one is done.  Flags on `cockroach start` are there, and all the SQL syntax is there - see linked issues for syntax details (h/t @ericharmeling )
