### ISSUE TITLE
Logging channels and configurability

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9344]
This issue tracks the broad docs effort to document the new 21.1 logging channels and configuration functionality.

We need to fill in the broad pieces of work here. In the meantime, we call out specific notes/gotchas that were called out during acceptance testing

- [ ] Clarify that `cockroach-stderr.log` is a catchall for non-logging events ([comment](https://github.com/cockroachdb/cockroach/issues/58968#issuecomment-760368202))
- [ ] Clarify that unlisted channels get grouped in with a sink listing DEV channel events ([comment](https://github.com/cockroachdb/cockroach/issues/59048))

**Comment by taroface** [comment]
cc @mikeCRL

**Comment by taroface** [comment]
Related: https://github.com/cockroachdb/docs/issues/7202

**Comment by taroface** [comment]
Closed by #10273.
