### ISSUE TITLE
missing flag --clock-device in documentation

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/docs#9347]
This githb issue was created from ZD 7275 opened by @cleeistaken

Issue: Cockroach 20.1 introduces a new flag (--clock-device) to allow time synchronization with a Precision Clock device as outlined in the release notes at https://www.cockroachlabs.com/docs/releases/v20.1.0-rc.2.html.

The release notes reference the Cockroach 20.1 start flags located at https://www.cockroachlabs.com/docs/v20.1/cockroach-start but the --clock-device flag missing.

Request: Add the --clock-device flag to the 20.1 start flags. :)

Added to the original request by @a-entin:
 
This may also be an opportunity to remove the obsolete guidance in the section https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#clock-synchronization. 

The last paragraph talks about VM migration by a hypervisor and recommends setting  `server.clock.forward_jump_check_enabled`. This guidance is obsolete since 20.1 CRDB that implements the complete support of the VMware platform with the use of --clock-device. Further, during QA/validation we found that enabling `server.clock.forward_jump_check_enabled` causes unnecessary disruptions during vMotion and therefore is counterproductive.
Please remove the entire last paragraph, including the recommendation to use `server.clock.forward_jump_check_enabled`

**Comment by jseldess** [comment]
cc @taroface, @mikeCRL. 

@a-entin, this could be part of the conversation around urgent updates to the production checklist, but I think there have also been recent related conversations about this with @bdarnell and CC SREs like @joshimhoff, so I'm not sure where we landed.

**Comment by a-entin** [comment]
The recent conversation was in the related area yet on a different topic - a possibility of stale reads (break in ACID guarantees). This setting (`server.clock.forward_jump_check_enabled`) does nothing to address that issue, yet can cause an unnecessary disturbance in the cluster. The recommendation to remove the paragraph, as originally suggested in the ticket, did not change in light of the recent conversation.
