### ISSUE TITLE
Serializable Transactions Doc Update 

### ISSUE THREAD

**Issue by tbg** [cockroachdb/docs#9349]
Re: [Serializable Transactions](https://cockroachlabs.com/docs//v20.2/demo-serializable.html)

## Issue Description

The TOC links for the CockroachDB sections link into the Postgres section.

## Suggested Resolution 

Fix the TOC links for the CRDB section.

**Comment by tbg** [comment]
Also look at the toc highlighting, I guess the anchor ids are just the same? 
![image](https://user-images.githubusercontent.com/5076964/104891455-43498400-5971-11eb-802a-307e2e990e58.png)

**Comment by jseldess** [comment]
Ah, yes. When there are two identical headings on a page, the TOC link uses the first. This is annoying. We need to change the way the site identifies anchor links. But for now, I can find a hack.
