### ISSUE TITLE
misleading summary of a graphic in "make queries fast"

### ISSUE THREAD

**Issue by Lukens4242** [cockroachdb/docs#9354]
David Lukens (lukens4242) commented:

In [this page](https://www.cockroachlabs.com/docs/v20.2/make-queries-fast.html), when the initial query is done to get the top 10 riders, the graphic shows that the server execution time was 103.41ms.  The text below it says that it took 160ms.  These two should be in agreement with each other.

_Unfortunately, this query is a bit slow. 160 milliseconds puts us over the limit where a user feels the system is reacting instantaneously, and we're still down in the database layer. This data still needs to be shipped back out to your application and displayed to the user._

The threshold for a human noticing a non-instantaneous transaction is around 100ms, which the graphic says we are near.  To use this as an example, you may want to artificially slow the query for the exercise.

Later on in the same page, the 160ms figure is referenced again: _This query is now running much faster than it was before we added the indexes (160ms vs. 25ms). This means we have an extra 135 milliseconds we can budget towards other areas of our application._

Jira Issue: DOC-908

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
