### ISSUE TITLE
differing queries on "make queries fast"

### ISSUE THREAD

**Issue by Lukens4242** [cockroachdb/docs#9355]
David Lukens (lukens4242) commented:

On [this page](https://www.cockroachlabs.com/docs/v20.2/make-queries-fast.html), the queries and their output change through the exercise.

The first query to get the top 10 riders is from the end of 2018 through to the start 2020.  The top rider is William Brown with 14 rides.
The explain below it is from the end of 2018 through to the start of 2019 (a year different).
After creating the indexes, the query is from the end of 2018 through the start of 2019 (different than the first query).  The top rider is William Brown with 6 rides.
The 2nd explain is only through the start of 2019.

In order to be clearer, all of the queries and explains need to be using the same date ranges.  The output from the queries should match each other.

Also, when displaying the tests of a merge join, the comment is made: _The results are consistently about 31-35ms with merge join vs. 25-27ms when we let CockroachDB choose the join type as shown in the previous section._
The two images that are shown just before this to illustrate the point are 23.5ms and 31.3ms.  Those numbers do not agree with the text below them.

Jira Issue: DOC-909

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
