### ISSUE TITLE
Hardcoded and broken links on landing pages

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9363]
Some of the links need to be made relative. Some of the links result in 404s. Probably should check all links. Jesse's PR to Peter's redesign branch fixed these a week or two ago-- can we find that commit?

https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/

**General Landing Page**
- `/tutorials/learn-cockroachdb-sql-interactive` should be `docs/tutorials/learn-cockroachdb-sql-interactive`
- `/tutorials/build-a-python-app-with-cockroachdb-interactive` should be `docs/tutorials/build-a-python-app-with-cockroachdb-interactive`
- `/tutorials/demo-json-support-interactive` should be `docs/tutorials/demo-json-support-interactive`
- `/docs/orchestrate-cockroachdb-with-kubernetes-multi-cluster` should be `/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html`
- `/docs/transaction-retry-error-reference.html` should be `/docs/stable/transaction-retry-error-reference.html`
- Start a Cloud Cluster is `/cockroachcloud/quickstart.html` but should be `/docs/cockroachcloud/quickstart.html`
- Start a Local Cluster is `/docs/secure-a-cluster.html` but should be `/docs/stable/secure-a-cluster.html`
- Sample Apps card at top should be "Start a local cluster"
- CockroachDB FAQ card should be "Sample apps" and link to `/docs/stable/hello-world-example-apps.html`

**CRDB Landing Page**
- Title on first card should be "Start a local cluster" and should link to `/docs/stable/start-a-local-cluster`
- Update Sample Apps card link to `/docs/stable/hello-world-example-apps.html`

**CC Landing Page**
- Under Recommended articles, the Stream a Changefeed link should be `/docs/cockroachcloud/stream-changefeed-to-snowflake-aws.html` (there's currently a misspelling)

**Comment by lnhsingh** [comment]
This LGTM - one thing I noticed is that the links under the CRDB landing page's Recommended Articles section all link to `/v20.2/` versions of the docs. Is that on purpose? We might want to link to the `/stable/` version so we don't have to manually update those link each release. This edit could be done later though (I can open a new issue for it if we want)

**Comment by jseldess** [comment]
The CRDB landing page is version-specific. For example, there's an `index.md` in `v20.2`, another in `v21.1`. So the recommended article links on those pages are relative, that is, they point to the page for the current version. It's unfortunate that we have to do this, but if we hard code the CRDB landing page to be the same across all versions, it's going to create a very frustrating UX. Imagine that you're looking at a SQL reference page for 21.1, you click "CockroachDB" in the sidenav, and then you click a recommended article. If the links points to stable, the version context will be switched for you.

I think it's worth revisiting the CRDB landing page approach post-launch. Would you mind opening an issue for that, @lnhsingh?
