### ISSUE TITLE
Broken link on CC docs landing page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9364]
https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/index.html

The "Stream a Changefeed" link has a typo in it: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/dstream-changefeed-to-snowflake-aws.html

**Comment by lnhsingh** [comment]
Closing in favor of #9363
