### ISSUE TITLE
Differentiate hover and active state for tabs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9366]
On a page with tabs, when you hover over the tab directly next to the active tab, there's no visual padding between the tabs, which looks kind of confusing. 

![Screen Shot 2021-01-20 at 10 37 49 AM](https://user-images.githubusercontent.com/15893490/105198559-c30b5600-5b0b-11eb-99ab-22923ad43569.png)

cc @luciaaaaaaa

**Comment by jseldess** [comment]
Styling is better for smaller on-page tabs, btw: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/stable/install-client-drivers.html

![Screen Shot 2021-01-20 at 10 49 01 AM](https://user-images.githubusercontent.com/15893490/105199845-3c577880-5b0d-11eb-8358-bc77cd7ad44b.png)

**Comment by luciaaaaaaa** [comment]
@jseldess I think its okay for tabs not to have padding, but the selected tab should be highlighted by making the text also purple. this way it is very clear which tab is selected vs. on hover. 

 reference: https://material.io/components/tabs/web 

However it should be consistent everywhere

**Comment by jseldess** [comment]
But in the materialize example, the text color changes and the background color changes. Without that background change, I find our design not clear. Again, unless there's some padding between tabs. 

This page shows the type of padding I'm talking about, and I think it looks fine: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/stable/install-client-drivers.html. 

Can you please clarify exactly what the design should be and help make sure it's applied everywhere?

**Comment by luciaaaaaaa** [comment]
I see what you mean @jseldess 

just discussed with @anagio. We want to avoid the gap between the tabs so that eventually tabs can slide to selected option. This is a nice micro-interaction that tabs usually employ

The issue is that currently the hover and selected state look exactly the same. To address this I propose: 

Hover state: Text in purple 
Active state: Text in purple and tab

**Comment by lnhsingh** [comment]
More feedback on tabs within content: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1612804229114400

It seems like the feedback here is that there isn't enough of a visual differentiation between the tabs and the rest of the text (example in step 2): 
![image](https://user-images.githubusercontent.com/15386648/107261575-77164780-6a0d-11eb-8d31-247b14daa087.png)

@luciaaaaaaa - I think your proposed changes (active state = purple text + tab) might help here but maybe we need more top padding too?

**Comment by jseldess** [comment]
@luciaaaaaaa, can you please clarify what you mean here for active state? What should the tab look like? Some background color? 

> Hover state: Text in purple
> Active state: Text in purple and tab

**Comment by luciaaaaaaa** [comment]
Hi, here are wireframes with proposed changes 

https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=4105%3A8047
