### ISSUE TITLE
Numbered and bulleted list color is hard to see

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9368]
Numbers and bullets in lists are colored light grey, which is harder to see that I'd prefer. 

![Screen Shot 2021-01-20 at 10 39 54 AM](https://user-images.githubusercontent.com/15893490/105198764-ffd74d00-5b0b-11eb-8b47-8c99bd2c8439.png)

cc @luciaaaaaaa

**Comment by luciaaaaaaa** [comment]
lets update to #7E89A9
