### ISSUE TITLE
Download icons on release notes look like tabs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9371]
Example: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/releases/v20.2.3.html#downloads

On the live site, I think these are using the same styling as tab "buttons". That's confusing, but the news styling, as explicit tabs, is even more confusing. I think we need to redesign these so it's clear they are downloads. 

![Screen Shot 2021-01-20 at 10 44 48 AM](https://user-images.githubusercontent.com/15893490/105199420-bd624000-5b0c-11eb-93fe-639b202060ff.png)

cc @luciaaaaaaa

**Comment by luciaaaaaaa** [comment]
These should be secondary buttons (outlined)  I think we are using the wrong component here

**Comment by lnhsingh** [comment]
Related to #9378.

"Run this in your browser" buttons also look like tabs.

**Comment by luciaaaaaaa** [comment]
Styling: Secondary button with hover state https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=3254%3A11908

**Comment by luciaaaaaaa** [comment]
pending fix: remove the external icon from buttons ![image](https://user-images.githubusercontent.com/48258790/106147841-56fda300-6146-11eb-9d33-5d6939ad977d.png)

**Comment by lnhsingh** [comment]
This looks like it's fixed now but I'm noticing there's a grey line that I'm not sure should be there? Or it should span the whole width, like it does in Lucia's screenshot

![image](https://user-images.githubusercontent.com/15386648/106178026-43166900-6167-11eb-8d7d-398082bafe04.png)

**Comment by anagio** [comment]
removing the line
