### ISSUE TITLE
No visual indication of external links

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9374]
This is something that I thought Vlad put in place for us. External links to have a visual indication. That seem to have gotten lost?

For example, in the following screenshot, several links should be marked as external and open in a new tab:

![Screen Shot 2021-01-20 at 10 50 31 AM](https://user-images.githubusercontent.com/15893490/105200072-6f9a0780-5b0d-11eb-8f0a-b64b909c5708.png)

**Comment by luciaaaaaaa** [comment]
On this one we still need to update the icon color, this is not a blocker but should be tracked
