### ISSUE TITLE
Some first-level lists are not styled right

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9375]
In addition to sub-bullets missing styling (https://github.com/cockroachdb/docs/issues/9373), some first-level bullets and numbered lists don't seem to be styled correct. Their font size is larger than the rest of the text.

Examples: 
- Numbered list: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/quickstart
- Bulleted list:https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/v20.2/developer-guide-overview.html

**Comment by lnhsingh** [comment]
Closing in favor of #9389
