### ISSUE TITLE
h4 headers are hard to distinguish

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9377]
They are quite small and don't really stand out from the paragraph text.

Example: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/v20.2/architecture/sql-layer.html#parsing

![Screen Shot 2021-01-20 at 11 04 21 AM](https://user-images.githubusercontent.com/15893490/105201855-55612900-5b0f-11eb-858e-66de4c041d76.png)

**Comment by jseldess** [comment]
![Screen Shot 2021-01-20 at 11 21 36 AM](https://user-images.githubusercontent.com/15893490/105203962-b1c54800-5b11-11eb-9203-82b27e264787.png)

**Comment by lnhsingh** [comment]
Related: #9387

**Comment by lnhsingh** [comment]
@luciaaaaaaa - can you add a H4 to Figma? I'd like to get this fix into the release, if possible!

**Comment by anagio** [comment]
I just increased font size, and weight for now on h4
![image](https://user-images.githubusercontent.com/1071553/106230649-8d105500-6222-11eb-9d77-6c459c170a43.png)
