### ISSUE TITLE
"Run this in your browser" looks like a tab

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9378]
The "Run this in your browser" element that opens a Katacoda tutorial in a new tab doesn't look like a CTA; it looks like an on-page tab.

Example: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/v20.2/learn-cockroachdb-sql.html

![Screen Shot 2021-01-20 at 11 06 19 AM](https://user-images.githubusercontent.com/15893490/105202208-b983ed00-5b0f-11eb-90b3-16d9e6d5a106.png)

**Comment by lnhsingh** [comment]
This might require docs to update the content to use a different style. Lauren to look into

**Comment by luciaaaaaaa** [comment]
Closed in favor of [Download icons on release notes look like tabs #9371](https://github.com/cockroachdb/docs/issues/9371)

**Comment by jseldess** [comment]
@luciaaaaaaa, can you please comment on that other issue so it's clear that it applies to both download icons and run this in your browser CTAs?
