### ISSUE TITLE
Docs footer is different than marketing site footer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9382]
Is this by design?

Docs: 

![Screen Shot 2021-01-20 at 11 20 16 AM](https://user-images.githubusercontent.com/15893490/105203817-88a4b780-5b11-11eb-8f39-4e843b5d1528.png)

Marketing:

![Screen Shot 2021-01-20 at 11 20 52 AM](https://user-images.githubusercontent.com/15893490/105203851-935f4c80-5b11-11eb-9903-c0f2bcda9776.png)

**Comment by luciaaaaaaa** [comment]
This is by design. Marketing agreed it was okay to have a different footer to display more links and a sign up field, but @anagio can you please confirm with Sami?
