### ISSUE TITLE
Scroll bar styling for sidenav

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9383]
When the sidenav does not require scrolling, there's still a somewhat thick scrollbar indication, which feels unnecessary to me. I think visual aspects of the scroll bar should appear only when needed. @luciaaaaaaa, thoughts?

![Screen Shot 2021-01-20 at 11 25 26 AM](https://user-images.githubusercontent.com/15893490/105204622-61021f00-5b12-11eb-927c-bc90d53aa8cd.png)

**Comment by lnhsingh** [comment]
This is something that came up awhile ago when Vlad was working on the sidenav I think (I see this too). It has to do with a setting on your Mac, so some users don't see this. 

![Screen Shot 2021-01-20 at 12 17 40 PM](https://user-images.githubusercontent.com/15386648/105210873-9d854900-5b19-11eb-84dc-ca874423e13e.png)

If you switch to "When scrolling", the scrollbar indication won't display.

**Comment by jseldess** [comment]
Thanks, @lnhsingh! That did the trick. I'll close this.
