### ISSUE TITLE
Monospaced text breaks the styling of the page TOC

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9384]
Example: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/v20.2/sql-faqs.html

![Screen Shot 2021-01-20 at 11 27 27 AM](https://user-images.githubusercontent.com/15893490/105204854-9149bd80-5b12-11eb-880f-9393a7794786.png)

**Comment by lnhsingh** [comment]
Closing in favor of #9381
