### ISSUE TITLE
Tooltip styling on DB comparison page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9385]
https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/v20.2/cockroachdb-in-comparison.html

It's very hard to read the tooltips:

![Screen Shot 2021-01-20 at 11 28 37 AM](https://user-images.githubusercontent.com/15893490/105204981-ba6a4e00-5b12-11eb-8b33-fa2b9a44489e.png)

**Comment by anagio** [comment]
Fixed default styling, @luciaaaaaaa let me know if colors need to be changed or anything else.
![image](https://user-images.githubusercontent.com/1071553/105801784-7a9cde00-5fcc-11eb-80d9-4231d5413f24.png)
