### ISSUE TITLE
Hover and active color for monospaced text in sidenav

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9386]
When you hover over something monospaced in the sidenav (e.g., a SQL statement), the hover color is blue. Is that right?

![Screen Shot 2021-01-20 at 11 30 15 AM](https://user-images.githubusercontent.com/15893490/105205243-06b58e00-5b13-11eb-98e4-9372eefda537.png)

Also, when you're on such a page, the item in the sidenav isn't purple to indicate it's active:

![Screen Shot 2021-01-20 at 11 31 38 AM](https://user-images.githubusercontent.com/15893490/105205278-146b1380-5b13-11eb-9447-6a92f6627f5c.png)

**Comment by lnhsingh** [comment]
Hover/ selected monospace in sidenav should be purple
