### ISSUE TITLE
no h4 styling

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9387]
There doesn't seem to be styling for h4 headers. This makes them look like body text.

Below, `#### Use the CockroachDB SQL client`

![image](https://user-images.githubusercontent.com/8740013/105208880-31a1e100-5b17-11eb-8e56-3787cc5af4f3.png)

(from https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/user-authorization)

**Comment by lnhsingh** [comment]
Thanks for filing! Closing this issue but linking to #9377
