### ISSUE TITLE
inconsistent formatting on ordered lists

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9388]
The first item in the list below (from https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/user-authorization) has inconsistent formatting vs. the rest of the list.

![image](https://user-images.githubusercontent.com/8740013/105209411-cb698e00-5b17-11eb-8ddc-58ad875729b0.png)

**Comment by luciaaaaaaa** [comment]
Closing in favor of [A lot of different fonts used #9428](https://github.com/cockroachdb/docs/issues/9428)
