### ISSUE TITLE
text is large in unordered lists

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9389]
It looks incongruous with the regular body text. I think the text in the ordered lists looks fine.

Also, the line spacing between each list item seems a little big? On the current design the list spacing seems identical to body spacing. On the new design, list spacing looks approx. double the body spacing.

![image](https://user-images.githubusercontent.com/8740013/105209758-33b86f80-5b18-11eb-9814-f074d902aa37.png)

(from https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/stable/orchestrate-cockroachdb-with-kubernetes.html)

**Comment by taroface** [comment]
This still looks the same to me on Chrome and Firefox, e.g.:

![image](https://user-images.githubusercontent.com/8740013/108866194-f7b67580-75c1-11eb-83a9-4d7b2f97d772.png)

The spacing between the body text and unordered list also looks like it has been reduced. Should the issue be reopened?

**Comment by lnhsingh** [comment]
Reopening this issue - there's another issue for spacing opened (#9849)
