### ISSUE TITLE
links to toggle pages don't work

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9390]
Previously, we could append an anchor to the url to directly access a page under a toggle button.

This link: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/stable/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#eks (which I believe is used in existing docs)

should open 

![image](https://user-images.githubusercontent.com/8740013/105211893-c4904a80-5b1a-11eb-936b-88c456774560.png)

But on the staging site, it still opens the default GKE toggle. Not sure if this is just a staging site problem.

**Comment by jseldess** [comment]
This is working for me, @taroface. Can you please test again?

**Comment by taroface** [comment]
Yes, working for me now! Closing the issue.
