### ISSUE TITLE
toggle styling is unclear

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9391]
The selected toggle is a bit subtle and I worry that people might get momentarily confused which option is selected. 

The current toggle is a colored box and the text is bold. This is very clear.

Maybe the active text on the new toggle design can be bold? Ideally I feel like there could also be a background color.

![image](https://user-images.githubusercontent.com/8740013/105212023-edb0db00-5b1a-11eb-8a46-0623e63ec8ee.png)

**Comment by lnhsingh** [comment]
Closing in favor of #9366
