### ISSUE TITLE
top spacing for unordered lists

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9395]
Unordered lists may need more top padding. Not sure if this is only an issue when directly under a set of toggles:

![image](https://user-images.githubusercontent.com/8740013/105219458-7aac6200-5b24-11eb-86be-88a43f04a4e8.png)

**Comment by jseldess** [comment]
Solved by https://github.com/cockroachdb/docs/pull/9963 and https://github.com/cockroachdb/docs/pull/9958

See https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#file-descriptors-limit
