### ISSUE TITLE
Add note to "Stream a Changefeed to Snowflake" tutorial

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#9396]
Add a bullet to the "Known Limitations Section" along the lines of:
- Snowpipe works best with append-only workloads. Snowpipe lacks native ETL capabilities to perform updates to the data. You may need to do pre-processing of the data before uploading to Snowflake.

**Comment by ericharmeling** [comment]
This is a limitation of Snowflake, and not CRDB. As a result, I'm going to leave it out of the Known Limitations proper page, and just added it to the Stream a Changefeed to Snowflake, as you suggest.
