### ISSUE TITLE
h2 styling is a little big

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9401]
h2 text could be a little big for certain pages that use many h2s:

![image](https://user-images.githubusercontent.com/8740013/105222328-5d799280-5b28-11eb-9861-280849b2e239.png)

(from https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/stable/common-errors.html)

**Comment by jseldess** [comment]
The current styling matches the designs that @luciaaaaaaa put in place:

<img width="257" alt="Screen Shot 2021-03-09 at 5 15 04 PM" src="https://user-images.githubusercontent.com/15893490/110545373-00976300-80fb-11eb-9cfd-78a555bf01de.png">

I'll close this for now, but @luciaaaaaaa please re-open if you think the docs don't, in fact, match your designs here, or if you think we need to revisit the header sizing hierarchy.
