### ISSUE TITLE
Prominent buttons are missing hover states

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9404]
**Observations**
* The `Get CockroachDB` button in the nav bar is missing a hover state 
* The `Get CockroachDB` CTA ([here](https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/stable/index.html)) and `Start A Free Cluster` CTA ([here](https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/index.html)) buttons are missing a hover state
* The buttons for "Was this page helpful? 👍  👎 " should have a hover state

However, notice how within the footer the `Subscribe` btn on the right hand side has a hover state

**Comment by luciaaaaaaa** [comment]
Additional notes: 

- Issue: Font weight doesnt match style in the marketing site. Font weight should be regular
-  Also, on buttons, the color is showing on the right/left margin
