### ISSUE TITLE
Fonts appear inconsistent between <p> and <li> tags

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9405]
* Fonts look inconsistent depending on if the text appears in `<p></p>` tags or `<li></li>`. It makes the reading experience feel a bit off, like we're missing polish/consistency.
<img width="1399" alt="Image 2021-01-20 at 6 00 43 PM" src="https://user-images.githubusercontent.com/1474303/105251521-b148a380-5b49-11eb-9514-a5cca86ffcfb.png">
 tags.

**Comment by lnhsingh** [comment]
Closing in favor of #9428
