### ISSUE TITLE
Hovering over table of content text sometimes causes it to spill over to 2-lines

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9407]
* At certain browser widths, the right-hand-side table of contents text would flow to the next line when hovering over the text (see Step 1 and Step 5 [here](https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/quickstart.html))
![Screen Recording 2021-01-20 at 06 03 PM](https://user-images.githubusercontent.com/1474303/105251732-0edcf000-5b4a-11eb-8fdb-b832db108e95.gif)

**Comment by lnhsingh** [comment]
Closing in favor of #9444
