### ISSUE TITLE
Inconsistent color for links - blue or purple

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9408]
This is more of a nit/question: Are links supposed to blue or purple? I notice purple across the board in navbar and footers. However, the body would reveal blue links. For example, in https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/cockroachcloud/quickstart.html the quicklinks to a subheader and individual links are blue.

Is this intentional?

![Screen Recording 2021-01-20 at 06 09 PM](https://user-images.githubusercontent.com/1474303/105252013-a17d8f00-5b4a-11eb-800b-23a3ca3a8723.gif)

**Comment by lnhsingh** [comment]
We decided that links in navs / footer are grey (purple when selected) and links in content are blue. This is a design choice (otherwise we think there would be too much purple)
