### ISSUE TITLE
Redundant underline for version dropdown menu hover state

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9412]
Is an underline necessary here in the version dropdown menu? The menu already darkens on hover - the underline seems extraneous. 

FWIW the GH `Contribute` button doesn't underline the text upon hover. 

![Screen Recording 2021-01-20 at 06 15 PM](https://user-images.githubusercontent.com/1474303/105253225-12be4180-5b4d-11eb-8bec-165b8b006042.gif)

**Comment by luciaaaaaaa** [comment]
Underline is not nessesary. @anagio we can remove
