### ISSUE TITLE
CC quickstart: Copying binary into the PATH

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9416]
https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html#step-3-use-the-built-in-sql-client

If you choose `homebrew`, the next step about copying the binary into the PATH is empty:

<img width="824" alt="Screen Shot 2021-01-20 at 8 17 43 PM" src="https://user-images.githubusercontent.com/15893490/105260965-c4b13a00-5b5c-11eb-9cfd-5f7eb7473dc5.png">

**Comment by lnhsingh** [comment]
Closed by https://github.com/cockroachdb/docs/pull/9400
