### ISSUE TITLE
Body font looks like different font form 'list item' font 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/docs#9422]
Body font looks like different font form 'list item' font (see highlighted text below in screenshots)

<img width="1393" alt="Screen Shot 2021-01-21 at 11 19 42 AM" src="https://user-images.githubusercontent.com/51920721/105379218-9f631100-5bda-11eb-81c7-12217e3bd185.png">
<img width="1393" alt="Screen Shot 2021-01-21 at 11 19 58 AM" src="https://user-images.githubusercontent.com/51920721/105379232-a38f2e80-5bda-11eb-869f-abe4e562f76d.png">

**Comment by luciaaaaaaa** [comment]
Closing in favor of  [#9428](https://github.com/cockroachdb/docs/issues/9428)
