### ISSUE TITLE
Light gray font may not be readable 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/docs#9423]
The main left nav, the index menu on the right, and the numbers in numbered lists use a light gray font that may not meet accessibility standards (looks very light)
 
<img width="198" alt="Screen Shot 2021-01-21 at 11 38 46 AM" src="https://user-images.githubusercontent.com/51920721/105381792-611b2100-5bdd-11eb-87a2-3202d20bfee5.png">

<img width="264" alt="Screen Shot 2021-01-21 at 11 14 58 AM" src="https://user-images.githubusercontent.com/51920721/105379298-b0138700-5bda-11eb-8257-82067f05be59.png">
<img width="1026" alt="Screen Shot 2021-01-21 at 11 14 13 AM" src="https://user-images.githubusercontent.com/51920721/105379325-b6096800-5bda-11eb-875a-3dd27323566b.png">

**Comment by lnhsingh** [comment]
Closing in favor of #9424
