### ISSUE TITLE
A lot of different fonts used 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/docs#9428]
Looks like we are using Poppins, Source Sans Pro, apple system font and AvenirLTStd-Roman (plus SourceCodePro for code snippits). Seems like we could limit those four to 1 or two different fonts?

<img width="1393" alt="Screen Shot 2021-01-21 at 11 24 09 AM" src="https://user-images.githubusercontent.com/51920721/105380305-b9e9ba00-5bdb-11eb-91f2-57614538ec7d.png">
<img width="1393" alt="Screen Shot 2021-01-21 at 11 24 21 AM" src="https://user-images.githubusercontent.com/51920721/105380320-be15d780-5bdb-11eb-9e09-e3898de1819a.png">
<img width="1393" alt="Screen Shot 2021-01-21 at 11 24 36 AM" src="https://user-images.githubusercontent.com/51920721/105380325-be15d780-5bdb-11eb-98a9-2a592d4ee2b2.png">
<img width="1393" alt="Screen Shot 2021-01-21 at 11 25 16 AM" src="https://user-images.githubusercontent.com/51920721/105380329-beae6e00-5bdb-11eb-89e3-78ba11bb13ff.png">
<img width="1393" alt="Screen Shot 2021-01-21 at 11 25 30 AM" src="https://user-images.githubusercontent.com/51920721/105380330-bf470480-5bdb-11eb-8939-7e2dbb6cbdbe.png">

**Comment by lnhsingh** [comment]
Should only be using Poppins, Source Sans Pro

This might fix the other font discrepancies.
