### ISSUE TITLE
Top Nav height increases when I scroll down 

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9432]
Issue: The top nav height increases when I scroll down. This behaviour does not occur on the marketing site. 

Fix: Height of the top nav should not change 

I have a reference video which was too big to upload here. Will post into Slack 

![image](https://user-images.githubusercontent.com/48258790/105380519-f9180b00-5bdb-11eb-9384-776a4b68c26a.png)

**Comment by lnhsingh** [comment]
Related to #9434

**Comment by anagio** [comment]
sent a fix to make sidebar and top navs all go mobile at the same time.
