### ISSUE TITLE
Menu navigation arrows in the left nav are confusing  

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/docs#9433]
Arrows in left nav are confusing and makes it difficult to know if there are more items within a section.

I think when a section is closed they should be facing right, when a section is open the should face down (similar to how the Mac Finder works).

<img width="257" alt="Screen Shot 2021-01-21 at 11 41 56 AM" src="https://user-images.githubusercontent.com/51920721/105382375-00401880-5bde-11eb-927b-bbb3e22803b4.png">

<img width="241" alt="Screen Shot 2021-01-21 at 11 46 25 AM" src="https://user-images.githubusercontent.com/51920721/105382679-5614c080-5bde-11eb-86bb-fdebc6bd64bb.png">

**Comment by jseldess** [comment]
@luciaaaaaaa, I tend to agree with @Annebirzin  here, but I'm not sure if the up/down direction is an explicit part of our broader design system? How do we handle this in our UI products?

**Comment by luciaaaaaaa** [comment]
@jseldess Here are wires reflecting the changes that @Annebirzin proposed. I think its okay to go ahead and make this update
https://www.figma.com/file/gUgY9eSxcWpLENJHLS5FZv/GitHub-Issues?node-id=301%3A4264

**Comment by jseldess** [comment]
OK, just opened a PR for review.
