### ISSUE TITLE
Add spacing between page title and Docs Menu on mobile

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9436]
Issue: As the browser window scales down, components look crammed together. We need to add top, left and right padding.

Example: 
![image](https://user-images.githubusercontent.com/48258790/105383196-d9cead00-5bde-11eb-9230-426cc2ae334f.png)

Fix: (Explore 30px on side, 40px on top)  Reference wireframes, it should look similar even if the browser window is a different width https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=3791%3A7940

**Comment by jseldess** [comment]
@luciaaaaaaa, do you think this is still an issue? If so, need more input from you.

**Comment by luciaaaaaaa** [comment]
![image](https://user-images.githubusercontent.com/48258790/111654574-429d6480-87df-11eb-8528-1028730e239b.png)
Looking at it now, looks like this issue is resolved.
