### ISSUE TITLE
Global nav - sub nav click target

### ISSUE THREAD

**Issue by rsadres** [cockroachdb/docs#9440]
Seems odd to me that only part of the subnav is clickable. 
![Screen Shot 2021-01-21 at 12 02 39 PM](https://user-images.githubusercontent.com/10146234/105384759-a2f99680-5be0-11eb-9b6e-41dab37aba64.png)

I expected Build fast and build to last, familiar SQL to be one clickable area. only Familiar SQL is clickable.

**Comment by lnhsingh** [comment]
This needs to be updated in Marketing

**Comment by rsadres** [comment]
Hey! 
I'd be happy to report this to marketing. Do you know their issue process? Do they have a JIRA queue or some other issue tool?

**Comment by jseldess** [comment]
Thanks, @rsadres! According to the #website channel, you should use https://form.asana.com/?k=yNIwp6J_6KnkLGtrkpcbxg&d=380964785343490.
