### ISSUE TITLE
Loading 

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9441]
Issue: loading looks choppy both on side nav, and opening the Docs menu when the browser window is smaller. The issue is I can see part appear on the screen as they are loaded rather than as 1 UI component. 

Fix: If we need to implement a loader, I can provide mocks.  minimum fix is for loading of individual parts to happen and only show the component once all parts have been loaded. 

Reference: 
https://user-images.githubusercontent.com/48258790/105384878-bc9ade00-5be0-11eb-93b5-0c3600910e29.mov

**Comment by luciaaaaaaa** [comment]
This issue will require design work

**Comment by jseldess** [comment]
This is really about how the sidenav gets built. Closing in favor of https://github.com/cockroachdb/docs/issues/9851.
