### ISSUE TITLE
Button font style

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9443]
Issue: Font weight doesnt match style in the marketing site
![image](https://user-images.githubusercontent.com/48258790/105385724-a80b1580-5be1-11eb-8a58-1f135d8fe0d0.png)
Fix: Font weight should be regular not bold

**Comment by luciaaaaaaa** [comment]
In this screenshot you can also see how the color is showing on the right/left margin

**Comment by lnhsingh** [comment]
Closing in favor of #9404
