### ISSUE TITLE
Tweak in "Stream Data Out of CockroachDB Using Changefeeds"

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#9447]
Under "Create a core changefeed using Avro" in step 3, we instruct users to start Confluent by running: "./bin/confluent start"

This is not a valid command with current versions of confluent, tweak to:
"./bin/confluent local services start"

**Comment by amruss** [comment]
<img width="683" alt="Screen Shot 2021-01-21 at 1 40 08 PM" src="https://user-images.githubusercontent.com/13264141/105403369-4c935480-5bee-11eb-9dac-c962442c7699.png">
<img width="607" alt="Screen Shot 2021-01-21 at 1 40 28 PM" src="https://user-images.githubusercontent.com/13264141/105403374-4dc48180-5bee-11eb-96fd-a55c9225dd8d.png">

**Comment by amruss** [comment]
We might also want to add a step between 2 and 3: set environment variables
"export CONFLUENT_HOME=<path-to-confluent>"
"export PATH="${CONFLUENT_HOME}/bin:$PATH""
Because this will only work after doing so

**Comment by kathancox** [comment]
I'm pretty sure this has been taken care of with https://github.com/cockroachdb/docs/pull/11834. Feel free to reopen, if that isn't the case.
