### ISSUE TITLE
Topic Name configurability

### ISSUE THREAD

**Issue by amruss** [cockroachdb/docs#9450]
In 21.1 we added several options that give the user additional power over kafka topic naming: the ability to specify a topic prefix (already documented), the ability to use fully qualified table name.

**Fully Qualified Name**
Add option to https://www.cockroachlabs.com/docs/v20.2/create-changefeed.html#options 
- option: full_table_name
- value: N/A
- Description: Use fully qualified table name for topic creation rather than the default (table name).  EXAMPLE: "movr.public.drivers" instead of "drivers".

**Topic Creation**
The nuances of topic creation haven't been well documented, and with the new options, its probably worth it to have a section on topics. I'm not sure where the best place for this is, probably in https://www.cockroachlabs.com/docs/v20.2/create-changefeed.html#options in a new section called "Topic Naming", with the following information:

By default, a kafka topic has the same name as the table that a changefeed was created on. If a changefeed was created on multiple tables, the changefeed will write to multiple topics corresponding to those table names. You can specify a topic prefix or use the full_table_name option to modify this. 

You can either manually create the topic in your kafka cluster before starting the changefeed, or the topic will be automatically created when the changefeed connects to your kafka cluster. Note: you must have the kafka cluster setting [auto.create.topics.enable](https://kafka.apache.org/documentation/#brokerconfigs_auto.create.topics.enable) set to True for automatic topic creation. 

Kafka has the following topic [limitations](https://github.com/apache/kafka/blob/0.10.2/core/src/main/scala/kafka/common/Topic.scala#L24) :
- Legal characters: numbers, letters, and [._-]
- Maximum character length of name: 249
- Topics with a period (.) and underscore (_) can collide on internal kafka data structures, so they advise using either, but not both 
For characters not accepted by Kafka, we encode them as unicode characters.

**Comment by lnhsingh** [comment]
Relevant PRs:
- https://github.com/cockroachdb/cockroach/pull/59710
- https://github.com/cockroachdb/cockroach/pull/59258

**Comment by HonoreDB** [comment]
Slight correction: the ability to specify a topic prefix is not new; it was in our initial implementation of changefeeds. The bulk of what's new in 21.1 has to do with confluent schema registry topic naming. Without those features, it's harder to use topic_prefix with Avro because the collisions it's preventing in the main topics still occur in the schema topic.

**Comment by HonoreDB** [comment]
I've written up an internal guide to our name generation logic, configuration, and rationale [here](https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/1636958818/Sink+Names+A+u0022+Simple+u0022+Guide). Hope it's helpful in creating the public docs.

**Comment by lnhsingh** [comment]
Thanks Aaron!
