### ISSUE TITLE
Implement CC Release Notes script / process

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9456]
Up until now, CockroachCloud Release Notes have been a manual process. This can be automated similarly to [how we generate release notes for CockroachDB](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-16.Updatedocs(handledbytheDocsteam)).

For every PR in CRDB, a release note must be included (or, alternatively, "release note: none"). The guidelines for writing release notes are outlined [here](https://cockroachlabs.atlassian.net/wiki/x/ZIJ5VQ), which we would adapt for CC release notes, as CC release notes only need to highlight feature changes and bug fixes that are *user-facing*.

The script that can be adapted for CC is here: https://github.com/cockroachdb/cockroach/blob/master/scripts/release-notes.py

I think a decent amount of the script can be trimmed for CC (e.g., we don't need authors, links to PRs, not sure if we need to delineate between different product areas yet).

**Comment by laurenbarker** [comment]
Some in progress thoughts:

If the changes are behind a feature flag, we could put the flag name in the commit message. Maybe something like:
```
release note: blah

feature flag name: BlahEnabled
```

Production flags can only be flipped by SREs, so we have a record of which feature flags have been flipped in the SREOPS project. It would be straight forward to setup a filter for the last month of SREOPS tickets of type Feature Flag.
 
![Screen Shot 2021-01-26 at 2 11 55 PM](https://user-images.githubusercontent.com/7131985/105892918-77abe880-5fe0-11eb-8886-283ec35c2514.png)

**Comment by lnhsingh** [comment]
Since @gaoxk merged the [changes to the githooks](https://github.com/cockroachlabs/managed-service/pull/4727), I've adapted our release notes writing guidance for CockroachCloud contributors: https://cockroachlabs.atlassian.net/wiki/x/ZIJ5VQ

@gaoxk (and probably @petermattis and/or @laurenbarker) can you review the wiki page above? Feel free to leave comments if something needs more explanation, is wrong, etc.

The next step in this is to write the script that will scrape for all of the commit messages, right? Kristy, are you working on that as well or is someone else?

**Comment by gaoxk** [comment]
@lnhsingh The release notes writing guidance looks good to me! I would mention that when generating release notes, release notes flagged with a feature will not be included, unless the person generating the notes indicates that the feature is ready. 

I am currently working on the script [here](https://github.com/cockroachlabs/managed-service/pull/4747). I'll @ you on the PR when it's ready for review!

**Comment by gaoxk** [comment]
@lnhsingh pr is up! here's a [comment](https://github.com/cockroachlabs/managed-service/pull/4747#issuecomment-776913015) describing the script's main usage, let me know what you think!

**Comment by lnhsingh** [comment]
Closing - will open a new issue if anything needs to be adjusted.
