### ISSUE TITLE
haproxy: document higher timeout requirement for CLI accessing via load balancer

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#9462]
Artem Ervits (dbist) commented:

See https://github.com/cockroachdb/cockroach/issues/59305 and [Clustrix](https://docs.clustrix.com/display/SAG90/Load+Balancing+ClustrixDB+with+HAProxy) recommendation for connection timeout.

Jira Issue: DOC-927

**Comment by jseldess** [comment]
I think it's best to lean on the cockroach issue first. cc @piyush-singh, @taroface.
