### ISSUE TITLE
syntax error on step 4 of the Katacoda Build a Python App with CockroachDB: Run the Python Code

### ISSUE THREAD

**Issue by dweatherbee** [cockroachdb/docs#9484]
There seems to be a syntax error on step 4 of the Katacoda Build a Python App with CockroachDB: Run the Python Code:

```
$ python3 example.py 'postgresql://python:test@127.0.0.1:39055/bank?sslmode=require'
  File "example.py", line 160
    "For CockroachCloud Free, use "postgres://<username>:<password>@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/<cluster-name>.bank?sslmode=verify-full&sslrootcert=<your_certs_directory>/cc-ca.crt",\n""
                                   ^
SyntaxError: invalid syntax
```

**Comment by jseldess** [comment]
This is the culprit: https://github.com/cockroachlabs/hello-world-python-psycopg2/blob/master/example.py#L160. We need to use single quotes around the connection string example.

**Comment by ianjevans** [comment]
Just to clarify here, you can use double quotes around the connection string. That actually is the way you **must** specify the connection string if you use environment variables.
```python3 example.py "postgresql://$DBUSER:$DBPASS@localhost:$DBPORT/bank?sslmode=require"```

Also see this issue comment for alternate ways of specifying the connection string, which might be easier for CockroachCloud connection strings.
https://github.com/cockroachlabs/hello-world-python-psycopg2/issues/3#issuecomment-760552256
