### ISSUE TITLE
popup bottom right corner asking for docs feedback is stuck open (can’t click a ratings choice)

### ISSUE THREAD

**Issue by dweatherbee** [cockroachdb/docs#9485]
FYI the popup bottom right corner asking for docs feedback is stuck open (can’t click a ratings choice). Using Chrome .

<img width="999" alt="Screen Shot 2021-01-25 at 11 50 23 AM" src="https://user-images.githubusercontent.com/17344738/105731979-61315e80-5f06-11eb-9e3a-56eb9739b700.png">

**Comment by jseldess** [comment]
We're looking into an alternative tool for this survey functionality. Closing this for now.
