### ISSUE TITLE
Address issues around install page pointing to the wrong version of CockroachDB

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#9489]
**Problem:**
When Google searching “install cockroachdb," some of the results point to incorrect versions of CockroachDB. 

**Solution:**
[Based on this guide](https://moz.com/learn/seo/duplicate-content), we're proposing to use a canonical URL. In addition, we need to add a `noindex` tag for pages that we don't for indexing. 

--

It appears we already have a canonical URL:
![image](https://user-images.githubusercontent.com/1663752/105741640-8de67580-5f08-11eb-8dae-b549e8b04b12.png)

--

Also, this is what has populated in searches in the last 3 months:
https://files.slack.com/files-pri/T03GD9U3D-F01KYRBR3RS/screen_shot_2021-01-25_at_11.58.41_am.png

**Comment by jseldess** [comment]
This has gotten better in the meantime, though a general `install cockroachdb` search still returns a slightly older windows link under the stable linux link. Not sure what else we can do about this for now, so closing. @johnrk, let me know if you have ideas.
