### ISSUE TITLE
Troubleshooting connection issues in CC

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#9497]
We get support tickets on connection issues for CC often and many of those can be avoided with a basic troubleshooting guidance. Filing this issue to track this, but its not urgent. Could be a nice early in the release process doc. See here for what motivated this https://docs.atlas.mongodb.com/troubleshoot-connection and also the AllSaints Post mortem that might have been possible to be avoided with such docs. https://cockroachlabs.atlassian.net/wiki/spaces/MC/pages/1196982501/2020-12-17+AllSaints+Connection+Issues+and+Escalation

**Comment by lnhsingh** [comment]
Closing in favor of CC-3687
