### ISSUE TITLE
Clicking Katacoda CTA ("Run this in your browser") causes other content to disappear

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9501]
On https://600fd229b7cea40008a185f2--cockroachdb-docs.netlify.app/docs/stable/demo-json-support.html, you'll see that the "Python" tab is selected by default. When you click the "Run this in your browser" CTA, back on the Python page, it seems to deselect "Python". The result is that some of the steps are empty because neither Python nor Go is selected on the page. 

Before:
<img width="651" alt="Screen Shot 2021-01-26 at 9 47 36 AM" src="https://user-images.githubusercontent.com/15893490/105860440-92b83180-5fbb-11eb-9c41-0fa0e8be25fd.png">

After:
<img width="836" alt="Screen Shot 2021-01-26 at 9 47 47 AM" src="https://user-images.githubusercontent.com/15893490/105860462-98ae1280-5fbb-11eb-8fcf-74b5930bbdd6.png">

------------
Same problem can be seen on https://600fd229b7cea40008a185f2--cockroachdb-docs.netlify.app/docs/stable/build-a-python-app-with-cockroachdb.html.

**Comment by luciaaaaaaa** [comment]
@anagio I'm still seeing this issue
