### ISSUE TITLE
Changefeed documentation should mention URL encoding

### ISSUE THREAD

**Issue by kevinkokomani** [cockroachdb/docs#9511]
Doc: https://www.cockroachlabs.com/docs/v20.2/stream-data-out-of-cockroachdb-using-changefeeds.html#create-a-changefeed-connected-to-kafka

A customer reached out that they were unable to set up a changefeed connected to Kafka and attached a log file. This log file referenced a log that according to a few GitHub issues meant that there was an error processing credentials, and the solution turned out to be that they had not URL encoded the `sasl_password` before interpolating it into the changefeed URL. Upon doing that, they were able to connect their changefeed.

Reference GitHub issues:
- https://github.com/cockroachdb/cockroach/issues/55788
- https://github.com/cockroachlabs/support/issues/774

Reference tickets:
- https://cockroachdb.zendesk.com/agent/tickets/7147
- https://cockroachdb.zendesk.com/agent/tickets/6635

The first blue note in [this doc](https://www.cockroachlabs.com/docs/v20.1/backup.html#backup-file-urls) mentions the URL encoding that would need to be done to connect the changefeed successfully. Proposal is to have something like this throughout the changefeed documentation whenever we mention a step to run: `CREATE CHANGEFEED`.

**Comment by mwang1026** [comment]
Not just changefeed -- all of our external sinks should have a mention of URL encoding -- we have seen this a LOT lately
