### ISSUE TITLE
SELECT FOR UPDATE Doc Update 

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#9517]
Irfan Sharif (irfansharif) commented:

Re: [SELECT FOR UPDATE](https://cockroachlabs.com/docs//v20.2/select-for-update.html)

## Issue Description

Towards the end, when closing out txn 2, our instructions suggest `COMMIT`-ing twice.

Jira Issue: DOC-932

**Comment by jseldess** [comment]
@ericharmeling, assigning to you because I don't know which board to put it on.
