### ISSUE TITLE
sql: Use Check constraint to approximate Postgres ENUM/MySQL SET type

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#952]
Using the Check constraint, you should have a simple `IN` check on strings to mimic Postgres ENUM type and, to a lesser extent, MySQL SETs:
https://www.postgresql.org/docs/9.1/static/datatype-enum.html
http://dev.mysql.com/doc/refman/5.7/en/set.html

**Comment by jseldess** [comment]
Thanks for adding, @sploiselle. Where did this question come up? Gitter, forum, etc.?

**Comment by sploiselle** [comment]
@jseldess Just realized it.

**Comment by petermattis** [comment]
Cleaner (and equivalent) to use an `IN` expression: `a STRING CHECK (a IN ('b', 'c', 'd'))`.

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/2722.
