### ISSUE TITLE
machine shapes for Digital Ocean

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#9533]
Artem Ervits (dbist) commented:

in speaking with @keith-mcclellan the consensus is to recommend Digital Ocean's [memory](https://www.digitalocean.com/blog/memory-optimized-droplets-generally-available/) or [storage](https://www.digitalocean.com/blog/introducing-storage-optimized-droplets-with-nvme-ssds/) optimized machines with SSD Variant greater than 1x to compensate for underwhelming network performance. Our recommendation for DO is minimal and having at least some guidance on the machine types would be a welcome addition. One other note, in speaking with @a-entin for memory optimized machines, those are provided with 1vcpu x 8GB RAM which is double our recommended 1x4 ratio. With that type of configuration, we can also recommend `--cache=.35 --max-sql-memory=.35` to take advantage of the additional memory and still remain under the 1x4 recommendation.

Jira Issue: DOC-933

**Comment by jseldess** [comment]
Thanks, @dbist. cc @piyush-singh and @johnrk for triage.
