### ISSUE TITLE
util/log: new logging channels SQL_SCHEMA, USER_ADMIN and PRIVILEGES

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9535]
PR: https://github.com/cockroachdb/cockroach/pull/51987

- Notable events that pertain to SQL schema, user, and privilege changes are now sent on the new `SQL_SCHEMA`, `USER_ADMIN`, and `PRIVILEGES` [logging channels](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logging.md). These can now be redirected to different [sinks](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logsinks.md) from the other log entries.
    - The `SQL_SCHEMA` channel is used to report changes to the SQL logical schema, excluding privilege and ownership changes (which are reported on the separate channel `PRIVILEGES`) and zone config changes (which go to OPS). This includes:
        - Database/schema/table/sequence/view/type creation
        - Adding/removing/changing table columns
        - Changing sequence parameters
        - More generally, changes to the schema that affect the functional behavior of client apps using stored objects
    - The `USER_ADMIN` channel is typically configured in "audit" mode, with event numbering and synchronous writes. It is used to report changes in users and roles, including:
        - Users added/dropped
        - Changes to authentication credentials, including passwords, validity, etc.
        - Role grants/revocations
        - Role option grants/revocations
    - The `PRIVILEGES` channel is typically configured in "audit" mode, with event numbering and synchronous writes. It is used to report data authorization changes, including:
        - Privilege grants/revocations on database, objects, etc.
        - Object ownership changes [#51987][#51987]

**Comment by taroface** [comment]
Closed by #10273.
