### ISSUE TITLE
sql: convert SQL audit and execution log to a structured format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9540]
PR: https://github.com/cockroachdb/cockroach/pull/59110

From release notes:
> The logging format for [SQL audit](../v21.1/sql-audit-logging), [execution](../v21.1/query-behavior-troubleshooting#cluster-wide-execution-logs), and [query](../v21.1/query-behavior-troubleshooting#slow-query-logs) logs has changed, from a crude space-delimited format to JSON. To opt out of this new behavior and restore the pre-v21.1 logging format, you can set the [cluster setting](../v21.1/cluster-settings.html) `sql.log.unstructured_entries.enabled` to `true`. [#59110][#59110] {% comment %}doc{% endcomment %}

Related to https://cockroachlabs.atlassian.net/browse/CRDB-2266.

**Comment by taroface** [comment]
Closed by #10273.
