### ISSUE TITLE
sql/catalog/lease: increase `sql.tablecache.lease.refresh_limit` to 500

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9547]
PR: https://github.com/cockroachdb/cockroach/pull/59319

From release notes:
> Increased the default value of `sql.tablecache.lease.refresh_limit` to 500 in order to accomodate larger schemas without encountering `RETRY_COMMIT_DEADLINE_EXCEEDED` errors and generally higher latency. [#59319][#59319] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9904.
