### ISSUE TITLE
geo: add st_voronoipolygons and st_voronoilines builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9550]
PR: https://github.com/cockroachdb/cockroach/pull/56496

From release notes:
> Added a new [builtin](../v21.1/functions-and-operators#built-in-functions) method to calculate voronoi lines. [#56496][#56496] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
docs here: https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions
