### ISSUE TITLE
parser: focus on LOCALITY syntax + add PRIMARY REGION syntax

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9552]
PR: https://github.com/cockroachdb/cockroach/pull/57275

From release notes:
> Added `LOCALITY REGIONAL BY TABLE IN PRIMARY REGION` syntax for configuring table locality. [#57275][#57275] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Docs mention this syntax in following places:

- https://www.cockroachlabs.com/docs/v21.1/set-locality.html
- https://www.cockroachlabs.com/docs/v21.1/regional-tables.html
