### ISSUE TITLE
Update Blog banner

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9560]
![image](https://user-images.githubusercontent.com/15386648/106316842-601c6c00-623b-11eb-93bf-0ffe9ea90029.png)

Update blog banner to: https://www.cockroachlabs.com/blog/2021-cloud-report/

cc @jess-edwards - This will be a quick follow fix that Peter can take care of. Can you confirm that we should be highlighting the Cloud Report blog post? Or do you want to show something else?

**Comment by jess-edwards** [comment]
@lnhsingh Yes, please, post the Cloud Report blog post. Thank you!
