### ISSUE TITLE
importccl: support IMPORT in mixed-version cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9563]
PR: https://github.com/cockroachdb/cockroach/pull/57382

From release notes:
> Added support for running [`IMPORT`](../v21.1/import.html) in a mixed-version cluster. [#57382][#57382] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Where do we talk about mixed version in docs?

**Comment by jseldess** [comment]
We don't recommend running mix-version clusters. The only place we talk about it is in the rolling upgrade docs. Perhaps this product change impacts some of the preparation steps/limitations around bulk operations? https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#check-ongoing-jobs

**Comment by lnhsingh** [comment]
Not sure if this issue needs documentation, but if we decide it does, the changes would also apply to v20.2: https://github.com/cockroachdb/docs/issues/9233

**Comment by kathancox** [comment]
@mwang1026 & @lnhsingh What do you think on this one? Searching the docs (as Jesse said) it looks like mention of mixed-version clusters are only in release notes and a v2.0 upgrade doc. I'm wondering if mentioning mixed-version cluster is something we want to totally avoid if it's not recommended? Or, providing a note on the `IMPORT` page is best?

Paul mentions this in the PR relating to #9233: "Note, that it does not add support for running an IMPORT during the upgrade of a node however. The IMPORT job would need to be restarted in that case." Maybe this is worth mentioning?

**Comment by lnhsingh** [comment]
I'm leaning toward not needing to update docs for this- even for the note about not supporting an IMPORT during an upgrade, since I assume this has always been the case 

I think it's ok to close this issue. @mwang1026 - please reopen if you disagree
