### ISSUE TITLE
sql: persist table locality metadata and display in SHOW CREATE TABLE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9567]
PR: https://github.com/cockroachdb/cockroach/pull/57513

From release notes:
> `LOCALITY` directives on [`CREATE TABLE`](../v21.1/create-table.html) are now persisted onto the database. [#57513][#57513] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
IDK if we need to explicitly document this...

@rmloveland You okay with me closing this?

**Comment by rmloveland** [comment]
yep, implied - closing!
