### ISSUE TITLE
FAQ: Why is my empty database so big?

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#957]
New users who set up a cockroach cluster and return to it after a few days are often surprised by the amount of memory (rocksdb cache) and disk (timeseries storage) its using. We should add something about this to the FAQ page (in addition to making it less surprising in other ways, like attributing this data to its source in the admin UI, or even better just using less space for this stuff)

**Comment by jseldess** [comment]
From Gitter:
```
DBuTbKa @DBuTbKa 03:18
Hello everyone. Can anybody tell me. I was up a cockroachdb cluster with 6 containers on Kubernetes, create couple empty databases. In one databse create 5 tables and put some data (about 200KB) and wait couple days. Now I was look to admin UI and see what my DB consume a lot of memory (up to 20GB) and db size is growing up (up to 2.5GB).  
database has about 500KB data

Ben Darnell @bdarnell 03:29
@DBuTbKa the memory usage is the rocksdb cache, which defaults to 25% of the memory available to the container (and it will eventually grow to use all that space regardless of how much real data there is). if you need to limit the cache usage independently of the container size (or if you’re not using containers), you can use the —cache-size flag
the data usage is the time-series data used by graphs on the admin UI. we keep this data around for two weeks so it will stop growing at that point (and we may make this less space-hungry in the future)
```

**Comment by a-robinson** [comment]
This got hit again in https://github.com/cockroachdb/cockroach/issues/15993. It'd be really nice if we had a well-written docs entry to point people to. How quickly can we get something up? If help would speed things up, let me know where you think we should put something about it and I can write up an explanation.

**Comment by sploiselle** [comment]
For the time being @a-robinson, if you want to throw an explanation in `frequently-asked-questions.md`, that would be great.

**Comment by a-robinson** [comment]
Looking at it now, the `frequently-asked-questions.md` page only has questions that someone would ask when investigating whether to use cockroach. It isn't a useful page for people that are already using it and have questions about it.

The SQL FAQ has questions that current users would care about, but they're all obviously SQL related, which this really isn't. Ideally there'd be a different page for operational questions or we'd slightly re-theme the SQL FAQ page.

I'll send a PR adding it to the Known Limitations page for now, and a better place can be found later.

**Comment by sploiselle** [comment]
Sorry, @a-robinson; that's a good point––I recommended throwing it there as a punt for the time being until we figure out a better knowledge base-style place for it, or expand an operator/DBA-focused FAQ.

Might also be worth throwing on StackOverflow if you have a few minutes to tackle that.

**Comment by jseldess** [comment]
We definitely need some other area-specific FAQs. Just haven't created those pages yet. What would a good FAQ category here. Would we want to have one page for deployment faqs and another for other admin tasks? If so, perhaps we should add `Deployment FAQs` and `Admin FAQs`? Or should we just start with an `Admin FAQs` page and work from there?
