### ISSUE TITLE
sql: partially implement CONFIGURE ZONE logic during CREATE TABLE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9574]
PR: https://github.com/cockroachdb/cockroach/pull/57654

From release notes:
> [`CREATE TABLE ... LOCALITY ...`](../v21.1/create-table.html) statements now modify the [zone configurations](../v21.1/configure-replication-zones.html) to be in line with the desired locality. [#57654][#57654] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
IDK if we need to explicitly document this... thoughts @rmloveland ?

**Comment by rmloveland** [comment]
Yeah this is an implementation detail, let's close
