### ISSUE TITLE
sql: add sql.trace.stmt.enable_threshold

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9575]
PR: https://github.com/cockroachdb/cockroach/pull/57733

From release notes:
> Added `sql.trace.stmt.enable_thresold`. Similar to `sql.trace.txn.enable_threshold`, this logs a trace of any statements that take longer than the specified duration. This new setting allows for more granularity than the transaction threshold since it applies to individual statements and does not include overhead such as communication with a SQL client. [#57733][#57733] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9904.
