### ISSUE TITLE
pkg/sql: implement levenshtein

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9577]
PR: https://github.com/cockroachdb/cockroach/pull/56843

From release notes:
> Implemented [builtin](../v21.1/functions-and-operators#built-in-functions) function `levenshtein`. [#56843][#56843] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
