### ISSUE TITLE
builtins: add fuzzystrmatch soundex and difference builtin functions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9581]
PR: https://github.com/cockroachdb/cockroach/pull/57615

From release notes:
> Added the `soundex()` and `difference()` [builtin](../v21.1/functions-and-operators#built-in-functions) functions. [#57615][#57615] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
