### ISSUE TITLE
geo: add st_orientedenvelope builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9583]
PR: https://github.com/cockroachdb/cockroach/pull/57697

From release notes:
> Added a new [builtin](../v21.1/functions-and-operators#built-in-functions) method to calculate oriented envelope. [#57697][#57697] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This function is documented in [Functions and Operators](https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions)
