### ISSUE TITLE
protoreflect,types,cli,builtins: fix json for types, plumb emitDefaults

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9586]
PR: https://github.com/cockroachdb/cockroach/pull/58087

From release notes:
> Added an overload to `crdb_internal.pb_to_json` to suppress populating default values in fields. [#58087][#58087] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think we want to document this... it seems like an internal change.

@vy-ton 
Please re-open if you disagree from a product perspective.
