### ISSUE TITLE
builtins: implement gateway_region

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9595]
PR: https://github.com/cockroachdb/cockroach/pull/58423

From release notes:
> Implemented the `gateway_region` [builtin](../v21.1/functions-and-operators#built-in-functions), which returns the region of the connection's current node. [#58423][#58423] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Documented on both of:

- https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html
- https://www.cockroachlabs.com/docs/v21.1/set-locality.html
