### ISSUE TITLE
backupccl: skip collecting/verifying full-file SHA512 checksums

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9596]
PR: https://github.com/cockroachdb/cockroach/pull/58487

From release notes:
> [`BACKUP`](../v21.1/backup.html) and [`RESTORE`](../v21.1/restore.html) now use the block-level checksums embedded in their data files instead of collecting / verifying more expensive file-level SHA512 checksums. [#58487][#58487] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
I don't thikn we really talk about this low level detail in docs today. We could but we don't so p3

**Comment by lnhsingh** [comment]
Going to close for now
