### ISSUE TITLE
sql: add support for using FROM with SHOW ZONE CONFIGURATION

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9599]
PR: https://github.com/cockroachdb/cockroach/pull/58740

From release notes:
> Multiple [`SHOW ZONE CONFIGURATION`](../v21.1/show-zone-configurations.html) statements that previously used `FOR` can now also use `FROM` (e.g., `SHOW ZONE CONFIGURATION FOR RANGE`). This change standardizes the use of `FROM` for `SHOW ZONE CONFIGURATION`. [#58740][#58740] {% comment %}doc{% endcomment %}

**Comment by andyyang890** [comment]
FYI this release note is superseded by the release note in https://github.com/cockroachdb/cockroach/pull/59410

**Comment by ericharmeling** [comment]
I think I fixed this already: https://github.com/cockroachdb/docs/pull/10366
