### ISSUE TITLE
sql: virtual table changes for implicit column definitions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9602]
PR: https://github.com/cockroachdb/cockroach/pull/58749

From release notes:
> Columns implicitly added from [hash-sharded indexes](../v21.1/experimental-features.html#hash-sharded-indexes) will no longer display on `pg_index` and `pg_indexes`. [#58749][#58749] {% comment %}doc{% endcomment %}

Related to https://cockroachlabs.atlassian.net/browse/CRDB-1523.
Related to https://cockroachlabs.atlassian.net/browse/CRDB-1504.

**Comment by ericharmeling** [comment]
I don't think we need to document this change.
