### ISSUE TITLE
sql: virtual table changes for implicit column definitions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9603]
PR: https://github.com/cockroachdb/cockroach/pull/58749

From release notes:
> Added a new `implicit` column to `crdb_internal.index_columns`, which signifies whether the column is implicitly added onto the index through [`PARTITION BY`](../v21.1/partition-by.html) with an implicit column or a [hash-sharded index](../v21.1/experimental-features.html#hash-sharded-indexes). [#58749][#58749] {% comment %}doc{% endcomment %}

Related to https://cockroachlabs.atlassian.net/browse/CRDB-1523.
Related to https://cockroachlabs.atlassian.net/browse/CRDB-1504.

**Comment by ericharmeling** [comment]
I don't think we need to document this.
