### ISSUE TITLE
sql, jobs: stop queuing schema change jobs for in-txn schema changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9607]
PR: https://github.com/cockroachdb/cockroach/pull/58888

From release notes:
> Creating a table and changing its schema within a transaction no longer schedules a schema change job. [#58888][#58888] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
I don't think this requires documentation... We don't specifically list the changed behavior in the limitations of online schema changes. cockroachdb/cockroach#58888 seems to be more of a bug fix.
