### ISSUE TITLE
builtins: Implement ST_GeneratePoints function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9608]
PR: https://github.com/cockroachdb/cockroach/pull/58288

From release notes:
> Implemented geo [builtin](../v21.1/functions-and-operators#built-in-functions) `ST_GeneratePoints`. [#58288][#58288] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
In the docs: https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions
