### ISSUE TITLE
geo/geomfn: implement ST_LineSubstring({geometry,float8,float8})

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9612]
PR: https://github.com/cockroachdb/cockroach/pull/58125

From release notes:
> Implemented the geometry-based [builtins](../v21.1/functions-and-operators#built-in-functions) `ST_LineSubstring({geometry,float8,float8})`. [#58125][#58125] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
in the docs: https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions
