### ISSUE TITLE
geo/geomfn: implement ST_ShiftLongitude

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9619]
PR: https://github.com/cockroachdb/cockroach/pull/59234

From release notes:
> Implemented the geometry [builtin](../v21.1/functions-and-operators#built-in-functions) function `ST_ShiftLongitude`, which is useful for plotting data on a Pacific-centred map. [#59234][#59234] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
in the docs: https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html#spatial-functions
