### ISSUE TITLE
sql: Implement ALTER TABLE from REGIONAL BY TABLE to GLOBAL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9620]
PR: https://github.com/cockroachdb/cockroach/pull/59256

From release notes:
> Implemented [`ALTER TABLE ... SET LOCALITY GLOBAL`](../v21.1/alter-table.html) for tables starting as `REGIONAL BY ROW`. [#59256][#59256] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Correct
