### ISSUE TITLE
sql: convert SQL audit and execution log to a structured format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9623]
PR: https://github.com/cockroachdb/cockroach/pull/59110

From release notes:
> CockroachDB now uses a structured logging format for the [SQL audit](../v21.1/sql-audit-logging), [execution](../v21.1/query-behavior-troubleshooting#cluster-wide-execution-logs), and [query](../v21.1/query-behavior-troubleshooting#slow-query-logs) logs. See the generated [reference documentation](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/eventlog.md) for details. Of note, audit and execution logs now also include information about whether a query plan contains full index scans. Previously, this information was only included in the slow query log. [#59110][#59110] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closed by #10273.
