### ISSUE TITLE
sql: correctly handle CREATE INDEX on REGIONAL BY ROW tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9624]
PR: https://github.com/cockroachdb/cockroach/pull/59223

From release notes:
> [`CREATE INDEX`](../v21.1/create-index.html) on `REGIONAL BY ROW` tables will now correctly include the implicit partitioning and inherit the correct [zone configurations](../v21.1/configure-replication-zones.html). [#59223][#59223] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
This was fixed in #10280
