### ISSUE TITLE
opt: improve EXPLAIN for render

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9625]
PR: https://github.com/cockroachdb/cockroach/pull/59313

From release notes:
> Made a minor improvement to [`EXPLAIN`](../v21.1/explain.html) output for "render" node. [#59313][#59313] {% comment %}doc{% endcomment %}

**Comment by ianjevans** [comment]
No doc impact in `EXPLAIN` or `EXPLAIN ANALYZE` docs.
