### ISSUE TITLE
util/log,cli: channel abstraction; new configuration system

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9626]
PR: https://github.com/cockroachdb/cockroach/pull/57134

From release notes:
> The logging configuration can now be specified via the `--log` parameter. See the documentation for details. The flags `--log-dir`, `--log-file-max-size`, `--log-file-verbosity`, `--log-group-max-size` are now deprecated. [#57134][#57134] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closed by #10273.
