### ISSUE TITLE
util/log,cli: channel abstraction; new configuration system

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9627]
PR: https://github.com/cockroachdb/cockroach/pull/57134

From release notes:
> A new command `cockroch debug check-log-config` prints out the logging configuration that results from the provided combination of `--store`, `--log`, and other logging-related flags on the command line. [#57134][#57134] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closed by #10273.
