### ISSUE TITLE
util/log: new JSON output formats

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9633]
PR: https://github.com/cockroachdb/cockroach/pull/58126

From release notes:
> It is now possible to set the `format` parameter of any log sink, including file sinks, to `json`, `json-compact`, `json-fluent`, or `json-fluent-compact` to write entries as structured JSON. Refer to the generated [reference documentation](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logformats.md) for details. [#58126][#58126] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closed by #10273.
