### ISSUE TITLE
eventpb: document that CreateStatistics is only reported conditionally

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9642]
PR: https://github.com/cockroachdb/cockroach/pull/57877

From release notes:
> The notable event `create_statistics` is only reported when the [cluster setting](../v21.1/cluster-settings.html) `sql.stats.post_events.enabled` is enabled. This fact is now also reported in the [event log reference documentation](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/eventlog.md). [#57877][#57877] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closed by #10273.
