### ISSUE TITLE
ts, ui, sql, ccl: add metrics, timeseries graph for feature flags

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9645]
PR: https://github.com/cockroachdb/cockroach/pull/57533

From release notes:
> Added a timeseries graph indicating statement denials due to feature flags on the [SQL Dashboard](../v21.1/ui-sql-dashboard.html) of DB Console. [#57533][#57533] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
This issue might be for @ianjevans @ericharmeling.
