### ISSUE TITLE
ui: sessions page copy changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9646]
PR: https://github.com/cockroachdb/cockroach/pull/58616

From release notes:
> On the [Sessions page](../v21.1/ui-sessions-page.html), any `age` label has been replaced with `duration` and `txn` has been replaced with `transaction`. The actual metrics remain unchanged. [#58616][#58616] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as this has already been updated in the doc.
