### ISSUE TITLE
sql: add open txns gauge

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9648]
PR: https://github.com/cockroachdb/cockroach/pull/57477

From release notes:
> Added Open SQL Transactions to [SQL Dashboard](../v21.1/ui-sql-dashboard.html) and renamed `SQL Queries` to `SQL Statements`. Removed references to "Distributed SQL Queries" when metrics really are discussing all SQL queries. [#57477][#57477] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
This issue might be for @ianjevans @ericharmeling.
