### ISSUE TITLE
Update recommended production settings

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#965]
In [recommended production settings](https://www.cockroachlabs.com/docs/recommended-production-settings.html), clarify information (or provide new information) on more discrete elements of a deployment like:

- Number of machines & disks
- Data center locations
- RAM & CPU

Also handle NTP in greater detail (#960)

**Comment by spencerkimball** [comment]
Please include minimum recommended configuration as well.

**Comment by jseldess** [comment]
Duplicate of #1132
