### ISSUE TITLE
Search bar should span whole sidenav column

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9654]
Feedback from Irfan: I’d expect the search modal to take up the full width of the column

**Comment by anagio** [comment]
@luciaaaaaaa how much more space on left and right should the search input expand ?
![image](https://user-images.githubusercontent.com/1071553/107317723-c8860b80-6acd-11eb-9d2a-e2c6aa8a54e1.png)

**Comment by jseldess** [comment]
@luciaaaaaaa, this is a design question. Since you don't seem to think more space is required, I'm closing this. Please reopen if you have more guidance here.
