### ISSUE TITLE
release-20.2: sql: fix bug where bad mutation job state could block dropping tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9660]
PR: https://github.com/cockroachdb/cockroach/pull/58255

From release notes:
> A table can now be successfully dropped in a transaction following other [schema changes](../v20.2/online-schema-changes.html) to the table in the same transaction. [#58255][#58255] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
AFAIK, we never documented this bug as a known limitation. No docs required.
