### ISSUE TITLE
release-20.2: kvtenant: fetch ID of cluster during tenant startup

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9661]
PR: https://github.com/cockroachdb/cockroach/pull/58441

From release notes:
> The `crdb_internal.cluster_id` [function](../v20.2/functions-and-operators.html) now returns the ID of the underlying KV cluster in multi-tenant scenarios rather than the [Nil UUID](https://www.ietf.org/rfc/rfc4122.html#section-4.1.7). [#58441][#58441] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
No docs needed
