### ISSUE TITLE
release-20.2: protoreflect,types,cli,builtins: fix json for types, plumb emitDefaults

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9663]
PR: https://github.com/cockroachdb/cockroach/pull/58127

From release notes:
> Added a flag to `cockroach debug decode-proto` to suppress populating default values in fields. [#58127][#58127] {% comment %}doc{% endcomment %}

**Comment by taroface** [comment]
Closing, as this command isn't documented.
