### ISSUE TITLE
New application testing best practices topic

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/docs#9679]
Ian Evans (ianjevans) commented:

Part of phase 2.

Describe the best practices for testing an application, including DDL setup/cleanup.

Initial suggestions:

- `cockroachdb start-single-node --store=type=mem,size=10GiB` to start an in-memory cluster.
- Explore whether `DELETE FROM table WHERE true` is faster for removing inserted test demo, as opposed to `TRUNCATE table`.

gz#7480

**Comment by ericharmeling** [comment]
This is effectively a duplicate of https://github.com/cockroachdb/docs/issues/10991
