### ISSUE TITLE
vertical alignment Docs Menu / CockroachLabs logo

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9688]

**Comment by jseldess** [comment]
@luciaaaaaaa, I'm not certain what this issue is about, but in the meantime @anagio reworked the topnav, and it is completely aligned with how it looks on the marketing site now, so I'll close this. Please reopen if you have a remaining concern.

**Comment by luciaaaaaaa** [comment]
This is about the alignment between the logo on top nav, and our docs navigation 
Notice how in Docs, the CockroachLabs logo is misaligned with the search bar and Docs navigation
![image](https://user-images.githubusercontent.com/48258790/110667727-8cab9800-8198-11eb-88b5-4b6c5062f06f.png)

In other sections of our website, the CockroachLabs logo is aligned with the content below. 
![image](https://user-images.githubusercontent.com/48258790/110667866-afd64780-8198-11eb-8305-2b99c6f12d5f.png)

Ideally, margins set by on the Docs site would be respected by the top nav.
 
This is not a priority fix, because it does not impact usability.
