### ISSUE TITLE
CC FAQs update

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#9689]
Two updates: 

1. We've received a bunch of feedback from internal stakeholders like marketing and SEs that they are very concerned about the use of the word "prod" here `CockroachCloud Free is currently in beta and as such, it is not suitable for heavy production use` Let's change this to --> `CockroachCloud Free is currently in beta and as such, it is not recommended for production use` 
@lnhsingh I know we've gone back and forth on this, sorry to bring this up again, thank for your patience here. 

2. @timveil pointed out that we don't see anything about observability limitations. Can we add a question that's something like "Can I access the Statement pages in the DB console?" And we say, at this time, the full suite of DB console metrics are not available for the free tier. We do have the Overview page which has QPS / % of storage etc. 

@timveil any other comments? 
cc @jaymce

**Comment by lnhsingh** [comment]
I'll address these changes today!

**Comment by timveil** [comment]
yeah the word `production` is such a trigger word for me :). i understand why we are trying to qualify it by adding `heavy` but i feel like that leads to more questions... 

what about just dropping the work production altogether?  "hey its in beta and here are the FAQ's that describe the limitations".  maybe we just don't attempt to qualify it as production or not or something in between.

**Comment by kannanlakshmi** [comment]
Fine with not using the word `production` at all.

**Comment by timveil** [comment]
yeah i think its worth discussing.  the problem is that our definition of production may be very different from others.  as long as we have those FAQ's and we are up front with limitations i think we are clean.

**Comment by lnhsingh** [comment]
I think we decided to qualify it with `heavy` since toy apps, etc. _could_ be considered "production" for some developers, but I'm also fine with just removing `production` in general.
