### ISSUE TITLE
sql: Break up Functions & Operators page into multiple includes

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#969]
Exalate commented:

If we could break up the auto-generated Functions & Operators page into multiple includes (one per category, instead of the monolith we have now), we could add free-form text to the page, increasing the page's utility to users. 

For example, adding descriptions to headers or examples of using functions onto the page itself.

**Comment by rmloveland** [comment]
This appears to have been done, yay (below is from the page source) :-)

``` markdown
## Built-in functions

{% include {{ page.version.version }}/sql/functions.md %}

## Aggregate functions

{% include {{ page.version.version }}/sql/aggregates.md %}

## Window functions

{% include {{ page.version.version }}/sql/window_functions.md %}
```

**Comment by dt** [comment]
I'd originally meant one include per section -- so string functions, date functions, etc would each have their own include.

**Comment by rmloveland** [comment]
Ah that makes sense @dt - in that case I'd like to reopen this (but I can't seem to find a button to let me do that!  And according to this [old SO link](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github) (which is the best thing I could find, sadly) I guess I can't?  

(meta: What even is this website)

**Comment by dt** [comment]
(the button is right under the comment box)
