### ISSUE TITLE
Update versioned links to use /stable/ in CC

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9701]
When cross-referencing CRDB docs, CockroachCloud docs should use the `/stable/` versions of links instead of `/vX.X/`. This way, links do not have to be manually updated whenever the `stable` version is updated.

Note: Some time after the v20.2 release, the `/stable/` alias seemed to stop working in TeamCity. _Existing_ links using `/stable/` still seem to work, but any _new_ links throw an error in the build log.

**Comment by lnhsingh** [comment]
Moving this to later - will probably need @yingzhuchin's help with this.

**Comment by lnhsingh** [comment]
Duplicated in Jira by CC-3694

**Comment by yingzhuchin** [comment]
@lnhsingh, @taroface, this syntax using Liquid tags works:

https://github.com/cockroachdb/docs/pull/10313/files (ignore the second change)

Is this an acceptable solution? More info on the `relative_url` Liquid tag: https://jekyllrb.com/docs/liquid/filters/

**Comment by yingzhuchin** [comment]
Sorry, I had to revert this due to SEO implications I belatedly realized should be discussed and thought through first!
