### ISSUE TITLE
Long Running Migrations | Additional Load on Cluster during Upgrade

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#9705]
As noted in our release notes for 21.1, there might be additional internal load in the cluster, and that the process to SET CLUSTER SETTING might take time in proportion to the amount of data in the system.

Given how sensitive customers are about the upgrade process, it may be worth calling out in our docs of this additional load during the upgrade. This may cause alarms in their systems, as operations, such as changing cluster settings, will take longer.

cc @irfansharif

**Comment by taroface** [comment]
@johnrk Thanks for filing. Could you also link the release note where @irfansharif described this change?

**Comment by irfansharif** [comment]
From https://github.com/cockroachdb/cockroach/commit/89781b1cd41e7913a08ba459fe63b237a90a4d6e:
```
    Release note (general change): Cluster version upgrades, as initiated by
    SET CLUSTER SETTING version = <major>-<minor>, now perform internal
    maintenance duties that will delay how long it takes for the command to
    complete. The delay is proportional to the amount of data currently
    stored in the cluster. The cluster will also experience a small amount
    of additional load during this period while the upgrade is being
    finalized.
```

**Comment by jseldess** [comment]
@taroface, I'll take this as well since I'm working on 21.1 upgrade docs.
