### ISSUE TITLE
K8s Operator | Update Guidance on Deleting PV and PVCs

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#9719]
In our existing README and docs, we recommend our users to delete all pv and pvcs. 

After speaking with @keith-mcclellan , this risks customers deleting non-CRDB pv and pvcs.

Instead, let's guide users to specify deleting their pv and pvcs. 
_Delete persistent volume:_
`kubectl delete -f pv <name of persistent volume>`

_Delete persistent volume claim:_
`kubectl delete -f pvc <name of persistent volume claim>`

In addition, there may be a more efficient way to delete all crdb pv and pvcs in a single command without having to specify the name of each. 

After taking a look at the [official K8s Persistent Volumes docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming), we may need to have users update their Reclaim policy as well to "Delete"

@keith-mcclellan, any additional thoughts here?

**Comment by keith-mcclellan** [comment]
Is a customer is cleaning up an install, they'll also need to clean up any secrets we generated. Other than that, I think you have to delete the PVC before k8s will let you delete the PV.  Thanks John!

**Comment by taroface** [comment]
It looks like the PVs are deleted after the PVCs are deleted. The Reclaim Policy is `Delete`. Also, our manual instructions only have you deleting the PVCs. Is it OK to leave deleting the PVs out of this step?

**Comment by keith-mcclellan** [comment]
Yes that's fine if the reclaim policy is delete.
