### ISSUE TITLE
cdc: document new prefix and full table name functionality

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/docs#9720]
https://www.cockroachlabs.com/docs/v20.2/stream-data-out-of-cockroachdb-using-changefeeds.html

See

- https://github.com/cockroachdb/cockroach/pull/59710
- https://github.com/cockroachdb/cockroach/pull/59764

In addition to documenting the options, perhaps there should be a paragraph on best practices or potentially confusing interactions with other flags.

**Comment by jseldess** [comment]
Note: I think we will end up with related issues generated from the upcoming 21.1 beta notes.

**Comment by jseldess** [comment]
cc @lnhsingh

**Comment by lnhsingh** [comment]
This is covered by https://github.com/cockroachdb/docs/pull/10292 - closing this issue!
