### ISSUE TITLE
'cockroach debug ballast': provide a checklist for operators

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#9727]
The following callouts must be added:

- the `cockroach debug ballast` should not be run by a unix `root` user directly, to limit the chance of mistakenly affecting system directories / files.
- the target file should not be named similarly to a block device in `/dev`, to reduce the chance of mistyping a `/dev`  prefix into the command and thereby trashing a filesystem.
- give a new file name every time, instead of overwriting existing ballast files. To replace ballasts, add more ballast and then remove the old one.

Related: https://github.com/cockroachdb/cockroach/pull/59995

**Comment by jseldess** [comment]
cc @taroface. Let me know if you need help.
