### ISSUE TITLE
CC Connection modal

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#9731]
When I select "Your tool" the docs don't update, should they? The other two tabs do but the third one doesn't which feels odd as a user experience. 

Also can we point them to other connection tools options we already have in our docs like this https://www.cockroachlabs.com/docs/v20.2/hello-world-example-apps.html

![image](https://user-images.githubusercontent.com/36172966/107266503-dd499d00-6a02-11eb-8155-26ab00aca6ee.png)

**Comment by lnhsingh** [comment]
Yep, Step 2 changes (it says "...connect to your cluster with a CRDB-compatible tool") and links them to this page: https://www.cockroachlabs.com/docs/v20.2/third-party-database-tools.html/

**Comment by lnhsingh** [comment]
Maybe the instructions should clarify that "Step 2 below will update accordingly"?

**Comment by kannanlakshmi** [comment]
wow - I must have been dreaming because I kept staring at the bottom of the page for a link to the third party database tools and completely missed that the line above had the link. Sorry, please ignore me. 
And yes maybe adding "Step 2..." will help. But this is an egregious user error on my part. Sorry for wasting your time.

**Comment by lnhsingh** [comment]
Haha no problem! If it's not obvious to you, then it might be confusing for another user. I'll keep this open so I remember to update the wording a bit.

**Comment by lnhsingh** [comment]
Closing in favor of CC-3682
