### ISSUE TITLE
add disk performance to CC cluster creation doc

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9732]
Per @bobvawter, we list transactions per second on https://www.cockroachlabs.com/docs/cockroachcloud/create-your-cluster.html but need more specific disk performance numbers.

Thread: https://cockroachlabs.slack.com/archives/CBE9QQC4S/p1612809212227300

**Comment by gemma-shay** [comment]
Moved to Jira: https://cockroachlabs.atlassian.net/browse/CC-4381
