### ISSUE TITLE
logconfig: support YAML arrays to configure channels

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9737]
PR: https://github.com/cockroachdb/cockroach/pull/59352

From release notes:

- The `channels` parameter for the log sink [configurations](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logsinks.md) now supports a more flexible input configuration format:  
    Syntax to include specific channels:   
    `channels: dev,sessions`  (yaml string)   
    `channels: 'dev,sessions'` (yaml string, equivalent to previous)   
    `channels: [dev,sessions]` (yaml array, can use multi-line syntax with hyphens too)   
    `channels: ['dev','sessions']` (same as previous)   
    `channels: '[dev,sessions]'` (bracket-enclosed list inside yaml string)   

    Syntax to include all channels:  
    `channels: all` (yaml string)   
    `channels: 'all'` (same as previous)   
    `channels: [all]` (yaml array)   
    `channels: ['all']` (same as previous)   
    `channels: '[all]'` (bracket-enclosed "all" inside yaml string)   

    Syntax to include all channels except some:  
    `channels: all except dev,sessions` (yaml string)   
    `channels: 'all except dev,sessions'`  (same as previous, quoted string)   
    `channels: 'all except [dev,sessions]'` (same as previous, list is bracket enclosed)  

    For example:  ``` sinks:   stderr:     channels:     - DEV     - SQL_SESSIONS ```  uses the "native" YAML syntax for lists. [#59352][#59352]

**Comment by jseldess** [comment]
@taroface, @mikeCRL, not sure who this fall to.

**Comment by taroface** [comment]
I can take this.

**Comment by taroface** [comment]
Closed by #10273.
