### ISSUE TITLE
sql: handle CONSTRAINT...UNIQUE with PARTITION BY ALL / REGIONAL BY ROW

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9739]
PR: https://github.com/cockroachdb/cockroach/pull/59364

From release notes:
> Fixed up [`ALTER TABLE ... ADD CONSTRAINT ... UNIQUE`](../v21.1/add-constraint.html) to partition correctly under a [`PARTITION ALL BY`](../v21.1/partition-by.html) table. [#59364][#59364] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed by #10280
