### ISSUE TITLE
sql: Implement ALTER TABLE ... LOCALITY REGIONAL BY TABLE from GLOBAL

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9745]
PR: https://github.com/cockroachdb/cockroach/pull/59407

From release notes:
> Implemented [`ALTER TABLE ... LOCALITY REGIONAL BY TABLE`](../v21.1/alter-table.html) from `LOCALITY GLOBAL`. [#59407][#59407] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@rmloveland
I don't think we need to document this any more than you already have done in https://www.cockroachlabs.com/docs/v21.1/set-locality.html ?

**Comment by rmloveland** [comment]
Yes!  PS I'm going around closing all these now :-)
