### ISSUE TITLE
config: introduce `num_voters` and `voter_constraints`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9746]
PR: https://github.com/cockroachdb/cockroach/pull/57184

From release notes:
> [Zone configs](../v21.1/configure-replication-zones.html) now support new attributes `num_voters` and `voter_constraints`. `num_voters` will specify the number of [voting replicas](../v21.1/architecture/life-of-a-distributed-transaction.html#consensus). When `num_voters` is explicitly specified, `num_replicas` will be the sum of voting and non-voting replicas. `voter_constraints` will specify the constraints that govern the placement of just the voting replicas, whereas the existing `constraints` attributes will govern the placement of all replicas (voting as well as non-voting). [#57184][#57184] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Fixed by #9897
