### ISSUE TITLE
streamingccl,sql: add sql syntax and ingestion planning logic

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9747]
PR: https://github.com/cockroachdb/cockroach/pull/59112

From release notes:
> Added SQL syntax for [`RESTORE tenant x FROM REPLICATION STREAM FROM 'replication_stream'`](../v21.1/restore.html). This allows the user to start an ingestion job to ingest KVs from the replication stream into the destination tenant's keyspace. [#59112][#59112] {% comment %}doc{% endcomment %}

**Comment by mwang1026** [comment]
Not doc-ing this go round since IIRC not doc-ing tenant things until a later release.
