### ISSUE TITLE
sql: deterministic zone config output for SHOW CREATE

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9748]
PR: https://github.com/cockroachdb/cockroach/pull/59580

From release notes:
> The [`SHOW CREATE`](../v21.1/show-create.html) statement now lists [`ALTER PARTITION`](../v21.1/alter-partition.html) statements sorted by the partition name and index_name. [#59580][#59580] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This change doesn't need to be directly documented.
