### ISSUE TITLE
changefeedccl: Freeze table name to the (optionally fully qualified) statement time name

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9751]
PR: https://github.com/cockroachdb/cockroach/pull/59258

From release notes:
> Added `WITH full_table_name` option to create a changefeed on `movr.public.drivers` instead of `drivers`. [#59258][#59258] {% comment %}doc{% endcomment %}

**Comment by lnhsingh** [comment]
Related to https://github.com/cockroachdb/docs/pull/10292

Closing - I don't think this specific GH issue requires more docs
