### ISSUE TITLE
util/log: report log flushes and TLS rotations on the ops channels

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9755]
PR: https://github.com/cockroachdb/cockroach/pull/59345

From release notes:
> The notification that `SIGHUP` was received, and that log files are flushed to disk as a result, is now sent to the [OPS logging channel](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logging.md#ops). [#59345][#59345] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@mikeCRL, @taroface, not sure who this goes to.

**Comment by taroface** [comment]
I can take this as `SIGHUP` feels related to deployments.

**Comment by taroface** [comment]
Closed by #10273.
