### ISSUE TITLE
util/log: report log flushes and TLS rotations on the ops channels

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9756]
PR: https://github.com/cockroachdb/cockroach/pull/59345

From release notes:
> The notification that `SIGHUP` was received, and that TLS certificates are reloaded from disk as a result, is now sent to the OPS logging channel as a structured event. Refer to the [reference docs](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/logformats.md) for details about the event payload. [#59345][#59345] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@mikeCRL, I think this is your part of the logging channels project, but if not, please reassign to @taroface.

**Comment by taroface** [comment]
@mikeCRL I've also added this to the Observability Docs project board, just for completion. Feel free to use a different/additional project board to track, if you like.

**Comment by mikeCRL** [comment]
@taroface FYI this looks like a duplicate of #9755, which is assigned to you. Reassigning this one too, but you can decide whether to close one of them.

**Comment by taroface** [comment]
Closed by #10273.
