### ISSUE TITLE
Missing backwards-incompatible callout for v20.2.0

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/docs#9769]
Irfan Sharif (irfansharif) commented:

Re: [What's New in v20.2.0](https://cockroachlabs.com/docs//releases/v20.2.0.html)

## Issue Description

In v20.2 we made a backwards incompatible change around the semantics for `node recommission`. The change, and the corresponding release note, can be found here: https://github.com/cockroachdb/cockroach/pull/50329/commits/57033b4bccd693e7b30a3359b256e0aa6375a14b.

## Suggested Resolution 

We should make mention of it. @a-robinson pointed it out on our Community Slack (thanks!)

Jira Issue: DOC-974

**Comment by irfansharif** [comment]
(Almost definitely got the assignment wrong, but feel free to move it around for better triage.)

**Comment by rmloveland** [comment]
Thanks @irfansharif - I think this should be mine.

Seems to be a docs issue (or several) related to this that I did not get to:

- #8191
- #8192
- #8193
