### ISSUE TITLE
use traditional version on Jekyll gem

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/docs#9770]
(Creating this issue for future reference, after @yingzhuchin has returned)

In the Gemfile, Jekyll is specified as a commit version on GitHub, instead a traditional release version. As a result, the [Netlify checks](https://app.netlify.com/sites/cockroachdb-docs/deploys/6021e71fb86fa1000803bb23) are expensive, requiring gem rebuilds. In [this experiment](https://github.com/cockroachdb/docs/pull/9736), using a traditional version reduced the execution time from ~5 minutes to ~2.

Looking at ci/README.md, I see that updating gem versions also requires updating the Docker image. So the immediate task is:

- Update the Dockerfile with the updated Jekyll gem version, as prescribed in the README

Further optimizations to consider after the above:

- Use a more recent Alpine image in the Dockerfile, which will get us a more recent Ruby
  - It is desirable that the CI Ruby version is close to the default version on Mac, that developers use
- Use an actual [Ruby Docker image](https://hub.docker.com/_/ruby)

Further consideration: requiring a Docker image update when gems are updated is a performance optimization, but imho, makes things harder than they should be. I’d rather have a gem update ‘just work’. If we wish to also optimize the Docker image, make it optional.

**Comment by jseldess** [comment]
This was address in a PR by @ianjevans: https://github.com/cockroachdb/docs/pull/9804/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR8. 

The docker image is just for TeamCity. We need to think about moving all the way over to Netlify for CI/CD: https://github.com/cockroachdb/docs/issues/7050 once @yingzhuchin is back.
