### ISSUE TITLE
Load balancing/connection pooling

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#978]
We should document multiple strategies with code samples in various langauges.

Possible strategies to cover (taken from @arjunravinarayan's response to this [forum post](https://forum.cockroachlabs.com/t/how-to-connect-to-a-pool-of-servers-in-php/407)):

1. Configure the client driver to connect to multiple node URLs for failover tolerance/performance. 
2. Set up a proxy server (such as HAProxy) that provides a single connection URL for the client, and have HAProxy provide load balancing/failover resilience.
3. Use DNS aliases with DNS round-robin load balancing.

2 and 3 seamlessly take advantage of cluster changes (e.g., a cockroach cluster growing to more nodes, or migrating nodes), without needing clients to be aware.

Related: #448

**Comment by InAnimaTe** [comment]
Regarding the HAProxy (LB) method in general, there needs to clarification on configuration i.e. should there be concerns about session affinity, what are the best timeout settings to use, what balancing strategy should be utilized etc..

Really excited to see how this pans out. Making clients only need to be aware of a single endpoint to access a replica set is definitely awesome.

**Comment by jseldess** [comment]
Status:
- Updated manual deployment tutorials to feature HAProxy load balancing.
- Updated Digital Ocean and GCE tutorials to feature platform-managed load balancing.

To do:
- Improve load balancing guidance for Azure and AWS.
- Consider whether to cover configuring client drivers to connect to multiple node URLs (@mberhault, is this important to cover?)

**Comment by alanhamlett** [comment]
Instead of implementing load balancing in every client driver, which is difficult to maintain, why not do what RethinkDB did and let the cockroach binary have a `proxy` mode thats used to load balance at each client?

**Comment by jseldess** [comment]
@alanhamlett, thanks for the suggestion! Since it is a feature request, would you mind opening an issue in the [`cockroach`](https://github.com/cockroachdb/cockroach/issues) repo?

**Comment by 0xbaadf00d** [comment]
PostgreSQL driver already has this feature, at least the Java version.

```
jdbc:postgresql://node1,node2,node3/accounting?loadBalanceHosts=true
```

**Comment by jseldess** [comment]
@awoods187, @knz, @bdarnell, since this issue was opened, we added quite a bit of guidance around load balancing:

- https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#load-balancing

That links out to environment-specific load balancing guidance in our deployment tutorials. 

Our docs still don't cover driver-level connection pooling. Is this something we should consider for 2.2 docs?

**Comment by bdarnell** [comment]
I think any further changes in this area are probably low-priority; we've covered the important stuff (and we're recommending managed load balancers in most cases which should be reliable). The main thing that would be left would be to talk about running two HAProxy instances for the manual deployment case, and balance between them on the client side.

**Comment by jseldess** [comment]
Given @bdarnell's last comment, closing this for now.
