### ISSUE TITLE
K8s Operator: Document how to use additionalArgs field 

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/docs#9780]
Exalate commented:

the additionalArgs field gives Operator a lot of flexibility in configuring their deployments. 

the syntax is weird because it's a string array.

It will be helpful to provide an example. In addition, we should point our users to our existing cockroach start docs. This will equip users with all of the available configurations through the additionalargs field.

Jira Issue: DOC-977

**Comment by taroface** [comment]
I'm aiming to document setting `--locality` with `additionalArgs`. @keith-mcclellan provided this example for EKS:

```
--locality=region=$(curl http://169.254.169.254/latest/meta-data/placement/region),zone=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)
```

I have an equivalent for determining the zone on GKE, but the region doesn't seem to be part of the [instance metadata](https://cloud.google.com/appengine/docs/standard/java/accessing-instance-metadata). 

```
--locality=region=$(curl <region endpoint>),zone=$(curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google')
```

@keith-mcclellan @udnay any tips here?

**Comment by keith-mcclellan** [comment]
thats a perfectly reasonable option, you could use a bash trick for this, so something like:

--locality=region=${${curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google' }::-2},zone=$(curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H 'Metadata-Flavor: Google')
