### ISSUE TITLE
K8s Operator: Document accounting for Ingress and Egress (placeholder)

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/docs#9783]
Exalate commented:

This is currrently listed as a known issue in our README because it hasn't been tested.

We'll need to document how one can use this: Document accounting for Ingress and Egress

Jira Issue: DOC-979

**Comment by taroface** [comment]
Is this related to the configuration of grpcPort, httpPort, and sqlPort? Or is this something else?

cc @keith-mcclellan
