### ISSUE TITLE
K8s Operator: Docs for Configuring Permissions (placeholder)

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/docs#9785]
Exalate commented:

Engineering is addressing an issue around our handling of permissions: [Address Permissions Required by the Operator #258](https://github.com/cockroachdb/cockroach-operator/issues/258)

Jira Issue: DOC-981

**Comment by taroface** [comment]
@johnrk @keith-mcclellan What docs are needed here? This looks like an Operator manifest change.

**Comment by johnrk** [comment]
@taroface , AFAIK, no docs are needed here. This particular change is related to tech debt.

@keith-mcclellan , can you confirm?
