### ISSUE TITLE
K8s: Create reference docs for all configurable custom resources

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/docs#9786]
Exalate commented:

We need comprehensive reference docs and an example yaml for all of the configurable custom resources for the Operator.

All configurable custom resources can be found in the custom resource definition (https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml). It's hard to navigate. Also, it contains descriptions for each of the fields.

--

Some of the custom resources that need some docs support are:
- cache (it's important that we point users to our production guidelines on cache)
- image (pull policy, pull secret)
- dataStore (we're removing support for emptyDir)
- maxSQLMemory (similar to cache, we have existing guidance)
- resources (related to production guidelines as well)
- tlsEnable (to be removed, all clusters will be secure by default - [Make Secure Mode the Default #153](https://github.com/cockroachdb/cockroach-operator/issues/153))
- status (probably not relevant, confirm with engineering)
- all of the ports (grpcPort, HTTPport, the 3rd port for SQL traffic)

Jira Issue: DOC-982

**Comment by taroface** [comment]
@udnay Is this [yaml](https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml) used to set the properties of the custom resource fields on the back end, or is it strictly a piece of internal documentation?
