### ISSUE TITLE
Add to CC Free FAQ 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#9801]
If a free tier user hits the storage limit, we currently 1. email them requesting them to delete some data to stay under the 5GB limit 2. Block that user from accessing their cluster if they don't respond to 1. In the next 1 month, 1 and 2 will be done programmatically. We should add this to the FAQ at a minimum and eventually write out a whole section on limits and what happens when you hit limits.

**Comment by lnhsingh** [comment]
Closing in favor of CC-3702
