### ISSUE TITLE
Mistake in changefeed example

### ISSUE THREAD

**Issue by greg-crl** [cockroachdb/docs#9805]
on this page

https://www.cockroachlabs.com/docs/dev/stream-data-out-of-cockroachdb-using-changefeeds.html#create-a-core-changefeed

step 1 of the core changefeed example says to start a single node cluster, but gives the incorrect command

**cockroach start --insecure --listen-addr=localhost --background**

subsequent examples correctly specify the command

**cockroach start-single-node --insecure --listen-addr=localhost --background**

**Comment by jseldess** [comment]
cc @lnhsingh. Easy fix.
