### ISSUE TITLE
Document crdb_internal.force_retry() and how to use it to test transaction retry scenarios

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#9806]
Even internally, we've recieved feedback to document the expected behavior of [crdb_internal.force_retry()](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1600356504179000).

In addition, `crdb_internal.force_retry()` usage within our [third-party tool examples](https://www.cockroachlabs.com/docs/v20.2/build-a-java-app-with-cockroachdb-hibernate) makes it difficult to explain just transaction retry to users. Ideally, we would extract transaction retry developer recipe.

**Comment by ericharmeling** [comment]
The help text for `crdb_internal.force_retry()`:

~~~
demo@127.0.0.1:26257/defaultdb> \hf crdb_internal.force_retry
Function:    crdb_internal.force_retry
Category:    System info
This function is used only by CockroachDB's developers for testing purposes.

Signature
crdb_internal.force_retry(val: interval) -> int

See also:
  https://www.cockroachlabs.com/docs/v21.1/functions-and-operators.html
~~~

The generated docs for `crdb_internal.force_retry()`:

![image](https://user-images.githubusercontent.com/27286675/114752934-ddc52380-9d24-11eb-8ab7-3cbe6afdf2f5.png)


According to this description, we shouldn't be encouraging users to use `crdb_internal.force_retry()` at all. 

We could document `crdb_internal.force_retry()` usage more explicitly (and then update the helptext/generated function docs). But I'm wondering if we want to remove `crdb_internal.force_retry()` from our examples entirely.

I don't find the function's behavior very intuitive. @timveil [seems to agree](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1600356504179000). 

@ajwerner, @rafiss : thoughts? How necessary/helpful is this function for users looking to write retry logic into their applications?

**Comment by timveil** [comment]
yes yes yes... i'd love to find another way to more simply trigger retry behavior so developers can test their application's behavior.  the current usage of this function complicates our examples and is not intuitive.  truthfully i still don't understand how to integrate its usage into code examples in a coherent way

**Comment by rafiss** [comment]
Let's just finalize https://github.com/cockroachdb/cockroach/pull/45224 once and for all. It lets you set a session variable to txn retries.

Based on the Slack convo here, we should be able to https://cockroachlabs.slack.com/archives/C04U1BTF8/p1609860010064800?thread_ts=1600356504.179000&cid=C04U1BTF8

cc @vy-ton would you agree that we should do the PR I linked instead of documenting this internal function?

**Comment by vy-ton** [comment]
Yes, the PR Rafi linked is a [21.2 roadmap item](https://cockroachlabs.atlassian.net/browse/CRDB-2268).

I created this docs issue as a stopgap until we could provide the session variable. Once the session variable exists, we can modify our examples to stop using `crdb_internal.force_retry`

I'm not opposed to closing this. Although the better testing won't be available until 21.2

**Comment by timveil** [comment]
Happy to test as much as I can.  I have a bunch of retry code ready to go.

**Comment by ericharmeling** [comment]
Closing this issue for now.

I assume https://github.com/cockroachdb/cockroach/pull/45224 will be backported, since it was written on 20.2 in the first place. As Vy said, after that's merged, we can coordinate on updating the samples.
