### ISSUE TITLE
SERIAL - explain rowid

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#9811]
Jessie Lin (lin-crl) commented:

Re: [SERIAL](https://cockroachlabs.com/docs//v20.2/serial.html)

## Issue Description
customer don't understand how to interpret rowid

## Suggested Resolution 
Add a section to help customer understand rowid

## Description
For troubleshooting purposes, it seems to be good to document the first 48bits on the rowid are the elapsed time in nanosecond since 2015-01-01, the last 15bits are node ids

## Outline
Add a note to walk through how to interpret rowid for troubleshooting. The first 48bits on the rowid are the elapsed time in nanosecond since 2015-01-01, the last 15bits are node ids, and use examples like below:

select to_hex(id) from t1;
to_hex
-------------------
7e39c56700c0001
7e39d34d0808001
7e3a035f75f8001
(3 rows)

root@:26257/defaultdb> select to_hex(id>>15) from t1;
to_hex
---------------
fc738ace018
fc73a69a101
fc7406beebf```

## Expected Audience
Technical audience 

Jira Issue: DOC-987

**Comment by jseldess** [comment]
Thanks, @lin-crl, and sorry for the delay. This is on the SQL docs team backlog now.

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
