### ISSUE TITLE
Third-part tools: Vault is in wrong category

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#9814]
Re: [Third-Party Database Tools](https://cockroachlabs.com/docs//v20.2/third-party-database-tools.html)

## Issue Description

Vault is listed as a "GUI".  This is really a Key management solution and nothing like the other "GUI"s  mentioned.  I think we need to move Vault to "other" or start a section around "Security/Key Management" as there are other products in this space that we should keep our eye on.

**Comment by jseldess** [comment]
cc @vy-ton, @ericharmeling, @ianjevans

**Comment by vy-ton** [comment]
Duplicate of https://github.com/cockroachdb/docs/issues/9475
