### ISSUE TITLE
Third-party tools: how we recommend versions

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#9815]
Re: [Third-Party Database Tools](https://cockroachlabs.com/docs//v20.2/third-party-database-tools.html)

## Issue Description

In the Drivers section, "Recommended Version" column we specify an exact version.  For example for Java we suggest `42.2.9` exactly.  This version is roughly 18 months old.  Wouldn't it make more sense to recommend something like `42.2.9 or higher` like we do for other versions?  I know with this driver in particular i'm not aware of reason not to use the latest which is `42.1.18`.

**Comment by jseldess** [comment]
cc @vy-ton, @ericharmeling, @ianjevans
