### ISSUE TITLE
New tooltips for Transactions page in DB Console

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/docs#9816]
Ian Evans (ianjevans) commented:

Per the work @Annebirzin is doing on designing the new Transactions page in the DB Console for 21.1, we need to review the tooltips, and provide stub topics for links if necessary.

https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1834%3A2895

cc @taroface

**Comment by Annebirzin** [comment]
@ianjevans just a heads up I also aded 2 more pages for the [statements detail](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1919%3A0) and [txn detail](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1919%3A1727) pages to capture the additional tooltips (most of them are duplicates from the list views).

Also, I am happy to transfer this messaging to a google doc or something if it's easier to collaborate/edit copy that way.

**Comment by ianjevans** [comment]
@Annebirzin left a few minor comments within Figma. If you're ok using Figma's comments for feedback, it's probably easier to consolidate everything in one place, I think. But I'm willing to move them into a doc if that's easier for you.

**Comment by Annebirzin** [comment]
Sounds good, we can leave in Figma so it's all in once place
