### ISSUE TITLE
Update deployment tutorials to put spatial libraries in right place

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9820]
For example: https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises.html#step-3-start-nodes

No reason not to include the proper steps so that spatial is enabled.

**Comment by jseldess** [comment]
@rmloveland, happy to take this one. Should be easy.

**Comment by rmloveland** [comment]
thanks Jesse! just took at look at the PR.  Sorry for slowness, finally almost done moving to the new machine
