### ISSUE TITLE
bulkio: deprecation notice for GCS authorization

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/docs#9822]
To authorize to Google Cloud Storage, you have a few options:
- Machine credentials
- The `cloudstorage.gs.default.key` cluster setting
- Explicit credentials supplied in the GCS URI

Today, we *default* to using the cluster setting. But this is bad. We should not be storing secrets in a cluster setting, and we should not have default dissonance -- specifically all of our other cloud storage options default to `AUTH=specified`.

We want to deprecate a few things:
- The cluster setting
- And swap the default to be `AUTH=specified`

Instructions for customers over the course of 21.1 is to:
- If they're using the cluster setting, move to using machine credentials or specified credential in URI
- If they are relying on default behavior (i.e. not including `AUTH=` and assuming default, that they shuld adjust queries / scripts to now specify the AUTH they want

**Comment by mwang1026** [comment]
cc @adityamaru for anything obvious I missed here

**Comment by adityamaru** [comment]
Thanks for this LGTM!
