### ISSUE TITLE
Remove schema changes warning for upgrade to 20.2

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/docs#9823]
[This docs page](https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#check-ongoing-jobs) has

> Make sure there are no bulk imports or schema changes in progress. 

@ajwerner commented regarding schema changes:
> it's not really a big deal in 20.1->20.2. We had some real limitations in 19.2->20.1"

@lucy-zhang agreed
>  this warning is not great.

Please modify this docs page. thanks!

**Comment by florence-crl** [comment]
[Step 5](https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#step-5-finish-the-upgrade) also mentions "new schema changes":

> If you disabled auto-finalization in step 3, monitor the stability and performance of your cluster for as long as you require to feel comfortable with the upgrade (generally at least a day) and remember to prevent new schema changes and changes to user privileges.

@ajwerner and @lucy-zhang: please confirm whether this reference to "new schema changes" should also be removed. thanks!

**Comment by ajwerner** [comment]
I mean, it's all a balance. We test it, sure, but do we test it nearly as much as in the single version case. Is there some way to say, "if you can defer large schema changes or put off cluster-wide changes, please do but it all should still work"?

**Comment by jseldess** [comment]
I'll just strike that as well. If we see problems in the future, we can revisit.
