### ISSUE TITLE
Change location of email-signup bar trigger

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#983]
Change location where email opt-in bar pops up. Code is probably located [here](https://github.com/cockroachdb/docs/blob/gh-pages/_includes/newsletter-popout.html#L64).

**Comment by jseldess** [comment]
@sploiselle, should we punt this over to DivisionOf? Not urgent really.

**Comment by sploiselle** [comment]
@jess-edwards @swatikumar16 Can either of you all check on an increase in sign-ups driven from docs on or around Jan. 31?

**Comment by swatikumar16** [comment]
@sploiselle  @jess-edwards @jseldess  There was definitely an increase in sign-ups in February from the Docs footer. We went from 2 in all of January to 26 in February, and that number has stayed high ever since (43 in March, 41 in April).

**Comment by sploiselle** [comment]
Amazing. Thanks!
