### ISSUE TITLE
--background flag doesn't work on Windows - docs are misleading

### ISSUE THREAD

**Issue by kevinkokomani** [cockroachdb/docs#9844]
Kevin Kokomani (kevinkokomani) commented:

Issue: Users who are on Windows are likely to navigate to our docs that outline the usage of `--background` to start a cluster in a terminal window so you can continue using the same terminal window. According to https://github.com/cockroachdb/cockroach/issues/17082, however, there are no plans to support usage of `--background` on windows.

User journey that is confusing:

1. User begins here: https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-windows
2. After downloading the .exe, they may want to "start a cluster locally": https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-windows#whats-next
3. Clicking the "start a cluster locally" link leads to this: https://www.cockroachlabs.com/docs/v20.2/start-a-local-cluster
4. Which are the generic docs that describe how to use `--background` to start your cluster locally.

Impact is low, but if we are not planning to support this for Windows users, we may consider making a docs change to https://www.cockroachlabs.com/docs/v20.2/start-a-local-cluster to reflect that, or wherever would be best.

Jira Issue: DOC-994

**Comment by jseldess** [comment]
Thanks, @kevinkokomani. We have talked about removing `--background` from those docs, but I can't find the issue. In any case, even if we don't, we need to consider the impact for Windows users, to your point.

**Comment by barathashok108** [comment]
has this been fixed? What's the alternative to --background for starting a cluster in the same way?
