### ISSUE TITLE
machine types and IOPS

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#9853]
I thought we had some of this in our docs but looks like we removed it or never added it. 

We should be transparent that we use the `n1` standard series and the `c5` series in GCP and AWS respectively for CC. We should also document that we use EBS and Persistent disks and the the IOPS associated with each node size in AWS. 

Inspired by this question https://cockroachlabs.slack.com/archives/CJX8V9SJ2/p1614090139010400

**Comment by lnhsingh** [comment]
Closing in favor of CC-3698
