### ISSUE TITLE
bold text in h2s needs style update

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9854]
Ryan Kuo (taroface) commented:

Bolded text in H2s is not appearing correctly: https://www.cockroachlabs.com/docs/stable/ui-custom-chart-debug-page.html

![image](https://user-images.githubusercontent.com/8740013/108865687-79f26a00-75c1-11eb-8c8e-a232b22a31be.png)

Jira Issue: DOC-998

**Comment by jseldess** [comment]
@luciaaaaaaa, @lnhsingh, is this a known or new issue?

**Comment by lnhsingh** [comment]
Oh this is weird! I'm pretty sure this is a new issue, but semi-related to #9401
