### ISSUE TITLE
Mobile UI incorrectly served to desktop

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/docs#9856]
(I've reported this in slack before but can't find it tracked anywhere) Our website serves its mobile navigation UI to my 1100-pixel wide desktop browser window (it appears to make this decision solely based on window width, with a cutoff around 1200 pixels). This is a bad experience since the navigation sidebar is now hidden behind a click (and the top-level non-docs-specific nav menu is even worse because it still has hover tracking enabled in its mobile layout). 

![image](https://user-images.githubusercontent.com/160562/108869114-e02cbc00-75c4-11eb-9379-f814894b1a64.png)

**Comment by jseldess** [comment]
@luciaaaaaaa, @lnhsingh, do we have an issue for this? Seems high priority.

**Comment by lnhsingh** [comment]
I think this is the same as https://github.com/cockroachdb/docs/issues/9312 ("CSS responsive breakpoint is too large"), right? If so, Peter's open PR will fix this.

**Comment by bdarnell** [comment]
Yes, #9312 is the same thing.
