### ISSUE TITLE
general docs: the top bar gets in the way of using the docs

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#9867]
The new design gets in the way of using the docs with new iframes.

![image](https://user-images.githubusercontent.com/461296/108905897-411cba00-75ee-11eb-88eb-bb04f376dbef.png)

The iframe persists for a few seconds and hinder the usability of the docs.

**Comment by dbist** [comment]
CC: @lnhsingh not sure how to direct this, I find the top menu very frustrating.

**Comment by lnhsingh** [comment]
Thanks for the feedback @dbist! This is actually being addressed by a PR in progress that'll change the top nav's behavior to be click-to-expand instead of rollover, so hopefully it won't be as bothersome. Going to close this issue in favor of #9243
