### ISSUE TITLE
use remote includes on generated docs

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9883]
Docs that use auto-generated `cockroach` content, such as:

- https://www.cockroachlabs.com/docs/stable/functions-and-operators.html
- https://www.cockroachlabs.com/docs/stable/cluster-settings.html
- https://www.cockroachlabs.com/docs/stable/sql-grammar.html

should use remote includes so that we won't have to manually update them for each release.

Remote includes should point to the appropriate branch for each docs version.

**Comment by jseldess** [comment]
Thanks, @taroface! @ianjevans, would you work with me on this? I think this could be great for us.

**Comment by ianjevans** [comment]
No problem. It should be really simple.

E.g. Replace the current contents of `functions-and-operators.md` with:
```
{% remote_include https://raw.githubusercontent.com/cockroachdb/cockroach/v20.2.5/docs/generated/sql/functions.md %}

{% remote_include https://raw.githubusercontent.com/cockroachdb/cockroach/v20.2.5/docs/generated/sql/operators.md %}
```

I imagine there's a way to have Jekyll replace `v20.2.5` with the latest patch value from `_config_base.yml`.

**Comment by ianjevans** [comment]
In the examples above I'm pointing at a tag, but the `dev` version of the docs could point to the default branch.
