### ISSUE TITLE
Filter buttons don't have enough top/bottom margin

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/docs#9889]
When the content filter buttons are rendered, there isn't enough margin above and below so the content seems squeezed.

<img width="754" alt="Screen Shot 2021-02-24 at 4 11 19 PM" src="https://user-images.githubusercontent.com/5760366/109083611-164c6780-76bb-11eb-8d5c-9463c3ad6a86.png">
<img width="772" alt="Screen Shot 2021-02-24 at 4 11 28 PM" src="https://user-images.githubusercontent.com/5760366/109083623-1ba9b200-76bb-11eb-9a71-106e3a3ae196.png">

Adding 5-10 px margins above and below the `filters` class should fix this.

**Comment by jseldess** [comment]
@ianjevans, I increase the bottom margin for paragraphs, and this has improved the spacing for filters. Can you please check and let me know if you think they need more space? Personally, I think https://github.com/cockroachdb/docs/issues/9366 is the bigger problem.

**Comment by ianjevans** [comment]
Looks good to me.
