### ISSUE TITLE
SQL Query Errors tooltip is ambiguous

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/docs#9893]
Piyush Singh commented:

@timveil had a question about tooltips for the SQL query errors graph:

> the tooltip says "The number of statements which returned a planning or runtime error." but the docs say " SQL statements that returned a planning, runtime, or retry error".  so first question, does this graph include retry errors?  second question, are these errors that would be returned to a client?

Jordan confirmed that these are only errors that are surfaced to clients, and it includes errors of any kind. 

See full [slack thread](https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1614268682020400) for all context

cc @thtruo and @awoods187 

Jira Issue: DOC-1003

**Comment by vy-ton** [comment]
cc @kevin-v-ngo this would be a product change and is mistakenly a docs issue.

**Comment by thtruo** [comment]
Thanks for the heads up - let's close this docs issue as no-op. 

Heads up @kevin-v-ngo this might be a small ui copy change that your team can take up for the SQL Statement Errors graph tooltip
