### ISSUE TITLE
CC Status Page 

### ISSUE THREAD

**Issue by iibuaka** [cockroachdb/docs#9894]
The CockroachCloud status page displays the current uptime status of the CC Console as well as other related components that affects a large amount of customers (e.g.,a region outage in a cloud provider). The status page also allows customers to subscribe to updates so they can be notified of unavailability. The status page is publicly available to all CC users - paid and free, and will be linked from the marketing website as well as the CC Console UI. 

The status page can be found here: https://cockroachcloud.statuspage.io/ (this page is currently hidden)

Full feature epic can be found here: https://cockroachlabs.atlassian.net/browse/CC-399

**Comment by lnhsingh** [comment]
Closing in favor of CC-3681
