### ISSUE TITLE
Liquibase: xml extra whitespace causing error

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/docs#9895]
I was trying out Liquibase and encountered this error after following the tutorial I linked below.
`Unexpected error running Liquibase: The processing instruction target matching "[xX][mM][lL]" is not allowed.`

https://www.cockroachlabs.com/docs/v21.1/liquibase.html#step-1-download-and-install-liquibase

This is because we have an extra space at the start of the xml definition
```
  <?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd">

    <changeSet id="1" author="max" runInTransaction="false">
        <validCheckSum>ANY</validCheckSum>
        <sqlFile path="create.sql"/>
    </changeSet>

</databaseChangeLog>
```

Removing the extra space at the front should be sufficient to fix this.
![image](https://user-images.githubusercontent.com/25163644/109219981-54fb2400-7786-11eb-8df8-a1f72a7ea75b.png)

**Comment by jseldess** [comment]
cc @ericharmeling, @ianjevans
