### ISSUE TITLE
Docs paragraph margins seem to be 0

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/docs#9896]
Looking at [this page](https://www.cockroachlabs.com/docs/stable/restore.html) as an example, at full width on a 16” Mac, it appears that paragraphs have zero margin, top or bottom. We probably want it to be 1rem or similar.

Looks like the base style is [here](https://github.com/cockroachdb/docs/blob/master/css/customstyles.scss#L56), for a media query of 992px. Thanks.

**Comment by jseldess** [comment]
Thanks, @shermanCRL. This is a known issue: https://github.com/cockroachdb/docs/issues/9849. Hopefully we can fix it soon.
