### ISSUE TITLE
Add clarification regarding VPC endpoints for customers with multiple clusters

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/docs#9919]
Thank you for the great documentation you have put together, it is very helpful and easy to follow. I would like to make a request for a brief clarification and possibly an addition to the docs here: 

https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster#establish-vpc-peering-or-aws-privatelink

We received a request from a customer, with the following question: 

```
we have provided the vpce id for an existing cluster. Would the endpoint service be different for each cluster to set up VPC peering?
```

Would it be possible for us to clarify in the documentation a new VPC endpoint is required for each individual cluster? For example, if a customer has multiple different clusters, can they use the same VPC endpoint? I would assume not, but our docs don't state that, so maybe we could add a clarification, so the customers would be aware.

Is that a correct assumption? A new VPC endpoint needs to be created for each individual cluster a customer would like to connect via VPC peering?

**Comment by lnhsingh** [comment]
Thanks for opening this issue, @daniel-crlabs! I'm going to copy this over to Jira ([CC-3821](https://cockroachlabs.atlassian.net/browse/CC-3821)) and close this GitHub issue.

**Comment by daniel-crlabs** [comment]
That's awesome, thanks :-)
