### ISSUE TITLE
Document that gen_random_uuid() does not do uniqueness checks anymore unless you make it

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#9921]
For context, see below (copied from cockroachdb/cockroach#61132):

> This commit removes uniqueness checks for UUID columns that are set to gen_random_uuid(), because uniqueness can be sufficiently guaranteed by randomness. The probability of collision when using gen_random_uuid() is extremely low. If users still want the checks, however, they can set sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled, a new cluster setting, to true. By default the setting is false.

> Release note (sql change): Added a new cluster setting sql.optimizer.uniqueness_checks_for_gen_random_uuid.enabled, which controls creation of uniqueness checks for UUID columns set to gen_random_uuid().  When enabled, uniqueness checks will be added for the UUID column if it has a unique constraint that cannot be enforced by an index. When disabled, no uniqueness checks are planned for these columns, and uniqueness is assumed due to the near-zero collision probability of gen_random_uuid()

**Comment by jseldess** [comment]
We'll likely end up with a similar release note text once the beta notes are ready.

**Comment by ericharmeling** [comment]
Dup of https://github.com/cockroachdb/docs/issues/10118.
