### ISSUE TITLE
sql: document known limitations around disk spilling for unordered distinct and hash aggregation

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/docs#9922]
Up until and including 20.2 version, we didn't support spilling to disk for unordered distinct and hash aggregation operations. The behavior was that we would buffer all of the relevant data in RAM (thus, possibly exceeding `sql.distsql.temp_storage.workmem` limit) until the query hits the node-wide `--max-sql-memory` limit, at which point it'll error out. Note that it is applicable to both row-by-row and vectorized execution engines. Furthermore, our memory accounting is imprecise (especially in the row-by-row engine), so it is possible that instead of erroring out with a memory limit, the node will crash.

In 21.1 version we merged the full support for disk spilling for hash aggregation and general case support for unordered distinct in the vectorized engine (the row-by-row engine will be deprecated, so we don't invest effort there). The missing support for unordered distinct is when it is used for UPSERT queries and has "nulls are distinct" and "error on duplicate" markers mentioned in EXPLAIN:
```
        ├── distinct                     |                     |
        │    │                           | distinct on         | ...
        │    │                           | nulls are distinct  |
        │    │                           | error on duplicate  |
```
The tracking issue for this case is https://github.com/cockroachdb/cockroach/issues/61411.

**Comment by jseldess** [comment]
Needs to be added to the unresolved list of 20.2 and 20.1 known limitations. Not sure it makes sense to go back further than that.
