### ISSUE TITLE
document Cockroach-specific extension columns in information schema

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/docs#993]
See https://github.com/cockroachdb/cockroach/pull/12801 for past discussion.

Our `information_schema` implementaiton, like most, contains a few Cockroach-specific columns in certain tables. Currently these are:
- `statistics.Storing`
- `statistics.Implicit`

We should document this in the column descriptions.

From @sploiselle:
> It's simple to do by just stating it on the line with the description––something like
> \<column descrtiption\>. *(This column is specific to CockroachDB's information_schema.)*

**Comment by jseldess** [comment]
These columns are already documented: https://www.cockroachlabs.com/docs/v21.2/information-schema.html#statistics
