### ISSUE TITLE
Add docs on restoring multi-region databases

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#9932]
Richard Loveland (rmloveland) commented:

Apparently this is a thing.

Docs will need to describe any caveats/edge cases/etc.

Estimated scope of work:

- Update `BACKUP` with info, maybe
- Update `RESTORE` with info
- See if we need an overview doc of some kind (depends on how much is different)
- ???
- Profit

Related issues:
- [ ] #10084 
- [ ] #10076 
- [ ] #11732
- [x] #10937

Jira Issue: DOC-1009

**Comment by rmloveland** [comment]
@ajstorm are you the right person to come to when I have questions about docs for backup/restore of multi-region DBs?

(don't have anyhing yet, need to research first - just checking)

**Comment by ajstorm** [comment]
Yup.
