### ISSUE TITLE
Migrate from Postgres: Recommend UUIDs over sequences or auto-increment-type primary keys

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9934]
Steven Hand (hand-crdb) commented:

Re: [Migrate from Postgres](https://cockroachlabs.com/docs//v20.2/migrate-from-postgres.html)

## Issue Description

The migration guide from PostgreSQL does not address the issue of sequences or auto-increment-type primary keys in PostgreSQL.  While sequences are extremely common with PostgreSQL, their use in CockroachDB is an anti-pattern.  Naive migrations that stick with the PostgreSQL approach and do not follow Cockroach DB best practices can result in poor performance, for which CockroachDB can be unfairly blamed.

## Suggested Resolution 

Add a description of this issue, and refer people to the existing documentation on preferring UUIDs to sequences.  Existing doc includes:

- Unique ID best practices https://www.cockroachlabs.com/docs/v20.2/performance-best-practices-overview.html#unique-id-best-practices
- Choosing Index Keys for CockroachDB  https://www.cockroachlabs.com/blog/how-to-choose-db-index-keys/
- UUID  https://www.cockroachlabs.com/docs/stable/uuid.html

Jira Issue: DOC-1010

**Comment by jseldess** [comment]
@lnhsingh, @mwang1026 for triage.

**Comment by mwang1026** [comment]
https://github.com/cockroachdb/docs/issues/10439
