### ISSUE TITLE
analysis and guidance doc on caveats around changing GC TTL and incremental backups and change data capture

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/docs#9940]
Steven Hand (hand-crdb) commented:

Re: [DELETE](https://cockroachlabs.com/docs//v20.2/delete.html)

## Issue Description

There is a lack of clarity on how changing garbage collection time-to-live (GC TTL) impacts incremental backups and change data capture.

Similarly, there is tight coupling between GC TTL and change data capture (CDC).  While there may not be as much of a lack of clarity on the effect of changing GC TTL on CDC, because there is not a more global-scope analysis in docs, DBAs with responsibilities in one area may inadvertently cause adverse impacts to a different area.

## Suggested Resolution 

Anything that can adversely affect backups needs clear analysis and guidance doc.  After all, customers depend upon backups, often for regulatory compliance.  They like to be able to set set up backups and not have to deal with it much afterwards.  And backup admins are sometimes not the same people as DB admins or developers, especially when backups are encrypted or segregated by geo.

This analysis and guidance doc should also address CDC, because CDC is also affected by GC TTL.  So a more global analysis and guidance doc on GC TTL and its effects on related systems in CockroachDB would be helpful.
  

Jira Issue: DOC-1012

**Comment by jseldess** [comment]
@lnhsingh and @mwang1026 for triage.

**Comment by hand-crdb** [comment]
I updated the title and description to include change data capture (CDC) in addition to incremental backups.  Perhaps there are additional systems in CockroachDB that are affected by GC TTL settings, and, if so, they should also be in scope.

**Comment by mwang1026** [comment]
Makes sense Thanks Steven
