### ISSUE TITLE
Add clarification for cockroach cloud single-node to multi-node cluster upgrade support (lack of)

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/docs#9945]
Hello folks, a customer is attempting to add additional nodes (upgrade from 1 node to multi-node) in cockroach cloud and receives the following message:

```
at this time we do not support adding nodes to a single-node cluster
```

![cc-error](https://user-images.githubusercontent.com/78774369/110381808-feb09f80-8027-11eb-80b1-27687742ab0a.png)

I have reached out to #cc-general and have found this is not a supported feature, however, this is not clearly documented and the customer only finds out after the fact.  
Would it be possible to have some sort of explicit message for the customers, whenever they choose a single-node cluster, stating **they will not be able to upgrade from a single-node to a multi-node cluster**?

I assume the only way here would be to dump the data or use an existing backup, then create a new multi-node cluster and then import the data, then delete the single-node instance. 

Could we also add this to the documentation found here: 

https://www.cockroachlabs.com/docs/cockroachcloud/frequently-asked-questions.html

**Comment by lnhsingh** [comment]
Thanks for filing @daniel-crlabs. Copied this to [Jira](https://cockroachlabs.atlassian.net/browse/CC-3821) so we can add something to the CC FAQs page. Closing this GitHub issue.

cc @rsadres @kannanlakshmi - FYI, in case you want to prioritize this fix in the UI.
