### ISSUE TITLE
release-20.2: sql: add parse_timestamp builtin

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9950]
PR: https://github.com/cockroachdb/cockroach/pull/60814

From release notes:
> A new `parse_timestamp` [function](../v20.2/functions-and-operators.html) can now be used to parse absolute timestamp strings in [computed column](../v20.2/computed-columns.html) expressions or [partial index](../v20.2/partial-indexes.html) predicates. [#60814][#60814] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@ianjevans, @ericharmeling, now that we are automatically including functions docs from the source, there might not be anything to do here. Routing to you just in case.

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/docs/pull/9907.
