### ISSUE TITLE
release-20.2: kv: allow manual GC that does not advance threshold

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9956]
PR: https://github.com/cockroachdb/cockroach/pull/60745

From release notes:
> Manually enqueueing a range in the [GC queue](../v20.2/architecture/storage-layer.html#garbage-collection) now properly respects the `SkipShouldQueue` option. This can be useful to force the GC of a specific range. [#60745][#60745] {% comment %}doc{% endcomment %}

**Comment by nvanbenschoten** [comment]
I do not think this needs documentation. It was primarily added as a mechanism for CRDB engineers to use during support escalations.

**Comment by jseldess** [comment]
Thanks, @nvanbenschoten!
