### ISSUE TITLE
Update decommissioning process info

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/docs#9968]
Erik Grinaker (erikgrinaker) commented:

Node decommissioning has seen some changes recently, e.g. in cockroachdb/cockroach#56529, that should be reflected in the 21.1 documentation:

https://www.cockroachlabs.com/docs/dev/remove-nodes.html

A node's status entry is now removed when the decommissioning operation completes (unless something goes wrong, in which case the operation can be run again). This means that the node will not show up under "Recently Decommissioned Nodes", since there is no longer an entry to show there. This needs to be updated a few places in the document (just search for "recently decommissioned"). I suppose the mentioned "historical list of decommissioned nodes" no longer applies either.

We may want to make some changes to DB Console following this as well.

Jira Issue: DOC-1022

**Comment by taroface** [comment]
cc @thtruo on the need to update DB Console

**Comment by erikgrinaker** [comment]
Thanks! I opened cockroachdb/cockroach#61812 for the Console DB work, but see that the backlink here didn't work since I moved the issue from the `cockroach` repo.

**Comment by erikgrinaker** [comment]
Hey @taroface, can we get this updated please? The docs are currently incorrrect.
