### ISSUE TITLE
SEO Issue: meta descriptions too short

### ISSUE THREAD

**Issue by dankellycockroach** [cockroachdb/docs#9978]
Dan Kelly (dankellycockroach) commented:

Recently the docs team fixed an issue in order to populate every docs page with a unique meta description (thank you @jseldess). Which was really great. 

But now we have an issue with some of those descriptions being too short. Here is a report: https://docs.google.com/spreadsheets/d/1r39xR3J35v9Vc01FuOLq2gLnFFaGa5PgnTsQyX8nMNc/edit?usp=sharing

Is it possible to require that each docs description be between 50–160 characters?  

Context: this work is part of a larger SEO project to optimize the whole site. With the goal being to double our site traffic. 

Jira Issue: DOC-1653

**Comment by jseldess** [comment]
@dankellycockroach, just created an issue to check for the presence and length of meta descriptions: https://github.com/cockroachdb/docs/issues/10183. Can we close this in favor of that? Once that's in place, all the short descriptions should be caught and then fixed.
