### ISSUE TITLE
Update QuickStart with instructions for Windows users

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/docs#9980]
Feedback from the cmd-f hackathon participants: The [this step of the QuickStart guide](https://www.cockroachlabs.com/docs/cockroachcloud/quickstart-trial-cluster.html?filters=linux#step-5-run-your-first-query) doesn't have instructions for Windows users. Since many hackathon participants use Windows, it might be helpful to include Windows-specific instructions here.

**Comment by lnhsingh** [comment]
Closing this issue - this is covered by CC-3895, which will be addressed by https://github.com/cockroachdb/docs/pull/10427
