### ISSUE TITLE
Cockroach University Robots issue

### ISSUE THREAD

**Issue by jeffreyroach** [cockroachdb/docs#9984]
In Cockroach University Admin (LearnDot) replace the file named robot.txt to be this new txt file (attached) but with the URL at /robots.txt

Search crawlers only search for Robots.txt files under .com/robots.txt but the current file there is an HTML page that has nothing to do with Robots. The correct placement for the attached file should live under:
https://university.cockroachlabs.com/robots.txt

[robots.txt](https://github.com/cockroachdb/docs/files/6132183/robots.txt)

**Comment by jseldess** [comment]
I think this was handled by the Training team. @jeffreyroach, @dweatherbee, if not, please create a Jira issue for this.
