### ISSUE TITLE
Create a CockroachCloud Cluster Doc Update 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#9989]
Re: [Create a CockroachCloud Cluster](https://cockroachlabs.com/docs/cockroachcloud/create-your-cluster.html)

## Issue Description
update this doc with iops per cloud provider

## Suggested Resolution 
adding IOPs to the page would make a welcome addition.

**Comment by lnhsingh** [comment]
Closing - dupe of CC-3698
