### ISSUE TITLE
301 redirect for tech talks page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#999]
We/DivisionOf moved the tech talks page from `https://www.cockroachlabs.com/docs/tech-talks.html/` to `https://www.cockroachlabs.com/community/tech-talks/`. So we need a 301 redirect from the old address to the new.

cc: @eballeste

**Comment by mberhault** [comment]
this is done. wordpress redirect plugins didn't do anything, probably because this is served directly by apache.
Had to modify `.htaccess` instead. bleh!
