### ISSUE TITLE
Add note to docs that Helm Chart is not supported past Kubernetes v1.17

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/docs#9991]
With the Kubernetes API deprecating Kubernetes Certificate Authority’s ability to issue application certificates beyond Kubernetes v1.17. 

As a result, we should update our docs to make it clear that it's unsafe to run the Helm Chart beyond Kubernetes v1.17.

@keith-mcclellan , can you confirm that this is the correct guidance? We're running into the risk for multiple customers using the Helm Chart in an unsupported way.

In the CRDB Kubernetes docs, it may make sense to include a callout in [Step 2: Start CockroachDB Section](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html?filters=helm#step-2-start-cockroachdb).

**Comment by keith-mcclellan** [comment]
I am not sure this is the correct guidance, this would be a hard deprecation without an off-ramp.  We need to either document a way to migrate off the helm chart to another install pattern (currently, that would be the static config install pattern), or we need to update the helm chart so it can be supported until the Operator is ready to take over those clusters.

**Comment by taroface** [comment]
@keith-mcclellan Will it be a lot of work to update the Helm chart to support custom CA? My first thought is that this seems easier than researching & creating docs for migrating off of Helm.

**Comment by keith-mcclellan** [comment]
We would need to do an analysis to make that determination, but my gut says we need to fix the helm chart instead. 30% of our installs are using the helm chart and we don't currently have a migration strategy to get them off of it.  @johnrk @piyush-singh

**Comment by piyush-singh** [comment]
We're having a conversation over slack to go over our options. We will summarize options and share with a wider audience (will include Keith and Ryan). We'll update here once we have a clear path forward.

**Comment by taroface** [comment]
Resolved by https://github.com/cockroachdb/docs/pull/10271.
