### ISSUE TITLE
VECTORIZE session setting docs shows illegal option 'auto'

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/docs#9996]
The [20.2 set-vars docs](https://www.cockroachlabs.com/docs/stable/set-vars.html) incorrectly show `auto` as an option for the `vectorize` session setting. This is not allowed:

```
defaultdb> SET VECTORIZE=auto;
ERROR: invalid value for parameter "vectorize": "auto"
SQLSTATE: 22023
HINT: Available values: off,201auto,on,experimental_always
```

I attempted putting up a PR to fix this, but looks like `_includes/v20.2/misc/session-vars.html` is auto-generated, and I'm unsure how.

**Comment by jseldess** [comment]
This page isn't auto-generated from cockroach code, although it should be. Instead, it's just included from elsewhere in the docs repo. 

@rmloveland, is that right? The include isn't auto-generated is it? I think you created it in the current html format. How did you go about that?

**Comment by ericharmeling** [comment]
I've been updating `_includes/v*/misc/session-vars.html` manually each release.

IIUC, only the cluster settings are automated by docgen, as [`settings.html`](https://github.com/cockroachdb/cockroach/blob/master/docs/generated/settings/settings.html). But it would be *awesome* if we could get session variables docs automated as well.

**Comment by ericharmeling** [comment]
Should be fixed by https://github.com/cockroachdb/docs/pull/10159. Thanks for filing this issue, @mgartner !

**Comment by rmloveland** [comment]
> @rmloveland, is that right? The include isn't auto-generated is it? I think you created it in the current html format. How did you go about that?

I'm sorry to say I don't entirely remember, but here is my hallucination: I think this was like 2+ years ago, and we had a big hand-maintained markdown table for these vars.  What I remember is that I could not seem to update the table without breaking the HTML rendering, so I rewrote it as HTML.

Totes agreed it would be great to autogenerate this now.  Especially with the var renaming that happens
